### ISSUE TITLE
Unable to install Keras to Anaconda3

### ISSUE THREAD

**Issue by i5han** [fchollet/keras#101]
Installation fails while trying to install h5py even though anaconda comes bundled with h5py. Removing the install_requires=['theano', 'h5py'], from the setup.py file allows keras to install. (i have theano installed as well)

Python: 3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit (AMD64)] on win32

OS: Windows 7 x64

**Comment by suixudongi8** [comment]
Dude, Why do not you use WinPython? It works well.
Haha~

**Comment by i5han** [comment]
I belive that keras should work for anaconda as well. Although i cant provide any hard numbers i think thats also a significant amount of users. Asking those users to switch to winpython just use Keras is not the most user friendly solution and it also acts as a hinderence to spreading Keras :)

**Comment by fchollet** [comment]
Agreed that Keras should work with Anaconda. But in this case it sounds
like an Anaconda issue, not a Keras issue. Keras *does* require h5py, so
that line belongs there.

**Comment by zhaoyy89** [comment]
maybe try pip install

**Comment by zhaoyy89** [comment]
try pip install

**Comment by zhaoyy89** [comment]
try pip install
