### ISSUE TITLE
What are the differences between test_on_batch()'s callback and evaluate()'s ?

### ISSUE THREAD

**Issue by meanmee** [fchollet/keras#1011]
Is that test_on_batch()'s callback means the accuracy and loss just on one batch of the test dataset, and evaluate()'s callback means the accuracy and loss over the all test dataset?
for example; my test dataset's size is 1000, if I set the batch size to 200, the test_on_batch returns the  accuracy and loss of the recent 200 samples from the test dataset. And If I use evaluate(), also set batch size to 200, but I got the accuracy and loss over the all test dataset(1000 samples). 
Am I right?
thanks for releasing  this project.

**Comment by fchollet** [comment]
Yes.
