### ISSUE TITLE
Switch to a modular backend for Theano and TensorFlow support

### ISSUE THREAD

**Issue by fchollet** [fchollet/keras#1014]
Here's the `backend` branch, introducing `theano_backend.py` and `tensorflow_backend.py`: https://github.com/fchollet/keras/tree/backend/keras/backend

It's still a work in progress. It contains 95% of the Theano functionality used in Keras, implemented both in Theano and in TensorFlow, and accessible through a same API. 

The general usage in Keras would be as follow (just a trivial example):

``` python
from keras import backend as K

x = K.variable(np.random.random((3, 4)))
y = K.placeholder(ndim=2)
z = K.exp(x) + y
f = K.function(inputs=[y], outputs=[z], updates=[(x, x * 2)])
```
### What isn't implemented:
- `rnn`, the equivalent of Theano's `scan`.
- the remaining 5%: as far as I can tell, `shape_padright`, `tensordot`, and `batched_tensordot`, the broadcasting business... we might deal with it by eliminating these from the Keras codebase.
### Known issues

`conv2d` and `maxpool2d` work separately in TF and Theano, but output different values. It is unclear yet why. Not a big issue unless we want trained models to be portable from one backend to another (which I would prefer, of course).
### What's next
- adding Theano and TF implementations for `rnn`
- figuring out the `conv2d` and `maxpool2d` issue
- rewriting Keras to use the backend (`K`) instead of Theano. In 95% of cases this would be a trivial search-and-replace. The remaining 5% might require extending the backend a little bit, or reimplementing old Theano functionality with existing backend primitives.

If you have cycles to spare, please consider helping out with the rewriting of Keras. It is simple and quite impactful.

**Comment by farizrahman4u** [comment]
>the remaining 5%: as far as I can tell, shape_padright, tensordot, and batched_tensordot, the broadcasting business... we might deal with it by eliminating these from the Keras codebase.

Didnt get this part. What do you mean by eliminating? You mean like rewrite tensordot using K.dot?

**Comment by rushter** [comment]
I will work on objectives module.

**Comment by rushter** [comment]
Is there any reason why lower bound for `sqrt` is epsilon?  Both backends can handle 0.

**Comment by hugman** [comment]
Awesome! Thank you for updating.
I'll find what can I contribute.

By the way, I agree with eliminating broadcasting things. Broadcasting is convenient, but very bad in readibility.

**Comment by dbonadiman** [comment]
That's a great deal!

**Comment by fchollet** [comment]
> What do you mean by eliminating? You mean like rewrite tensordot using K.dot?

Yes.

**Comment by dbonadiman** [comment]
@fchollet @fchollet Theano already did that they switched from a "fancy" tensor dot implementation to the simple dot here is the function that does the trick.

https://github.com/Theano/Theano/blob/33c976054771cbf43c3f9cf01463eca840072f43/theano/tensor/basic.py#L5507

**Comment by EderSantana** [comment]
@fchollet for problems with convolutions did you check if they do correlation like theano does? At least this was a difference between Theano and Caffe conv.

**Comment by fchollet** [comment]
@EderSantana possible, but that wouldn't explain the maxpooling issue. I suspect the issue is with the shape format used. But really, I don't know.

**Comment by fchollet** [comment]
I hope we can release the dual-backend version within the same timeline as Python3 support in TensorFlow, probably about 2 weeks. 

Main hurdles are `scan`/`rnn` and understanding the conv2d / maxpooling2d discrepancy.

**Comment by EderSantana** [comment]
For a unifying API, I believe we will have to write a "scan" for TensorFlow. Basically TF handles for loops with regular python `for`. So, we just have to create a function around it with the same API as scan. I started a little example here:
https://github.com/EderSantana/TwistedFate/blob/master/Fibonacci.ipynb

But, this doesn't mean we cannot use the optimized RNNCells that already comes with TF. For example, when using Theano, we have our own LSTM code, but when using TF, we just switch to models.rnn_cell.LSTMCell.

What do you think?

**Comment by fchollet** [comment]
> What do you think?

Cool stuff! Would you see RNN cells as part of the backend? (full implementations in Theano and thin wrappers in TF).

By the way, if we are going to reimplement scan in TF, why not try to improve its API? I know lots of people are not fond of the `scan` API. If we can figure out something better that will work with both backends, why not...

**Comment by EderSantana** [comment]
> (full implementations in Theano and thin wrappers in TF).


I think it can be done. TF's `step` functions are implemented as RNNCells on `tensorflow.models.rnn_cell`. Their `scan` is on `tensorflow.models.rnn` which is just a for loop. When using the TF backend and regular models (LSTMs and GRUs) we could just use their code. The problem would be importing from one backend to another. In that sense, having everything "made in Keras" would be nicer.


> By the way, if we are going to reimplement scan in TF, why not try to improve its API?

Well remembered! I was thinking like "Theano scan is set on stone, but TF is flexible, so..." . But that is not true. There is that work started on Lasagne to unroll scan. Theano scan is defined here (in 1119 lines of code, counting docs):
https://github.com/Theano/Theano/blob/master/theano/scan_module/scan.py

Meanwhile, unroll_scan is just 70 lines:
https://github.com/Lasagne/Lasagne/blob/80b61cb1bda4d2a3eca1a8b97f0ccfc4ed8205b4/lasagne/utils.py#L340-L411

Maybe we should use the second as reference and come up with an API in the Keras way of doing things. +1 if it could be one code for both Theano and TF. 

So, what would be the wish list for this new way of doing loops?

**Comment by fchollet** [comment]
A few thoughts:
- a more elegant API than `scan` is possible. So far I've been finding the TF approach to RNNs more intuitive.
- it would great to be able to define a recurrent layer in Keras by simply specifying the step function and the states. This API change is an opportunity to achieve that.
- RNNs have been a key use case of Keras so far. Keras should establish itself as the best solution for RNNs going forward, in particular it should be superior to vanilla TensorFlow.

I'm nearly done with the dual-backend conversion for everything except RNNs (I'll finish it up this week-end). Would you like to look together in detail at how to design the best dual-backend API for RNNs?

**Comment by dbonadiman** [comment]
In general i would agree, Api level the Tensorflow approach is more
intuitive. Another things to address from my point of view is the problem
of training RNN on GPU the current theano scan is inefficient as hell when
training on GPU. The possibility to unfold the recursion should be a must
have in this scenario.

Unfold discussion apart the mayor limitation of using Theano scan to
achieve that is the fact that we need to make simpler the use of layers as
function so that it is possible to pass directly a container into the scan,
and in particular we need to separate all the sequential and not sequential
parameters  since they  needs to be directly specified in the scan. Am i
right? or am i missing something?

*Daniele Bonadiman*

**Comment by EderSantana** [comment]
> the fact that we need to make simpler the use of layers as
> function so that it is possible to pass directly a container into the scan

I ran into that problem with the Neural Turing Machine implementation. It was hard to model reuse. But this is something Keras could get from TF, to have layers with a __call__ method. Right now we only have `get_output` which forces us to define a `previous_layer` or to set `input` to be able to use it.

**Comment by jeffzhengye** [comment]
I discussed with @dbonadiman about the possible bugs in RNNs, especially the bidirectional RNNs. 
@dbonadiman referred to state the problem here since you guys are trying to re-implement the scan function. 

1. for the bidriectional rnn, I suspect it's having problem, when we set return_sequences==False. 
Say we do left padding (e.g input=[0, 0, 0, 3, 5], 0 indicates mask in embedding), it's fine to scan from left to right. However, when you reverse (scan from right to left) (then input=[5, 3, 0, 0, 0]), the output we get from with return_sequences==False is the hidden state of '0', instead of '3', which is wrong to me. @fchollet How do you thing? Is it a bug?

2. if that's the case, then we will have problems when we do right-padding.

3. BTW, since you mentioned seya in this, seya's implementation also seems buggy to me since they do Xb = Xb[::-1]. They reverse the first dimension, which is unfortunately the batch size dimension.

**Comment by fchollet** [comment]
What about a `Recurrent` meta-layer that can be used to instantiate new RNN layers:
```python
def step_function(input, states):
   # blah blah
   return output, new_states

VLSTM = Recurrent(step=step_function, initial_states)
# standardized arguments across RNN layers
model.append(VLSTM(128, return_sequences=True, ...) 
```

This would really be a thin wrapper around a `rnn` function in the backends.

- easy instantiation of new RNN types
- no redundancy in `recurrent.py`
- no more `scan` (it's hidden in the Theano backend)
- more standardization
- easy to setup statefulness: just store the states internally in the layer and reload them if `stateful=True`

**Comment by fchollet** [comment]
> But this is something Keras could get from TF, to have layers with a __call__ method. Right now we only have get_output which forces us to define a previous_layer or to set input to be able to use a layer or model as a function inside another model/layer. 

It is unclear how this is necessary in Keras. Keras is OO and wouldn't really benefit from more pseudo-functional sugar... if you want to run a layer on a specific input outside of a model (which is almost never necessary unless you are writing unit tests), you can add one line and do:

```python
layer.input = K.variable(some_numpy_array)
result = layer.get_output()
```

**Comment by EderSantana** [comment]
> It is unclear how this is necessary in Keras.

Here is an example: A Spatial Transformer Network has a localization module that can be any DNN with 6 outputs. Does, it is natural to pass a Sequential model (here locnet) as a parameter to a STN. The STN is a layer itself. The input of that locnet should be same as the input of the STN itself. In that case we cannot just say inside the STN:
```python
X = self.get_input()
Y = self.locanet.get_output(X)
```

We have to:
```python 
X = self.get_input()
self.model.layers[0].input = X # This line is not the most intuitive
Y = self.model.get_output() 
```

Obviously, this is not super necessary or a biggy, it's just one extra line (although an unclear one). In seya, I just created a utility function called `apply_model`:
```python
X = self.get_input()
Y = apply_model(self.locnet, X)
```

I could bring it here if others find it useful.

**Comment by EderSantana** [comment]
The real problem is, how will our for-loops look like? xD
Anybody has an API idea?

**Comment by fchollet** [comment]
A proposal for the backend API:

```python
def rnn(step_function, inputs, initial_states, go_backwards=False):
    '''Iterates over the time dimension of a tensor.

    Parameters
    ----------
    inputs: tensor of temporal data of shape (samples, time, ...)
        (at least 3D).
    step_function:
        Parameters:
            input: tensor with shape (samples, ...) (no time dimension),
                representing input for the batch of samples at a certain
                time step.
            states: list of tensors.
        Returns:
            output: tensor with shape (samples, ...) (no time dimension),
            new_states: list of tensors, same length and shapes
                as 'states'.
    initial_states: tensor with shape (samples, ...) (at least 2D),
        containing the initial values for the states used in
        the step function.
    go_backwards: boolean. If True, do the iteration over
        the time dimension in reverse order.

    Returns
    -------
    A tuple (outputs, new_states).
        outputs: tensor with shape (samples, time, ...) where each
            entry outputs[s, t] is the output of the step function
            at time t for sample s.
        new_states: list of tensors, updated states used by
            the step function.
    '''
    pass
```

This would be used in `recurrent.py` to create the `Recurrent` layer, from which all other RNN layers would descend:

```python
LSTM = Recurrent(step=step_function, initial_states)
# standardized arguments across RNN layers
model.append(LSTM(128, return_sequences=True, ...) 
```

**Comment by EderSantana** [comment]
That is what I'm talking about!

Question, will `inputs` be always a single or tensor or can it be a list? Here are the advantages of each one:
* Single tensor: Faster, if we do all the operations at once, this will be much faster. (TensorFlow syle)
* List: Easier to read, understand and debug. (Theano style)

Also, for Theano backend `non_sequences` can be inferred, `_step` can get an *args in its definition and we just use `self.parameter_name` inside that function. No need to clutter `_step` definitions. This is what is done in the `NeuralTuringMachine` class, see `_step` definition in there.

**Comment by fchollet** [comment]
I'd advocate for making it a single tensor, but then this raises the question of how to handle masking. In our currently implementation we are passing around two "inputs": the actual input tensor, and the mask. 

Would it be done via a specific value in the input tensor?

**Comment by fchollet** [comment]
Actually, instead of 
```python
LSTM = Recurrent(step=step_function, initial_states)
```

We should probably go for inheritance:
```python
class LSTM(Recurrent):
   def step(self, ...):
      ...
```

**Comment by EderSantana** [comment]
There some better solutions than passing the mask as part of the input:

* mask as a global (non_sequences in Theano).
Since we will be using for-loops, we get the current mask simply as `mask = complete_mask[:, i]`

* Conditional calculatation:
Using `if_else` or the TF equivalent, we do something like `if x.sum() != 0: mask = 1, else mask = 0`.

Still, passing mask as part of the input is only necessary for Theano backend (in case we use regular `scan`), but doable for sure.

**Comment by fchollet** [comment]
Right. We could simply propose a rule, that any custom RNN that supports masking should follow: if `not K.any(inputs[s, t, :])`, then output back the input and states unchanged (i.e. treat the step as non-existent).

**Comment by EderSantana** [comment]
Yeah, to be even safer maybe:
```python 
def rnn(step_function, inputs, initial_states, go_backwards=False, masking=False):
```

So `rnn` knows if it will have to care about masking at all. Or is that too much?

**Comment by fchollet** [comment]
I think that's reasonable. Just in case there are valid all-zero inputs I guess?

**Comment by EderSantana** [comment]
that is what I thought...

**Comment by fchollet** [comment]
So I think we are looking for something like this on the Theano side...

```python
def rnn(step_function, inputs, initial_states,
        go_backwards=False, masking=True):
    '''Iterates over the time dimension of a tensor.

    Parameters
    ----------
    inputs: tensor of temporal data of shape (samples, time, ...)
        (at least 3D).
    step_function:
        Parameters:
            input: tensor with shape (samples, ...) (no time dimension),
                representing input for the batch of samples at a certain
                time step.
            states: list of tensors.
        Returns:
            output: tensor with shape (samples, ...) (no time dimension),
            new_states: list of tensors, same length and shapes
                as 'states'.
    initial_states: tensor with shape (samples, ...) (at least 2D),
        containing the initial values for the states used in
        the step function.
    go_backwards: boolean. If True, do the iteration over
        the time dimension in reverse order.
    masking: boolean. If true, any input timestep inputs[s, i]
        that is all-zeros will be skipped (states will be passed to
        the next step unchanged) and the corresponding output will
        be all zeros.

    Returns
    -------
    A tuple (outputs, new_states).
        outputs: tensor with shape (samples, time, ...) where each
            entry outputs[s, t] is the output of the step function
            at time t for sample s.
        new_states: list of tensors, updated states used by
            the step function.
    '''
    inputs = inputs.dimshuffle((1, 0, 2))
    initial_states = [s.dimshuffle((1, 0, 2)) for s in initial_states]

    def _step(*args):
        assert len(args) >= 2
        input = args[0]
        states = args[1:]
        if masking and not T.any(input):
            # if all-zero input timestep, return
            # all-zero output and unchanged states
            return [T.zeros_like(states[0])] + states[1:]
        output, states = step_function(input, states)
        results = [output] + states
        return results

    results, _ = theano.scan(
        _step,
        sequences=inputs,
        outputs_info=initial_states,
        go_backwards=go_backwards)

    outputs = results[0]
    states = results[1:]
    outputs = outputs.dimshuffle((1, 0, 2))
    states = [s.dimshuffle((1, 0, 2)) for s in states]
    return outputs, states
```

This may well be mistaken, particularly the handling of masking. I'm still thinking about it. If you see anything fishy, please let me know.

**Comment by EderSantana** [comment]
Maybe you mixing Theano's with TF's API... For example, why are you slicing inputs and initial_states? This is what we do in TF. Also, shouldn't it be:
```python
initial_states = [s for s in initial_states.dimshuffle((1, 0, 2))]  # TensorFlow would use this, but Theano does it automatically inside scan
```

I'm not sure the `if` will work in Theano or TF. We should use their conditional operations like:
```python
def _step(*args):
    assert len(args) >= 2
    input = args[0]
    states = args[1:]
    output, new_states = step_function(input, states)
    results = T.concat([output, new_states], axis=-1)
    if masking: # This can be python, its global
        results = T.switch(T.any(input), results, 0*results) # I would prefer passing the old output and old state again, instead of zeros
    else:
        return results
```

**Comment by fchollet** [comment]
> Also, shouldn't it be:

The base idea here is that `initial_states` is not a tensor, it's a list of tensor. We can have multiple states.

So this is not tensor slicing, this is just Python list manipulation.

> I'm not sure the if will work in Theano or TF.

It would in TF. You're right that it most likely wouldn't work in Theano, we should use `switch` instead.

**Comment by fchollet** [comment]
I suggest we get rid of `SimpleDeepRNN` because it is a rather useless layer. Bloat does not help Keras move forward. 

Any objections?

**Comment by fchollet** [comment]
The main obstacle I see with a `Recurrent` layer that could be quickly adapted into different RNNs, is weight management. Supplying a step function is not sufficient, we also need shared weight tensors, output shapes, etc.

It is possible to abstract quite a bit into a `Recurrent` layer, but certainly not everything. At the very least we would need to specify:
```python
class LSTM(Recurrent):
   def __init__(self, ...):
      ...
   def build(self, ...):
      ...
   def step(self, ...):
      ...
   def get_config(self, ...):
      ...
```

**Comment by fchollet** [comment]
The highly-redundant JSZs have certainly become quite terse all of a sudden.

```python
class JSZ1(JZS):

    def step(self, x, states):
        assert len(states) == 1
        h_tm1 = states[0]

        x_z = K.dot(x, self.W_z) + self.b_z
        x_r = K.dot(x, self.P) + self.b_r
        x_h = K.dot(x, self.W_h) + self.b_h

        z = self.inner_activation(x_z)
        r = self.inner_activation(x_r + K.dot(h_tm1, self.U_r))
        hh = self.activation(x_h + K.dot(r * h_tm1, self.U_h))
        h = hh * z + h_tm1 * (1. - z)
        return h, [h]

# yep, that's it.
```

**Comment by fchollet** [comment]
It's unclear to me that we should keep the recurrent layers `JZS1, 2, 3`. They are useless and incredibly redundant.

**Comment by fchollet** [comment]
I'm happy to say that our RNNs now work both with Theano and TensorFlow seamlessly. 

However: in the TF case, it only works if the number of timesteps is specified. That is due to a hard limitation of TensorFlow at the moment. 

Similarly there are a number of other features of Keras that will not work due to TF limitations. But all these limitations are temporary: these are known TF issues that people are working to fix. In the near future, these limitations will be lifted and Keras will take advantage of it.

Mostly notably:
- lack of float/int -> bool casting => masking will not work
- lack of tensor contraction => dot mode in merge will not work
- various limitations in the conv2d API (no support for inequal strides, etc)
- no support for dynamic-timesteps RNNs

**Comment by EderSantana** [comment]
* No objections against taking SimpleDeepDNN out. If it is an example, it should be in "examples instead". Same for JSZ, they can be in a separate `rnn_examples` folder or something like that.

I hope we are not downgrading our capabilities to support TF though. They are the ones who have to catch up. But for sure, the effort to support TF in here will give a lot of feedback for them to improve.

I'll give the code another spin. Is there any open problem you want me to check out? When do you plan to release it into the main branch?

**Comment by fchollet** [comment]
> I hope we are not downgrading our capabilities to support TF though.

We are not. But quite a few features won't be available when using the TF backend, at least for the first few weeks. Also, the switch to a modular backend has led me to change the Keras API in some ways (including remove some things). We were often following the Theano API in ways that were not optimal, and this was an occasion to take a step back and reflect.

> Is there any open problem you want me to check out?

The only remaining problem is figuring out why there is an output discrepancy between TF and Theano for conv2d and maxpooling. It has eluded me so far. There are two commented-out tests in `test_backends.py` related to this.

> When do you plan to release it into the main branch?

Probably sometime during next week. What's left is mostly UX polishing (informative error messages, etc) and doc updates.

**Comment by fchollet** [comment]
It's obvious that we have a dire need for better documentation and better failure UX in the codebase (assumption checking and helpful error messages). This is the right way to scale user support. I have stopped checking the issues section a while ago.

**Comment by EderSantana** [comment]
I usually go to issues section and answer questions and others started to do the same as well. Questions started to repeat themselves: no nnet.relu, can we have RBMs, how to save weights, my data doesn't fit on memory, etc. You didn't miss much. 

What you could do is by the time you decide to push the new backend, freeze all PRs so that the new backend can catch up. We could ask all contributors to wait for the new backend or work on new backend adaptation instead. When I was helping with Blocks, there was a time Bart did that right before releasing 0.1. He stopped accepting all PRs that were not polishing what we already had.
Let's say, the new backend is Keras 0.3 so we will only accept PRs that contribute with 0.3 objectives.

What do you think?

**Comment by fchollet** [comment]
Right. This is definitely the right way to proceed.

**Comment by EderSantana** [comment]
btw, masking for TF could be handled by passing the mask by hand. In other words, the mask could be a model property shared variable. Before the batch begins, Keras get the data, calculate the mask and set the mask property. Inside each class that is supposed to use the mask, just refer to that shared variable. That would also free theano from calculating and compiling yet one more thing. Cons: moving the mask data to GPU

**Comment by EderSantana** [comment]
Did you push the rnn backend to the `backend` branch already?

**Comment by fchollet** [comment]
Jut pushed now. I believe there is no need to think of workarounds, because the issue is really tiny (lack of float->bool casting) and will be fixed in the next TF release. The best way to deal with it is to wait a little bit.

**Comment by EderSantana** [comment]
I'm cool with that!

**Comment by EderSantana** [comment]
Btw, I liked the way you abstracted the `get_output` out of the RNNs. Also TimeDistributed shows an example of how to use `rnn` without that abstraction. 

I just have a little question about the choice of masked outputs, they are fixed to zero. This still forces padding to be always on the left. If we could find a way to repeat the previous output, just like we repeat the previous state, padding location could be anywhere. Pad invariant outputs are a possible way to solve the bidirectional RNNs problem.

**Comment by fchollet** [comment]
I believe what is done now (passing the states unchanged if an input is 0) allows for direction-independent padding. Can you expand on that?

I'm currently in the process of merging `master` into `backend`.  This is making me realize that there is a lot of shitty / buggy code that has ended up in master, which demonstrates that the current PR review process (i.e. me vaguely looking at the Github interface) is completely broken.

How can we scale Keras development, and improve the review process?

**Comment by fchollet** [comment]
Executive decision: all development effort after 0.3 (TF backend) will be focused on improving code quality, adding docstrings, improving the documentation, improving the unit tests, improving the PR submission and review process. Until these things are fixed.

**Comment by fchollet** [comment]
How should the choice of the backend be handled by the user? 

Currently you have to change a string in `backend/__init__.py` then reinstall. Obvious that's not optimal. 

Possibilities:
- a command-line flag, Theano-style. Unclear how that would be implemented.
- a line in `.kerasrc`. That would be easy to implement.
- other suggestions?

**Comment by EderSantana** [comment]
> How can we scale Keras development, and improve the review process?

I'm readying and reviewing PRs and Issues as much as I can too. But it is really hard to do more than that without counting with contributors good sense. There are few things that might help, for example coverage is a good metric, see: https://coveralls.io there are other options too (it's like travis to measure how much of the library is tested).
Good libraries usually gets its coverage around 90%. Whenever somebody makes a PR that reduces the coverage too much we can call on them.

We may sound a little bit too arrogant in the beginning by asking people to comply to metrics while they are trying to help us. But this is actually useful for everybody and I believe that with the right words, everybody can understand. For example, a PR must be easy for a human to ready, if they come without a good description and we have to read the code to see what the person is proposing, this might also be not really helpful. But I believe that creating rules such as:
* Create an issue before making a PR, so the community can discuss suggestions and discuss API (this is usually done without a lot of visibility inside the PR). Unless fixing typo or any other super obvious thing.
* The issue discussion will check, for example, if contribution shouldn't be maintained in user's own github and listed in the Wiki instead. I have several examples of those (DRAW, Spatial Transformer Net, etc). And reduces the burden on you to fix errors after pushed.
* PR will be reviewed after passing tests.
* PR must not drop coverage too much if at all.
* Any new layer, class, function will only be accepted with docs
* PRs that contribute to Keras listed priorities will be reviewed first.
* Current priorities should be listed on the wiki for quick access (better than navigate past issues)

**Comment by EderSantana** [comment]
> Currently you have to change a string in backend/__init__.py then reinstall. Obvious that's not optimal.

I'd personally prefer a way that could be changed programatically. If possible I'd like to be able to go back and forth from the two backends inside an IPython session for instance. Like setting a global variable or something.
```python
import keras
keras.set_backend('theano') # default???
from kears import Dense
X = Dense() # shared theano variables

keras.set_backend('tensorflow')
X = Dense() # shared tensor flow variables
```

Is that too crazy or impractical? It is, then we could just go the conventional way and setup a `.kerasrc`. And something like:
```
Keras_flags=backend='tensorflow' python experiment.py
```

**Comment by EderSantana** [comment]
> I believe what is done now (passing the states unchanged if an input is 0) allows for direction-independent padding. Can you expand on that?

Padding is always on the left, or so we assume, but what happens in the backward pass of a bidirectional RNN? It sees the padding on the right! If we zero out its states or outputs, the last hidden state and output will be useless. Lets say the input is:
```python
X = [1, 2, 3, mask, mask, mask]
# states with zeroing out
H = [h1, h2, h3, 0, 0, 0]
# if we pass the previous state whenever we see mask
H = [h1, h2, h3, h3, h3, h3]
```

This is padding agnostic, see the result for mask in the left:
```python
X = [mask, mask, mask, 1, 2, 3]
# if we pass the previous state whenever we see mask
H = [h1, h1, h1, h1, h2,  h3]
```

In both cases, if we pass the last hidden state to the output, the result will be correct, if we zero out, they will differ and be dependent of where we do padding. This is why bidirectional RNNs won't working with padding, unless we find a way to maintain both hidden states and outputs.

**Comment by rw** [comment]
+1 (watching this thread with interest)

**Comment by elanmart** [comment]
> improving the PR submission and review process.

#JustCurious: how exactly do You plan to achieve this?

I actually have a question about TF's rnns: does `TensorFlow` have a lazy `IfElse`? Because it seems it's going to be quite inefficient if we're going to execture `MAX_STEPS` for every batch with a `switch` that computes both outputs?

**Comment by elanmart** [comment]
Also: `TF` has some cool sampling function for training on large output spaces (`nce, negative sampling` etc). Any plans to incorporate that in Keras?

**Comment by farizrahman4u** [comment]
> How should the choice of the backend be handled by the user?

Something like `keras.set_backend('tensorflow')` would be the best way to do. One of the key features of Keras is that a single python file completely defines a model (no prototxt etc), so we have everything in one  place. Declaring a backend flag in an external text file would be against this spirit of  keras in my opinion.

**Comment by fchollet** [comment]
Thank you for the good suggestions. 

> `keras.set_backend('tensorflow')`

While possible, the implementation would be quite involved. We'll likely release without it, but we will look into adding it in the future. 

> Any plans to incorporate that in Keras?

Maybe, but in general we won't add things that would be specific to one backend.

> direction-independent masking

I think there is some confusion here between states and output. The "states" are a list of tensors (more often a single value, or 2 in the LSTM case) that get fed back into the network, while the output is what gets *out* of the network at a given timestep. In general, the first element of the states list is the previous output. *The current implementation follows what you describe, when it comes to states.* 

However, I realize that it isn't direction-agnostic, because the *last* output (that will be returned in the `return_sequences=False` case) will always be zero if the padding is on the right.

One solution would be, if an input is 0, to use as output the first element of the previous states (instead of outputting 0). But this is very assumption-heavy: although in most cases the first element of the states list will be the last output, there is no guarantee that this would always be the case.

**Comment by fchollet** [comment]
By the way, I realized that `layers/ntm.py` and the associated example were still using Theano --I had overlooked it. I started a conversion, but it uses a bit of Theano-specific functionality that isn't immediately expressible in the abstract backend. 

@EderSantana, can you look into it?

**Comment by fchollet** [comment]
We'll target Monday or Tuesday for the release. If the neural turing machine isn't converted by then, we can either remove it and reintroduce it later, or add exceptions to be triggered when trying to instantiate one with the TF backend.

**Comment by EderSantana** [comment]
@fchollet I'll check it out. I think the problem is because I use masking, but it is not necessary for the example code to run, I can take it our for a while.

**Comment by EderSantana** [comment]
also, can you update the branch? I think I found other issues with the NTM, I also have to set shared ways using the new API. Did you decide how to config which backend to use?

**Comment by fchollet** [comment]
The branch is up to date, latter modifications deal with documentation and unit tests.

> I also have to set shared weights using the new API

You need two things:

```python
# equivalent to T.tensor3(), etc.
self.input = K.placeholder(shape=self.input_shape)

# equivalent to theano.shared(), handles casting automatically
self.M = K.variable(.001 * np.ones((1,)))
self.init_h = K.zeros((self.output_dim))

```

**Comment by fchollet** [comment]
To make things clearer, I've converted the first 230 or so lines. https://gist.github.com/fchollet/4840d822ad88659a7dd7

What's left would involve changes to the logic itself, which is why I didn't do it.

You'll need `K.permute_dims` (dimshuffle), `K.expand_dims` (adding a 1-sized dim at a specific index), `K.rnn`.

**Comment by EderSantana** [comment]
I made a PR to backend by I can't see it xD, can you? It's about the `repeat` function. @fchollet

**Comment by dbonadiman** [comment]
I've seen the discussion about masking and i have a general thought, a layer can handle masks in two way:
- Apply: the mask is applied to the input before, or inside the computation.
- Broadcast: the mask is broadcasted to the upper layers. 

These are quite independent conditions that have to be taken in consideration layers to layers.
Time distributed merge layers should for instance apply the mask without broadcasting it.
Recurrent with return sequences=True applies the mask and broadcast it, but if return sequences is false the mask shouldn't be propagated. Many other condition may arise from model to model but i think that we need layers that are able to generate masks (Embedding) and some layer wise flags to decide whether a mask should be applied or simply broadcasted, with default values matching the common usage of the layer (eg. `mask_dim=1` for masking the time dimension, `mask_dim = -1` to not apply the mask, and `masked_output=False/True`) . 

The current mask usage it is not that transparent in particular for users that keeps asking how we can handle variable size inputs (TBH i had trouble myself). In particular i had to locally reimplement the Time distributed Merge layer to apply the mask before average (summing the non zero and normalising for the actual length of the sentence and not the padded length), and the Merge layer to broadcast the mask under some conditions (Concatenating different feature embeddings for the same input sequence).
The most funny things however is that for some of my model i had to process the input sequence backwards (that is not theoretically solid, but it works better then the unmasked input) to have some kind of convergence using LSTM since i'm forced to have right padding.
