### ISSUE TITLE
verbose=1 significantly slow down the training process.

### ISSUE THREAD

**Issue by fyears** [fchollet/keras#102]
When I am using `model.fit()`, I find that if I use `verbose=1`, the process is significantly slower than that of `verbose=2`. I am using gpu.

**Comment by fchollet** [comment]
What's your batch size? 

All that `verbose=1` does is printing a log line after every batch. Printing does take a few milliseconds, so you don't want it to happen hundreds of times per second. In most cases the training time on each batch will be large enough that you won't see a difference. If the training time per batch is very small, you will see the difference, though.

**Comment by fyears** [comment]
My batch size is 16. (Actually I am running your kaggle-otto code. :-) )

So since it's not a bug. I would close the issue and change verbose to 2 to avoid serious printing time.

**Comment by MjdMahasneh** [comment]
@fyears in some cases, it does affect the duration significantly, as fchollet said. From my experience, repeatedly printing consumes more time that what we would expect:


```
import time
start = time.time()
for i in range(9999):
    pass
print('time passed in first loop : ', time.time() - start)

start = time.time()
for i in range(9999):
    print('I love slowing your script down!')
print('time passed in second loop : ', time.time() - start)
```

The output is something similar to (depends on the specs of your machine, indeed.):

> time passed in first loop :  0.0
> I love slowing your script down!
> I love slowing your script down!
> I love slowing your script down!
> I love slowing your script down!
> .
> .
> time passed in second loop :  35.46507930755615
