### ISSUE TITLE
Combining different filter lengths in 1D convolutional layers

### ISSUE THREAD

**Issue by sebastianruder** [fchollet/keras#1023]
[1] show that combining filter lengths around the 'best' filter length achieves better sentence classification results than just using the 'best' filter length. Is there a possibility to specify a combination of filter lengths for 1D convolution? If not, is this a feature that should be implemented?

Zhang, Y., & Wallace, B. (2015). A Sensitivity Analysis of (and Practitioners’ Guide to) Convolutional Neural Networks for Sentence Classification, (1). Retrieved from http://arxiv.org/abs/1510.03820

**Comment by dbonadiman** [comment]
This is kinda of topic but thanks a lot for the paper :) 
For the question itself i think that it should be up to the user to do that, on the other side the k-max pooling layer is missing from Keras and that is a big issue.

**Comment by dbonadiman** [comment]
@sebastianruder Just a reminder do not exaggerate on the nb_filters because depending on the task you are modelling it might not converge (just experienced that problem).

**Comment by sebastianruder** [comment]
@dbonadiman: Wow, that was fast indeed! Thanks a lot for the commented implementation snippet and the tip! :D

**Comment by dbonadiman** [comment]
@sebastianruder It is fast to do these implementations if you have a working model to test them over ;)

**Comment by MdAsifKhan** [comment]
It creates an identifier issue:

**Comment by MdAsifKhan** [comment]
It creates an identifier issue:
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 366, in add_node
Exception: Unknown identifier: 7input

**Comment by Ambros94** [comment]
This graph model can still be created with keras 2.0 using sequential models?

**Comment by hsiaoyi0504** [comment]
@Ambros94 They are different containers actually. You should check the [documentation](https://keras.io/layers/containers/) for further details.
