### ISSUE TITLE
documentation css change of last day or so breaks layouts and navigation.

### ISSUE THREAD

**Issue by dcgrigsby** [fchollet/keras#1027]
The CSS for the documentation at http://keras.io appears to have changed in the last day or two, breaking display and navigation.

To reproduce:  visit e.g., http://keras.io/models/, note formatting of the examples, note the formatting of the navigation 

(Issue present in Chrome and Safari; presumably others)

**Comment by fchollet** [comment]
Right. It seems we had a botched doc update earlier today. It's fixed now. Thanks for spotting!
