### ISSUE TITLE
Examples are missing parameters

### ISSUE THREAD

**Issue by cjmcmurtrie** [fchollet/keras#1030]
Hi there, this might be due the version I have installed, but most of the examples seem to be missing parameters in various layers.

For instance, when I run the imdb_cnn.py example, the Dense layer is missing a parameter:

Traceback (most recent call last):
  File "D:/aviation/findingsConvolutional.py", line 66, in <module>
    model.add(Dense(hidden_dims))
TypeError: __init__() takes at least 3 arguments (2 given)

Is this because the examples are not up-to-date, or is my version (0.1.2) not up to date?

**Comment by dbonadiman** [comment]
These example works on Keras >= 0.2.0 .

**Comment by fchollet** [comment]
Please update your version of Keras.

**Comment by cjmcmurtrie** [comment]
I will try to, but legacy code for all my projects is written in the older
version.

Incidentally, the reason for this is there were issues getting Theano
running on GPU in Windows for certain versions Anaconda, I don't know if
this has changed (it was back in August this summer).

On Wed, Nov 18, 2015 at 5:23 PM, François Chollet <notifications@github.com>
wrote:

> Closed #1030 <https://github.com/fchollet/keras/issues/1030>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/1030#event-468202652>.
>



-- 
Conan McMurtrie
M (+44)7910 083 514
E cj.mcmurtrie@gmail.com
P 9 Tarleton Gardens, London, SE23 3XN
