### ISSUE TITLE
GAN with Keras

### ISSUE THREAD

**Issue by jocicmarko** [fchollet/keras#1034]
Did anyone manage to create Generative Adversarial Network (GAN) using Keras?
If not, I am going to try implement this according to http://arxiv.org/abs/1406.2661, and make a pull request as an example.

**Comment by EderSantana** [comment]
I did that before, but I can't find the code... Way too many details to get it working... But here are some suggestions that you may find useful http://torch.ch/blog/2015/11/13/gan.html Torch's architecture definition is pretty similar to Keras'

**Comment by phreeza** [comment]
I made a very simple one, here you go: https://github.com/phreeza/keras-GAN
Not sure this needs to be in keras main, it is essentially five lines to set up with keras.

**Comment by iskandr** [comment]
@phreeza This model doesn't work for me, it fails with the following output: 

```
Using Theano backend.
Setting up decoder
Setting up generator
Setting up combined net
Traceback (most recent call last):
  File "simple_gan.py", line 39, in <module>
    gen_dec.compile(loss='binary_crossentropy', optimizer=sgd)
  File "/Users/iskander/code/keras/keras/models.py", line 410, in compile
    train_loss)
  File "/Users/iskander/code/keras/keras/optimizers.py", line 59, in get_updates
    grads = self.get_gradients(loss, params)
  File "/Users/iskander/code/keras/keras/optimizers.py", line 35, in get_gradients
    grads = K.gradients(loss, params)
  File "/Users/iskander/code/keras/keras/backend/theano_backend.py", line 365, in gradients
    return T.grad(loss, variables)
  File "/Users/iskander/code/Theano/theano/gradient.py", line 545, in grad
    handle_disconnected(elem)
  File "/Users/iskander/code/Theano/theano/gradient.py", line 532, in handle_disconnected
    raise DisconnectedInputError(message)
theano.gradient.DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: <TensorType(float32, matrix)>
Backtrace when the node is created:
  File "/Users/iskander/code/keras/keras/backend/theano_backend.py", line 34, in variable
    return theano.shared(value=value, name=name, strict=False)
```

Looking over the code it seems a little suspicious that `trainable` gets set to False before the training loop. Do you that's responsible for the error?

**Comment by phreeza** [comment]
Hey @iskandr , I agree setting trainable manually is a slightly dodgy way of doing it, but it definitely works for me. I have pushed a more recent version to the repo, which i recently ran against keras git. Can you try again with that? Obviously this is totally just my playground code, if there is demand I will clean it up and that will hopefully make it easier to track down the error you are encountering.

**Comment by EderSantana** [comment]
I found my code. If you want to update it to this new API, I could help reviewing: https://github.com/EderSantana/seya/blob/master/examples/wip-GAN.ipynb

**Comment by phreeza** [comment]
@iskandr I was able to reproduce your error with the latest version of keras. It is due to the new caching feature. Setting use_cache=False on all the layers when instantiating should fix this.

**Comment by pwaller** [comment]
Ping. What's the state of the art here, does anyone have anything to play with?

**Comment by EderSantana** [comment]
we wrote something here: https://github.com/commaai/research/blob/master/models/autoencoder.py
it only works with tensorflow, though
and its a autoencoder-gan, you would have to erase a few things to get the GAN only

**Comment by bstriner** [comment]
Implemented a custom model for adversarial networks and multiplayer games:

https://github.com/bstriner/keras_adversarial

Basically, the model is compiled with an optimizer for each player and creates a combined training function.  All the user has to do is create the generator and discriminator networks, pass them to the AdversarialModel, and train using standard model.fit.

I'm hoping a model specific to multiplayer games will make experiments with GANs a lot cleaner.

**Comment by ErmiaAzarkhalili** [comment]
@bstriner Thanks for the package, but could you please simple example for non-image dataset?

**Comment by bstriner** [comment]
@ErmiaAzarkhalili Any dataset in particular? The mnist example just uses dense layers so you should be able to put anything in there.
