### ISSUE TITLE
Convolution2D fails when using filter

### ISSUE THREAD

**Issue by audiofeature** [fchollet/keras#1040]
I'd like to use a Conv2D layer where one of the filter dimensions is the full size of the input image.
I don't want to use zero-padding, therefore I leave the border mode as the default, which is 'valid':
    # border modes:
    full: The output is the full discrete linear convolution of the inputs.
    valid: The output consists only of those elements that do not rely on the zero-padding.
    same: The output is the same size as in1, centered with respect to the ‘full’ output.

    conv_layer1 = (Convolution2D(15, 40, 1, input_shape=(1,40,15)))
    model.add(conv_layer1)
    conv_out1 = Activation('sigmoid')
    model.add(conv_out1)
    model.add(MaxPooling2D(pool_size=(2,1)))

    model.add(Flatten())
    model.add(Dense(200)) 
    model.add(Activation('sigmoid'))
    model.add(Dropout(0.5))

    # last fully connected layer which outputs classes
    model.add(Dense(output_dim=output_dim))
    model.add(Activation('softmax'))

-- It correctly tells me the desired output size of the layer, 

        convout1_f = tfunction([model.get_input(train=False)], conv_out1.get_output(train=False))

        # select for which input image to visualize the activations
        #img_to_visualize = randint(0, len(X_train) - 1)
        img_to_visualize = 0
        convolutions = convout1_f(train_data[img_to_visualize: img_to_visualize+1])
        print "ConvLayer 1 Output size: ", convolutions[0][0].shape

ConvLayer 1 Output size:  (1, 15)

but then fails with :

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x11231ac90>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/Library/Python/2.7/site-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/Library/Python/2.7/site-packages/theano/tensor/opt.py", line 5338, in local_fuse
    tmp.tag.test_value = gof.op.get_test_value(ii).flatten()[0]
IndexError: index out of bounds

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.FusionOptimizer object at 0x11231ac90>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/theano/gof/opt.py", line 195, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/Library/Python/2.7/site-packages/theano/gof/opt.py", line 81, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/theano/tensor/opt.py", line 5498, in apply
    new_outputs = self.optimizer(node)
  File "/Library/Python/2.7/site-packages/theano/tensor/opt.py", line 5338, in local_fuse
    tmp.tag.test_value = gof.op.get_test_value(ii).flatten()[0]
IndexError: index out of bounds

It works when I use 39 as the nb_row parameter, but not with 40 (= the full image height).

Why is that?

**Comment by audiofeature** [comment]
Note that the first code line should read correctly:
conv_layer1 = (Convolution2D(15, 40, 1, input_shape=(1,40,15)))

**Comment by jocicmarko** [comment]
>  I don't want to use zero-padding, therefore I leave the border mode as the default, which is 'valid'

Default value for border mode is 'full', see http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve2d.html

**Comment by daniel-j-h** [comment]
The documentation implies 'valid' --- http://keras.io/layers/convolutional/#convolution2d. Could you have a look at it and check it?

**Comment by jocicmarko** [comment]
My bad :), I totally misunderstood that line in documentation. Default value is indeed 'valid'.

**Comment by audiofeature** [comment]
Sorry this was a false alarm. The problem was due to using a Max pooling on the vertical dimension that was larger than the resulting matrix after the first Convolution:

conv_layer1 = (Convolution2D(15, 40, 1, input_shape=(1,40,15)))
model.add(conv_layer1)
conv_out1 = Activation('sigmoid')
model.add(conv_out1)
model.add(MaxPooling2D(pool_size=(2,1)))

Using a 40x15 input image and a 40x1 filter will create only 1 row as an output, and using a 2x1 max pooling then obviously fails. 
I.e. In the case of using a full vertical filter, obviously no vertical max pooling can be used.
