### ISSUE TITLE
Does Keras support K-hot index representation input？

### ISSUE THREAD

**Issue by placebokkk** [fchollet/keras#1043]
There is the Embedding Layer which could support the index representation of one-hot feature. But sometimes I need not only the one-hot but also the k-hot feature. For example, in NLP task, for a word input in step i, `in addition to the one-hot uni-gram feature,I also want to include some other auxiliary binary feature(e.g. f(x) = if x is a verb).  I could use a k-hot directly in keras like[0,1,0,1] , But how to use a index representation like [1,3] to save the memory?

**Comment by EderSantana** [comment]
You will have to write your own python function to prepare your data. After that you can input it normally to a keras layer.
