### ISSUE TITLE
[wiki]

### ISSUE THREAD

**Issue by EderSantana** [fchollet/keras#1058]
I would like to announce that @fchollet suggested me to start organizing our wiki:
https://github.com/fchollet/keras/wiki

Check out what I wrote and give us feedback before we announce it to the outer world.

I'd really like you guys to check the `Built with Keras` section and do some nice suggestions. You can write your suggestions to the wiki in this Issue.

**Comment by matthiasplappert** [comment]
I'd like to suggest my library, `keras-rl`, for inclusion in the `Built with Keras` section. It's a deep reinforcement library that implements some state-of-the-art algorithms like DQN, double DQN, DDPG and (soon) A3C. You can find it here: https://github.com/matthiasplappert/keras-rl

**Comment by EderSantana** [comment]
@matthiasplappert you could make a PR to https://github.com/fchollet/keras-resources this is the new way to share keras projects
