### ISSUE TITLE
Mixture Density Network

### ISSUE THREAD

**Issue by rpinsler** [fchollet/keras#1061]
Hi all,

I try to build a [MDN](http://research.microsoft.com/en-us/um/people/cmbishop/downloads/Bishop-NCRG-94-004.ps)-like model with keras. This basically adds a GMM on top of a network, which can be modeled using appropriate activation functions, i.e. for a D-dimensional output and M mixture components, we would apply:
- linear activation for the means (M*D outputs)
- exponential activation for the variances (M outputs, assuming radial covariance matrix)
- softmax activation for the weights (M outputs)

I tried to model this using Graph but the only thing I could come up with is to split the (intermediate) output of the network into three dense layers with M*D, M and M outputs, respectively, and then apply the activations mentioned above. However, I don't want to learn separate weights, but rather apply the three activations to different parts of the output (since this is typically done if I understand it correctly). 
I had a look into the Lambda layer too, but then again it seems that indexing in Theano isn't straightforward as well. 

Any ideas?

**Comment by rpinsler** [comment]
I came up with a solution, but don't know how to properly pass the number of mixing coefficients, M, as a parameter. The code looks as follows:

```
M = 3
model_gmm = Sequential()
[...]
model_gmm.add(Dense((M+2)*input_dim))
model_gmm.add(Lambda(gmm_activation(M))
model_gmm.compile(loss=gmm_loss(M), optimizer='adam')

def gmm_activation(M):
  """
  GMM-like activation function.
  Assumes that input has (M+2)*D dimensions, where D is the dimensionality 
  of the target data. The first M*D features are treated as means, the next 
  M features as variances and the last M features as mixture components of the GMM. 
 """

  def gmm_activation_fn(x): 
    D = T.shape(x)[1]/(M+2)
    return T.concatenate([x[:,:M*D-1], T.exp(x[:,M*D:2*M*D-1]), T.nnet.sigmoid(x[:,2*M*D:])], axis=1)

def gmm_loss(M):
  """
  GMM loss function.
  Assumes that y_pred has (M+2)*D dimensions and y_true has D dimensions.
  The first M*D features are treated as means, the next M features as 
  variances and the last M features as mixture components of the GMM. 
  """
  def loss(m, M, y_true, y_pred):
    D = T.shape(y_true)[1]
    return (y_pred[:,(D+1)*M+m]/y_pred[:,D*M+m]) \
      * T.exp(-T.sum(T.sqr(y_pred[:,D*m:(m+1)*D] - y_true))/(2*y_pred[:,D*M+m]**2))

  def gmm_loss_fn(y_true, y_pred):
    seq = T.arange(M)
    result, _ = theano.scan(fn=loss, 
      outputs_info=None, 
      sequences=seq, 
      non_sequences=[M, y_true, y_pred])
    return result.sum()

  return gmm_loss_fn
``` 

Note that for both the activation and the loss function I return another function handle, which takes the correct arguments (as specified by the keras API). However, this doesn't work with the Lambda layer: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 359, in compile
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 74, in get_output
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 1022, in get_output
TypeError: arg 5 (closure) must be tuple
```

Are there better ways to do this?

**Comment by j88k** [comment]
Haven't tested it so can't say if this solves your problem, but I'd use partial from functools [https://docs.python.org/2/library/functools.html]

from functools import partial
M = 3
gmm_used_activation = partial(gmm_activation, M)
model_gmm = Sequential()
[...]
model_gmm.add(Dense((M+2)*input_dim))
model_gmm.add(Lambda(gmm_used_activation))
model_gmm.compile(loss=gmm_loss(M), optimizer='adam')

**Comment by rpinsler** [comment]
Thanks for the suggestion. Actually I tried that as well, but it leads to a similar error. I think I have to write a completely new layer which I can properly parameterize.

**Comment by j88k** [comment]
Thanks.

**Comment by rpinsler** [comment]
I've now implemented something that compiles, but I always get a training error of -Inf. Here's the code:
```
M = 3
model_gmm = Sequential()
[...]
model_gmm.add(Dense((M+2)*input_dim))
model_gmm.add(GMMActivation(M))
model_gmm.compile(loss=gmm_loss, optimizer='adam')

class GMMActivation(Layer):
    """
    GMM-like activation function.
    Assumes that input has (M+2)*D dimensions, where D is the dimensionality of the 
    target data. The first M*D features are treated as means, the next M features as 
    variances and the last M features as mixture components of the GMM. 
    """
    def __init__(self, M, **kwargs):
        super(GMMActivation, self).__init__(**kwargs)
        self.M = M

    def get_output(self, train=False):
      X = self.get_input(train)
      D = T.shape(X)[1]/(self.M+2)
      mu = X[:,:self.M*D]
      sigma = T.exp(X[:,self.M*D:2*self.M*D])
      alpha = T.nnet.sigmoid(X[:,2*self.M*D:])
      return T.concatenate([mu, sigma, alpha], axis=1)

    def get_config(self):
        config = {"name": self.__class__.__name__,
                  "M": self.M}
        base_config = super(GMMActivation, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

def gmm_loss(y_true, y_pred):
  """
  GMM loss function.
  Assumes that y_pred has (M+2)*D dimensions and y_true has D dimensions. The first 
  M*D features are treated as means, the next M features as variances and the last 
  M features as mixture components of the GMM. 
  """
  def loss(m, M, D, y_true, y_pred):
    mu = y_pred[:,D*m:(m+1)*D]
    sigma = y_pred[:,D*M+m]
    alpha = y_pred[:,(D+1)*M+m]
    return (alpha/sigma) * T.exp(-T.sum(T.sqr(mu-y_true),-1)/(2*sigma**2))

  D = T.shape(y_true)[1]
  M = T.shape(y_pred)[1]/D - 2
  seq = T.arange(M)
  result, _ = theano.scan(fn=loss, outputs_info=None, 
    sequences=seq, non_sequences=[M, D, y_true, y_pred])
  return -T.log(result.sum(0))
```

Any ideas?

**Comment by rpinsler** [comment]
It seems that there's still some issue. This happened after like 16 iterations:
```
 6400/10520 [=================>............] - ETA: 34s - loss: 2.0416
 6528/10520 [=================>............] - ETA: 33s - loss: inf   
 6656/10520 [=================>............] - ETA: 32s - loss: nan
...
```

**Comment by rpinsler** [comment]
Was probably just a numeric problem with the optimizer.

**Comment by ylqfp** [comment]
mark

**Comment by yunzhou** [comment]
I actually merge the scale sigmas and scale alpha in the gmm_loss, then the numeric problem is gone.

```python
def neg_log_normal_mixture_likelihood(true, parameters):
    D = T.shape(true)[1]
    M = T.shape(parameters)[1] / (D + 2)

    means = parameters[:, : D * M]
    sigmas = T.exp(parameters[:, D * M: (D + 1) * M])
    weights = T.nnet.softmax(parameters[:, (D + 1) * M:])
    root_two_pi = np.sqrt(2 * np.pi)

    def component_normal_likelihood(i, mus, sis, als, tr):
        mu = mus[:, i * D:(i + 1) * D]
        sig = sis[:, i]
        al = als[:, i]
        ps = T.exp(-(T.sum((tr - mu) ** 2, axis=-1)) / (2 * sig ** 2)) / (sig * root_two_pi)
        pin = al * ps
        return pin

    r, _ = theano.scan(
            fn=component_normal_likelihood,
            outputs_info=None,
            sequences=T.arange(M),
            non_sequences=[means, sigmas, weights, true])
    lp = -T.log(T.sum(r, axis=0))
    return lp
```

**Comment by erlebach** [comment]
Hi yunzhou, 

According to Keras documentation, the arguments to a loss function, in your case, "true" and "parameters", in 

 def neg_log_normal_mixture_likelihood(true, parameters):

should have the same dimensionality. I printed the shape of the two arguments in the function np_loss(), and they were different. The actual parameters in neg_log_normal_mixture_likelihood probably do not have memory allocated yet when the function is first called, so I cannot ascertain the argument dimensionality at that point. 

Any clarification on this would be great. Thanks!

  Gordon

**Comment by yunzhou** [comment]
Yes the "true" and "parameters" are in different shapes. It is a dirty and hacky way to implement the mixture density network layer.

The "true" is the samples in the dataset. But since we want to use density network layer to generate new data, we are optimizing the parameters of the mixture layer.
The truth dimension is only n*2, since they are points on XY plane. But we using the mixture gaussian model to generate these points.

So given our training dataset, we want to find out the parameters of the mixture gaussian model are most likely to generate these points.

**Comment by erlebach** [comment]
Great! Thanks for the reply. You confirmed my hypothesis.

    Gordon

On Sun, Jun 26, 2016 at 10:06 PM, ZY0627 <notifications@github.com> wrote:

> Yes the "true" and "parameters" are in different shapes. It is a dirty and
> hacky way to implement the mixture density network layer.
>
> The "true" is the samples in the dataset. But since we want to use density
> network layer to generate new data, we are optimizing the parameters of the
> mixture layer.
> The truth dimension is only n*2, since they are points on XY plane. But we
> using the mixture gaussian model to generate these points.
>
> So given our training dataset, we want to find out the parameters of the
> mixture gaussian model are most likely to generate these points.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/fchollet/keras/issues/1061#issuecomment-228639779>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAT0ZD0YBslgI5K0uwj4gJrOAam_l06Nks5qPzALgaJpZM4GnRee>
> .
>



-- 
Gordon Erlebacher
Chair, Department of Scientific Computing

**Comment by erlebach** [comment]
Hi again yunzhou, 

Looking at the following lines in the function nploss(), 

```
￼￼￼￼for c in range(M):
        z[:,c:c+1] = np.sum(((true - mu[:, c * D:(c + 1) * D]) / sig[:, c * D:(c + 1) * D]) ** 2, axis=1, keepdims=True, dtype=np.float32)/ -2.0
        normalizer = np.prod(sig[:, c * D:(c + 1) * D], axis=1, keepdims=True, dtype=np.float32) * two_pi
        z[:,c:c+1] = z[:,c:c+1] + np.log(al[:, c:c + 1]) - np.log(normalizer)
    lp = np_log_sum_exp(z,1)
```

Shouldn't z[:c,c+1] be np.sum(((T.exp(true-mu......**2), axis=1 ...)

Given how you sample your distribution in draw_sample_from_mixture_guassian, it would seem to be the case. You do use the function np.random.multivariate_normal(mu, sig ** 2, 1) to do so, which implies you expect the mixture model to be a sum of Gaussian distributions. 

Thanks, 

    Gordon
