### ISSUE TITLE
Misleading documentation about Activation layers?

### ISSUE THREAD

**Issue by rmalouf** [fchollet/keras#1064]
The documentation says: "Activations can either be used through an Activation layer, or through the activation argument supported by all forward layers" so that 

```
from keras.layers.core import Activation, Dense

model.add(Dense(64))
model.add(Activation('tanh'))
```

is equivalent to:

```
model.add(Dense(64, activation='tanh'))
```

However, this doesn't seem to be the case.  I'm getting very different results using the two methods (namely, the second converges and the first doesn't), and as far as I can tell, the problem is that the first version applies both the default activation for the previous layer and the activation specified in the Activation layer.  Only in the case where the previous layer's activation is linear (which happens to be the case for Dense) do the two forms end up being equivalent.  Or am I missing something?

**Comment by lemuriandezapada** [comment]
No, that's quite correct. However forward layers are pretty much all non-recurrent layers. So that will be equivalent for those.
Recurrent layers will have different functionality.

**Comment by rmalouf** [comment]
Ah yes, I didn't read carefully enough and missed the word "forward".  In my defense, it's still a little confusing, since the recurrent layers all support the activation flag too.  It's not clear that the discussion only applies to forward layers. Maybe rather than 
````
Activations can either be used through an Activation layer, or through the activation argument supported by all forward layers
````
it could say something like
````
For forward layers, activations can either be used through an Activation layer or through the activation argument
````
