### ISSUE TITLE
How to save model trained by keras?

### ISSUE THREAD

**Issue by cxfneo** [fchollet/keras#1069]
hi
    How to save model trained by keras? and Will the model.fit() function with several epochs  shuffle the training data?

**Comment by jocicmarko** [comment]
Check out **model.save_weights()** function. It store the weights of all layers to a HDF5 file.
**model.fit()** shuffles the data by default (argument shuffle=True) at each epoch.

**Comment by EderSantana** [comment]
That is answered in the FAQ http://keras.io/faq/

**Comment by michael-quinlan** [comment]
I think this issue should be closed.

**Comment by MartinThoma** [comment]
http://keras.io/getting-started/faq/#how-can-i-save-a-keras-model

**Comment by alyato** [comment]
@cxfneo You can do the suggestion by @MartinThoma.

save the weights
save the json or yaml format

**Comment by L226** [comment]
Is there any way to save the weights without using h5py? I'm deploying to AWS EB and h5py won't install properly.

**Comment by alyato** [comment]
The keras document suggest that  the h5py format is to save the weights. I
install it in ubuntu 14.04

2016-05-26 20:55 GMT-06:00 L226 <notifications@github.com>:

**Comment by ShunyuanZ** [comment]
I used model.save(), trying to save the trained model. But the following error raised:

AttributeError: 'Sequential' object has no attribute 'save'


I know there is attribute 'save_weights' to save all parameters, but I would like to save the whole trained model, including weights, architecture of the model, configuration etc. , so that I can reconstruct the model, or resume the training model afterwards.

Any suggestion? Thank you!

**Comment by jackhftang** [comment]
same issue: 'AttributeError: 'Sequential' object has no attribute 'save''

**Comment by ChihebTrabelsi** [comment]
I am not working with sequential models and still, I coudn't use model.save to store the architecture of my model and its parameters. The following example contains the error that I get when try to save the model:
"
In [50]: model.save('saved_keras_model')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-50-68220170a293> in <module>()
----> 1 model.save('saved_keras_model')

AttributeError: 'Model' object has no attribute 'save'
"
However, I found an easy way which allows to store the model and loading it. It consists of first (save / load) its architecture first, then (save / load) its parameters, i.e, its weights.
http://machinelearningmastery.com/save-load-keras-deep-learning-models/

Thank you

**Comment by cicobalico** [comment]
To those having problem with model.save().
It started working for me when I finally installed keras directly from github
try this:
`sudo pip install --upgrade git+https://github.com/fchollet/keras`

**Comment by joe-123** [comment]
Same problem here! (model.save not working)
Reinstalled keras directly from github like recommended (version 1.0.7). Still not working though...

**Comment by ShunyuanZ** [comment]
Tried recommended above @cicobalico , reinstall keras from github. The version of keras is 1.0.7.
Now model.save() works, but load_model() to load a compiled model (https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model) is not working...

```
final_model.save('mymodel.h5') ## this worked, 'mymodel.h5' file is saved to local
del final_model ## delete current model
final_model=load_model('mymodel.h5') ## trying to reload the compiled model
```

Then got following error:
```
Traceback (most recent call last):
  File "C:\Users\Yuan_Work\AppData\Local\Enthought\Canopy\User\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-62-0e6059d74008>", line 1, in <module>
    final_model=load_model('mymodel.h5')
NameError: name 'load_model' is not defined
```

**Comment by ShunyuanZ** [comment]
Just in case someone had the same error when loading model:
`NameError: name 'load_model' is not defined`
I figured in my case the problem was that I did't import the module..
So I did the following, then model was correctly loaded:
```
from keras.models import load_model
model=keras.models.load_model('mymodel.h5')
```

**Comment by joe-123** [comment]
Seems to be a problem with my configuration. On a different computer it works for me as well! Thx!

**Comment by guicho271828** [comment]
to be closed?

**Comment by Bitsolo** [comment]
I had same issue and fixed with

`sudo pip install h5py`

**Comment by dudeperf3ct** [comment]
I re-intsalled keras as @cicobalico suggested but still load_model() error `  File "test.py", line 4, in <module>
    model = load_model('model_with_mymodel.h5')
  File "/home/dude_perf3ct/anaconda2/lib/python2.7/site-packages/Keras-1.2.2-py2.7.egg/keras/models.py", line 140, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.
`. 
I saved the model using model.save('model_with_mymodel.h5') and have the .h5 file saved in the location after training but **unable to load**.

**Comment by imanoluria** [comment]
@ShunyuanZ if you do:
`from keras.models import load_model`
then you don´t have to type `model=keras.models.load_model(--)` it's enough with `model=load_model(--)`.
When you imported you don't have to type all the source.

**Comment by jerrypaytm** [comment]
Is it possible to load the model from s3? The file path argument only works locally.

**Comment by ElenaGlezRubio** [comment]
I have the same problem. I cannot save/load to/from s3. Any help?

**Comment by jerrypaytm** [comment]
I ended up using `aws s3` cli to save and load from s3.

**Comment by manbharae** [comment]
what is significance of `model.h5`  , is that a format like csv or .dat or .png etc? 
I tried `model.h6` and the model still ouput good results.

**Comment by Krunal91** [comment]
If you are using google colab gpu, you might run into this problem.
I did : from tensorflow import keras 

To fix it: I installed keras using pip and then do : pip isntall keras

**Comment by nguyenvulong** [comment]
after `model = load_model("file.h5")`
How can I reuse it?

I've tried `model.score(X, y)` but it throws: `AttributeError: 'Sequential' object has no attribute 'score`

**Comment by Afef00** [comment]
Is it possible to save/load the whole model(weight and architecture) to json file ?

**Comment by DMells** [comment]
I had this issue too - "model has no attribute 'save'"

For those also facing this, it was because I had assigned the model.fit() to a variable like so :
```
model = text_model.fit(train_data, validation_data=val_data, epochs=NB_EPOCHS)
```

And then subsequently calling model.save() resulted in the error.

Instead, don't assign the variable, just fit, and then call save on 'text_model'.

```
text_model.fit(train_data, validation_data=val_data, epochs=NB_EPOCHS)

text_model.save('save_directory')
```
