### ISSUE TITLE
mnist_irnn.py strange behavior

### ISSUE THREAD

**Issue by lxc-xx** [fchollet/keras#1076]
Not sure if it is due to my personal setting or it is a general issue.

I can run the example mnist_irnn.py using CPU.
When I run it using gnu, I got this error message:

```
ubuntu@ip-172-31-2-0:~/keras/examples$ python mnist_irnn.py
Using gpu device 0: GRID K520 (CNMeM is disabled)
X_train shape: (60000, 784, 1)
60000 train samples
10000 test samples
Evaluate IRNN...
Train on 60000 samples, validate on 10000 samples
Epoch 1/200
Traceback (most recent call last):
  File "mnist_irnn.py", line 69, in <module>
    show_accuracy=True, verbose=1, validation_data=(X_test, Y_test))
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 495, in fit
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 216, in _fit
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 952, in <lambda>
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 389, in theano.scan_module.scan_perform.perform (/home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/scan_perform/mod.cpp:3936)
AttributeError: 'CudaNdarray' object has no attribute 'data'
Apply node that caused the error: forall_inplace,gpu,grad_of_scan_fn}(Elemwise{minimum,no_inplace}.0, GpuSubtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, GpuSubtensor{int64:int64:int64}.0, GpuSubtensor{::int64}.0, Elemwise{minimum,no_inplace}.0, Elemwise{minimum,no_inplace}.0, <CudaNdarrayType(float32, matrix)>, GpuDimShuffle{1,0}.0)
Toposort index: 247
Inputs types: [TensorType(int64, scalar), CudaNdarrayType(float32, 3D), TensorType(int8, (False, False, True)), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D), TensorType(int64, scalar), TensorType(int64, scalar), CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(), (784, 32, 100), (784, 32, 1), (784, 32, 100), (785, 32, 100), (), (), (100, 100), (100, 100)]
Inputs strides: [(), (-3200, 100, 1), (-32, 1, 1), (-3200, 100, 1), (-3200, 100, 1), (), (), (100, 1), (1, 100)]
Inputs values: [array(784), 'not shown', 'not shown', 'not shown', 'not shown', array(784), array(784), 'not shown', 'not shown']
Outputs clients: [[], [GpuSubtensor{::int64}(forall_inplace,gpu,grad_of_scan_fn}.1, Constant{-1})], [GpuReshape{2}(forall_inplace,gpu,grad_of_scan_fn}.2, MakeVector{dtype='int64'}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

According to the output, I re-run the code using:

```
THEANO_FLAGS='optimizer=None' python mnist_irnn.py
```

Then there is no error message but very slow.

Anyone has similar issues?

**Comment by jeffzhengye** [comment]
I saw TensorType(int64, which is not going to work with GPU.

On Wed, Nov 25, 2015 at 3:04 AM, Xuanchong <notifications@github.com> wrote:

> Not sure if it is due to my personal setting or it is a general issue.
>
> I can run the example mnist_irnn.py using CPU.
> When I run it using gnu, I got this error message:
>
> ubuntu@ip-172-31-2-0:~/keras/examples$ python mnist_irnn.py
> Using gpu device 0: GRID K520 (CNMeM is disabled)
> X_train shape: (60000, 784, 1)
> 60000 train samples
> 10000 test samples
> Evaluate IRNN...
> Train on 60000 samples, validate on 10000 samples
> Epoch 1/200
> Traceback (most recent call last):
>   File "mnist_irnn.py", line 69, in <module>
>     show_accuracy=True, verbose=1, validation_data=(X_test, Y_test))
>   File "build/bdist.linux-x86_64/egg/keras/models.py", line 495, in fit
>   File "build/bdist.linux-x86_64/egg/keras/models.py", line 216, in _fit
>   File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in __call__
>     storage_map=getattr(self.fn, 'storage_map', None))
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
>     reraise(exc_type, exc_value, exc_trace)
>   File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in __call__
>     outputs = self.fn()
>   File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 963, in rval
>     r = p(n, [x[0] for x in i], o)
>   File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 952, in <lambda>
>     self, node)
>   File "theano/scan_module/scan_perform.pyx", line 389, in theano.scan_module.scan_perform.perform (/home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/scan_perform/mod.cpp:3936)
> AttributeError: 'CudaNdarray' object has no attribute 'data'
> Apply node that caused the error: forall_inplace,gpu,grad_of_scan_fn}(Elemwise{minimum,no_inplace}.0, GpuSubtensor{int64:int64:int64}.0, Subtensor{int64:int64:int64}.0, GpuSubtensor{int64:int64:int64}.0, GpuSubtensor{::int64}.0, Elemwise{minimum,no_inplace}.0, Elemwise{minimum,no_inplace}.0, <CudaNdarrayType(float32, matrix)>, GpuDimShuffle{1,0}.0)
> Toposort index: 247
> Inputs types: [TensorType(int64, scalar), CudaNdarrayType(float32, 3D), TensorType(int8, (False, False, True)), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D), TensorType(int64, scalar), TensorType(int64, scalar), CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
> Inputs shapes: [(), (784, 32, 100), (784, 32, 1), (784, 32, 100), (785, 32, 100), (), (), (100, 100), (100, 100)]
> Inputs strides: [(), (-3200, 100, 1), (-32, 1, 1), (-3200, 100, 1), (-3200, 100, 1), (), (), (100, 1), (1, 100)]
> Inputs values: [array(784), 'not shown', 'not shown', 'not shown', 'not shown', array(784), array(784), 'not shown', 'not shown']
> Outputs clients: [[], [GpuSubtensor{::int64}(forall_inplace,gpu,grad_of_scan_fn}.1, Constant{-1})], [GpuReshape{2}(forall_inplace,gpu,grad_of_scan_fn}.2, MakeVector{dtype='int64'}.0)]]
>
> HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
> HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
>
> According to the output, I re-run the code using:
>
> THEANO_FLAGS='optimizer=None' python mnist_irnn.py
>
> Then there is no error message but very slow.
>
> Anyone has similar issues?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/1076>.
>



-- 
Jeff Ye.

**Comment by lxc-xx** [comment]
Yeah. But I am not sure where the TensorType(int64, scalar) is from. I remove the weight initialization part. But the error still exists.
