### ISSUE TITLE
Advanced activations in recurrent layers?

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#1085]
Currently advanced activations come as part of separate layers. Is there any way we can push them to also be settable through the activation=? part of a layer creation?

**Comment by EderSantana** [comment]
I mentioned the same thing in the ELU PR https://github.com/fchollet/keras/pull/1079
what do you think @transcranial ?

**Comment by transcranial** [comment]
I agree it would be nice to be able to experiment with advanced activations inside RNNs, for example. I think having the activations that are parameterized (LeakyReLU, ELU, ThresholdedLinear, ThresholdedReLU) - even though they don't have state - still makes sense. Currently the way `activation=` is initialized, I don't  see a way to pass in kwargs. Maybe we can modify https://github.com/fchollet/keras/blob/master/keras/activations.py#L47-L49 or https://github.com/fchollet/keras/blob/master/keras/utils/generic_utils.py#L8-L19?
