### ISSUE TITLE
Wrong predictions after loading a saved model

### ISSUE THREAD

**Issue by hemanth2090** [fchollet/keras#1089]
Hi,

   I have a trained a model which is a combination of keras and theano. I have the cifar10 convolution and pooling layers and then defined three dense layers in theano. Each dense layer gives a 10 dimension one-hot vector. To obtain the predictions, I use the theano function as below.
```
f_test = theano.function([model.layers[0].input],[dense.get_output(train=False) for dense in dense_layer])
```

I saved the weights of the dense layer and model separately. I have saved in two ways. I used both pickling as well as model.save_weights() for the convolution and pooling layers. For the dense layers, I used pickling and dense_layer.get_weights(). 

When I load the weights and run my predictions, I get a different values from when the predictions were obtained while training. My predictions are obtained as given below.
```
predictions = f_test(test_images)
```

The error is similar to issue #884. Can someone please tell me how to correct this?

**Comment by mthmn20** [comment]
@hemanth2090, did you figure this out? I'm having the same issue and am pretty stumped...
