### ISSUE TITLE
Support for context windows and Embedding layer

### ISSUE THREAD

**Issue by amitbeka** [fchollet/keras#1090]
Is it possible to use context window approach with the Embedding layer?

IIUC, the Embidding layer gets a 2-d matrix of (nb_samples, maxlen) so it isn't possible to use a context window shape like (nb_samples, maxlen, cwindow).

However, I would like to have a single embedding layer for all the words in the context window (and not multiple Embedding layers, one for each position in the window). Is it possible somehow with a Graph model?

Thanks, Beka

**Comment by nooralahzadeh** [comment]
Hi Beka
I have a same issue, did you find any solution.
I am thinking to create this context_window before feeding to embedding layer.

**Comment by amitbeka** [comment]
No I haven't :(
You can write a layer yourself which does it, I think

**Comment by nooralahzadeh** [comment]
Do you think I have to put first embedding layer and then the context layer or vice versa.
other issue is using sequence or Graph?

**Comment by amitbeka** [comment]
I guess an embedding layer first, then some kind of context layer which adds the embedding of each word to the correct "position" for each timestamp. The graph/sequence question seems irrelevant - each layer should work on both, and this one too.

**Comment by nooralahzadeh** [comment]
I found out by modifying  the code of embedding layer in Keras you can have your input in context window format in 3D dimension (sample_size, sequence_Length, cwindow) , the embedding can generate the out put. Now I dont know how to create new embedding layer and add it to the Keras.

**Comment by amitbeka** [comment]
I'm not sure what you mean "create a new embedding and add to Keras". You can copy/paste or subclass the current Embedding class and use your modifications to create a new class, e.g. CWEmbeddings.

**Comment by nooralahzadeh** [comment]
Following class will do this job:

from __future__ import absolute_import
from keras import backend as K
from keras import activations, initializations, regularizers, constraints
import tensorflow as tf
 
from keras.layers.core import Layer

class CWEmbedding(Layer):
	
    '''Turn positive integers (indexes) into dense vectors of fixed size.
    see "http://deeplearning.net/tutorial/rnnslu.html#context-window" for more detail
    eg. [[1,2,3], [2,3,4]] where the context_window is 3 here, and you want the embedding for each of the index in the vector
    This layer can only be used as the first layer in a model.
    # Input shape
        3D tensor with shape: `(nb_samples, sequence_length, context-window)`.
    # Output shape
        3D tensor with shape: `(nb_samples, sequence_length, output_dim)`.
    # Arguments
      input_dim: int >= 0. Size of the vocabulary, ie.
          1 + maximum integer index occurring in the input data.
      output_dim: int >= 0. Dimension of the dense embedding.
     context_window: int >= 0.
      init: name of initialization function for the weights
          of the layer (see: [initializations](../initializations.md)),
          or alternatively, Theano function to use for weights initialization.
          This parameter is only relevant if you don't pass a `weights` argument.
      weights: list of numpy arrays to set as initial weights.
          The list should have 1 element, of shape `(input_dim, output_dim)`.
      W_regularizer: instance of the [regularizers](../regularizers.md) module
        (eg. L1 or L2 regularization), applied to the embedding matrix.
      W_constraint: instance of the [constraints](../constraints.md) module
          (eg. maxnorm, nonneg), applied to the embedding matrix.
      mask_zero: Whether or not the input value 0 is a special "padding"
          value that should be masked out.
          This is useful for [recurrent layers](recurrent.md) which may take
          variable length input. If this is `True` then all subsequent layers
          in the model need to support masking or an exception will be raised.
      input_length: Length of input sequences, when it is constant.
          This argument is required if you are going to connect
          `Flatten` then `Dense` layers upstream
          (without it, the shape of the dense outputs cannot be computed).
    '''
    input_ndim = 2

    def __init__(self, input_dim, output_dim, context_window,
                 init='uniform', input_length=None,
                 W_regularizer=None, activity_regularizer=None,
                 W_constraint=None,
                 mask_zero=False,
                 weights=None, **kwargs):
        self.context_window=context_window
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.init = initializations.get(init)
        self.input_length = input_length
        self.mask_zero = mask_zero

        self.W_constraint = constraints.get(W_constraint)
        self.constraints = [self.W_constraint]

        self.W_regularizer = regularizers.get(W_regularizer)
        self.activity_regularizer = regularizers.get(activity_regularizer)

        self.initial_weights = weights
        kwargs['input_shape'] = (self.input_dim,)
        super(CWEmbedding, self).__init__(**kwargs)

    def build(self):
        self.input = K.placeholder(shape=(self.input_shape[0], self.input_length, self.context_window),
                                   dtype='int32')
        self.W = self.init((self.input_dim, self.output_dim))
        self.trainable_weights = [self.W]
        self.regularizers = []
        if self.W_regularizer:
            self.W_regularizer.set_param(self.W)
            self.regularizers.append(self.W_regularizer)

        if self.activity_regularizer:
            self.activity_regularizer.set_layer(self)
            self.regularizers.append(self.activity_regularizer)

        if self.initial_weights is not None:
            self.set_weights(self.initial_weights)

    def get_output_mask(self, train=None):
        X = self.get_input(train)
        if not self.mask_zero:
            return None
        else:
            return K.not_equal(X, 0)

    @property
    def output_shape(self):
        return (self.input_shape[0], self.input_length, self.output_dim*self.context_window)

    def get_output(self, train=False):
        X = self.get_input(train)
        out = K.gather(self.W, X)
	# as far as the first dimension in None the wildcard "-1" has been used
 	out=K.reshape(out, [-1, self.input_length, self.output_dim*self.context_window])
        return out

    def get_config(self):
        config = {"name": self.__class__.__name__,
                  "input_dim": self.input_dim,
                  "output_dim": self.output_dim,
                  "context_window":self.context_window,
                  "init": self.init.__name__,
                  "input_length": self.input_length,
                  "mask_zero": self.mask_zero,
                  "activity_regularizer": self.activity_regularizer.get_config() if self.activity_regularizer else None,
                  "W_regularizer": self.W_regularizer.get_config() if self.W_regularizer else None,
                  "W_constraint": self.W_constraint.get_config() if self.W_constraint else None}
        base_config = super(CWEmbedding, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

**Comment by amitbeka** [comment]
looks good a well coded :+1: 
I don't have any project I may test it with, so I guess that you can add a test and make a pull request, looks like a good addition to the repo

**Comment by nooralahzadeh** [comment]
I found out the  `def get_output_mask(self, train=None): ` must be updated as follow because in model.fit() uses the mask part if the mask_zero=True in embedding layer, I am wondering if it is enough and there is no any affect in other part of keras. However I tested and I saw the loss value is calculated correctly but acc value seems has a problem.

`def get_output_mask(self, train=None):
        X = self.get_input(train)
        if not self.mask_zero:
            return None
        else:
	    #here as far as the dimension of X is (?,input_length, context_window) we have to convert the mask to (?, input_length) 
	    #to be consider in the loss 	calculation
            return tf.greater(tf.reduce_sum(tf.to_int32(K.not_equal(X, 0), name='ToInt32'),2),0)`

**Comment by ymfa** [comment]
Thanks for @nooralahzadeh 's code, but it doesn't seem to work when I don't have an `input_length`. I have some sequences of variable lengths, and `Embedding(len(input_set), 256)` was the layer I used before using context windows. Changing that to `CWEmbedding(len(input_set), 256, 7)` breaks the program when I do `model.compile`, before I load any data. The error was `theano.tensor.var.AsTensorError: ('Cannot convert [-1, None, 1792] to TensorType', <class 'list'>)`; apparently the offending line is `out=K.reshape(out, [-1, self.input_length, self.output_dim*self.context_window])`.

**Comment by nooralahzadeh** [comment]
@ymfa  Could you have variable input length in Keras? as I know you have to pad the input sequence to have same length in each batch!!

**Comment by rhythmbhatia** [comment]
Hey @nooralahzadeh can we use it as fourth or fifth layer? Some other changes are required for that? Since its mentioned in the code that itcan be used only as first layer.
