### ISSUE TITLE
IndexError when running Examples

### ISSUE THREAD

**Issue by dichld** [fchollet/keras#1091]
I tried running two official examples without any changing, both of them show the IndexError, for example, cifar10_cnn:

---------------------------------------------------------------------------
```
IndexError                                Traceback (most recent call last)
<ipython-input-1-52a55e5c76bc> in <module>()
     67 # let's train the model using SGD + momentum (how original).
     68 sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
---> 69 model.compile(loss='categorical_crossentropy', optimizer=sgd)
     70 
     71 X_train = X_train.astype("float32")

.......


/home/cics/Theano/theano/tensor/nnet/abstract_conv2d.pyc in get_conv_output_shape(image_shape, kernel_shape, border_mode, subsample)
     53         out_shp = tuple(get_conv_shape_1axis(
     54             imshp[i], kshp[i], border_mode, subsample[i])
---> 55             for i in range(len(subsample)))
     56     return (bsize, nkern) + out_shp
     57 

/home/cics/Theano/theano/tensor/nnet/abstract_conv2d.pyc in <genexpr>((i,))
     53         out_shp = tuple(get_conv_shape_1axis(
     54             imshp[i], kshp[i], border_mode, subsample[i])
---> 55             for i in range(len(subsample)))
     56     return (bsize, nkern) + out_shp
     57 

IndexError: list index out of range
```

**Comment by rpinsler** [comment]
Just tried the cifar10_cnn example and it worked. Do you have the latest Theano and keras versions?

**Comment by dichld** [comment]
@rpinsler Yes, I have reinstalled several times. It's still there.

**Comment by rpinsler** [comment]
I assume you use the Theano version from github, not PyPI (sudo pip install git+git://github.com/Theano/Theano.git). Then maybe it's a problem with one of the dependencies, e.g. numpy. For some features, Theano requires numpy 1.8.

**Comment by dichld** [comment]
@rpinsler Look at the last track,
```
/home/cics/git/Theano/theano/tensor/nnet/abstract_conv2d.py in <genexpr>((i,))
     54         out_shp = tuple(get_conv_shape_1axis(
     55             imshp[i], kshp[i], border_mode, subsample[i])
---> 56             for i in range(len(subsample)))
     57     return (bsize, nkern) + out_shp
     58 
```
"i" has value 0 and 1, but "imshp" is a "TensorVariable" not given value, so "pimshp[0"] is invalid.
Do you know what could cause it?

**Comment by benjaminklein** [comment]
I had the same problem. I reinstalled theano from commit f52b6e421b78a70c7d341358311268f0dc5a65a0 and now the example is working.

**Comment by jhallard** [comment]
there was a bug with Theano that was causing this, it should be fixed at HEAD now.

**Comment by alaabd** [comment]
I have the same problem, i try to upgrade keras, but didn't work???

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 630, in convolution
    input_channels_dim = input.get_shape()[num_spatial_dims + 1]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 502, in __getitem__
    return self._dims[key]
IndexError: list index out of range

**Comment by YaduKini** [comment]
I have the same problem when I used Keras. could anyone please help me?

 File "/home/hitech/anaconda3/envs/dl_env/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 524, in __getitem__
    return self._dims[key]

IndexError: list index out of range
