### ISSUE TITLE
LSTM `go_backwards`

### ISSUE THREAD

**Issue by jakubfiala** [fchollet/keras#1093]
Hello,

When I try to run the `imdb_bidirectional_lstm.py` example, the model fails to build, and it throws the following error:

```
  File "/usr/local/lib/python2.7/site-packages/keras/layers/recurrent.py", line 385, in __init__
    super(LSTM, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/keras/layers/core.py", line 23, in __init__
    assert kwarg in {'input_shape'}, "Keyword argument not understood: " + kwarg
AssertionError: Keyword argument not understood: go_backward
```

I'm using the latest Keras from `pip`, as well as the latest Theano from github, as was suggested many times. The error obviously occurs even when I try to create a backwards LSTM layer in my own models.

Any clue why this might be?

**Comment by fchollet** [comment]
> I'm using the latest Keras from pip

That is not the latest Keras. The latest Keras is the master branch on
Github.

**Comment by jakubfiala** [comment]
oh okay, should `go_backwards` work in the github version?

**Comment by fchollet** [comment]
Yes.

**Comment by jakubfiala** [comment]
Thanks!
