### ISSUE TITLE
Deconvolutional Layer using Keras

### ISSUE THREAD

**Issue by KlaymenGC** [fchollet/keras#1098]
Hello everyone,

I'm new to deep learning and python and now I'm trying to implement a deconvolutional network to do semantic segmentation (http://arxiv.org/abs/1505.04366), I've got a problem implementing the deconvolutional layer, the code is shown below:
```python
# fully connected layer 1, 8x8x8 -> 1x1x16
model.add(Flatten())
model.add(Dense(16))
model.add(Activation('relu'))

# deconv layer 1, 1x1x16 -> 8x8x8
model.add(Convolution2D(8, 8, 8,
                        border_mode='full'))
model.add(Activation('relu'))
```
I'll leave out the convolutional layer, an error occurs right after the fully connected layer:
```
Traceback (most recent call last): 
File "/Documents/PycharmProjects/Deconvnet/Deconvnet.py", line 77, in <module> border_mode='full')) 
File "/Library/Python/2.7/site-packages/keras/layers/containers.py", line 37, in add self.layers[-1].set_previous(self.layers[-2]) 
File "/Library/Python/2.7/site-packages/keras/layers/core.py", line 33, in set_previous str(self.input_ndim) + " but previous layer has output_shape " + str(layer.output_shape)
AssertionError: Incompatible shapes: layer expected input with ndim=4 but previous layer has output_shape (None, 16)
```
I think the deconvolution using convolution has no problem theoretically... Is there a way of doing this deconvolution using Keras? Any help would be much appreciated!

**Comment by AvantiShri** [comment]
As the error says, your shapes are incompatible; 2d convolutional layers expect the input to have dimensions of [batch index, channel, row, column], but the fully connected layers have dimensions of [batch index, node index]. You would need to use http://keras.io/layers/core/#reshape to fix this. Also note that the second and third arguments to Convolution2D are referring to the number of rows/columns in the *kernel*, not in the output.

**Comment by KlaymenGC** [comment]
@AvantiShri I've solved the problem now, thank you so much for your help!!

**Comment by EderSantana** [comment]
please don't change the tittle of your issues after solved. This difficult searches.

**Comment by meanmee** [comment]
@KlaymenGC Could U share your experiences about deconvolution？ Thx
