### ISSUE TITLE
scipy error: undefined symbol: sgegv_

### ISSUE THREAD

**Issue by dichld** [fchollet/keras#1108]
```
/usr/local/lib/python2.7/dist-packages/scipy/linalg/lapack.py in <module>()
    356 from .blas import find_best_blas_type as find_best_lapack_type
    357 
--> 358 from scipy.linalg import _flapack
    359 try:
    360     from scipy.linalg import _clapack

ImportError: /usr/local/lib/python2.7/dist-packages/scipy/linalg/_flapack.so: undefined symbol: sgegv_
```
I have reinstalled scipy,numpy,thenao,lapack,atlas.. for many times...Anyone could help me?

**Comment by FredericGodin** [comment]
I have the same issue...

**Comment by SoldierNeverDie** [comment]
me too.. anyone can help?

**Comment by SoldierNeverDie** [comment]
Ok, I solved it. I used apt-get install scipy and it work...

**Comment by fchollet** [comment]
This is just a scipy install error. I suggest using Conda, which is also what we use for Travis CI in Keras. https://github.com/fchollet/keras/blob/master/.travis.yml 

It will take care of setting up scipy for you.
