### ISSUE TITLE
print_layer_shape with keras 0.2.0?

### ISSUE THREAD

**Issue by NanditaDamaraju** [fchollet/keras#1122]
Is there a way to print the sizes of each layer as was with `print_layer_shape` in Keras 0.1.3

**Comment by fchollet** [comment]
You can just print "layer.output_shape" for any layer.

**Comment by NanditaDamaraju** [comment]
What about graphs?
For 
`model = Graph()`
model does not have a `.layer` object

**Comment by fchollet** [comment]
Just iterate on model.nodes (it's a dictionary of layers).

**Comment by NanditaDamaraju** [comment]
Got it thanks

`
for layer in  model.nodes.values():
    print layer.output_shape
`

**Comment by NanditaDamaraju** [comment]
got it thanks

`for layer in  model.nodes.values():`
