### ISSUE TITLE
 'module' object has no attribute 'relu' in keras and tensorflow

### ISSUE THREAD

**Issue by helxsz** [fchollet/keras#1126]
my keras is not built upon theano but tensorflow, for the testing , I am running a mnist_mlp.py, it outputs the error : 

  File "/usr/local/lib/python2.7/dist-packages/keras/activations.py", line 20, in relu
    return T.nnet.relu(x)
AttributeError: 'module' object has no attribute 'relu

how to solve this issue?

**Comment by fchollet** [comment]
Update Theano to the Github / master branch.

**Comment by helxsz** [comment]
@fchollet I am now switching the tensorflow for keras, why should I update theano ??
