### ISSUE TITLE
RNN does not keep but reset its hidden state

### ISSUE THREAD

**Issue by jinfengfeng** [fchollet/keras#1128]
I implement a char language model similar to Andrej Karpathy's char-rnn. In the sampling step to generate text using a trained model, if I input char one by one, I got meaningless text; but if I input a sequence of chars to predict a next char, I got similar result with Andrej. It seems the LSTM by default reset its hidden state between different input sequences. This issue causes inconvenience. And we have to input an entire sequence to get a correct output in the rnn language model text generating case. Maybe we should let rnn keep its hidden state between different input sequences, and provide a function to reset hidden state if we don't want it to keep.

Is my expression clear?

**Comment by RaffEdwardBAH** [comment]
The new `stateful` keyword should help with that, but I've been having problems with it so far in getting the model to compile. I'm also not sure how it works for predicting, as the documentation says it only applies to training in batches. I'm hoping to get answers to those questions as well.

**Comment by mynameisfiber** [comment]
@RaffEdwardBAH #1230 should take care of statefulness when predicting!

**Comment by mynameisfiber** [comment]
@RaffEdwardBAH #1230 should take care of statefulness when predicting!

**Comment by subercui** [comment]
I met the same problem. I found after `model.predict()`, the recurrent states reset. `stateful` does not help in testing. And in real time scenario, it's sometimes not possible to get the whole length of sample in prepare. Need to keep up
