### ISSUE TITLE
neural_turing_machine_copy.py does not work

### ISSUE THREAD

**Issue by IvanDrokin** [fchollet/keras#1131]
I tried running neural_turing_machine_copy.py, but get an ImportError

Using Theano backend.
Traceback (most recent call last):
  File "ntm.py", line 15, in <module>
    from keras.layers.ntm import NeuralTuringMachine as NTM
  File "/home/tesla/anaconda2/lib/python2.7/site-packages/keras/layers/ntm.py", line 10, in <module>
    from keras.utils.theano_utils import shared_zeros, alloc_zeros_matrix, shared_scalar
ImportError: No module named theano_utils

**Comment by fchollet** [comment]
I just removed this example. Its heavy dependence on no-longer existing features of `Recurrent` made it unviable. It will be reintroduced later, after it is adapted to the new `Recurrent` interface and to the abstract backend.
