### ISSUE TITLE
Why the performance of new keras reduce so much?

### ISSUE THREAD

**Issue by suixudongi8** [fchollet/keras#1133]
When i use the cnn with new keras, eg keras 0.3.0, i get a quite slow cnn training using mnist_cnn.py 2x faster than cpu version. Well, keras 0.2.0 got a almost 60x faster than cpu. 
I don't understand.
What happend in Dec 01, 2015?

**Comment by fchollet** [comment]
The example script has changed quite a bit so it's not an apples to apples comparison. 

One thing that did change on the Theano side was the removal of the `image_shape` conv2d argument. It is to be deprecated anyway.
