### ISSUE TITLE
where is the source code of 'tanh' and 'relu' activationin Theano

### ISSUE THREAD

**Issue by yiyihu** [fchollet/keras#1134]
These days,im studying activation functions,but i can't find the source code of them.

**Comment by rpinsler** [comment]
How is that related to keras? Anyway, you can find the implementations here:
https://github.com/Theano/Theano/blob/master/theano/tensor/nnet/nnet.py (includes relu)
https://github.com/Theano/Theano/blob/master/theano/tensor/basic.py (includes tanh)
