### ISSUE TITLE
Convolution2D

### ISSUE THREAD

**Issue by volvador** [fchollet/keras#1139]
I apologize in advance as my question is due to me not understanding the doc, and not to an issue in Keras. As it seems Github is the best place to ask Keras questions, I post it here instead of SO.

To simplify my problem : my training set is a series of matrices, and my target is a vector. I am trying to put a convolutional2D layer as a first layer, then a hidden dense layer, then a final Dense layer. The code below presents what I wrote, and I am obtaining a shape mismatch which I do not understand. Can you please correct and explain?

```
X, Y  = [], []
for i in range(100):
  X.append(np.random.rand(100).reshape((10, 10)))
  Y.append(np.random.randn(5).reshape((5, 1)))

X = np.array(X)
Y = np.array(Y)
NB_FILTER = 25
model = Sequential()
model.add(Convolution2D(nb_filter = NB_FILTER, stack_size=1,  nb_row=5, nb_col=5))
model.add(Flatten())
model.add(Dense(output_dim = 10, input_dim = NB_FILTER))
model.add(Dense(output_dim=5, input_dim = 10))
model.compile(loss='mse', optimizer='adam')
X = X.reshape((X.shape[0], 1, 10, 10))

model.fit(X, Y, validation_split = 0.3, batch_size=10, nb_epoch=2)
```

**Comment by suixudongi8** [comment]
You must use a param called input_shape in the first layer, like the example mnist_cnn do.
"
model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                        border_mode='same',
                        input_shape=(1, img_rows, img_cols)))
"

The right one is 
"
model.add(Convolution2D(nb_filter = NB_FILTER, stack_size=1,  nb_row=5, nb_col=5), input_shape=(1, 10, 10))
"

Which keras version are you using?
You better update your Theano and Keras.

**Comment by volvador** [comment]
Thanks a lot.
I am using keras 0.1.4 and theano 0.7.1, and unfortunately will noot be able to update soon. 
Any solution with keras 0.1.4?

**Comment by suixudongi8** [comment]
Just follow the interface of the Convolution2D and you will get the right answer.
It's in your keras src dir.

**Comment by volvador** [comment]
yes, followed it in my code above but I still had that dimension mismatch problem when I execute the code, still trying to figure out what causes it

**Comment by volvador** [comment]
Found my error, my receptive field is 5x5 so there are 36 of them for a 10x10 matrix, and as NB_filer is 25, the first dense layer should have an input_dim = 25*36=900

**Comment by suixudongi8** [comment]
it seems like this 
"
model.add(Dense(output_dim = 10, input_dim = NB_FILTER))
"
the "input_dim" should be NB_FILTER * (10-5+1) * (10-5+1).
