### ISSUE TITLE
callback, Modelcheckpoint monitor on val_acc

### ISSUE THREAD

**Issue by cheyuanl** [fchollet/keras#1144]
I think the weight should be recorded if the "val_acc" increases instead of decreases. The "val_loss" works fine!

**Comment by c0d3rman** [comment]
Are you using `mode='auto'`?
If you are, it should work - I haven't tried it myself, but the [source code](https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L263) suggests it would work.
If that doesn't work, upgrade Keras. Then, if that doesn't fix it, try to manually use `mode='max'` (which will maximize it).
For more information see the [doc](http://keras.io/callbacks/).
