### ISSUE TITLE
Combining the output of a 1D CNN encoder with other inputs and pass to a LSTM

### ISSUE THREAD

**Issue by kapil-utexas** [fchollet/keras#1151]
Hi,

I am new to Keras and Machine Learning. I am trying to feed a number of inputs alongside review/text data to a LSTM. The reviews need to pass through a 1D CNN before I can feed them to LSTM to capture spatial locality. And then the rest of the inputs with output of the CNN encoder have to be merged to be passed to a LSTM, and produce output. My questions are:
1. Is it possible to have a simple model for this?
2. How will error-propagation or weight updation takes place since the errors are to be propagated back to the CNN input for weight adjustment in CNN.
3. And I want model to do regression of a response variable instead of carrying out classification as the examples show.

I already done some pre-processing on the text reviews I have by encoding them based on random indexes assigned in a dictionary. All text vectors are of equal length and saved in a pickle file as well as the rest of the inputs.

Thanks

**Comment by PiranjaF** [comment]
You can look at https://github.com/fchollet/keras/issues/1330 for inspiration.
