### ISSUE TITLE
print_layer_shapes is gone

### ISSUE THREAD

**Issue by phreeza** [fchollet/keras#1153]
In a744b60 this highly useful function disappeared. What is the reason, and is there a chance of bringing it back?

**Comment by fchollet** [comment]
The reason is that Keras now does automatic shape inference, and you can get the output shape of a layer by calling `layer.output_shape`. 

What we could potentially bring back would be a convenience function that simply calls `output_shape` on all layers of a model.

**Comment by phreeza** [comment]
My use case is figuring out the output dimension of stacked 1D convolutional layers. As long as no input is provided, the shape along the convolutional dimension will remain unknown, or am I missing something?
