### ISSUE TITLE
Problem using masks with sequential outputs

### ISSUE THREAD

**Issue by jfsantos** [fchollet/keras#1154]
I have a network that looks like this (it's kind of a next character prediction model, but using masks, and it predicts the whole sequence of "future characters" at once):

```
model = Sequential()
model.add(Embedding(vocab_size, n_hidden, mask_zero=True))
model.add(Dropout(0.5))
model.add(LSTM(n_hidden, return_sequences=True))
model.add(Dropout(0.5))
model.add(LSTM(n_hidden, return_sequences=True))
model.add(Dropout(0.5))
model.add(TimeDistributedDense(vocab_size))
model.add(Activation('softplus'))
```

The model is compiled with categorical crossentropy as the loss function. However, when I try to train it, I get a shape mismatch error from Theano which looks like this:

```
ValueError: Input dimension mis-match. (input[0].shape[1] = 64, input[1].shape[1] = 250)
Apply node that caused the error: Elemwise{mul,no_inplace}(InplaceDimShuffle{x,0}.0, 
Elemwise{Composite{(i0 - EQ(i1, i2))}}.0)
Toposort index: 452
Inputs types: [TensorType(float64, row), TensorType(int8, matrix)]
Inputs shapes: [(1, 64), (64, 250)]
Inputs strides: [(512, 8), (250, 1)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Sum{axis=[1], acc_dtype=float64}(Elemwise{mul,no_inplace}.0)]]
```

(here, 64 is the batch size, 250 is the sequence length, and `n_hidden = 512`)

The same model works properly if I disable masking in the Embedding layer. I tried investigating the Embedding layer implementation for clues but I'm afraid I don't understand how masking works that well on Keras.

**Comment by EderSantana** [comment]
I believe the masking mechanism was changed in 0.3.  But looks at this:
`Inputs shapes: [(1, 64), (64, 250)]`
It seems that your batch is inverted for some reason. Data was not permuted to `(time, batch_size)`

**Comment by jfsantos** [comment]
The dataset is correct, as it works when I disable masking. Also, there's a `int8` matrix there, which can only be the mask (the sequences I'm using as input to the embedding layer are `int32`).

**Comment by fchollet** [comment]
The mechanism was simplified / sanitized in 0.3. 

The way it works now: the `mask` is expected to be a binary (1 or 0) float tensor of the same shape as the output of your loss function. The output of your loss function will typically be the same shape as your model output minus the last dimension.

Another thing that was simplified is weighting: now there is a one-to-one mapping between samples and weights. Weights are for *samples* only.

```python
def weighted_objective(fn):
    def weighted(y_true, y_pred, weights, mask=None):
        '''To be called only with non-zero weights.

        mask: binary
        '''
        # score_array has ndim >= 2
        score_array = fn(y_true, y_pred)
        if mask is not None:
            # mask should have the same shape as score_array
            score_array *= mask
            #  the loss per batch should be proportional
            #  to the number of unmasked sampled.
            score_array /= K.mean(mask)

        # reduce score_array to 1D
        ndim = K.ndim(score_array)
        for d in range(ndim-1):
            score_array = K.mean(score_array, axis=-1)

        if weights is not None:
            score_array *= weights
        return K.mean(score_array)
    return weighted
```

**Comment by jfsantos** [comment]
@fchollet does it mean I have to change something in my code or is this indeed a bug? I am using the masks generated by an `Embedding` layer, not creating my own masks.

**Comment by fchollet** [comment]
Then it's probably a bug. We probably need more unit tests related to
masking (we do have some, but apparently they aren't sufficient).

**Comment by hr0nix** [comment]
Any updates on this issue?
