### ISSUE TITLE
What does inner_init do ?

### ISSUE THREAD

**Issue by gaoyuankidult** [fchollet/keras#116]
Hi

I didn't find any use of inner_init in SimpleDeepRNN, did I miss it or actually we need to initialize Us using inner_init ?

**Comment by fchollet** [comment]
Beware that SimpleDeepRNN is actually an example model, as specified in the doc and the code comments. If you need a RNN for practical purposes, you should be using GRU or LSTM.

Indeed, `inner_init` should be used for the initialization of the `U` parameters. I see that wasn't the case until now (`init` used instead). I'm fixing this.

**Comment by gaoyuankidult** [comment]
@fchollet Thanks for your reply !
