### ISSUE TITLE
lstm_text_generation shuffle question

### ISSUE THREAD

**Issue by DirkWW** [fchollet/keras#1160]
As far as I understand the fit command  defaults shuffle=True. I am new to lstm's but how is the sequential information in the lstm_text_generation example used if the train data is shuffled? Thanks!

**Comment by rpinsler** [comment]
Each sample consists of T timesteps and therefore already contains sequential information. Hence, it's no problem to shuffle the samples.

**Comment by DirkWW** [comment]
Ah, clear. Thanks!
