### ISSUE TITLE
Visualise training image example

### ISSUE THREAD

**Issue by KeironO** [fchollet/keras#1161]
Hey there,

Is there any way that I can plot the vector an image loader (MNIST will be fine) after I have loaded it in? (with matplotlib or similar!)

This would be useful for verification purposes.

Thanks,

Keiron.

**Comment by rpinsler** [comment]
Why not simply use:
```
import matplotlib.pyplot as plt
import numpy as np
img = np.random.rand(100,100)
plt.imshow(img)
plt.show()
```

**Comment by KeironO** [comment]
Thank you :)

**Comment by EderSantana** [comment]
resize the MNIST vector from 784 to 28x28 and matplotlib it.
