### ISSUE TITLE
mnist_cnn.py and other examples failing taking longer than expected

### ISSUE THREAD

**Issue by jaybob20** [fchollet/keras#1165]
At commit 4b39b5f36b997868f9105d8bc76188f8837f50db "Remove deprecated code." things are acting strange. mnist_cnn.py takes 100+ times longer, also mnist_irnn.py fails with "AssertionError: Keyword argument not understood: truncate_gradient"

I have the latest pull of Theano, I'm happy to test anything.

~/src/keras/examples$ python mnist_cnn.py 
Using Theano backend.
Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled)
X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
 8832/60000 [===>..........................] - ETA: 2009s - loss: 0.7932 - acc: 0.7508

~/src/keras/examples$ python mnist_cnn.py
Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled)
X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 20s - loss: 0.2683 - acc: 0.9180 - val_loss: 0.0605 - val_acc: 0.9793

**Comment by yangnaisen** [comment]
I meet this too.

**Comment by yangnaisen** [comment]
This problem is so serious. I have spent the whole day on it after the upgrade.

**Comment by fchollet** [comment]
Sorry, but the claims do not check out.

> At commit 4b39b5f "Remove deprecated code."

This commit, as you can notice, is only *removing* files (no longer used code). It materially cannot introduce bugs or performance issues.

> also mnist_irnn.py fails with "AssertionError: Keyword argument not understood: truncate_gradient"

Factually incorrect. This example was update to remove the use of `truncate_gradient`. You can look up the exact commit --it was some time last week.

> mnist_cnn.py takes 100+ times longer

Factually incorrect. It performs sensibly the same, both on CPU and GPU. This can be easily verified by benchmarking the example with the current version of Keras and an earlier version (e.g. master from 2 weeks ago).

**Comment by jaybob20** [comment]
commit 4b39b5f36b997868f9105d8bc76188f8837f50db is also tagged 0.3.0
I created 2 keras directories one commit 4b39b5f36b997868f9105d8bc76188f8837f50db (keras) and the other 1a7c6627ac89cbbc8612ea4df59755c3109f6684 (keras.old)
I ran 'diff -rq keras keras.old' output follows:
Files keras/examples/babi_memnn.py and keras.old/examples/babi_memnn.py differ
Files keras/examples/cifar10_cnn.py and keras.old/examples/cifar10_cnn.py differ
Files keras/examples/mnist_cnn.py and keras.old/examples/mnist_cnn.py differ
Files keras/examples/mnist_mlp.py and keras.old/examples/mnist_mlp.py differ
Files keras/examples/mnist_transfer_cnn.py and keras.old/examples/mnist_transfer_cnn.py differ
Only in keras.old/examples: skipgram_word_embeddings.py
Files keras/.git/index and keras.old/.git/index differ
Files keras/.git/logs/HEAD and keras.old/.git/logs/HEAD differ
Files keras/.git/logs/refs/heads/master and keras.old/.git/logs/refs/heads/master differ
Files keras/.git/logs/refs/remotes/origin/HEAD and keras.old/.git/logs/refs/remotes/origin/HEAD differ
Files keras/.git/ORIG_HEAD and keras.old/.git/ORIG_HEAD differ
Files keras/.git/refs/heads/master and keras.old/.git/refs/heads/master differ
Files keras/keras/activations.py and keras.old/keras/activations.py differ
Only in keras/keras: backend
Files keras/keras/callbacks.py and keras.old/keras/callbacks.py differ
Files keras/keras/constraints.py and keras.old/keras/constraints.py differ
Files keras/keras/initializations.py and keras.old/keras/initializations.py differ
Files keras/keras/layers/advanced_activations.py and keras.old/keras/layers/advanced_activations.py differ
Files keras/keras/layers/containers.py and keras.old/keras/layers/containers.py differ
Files keras/keras/layers/convolutional.py and keras.old/keras/layers/convolutional.py differ
Files keras/keras/layers/core.py and keras.old/keras/layers/core.py differ
Files keras/keras/layers/embeddings.py and keras.old/keras/layers/embeddings.py differ
Files keras/keras/layers/noise.py and keras.old/keras/layers/noise.py differ
Files keras/keras/layers/normalization.py and keras.old/keras/layers/normalization.py differ
Files keras/keras/layers/recurrent.py and keras.old/keras/layers/recurrent.py differ
Files keras/keras/models.py and keras.old/keras/models.py differ
Files keras/keras/objectives.py and keras.old/keras/objectives.py differ
Files keras/keras/optimizers.py and keras.old/keras/optimizers.py differ
Files keras/keras/preprocessing/image.py and keras.old/keras/preprocessing/image.py differ
Files keras/keras/regularizers.py and keras.old/keras/regularizers.py differ
Files keras/keras/utils/layer_utils.py and keras.old/keras/utils/layer_utils.py differ
Only in keras.old/keras/utils: theano_utils.py
Only in keras.old: tests

I think the 0.3.0 tag is adding extra updates? I run 'git reset --hard 4b39b5f36b997868f9105d8bc76188f8837f50db'

**Comment by jaybob20** [comment]
Looks like Nvidia Ubunu repositories erase the cuDNN stuff on updates.
Not a keras issue, still strange at the time difference in versions. I tracked it down by looking at the output of dnn.dnn_available.msg/dnn.dnn_available().

Maybe a warning message would be helpful when keras initializes and gpu is requested and dnn.dnn_available() is Flase?

**Comment by fchollet** [comment]
> Maybe a warning message would be helpful when keras initializes and gpu is requested and dnn.dnn_available() is Flase?

The problem is that beyond this function, we have no way to know if cuDNN is *supposed* to be available. If we printed a warning message every time anyone compiled a conv2d layer, it wouldn't be a great experience for people who aren't users of cuDNN.

I believe cuDNN will become easier to install and more open in the next update, so hopefully we can just make it an automatic dependency of Keras.

**Comment by jaybob20** [comment]
Yes it would be a bother to people.
I was thinking something along the lines of in theano_backend.py. _on_gpu checks if the user set gpu in the theano config. So the user would be expecting gpu/cuDNN. When dnn is imported based on _on_gpu and dnn.dnn_available() is Flase, dnn.dnn_available.msg could be printed letting the use know there is a problem. Theano seems to silently ignore dnn failing and default to cpu, which lead to all my frustration. 

Either way, keras is working again and I'm happy... and I know something else to check it things go wonky.
