### ISSUE TITLE
How to do "return_sequences=False" for LSTM

### ISSUE THREAD

**Issue by lireagan** [fchollet/keras#1166]
Hey guys. If return_sequences=False the LSTM layer output will be size of (nb_samples, output_dim). Is the backend operation doing pooling for all of the LSTM cell's outputs likes http://deeplearning.net/tutorial/lstm.html ?

Thank you!

**Comment by jfsantos** [comment]
No, the output corresponds to the output for the last timestep (i.e., after seeing the whole input sequence).

**Comment by SoldierNeverDie** [comment]
@jfsantos Thank you.
