### ISSUE TITLE
root_mean_squared_error gives nan

### ISSUE THREAD

**Issue by entron** [fchollet/keras#1172]
I created a neural network for a regression problem. It always works fine when I optimize it with mean_absolute_error as the objective. However when I changed it to root_mean_squared_error it returns nan after a few epoch no matter which optimizer I use. Does someone where should I look for the problem?

**Comment by fchollet** [comment]
Try using MSE instead.

**Comment by entron** [comment]
Thanks for the suggestion. Indeed MSE also works withouth any problem. Do you have any insight why it works like this?

**Comment by fchollet** [comment]
I don't know, `sqrt` is supposed to be able to handle 0 values. It's a Theano bug I assume. 

In any case, RMSE should be avoided for other reasons, too. Maybe we'll remove it altogether.
