### ISSUE TITLE
Poisson loss doesn't work with Theano backend

### ISSUE THREAD

**Issue by lmcintosh** [fchollet/keras#1173]
Running latest Theano (0.7.0.dev) and latest keras, poisson_loss in objectives.py fails with an attribute error,  'module' object has no attribute '_EPSILON'.

     46 
     47 def poisson_loss(y_true, y_pred):
---> 48     return K.mean(y_pred - y_true * K.log(y_pred + K._EPSILON), axis=-1)
     49 
     50 # aliases

AttributeError: 'module' object has no attribute '_EPSILON'

**Comment by fchollet** [comment]
This is now fixed.
