### ISSUE TITLE
Development goals: December 2015

### ISSUE THREAD

**Issue by fchollet** [fchollet/keras#1174]
Now that we've completed the switch to a modular backend, here's an update on where we want to go in the near future.

## Priorities: code quality and documentation.

- better, faster unit tests with higher coverage.
- comprehensive docstrings everywhere. Switch to autogenerated, versioned documentation.
- strict enforcement of user input assumptions, and raising of helpful error messages.

## Secondary goals:

- layer output memoization.
- Graph API improvements.
- Caffe model support. There is a PR outstanding, it needs to be reviewed. Also it seems to be lacking any form of tests. Anyone interested?

**Comment by ekerazha** [comment]
* stateful RNNs? :stuck_out_tongue:

**Comment by phreeza** [comment]
I have started on improving test coverage, see #1179

**Comment by fchollet** [comment]
Ok, an update on this:

- layer memoization: done.
- docstrings everywhere and autogenerated documentation: done.
- unit test coverage: in progress!
-  Caffe support: nope. Any takers?
- Graph API improvements: unclear what it would entail. I guess that's the next thing I'll look into.
- input validation and helpful error messages: we should start with a survey of current error messages.

**Comment by ZHRbt** [comment]
>Graph API improvements: unclear what it would entail. I guess that's the next thing I'll look into.

Have you considered adding accuracy tracking to graph model training outputs? As it is, graph models can only output loss, without accuracy.

**Comment by fchollet** [comment]
Final update, as December is drawing to a close.

- layer memoization: **done.**
- docstrings everywhere and autogenerated documentation: **done.**
- unit test coverage: **done, now at 84%**. Hopefully we can get over 90% in the near future.
- input validation and helpful error messages: **considerably improved**, especially in Sequential and Graph.
-  Caffe support: **nope.**
- Graph API improvements: **nope.**

A number of other things that weren't in the roadmap were added: highway layers, support for generator inputs, etc...
