### ISSUE TITLE
from_json incompatible with older models

### ISSUE THREAD

**Issue by nicholaslocascio** [fchollet/keras#1180]
Old saved json models (old as in ~1 week old) have this argument '\"truncate_gradient\": -1', whereas new ones do not. When trying to load these older saved model structures with from_json in the latest keras, it fails with this assert:
`assert kwarg in {'input_shape', 'trainable'}, "Keyword argument not understood: " + kwarg
AssertionError: Keyword argument not understood: truncate_gradient`.

I know sometimes keras makes API-breaking changes, but was this intended? If not, can we just ignore the truncate_gradient argument here instead of Asserting?

**Comment by fchollet** [comment]
It's super easy to fix: edit your JSON file to remove that field. Done. 

One of the reasons we picked JSON as our serialization format, is that it is human-readable and human-editable.

> If not, can we just ignore the truncate_gradient argument here instead of Asserting?

This is a useful sanity check. Without it, users could pass mistyped arguments and things would not work as intended or fail mysteriously later.
