### ISSUE TITLE
Switching to autogenerated documentation.

### ISSUE THREAD

**Issue by fchollet** [fchollet/keras#1188]
We would like to start autogenerating the documentation from docstrings in the source. What are your thoughts on this, and suggestions as to what tools we should use and how this should be handled?

In particular, we would like to:
- keep the documentation source files in MarkDown
- be able to blend additional "manual" notes (stored in MarkDown files) with the autogenerated MarkDown, seamlessly
- be able to integrate with our existing static website generator (mkdocs).

**Comment by EderSantana** [comment]
The natural choice would be Sphinx and readthedocs host. But Sphinx uses RST.
There is some discussion about using Sphinx with Markdown http://stackoverflow.com/questions/2471804/using-sphinx-with-markdown-instead-of-rst#2487862

I'd really like to keep markdown too. RST can be a pain.

**Comment by EderSantana** [comment]
I just found out that readthedocs also supports markdown: http://docs.readthedocs.org/en/latest/getting_started.html#in-markdown

**Comment by fchollet** [comment]
Worse comes to worst, I image we could write our own docstring parser and Markdown generator. How difficult could it be?

**Comment by phreeza** [comment]
Mkdocs (which last time I checked is used for the keras docs?) also has the possibility to generate docs from docstrings and pull in the python api and autogenerate a structured documentation from that, using an extension: https://github.com/erichulser/mkdocs_autodoc

(I will go ahead and close the ancient #220 which I opend with this goal in mind ;-) )

**Comment by fchollet** [comment]
@phreeza seems like it could be a good option. Thanks for mentioning it! I'll look into it.

**Comment by fchollet** [comment]
Just a heads-up that we will be rolling out our own documentation generation system, which will offer us maximum flexibility. It's fairly trivial in Python, the only difficult point being the handling of inheritance data, which we will hack around.

**Comment by EderSantana** [comment]
will we use @phreeza suggestions or are you planning something custom?

**Comment by fchollet** [comment]
@EderSantana custom. Here's a sample page: https://gist.github.com/fchollet/b9d32c6c19f543d7f5b9

I don't think we'll keep the `methods` section, too redundant for layers.

The powerful thing about it, is that any change in style or functionality is now just a few lines of code away --since everything is programmatic. This will save me a ton of time.

**Comment by fchollet** [comment]
Layer docs are now autogenerated from the docstrings. http://keras.io/layers/core/

Please check it out, and let me know if you spot any issues, or think of things we should do differently.

We'll roll it out to the most of the documentation over the week-end (the core of the work is to add docstrings in all classes and methods).

**Comment by EderSantana** [comment]
@fchollet can you show me what you are using. I may like to use it elsewhere for document other projects too.

**Comment by fchollet** [comment]
@EderSantana I've just made it part of Keras (in the docs folder). 200 lines of hack, unclear if it could easily be adapted elsewhere since it is very ad-hoc.

I've extended the autogeneration business to optimizers, callbacks and models.

The remainder would just be preprocessing utils, everything is fine with manual docs.
