### ISSUE TITLE
global name 'Sequential' is not defined(after add 'from keras.models import Sequential, Graph')

### ISSUE THREAD

**Issue by meanmee** [fchollet/keras#1193]
I used the next command:
print(type(model)) 
Then it return: 'keras.models.Sequential'

And I found that in visulize_util.py:  if type(model) == Squeential

Is  type(model) == Squeential?

or should I add 'from keras.models import Sequential, Graph' in  visulize_util.py.

**Comment by rpinsler** [comment]
I don't get what your problem is. Does
```
from keras.utils.visualize_util import to_graph
from keras.models import Sequential
to_graph(Sequential())
```
work for you?

And yes, indeed:
```
>>> type(Sequential()) == Sequential
True
```

**Comment by Hemanth2396** [comment]
I am also getting the same issue regarding the "Global name sequential is not defined even i am importing model from keras also I am getting the error. While using the keras model in  the code.

model = Sequential()
