### ISSUE TITLE
How to display RGB image (e.g. cifar) in Keras?

### ISSUE THREAD

**Issue by dichld** [fchollet/keras#1198]

**Comment by rpinsler** [comment]
See #1161. For RGB, resize your vector to have shape (width, height, 3).

**Comment by dichld** [comment]
Well.. I got the problem of dimensions from matplotlib:
```
TypeError: Invalid dimensions for image data
```
Because I directly use 'imshow' the image from cifar with shape(3,32,32), so the solution to solve it is to 'transpose' it.
```
plt.imshow(x.transpose(1,2,0)) #(height,width,dim)
 ```
