### ISSUE TITLE
Is there an example to show feature extraction?

### ISSUE THREAD

**Issue by willard-yuan** [fchollet/keras#12]
Hi, fchollet,

After training the model using CNN, how to extract feature by the pre-trained model?

**Comment by fchollet** [comment]
After training a model, you can get the weights for each layer by calling the .get_weights() method. The "weights" are the numerical values of the parameters of the layer, as a list of arrays.

```python
all_weights = []
for layer in model.layers:
   w = layer.get_weights()
   all_weights.append(w)
```

You can then visualize these weights, or use them to initialize new layers (pass a "weights" argument to each layer). Check out the code itself for more detail, until there is a documentation available.

**Comment by willard-yuan** [comment]
Thanks for your help.

**Comment by fatemaaa** [comment]
how can I save the features of the last fully connected layer (before the softmak layer) of the trained model?
