### ISSUE TITLE
Problem on Keras 0.3.0 MaxPooling2D

### ISSUE THREAD

**Issue by lqchn** [fchollet/keras#1200]
At the beginning I install Theano through pip so i cannot use Activation('relu') it will throw exception, Today I have update my Theano on github, Activation('relu') does not throw exception, but there is a problem, MaxPooling2D is not work,At the beginning my program takes 50s on each epoch and accuracy will be 0.99,but now it takes long time to calculate and accuracy is too low EAT is 900s accuracy is 0.2 most.  then I use model.add(Convolution2D(8, 3, 3, border_mode='valid', subsample=(2, 2), activation='relu')) it takes little time, but accuracy is also too low, ETA is 40s accuracy is 0.5 most

how can i solve this problem?

**Comment by EderSantana** [comment]
are you using GPUs? Which example are you running?

**Comment by lqchn** [comment]
@EderSantana I have not use GPU, if I use GPU EAT is 700s if I use CPU EAT is 900s, before I update Theano it works well, ETA 50s accuracy 0.99. I want to use Activation('relu') so I update my Theano then my program goes wrong...
