### ISSUE TITLE
Is there a bug in Siamese?

### ISSUE THREAD

**Issue by mowayao** [fchollet/keras#1209]
graph = Graph()
graph.add_input(name='input1',input_shape=(1,28,28))
graph.add_input(name='input2',input_shape=(1,28,28))
graph.add_shared_node(Convolution2D(96,4,4),name="shared_conv1",inputs=['input1','input2'],merge_mode='concat')

but,it reported that:

File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 329, in add_shared_node
AttributeError: 'Siamese' object has no attribute 'set_name'

**Comment by farizrahman4u** [comment]
This error has been resolved. Reinstall Keras.

**Comment by mowayao** [comment]
Solved. Thank you so much!

**Comment by hr0nix** [comment]
I'e just updated from master, and now I'm getting the following error:

AttributeError: 'SiameseHead' object has no attribute 'set_name'

**Comment by hr0nix** [comment]
Oh, I see, there's a pending pr to fix that

**Comment by cxfneo** [comment]
where can I get more examples about function add_shared_node(……)'s usage ?
