### ISSUE TITLE
theano.gof.fg.MissingInputError when stateful

### ISSUE THREAD

**Issue by ekerazha** [fchollet/keras#1217]
This is my code

    in_out_neurons = 1
    hidden_neurons = 10
    batch_size = 10
    
    model = Sequential()
    model.add(GRU(hidden_neurons, batch_input_shape=(batch_size, 5, in_out_neurons), return_sequences=True, stateful=True))
    model.add(Dropout(0.2))
    model.add(TimeDistributedDense(in_out_neurons))
    model.add(Activation("linear"))
    model.compile(loss="mean_squared_error", optimizer="rmsprop")

and I get this error on compile

    theano.gof.fg.MissingInputError
    MissingInputError: ("An input of the graph, used to compute DimShuffle{1,0,2}(<TensorType(float32, 3D)>), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", <TensorType(float32, 3D)>)

This is the traceback

    model.compile(loss="mean_squared_error", optimizer="rmsprop")

    keras/models.py", line 372, in compile
    self.y_train = self.get_output(train=True)

    keras/layers/containers.py", line 82, in get_output
    return self.layers[-1].get_output(train)

    keras/layers/core.py", line 527, in get_output
    X = self.get_input(train)

    keras/layers/core.py", line 117, in get_input
    return self.previous.get_output(train=train)

    keras/layers/core.py", line 807, in get_output
    X = self.get_input(train)

    keras/layers/core.py", line 117, in get_input
    return self.previous.get_output(train=train)

    keras/layers/core.py", line 503, in get_output
    X = self.get_input(train)

    keras/layers/core.py", line 117, in get_input
    return self.previous.get_output(train=train)

    keras/layers/recurrent.py", line 82, in get_output
    K.set_value(self.states[i], K.eval(states[i]))

    keras/backend/theano_backend.py", line 74, in eval
    return x.eval()

    theano/gof/graph.py", line 519, in eval
    self._fn_cache[inputs] = theano.function(inputs, self)

    theano/compile/function.py", line 317, in function
    output_keys=output_keys)

    theano/compile/pfunc.py", line 526, in pfunc
    output_keys=output_keys)

    theano/compile/function_module.py", line 1777, in orig_function
    output_keys=output_keys).create(

    theano/compile/function_module.py", line 1429, in __init__
    accept_inplace)

    theano/compile/function_module.py", line 177, in std_fgraph
    update_mapping=update_mapping)

    theano/gof/fg.py", line 171, in __init__
    self.__import_r__(output, reason="init")

    theano/gof/fg.py", line 363, in __import_r__
    self.__import__(variable.owner, reason=reason)

    theano/gof/fg.py", line 477, in __import__
    r)

**Comment by fchollet** [comment]
This is now fixed.

However, one remaining gotcha with statefulness is that the RNN states won't be updated if you use `predict`, `evaluate`, etc. In other words, statefulness only works in training mode. The reason being that `predict` & co are implemented to be idempotent. Changing that would require crafting an exception specifically for RNN statefulness.

**Comment by lemuriandezapada** [comment]
which is a horrible thing, as one of the main issues with the lack of states is that you can't let your network generate stuff without redundantly iterating through your sequence over and over and over.

**Comment by kfzn** [comment]
"In other words, statefulness only works in training mode. "

Hi, Is this still the case? I am afraid "Stateful LSTM" will be much less useful if "statefulness" does not work for testing mode.
