### ISSUE TITLE
Rough edges with statefulness

### ISSUE THREAD

**Issue by ekerazha** [fchollet/keras#1221]
In https://github.com/fchollet/keras/issues/1217#issuecomment-163072470 you said

> However, one remaining gotcha with statefulness is that the RNN states won't be updated if you use predict, evaluate, etc. In other words, statefulness only works in training mode. The reason being that predict & co are implemented to be idempotent. Changing that would require crafting an exception specifically for RNN statefulness.

Also, there's a "**ValueError: operands could not be broadcast together**" exception when data size is not divisible by batch size. Maybe this should be handled gracefully. This can be particularly annoying when you set a `validation_split` parameter in `fit()`, because the final data size varies.

**Comment by ekerazha** [comment]
I updated my previous message because the error is not caused by `validation_split` itself, but there's a side effect when split data isn't divisible by batch size.

**Comment by kylemcdonald** [comment]
this issue has mostly been closed by an addition of a nice error message when you try to fit on a set of samples that is not divisible by the batch size. it would be cool to truncate the data automatically and issue a warning, but that's a design decision.

regarding the `validation_split` causing this error, i've added the following to my code to help avoid this problem:

```python
def quantize_validation_split(validation_split, sample_count, batch_size):
    batch_count = sample_count / batch_size
    return float(int(batch_count * validation_split)) / batch_count
```

then you can call `model.fit(..., validation_split=fix_validation_split(0.05, len(X), batch_size))`. but it would be cool if keras did this for you inside `fit()`.
