### ISSUE TITLE
Different results between 81787dd (9 December) and master from 19 November

### ISSUE THREAD

**Issue by jnlaia** [fchollet/keras#1223]
### Description
Something has changed in the last 20 days. I'm running a MLP with rmsprop. I'm using a highly unbalanced dataset, and setting the class_weights to be the inverse of each class frequency.

Maybe some issue with rmsprop or with class_weights?

The script I'm running is here: https://gist.github.com/jnlaia/3c2e5bf1e77986dfd51f

##### Running with the keras commit "81787dd Cleanup examples"
Using Theano backend.
Epoch 1/1
88737/88737 [==============================] - 108s - loss: 1.4438

##### Running with keras from 19 November, around 17.00 CET (sorry, no info about the commit)
Epoch 1/1
88737/88737 [==============================] - 103s - loss: 0.6875

Thanks for the help!

**Comment by fchollet** [comment]
You should not compare via the internal loss, as the way it is computed per batch with sample weights has changed since. Which is likely your issue here.

**Comment by jnlaia** [comment]
Good to know. I'm closing this issue then, as I have no other reason to believe something is wrong.
