### ISSUE TITLE
How does mask (for RNN) work in new version of keras?

### ISSUE THREAD

**Issue by ypxie** [fchollet/keras#1224]
I have just updated my keras, and a lot of changes happened.
I am trying to find the mask, which is quite extensively used in older version .
like the following:
     self.activation(x_t + mask_tm1 \* T.dot(h_tm1, u))

In theano_backend.rnn

if masking:
            # if all-zero input timestep, return
            # all-zero output and unchanged states
            switch = T.any(input)
            output = T.switch(switch, output, 0. \* output)
            return_states = []
else:
            return [output] + new_states

 It seems to me T.any(input) is kind of fusing inputs of different samples. It is quite confusing to me. And what if the actual inputs do contain zeros? Can anyone help to point out what did I miss?

**Comment by shampool** [comment]
@fchollet  @EderSantana  @wxs

**Comment by EderSantana** [comment]
For now, I believe you will have to make your batches have the same size. See discussion here: https://github.com/fchollet/keras/issues/1206

**Comment by wxs** [comment]
@shampool yeah there's definitely an issue here with the new backends. Thanks for pinging me, I'm moving over to #1206 to discuss.

**Comment by shampool** [comment]
@wxs  @EderSantana  Thanks for clarifying the thing! I will move to that thread to see the details.
