### ISSUE TITLE
UpSampling3D layer seems to tile instead of doing nearest neighbor upsampling

### ISSUE THREAD

**Issue by isaacgerg** [fchollet/keras#1226]
UpSampling2D layer appears to be doing a tile replication instead of doing nearest neighbor upsampling.

in a 2x2 case, upsampling by 2:

WX
YZ

becomes

WXWX
YZYZ

instead of
WWXX
YYZZ

**Comment by julienr** [comment]
[This notebook](https://github.com/julienr/ipynb_playground/blob/master/keras/convmnist/keras_conv_autoencoder_mnist.ipynb) demonstrates the issue @isaacgerg is talking about.
When using ``UpSampling2D``, one can see blocks in the reconstructed image. Using a custom layer works (but this is Theano-specific) :
```python
class UnPooling2D(Layer):
    """A 2D Repeat layer"""
    def __init__(self, poolsize=(2, 2)):
        super(UnPooling2D, self).__init__()
        self.input = T.tensor4()
        self.poolsize = poolsize
        
    @property
    def output_shape(self):
        input_shape = self.input_shape
        return (input_shape[0], input_shape[1],
                self.poolsize[0] * input_shape[2],
                self.poolsize[1] * input_shape[3])

    def get_output(self, train):
        X = self.get_input(train)
        s1 = self.poolsize[0]
        s2 = self.poolsize[1]
        output = X.repeat(s1, axis=2).repeat(s2, axis=3)
        return output

    def get_config(self):
        return {"name":self.__class__.__name__,
            "poolsize":self.poolsize}
```

**Comment by haseebkhan36** [comment]
when I'm using this .then it is showing error : AttributeError: Can't set the attribute "input", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.
can anyone explain me how to solve that
