### ISSUE TITLE
SimpleRNN update

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#1231]
It took me 2 whole days to figure out why my RNN was fucked. Finally I reached the step function.

``` Python
h = K.dot(x, self.W) + self.b
output = self.activation(h * K.dot(prev_output, self.U))
```

If I'm correct it should actually be

```Python
output = self.activation(h + K.dot(prev_output, self.U))
```

Which actually lets you use something other than sigmoid for your transfer function

**Comment by fchollet** [comment]
lol, you're right. This is fixed.
