### ISSUE TITLE
how to solve the exception "Invalid border mode for Convolution2D"

### ISSUE THREAD

**Issue by HeJudgin** [fchollet/keras#1232]
How to solve the exception "Invalid border mode for Convolution2D"

**Comment by jocicmarko** [comment]
Can you at least show your code and/or stack trace of the exception that you get?

**Comment by HeJudgin** [comment]
Thank you !
Just the example code inconsistent with the version of Keras,I have solved the problem.

**Comment by suixudongi8** [comment]
Now, the new Keras 0.3.0 only have 2 options.
"same" and "valid"
Maybe your error is caused by "full" mode.

**Comment by daniel-j-h** [comment]
For the record, the VGG-like convnet shown in [the examples](http://keras.io/examples/) still has `border_mode='full'`:
