### ISSUE TITLE
Masking For Image Data 

### ISSUE THREAD

**Issue by rpinsler** [fchollet/keras#1238]
Hey guys,
I'd like to mask out some values of an image. Is that currently possible? 

I haven't done very much with images before, but isn't that a quite common application which should be supported?

**Comment by lmoesch** [comment]
There are several ways to mask image data with numpy, opencv, etc.

Does something prevent you from masking your images before putting them into the net?

**Comment by rpinsler** [comment]
How would that look like? Would it be sufficient to just set the pixel values to zero?

**Comment by lmoesch** [comment]
Someone might correct me if I'm wrong, but when you look a a standard pre-activation function, wich equals X * W + b, than your layer output should equal b, when your input is 0.

So with biases initialized to 0 (wich is default) your neuron output should be zero too. Though nothing prevents your net from changing your biases...
