### ISSUE TITLE
Keras use only single thread

### ISSUE THREAD

**Issue by Jallet** [fchollet/keras#1245]
I have installed keras on a redhat 6 server, it is really a attractive framework cause it is really easy to build a deep neural network. However, I found my keras use only single thread(or single core). I ran examples given in the source code package, such as "mnist_mlp.py", and used "top" command, found the usage of CPU is 100%, never more than CPU, I have 6 cores, each with four threads, no GPU, so hope keras can make efficient use of all cores, however, it use only one thread.
I don't know whether this is caused by my theano or blas.
Below is some information about my keras:

System: redhat 6
Theano:  0.7.0
numpy: 1.10.1
scipy: 0.16.1
BLAS: atlas 3.8.4-1.el6 
keras: 0.2.0

Does anyone know how to fix this? I will appreciate any suggestion. Thanks very much.

ps: I can not make keras run with multithreads on Ubuntu 15.10 either.

**Comment by dandxy89** [comment]
Try switching the backend to Tensorflow

**Comment by Sebubu** [comment]
This enables multithreading in theano:
import theano
theano.config.openmp = True

**Comment by Jallet** [comment]
@dandxy89 I switched backend to Tensoflow by modifying ~/.keras/keras.json, but it didn't work, thank for your reply anyway, any other idea?

**Comment by Jallet** [comment]
@Sebubu I add "import theano theano.config.openmp = True" in the keras example "mnist_mlp.py", but it didn't work, thanks anyway. Any other idea?

**Comment by dandxy89** [comment]
@Jallet do any of the examples work for you, after you had switched the backend to "Tensorflow"?

**Comment by Jallet** [comment]
@dandxy89 Yes, the example works, although still with one thread, I added "{"epsilon": 1e-07, "floatx": "float32", "backend": "tensorflow"}" in ~/.keras/keras.json according to the keras document.

**Comment by Jallet** [comment]
@dandxy89 By the way, when I run "OMP_NUM_THREADS=2 python theano/misc/check_blas.py -q", the cpu usage of python is still at most 100%, never more than 100, and found only one core is being in use by command "htop", does this mean there is something wrong with my blas or openmp?
ps: If everyting is fine, when running keras' s example, should it use multi cores, or the cpu usage more than 100%

**Comment by nouiz** [comment]
if check_blas.py only use one cores, it mean your BLAS is an single core
blas. Try to change it.

**Comment by fchollet** [comment]
Try [OpenBlas](https://github.com/xianyi/OpenBLAS).

**Comment by georgegak** [comment]
import theano
theano.config.openmp = True 

then after that write OMP_NUM_THREADS=4 python script_name.py and u re good to go
