### ISSUE TITLE
Graph cycles created when stacking Bidirectional LSTM's

### ISSUE THREAD

**Issue by dscohen** [fchollet/keras#1251]
I've been trying to create a stacked BLSTM but haven't had much success in Keras. 

``` python
print('Build model...')
model = Graph()
model.add_input(name='input', input_shape=(maxlen,), dtype=int)
model.add_node(Embedding(max_features, 256, input_length=maxlen),
               name='embedding', input='input')
model.add_node(LSTM(128,return_sequences=True), 
               name='f1', input='embedding')
model.add_node(LSTM(128, go_backwards=True,return_sequences=True), 
               name='b1', input='embedding')

model.add_node(LSTM(128),
               name='f2' , inputs=['f1','b1')
model.add_node(LSTM(128, go_backwards=True),
               name='b2', inputs=['f1','b1'])

model.add_node(Dense(1, activation='sigmoid'), name='sigmoid', inputs=['f2','b2'])
model.add_output(name='output', input='sigmoid')
```

But whenever I try to compile, it will crash due to graph cycles. The traceback is pretty long so I attached it as a file. From trying to work around it, it's the 2nd BLSTM layer that causes this only when taking inputs ['f1','b1']. I can add a reshape node between the 1st and 2nd BLSTM layer, but then I get a warning about backprop not working through the graph.

[error.txt](https://github.com/fchollet/keras/files/60077/error.txt)

**Comment by fchollet** [comment]
>  it will crash due to graph cycles

The problem is almost certainly your graph connections, and not the bidirectional LSTMs. Bidirectional LSTMs work fine, we even have one in the example folder.

I can spot one issue with your code:
`input=['f2','b2']` -> that should be "inputs".

Also you can skip the last output and simply use the `create_output` argument.

**Comment by dsc381** [comment]
Right, I have no problem working with a single layer BLSTM, but the issue only arises when I'm feeding one BLSTM layer into another BLSTM layer. As it stands right now, I can't seem to avoid the graph cycle error when stacking BLSTMs.

Thanks for the tip about ```create_output``` argument, I was actually going off of the example you mentioned.

**Comment by dandxy89** [comment]
@dsc381 This compiles and runs...The only additions I made were to add ``` , merge_mode='sum')```

```python
model = Graph()
model.add_input(name='input', input_shape=(maxlen,), dtype=int)
model.add_node(Embedding(max_features, 256, input_length=maxlen),
               name='embedding', input='input')
model.add_node(LSTM(128,return_sequences=True), 
               name='f1', input='embedding')
model.add_node(LSTM(128, go_backwards=True,return_sequences=True), 
               name='b1', input='embedding')

model.add_node(LSTM(128), name='f2', 
               inputs=['f1','b1'], merge_mode='sum')

model.add_node(LSTM(128, go_backwards=True), name='b2', 
               inputs=['f1','b1'], merge_mode='sum')
               
model.add_node(Dense(1, activation='sigmoid'), 
               name='sigmoid', inputs=['f2', 'b2'])
        
model.add_output(name='output', input='sigmoid')
```

**Comment by dandxy89** [comment]
#1282

**Comment by mossaab0** [comment]
@dandxy89 I can't seem to be able to compile your code. Can you compile the following?

model = Graph()
model.add_input(name='input', input_shape=(128,), dtype=int)
model.add_node(Embedding(128, 128, input_length=128), name='embedding', input='input')

model.add_node(LSTM(128, return_sequences=True), name='f1', input='embedding')
model.add_node(LSTM(128, go_backwards=True, return_sequences=True), name='b1', input='embedding')

model.add_node(LSTM(128), name='f2', inputs=['f1', 'b1'], merge_mode='sum')
model.add_node(LSTM(128, go_backwards=True), name='b2', inputs=['f1', 'b1'], merge_mode='sum')

model.add_node(Dense(1, activation='sigmoid'),  name='sigmoid', inputs=['f2', 'b2'])

model.add_output(name='output', input='sigmoid')
model.compile('adagrad', {'output': 'binary_crossentropy'})

**Comment by dandxy89** [comment]
Hi @mossaab0 - take a look at [this](https://github.com/dandxy89/DeepLearning_MachineLearning/blob/master/Keras/Issues/Issue_1251.py) - I was able to compile both models using Theano.

I think your issue may be with the Embedding Layer - are you able to provide the error?. Can you try the script I linked to and let us know the result.

FYI - Graph() will be changing in the next few weeks.

**Comment by mossaab0** [comment]
Thanks @dandxy89 - I have just tried the first model, and it generates the following error:

    >>> max_features = 20000
    >>> maxlen = 100
    >>> batch_size = 32
    >>> embedding_size = 128
    >>> model = Graph()
    >>> # Input Layer
    ... model.add_input(name='input', input_shape=(maxlen,),
    ...                 dtype=int)
    >>> # Embedding Layer
    ... model.add_node(Embedding(max_features, embedding_size, input_length=maxlen),
    ...                name='embedding',
    ...                input='input')
                   inputs=['f2', 'b2'])
    
    model.add_output(name='output',
                     input='sigmoid')
    
    model.compile('adam',
                  {'output': 'binary_crossentropy'})
    
    >>> # First Hidden Lyaer with Bi-LSTM
    ... model.add_node(LSTM(128, return_sequences=True),
    ...                name='f1', input='embedding')
    >>> model.add_node(LSTM(128, go_backwards=True, return_sequences=True),
    ...                name='b1',
    ...                input='embedding')
    >>> # ADD DROPOUT?
    ... # Second Hidden Layer with Bi-LSTM
    ... model.add_node(LSTM(128),
    ...                name='f2',
    ...                inputs=['f1', 'b1'],
    ...                merge_mode='sum')
    >>> 
    >>> model.add_node(LSTM(128, go_backwards=True),
    ...                name='b2',
    ...                inputs=['f1', 'b1'],
    ...                merge_mode='sum')
    >>> # ADD DROPOUT / Merge?
    ... model.add_node(Dense(1, activation='sigmoid'),
    ...                name='sigmoid',
    ...                inputs=['f2', 'b2'])
    >>> 
    >>> model.add_output(name='output',
    ...                  input='sigmoid')
    >>> 
    >>> model.compile('adam',
    ...               {'output': 'binary_crossentropy'})
    
    ERROR (theano.gof.opt): SeqOptimizer apply <theano.gof.opt.EquilibriumOptimizer object at 0x7fc17dc619d0>
    ERROR (theano.gof.opt): Traceback:
    ERROR (theano.gof.opt): Traceback (most recent call last):
      File "/PATH/python2.7/site-packages/theano/gof/opt.py", line 230, in apply
        sub_prof = optimizer.optimize(fgraph)
      File "/PATH/python2.7/site-packages/theano/gof/opt.py", line 89, in optimize
        ret = self.apply(fgraph, *args, **kwargs)
      File "/PATH/python2.7/site-packages/theano/gof/opt.py", line 2144, in apply
        sub_prof = gopt.apply(fgraph)
      File "/PATH/python2.7/site-packages/theano/gof/opt.py", line 1855, in apply
        q = deque(graph.io_toposort(fgraph.inputs, start_from))
      File "/PATH/python2.7/site-packages/theano/gof/graph.py", line 1025, in io_toposort
        deps_cache=deps_cache, clients=clients)
      File "/PATH/python2.7/site-packages/theano/gof/graph.py", line 955, in general_toposort
        raise ValueError('graph contains cycles')
    ValueError: graph contains cycles

**Comment by dandxy89** [comment]
Try updating theano to the latest git version. 

I can try and run it on another machine I. The meantime

**Comment by mossaab0** [comment]
I tried again with theano 0.8.1 and then with a theano git clone: same problem.
