### ISSUE TITLE
Did I do anything wrong with this code

### ISSUE THREAD

**Issue by vinhqdang** [fchollet/keras#1263]
Hello

I really do not want to spam the Issue list, but however there is no mailing list or forum to ask about Keras :-( (if there is, please tell me).

I implemented the code as:

http://pastebin.com/BzECQR90

Basically, I have files as:
train_1, train_2, ...: each file contains a list of word, and each file corresponds to one document for training (there are ~25K files)
test_1, test_2 ..: each file contains a list of word, and each file corresponds to one document for testing (there are ~5K files)

train_number.txt: contains ~25K lines, each line is the score of the training document
test_number.txt: contains ~5K lines, like train_number.txt

I read these 4 files into variables in Python, and used *fit_on_texts* function to convert the words to frequency (similar with imdb example).

I also converted the train_number and test_number to categorical (there are 6 classes). You can see that in my code.

Then I ran the code.

The point is, the code tells me that the accuracy is 1.0 (100%), which is so great, but somehow unbelievable :-(. Of course, I hope that it is correct, but I am also afraid that I did something wrong.

If needed, I can provide objects X_train, X_test, Y_train, Y_test for reproducibility.

**Comment by dandxy89** [comment]
```model.add(Dense(1))```  =>   ```model.add(Dense(nb_classes))```

and

```model.add(Activation('sigmoid'))```  =>  ```model.add(Activation('softmax'))```

**Comment by vinhqdang** [comment]
Hi @dandxy89 , so it means that the accuracy 1.0 is wrong :-(? But I think, whatever the model is, if it can predict the unknown data correctly, the model should be okay? Am I wrong?

**Comment by around1991** [comment]
If you haven't set the number of classes to predict correctly, I wouldn't trust what your model prediction accuracy is...

Also, there's a Google Group at https://groups.google.com/forum/#!forum/keras-users

**Comment by vinhqdang** [comment]
Hi, but when I modified the code to **Dense(nb_classes)**, I met the problem as http://pastebin.com/cnpiLkeT

The error is:

*
ValueError: Input dimension mis-match. (input[0].shape[1] = 1, input[1].shape[1] = 6)*
