### ISSUE TITLE
Exporting models trained with Keras for use with another tool

### ISSUE THREAD

**Issue by atveit** [fchollet/keras#1264]
Hi, what is the best approach to export a trained convolutional neural model (i.e. matrices with weights) in Keras for use in another tool? Does it also depend on the backend used (Theano or TensorFlow)?

(The tool I am talking about is DeepLearningKit (http://deeplearningkit.org) - that will be opensourced now in December)

Best regards,
Amund Tveit

**Comment by ZHRbt** [comment]
You can get the a list of the actual values of the individual layer parameters with model.get_weights(), which you can then save for external use, for example with numpy.save().
