### ISSUE TITLE
Feature request: adding layers without overwriting weights

### ISSUE THREAD

**Issue by around1991** [fchollet/keras#1266]
Currently, when we call the `add` method on Sequential (and the `add_node` method on Graph) models, `set_previous` is called, which also calls `build`. Most of the time, this results in any existing weights on the layer being re-initialised. Thus, if we want to train a layer-by-layer autoencoder (for example), we need to store the existing weights of each encoder layer before adding them to our model, and then resetting the weights again after adding. 

It seems like adding a `overwrite_weights` argument to `Sequential.add` and `Graph.add_node` methods, which feeds into `set_previous` on both containers and layers, basically telling Keras not to call `Layer.build`, would simplify this considerably. This would make incorporating pre-trained layers into a model much easier, and wouldn't impact any existing APIs.

Thoughts?

**Comment by fchollet** [comment]
One trivial workaround for you would be to set `layer.build = lambda: None` on your existing layer. `build` will be called, and won't do anything.

**Comment by ppramesi** [comment]
Couldn't you add the layers and then apply the weight after?

```python
def modelWeightsLoader(model, filepath, loadLayers={}):
    # Loads weights from HDF5 file
    import h5py
    f = h5py.File(filepath)
    for k in range(f.attrs['nb_layers']):
        g = f['layer_{}'.format(k)]
        weights = [g['param_{}'.format(p)] for p in range(g.attrs['nb_params'])]
        if k in loadLayers:
            model.layers[loadLayers[k]].set_weights(weights)
        elif not loadLayers:
            model.layers[k].set_weights(weights)
    f.close()
```
Something like this?
