### ISSUE TITLE
Why support for input with variable length in Graph models is discarded?

### ISSUE THREAD

**Issue by rudaoshi** [fchollet/keras#1270]
I used to use add_input(ndim=x)  to feed variable length input to graph. However, the newest version request to specify the input_shape. How can I input a sequence with variable length to a graph and then send them to an Embedding layer?

Thank you very much!

**Comment by fchollet** [comment]
You can use `None` for variable dimensions. For instance, `(None, 10)` for a 10-dimensional timeseries with a variable number of timesteps.

**Comment by rudaoshi** [comment]
Thanks!

Is it a common rule for keras now?

**Comment by alyato** [comment]
@rudaoshi  Do you try it  in the new version? Thanks
