### ISSUE TITLE
Convolution1D crashes on training

### ISSUE THREAD

**Issue by farizrahman4u** [fchollet/keras#1274]
I am unable to run any example that uses Convolution1D. I am pretty sure it used to work for me(because I actually wrote one of those examples). I thought it might be some memory issue, but its  not. The models compile successfully and crash on training (it crashes the terminal, and no theano error message or  anything).

The error can be reproduced by running  imdb_cnn.py  or imdb_cnn_lstm.py. To make sure that this not a memory problem, I wrote a smaller  model and it too crashes the same way:

``` python

import keras
from keras.layers.core import*
from keras.activations import*
from keras.models import*
from keras.layers.convolutional import*
import numpy as np

model = Sequential()
model.add(Convolution1D(nb_filter=5,filter_length=3, input_shape=(10,5)))
model.compile(loss='mse', optimizer='sgd')

x_shape=list(model.input_shape)
x_shape[0] = 7

y_shape=list(model.output_shape)
y_shape[0] = 7

x=np.zeros(tuple(x_shape))
y=np.zeros(tuple(y_shape))

model.fit(x, y)
```

Output:

```
C:\Users\USER\Desktop>python conv_test.py
Using Theano backend.
Epoch 1/100
C:\Users\USER\Desktop>
```

![image](https://cloud.githubusercontent.com/assets/11006006/11812221/9b0761b6-a360-11e5-8715-9c53ebfd150d.png)

Is anyone else facing a similar issue?

**Comment by ekerazha** [comment]
It doesn't crash here. Fully updated conda setup with theano git and keras git.

**Comment by tboquet** [comment]
It also crashes for me and the tests are not passing.

**Comment by farizrahman4u** [comment]
@ekerazha Are you using Windows?

**Comment by ekerazha** [comment]
@farizrahman4u Yes, no crashes on Microsoft Windows 8.1. I tried the CPU mode, I can also try the GPU/CUDA mode.

**Comment by fchollet** [comment]
Keras is pure Python and so doesn't have the capability to crash anything. The most likely is an issue with Theano. Does conv2d work normally?

**Comment by farizrahman4u** [comment]
No.. conv2d doesnt work. So this is not related to keras.

**Comment by nouiz** [comment]
This type of issue in Theano should get an issue in Theano. I'm not able to read the keras mailing list or issue. I just made one:

https://github.com/Theano/Theano/issues/3844

I don't know when we will have the time to look at this. But we have 2 implementations on the CPU now. The old one and the new one that use blas (caffe style convolution, but on CPU):

http://deeplearning.net/software/theano/library/tensor/nnet/conv.html

Can you call theano.printing.debugprint() on the theano function that cause this crash to know which one have this problem? Disabling that version would be a workaround.
