### ISSUE TITLE
How to use GPU

### ISSUE THREAD

**Issue by lglhuada** [fchollet/keras#128]
Hi,

I read the whole documents, but I did not find any information regarding how to choose CPU or GPU apparently. Any help is more than welcome. Thanks!

Guangliang

**Comment by mthrok** [comment]
Check out the comments of examples.
https://github.com/fchollet/keras/search?utf8=✓&q=gpu

 GPU/CPU setting is handled by Theano. so you can specify in command line or setting file ~/.theanorc 
http://deeplearning.net/software/theano/tutorial/using_gpu.html

**Comment by lglhuada** [comment]
Thanks for your answers, it's clear now.
