### ISSUE TITLE
How to add a Dense following the LSTM and use the output as the next input?

### ISSUE THREAD

**Issue by dichld** [fchollet/keras#1281]
Hi, everyone!
I want to add a Dense layer after LSTM, it looks like this:
```
    Out_t              Out_t+1
     ↑                   ↑
  Dense(n)       →     Dense(n)  ...
     ↑                   ↑
   LSTM                 LSTM  
     ↑                    ↑
  Out_t-1               Out_t  
```
 that means for every single step this Dense layer will get output, and I want it as input to the next step.

BTW, the Out_t will connect to hardware, so the program will wait the new input until the operation finished.

**Comment by shampool** [comment]
TimeDistributedDense  is for this case.

**Comment by dichild** [comment]
@shampool Look, here it has a problem, if we transfer the previous output to next input, so the input to LSTM is not static. In other words, the question is how do we update the inputs after putting into the X_train or y_train?

**Comment by shampool** [comment]
Not clear what do you mean by "static" and "update the inputs after putting into the X_train or y_train?" .
Would you mind elaberating the problem in a clearer way?

**Comment by dichild** [comment]
@shampool Well.. the training data, such as X_train, which is set up in ```fit``` function, right? Normally, we will not change the X_train,which means it's ```static```. In my case, I want to use input data from robot (online learning, real-time data), which means the input data is ```dynamic``` or not static.

**Comment by dichild** [comment]
@shampool Also, the data is not received only one time. It can receive one point (one step data) in one lstm step-time.

**Comment by shampool** [comment]
I see, If I get your right, You can use stateful RNN to deal with this case.

**Comment by dichild** [comment]
@shampool I think it doesn't change the situation. When using stateful RNN, we still can not put in new data into the training data. Unless we can still hold on the cell state after finishing ```fit```, then give it new (appended) data.

**Comment by dichild** [comment]
OK, I find ```train_on_batch``` and ```statefulness``` can solve the augmented data problem.
