### ISSUE TITLE
GRU not using self.activation

### ISSUE THREAD

**Issue by mbotumbo** [fchollet/keras#1286]
GRU has a self.activation that appears to be unused. 
I would have expected it to be applied when computing hh (like it was) (Or alternatively removed from the init signature to avoid confusion.)  

```python
hh = self.inner_activation(x_h + K.dot(r * h_tm1, self.U_h)
```
was, and probably should be
```python
hh = self.activation(x_h + K.dot(r * h_tm1, self.U_h)
```

**Comment by fchollet** [comment]
Thanks for pointing this out. This is now fixed.
