### ISSUE TITLE
Which paper can I refer to about convolution1D, max-pooling1D and flatten layers?

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#1288]
In the example of  imdb_cnn, it is the architecture that convolution 1D, max-pooling 1D, flatten layers and then follows the traditional MLP. I want to study the detailed theoretical explanation, but I have read most about convolution 2D processing images like the paper of Letcun. Which paper can I refer to about convolution1D, max-pooling1D and flatten layers?  Many thanks!

**Comment by dbonadiman** [comment]
Go for the Collobert and Weston 2011 architecture or the more complete and
interesting Kalckbrenner paper A Convolutional neural network for modelling
sentences . probably I misspelled something just Google these things and
you should find what you search for. It is a quite simple architecture, the
only difference in keras is the 1Dmaxpooling that is a subsampling and not
k-maxpooling but you should easily understand it, I usually use these
models as baselines if you have problem just drop a comment.

**Comment by Imorton-zd** [comment]
HI, @dbonadiman 
If I use the merge layer in keras, which paper can I refer to and how can I represent the functions of merge layer?
