### ISSUE TITLE
Two stream CNNs for video?

### ISSUE THREAD

**Issue by KeironO** [fchollet/keras#1294]
Hey there,

I have been doing a lot of work recently with Theano in getting a two-stream CNN set up for classification purposes. Everything is working fine, but I feel that the readability of the Theano framework is nowhere near as verbose as what keras can offer me.

Does anybody have a worked example for a two-stream CNN?
Cheers,

KeironO.

Edit: Readability is important as I'm attempting to show the networks to people unfamiliar with the delicate intricacies of DL.

**Comment by fchollet** [comment]
> Does anybody have a worked example for a two-stream CNN?

It's not entirely clear what you mean by "two streams". Do you mean a CNN with two branches? You can use either a `Graph` containing 2 `Sequential` containers (each being a "stream"), or a `Merge` layer, depending on what you are trying to do.

**Comment by KeironO** [comment]
Thank you.
