### ISSUE TITLE
Element-wise max?

### ISSUE THREAD

**Issue by EpicWayne** [fchollet/keras#1296]
Hi I was wondering if keras supported element-wise max-pooling? For instance, given vectors Y=y_1,...,y_k, the result would be a vector z where the kth element in z would be the maximum of the kth elements in Y?
Thank you

**Comment by fchollet** [comment]
You can write your own layer to do that, or pass an appropriate Theano / TensorFlow expression to a `Lambda` layer.

**Comment by EpicWayne** [comment]
Thank you! So I figured out the function I want, but when I build my model I get the error "'Function' object has no attribute 'func_code'". Would you be able to tell me what I'm doing wrong? Sorry for the simple issues. My code is 

x = tensor.dmatrix('x')
elem_max = function([x], tensor.max(x,0))
model.add_node(Lambda(elem_max))

**Comment by fchollet** [comment]
> elem_max = function([x], tensor.max(x,0))

Actually you need to specify a Python function. As in, `def my_function(X): ...`

**Comment by EpicWayne** [comment]
sorry, I'm pretty new to dealing with theano, I attempted to put it inside a python function, 

x = tensor.dmatrix('x')
    elem_max = function([x], tensor.max(x,0))
    def e_max(X):
        return elem_max(X)
    model.add_node(Lambda(e_max), input = 'tanh', name='bin-softmax')

Unfortunately this yields the error

Traceback (most recent call last):
  File "RCNN.py", line 142, in <module>
    model = build_BGRU(vocab_size, max_doc_length, embedding_size)
  File "RCNN.py", line 138, in build_BGRU
    model.compile('adam',  {'output': 'binary_crossentropy'})
  File "/u/me/Desktop/keras/keras/models.py", line 602, in compile
    y_train = output.get_output(True)
  File "/u/me/Desktop/keras/keras/layers/core.py", line 1045, in get_output
    func = types.FunctionType(func, globals())
TypeError: arg 5 (closure) must be tuple

Would it be possible for you to show me an example of what I should be doing ? Thank you very much

**Comment by fchollet** [comment]
Just use a Theano expression...

```
from theano import tensor as T
def e_max(x):
   return T.max(x, 0.)
```

**Comment by EpicWayne** [comment]
This does not seem to work because coreLayers does not import tensor. After importing tensor, I still get the error
File "RCNN.py", line 134, in build_BGRU
    model.compile('adam',  {'output': 'binary_crossentropy'})
  File "/u/me/Desktop/keras/keras/models.py", line 602, in compile
    y_train = output.get_output(True)
  File "/u/me/Desktop/keras/keras/layers/core.py", line 698, in get_output
    X = self.get_input(train)
  File "/u/me/Desktop/keras/keras/layers/core.py", line 119, in get_input
    return self.previous.get_output(train=train)
  File "/u/me/Desktop/keras/keras/layers/core.py", line 608, in get_output
    X = self.get_input(train)
  File "/u/me/Desktop/keras/keras/layers/core.py", line 119, in get_input
    return self.previous.get_output(train=train)
  File "/u/me/Desktop/keras/keras/layers/core.py", line 1047, in get_output
    func = types.FunctionType(func, globals())
TypeError: arg 5 (closure) must be tuple

**Comment by jgc128** [comment]
Hi! 

I think you can use` K.max` instead of `T.max`.

```from keras import backend as K```

You can look how it is implemented here:
https://github.com/fchollet/keras/blob/80096798fc3ecbd51e8e7a9109d6344d808d03a7/tests/keras/test_models.py#L358

And it looks like right now you cannot use any other names for K, like "K_ops", for example
