### ISSUE TITLE
Why in Merge with dot model do reshape?

### ISSUE THREAD

**Issue by jeffzhengye** [fchollet/keras#1299]
The following code is from https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L551. 
I don't understand why we need reshape here. And it will cause exception. Anyone tested this?

```
        output = T.batched_tensordot(l1, l2, self.dot_axes)
        output_shape = list(self.output_shape)
        output_shape[0] = l1.shape[0]
        output = output.reshape(tuple(output_shape))
        return output
```

**Comment by farizrahman4u** [comment]
Check this out:
https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L506-L510

```python
            if len(tensordot_output.shape) == 0:
                shape = (1,)
            else:
                shape = tensordot_output.shape
            return (shape1[0],) + shape
```
It simply adds a dimension if its a scalar.

**Comment by jeffzhengye** [comment]
But I still got problem like this. Not sure why, the code seems fine to me. 

ValueError: total size of new array must be unchanged
Apply node that caused the error: Reshape{3}(Reshape{3}.0, MakeVector{dtype='int32'}.0)
Toposort index: 95
Inputs types: [TensorType(float32, 3D), TensorType(int32, vector)]
Inputs shapes: [(10, 36, 4), (3,)]
Inputs strides: [(576, 16, 4), (4,)]
Inputs values: ['not shown', array([10, 51,  4], dtype=int32)]
Outputs clients: [[MaxAndArgmax(Reshape{3}.0, TensorConstant{(1,) of 1})]]

Backtrace when the node is created:
  File "/home/jeffye/workspace/jeff/keras/keras/layers/core.py", line 552, in get_output
    output = output.reshape(tuple(output_shape))

**Comment by jeffzhengye** [comment]
Before upgrade keras, the code was good.

**Comment by jeffzhengye** [comment]
OK. this is in my code. I will close this issue.

**Comment by jeffzhengye** [comment]
Maybe this is not only my issue. After thinking about the problem a bit, this could be a inconsistency problem. 

The reshape problem I posted above, is due the input size changed in running time is different from training. However, the output_shape was inferred at training time and won't change, which cannot apply in running time.

@farizrahman4u @fchollet How do you guys think of this problem?

**Comment by farizrahman4u** [comment]
Cant see anything wrong with the code. Its most probably on your  side. Dot mode has tests and is used in the babi_memnn.py example. There is not much reshaping going on..just converting scalar to vector.

**Comment by jeffzhengye** [comment]
in babi_memnn.py example, there is no running time. I don't think the test covers runtime either. 
If we just do experiments, should be fine since we get all the data ready together. 

Imagine that when we do training, the input size is (batch_size, num_setence_in_an_article, num_of_words_in_a_sentence), on training and test these would be the same. But on running time, we don't have to do padding, num_setence_in_an_article would be way smaller. 
This is when reshape causes problems.

The problem is not necessarily to be at runtime, but would be easier for explain.

**Comment by farizrahman4u** [comment]
It is not reshape that causes the problems. The only thing the reshape does is add  an additional dim id the output is scalar. The core problem is that only batch_size can be changed between training and run times.. every other shape should remain same.. the output shape of dot merge is inferred from the output shapes of the input layers and the dot axes. You would have to pad during run time too.

**Comment by jeffzhengye** [comment]
"The core problem is that only batch_size can be changed between training and run times.. every other shape should remain same"

That's something I don't agree.

**Comment by farizrahman4u** [comment]
You could then write a custom LambdaMerge layer.. but i still dont get what your problem is..in Keras the output_shape is inferred by logic from the output shape of the previous layers and the parameters of the layer.. they are not inferred from the tensors itself..Just pad everything to fit and you will be fine.

**Comment by jeffzhengye** [comment]
@farizrahman4u Yes, I understand I could write a custom LambdaMerge layer, and output_shape is inferred by logic. 
The problem of this logic is the output_shape is not inferred in a dynamic way (I know this is hard and I don't have a way doing that). I cannot change according to the input once the model is compiled. 

Another scene that could have issue, is that what if we want to do padding for each batch, instead of whole dataset, because the dataset varies dramatically (for example the longest sentence is 1000, shortest is 1). 
If we we padding for each min-batch, we can save lots of time. So does the running time.

Do you think this makes sense? and what is your opinion? @fchollet @dbonadiman

**Comment by farizrahman4u** [comment]
What doesnt makes sense is dynamic output shape. Because the output shape of the previous layer is used to make the weights for the next layer. For e.g for a dense layer its weights are of dimensions W[input_dimxoutput_dim] and b[outpu_dim].. if the output_shape of the previous layer was varying.. it would make no sense at all.

**Comment by jeffzhengye** [comment]
For the dense layer example, I agree with you.
But the current inferring logic makes we even cannot change things like the
number of time steps.

On Fri, Dec 18, 2015 at 12:23 PM, Fariz Rahman <notifications@github.com>
wrote:

> What doesnt makes sense is dynamic output shape. Because the output shape
> of the previous layer is used to make the weights for the next layer. For
> e.g for a dense layer its weights are of dimensions W[input_dimxoutput_dim]
> and b[outpu_dim].. if the output_shape of the previous layer was varying..
> it would make no sense at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/1299#issuecomment-165845789>.
>



-- 
Jeff Ye.

**Comment by farizrahman4u** [comment]
Just like the dense layer example, the number of timesteps are used to build weight matrices for the next layer. In babi_memnn.py, the number of timesteps decides the shapes of the weights in the final layer for example..

**Comment by farizrahman4u** [comment]
This is what padding is used for.. isnt it? For sequences with variable timesteps.

**Comment by jeffzhengye** [comment]
I think padding if only for one batch until the maximum length in it.
We don't have to do that with respect to the whole dataset, which will
waste lots of time.
In my experiments very large dataset, we did this before. And it was broken
due to the inferred reshape.


On Fri, Dec 18, 2015 at 1:48 PM, Fariz Rahman <notifications@github.com>
wrote:

> This is what padding is used for.. isnt it? For sequences with variable
> timesteps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/1299#issuecomment-165867929>.
>



-- 
Jeff Ye.
