### ISSUE TITLE
Current masking approach propagates internal biases in recurrent layers

### ISSUE THREAD

**Issue by wxs** [fchollet/keras#1300]
OK so as discussed over in #1206 I think the masking needs to be revisited (I am doing this now).

As part of this investigation I've found an issue with the current masking approach. So even if my preferred solution (masks being passed around) is not accepted, we'll need to solve this.

The issue is, that an all-zero masked out timestep in an RNN still affects the next hidden state, via biases. Look at the SimpleRNN's `step` function for instance:

```
    def step(self, x, states):
        # states only contains the previous output.
        assert len(states) == 1
        prev_output = states[0]
        h = K.dot(x, self.W) + self.b
        output = self.activation(h + K.dot(prev_output, self.U))
        return output, [output]
```

Let's say we're at the first timestep, and it's masked.The input is all 0, so `h` becomes `activation(b)`.

Now we reach the second timestep, still masked. The input is is all 0. *however* `prev_output` is not all 0 anymore, but `activation(b)` from the previous timestep, so the new output becomes `activation(b + K.dot(activation(b), self.U))`, etc.

By the time we reach the first unmasked timestep we'll have a garbage `prev_output` generated by all the previous masked timesteps. What's worse is that this garbage input is a function of *how much* padding there was, so you will get different results if you later feed inputs with different amounts of padding into the RNN.

Or have I grossly misinterpreted something here?

(this is relevant to #1282 as well)

**Comment by farizrahman4u** [comment]
> By the time we reach the first unmasked timestep we'll have a garbage prev_output generated by all the previous masked timesteps. What's worse is that this garbage input is a function of how much padding there was

This seems to be pretty serious. We must reintroduce mask inside step function.
#1282  Was written with the assumption that at least left padding works with RNNs. But it doesnt. We must consider this issue as priority no.1.

**Comment by fchollet** [comment]
What are your thoughts on the following:

- handling masking via an explicit `mask` array being passed around
- `rnn` returning the last valid output for any masked step (in much the same way that it currently returns as states the last valid states). For instance, for a timeseries [1., 2., 3., masked, masked], an accumulator RNN would return [1., 3., 6., 6., 6.].

**Comment by wxs** [comment]
Yes I think this is reasonable. I was doing the first bullet point (although I'm getting pulled in several directions I'm *really* hoping to have something by the end of the week).

The second bullet point seems reasonable. I presume this is so that right-padding works with `return_sequences=False`? Has the interesting consequence that I can pad *internally* if for some reason I need to.

**Comment by fchollet** [comment]
> Yes I think this is reasonable. I was doing the first bullet point (although I'm getting pulled in several directions I'm really hoping to have something by the end of the week).

Cool, sounds good.

> I presume this is so that right-padding works with return_sequences=False?

Yes, it makes the last returned element robust to post-sequence padding. So it also makes `go_backwards` work independently of the padding side.

**Comment by shampool** [comment]
I agree that an explicit masking appoach  is better. 

But I think the following code snapt from theano_backend.rnn will prevent the invalid state from being updated and passed along the time.


for state, new_state in zip(states, new_states):
                return_states.append(T.switch(switch, new_state, state))

**Comment by wxs** [comment]
> But I think the following code snapt from theano_backend.rnn will prevent the invalid state from being updated and passed along the time

Ah I think you're write @shampool, of course it is `_step` in `theano_backend` that is passed to scan, not `step` from `recurrent.py`. I'm going to close this issue for now.

**Comment by wxs** [comment]
Incidentally, this observation I think makes passing around the mask much simpler. I believe I can get away without rewriting each recurrent layer type, and rather just apply the mask in `theano_backend.py`, thanks.
