### ISSUE TITLE
Can not save the model structure

### ISSUE THREAD

**Issue by nedved66** [fchollet/keras#1303]
I want to save the model structure through the .to_json() method, but an exception returned:
Exception: 'get_value() can only be called on a variable. If you have an expression instead, use eval().
details:
Exception                                 Traceback (most recent call last)
<ipython-input-56-e4ea706a7cfc> in <module>()
----> 1 json_string = model.to_json()

/home/nedved/anaconda2/lib/python2.7/site-packages/keras/models.pyc in to_json(self, *_kwargs)
    340         # dump model configuration to json string
    341         import json
--> 342         config = self.get_config()
    343         return json.dumps(config, *_kwargs)
    344 

/home/nedved/anaconda2/lib/python2.7/site-packages/keras/models.pyc in get_config(self, verbose)
    319                 config[p] = getattr(self, p)
    320         if hasattr(self, 'optimizer'):
--> 321             config['optimizer'] = self.optimizer.get_config()
    322         if hasattr(self, 'loss'):
    323             if type(self.loss) == dict:

/home/nedved/anaconda2/lib/python2.7/site-packages/keras/optimizers.pyc in get_config(self)
    169         return {"name": self.**class**.**name**,
    170                 "lr": float(K.get_value(self.lr)),
--> 171                 "rho": float(K.get_value(self.rho)),
    172                 "epsilon": self.epsilon}
    173 

/home/nedved/anaconda2/lib/python2.7/site-packages/keras/backend/theano_backend.pyc in get_value(x)
    338     if not hasattr(x, 'get_value'):
    339         raise Exception("'get_value() can only be called on a variable. " +
--> 340                         "If you have an expression instead, use eval().")
    341     return x.get_value()
    342 

Exception: 'get_value() can only be called on a variable. If you have an expression instead, use eval().

Could anyone tell me what's the wrong? Thx.

**Comment by jadore801120** [comment]
Same problem in Debian, python 2.7, theano 0.6.0, keras 0.2.0. 
--
File "use_swag_keras_json.py", line 190, in build_model_from_json
    print optimizer.get_config()
  File "/home/yhhuang/.local/lib/python2.7/site-packages/keras/optimizers.py", line 171, in get_config
    "rho": float(K.get_value(self.rho)),
  File "/home/yhhuang/.local/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 340, in get_value
    "If you have an expression instead, use eval().")
Exception: 'get_value() can only be called on a variable. If you have an expression instead, use eval().
--
Any help will be greatly appreciated.

**Comment by jgc128** [comment]
@jadore801120 you have an old version of theano and keras, try update it to the latest version from github: `pip install git+git://github.com/Theano/Theano.git`

**Comment by jadore801120** [comment]
Hi @jgc128 Thanks for your kindly reply! I will try to update my theano.

**Comment by dpgfoures** [comment]
I still have this error.
