### ISSUE TITLE
Is there any pre-training model?

### ISSUE THREAD

**Issue by nedved66** [fchollet/keras#1304]
Hi, I tried to find some pre-training models in keras, but I can't see any. Do I need to train a model from scratch every time? Thx.

**Comment by elbamos** [comment]
@nedved66 You can create a model for just the layer you want to pre-train, pre-train it, and extract the trained weights (e.g., with get_weights()).  Then when you make your bigger model, you pass the weights into the constructor for the relevant layers (e.g., Dense(weights = [extracted_weights])).  

It would be nice if there was a pre-training infrastructure in keras.  If anyone is interested in collaborating on it, lmk.

**Comment by aymericdamien** [comment]
There is a pre-trained model available of the VGG - 16 layers, trained on Imagenet: https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3
