### ISSUE TITLE
Extract representations for a give example.

### ISSUE THREAD

**Issue by dbonadiman** [fchollet/keras#1306]
Hello everyone, 
I would like to know if with the current backend and the graph api it is possible to extract the representation in a predeterminate node for a given example. If it is not i would like to understand how to create a fast workaround.
I have seen a post in the past that was for Sequential layers  using Theano. My request is to know if it is possible to create general API that works container-wise. 
My idea is to extract the representation of the penultimate layer of the network to stack on top other kind of classifiers. (SVM and possible Kernels for instance) So i need to extract the feature vectors from the network.
Thanks you.

**Comment by gw0** [comment]
In FAQ there are two examples for doing this using Theano backend (http://keras.io/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer).

**Comment by dbonadiman** [comment]
Oh i missed this. so i think that it is theoretically possible to compile a Keras backend function at the same way? I hope so in alternative i will go for the theano only implementation.

Thanks

**Comment by gw0** [comment]
I haven't used TensorFlow backend yet, but it should probably be similar. If you figure it out, you could post a snippet somewhere, so that others can also use it.

**Comment by dbonadiman** [comment]
In fact there are problems doing that the example in the FAQ it doesn't work out of the box but i can get the idea. I think i finished already so at soon as i'm sure of the result i will post a gist.
