### ISSUE TITLE
Kaggle Data Science Bowl

### ISSUE THREAD

**Issue by fchollet** [fchollet/keras#1312]
Who is down for a Keras deep net entry to the Data Science Bowl? https://www.kaggle.com/c/second-annual-data-science-bowl

I am not interested in the prize money, so you can have that if that's what you're into. I'm interested in seeing Keras used for state of the art applications. 

I can contribute in advising, as well as some coding. I am generally quite busy so other people would to handle most of the work. I also have code lying around for distributed hyperparameter optimization with Keras...

**Comment by meank** [comment]
I am in Right Whale competition，It iwill be helpful if you can help us， we do not require the prize money 。 just need sume suggestions from other  cattle man! We are now trying to implement Faster-RCNN and Deep Residul Network。

**Comment by meanmee** [comment]
I am interested in this competition，And i also trying to use keras to join the game。 It will be helpful
 if you'd like help me with that, bacause i am not familiar enough with keras. I need some advises both on choosing which methods and coding skills.

Thx very much!

**Comment by jocicmarko** [comment]
I would definitely like to participate/contribute.
In my master thesis I did image segmentation and feature extraction on DICOM images (CT scans of human skull). However, I did not use any machine (nor deep) learning techniques in the process (except maybe fuzzy logic and fuzzy sets), it was just extensive image processing/analysis.
Keras can definitely be used in state of the art applications, so lets get it done.

**Comment by lukedeo** [comment]
I'd be interested too, but in a similar way to @fchollet I couldn't do any crazy heavy lifting, as I'm also quite busy, but would be happy to help in idea generation + code here and there.

**Comment by meanmee** [comment]
I think we need a tutorial like this:  https://www.kaggle.com/c/second-annual-data-science-bowl/details/deep-learning-tutorial

but inplement by keras

**Comment by meanmee** [comment]
How to implement a [Fully Convolutional Networks for Semantic Segmentation](http://www.cs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf) via Keras?

**Comment by srepho** [comment]
I would be keen - happy to donate any prize money back to Keras development. The only downside is that I only have access to AWS GPU instances - but happy to pay for them.

**Comment by elbamos** [comment]
I'm very, very interested.  I looked at this a bit and it seems like a very interesting project but one I'd want to work on with a more experienced team. 

I have a fast GPU to contribute to the "cause."

**Comment by fchollet** [comment]
Ok, looks like there is enough interest to start a team : )

Our first steps should be:

- download the training data, parse it and make it available for team members as numpy arrays ready for model training (stored in a binary format, e.g. via `numpy.save()`), on S3.
- decide on a local evaluation scheme, e.g. five-fold cross-validation where we use known, fixed validation folds. This will allow us to compare approaches accurately.
- organize our workflow. We are going to need:
   - a shared private code repository. I suggest BitBucket.
   - a (private) repository of saved models, i.e. JSON files and HDF5 weight files. I suggest to use a S3 bucket.
   - a (private) repository of experiment logs: for each save model, we need to know how it was trained, and what results it achieved on our cross-validation scheme. I suggest to use a S3 bucket.
   - a repository of models predictions (probabilities) on each cross-validation fold. This allows us to optimize ensembling without having to re-run any model. I suggest to use a S3 bucket.
   - a private communication channel to share salient results. Maybe BitBucket.
- brainstorm some initial approaches.

The general timeline will be:
- brainstorm, experiment with various approaches (~2 weeks)
- identify a handful of approaches that seems the most promising
- have each willing team member works on one approach, and outputs a number of models (alongside experiment logs, saved validation predictions) (~2-3 weeks). We should figure out a way to share infrastructure costs (AWS GPUs basically). I'm willing to invest.
- ensemble results (1 week)
- submit

Please send an email to me (address is in my profile) so I have your email addresses and can add you to any shared org we end up creating.

**Comment by gravity1989** [comment]
Did something happen over this? Is there something created somewhere? I would be keen to look at the code and if possible, contribute.
