### ISSUE TITLE
Updating to 0.3.0 cause slow performance

### ISSUE THREAD

**Issue by XiaoranJin** [fchollet/keras#1318]
I updated keras from 0.2.0 to 0.3.0 using pip. Then the model training became dramatically slow.

0.2.0: each epoch costs 284s.
0.3.0: each epoch costs 6149s.

Updating keras directly from github makes it much better (635s per epoch), but still 2 times slower than 0.2.0.

My GPU is GTX 780 and My model is CNN+GRU.

**Comment by ymcui** [comment]
I have also encountered the same problem in speed. 
0.2.0 version is quite faster  (~2x @Tesla K40) than the latest keras on github.
Now, I have to revert to 0.2.0 version :(

**Comment by mundher** [comment]
I have the same issue

**Comment by fchollet** [comment]
Your post is basically information-free, this is barely a step up from "yo this sucks".

Last people reporting performance issues solved them by reinstalling Keras / Theano / cuDNN. https://github.com/fchollet/keras/issues/1250
