### ISSUE TITLE
[Question] Loading images on disk for training

### ISSUE THREAD

**Issue by davidlis** [fchollet/keras#132]
Hello
Not sure how to build the X_train and Y_train objects from a set of images sitting on disk.
Are there any examples available?
Thanks

**Comment by jramapuram** [comment]
Images are just matrices. You can use scipy or opencv, its pretty straightforward: http://scipy-lectures.github.io/advanced/image_processing/

**Comment by fchollet** [comment]
Keras has some utils that could use to do that: https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py

Take a look at `load_img`.

**Comment by aventurella** [comment]
@davidlis did you ever find examples of how to do this?
