### ISSUE TITLE
How to implement a Residul block via keras?

### ISSUE THREAD

**Issue by meanmee** [fchollet/keras#1321]
def build_residual_block_conv(num_filters, name, input_shape, input_name='x'):
    """
    Rough sketch of building blocks of layers for residual learning.
    See http://arxiv.org/abs/1512.03385 for motivation.
    """
    block = Graph()

```
block.add_input(input_name, input_shape=input_shape)

h1 = Convolution2D(num_filters, 3, 3,activation='relu', border_mode='same')
block.add_node(h1, name=name+'h1', input=input_name)
block.add_node(Dropout(0.25), name=name+'d1', input=name+'h1')

h2 = Convolution2D(num_filters, 3, 3,activation='linear', border_mode='same')
block.add_node(h2, name=name+'h2', input=name+'d1')

block.add_output(name=name+'output', inputs=[name+'h1', name+'h2'], merge_mode='sum')

return block
```

**Comment by Sebubu** [comment]
I believe you have to connect the input with the output.
Anyway, I've already tried to implement it and I failed dramatically.
* Graph has a curious issue with adding several graphs in another graph #1275
* After adding more than 50 layers to a graph, keras gets really slow (not just the compilation). I guess add_node calculates the output_shape recursively and that kills the performance of it.

My code:
https://github.com/Sebubu/mushroom_crawler/blob/master/mushroom/ResidualNet.py

**Comment by meanmee** [comment]
Thanks very much！

**Comment by Sebubu** [comment]
No, like I said above it didn't work so far. Feel free to experiment with the code.

**Comment by meanmee** [comment]
I think the shortcut is not a Convolutional layer, but a linear layer. In your code you modified it as convolutional. Now i want to replace it with a linear layer ,what code should I modified? Sorry , I am not familiar with keras.

**Comment by Sebubu** [comment]
paper proposes two options: either linear or convolution and believe me a convolution is easier. Otherwise you have to handle with reshaping and so on...

**Comment by meanmee** [comment]
It seems like ZeroPadding2D AveragePooling2D or BatchNor can not add to a graph as a node. I modified your code, The Graph can be generated but can work when apply to real cifar-10 data:

from keras.layers.convolutional import Convolution2D, MaxPooling2D, ZeroPadding2D, AveragePooling2D
import sys
from keras.models import Sequential, Graph
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D, AveragePooling2D

sys.setrecursionlimit(10000)

def cinput_shape(graph):
    shape = list(graph.output_shape)
    shape.pop(0)
    return shape

def ConvB(input_shape, nb_filter, nb_row, nb_col, subsample=(1, 1)):
    g = Graph()
    g.add_input("input", input_shape)
    g.add_node(Convolution2D(nb_filter,nb_row,nb_col,subsample=subsample, border_mode='same', activation='relu'),"conv1", "input")
    g.add_node(Dropout(0.2),"d", "conv1")
    g.add_output("output", "d")
    return g

def Zero(input_shape, pad=(1,1)):
    g = Graph()
    g.add_input("input", input_shape)
    g.add_node(ZeroPadding2D(pad),"zero","input")
    g.add_output("output", "zero")
    return g

def time_block2(input_shape, nb_filters, nb_blocks):
    convs = []
    last_shape = input_shape
    for i in range(nb_blocks):
        c = block2(last_shape,nb_filters)
        last_shape = cinput_shape(c)
        convs.append(c)

    g = Graph()
    g.add_input("input", input_shape)
    last_name = "input"
    for i in range(len(convs)):
        name = "conv" + str(i)
        g.add_node(convs[i],name,last_name)
        last_name = name
    g.add_output("output",last_name)
    return g

def block_downsample(input_shape, nb_filters):


    subsample = (2,2)

    g = Graph()
    g.add_input("input",input_shape)

    zero = Zero(input_shape,(0,0))
    conv1 = ConvB(cinput_shape(zero), nb_filters, 3, 3, subsample=subsample)
    conv2 = ConvB(cinput_shape(conv1), nb_filters, 3, 3)
    shortcut = ConvB(input_shape,nb_filters,1,1,subsample=subsample)

    g.add_node(zero,"zero","input")
    g.add_node(conv1,"conv1","zero")
    g.add_node(conv2,"conv2","conv1")
    g.add_node(shortcut,"shortcut","input")
    g.add_output("output", inputs=["conv2", "shortcut"], merge_mode="sum")

    return g

def block2(input_shape, nb_filters):

    g = Graph()
    g.add_input("input",input_shape)

    zero = Zero(input_shape,(0,0))
    conv1 = ConvB(cinput_shape(zero), nb_filters, 3, 3)
    conv2 = ConvB(cinput_shape(conv1), nb_filters, 3, 3)

    g.add_node(zero,"zero","input")
    g.add_node(conv1,"conv1","zero")
    g.add_node(conv2,"conv2","conv1")
    g.add_output("output", inputs=["conv2", "zero"], merge_mode="sum")

    return g

def get_model(input_shape, nb_residual1, nb_residual2, nb_residual3):
    conv1 = ConvB(input_shape, 16, 3, 3)

    residual1 = time_block2(cinput_shape(conv1), nb_filters=16, nb_blocks=nb_residual1)

    residual1_to_residual2 = block_downsample(cinput_shape(residual1), nb_filters=32)
    residual2 = time_block2(cinput_shape(residual1_to_residual2), nb_filters=32, nb_blocks=nb_residual2)

    residual2_to_residual3 = block_downsample(cinput_shape(residual2), nb_filters=64)
    residual3 = time_block2(cinput_shape(residual2_to_residual3), nb_filters=64, nb_blocks=nb_residual3)

    g = Graph()
    g.add_input("input",input_shape)
    g.add_node(conv1, "conv1", "input")

    g.add_node(residual1, "residual1", "conv1")

    g.add_node(residual1_to_residual2, "residual1_to_residual2", "residual1")
    g.add_node(residual2, "residual2", "residual1_to_residual2")

    g.add_node(residual2_to_residual3, "residual2_to_residual3", "residual2")
    g.add_node(residual3, "residual3", "residual2_to_residual3")

    g.add_output("output", "residual3")

    return g

def create_31_layer(input_shape):
    print "create model"
    return get_model(input_shape, 5, 4, 4)

input_shape = (3,32,32)

model = create_31_layer(input_shape)
for n in model.nodes:
    node = model.nodes[n]
    print n + str( node.output_shape)

**Comment by Sebubu** [comment]
issue #1275 describes your exception. The problem is I have not found a solution till now.

**Comment by keunwoochoi** [comment]
Is it like building a wrapper that would enable implementing residual net by adding several residual block, i.e. 
```
mode.add(residual())
model.add(residual())
```
? Then it would be so cool. I think the problem with BN and `graph` was resolved.

**Comment by courageon** [comment]
I implemented a residual class based on the Regularizer class. Not sure if this is the correct way to do it or not, but it *seems* to work. Also slows down training to a crawl.

For the life of me this thing will not format right, so sorry for the awful formatting...

***CODE START***

from keras.layers.core import Layer
from keras.regularizers import Regularizer

class ResidualRegularizer(Regularizer):
    def __init__(self):
		pass

    def set_layer(self, layer):
        self.layer = layer

	#When asked for the loss, just return 0 to prevent back-prop to the previous layers
	def __call__(self, loss):
		return 0

	def get_config(self):
		return {"name": self.__class__.__name__}
		
class Residual(Layer):
    """
        Layer that passes through its input unchanged, and applies no back propagation.
		It is simply a forward-propagated link intended for residual linking.
    """
    def __init__(self, **kwargs):
        super(Residual, self).__init__(**kwargs)
        residual_regularizer = ResidualRegularizer()
        residual_regularizer.set_layer(self)
        self.regularizers = [residual_regularizer]

    def get_output(self, train=False):
        return self.get_input(train)

    def get_config(self):
        config = {"name": self.__class__.__name__}
        base_config = super(Residual, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

***CODE END***

Then you implement it like...
model.add_node(Dense(1536, activation='relu'), merge_mode='concat', concat_axis=-1, name='class_dense1', inputs=['flatten_embed','flatten'])
model.add_node(Dense(1536, activation='relu'), name='class_dense2', input='class_dense1')
model.add_node(Dense(1536, activation='relu'), name='class_dense3', input='class_dense2')
model.add_node(Residual(), name='class_residual', input='class_dense1')
model.add_node(Dense(vocab_size, activation='softmax'), name='class_softmax', merge_mode='sum', inputs=['class_residual','class_dense3'])

Again sorry for the terrible formatting...

It's not so much a residual layer as it is just a way to grab a previous layers outputs without back propagating. Then you can take that output and merge it, creating your 'residual'. 

Also note this method only works if all the layers are the same size.

**Comment by sergeyf** [comment]
Has anyone given this a shot? https://github.com/ndronen/modeling/blob/master/modeling/residual.py

**Comment by courageon** [comment]
I've seen that code but I don't understand how it's supposed to be used. It looks like it's building the entire network, so it may be more of a factory? But, maybe we can use the Identity class in that code as a replacement for the Residual class in my example. Could be worth a shot if it's any faster. I'll give it a try and report back. 
Thanks sergeyf!

**Comment by sergeyf** [comment]
I think you can just use the blocks it returns in other models. So:

```
s = Sequential()
s.add( build_residual_block('resblock1', (100,), 2, n_skip=2) )
s.add( build_residual_block('resblock2', (100,), 2, n_skip=2) )
```
etc.

**Comment by courageon** [comment]
Ah, ok, I see it now. Thanks for the example! :)

**Comment by keunwoochoi** [comment]
Worth to check out this [comment](https://github.com/ShaoqingRen/faster_rcnn/issues/47#issuecomment-168357314), I think the code @sergeyf mentioned has the same mistake. ReLU() should be applied after merge I guess - according to the comment. What do you think?

**Comment by keunwoochoi** [comment]
https://github.com/keunwoochoi/residual_block_keras
I opened a repo for my residual block implemented in Keras. 
I put many comments in the files so it would be easy to understand. However I'm not sure if it's correct.

**Comment by cmishra** [comment]
@keunwoochoi I think your observation is correct. Additionally, I walked myself through the logic of your code and it seems to be correct (albeit I haven't used it, that's for tomorrow). I did have a couple questions:

- Your current implementation would only work if kernel_sizes = (3, 3) correct? I say this because of [line 63](https://github.com/keunwoochoi/residual_block_keras/blob/master/residual_blocks.py#L63). 
- Any reason you used max pooling for subsampling instead of increasing the stride? Admittedly it makes more sense to me then setting stride=2 on a (1, 1) filter, but I'm curious whether you have a source on this. Aside: I'd also be curious to see whether average pool would work better than max pooling and stride=2 since intuition would suggest that it would better resemble the original x. 
- Any reason you implement the main path in the residual block internally instead of accepting it as a parameter? This would simplify and make more robust the implementation. I see two potential thorns: automatically detecting necessary subsampling/dimension modifications, and deep copying a Keras layer. I'm fairly confident the first can be easily resolved. Not sure about the latter. Do Keras layers work with [deepcopy](https://docs.python.org/2/library/copy.html)?

**Comment by keunwoochoi** [comment]
Thanks, @cmishra. 
* Oh, yes, there's a mistake. It used to assume (3,3) input but now it should be (1,1) rather than `(kernel_row-1)/2`. I'll update it. 
* It seems a different story, but does (1,1) convolution with stride>1 really work? I'm not sure it's okay to do when the `stride > kernel size`. I chose MP than increasing the stride as in my case `stride > kernel size` for some layers.
* Average pooling: true, I once implemented it but not tested yet. Your saying supports the idea as well, I'll try it soon after the networks seems to work.
* main path - I think it's natural and convenient but haven't thought about separate the main path and the shortcut in different function. Wouldn't it be more complex to use? 

I'll also update [line58](https://github.com/keunwoochoi/residual_block_keras/blob/master/residual_blocks.py#L58) to [line81](https://github.com/keunwoochoi/residual_block_keras/blob/master/residual_blocks.py#L81) to make it clear (the shortcut convolution part).

(PS. At #1910 I added an issue for it but here people can get notifications.)

**Comment by keunwoochoi** [comment]
Now my networks seems to start to learning something meaningful features - not sure yet though. I once added usual classifier - `flatten() - maxout() - BN - maxout ().. ` but now I change it to an almost fully convolution architecture as in the original ResNet paper, removed all dropouts, change `MaxPooling` to `AveragePooling` in the shortcut path. Still not sure which is critical and which is not, but worth noting. I'll update more.

**Comment by cmishra** [comment]
@Sebubu with #1387 does your code work? I'd try to run it myself, but I'm traveling and my personal laptop doesn't have the processing.

**Comment by sergeyf** [comment]
There's a more recent (apparently) improved version of the residual block:

http://arxiv.org/pdf/1603.05027v1.pdf

**Comment by raghakot** [comment]
I recently implemented it in Keras using the new functional API: https://github.com/raghakot/keras-resnet

**Comment by keunwoochoi** [comment]
Great, I also updated my residual network implementation with Keras 1.0 API and the author's new paper that @sergeyf mentioned: https://github.com/keunwoochoi/residual_block_keras .

**Comment by codingneo** [comment]
keunwoochoi, I try to use your residual_block_keras, but I encountered the following error
```
Traceback (most recent call last):
  File "example.py", line 151, in <module>
    model = get_residual_model()
  File "example.py", line 120, in get_residual_model
    residual_blocks = design_for_residual_blocks(num_channel_input=128)
  File "example.py", line 100, in design_for_residual_blocks
    subsample=pool_sizes[conv_idx]
  File "/usr/local/lib/python2.7/site-packages/keras/models.py", line 145, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 1922, in call
    output_tensors, output_masks, output_shapes = self.run_internal_graph(inputs, masks)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2064, in run_internal_graph
    output_tensors = to_list(layer.call(computed_tensor, computed_mask))
  File "/usr/local/lib/python2.7/site-packages/keras/layers/normalization.py", line 116, in call
    raise Exception('You are attempting to share a '
Exception: You are attempting to share a same `BatchNormalization` layer across different data flows. This is not possible. You should use `mode=2` in `BatchNormalization`, which has a similar behavior but is shareable (see docs for a description of the behaviour).
```

Do you have any suggestion?

**Comment by keunwoochoi** [comment]
Hi @codingneo, it was fixed yesterday, https://github.com/keunwoochoi/residual_block_keras/commit/a35fe6fb8e356cea8a3e491d24beefc8a996ce05. Pull the repo again and give it a try!

**Comment by codingneo** [comment]
Hi @keunwoochoi I actually did similar fix as your new changes by using mode=2 for BatchNormalization layer. But with mode=2 in BatchNormalization layer, the training procedure will generate NaN loss as follows

> Train on 60000 samples, validate on 10000 samples
> Epoch 1/20
>   1088/60000 [..............................] - ETA: 13519s - loss: nan - acc: 0.1158
>   1152/60000 [..............................] - ETA: 13522s - loss: nan - acc: 0.1137

Is it something need to be cautious?

**Comment by keunwoochoi** [comment]
Is it the result of running `example.py`? 
With Theano backend it’s working well. Had an error with TensorFlow though. 

```
Epoch 1/20
 5760/60000 [=>............................] - ETA: 349s - loss: 0.5634 - acc: 0.8210
```

**Comment by codingneo** [comment]
@keunwoochoi Yes, the result is getting from running example.py.
I am in mac using then backend.

**Comment by Darthholi** [comment]
For other googlers like me - there IS now a way to do residual connection in keras - 
https://keras.io/getting-started/functional-api-guide/

```
from keras.layers import Conv2D, Input

# input tensor for a 3-channel 256x256 image
x = Input(shape=(256, 256, 3))
# 3x3 conv with 3 output channels (same as input channels)
y = Conv2D(3, (3, 3), padding='same')(x)
# this returns x + y.
z = keras.layers.add([x, y])
```

x,y being two consecutive layers

**Comment by MarviB16** [comment]
But how would i add it to my model? (Sorry im pretty new to Keras)
`model.add(z)`
Doesn't work, obviously
