### ISSUE TITLE
JZS1-3 and forget_bias_init in master

### ISSUE THREAD

**Issue by viksit** [fchollet/keras#1322]
I was looking at the code, and it looks like the forget_bias_init param in the GRU class takes over the functionality that was previously in the JZS1 classes?

Could you explain what the np.ones() are doing and what the rationale is?

Thanks!

**Comment by arodland** [comment]
No, they're unrelated except that the JZS paper also mentions the need for forget bias in LSTMs. The "JZS" class of layers was much closer to GRU than LSTM.

From the [JZS paper](http://www.jmlr.org/proceedings/papers/v37/jozefowicz15.pdf):

> There is an important technical detail that is rarely mentioned in discussions of the LSTM, and that is the initialization of the forget gate bias b<sub>f</sub>. Most applications of LSTMs simply initialize the LSTMs with small random weights which works well on many problems. But this initialization
effectively sets the forget gate to 0.5. This introduces a vanishing gradient with a factor of 0.5 per timestep, which can cause problems whenever the long term dependencies are particularly severe (such as the problems in Hochreiter & Schmidhuber (1997) and Martens & Sutskever (2011)). 

> This problem is addressed by simply initializing the forget gates b<sub>f</sub> to a large value such as 1 or 2. By doing so, the forget gate will be initialized to a value that is close to 1, enabling gradient flow. This idea was present in Gers et al. (2000), but we reemphasize it since we found many practitioners to not be familiar with it. 

> If the bias of the forget gate is not properly initialized, we may erroneously conclude that the LSTM is incapable of learning to solve problems with long-range dependencies, which is not the case.

**Comment by arodland** [comment]
Keras uses 1 because an initialization of `ones` is readily available.
