### ISSUE TITLE
How Can I do a deconvolution with keras?!?!?!?!

### ISSUE THREAD

**Issue by gtshs2** [fchollet/keras#1323]
I want to create Stacked Convolutional Auto Encoders.
I don't know how to do a deconvolution.
For example, If I do convolution with 32(Filter Size)x7x7 filter on 1x28x28 input image, then the output will be 32x22x22. And I want to do a deconvolution it to 1x28x28 image.
How Can I do this one?! 

Thank you in advance!

**Comment by meanmee** [comment]
``class Deconvolution2D(Layer):

    input_ndim = 4

    def __init__(self,ratio,**kwargs):
        self.ratio = ratio
        super(Deconvolution2D, self).__init__(**kwargs)

    @property
    def output_shape(self):
        return (self.input_shape[0],self.input_shape[1],
                self.input_shape[2]*self.ratio,self.input_shape[0]*self.ratio)

    def get_output(self, train=False):
        X = self.get_input(train=False)
        X = K.expand_dims(X, -1)
        X = K.permute_dimensions(X, (0, 2, 1, 3))
        output = bilinear_upsampling(X,self.ratio,batch_size=self.input_shape[0],
                                     num_input_channels=self.input_shape[1],use_1D_kernel=False)
        return output

    def get_config(self):
        config = {'name': self.__class__.__name__,
                  'ratio':self.ratio}
        base_config = super(Deconvolution2D, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))``

I am trying， but there are some thing confusing me. I just add the Bilinear interpolation as the paper 'Fully Convolutional Layer for Semantic Segmentation' did. Is it right?
