### ISSUE TITLE
Reusing only some layers in previously trained network

### ISSUE THREAD

**Issue by PiranjaF** [fchollet/keras#1344]
I'd like to reuse only a part of a previously trained network. The way I currently do this is using the code below, which seems to work fine. Is this a proper way to do it or could I potentially mess up some internal part of the code?

```python
from keras.models import model_from_json
from keras.layers.core import Dense, Activation

# Loading and cutting
model = model_from_json(open('my_model_architecture.json').read())
model.load_weights('my_model_weights.h5')
model.layers = model.layers[0:15]

# Adding new layers
model.add(Dense(2))
model.add(Activation('softmax'))
```

**Comment by farizrahman4u** [comment]
It will work fine. Nothing will be messed up.

**Comment by PiranjaF** [comment]
Thanks for the quick reply!
