### ISSUE TITLE
Categorical Graph Model - Show Accuracy

### ISSUE THREAD

**Issue by tywp1115** [fchollet/keras#1345]
There is no show_accuracy for the Graph model (Graph().fit(...)). Should there be? It is in the base class (Model().fit(...)) has one and Sequential has one too.

Is accuracy not valid for the Graph() structure?

I am using the objective categorical_crossentropy. [0, 1, 0]. It says show_accuracy not supported.

**Comment by stevenxxiu** [comment]
:+1:, there are also other methods which exist for the sequential but not for the graph model, like `predict_proba()`, `predict_classes()`.

**Comment by arisliang** [comment]
why is this closed? Sounds like there should be show_accuracy for graph model.
