### ISSUE TITLE
TypeError about ‘dot_axes’ while running babi_memnn.py

### ISSUE THREAD

**Issue by medrifter** [fchollet/keras#1346]
Like this below, who knows why, thanks
Extracting stories for the challenge: single_supporting_fact_10k
-
Vocab size: 22 unique words
Story max length: 68 words
Query max length: 4 words
Number of training stories: 10000
Number of test stories: 1000
-
Here's what a "story" tuple looks like (input, query, answer):
([u'Mary', u'moved', u'to', u'the', u'bathroom', u'.', u'John', u'went', u'to', u'the', u'hallway', u'.'], [u'Where', u'is', u'Mary', u'?'], u'bathroom')
-
Vectorizing the word sequences...
-
inputs: integer tensor of shape (samples, max_length)
inputs_train shape: (10000, 68)
inputs_test shape: (1000, 68)
-
queries: integer tensor of shape (samples, max_length)
queries_train shape: (10000, 4)
queries_test shape: (1000, 4)
-
answers: binary (1 or 0) tensor of shape (samples, vocab_size)
answers_train shape: (10000, 22)
answers_test shape: (1000, 22)
-
Compiling...
Traceback (most recent call last):
  File "babi_memnn.py", line 170, in <module>
    dot_axes=[(2,), (2,)]))
TypeError: __init__() got an unexpected keyword argument 'dot_axes'

**Comment by fchollet** [comment]
Keras: You Need To Update It (tm)

**Comment by medrifter** [comment]
yes,i update it and worked, but something other happend:
Traceback (most recent call last):
  File "babi_memnn_fl.py", line 204, in <module>
    validation_data=([inputs_test, queries_test, inputs_test], answers_test))
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 581, in fit
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 239, in _fit
  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 365, in __call__
  File "/usr/lib/python2.7/site-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/usr/lib/python2.7/site-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
ValueError: Shape mismatch: x has 68 cols (and 32 rows) but y has 132 rows (and 32 cols)
Apply node that caused the error: Dot22(Alloc.0, <TensorType(float32, matrix)>)
Inputs types: [TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(32, 68), (132, 32)]
Inputs strides: [(272, 4), (128, 4)]
Inputs values: ['not shown', 'not shown']

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by fchollet** [comment]
Theano: You Need To Update It Too (tm)
