### ISSUE TITLE
Siamese and multiple Merge - problem with save/load weights

### ISSUE THREAD

**Issue by jgc128** [fchollet/keras#1349]
Hi!

The following script is failing to load weights with an error `AssertionError: Provided weight array does not match layer weights (2 layer params vs. 0 provided weights)` 
I am using the lastest version of Keras from GitHub

```
from keras.models import Sequential
from keras.layers.core import Layer, Dense, Merge, add_shared_layer

model_weights_filename = 'test_weights.hdf5'

input1 = Sequential()
input1.add(Layer(input_shape=(10,)))

input2 = Sequential()
input2.add(Layer(input_shape=(10,)))

add_shared_layer(Dense(5), [input1, input2])

merge_sum = Sequential()
merge_sum.add(Merge([input1, input2], mode='sum'))

merge_mul = Sequential()
merge_mul.add(Merge([input1, input2], mode='mul'))


dense = Sequential()
dense.add(Merge([merge_mul, merge_sum], mode='concat'))

dense.save_weights(model_weights_filename, overwrite=True)
dense.load_weights(model_weights_filename)
```

Merging without `merge_mul` and `merge_sum`  only with the last merge works fine. 

I think it has something to do with the parameters that the merge layers is getting from the shared layer - maybe it gets it twice...

**Comment by fchollet** [comment]
@farizrahman4u any thoughts on this?

**Comment by farizrahman4u** [comment]
@fchollet This is a general Keras bug.. got nothing to do with Siamese layer.

**Comment by farizrahman4u** [comment]
@fchollet Here is a script that doesnt use `Siamese` layer but still fails.
```
from keras.models import Sequential
from keras.layers.core import Layer, Dense, Merge

input1 = Sequential()
input1.add(Dense(input_dim=10, output_dim=5))

input2 = Sequential()
input2.add(Dense(input_dim=10, output_dim=5))

merge_sum = Sequential()
merge_sum.add(Merge([input1, input2], mode='sum'))

merge_mul = Sequential()
merge_mul.add(Merge([input1, input2], mode='mul'))

model = Sequential()
model.add(Merge([merge_mul, merge_sum], mode='concat'))

w=model.get_weights()
model.set_weights(w)
```

**Comment by jgc128** [comment]
It's strange... I tested it and it turns out that in your script `save_weights` and `load_weights` work, but `get_weights` and `set_weights` do not.

**Comment by farizrahman4u** [comment]
@jgc128 So you mean the code I posted above works for you?

**Comment by jgc128** [comment]
@farizrahman4u no, it doesn't work, but when I replaced `get_weights` and `set_weights` with `save_weights` and `load_weights` it worked. 

But save/load_weights use get/set, right? 

I tried to see how many weights it is saving and loading and it looks like it is saving, for example, 12 parameters but loading 24 parameter for the same layer. Because of it the next layer does not have enough parameters. I may be wrong though...

**Comment by farizrahman4u** [comment]
save/load doesnt use get/set I think.. because of backward compatibility issues.. not sure though. Let me check.

**Comment by ymcui** [comment]
hi, there. Have you solved this problem?
i've also meet this problem, it seems that if we place 'Merge' layer inside another 'Merge' layer, the params cannot be correctly loaded.  #1508

**Comment by jgc128** [comment]
Hi @ymcui 

as I remember it worked fine with `Graph` model - probably you can use this model as a temporary solution.

**Comment by issey173** [comment]
Hi,

I am having a similar issue where I'm merging a Sequential model with a VGG-like architecture with all its weights frozen and another Sequential model with an embedding layer to process text (much like the [image captioning example](http://keras.io/getting-started/sequential-model-guide/) in the keras docs). I've trained the model and saved the weights using the [ModelCheckpoint callback](http://keras.io/callbacks/#modelcheckpoint) but when I try to load them in the same exact model (previously saved with model.to_json() and loaded with model_from_json()) I get the following error: 

`AssertionError: Provided weight array does not match layer weights (2 layer params vs. 0 provided weights)
`

This AssertionError is thrown when setting the weights to the Merge layer. Is there any solution that does not imply changing all my code to use the new Functional API instead of the Sequential model?

Thanks!

**Comment by divamgupta** [comment]
Hi,

Any updates on this. I have trained a model and it took a lot of time and I can't retrain the model. Any solutions?

Thanks

**Comment by abossenbroek** [comment]
Same issue. Any update on this?

**Comment by saroufimc1** [comment]
@farizrahman4u @fchollet 
Any update? I am still having an issue when loading a saved Keras model, even when using functional API...
