### ISSUE TITLE
Wrong precision when loading weights

### ISSUE THREAD

**Issue by ivodopyanov** [fchollet/keras#1353]
Hello.
I've got into troublesome behavior recently.
I trained model on one machine and saved it weights into .h5 file. I've loaded them on another computer - it was alright.
But when I tried to load them on third, resulting data had numpy.float32 type instead of numpy.float64. Because of that model predicted worse than expected.

That computer has 64-bit CPU.
sys.float_info shows same numbers as on first machine
np.finfo(np.float).precision shows 15

UPD:
I found the problem. I was saving weights in keras 0.2.0 and was loading them in keras 0.3.0
Probably, there should be done something to support compability?

**Comment by fchollet** [comment]
You can set the precision that Keras uses by modifying `~/.keras/keras.json`.
