### ISSUE TITLE
Undefined variable raw_input.

### ISSUE THREAD

**Issue by benigls** [fchollet/keras#1356]
The variable `raw_input` on this [link](https://github.com/fchollet/keras/blob/16675b98c0d47c1f58f42ada534ff52721aa085e/keras/models.py#L753) doesn't exist.

```
get_input = input
if sys.version_info[:2] <= (2, 7):
    get_input = raw_input
    overwrite = get_input('[WARNING] %s already exists - overwrite? '
                          '[y/n]' % (filepath))
```

**Comment by benigls** [comment]
And also in [here](https://github.com/fchollet/keras/blob/16675b98c0d47c1f58f42ada534ff52721aa085e/keras/models.py#L1204).

**Comment by julienr** [comment]
`raw_input` was renamed to `input` in python3. The lines you mention are specifically only using `raw_input` for python < 2.7, in which it should be available.

What version of python are you using ? Could you post a full traceback of the error you're seeing ?

**Comment by benigls** [comment]
I'm using python3. I saw the error when I opened it on my editor with [flake8](https://github.com/pycqa/flake8) linter along with `line too long errors`.

Here's the error message.
```
.../keras/keras/models.py|765 col 29 error| undefined name 'raw_input' [F821]
```

**Comment by julienr** [comment]
Then I think it's a false positive from flake8 being unable to figure out that this is for python < 2.7.

**Comment by benigls** [comment]
Is `input` and `raw_input` a variable? I don't see the variable declaration.

**Comment by julienr** [comment]
It is a builtin function. It is named [`raw_input`](https://docs.python.org/2/library/functions.html#raw_input) in <2.7 and [`input`](https://docs.python.org/3/library/functions.html#input) in 3 and it allows you to prompt the user for input.

keras does the right thing by falling back to `input` for python <2.7 but flake8 cannot figure that out because it is a static checker.

**Comment by benigls** [comment]
I got it, thanks for clarifying this for me.
