### ISSUE TITLE
How to reallize 3D CNN with Keras to learn spatio-temporal Features from Video sequence?

### ISSUE THREAD

**Issue by tzczsq** [fchollet/keras#1359]
Hi, I am interested in that how to use the existed Keras to realize 3D-CNN to learn spatio-temporal Features from Video sequence, as described in following papers? the key step is how to realize 3D-Convoution and 3D-pooling.
3D convolutional neural networks for human action recognition-2013-ICMI;
Learning Spatiotemporal Features with 3D Convolutional Networks_2015-ICCV
Could you please give an answer?

**Comment by meanmee** [comment]
I found it in a pull request : #718

**Comment by happygds** [comment]
I encoutered the same error when the inputs are 5D tensor: 
Exception: ndim too large: 5
Then I add the two lines code at File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 55, in placeholder as following:
>    elif ndim == 5:
>        return T.TensorType('float32', (False,) * 5, name=name)
Then it raises another error:
Traceback (most recent call last):
>  File "C:\Anaconda\dl_modules\keras\examples\simple_test.py", line 23, in <module>
>    model.compile(optimizer='sgd', loss='mse')
>  File "c:\anaconda\dl_modules\keras\keras\models.py", line 420, in compile
>    train_loss = weighted_loss(self.y, self.y_train, self.weights, mask)
>  File "c:\anaconda\dl_modules\keras\keras\models.py", line 82, in weighted
>    score_array = fn(y_true, y_pred)
>  File "c:\anaconda\dl_modules\keras\keras\objectives.py", line 7, in mean_squared_error
>    return K.mean(K.square(y_pred - y_true), axis=-1)
>TypeError: unsupported operand type(s) for -: 'TensorVariable' and 'TensorType'
How to fix it ?
