### ISSUE TITLE
HDF5Matrix for N-dim (N>=3) data

### ISSUE THREAD

**Issue by keunwoochoi** [fchollet/keras#1373]
As mentioned in #991 and #1024 - by @EderSantana, the current HDF5matrix is only capable of dealing with 2d array. As my input is 4-d (n_sample, n_channel, n_row, n_col), I modified it and am using it like this:

```
	def shape(self):
		ret = []
		ret.append(self.end - self.start)
		ret = ret + [dim for dim in list(self.data.shape[1:])]
		return tuple(ret)
```
Would it be helpful to modify Keras' HDF5Matrix in this way? If so, I'd be happy to PR.

**Comment by berleon** [comment]
I have the same use case as you and would find a ndim HDF5Matrix usefull. Here is my implementation: https://github.com/berleon/beras/blob/master/beras/data_utils.py

**Comment by AlexMarshall12** [comment]
Can you show an example of how to call the start and end property so that it can be sent into keras for batch training?

**Comment by rogertrullo** [comment]
Did they change this? for me it is showing the correct shape

**Comment by fchollet** [comment]
I believe this has been fixed.
