### ISSUE TITLE
60 secondes by epoch (cifar10_cnn.py example)

### ISSUE THREAD

**Issue by tboquet** [fchollet/keras#138]
Hi all,
I tried to run the cifar cnn example and I have some troubles getting my first results.
I have a decent hardware config (gtx 980) and my .theanorc config seems to be ok:
[global]
device=gpu0
floatX=float32
allow_gc=False
[nvcc]
fastmath=True

I see that my GPU is used by theano (Using gpu device 0: GeForce GTX 980) and a bump in memory used using nvidia-smi.
First question : do I have a problem?
Second question: what could I do to speed up the learning?

Thanks!

**Comment by fchollet** [comment]
Yes, that's pretty much standard. 

If you want faster learning, you can try to augment the batch size, reduce the size of the network, or experiment with different optimizers (SGD should be fairly fast though, at least in time/epoch, not necessarily in convergence speed).
