### ISSUE TITLE
Parallel Model

### ISSUE THREAD

**Issue by kenterao** [fchollet/keras#139]
Hi all,

I'm a big fan of the Keras architecture.  I see that we can now support more complex tree structures with Merge.  This replicates Torch's nn.Concat().  What do you think about adding a Parallel model to replicate nn.Parallel()?

https://github.com/torch/nn/blob/master/doc/containers.md#nn.Container

```python
model = Sequential()
model.add(Dense(20, 10))
par = Parallel()
par.add(Dense(10, 3))
par.add(Dense(10, 2))
model.add(par)
model.add(Dense(5,1))

model.fit()
```

**Comment by fchollet** [comment]
We definitely plan on adding something similar in the near future. Here's the discussion: https://github.com/fchollet/keras/issues/104

Out of curiosity, what would you use it for?

**Comment by kenterao** [comment]
Great!  Sounds like Fork() is what I need.

I would like to use it as a partial pass-through or block-sparse connections.
```python
# input: X = [X1, X2]
# output: [X1 * W1, X2 * I]
model = Sequential()
model.add(Dense(10, 3))
left, right = Fork(model, n=2)
left.add(Mask([True, True, False]))
left.add(Dense(2, 1))
right.add(Mask([False, False, True]))

model2 = Merge([left, right], 'concat')
model2.compile()
```
Which might be cleaner than
```python
model = Sequential()
model.add(Dense(10, 3))
forked_model = Fork(model, n=2)
forked_model.add(Mask([True, True, False]), position=0)
forked_model.add(Dense(2, 1), position=0)
forked_model.add(Mask([False, False, True]), position=1)
# Fork does the concatenation

forked_model.compile()
```
Or something like
```python
model = Sequential()
model.add(Dense(10, 3))
left = Sequential()
left.add(Mask([True, True, False]))
left.add(Dense(2, 1))
right = Sequential()
right.add(Mask([False, False, True]))
forked_model = Fork(model)
forked_model.add(left)
forked_model.add(right)

forked_model.compile()
```

**Comment by lemuriandezapada** [comment]
Fork() would be great for multimodal outputs for example. Say your outputs need to perform 2 softmaxes of different sizes for one data point which is not possible within the current framework.

**Comment by fchollet** [comment]
Resolved by the Graph model.
