### ISSUE TITLE
Release 0.3.0 version mismatch

### ISSUE THREAD

**Issue by oraac** [fchollet/keras#1394]
__init__.py in release 0.3.0 says __version__ = '0.2.0' untill merge pull request #1137.

This creates a mismatch where pip believes 0.2.0 is installed when we in fact have 0.3.0.

Thanks for the great package!

-Dave

**Comment by fchollet** [comment]
Right. Thanks for pointing this out.

**Comment by fchollet** [comment]
This is fixed with version 0.3.1.
