### ISSUE TITLE
Implementing custom realtime augmentation

### ISSUE THREAD

**Issue by awhitesong** [fchollet/keras#1402]
I need to do a realtime augmentation for my dataset. `ImageDataGenerator` has all the methods implemented for it but they are limited for now. I want to implement some of my own augmenting techniques (In my clone). I can see this file where these are implemented:
https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py

Right now i can look that changing the `__init__` parameters in the `ImageDataGenerator`, writing own functions, and calling in `flow()` might seem to work. Is there any other change that i need to do for this? Or will it actually work this way?
Thanks.

**Comment by fchollet** [comment]
You can write your own `ImageDataGenerator` and use the `model.fit_generator` methods for training.

**Comment by awhitesong** [comment]
Few queries:
1. In `fit_generator` , what are the `samples per epoch` and what's the `batch` size loaded in the GPU at a time? Is it the number of rows X[0] that our generator yields, where epoch gets completed until the rows are equal to `samples per epoch`? 
2. Also what if i also want to use the augmentations already provided along with my new ones? Isn't it safe to change `image.py`?
3. I want to add zero-padding in the convolutional layer filter(2D)? There's another layer for this? Whose use i'm not sure of. How should i add it?
4. What is the default initialization of the weights in the network? Its not mentioned in the docs.
Thanks.
