### ISSUE TITLE
TypeError: max_pool_2d() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by WERush** [fchollet/keras#1405]
full error log is:
>in pool2d mode='average_exc_pad') TypeError: max_pool_2d() got an unexpected keyword argument 'mode'

I find some outputs by google that instruct me to update the theano, then i run the command:
>pip install --upgrade --no-deps theano

And i get 

>Requirement already up-to-date: theano in /anaconda/lib/python2.7/site-packages

Now i have no idea how to fix the error.
Hope get yout help, thanks

**Comment by nouiz** [comment]
For reference, you need Theano development version. Instruction here:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions
