### ISSUE TITLE
example code request

### ISSUE THREAD

**Issue by goodtogood** [fchollet/keras#1410]
Hello,

 I'm a new about python and Keras, I wanna make some test about OCR without segmention using LSTM. I didn't find related example in the code. I noticed MNIST demo, but it's a single char not string sequence. Would you like to make a little demo about OCR using LSTM similar to ocropy [https://github.com/tmbdev/ocropy],

THX.

**Comment by fchollet** [comment]
Good idea, if you come up with something cool we will consider it for inclusion in the Keras examples. Good luck!

**Comment by goodtogood** [comment]
I tried ocropy several times，generally It does well in prediction (even touched character with heavy noise). Unfortunately It doesn't support CUDA, the training progress is just like a nightmare.  After some research, I find reimplementing ocropy with Keras might be a better choice ! 
thanks for your efforts!
Best regards !

**Comment by Adesun** [comment]
Good idea

**Comment by yeshwanth12** [comment]
Hi @goodtogood.Could you give more details on how you reimplemented ocropy with keras. Could u like give a brief description. Thanks
