### ISSUE TITLE
Possible theano bug when using time distributed layers (Windows)

### ISSUE THREAD

**Issue by loyeamen** [fchollet/keras#1413]
I think using the step function that uses the Theano rnn function may cause a crash sometimes.
I experienced many crashes when used a relu activation and when increasing the number of hidden units in the TimeDistributedDense layer (e.g. 128 -> 512)

I solved it simply by replacing the 'rnn' function with my implementation.

Did anyone encounter such a problem?

**Comment by farizrahman4u** [comment]
Are you on windows?

**Comment by loyeamen** [comment]
Yes

**Comment by farizrahman4u** [comment]
I guessed so. You  won't find any help here..Keras is pure python  so it can not crash anything. Theano for windows is buggy. I too use windows and it crashes when using convolution layers. Now I use Keras inside a linux VM and everything works fine. See #1274

**Comment by loyeamen** [comment]
Does linux VM support Theano with GPU?

**Comment by farizrahman4u** [comment]
Forgot to mention that.. No it doesn't.

**Comment by loyeamen** [comment]
OK, update:
The problem was when using
TimeDistributedMerge(mode = 'mul')

I have got the output:
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <type 'exceptions.TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Prod{axis=[1], acc_dtype=float64}.0, Elemwise{mul,no_inplace}.0, TensorType(float32, matrix), TensorType(float64, matrix), 'local_sum_prod_mul_by_scalar') local_sum_prod_mul_by_scalar
ERROR (theano.gof.opt): Optimization failure due to: local_sum_prod_mul_by_scalar
ERROR:theano.gof.opt:Optimization failure due to: local_sum_prod_mul_by_scalar
ERROR (theano.gof.opt): node: Prod{axis=[1], acc_dtype=float64}(Elemwise{mul,no_inplace}.0)
ERROR:theano.gof.opt:node: Prod{axis=[1], acc_dtype=float64}(Elemwise{mul,no_inplace}.0)
ERROR (theano.gof.opt): TRACEBACK:
ERROR:theano.gof.opt:TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Oren\WinPython-64bit-2.7.10.1\python-2.7.10.amd64\lib\site-packages\theano-0.7.0-py2.7.egg\theano\gof\opt.py", line 1814, in process_node
    fgraph.replace_all_validate(repl_pairs, reason=lopt)
  File "C:\Oren\WinPython-64bit-2.7.10.1\python-2.7.10.amd64\lib\site-packages\theano-0.7.0-py2.7.egg\theano\gof\toolbox.py", line 306, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "C:\Oren\WinPython-64bit-2.7.10.1\python-2.7.10.amd64\lib\site-packages\theano-0.7.0-py2.7.egg\theano\gof\fg.py", line 564, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Prod{axis=[1], acc_dtype=float64}.0, Elemwise{mul,no_inplace}.0, TensorType(float32, matrix), TensorType(float64, matrix), 'local_sum_prod_mul_by_scalar')

**Comment by nouiz** [comment]
NVIDIA released Windows VM that support GPU. I don't know the constraint.
Maybe it need a dedicated GPU not shared. I never tried this or heard
anyone tring it. Just in case it help.

**Comment by loyeamen** [comment]
Specifically, using theano.tensor.prod cause the error.
Replacing it with my implementation solved the problem, i did not try to figure out what exactly the type of this problem but it seems that Theano failed to optimized something.

**Comment by loyeamen** [comment]
To sum up, there are two issues.
1.
If i used TimeDistributedDense with a large number of hidden units (say 512) i have got nan in the loss (binary crossentropy). This is solved by replacing the call to rnn with my implementation.
2.
When using TimeDistributedMerge(mode = 'mul') after TimeDistributedDense i have the above error. This is solved by replacing the 'mul' case with my implementation.

**Comment by farizrahman4u** [comment]
Can you post your implementation?

**Comment by loyeamen** [comment]
This is an adhoc one. Since i want to train on pairs, it reduces to a specific case, e.g. i replaced

elif self.mode == 'mul':
            s = K.prod(X, axis=1)
            return s

with:
elif self.mode == 'mul':
            s = X[:, 0, :] * X[:, 1, :] 
            return s

Is that clear?

**Comment by farizrahman4u** [comment]
Yep.
