### ISSUE TITLE
Graph with multiple outputs causes float64

### ISSUE THREAD

**Issue by ozancaglayan** [fchollet/keras#1416]
Hi,

I'm trying to build a graph with multiple outputs and also masks. During model creation, Theano gives me float64 warnings (as I told it to raise those exceptions in `.theanorc`). The blamed op resides in `weighted_objective()` defined in `models.py`:

```
...
if mask is not None:
  score_array *= mask
...
```

If I cast the `mask` to `K.floatx()` everything seems to work fine. Am I doing something wrong or should I send a PR for this?

**Comment by fchollet** [comment]
> should I send a PR for this?

Please do.
