### ISSUE TITLE
cant load the mnist dataset

### ISSUE THREAD

**Issue by karen-turing** [fchollet/keras#1425]
i try to load the mnist dataset by writing : 
    from keras.datasets import mnist
    (x_train,y_train),(x_test,y_test)=mnist.load_data()

but i get the following error : 
    IOError: CRC check failed 0xc187cf56L != 0x14c5212fL

how can i fix this error??

**Comment by karen-turing** [comment]
i also tried to mnist.py in my keras datasets directory to download the dataset but i get the following error : 
ValueError: Attempted relative import in non-package

**Comment by fchollet** [comment]
`rm ~/.keras/datasets/*` and retry.

**Comment by karen-turing** [comment]
i did that it starts to download the dataset but i get  this error  :      
     raise IOError(errno.EBADF, "read() on write-only GzipFile object")
     IOError: [Errno 9] read() on write-only GzipFile object

thank you for helping

**Comment by dderiso** [comment]
For OSX 10.11.3 using Python3.6, here's what worked for me. To the top of

```
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/utils/data_utils.py
```

just below the import statements, add:

```
import requests
requests.packages.urllib3.disable_warnings()
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    # Legacy Python that doesn't verify HTTPS certificates by default
    pass
else:
    # Handle target environment that doesn't support HTTPS verification
    ssl._create_default_https_context = _create_unverified_https_context
```

Restart Python and it will hopefully work

**Comment by Nithanaroy** [comment]
@dderiso 's code change worked for imdb dataset too

**Comment by Kishwar** [comment]
@dderiso worked for me.. Thanks

**Comment by tharhtetsan** [comment]
Thank @dderiso it work for me.

**Comment by mughuara** [comment]
nice. I've done it and my VM bricked. hahahahahaha What the hell...

I found the file data_utils.py and copied the code insertion. After reboot the system, it won't boot anymore...
