### ISSUE TITLE
Python keras package returns an error about data dimensions

### ISSUE THREAD

**Issue by rahimikia** [fchollet/keras#143]
I have this code:

import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD
from sklearn import datasets
import theano

iris = datasets.load_iris()
X = iris.data[:,0:3]  # we only take the first two features.
Y = iris.target

X = X.astype(theano.config.floatX)
Y = Y.astype(theano.config.floatX)

model = Sequential()
model.add(Dense(150, 1, init='uniform'))
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(Dense(150, 1, init='uniform'))
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(Dense(150, 1, init='uniform'))
model.add(Activation('softmax'))

sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer=sgd)

model.fit(X, Y, nb_epoch=20, batch_size=150)

score = model.evaluate(X_train, y_train, batch_size=16)

Returns this error:

ValueError: Shape mismatch: x has 3 cols (and 150 rows) but y has 150 rows (and 1 cols)
Apply node that caused the error: Dot22(<TensorType(float64, matrix)>, <TensorType(float64, matrix)>)
Inputs types: [TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(150L, 3L), (150L, 1L)]
Inputs strides: [(24L, 8L), (8L, 8L)]
Inputs values: ['not shown', 'not shown']

What is the problem?

**Comment by kenterao** [comment]
The input_dim of the Dense layer must equal the output_dim of the layer above, in this case 3.
Also, Y is a categorical variable so it should be translated into a one-hot matrix and use categorical_crossentropy as the loss instead of mean_squared_error.

```python
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD
from keras.utils.np_utils import to_categorical
from sklearn import datasets
import theano

iris = datasets.load_iris()
X = iris.data[:,0:3] # we only take the first three features.
Y = to_categorical(iris.target)

X = X.astype(theano.config.floatX)
Y = Y.astype(theano.config.floatX)

model = Sequential()
model.add(Dense(3, 3, init='uniform'))
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(Dense(3, 3, init='uniform'))
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(Dense(3, 3, init='uniform'))
model.add(Activation('softmax'))

sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)

model.fit(X, Y, nb_epoch=20, batch_size=16)

score = model.evaluate(X, Y, batch_size=16)


```

**Comment by rahimikia** [comment]
Thank you for answer. Where can I set number of neurons in every layer? Can you describe dense layer dimensions (pair values) with more details? I didn't understand documentation.

**Comment by rahimikia** [comment]
Thank you for answer. Is anyway in this package to set train,test and validation data-sets as we have in MATLAB?

**Comment by kenterao** [comment]
X and Y are indexable arrays.  There are examples in /keras/keras/datasets/imdb.py in load_data().
