### ISSUE TITLE
Some CS229 projects using Keras

### ISSUE THREAD

**Issue by fchollet** [fchollet/keras#1432]
[CS229](http://cs229.stanford.edu/) is the Stanford machine learning class, taught by Andrew Ng. This year a number of student projects were implemented using Keras. I thought it would be interesting for the Keras community to check them out:
- [Sign Language Recognition using Temporal Classification](http://cs229.stanford.edu/proj2015/118_report.pdf)
- [Energy Consumption Prediction for Optimum Storage Utilization](http://cs229.stanford.edu/proj2015/345_report.pdf)
- [Contextual Code Completion Using Machine Learning](http://cs229.stanford.edu/proj2015/312_report.pdf)
- [Deep Learning Stock Volatilities with Google Domestic Trends](http://cs229.stanford.edu/proj2015/186_report.pdf)
- [Object classification for autonomous vehicle
  navigation of Stanford campus](http://cs229.stanford.edu/proj2015/170_report.pdf)

There may be more projects that I'm missing, either because they weren't indexed by Google or because they didn't cite Keras (100% of students use one or several open-source packages to implement their projects, but few of them actually cite their tools, probably only around 10% do). For comparison, I could find 1 (one) project using Torch, 4 (four) using TensorFlow and 3 (three) using Caffe.

**Comment by phreeza** [comment]
Nice stuff!

My guess would be more of them would properly cite Keras if there was a canonical paper, instead of 'just' a github repo to cite?

**Comment by liyi193328** [comment]
@fchollet Great.
And is there some pretty projects using keras like farizrahman4u's seq2seq. By that kind of beautiful projects, I(fresher) can learn how to custom my own deep learning demands.Can you summary it, and post it out? 
Appreciate.Thanks.
seq2seq: https://github.com/farizrahman4u/seq2seq

**Comment by farizrahman4u** [comment]
Cool stuff!

**Comment by fchollet** [comment]
> My guess would be more of them would properly cite Keras if there was a canonical paper, instead of 'just' a github repo to cite?

It's possible, but I don't really believe it because users of Theano (and Torch, TensorFlow) tend not to cite their tools even though there are papers to cite. There is just no culture of crediting open-source projects in academia.

**Comment by farizrahman4u** [comment]
We should not be worried about people not citing us. But I think its time for Keras to be more than a github repo. I am talking about Youtube channels, Tutorials, Blogs, Developer communities, Meetups, Workshops etc (the Mozilla of deep learning).

**Comment by tboquet** [comment]
:+1: for @farizrahman4u suggestion. What about a simple mardown file including directives to cite Keras with a BibTeX entry like [this](https://github.com/Kaixhin/dockerfiles/blob/master/CITATION.md)?

**Comment by farizrahman4u** [comment]
@tboquet Sounds good. What do you think @fchollet ?

**Comment by meanmee** [comment]
I suggest add an cite example(BibTex) in the ReadMe.md file.
like this:
@article{Stamatakis2006Stamatakis,
  title={Stamatakis A. RAxML-VI-HPC: Maximum Likelihood—based Phylogenetic Analyses with Thousands of Taxa and Mixed Models, v. 7.03. Bioinformatics},
  author={Stamatakis, A},
  journal={Bioinformatics},
  volume={22},
  number={21},
  pages={2688-90},
  year={2006},
}

**Comment by phreeza** [comment]
Here is the suggested BibTeX for scipy:

    @Misc{,
    author =    {Eric Jones and Travis Oliphant and Pearu Peterson and others},
     title =     {{SciPy}: Open source scientific tools for {Python}},
     year =      {2001--},
     url = "http://www.scipy.org/",
     note = {[Online; accessed 2016-01-13]}
    }

**Comment by brettbj** [comment]
@fchollet I acutally just submitted a paper citing Keras (I do think it'd be helpful to have a standard paper or at least preferred citation format - maybe using zenodo?)

**Comment by farizrahman4u** [comment]
@brettbj Link to your paper?

**Comment by brettbj** [comment]
@farizrahman4u it's a conference submission that doesn't allow preprints. Will post if it gets in!

**Comment by farizrahman4u** [comment]
Cool!
