### ISSUE TITLE
The add_input before Embedding layer in Graph

### ISSUE THREAD

**Issue by Ryan2liu** [fchollet/keras#1440]
Hi, I got the same problem posted https://groups.google.com/forum/#!topic/keras-users/2R_mEinnEcc , when add a embedding layer after add_input in graph, I got the error 'Exception: Type "int" can only be used with ndim==2 (Embedding).' , but the add_input function now didn't have the parameter 'ndim' , 'add_input() got an unexpected keyword argument 'ndim'', how can i sovle this, Thx.

**Comment by leonardblier** [comment]
Hi,
I have the same problem. Have you found a way to solve it ?
Thanks,

Léonard
