### ISSUE TITLE
Unable to instantiate Siamese layers from saved config

### ISSUE THREAD

**Issue by around1991** [fchollet/keras#1444]
Hi all

The following code gives an error:

``` python
from keras.models import Graph, Sequential, model_from_json
from keras.layers.core import Dense

inner_model = Sequential()
inner_model.add(Dense(input_dim=2, output_dim=1))

model = Graph()
model.add_input(name='l', input_shape=(2,), dtype='float')
model.add_input(name='r', input_shape=(2,), dtype='float')
model.add_shared_node(layer=inner_model, name='comp', inputs=['l', 'r'], merge_mode='sum', create_output=True)

config = model.to_json()

test_model = model_from_json(config)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/auto/homes/kc391/event_rnn/env/bin/keras/keras/models.py", line 137, in model_from_json
    return model_from_config(config, custom_objects=custom_objects)
  File "/auto/homes/kc391/event_rnn/env/bin/keras/keras/models.py", line 148, in model_from_config
    model = container_from_config(config, custom_objects=custom_objects)
  File "/auto/homes/kc391/event_rnn/env/bin/keras/keras/utils/layer_utils.py", line 57, in container_from_config
    layer = container_from_config(layer_dict['nodes'].get(node['name']))
  File "/auto/homes/kc391/event_rnn/env/bin/keras/keras/utils/layer_utils.py", line 88, in container_from_config
    base_layer = get_layer(name, layer_dict)
  File "/auto/homes/kc391/event_rnn/env/bin/keras/keras/utils/layer_utils.py", line 154, in get_layer
    instantiate=True, kwargs=kwargs)
  File "/auto/homes/kc391/event_rnn/env/bin/keras/keras/utils/generic_utils.py", line 18, in get_from_module
    return res(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'trainable'

```

I think there are multiple issues in the way Siamese loads from config:

1) Siamese.**init** accepts different kwargs to Layer.**init**, but Siamese.get_config() calls Layer.get_config(), so any attempt to load a Siamese layer from config will call some of the kwargs that Layer inits with (such as 'trainable' and 'cache_enabled'). At the very least, we should probably have a **kwargs at the end of Siamese.**init**() to handle this case.

2) When loading from config, the 'layer' argument of kwargs is a dictionary, not a layer or container object. I think we need to instantiate this argument first before feeding it in to the Siamese constructor, but the way get_from_module works doesn't seem to allow this as an easy case. 

@farizrahman4u do you have any ideas or suggestions?

**Comment by around1991** [comment]
Update: for issue 2, I think container_from_config needs to be updated to check for a Siamese layer, and instantiate the inner layer first before passing it through to the Siamese constructor (see how it currently handles reconstructing AutoEncoder layers for an example).

I can try and patch support for this in, but I can't run the Keras unit tests locally (due to weird virtualenv issues), and I'd probably break a whole bunch of regressions.

**Comment by sergeyf** [comment]
I'm having this same issue.

**Comment by lemuriandezapada** [comment]
I concur, same problem

**Comment by chenb67** [comment]
same here for recurrent net with cache_enabled

**Comment by TomasJiang** [comment]
same issue.

**Comment by rkempter** [comment]
+1

**Comment by rkempter** [comment]
@around1991: You are right with extending `container_from_config` with `elif name == 'Siamese'`. At least for the layer part, this works. Unfortunately, I get similar errors afterwards with the inputs, as they are represented as dictionaries as well.

in `add_shared_node` (layers/containers.py), we do this before initializing a Siamese Layer:
```python
498         layers = []
499         for i in range(len(inputs)):
500             input = inputs[i]
501             if input in self.nodes:
502                 n = self.nodes[input]
503                 if n.__class__.__name__ == 'Siamese':
504                     if n.merge_mode is None:
505                         for j in range(len(n.inputs)):
506                             sh = SiameseHead(j)
507                             sh.previous = n
508                             layers.append(sh)
509                     else:
510                         layers.append(n)
511                 else:
512                     layers.append(n)
513             elif input in self.inputs:
514                 n = self.inputs[input]
515                 layers.append(n)
516             else:
517                 raise Exception('Unknown identifier: ' + input)
```

Any ideas how to solve this?

**Comment by around1991** [comment]
What I've done in my private fork is to add a config flag for shared nodes, and then when we reconstruct from config, check for this, and call graph.add_shared_node instead of graph.add_node (see lines 59-61 and lines 79-80 in this: https://github.com/around1991/keras/blob/master/keras/utils/layer_utils.py).

Otherwise, none of the Siamese layer initialisation is carried out properly, and you end up with a duff layer.

**Comment by rkempter** [comment]
Thanks for your comment. I also had a closer look at it, and I was able to fix it without a config flag. I only tested on my current model, will do proper testing later on. Please have a look at it as well `https://github.com/rkempter/keras/blob/master/keras/utils/layer_utils.py#L61`

**Comment by around1991** [comment]
I thought about doing it that way as well, but I figured that the graph container already has the right method to instantiate shared layers correctly, so we might as well go through an existing code path rather than add a new one.
