### ISSUE TITLE
Convolution1D, unexpected keyword argument 'input_length', keras0.1.3

### ISSUE THREAD

**Issue by breadada** [fchollet/keras#1457]
Hi, all.
I am new here. I just want to try 1D-CNN on kaggle-titanic competition.My input data is 819 rows and 24 cols. I have already met many erros such as 

1."expected 3, got 2 with shape(128, 24)".After reshape(891, 1, 24), it seems solved.

2."ValueError:Output dimensions are not valid -3*1", I try to fix it, so I change "input_dim=24" to "input_length=24", and something strange occurs:

pic1:source code in keras/layers/convolutional.py  (Keras0.1.3)
pic2:my code, change input_dim to input_length
pic3:erros, no input_length!? but it did exist in the source code.

I just want to know how to run through such codes and realize Conv and Pool in 1D data.

![1](https://cloud.githubusercontent.com/assets/11451898/12296895/74ca5138-ba45-11e5-8a13-d152fd9f833c.png)
![2](https://cloud.githubusercontent.com/assets/11451898/12296901/7a30896c-ba45-11e5-9360-7b0064324e1c.png)
![3](https://cloud.githubusercontent.com/assets/11451898/12296904/7e73145e-ba45-11e5-92e9-b7365315311e.png)

my code:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.advanced_activations import PReLU
from keras.layers.convolutional import Convolution1D, MaxPooling1D
from keras.optimizers import SGD, Adadelta, Adagrad
from keras.utils import np_utils, generic_utils
import cPickle as pickle
import numpy as np
from sklearn.cross_validation import train_test_split

''' input data
train_add_test = pickle.load(open('train_add_test.pkl', 'rb'))
label = np.array(train_add_test.Survived[:891])
data = np.array(train_add_test.drop('Survived', axis=1))
label = np_utils.to_categorical(label, 2)

train = data[:891]
test = data[891:]
print train.shape, label.shape  # (891, 24) (891, 2)

''' reshape
newshape = (891, 1, 24)
train = np.reshape(train, newshape)
print train.shape # (891, 1, 24)

''' model
model = Sequential()

''' input_dim= 24, after Conv=24-5+1=20, after Maxp=20/2=10
model.add(Convolution1D(nb_filter=4, filter_length=5, input_length=24, border_mode='valid'))
model.add(Activation('tanh'))
model.add(MaxPooling1D(pool_length=2))

''' input_dim=10, after Flatten=4*10
model.add(Flatten())
model.add(Dense(input_dim=40, output_dim=10, init='uniform'))
model.add(Dropout(0.5))
model.add(Activation('tanh'))

model.add(Dense(input_dim=10, output_dim=1))
model.add(Activation('sigmoid'))

''' train
sgd = SGD(l2=0.0, lr=0.02, decay=1e-6)
model.compile(loss='binary_crossentropy',optimizer=sgd, class_mode='binary')

print 'Training...'
model.fit(train, label, nb_epoch=20, shuffle=True, verbose=1, show_accuracy=True, validation_split=0.2)

print 'Done.'

OUTPUT:
  "This module will be removed in 0.20.", DeprecationWarning)
(891, 24) (891, 2)
(891, 1, 24)
Traceback (most recent call last):
  File "cnn.py", line 37, in <module>
    model.add(Convolution1D(nb_filter=4, filter_length=5, input_length=24, border_mode='valid'))
TypeError: **init**() got an unexpected keyword argument 'input_length'

**Comment by keunwoochoi** [comment]
According to the [document](http://keras.io/layers/convolutional/), `input length` is used as below:
>  Length of input sequences, when it is constant. This argument is required if you are going to connect  Flatten then Dense layers upstream (without it, the shape of the dense outputs cannot be computed).

I think what you should do is to set `input_dim` as following:
> When using this layer as the first layer in a model, either provide the keyword argument input_dim (int, e.g. 128 for sequences of 128-dimensional vectors), or input_shape (tuple of integers, e.g. (10, 128) for sequences of 10 vectors of 128-dimensional vectors).

For the first layer and only for the first layer. For other layers you don't need to specify it. Check [examples](http://keras.io/examples/) how it should be set for either `conv` or `dense`.

**Comment by breadada** [comment]
Hi, @keunwoochoi . Thanks for your advice.I try what you say, and questions still there, but not the same. Here are some notation:

1.My data is 891 vectors of 24 dimensions

2.before model.fit(train, label, ...), I reshape train from(891, 24) to (891, 1, 24), as describe in the Conv1D input shape(samples, steps, input_dim)

---------------------My change---------------------------
1."model.add(Convolution1D(nb_filter=4, filter_length=3, input_length=24, border_mode='valid'))" to
   "model.add(Convolution1D(nb_filter=4, filter_length=3, input_dim=24, border_mode='valid'))":

TypeError: Output dimensions are not valid -1*1

2."model.add(Convolution1D(nb_filter=4, filter_length=3, input_dim=24, border_mode='valid'))" to
   "model.add(Convolution1D(nb_filter=4, filter_length=3, input_shape=(891,24), border_mode='valid'))":

TypeError:__init__() got an unexpected keyword argument 'input_shape'

strange, it doesn't work. so sad :(

**Comment by keunwoochoi** [comment]
Hm, btw, which version are you using? `input_dim` is required only for the first layer, which would make debugging process less painful. I would also change `valid` to `same` at least for temporary because that would also make the problem easier.

**Comment by breadada** [comment]
Hi, @keunwoochoi  . I think the version is 0.1.3, I check it in this way:
>>python
>>help('keras')
...
FILE
       /usr/local/lib/python2.7/dist-packages/Keras-0.1.3-py2.7.egg/keras/__init__.py
PACKAGE CONTENTS
....

But in /usr/local/lib/python2.7/dist-packages/keras/__init__.py, it says:__version__=0.2.0'

which is correct?0.1.3 or 0.2.0?

---------------------
I do what you say, change "valid" to "same":
model = Sequential()
model.add(Convolution1D(nb_filter=4, filter_length=5,  border_mode='same', input_dim=24))

OUTPUT is :float point exception core dumped
maybe some value/0 or value%0 occurs..hm....a new error.

**Comment by keunwoochoi** [comment]
```import keras
print keras.__version__```
would be more correct. Whichever it is, it's quite old. Please update it to 0.3.0 or 0.3.1 by
``` $ sudo pip install keras --upgrade ```
or clone it.

**Comment by breadada** [comment]
Hi, @keunwoochoi . Thanks for your patience, I am sorry to troble you so many times..

I have already change the version to 0.3.1, and I can run through the MLP, which ensures my data works. 

Now my data is 623 vectors of 24 dimensions， not 891 vectors of 24 dimensions any more.

After MLP, I run through 1D-CNN program, with<code>input_shape=(623, 24)</code>which outpus:

>TypeError: ('Bad input argument to theano function with name "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py:362"  at index 0(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (1, 24).')

Do you know what make such problems?

Here is my code.

```Python
newshape = (623, 1, 24)
train = np.reshape(X_train, newshape)

model = Sequential()

# input_dim= 24, after Conv=24-5+1=20, after Maxp=20/2=10
model.add(Convolution1D(nb_filter=4, filter_length=5,  border_mode='valid', input_shape=(623,24)))
model.add(Activation('tanh'))
model.add(MaxPooling1D(pool_length=2))

# input_dim=10, after Flatten=4*10
model.add(Flatten())
model.add(Dense(input_dim=40, output_dim=10, init='uniform'))
model.add(Dropout(0.5))
model.add(Activation('tanh'))

model.add(Dense(input_dim=10, output_dim=2))
model.add(Activation('softmax'))

# train
sgd = SGD(l2=0.0, lr=0.02, decay=1e-6)
model.compile(loss='binary_crossentropy',optimizer=sgd, class_mode='binary')
model.fit(X_train, y_train, nb_epoch=10, batch_size=1, verbose=1, show_accuracy=True)

print 'Done.'
```

P.S Markdown is cool, I learn a lot in the past 24 hours :)

**Comment by keunwoochoi** [comment]
Hm, it would be much easier if there's an example that uses `Convolution1D`, so how about make a pull request to add one with your code? 
What's the meaning of 623 vectors? Does it mean one, single data point consists of 623-by-24 2D array? Or does it mean 24-length 1D vector is a single data point and you have 623 data points as a training set? If it's latter, I think you should set a `input shape` of (1,24) (or perhaps equivalently, `input_dim` of 24). You don't put the number of training data when you build the network, you just specify the size of an instance of data.

**Comment by breadada** [comment]
Hi, @keunwoochoi 
it's the latter one. I have already debug it the past 5 hours, and several erros occurs.
I will do it tomorrow, it's 0:13 now. I will check my data first, then tell you what happened.

I am here to say thanks to you :)
Good night(maybe it's morning in your place, haha)

**Comment by breadada** [comment]
Hi, @keunwoochoi .
Good news ! I can run through my code without MaxPooling1D now, which says my data and reshape may be correct. Here is the code:
```python
data = pickle.load(open('train.pkl', 'r'))
label = map(int, list(pickle.load(open('label.pkl', 'r'))))
label = np.array(label)
X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.3, random_state=4)
#y_train, y_test = [np_utils.to_categorical(x) for x in (y_train, y_test)]
y_train = np_utils.to_categorical(y_train, 2)
y_test =  np_utils.to_categorical(y_test, 2)

print 'data format[:2]\n',X_train[:2]
print 'label format[:2]\n',label[:2]
print X_train.shape, y_train.shape


X_train = X_train.reshape(X_train.shape[0],1,24 )
print 'reshape:', X_train.shape

#########
# model #
######### 
model = Sequential()

# input_dim= 24, after Conv=24-5+1=20, after Maxp=20/2=10
model.add(Convolution1D(nb_filter=4, filter_length=5, activation = 'tanh', border_mode='same', input_shape=(1,24)))
model.add(Activation('tanh'))
#model.add(MaxPooling1D(pool_length=2))

model.add(Flatten())
model.add(Dense(output_dim=10, init='uniform'))

model.add(Dropout(0.5))
model.add(Activation('tanh'))

model.add(Dense(output_dim=2))
model.add(Activation('softmax'))


#########
# train #
#########
sgd = SGD(l2=0.0, lr=0.02, decay=1e-6)
model.compile(loss='binary_crossentropy',optimizer='sgd', class_mode='binary')
print 'Training...'

model.fit(X_train, y_train, nb_epoch=5, batch_size=16, verbose=1, show_accuracy=True)
print 'Done.'
```
Output is :
>Training...
>Epoch 1/5
>623/623 [==============================] - 0s - loss: 0.6871 - acc: 0.5618     
>Epoch 2/5
>623/623 [==============================] - 0s - loss: 0.6748 - acc: 0.5955     
>Epoch 3/5
>623/623 [==============================] - 0s - loss: 0.6622 - acc: 0.5955     
>Epoch 4/5
>623/623 [==============================] - 0s - loss: 0.6526 - acc: 0.5971     
>Epoch 5/5
>623/623 [==============================] - 0s - loss: 0.6510 - acc: 0.6051     
>Done.

### BUT
if I add <code>MaxPooling1D(pool_length=2)</code>, this error will occur. if not, the program runs well.
>Traceback (most recent call last):
  File "cnn.py", line 60, in <module>
    model.add(Dense(output_dim=10, init='uniform'))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/containers.py", line 68, in add
    self.layers[-1].set_previous(self.layers[-2])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 82, in set_previous
    assert self.input_ndim == len(layer.output_shape), ('Incompatible shapes: layer expected input with ndim=' +
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 814, in output_shape
    '(got ' + str(input_shape[1:]) + '. '
Exception: The shape of the input to "Flatten" is not fully defined (got (0, 4). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.

I think we may succeed...

**Comment by breadada** [comment]
https://github.com/breadada

**Comment by breadada** [comment]
sorry, misclick, no close now.

**Comment by keunwoochoi** [comment]
Cool, now I don't get the whole picture but it's good anyway.

**Comment by breadada** [comment]
pic here.
![qq 20160115113833](https://cloud.githubusercontent.com/assets/11451898/12345006/68a98100-bb7e-11e5-9235-6bf5d50854b9.png)

## what can I do to fix this final bug? ##
input shape, or parameters?

```python
data = pickle.load(open('train.pkl', 'r'))
label = map(int, list(pickle.load(open('label.pkl', 'r'))))
label = np.array(label)
X_train, X_test, y_train, y_test = train_test_split(data, label, test_size=0.3, random_state=4)
#y_train, y_test = [np_utils.to_categorical(x) for x in (y_train, y_test)]
y_train = np_utils.to_categorical(y_train, 2)
y_test =  np_utils.to_categorical(y_test, 2)

print 'data format[:2]\n',X_train[:2]
print 'label format[:2]\n',label[:2]
print X_train.shape, y_train.shape


X_train = X_train.reshape(X_train.shape[0],1,24 )
print 'reshape:', X_train.shape

#########
# model #
######### 
model = Sequential()

# input_dim= 24, after Conv=24-5+1=20, after Maxp=20/2=10
model.add(Convolution1D(nb_filter=4, filter_length=5, activation = 'tanh', border_mode='same', input_shape=(1,24)))
model.add(Activation('tanh'))
#################################
#                         HERE #
#################################
model.add(MaxPooling1D(pool_length=2))

model.add(Flatten())
model.add(Dense(output_dim=10, init='uniform'))

model.add(Dropout(0.5))
model.add(Activation('tanh'))

model.add(Dense(output_dim=2))
model.add(Activation('softmax'))


#########
# train #
#########
sgd = SGD(l2=0.0, lr=0.02, decay=1e-6)
model.compile(loss='binary_crossentropy',optimizer='sgd', class_mode='binary')
print 'Training...'

model.fit(X_train, y_train, nb_epoch=5, batch_size=16, verbose=1, show_accuracy=True)
print 'Done.'
'''

**Comment by kakaguotao** [comment]
@breadada ,Hi. I am facing the same problem.
I got "ValueError:Output dimensions are not valid -6*1".
 Could you please show the shape of you label set?

**Comment by breadada** [comment]
Hi, @kakaguotao 

Maybe we mis-understand what 1D means. In my code above, the length of output of the Convolution1D layers is the nb_filter, 4, not 24-5+1=20, which confuses me a lot.

If you know the truth, please let me know.QQ:241869553

Best wishes!

**Comment by kakaguotao** [comment]
Hi, @breadada. It is very kind of you to reply. Do you mean that this error is caused by the output of the conv layer but not by the output of the whole net?

**Comment by breadada** [comment]
Hi, @kakaguotao .  Yes, I tried to print the dimension every layer, and the error came from the conv layer and had effect on the flatten layer.

**Comment by hugofgh** [comment]
X_train = X_train.reshape(X_train.shape[0],**_24 ,1)_**
print 'reshape:', X_train.shape

#########
# model #
######### 
model = Sequential()

# input_dim= 24, after Conv=24-5+1=20, after Maxp=20/2=10
model.add(Convolution1D(nb_filter=4, filter_length=5, border_mode='same', input_shape=_**(24,1)))**_
model.add(Activation('tanh'))

**Comment by hugofgh** [comment]
change the input_shape from input_shape=(1,24)  to input_shape=(24,1)
and  fix the  
X_train = X_train.reshape(X_train.shape[0],24 ,1)
