### ISSUE TITLE
keras.utils.visualize_util error: global name 'Sequential' is not defined

### ISSUE THREAD

**Issue by pdejorge** [fchollet/keras#1458]
I am trying to visualize a graph of my model. It is a sequential model like this

model = Sequential()
model.add(Dense(1024, input_shape=(536,)))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dense(2))
model.add(Activation('softmax'))

then I import

from keras.utils.visualize_util import plot

and write

plot(model)

but I get the following error:

 in plot(model, to_file)
      7 
      8     graph = pydot.Dot(graph_type='digraph')
----> 9     if type(model) == Sequential:
     10         previous_node = None
     11         written_nodes = []

NameError: global name 'Sequential' is not defined

**Comment by rpinsler** [comment]
This was [fixed recently](https://github.com/fchollet/keras/pull/1039). Please try to update to the latest version of keras.

**Comment by AND2797** [comment]
if it still  doesn't  work -
use

`from  keras import  sequential`
