### ISSUE TITLE
Problems running Keras imdb_cnn.py example with Theano

### ISSUE THREAD

**Issue by claudiogreco** [fchollet/keras#1460]
Hello,

I recently tried to run Keras imdb_cnn.py example (https://github.com/fchollet/keras/blob/master/examples/imdb_cnn.py):

I have noticed that it returns the following error message:

 `AttributeError: module 'theano.tensor.nnet' has no attribute 'relu' `

I solved this error by defining my RELU function like this and by calling it when needed:

```
import theano.tensor as T

def my_relu(x):
    return T.switch(x<0, 0, x)
```

That problem has been solved, but now it returns a new error message:

 `TypeError: max_pool_2d() got an unexpected keyword argument 'mode' `

I am using Keras 0.3.1 with Theano 0.7.0.

Could you help me with this problem?

Thank you!

**Comment by tboquet** [comment]
Do you have the [bleeding edge version of Theano](https://github.com/Theano/Theano). If not, it seems you should update to the latest Theano development version using:
```
pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
```

**Comment by claudiogreco** [comment]
Now it works. Thanks!
