### ISSUE TITLE
Textual information for labels?

### ISSUE THREAD

**Issue by KeironO** [fchollet/keras#1461]
I seem unable to use text for labels, whilst using to_categorical

```
Using Theano backend.
Traceback (most recent call last):
  File "playground.py", line 88, in <module>
    train_model_and_test(number_of_epochs, number_of_classes, train_data, train_label, augmented_data_generator)
  File "playground.py", line 62, in train_model_and_test
    train_label = np_utils.to_categorical(train_label, number_of_classes)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/np_utils.py", line 12, in to_categorical
    y = np.asarray(y, dtype='int32')
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 460, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: invalid literal for int() with base 10: 'yellow'
```

**Comment by KeironO** [comment]
The problem has been fixed, but I might as well ask - why on earth are you only allowing for int32 labels?

https://github.com/fchollet/keras/blob/master/keras/utils/np_utils.py#L8-L18

Seems a bit daft!

**Comment by kylemcdonald** [comment]
for my application, i have a varying number of classes for each sample. `y = np.asarray(y, dtype='int32')` causes `to_categorical` to fail with `ValueError: setting an array element with a sequence.` but if i remove the line completely, `to_categorical` behaves correctly.

**Comment by derekchen14** [comment]
I think the check for integers was originally included because `nb_classes = np.max(y)+1` requires a number rather than text.  If you have text labels, and also include the number of classes, then everything works.  Might be useful to perform a check for 'int32' or 'str' and give and handle accordingly.  Thoughts?

**Comment by KeironO** [comment]
This sounds like the best possible way of doing it.
