### ISSUE TITLE
How do I implement a many-to-many RNN for language modeling?

### ISSUE THREAD

**Issue by camcam3** [fchollet/keras#1469]
Most of the examples I read in Keras such as the char_rnn implement RNNs where the prediction is made at the end only. For language modeling, I would like to predict y after each step, such as the one described in this paper http://arxiv.org/pdf/1409.2329v5.pdf as implemented by TensorFlow https://www.tensorflow.org/versions/master/tutorials/recurrent/index.html.
![rnn](https://cloud.githubusercontent.com/assets/16708060/12334929/76ea3bb0-bab1-11e5-9992-1a8d009722d9.PNG)

**Comment by fchollet** [comment]
You use `return_sequences=True` in your RNN layer(s). It's in the docs.
