### ISSUE TITLE
Just starting ...

### ISSUE THREAD

**Issue by vsraptor** [fchollet/keras#1471]
Hi, trying to create input conv1d layer, my data is 64 bytes.
I find it hard to figure out the meaning of the parameters ... 

```
nb_filter: Number of convolution kernels to use (dimensionality of the output).
filter_length: The extension (spatial or temporal) of each filter.
```

What is "nb" shortcut for ? 
filter_length ? is this the conv kernel size ?
Then there are the input and output shape which include steps and samples ? I thought the shape is provided by input_shape ?

I used this : 
model.add(Convolution1D(64,1,input_shape=(1,64), border_mode='same') )
but not sure if it is correct ?

If you could point me to some explanation of Conv args in general as used in software, rather than math.
Also is there a way to print the dimentions/shapes of the layers and other information ?

**Comment by keunwoochoi** [comment]
1. nb: number. filter_length = conv kernel size it can be called as both filter or kernel.
2. My advice is to spend more time on tutorial - cs231n for example. Otherwise you WILL face more problems at the very next stage.
