### ISSUE TITLE
Some questions about the momentum term of SGD

### ISSUE THREAD

**Issue by ssiaw12345** [fchollet/keras#1475]
the get_updates method in class SGD,as follow:

def get_updates(self, params, constraints, loss):
        grads = self.get_gradients(loss, params)
        lr = self.lr * (1.0 / (1.0 + self.decay * self.iterations))
        self.updates = [(self.iterations, self.iterations + 1.)]

        for p, g, c in zip(params, grads, constraints):
            m = K.variable(np.zeros(K.get_value(p).shape))  # momentum
            v = self.momentum * m - lr * g  # velocity
            self.updates.append((m, v))

            if self.nesterov:
                new_p = p + self.momentum * v - lr * g
            else:
                new_p = p + v

            self.updates.append((p, c(new_p)))  # apply constraints
        return self.updates

the momentum term seems that it always only has zero elements because of the numpy function that np.zeros(). How does the parameter self.momentum make sense?

**Comment by lucienevans** [comment]
Yes, I agree with you that momentum is useless in the SGD.

Also, I think the m should be initialized in `__init__` function and updated in `get_gradients` function.

Can someone fix it?

**Comment by fchollet** [comment]
The momentum term is a constant. You would normally set it to 0.9, or a similar value reasonably close to one. It modulates the contribution of the previous update in the current update.

**Comment by gfgkmn** [comment]
Today i read source code, also find in SGD class, momentum is multiple with moments that always initial with zero. 
i have read this issue, but i didn't got it.
for clearly, i want to sure:
momentum is not used in keras, is it right?
``` 
    shapes = [K.get_variable_shape(p) for p in params]
    moments = [K.zeros(shape) for shape in shapes]    
    self.weights = [self.iterations] + moments        
    for p, g, m in zip(params, grads, moments):       
        v = self.momentum * m - lr * g  # velocity    
        self.updates.append(K.update(m, v))
```
