### ISSUE TITLE
Convolution2D(border_mode='full') used in examples but not allowed

### ISSUE THREAD

**Issue by udibr** [fchollet/keras#1477]
using `Convolution2D(64, 32, 3, 3, border_mode='full')` cause an assertion but it appears in VGG-like convnet example at http://keras.io/examples/

probably should be 'same' instead of 'full'

**Comment by KlaymenGC** [comment]
I think the ```full``` mode was removed in v0.3.0, you can add a ```ZeroPadding2D``` layer before the ```Convolution2D``` layer.

**Comment by fchollet** [comment]
This is fixed.
