### ISSUE TITLE
How to get the activation's output

### ISSUE THREAD

**Issue by meanmee** [fchollet/keras#1479]
I want to get  the output value of each activiation layer after each sample through it.

**Comment by farizrahman4u** [comment]
Let  X be your input. Let `model` be a `Sequential` model  with say, 10 layers. If you want to get the activation at the 8th layer, then:

```python
tmp = model.layers[:]
model.layers = model.layers[:8]
Y = K.eval(model(K.variable(X)))
model.layers = tmp
print(Y)
```

**Comment by fchollet** [comment]
Alternatively you could do something like:

```python
from keras import backend as K

layer = model.layers[8]
f = K.function([model.get_input(train=False)], [layer.get_output(train=False)])
print(f([x])[0])  # your activation tensor
```

**Comment by silentsnooc** [comment]
@fchollet I am trying this to get the activations of the model if I call the `predict()` function:

```python
layer = ae.model.layers[2]
f = K.function([ae.model.get_input(train=False)], [layer.get_output(train=False)])
print(f([v])[0])
```

Where `ae` is simply

```python
class WordEmbeddingEncoder:

    def __init__(self, nb_dimensions, nb_outputs):

        in_x = Input(shape=(nb_dimensions,))

        e_h1 = Dense(1024, activation='relu')(in_x)

        encoded = Dense(64, activation='relu')(e_h1)

        output = Dense(nb_outputs, activation='softmax', trainable=False)(encoded)

        self.model = Model(input=[in_x], output=[output])
        self.model.compile(optimizer='adam', loss='mse')
```

But it appears that the API changed as I get 

    AttributeError: 'Model' object has no attribute 'get_input'

So, how could I get the activation of a certain layer as I call the `predict()` function?

**Comment by silentsnooc** [comment]
Okay I think I figured it out myself

```python
tmp = ae.model.outputs
ae.model.outputs = [ae.model.layers[2].output]
y_pred = ae.model.predict(v)

# In case a restoration is needed one can do it
# but I think this has a huge performance impact
ae.model.outputs = tmp
ae.model.predict_function = None
```

**Comment by jbalma** [comment]
Just to tag onto this, I was able to print the output validations over my test set using the solution provided by @silentsnooc, but using multiple inputs (which I've had trouble getting to work). I've seen a few other examples where they use keras.backend.eval() on the model.layer[layer_name].output as is suggested in the documentation, but I haven't gotten this method to work. So thanks @silentsnooc for following up with a working solution to getting the actual activation output values. Here's what I did to print the activations to stdout:

--------------------------------------
...#Declare the model from two sets of layers called left_branch and right_branch
merged_branches = keras.layers.concatenate([left_branch, right_branch], axis=1)
final_layers= Dense(32, activation='linear', name='merge_fc1')(merged_branches)
final_layers = Dropout(.5)(final_layers)
final_layers = Dense(16, activation='relu', name='merge_fc2')(final_layers)
final_layers = Dropout(.5)(final_layers)
predictions = Dense(num_classes, activation='sigmoid', name="output_vals")(final_layers)

model = Model(inputs=[left_input, right_input], outputs=[predictions])
...
#In the epoch loop:

  # Test Set Evaluation.
  scores = model.evaluate([x_test, x_test_r], y_test, verbose=1)
  print( model.get_layer('output_vals').output ) 
  tmp = model.outputs
  model.outputs = [model.get_layer(layer_name).output]
  y_pred = model.predict([x_test, x_test_r])
  print(y_pred)
--------------------------------------

Which produces the following output for a single epoch:

Train on 600 samples, validate on 200 samples
Epoch 1/1
600/600 [==============================] - 16s - loss: 0.5712 - acc: 0.7083 - val_loss: 0.7051 - val_acc: 0.4400
192/200 [===========================>..] - ETA: 0s
Tensor("output_vals/Sigmoid:0", shape=(?, 2), dtype=float32)
[[ 0.3882978   0.48870558]
 [ 0.38873807  0.48904496]
 [ 0.38641962  0.48915014]
 [ 0.38890356  0.48918203]
 [ 0.38708338  0.48985761]
....

Thanks!
