### ISSUE TITLE
How to  convert list of 2D tensors to a 3D tensors?

### ISSUE THREAD

**Issue by farizrahman4u** [fchollet/keras#1484]
Hi. I am trying to make a  few changes to the `Recurrent` class so that if the `input_length` is provided, the RNN will be unrolled. Pseudo code:

```
X = input
X = K.permute_dimensions(X, (1, 0, 2))
input_length  = self.input_shape[1]
outputs = []
states = bla bla bla
for i in range(input_length):
    x = X[i]
    y, states = self.step(x, states)
    outputs.append(y)
if self.return_sequences:
     #TODO
else:
     return outputs[-1]
```
If  `return_sequences` = True, how  do  I  convert the `outputs`, which is a list of 2D tensors, to a  3D tensor? Should be using the Kears  backend functions.. no theano code.  Thanks.

cc: @fchollet

**Comment by fchollet** [comment]
You can use `T.concatenate(tensors, axis=1)`, followed by a `T.reshape`...

**Comment by farizrahman4u** [comment]
Ohh..Why didnt' I think of that..

**Comment by farizrahman4u** [comment]
It was actually `T.stack()` and `tf.pck()` btw.

**Comment by shaival2905** [comment]
I am doing same thing but not able to get it.
Please tell me the code.
Instead of:
outputs = []
states = bla bla bla
for i in range(input_length):
    x = X[i]
    y, states = self.step(x, states)
    outputs.append(y)

what should be done to create 3d tensor

**Comment by shaival2905** [comment]
how to use T.stack()

**Comment by Zhangtd** [comment]
If your list does not have too many elements, you can first use RepeatVector layer to expand every 2D tensor into 3D tensor, and then use Concatenate layer to merge them into one.

`t1 = RepeatVector(1)(t1)`
`t2 = RepeatVector(1)(t2)`
`T = Concatenate()([t1,t2])`
