### ISSUE TITLE
Skip connection implementation issue

### ISSUE THREAD

**Issue by zzjin13** [fchollet/keras#1486]
I want to implement the skip connection.
<code>
    model1 = Sequential()
    model1.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, mask_zero=True, init='normal'))

```
model2 = Sequential()
model2.add(model1)
model2.add(LSTM(hidden_layer_size, go_backwards=is_reverse, return_sequences=True))

model3 = Sequential()
model3.add(Merge([model1,model2], mode='concat'))
model3.add(LSTM(hidden_layer_size, return_sequences=False))
model3.add(Dropout(dropout_rate))

model3.add(Dense(output_dim=entity_size, init="normal"))
model3.add(Activation("softmax"))

model3.compile(loss='categorical_crossentropy', optimizer=SGD(lr=init_learning_rate, momentum=0.9, decay=0.95, nesterov=True))
```

</code>
And an error occurs.(Note that embedding_dim=1000,hidden_layer_size=256)
<code>
ValueError: dimension mismatch in args to gemm (128,1000)x(1256,256)->(128,256)
</code>
How can I solve this problem?

**Comment by zzjin13** [comment]
Now I use the Graph class, and the problem still exists.
<code>
    model = Graph()

    model.add_input(name='input', input_shape=(None,), dtype='int')

    model.add_node(Embedding(input_dim=vocab_size, output_dim=embedding_dim, mask_zero=True, init='normal'), name='embedding', input='input')

    model.add_node(LSTM(hidden_layer_size, go_backwards=is_reverse, return_sequences=True), name='lstm0', input='embedding')

    model.add_node(LSTM(hidden_layer_size, return_sequences=False), name='lstm1', inputs=['embedding', 'lstm0'], merge_mode='concat')

    model.add_node(Dropout(dropout_rate), name='dropout', input='lstm1')

    model.add_node(Dense(output_dim=entity_size, init="normal"), name='dense', input='dropout')

    model.add_node(Activation("softmax"), name='prob', input='dense')

    model.add_output(name='output', input='prob')
</code>
Is there something wrong with my code?

**Comment by mbotumbo** [comment]
No problems here running the code you provided. 
I think you are using theano, right? Have you updated keras/theano lately?

**Comment by lemuriandezapada** [comment]
well embedding is of size embedding_dim while LSTM is of size hidden_layer_size. If you're gonna do concat you must at least agree on one axis. By default it's -1 http://keras.io/layers/core/#merge so the last one. But you want to concat them over the time dimension which is 1. 
Or something similar. 
also I set the input shape to input_shape=[1] when working with embedding layers.

**Comment by mbotumbo** [comment]
@lemuriandezapada I don't want to correct you if I'm missing something, so can you expand on why you think @zzjin13 wants to concat on axis = 1 (or why -1 won't work)? 

I'll reiterate and clarify. No problems here running the code provided, including fitting the model (to some randomly generated data). embedding_dim doesn't need to match hidden_layer_size. Default concat executes fine (in fact, setting concat_axis to 1 won't work). Unspecified input shape is no problem, though I also generally set it to (sequence_length,)

I also decided to check to see if i could get the original sequential model based approach to also compile and fit, again, no problems, no modifications.
