### ISSUE TITLE
about epoch and batch generator

### ISSUE THREAD

**Issue by XuesongYang** [fchollet/keras#1489]
I am trying to implement my own code to feed in data batch-to-batch in memory: for each epoch, training process will get through all the batches. Each batch is iteratively drawn from some generator.

My question is that: since python generator can only be iterated through all elements once (no problem for one epoch), how can we make it happen if this generator is applied for multiple epoches? Thanks

**Comment by around1991** [comment]
Try something like:

```python
while True:
    for item in iterator:
        print item
```

This will restart the iterator whenever it finishes. Assuming your iterator can be called multiple times, this should do what you want.
