### ISSUE TITLE
AttributeError: 'module' object has no attribute 'relu'

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#1490]
Keras and Theano are all newest. I have used sudo pip install git+git://github.com/Theano/Theano.git. How can I solve this problem? Many thanks!

**Comment by Imorton-zd** [comment]
@fchollet  If you have time, could you help me solve this problem? Thanks

**Comment by lukedeo** [comment]
You might have an old version of Theano floating around that is getting priority during import time. Not really a Keras issue...

**Comment by Imorton-zd** [comment]
@lukedeo The editions of these tools are Theano-0.8.0 and Keras-0.3.1. If using theano only, there are not any problems. However, running imdb_cnn.py yielded this problem. Are there some suggestions? Thanks a lot
![1](https://cloud.githubusercontent.com/assets/13865086/12412839/20d4b936-bec5-11e5-928c-c25a52845550.png)

**Comment by around1991** [comment]
You need to get Theano from the git repo, not pip for the theano.nnet functions to be available.

**Comment by Imorton-zd** [comment]
@around1991  I indeed get Theano from the git repo by sudo pip install git+git://github.com/Theano/Theano.git

**Comment by tboquet** [comment]
Maybe it's because you are installing theano with pip pointing to another version of python. If sudo pip and pip are linked with two different version it might be the problem. Why are you using sudo?

**Comment by nouiz** [comment]
Uninstall Theano multiple time. You probably have an old version somewhere
that is causing conflict. Then make sure you can't import theano. Then
reinstall Theano.

Using pip with the git path install the development version.
