### ISSUE TITLE
K.rnn only supports 3D data

### ISSUE THREAD

**Issue by farizrahman4u** [fchollet/keras#1500]
The docstrings of `rnn` says atleast 3D, but only 3D input works because of the line `inputs = inputs.dimshuffle((1, 0, 2))`.  I need this to be fixed to test my `TimeDistributed` wrapper on 5D data(array of RGB images). #1456 .

CC:@fchollet

**Comment by fchollet** [comment]
Algorithmically there is no obstacle to supporting nD data, as you say it's
just the dimshuffle op. We could just change it.

**Comment by farizrahman4u** [comment]
Thanks!

**Comment by farizrahman4u** [comment]
#1512
