### ISSUE TITLE
Printing exception backtrace when using fit_generator

### ISSUE THREAD

**Issue by cassianokc** [fchollet/keras#1505]
When training NN by calling the fit_generator, exceptions/errors in the generator function are omitted since they are executing in a different thread. 
There are two possible solutions:
1) Instead of running the generator in Thread object, run it on a subclass which properly prints exception backtraces and errors.

2) Change the example on documentation to make it explicit that possible errors will be omitted and add a try: block on the example generator code

**Comment by fchollet** [comment]
keras/models.py, line 954. An exception is raised (and all threaded
processing is interrupted) when an error occurs in the generator.

**Comment by cassianokc** [comment]
Couldn't reproduce it, closing.
