### ISSUE TITLE
Merge variable inputs?

### ISSUE THREAD

**Issue by ppaanngggg** [fchollet/keras#1506]
I am achieving A Hierarchical Neural Autoencoder for Paragraphs and Documents.

The number of sentences in a paragraph varys. I wonder there is a way to merge variable inputs

**Comment by farizrahman4u** [comment]
You are not providing enough information for us to help you! What you mean by merge? In Keras context merge means to combine 2 tensors with some op, like + or *. Are you looking for masking/padding?
