### ISSUE TITLE
Merge fails on GPU but passes on CPU

### ISSUE THREAD

**Issue by vzhong** [fchollet/keras#152]
Hi,

I've noticed a problem using `Merge` on `Sequential` networks with flattened `Embedding`s. The context of the problem is as follows:

I have two embedding tables, for each example, I'd like to look up 1 embedding from table 1 and two embeddings from table 2 and concatenate the three embeddings together. While this works on the CPU, it fails on the GPU with the following error:

```text
ValueError: GpuJoin: Wrong inputs for input 1 related to inputs 0.!
Apply node that caused the error: GpuJoin(TensorConstant{-1}, GpuReshape{2}.0, GpuReshape{2}.0)
Inputs types: [TensorType(int8, scalar), CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(), (2, 2), (2, 4)]
Inputs strides: [(), (2, 1), (4, 1)]
Inputs values: [array(-1, dtype=int8), <CudaNdarray object at 0x11766c0f0>, 'not shown']

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

I've made a unittest for my model demonstrating this problem [here](https://github.com/vzhong/keras/blob/master/test/test_embeddings). Using a GTX760, the first two tests (single embedding lookup and double embedding lookup) pass while the third test fails with the above error.

I think I've tracked down the discrepancy to `Merge`'s `T.concatenate(..., axis=-1)`. This problem goes away if `axis=1` in this particular case. I'm not sure that the cause of this particular error is a Keras issue, as it doesn't exist on the CPU.

**Comment by vzhong** [comment]
Ok, I found the Theano problem that causes this Theano/Theano#2613. It seems like this was discovered rather recently, and have not been incorporated into a release yet. After deleting my Pypi Theano and installing it from git to get the bleeding edge, this problem no longer persists. 

I'm not sure whether this is worth "fixing" here. For future reference, if someone else has this problem they can just fix it by moving to the git version of Theano instead of the latest Pypi release.

**Comment by fchollet** [comment]
Correct, it was a Theano bug with T.Concatenate(). It has been fixed in the dev version of Theano a few weeks ago, and it will be on Pypi soon. Not worth fixing on the Keras side...
