### ISSUE TITLE
Memory error in data augmentation

### ISSUE THREAD

**Issue by awhitesong** [fchollet/keras#1531]
I am running data augmentation on image sample of 1000 227 * 227 * 3  images in 8GB memory.

running `free` at the time of training gives 5Gb memory free. when `datagen.fit()` is called i still have about 3.5gb memory free.

                 total       used       free     shared    buffers     cached
    Mem:       8085564    4139904    3945660     152380     136096     958264
    -/+ buffers/cache:    3045544    5040020
    Swap:      8298492          0    8298492

 
But it gives this error everytime: 
`File "build/bdist.linux-x86_64/egg/keras/preprocessing/image.py", line 244, in fit
MemoryError`
which is the line 
`sigma = np.dot(flatX.T, flatX) / flatX.shape[1]`

I reduced the sample size to half, still the same problem. Its showing memory error even with 50 image samples.

someone else got the same problem here http://stackoverflow.com/questions/33547128/keras-image-augmentation-error. no solution yet. 
How should i be fixing this? I need to do zca_whitening. How large should the sample size be? I am including one sample from each class atleast.

**Comment by jocicmarko** [comment]
If you calculate the memory needed for dot product, it's (227*227*3)^2, which is 23,897,140,569 floats (32-bit = 4B), which leads to ~89GB needed memory... So, 8GB won't do :)
With your memory, you could try with 64x64 images.

**Comment by denizn** [comment]
@jocicmarko So does this mean it's impossible to do ZCA Whitening on even a top end GPU at the moment? I have been trying to do this for even a single image of 299x299 and it doesn't have enough memory??? How do people execute this?
