### ISSUE TITLE
How to use pre_trained word2vec as the input for text classification?

### ISSUE THREAD

**Issue by FRDCcdj** [fchollet/keras#1544]
Hi, all, I'm a keras newer, when I run the example imdb_cnn.py and imdb_lstm.py, I want to use the pre_trained word2vec (very large) as the input, how should I do? Thanks!

**Comment by WengerWatch** [comment]
That's a great question ! I've been wondering the same thing for a while now !

**Comment by jgc128** [comment]
You can initialize the weights of the Embedding layer with word2vec vectors: #853

**Comment by medrifter** [comment]
you can refer to "https://github.com/nicolas-ivanov/debug_seq2seq.git"
