### ISSUE TITLE
A Neural Turing Machine to texts classification using Keras

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#1546]
I just read the Keras Documentation, in which I meet one sentence "Building a network of LSTMs, a deep CNN, a Neural Turing Machine, a word2vec embedder or any other model is just as fast".
Had someone implement a Neural Turing Machine to process texts using Keras? Could you let me study the codes and method? Thanks a lot.

**Comment by lemuriandezapada** [comment]
If I recall right it was removed from the repo some time ago

**Comment by cmyr** [comment]
see #1520

**Comment by EderSantana** [comment]
check this out and let me know if works for you:
https://github.com/EderSantana/seya/blob/master/examples/NTM.ipynb
