### ISSUE TITLE
explicit/corresponding labels of a prediction 

### ISSUE THREAD

**Issue by WengerWatch** [fchollet/keras#1547]
Hi guys ! I'm fairly new to keras, and was wondering how I can get the explicit labels of a prediction after I train my model. Let me illustrate my issue:
I train my model with the classic X_train and y_train, and y_train is an array whose form is array([[ 1.,  0.,  0.], [ 0.,  1.,  0.], ..., [ 0.,  1.,  0.]). But when I test it with the X_test matrix, I get y_pred = array([0, 0, 2, ..., 1, 1, 1]) . 

Do you have a way to connect the dots? So that I know that 0 corresponds to [1.,0.,0.], 1 corresponds to [0.,1.,0.], etc 

Thanks in advance for your help !

**Comment by ymcui** [comment]
Hi, could you please post your code?
And what do you mean by "connect the dots", i didn't quite get this.
Actually, `y_pred` has already indicate the index of the predictions.
