### ISSUE TITLE
How can I use 'theano.shared(..., borrow=True)'?

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#1548]
Executing cnn yields this error: MemoryError: ('Error allocating 255974400 bytes of device memory (out of memory).', "you might consider using 'theano.shared(..., borrow=True)'")
Please give me an example. I am using GTX950 and have configured GPU well. Thanks.

**Comment by ymcui** [comment]
Hi,
This is an error that your GPU memory cannot satisfy your needs.
Try using a lower `batch_size` and `dimensions` of hidden layer

**Comment by jesuisnicolasdavid** [comment]
I have the same issue than @Imorton-zd, is there a way to set up this parameter through keras ? I just tried through the tensorflow backend : 

> ValueError: Cannot create an Operation with a NodeDef larger than 2GB.

**Comment by nouiz** [comment]
This won't help on the GPU, as we need to allocate it on the GPU. You are
tring to allocate 244MB of memory. On a 2GB GPU card, it is big. Your model
is probably too big. Just make it smaller (or use a GPU with more ram).

**Comment by Imorton-zd** [comment]
@jesuisnicolasdavid   this parameter needn't to be set, you just  configuration the theano on GPU accurately according to some configuration notes online. And your model may be too big, you could decrease several parameters or layers.

**Comment by jesuisnicolasdavid** [comment]
The file is a pre-train word2vec on wikipedia dump and is about 9GB that i am using through an embedding layer, i run into a GPU memory error with theano/tensorflow through keras which said : 

> _Theano :_
> ('Error allocating 4604368000 bytes of device memory (out of memory).', "you might consider using 'theano.shared(..., borrow=True)'")

> _Tensorflow:_
> ValueError: Cannot create an Operation with a NodeDef larger than 2GB.

As you wonder, i already reduce the batch size but the dimension is stuck to 1000. I am using https://github.com/idio/wiki2vec

Do you think there is a way to find a solution ?

**Comment by abhinavbh08** [comment]
I also have the same problem. Can anyone provide the solution. I am using Titan X gpu with 12GB Memory. But it is only showing 1.8 GB free while my network needs 3.6 GB.? What to do ? By the way I am using the GPU via SSH to a remote server ?

**Comment by nouiz** [comment]
If you use the Theano flag lib.cnmem=0.8, then Theano will pre alloc 80% of
the total GPU memory size.

The system also need temp memory for the computation. During the forward,
we need to keep some intermediate results that get reused for the gradient.
This can raise the memory usage.

This doc section give some option to lower memory usage:

http://deeplearning.net/software/theano/faq.html#theano-memory-speed-trade-off

But the simplest solution is to lower the batch size.

**Comment by NickYi1990** [comment]
@abhinavbh08 restart you notebook and just run it, you will find some batch size you can not run can run now!
