### ISSUE TITLE
Training a LRCN using video data.

### ISSUE THREAD

**Issue by KeironO** [fchollet/keras#1550]
Good afternoon,

I have written the following code to vectorise video data into an ndarray.
```python
import cv2, numpy as np, random, csv, os
from scipy import misc

def load_labels_and_file_name(tsv_file, directory):
    tsv_list = []
    with open(tsv_file, "rb") as tsv:
        reader = csv.reader(tsv, delimiter="\t", lineterminator="\n")
        for files in reader:
            if os.path.isfile(directory+"/"+files[0]) == True:
                tsv_list.append(files)
            else:
                print "Not found!"
        return tsv_list

def load_video_vector(directory, tsv_file, height, width):
    labels_file_name = load_labels_and_file_name(tsv_file, directory)
    number_of_videos = len(labels_file_name)
    n_channels = 1 #grayscale
    data = np.empty((number_of_videos, n_frames, n_channels, height, width), dtype="float32")
    data.flatten()
    labels = np.empty((number_of_videos, ), dtype=np.dtype("a16"))
    for i, details in enumerate(labels_file_name):
        video = cv2.VideoCapture(directory+details[0])
        for x in range(n_frames):
            return_value, frame = video.read()
            if return_value == False:
                break
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            frame = misc.imresize(frame, (height, width))
            data[i:x:n_channels,:,:,:] = frame
            labels[i] = details[1]
    return data, labels

if __name__ == "__main__":
    n_frames, height, width = 50, 64, 64
    data, labels = load_video_vector("/home/keo7/.data/pouch_of_douglas/", "/home/keo7/.data/pouch_of_douglas/labels.tsv", height, width)
    np.random.seed(1337) # Reproducible results

    print data.shape
```

The shape of this is returned as (52, 50, 1, 64, 64), where 52 is the total number of videos, 50 being the number of frames of each video, 1 representing the number of channels and 64, 64 being the height and width respectively.

How can I feed this into a LRCN using the Keras deep learning framework?

Thank you,

Keiron.

**Comment by KeironO** [comment]
Still no response, so I was wondering how best could I get this question answered?

**Comment by aezco** [comment]
@KeironO Did you find a solution>

**Comment by KeironO** [comment]
@aezco I did, yes. I'll soon make public the git repository which I did this work in for you to take a look at.

**Comment by KeironO** [comment]
Here you go:

https://github.com/KeironO/podc/

Here's some code to get frames from video:

https://github.com/KeironO/podc/blob/master/podc/data/video.py

And here's some code for a lightweight LCRN model that I use for testing purposes:

https://github.com/KeironO/podc/blob/master/podc/deeplearning/models.py#L162-L200

**Comment by aezco** [comment]
@KeironO Thanks. One final question about your dataset? how does the structure lookalike? If I check the videogenerator, you are loading a json file with label and video id's. For example: 


Folder structure: 
```
- video1

-- Frame1.jpg
-- Frame2.jpg
-- FrameN.jpg

- video2

-- Frame1.jpg
-- Frame2.jpg
-- FrameN.jpg

- videoN

-- Frame1.jpg
-- Frame2.jpg
-- FrameN.jpg
```

How does the json file look like (https://github.com/KeironO/podc/blob/eb73cf9ecd065757a2ffd69b680fd65aa92ac303/podc/pouch_of_douglas_classifier.py#L35):

something like?  
```
- video 1, 50 frames, label "cat" 
- video 2, 30 frames, label "dog" 
- video N, 45 frames, label "cat" 

```

**Comment by KeironO** [comment]
I really should be cracking on with my own work, but seeing as you seem nice:

I can't quite remember off the top of my head as this is a dead project atm, but the video_ids = dict.keys() indicates that it looks like:

```json
{
    "video_one.mp4" : "dog",
    "video_two.mp4" : "cat"
}
```

The frames are dealt with my the class.

> Also how can I display single frame or load single data from the VideoDataGenerator such as x,y = next(train_vg) for displaying image-label?

Have you used matplotlib before?
