### ISSUE TITLE
ImageDataGenerator.flow does not re-shuffling before every epoch

### ISSUE THREAD

**Issue by udibr** [fchollet/keras#1551]
when shuffle=True in ImageDataGenerator.flow
there is a single shuffle and then the generator never terminates.
Repeating the same shuffle again and again.
It should reshuffle before every epoch.

If seed is also given then this should some ensure that overhaul the sequence will be the same.
For example, the per epoch shuffle could be seeded with the seed and an epoch counter

**Comment by fchollet** [comment]
Right. This would be easy to implement, can you open a PR?

**Comment by udibr** [comment]
even worse! there is a bug because I'm over stepping `seed`

**Comment by thebeancounter** [comment]
Is it the behavior now? @udibr 
does it re shuffle each iteration of flow_from_dataframe (inside the batches)? am i getting the same batches in different order, or am i getting completely new batches each time?
