### ISSUE TITLE
TypeError: float32 and float64 when using dot operation to merge layers

### ISSUE THREAD

**Issue by getao** [fchollet/keras#1555]
Hi,
I found that when I merge the output of a LSTM layer which return sequences and another matrix using 'dot' mode, I will got this type error. I think this may happen because of the dot operation. Could you help me fix this problem?

Thanks,

TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by ymcui** [comment]
Hi,
Maybe you should try to set your input data as `numpy.array(dtype=float32)`?
and if it is possible, please post your source code.
