### ISSUE TITLE
tributeError: 'PReLU' object has no attribute 'alphas'

### ISSUE THREAD

**Issue by suraj-deshmukh** [fchollet/keras#1562]
I am trying to use PReLU advance activation function but model.compile is giving "tributeError: 'PReLU' object has no attribute 'alphas'" error. 
Please help me.
Thank you in advance

**Comment by ymcui** [comment]
There is no attribute called `alphas` in `PReLU`.
`keras.layers.advanced_activations.PReLU(init='zero', weights=None)`
see http://keras.io/layers/advanced_activations/

**Comment by suraj-deshmukh** [comment]
look at https://github.com/fchollet/keras/blob/master/keras/layers/advanced_activations.py#L38 this
in get_output method

**Comment by ymcui** [comment]
@suraj-deshmukh 
see line 60~63
    def build(self):
        input_shape = self.input_shape[1:]
        self.alphas = self.init(input_shape)
        self.params = [self.alphas]
`self.alphas` is defined by `input_shape`

**Comment by suraj-deshmukh** [comment]
[ConvNet.txt](https://github.com/fchollet/keras/files/106133/ConvNet.txt)
I have attached my code. Please tell me where i am making mistake.
when i run this code i get "AttributeError: 'PReLU' object has no attribute 'alphas'" this type of error.

**Comment by suraj-deshmukh** [comment]
for the same code LeakyReLU is working fine but not PReLU

**Comment by ymcui** [comment]
change all 
`model.add(Activation(PReLU()))`
to
`model.add(PReLU())`
works fine for me. give it a try.

**Comment by suraj-deshmukh** [comment]
@ymcui 
It worked.:)
Thank You
