### ISSUE TITLE
Masked RNNs return zero vectors for masked inputs and not a valid state

### ISSUE THREAD

**Issue by around1991** [fchollet/keras#1569]
Hi all

Is there a way to change the behaviour of RNNs with masking so that masked values output the most previous valid state rather than the zero vector? This means we can pad at the end of variable length sequences, which is a little bit easier than pre-padding. Also, it makes a forward-backward RNN model slightly easier to implement, which helps to implement some sequence-to-sequence stuff.

In addition, why is masking only applied if return_sequences is set as True?  I can see why this is the sensible thing to do if padding values return 0 (as otherwise you'll just get 0's at the end), but if you return the most recent valid state I think there's a reasonable use case for masking to always be applied.

Thanks
Kris

**Comment by fchollet** [comment]
> n addition, why is masking only applied if return_sequences is set as True?

Masking is always applied, independently from `return_sequences`.

> so that masked values output the most previous valid state rather than the zero vector?

This is already the case.

**Comment by around1991** [comment]
Sorry, I was working off an older version of Keras. Just rebased and picked up the changes.

Thanks for the heads up!
