### ISSUE TITLE
Backends

### ISSUE THREAD

**Issue by lifeng1989** [fchollet/keras#1570]
I want to add a new backend ,such as mxnet . where can i get a tutorial?  Thank you.

**Comment by fchollet** [comment]
It's simple.

Here is the TensorFlow backend: https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py

Here is the Theano backend:
https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py

They both implement the same 73 basic functions. All you have to do is reimplement these same functions with MXnet (or something else). Then you will be able to run Keras on top of it.

Probably over 80% of the functions will be trivial to implement, but some might require some research (e.g. `rnn`).
