### ISSUE TITLE
Can't constraint the bias for Zero?

### ISSUE THREAD

**Issue by thippo** [fchollet/keras#1575]
there are three constraint:
maxnorm(m=2): maximum-norm constraint
nonneg(): non-negativity constraint
unitnorm(): unit-norm constraint, enforces the matrix to have unit norm along the last axis
No zero?

by the way? How can I use no bias?
thank!

**Comment by fchollet** [comment]
> by the way? How can I use no bias?

Create your own layers with no bias, it's really easy...

**Comment by thippo** [comment]
oh, I see.
but which argument can be used to create layer with no bias?

such as Dense layer:
```
output_dim
init
activation
weights
W_regularizer
b_regularizer
activity_regularizer
W_constraint
b_constraint
input_dim
```
seemingly none of them.
thanks!

**Comment by the-moliver** [comment]
Alternatively you could write your own constraint function, which is also really easy.

**Comment by lemuriandezapada** [comment]
Any. 
Just go into the codebase and copy a class definition and give it a new name. 
Then remove any self.b from self.params (and maybe also from the compute stage in the step function to speed shit up)
Then just reinstall keras and you're all set to use your new layer

**Comment by thippo** [comment]
hum, still need to do it myself anyway.
Thanks a lot!
