### ISSUE TITLE
Embedding layer and Constraints

### ISSUE THREAD

**Issue by pminervini** [fchollet/keras#1580]
Dear everyone,
what follows is not really a bug, but IMO it can be considered a sort of counter-intuitive behavior.

When enforcing unitary norm constraints on an embedding layer, the constraints are enforced on the columns of the embedding matrix (the embedding vector dimension) instead of the rows (the no. of embedding vectors).

 For instance consider the following setting, in which we have two embedding vectors of size 10:

``` python
import numpy as np
from keras.models import Sequential
from keras.layers.embeddings import Embedding
from keras.layers.core import Flatten, TimeDistributedDense, Activation

from keras.constraints import unitnorm

model = Sequential()
embedding_layer = Embedding(input_dim=2, output_dim=10, input_length=1, W_constraint=unitnorm())
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(output_dim=1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adagrad')
model.fit(np.array([[0]]), np.array([0]), batch_size=1, nb_epoch=5, verbose=0)

embedding_matrix = embedding_layer.params[0].get_value()

print(embedding_matrix.shape)
print(np.linalg.norm(embedding_matrix[1, :]))
print(np.linalg.norm(embedding_matrix[:, 1]))
```

The unitary norm is enforced on each column of the matrix; in my opinion, it could make sense to enforce it on its rows (the actual embedding vectors).

``` bash
(2, 10)
2.25984
1.0
```

At the moment I'm working around this by using a custom Constraint:

``` python
class FixedNorm(Constraint):
    def __init__(self, m=1.):
        self.m = m

    def __call__(self, p):
        p = K.transpose(p)
        unit_norm = p / (K.sqrt(K.sum(K.square(p), axis=0)) + 1e-7)
        unit_norm = K.transpose(unit_norm)
        return unit_norm * self.m

    def get_config(self):
        return {'name': self.__class__.__name__, 'm': self.m}
```

**Comment by tstandley** [comment]
Just to be clear, the current constraint is that each word vector have unit length, right?

Rather than the ith dimension of all the word vectors is unit?

The second case seems crazy to me. If you have 10k word vectors in your embedding, each word vector would be nearly the zero vector. Why would that be good?

I just want to make sure that the current behavior is the first, rather than the second.

**Comment by tstandley** [comment]
Ok, after experimenting, it is indeed the second way. So strange. Maybe I'm missing something, but I don't see how that's ever useful. Thanks @pminervini for bringing it to my attention and offering a solution! Don't forget to make the necessary imports:

```
from keras.constraints import Constraint

from keras import backend as K
```

**Comment by pminervini** [comment]
Thanks @tstandley, I'm glad I was not hallucinating.

I think in some architectures it's really useful to impose constraints on the embedding vector layer, for avoiding trivial solutions for the loss minimization problem (e.g. you can increase the distance between two vectors by simply increasing their norm).

**Comment by eshijia** [comment]
Glad to see this discussion. It was really helpful to implement some representation learning tasks of knowledge graph.

**Comment by pminervini** [comment]
Same! All the problems I've run into were because I was implementing KG embedding models :) (the last one was an issue with cascades of Merge layers)

I'm glad this topic is getting attention; feel free to contact me if you feel like you want to discuss something!

**Comment by eshijia** [comment]
Yes. I am trying to implement some basic models of KG embedding such as TransE with Keras. Hope it can reproduce the results in the paper.

**Comment by pminervini** [comment]
Actually you can achieve much better results than the original NIPS'13 paper, by simply switching from SGD to Adagrad.

Some up-to-date numbers (and models) are available here: http://jmlr.org/proceedings/papers/v48/trouillon16.pdf

**Comment by shaifugpt** [comment]
@pminervini Where did you code your custom constraint? is it in the same file. In my custom constraint and while using yours also I get error TypeError: Error when calling the metaclass bases
    list() takes at most 1 argument (3 given)

**Comment by mdmustafizurrahman** [comment]
@eshijia  Can you share your TransE implementation in Keras here please??

**Comment by eshijia** [comment]
@mdmustafizurrahman You can check this [repo](https://github.com/eshijia/knowledge-graph-keras).  That is not a perfect implementation. I just rewrote some codes based on some [QA models](https://github.com/codekansas/keras-language-modeling). Maybe that repo doesn't fit the current release of Keras. I don't have enough extra time to implement the perfect Keras version of TransX. Recently, there is an [implementation](https://github.com/jimmywangheng/knowledge_representation_pytorch) in PyTorch, I think maybe that is a better reference than the [Tensorflow implementations](https://github.com/thunlp/OpenKE). Hope to see your implementation in Keras.

**Comment by mdmustafizurrahman** [comment]
@eshijia Hey thanks for sharing this. And sorry for my late reply I did not check earlier.
