### ISSUE TITLE
theano.scan() unused in keras source?

### ISSUE THREAD

**Issue by TheDiscoMole** [fchollet/keras#1584]
Hi,

Shouldn't theano.scan() be used for things like the get_output() in Graph containers and such? Would theano be able to (GPU) optimize such functions if scan() was used instead of normal python dictionary iterations?

**Comment by EderSantana** [comment]
this was discussed before:
https://github.com/fchollet/keras/issues/954

the unrolled scan is actually faster

**Comment by nouiz** [comment]
I still see it in keras/backend/theano_backend.py in the method rnn. I
don't see the code to unroll it in keras, did I miss it?

If you want a number of step that change at each call, in Theano, you must
use scan.

**Comment by fchollet** [comment]
Right. Only the TensorFlow version is unrolled, and that is why you can't use variable-length sequences with the TensorFlow backend. In the future a new solution for handling variable-length sequences will be released in TensorFlow, and we will bring it into Keras.
