### ISSUE TITLE
cannot import name LRN2D

### ISSUE THREAD

**Issue by bhaveshoswal** [fchollet/keras#1588]
I am new to keras and trying to import LRN2D normalization in keras(v0.3.1) but showing me following error ( theano version is 0.8 dev and also have installed pylearn2 separately )

**from keras.layers.normalization import LRN2D**
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-41427d34359b> in <module>()
----> 1 from keras.layers.normalization import LRN2D

ImportError: **cannot import name LRN2D**

please tell what to do know
Thank you

**Comment by keunwoochoi** [comment]
It is removed.

**Comment by ymcui** [comment]
It is no longer exist in current version of Keras

**Comment by bhaveshoswal** [comment]
ok thanks

**Comment by danieljl** [comment]
Why was it removed?
