### ISSUE TITLE
show_accuracy for graph models

### ISSUE THREAD

**Issue by faroit** [fchollet/keras#1589]
Is there a specific reason why the graph model accepts validation data but does not have the ability to show the class accuracy during training?

For now I could solve this by passing a custom callback to compute the accuracy. But maybe this would be nice having it built in.

Is there something in the works or can I help out here?

**Comment by ymcui** [comment]
check this one. #611

**Comment by faroit** [comment]
Ok, sorry. Got it. I'll wait until #1282 is merged, so I can switch back to the sequential model then.
