### ISSUE TITLE
Error when using TimeDistributedDense

### ISSUE THREAD

**Issue by lileicc** [fchollet/keras#159]
I got the following error when using GRU connected to TimeDistributedDense then get_output().

ValueError: get_scalar_constant_value detected deterministic IndexError: x.shape[2] when x.ndim=2.x=Subtensor{int64}.0

Any hint to fix it?
Thanks!

**Comment by fchollet** [comment]
Do you have any code to repro this?

**Comment by lileicc** [comment]
```
    emb = Embedding(num_tokens, word_vec_dim)
    output_layer = TimeDistributedDense(word_vec_dim, num_tokens, activation='time_distributed_softmax')
    output_layer.connect(emb)
    output = output_layer.get_output(train=True)
```

Error:
```
ValueError: get_scalar_constant_value detected deterministic IndexError: x.shape[2] when x.ndim=2.x=Subtensor{int64}.0
```

**Comment by Kazjon** [comment]
This is happening to me too, with the following code (a modification of the Nietzsche example to output sequences):
```python
model = Sequential()
model.add(LSTM(len(chars), 512, return_sequences=True))
model.add(Dropout(0.5))
model.add(LSTM(512, 512, return_sequences=True))
model.add(TimeDistributedDense(512, len(chars), activation='time_distributed_softmax'))

model.compile(loss='binary_crossentropy', optimizer='rmsprop')
```

At first I thought it was my choice of loss (as categorical_crossentropy says it won't work for sequence outputs), but it seems to happen with any loss or optimiser.

**Comment by Kazjon** [comment]
OK, new discovery: this does *not* happen if you separately add an Activation to the stack, as in:

```python
model = Sequential()
model.add(LSTM(len(chars), 512, return_sequences=True))
model.add(Dropout(0.5))
model.add(LSTM(512, 512, return_sequences=True))
model.add(TimeDistributedDense(512, len(chars)))
model.add(Activation('time_distributed_softmax'))

model.compile(loss='binary_crossentropy', optimizer='rmsprop')
```

(As an aside for anyone more familiar with RNNs than me: what loss should I be using for sequence softmax output?)

**Comment by fchollet** [comment]
> As an aside for anyone more familiar with RNNs than me: what loss should I be using for sequence softmax output?

In this case you should be using `categorical_crossentropy`. What you are using, `binary_crossentropy`, will only work for an output of size 1.

**Comment by Kazjon** [comment]
Thanks -- I'll make sure to change that.

Along that line, though, there's a snippet in the docs that made me shy away from categorical crossentropy:

> Note: using this objective requires that your labels are binary arrays of shape (nb_samples, nb_classes).

I interpreted that as meaning it wouldn't work with the (nb_samples, nb_timeseps, nb_classes) output from TimeDistributedDense -- it seems from messing around with it, and from other code snippets I've seen around, that it actually works just fine.
