### ISSUE TITLE
Universal axis parameter for Merge

### ISSUE THREAD

**Issue by pasky** [fchollet/keras#1595]
Wouldn't it make more sense, rather than having specific concat_axis and dot_axes parameters, to have a general axis specification of what shapes should merge operate on?  The semantics might be tricky for dot_axes, but for concat_axis, I don't see why that needs to be specific for concat.

For example, right now I'd need a model that could produce a time series by summing up two other time series timepoint-wise, and I see no easy way to do that - I'd like something like ``merge_mode='sum', merge_axis=1``. I hope I'll figure out how to do that using LambdaMerge but it seems a bit scary for such a simple operation...

**Comment by fchollet** [comment]
We considered this initially. The different usage syntax means it is clearer not to reuse the same keyword twice (or more), in terms of UX. 

You should consider using `LambdaMerge`, which isn't scary.

**Comment by farizrahman4u** [comment]
`concat_axis` and `dot_axes` are different things. `dot_axes` could be a list/tuple but `concat_axis` is always an integer. Also, I didn't  quite catch what you are trying to do. You  have  got 2 3D layers(2  timeseries) and you want to add them, is it? Just merge with `mode='sum'`. If this is not what you want,  then provide an example.

**Comment by pasky** [comment]
@farizrahman4u you are right, I was terribly confused about sum, mul, ave as I started out with timewise dot-products and these are probably the only problematic ones. mul works just fine! (In case someone needs to timewise multiply vector by scalar, RepeatVector(dim) and Permute((2,1)) first.)

So if anyone else finds LambdaMerge scary, this is an example of using it for elementwise dot-product (for example to generate token attentions):

```python
    def batched_batched_dot(s):
        """ from (x,y,z)-shaped pair, produce (x,y)-shaped pair that replaces the z-vector pairs by their dot-products """
        import theano
        import theano.tensor as T
        return theano.scan(fn=lambda xm, ym: T.batched_dot(xm, ym),
                           outputs_info=None, sequences=s, non_sequences=None)[0]
    model.add_node(name='esa[0]',  # nested batched_dot
               layer=LambdaMerge([model.nodes['e0sa'], model.nodes['e1sa']],
                                 batched_batched_dot,
                                 lambda s: (s[1][0], s[1][1])))
```

(hope I got it right; it seems to work).
