### ISSUE TITLE
How to get every states of the rnn(like lstm, gru unit) network in the procedure of predicting a sample?

### ISSUE THREAD

**Issue by dvector89** [fchollet/keras#1598]
Dear everyone,
        I had used Keras to conduct a rnn network and ran it well. But I want to look the every states of the rnn, when it predicts a sample. Do you know how to print the states, when the model predicts? Thank you very much.

**Comment by pasky** [comment]
return_sequence=True should do what you need, I think - it returns a new sequence that represents the state at every step of the input sequence.

**Comment by dvector89** [comment]
@pasky Thank you. I know the parameter "return_sequence", but I want to print the value of state at very step when model predicts a sample,not in the process of training model.
