### ISSUE TITLE
Problem with cifar10_cnn.py example

### ISSUE THREAD

**Issue by MCin22** [fchollet/keras#1599]
I've tried to run cifar10_cnn.py example on Python 2.7.6 (32 bit) with libraries like the newest Theano (0.80dev) on Windows 8.1 64-bit; I'm not using cuDNN. The project terminates every time I try to run this example. I've tried to run imdb_cnn.py but still got the similiar problem. 

> X_train shape: (50000, 3, 32, 32)
50000 train samples
10000 test samples
Not using data augmentation.
Train on 50000 samples, validate on 10000 samples
Epoch 1/200

> Process finished with exit code -1073741819 (0xC0000005)

My friend did a project with Multilayer Perceptron and it worked on my PC, but when there are these two examples with Convolve layers, the projects terminate. What could be the cause of it? Maybe someone had similiar problem?

EDIT: I checked example mnist_mlp.py and haven't got any problem with terminating script.

EDIT2: It was probably something with my operating system and its configuration or installed libraries, because I installed Linux and everything worked.

**Comment by xdr940** [comment]
so it

> I've tried to run cifar10_cnn.py example on Python 2.7.6 (32 bit) with libraries like the newest Theano (0.80dev) on Windows 8.1 64-bit; I'm not using cuDNN. The project terminates every time I try to run this example. I've tried to run imdb_cnn.py but still got the similiar problem.
> 
> > X_train shape: (50000, 3, 32, 32)
> > 50000 train samples
> > 10000 test samples
> > Not using data augmentation.
> > Train on 50000 samples, validate on 10000 samples
> > Epoch 1/200
> > Process finished with exit code -1073741819 (0xC0000005)
> 
> My friend did a project with Multilayer Perceptron and it worked on my PC, but when there are these two examples with Convolve layers, the projects terminate. What could be the cause of it? Maybe someone had similiar problem?
> 
> EDIT: I checked example mnist_mlp.py and haven't got any problem with terminating script.
> 
> EDIT2: It was probably something with my operating system and its configuration or installed libraries, because I installed Linux and everything worked.

i have the same problem, so i have to change my windows to linux?T T??

**Comment by xdr940** [comment]
I changed the number of convolution kernels of several convolutional layers to a other number which are not power of 2 ，and it works???!!!!!!? ? ? ! ! !why!?!?!?!?!?!,who can tell me, this is too strange！！
