### ISSUE TITLE
ImageDataGenerator with regression problem

### ISSUE THREAD

**Issue by gregLibert** [fchollet/keras#1614]
Dear all,

I would like to use ImageDataGenerator with a regression problem (detect facial key points - https://www.kaggle.com/c/facial-keypoints-detection). By looking at the code I've got the feeling that_ y_ value is not modified when images are transformed. 
Is that true ? 
If so are you planning to support a kind of regression mode in parallel to the classification one

**Comment by udibr** [comment]
true

**Comment by gregLibert** [comment]
If you are interested I did some small modifications to handle that use case for rotation, shift and flipping. You can find modified preprocessing image here (https://github.com/gregLibert/keras/blob/master/keras/preprocessing/image.py) or I can pull it ...
