### ISSUE TITLE
Predicting sequence with recurrent output layer does not work

### ISSUE THREAD

**Issue by jfsantos** [fchollet/keras#163]
I made a simple model with a 1 cell LSTM to predict the next number in a sequence given the current number (not for any practical reasons, this is just to demonstrate the bug). Here's the code:

```
from keras.models import Sequential
from keras.layers.recurrent import LSTM

import numpy

# Dataset has a single sample just to make things simpler
x1 = numpy.random.randn(100)
X_train = numpy.empty((1,len(x1)-1, 1)) #  (# samples, # timesteps, # features) 
Y_train = numpy.empty((1,len(x1)-1, 1))

X_train[0,:] = x1[:-1]
Y_train[0,:] = x1[1:]

model = Sequential()
model.add(LSTM(1, 1, activation='sigmoid', inner_activation='hard_sigmoid', return_sequences=True))

model.compile(loss='mean_squared_error', optimizer='sgd')
model.fit(X_train, Y_train, batch_size=1, nb_epoch=10)
```

But running this fails during the compile step, with the following error message:

```
TypeError: Cannot convert Type TensorType(float64, (False, True, True)) (of Variable 
IncSubtensor{Set;:int64:}.0) into Type TensorType(float64, (False, False, True)). You can try to manually
 convert IncSubtensor{Set;:int64:}.0 into a TensorType(float64, (False, False, True)).
```

I remember that a while ago we had to pass a parameter to `compile` to say how many dimensions the targets have, but it was removed and now `compile` uses `T.zeros_like(self.y_train)` to set the output dimension.

Am I doing something wrong or is this a bug?

**Comment by fchollet** [comment]
It doesn't look like you are doing anything wrong, so this must be a bug (either Keras or Theano...). 

I don't get this issue when using more than one feature; the issue arises specifically with the input/output shape `(samples, time, 1)`. The issue happens at the scan step on the LSTM layer.

**Comment by fchollet** [comment]
Sounds like it is the same issue as: https://github.com/Theano/Theano/issues/1772

Basically, some Theano bug. I will look into setting up a workaround in Keras.

**Comment by jfsantos** [comment]
Hopefully all we need to do is call `T.unbroadcast` in `get_output` from all recurrent layers when the last dimension is 1.

**Comment by fchollet** [comment]
Here's the fix: https://github.com/fchollet/keras/commit/5e2b9358d6741840f3b86adbaf4f5ac8a99ea9ee

Cheers!

**Comment by jfsantos** [comment]
That was quick, thanks!
