### ISSUE TITLE
Tensorboard callback doesn't work on fit_generator

### ISSUE THREAD

**Issue by heygawau** [fchollet/keras#1631]
We have this error on a sequential model with multiple inputs:
keras sequential object as no attribute validation data

We have the same error for the graph:
keras graph object as no attribute validation data

It does work on fit !!

Is it normal?

`mix_model.fit_generator(trainBatchBuilder.seq_batch_generator(), 100, 5, validation_data=(X_test, Y_test),
                        callbacks=[TensorBoard("path/tensorboard_logs/", 1)])
`
Am I missing something?

**Comment by PHLF** [comment]
Same here with Graph model, looking at lines 1399-1428 in models.py and 501-524 in callbacks.py shows that it is not implemented. Shouldn't be too hard to implement manually though.
