### ISSUE TITLE
Implementing objective function of own

### ISSUE THREAD

**Issue by bienbinod** [fchollet/keras#1635]
I found  a good number of already implemented objective function in keras. But would it be possible to 
plug new objective function with minimal efforts in Keras?

**Comment by tboquet** [comment]
You could pass it like this:

```python
def another_mse(y_true, y_pred):
    return K.mean(K.square(y_pred - y_true), axis=-1)

model.compile(loss=another_mse, optimizer='sgd')
```

**Comment by bienbinod** [comment]
@tboquet Thank you very much for your quick reply.

**Comment by tboquet** [comment]
@bienbinod did you succeeded? If so could you close the issue? Tx!
