### ISSUE TITLE
Shared (siamese) nodes and LambdaMerge in Graph

### ISSUE THREAD

**Issue by mikekestemont** [fchollet/keras#1636]
There has been a lot of discussion recently on shared nodes and 'siamese' architectures, with some great progress on weight sharing (cf. #928 ). It would be nice to add an example on how to implement a 'vanilla' siamese net, like seminally proposed by [Chopra et al.](http://yann.lecun.com/exdb/publis/pdf/chopra-05.pdf). I wanted to do this, but implementing this architecture is surprisingly far from trivial. Assume that our model takes two inputs, transforms these through a set of shared layers, and finally outputs the distance/similarity for the representations obtained in both subnets. In any case, the distance function must probably be implemented as a custom function to allow enough flexibility and add e.g. the Euclidean distance as they do in the original paper. Sorry for the long question. The setup:

```python

from keras.models import Graph, Sequential
from keras.layers.core import *

in_dim = 1000
hidden_dim = 100
out_dim = 1
```

I wanted to use a Graph (which originally felt quite natural, because we have multiple inputs). We leave the Euclidean distance for what it is and we use a dummy Layer() layer to produce a dot product.
```python
G = Graph()
G.add_input(name='input_a', input_shape=(in_dim,))
G.add_input(name='input_b', input_shape=(in_dim,))

G.add_shared_node(Dense(hidden_dim),
                  name='shared_dense',
                  inputs=['input_a', 'input_b'],
                  outputs=['input_a+', 'input_b+'],
                  merge_mode=None,
                  create_output=False)

G.add_node(Layer(),
            name = 'target', 
            inputs = ['input_a+', 'input_b+'],
            merge_mode = 'dot',
            dot_axes = 1,
            create_output = False)

G.add_node(Activation('tanh'),
                   input='target',
                   name='bin',
                   create_output=True)

G.compile(optimizer='RMSprop',
          loss={'bin':'mse'})
```

This compiles, but doesn't give any flexibility as to the distance computation (e.g. Euclidean distance, or any other metric). The recently added LambdaMerge layer seems a great way to this, but it still unclear to me (from docs and code) whether the LambdaLayer is compatible with the Graph container. Using the example in LambdaMerge's docstring (root mse), I tried this:
```python
G = Graph()
G.add_input(name='input_a', input_shape=(in_dim,))
G.add_input(name='input_b', input_shape=(in_dim,))

def rms(X):
    s = X[0]**2
    for i in range(1, len(X)):
        s += X[i]**2
    s /= len(X)
    s = np.sqrt(s)
    return s

def output_shape(input_shapes):
    return input_shapes[0]

G.add_shared_node(Dense(hidden_dim),
                  name='shared_dense',
                  inputs=['input_a', 'input_b'],
                  outputs=['input_a+', 'input_b+'],
                  merge_mode=None,
                  create_output=False)

lambda_merge = LambdaMerge(['input_a+', 'input_b+'], rms, output_shape)

G.add_node(lambda_merge, name='target')

G.add_node(Activation('tanh'),
                   input='target',
                   name='bin',
                   create_output=True)
G.compile(optimizer='SGD',
                       loss={'bin':'binary_crossentropy'})
```
This gives an error, implying that I can't pass string names to LambdaMerge. Bottom line: how can I add a LambdaMerge layer on top of the outputs produced by the shared nodes in a Graph? Using a stack of Sequentials did not help either (even though I added a dummy layer to make sure that the shared layers aren't first in the network):

input1 = Sequential()
input2 = Sequential()
input1.add(Activation('linear'))
input2.add(Activation('linear'))
add_shared_layer(Dense(100), inputs=[input1, input2])
m = Sequential()
lambda_merge = LambdaMerge([input1, input2], rms, output_shape)
m.add(lambda_merge)
m.add(Activation('tanh'))
model.compile(loss='mse', optimizer='rmsprop')

This gives:
```
Exception: Layer is not connected. Did you forget to set "input_shape"?
```

All feedback is welcome (I might be missing something obvious).

**Comment by jgc128** [comment]
Try to use `Layer(input_shape=(in_dim,))` as the first layer:
```python
input1 = Sequential()
input2 = Sequential()
input1.add(Layer(input_shape=(in_dim,)))
input2.add(Layer(input_shape=(in_dim,)))
add_shared_layer(Dense(100), inputs=[input1, input2])
m = Sequential()
lambda_merge = LambdaMerge([input1, input2], rms, output_shape)
m.add(lambda_merge)
m.add(Activation('tanh'))
model.compile(loss='mse', optimizer='rmsprop')
```

PS: 
>I added a dummy layer to make sure that the shared layers aren't first in the network

I think farizrahman4u  had fixed it some time ago but I don't see these changes in the code right now...

**Comment by mikekestemont** [comment]
Thank you so much, @jgc128 , that fixed it! Indeed, I saw a PR for this coming by for this too...

**Comment by farizrahman4u** [comment]
In a gaph, instead of LambdaMerge you can simply merge them using join mode, and then add a Lambda layer which compjtes the distance.

**Comment by mmmikael** [comment]
I have also been trying the graph version working but if I use `'join'`, I am stuck with this error:
`ValueError: merge_mode="join" only works with named inputs.`
My graph looks like this:
```python
g = Graph()
g.add_input(name='input_a', input_shape=(in_dim,))
g.add_input(name='input_b', input_shape=(in_dim,))
g.add_shared_node(base_network, name='shared',
                  inputs=['input_a', 'input_b'],
                  outputs=['input_a+', 'input_b+'],
                  merge_mode=None,
                  create_output=False)
g.add_node(Lambda(euclidean_distance),
           inputs=['input_a+', 'input_b+'],
           merge_mode='join',
           name='d')
g.add_output(name='output', input='d')
```
What am I missing?

**Comment by farizrahman4u** [comment]
Can you see if join mode is working by using it in a model without shared layers?

**Comment by mmmikael** [comment]
> Can you see if join mode is working by using it in a model without shared layers?

Yes, I get the error without shared layers as well:
```python
g = Graph()
g.add_input(name='input_a', input_shape=(in_dim,))
g.add_input(name='input_b', input_shape=(in_dim,))
g.add_node(Dense(128), name='input_a+', input='input_a')
g.add_node(Dense(128), name='input_b+', input='input_b')
g.add_node(Lambda(euclidean_distance),
           inputs=['input_a+', 'input_b+'],
           merge_mode='join',
           name='d')
g.add_output(name='output', input='d')
```

**Comment by farizrahman4u** [comment]
Hmm. so join mode is broken. 
@fchollet

**Comment by mmmikael** [comment]
Thansk @farizrahman4u, I have created a new issue #1655 to look at that.
