### ISSUE TITLE
Help: Is there any way to set up taps for scan op in Keras, for LSTM application

### ISSUE THREAD

**Issue by WeidiXie** [fchollet/keras#1643]
Hello, 

I am actually new to python, 

I'm wondering is there some way to use taps in Keras?

E.g. say, I want to compute,  i_t = T.dot(W_xi, x_t) + T.dot (W_hi1, h_tm1) + T.dot(W_hi2,h_tm2)

h_tm1 :h(t-1)
h_tm2 : h(t-2)

It's quite straightforward in theano, just use output_info, and specify the taps.

**Comment by fchollet** [comment]
Yes: simply write your own RNN layer for Keras, using Theano.

**Comment by WeidiXie** [comment]
I wrote my own class, but is there any small examples that show how to use my own class in the Keras? Sorry for the stupid question, I'm really new to python.
