### ISSUE TITLE
Unable to Install on Mac OS

### ISSUE THREAD

**Issue by Tgaaly** [fchollet/keras#165]
When trying to install, I get the following error:

Compiling /tmp/easy_install-9FmuOc/h5py-2.5.0/h5py/h5o.pyx
Compiling /tmp/easy_install-9FmuOc/h5py-2.5.0/h5py/h5ds.pyx
Compiling /tmp/easy_install-9FmuOc/h5py-2.5.0/h5py/h5ac.pyx
In file included from /tmp/easy_install-9FmuOc/h5py-2.5.0/h5py/defs.c:252:
/tmp/easy_install-9FmuOc/h5py-2.5.0/h5py/api_compat.h:27:10: fatal error:
      'hdf5.h' file not found
#include "hdf5.h"
         ^
1 error generated.
error: Setup script exited with error: command 'cc' failed with exit status 1

**Comment by vzhong** [comment]
try `brew install h5py`

**Comment by Tgaaly** [comment]
I installed hdf5 from source, installed h5py (pip install h5py).
reinstalled python, numpy, scipy...etc. and then it finally worked.
