### ISSUE TITLE
'join' merge mode seems broken

### ISSUE THREAD

**Issue by mmmikael** [fchollet/keras#1655]
Following the discussion in #1636, it looks like 'join' merge mode is broken. 
The example below returns the error `ValueError: merge_mode="join" only works with named inputs.` while inputs are actually named.

Problematic example:
```python
g = Graph()
g.add_input(name='input_a', input_shape=(in_dim,))
g.add_input(name='input_b', input_shape=(in_dim,))
g.add_node(Dense(128), name='input_a+', input='input_a')
g.add_node(Dense(128), name='input_b+', input='input_b')
g.add_node(Lambda(euclidean_distance),
           inputs=['input_a+', 'input_b+'],
           merge_mode='join',
           name='d')
g.add_output(name='output', input='d')
```

According to @farizrahman4u: 
> Join mode hasn't been updated since you changed the naming scheme. Join mode still looks for the tensor's name instead of the layer's name.

**Comment by fchollet** [comment]
I'm looking at it. The main issue here is that we don't have a unit test for the `join` mode.

**Comment by fchollet** [comment]
How is your `euclidean_distance` function implemented?

**Comment by fchollet** [comment]
This is fixed.

**Comment by mmmikael** [comment]
That was fast! Thanks a lot.

> How is your euclidean_distance function implemented?

```python
def euclidean_distance(inputs):
    assert len(inputs) == 2, \
        'Euclidean distance needs 2 inputs, %d given' % len(inputs)
    u, v = inputs.values()
    return K.sqrt((K.square(u - v)).sum(axis=1, keepdims=True))
```
