### ISSUE TITLE
Loading in data

### ISSUE THREAD

**Issue by Tgaaly** [fchollet/keras#166]
I'm trying to load my own data in to a simple MLP. 

comment: it should be written explicitly in the documentation whether the input data is row-wise or column-wise. This is to avoid confusion.

I get the following error....any ideas?

Traceback (most recent call last):
  File "/Users/anubis/Dev/keras_trial.py", line 58, in <module>
    model.fit(train_x, train_y, nb_epoch=20, batch_size=16)
  File "build/bdist.macosx-10.9-intel/egg/keras/models.py", line 239, in fit
  File "build/bdist.macosx-10.9-intel/egg/keras/models.py", line 45, in slice_X
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/easy_install-tGpjUt/h5py-2.5.0/h5py/_objects.c:2418)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/easy_install-tGpjUt/h5py-2.5.0/h5py/_objects.c:2375)
  File "/Library/Python/2.7/site-packages/h5py-2.5.0-py2.7-macosx-10.9-intel.egg/h5py/_hl/dataset.py", line 431, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/Library/Python/2.7/site-packages/h5py-2.5.0-py2.7-macosx-10.9-intel.egg/h5py/_hl/selections.py", line 79, in select
    sel[arg]
  File "/Library/Python/2.7/site-packages/h5py-2.5.0-py2.7-macosx-10.9-intel.egg/h5py/_hl/selections.py", line 217, in __getitem__
    raise TypeError("PointSelection __getitem__ only works with bool arrays")
TypeError: PointSelection __getitem__ only works with bool arrays
[Finished in 7.4s with exit code 1]

any ideas?

**Comment by mthrok** [comment]
can you show the corresponding part of your code? and what format your data uses?

h5py is used to save and load model weight, and training data is simple NumPy Array.
The error does not seem to be related to NumPy Array.

**Comment by Tgaaly** [comment]
I'm loading in .mat files of type double. I wrote comments in my code below. 

import h5py
import scipy.io 
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import SGD
from keras.datasets import cifar10
from keras.utils import np_utils

# load data (these are mat files with the type double - saved in matlab)
train_data = h5py.File('train.mat')
test_data  = h5py.File('test.mat')

train_x = train_data['train_x']
train_y = train_data['train_y']
test_x = test_data['test_x']
test_y = test_data['test_y']

# if I add these lines I get an error about index: TypeError: only integer arrays with one element can be converted to an index
#train_x = train_x.astype("float32")
#test_x = test_x.astype("float32")

# convert class vectors to binary class matrices
train_Y = np_utils.to_categorical(train_y, 2)
test_Y = np_utils.to_categorical(test_y, 2)

inputDim = 2744
hiddenDim1 = 1000
hiddenDim2 = 500
outputDim = 2

model = Sequential()
model.add(Dense(inputDim, hiddenDim1, init='uniform'))
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(Dense(hiddenDim1, hiddenDim2, init='uniform'))
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(Dense(hiddenDim2, outputDim, init='uniform'))
model.add(Activation('softmax'))

sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer=sgd)

model.fit(train_x, train_Y, nb_epoch=10, batch_size=20)
score = model.evaluate(test_x, test_y, batch_size=20)

**Comment by mthrok** [comment]
I don't have your mat file so I can't be completely sure, but from the error message, I can see that `train_x` is not a NumPy Array when you do `model.fit(train_x, train_Y, nb_epoch=10, batch_size=20)
 `.

So I am guessing that you are not loading MATLAB file properly. 
Maybe you can try something like this. 
http://stackoverflow.com/questions/874461/read-mat-files-in-python/19340117#19340117

**Comment by Tgaaly** [comment]
this made it work. thanks for the info!
