### ISSUE TITLE
AutoEncoder example raises AttributeError: 'Sequential' object has no attribute 'compile'

### ISSUE THREAD

**Issue by viktor-ferenczi** [fchollet/keras#1664]
Code is from [Keras documentation](http://keras.io/layers/core/#autoencoder):
```
import keras
from keras.layers import core, containers

encoder = containers.Sequential([core.Dense(16, input_dim=32), core.Dense(8)])
decoder = containers.Sequential([core.Dense(16, input_dim=8), core.Dense(32)])

autoencoder = containers.Sequential()
autoencoder.add(core.AutoEncoder(encoder=encoder, decoder=decoder, output_reconstruction=True))

autoencoder.compile(optimizer='sgd', loss='mse')
```

Trying to execute the above raises:
```
builtins.AttributeError: 'Sequential' object has no attribute 'compile'
```

**Comment by fchollet** [comment]
It's `models.Sequential`, not `containers.Sequential`. Also your code does not come from the documentation.

**Comment by viktor-ferenczi** [comment]
Thank you for fixing the documentation in 1b22915f8575a26e14c0f5aa77103e24e927e4dd by adding the missing imports. The code above was from the documentation with the missing imports added. That's where I made the mistake and imported Sequential from the wrong module.
