### ISSUE TITLE
CNN to RNN with variable input width/timesteps

### ISSUE THREAD

**Issue by raindeer** [fchollet/keras#1666]
Im trying to figure out if it is possible to define a model that combines Convolutional layers with Recurrent layers without specifying the width of the input image/length of the sequence. 

For a model that only contains Convolution2D layers we can set the input shape to (1, None, None) to allow it to take images of any height and width. And for an RNN layer we can set the number of timesteps to None (e.g., input shape=(None, 10)).

What I would like to do is to be able to do something like this:
```python
num_classes = 5
input_height = 16
cnn_out_height = input_height
cnn_out_channels = 8

cnn_input_shape = (1, input_height, None)
rnn_input_shape = (None, cnn_out_height * cnn_out_channels)

model = Sequential()
model.add(Convolution2D(cnn_out_channels, 3, 3,
                        border_mode='same',
                        input_shape=cnn_input_shape))

model.add(Permute((3, 2, 1)))
model.add(Reshape(rnn_input_shape))  # does not work

model.add(SimpleRNN(1, return_sequences=True, input_shape=rnn_input_shape))
model.add(TimeDistributedDense(num_labels))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='sgd')
``` 

Here the problem is the Reshape layer, that is needed to go from the 4D output tensor of the Convolution2D to the 3D input of the RNN. I basically just want to merge to last two dimensions of the permuted Convolution2D output without caring for the shape of the other two dimensions (batch size and width). Anyone has an idea how to do this?

**Comment by oeway** [comment]
I think you can use a Lambda layer with a reshape function to merge the last two dimensions. 
http://keras.io/layers/core/#lambda

**Comment by raindeer** [comment]
I ended up using Theanos .flatten(ndims)
```python
class CnnToRnn(Layer):
    """
    Reshapes the Permuted CNN output so that it can be feed to the RNNs.
    Flattens the last two dims.
    """

    def __init__(self, output_shape, **kwargs):
        super(CnnToRnn, self).__init__(**kwargs)
        self._output_shape = tuple(output_shape)

        super(CnnToRnn, self).__init__()

    @property
    def output_shape(self):
        return (self.input_shape[0], ) + self._output_shape

    def get_output(self, train=False):
        cnn_out = self.get_input(train)
        return cnn_out.flatten(ndim=3)

    def get_config(self):
        config = {'name': self.__class__.__name__,
                  'output_shape': self._output_shape}
        base_config = super(CnnToRnn, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
```

**Comment by keunwoochoi** [comment]
Hi @raindeer, could you share bit more about your work and codes? I'm thinking of building a system with variable length inputs/fixed output by combining RNNs and CNNs but not sure what to read and how to implement them. The setup is pretty much similar to yours - fixed height, variable width input and for the output of a vector.
