### ISSUE TITLE
Merge two embedding layers

### ISSUE THREAD

**Issue by GratefulTony** [fchollet/keras#1675]
I have seen this use case a few times in the issues here, but can't quite seem to get it working:

Simply, I have a dataset of pairs of co-occurring indices, and want to learn embeddings for them based on their co-occurrence.

I plan to feed the model two n_samp*1-d input vectors as follows:

...(and learn the embeddings using an autoencoder)...

```
src_model = Sequential()
src_model.add(Embedding(collapse_dim, embedding_size, input_length=1))
dst_model = Sequential()
dst_model.add(Embedding(collapse_dim, embedding_size, input_length=1))

```
It would seem to me here, that the output dims of each of the embedding layers are simply embedding_size...

Then I would expect after concat-merging them, my output dim  would be 2*embedding_size?
 
```
encoder = Sequential()
encoder.add(Merge([src_model, dst_model], mode='concat'))
encoder.add(Dense(3*embedding_size, init='uniform'))
encoder.add(Activation('relu'))

```
This is where my code breaks... The library is having a tough time appending the dense layer onto the back of the merged embedding layers.

```
AssertionError: Incompatible shapes: layer expected input with ndim=2 but previous layer has output_shape (None, 1, 128)
```
There's probably something obvious I'm missing here-- but would appreciate a push in the right direction...

Anyway, for color, here's the rest of the plan...
```

decoder = Sequential([Dense(input_dim=3*embedding_size, output_dim=2*embedding_size, init='uniform')])

autoencoder = AutoEncoder(encoder=encoder, decoder=decoder, output_reconstruction=True)

model = Sequential()
model.add(autoencoder)
```

Thanks in advance to any of you fine folks who can help me out here.

**Comment by farizrahman4u** [comment]
`Embedding` layer works on sequences. Even though in this case you have confined your input_length to just 1, it still outputs a 3D tensor of dimensions `(nb_samples, 1, 128)` . So you have to reshape it into to a 2D tensor in order add a 2D layer such as a `Dense` layer on top of it.

```python
encoder = Sequential()
encoder.add(Merge([src_model, dst_model], mode='concat'))
encoder.add(Reshape((embedding_size,)))#(None, 1, 128) -> (None, 128)
encoder.add(Dense(3*embedding_size, init='uniform'))
encoder.add(Activation('relu'))
```

**Comment by GratefulTony** [comment]
It seems so clear now-- thanks, that cleared it right up!

**Comment by farizrahman4u** [comment]
You may close the issue if everything is fine.

**Comment by GratefulTony** [comment]
gladly

**Comment by ronxin** [comment]
I experienced the same problem, but my `input_length` is not fixed. So I would have code like following, and it still gives an error about dimensions.

```
src_model = Sequential()
src_model.add(Embedding(collapse_dim, embedding_size))
dst_model = Sequential()
dst_model.add(Embedding(collapse_dim, embedding_size))
encoder = Sequential()
encoder.add(Merge([src_model, dst_model], mode='concat'))
encoder.add(Reshape((embedding_size,)))
encoder.add(Dense(3*embedding_size, init='uniform'))  # <-- error given here
```

Any help would be appreciated!

**Comment by alyato** [comment]
@ronxin ， i think that  it's the `input_length`. When you call the Merge layer, you can set `concat_axis = 1`. Then you use the Reshape layer, not `(embedding_size,)`. Thanks

**Comment by Qululu** [comment]
(Using TF backend) I'm having the same problem, but mine is a combination of the 2 problems mentioned here. I want to merge a fixed-length input Embedding layer with a non-fixed-length input Embedding layer:

```
#Embeddings for word-ordered sentence features
encoder_a = Sequential()
encoder_a .add(Embedding(collapse_dim_a, embedding_size, input_length=15))
encoder_a .add(LSTM(128, activation='sigmoid', inner_activation='hard_sigmoid'))

#Embeddings for unordered word set features corresponding to each sentence
encoder_b = Sequential()
encoder_b .add(Embedding(collapse_dim_b, embedding_size))    #no specified max_len
encoder_b .add(Lambda(average))   #average the embeddings

decoder = Sequential()
decoder.add(Merge([encoder_a, encoder_b], mode='concat', concat_axis=1))
decoder.add(Reshape((embedding_size,)))
decoder.add(Dense(64, activation='relu'))
decoder.add(Dense(n_classes, activation='softmax'))
```

I get the following error:
```
File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/layers/core.py", line 201, in _fix_unknown_dimension
    raise ValueError(msg)
ValueError: total size of new array must be unchanged
```

@alyato , Can you please clarify what you mean by "Then you use the Reshape layer, not `(embedding_size,)`". I tried removing the Reshape layer, but get the following error:

```
File "/home/user/anaconda2/envs/tensorflow/lib/python2.7/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

**Comment by link-er** [comment]
@ronxin hi! is this your example still working? I am trying also to merge embedding layers, but I am getting error on the Reshape layer and it is really weird one:
```
TypeError: long() argument must be a string or a number, not 'NoneType'
```

**Comment by link-er** [comment]
@farizrahman4u hello! maybe you know where from this error can come?

**Comment by farizrahman4u** [comment]
@link-er Post your code.

**Comment by link-er** [comment]
I want to make It work for any sequence length, so I do not have input length. But after merge I need to apply convolution, so I want to convert my sequence of word embeddings to one long sequence, i.e. if sentence has 16 words, each mapped to 200-dimensional embedding, I want to get (3200, 1) tensor
```
word_emb = Sequential()
word_emb.add(Embedding(20000, 100, weights=[embedding_matrix], trainable=False))
d_embedding_matrix = np.random.rand(201, 50)
d1_emb = Sequential()
d1_emb.add(Embedding(201, 50, weights=[d_embedding_matrix], trainable=True))
d2_emb = Sequential()
d2_emb.add(Embedding(201, 50, weights=[d_embedding_matrix], trainable=True))
model = Sequential()
model.add(Merge([word_emb, d1_emb, d2_emb], mode='concat'))
model.add(Reshape((,))) # for now, after investigation, I am not even sure what should I pass here. Flatten I guess is a better alternative
model.add(Conv1D(1000, 3*200, activation='tanh', border_mode='same', subsample_length=200, W_regularizer=l2(0.01), b_regularizer=l2(0.01)))
```
But as I understand now, both Reshape and Flatten will require fixed input_shape. There is no way to overcome this?

**Comment by farizrahman4u** [comment]
So basically you have a (batch_size, input_length, embedding_dim) tensor and you want to reshape it into  a (batch_size, input_length * embedding_dim, 1) tensor. Instead of `Reshape` you can Try adding a `Lambda` layer:

```python
model.add(Lmabda(lambda x: K.reshape(x, (K.shape(x)[0], K.shape(x)[1] * K.shape(x)[2], 1), output_shape=(None, 1))
```

**Comment by farizrahman4u** [comment]
Btw, I am not sure why you are squashing the embedding dim and input length dim.. Probably you meant to do something else?

**Comment by link-er** [comment]
> You could simple add a flatten layer

Nah, it does not work. Gives me
```
Exception: The shape of the input to "Flatten" is not fully defined (got (None, 100). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model
```
And giving input_shape to the first layers fixes it - i.e. exactly what i do not want to do

> Btw, I am not sure why you are squashing the embedding dim and input length dim.. Probably you meant to do something else?

No, you are right, I need exactly this - I want to apply convolution later on concatenation of word embeddings, as if it is again a sentence, but consisting of embeddings

**Comment by farizrahman4u** [comment]
> No, you are right, I need exactly this - I want to apply convolution later on concatenation of word embeddings, as if it is again a sentence, but consisting of embeddings

Then you shouldn't squash the input_length dim and embedding_dim.

**Comment by link-er** [comment]
why?

**Comment by farizrahman4u** [comment]
Then it wouldn't make sense for the conv layer.. input to the conv1d should be of shape (batch_size, input_length, embedding_dim).
Each of the conv filter would be then of size (filter_size, embedding_dim).. and move across your sequence like a sliding window. If you flatten it out and add an extra 1-dim, you will get a sequence of scalars, and the sequence length will be different from the sentence length, and wouldn't make much sense overall.

**Comment by link-er** [comment]
Oh, yes, you are right. I did not realize that it will make the same effect as if I will get it to complete 1d and add filter_size*embedding_dim filter. Thanks a lot!

**Comment by anamika06jain** [comment]
i have designed the merged model successfully, but how can i pass two different images to different CNNs using fit generator???
