### ISSUE TITLE
Training and Validation Data as Part of Model Data Structure

### ISSUE THREAD

**Issue by imk1** [fchollet/keras#1676]
Why are the training and validation data put into the model data structure when model.fit is run?  This substantially increases the space, and these parts of the data structure never seem to be referenced.  Thanks!

**Comment by fchollet** [comment]
There are not part of the "model data structure", we just add a pointer to
the current data as a Model attribute. There is not added cost to doing so,
and it's useful to reference the training data from various parts of the
code.

If you need to store the model, you should do it via the canonical way
(refer to the documentation).

**Comment by imk1** [comment]
Thanks for the clarification.
