### ISSUE TITLE
RFC: Visualization Tool

### ISSUE THREAD

**Issue by claymcleod** [fchollet/keras#1680]
Hey everyone. I'm thinking about making a visualization tool that is native to Keras and will work with both backends. Right now the plan is to wrap a Bokeh server. Some principles I'm thinking of:
- **Customization**: Give users access to everything they would have access to in Bokeh
- **Simplicity**: In terms of integrating with Keras, I would say add two extra arguments to the model.fit method: something like "visualization" (boolean) and "visualization_config" (dict) (better names?) If visualization is on, default visualization settings would be used unless they provided a visualization_config.
- **Flexibility**: I'd like to make the server able to deploy on localhost or connect to a remote server. There are numerous use cases for a remote server.

Anyone else have something to add to the discussion? Pros? Cons?

**Comment by lukedeo** [comment]
Not a viz expert, but in terms of integration, this should probably be done with a `VizServerCallback` or something like that, rather than being plugged directly into the model estimation infrastructure. Then, your configs and stuff can go into this.

**Comment by nouiz** [comment]
I just want to point to d3viz that work for Theano. Maybe it can be useful
to you:

http://deeplearning.net/software/theano/library/d3viz/index.html?highlight=d3viz#module-theano.d3viz

Making good visualization take times, so if you can reuse works elsewheree,
it would be good.

**Comment by tboquet** [comment]
Hi, good idea! The best way would be to use callbacks. There are 2 projects already started, it could be interesting to take a look and then decide if we could contribute to these projects or start a new one.

https://github.com/AgnezIO/agnez
https://github.com/fchollet/hualos

The callback available to work with hualos is there:
https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L361-L404

For the computation graph in Theano I would be interested to know if someone has an example for a bigger graph than the one in the documentation. I have been affraid to use it because some graphs could be huge :).

**Comment by nouiz** [comment]
It was tested with some big graph and it was "fast enough".

**Comment by tboquet** [comment]
Cool tx I'll try it!

**Comment by claymcleod** [comment]
Thanks for the comments everyone. However, I really wanted to integrate with Bokeh, as I feel like its much more extendable.

Here is the code the user has to implement to run this:

```python
from keras.visualization import charts

# ...

config = charts.ChartConfig()
config.add_chart(charts.ParameterHistogram('W', title="weights"))
config.add_chart(charts.ParameterHistogram('b', title="biases"))

# ...

model.fit(X_train, Y_train,
          batch_size=batch_size,
          nb_epoch=nb_epoch,
          show_accuracy=True,
          verbose=2,
          validation_data=(X_test, Y_test),
          visualize=True,
          visual_config=config)
```

Thoughts on this picture? I've got histograms for any parameter working and live updating.

<img width="888" alt="screen shot 2016-02-10 at 11 37 48 pm" src="https://cloud.githubusercontent.com/assets/3411613/12970062/59a80542-d04f-11e5-84c3-a512f16f26fe.png">

**Comment by claymcleod** [comment]
Parameter line charts now added. I wanted to add mean and STD on the same chart, but I'm still thinking about the best way to do that in bokeh (candlesticks, quad, etc). Anyone with experience in Bokeh feel free to suggest. Also, is that even necessary?

<img width="1104" alt="screen shot 2016-02-11 at 1 13 08 am" src="https://cloud.githubusercontent.com/assets/3411613/12971149/3eae369a-d05d-11e5-8a6c-92399180bdd4.png">

**Comment by tboquet** [comment]
Hey nice work! The candlesticks (or boxplots) for the means and std is a good idea. It would be interesting to plot the weights using a 2D map (even if it's 1D, it could be cool!).

**Comment by EderSantana** [comment]
@claymcleod Agnez, the project @tboquet pointed out has a bokeh example:
https://github.com/AgnezIO/agnez/blob/master/examples/bokeh_plotting.py

I'm in charge of that project now and I would love to review any PR of your's if you are interested.

**Comment by tboquet** [comment]
@claymcleod @EderSantana I would be interested to contribute to merge/improve/expand/test these projects and features. I'm working on building a scheduling service to be able to train several models, keep track of what's happening and tune hyperparameters and a real time visualization app would be a super cool add-on :). @EderSantana I'm not sure if Agnez is using the latest version of Bokeh? They changed how the server behave at some point.

**Comment by claymcleod** [comment]
@EderSantana Very cool project! 

I think our approaches might different --- I'm working on a very minimal (one new file) but extendable system that can fit inside of Keras without having to be maintained. It will provide some basic plots, but its main function is allowing users to easily create and deploy their own plots quickly.

After looking at the source, I think Agnez is aiming to give you much more complex features out of box, which might be better contained in a third-party library.

@tboquet I can only speak on the pull request I'm working on, but anything you can do in bokeh will be easily done with this framework. AKA, you could very easily create a controlling interface in Bokeh **and** the charts that you would want to use.

**Comment by tboquet** [comment]
@claymcleod cool, that's what I'm looking for.
I tried the tools and added the option to pass the server url and more plots. It's easy and it works really well.

Looking at how Bokeh evolve it might be difficult to add it as a dependency. Its api is changing a lot and it is a good idea to have well separated containers. Adding a link between the core of Keras api (`model.py`) via the `_fit` method could be handy for some users if the dependency is very robust but painful if users can't fit their models anymore and have to wait for a fix or change their scripts. 

I maybe wrong in how this tool should be integrated and the best way to know would be to have @fchollet and @EderSantana advice because they have already worked a lot on this path :).

**Comment by claymcleod** [comment]
@tboquet I'd be interested to hear their thoughts too. However, the whole thing is driven by the VisualizationPublisher callback --- the only thing that is tied into the model module is adding that callback to the callback stack.  Since there is one point of entry to the charts module, all users have to do if Bokeh changes is have ```visualize=False``` (or remove the argument altogether) and forgo visualization. That would be a given no matter what technology stack you build on.

So, at worst, nothing changes from the current capabilities.
