### ISSUE TITLE
fit_generator

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#1685]
So I've been trying to work with the fit_generator method for the graph model.
All works well if I set nb_worker=1, but any value higher than that and it just crashes.

It seems thread.start automatically triggers _stop.is_set() after the first thread. This is in python3. Haven't tested python2.7

I lack the skills for any more informative debugging >.>

**Comment by parag2489** [comment]
You should read #1638 and try my solution. It worked for me for the Sequential() model.
