### ISSUE TITLE
Merge two CNNs has the Error:"TypeError: 'int' object is not iterable"

### ISSUE THREAD

**Issue by xiaominlan** [fchollet/keras#169]

**Comment by fchollet** [comment]
Do you have the code to repro this?

**Comment by xiaominlan** [comment]
the follow is my code:




batch_size=16
nb_epoch=5
#load the data
print('load data.....')
path="rt_polarity_for_cnn.pkl"
f=open(path,"rb")
revs, word_idx_map, word_vecs=cPickle.load(f)
f.close()
data,label=process_data.make_idx_data_cnn(revs,word_idx_map,word_vecs)

print(data.shape[0],'sample')
#tranform the label,this is important!!!
label=np_utils.to_categorical(label,2)
print('data shape:',data.shape)
print('label shape : ',label.shape)

print("Create Merge model.....")
model_3=Sequential()
model_3.add(Convolution2D(100,1,3,300,border_mode='valid'))
model_3.add(Activation('relu'))
model_3.add(MaxPooling2D(56,1))

model_4=Sequential()
model_4.add(Convolution2D(100,1,4,300,border_mode='valid'))
model_4.add(Activation('relu'))
model_4.add(MaxPooling2D(55,1))

model=Sequential()
model.add(Merge([model_3,model_4],mode="concat"))
model.add(Flatten())
model.add(Dense(200,2))
model.add(Dropout(0.5))
model.add(Activation("softmax"))

sgd=SGD(l2=0.0,decay=1e-6,momentum=0.9,nesterov=True)
model.compile(loss="binary_crossentropy",optimizer=sgd)

model.train([data,data],label,accuracy=True)
