### ISSUE TITLE
Bug: ImageDataGenerator actually shifts image vertically when used width_shift_range >0 and height_shift_range=0 (and vice-versa)

### ISSUE THREAD

**Issue by parag2489** [fchollet/keras#1690]
The title is explains the problem in ImageDataGenerator. I defined the data generator as follows:

```
datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.5,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.0,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=False,  # randomly flip images
        vertical_flip=False)  # randomly flip images
```

Now one may assume by reading the `ImageDataGenerator` documentation that the images will be shifted by `0.5*image_width` from left to right (or from right to left). What I found by looking at the shifted images was totally opposite. When width_shift_range>0 and height_shift_range=0, it shifts the image from **top to bottom**. 

The culprit is in this line in `image.py`:

```
ndimage.interpolation.shift(x, (0, crop_left_pixels, crop_top_pixels), order=0, 
mode=fill_mode, cval=cval)
```
If we change the order of `crop_left_pixels` and `crop_right_pixels`, the images will shift as expected. One more thing remains, if `crop_left_pixels = 0.2`, then the image shifts in one direction only (I think `ndimage` does it from left to right). This prevents images getting shifted from other direction. Solution? Multiply `crop_left_pixels` by -1 in a random fashion. The modified function looks as follows:

```
def random_shift(x, wrg, hrg, fill_mode="nearest", cval=0.):
    crop_left_pixels = 0
    crop_top_pixels = 0

    if wrg:
        crop = random.uniform(0., wrg)
        split = random.uniform(0, 1)
        randSign = 2*np.random.randint(2)-1 #allows cropping from left and right both
        crop_left_pixels = randSign*int(split*crop*x.shape[2]) #x.shape[2] are actually columns
    if hrg:
        crop = random.uniform(0., hrg)
        split = random.uniform(0, 1)
	randSign = 2*np.random.randint(2)-1 #allows cropping from top and bottom both
        crop_top_pixels = randSign*int(split*crop*x.shape[1]) #x.shape[1] are actually rows
    x = ndimage.interpolation.shift(x, (0, crop_top_pixels, crop_left_pixels),
                                    order=0,
                                    mode=fill_mode,
                                    cval=cval)
    return x

```
If @fchollet can comment on this, then I can submit a pull request or anything else needed as per the norms.

**Comment by fchollet** [comment]
It would help if you could post pictures to demonstrate what's happening. 

If you are confident with your fix, then sure, you should submit a PR.

**Comment by parag2489** [comment]
@fchollet  I am attaching some pictures generated by:

```
datagen = ImageDataGenerator(
        featurewise_center=True,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.8,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.0,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=False,  # randomly flip images
        vertical_flip=False)  # randomly flip images
```

Now, I am posting some images from CIFAR-10 (sorry, they are 32x32, but I think you get the point) obtained from above augmentation. You can see that they are: 1. shifted vertically instead of horizontally  2. shifted only in one direction, from top to bottom.


![0_0_0](https://cloud.githubusercontent.com/assets/6313583/12993588/4d40c544-d0d8-11e5-86fc-21f1fd36ba2c.jpeg)     ![1_0_0](https://cloud.githubusercontent.com/assets/6313583/12993589/4d40d7f0-d0d8-11e5-9a72-1787f371abd4.jpeg)     ![3_0_0](https://cloud.githubusercontent.com/assets/6313583/12993677/d570034e-d0d8-11e5-8650-208a85273cb7.jpeg)     ![4_0_0](https://cloud.githubusercontent.com/assets/6313583/12993678/d571bf04-d0d8-11e5-980d-561906bd0224.jpeg)     ![5_0_0](https://cloud.githubusercontent.com/assets/6313583/12993680/d5744864-d0d8-11e5-8dcc-7ab9a0fb7c71.jpeg)     ![6_0_0](https://cloud.githubusercontent.com/assets/6313583/12993682/d576689c-d0d8-11e5-9585-cf917f9cce2e.jpeg)     ![7_0_0](https://cloud.githubusercontent.com/assets/6313583/12993679/d57283b2-d0d8-11e5-9b46-a33513683ff4.jpeg)     ![8_0_0](https://cloud.githubusercontent.com/assets/6313583/12993681/d5754d7c-d0d8-11e5-984a-0e1bc270237b.jpeg)     ![9_0_0](https://cloud.githubusercontent.com/assets/6313583/12993683/d5819c30-d0d8-11e5-8948-4b07e24e411d.jpeg)     ![2_0_0](https://cloud.githubusercontent.com/assets/6313583/12993587/4d3f3d28-d0d8-11e5-958c-872122f9ebf7.jpeg)

If you apply the fix, as explained above, you get these pictures:

![0_0_0](https://cloud.githubusercontent.com/assets/6313583/12993719/2e7a082c-d0d9-11e5-8efe-90f55931b38e.jpeg)    ![1_0_0](https://cloud.githubusercontent.com/assets/6313583/12993721/2e7ec466-d0d9-11e5-9b6e-aa59949452fb.jpeg)    ![2_0_0](https://cloud.githubusercontent.com/assets/6313583/12993720/2e7e1e12-d0d9-11e5-99ae-df2f7b978b0f.jpeg)    ![3_0_0](https://cloud.githubusercontent.com/assets/6313583/12993722/2e7ee824-d0d9-11e5-8abc-9ec51a2c8dcf.jpeg)    ![4_0_0](https://cloud.githubusercontent.com/assets/6313583/12993723/2e7fce42-d0d9-11e5-8f6d-2e6154f96405.jpeg)    ![5_0_0](https://cloud.githubusercontent.com/assets/6313583/12993724/2e7fed8c-d0d9-11e5-89bf-d28d4169a72b.jpeg)    ![6_0_0](https://cloud.githubusercontent.com/assets/6313583/12993725/2e87cbd8-d0d9-11e5-890b-db24a52b5d12.jpeg)    ![7_0_0](https://cloud.githubusercontent.com/assets/6313583/12993727/2e8cf7d4-d0d9-11e5-830b-b9a9cd55d956.jpeg)    ![8_0_0](https://cloud.githubusercontent.com/assets/6313583/12993726/2e8c9de8-d0d9-11e5-8185-d4c5b3d3bbdc.jpeg)    ![9_0_0](https://cloud.githubusercontent.com/assets/6313583/12993728/2e8d03fa-d0d9-11e5-8083-7bd3e714993d.jpeg)

You can see that third and fifth image are shifting in the opposite directions as desired. I will soon submit a PR on this.

**Comment by parag2489** [comment]
Its fixed now so I am closing it.
