### ISSUE TITLE
'mask' error with simple LSTM

### ISSUE THREAD

**Issue by shirtzet** [fchollet/keras#1708]
I was trying to compile the Sequence classification with LSTM example and got the following error:
`model.compile(loss='binary_crossentropy', optimizer='rmsprop')
.....
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Keras-0.3.1-py3.4.egg/keras/layers/recurrent.py", line 150, in get_output
TypeError: rnn() got an unexpected keyword argument 'mask'`

**Comment by fchollet** [comment]
It might occur to some that "official" code failing with an "unexpected keyword" error is indicative of API changes and that you should update the the latest version of the library you are using.
