### ISSUE TITLE
Weighted Objective for categorial Cross entroy

### ISSUE THREAD

**Issue by imraghs** [fchollet/keras#1710]
I am training a graph model in which there is a class imbalance issue. I would like to address it using  weighted_objectitve with categorial cross entropy loss. Can anyone give any example on how to use it. Weighted_obejctive is tested in tests/test_loss_making.py but it is not evaluated on some model. I can define: weighted_loss = weighted_objective(objectives.get('categorical_crossentropy')) and then pass it to graph.compile(optimizer='rmsprop', loss={'output':weighted_loss}), now my question is how can I pass the weights during graph.fit ??

Can anyone give some input regarding this??

**Comment by Aliases** [comment]
Hi,

I am trying to do the same thing. Were you able to find a solution?

Also, I am getting error NameError: name 'weighted_objective' is not defined.

I am trying to import weighted_objective from keras.models

**Comment by danielgy** [comment]
Hi Aliases, you need add 'from keras.engine.training import weighted_objective' first

**Comment by Aliases** [comment]
Thanks Daniel.
