### ISSUE TITLE
Embedding 

### ISSUE THREAD

**Issue by worldofpiggy** [fchollet/keras#1726]
I am training an LSTM with this language model:
every 20 words, I predict the next one (the 21st).
Therefore I give batches of matrices (20, vocabulary_size) as input x and
a vector of (vocsize) as input y.

The model in keras is this one: 

```
# build the model: 2 stacked LSTM
print('Build model...')
model = Sequential()
model.add(LSTM(512, return_sequences=True, input_shape=(maxlen, vocsize)))
model.add(Dropout(0.2))
model.add(LSTM(512, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(vocsize))
model.add(Activation('softmax'))
```

model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
model.fit(X, y, batch_size=128, nb_epoch=100)

How can I add and embedding layer (vocsize, emb_dims) to such a model?
Does keras support this?

**Comment by pasky** [comment]
Did you take a look at the NLP examples included with Keras?  Most of them combine Embedding with LSTM or CNN.

**Comment by worldofpiggy** [comment]
With this model 
model = Sequential()
model.add(Embedding(50, 512, input_length=maxlen))
model.add(LSTM(512, return_sequences=True, input_shape=(maxlen, vocsize)))
model.add(Dropout(0.2))
model.add(LSTM(512, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(vocsize))
model.add(Activation('softmax'))

I get 

TypeError: ('Bad input argument to theano function with name "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py:362"  at index 0(0-based)', 'Wrong number of dimensions: expected 2, got 3 with shape (128, 10, 2500).')

**Comment by lemuriandezapada** [comment]
Well what are your inputs?
You feed the embedding layer something 3d (128, 10, 2500) -> (batch_size, time_length, some_dim) while you need to feed it something 2d (batch_size, time_length) and the values are just some indices in your vocab.

If you want to feed it that 3d vector you need to remove the embedding layer.

**Comment by worldofpiggy** [comment]
My inputs are:
X_train is an array with shape ( 12000, 10, vocsize) where 12000 is the
number of sentences, 10 is the number of words and vocsize is the size of
the vocabulary
y_train is array of (12000, vocsize) that is one word for each training
example (every 10 words)

If I remove the embedding layer it works indeed. But I need to plot the
word embedding with t-sne, therefore I need that matrix (number_of_words,
embedding_dimensions)

Is there a solution to this?


Francesco Gadaleta, PhD

Data Scientist, R&D
Janssen Pharmaceuticals
Companies of Johnson and Johnson

Mobile: +32 (0)478998936
Personal website: www.worldofpiggy.com

**Comment by snowxiaoru** [comment]
I have trained wordvec,and I donnot need emdding level ,how can I transfer my data into the crrect format that lstm need?

**Comment by brunoalano** [comment]
The purpose of Embedding Layer is to "learn" how to transform Word Indices to a 3D space. So, your input should be 2D to use the Embedding layer.

What are you actually doing, is using a one-hot encoding (or one-vs-k), where the memory can be an issue. To use the Embedding layer, your input should be like [0, 0, 5, 3, 1, 7, 2, 9, 213, 312], where those indices represents words in a dictionary (for example,  5 = "dog", and 3 = "are")

**Comment by githubUser884** [comment]
## **This is the error I got. Unable to go forward plz help me out. Thanks in advance..**
```
sentiment.py:84: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  model.add(Embedding(dictionary_size, 128, dropout=0.2))
sentiment.py:85: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(128, dropout=0.2, recurrent_dropout=0.2)`
  model.add(LSTM(128, dropout_W=0.2, dropout_U=0.2))
Traceback (most recent call last):
  File "sentiment.py", line 85, in <module>
    model.add(LSTM(128, dropout_W=0.2, dropout_U=0.2))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 455, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 252, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 554, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 290, in call
    preprocessed_input = self.preprocess_input(inputs, training=None)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 1033, in preprocess_input
    return K.concatenate([x_i, x_f, x_c, x_o], axis=2)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1525, in concatenate
    return tf.concat([to_dense(x) for x in tensors], axis)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```
