### ISSUE TITLE
What Filters are used in Convolution Neural Network?

### ISSUE THREAD

**Issue by bhaveshoswal** [fchollet/keras#1729]
I am not able get the "nb_filters" in CNN 2D. i am doing a image classification using CNN 2D so i have to nb_filters argument in it for convolution purpose so suppose filter size is 3 * 3 and i want know what values does it contains? how it is decided for all 'n' filters

**Comment by farizrahman4u** [comment]
`nb_filters` sands for number of filters. If you set it to 10 for instance, 10 3*3 filters will be learned.

**Comment by bhaveshoswal** [comment]
you are right but what each instance contains and how it is decided?

**Comment by keunwoochoi** [comment]
> what each instance contains
Save weights of model, open it as a hdf, then open each layer, check the values.

> how it is decided?
What do you mean? Is Backprop what you're asking?

**Comment by bhaveshoswal** [comment]
thanks No  keunwoochoi I meant that the filters which we take in 'nb_filter' argument in Convolution Neural Network is like '32, 3, 3' so what that 32 filters contains and how it is decided

**Comment by keunwoochoi** [comment]
That sounds like I answered correctly. 
32 means 32 filters each of which size of 3x3. The values are decided so that it can represent what it needs to do and by backprop algorithm. I know I'm almost repeating the same answer but that's what your questions are asking I think.

**Comment by KeironO** [comment]
Hey @bhaveshoswal, 

I wrote a short introduction paper about ConvNets, that you can read here.

https://www.researchgate.net/publication/285164623_An_Introduction_to_Convolutional_Neural_Networks

If you have any further questions feel free to ask.

Keiron

**Comment by bhaveshoswal** [comment]
thanks but this gives a better and good about filter value initializations explanation [(http://cs231n.stanford.edu/slides/winter1516_lecture7.pdf)]

**Comment by Chang-Hoon** [comment]
above mentioned pdf has moved to http://cs231n.stanford.edu/slides/2016/winter1516_lecture7.pdf

**Comment by tispratik** [comment]
Are the 32 filters of the same type... just 32 instances? Or are they 32 different types of filters?
Example of "types" of a filters are "Sharpen", "Blur", "Edge detect", "Emboss", etc.

**Comment by amay1212** [comment]
@tispratik  , 

so this is how it works , first your image gets divided into matrix , kernel 3*3 with 32 filters mean ,
the combination of filter maps you will get while multiplying the kernel size matrix i.e(3*3) with the matrix of your input let say image and let suppose stride=1 , so the filter maps will be consisting of the product of two with a difference of 1 stride(assumption).

Hope this helps!!
