### ISSUE TITLE
model.load_weights creates .h5 files if the file was non-existant.

### ISSUE THREAD

**Issue by bryan-lunt** [fchollet/keras#1734]
This can be confusing and/or corrupting.

**Comment by wadhwasahil** [comment]
I am having problem loading weights from a graphical model.
This is the error I get.
`KeyError: "Unable to open object (Object 'graph' doesn't exist)"
`

**Comment by bryan-lunt** [comment]
Do you mean when using my patch or without?

I suspect this patch will cause your code to throw a different error. (IOError) because the file you are opening either doesn't exist, or it's a stub created by a previous call to load_weights. Empty files seem to be 800 bytes.

-Bryan Lunt

**Comment by wadhwasahil** [comment]
not using your patch. I am trying to load weights using graphical model of keras. However, it is showing the above error.

**Comment by bryan-lunt** [comment]
@wadhwasahil I'm quite sure that the underlying reason is as I said, you are trying to load either a non-existant .h5 file, or an empty .h5 file. Even if you apply my patch, the underlying cause of your problem (bad path to saved weights, weights not actually saved, whatever.) won't go away.
