### ISSUE TITLE
Sharing/Duplicating output of a layer?

### ISSUE THREAD

**Issue by shyamupa** [fchollet/keras#1738]
I am trying to implement the model specified by eqn. 7,8,9 in [this](http://arxiv.org/pdf/1509.06664v3.pdf) paper. The idea is to encode a sequence (say x) with an LSTM having return sequences=True (call it x-encoder), then let its final hidden output initialized another LSTM which encodes another sequence y. Also, use all the sequences returned by the x-encoder in a attention model.

I think I will need to share the output of the x-encoder into two nodes (one for initializing the y-decoder, and another for the attention model). Is this possible?

**Comment by pasky** [comment]
Yes, this should definitely be possible!  You want to use Graph to easily connect x-encoder into two nodes.  To take the last element of a sequence, you will probably need to have a Lambda layer that returns seq[-1].

BTW, I'll be very happy if you post your model on GitHub under a reusable licence, as I'm collecting these models in https://github.com/brmson/dataset-sts :-) You can also find there some examples of how to use Graph for attention and reuse outputs.

**Comment by shyamupa** [comment]
Thanks for your suggestion! I will be glad to share my model on github.

**Comment by shyamupa** [comment]
This is in reference to the suggestion of using Lambda layers. Would you kindly answer [this](https://groups.google.com/forum/#!topic/keras-users/tNBVeuhjsN4) question posted on the google group? I do not understand how to go about multiplying a 3d tensor with a dense layer.

Thanks!
