### ISSUE TITLE
Slow model initialisation

### ISSUE THREAD

**Issue by KeironO** [fchollet/keras#1746]
Hey there,

Does anyone know why it takes so long to initialise a neural network in Keras? 

It's taking almost as long to create my CNN than it does to train the damned thing!

Thank you,

Keiron.

**Comment by lukovkin** [comment]
At least because it seems that 'compile' doesn't run in parallel on different cores, it is seems to be single-threaded.
Training is multi-threaded and distributed among available cores.
It is annoying and may be someone knows how to optimize it?

**Comment by tboquet** [comment]
If you have not so big models, consider using Tensorflow. Theano is doing a lot of optimisation of the computation graph and should be used with "complex" models. Complex meaning it should be complex enough so you have to optimize your graph for the epoch to be computed faster. If you spend half of the time compiling your models, either you don't have a lot of data or a lot of weights. One other thing is the first time you compile you model, Theano will take longer to compile if you didn't run any similar model before. Some of the optimized parts are beeing cached.

**Comment by fchollet** [comment]
Most models (except recurrent ones) build almost instantly in TensorFlow. So if it's a big deal to you maybe you should switch to TensorFlow.

As for Theano compilation, it is a sequential process and there isn't much that could be run in parallel anyway.

**Comment by KeironO** [comment]
Is it possible to just simply clear the weights of the neural network?

**Comment by KeironO** [comment]
Ok, managed to find ```model.reset_states()``` which restarts the model.

Thank you!

**Comment by KeironO** [comment]
Ok. I've just found this https://github.com/fchollet/keras/issues/609 - was there any progress made?

**Comment by kirk86** [comment]
also I think `load_model` is not utilizing all the available cores. I've noticed that is running only on one core.

**Comment by cdicle** [comment]
Same here with @kirk86. I have finetuned an inception v3 model. I saved it. Now, I am loading the model in a different process. It is taking forever to load. Is this normal?

**Comment by kirk86** [comment]
@cdicle Maybe try serialize the model to disk using using cPickle, json, or yaml format. Then load them that way instead of `load_model`.  Maybe u can gain some speed.

**Comment by ibmua** [comment]
I'm using TF + Keras and it takes me 5 minuts to load a 18mb model. You can't make this shit up.
