### ISSUE TITLE
Lambda Layer to slice output not working

### ISSUE THREAD

**Issue by shyamupa** [fchollet/keras#1747]
I am using a LSTM to get a time series embedding of shape `(batch_size, seq_length, hidden_dim)`. I want to slice out the last vector of the series (the one I would get if I had `return_sequence` set to False). I cannot use return sequence because I am using part of the time series elsewhere. So I try using Lambda layer like so,
```
def get_H_n(X):
    return X[:,-1,:]

...
model.add_node(LSTM(options.lstm_units, return_sequences=True), name='forward', ...)
model.add_node(LSTM(options.lstm_units, return_sequences=True, go_backwards=True), name='backward' ..)
model.add_node(Dropout(0.5), name='dropout', inputs=['forward', 'backward']) # the bidir-lstm is passed through dropout
model.add_node(Lambda(get_H_n), name='h_n', input='dropout')
```

Strangely, I still get the same output sizes when I do `print(model.summary())`,
```
Dropout (dropout)             (None, 200, 280)              0
Lambda (h_n)                  (None, 200, 280)              0
```

What am I doing wrong?

**Comment by jgc128** [comment]
You have to specify the `output_shape` parameter in Lambda layer (http://keras.io/layers/core/#lambda), otherwise the output shape will be the same as the input shape. These parameter actually may be different than the real shape that you have.

**Comment by neggert** [comment]
This has gotten me in the past as well. Why does Keras allow create of a `Lambda` layer without setting `output_shape`? @fchollet would you be open to a PR that adds a check requiring output_shape to be set?

**Comment by jgc128** [comment]
I think it is good to have default output shape. Often the input shape equals the output shape.

**Comment by farizrahman4u** [comment]
@jgc128 Right. Thats why I left it that way..most ops do not change the shape, and if there is no default value, users would have to write `output_shape=lambda x:x` everytime.
