### ISSUE TITLE
More Descriptive Names for Layer Parameters

### ISSUE THREAD

**Issue by mdering** [fchollet/keras#1757]
I guess this more of a feature request, but I'm trying to render some visualizations of my model weights from the h5 files and I'm having a hard time figuring out which parameters are which. I have no idea if this would break anything but it seems like giving parameters names in addition to being able to name layers would be fairly straightforward and might be a big help to some people.

**Comment by KeironO** [comment]
Hey @mdering 

It's actually possible to do this with Keras.

https://github.com/fchollet/keras/issues/431

However, I too would like further description for the saved models.

**Comment by mdering** [comment]
this seems like its for visualizing the convolutions, right? I'm actually working on the 3D Conv layers which are still in PR, which is why i'm trying to use an external tool, and while each layer has a bad name (which is my fault), the parameters are just called param_0, param_1, etc. My sense is that param_0 is the weight and param_1 is the bias, based on dimensionality alone (?) but I'm not sure about that.

**Comment by KeironO** [comment]
Aah, right. I am currently experiencing the same problem, but with 5D outputs given by the TimeDistributedConvolution2D layer in [keras-extra](https://github.com/anayebi/keras-extra).

I have begun an issue there today, so perhaps the answer will be the same (seeing as we're both working with similar outputs)?

https://github.com/anayebi/keras-extra/issues/7
