### ISSUE TITLE
How to have TimeDistributedMerge with Masking

### ISSUE THREAD

**Issue by snakeztc** [fchollet/keras#1760]
The model that I am trying to build is as follows:
<img width="433" alt="screen shot 2016-02-18 at 11 57 07 pm" src="https://cloud.githubusercontent.com/assets/1688939/13166899/627611d0-d69b-11e5-992e-1e66e403160f.png">

So I constructed the following model using Keras:

```
    model = Sequential()
    model.add(Embedding(nb_words, hidden_size, mask_zero=True))
    model.add(LSTM(hidden_size, return_sequences=True))
    model.add(Dropout(0.2))

    model.add(TimeDistributedMerge(mode='ave'))
    model.add(Dense(hidden_size, init='lecun_uniform'))
    model.add(Activation('relu'))
    model.add(Dropout(0.2))

    model.add(Dense(self.domain.actions_num, init='lecun_uniform'))
    model.add(Activation('linear'))
    model.compile(loss='mse', optimizer="adam")
```

So the problem is that I want to use mask_zero because each input sequence have different length. However, I got the error:
**AssertionError: Cannot connect non-masking layer to layer with masked output.**

So is it possible to have mean pooling with masking?  Do I need to implement my own layer? Thanks!

**Comment by jmhessel** [comment]
Currently, time distributed merge doesn't support masking (I filed a similar issue a few days ago @1698). My understanding of masking in Keras is certainly outdated, but I'd be happy to help with a PR.

**Comment by LiuAndYang** [comment]
hi @snakeztc , did you solve this problem now? I met the same question, can't find a way out.

**Comment by abdulqayyum** [comment]
@snakeztc did you solve it? I have same issue #1913. My network is alot similar to yours and is just drwn upside down. my question is how are you trying to input your LSTM. Are they same? Because, If you are trying to implement MD LSTM then the input_shape should be same for all but sequences should be different?

**Comment by snakeztc** [comment]
@LiuAndYang @abdulqayyum  I didn't really solve it. I did try set the MaskZero to be false which effectively treat padding zeros as normal inputs. It sort of works, but I suspect the performance will be better if we have proper masking.

**Comment by codekansas** [comment]
I'm having a similar problem, I'd just like to merge two masked LSTM layers. Does anyone know of a solution?

**Comment by jmhessel** [comment]
Does the new functional API solve this problem? TimeDistrubted(Merge(...)) I think is the new notation? I haven't tried it myself.

**Comment by makagan** [comment]
I have a similar problem.  I have tried with TimeDistrubted(Merge(...)),  but have not been able to make it  work.  Is there other news about this?

**Comment by snakeztc** [comment]
@makagan I believe that when @codekansas's pull request is merged, this problem should be solved.

**Comment by makagan** [comment]
@snakeztc @codekansas , Thanks! I'll keep a look out

**Comment by codekansas** [comment]
PR is here #2413
