### ISSUE TITLE
What are the words represented by each id in the imdb dataset

### ISSUE THREAD

**Issue by EderSantana** [fchollet/keras#1775]
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

@fchollet @rodrigob I noticed you two were the ones who touched that file. Do you know how can I convert the imdb dataset that ships with keras back to words?

**Comment by coodoo** [comment]
It would be perfect if the script used to produce those datasets were available too!

**Comment by ymcui** [comment]
any update on this?

**Comment by ymcui** [comment]
any update on this?

**Comment by bestxolodec** [comment]
+1 to this topic  – obtaining particular words is a useful feature
