### ISSUE TITLE
LambdaMerge for computing dot product?

### ISSUE THREAD

**Issue by shyamupa** [fchollet/keras#1779]
I am trying to compute the dot product of a matrix (`Y`) and a vector (`alpha`) using keras. The matrix was the output of a LSTM with `return_sequence=True` passed through a `TimeDistributedDense`. The code is [here](https://gist.github.com/shyamupa/47a5a9301be6ad0eca5b). I am implementing the model from [this](arxiv.org/abs/1509.06664) paper.

`model.add_node(LambdaMerge(get_R), name='r', inputs=['Y','alpha'])`

where 

```
def get_R(X,Y):
    return K.dot(X,Y)

```

But I get the error,

`TypeError: __init__() takes at least 3 arguments (2 given)`

What am I doing wrong here? Seems like LambdaMerge does not work well with Graphs?

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by farizrahman4u** [comment]
```
def get_R(X):
    return K.dot(X[0], X[1])
```

**Comment by shyamupa** [comment]
Ok. So changing to this works, (I also changed my `get_R`)

`model.add_node(Lambda(get_R), name='r', inputs=['Y','alpha'], merge_mode='join')`

But, I also need to add the `output_shape` (as mentioned in #1747), so I did,

`model.add_node(Lambda(get_R,output_shape=(k,)), name='r', inputs=['Y','alpha'], merge_mode='join')`

This leads to the following error on calling `model.summary()`,

```
File "/home/anaconda/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 139, in model_summary
    display_layer_info(layer, name, positions)
  File "/home/anaconda/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 105, in display_layer_info
    output_shape = layer.output_shape
  File "/home/anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 1375, in output_shape
    return (self.input_shape[0], ) + self._output_shape
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by farizrahman4u** [comment]
Thats a bug, Thanks.
For the time being, you can do `output_shape=lambda _:(None, k)`.
@fchollet 
Missiing tes case -  Graph, join merge + Lambda, output shape specified as tuple

**Comment by shyamupa** [comment]
Thanks for the prompt response, but it still does not work, I changed to

`model.add_node(Lambda(get_R, output_shape=lambda _:(None, k)), name='r', inputs=['Y','alpha'], merge_mode='join')`

and get the new error,

```
anaconda/lib/python2.7/site-packages/keras/layers/core.py", line 1378, in output_shape
    output_shape_func = types.FunctionType(output_shape_func, globals())
TypeError: arg 5 (closure) must be tuple

```

**Comment by shyamupa** [comment]
@fchollet @farizrahman4u I am still struggling with this issue, if anyone can suggest a temporary fix, it will be great. I do not want to reimplement all my work in theano :P

**Comment by farizrahman4u** [comment]
#1801

**Comment by shyamupa** [comment]
So the idea of passing a full function did not help, but I just updated to the bleeding edge with
`pip install git+git://github.com/fchollet/keras.git`

Now it compiles :)
