### ISSUE TITLE
Add h5py to the requires list

### ISSUE THREAD

**Issue by lshamis** [fchollet/keras#178]

**Comment by fchollet** [comment]
It used to be included, but that caused some issues for some people, since HDF5 is not trivial to install. Since HDF5/h5py are essentially optional (only used for model loading/saving), I'm not sure we should include it. 

What reasons would you see to include it?

**Comment by lshamis** [comment]
I didn't know that it was removed for causing issues.
I was trying to train a model on one machine and serve off another. I added this issue when I noticed that [pip install keras] was not enough.

As an aside, it's hard for me to imagine a use-case that doesn't involve saving/loading models. Do people use their models immediately upon training, then discard them?

**Comment by JulianKniephoff** [comment]
This should at least be mentioned in the docs in my opinion. It is pretty frustrating to wait for your model to be trained only to have your program crash with an `ImportError` when it is finally done and you try to save it.

**Comment by fchollet** [comment]
It is mentioned on the first page of the documentation, and in README.md.

**Comment by JulianKniephoff** [comment]
Oops, how embarassing. I got my model saving code from [the FAQ](http://keras.io/faq/#how-can-i-save-a-keras-model). Any chance of a mention of this problem there, too?

**Comment by kargarisaac** [comment]
I want to load vgg16 weights in keras but I got "`load_weights` requires h5py"!! I installed h5py and imported that. What should I do?

**Comment by yvan** [comment]
having issues on this issue with keras 2.0.4, python 3.5.3, osx 10.11.6. i installed h5py with pip, then tried with conda, can't seem to get it working.

**Comment by Swanand-Kulkarni94** [comment]
@kargarisaac Same problem over here. 

--> model = VGG16(input_tensor = input_tensor, weights = 'imagenet', include_top = False)
--> ImportError: `load_weights` requires h5py.

I installed h5py using pip.

--> import h5py
--> import h5py as h5py
--> try:
    import h5py
except ImportError:
    h5py = None 

None has worked for me.

**Comment by DecentMakeover** [comment]
Facing the same Error-Anyone know what to do with this?

**Comment by sampath1310** [comment]
same problem did any one find solution?

**Comment by warp1337** [comment]
bump

**Comment by thedominica** [comment]
same error with load_model :/

**Comment by warp1337** [comment]
I found out that, in my case, you need to install unittest2 via pip in order to get it running
