### ISSUE TITLE
why use np.random.seed(1337) in mnist_cnn.py example

### ISSUE THREAD

**Issue by DanlanChen** [fchollet/keras#1783]
Why in mnist_cnn.py example, we should use np.random.seed(1337), the comment says it is used for reproductivity. What does it mean?

**Comment by fchollet** [comment]
"Reproducibility" means the ability to run the same thing twice and get the same results. That's why we seed our sources of randomness.

**Comment by DanlanChen** [comment]
But if you are using np.random.seed, in each batch, when you do shuffle, you always gets the same index, which means you are always using the same data to train your model in each iteration?

**Comment by DanlanChen** [comment]
I am having this trouble as I am training a model, but my acc and val_acc is same for each epoch, which makes me confused.

**Comment by alyato** [comment]
@DanlanChen What do you mean saying 

> y acc and val_acc is same for each epoch

I meet similar question that val_acc always the same for each epoch.
how do you solve it? Thanks
