### ISSUE TITLE
RMSE is being used in stateful_lstm.py, although it's been removed

### ISSUE THREAD

**Issue by dblN** [fchollet/keras#1784]
Running `python examples/stateful_lstm.py` gives me an error, because `rmse` has been removed. It should use `mse` instead.

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
Thanks, this is now fixed.
