### ISSUE TITLE
What happened to WordContextProduct?

### ISSUE THREAD

**Issue by zachmayer** [fchollet/keras#1787]
```{python}
In [1]: import keras

In [2]: keras.__version__
Out[2]: '0.3.2'

In [3]: from keras.layers.embeddings import WordContextProduct
Using Theano backend.
/usr/local/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-65e83b407b3e> in <module>()
----> 1 from keras.layers.embeddings import WordContextProduct

ImportError: cannot import name 'WordContextProduct'
```

This page now returns a 404: https://github.com/fchollet/keras/blob/master/examples/skipgram_word_embeddings.py

Was this code taken out of keras, or just moved somewhere else?

Thanks,

Zach

-------------
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by dandxy89** [comment]
I believe it was removed as there is a dedicated module called Gensim that can replace it.

**Comment by mrwns** [comment]
It was removed a while ago. As dandxy89 said, check gensim if you want to use word2vec. 

If you want to achieve the same thing using keras, I believe you could do so using some of the core layers.
This is what get_output looked like in the old WordContextProduct

```
def get_output(self, train=False):
        X = self.get_input(train)
        w = self.W_w[X[:, 0]]  # nb_samples, proj_dim
        c = self.W_c[X[:, 1]]  # nb_samples, proj_dim

        dot = T.sum(w * c, axis=1)
        dot = theano.tensor.reshape(dot, (X.shape[0], 1))
        return self.activation(dot)
```

So, if I understand this right, you just do a dot product of two Embeddings, this should be possible using the `Merge` layer (please correct me if I am wrong)

**Comment by zachmayer** [comment]
Ahhh, ok.  So is the reccomended workflow now:
1. Use gensim to find the word vectors
2. Use an embedding layer in keras that uses those word vectors
?

Thanks!

**Comment by zachmayer** [comment]
It would be nice to have some examples in the examples folder of using gensim + keras, to replace the old WordContextProduct examples.

**Comment by fchollet** [comment]
If you need something like WordContextProduct for your models, it's easy to
reimplement with a Graph (or just a Merge) and a dot merge.

**Comment by zachmayer** [comment]
Thanks for all the advice!

**Comment by zachmayer** [comment]
I'm trying something like this:
```{python}
# Word vectors
model_word = Sequential()
model_word.add(Embedding(1e6, 300, input_length=1))
models.append(model_word)

# Context vectors
model_context = Sequential()
model_context.add(Embedding(1e6, 300, input_length=1))
models.append(model_context)

# Combined model
model = Sequential()
model.add(Merge(models, mode='dot'))
model.add(Activation('sigmoid'))
model.compile(loss='mean_squared_error', optimizer=Adam(lr=0.001))
```

Does that look reasonable?  And then as input, I need to provide 2 lists of indexes?

**Comment by zachmayer** [comment]
See updated comment above.  Its for a word vector model with 1e4 words into an embedding with 300 dimensions.

**Comment by nooralahzadeh** [comment]
In case some one interested:
`from __future__ import absolute_import
from __future__ import print_function

import numpy as np
import theano
import six.moves.cPickle
import os, re, json

from keras.engine import Merge
from keras.layers import Reshape, Dense

from keras.preprocessing import sequence, text
from keras.optimizers import SGD, RMSprop, Adagrad, Adam
from keras.utils import np_utils, generic_utils
from keras.models import Sequential
from keras.layers.embeddings import Embedding
from six.moves import range
from six.moves import zip

max_features = 50000 # vocabulary size: top 50,000 most common words in data
skip_top = 100 # ignore top 100 most common words
nb_epoch = 1
dim_proj = 256 # embedding space dimension

save = True
load_model = False
load_tokenizer = False
train_model = True
save_dir = os.path.expanduser("~/Project/SIRIUS-LTG-IE/models")
model_load_fname = "HN_skipgram_model.pkl"
model_save_fname = "HN_skipgram_model.pkl"
tokenizer_fname = "HN_tokenizer.pkl"

data_path = os.path.expanduser("~/Project/SIRIUS-LTG-IE/")+"HNCommentsAll.1perline.json"

# text preprocessing utils
html_tags = re.compile(r'<.*?>')
to_replace = [('&#x27;', "'")]
hex_tags = re.compile(r'&.*?;')

def clean_comment(comment):
    c = str(comment.encode("utf-8"))
    c = html_tags.sub(' ', c)
    for tag, char in to_replace:
        c = c.replace(tag, char)
    c = hex_tags.sub(' ', c)
    return c

def text_generator(path=data_path):
    f = open(path)
    for i, l in enumerate(f):
        comment_data = json.loads(l)
        comment_text = comment_data["comment_text"]
        comment_text = clean_comment(comment_text)
        if i % 10000 == 0:
            print(i)
        yield comment_text
    f.close()

# model management
if load_tokenizer:
    print('Load tokenizer...')
    tokenizer = six.moves.cPickle.load(open(os.path.join(save_dir, tokenizer_fname), 'rb'))
else:
    print("Fit tokenizer...")
    tokenizer = text.Tokenizer(nb_words=max_features)
    tokenizer.fit_on_texts(text_generator())
    if save:
        print("Save tokenizer...")
        if not os.path.exists(save_dir):
            os.makedirs(save_dir)
        six.moves.cPickle.dump(tokenizer, open(os.path.join(save_dir, tokenizer_fname), "wb"))

# training process
if train_model:
    if load_model:
        print('Load model...')
        model = six.moves.cPickle.load(open(os.path.join(save_dir, model_load_fname), 'rb'))
    else:
        print('Build model...')
        models = []

        # Word vectors
        model_word = Sequential()
        model_word.add(Embedding(max_features, dim_proj, input_length=1))
        model_word.add(Reshape((dim_proj,)))
        models.append(model_word)

        # Context vectors
        model_context = Sequential()
        model_context.add(Embedding(max_features, dim_proj, input_length=1))
        model_context.add(Reshape((dim_proj,)))
        models.append(model_context)

        # Combined model
        model = Sequential()
        model.add(Merge(models, mode='dot', dot_axes=1))
        model.add(Dense(1, activation='sigmoid'))
        model.compile(loss='mean_squared_error', optimizer=Adam(lr=0.001))

    sampling_table = sequence.make_sampling_table(max_features)

    for e in range(nb_epoch):
        print('-'*40)
        print('Epoch', e)
        print('-'*40)

        progbar = generic_utils.Progbar(tokenizer.document_count)
        samples_seen = 0
        losses = []
        
        for i, seq in enumerate(tokenizer.texts_to_sequences_generator(text_generator())):
            # get skipgram couples for one text in the dataset
            couples, labels = sequence.skipgrams(seq, max_features, window_size=4, negative_samples=1., sampling_table=sampling_table)
            if couples:
                # one gradient update per sentence (one sentence = a few 1000s of word couples)
                X1, X2 = zip(*couples)
                X1 = np.array(X1, dtype="int32")
                X2 = np.array(X2, dtype="int32")
                loss = model.train_on_batch([X1,X2], labels)
                losses.append(loss)
                if len(losses) % 100 == 0:
                    progbar.update(i, values=[("loss", np.mean(losses))])
                    losses = []
                samples_seen += len(labels)
        print('Samples seen:', samples_seen)
    print("Training completed!")

    if save:
        print("Saving model...")
        if not os.path.exists(save_dir):
            os.makedirs(save_dir)
        six.moves.cPickle.dump(model, open(os.path.join(save_dir, model_save_fname), "wb"))


print("It's test time!")

# recover the embedding weights trained with skipgram:
weights = model.layers[0].get_weights()[0]

# we no longer need this
del model

weights[:skip_top] = np.zeros((skip_top, dim_proj))
norm_weights = np_utils.normalize(weights)

word_index = tokenizer.word_index
reverse_word_index = dict([(v, k) for k, v in list(word_index.items())])
word_index = tokenizer.word_index

def embed_word(w):
    i = word_index.get(w)
    if (not i) or (i<skip_top) or (i>=max_features):
        return None
    return norm_weights[i]

def closest_to_point(point, nb_closest=10):
    proximities = np.dot(norm_weights, point)
    tups = list(zip(list(range(len(proximities))), proximities))
    tups.sort(key=lambda x: x[1], reverse=True)
    return [(reverse_word_index.get(t[0]), t[1]) for t in tups[:nb_closest]]  

def closest_to_word(w, nb_closest=10):
    i = word_index.get(w)
    if (not i) or (i<skip_top) or (i>=max_features):
        return []
    return closest_to_point(norm_weights[i].T, nb_closest)


''' the resuls in comments below were for: 
    5.8M HN comments
    dim_proj = 256
    nb_epoch = 2
    optimizer = rmsprop
    loss = mse
    max_features = 50000
    skip_top = 100
    negative_samples = 1.
    window_size = 4
    and frequency subsampling of factor 10e-5. 
'''

words = ["article", # post, story, hn, read, comments
"3", # 6, 4, 5, 2
"two", # three, few, several, each
"great", # love, nice, working, looking
"data", # information, memory, database
"money", # company, pay, customers, spend
"years", # ago, year, months, hours, week, days
"android", # ios, release, os, mobile, beta
"javascript", # js, css, compiler, library, jquery, ruby
"look", # looks, looking
"business", # industry, professional, customers
"company", # companies, startup, founders, startups
"after", # before, once, until
"own", # personal, our, having
"us", # united, country, american, tech, diversity, usa, china, sv
"using", # javascript, js, tools (lol)
"here", # hn, post, comments
]

for w in words:
    res = closest_to_word(w)
    print('====', w)
    for r in res:
        print(r)
`

**Comment by kemaswill** [comment]
Hi zachmayer,

  Have you ran your code in the latest comments? Seems doesn't work for me, get the error: "Exception: Input 0 is incompatible with layer dense_1: expected ndim=2, found ndim=5".

Regards
Junwei Pan

**Comment by nooralahzadeh** [comment]
Try it with modifying  the following line: 
`model.add(Merge(models, mode='dot', dot_axes=1))`

**Comment by kemaswill** [comment]
Hi nooralahzadeh,

  Seems that your solution does not work, after setting `dot_axes=1`, the output shape of the Merge layer is not correct, if the input is a (1,100) and (5,100) tensor respectively, then the output will become (100, 100) rather than the (1,5) which is the desired output. I have pasted the code under https://github.com/kemaswill/keras/blob/master/examples/word2vec.py

Regards
Junwei Pan

**Comment by nooralahzadeh** [comment]
It should work in the original code from @zachmayer . your code is different because you get negative sample in once, but it should be pair in training time like (word1, negSample1) (word1,negSample2) ... based on the output from WordContextProduct . your input looks like (word, negSample, negSample,....,negSample)

**Comment by kemaswill** [comment]
Yes, it works by adding the `dot_axes=1` to the original code from @zachmayer . I just wonder why it does not work for my code which train multiple negative samples at the same time. Since I have implemented the word2vec in a similar way using Lua and Torch: https://github.com/kemaswill/word2vec_torch/blob/master/word2vec.lua. Thanks a lot, @nooralahzadeh

**Comment by kemaswill** [comment]
Problem resolved, I should use `dot_axes=[2,2]` instead. Thanks!
