### ISSUE TITLE
How to stack two shared nodes in Graph?

### ISSUE THREAD

**Issue by smohsensh** [fchollet/keras#1797]
I have a shared layer with join merge mode (like in [this example](https://github.com/fchollet/keras/blob/99991779e5234c57feee1723addd5b523acfc852/examples/mnist_siamese_graph.py)) and then I want to feed the output of this layer (which is an ordered dictionary) to another shared node. 
I tried splitting output of first shared node with lambda layer (like in code below) but I get errors on None output/input shape. 
I was wondering what is the right way to stack two shared nodes?

`g = Graph()`
`g.add_input(name='im1', input_shape=(input_dim,))`
`g.add_input(name='im2', input_shape=(input_dim,))`
`g.add_shared_node(base_network, name='shared', inputs=['im1', 'im2'], merge_mode='join')`
`g.add_node(Lambda(euclidean_distance), name='d', input='shared')`
`g.add_node(Lambda(lambda d: d['im1'], output_shape=(im_emb_dim,)), name='im1emb', input='shared')`
`g.add_node(Lambda(lambda d: d['im2'], output_shape=(im_emb_dim,)), name='im2emb', input='shared')`
`g.add_shared_node(Dense(att_dim, activation='sigmoid', input_shape=(im_emb_dim,)), name='att_pred', inputs=['shared'])`

**Comment by neggert** [comment]
I believe you want to use the `outputs` kwarg of `add_shared node`. E.g.

```{python}
g = Graph()
g.add_input(name='im1', input_shape=(input_dim,))
g.add_input(name='im2', input_shape=(input_dim,))
g.add_shared_node(base_network, name='shared', inputs=['im1', 'im2'],
                  merge_mode='join', outputs=['sharedA', 'sharedB'])
g.add_shared_node(Dense(10), inputs=['sharedA', 'sharedB'], merge_mode='concat', name='shared2')
```

**Comment by smohsensh** [comment]
thank @neggert but the example you provided doesn't work:
`Exception: Unknown identifier: sharedA`
 It seems adding `outputs`  kwarg only changes keys in the ordered dictionary of the layer output. and doesn't  affect `nodes` property of Graph model

**Comment by neggert** [comment]
Ah, sorry. You need to set `merge_mode=None`. This works for me:

```{python}
input_dim=3
base_network=Dense(10, input_dim=10)
g = Graph()
g.add_input(name='im1', input_shape=(input_dim,))
g.add_input(name='im2', input_shape=(input_dim,))
g.add_shared_node(base_network, name='shared', inputs=['im1', 'im2'],
                  merge_mode=None, outputs=['sharedA', 'sharedB'])
g.add_shared_node(Dense(10), inputs=['sharedA', 'sharedB'], merge_mode='concat', name='shared2')
```

**Comment by farizrahman4u** [comment]
There is another hack that I planted in the `add_shared_node` method.

```python
g = Graph()
g.add_input(name='im1', input_shape=(input_dim,))
g.add_input(name='im2', input_shape=(input_dim,))
g.add_shared_node(base_network, name='shared1', inputs=['im1', 'im2'],
                  merge_mode=None)
g.add_shared_node(base_network, name='shared2', inputs=['shared1'],
                  merge_mode=None)
g.add_shared_node(Dense(10),  name='shared3', inputs=['shared2'], merge_mode='concat')
```

**Comment by smohsensh** [comment]
Thanks you both for your help.
It almost did the trick, there was a minor problem where I wanted to use `merge_mode = 'join'` later in code because all outputs had the same name, but setting the names manually in my code solved that.
