### ISSUE TITLE
SimpleRNN Error

### ISSUE THREAD

**Issue by patyork** [fchollet/keras#18]
The SimpleRNN layer seem to require a tensor3 input of shape (batch_size, time_steps, features). However, Keras as a whole seems to expect only matrix inputs/outputs.

```python
model = Sequential()
#model.add(Dense(20, 5, init='uniform', activation='tanh'))
model.add(SimpleRNN(5, 20, activation='sigmoid'))

sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mse', optimizer='sgd')
```

```python
/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.pyc in output(self, train)
     47         X = self.get_input(train) # shape: (nb_samples, time (padded with zeros at the end), input_dim)
     48         # new shape: (time, nb_samples, input_dim) -> because theano.scan iterates over main dimension
---> 49         X = X.dimshuffle((1,0,2))
     50 
     51         x = T.dot(X, self.W) + self.b

/usr/local/lib/python2.7/dist-packages/theano/tensor/var.pyc in dimshuffle(self, *pattern)
    332             pattern = pattern[0]
    333         op = theano.tensor.basic.DimShuffle(list(self.type.broadcastable),
--> 334                                             pattern)
    335         return op(self)
    336 

/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.pyc in __init__(self, input_broadcastable, new_order, inplace)
    139                     raise ValueError(("new_order[%d] is %d, but the input "
    140                         "only has %d axes.") %
--> 141                         (i, j, len(input_broadcastable)))
    142                 if j in new_order[(i + 1):]:
    143                     raise ValueError((

ValueError: new_order[2] is 2, but the input only has 2 axes.```

**Comment by fchollet** [comment]
In a Keras model, the only requirements on the input are those of the initial layer. 

What does your input look like? I suspect you might be working with a 2D input. The imdb_lstm.py script in the examples folder provides a demo of how to build RNNs. You can replace the LSTM layer in that example with a SimpleRNN layer and it will work.

**Comment by patyork** [comment]
This is extent of the code - no inputs defined. The compilation fails.

I haven't delved deep enough into the implementation yet, but I'm guessing Theano finding that the input will be a fmatrix, so the `dimshuffle((1,0,2))` is invalid. I'm guessing this will require a reshape before-hand, depending on how the batches are being handled. Something along the line of

```python
X = X.reshape((batch_size, X.shape[0]/batch_size, X.shape[1])).dimshuffle((1,0,2))
```
or
```python
X = X.reshape((X.shape[0]/batch_size, batch_size, X.shape[1]))
```
I can't recall if Theano handles the second snippet intelligently, resulting in equivalent outputs from both of the above snippets.

**Comment by fchollet** [comment]
You were right, there was in fact an issue were recurrent layers had their default input shape set to matrix whereas they were expecting 3D inputs. This was not immediately apparent because the tests and example script did not implement any model where the recurrent layer came first.

The issue is fixed. Thanks for pointing this out!

**Comment by patyork** [comment]
Awesome, thanks for the update.
