### ISSUE TITLE
Problem in Image caption example 

### ISSUE THREAD

**Issue by shashankg7** [fchollet/keras#1804]
Can anyone explain the paramters involved in image captioning example in Keras.
The training data consists of images with 5 caption per image. Model gives prop distribution over next word given caption. So should I concatenate all 5 captions and pass that as sequence?

What does partial_caption here stands for and what is next_words? Is it one-hot encoded vector of next word after 1 caption out of 5? Also how to pass input at test time ?. I will only have image vector, but input requires [image, partial_caption].

**Comment by GriffinLiang** [comment]
(image, partial_caption)->(next_words)
(image, "word1 word2")->("word3")

**Comment by indra215** [comment]
@GriffinLiang could you please explain this in detail on how to give the inputs and also how to give the test data ?

**Comment by JiteshPshah** [comment]
How to do it for whole caption ?
