### ISSUE TITLE
Assertionerror when compiling LSTM

### ISSUE THREAD

**Issue by TimB92** [fchollet/keras#1806]
I try to classify Dutch and Belgian tweets (e.g. 2 classes) using LSTM. Right now, I have the following code:

```
max_features = 5000
maxlen = 140

model = Sequential()
model.add(Embedding(max_features, 128, input_length = maxlen)) 
model.add(LSTM(128, activation = 'sigmoid', inner_activation =  'hard_sigmoid', return_sequences = False))
model.add(Dense(2, activation = 'softmax'))

optimizer = Adam(lr = 0.001, beta_1 = 0.9, beta_2 = 0.999, epsilon = 1e-8)
model.compile(loss = 'categorical_crossentropy', optimizer = optimizer)

```

However, when I compile the model, I get an assertion error stating: AssertionError: The number of inputs given to the inner function of scan does not match the number of inputs given to scan.

At first, I thought it had something to do with my data, but the model does not 'receive' the data until you fit it, right?

**Comment by mandarhaldekar** [comment]
@TimB92 : did you find cause for this error ? Even I am facing the same issue!

**Comment by ymcui** [comment]
I tried your code on the latest version of Keras, nothing goes wrong here.

**Comment by TimB92** [comment]
Alright, so it turns out it has indeed something to do with an outdated theano version. I ran it on a different server of my University, which had the latest version, and it works now. So if you get this error, you'd probably want to update theano.
