### ISSUE TITLE
How to merge two graph models?

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#1807]
Is there "Merge" layer in Graph model? Just like: model.add(Merge(model_m, mode='sum'))

**Comment by lemuriandezapada** [comment]
I usually just add a linear activation layer and set the merge_mode in the add_node method.

**Comment by hx364** [comment]
just set the inputs as your previous nodes in the next layer.
For example, you have nodes named 'node_1' and 'node_2'.
In the next year. set inputs = ['node_1', 'node_2']

**Comment by snakeztc** [comment]
@hx364 Will that concatenate the output of node_1 and node_2?
