### ISSUE TITLE
Compile error due to Lambda Layer?

### ISSUE THREAD

**Issue by shyamupa** [fchollet/keras#1808]
This is a followup of another issue #1779. I upgraded to the latest version after the bugfix in #1801. 

Now I am getting another strange error for the argument of the Lambda layer when I do `model.compile(loss={'output':'categorical_crossentropy'}, optimizer='rmsprop')`,

```
def get_R(X):
    return K.dot(X[0], X[1])


line 1482, in get_output
    return func(X)
line 83, in get_R
    return K.dot(X[0], X[1])
KeyError: 0
```

Here is the [gist](https://gist.github.com/shyamupa/90a9050a6f35323c10df) to reproduce.
Is the bug still persisting in the Lambda Layer?

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by farizrahman4u** [comment]
For `Sequential` + `LambdaMerge` : 

```python
def get_R(X):
    return K.dot(X[0], X[1])
```

For `Graph` + `join Merge` + `Lambda` : (This is what you need)

```python
def get_R(X):
    a, b = X.values()
    return K.dot(a, b)
```

**Comment by shyamupa** [comment]
@farizrahman4u  I am porting my code to the new functional api, but seems like join mode is not there anymore. How to reproduce the above routine in the functional api?
