### ISSUE TITLE
Keras 0.3.2 is incompatible with TensorFlow 0.7.1?

### ISSUE THREAD

**Issue by lukovkin** [fchollet/keras#1809]
It seems that Keras 0.3.2 is incompatible with TensorFlow 0.7.1.
I was running Keras 0.3.2 succesfully with TensorFlow 0.6.0.

After running 'pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl' to upgrade to 0.7.1, I've got the following error message:

`ImportError: Traceback (most recent call last):
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/root/miniconda2/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.`

It happens in the very beginning, on the import (see gist - [https://gist.github.com/lukovkin/cbc13af27fa0aa7cf7e3](url))

Does anybody have this issue too?
May be doesn't need to be fixed right now, but worth mentioning in the docs?

**Comment by fchollet** [comment]
Your TensorFlow installation is broken; it seems that you do not have protobuf installed. Note that TensorFlow requires protobuf 3.0, and will fail will any previous version.
