### ISSUE TITLE
A small quibble about Embedding layer's input_dim argument 

### ISSUE THREAD

**Issue by jraoatlogic** [fchollet/keras#1829]
Just an observation: It looks to me that Embedding layer's input_dim is a bit confusing, it's not actually the input dimension (the input_length is), it's actually the vocabulary size.

**Comment by fchollet** [comment]
That's precisely what the input dimension of an Embedding layer is. Hence the name...

**Comment by jraoatlogic** [comment]
Sorry, I thought the input shape of Embedding is (nb_samples, input_length)? In this case input_dim is not related to the shape of input, but it's an limit on the input value.

**Comment by fchollet** [comment]
We're not talking about the input tensor *shape*, but about the input *dimension*, as in, the dimensionality of the input space. Which is the vocabulary size.

**Comment by alyato** [comment]
@jraoatlogic I check the the Embedding layer. It says that
![wwwwwww](https://cloud.githubusercontent.com/assets/6815071/17424359/5626ae30-5a80-11e6-8ac5-ee23c186e6d0.png)
The Embedding layer also use to the first layer.
I think that the ` input_length`  are sequences  contains many vocabularys.
Then the out_shape is (32,10,64).
I can refer the LSTM layer.
![eeeeeee](https://cloud.githubusercontent.com/assets/6815071/17424431/1fc41eee-5a81-11e6-9886-0d966dcad09d.png)

> so  the output of the Embedding layer can be as the input of the LSTM layers. Thanks
