### ISSUE TITLE
Using text.tokenizer for a CSV File

### ISSUE THREAD

**Issue by ml-tn** [fchollet/keras#184]
Hi,

I would like to use the "keras.preprocessing.text.Tokenizer" method in order to generate word sequencing for my corpus.
Is it possible to use the above mentioned method directly on a CSV file to generate a "keras.datasets.imdb"-like dataset ? 
If possible, could you give me some indications to implement the solution ?
Any kind of help is appreciated :)

**Comment by fchollet** [comment]
Note that the Keras tokenizer only generates 1-grams, not n-grams. This might not be what you want.

It is possible to pass a CSV file to a method such as `tokenizer.fit_on_texts(csv)` or `tokenizer.texts_to_matrix(csv)` (the tokenizer can handle any iterator over strings). The exact configuration would depend on your CSV file...
