### ISSUE TITLE
lstm error: blocks nested too deeply

### ISSUE THREAD

**Issue by eyaler** [fchollet/keras#1840]
i am running master imdb_lstm.py example
works for:
https://github.com/fchollet/keras/commit/3f905e4a357c05b216c29e34d26c12a4cd866f8e

broken by:
https://github.com/fchollet/keras/commit/73e563ecaf915d073d8b8fabc4a568ecddb0ea11

i can run by reducing LSTM(128) to LSTM(64)

error message for LSTM(128):

C:\Anaconda34\python.exe C:/Users/eyaler/Dropbox/python/keras-lstm/lstm.py
Using Theano backend.
DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/eyaler/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.4-64/tmp40r8j54g/m91973e5c136ea49268a916ff971b7377.lib and object C:/Users/eyaler/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.4-64/tmp40r8j54g/m91973e5c136ea49268a916ff971b7377.exp

Using gpu device 0: GeForce GTX 970 (CNMeM is enabled with initial size: 70.0% of memory, CuDNN 4004)
C:\Anaconda34\lib\site-packages\theano\tensor\signal\downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Loading data...
20000 train sequences
5000 test sequences
Pad sequences (samples x time)
X_train shape: (20000, 100)
X_test shape: (5000, 100)
Build model...
C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\cuda_ndarray.cuh(17) : warning C4005: 'PyString_Check' : macro redefinition
        C:\Anaconda34\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(63) : see previous definition of 'PyString_Check'
C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\cuda_ndarray.cuh(18) : warning C4005: 'PyString_FromString' : macro redefinition
        C:\Anaconda34\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(65) : see previous definition of 'PyString_FromString'
C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\cuda_ndarray.cuh(19) : warning C4005: 'PyString_AsString' : macro redefinition
        C:\Anaconda34\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(72) : see previous definition of 'PyString_AsString'
C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\cuda_ndarray.cuh(20) : warning C4005: 'PyString_FromStringAndSize' : macro redefinition
        C:\Anaconda34\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(66) : see previous definition of 'PyString_FromStringAndSize'
C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\cuda_ndarray.cuh(21) : warning C4005: 'PyString_Size' : macro redefinition
        C:\Anaconda34\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(74) : see previous definition of 'PyString_Size'

C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\cuda_ndarray.cuh(17) : warning C4005: 'PyString_Check' : macro redefinition
        C:\Anaconda34\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(63) : see previous definition of 'PyString_Check'
C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\cuda_ndarray.cuh(18) : warning C4005: 'PyString_FromString' : macro redefinition
        C:\Anaconda34\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(65) : see previous definition of 'PyString_FromString'
C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\cuda_ndarray.cuh(19) : warning C4005: 'PyString_AsString' : macro redefinition
        C:\Anaconda34\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(72) : see previous definition of 'PyString_AsString'
C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\cuda_ndarray.cuh(20) : warning C4005: 'PyString_FromStringAndSize' : macro redefinition
        C:\Anaconda34\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(66) : see previous definition of 'PyString_FromStringAndSize'
C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\cuda_ndarray.cuh(21) : warning C4005: 'PyString_Size' : macro redefinition
        C:\Anaconda34\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(74) : see previous definition of 'PyString_Size'

Traceback (most recent call last):
  File "C:/Users/eyaler/Dropbox/python/keras-lstm/lstm.py", line 52, in <module>
    class_mode="binary")
  File "C:\Anaconda34\lib\site-packages\keras\models.py", line 547, in compile
mod.cu
mod.cu(9609) : fatal error C1061: compiler limit : blocks nested too deeply

['nvcc', '-shared', '-O3', '-use_fast_math', '-arch=sm_52', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=m18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-IC:\Users\eyaler\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.4-64\cuda_ndarray', '-IC:\Anaconda34\lib\site-packages\numpy\core\include', '-IC:\Anaconda34\include', '-IC:\Anaconda34\lib\site-packages\theano\gof', '-IC:\Anaconda34\lib\site-packages\theano\sandbox\cuda', '-o', 'C:\Users\eyaler\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.4-64\tmpjn1b5rys\m4ede61e241807f1f7e84ac7a20c0e454.pyd', 'mod.cu', '-LC:\Users\eyaler\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.4-64\cuda_ndarray', '-LC:\Anaconda34\libs', '-LC:\Anaconda34', '-lcudart', '-lcublas', '-lcuda_ndarray', '-lpython34']
    self._train = K.function(train_ins, [train_loss], updates=updates)
  File "C:\Anaconda34\lib\site-packages\keras\backend\theano_backend.py", line 449, in function
    return Function(inputs, outputs, updates=updates)
  File "C:\Anaconda34\lib\site-packages\keras\backend\theano_backend.py", line 441, in __init__
    allow_input_downcast=True, **kwargs)
  File "C:\Anaconda34\lib\site-packages\theano\compile\function.py", line 320, in function
    output_keys=output_keys)
  File "C:\Anaconda34\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "C:\Anaconda34\lib\site-packages\theano\compile\function_module.py", line 1777, in orig_function
    defaults)
  File "C:\Anaconda34\lib\site-packages\theano\compile\function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\Anaconda34\lib\site-packages\theano\gof\link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\Anaconda34\lib\site-packages\theano\gof\vm.py", line 1003, in make_all
    no_recycling))
  File "C:\Anaconda34\lib\site-packages\theano\sandbox\cuda__init__.py", line 257, in make_thunk
    compute_map, no_recycling)
  File "C:\Anaconda34\lib\site-packages\theano\gof\op.py", line 970, in make_thunk
    no_recycling)
  File "C:\Anaconda34\lib\site-packages\theano\gof\op.py", line 879, in make_c_thunk
    output_storage=node_output_storage)
  File "C:\Anaconda34\lib\site-packages\theano\gof\cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "C:\Anaconda34\lib\site-packages\theano\gof\cc.py", line 1143, in **compile**
    keep_lock=keep_lock)
  File "C:\Anaconda34\lib\site-packages\theano\gof\cc.py", line 1595, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "C:\Anaconda34\lib\site-packages\theano\gof\cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Anaconda34\lib\site-packages\theano\gof\cc.py", line 1506, in compile_cmodule
    preargs=preargs)
  File "C:\Anaconda34\lib\site-packages\theano\sandbox\cuda\nvcc_compiler.py", line 396, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', GpuJoin(TensorConstant{0}, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0, GpuAlloc{memset_0=True}.0), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -use_fast_math -arch=sm_52 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=m18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -IC:\Users\eyaler\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.4-64\cuda_ndarray -IC:\Anaconda34\lib\site-packages\numpy\core\include -IC:\Anaconda34\include -IC:\Anaconda34\lib\site-packages\theano\gof -IC:\Anaconda34\lib\site-packages\theano\sandbox\cuda -o C:\Users\eyaler\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.4-64\tmpjn1b5rys\m4ede61e241807f1f7e84ac7a20c0e454.pyd mod.cu -LC:\Users\eyaler\AppData\Local\Theano\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.4-64\cuda_ndarray -LC:\Anaconda34\libs -LC:\Anaconda34 -lcudart -lcublas -lcuda_ndarray -lpython34', '[GpuJoin(TensorConstant{0}, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>, <CudaNdarrayType(float32, row)>)]')

Process finished with exit code 1

**Comment by ameasure** [comment]
I'm getting this too. It appears to be related to [this](https://support.microsoft.com/en-us/kb/315481) issue with the Visual Studio compiler although I don't know why it shows up now. It also worked fine for me in previous versions.

**Comment by DingKe** [comment]
The newly merged get_initial_states breaks for Linux too. I use thenao backend. After a lot tedious outputs, it complained that 'RuntimeError: maximum recursion depth exceeded'. I rolled back to the previous implementation, it's OK now.

**Comment by jgc128** [comment]
On Linux imdb_lstm.py works for me but lstm_text_generation.py does not.

@farizrahman4u Could you have a look?

**Comment by fchollet** [comment]
I reverted it. Please confirm that it fixed the issue.

**Comment by ameasure** [comment]
I'm still getting the same error.

**Comment by jgc128** [comment]
It works now for me

@ameasure Have you done `pip install -U git+git://github.com/fchollet/keras.git`?

**Comment by ameasure** [comment]
I did a pip uninstall keras, verified that I could no longer import keras, then did pip install -U git+git://github.com/fchollet/keras.git. I still get the same error on Windows 7, Theano backend, Anaconda Python 2.7 distribution with bleeding edge Theano.

A gist is here: https://gist.github.com/ameasure/25403119908e52869716

**Comment by eyaler** [comment]
@fchollet i still get "blocks nested too deeply" on bleeding edge. what is the hash for the revert?

**Comment by farizrahman4u** [comment]
@eyaler Its working for me. Maybe somethings wrong with your installation procedure? Or you are running some compiled python code (.pyc) from before?

**Comment by fchollet** [comment]
What's your complete config description?

**Comment by eyaler** [comment]
So, again my setup worked up to this commit. I validated it several times.
I am using windows 10 64 + anaconda 2.5 64 + python 3.4.4 + theano bleeding edge + cuda 7.5
no pyc just the lstm_imdb example. deleted cache.

**Comment by farizrahman4u** [comment]
Does anyone know what "blocks nested too deeply" actually mean?

**Comment by ameasure** [comment]
The traceback is full of the code below, repeated many many many times. I assume it means the code that Theano is generating has if statements nested too deeply:

9628         if (!PyErr_Occurred()) {
9629             PyErr_SetString(PyExc_RuntimeError,
9630                 "Unexpected error in an Op's C code. "
9631                 "No Python exception was set.");
9632             }
9633         goto __label_7;};
9634             }
9635             Py_XDECREF(out_sub);
9636             Py_XDECREF(start);
9637             start = stop;
9638             stop = NULL;
9639             
9640             sum += shape_V5[axis];
9641             stop = PyInt_FromLong(sum);
9642             slice_tuple = PyTuple_New(nd);
9643             if(slice_tuple == NULL){
9644                 {
9645         __failure = 7;
9646         if (!PyErr_Occurred()) {
9647             PyErr_SetString(PyExc_RuntimeError,
9648                 "Unexpected error in an Op's C code. "
9649                 "No Python exception was set.");
9650             }
9651         goto __label_7;};
9652             }
9653             section_slice = PySlice_New(start, stop, NULL);
9654             if(section_slice == NULL){
9655                 {
9656         __failure = 7;

**Comment by bayesrule** [comment]
Same issue here with the latest keras running the imdb_lstm.py example, any suggestions? @fchollet @farizrahman4u
