### ISSUE TITLE
No simple way to insert a projection layer for an RNN

### ISSUE THREAD

**Issue by ygoncharov** [fchollet/keras#1843]
It seems that there is no a simple way to insert a projection layer for an RNN as described in "Exploring the Limits of Language Modeling" (http://arxiv.org/pdf/1602.02410v2.pdf):

"Exhaustively trying all combinations would be extremely time consuming for such a large data set, but our findings suggest that LSTMs with a projection layer (i.e., a bottleneck between hidden states as in (Sak et al., 2014)) performed well."

**Comment by pasky** [comment]
To paraphrase for those that don't want to look at that paper and its reference [(Sak et al., 2014)](http://arxiv.org/abs/1402.1128) in detail - the idea is:

  * Normally, the memory units state is carried in the hidden activation vector and that one is referenced in the next time step
  * Here, the memory units state is compressed (projected) into a *recurrent* vector which is referenced in the next time step, and has lower dimensionality than the number of memory units (say, 1/4)
  * Furthermore, the output sequence is also not the state of the memory units, but another projection in an *output* vector (we do this with a followup Dense layer often enough anyway); the *output* vector is this projection, also concatenated with the *recurrent* vector

This should be pretty easy to do, seems to me, and 1602.02410 seems like a good paper, so if they say it's important, it might be worth a shot.

**Comment by manish-kumar-garg** [comment]
Is there any way to achieve this in tensorflow2.0
