### ISSUE TITLE
algorithms implementation

### ISSUE THREAD

**Issue by fayeshine** [fchollet/keras#1845]
could keras implement Maxout activation layer?
and the newly weight normalization?
http://arxiv.org/abs/1602.07868

**Comment by fchollet** [comment]
There is already a Maxout layer (fully-connected only). As for weight normalization, it wouldn't be a layer, and it is easy to add to a Keras layer yourself.

**Comment by llp1992** [comment]
the implement of weight normalizationhttps://github.com/openai/weightnorm

**Comment by llp1992** [comment]
the implement of weight normalization

**Comment by llp1992** [comment]
the implement of weight normalization      https://github.com/openai/weightnorm
