### ISSUE TITLE
the efficiency of backends

### ISSUE THREAD

**Issue by fayeshine** [fchollet/keras#1846]
is the efficiency using tensorflow much lower than using theano?
I tested on my data, using 1 cpu and 2 titan X with tensorflow is 3 times slower than using  1 titan X with theano

**Comment by philipperemy** [comment]
Concerning the performance on CPU, the documentation of Keras states the following:

From https://github.com/fchollet/keras/wiki/Keras,-now-running-on-TensorFlow

On CPU, here's what performance looks like right now on some basic examples scripts. This on a 2.2 GHz Intel Core i7.

In summary: Theano has well-optimized tensor loops compared to TensorFlow, but relies on a poorly-performing CPU convolution operation (of course, few people would actually attempt to train convnets on CPU, although with TensorFlow it wouldn't be too unrealistic).

Task	TensorFlow	Theano
mnist_mlp.py: compilation (s)	0.6	5.9
mnist_mlp.py: runtime/epoch (s)	7.5	6.3
imdb_lstm.py: compilation (s)	39.3	38.3
imdb_lstm.py: runtime/epoch (s)	283	123
mnist_cnn.py: compilation (s)	0.8	11.4
mnist_cnn.py: runtime/epoch (s)	190	3230

The similar benchmark on GPU will be added soon.

Can you provide the script that you're running? I haven't seen any big differences in performance between the backends.

**Comment by ipod825** [comment]
On GPU, I also feel that the running time (at least for cnn) theano is much faster than tensorflow. Though I don't know if tensorflow has counterpart of the `mode=FAST_RUN/FAST_COMPILE` environment variables. I think the comparison in https://github.com/fchollet/keras/wiki/Keras,-now-running-on-TensorFlow should mention the theano mode used.

**Comment by gw0** [comment]
I have done some comparisons of both backends on CPU and GPU of the LSTM example in ticket https://github.com/fchollet/keras/issues/855#issuecomment-228344543.

**Comment by nouiz** [comment]
This depend of the model and its size... See our last Theano tech report
that have more comparison:

https://arxiv.org/abs/1605.02688

Mostly, there is no clear winner, it is case dependent and when there is a
difference, it isn't super big.
