### ISSUE TITLE
Failed to merge two  embedding nodes with graph model?

### ISSUE THREAD

**Issue by njoe9** [fchollet/keras#1847]
I'm using graph model to create bidirectional RNN,and want to merge two embedding nodes into one embedding node as the input of LSTMs.The code snippet is the followings:
```
embedding_size=100
def get_R(x):
    return K.concatenate(x)

def shape(x):
    return (None,200)
    
print('Build model...')
model = Graph()
model.add_input(name='input', input_shape=(maxlen,), dtype=int)
model.add_input(name='input_c', input_shape=(maxlen_c,), dtype=int)
               
model.add_node(Embedding(maxfeatures, embedding_size,weights=init_weight),
               name='embedding0', input='input')

model.add_node(Embedding(maxfeatures_c, embedding_size,weights=init_weight_c),
               name='embedding1', input='input_c')        

model.add_node(Lambda(get_R,output_shape=shape), name='embedding', inputs=['embedding0','embedding1'], merge_mode='join')

model.add_node(LSTM(lstm_output_size), name='forward', input='embedding')
model.add_node(LSTM(lstm_output_size, go_backwards=True), name='backward', input='embedding')
```
the compile error as the follows:
```
AssertionError: Incompatible shapes: layer expected input with ndim=3 but previous layer has output_shape (None, 200)
```
I succeeded to merge the two embeddings using Sequence model.

I've tried to solve it by following the methods from #1779 ,but i failed.

Did i miss something?

Thanks.

-----------------
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by pasky** [comment]
Could it be that your Lambda is messing the dimensions up? I'm not sure what is your shape() supposed to return but RNNs indeed obviously want 3d sequences.  What does the 200 represent?

IMHO a more natural way to merge these things is

````python
model.add_node(name='embedding', inputs=['embedding0', 'embedding1'], merge_mode='concat', layer=Activation('linear'))
````

**Comment by njoe9** [comment]
@pasky thanks.
I used the natural way to merge the two embeddings.
It's ok.

**Comment by alyato** [comment]
@pasky I'm confused by the output_shape in `Lambda layer`, how can i understand it and set its? Thanks.

**Comment by alyato** [comment]
@pasky how can understand your code .
`model.add_node(name='embedding', inputs=['embedding0', 'embedding1'], merge_mode='concat', `layer=Activation('linear')`)`

> I  think  the output_shape of embedding0 and embedding1 are 3-dim.   when the `merge_mode='concat'` , does  the output_shape be reshaped to 2-dim. and 
 what does `layer=Activation('linear')` do?
