### ISSUE TITLE
Give different input to LSTM at different timestep

### ISSUE THREAD

**Issue by mandarhaldekar** [fchollet/keras#1849]
My goal is to implement a many to one LSTM of 3 timestep. First step will take input as image features extracted from VGGNet fc7 (size = 4096), second will take one hot encoded vector of size 42 and third step will take another one hot encoded vector of size 42.  See following figure

![manytoone](https://cloud.githubusercontent.com/assets/918253/13385395/3a6313ca-de6e-11e5-86ce-3084e6bc4d99.png)

How do I model it in Keras ? It seem very simple as I just have to one one LSTM, but I do not understand how to give different input to LSTM based on timestep while training. How do I specify that ?

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by around1991** [comment]
LSTMs need to have the same input vector dimension at all timesteps. Concretely, this means that all of your input vectors need to live in the same vector space.

What are the one-hot vectors you want to feed in encoding? Can you not just concatenate them to your VGGNet feature vectors?

**Comment by pasky** [comment]
What you describe is pretty unusual. Consider more carefully how LSTMs and RNNs work - if you need to feed it inputs with different inputs, how should your weight matrix look like?

If you want to gate updates of hidden representation based on the VGG input by the one-hot vectors, maybe an easier alternative could be feeding all three into a Highway Network, take a look at these.

Another alternative is to just code an "unrolled" LSTM (but an output gate, really? GRU may make more sense) into your model manually.

**Comment by pasky** [comment]
Expanding a bit more on this - rather than what you presented, isn't a better view to use the VGG as initial hidden state (memory units) to feed through a 2-step LSTM?  (I personally think what I proposed above is still more reasonable, but this could work.) 

This should be possible to do with Keras as long as you'd be able to set the initial hidden states from other layers. Unfortunately, that's not implemented yet.

But more of us would like that feature, for example to be able to implement the Read&Comprehend paper or the family of http://arxiv.org/abs/1509.06664 based papers.

**Comment by mandarhaldekar** [comment]
One hot encoded vectors are nothing but one hot encoding of objects present in an input image. E.g. consider an image of car on the road. First one hot encoded vector would represent "car" and second would represent "road".  (Instead of this, it would be better to pass CNN features of those objects, but that itself is a challenging task of extracting features of particular object from image, so I am trying first with this approach).  Goal is to see how well network captures relations between objects.

To have same dimension of inputs, I padded one hot encoded vectors .Then I did concatenate and reshape(see code below) so that features will have dimension "nb_instances x 3 x 4096" . Does this make sense to have input dimension equal to number of timesteps in LSTM ? I hope this makes my use case more clear!

```
nb_instances = X_img.shape[0]
max_len = 3  # 3 timesteps
img_dim = 4096
X_obj1 = sequence.pad_sequences(X_obj1, maxlen=4096)
X_obj2 = sequence.pad_sequences(X_obj2, maxlen=4096)

# Concatenate and reshape
feats = np.append(X_img, X_obj1, axis = 1)
feats = np.append(feats, X_obj2, axis = 1)
feats = np.reshape(feats, (nb_instances, 3, 4096))

model = Sequential()
model.add(LSTM(output_dim = num_hidden_units_lstm, return_sequences=False, input_shape=(max_len, img_dim)))  
model.add(Dense(num_hidden_units_mlp, init='uniform')) 
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(Dense(num_hidden_units_mlp, init='uniform'))
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))
```

**Comment by pasky** [comment]
I don't really see how that approach makes sense.  Just to be clear,
the image and the one-hot encodings all pass through the same weight
matrices.  So your network couldn't distinguish the first 42 dimensions
of the image representation from the object indicators.  I'm not sure
it will be learning anything useful efficiently.

**Comment by mandarhaldekar** [comment]
@pasky 
Yes I see that. I need something like this https://github.com/jazzsaxmafia/show_and_tell.tensorflow/blob/master/model.py#L61

This is implementation of[ show and tell]( http://arxiv.org/abs/1411.4555). It has different weight vectors for image and sentences and it is differentiated based on current time step value "i".

**Comment by aloksingh3110** [comment]
did you get any solution for you problem?
I am getting same problem can you help me?
