### ISSUE TITLE
Can I do joint layer training in Keras?

### ISSUE THREAD

**Issue by marcel-proust** [fchollet/keras#185]
I have video and audio input and I want to train a joint layer using feedforward neural network. The architecture is as follows: 

audio input  (goes to) hidden layer (goes to)                                                                               
video input  (goes to)  hidden layer (goes to)    joint layer (goes to) output              

I did this on theano but I wonder if it is doable in Keras. If yes, can you provide me a simple code? Thanks

ps: I couldn't draw the figures as I wanted. The architecture is similar to Figure 3 of this paper http://ai.stanford.edu/~ang/papers/icml11-MultimodalDeepLearning.pdf

**Comment by fchollet** [comment]
Sure, you'd need to use a Merge layer. Here's the corresponding doc, including a code snippet similar to what you want to do: http://keras.io/layers/core/#merge
