### ISSUE TITLE
ProgBar Usage Documentation

### ISSUE THREAD

**Issue by anjishnu** [fchollet/keras#1851]
The latest version of the keras library no longer has an example how to use the ProgBar utility.

**Comment by EderSantana** [comment]
:+1:

**Comment by EderSantana** [comment]
:+1: yes, I was looking for the same yesterday. Documentation missing. Progbars are usually useful. I used to copy paste usage from an example and now it is gone :D

**Comment by anjishnu** [comment]
Yeah I managed to find some documentation about the progbar update callback - but it's still not much help in figuring out how best to actually use a ProgBar. I'm currently code derived from the old cifar10 example and am not sure if the reason it was removed was because the class is being deprecated.

**Comment by EderSantana** [comment]
Do you want to PR a contribution to the docs? Maybe Keras.io could get a section dedicated to the `utils`, @fchollet ?

**Comment by anjishnu** [comment]
I would, but I actually don't know everything about the ProgressBar. If I get time I'll try to go through the code, find out how the whole thing works and submit a PR.

**Comment by fchollet** [comment]
Sure, you could add a utils section in the doc. I would also recommend
moving datasets/data_utils to utils btw.
