### ISSUE TITLE
input size must be a multiple of batch_input_shape  : after validation split

### ISSUE THREAD

**Issue by earonesty** [fchollet/keras#1853]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

### the x/y matrices need to have their first dimension as a multiple of the batch_size, or else you get an error.  this is true even after the validation split ... so the validation split has to be a multiple of 1/batch_size 

```
X = np.zeros(32000, 20, 16), dtype=np.bool)
y = np.zeros(32000, 16), dtype=np.bool)

model = Sequential()
model.add(LSTM(100, batch_input_shape=(32, 20, 16), stateful=True, return_sequences=False))
model.add(Dense(cDex.nchar, activation='softmax'))
model.compile(optimizer='rmsprop', loss='categorical_crossentropy')


# this works
model.fit(X, y, batch_size=32, nb_epoch=1)

# this fails
model.fit(X, y, batch_size=32, nb_epoch=1, validation_split=0.1)

# this works
model.fit(X, y, batch_size=32, nb_epoch=1, validation_split=0.0625)

```

**Comment by fchollet** [comment]
Yes, for stateful networks. All of this is extensively described in the RNN documentation, and in the FAQ.
