### ISSUE TITLE
LSTM argument

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [fchollet/keras#1854]
I am getting an error when i am trying to change those argument inside a LSTM function `LSTM(W_regularizer=None, U_regularizer=None, b_regularizer=None, dropout_W=0.0, dropout_U=0.0)`
Did they always exist or did the typo changed ? Because they are on the keras documentation. Thanks!

**Comment by pasky** [comment]
These are new parameters (introduced ~last week), are you using the latest Keras?

**Comment by jesuisnicolasdavid** [comment]
Well i am using 0.3.2, and a pip install --upgrade keras gives me a Requirement already up-to-date..

**Comment by pasky** [comment]
This feature is not included in 0.3.2.  When creating an issue, you are presented with (...you seemed to delete):

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

**Comment by jesuisnicolasdavid** [comment]
You are the man! Thanks for the great answer!

**Comment by pasky** [comment]
You're welcome. :)
