### ISSUE TITLE
Convolutional autoencoder volumetric images

### ISSUE THREAD

**Issue by hawk31** [fchollet/keras#1859]
Hello, I am currently trying to build a convolutional autoencoder with Keras for 3d volumetric images with one channel only. My images are of size 10x10x10 and stored in a numpy array of shape (n_samples, 1,10, 10, 10).

The plan was to use the new 3D Convolutional layers to try to reconstruct the images. My (little) knowledge on convolutional autoencoders is that there is a convolutional encoding step (convolution and pooling layers), followed by dense layers, and then another convolutional encoding step (convolution + upsampling). However, I can not find a working example of something like this in Keras.

My network is currently defined as:

``` python
def convolutional_autoenc(boxsize = 10):
    print("Compiling convnet. Checking shape consistency.")
    model = Sequential()
    # Convolutional encoding step
    model.add(Convolution3D(32, 3, 3, 3, input_shape = (1, boxsize, boxsize, boxsize)))
    model.add(Activation(relu))
    model.add(MaxPooling3D(pool_size=(2, 2, 2)))
    model.add(Dropout(0.25))
    model.add(Convolution3D(64, 3, 3, 3))
    model.add(Activation(relu))
    model.add(MaxPooling3D(pool_size = (2, 2, 2)))
    model.add(Dropout(0.4))
    # Dense layers
    model.add(Flatten())
    model.add(Dense(256))
    model.add(Activation(relu))
    model.add(Dropout(0.5))
    model.add(Dense(256))
    model.add(Activation(relu))
    model.add(Dropout(0.4))
    model.add(Reshape((10, 10, 10)))
    # Deconvolutional decoding step
    model.add(Convolution3D(64, 3, 3, 3))
    model.add(Activation(relu))
    model.add(Dropout(0.25))
    model.add(UpSampling3D(size = (2, 2, 2)))
    model.add(Convolution3D(32, 3, 3, 3))
    model.add(Activation(linear))
    # Reshape to original shape
    model.add(Reshape((boxsize, boxsize, boxsize)))
    adam = Adam()
    model.compile(loss = 'mean_absolute_error', optimizer = adam)
    return(model)
```

However, this returns `ValueError: total size of new array must be unchanged`. I believe there is something wrong with shapes in the network definition. Can someone point out the mistakes or provide a working example of a conv autoencoder working in keras? Any help is greatly appreciated.

**Comment by pkainz** [comment]
You need to reshape the dense layer into 3D (+n channels) before applying the de-convolution. Each `Reshape` layer must contain as many elements as the previous layer outputs. 
Further, the number of units in your last dense layer must meet some criteria such that your output can be equal to your input size. So something like the following may work for a `boxsize` of 10:
```python
def convolutional_autoenc(boxsize = 10):
    print("Compiling convnet. Checking shape consistency.")
    model = Sequential()
    # Convolutional encoding step
    model.add(Convolution3D(32, 3, 3, 3,
                            border_mode='same', 
                            activation='relu',
                            input_shape = (1, boxsize, boxsize, boxsize)))
    model.add(MaxPooling3D(pool_size=(2, 2, 2)))
    model.add(Dropout(0.25))
    model.add(Convolution3D(64, 3, 3, 3, 
                            border_mode='same', 
                            activation='relu'))
    model.add(MaxPooling3D(pool_size = (2, 2, 2)))
    model.add(Dropout(0.4))
    # Dense layers
    model.add(Flatten())
    model.add(Dense(256, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(256, activation='relu'))
    model.add(Dropout(0.4))
    model.add(Reshape((32, 2, 2, 2))) # reshape 256 to 32x2x2x2
    # Deconvolutional decoding step
    model.add(Convolution3D(64, 3, 3, 3,
                            border_mode='same',
                            activation='relu'))
    model.add(Dropout(0.25))   
    model.add(UpSampling3D(size = (2, 2, 2)))
    model.add(ZeroPadding3D(padding = (1,1,1))) # needed to match the output shape
    model.add(Convolution3D(32, 3, 3, 3,
                            border_mode='same',
                            activation='relu'))
    model.add(UpSampling3D(size = (2, 2, 2)))
    model.add(Convolution3D(1, 3, 3, 3, 
                            activation='linear'))
    model.add(Reshape((boxsize,boxsize,boxsize)))
    
    adam = Adam()
    model.compile(loss = 'mean_absolute_error', optimizer = adam)
    model.summary()
    
    return(model)
```
You can use `model.summary()` after the layers to debug the model building step and see at which layer the errors occur. Also, check out this answer here: https://groups.google.com/forum/#!topic/keras-users/BBeFDwRjaT0.
However, I doubt that your function will work for arbitrary `boxsize`s, because you need to control the de-convolution path such that the output shape matches the input shape. 

You can also omit the dense layer and represent the bottleneck as convolutional layer, like in this example: http://blog.keras.io/building-autoencoders-in-keras.html.
