### ISSUE TITLE
Host documentation on readthedocs.org

### ISSUE THREAD

**Issue by hammer** [fchollet/keras#186]
It's quite nice to be able to [generate a PDF](http://docs.readthedocs.org/en/latest/features.html#pdf-generation) from the documentation for offline reading.

**Comment by hammer** [comment]
I should also note that [MkDocs doesn't currently allow PDF export](https://github.com/mkdocs/mkdocs/issues?q=pdf)

**Comment by fchollet** [comment]
The Keras documentation is just a set of Markdown files (Github-flavored). You can very easily convert them to PDF. A few solutions are available online, including: https://gitprint.com/

readthedocs.org is compatible with the Keras documentation, but the reason readthedocs exists is to offer easy hosting to projects that don't have a dedicated website. Keras does, so it's not clear to me what readthedocs would bring that Keras.io doesn't do... what do you think?

**Comment by hammer** [comment]
There are a number of features that make Read the Docs preferable to self-hosted Markdown. They are listed on the page that I linked above. I think the most important are PDF export, versioning, and search. Note that you can have Read the Docs serve your documentation under the keras.io domain, if that's what's giving you pause.

Also, your solution for exporting your documentation to PDF does not work well as it can only handle one Markdown document at a time. I'd like to export all of the documentation as a single PDF.

**Comment by fchollet** [comment]
Search would be nice to have. I'll look into it.

**Comment by hammer** [comment]
Thanks for your consideration! You've done such a great job on API design and documentation content that it would be a shame to fall short on documentation presentation.

**Comment by fchollet** [comment]
Here you go: https://keras.readthedocs.org/en/latest/

Search doesn't seem to work though (maybe it requires more time to build an index?). 

The inability to choose a source folder (the un-editable default is `docs/`, whereas Keras uses `docs/sources`) means the documentation structure is messed up.

I'm also pretty sure Google will get pissed at the duplicate content. That is a potentially significant issue.

**Comment by JGuillaumin** [comment]
Hi, 
It works with this docker image : https://hub.docker.com/r/fiware/md2pdf/. 
I generated the documentation, with Keras==2.0.8. 
PDF : https://drive.google.com/open?id=0BxaH5r4iW8cWeEdEMG1lQ0lIMFk !

**Comment by JGuillaumin** [comment]
Now you can find a PDF for 2.1.6 : https://github.com/JGuillaumin/keras-doc-pdf/releases
