### ISSUE TITLE
Change subsample from (1,1) into (4,4) in Convolution2D 

### ISSUE THREAD

**Issue by dsy412610** [fchollet/keras#1860]
When I use Convolution2D in my model, I set subsample to (4,4). And now I find a problem is that the training time is even longer than only using CPU. But when I change this value into (1,1), the GPU works. Why? And is there any solutions to this problem?

**Comment by philipperemy** [comment]
First of all, I would like to recap the formula (from the theory) on how the output is computed from the input for a Conv Layer.
If a Conv Layer has a kernel of size kernelsize, stride (aka outsample) as strides and border paddings as pad, the formula is:
shape(out) = (shape(input) - kernelsize + 2*pad)/strides+1.
For example, input = (224,224), ks = (11,11), strides=(4,4), pads=(2,2), you have 
output = (224-11+4)/4+1 = 55.25.
When you have a non integer value, you have a risk that the backend shouts an error. This is for example the case in Torch.

When you select a stride of (1,1), you play safe as you will always have an integer.

Obviously, the bigger your output is, the longer it will take to train. So it's understandable that (1,1) will take much more train than (4,4). You can even quantify it. If your ks is (1,1), having a stride of (1,1) on a 8x8 image will have an output of 8x8. Having a stride of (4,4) will yield 2x2. Ratio is (8*8)/(2*2) = 16 times slower.

Hope this helps.

**Comment by dsy412610** [comment]
Thank you very much. My output is a non integer value, but I have solved this problem by this way: https://github.com/Theano/Theano/issues/4158

**Comment by philipperemy** [comment]
Thanks! Can you close the issue then?
