### ISSUE TITLE
Restoring Lambda from YAML

### ISSUE THREAD

**Issue by temporaer** [fchollet/keras#1863]
Is there a reason why `Lambda` does not have `get_config()` and therefore does not pickle it's `.function` member? It seems rather fundamental to its functionality. Recreating from yaml fails, and `function` is not mentioned in the config file. A minimal example that should work IMHO:

```
from keras.layers.core import Lambda
from keras.models import Graph as GraphModel
from keras.models import model_from_yaml
import theano

g = GraphModel()
g.add_input('x', input_shape=(7, 13))
g.add_node(Lambda(lambda x: x.sum(1), output_shape=(None,)), name='out', input='x', create_output=True)
g.compile(optimizer='SGD', loss=dict(out='mse'))
with open("xyz.cfg", "w") as f:
    f.write(g.to_yaml())
    g.save_weights("xyz.h5", overwrite=True)
with open("xyz.cfg") as f:
    g = model_from_yaml(f.read())
    g.load_weights("xyz.h5")
```

**Comment by shyamupa** [comment]
Will this help #1800?

**Comment by temporaer** [comment]
@shyamupa thank you for the quick response! Your suggestion will help if I subclass `Lambda`, and register it for loading as suggested in #1800. However, my question is, why doesn't `Lambda` take care of pickling `.function` in the first place? `LambdaMerge` does it, but `Lambda` does not. For the above example, It'll boil down to

```
class Sum(Lambda):
    def __init__(self):
        super(Sum, self).__init__(function=lambda x: x.sum(1))
# ...
g.add_node(Sum(), ...)
# ...
g = model_form_yaml(f.read(), dict(Sum=Sum))
```
it works, but why not really just pickle `Lambda` correctly?
