### ISSUE TITLE
Maximum Depth Recursion limit exceeded

### ISSUE THREAD

**Issue by EnriqueSMarquez** [fchollet/keras#1865]
Hello all,

How can I avoid hitting the recursion limit? I would not like to change the system recursion limit.

I am getting a maximum recursion limit error when adding layers into a model, after several models have been created and erased. Thank you

Enrique Marquez

**Comment by ymcui** [comment]
Well, this is a problem of `python`
The system set a limit on the recursion depth for protection purpose.
To solve this, add following code in the beginning of your script.
'''
import sys
sys.setrecursionlimit(10000)
'''
Hope it work for you :)
