### ISSUE TITLE
test_models.py fails

### ISSUE THREAD

**Issue by tdhd** [fchollet/keras#187]
The model test fails for the current version.

See below for `verbose=0`:

$ python test/test_models.py 
Test sequential
Traceback (most recent call last):
  File "test/test_models.py", line 43, in <module>
    model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch, show_accuracy=True, verbose=0, validation_data=(X_test, Y_test))
  File "/home/thread/workspace/keras/keras/models.py", line 294, in fit
    return callbacks.callbacks[-1]
IndexError: list index out of range

**Comment by fchollet** [comment]
Thank you for pointing this out! It's fixed now. A screw-up on my part.
