### ISSUE TITLE
Loading weights for part of the network

### ISSUE THREAD

**Issue by KlaymenGC** [fchollet/keras#1873]
Hello,

Say I have weights from a trained network and now I want to change the architecture of the network by adding 2 more filters for the last convolutional layer. For the new network, I don't want to train it from scratch again, I want to load the existing weights to the network while initializing the weights for the added 2 filters using other techniques. Is there a way to do it in Keras?

**Comment by tboquet** [comment]
You could take a look [here](https://github.com/fchollet/keras/blob/master/examples/conv_filter_visualization.py#L98-L107) and in #1728.

**Comment by KlaymenGC** [comment]
@tboquet Thanks for your reply, I think I don't have trouble adding weights to layers. The thing is, I'm now using a sequential model, say the last convolutional layer is:
```Convolution2D(10, 3, 3, activation='relu')```
and I've got the trained weights, then I change the last conv layer to:
```Convolution2D(12, 3, 3, activation='relu')```
and I still want to use the trained weights for the first 10 filters while initializing the weights of the remaining filters using ```he_normal``` or something like that.
Could you please elaborate?

**Comment by pasky** [comment]
According to PR #1796, the canonical way to do this is to build both the old and the new model (you don't need to compile the old one), load weights to the old one, then use the .nodes property to manually transfer the weights to the new model.

**Comment by tboquet** [comment]
@KlaymenGC oops sorry I didn't understood your question, @pasky is right!

**Comment by KlaymenGC** [comment]
@pasky thanks for the reply, but it seems that sequential models don't have this ```node``` property... any ideas?

**Comment by pasky** [comment]
I'd try .layers for Sequential models - sorry, it's been long I've been using these.

**Comment by fchollet** [comment]
For a Sequential model, you can get the layers by index:

```python
weights = model.layers[5].get_weights()
```

Or by name, if all your layers are named;
```python
layer_dict = dict([(layer.name, layer) for layer in model.layers])
weights = layer_dict['some_name'].get_weights()
```

**Comment by KlaymenGC** [comment]
@fchollet yeah but adding weights from
```Convolution2D(10, 3, 3, activation='relu')```
to
```Convolution2D(12, 3, 3, activation='relu')``` while initializing the weights for the last 2 filters using built-in initialization methods is not possible I guess

**Comment by fchollet** [comment]
Sure it's possible. But it will require manipulating the weight array in
Numpy-space before calling set_weights(). e.g. array[:-2, :, :, :] =
old_array[:, ;, :, :]

**Comment by KlaymenGC** [comment]
@fchollet nice, thanks for your help!

**Comment by bhack** [comment]
@fchollet Is it possible instead to add an extra channel to the weights?

**Comment by Raazzta** [comment]
hi @KlaymenGC, all , could you share your complete code how to combine the weights? 
new_weights = pretrained_weights + he_normal

Thanks.
