### ISSUE TITLE
to_graph and plot should show the shape of the expected input and output

### ISSUE THREAD

**Issue by hlin117** [fchollet/keras#1877]
First, I love the `keras.utils.visualize_util` module. It makes a quick summary of the neural network possible.

![model](https://cloud.githubusercontent.com/assets/1865885/13476093/cad1236a-e08b-11e5-9b65-814b74e1aba1.png)

But it would be nice to also annotate the visualization with the expected input and output shape. This would make debugging the neural network easier.

How does a change to `keras.utils.visualize_util.plot` and `keras.utils.visualize_util.to_graph` with this feature sound?

**Comment by hlin117** [comment]
(It would also be nice to show the activation of a layer, if any. But that might be bundled in a separate issue.)

**Comment by fchollet** [comment]
That sounds quite reasonable, but it should be made optional. Are you preparing a PR?

**Comment by hlin117** [comment]
Well, I just encountered a pleasant surprise.

I went through the source code, and it turns out that 

1. There are three kwargs that are undocumented for `to_graph`. See [this line](https://github.com/fchollet/keras/blob/master/keras/utils/visualize_util.py#L119) of the source code. 
    * `recursive=True`
    * `show_shape=False`
    * `connect_to=None`<br>
It's self explanatory what `show_shape` does. However, since I am only starting to use Keras, I'm unfamiliar with what the two other options are. 
2. `plot` can not accept these kwargs. See [here](https://github.com/fchollet/keras/blob/master/keras/utils/visualize_util.py#L152)

I have three future PR requests:

1. Change the `**kwargs` [here](https://github.com/fchollet/keras/blob/master/keras/utils/visualize_util.py#L144) in `to_graph` to use explicit kwargs.
2. Documenting the undocumented kwargs. However, I'll need more information about what the kwargs `recursive=True` and `connect_to=None` do.
3. Adding the three kwargs to `plot`.

What do you think about these requests, @fchollet?

![screenshot 2016-03-02 23 53 15](https://cloud.githubusercontent.com/assets/1865885/13485936/0f72610a-e0d2-11e5-9a69-d8343a477444.png)

**Comment by hlin117** [comment]
You'd notice from the graphic that the shapes are like `(None, 1500)`, `(None, 300)`, etc. I'm actually curious why this is the case.

**Comment by hlin117** [comment]
Seems that this was addressed in 98c6c8b3b6c81de7ec3583f49d45a52c38b42d2d. Closing issue.

**Comment by dhanush987** [comment]
What does the None mean actually in the diagram. Is that a bug ?
