### ISSUE TITLE
Merge Two LSTM

### ISSUE THREAD

**Issue by resplendentfrever** [fchollet/keras#1890]
Hello,
I am trying to merge the output of two LSTM and then predict the polarity of a word in the sentence.
So my X-train has dimension (No of sentences,maxlen,word_embedding_dim) and Y_Train has dimension(No of sentences,no of classes).
here is my code:
left = Sequential()
left.add(LSTM(output_dim=600, input_shape=(80,600),return_sequences=True))
left.add(TimeDistributedDense(600))

right = Sequential()
right.add(LSTM(output_dim=600, input_shape=(80,600),return_sequences=True))
right.add(TimeDistributedDense(600))

model = Sequential()
model.add(Merge([left, right],mode='sum'))
model.add(TimeDistributedDense(4))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='rmsprop')

model.fit([X_left, X_right], Y_train, nb_epoch=100,validation_split=0.2,show_accuracy=True)
~
But i am getting this issue:
TypeError: ('Bad input argument to theano function with name "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py:380"  at index 2(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (128, 4).')
Please help me out

**Comment by tboquet** [comment]
What is the shape of `Y_train`? Is it a sequence or a vector with shape `(n, 4)`?

**Comment by resplendentfrever** [comment]
It is a vector of (n,4).

**Comment by farizrahman4u** [comment]
The output of your model is 3D, but your Y_train is your 2D. Try this:

```python
left = Sequential()
left.add(LSTM(output_dim=600, input_shape=(80,600)))
left.add(Dense(600))

right = Sequential()
right.add(LSTM(output_dim=600, input_shape=(80,600)))
right.add(Dense(600))

model = Sequential()
model.add(Merge([left, right],mode='sum'))
model.add(Dense(4))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='rmsprop')

model.fit([X_left, X_right], Y_train, nb_epoch=100,validation_split=0.2,show_accuracy=True)
```

The above code will run without any error, but might not be what you are looking for. Can you elaborate what you are trying to do here?

**Comment by tboquet** [comment]
So the part where you merge the 2 LSTM works. In fact, `TimeDistributedDense` will output you a tensor with a shape `(batch_size, 80, 600)`.

**Comment by farizrahman4u** [comment]
@tboquet But his `Y_train` is of shape (batch_size, 4) which doesnt make sense.

**Comment by tboquet** [comment]
@farizrahman4u yep sure your solution works :). Sorry I wrote my comment at the same time. I wanted to point out that the merging part was ok but the last `TimeDistributedDense` outputs a tensor having the wrong shape. Would it make sense to `Flatten` after the merge and take all the sequences?

**Comment by farizrahman4u** [comment]
But then the output_dim wouldn't be 4. `Y_train` is of shape `(n, 4)`.

**Comment by tboquet** [comment]
I was thinking about:

```python
left = Sequential()
left.add(LSTM(output_dim=600, input_shape=(80,600),return_sequences=True))
left.add(TimeDistributedDense(600))

right = Sequential()
right.add(LSTM(output_dim=600, input_shape=(80,600),return_sequences=True))
right.add(TimeDistributedDense(600))

model = Sequential()
model.add(Merge([left, right],mode='sum'))
model.add(Flatten())
model.add(Dense(4))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='rmsprop')

model.fit([X_left, X_right], Y_train, nb_epoch=100,validation_split=0.2,show_accuracy=True)
```

**Comment by farizrahman4u** [comment]
That would work.

**Comment by tboquet** [comment]
:sunglasses: 
And to extend the idea, having something like:

```python
def f(x):
    return x[:, 10:, :]

 left = Sequential()
left.add(LSTM(output_dim=600, input_shape=(80,600),return_sequences=True))
left.add(TimeDistributedDense(600))

right = Sequential()
right.add(LSTM(output_dim=600, input_shape=(80,600),return_sequences=True))
right.add(TimeDistributedDense(600))

model = Sequential()
model.add(Merge([left, right],mode='sum'))
model.add(Lambda(f, output_shape=(70,600))
model.add(Flatten())
model.add(Dense(4))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy',optimizer='rmsprop')
model.fit([X_left, X_right], Y_train, nb_epoch=100,validation_split=0.2,show_accuracy=True)
```

So it would be possible to cut the sequences that we want to be fed to the last layer.
I don't have a reference in mind for this type of sequence masking though.

**Comment by resplendentfrever** [comment]
Thanks a lot for helping me out. I am really new to Keras. I wanted to implement the architecture of this paper
[1512.01100.pdf](https://github.com/fchollet/keras/files/159672/1512.01100.pdf)
I want to use the ht created by the 2 lstm and merge them to predict the polarity of a word. 
I should really read the keras documentation properly. 
Thanks a lot :)

**Comment by anantvir** [comment]
![image](https://user-images.githubusercontent.com/27782859/80047391-4e06e380-84db-11ea-8bcd-e7c0759a08a4.png)
This is the architecture I want to implement. Can someone please help me understand how to do it in Keras ?
I specifically do not understand how to implement the M matrix which should be a learnable matrix where M belongs to R --> d*d, and C = d-dimensional and R = d-dimensional
