### ISSUE TITLE
Convolution2D: Wrong number of dimensions

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#1894]
Hi,
I am learning how to use Keras, and I am interested by the CNN.
I wanted to run this little code:
`model = Sequential()`
`model.add(Convolution2D(nb_filter=16, nb_row=7, nb_col=7, border_mode='valid', input_shape=(1, 31, 31), activation='tang'))`
`model.add(Convolution2D(32, 3, 3, border_mode='valid', activation='tanh'))`
`model.add(Convolution2D(64, 3, 3, border_mode='valid', activation='tanh'))`
`model.add(Flatten())
model.add(Dense(23, activation='tanh'))`
`model.add(Dense(11, activation='sigmoid'))`
`model.add(Dense(1, activation='sigmoid'))`
`optimizer = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)`
`model.compile(loss='binary_crossentropy', optimizer=optimizer)`
`model.fit(dataset, labels, batch_size=32, nb_epoch=10, shuffle=True, validation_split=0.1, verbose=1)`

And here are my inputs and labels:
`dataset = np.ndarray(shape=(nbimages, image_size, image_size), dtype=np.float32)`
`labels = np.ndarray(shape=(nbimages, 1), dtype=np.float32)`

But it seems that I don't put the good dimensions because I get the following error:

> Epoch 1/10
Traceback (most recent call last):
  File "Convolutional.py", line 129, in <module>
    model.fit(dataset, labels, batch_size=batch_size, nb_epoch=10, shuffle=True, validation_split=0.1, verbose=1)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/models.py", line 646, in fit
    shuffle=shuffle, metrics=metrics)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/models.py", line 280, in _fit
    outs = f(ins_batch)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 384, in __call__
    return self.function(*inputs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/function_module.py", line 786, in __call__
    allow_downcast=s.allow_downcast)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/tensor/type.py", line 177, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/theano_backend.py:380"  at index 0(0-based)', 'Wrong number of dimensions: expected 4, got 3 with shape (32, 31, 31).')

So "expected 4, got 3". But if I add the batch size into my first layer "input_shape=(32, 1, 31, 31)", then I got this other error:

> Invalid input shape - Layer expects input ndim=4, was provided with input shape (None, 32, 1, 31, 31)

I looked to a lot of Keras Convolution2D examples, and I didn't get why my code does not compile.
Could you please help me?

**Comment by tboquet** [comment]
What's the shape of your input? It seems you have only one channel and you miss a dimension.

**Comment by keunwoochoi** [comment]
> dataset = np.ndarray(shape=(nbimages, image_size, image_size), dtype=np.float32)

The shape should be (nbimages, num_channels, height, width), so they should be expanded to 4D array.

**Comment by fchollet** [comment]
Right, 1-channel images should still have shape `(batch_size, 1, width, height)`.

**Comment by FiReTiTi** [comment]
Thanks, I am going to test it right away!

**Comment by zhouxibnu** [comment]
Hi！
I met a similar situations. The error is (Exception: The shape of the input to "Flatten" is not fully defined (got (32, 0, 0). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.)  

My data is a 12900 X 256 ndarray and I really don't know how to set the parameters of input_shape() in the function  Convolution2D(). To solve the problems, do I need to  reshape my input data or set the parameters of input_shape()?  How do I do that? Thanks very much.

**Comment by totuta** [comment]
@FiReTiTi 

Did you solve the problem? I'm having the same issue with yours.

**Comment by FiReTiTi** [comment]
Yes, the input must be (batch_size, 1, width, height), with 1 being the number of channels into the images.

**Comment by Devesh16** [comment]
I am getting an error showing "'Convolution2D' is not defined". while using IPython notebook
Any solution?

**Comment by Danielhiversen** [comment]
@Devesh16 
Have you imported the Convoulution2D ?
`from keras.layers.convolutional import Convolution2D`
