### ISSUE TITLE
Using an embedded layer with stateful LSTM

### ISSUE THREAD

**Issue by viksit** [fchollet/keras#1897]
I haven't been able to solve a similar problem to #1739. I'm trying to feed an embedding layer into a stateful LSTM, but I end up running into an error like the following,

```
# input shape: (291, 200, 64)
```

Model:
```
model = Sequential()
model.add(Embedding(max_features,
                            embedding_size, # output dim
                            batch_input_shape =(batch_size, maxlen, 64), # 25, 200, 64
                            input_length=maxlen)) # sequence length
model.add(LSTM(50,
                       return_sequences=True,
                       stateful=True))
model.add(LSTM(50,
                       return_sequences=False,
                       stateful=True))
model.add(Dense(1))
model.compile(loss='mse', optimizer='rmsprop')
```

Error:
```
Exception: Invalid input shape - Layer expects input ndim=2, was provided with input shape (25, 200, 64)
```

@fchollet - In your previous comment on the other issue, you suggested putting in the batch_input_shape into the first layer. Is this how you were suggesting?

Thanks.

**Comment by fchollet** [comment]
You seem to misunderstand the purpose of an Embedding layer. If your data
already consists of 64-dimensional vectors, then you can simply *not*
include the Embedding layer, and feed your data directly in a LSTM.

The Embedding layer expects 2D integer data (where each integer encodes a
word), and you are passing 3D data, which is what Keras is complaining
about.

**Comment by viksit** [comment]
Uh oh. Sorry - my bad. I actually ended up pasting/using some wrong values in the input dimension and forgot about the fact that I'd already converted my 2d data into a 3d tensor via manually using word vectors from a pre-trained model.. and forgot to remove the embedding layer.
