### ISSUE TITLE
AssertionError: Keyword argument not understood: dropout?

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#1898]
```
model = Sequential()
model.add(Embedding(max_features, 128, input_length=maxlen, dropout=0.5))
model.add(LSTM(128, dropout_W=0.5, dropout_U=0.1))  # try using a GRU instead, for fun
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              class_mode="binary")
```

**Comment by Imorton-zd** [comment]
AssertionError: Keyword argument not understood: dropout_U

**Comment by pasky** [comment]
Have you looked at the new issue checklist? Are you using keras from git?

**Comment by fchollet** [comment]
To post this message, you had to deleted the following message:

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

**Comment by philipperemy** [comment]
Just for info, it worked with me

```
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
```
