### ISSUE TITLE
Realtime prediction and training

### ISSUE THREAD

**Issue by jpeg729** [fchollet/keras#1901]
I am looking into using a Keras built LSTM network on a timeseries prediction problem, and I would love to be able to code it and simply set it going, training itself while providing predictions. However, one difficulty is that the predictions are not immediate, in other words, new data keeps coming in, modifying the internal state of the LSTM nodes... Here is a rough outline of what I think is needed.

1. I think I would need to save the internal state at each step, so that when a prediction's results come in, I could re-apply the internal state before calculating the weight adjustments. Then I would have to re-apply the latest state before accepting more input data. Execution speed is not a big concern.
    I had a look at the implementation of reset_states() and at first glance I could use K.get_value() instead of K.set_value() to save state. Which doesn't seem too difficult.

2. I would need to find and adapt the training code, so that I could run it on demand given a single prediction.

3. I would need to filter out gaps in the data in order to avoid training the network on bad data, but I would have to do that on datasets for batch training too.

All that doesn't seem too difficult, or am I crazy?

N.B. I do understand there are other ways of training a network, but I can get a larger breadth of input data in real time than I can for batch training. I know the training will be slower, but I do want it to fit the breadth of data I will be using it on afterwards. That is why I want to train it in real time.

**Comment by fchollet** [comment]
What I would be would be much simpler and less error prone: Have one model for prediction and one model for continuous training. Occasionally transfer the weights for the training model to the prediction model. If the changes in the weights are small enough, you wouldn't even need to reset the states of the prediction model when doing so (assuming that you are using a stateful model).

**Comment by jpeg729** [comment]
That is a good idea. 
The training model would have to lag behind the prediction model so that it could be fed the data only when the prediction results came in.

I'll work on that first, then if the prediction success rate of the prediction model diverges too much, I'll see if I can implement save_states() and load_states() functions.

**Comment by nextdawn** [comment]
@jpeg729 
I met the same problem as you mentioned.
I wonder how you resolved this issue finally. Have you ever implemented save_states() and load_states() functions?

Thanks a lot.

**Comment by jpeg729** [comment]
In the end, I collected training data and used a more traditional approach. However...

@NasenSpray provided code for `get_states()` and `set_states()` functions in issue #2064. I haven't tested it recently, but it is probable that the internal API hasn't changed since this code was proposed. I quote it here...

```python
import keras.backend as K

def get_states(model):
    return [K.get_value(s) for s,_ in model.state_updates]

def set_states(model, states):
    for (d,_), s in zip(model.state_updates, states):
        K.set_value(d, s)
```
