### ISSUE TITLE
LSTM - Training a sequence, testing by point for Time Series data

### ISSUE THREAD

**Issue by ashwin123** [fchollet/keras#1905]
I'm using LSTM to predict value at next time step.

I have January's time series data where values are recorded every 15mins. 
Now I want to test this model real-time every 15mins in February.

Note: At any point during testing [February] I would not have a sequence as it is real time and the future values are not known yet.
```
train_X = [ [4], [5], [6.3], ...., [4.5] ]  #JANUARY's DATA
train_y = [ [5], [6.3] , .., [4.5], [5] ] 

test_X1 = [ [5.3] ] #FEBRUARY 1st @ 00:00 AM
predicted_y1 = model.predict(test_X1)

# Following data appears only after 15 mins in real-time

test_X2 = [ [5.6] ] #FEBRUARY 1st @ 00:15 AM
predicted_y2 = model.predict(test_X2)
``` 

Basically problem is

```
model.predict(test_X)
```
fails because test_X and train_X have different dimensions.

The goal is to make ``` predicted_y1 ``` as close to ``` test_X2 ``` as possible.

**Comment by fchollet** [comment]
You should train by using as target the next timestep in the training
sequence (same setup as testing, and therefore same data shape). Anything
else wouldn't be solving your problem.

Maybe check out the lstm_text_generation.py example in Keras, since that is
what it does.

**Comment by ashwin123** [comment]
Thanks for clearing that.
So as per our requirement, we need to train the model point by point as well. 

I/P Data format is
```
                X attributes                                         Y attribute
--------------------------------------------------------------------------------------
         timestamp              | value                               value                                                                         
Monday 3rd Jan 9:15pm           | 4.4                                 5.2
Monday 3rd Jan 9:30pm           | 5.2                                 6.5
```
So if we are to train point by point, 2 concerns we have are : 

1. Will the LSTM learn the time factor inherent in the data?
2. Is there a need to encode the date and time as an attribute in our training input?
That is,
```
train_X = [ [day_of_week,time,value],[day_of_week,time,value],....]
```
and train the above with ``` batch_size = 1 ``` ?
