### ISSUE TITLE
pad_sentences

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [fchollet/keras#1907]
Hi,
I'm wondering where i can find an explanation of why we need to apply pad_sentences to text for the embedding layer and why the 2D transformation ? Thanks!

**Comment by fchollet** [comment]
The input to an Embedding layer is a 2D tensor of integers. The first dimension is the batch size, the second dimension is the sequence length. So that's why all your sequences have to have the same size, and the simplest way to achieve same-length sequences is to pad the shorter ones with zeros.

**Comment by jesuisnicolasdavid** [comment]
Thanks for this straightforward explanation !
