### ISSUE TITLE
predict(one sentence)

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [fchollet/keras#1909]
Hi, is there a way to test the binary classification prediction of only one sentence (handmade) after the training of a model ? Thanks!

**Comment by pasky** [comment]
You can call model.predict() to get NN prediction on new unseen samples.

**Comment by jesuisnicolasdavid** [comment]
Thanks for your answer, i suppose that the data we feed to model.predict() has to be processed by the same pipeline as our training dataset, right ?

**Comment by pasky** [comment]
That's right.

**Comment by philipperemy** [comment]
@jesuisnicolasdavid close the issue if it works for you.
