### ISSUE TITLE
Explanation about Sequential and Graph Model

### ISSUE THREAD

**Issue by abdulqayyum** [fchollet/keras#1913]
[Please](http://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Byeon_Scene_Labeling_With_2015_CVPR_paper.pdf) make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by abdulqayyum** [comment]
Hi I am new to LSTM and coming from Matlab. I want to ask (may seem weird) that suppose I want to implement a Model. Keras provide: Sequential and Graph. Can someone give examples (Graphical one) to differentiate these models. I want to implement a model in this paper. Which one method is best At this time I am trying Graph because using Sequential I was unable to Merge outputs from 4 LSTM in previous layer to Hi I am new to LSTM and coming from Matlab. I want to ask (may seem weird) that suppose I want to implement a Model. Keras provide: Sequential and Graph. Can someone give examples (Graphical one) to differentiate these models. I want to implement a model in [this paper](http://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Byeon_Scene_Labeling_With_2015_CVPR_paper.pdf). Which one method is best At this time I am trying Graph because using Sequential I was unable to Merge outputs from 4 LSTM in previous layer.

**Comment by Sandy4321** [comment]
GOOD question thank you
lets see answers

**Comment by ymcui** [comment]
If your model should have multiple outputs or the architecture is sophisticated, then you should use `Graph` model. Or the `Sequential` model is good for setup a pipeline-like architecture.
Here is the explanation in Keras documentation.

> Keras has two models: Sequential, a linear stack of layers, and Graph, a directed acyclic graph of layers.

If you want to combine 4 LSTM output, just create a `Merge` layer, just like
'''
model = Sequential()
model.add(Merge([lstm1,lstm2,lstm3,lstm4], merge_mode='concat'))
'''

**Comment by abdulqayyum** [comment]
I don't know what do you mean by sophisticated here. My original code is in my own system at home.But a few Lines from model I remember are given as:
`model=Graph()`
Don't know if my input is prepared as paper asks for:
`model.add_input('input',input_shape=(3.))`
Here I made 4 LSTM and post my input:
`model.add_node(LSTM(input_shape,activation='tanh'),name='lh1',input='input')`
`model.add_node(LSTM(input_shape,activation='tanh'),name='lh2',input='input')`
`model.add_node(LSTM(input_shape,activation='tanh'),name='lh3',input='input')`
`model.add_node(LSTM(input_shape,activation='tanh'),name='lh4',input='input')`
Here I got my error may be due to `mode ='sum'` 
`model.add_node(keras.layers.core.Merge([lh1,lh2,lh3,lh4],mode='sum'))`
A simplistic picture of what I want to implement or you can see [this paper](http://www.cv-foundation.org/openaccess/content_cvpr_2015/papers/Byeon_Scene_Labeling_With_2015_CVPR_paper.pdf)
![scene labeling](https://cloud.githubusercontent.com/assets/6094454/13633307/039d5cd4-e610-11e5-8891-bb6e7bbfa30e.png)

**Comment by abdulqayyum** [comment]
Oh, why am I adding activation in each layer by the way ?!

**Comment by keunwoochoi** [comment]
`Sequential()` only stacks layers upon previous ones sequentially like a stack or queue, while with `Graph()` you can add any node to the space and connect them as you want. At the beginning you asked about the difference between them but seems like you already understood - you need to use `Graph` for the illustrated model.

If that's the exact code you used, `keras.layers.core.Merge([lh1,lh2,lh3,lh4],mode='sum')` seems okay but there's `name` and `input` missing in the `model.add_node()` (but I guess you just omitted them here..). Otherwise posting error message would help understand what's the problem. With `sum` probably there's an issue on the shapes of the outputs of layers?

**Comment by abdulqayyum** [comment]
@keunwoochoi to some extent yes, in fact it was what I understood by reading but I was not sure about this. Moreover, If you have seen the paper I referred you will understand the real issue, can you please give some suggestion regarding implementation of architecture in paper? Thanks for help
