### ISSUE TITLE
Model performance significantly worse after loading blank weights

### ISSUE THREAD

**Issue by KeironO** [fchollet/keras#1914]
Whenever I want to do k-fold CV, I save a newly created model and then load it in.

However, I'm finding that this is resulting in significantly worse results.

**Comment by cmyr** [comment]
@KeironO Can you clarify? What are these results worse then?

**Comment by fchollet** [comment]
If you can post a code snippet to reproduce your results (something I can
just copy and paste and run) then I will look at it.
