### ISSUE TITLE
Error when using target of shape (n_batch, timesteps, n_features) in train_on_batch for RNN

### ISSUE THREAD

**Issue by afruizc** [fchollet/keras#1928]
I have posted this in the google groups forum but it does not seem to have any visibility:

https://groups.google.com/forum/#!topic/keras-users/L1e7QVLI3nY

if anyone could help me out, I'd greatly appreciate it. Thank you!

**Comment by cmyr** [comment]
@afruizc  can you convert your batch to a numpy array before calling train on batch, to verify it's shape? it looks like you're passing a list of lists, and they have different dimensions.

**Comment by afruizc** [comment]
Well, this is a little embarrassing. I implemented the change you suggested to check the dimensions and the code magically works now. Thank you for your help.
