### ISSUE TITLE
Cannot pass index array to categorical_crossentropy objective

### ISSUE THREAD

**Issue by wxs** [fchollet/keras#193]
Keras uses Theano's `T.nnet categorical_crossentropy` function behind the scenes when you use the `categorical_crossentropy` objective in your model. From the [Theano docs](http://deeplearning.net/software/theano/library/tensor/nnet/nnet.html#tensor.nnet.categorical_crossentropy): 

> true_dist - symbolic 2D Tensor OR symbolic vector of ints. In the case of an integer vector argument, each element represents the position of the ‘1’ in a 1-of-N encoding (aka “one-hot” encoding)

Unfortunately if I pass in an integer vector as the true labels to the `fit()` method of my model I get an error at this line:

```
loss = self._train(*ins)
```

which says

> ValueError: GpuElemwise. Input dimension mis-match. Input 3 (indices start at 0) has shape[1] == 1, but the output's size on that axis is 800.

I'm not sure I understand Keras' architecture enough to understand what the issue is here, since it appears that `self._train` here is directly wrapping `categorical_crossentropy` which should be able to handle the dimension mis-match.

Any ideas how to resolve this?

**Comment by fchollet** [comment]
I will look into it. 

For now, it would be easy for you to convert your integer array to a binary categorical matrix: 
```python
from keras.utils import np_utils
Y_train = np_utils.to_categorical(y_train, nb_classes)
```

**Comment by wxs** [comment]
Thanks! Yeah I've been resolving the issue that way for now, but it limits how large a dataset I can have in-memory, because it appears that I can't pass in a sparse matrix, either.

**Comment by stephenroller** [comment]
I think this is because Sequential and Graph obtain use get_output() of the last layer to get the shape/type of the variable. If I understand correctly, Theano picks which variation of categorical_crossentropy you're using at compile time based on the predeclared shapes.

This could be alleviated by having an option which lets you explicitly declare the shape/type of Sequential.y, but it would be messier for Graph.

**Comment by NewbieAlex** [comment]
test
