### ISSUE TITLE
Bug in ImageDataGenerator Whitening procedure?

### ISSUE THREAD

**Issue by parag2489** [fchollet/keras#1931]
I was looking at the source code of the whitening procedure. I found that the data is never mean centered before doing the whitening. Specifically, if we keep all the other options as False and just keep the image whitening to be true, then covariance matrix is computed without mean centering the data! Thus `XX^T` will no longer be the covariance matrix of the data if `mean(X) ~= 0`.

If everyone agrees with me on this, I can submit a pull request to correct this issue.

**Comment by fchollet** [comment]
You can submit a PR.
