### ISSUE TITLE
Deconvolution for text-classification

### ISSUE THREAD

**Issue by shyamupa** [fchollet/keras#1932]
I am trying to visualize the activations of my convnet text classifier. I want to put back the max values back to their original location so that I can find which word(s) in the text triggered the activation. Can I do this with the layers provided with keras??

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by mutex9** [comment]
There's no deconv layer in keras, you would have to make one, or perhaps use a lambda layer. Deconv is just backpropagation pass, it's possible in theano. Maybe this code will help you.   

`def deconv(X, w, subsample=(1, 1), border_mode=(0, 0), conv_mode='conv'):
    img_shp = [X.shape[2]*subsample[0], X.shape[3]*subsample[1]]
    return _conv2d_grad_wrt_inputs(X, w, input_shape=img_shp,
                           border_mode=border_mode,
                           subsample=subsample,
                           filter_flip=True if conv_mode=='conv' else False)

from theano.tensor.nnet.abstract_conv import AbstractConv2d_gradInputs
def _conv2d_grad_wrt_inputs(output_grad,
                           filters,
                           output_grad_shape=None,
                           input_shape=None,
                           filter_shape=None,
                           border_mode='valid',
                           subsample=(1, 1),
                           filter_flip=True):
    grad_input_op = AbstractConv2d_gradInputs(imshp=None, # issue #4048
                                              kshp=filter_shape,
                                              border_mode=border_mode,
                                              subsample=subsample,
                                              filter_flip=filter_flip)

    return grad_input_op(filters, output_grad, input_shape)`

X - what you want to deconvolve, w - convolution filters. See documentation for conv2d_grad_wrt_inputs in theano/tensor/nnet/abstract_conv.py for more info

**Comment by transcranial** [comment]
In tensorflow, deconv2d was renamed to conv2d_transpose. Note:
```
This operation is sometimes called "deconvolution" after (Deconvolutional
  Networks)[http://www.matthewzeiler.com/pubs/cvpr2010/cvpr2010.pdf], but is
  actually the transpose (gradient) of `conv2d` rather than an actual
  deconvolution.
```
