### ISSUE TITLE
How to get the features of the last Dense of my CNN network

### ISSUE THREAD

**Issue by gklee2014** [fchollet/keras#1937]
Now, I have build my CNN network with Keras, my backend is tensorflow, and I want to get the features of the last dense of my CNN model for SVM.
Does Keras has functions to solve this problem? How?

**Comment by santi-pdp** [comment]
I think your question is: "How can I visualize the output of an intermediate layer?", in this case your Dense layer. This is specified in the FAQ, "You can build a Keras function that will return the output of a certain layer given a certain input":
`from keras import backend as K`
`get_3rd_layer_output = K.function([model.layers[0].input], [model.layers[3].get_output(train=False)])`
`layer_output = get_3rd_layer_output([X])[0]`

**Comment by myk1603** [comment]
@gklee2014  could you please tell how can i use CNN with SVM
