### ISSUE TITLE
problem when using stateful LSTM

### ISSUE THREAD

**Issue by talentlei** [fchollet/keras#1938]
Hello @fchollet @farizrahman4u ,

I'm having troubles using a stateful LSTM . 

`        model = Sequential()  

model.add(LSTM(output_dim=64,input_length=self.seq_len,input_dim=self.embed_length,return_sequences=True,stateful=False ))

```
    model.add(Dropout(0.2))
    model.add(TimeDistributedDense(output_dim=self.labs_len))
    model.add(Activation('softmax'))`
```

 this code works fine. 
but when I  use stateful = true, modify

`model.add(LSTM(output_dim=64,input_length=self.seq_len,input_dim=self.embed_length,return_sequences=True,stateful=False ))`

to

`model.add(LSTM(output_dim=64,input_length=self.seq_len,input_dim=self.embed_length,return_sequences=True,stateful=True,batch_input_shape=(batch_size,tstep,self.embed_length) ))`

It doesn't work.  How can I use the stateful ? Thanks !

**Comment by santi-pdp** [comment]
What's the error message? Does it train almost for a full epoch? Because it can be caused for having different batch sizes during training (i.e. the last batch is smaller than the other ones as full_dataset_length % batch_size != 0). Remember that all batches must have the same size as stated in the FAQ: "all batches have the same number of samples"

**Comment by talentlei** [comment]
@santi-pdp ,  Yes, the last batch have the same size with others.

the error message as follow:

```
ValueError: Shape mismatch: x has 16 rows but z has 192 rows
Apply node that caused the error: Gemm{no_inplace}(Subtensor{::, int64::}.0, TensorConstant{0.20000000298}, <TensorType(float32, matrix)>, lstm_U_o_copy, TensorConstant{0.20000000298})
Toposort index: 5
Inputs types: [TensorType(float32, matrix), TensorType(float32, scalar), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, scalar)]
Inputs shapes: [(192, 64), (), (16, 64), (64, 64), ()]
Inputs strides: [(1024, 4), (), (256, 4), (256, 4), ()]
Inputs values: ['not shown', array(0.20000000298023224, dtype=float32), 'not shown', 'not shown', array(0.20000000298023224, dtype=float32)]
Outputs clients: [[Elemwise{Composite{(clip((i0 + i1), i2, i3) * tanh(i4))}}(TensorConstant{(1, 1) of 0.5}, Gemm{no_inplace}.0, TensorConstant{(1, 1) of 0}, TensorConstant{(1, 1) of 1}, Elemwise{Composite{((clip((i0 + i1), i2, i3) * i4) + (clip((i5 + i6), i2, i3) * tanh(i7)))}}.0)]]


```

**Comment by philipperemy** [comment]
Please give full script if possible

**Comment by philipperemy** [comment]
Have a look at that if it's still not resolved : http://philipperemy.github.io/keras-stateful-lstm/

**Comment by farizrahman4u** [comment]
Dont provide the ìnput_length` argument when you have already specified `batch_input_shape`.
