### ISSUE TITLE
Reproducibility with ImageDataGenerator

### ISSUE THREAD

**Issue by cadurosar** [fchollet/keras#1940]
Hello, I was experimenting with Keras and noticed that I could not reproduce the same results even when  I defined a np.seed(). Looking at the code it uses python random instead of numpy random. Shouldn't it be using numpy random?

If it should be using numpy random I have made that modification locally and can submit a pull request to correct this issue.

**Comment by nouiz** [comment]
I would recommand to use an instance of numpy random generator. This way,
change inside keras won't affect random numbers in user code. This caused
difficulties to Theano user.

**Comment by hlin117** [comment]
Yes, it should use `np.random.seed`.

**Comment by cadurosar** [comment]
`from __future__ import absolute_import

import numpy as np
import re
from scipy import ndimage
from scipy import linalg

from os import listdir
from os.path import isfile, join
import random
import math
from six.moves import range
import threading

'''Fairly basic set of tools for realtime data augmentation on image data.
Can easily be extended to include new transformations, new preprocessing methods, etc...
'''


def random_rotation(x, rg, fill_mode="nearest", cval=0.):
    angle = random.uniform(-rg, rg)
    x = ndimage.interpolation.rotate(x, angle,
                                     axes=(1, 2),
                                     reshape=False,
                                     mode=fill_mode,
                                     cval=cval)
    return x
`

Adding an extract from the code that shows that it uses python random instead of numpy.random

**Comment by cadurosar** [comment]
Resolved with #1968
