### ISSUE TITLE
can keras put two bidirectional_RNN vectors in corresponding position？

### ISSUE THREAD

**Issue by liyi193328** [fchollet/keras#1941]
In https://github.com/fchollet/keras/blob/master/examples/imdb_bidirectional_lstm.py 's bidirectional_RNN, it achieve to concate two represtion vectors(using LSTM) to classify.
But the most import thing is : 
#### the two vector in same index(order) is two different representions of one  word, they should merge together to do something wonderful ,like the picture below:

![image](https://cloud.githubusercontent.com/assets/6782974/13673244/2b94953c-e713-11e5-9faf-b89d04b2c664.png)![image](https://cloud.githubusercontent.com/assets/6782974/13673281/4b594de0-e713-11e5-8d3f-ede045d3d73b.png)
How to achieve these models? need to custom bidirectional_RNN ?

**Comment by ymcui** [comment]
I'm not sure about this, the older version works well.
but in the latest version of Keras, if you set `go_backwards=True`, the model return the hidden states in backward directions, which cannot be concatenated correctly with forward_RNN.

try this,
rnn() in theano_backend.py, fix the following codes before `return`
```
axes = [1, 0] + list(range(2, outputs.ndim))
if return_sequences and go_backwards:
    output = output[::-1]
outputs = outputs.dimshuffle(axes)
states = [T.squeeze(state[-1]) for state in states]
return last_output, outputs, states
```
