### ISSUE TITLE
Convert 2d 3d output shape

### ISSUE THREAD

**Issue by freeze5272** [fchollet/keras#1942]
Hi, 

I was wondering if there is a way to convert 3d output shape (nb_samples, timesteps, output_dim) to 2d (nb_samples, output_dim) or the other way around for the result after LSTM layer? Or maybe feed LSTM layer with 2d shape data instead?

**Comment by philipperemy** [comment]
I think you're looking for the TimeDistributedMerge layer.

https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L653

http://keras.io/layers/core/

```
Input shape

3D tensor with shape: (samples, steps, features).

Output shape

2D tensor with shape: (samples, features).
```
