### ISSUE TITLE
Tensorboard callback gives error on Test data shape when using stateful LSTM  

### ISSUE THREAD

**Issue by marcdumon** [fchollet/keras#1944]
Hello, 
The TensorBoard calback does't seem to work with stateful LSTM.
Here's my model:
`model = Sequential()`
`model.add(LSTM(7, return_sequences = True,  stateful=True,  batch_input_shape=(10, 10, 24), input_shape=(10, 24)))`
....
`tb = TensorBoard(log_dir='./logs', histogram_freq=1)`
`model.fit(X_train, y_train, batch_size=10, nb_epoch=nb_epoch, validation_data=(X_test, y_test), show_accuracy=True, callbacks=[tb])`

When I train it, I get following error: 
> ValueError: Cannot feed value of shape (300, 10, 24) for Tensor u'Placeholder_1:0', which has shape '(10, 10, 24)
BTW: (300, 10, 24) is the shape of the Test data.

When I remove the callback from model.fit() it doesn't give the error.

Is this a bug or am I overlooking something?

**Comment by fchollet** [comment]
For the time being you can just set `histogram_freq` to 0 (or None).

**Comment by marcdumon** [comment]
@fchollet: Thanks..... I'll do that till it's fixed.
BTW: I really enjoy how easy I can experiment with ML thanks to Keras. Great job!
