### ISSUE TITLE
Can I concatenate feature maps from two layers?

### ISSUE THREAD

**Issue by sunshineatnoon** [fchollet/keras#1945]
I want to concatenate feature maps from lower layers and upper layers, and then input the concatenated feature map to the fully connected layer. The feature map of lower layers and upper layers will in different shapes, so should I use a pooling layer or just flatten them in order to concatenate them? How to do this in Keras? THX!

**Comment by fchollet** [comment]
Yes. Use a `Merge` layer with `mode='concat'`. Specify the right concatenation axis.

**Comment by rmanak** [comment]
The Merge layer does not exist anymore in keras 2? I am using `concatenate` function API to Concatenate and getting an error message: AttributeError: 'Sequential' object has no attribute 'get_shape'

**Comment by RaskaFR** [comment]
Hello ! I got the same error. The answer to this question could interest me too ! Thank you.

**Comment by seinberg** [comment]
I too get this error.

**Comment by sreevasu** [comment]
Hi, i am also facing same problem. Please any one can help me.
