### ISSUE TITLE
More documentation for keras.layers.embeddings.Embedding

### ISSUE THREAD

**Issue by hlin117** [fchollet/keras#1946]
I'm been trying to understand how to use the `keras.layers.embeddings.Embedding` class for a while for a word2vec application I have. 

I have code similar to the small script below, but I'm not sure why it's not working. It would be nice to provide more documentation with how to use the `Embedding` layer.

```
>>> import keras
>>> from keras.models import Sequential
>>> from keras.layers.embeddings import Embedding
>>> import numpy as np
>>> 
>>> model = Sequential()
>>> model.add(Embedding(4, 7, input_length=10))
>>> model.compile(loss='categorical_crossentropy', optimizer='adam')
>>> 
>>> np.random.randint(0, 4, size=10)
>>> X = np.random.randint(0, 4, size=(3, 10))
>>> y = [-1, 1, -1]
>>> model.fit(X, y)
```

`TypeError: ('Bad input argument to theano function with name "/Users/hlin117/ajmori2/venv/lib/python2.7/site-packages/keras/backend/theano_backend.py:446"  at index 1(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (3, 1).')`

The error message isn't very helpful either. I performed `X.reshape(3, 10, 1)`, and got a different error message.

```
>>> model.fit(X.reshape(3, 10, 1), y)
```

`TypeError: ('Bad input argument to theano function with name "/Users/hlin117/ajmori2/venv/lib/python2.7/site-packages/keras/backend/theano_backend.py:446"  at index 0(0-based)', 'Wrong number of dimensions: expected 2, got 3 with shape (3, 10, 1).')`

**Comment by FighterLYL** [comment]
For this `model`, the expected input dimension is 2 while the expected `y`'s dimension is 3, the `Embedding` layer's output, i.e. the `model`'s output, shape is `(3, 10, 7)`

**Comment by naisanza** [comment]
How do you determine the output_dim of an Embedding layer?

In https://www.youtube.com/watch?v=YimQOpSRULY it just shows output_dim=64, but doesn't explain why
