### ISSUE TITLE
RELU outputs NEGATIVE numbers !!!!!!!

### ISSUE THREAD

**Issue by tanxchong** [fchollet/keras#1948]
I tried the example in the file "neural_style_transfer.py". I want to see the outputs features of relu units for a single image in VGG network. I do not want to trouble to modify the code so I simply duplicated the same image for three times and inputs them together to the net (using K.function to extract three outputs). But the output has negative numbers. 

However, when I tried to extract the output of only one image (still kept three image as inputs, but using three K.fucntion() to extract their outputs seperately) the problem is gone.

Even for the positive values, joint outputs are still different from individual outputs.

This is weird, I worry if it may cause serious problem. See below for the code segments (I do not modify other codes)
![2016-03-11 11 00 27 pm](https://cloud.githubusercontent.com/assets/13939832/13708151/05f39c94-e7e8-11e5-9915-b5421acdef20.png)

**Comment by hlin117** [comment]
That's indeed strange. Can you provide a sample toy dataset by `np.random.rand`? It would be nice to replicate this bug.

**Comment by tanxchong** [comment]
the replication is easy. 
1. copy the code segment(start from "test_img = ..." end with "min_2=...") into the neural style transfer py file and put at the corresponding place. 
2. replace the path of an image as inputs of preprocess_img function (using color image)
3. debug the py file with args_1 and args_2 being the same as the path in step 2 (for example, assume the path in step 2 is "PATH", then excute "neural_style_transfer.py PATH PATH output_img")

**Comment by tanxchong** [comment]
forgot to mention, u have to download the VGG net weights and put its path in the py file as well. just follow the instruction in neural_style_transfer.py to do this.

**Comment by fchollet** [comment]
Too many `!`s in the title (I count seven), closing.

**Comment by hlin117** [comment]
@tanxchong: Generally, package owners do not have enough time to address every issue for such a large open source project, and neither do package contributors. 

It would be more convenient if, next time, you help contributors and package owners replicate your bugs, so we could diagnose what is happening faster. Perhaps posting a short demo script with `np.random.rand` inputs can help us find your problem.
