### ISSUE TITLE
samplewise normalization should be done before featurewise and ZCA

### ISSUE THREAD

**Issue by eyaler** [fchollet/keras#1949]
in convnet literature global contrast normalization (=samplewise) is done before feature normalization and ZCA. In ImageDataGenerator samplewise is currently the last action. should be moved to the beginning of standartize() and added after the augment part in fit()

**Comment by fchollet** [comment]
You are right. This is now fixed.

**Comment by Liyang90** [comment]
It seems the fit() method hasn't been changed yet?
