### ISSUE TITLE
Sequence of floats as an input to LSTM

### ISSUE THREAD

**Issue by rrahmati** [fchollet/keras#195]
I have a 2D array of floats which I want to give as an input to the LSTM. I can give it to a Dense layer but LSTM needs a 3D input. The example uses Embedding which accepts integers as inputs but I need to pass floats to it. Can you guys give me an example of how to do this?

**Comment by fchollet** [comment]
What are the dimensions of your current input, `(samples, time)`? In that case you could reshape it to `(samples, time, 1)` and you'd be done.

**Comment by rrahmati** [comment]
The current input is a 2D array of the form (nb_samples, input_dim). Is there any ways to reshape it to (nb_samples, timesteps, input_dim)?

**Comment by fchollet** [comment]
So where's time in your problem? You're talking about 'sequences', which implies a time axis.

**Comment by rrahmati** [comment]
I have a sequence of positions and orientations of an object changing by time. So, the first index of the array shows the time and the second shows the position and orientation which are 7 float numbers in total.

**Comment by fchollet** [comment]
So time is your first dimension (samples). You can cut your array in redundant chunks of N timesteps, to create P samples. 

Like: 
```python
samples = np.array([timesteps[i:i+n] for i in range(nb_timesteps-n)])
```
