### ISSUE TITLE
Warn user when number of y labels doesn't match output shape

### ISSUE THREAD

**Issue by hlin117** [fchollet/keras#1954]
The following code fails for pretty obvious reasons:

```
>>> import numpy as np
>>> from keras.models import Sequential
>>> from keras.layers.core import Dense
>>>
>>> # Very simple architecture
>>> model = Sequential()
>>> model.add(Dense(400, input_dim=400))
>>> model.compile(loss='categorical_crossentropy', optimizer='adam')
>>> 
>>> X = np.random.rand(5, 400)
>>> y = [1, -1, -1, 1, 1]
>>> model.fit(X, y)
```

It leaves the not-so-helpful error message (below). I'm not sure what variety of architectures Keras is expected to support, but it would be nice if a warning was thrown if the problem is a multiclass classification problem, and there is no softmax output layer (or some similar output layer).

---

Output message:

```
ValueError: Input dimension mis-match. (input[0].shape[1] = 400, input[3].shape[1] = 1)
Apply node that caused the error: Elemwise{Composite{((i0 * i1 * i2 * i3 * i4) / (i5 * i6 * i7 * i8 * i8))}}[(0, 4)](Elemwise{Composite{AND(GE(i0, i1), LE(i0, i2))}}.0, InplaceDimShuffle{x,x}.0, InplaceDimShuffle{0,x}.0, <TensorType(float32, matrix)>, Elemwise{Add}[(0, 0)].0, InplaceDimShuffle{x,x}.0, InplaceDimShuffle{x,x}.0, Elemwise{Clip}[(0, 0)].0, InplaceDimShuffle{0,x}.0)
Toposort index: 32
Inputs types: [TensorType(int8, matrix), TensorType(float32, (True, True)), TensorType(float32, col), TensorType(float32, matrix), TensorType(float32, matrix), TensorType(float32, (True, True)), TensorType(float32, (True, True)), TensorType(float32, matrix), TensorType(float32, col)]
Inputs shapes: [(5, 400), (1, 1), (5, 1), (5, 1), (5, 400), (1, 1), (1, 1), (5, 400), (5, 1)]
Inputs strides: [(400, 1), (4, 4), (4, 4), (4, 4), (1600, 4), (4, 4), (4, 4), (1600, 4), (4, 4)]
Inputs values: ['not shown', array([[ 5.]], dtype=float32), array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]], dtype=float32), array([[-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.]], dtype=float32), 'not shown', array([[ 5.]], dtype=float32), array([[ 5.]], dtype=float32), 'not shown', array([[ 15.79184151],
       [ 11.54109573],
       [  4.8348279 ],
       [ 12.4104147 ],
       [  9.79920959]], dtype=float32)]
Outputs clients: [[Sum{axis=[1], acc_dtype=float64}(Elemwise{Composite{((i0 * i1 * i2 * i3 * i4) / (i5 * i6 * i7 * i8 * i8))}}[(0, 4)].0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by NasenSpray** [comment]
> it would be nice if a warning was thrown if the problem is a multiclass classification problem, and there is no softmax output layer (or some similar output layer)

Which would probably annoy people that use Keras for other stuff. It's not easy to distinguish between not-so-obvious user intent and real errors; dealing with such design questions is a balancing act of (IMHO) questionable value.

**Comment by hlin117** [comment]
I agree with that. But if you look at some other libraries like
scikit-learn and pandas, warnings are thrown all the time.

I think it's important that in the common case, warnings should be thrown
before any such incomprehensible errors are raised.

**Comment by fchollet** [comment]
> if you look at some other libraries like scikit-learn and pandas

The degree of freedom you have in Keras (the flexibility of the library) is way above that of sklearn, where the user is confined to well-oiled but inflexible template use cases.

What specific warnings would you suggest, in what specific cases?

**Comment by hlin117** [comment]
> The degree of freedom you have in Keras (the flexibility of the library) is way above that of sklearn, where the user is confined to well-oiled but inflexible template use cases.

Very true. The flexibility of keras is a reason why I praise it. Unfortunately, determining the use-cases of neural networks is difficult, but this is an artifact of working with neural networks in general.

> What specific warnings would you suggest, in what specific cases?

I think a lot of information about the output of neural networks can be derived from the output activation. (Please feel free to correct me for any common cases when this isn't true.) For example,

* Classification: Check if the output layer ends with a sigmoid-like activation. If it does, check if the output `y` are integers. (You could also check if `output_dim >> len(np.unique(y))`.)
* Regression: Check if the output layer ends with a linear-like activation. If it does, check if the output `y` are floats.

My prior experience is from contributing to scikit-learn. One of the package's goal is to lower the barrier of machine learning to newcomers, and part of the way they implement this idea is glittering their internals with `ValueErrors` and warnings if users have strange inputs.

Not sure whether you share similar goals, @fchollet, but raising warnings like these is a great way to start.
