### ISSUE TITLE
Print losses separately for Graph model

### ISSUE THREAD

**Issue by bkj** [fchollet/keras#1957]
Does anyone have an idea how to print all of the losses for a `Graph` model separately?

I.e. for a graph model with

```
model.compile({"first_loss" : "categorical_crossentropy", "second_loss" : "mse"}, optimizer="rmsprop")
```

instead of

```
33019/33019 [==============================] - 64s - loss: 0.3151
```

we would have

```
33019/33019 [==============================] - 64s - first_loss: 0.4151 - second_loss: 0.200
```

**Comment by ymcui** [comment]
Seems not supported yet.
But you can write your own `train_on_batch` to support this feature. It won't be that hard.
