### ISSUE TITLE
about LSTM + BatchNormalization

### ISSUE THREAD

**Issue by XuesongYang** [fchollet/keras#1962]
Hi guys,

I am trying to add BatchNormalization layer on top of the lstm layer. However I am always get the error as follows:

Build graph of the model...
Traceback (most recent call last):
  File "trans_bilstm_asr.py", line 124, in <module>
    model.add_node(BatchNormalization(), name='batch_norm_forward', input='embedding')
  File "keras/layers/containers.py", line 440, in add_node
    layer.set_previous(self.nodes[input])
  File "keras/layers/core.py", line 144, in set_previous
    assert self.supports_masked_input(), 'Cannot connect non-masking layer to layer with masked output.'
AssertionError: Cannot connect non-masking layer to layer with masked output.

the snippet of my code
`
model.add_node(LSTM(output_dim=256), name='forward', input='embedding')
model.add_node(BatchNormalization(), name='batch_norm_forward', input='embedding')`

Thanks.
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by GregorySenay** [comment]
model.add_node(BatchNormalization(), name='batch_norm_forward', input='embedding')
--> 
model.add_node(BatchNormalization(), name='batch_norm_forward', input=**'forward'**)
maybe?

**Comment by braingineer** [comment]
I've just come across this as well. 

@fchollet  --- there's no reason batch normalization can't support masking right by just passing the mask forward?

**Comment by fchollet** [comment]
Yes, that should not be an issue. It's actually just a matter of adding a flag in `__init__`.

**Comment by balsulami** [comment]
I think I have the same problem with Sequential Model. When I add BatchNormalization after Masking+LSTM, I get the error:

`Exception: Layer batchnormalization_1 does not support masking, but was passed an input_mask: Any{2}.0`

Thanks

**Comment by balsulami** [comment]
Hi @fchollet -- I downloaded the latest version and found out that this issue is still not resolved. It's just one small change in the `__init__` as you mentioned. Should I do PR ? is it worth it ? Thanks

**Comment by nmaiorana** [comment]
I'm having the same issue.

**Comment by Dando1996** [comment]
I'm also having this issue.
` model = Sequential( [
            Masking(mask_value=0.0, batch_input_shape=(model_config.batch_size,model_config.TIME_STEPS, model_config.features_num ) ),
            BatchNormalization(),
            LSTM(model_config.num_units, stateful=True, return_sequences=False,
                 recurrent_dropout = model_config.recurrent_dropout,
                 dropout = model_config.dropout) ,
            Dense(model_config.num_output, activation='sigmoid') #fully connected layer with 1 hidden units
    ] )`
