### ISSUE TITLE
new (faster_rnn) computing method is a huge memory hog

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#1964]
Ever since the new outside-of-scan RNN computing, I'm forced to cut batch sizes in half (and thus double computing time) because the representation takes nearly double on the GPU. 
Am I the only one experiencing this problem?
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
Can you provide us with a time/memory benchmark on your GPU? With code.

I am thinking we should make both implementations available and usable via a layer argument (such as `faster=True`).
