### ISSUE TITLE
How can I output valid_accuracy when training a graph model

### ISSUE THREAD

**Issue by LiuAndYang** [fchollet/keras#1966]
I set the show_accuracy = True, but can't set class_mode which leads to the valid_accuracy didn't show when training a graph model. how can i solve this, i am just doing a very common three-way classification. thx~

In the source code, this part matters whether the class_mode can be automatically set.
 # deal with accuracy computation         if len(self.output_order) == 1:

**Comment by ymcui** [comment]
I'm afraid you should write it by your own.
As the `Graph` model may have multiple outputs, current version doesn't support to show accuracy.

**Comment by LiuAndYang** [comment]
Thinks , @ymcui But I am not very familiar with Keras and Theano, It's would be appreciated if you give me some instructions about how to write this part, Thx~~
BTW: Surprised to find that you also graduated from HIT~~~

**Comment by ymcui** [comment]
I saw that, the latest Keras has already support `show_accuracy` feature in `Graph` model.
Check: https://github.com/fchollet/keras/blob/master/keras/models.py#L1317

**Comment by LiuAndYang** [comment]
@ymcui Already fixed that, Thx~

**Comment by ymcui** [comment]
No problem. You can now close your issue. Have fun :)
