### ISSUE TITLE
`model.reset_states()` taking too long with Tensorflow backend

### ISSUE THREAD

**Issue by jfsantos** [fchollet/keras#1970]
I have a model using LSTMs where I implemented backpropagation through time by using stateful LSTM layers and calling `model.reset_states()` every time I finish feeding the model a sequence of batches that corresponds to a whole, larger sequence. Each of my original sequences was 450 timesteps long and I was dividing them into 9 segments with 50 timesteps each, so I was calling `model.reset_states()` after every 9 batches. I noticed a considerable delay when using the Tensorflow backend every time I needed to reset the LSTM inner states (i.e., during training, there was a small delay of approximately 1 second after every time I called `model.reset_states()`, which does not happen with the Theano backend). I guess this is probably related to unrolling vs. scan.

Am I doing something wrong or is this expected?

**Comment by fchollet** [comment]
I don't think unrolling vs. scan should affect how long it takes to reset
the states.

You could get more efficient by replacing the N calls to K.set_value() by a
single multi-tensor assignment call to session.run() in TF-land. But if the
overhead is just 1s I don't think it's worth it.

**Comment by jfsantos** [comment]
Thanks for your reply! What seems strange is that I do not have this issue with Theano. I am training on a very large dataset (> 100 GB of data) and an entire epoch is taking ~6000 seconds on Theano and ~16000 seconds on Tensorflow, and a good part of the difference is due to these delays. 

For now switching to Theano is an option, so I just did that. Since this is currently only an issue in my implementation (as Keras does not support BPTT), should I close the issue or do we leave it open for further investigation (in case anyone feels inclined)?

**Comment by philipperemy** [comment]
Tensorflow is slower than Theano for sure. TensorFlow does not support so-called “inline” matrix operations, but forces you to copy a matrix in order to perform an operation on it. Copying very large matrices is costly in every sense. TF takes 4x as long as the state of the art deep learning tools. Google says it’s working on the problem.

Might be related to that.
