### ISSUE TITLE
How to perform cross validation?

### ISSUE THREAD

**Issue by anik786** [fchollet/keras#1972]
in sklearn I was able to do cross validation like so:

`cross_validation.cross_val_score(model, x, t, cv=cv, scoring=scoring, n_jobs=-1)`

How can I do this using keras (preferably using sklearn)?

**Comment by jacobzweig** [comment]
Sure, just as you would with any other sklearn models...

```
kf = KFold(4, n_folds=2)
for train, test in kf:
    X_train = X[train]
    X_test = X[test]
    y_train = y[train]
    y_test = y[test]

    #fit model and score
    net.fit( ... )
```

Make sure that you're reinitializing random weights rather than continuing to train the existing model on every cv iteration.
