### ISSUE TITLE
Cannot use containers.Sequential() inside TimeDistributed()

### ISSUE THREAD

**Issue by sjebbara** [fchollet/keras#1973]
Hi,
I am currently experiencing the issue that I cannot use a Sequential() container as the argument to the TimeDistributed() layer. See the dummy script below:

``` python
 1: input_size = 2
 2: dense_size = 10
 3:
 4: model = Graph()
 5: model.add_input(name="input_sequence", input_shape=(0, input_size))
 6:
 7: scorer = containers.Sequential()
 8: scorer.add(Dense(dense_size, input_dim=input_size, activation="relu"))
 9:
10: distributed = TimeDistributed(scorer)
11: 
12: model.add_node(distributed, name="dense", input="input_sequence")
13: ...
```

An error is thrown when adding the TimeDistributed layer to the model (line 12 in this example):

```
Using Theano backend.
Traceback (most recent call last):
  File ".../src/KerasError.py", line 21, in <module>
    model.add_node(distributed, name="dense", input="input_sequence")
  File ".../keras/layers/containers.py", line 444, in add_node
    layer.set_previous(self.inputs[input])
  File ".../keras/layers/core.py", line 151, in set_previous
    self.build()
  File ".../keras/layers/wrappers.py", line 47, in build
    self.layer.set_input_shape(child_input_shape)
  File ".../keras/layers/core.py", line 222, in set_input_shape
    self.input = K.placeholder(shape=self._input_shape)
AttributeError: can't set attribute
```

However, it does work when I put the Dense() layer directly into the TimeDistributed Layer.
I guess the error has something to do with self.input of the Layer already being assigned (?!).

I have to note that I use a forked Keras repository with a few changes for my work but none at the relevant locations.

Simply switching to TimeDistributedDense() is not an option since I want to distribute more complicated combinations of layers than a simple Dense() layer.

Am I missing something about the order in which to add the models or about providing dimensionalities?

**Comment by tboquet** [comment]
You could try:

```python
 1: input_size = 2
 2: dense_size = 10
 3:
 4: model = Graph()
 5: model.add_input(name="input_sequence", input_shape=(0, input_size))
 6:
 7: scorer = containers.Sequential()
 8: dense = Dense(dense_size, input_dim=input_size, activation="relu")
 9:
10: scorer.add(TimeDistributed(dense))
11: 
12: model.add_node(scorer, name="dense", input="input_sequence")
```

**Comment by sjebbara** [comment]
Thanks for your reply.
Unfortunately, I don't think this addresses the issue the way I hoped.
Your solution makes the use of the Sequential container redundant, while only allowing a single layer being passed to the TimeDistributed layer.
However, I intended to add several layers to the distributed layer like so:

```python
 1: input_size = 2
 2: dense_size = 10
 3:
 4: model = Graph()
 5: model.add_input(name="input_sequence", input_shape=(0, input_size))
 6:
 7: scorer = containers.Sequential()
 8: scorer.add(Dense(dense_size, input_dim=input_size, activation="relu"))
 8: scorer.add(Dense(100, activation="relu"))
 9:
10: distributed = TimeDistributed(scorer)
11: 
12: model.add_node(distributed, name="dense", input="input_sequence")
13: ...
```

I know that I can work around this problem by using multiple TimeDistributed layers, each containing a single (e.g. Dense) layer. However, I want to point out this issue as being a potential Bug in the Keras Framework, right?

**Comment by tboquet** [comment]
Sorry I didn't noticed that you used `Sequential` from `container`. You should use `Sequential` from `models`.

So first, you can't add this container to a model. Then, wrappers are intended to be used around layers and not models.
You could take a look at the [docstring](https://github.com/fchollet/keras/blob/master/keras/layers/wrappers.py#L6-L37) for more informations.

You could use something like this:

```python
def TimeDistributedSequential(model):
    for i, l in enumerate(model.layers):
        model.layers[i] = TimeDistributed(l)
    return model # not necessary but could be handy


input_size = 2
dense_size = 10

model = Graph()
model.add_input(name="input_sequence", input_shape=(0, input_size))
scorer = Sequential()
scorer.add(Dense(dense_size, input_dim=input_size, activation="relu"))
TimeDistributedSequential(scorer)

model.add_node(scorer, name="dense", input="input_sequence")
model.add_output(name='output', input='dense')
model.compile(optimizer='rmsprop', loss={'output': 'mse'})
```

The model compiles but I didn't test it.

**Comment by sjebbara** [comment]
Are you sure about the Sequential part?
I thought the whole point of having classes like container.Sequential is to wrap several layers in a single object that acts as a layer itself. containers.Sequential actually inherits from Layer.

Also, the documentation of the TimeDistributed Layer says that

> it can be used with arbitrary layers

Since containers.Sequential is a Layer, I would expect it to work here, too.

But, I am a bit surprised that it works with model.Sequential, when it does not with its super class. Yet, adding a model to a graph as a node seems a bit counter intuitive to me.

Maybe @fchollet can clarify this?

**Comment by tboquet** [comment]
Sorry again, I didn't thought about encapsulating a combination of layers when I first read your comment. You should be able to add it to a model.
Did you try to replace `input_dim` by `input_shape`?
One thing is that you have to define an input shape and `Dense` accepts only 2 dims. Since your input has 3 dims in your `Graph` I'm not sure how you could handle this part.
