### ISSUE TITLE
How to do runtime stuff using stateful rnn

### ISSUE THREAD

**Issue by xingdi-eric-yuan** [fchollet/keras#1977]
Hey guys, 

When using stateful rnn, we need to pre-define batch size before compile, then what is an easy way to do runtime stuff (one input data per time) with the trained big batch sized models? 

Thanks

**Comment by VanushVaswani** [comment]
Why not create array of all zeros, then set last n to your input data?
```
inbatch = np.zeros((batch_size, n_steps, n_features))
inbatch[-10,:,:] = indata
# assume we require 10 predictions
````

**Comment by xingdi-eric-yuan** [comment]
@VanushVaswani Thanks! Yea I'm doing the similar thing, but I'm wondering is there any more efficient way, more flexible way?
