### ISSUE TITLE
You cannot drop a non-broadcastable dimension.

### ISSUE THREAD

**Issue by Tokukawa** [fchollet/keras#1982]
I am trying to translate a Theano code into [Keras code]()
The problem is the line 22 of the code:

>         freqs = K.equal(val2[:,None], val2[None,:]).sum(0).astype("float32")

that return me 

> ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False), (0, 'x')))

The code logic works perfect in Theano. I can't figure out where is the problem.

**Comment by anandjeyahar** [comment]
Any clarity/update on how this was solved? or why it was closed?
