### ISSUE TITLE
How do you predict values for categories?

### ISSUE THREAD

**Issue by anik786** [fchollet/keras#1989]
In the CNN example for the minst dataset:
https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py

they tell you how to make a good CNN network to recognise hand written digits.

The issue is that it doesn't tell you how to predict new digits.

For example give an image, if I do this:

`model.predict(image)`

instead of telling me what digits it think it is, it instead gives me a list of 10 numbers (presumably probabilities)

Please help!

**Comment by MarcoROG** [comment]
Yes they are indeed the probability of each class.
You can use model.predict_classes(X, batch_size=128, verbose=1)
Following the doc this  "Generates class predictions for the input samples batch by batch."

**Comment by Sandy4321** [comment]
good question, thank you, it would be great to know answer

**Comment by Sandy4321** [comment]
And why to use batches, is it possible to send one by one?
May you add link to this place in documentation
