### ISSUE TITLE
Symmetric ZeroPadding1D

### ISSUE THREAD

**Issue by jstypka** [fchollet/keras#1998]
I'm having a problem with this line:

https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L1108

Why do we multiply `self.padding` by 2? If I want to add one zero at the end, I pass `padding=1` in the constructor and the output size then increases by 2. This does not make sense to me at all. If I wanted to increase the size by 2, I would pass 2 in the argument.

Is it just a mistake or there's something that I'm not seeing?

EDIT:
Ok, I figured out that the `ZeroPadding1D` appends zeros both at the end and the beginning, hence the multiplication. But why is it that way? Shouldn't we predominantly enable padding only at the end or only at the beginning? I have an impression that this would cover much more usecases.

**Comment by jstypka** [comment]
I wrote a simple `AsymetricZeroPadding1D` layer that covers these cases. I would be happy to make a pull request with it, if you think it might be useful.

**Comment by keunwoochoi** [comment]
I agree +1, not sure how the API should be changed though. It wouldn't hurt if we have bit more generalised code.

**Comment by jstypka** [comment]
@keunwoochoi this is roughly how I thought about it:

```
class AsymmetricZeroPadding1D(Layer):
    input_ndim = 3

    def __init__(self, left_padding=0, right_padding=0, **kwargs):
        super(AsymmetricZeroPadding1D, self).__init__(**kwargs)
        self.left_padding = left_padding
        self.right_padding = right_padding

    ...

    def get_output(self, train=False):
        X = self.get_input(train)
        return K.asymmetric_temporal_padding(X,
                                             left_padding=self.left_padding,
                                             right_padding=self.right_padding)

```
