### ISSUE TITLE
PyraMiD-LSTM in Keras

### ISSUE THREAD

**Issue by ghost** [fchollet/keras#2008]
Hi,
I would like to implement the PyraMiD-LSTM: [link](http://papers.nips.cc/paper/5642-parallel-multi-dimensional-lstm-with-application-to-fast-biomedical-volumetric-image-segmentation.pdf) in Keras.

Is there an easy way? because i don't see a way with the built in "functions"

Thanks

**Comment by MinaRe** [comment]
Hi,
Have you finished pyramid-lstm implementation?

Thanks.

**Comment by isarker** [comment]
hi @MinaRe , did you find out that how to make .mat file for MNC?

**Comment by MinaRe** [comment]
Hi, Yes I prepared .mat file but I have problem on training !!!

**Comment by isarker** [comment]
i also try... please let me know if you success . thanks in advance @MinaRe

**Comment by MinaRe** [comment]
% converts a png ground trith to .map
function GTinst=cnvt2gt(fname)
     % fname='C:\Users\ogaes\Documents\MATLAB\Mina\GT.png';
     seg=imread(fname);
     imshow(rgb2gray(seg),[]);
     GTinst.Segmentation=rgb2gray(seg);
     GTinst.Boundaries=cell(0);
     GTinst.Categories=[]; 
     ObjNumber=0;
     categoriesList=sort(unique(GTinst.Segmentation),'ascend');
     for it=1:size(categoriesList,1)
         ctg=categoriesList(it);
         if(ctg~=0)
             CC = bwconncomp(GTinst.Segmentation==ctg);% connected components analysis
             for obj=1:CC.NumObjects
                 imgb=zeros(CC.ImageSize);
                 pixelsIndex=CC.PixelIdxList{obj};
                 imgb(pixelsIndex)=ctg;
                 bnd = bwboundaries(imgb);
                 imgb2=zeros(CC.ImageSize);
                 imgb2(sub2ind(CC.ImageSize,bnd{1}(:,1),bnd{1}(:,2)))=ctg;
                 ObjNumber=ObjNumber+1;
                 GTinst.Boundaries{ObjNumber,1}=sparse(imgb2);
                 GTinst.Categories=[GTinst.Categories;ctg];
             end
         end
     end
     
end
function GTcls=cnvt2-gt(fname)
     % fname='C:\Users\ogaes\Documents\MATLAB\Mina\GT.png';
     seg=imread(fname);
     imshow(rgb2gray(seg),[]);
     GTcls.Segmentation=rgb2gray(seg);
     GTcls.Boundaries=cell(0);
     GTcls.Categories=[]; 
     ObjNumber=0;
     categoriesList=sort(unique(GTcls.Segmentation),'ascend');
     for it=1:size(categoriesList,1)
         ctg=categoriesList(it);
         if(ctg~=0)
             CC = bwconncomp(GTcls.Segmentation==ctg);% connected components analysis
             for obj=1:CC.NumObjects
                 imgb=zeros(CC.ImageSize);
                 pixelsIndex=CC.PixelIdxList{obj};
                 imgb(pixelsIndex)=ctg;
                 bnd = bwboundaries(imgb);
                 imgb2=zeros(CC.ImageSize);
                 imgb2(sub2ind(CC.ImageSize,bnd{1}(:,1),bnd{1}(:,2)))=ctg;
                 ObjNumber=ObjNumber+1;
                 GTcls.Boundaries{ObjNumber,1}=sparse(imgb2);
                 GTcls.Categories=[GTcls.Categories;ctg];
             end
         end
     end
     
end

**Comment by SnowRipple** [comment]
Hey guys!

   Did anyone succeded in implementing Pyramid-lstms in Keras?

**Comment by kutoga** [comment]
I am also very interested in PyraMiD-LSTM. Maybe someone has implemented it?

**Comment by wellescastro** [comment]
+1

**Comment by John1231983** [comment]
Hi all, anyone is the success with pre-processing of Pyramid-lstms? Could we discuss this step?
