### ISSUE TITLE
Skipgram, CBOW and variants

### ISSUE THREAD

**Issue by ktsaurabh** [fchollet/keras#2010]
Dear moderators,

Are there any particular reasons skipgram was removed from latest release? I have built upon Skipgram to code cbow, WSABIE, and various other word2vec style embedding which I tested to be of equivalent quality (qualitatively) as that of gensim. if there was no particular reason for Skipgram removal, I would like to contribute the codes to Keras.

Regards,
SK

**Comment by fchollet** [comment]
It's still there. In the same place (preprocessing/sequence.py).
