### ISSUE TITLE
Add a predict_generator method to Sequential

### ISSUE THREAD

**Issue by aKzenT** [fchollet/keras#2015]
I think it would be useful to have a predict_generator method, which accepts a generator as a first argument just like the existing *_generator methods.

Example use case:
I want to do custom evaluation after training (e.g. computing F1 score) and my evaluation data is too large to fit into a single array.

While it is not too complicated to write my own utility method for this, I believe having this in keras would have advantages as there is already some infrastructure for generators in the code base (e.g. background queue) and it would complement the other _generator methods nicely.

**Comment by aKzenT** [comment]
The following code seems to work for me, although it does show multiple progress bars which is not optimal.

```
    def predict_generator(self, generator, nb_samples, verbose=1, **kwargs):
        '''Evaluates the model on a generator. The generator should
        return the same kind of data with every yield as accepted
        by `predict`

        Arguments:
            generator:
                generator yielding dictionaries of the kind accepted
                by `evaluate`, or tuples of such dictionaries and
                associated dictionaries of sample weights.
            nb_samples:
                total number of samples to generate from `generator`
                to use in prediction.
            verbose: verbosity mode, 0 (silent), 1 (per-batch logs),
                or 2 (per-epoch logs).
        '''
        done_samples = 0
        all_outs = []
        q, _stop = generator_queue(generator, **kwargs)

        while done_samples < nb_samples:
            X = q.get()
            do_samples = len(X)
            outs = self.predict(X, batch_size=do_samples, verbose=verbose)
            all_outs.extend(outs)

            done_samples += do_samples

        _stop.set()
        return np.asarray(all_outs)
```

**Comment by martinbel** [comment]
@aKzenT Were you able to compute the f1-score with the current version of `predict_generator`?

**Comment by aKzenT** [comment]
Hey,

I'm not sure I understand your question.

At the time I was able to calculate the F1 Score easily using the result of the `predict_generator` function above.

However, there have been a lot of major changes to keras since I've written the method, so this will no longer work. Unfortunately there is also still no `predict_generator` method in the standard code.

So I guess the only way for now is to call predict in a loop and then combine the results to calculate the F1 score.

Regards!
