### ISSUE TITLE
How can i implement a word-by-word attention model?

### ISSUE THREAD

**Issue by LiuAndYang** [fchollet/keras#2017]
In this paper , [http://arxiv.org/pdf/1412.7449v3.pdf](paper), They designed a attention model, I implement the first one, the single attenion model. But how can i implement word to word attention using Keras? They need the attend vector from last step, I got no idea now about how to do it? Can anyone help me with this thank you very much!
I refered to the code posted in [https://github.com/fchollet/keras/issues/981](attention), but it seems that they are different.
and the codes posted in issue https://github.com/fchollet/keras/issues/2067 seems like single word attention, not a word-by-word attention.
@fchollet @farizrahman4u @tboquet @wxs

**Comment by wxs** [comment]
I don't currently have time to work through this paper to help you with your specific problem I'm afraid! Good luck, if you do manage to build something write up a description, I'm sure more people would like to know how to build various kinds of attention models in Keras.
