### ISSUE TITLE
How to formulate the sequence to sequence problem?

### ISSUE THREAD

**Issue by siddBanPsu** [fchollet/keras#2018]
I read other threads and understand how to model the problem with the various layers. But, when I call 

model.fit(X, Y .....)

What should X and Y be? 
For example, if actually I am mapping sentences (for machine translation), does X need to be embeddings and Y just one hot representations? 

Is there a code example that does such word to word-based sequence generation using RNN?

**Comment by fchollet** [comment]
You could have one-hot representations for both, or pre-computed embeddings
for both (for decoding the output of the model would pick the closest known
embedding of the predicted embedding...). Not sure what your problem is?

**Comment by siddBanPsu** [comment]
Yeah, I did that already, but results were not good as far the predictions were concerned. I was looking to see if Keras supports any beam search technique for sequence prediction that gives more options to the output.
