### ISSUE TITLE
BinaryWeight-Networks

### ISSUE THREAD

**Issue by Cospel** [fchollet/keras#2019]
I found this paper yesterday about Binary Networks/Convolutions and XNOR-NET: http://arxiv.org/pdf/1603.05279v1.pdf (XNOR-Net: ImageNet Classification Using Binary Convolutional Neural Networks).

Anyone tried this to implement in Keras/Tensorflow?

The memory savings looks great. Probably it will be possible just to implement something like Convolution2DBinary layer.

**Comment by NasenSpray** [comment]
There's no easy way to implement this in Keras w/o backend support, i.e., the required ops have to be supported by Theano/TensorFlow first

**Comment by bhack** [comment]
@Cospel Please try to open an issue upstream for ops then reference here.

**Comment by bhack** [comment]
I open an issue on TF at https://github.com/tensorflow/tensorflow/issues/1592. I don't know what is the state of TH.

**Comment by Cospel** [comment]
Thanks @bhack, i think this could be another great feature. :)

**Comment by EderSantana** [comment]
there are some ops here for +1, -1 https://github.com/MatthieuCourbariaux/BinaryNet

**Comment by bhack** [comment]
@EderSantana But has a [custom kernels](https://github.com/MatthieuCourbariaux/BinaryNet/blob/master/Run-time/binary_kernels.cu) not integrated  upstream.

**Comment by EderSantana** [comment]
and the license is GPL. Theano is BSD... They won't merge it upstream

**Comment by bhack** [comment]
If you want you can try to open an issue to Theano.

**Comment by nouiz** [comment]
I just asked the author and he agree to change the license. Opening an
issue on Theano is a good idea. I let the a user that want this do it.

**Comment by nouiz** [comment]
It is changed.

**Comment by bhack** [comment]
I think that some implementation  stuffs related to the paper are done in Torch and available here https://github.com/mrastegari/Deeper_Net

**Comment by Seraphli** [comment]
@bhack The repo disappeared. That's strange. I think he is the author of the paper about XNOR-Net. I was trying to find more about xnor-net, and just find this thread.

**Comment by xxlylf** [comment]
@bhack Do you have downloaded the code of XNOR-Net from https://github.com/mrastegari/Deeper_Net ？Can you email this code to me? xxlylf@sina.com   Thanks!

**Comment by albicasty** [comment]
@bhack I'm also interested, thanks!

**Comment by bhack** [comment]
Sorry I don't have. Please follow also the last messages from https://github.com/tensorflow/tensorflow/issues/1592

**Comment by kaihuchen** [comment]
Has there been any progress reported in making the Binary Networks available in Keras or Tensorflow? 
My interest here is in using it to investigate a kind of Monte Carlo method for neural networks. 
The idea here is that if the forward pass is lightning fast then it is perhaps possible to dispose of the more expensive backward passes by doing many guided guesses in the forward passes. It should be really interesting to try this out.

**Comment by xylcbd** [comment]
follow it

**Comment by bentaylordata** [comment]
Following

**Comment by DingKe** [comment]
There is an ineffient implementation for demo: https://github.com/DingKe/nn_playground/tree/master/binarynet

**Comment by ppwwyyxx** [comment]
There are some other "inefficient" implementation in tensorflow, e.g.:
DoReFa-Net: https://github.com/ppwwyyxx/tensorpack/tree/master/examples/DoReFa-Net
Binary-Weight network (with full precision activations) is a special case in DoReFa-Net.
Trained Ternary Quantization (ICLR17 submission): https://github.com/czhu95/ternarynet

**Comment by JingrenChen** [comment]
There is an implementation of Binarized Neural Networks on embedded device:
https://gitlab.com/htkung/ddnn/

Here is the paper: 
http://www.eecs.harvard.edu/~htk/publication/2017-ewsn-mcdanel-teerapittayanon-kung.pdf

**Comment by itransvideo** [comment]
following it. I want to use the binaryConnect too

**Comment by lgeiger** [comment]
If anyone is still looking for binarized and other extremely quantized layers and pretrained models, feel free to checkout http://larq.dev and https://github.com/larq/larq which is based on `tf.keras` with full support for TF 1.x and 2.0.0.
