### ISSUE TITLE
Predicting next values using LSTM

### ISSUE THREAD

**Issue by plentsov** [fchollet/keras#2022]
Hello!

I have a large time-series (each point is vector of length 30), and I need to predict the following time-series point using the previous ones. 
So I have some amount of independent training sets (each represents a time-series of length 1mln+).
And I know that there is a long-term dependence of the points. 
I'm trying to figure out how to use LSTM => Dense in this case. 

First of all, I don't understand the issue of the input shape. I found that It should be (timesteps, 30) in my case. Does it mean, that if assume that the point Xi depends on the previous ten points, my i-th training example should be of shape (10,30) and include concatenateed X_i-10...X_i-1? It seems like a lot of replicated data. It seems like this "timesteps" should mean the length of sequence, while in my case I have a sequence of 1.2mln...

Also this is important because I'm going to use this model on the absolutely new data, feeding test examples one by one, so for the first points there will be no previous points.
I have also found the idea of the stateful RNN. Should I use it in this case? And if so, what about the shape again.

Thanks a lot!

**Comment by keunwoochoi** [comment]
Have you checked the [char-lstm generation example](https://github.com/fchollet/keras/blob/master/examples/lstm_text_generation.py)? It would help understanding how to preprocess the sequence. Adjusting `maxlen` and `step` in the example would let you get the data prepared - probably `maxlen=10` and `step` for something shorter than 10.

**Comment by plentsov** [comment]
@keunwoochoi I will check it out, also I have already studied some examples. But most of them (and yours too) cover text prediction, while I am interested in prediction of the next vector of 30  floats.
I'm  now trying to use stateful option and batches of size 1, and not quite sure how often should I reset the state. The model performance is very poor now.
So it's more question on the concept on solving my problem...

**Comment by keunwoochoi** [comment]
Yes, but I assume the same architecture would work whether it's one-hot vector or vectors with continuous values (I haven't used it on RNN layers but other types of layer work for both of them).

**Comment by elopiccoli** [comment]
Hi, related question here. The prediction will always be t+1 or is there any way to get the next 3 values t+1,t+2,t+3, for example?
