### ISSUE TITLE
graph model as a shared node:theano.compile.function_module.UnusedInputError

### ISSUE THREAD

**Issue by cxfneo** [fchollet/keras#2024]
## My base network as follows:

def create_base_network(last_hidden_dims,hidden_units,vocabsize,timesteps,data_dim):
    model = Graph()
    model.add_input(name='input0', input_shape=(timesteps,), dtype=int)
    model.add_node(Embedding(vocabsize, data_dim, input_length=timesteps),
               name='embedding', input='input0')
    model.add_node(LSTM(hidden_units), name='forward', input='embedding')
     model.add_node(Dense(last_hidden_dims, activation='sigmoid'), name='sigmoid', input='forward')
    model.add_output(name='output', input='sigmoid')
##     return model

After this , I use this base network as an another shared graph node:
g = Graph()
g.add_input(name='input_a', input_shape=(nsteps,),dtype='int')
g.add_input(name='input_b', input_shape=(nsteps,),dtype='int')
g.add_input(name='input_c', input_shape=(nsteps,),dtype='int')
g.add_shared_node(base_network, name='shared', inputs=['input_a','input_b','input_c'],merge_mode='join')
g.add_node(Lambda(euclidean_distance),name='d',input='shared')
g.add_output(name='output', input='d')
rms = RMSprop()
## The error is :theano.compile.function_module.UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 1 is not part of the computational graph needed to compute the outputs: input_b

Thanks for anyone's help or advice for this problem. I can't work it out.

**Comment by sunshineatnoon** [comment]
I've encountered similar problem, maybe you declared but didn't use variable input_b in you loss function.
