### ISSUE TITLE
How to install graphviz ?

### ISSUE THREAD

**Issue by Zjw-ML** [fchollet/keras#2026]
Hello!

If use this
`from keras.utils.visualize_util import plot`
`plot(model, to_file='model.png')`

will rise an error that
`from keras.utils.visualize_util import plot`
`File "build\bdist.win-amd64\egg\keras\utils\visualize_util.py", line 12, in <module>`
`RuntimeError: Failed to import pydot. You must install pydot and graphviz for pydotprint to work.`

I can `import pydot`
But `print pydot.find_graphviz()` is `None`

How to install graphviz ?

I try to install `graphviz-2.38.msi` , after that `pip install graphviz`
But `print pydot.find_graphviz()` is still `None`

Thanks a lot!

**Comment by Zjw-ML** [comment]
[https://github.com/Theano/Theano/issues/1801](url)
Here you can solve this problem !

**Comment by NasenSpray** [comment]
You have to add the path of GraphViz' `\bin` folder (for example, it's `C:\Program Files (x86)\Graphviz2.38\bin` for me) to the `PATH` environment variable. 

btw, your problem has nothing to do with Keras _at all_.

**Comment by Zjw-ML** [comment]
thinks very much ，my fault !
