### ISSUE TITLE
The merge layer set in "sum" means the simple element-wise addition or weighted addition?

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#2032]
For instance, the output of `model0` is `g0`, and the output of `model1` is `g1`. Then the output of `model.add(Merge([model0, model1], mode='sum'))` is `g0+g1`, or `p0*g0+p1*g1`?
If not `p0*g0+p1*g1`, can I set the rate `p0` and `p1` ?

**Comment by NasenSpray** [comment]
`g0+g2`

**Comment by Imorton-zd** [comment]
@NasenSpray Thanks for your response. Can I achieve the addition like `p0*g0+p1*g1`, how do I set these two parameters?

**Comment by NasenSpray** [comment]
It depends, should `p0` and `p1` be trainable or are they fixed constants?
* trainable: you have to implement a custom layer
* fixed: use a [`LambdaMerge`](http://keras.io/layers/core/#lambdamerge) layer  
`
model.add(LambdaMerge([model0, model1], lambda inputs: p0*inputs[0]+p1*inputs[1]))
`

**Comment by bmkelly** [comment]
Sorry to revive a post a year later, but if other people are doing this same thing, I think there exists an easier way to implement this to be trainable:

Add a trainable scaling layer after g0/g1, then add the output of the scaling layers, which learn p0/p1.

**Comment by Imorton-zd** [comment]
@bmkelly Thanks for your reply. Actually, what is the trainable scaling layer? Please give an simple example like code snippet. Thanks again!

**Comment by bmkelly** [comment]
Oh wow, I was incorrect, a Scaling layer does not exist in Keras.  

I would hack it together like this:

use a lambda layer to acquire a single '1' vector,
learn a scaling factor via a dense layer which takes a single input and outputs a single number
repmat that scaling factor to the correct size
multiply the scaling factor with whatever we are scaling

In code form.  This doesn't throw any errors when generating the model, but I havn't fully tested it.  Also, its getting late so hopefully this is understandable.

input_shape=(64,64,1)
input_img = Input(shape=input_shape)
conv1_output = Convolution2D(64,3,3,activation='relu', border_mode='valid')(input_img)

# Getting a tensor with a single 1:
single_one = GlobalMaxPooling2D()(input_img)
single_one = Lambda(lambda x: x**0)(single_one)
# Scaling parameter!
trainable_scaling_parameter = Dense(1)(single_one)
# Repmat this to the size of conv1
size_conv1_output = conv1_output.get_shape()[1]*conv1_output.get_shape()[2]*conv1_output.get_shape()[3]
repeated_scale = RepeatVector(int(size_conv1_output))(trainable_scaling_parameter)
target_shape = (int(conv1_output.get_shape()[1]),int(conv1_output.get_shape()[2]),int(conv1_output.get_shape()[3]))
reshaped_to_conv1_shape = Reshape(target_shape)(repeated_scale)

# Finally multiply the scaling matrix with our convolution output:
scaled_conv1_output = merge([conv1_output,reshaped_to_conv1_shape],mode='mul')

**Comment by alyato** [comment]
@Imorton-zd  I don't understand the `mode=sum ,dot,concat` in merge well.
Do i understand it like this

> the output of c1 is`(batchsize,64,32,32)` and  the output of c3 is`(batchsize,64,28,28)` 
when i set `merge([out1,out3],mode=sum)` ,it does't work.
but the output of c1 is`(batchsize,64,32,32)` and  the output of c3 is`(batchsize,64,32,32)`
when i set `merge([out1,out3],mode=sum)` ,it work.

So both the outputs must be same? Is it right? Thanks

**Comment by alyato** [comment]
@bmkelly I have some questions about your question. Im not famillar with the `Lambda` layer.

> single_one = GlobalMaxPooling2D()(input_img)  ---(64,32,32)
single_one = Lambda(lambda x: x**0)(single_one) ---(64,1)

Is it right  about the output? Thanks
