### ISSUE TITLE
More documentation and comments for Keras please!

### ISSUE THREAD

**Issue by shyamalschandra** [fchollet/keras#2039]
Hi,

Would you please be able to provide more explanation in the comments for the Keras code (or at least the papers that are relevant to the underlying theory in the docs on the website), similar to Keras, for the Keras tutorials and the general documentation?  I have the code running with the binary installation (not the source installation) so I need a way to guide my intuition so that i can build complex deep layered models.

Thanks!

Best regards,
Shyamal Chandra

**Comment by ymcui** [comment]
At first, you should get familiar with Theano or Tensorflow.
Because the actual implementation is done on these two backends.
I think it won't be hard to understand the source code with knowing Theano/Tensorflow.

**Comment by shyamalschandra** [comment]
How can I _know_ Theano or Tensorflow if their documentation has holes too?  What do you recommend, @ymcui?

**Comment by ymcui** [comment]
personally I recommend to use **Theano** :)
