### ISSUE TITLE
Display keras visualization from ipython console

### ISSUE THREAD

**Issue by grahamannett** [fchollet/keras#2043]
Hey, I noticed for the Keras documentation, while displaying the simple visualization in a notebook works fine, using console is not as direct.  I was curious if this should be incorporated just into the documentation (since it is more of a matplotlib/ipython/pydot thing) or if this is something that should be included in the keras visualize_util module.  

Example for how to get it to plot (at least for me, using python3.5) from console is:
```
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.utils.visualize_util import to_graph

model = Sequential()
model.add(Dense(output_dim=64, input_dim=100, init="glorot_uniform"))
model.add(Activation("relu"))
model.add(Dense(output_dim=10, init="glorot_uniform"))
model.add(Activation("softmax"))
model.compile(loss='categorical_crossentropy', optimizer='sgd')


import io
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
%matplotlib

img = io.BytesIO()
png_img = to_graph(model).create(prog='dot', format='png')
img.write(png_img)
img.seek(0)
img = mpimg.imread(img)
plt.imshow(img)
```

Just seem's like if there is a way to get it to plot easily from an ipython notebook that it would be useful from console as well (and perhaps there is a better way to do this than I know of?)

Also, I have no idea what people with more knowledge think is better but could easily be incorporated into keras.utils.visualize_util.plot() with some flag to display or save 

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by kmader** [comment]
You can use the ```IPython.display``` tools to make it easier. Since I prefer SVG to PNG I switched it, but you can use the original code with the ```from IPython.display import Image``` if you prefer

```
from IPython.display import SVG
svg_img = to_graph(model).create(prog='dot', format='svg')
SVG(svg_img)
```

**Comment by grahamannett** [comment]
@kmader That doesn't display/open from console for me.  Are you referring to a notebook?

**Comment by rollingstone** [comment]
have u tried 
%matplotlib inline 
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

**Comment by EderSantana** [comment]
maybe you should start the console ipython in `qtconsole` mode https://ipython.org/ipython-doc/3/interactive/qtconsole.html

**Comment by grahamannett** [comment]
@EderSantana that isnt using ipython from within terminal of choice though.  I guess this doesn't really matter since it's not Keras problem and could be noted in docs if necessary in the future.
