### ISSUE TITLE
CNN parameters

### ISSUE THREAD

**Issue by resplendentfrever** [fchollet/keras#2047]
Hello. I am trying to implement my first cnn using Keras. I could not understand the parameters nb_filter,filter_length and border_mode.
Can someone please explain it to me?
Thanks in advance

**Comment by ymcui** [comment]
`nb_filter` means how many filters are you going to use. in `Convolution1D`, it also means the output dimension
`filter_length` is only used in `Convolutional1D` which means the length of each filter. 
for e.g. X=[a,b,c,d]
if you choose `filter_length=3`
then
[a,b,c],[b,c,d] are sent to conv net.
`border_mode` indicate the type of output, details can be found in 
http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve2d.html
```
mode : str {‘full’, ‘valid’, ‘same’}, optional
A string indicating the size of the output:
full
The output is the full discrete linear convolution of the inputs. (Default)
valid
The output consists only of those elements that do not rely on the zero-padding.
same
The output is the same size as in1, centered with respect to the ‘full’ output.
```

**Comment by resplendentfrever** [comment]
So if I want to give variable length input to my cnn, how can I do so?
Basically I want to give word embeddings of a sentence, without padding it with zeros

**Comment by ymcui** [comment]
I'm afraid you must do paddings before sending it to convnet.
