### ISSUE TITLE
Shared Layers

### ISSUE THREAD

**Issue by ssamot** [fchollet/keras#2048]
What's the best way to instantiate a number of models, with all layers being the same (i.e. sharing the same weight matrix) apart from one?

**Comment by fchollet** [comment]
Currently the way to do this is via the `Siamese` layer wrapper, or `add_shared_node` in `Graph` (you'll find an example at http://keras.io/examples/).

However if you can wait a week or two, there is a new functional API coming that will make shared layers first-class citizens.

**Comment by ssamot** [comment]
Thanks - so if I have run 1000 networks that share every layer between each other except one and train them independently would I have to compile 1000 networks?

**Comment by cxfneo** [comment]
Hi @fchollet   
Can we make a graph  as  a shared node of an another graph with multi-input?   I found it didn't work.
It gave theano errors about unused input. Could you give some advice about using graph in Keras?
