### ISSUE TITLE
Simple mlp with one hidden layer keeps predicting same number for all training examples

### ISSUE THREAD

**Issue by asai95** [fchollet/keras#2051]
Hi, everyone! 
I've just started to learn keras and already have one serious problem. I'm trying to predict stock price using its previous values. The model I use is built on examlples from official site. This model minimizes its lost function and weights are changing, but when I'm trying to actualy predict prices using trainig examples, I'm getting an array with fixed number (well, it's changing a little, but insignificantly).

Here's my code:
```
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
import numpy

data = numpy.genfromtxt('data.csv', delimiter=';', skip_header=True, skip_footer=False)

scale = numpy.max(data)
data /= scale

y = data[:, :1]
x = data[:, 1:]

model = Sequential()
model.add(Dense(7, input_dim=x.shape[1], init='uniform', activation='linear'))
model.add(Dense(4, init='uniform', activation='tanh'))
model.add(Dense(y.shape[1], init='uniform', activation='linear'))

sgd = SGD(lr=0.06, decay=1e-6, momentum=0.5, nesterov=False)
model.compile(loss='mean_squared_error', optimizer=sgd)
model.fit(x, y, nb_epoch=2, batch_size=1, shuffle=False)

print(model.predict(x, batch_size=1)*scale)
```
And the output:
```
Epoch 1/2
2451/2451 [==============================] - 2s - loss: 8.8777e-04     
Epoch 2/2
2451/2451 [==============================] - 2s - loss: 5.1640e-04     
2451/2451 [==============================] - 1s     

[[ 145.92594338]
 [ 145.92718066]
 [ 145.92615142]
 ..., 
 [ 145.88787241]
 [ 145.88566064]
 [ 145.88658038]]
```
Can someone please explain what's wrong with this model. I understand that basic mlp is not a good predictor, especially with only previous values as input features, but this still seems wrong to me.

**Comment by NasenSpray** [comment]
> I understand that basic mlp is not a good predictor, especially with only previous values as input features, but this still seems wrong to me.

Why? It's such an incredibly tiny network...

**Comment by asai95** [comment]
> Why? It's such an incredibly tiny network...
I don't really understand how could we get same output for different inputs? Even with simple linear regression this result would be strange.

**Comment by tboquet** [comment]
Do you have your residuals? What's the max, the min and their variance?

**Comment by asai95** [comment]
> Do you have your residuals?

Can you please give me a tip how to get them in keras?

**Comment by asai95** [comment]
> What's the max, the min and their variance?

They're 0.603 -0.161 0.030 respectively.

**Comment by tboquet** [comment]
Try to graph your predictions against the variable you are trying to predict at each epoch. Given the predicted values you posted and your data, the statistics you gave on your residuals seems weird. Also note that you don't have a lot of data and you only trained the model for 2 epochs...  I suspect the model learnt the mean of your timeseries and you should increase the number of epochs.

**Comment by asai95** [comment]
My bad. I forgot to point that predictions are multiplied by scaling factor (which is basically maximum in my dataset), but residual calculated as scaled targets - unscaled predictions.
I also tried to run up to 100 epochs and got same result.
May be I should change batch size? I'm not quite understand how to choose it. Because each epoch takes about two seconds to learn on batch size = 1.

**Comment by charlesjansen** [comment]
same issue
