### ISSUE TITLE
Question about why SGD does not work

### ISSUE THREAD

**Issue by dsy412610** [fchollet/keras#2058]
I have this problem: When I changed the value of lr or decay in SGD, I find that nothing changed in my result. (I fixed random number by using np.random.seed(1234))

**Comment by dsy412610** [comment]
The problem was solved for I made a stupid mistake by using "optimizer = 'sgd'".

**Comment by dsy412610** [comment]
The problem was solved for I made a stupid mistake by using "optimizer = 'sgd'".

**Comment by alyato** [comment]
@dsy412610  what does your mean?

> The problem was solved for I made a stupid mistake by using "optimizer = 'sgd'".
