### ISSUE TITLE
Exception: Layer is not connected. Did you forget to set "input_shape"?

### ISSUE THREAD

**Issue by taiji1985** [fchollet/keras#2060]
I am  a beginner of Keras .

I got the Exception ,when I run the example code python mnist_cnn.py。

when I first run ,I found that The code 
`model.add(Convolution2D(32, 1, 3, 3, border_mode='full'))` cause an exception ,
I check the source of Convolution2D and changed it to valid。
Then An exception occured 
`
model.add(Convolution2D(32, 1, 3, 3, border_mode='valid'))
model.add(Activation('relu'))
model.add(Convolution2D(32, 32, 3, 3))  #58 This cause an exception 
model.add(Activation('relu'))
model.add(MaxPooling2D(poolsize=(2, 2)))
model.add(Dropout(0.25))
`
**How can I do to fix it ? Or How can I get matched example of the keras 0.3.2 version ?
Is that caused by version upgrade?
**

  File "mnist_cnn.py", line 58, in <module>
    model.add(Convolution2D(32, 32, 3, 3))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/containers.py", line 70, in add
    self.layers[-1].set_previous(self.layers[-2])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 137, in set_previous
    assert self.input_ndim == len(layer.output_shape), ('Incompatible shapes: layer expected input with ndim=' +
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 228, in output_shape
    return self.input_shape
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 202, in input_shape
    previous_size = self.previous.output_shape
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 287, in output_shape
    input_shape = self.input_shape
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 210, in input_shape
    raise Exception('Layer is not connected. Did you forget to set "input_shape"?')
Exception: Layer is not connected. Did you forget to set "input_shape"?

**Comment by ymcui** [comment]
You should read documentation carefully.
When you use `Convolutional1D` or `Convolutional2D` as your first layer, the `input_shape` MUST be provided.
```
Convolution operator for filtering neighborhoods of one-dimensional inputs. When using this layer as the first layer in a model, either provide the keyword argument input_dim (int, e.g. 128 for sequences of 128-dimensional vectors), or input_shape (tuple of integers, e.g. (10, 128) for sequences of 10 vectors of 128-dimensional vectors).
```

**Comment by taiji1985** [comment]
@ymcui Thanks ! I read the source code of keras and modified mnist_cnn.py . and it works!

achieve a 98.99% accuracy for mnist dataset  ! Great Deep Learning , Great CNN !  ,Great Keras ! 
The examples same to be out-of-date . maybe i should contribute the modified code to the project!
