### ISSUE TITLE
Trying to run a SimpleRNN but having shape problems in model.fit

### ISSUE THREAD

**Issue by abutremutante** [fchollet/keras#2063]
I'm new to Keras and having some trouble with shapes, specially when it comes to RNNs and LSTMs.

**I'm running this code:**

```
model.add(SimpleRNN(init='uniform',output_dim=1,input_dim=len(pred_frame.columns)))
model.compile(loss="mse", optimizer="sgd")
model.fit(X=predictor_train, y=target_train, batch_size=len(pred_frame.index),show_accuracy=True)
```

The variable predictor_train is a numpy array with 119 inner arrays, each one having 80 different items.

**I'm having this error:**

```
File "/Users/file.py", line 1496, in Pred
model.fit(X=predictor_train, y=target_train, batch_size=len(pred_frame.index),show_accuracy=True)
File "/Library/Python/2.7/site-packages/keras/models.py", line 581, in fit
shuffle=shuffle, metrics=metrics)
File "/Library/Python/2.7/site-packages/keras/models.py", line 239, in _fit
outs = f(ins_batch)
File "/Library/Python/2.7/site-packages/keras/backend/theano_backend.py", line 365, in __call__
return self.function(*inputs)
File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 513, in __call__
allow_downcast=s.allow_downcast)
File "/Library/Python/2.7/site-packages/theano/tensor/type.py", line 169, in filter
data.shape))
TypeError: ('Bad input argument to theano function with name "/Library/Python/2.7/site-packages/keras/backend/theano_backend.py:362"  at index 0(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (119, 80).')
```

The shape the error is appointing matches with the numpy array used as predictor_train. According to http://keras.io/layers/recurrent/, the third dimension I'm missing apparently is nb_samples.

**My question is: how do I find the shape of nb_samples and how do include that in my code in a way it fixes this problem?**

**Comment by ymcui** [comment]
The `RNN` receives 3D tensor with shape of `(batch_size, timesteps, dimension)`
when you set `input_shape` the `batch_size` is usually omitted, and you should just provide a tuple of (timesteps, dimension).

**Comment by abutremutante** [comment]
@ymcui thanks a lot for your contribution. Please correct me if I'm wrong: batch_size=timesteps*dimension?
Where exactly in the code should I include that data for it to work (inside model.fit or inside SimpleRNN)? How should the code be?
Sorry about this basic questions, I'm a beginner on Keras trying to find out how to move in the layers world.
