### ISSUE TITLE
How to avoid updating state with stateful=True

### ISSUE THREAD

**Issue by plentsov** [fchollet/keras#2064]
I'm using RNN with stateful=True.
In each iteration I have two calls of model.predict_on_batch and one call of model.train_on_batch
How can I avoid updating internal state of model during predictions and only update it when using train?
Thanks.

**Comment by ymcui** [comment]
in documentation,
`To reset the states of your model, call .reset_states() on either a specific layer, or on your entire model.`
Hope this works.

**Comment by plentsov** [comment]
@ymcui .reset_states() will literally reset state, when I need it to be untouched when predicting and to be updating when training.

**Comment by ymcui** [comment]
What do you mean by 'avoid updating internal state' ?
do you mean you would like to set `stateful=True` when in training, and turn `stateful=False` in testing?

**Comment by plentsov** [comment]
@ymcui 

According to FAQ:

> Notes that the methods predict, fit, train_on_batch, predict_classes, etc. will all update the states of the stateful layers in a model. This allows you to do not only stateful training, but also stateful prediction.

I want to avoid updating during some calls, while update on others. (without resetting states in the meanwhile)

**Comment by NasenSpray** [comment]
> I want to avoid updating during some calls, while update on others. (without resetting states in the meanwhile)

Currently not possible.

**Comment by ymcui** [comment]
I'm afraid it is not supported for now. :(

**Comment by plentsov** [comment]
@NasenSpray 
I thought of the possibility to clone mode and do predictions with this clone, while train on the main model. Is it possible?

**Comment by ymcui** [comment]
> I thought of the possibility to clone model and do predictions with this clone, while train on the main model. Is it possible?

you can try to train a stateful model, and save the weights of it, and load weights to another non-stateful model and make predictions. but i am not sure this gonna work.

**Comment by NasenSpray** [comment]
You could also save/restore the RNN states:

```
import keras.backend as K

def get_states(model):
    return [K.get_value(s) for s,_ in model.state_updates]
    
def set_states(model, states):
    for (d,_), s in zip(model.state_updates, states):
        K.set_value(d, s)
```

**Comment by plentsov** [comment]
@NasenSpray Thanks! I'll try it.
