### ISSUE TITLE
Different time between building model and training model when using CPU and GPU, repectively. 

### ISSUE THREAD

**Issue by fluency03** [fchollet/keras#2075]
When I was running some examples, I have tested them by switching between CPU and GPU on my PC. 

Obviously, when using GPU, the training time is less than using CPU. 
However, the timing of building the model seems takes longer time when enabling GPU than purely using CPU.  

I am assuming that, when enabling GPU, even the model building is done on GPU, which may have less parallel requirements and CPU would be faster on building it. 

So I am wondering, is there any way (or api or code) that I could use CPU to build the model and switch to GPU to train the model?

**Comment by ymcui** [comment]
When compiling with GPU, some GPU specific variables should be set up (via `nvcc` compiler or something), and obviously, it can not be done only with CPU.
So, be patient and wait.

**Comment by NasenSpray** [comment]
Nvidia's GPU compiler (`nvcc`) is painfully slow, it's normal.

**Comment by fluency03** [comment]
@ymcui This is my GPU settings, if this is what you mean. 

    [global]
    floatX = float32
    device = gpu

    [lib]
    cnmem = 0.9

    [cuda]
    root = /usr/local/cuda

**Comment by ymcui** [comment]
Nope, I am not meaning the GPU setups.
I mean when you are going to run your code on GPU, some variables (such as theano tensors) should be converted to CUDA related stuff (such as kernel functions, kernel variables, which is done by nvcc compilers), and this procedure cannot be only done on CPU. So you HAVE TO wait, because there is no the other way.

**Comment by fluency03** [comment]
Thanks. What I am wondering is that, I have seen another library [neon](https://github.com/NervanaSystems/neon), where you could switch from CPU to GPU, or vice versa [here](http://neon.nervanasys.com/docs/latest/faq.html). 

i am wondering whether Keras is capable of this.
