### ISSUE TITLE
Compile error while using Embedding and Merge together

### ISSUE THREAD

**Issue by luopuya** [fchollet/keras#208]
Hi guys, I love this project very much but not familiar with theano.

My real question is to implement the architecture of https://github.com/yoonkim/CNN_sentence:
 the simplified pipeline is **Embedding -> Merge(cnns) -> Dense**
**Merge acts similar as FeatureUnion in sklearn here, Embedding' W need to be changeable.**

----

While using Keras, I meet this question **Could Merge connect previous layer?**

    Merge's super is Object rather than Layer, so it must be the first 'layer'?
    I change Merge's super to Layer, but it raises  **DisconnectedInputError** when compiling
> DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: <TensorType(float64, matrix)>

**Comment by fchollet** [comment]
Can you show your code that led to this error message?

**Comment by luopuya** [comment]
Thanks for replying~

**My original goal is ‘Merge’ connect Embedding and share same input**

```Python
m = Sequential()

m.add(Dense(50, 50))
m.add(RepeatVector(2))  # Repeat for Merge?

l = Sequential()
l.add(Dense(50, 50, activation='relu'))
r = Sequential()
r.add(Dense(50, 50, activation='relu'))
m.add(Merge([l, r], mode='concat'))

m.add(Dense(100, 2, init='uniform', activation='sigmoid'))

m.compile(loss='categorical_crossentropy', optimizer='sgd')
```

It raise *AttributeError: 'Merge' object has no attribute 'connect'*
Then I change Merge's super to Layer, so it has 'connect' now
Finally, it raise *DisconnectedInputError*
> DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: <TensorType(float64, matrix)>

-----------------------
Is it possible to implement that Merge's models share same input from previous layer?

**Comment by fchollet** [comment]
I'm starting to think we should refactor Merge as a model, which is made possible now by the recent container refactor (wasn't the case when Merge when initially implemented). It would make things clearer.

It sounds like you are trying to do a fork of your network after the first layer, then a Merge. But forks are not yet supported. RepeatVector is not a fork (the output is still a single tensor).

**Comment by simonzack** [comment]
Having the same issue, I'm using `Graph` to address this but it isn't very clean.
