### ISSUE TITLE
Implementation of Spatial Pyramid Pooling Layer

### ISSUE THREAD

**Issue by guilk** [fchollet/keras#2080]
Hi All,

I am new to keras. I was wondering if there is an implementation of Saptial Pyramid Pooling as described in this paper: http://arxiv.org/pdf/1406.4729.pdf . Could someone give me a pointer to the related materials.

**Comment by NasenSpray** [comment]
It's not possible to do this with Keras. It would have to be a custom layer that uses Theano/TensorFlow directly.

**Comment by dsy412610** [comment]
Yeah, I defined SPP pooling layer myself by myself using Theano.

**Comment by dsy412610** [comment]
Yeah, I defined SPP pooling layer by myself.

**Comment by guilk** [comment]
@NasenSpray Thanks for your comments.
@dsy412610 Would you mind sharing your implementation of SPP pooling layer? Many thanks!

**Comment by dsy412610** [comment]
@guilk Yeah. Could you please give me your Email or some other way of contact？

**Comment by MeJn** [comment]
@dsy412610 Hi, I'm also confused about the implementation of spp, and would you mind sharing it to me?Thank you very very much! And that's my email: mega.mj@hotmail.com

**Comment by guilk** [comment]
@dsy412610 Thanks very much. my email address is guiliangke@gmail.com

**Comment by jiaqima** [comment]
@dsy412610 Hi, would you mind sharing it to me too? Thank you very much. My email: brucemjq@gmail.com

**Comment by shirtzet** [comment]
@dsy412610 Hi, its is nice to see what you've done, can you share it with me too?
shiretzet@gmail.com

**Comment by zubata88** [comment]
Hi, I have the same problem. It would be nice if you could share it with me too! My email: simon <DOT> andermatt <AT> gmail.com
Thank you very much!

**Comment by braingineer** [comment]
Hi @dsy412610, would you mind sharing your implementation with me as well? My email is brian.c.mcmahan at gmail.com

**Comment by BackNode** [comment]
@dsy412610 Hi, would you mind sharing it to me ? Thank you very much. My email: tingtingzhao6746@hotmail.com

**Comment by piotrmilos** [comment]
I would appreciate a copy as well. Me email is lyzell@gmail.com

Best

**Comment by yongzheyan** [comment]
Hello @dsy412610, being confused with the implementation when defining the fixed size in the data layer, could you please share the code with me by email: yanyongzhe@gmail.com ?  Thanks a lot.

**Comment by hirohashi** [comment]
@dsy412610 I am also interested in the spp-net. Could you please send me the implementation? My email address is udpip.nnct<ATMARK>gmail.com . Thank you.

**Comment by Yozey** [comment]
Similar implementation could be found in Lasagne framework. The implementation could be the same. Reference: [Lasagne_dnn.py](https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/dnn.py)

**Comment by yunqy** [comment]
Hi @dsy412610, I am interested in the implementation of SPP-Net too. It would be so nice if you could share it with me as well! 
My email: yunqyzhang@gmail.com
Thank you very much!

**Comment by adammenges** [comment]
@dsy412610 same here! 

adam@adammenges.com

Thanks!

**Comment by duducheng** [comment]
@dsy412610 cound you please send me a copy for your implement of  Sppnet? I'm confused on how to define my own layer

**Comment by duducheng** [comment]
@dsy412610  cound you please send me a copy for your implement of Sppnet? I'm confused on how to define my own layer. My email is jekyLL4168@icloud.com , thank you in advance!

**Comment by parag2489** [comment]
@dsy412610 Can you please share your implementation with me? Email: parag2489@gmail.com

**Comment by anewlearner** [comment]
If someone got a copy, could you share it to me? Email: lishaxue3@gmail.com
Thanks.

**Comment by JoelChev** [comment]
I would be interested in a copy too. If anyone has it, can you please send it to me? joelcheverie@hotmail.com

**Comment by fusionlove** [comment]
I would also very much appreciate a copy :)
fintan.nagle@ucl.ac.uk
Thanks!

**Comment by akashmjn** [comment]
@dsy412610 Would you mind sharing the implementation with me too? 
akash7190@gmail.com 
Would really appreciate it :)

**Comment by chenhuai1994** [comment]
Hi,would you mind share the code with me?Thanks!  My email is 201311212009@mail.bnu.edu.cn

**Comment by birnbera** [comment]
@dsy412610 I would also be interested in seeing how you implemented this. If you don't mind pushing it to Github it would make this a lot simpler as many people are clearly interested. Thanks!

**Comment by hbyk** [comment]
@dsy412610 I would also appreciate a copy hananelbyk@gmail.com

**Comment by carpeanon** [comment]
@dsy412610 Hi, would you mind sharing it to me too? Thank you very much. My email: moblscience4@gmail.com

**Comment by MartinThoma** [comment]
@dsy412610 I am interested in your SPP layer implementation as well (probably it would be easier to add a [gist](https://gist.github.com/) here then to answer all requests?)

**Comment by MartinThoma** [comment]
See also: http://stackoverflow.com/q/40913794/562769

**Comment by mkastala** [comment]
I would also very much appreciate a copy
mkastala@uci.edu
Thanks!

**Comment by NickBuchny** [comment]
Mind if I get a copy? 

nickbuchny@gmail.com

**Comment by vision-mcgm** [comment]
Just get it here everyone:
https://github.com/yhenon/keras-spp

**Comment by dear983604** [comment]
@dsy412610 may I have your tutorial lesson. appreciate that
dear983604@gmail.com

**Comment by hiteshnitetc** [comment]
@dsy412610 please mail me at: hiteshtekchandani1@gmail.com

**Comment by 13293824182** [comment]
I would appreciate a copy as well. Me email is 13293824182@163.com

Best

**Comment by abhaykhareedhi** [comment]
Please send a copy to me too. My email is abhaykhareedhi@gmail.com

**Comment by Immasolo** [comment]
@dsy412610 Please if you don't mind send me a copy at emmani88@outlook.com. thanks

**Comment by Nevin06** [comment]
@dsy412610 Could you send me a copy at thomasnevink@gmail.com Thanks

**Comment by sohailkhanmarwat** [comment]
@dsy412610  I am also interested in the spp-net. Could you please send me the implementation? My email address is mrsohailkhan@gmail.com Thank you.

**Comment by abhaykhareedhi** [comment]
Please share the implementaion details to me as well. My ID is abhaykhareedhi98@gmail.com

**Comment by obravo7** [comment]
@dsy412610 I know I'm a bit late to the party, but could you possibly share your code with me as well? my email is eric.narciso12@gmail.com
Much appreciated.

**Comment by vision-mcgm** [comment]
Guys, I do not believe these requests will be answered. There are other
implementations of SPP which are available for download.
