### ISSUE TITLE
keras 0.3.2 not playing along with theano 0.8.0

### ISSUE THREAD

**Issue by asimkievich** [fchollet/keras#2083]
I initially thought this was a theano issue but I am not sure now. Problem is the following wickedly tricky theano message.

```
TypeError: ('An update must have the same type as the original shared variable (shared_var=    <TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix),     update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the   difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')
```

Following line triggers the issue:

```
model.compile(optimizer=SGD(lr=0.01, momentum=0.9, nesterov=True),loss='mse')
```

before going into theano, problem comes up in models.py

```
file "C:\Users\xxxx\Anaconda3\lib\site-packages\keras\models.py", line 515, in compile
self._train = K.function(train_ins, [train_loss], updates=updates)
```

Any hints?

**Comment by nouiz** [comment]
The problem is that some weights are defined as float32, but the new version of the weights in the update is in float64. You can use Theano flag warn_float64=pdb to get in python debugger when there is a float64 that is created. Do you use the Theano flag floatX=float32?

**Comment by asimkievich** [comment]
yes, sir. mode=FAST_RUN,device=cpu,floatX=float32

should I change anything?

**Comment by nouiz** [comment]
Add the flag: warn_float64=pdb

This will show you where the upcast to float64 happen.

**Comment by asimkievich** [comment]
thanks a lot Fréderic. This is what I get. Apologies, but I am a bit lost. what do I do with that? 
My script does not deal with theano, it is called from Keras. Thanks!

    > c:\users\xxx\anaconda3\lib\site-packages\theano\tensor\var.py(766)__init__()->None
    -> pdb.set_trace()
    (Pdb)

**Comment by NasenSpray** [comment]
Please post the code used to create the network to help narrow down the cause.

**Comment by asimkievich** [comment]
thanks a lot guys. here is the entire keras code.

    class NnRegression(BaseEstimator, RegressorMixin):
            def __init__(self, apply_standart_scaling=True,
                 dropx=[0.2, 0.5, 0.5], nb_neuronx=[50, 30], nb_epoch=105, validation_split=0.,
                 verbose=1):
            self.apply_standart_scaling = apply_standart_scaling
            self.dropx = dropx
            self.nb_neuronx = nb_neuronx
            self.nb_epoch = nb_epoch
            self.validation_split = validation_split
            self.verbose = verbose

        def fit(self, X, y):

            nb_features = X.shape[1]
            self.standart_scaling = StandardScaler() if self.apply_standart_scaling else None

            if self.standart_scaling:
                X = self.standart_scaling.fit_transform(X)

            model = Sequential()
            model.add(Dropout(input_shape = (nb_features,),p= self.dropx[0]))
            model.add(Dense(output_dim = self.nb_neuronx[0], init='glorot_uniform'))
            model.add(PReLU())
            
            model.add(BatchNormalization((self.nb_neuronx[0],)))
            model.add(Dropout(self.dropx[1]))

            model.add(Dense(self.nb_neuronx[1], init='glorot_uniform'))
        
            model.add(PReLU())
            
            model.add(BatchNormalization((self.nb_neuronx[1],)))
            model.add(Dropout(self.dropx[2]))

            model.add(Dense(1, init='glorot_uniform'))
        
            nn_verbose = 1 if self.verbose>0 else 0
            optz = keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08)
            model.compile(optimizer=Adam(),loss='mse')
            model.fit(X, y, batch_size=16, nb_epoch=self.nb_epoch, validation_split=self.validation_split, verbose=nn_verbose)

            self.model = model

        def predict(self, X):
            if self.standart_scaling:
                X = self.standart_scaling.transform(X)
            return self.model.predict_proba(X, verbose=0)

and then I call the class with the following lines of code:

    clf = NnRegression(nb_epoch=105, dropx=[0.2, 0.2, 0.2], nb_neuronx=[50, 30], validation_split=0., verbose=0)
    clf.fit(cv_train, label_cv_train)
    pred_cv = clf.predict(cv_test)

**Comment by NasenSpray** [comment]
Why are you passing the number of neurons to `BatchNormalization`? It doesn't even have such an argument.

**Comment by asimkievich** [comment]
hi Nasen, good point. I had some legacy code that worked in a previous version of keras. I removed the number of neurons from batch normalization, so that now it reads:

    model.add(BatchNormalization())

Now it appears that the code goes into an infinite loop (?) because it starts running and never comes back. I love theano but sometimes it is so hard....

**Comment by asimkievich** [comment]
Hi Nasen, removing the number of neurons from batch normalization solved the issue.

Too bad I cannot buy you a bear man, I would do it very happily (would actually buy you a dinner voucher very happily :) ). Thanks a lot again and feel free to close the issue.

**Comment by aimaaonline** [comment]
i am facing the problem but couldnot get what to change:
Loading Word2Vec
Traceback (most recent call last):
  File "example3.py", line 5, in <module>
    sls=lstm("new.p",load=False,training=True)
  File "/home/seemab/seemab/Siamese-LSTM-master/lstm.py", line 303, in __init__
    self.f_grad_shared, self.f_update = adadelta(lr, tnewp, grads,emb11,mask11,emb21,mask21,y, cost)
  File "/home/seemab/seemab/Siamese-LSTM-master/lstm.py", line 192, in adadelta
    name='adadelta_f_grad_shared')
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 208, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=1lstm1_U_rgrad2, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')
