### ISSUE TITLE
How is the training procedure of Autoencoder layer exactly? 

### ISSUE THREAD

**Issue by meanmee** [fchollet/keras#2084]
Is it layer-wise training or end-to-end training?

**Comment by EderSantana** [comment]
Training will be done as any other keras layer. If you put in several layers as encoder and another group as decoder, they will all be trained end to end. They can be trained layer-wise, but I believe not out of the box.

**Comment by dsy412610** [comment]
Thanks! But how should I set the value of patience, with experience or some rules？
