### ISSUE TITLE
 max_pool_2d() problem

### ISSUE THREAD

**Issue by nku428** [fchollet/keras#2085]
TypeError: max_pool_2d() got an unexpected keyword argument 'mode'

and I have run "pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps"
but the problem is still there

Let me know if a solution is available.

**Comment by EderSantana** [comment]
@nouiz, would you help us with this Theano related issue?

**Comment by ymcui** [comment]
Have you tried to install the latest Theano in GITHUB?
see Theano documentation,
http://deeplearning.net/software/theano/library/tensor/signal/downsample.html?highlight=max_pool_2d#theano.tensor.signal.downsample.max_pool_2d
`max_pool_2d()` has the argument 'mode'

**Comment by nku428** [comment]
I have tried it again, and the issue disappear, 
I don't know the reason, I just restart my computer.
thank you! @EderSantana @ymcui

**Comment by nouiz** [comment]
Sometimes pip cache the download. So when you try later to update again it
don't give you the latest version... I think this is what happened here.

Fred
