### ISSUE TITLE
Version branches

### ISSUE THREAD

**Issue by EderSantana** [fchollet/keras#2086]
@fchollet  I'd like to ask for something like what they do over sklearn: a branch with the name of a version is kept for future refere. Check it out:
https://github.com/scikit-learn/scikit-learn

That would be useful for reproducibility as well.

**Comment by nouiz** [comment]
Why a branch and not just a git tag?

**Comment by fchollet** [comment]
Good question. We already have git tags for all previous versions. What
would be the benefits of a branch?

**Comment by EderSantana** [comment]
well, yeah, I guess I can just click through the tags and get to the code online. Did see that before. tkx!

**Comment by glouppe** [comment]
For us the benefits of using branches for releases is to make it easy to backport critical bug fixes to an already released version, without having to sync to master.

**Comment by nouiz** [comment]
You don't need a version branch for that. We just did a 0.8.1 release that
only have a tag. I'm not sure if tag get tested by travis, if not, then a
version branch would be useful.

**Comment by nouiz** [comment]
Replying to myself, a version branch like 0.8.X can be useful to
incrementatally back-port commits. It would also allow user to track it
more easily and update to the branch version more easily.

We are starting to do that for Theano and we should release an 0.8.2
version this week or next week with cudnn v5.
