### ISSUE TITLE
Error with TimeDistributed(Convolution1D())

### ISSUE THREAD

**Issue by ianni67** [fchollet/keras#2090]
Hi,
I'm trying to build a sequence of CNN and LSTM layers for 1D signal (sound) analysis.
In my network I have the following first layer:

``` python
model.add(TimeDistributed(Convolution1D(nb_filter=32, filter_length=3, border_mode='same', activation='relu', subsample_length=1, input_shape=( num_of_blocks, 1, num_hidden_dimensions))))
```

and the net is fed with an input tensor of shape:

``` python
(6, 4, 1024)
```

where 6 is the number of clips (samples), 4 the steps per sample and 1024 the dimension of each step. 
According to the example: https://github.com/jamesmf/mnistCRNN/blob/master/scripts/addMNISTrnn.py 
I pass the input_shape as (steps, channels, num_hidden_dimensions) where the third parameter is the number of elements for each step.
When I compile the model I get the following error message:

```
model.add(TimeDistributed(Convolution1D(nb_filter=32, filter_length=3, border_mode='same', activation='relu', subsample_length=1, input_shape=( 4, 1, num_hidden_dimensions))))
  File "/home/ianni/.local/lib/python2.7/site-packages/keras/layers/convolutional.py", line 104, in __init__
    super(Convolution1D, self).__init__(**kwargs)
  File "/home/ianni/.local/lib/python2.7/site-packages/keras/layers/core.py", line 60, in __init__
    self.set_input_shape((None,) + tuple(kwargs['input_shape']))
  File "/home/ianni/.local/lib/python2.7/site-packages/keras/layers/core.py", line 220, in set_input_shape
    ', was provided with input shape ' + str(input_shape))
Exception: Invalid input shape - Layer expects input ndim=3, was provided with input shape (None, 4, 1, 1024)
```

I cannot figure out how to solve the problem. Any hints?
Thank you very much for your help

---

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
The argument "input_shape" in the 1st layer should be (4, 1024). It doesn't
include the batch dimension.

**Comment by ianni67** [comment]
Thank you **very** much for your fast and kind response.
When I change my code according to your indication:
```python
model.add(TimeDistributed(Convolution1D(nb_filter=32, filter_length=3, border_mode='same', activation='relu', subsample_length=1, input_shape=( 4,  num_hidden_dimensions))))
```



 I get the following error (which indeed puzzles me):
```
   model.add(TimeDistributed(Convolution1D(nb_filter=32, filter_length=3, border_mode='same', activation='relu', subsample_length=1, input_shape=( 4,  num_hidden_dimensions))))
  File "/home/ianni/.local/lib/python2.7/site-packages/keras/layers/containers.py", line 70, in add
    self.layers[-1].set_previous(self.layers[-2])
  File "/home/ianni/.local/lib/python2.7/site-packages/keras/layers/core.py", line 151, in set_previous
    self.build()
  File "/home/ianni/.local/lib/python2.7/site-packages/keras/layers/wrappers.py", line 47, in build
    self.layer.set_input_shape(child_input_shape)
  File "/home/ianni/.local/lib/python2.7/site-packages/keras/layers/core.py", line 220, in set_input_shape
    ', was provided with input shape ' + str(input_shape))
Exception: Invalid input shape - Layer expects input ndim=3, was provided with input shape (None, 1024)
```

**Comment by bruderjakob12** [comment]
I have the same issue. The root of the problem seems to be how the size of the tensor is calculated in line 10
`child_input_shape = (input_shape[0],) + input_shape[2:]`

e.g. for 128 timesteps and 3 dims the input_shape in convolutional.py is (128, 3) where it should be (None, 128, 3). For the time being I helped myself with 
`batch_input_shape=(batch_size, None, timesteps, data_dim)`
which seems to initialize the layer correctly.

**Comment by ianni67** [comment]
@bruderjakob12 thank you very much for your answer and sorry for not reading it. I abandoned keras and went back to torch, so I did not read the thread any more... As you gave a solution, I'll close the issue.

**Comment by ianni67** [comment]
Issue apparently solved by @bruderjakob12
