### ISSUE TITLE
TypeError: fit() got an unexpected keyword argument 'show_accuracy' ---- Graph().fit

### ISSUE THREAD

**Issue by fluency03** [fchollet/keras#2096]
I am training the `Graph` model with using `fit` with parameter `show_accuracy`. However, I got the error: 

    TypeError: fit() got an unexpected keyword argument 'show_accuracy'

When I check the source code on github [here](https://github.com/fchollet/keras/blob/master/keras/models.py#L1319), it shows that `Graph`'s `fit` has `show_accuracy`:

    def fit(self, data, batch_size=128, nb_epoch=100, verbose=1, callbacks=[],
            validation_split=0., validation_data=None, shuffle=True,
            show_accuracy=False,
            class_weight={}, sample_weight={}):

But when I check the release version [0.3.2](https://github.com/fchollet/keras/archive/0.3.2.zip), it is like:

    def fit(self, data, batch_size=128, nb_epoch=100, verbose=1, callbacks=[],
            validation_split=0., validation_data=None, shuffle=True,
            class_weight={}, sample_weight={}):

I am wondering, which one is the newest version? 

I used this `pip install git+git://github.com/fchollet/keras.git` to install Keras. Even this, the `Graph`'s `fit`  I got has no `show_accuracy` parameter.

**Comment by jisungk** [comment]
Hi fluency03,

I checked my version (which was downloaded using the command `pip install git+git://github.com/fchollet/keras.git`) and I see the following code:
```
def fit(self, data, batch_size=128, nb_epoch=100, verbose=1, callbacks=[],
            validation_split=0., validation_data=None, shuffle=True,
            show_accuracy=False,
            class_weight={}, sample_weight={}):

```

Did you previously install Keras using the command, `sudo pip install keras`? 

If so, maybe you should try upgrading your installation with the following command:
`sudo pip install --upgrade git+git://github.com/fchollet/keras.git`

**Comment by fluency03** [comment]
I have done this `sudo pip install git+git://github.com/fchollet/keras.git`. Is it necessary to add `--upgrade`?

**Comment by jisungk** [comment]
If you have any previous installation of Keras, then even if you call `sudo pip install....` will not make any updates. You have to specify that you want to upgrade your existing installation with the `--update` flag.

Hope this helps!

**Comment by fluency03** [comment]
@jisungk It's solved. thanks

**Comment by KingfaLuis** [comment]
model.fit(X_train, Y_train,
          batch_size=128, nb_epoch=4,
          show_accuracy=True, verbose=1,
          validation_data=(X_test, Y_test))

get the error
TypeError                                 Traceback (most recent call last)
<ipython-input-11-621eaf0c4f82> in <module>()
      2           batch_size=128, nb_epoch=4,
      3           show_accuracy=True, verbose=1,
----> 4           validation_data=(X_test, Y_test))

/usr/local/lib/python3.6/dist-packages/keras/models.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    983             epochs = kwargs.pop('nb_epoch')
    984         if kwargs:
--> 985             raise TypeError('Unrecognized keyword arguments: ' + str(kwargs))
    986 
    987         if not self.built:

TypeError: Unrecognized keyword arguments: {'show_accuracy': True}

**Comment by tsinghuazl22** [comment]
what about the error fit_generator() got an unexpected keyword argument 'samples_per_epoch'?My keras version is 2.4.1.
