### ISSUE TITLE
Reshape Order

### ISSUE THREAD

**Issue by flybass** [fchollet/keras#2099]
Hi,

I have a quick question about the reshape module. If possible, could we add the answer to the documentation?

What order is applied in the reshaping module ( C or Fortran )?  

Thank you,
Daniel

**Comment by NasenSpray** [comment]
row-major aka C

**Comment by flybass** [comment]
Great. Thank you for your response.

**Comment by alyato** [comment]
@flybass I want to using the `Reshape`.

> The input: (1,224,224) gray image.
firest layer `:conv2d(32,3,3)`, the output_shape is `(none,32,222,222)`
second `layer:` conv2d(64,5,5),the output_shape is `(none,64,118,118)`

Then  i want to merge`(none,32,222,222)`and  `(none,64,118,118)`

> Then `(none,32,222,222)` Reshape to `(none,(32*222*222)/(118*118),118,118)`

Does it right? Thanks.
