### ISSUE TITLE
Add a data loading example for RNNs

### ISSUE THREAD

**Issue by valexandersaulys** [fchollet/keras#210]
This might not be the place to raise the issue or it might already be raised, in which case I apologize.

Looking at the examples, there is one for a simple RNN. Looking at the documentation, it says the RNN is looking to accept a 3d tensor of (nb_samples, timesteps, input_dim). Is there an example of how to load data into this to fit it?

Specifically, I am looking to process signals. I have a collection of them and they all go on for X time steps and are only 1 signal. Does that make the input_dim just 1 & the timesteps X?

Thanks in Advance

**Comment by floydsoft** [comment]
```Python```
samples = [[[1], [0], [1]], [[1], [1], [0]]]
```

Above example suppose you have two samples with three timesteps, and your feature space in each timestep is one. It forms a tensor.

**Comment by fchollet** [comment]
Here's what you would do as input to a LSTM:
```python
import numpy as np
# 2 samples with 3 timesteps and 1 dimension
samples = [[[1], [0], [1]], [[1], [1], [0]]]
X = np.array(samples)
print X.shape

# alternatively
samples = [[1, 0, 1], [1, 1, 0]]
X = np.array(samples)
X = np.reshape(X, (len(samples), 3, 1))
print X.shape
```
