### ISSUE TITLE
Feeding LSTM embeddings from one task to train another LSTM

### ISSUE THREAD

**Issue by ngopee** [fchollet/keras#2103]
Hello,

The title might sound a bit confusing but I am trying to do some form of deep learning with LSTM. So, I am first training an LSTM to predict Part of Speech(POS) and I want to take the embeddings produce by training this POS LSTM layer and feed it to another LSTM to do some other form of tagging. I would like to know how I should proceed with feeding the embeddings from the POS LSTM later to the other tagging LSTM layer.

PS. What I want to achieve by doing so is when I train the POS layer, the output embeddings will have the POS features encoded which would be useful for my other tagging tasks.

Thanks!

@fchollet @farizrahman4u @EderSantana @ymcui

**Comment by ymcui** [comment]
There is a method called `get_weights()`, which can output the weights of a specific `layer` (for `Sequential` model) or `node` (for `Graph` model).
For e.g., in `Sequential` model
if the `Embedding` is placed first in your model, you can just call
`W=your_model_name.layers[0].get_weights()`
the index in `layers` indicate the specific layer you desired to output.
and you can save this Numpy array `W` into file or somewhere else.
If you want to reuse this weights in other models, simply load these weights (don't forget to transform into Numpy array) into `Embedding` layer, with param `weights=your_loaded_weights_in_numpy`(sometimes if you don't want these weights changed during training, also set `trainable=False`).

Hope this works.

**Comment by ngopee** [comment]
@ymcui 
Epic! Thank you very much for your prompt reply. I'll try this and get back to you.

**Comment by ngopee** [comment]
@ymcui
Okay, I tried it and get the data but I'm not able to make too much sense of the dimension. So, here is the issue:

Here are my parameter:

```
vocab_dim = 10   #(size of embeddings)
maxlen = 17   #(number of words in a sentence)
batch_size = 32
nb_epoch = 1
nb_classes =4
num_hidden_nodes = 10

```

So my input has dimension (128, 17, 10) -- 128 sentences of 17 words each and with embeddings of size 10.

Now here is my code:

```
model = Sequential()
model.add(LSTM(num_hidden_nodes , return_sequences=True, input_shape=(maxlen, vocab_dim)))
model.add(LSTM(num_hidden_nodes , return_sequences=True))
model.add(TimeDistributedDense(output_dim = 4,input_dim= num_hidden_nodes , activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', class_mode="categorical")

weights = model.layers[1].get_weights()
```
I was to get the weights of the second LSTM later. the Sequential layer does not count so that's why the layer index is 1.

So, I'm was expecting the dimension of my weights to be (128, 17, 10) but have dimension (12, 10, 10). I can't make much sense out of it. Your insight would greatly help.

Thanks!

**Comment by Imorton-zd** [comment]
@ngopee The index of first LSTM layer is 0, so the index of second LSTM layer is 1. In my opinion, I don't know why the "12" appears in the dimension of weights, but the first "10" is the size of embeddings and the second "10" is num_hidden_nodes because of the dimension of LSTM output.

**Comment by ngopee** [comment]
@Imorton-zd @ymcui @fchollet @farizrahman4u 

Thank you for your reply. I want the hidden nodes to be representative of the size of the embeddings rather than the words. I wondering what I'm doing wrong? For instance, if I have an embedding of size 10, I want each number in the word-vector to be fed to a given number of hidden nodes and then this particular architecture is repeated for multiple time-steps. Any insight on what I'm doing wrong? or how this can be done in Keras?
