### ISSUE TITLE
Feedback from callbacks

### ISSUE THREAD

**Issue by tdhd** [fchollet/keras#211]
Hey François,

I think it would be useful to have the callbacks return an optional feedback to the `fit` method. This would be useful to let the callbacks control in certain aspects how `fit` behaves.

For example when thinking of an early stopping callback, it could tell `fit` to stop gracefully by exiting the loop over the epochs. Yesterday I was reading over http://papers.nips.cc/paper/4522-practical-bayesian-optimization-of-machine-learning-algorithms.pdf, where they also let the time to train a model be a factor in their optimization. So being able to stop the training early would have a benefit for hyper parameter optimization.

If you look at my current implementation, it calls `sys.exit` in which case the overall optimization of hyper parameters would only resume when the training has been spawned in a different thread:

```python
class EarlyStop(Callback):
    def __init__(self, nb_epoch_lookback=5, verbose=0):
        super(Callback, self).__init__()

        self.nb_epoch_lookback = nb_epoch_lookback
        self.verbose = verbose
        self.best_val_loss_epoch = 0
        self.best_val_loss = np.Inf

    def on_epoch_end(self, epoch, logs={}):
        '''currently, on_epoch_end receives epoch_logs from keras.models.Sequential.fit
        which does only contain, if at all, the validation loss and validation accuracy'''
        if self.params['do_validation']:
            cur_val_loss = logs.get('val_loss')
            if cur_val_loss < self.best_val_loss:
                self.best_val_loss_epoch = epoch
                self.best_val_loss = cur_val_loss
            elif (epoch - self.best_val_loss_epoch) > self.nb_epoch_lookback:
                if self.verbose > 0:
                    print("EarlyStop: Did not observe an improvement over the last {0} epochs, stopping.".format(self.nb_epoch_lookback))
                import sys
                sys.exit(0)
        else:
            import warnings
            warnings.warn("Can run EarlyStop callback only with validation data, skipping", RuntimeWarning)
```

Using the feedback approach, the hyper parameter optimization could continue, regardless of whether running the training processes in different threads.

Concretely the feedback could be implemented as an aggregate in `CallbackList` where all the logic of feedback aggregation is implemented in `CallbackList` and a single feedback is returned. Alternatively a list of feedbacks could be returned to `fit`.

Let me know what you think about it.

**Comment by tristandeleu** [comment]
The idea behind callbacks was definitely to interact both ways with `fit`. I had this very same example in mind (early stopping).

Besides stopping the training, do you have any other feedback in mind? One way to stop the training would be to catch an exception inside the loop, and raise this exception in the callback.

**Comment by fchollet** [comment]
Being able to interact with models both ways will definitely be required when building a GUI for monitoring experiments. 

I guess one way to do it, is to have callback methods return a list of pre-defined commands, and have the .fit() method (and potentially other methods, such as train) take action based on the commands returned.

**Comment by tdhd** [comment]
No, early stopping is the only idea I had in mind. Using the feeback for the GUI is of course another good use.

When I have the time I can prepare a PR with a simple list based feedback and work our way from there.

**Comment by jramapuram** [comment]
I like @tristandeleu 's idea instead of the 
```python 
sys.exit(0) 
``` 
since we can still save weights/do predictions, etc.
But yes, +1 for early stopping.

**Comment by jramapuram** [comment]
So I needed this now and made both @tdhd 's & @tristandeleu's changes: https://github.com/fchollet/keras/pull/213

**Comment by tdhd** [comment]
Closing this, discussion in #219
