### ISSUE TITLE
Using Graph network

### ISSUE THREAD

**Issue by ducminhnguyen** [fchollet/keras#2112]
Can I implement a graph network that looks like this
![rgdb-net](https://cloud.githubusercontent.com/assets/5888561/14101542/65c616ee-f5bf-11e5-901b-635666b45709.png)

I am having problem with how to merge the 2 sub network and add more layer onto the merged result. I want to know how can I implement such network in Keras. 
Thank you

**Comment by ymcui** [comment]
By using `Graph` model, you can achieve that.

**Comment by ducminhnguyen** [comment]
What is the meaning of the output layer in a graph network. As I observe from Keras it is only used as the last layer in the network. Can there be more layer after the output layer spawn from model.add_output()

**Comment by EderSantana** [comment]
In Keras you can create two separate models and merge them with merge. Se here for example:
https://github.com/fchollet/keras/blob/master/examples/babi_rnn.py#L180-L196

Just create two convnets, merge them and follow up with as many layers as you need. Later you just pass you two inputs in a list to the trainer.
