### ISSUE TITLE
Building LSTM networks

### ISSUE THREAD

**Issue by ashwin123** [fchollet/keras#2114]
When we run
```
model = Sequential()
model.add(LSTM(5))
```
Does this generate 5 LSTM cells chained to each other (such that each cell emits one output) or a single LSTM cell emitting 5 outputs?

**Comment by fluency03** [comment]
I think it is a LSTM layer with 5 cells.

**Comment by ymcui** [comment]
by default, the LSTM will return the final state, not every timesteps
so in your code, it will return a 2D tensor of shape (batch_size, 5)
if you want to return each timesteps, you should specify in LSTM `return_sequences=True`.

**Comment by ashwin123** [comment]
okay, thank you
