### ISSUE TITLE
Implement the clipped ReLU activation function

### ISSUE THREAD

**Issue by bryandeng** [fchollet/keras#2119]
This activation function is introduced in

Hannun, Awni, et al. "Deep speech: Scaling up end-to-end speech recognition." *arXiv preprint arXiv:1412.5567* (2014).

**Comment by bryandeng** [comment]
One can just use `max_value` to do the clipping.

Closing.

**Comment by harikrishnavydana** [comment]
@fchollet can u mention its usage clipped relu n this format 
 x = Dense(64, activation='relu')(inputs)
@bryandeng

**Comment by HongyeYang** [comment]
This is what I did using Lambda layer to implement clip relu:
Step 1: define a function to do reluclip:
def reluclip(x, max_value = 20):
    return K.relu(x, max_value = max_value)

Step 2: add Lambda Layer into model:
y = Lambda(function = reluclip)(y)
