### ISSUE TITLE
Support low-precision floats

### ISSUE THREAD

**Issue by carlthome** [fchollet/keras#2122]
With Theano's new GPU backend for multiple graphics cards, [libgpuarray](https://github.com/Theano/libgpuarray), they also added [Float16 support](https://github.com/Theano/Theano/issues/2908), which [has been shown to work just as well as 32-bit floats](http://arxiv.org/pdf/1412.7024.pdf) but at lower memory cost. It would be great if Keras could support this. I think it would mostly be a matter of adding `float16` [here](https://github.com/fchollet/keras/blob/master/keras/backend/__init__.py#L21) and [here](https://github.com/fchollet/keras/blob/3bfe4eace955f8b6b46b389f37375b9cc4ae94a0/keras/backend/common.py#L23).

**Comment by carlthome** [comment]
Also, @fchollet, I could take it upon myself to add this in and do a pull-request if you'd like. I guess one worry could be that this would not be backend-agnostic and would only work with Theano though.

**Comment by nouiz** [comment]
I don't know enough keras, but if keras use the floatX parameter, then it
could work automatically without introducing code dependend of float16 if
there isn't rouding of constant to 0 in float16 and other corner case like
that.

**Comment by carlthome** [comment]
Yes, Float16 seems to work fine by just adjusting Keras' error handling and setting `"floatx"` to `"float16"` in `~/.keras/keras.json`. https://github.com/fchollet/keras/pull/2123

**Comment by ddofer** [comment]
When I tried that, it gave errors relating to "mix of float16" and "float32". (Using 1D convolutions and FC layers).  - So - not supported I think?

**Comment by carlthome** [comment]
Could you share your code or an example to reproduce the error? Are you sure the dtype of your data is 16-bit?
