### ISSUE TITLE
ImageDataGenerator for testing

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#2126]
Hi,
I've trained a CNN, and now I would like to test it on big images. So for each pixel of the test image, I need to cut a neighborhood window / patch of size NxN.

Is that possible to use ImageDataGenerator (or an other function) to generate such batches of window/patches, and then use them into mymodel.predict_proba()?
Because I've seen example of ImageDataGenerator for training NNs, but it's not what I would need.

Thanks for your help.

**Comment by EderSantana** [comment]
try `model.evaluate_generator`

**Comment by FiReTiTi** [comment]
Thanks!
Is there a way to know the central (or corners, etc.) coordinates of each image/patch generated in order to reconstruct the probability map associated with the test?
