### ISSUE TITLE
What is the parameter timesteps in Recurrent?

### ISSUE THREAD

**Issue by narrowview** [fchollet/keras#2129]
I don't understand what is timesteps in Recurrent.
In my opinion,I have a dateset like this [x1,x2,x3] [x4,x5,x6] [x7,x8,x9],each of xi is n dimension vector.
When I train the rnn,I take the first group[x1,x2,x3] as input, one by one,and get one output y1.
It is the same way in group[x4,x5,x6] and group[x7,x8,x9].
The group size is timesteps.
Is it my opinion is right?
Could give me some literature about this?
Thanks.

**Comment by keunwoochoi** [comment]
Sorry, I don't understand what you're saying exactly. 
In general, `timesteps` is the number of time step, i.e. length of sentence, number of samples of time-series, length of sequences you're going to use.

**Comment by narrowview** [comment]
Sorry,my English is not very well.
Does you mean that there are many sequences in training set?  Each sequences have a timestep?
For every x in sequences,there is a y for it?

**Comment by keunwoochoi** [comment]
Yes, there are many sequences in training set. Let's say we have two sequence for training. e.g. `[[1,1], [2,2], [3,3], [4,4]]` and `[[0,0],[0,0],[1,1],[2,2]]`. Here, `timesteps` == 4 and `data_dim` == 2 and you can set these when you create any kinds of RNN layer, e.g. 

```
timesteps = 4
data_dim=2
model.add(LSTM(32, input_shape=(timesteps, data_dim))
```

 (32 is the number of hidden units)).

**Comment by narrowview** [comment]
Thanks
