### ISSUE TITLE
ImageDataGenerator numpy TypeError

### ISSUE THREAD

**Issue by cmishra** [fchollet/keras#2131]
I'm trying to use ImageDataGenerator to preprocess the MNIST dataset. It's unsuccessful with the error message being:

> Traceback (most recent call last):
>   File "/home/cm5ky/Dropbox/College/4_Fourth_Year/deep learning/MNIST/assess_performance/test.py", line 14, in <module>
>     `generator.fit(all_x_train)`
>   File "/home/cm5ky/anaconda3/lib/python3.5/site-packages/keras/preprocessing/image.py", line 294, in fit
>     `X -= self.mean`
> TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

Changing line 294 in image.py glow `X -=  self.mean` to `X = X - self.mean` resolved my issue. My numpy version is 1.10.4. 

The error can be reproduced with:

```
from keras.datasets import mnist
from keras.preprocessing.image import ImageDataGenerator
(all_x_train, all_y_train), ignore = mnist.load_data()
generator = ImageDataGenerator()
generator.fit(all_x_train)
```

**Comment by nitish11** [comment]
I got the same error.

_# this will do preprocessing and realtime data augmentation
datagen = ImageDataGenerator(
        featurewise_center=True,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=True,  # divide inputs by std of the dataset
        samplewise_std_normalization=True,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False)  # randomly flip images

datagen.fit(X_train)_

I got the error as follows : 

  _File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.2-py2.7.egg/keras/preprocessing/image.py", line 428, in fit
    X -= self.mean
TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'_

**Comment by nitish11** [comment]
@jnphilipp  : Could you please check this issue when _featurewise_std_normalization=True_,

I got similar error as follows.

```
    datagen.fit(X_train)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.2-py2.7.egg/keras/preprocessing/image.py", line 432, in fit
    X /= (self.std + 1e-7)
TypeError: ufunc 'divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'B') according to the casting rule ''same_kind''
n
```

**Comment by barrykui** [comment]
I got the same error.

`TypeError: ufunc 'subtract' output (typecode 'O') could not be coerced to provided output parameter (typecode 'f') according to the casting rule ''same_kind''`

**Comment by lopuhin** [comment]
This error happens when using ``ImageDataGenerator`` that requires fitting on the data before being able to generate examples (for example when you have ``featurewise_center=True``).
So the solution is to call the ``fit`` method on the generator before starting training.

**Comment by burgalon** [comment]
@lopuhin Thank you. This makes it hard to use together with flow_from_directory

**Comment by lopuhin** [comment]
@burgalon yes, I totally agree with that. I ended up using ``flow_from_directory`` on an ``ImageDataGenerator`` without ``featurewise_center`` to load images (or a sample of images if there are too many) from a directory, and then fit another ``ImageDataGenerator`` on that data. There is also an issue with a plan for improvement: https://github.com/fchollet/keras/issues/3338#issuecomment-237252884

**Comment by burgalon** [comment]
on a somewhat similar note, I'm wondering how is it possible to connect Tensorflow pipeline into a Keras Model() - 
http://stackoverflow.com/questions/40767222/add-tf-image-decode-jpeg-to-keras-created-graph
