### ISSUE TITLE
Passing input to LSTM layer in a network twice

### ISSUE THREAD

**Issue by rajendramishra18** [fchollet/keras#2142]
I am recently working on a problem where I have LSTM layer in network. After LSTM, DNN layer is placed. I want to pass the input twice through the LSTM layer, once just to generate prior without any output. During second pass of the same input to LSTM, now LSTM shall generate the output sequence. This output after two passes over same LSTM, will be sent to the DNN layer. As keras provides so much less flexibility in sequential model and LSTM, I am not getting how can I handle this situation.

Thanks

**Comment by jrieke** [comment]
Make your LSTM layers stateful (`stateful=True`). Then, pass your data through the network twice (e. g. with `model.train_on_batch(...)`; the LSTM layers will keep their memory in between) and use only the output of the second pass. Before you feed in the next input, run `model.reset_states()` to reset the memory of the LSTM layers. 
More on statefulness [here](https://github.com/fchollet/keras/blob/master/examples/stateful_lstm.py), [here](http://keras.io/faq/#how-can-i-use-stateful-rnns) and in #98 (I recommend scanning through that issue as the official docs are rather imprecise).

**Comment by jrieke** [comment]
Just came to my mind: During training, you should use `model.predict_on_batch(...)` for the first pass and `model.train_on_batch(...)` only for the second pass. This way, the first pass initializes your LSTM memory without changing the weights/biases of the network.

**Comment by rajendramishra18** [comment]
Thanks @jrieke  ... I will try both these approaches and will get back to you ..

**Comment by rajendramishra18** [comment]
@jrieke  the problem that I have with this approach is .. I have DNN layer at the end of LSTM. During the first pass of input I want the LSTM layer to just maintain the memory. No training. So the weights during first pass shall not change. When the second pass is made now the output of LSTM layer shall be propagated to DNN and backpropagation  is carried out.

Thanks

**Comment by jrieke** [comment]
@rajendramishra18 If you use `predict_on_batch` for the first pass, it doesn't change the weights (i.e. it doesn't train the network, but initializes the LSTM state in just the same way as the `train_on_batch` method does).

**Comment by rajendramishra18** [comment]
@jrieke  OK thanks I got it ... it will work .. Thanks
