### ISSUE TITLE
convolution2d support operation between channels(feature maps)? 

### ISSUE THREAD

**Issue by liyi193328** [fchollet/keras#2146]
Hi,
   I already know convolution 2d in keras can support map a n*m matrix multiple feature maps according to nb_filter and filter, but it can support the situation like the following:
![image](https://cloud.githubusercontent.com/assets/6782974/14177589/925e17f8-f789-11e5-9368-06a213612498.png)

That means, a value of a feature map after convolution can be computed by different input feature map. Is there a way to achieve it? Thanks very much!

**Comment by liyi193328** [comment]
can someone have ideas? Thanks

**Comment by EderSantana** [comment]
that figure describes a regular keras convolutional2d layer followed by "relu" activation.

**Comment by liyi193328** [comment]
@EderSantana thanks, I 'll see the document more carefully.

**Comment by EderSantana** [comment]
is this issue solved? please, close it if it is :D
