### ISSUE TITLE
MaxoutDense doesn't work

### ISSUE THREAD

**Issue by dblN** [fchollet/keras#2149]
```python:
model = Sequential()
model.add(MaxoutDense(output_dim=16, nb_feature=4, input_dim=8))
model.add(Dense(1, activation="sigmoid"))
model.compile(optimizer="sgd", loss="binary_crossentropy")

==> ValueError: Shape (4, 8, 16) must have rank 2
```

MaxoutDense calculates the output as below. `X` is 2D and `self.W` is 3D, but `K.dot` takes two 2D inputs. Hence, it raises the error like above.

```python:
output = K.max(K.dot(X, self.W) + self.b, axis=1)
```

I think it should be fixed like below.

```python:
splited_W = [self.W[i, :, :] for i in range(self.nb_feature)]
splited_z = [K.dot(X, W) for W in splited_W]
z = K.concatenate([K.expand_dims(_z) for _z in splited_z])
output = K.max(z, -1)
```

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by the-moliver** [comment]
I cannot reproduce the error. Tried this model on the mnist_mlp example and it worked fine:
```python
model = Sequential()
model.add(MaxoutDense(output_dim=512, nb_feature=4, input_dim=784))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(MaxoutDense(10))
model.add(Activation('softmax'))
```
Also loops, as in your proposed solution, should be avoided whenever possible. If you can provide a more complete demonstration (as in everything needed to reproduce) of things breaking I'll try it out.

**Comment by dblN** [comment]
@the-moliver 
Thanks. Do you use theano as backend? Using it, as you said it didn't raise error. I get error when with tensorflow.

**Comment by the-moliver** [comment]
Ah yes this is indeed an issue!

**Comment by dblN** [comment]
The main cause of this issue is not `MaxoutDense`, so I'll close this. Thank you.
