### ISSUE TITLE
bidirectional rnn

### ISSUE THREAD

**Issue by hycis** [fchollet/keras#215]
does keras support bidirectional rnn?

**Comment by fchollet** [comment]
Not out of the box, but it would be very easy to extend, for instance, the SimpleDeepRNN layer to look into the future as well as into the past. 

No available recurrent layer is bidirectional. But building a bidirectional recurrent layer would take a few minutes, if that's something you are interested in. Keras is meant to be extensible, take advantage of it! :)

**Comment by jramapuram** [comment]
I believe the issue with this is how the model sees data (i.e. one sees X, the other sees X[::-1] for the simple 1D case). It would more sense to pass this into two separate RNNs for example, train them and merge. But yes, should be easy :)

**Comment by hycis** [comment]
For the simple rnn layer, it seems like it only fixed length sequences? for sequences with shorter length, it just append 0?

**Comment by jramapuram** [comment]
RNNs are implemented as single layer models. You can use the Flatten layer and accept your 2d sequences.

**Comment by hycis** [comment]
@jramapuram Thanks for the quick reply. I am not sure how to apply Flatten, but I have a dataset shape of (10000,  10,  300) where there are 10000 groups, each group has 10 sequences, and each sequence has dimension of 300. Then I tried 

model = Sequential()
model.add(Dense(300, 256))
model.add(LSTM(256, 128))
model.add(Dense(128,1))
model.add(Activation('sigmoid'))

But I get error ValueError: new_order[2] is 2, but the input only has 2 axes. Do you know how to fix it? Thanks.

**Comment by fchollet** [comment]
@hycis the input to the LSTM layer should a 3D tensor. The output of a Dense layer is a 2D tensor, so you won't be able to stack a LSTM after a Dense layer without applying a Reshape.

If your input is already 3D (10000, 10, 300), then simply removing the first Dense layer will work.

> Also, is there a way to feed the model with sequences of variable length, currently from the lstm example, the sequences are padded with zeros to make them of similar length and then you use a word embedding to convert the zeros to an embedding vector. Which means the zeros is actually represented as some word vector. I will prefer that the model takes whatever the sequence as it is, and not append additional vectors, I believe the result will be different with and without appending.

Not yet. Agreed that we would need a mask system.

**Comment by hycis** [comment]
Thanks, I have a created a bidirectional LSTM with mlp layers for anyone who might be interested to use
https://github.com/hycis/bidirectional_RNN.git
I will close the issue.
