### ISSUE TITLE
Model Zoo to Keras: Additional Functionality for Using Subset of Layers?

### ISSUE THREAD

**Issue by davisliang** [fchollet/keras#2154]
Using a pre-trained VGG-16 model with Keras is quite easy: https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3

However, using a subset of the weights in Keras seems to be nontrivial. For example, I want to only load the weights for the convolutional layers and let the fully connected layers initialize randomly. This would allow me to use images that aren't resized to 224x224 (otherwise we get a dimension mismatch with the pre-trained fully connected layers). I've tried several things including editing the hdf5 file itself but that's proven to be quite complicated too... Is there any easy way to do this that is either already built into Keras or is being worked on? Thanks!

**Comment by tboquet** [comment]
You could take a look [here](http://blog.keras.io/how-convolutional-neural-networks-see-the-world.html) and in #1728.

**Comment by davisliang** [comment]
@tboquet Thank you!
