### ISSUE TITLE
training Graph model with many input nodes of single value

### ISSUE THREAD

**Issue by zhangchengcsb** [fchollet/keras#2157]
Hi all,  I'm trying to build a model like this:
![keras_model_gates_over_input](https://cloud.githubusercontent.com/assets/7233438/14197229/a0d69e88-f791-11e5-8ca0-a3290a54a973.png)

the nodes i1, i2, i3 are 3 input values, i.e. my input has shape (nsamples, 3). I hope to train the neurons in the "gates" layer to be "AND" or "OR" logic gates. The following dense layer takes 2 input values and make a binary classification.

I tried to implement the model as follows:

```
from keras.objectives import *
from keras.models import Graph
from keras.layers.core import Dense
from keras.utils.visualize_util import plot as kerasplot
import numpy as np

m=Graph() 
m.add_input('i1', input_shape=(1,))
m.add_input('i2', input_shape=(1,)) 
m.add_input('i3', input_shape=(1,))
m.add_node(Dense(1, init='he_normal', activation='relu'), name='l1n1', inputs=['i1', 'i2'],  merge_mode='concat')
m.add_node(Dense(1, init='he_normal', activation='relu'), name='l1n2', inputs=['i2', 'i3'],  merge_mode='concat')
m.add_node(Dense(2, init='he_normal', activation='softmax'), name='o1', inputs=['l1n1', 'l1n2'], merge_mode='concat', create_output=True)
kerasplot(m, to_file='m.png', show_shape=True, recursive=True)
m.compile(optimizer='rmsprop', loss={"o1":'categorical_crossentropy'})

x=np.asarray(
            [[0,0,0],
             [1,0,0],
             [1,1,0],
             [1,1,1],
             [1,0,1],
             [0,1,0],
             [0,1,1],
             [0,0,1]
            ],
            dtype=float)
y=np.asarray(
            [[0,1],
             [0,1],
             [1,0],
             [1,0],
             [0,1],
             [0,1],
             [0,1],
             [0,1]
             ])

m.fit({"i1":x[:,0, np.newaxis], "i2":x[:,1, np.newaxis], "i3":x[:,2, np.newaxis], "o1":y}, nb_epoch=10)
```

The plot of my model looks like:
![m](https://cloud.githubusercontent.com/assets/7233438/14209174/75633fde-f7e8-11e5-8ce3-3e84d6e23c61.png)

My questions are:
1. Is this the correct implementation of the model I wanted? 
2. Is there a more efficient implementation? I plan to use input vectors with thousands of values ( for example, (nsample, 2000) ) and thousands of gates, is this going to be a problem in performance since I have one input node for each value in an input vector, and one node for each logic gate?

Thanks a lot in advance.

**Comment by gw0** [comment]
1. Yes, but you probably want `binary_crossentropy`.
2. Not yet, a custom layer will need to be implemented. Maybe something like https://github.com/fchollet/keras/issues/2200 is what you could use.
