### ISSUE TITLE
Is it possible to define order in Reshape layer?

### ISSUE THREAD

**Issue by sunshineatnoon** [fchollet/keras#2167]
I have 1024 7*7 convolutional feature maps and I want to reshape them to a 49*1024 tensor. While reshaping, I want to put features from the same image patch into a row, that means I want to keep the 0th dimension untouched while flatten the 1st and 2nd dimension. I don't see any parameters in Reshape layer to do this, do I need to implement my own Reshape layer? Thanks!

**Comment by NasenSpray** [comment]
`Permute((2,3,1))` followed by `Reshape((49, 1024))` should do the trick.
