### ISSUE TITLE
Image Caption

### ISSUE THREAD

**Issue by suraj-deshmukh** [fchollet/keras#2180]
I want some clarification on Image Captioning problem example.
1) What is partial caption?
    Is it one hot encoding of text data with sequence padding of fixed length
2) What is next words?
    I am unable to understand it from comments
3) and for test image do we need partial captions and if yes then how to generate partial captions for test images.
If anybody has working model of same with flickr8k dataset then please guide me.
I am planing to use flickr8k dataset.
Thanks In advance

**Comment by fchollet** [comment]
> What is partial caption?

The model will generate the output captions one word at a time (by predicting the next word based on the previous words and the current image). So, a "partial caption" means "words `0` to `n` in a caption", and the corresponding target of the model will be word `n+1`.

> What is next words?

Word n+1, as described above.

Basically:

step 1: input = image vector + encoded sentence "picture", target = "of"
step 2: input = image vector + encoded sentence "picture of", target = "a"
step 3: input = image vector + encoded sentence "picture of a", target = "boy"
step 4: input = image vector + encoded sentence  "picture of a boy", target = "picking"
step 5: input = image vector + encoded sentence "picture of a boy picking", target = "apples"

etc.

**Comment by suraj-deshmukh** [comment]
thank you

**Comment by indra215** [comment]
@suraj-deshmukh  Sorry I couldn't understand on how to give the input to the model yet. Could you please help me in how to give the input for the training as well as testing for generating new captions.

**Comment by JiteshPshah** [comment]
How to get a full caption ?
