### ISSUE TITLE
Locally-connected layer with unshared weights

### ISSUE THREAD

**Issue by dvigneshwer** [fchollet/keras#2184]
I could not find an implementation of convolutional layer with different weights for each pixel in keras.Is there any current available implementation in keras.

**Ref implementation:**
- https://code.google.com/p/cuda-convnet/wiki/LayerParams#Locally-connected_layer_with_unshared_weights
- https://github.com/lisa-lab/pylearn2/blob/d43d015d11747bdbd49737ce1163b9af67eac840/pylearn2/packaged_dependencies/theano_linear/unshared_conv/localdot.py

**Comment by dvigneshwer** [comment]
Has any one tried to implement locally connected layer in keras?

**Comment by joelthchao** [comment]
It's in PR #2658.
