### ISSUE TITLE
predict_generator doesn't exist

### ISSUE THREAD

**Issue by the-moliver** [fchollet/keras#2191]
Given that evaluate_generator exists, it seems we should be able to get the model outputs when using a generator with a method like ```predict_generator```. I'll tackle this tomorrow unless someone gets to it first. I don't think it will be too hard and would be extremely useful.

**Comment by fchollet** [comment]
Yes, agreed, it seems logical to have it and it would be useful.

**Comment by ericvrp** [comment]
I have the feeling predict_generator gives an output out of order. If I understand correctly then both of the following branches should be equal.

```
if False:
    predictions = model.predict_generator(augment.testDataGenerator.flow(X_test, batch_size=batch_size), len(X_test))
else:
    predictions = []
    for i in xrange(len(X_test)):
        prediction = model.predict_generator(augment.testDataGenerator.flow(X_test[i:i+1], batch_size=1), 1)
        predictions.append(prediction)
```
