### ISSUE TITLE
Significant performance drop on LSTM examples (e.g. imdb_bidirectional_lstm.py) after PR #1811

### ISSUE THREAD

**Issue by bayesrule** [fchollet/keras#2199]
@fchollet 
**Really** hope you can take this seriously. I read your previous responses very carefully. I also understand your explanations and suggestions. However, after I did some experiments today (since I have to use keras recently for an important paper) I think I should report this issue again.

I tried both the latest 0.3.3 keras (since keras-1 is not yet completed) and the pre-PR (#1811) version. Running the same **imdb_bidirectional_lstm.py** example,

it turns out that the performance does decrease quite a lot on my GTX 970M GPU with CUDA 7.5 and Theano 0.8.1.

0.3.3         --> 299s per epoch
pre-PR     --> 116s per epoch

Many many thanks! #1811 #2088

**Comment by fchollet** [comment]
In Keras 1.0 you can choose between the old implementation and the new implementation (which is faster on most configurations and problems, including on GPU), via the keyword argument `consume_less='cpu'`/`consume_less='mem'`. So you could just start using Keras 1.0 (`keras-1` branch).
