### ISSUE TITLE
Place documentation for objects in docstrings in source code

### ISSUE THREAD

**Issue by phreeza** [fchollet/keras#220]
It seems more natural to put the documentation for Layers, Optimizers, etc directly in the docstring when writing the code. This could be achieved with the autodoc extension for mkdocs:

https://github.com/erichulser/mkdocs_autodoc

**Comment by fchollet** [comment]
I agree on principle, but it would make managing the documentation somewhat more difficult vs. having it all in one place. I'll think about it...

**Comment by phreeza** [comment]
I think it would actually make it easier, above all keeping the api documentation in sync with the actual implementation. As it is, I think it is quite easy for some change to slip through the cracks, which might lead to confusion for the users. Another advantage is that docstrings are discoverable for IDEs and ipython.

Implementation notes in idiomatic python belong in line comments, I believe. (cf PEP-257)

**Comment by phreeza** [comment]
Since documentation seems to be coming up frequently in the issues lately, maybe this would be worth thinking about, @fchollet ? If you think it is a path you want to take, let me know and I will start a branch for the transistion.
