### ISSUE TITLE
求助，model.compile()运行出错

### ISSUE THREAD

**Issue by yw411** [fchollet/keras#2203]
错误是：Exception: ('The following error happened while compiling the node', mrg_uniform{TensorType(float32, vector),inplace}(<TensorType(int32, matrix)>, TensorConstant{(1,) of 20000}), '\n', "Compilation failed (return status=1): C:\\Users\\Administrator\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-x86_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.11-32\\tmpc2_g4d\\mod.cpp: In member function 'int {anonymous}::__struct_compiled_op_cc0dd545794361d9189316f02351d57b::run()':\r. C:\\Users\\Administrator\\AppData\\Local\\Theano\\compiledir_Windows-7-6.1.7601-SP1-x86_Family_6_Model_42_Stepping_7_GenuineIntel-2.7.11-32\\tmpc2_g4d\\mod.cpp:457:34: error: cannot convert 'npy_int64* {aka long long int*}' to 'npy_intp* {aka int*}' in argument passing\r. ", '[*1 -> mrg_uniform{TensorType(float32, vector),inplace}(<TensorType(int32, matrix)>, TensorConstant{(1,) of 20000}), *1::1]')
不知各位大神是否遇到过这种情况，该如何解决呢？

**Comment by EderSantana** [comment]
sounds like a type problem...
do you have your theanorc properly set up?
http://deeplearning.net/software/theano/library/config.html
maybe you want to type cast you data before hand?

internet told me to say:
配置theanorc http://deeplearning.net/software/theano/library/config.html
尝试键入投你的数据。

**Comment by yw411** [comment]
我的theano配置是：
[global] 
openmp=False
floatX=float32
[blas] 
ldflags=
[gcc] 
cxxflags = -IC:\Anaconda2\MinGW\include

**Comment by nouiz** [comment]
We have a pr to fix this in Theano that we just merged. The problem happen
only on 32b computer/OS I think. It doing happen with 64bit os and python
32bit. Update to the dev version of Theano and it should be fixed.

**Comment by yw411** [comment]
@nouiz，sorry,I don’t understand very much.update to dev version of theano?dev version is not the newest version?how can i update?

**Comment by fluency03** [comment]
I think you can do the following for updating. 

    sudo pip install --update git+git://github.com/Theano/Theano.git

**Comment by nouiz** [comment]
I would add this extra parameter --nodeps  or --no-deps. I always forget
the exact syntax.

**Comment by philipperemy** [comment]
```
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
```

**Comment by meanmee** [comment]
wow ，Chinese， So familiar。 world is so small

**Comment by yw411** [comment]
@nouiz @philipperemy  @fluency03 @EderSantana ，thank you so much for your help。I solved the problem today in the way which @nouiz and @philipperemy advised。

**Comment by EderSantana** [comment]
please close the solved ticket! :)

**Comment by ddofer** [comment]
I'm having this exact same issue, with the latest (dev3) Theano and keras. 
Windows 64 bit, Anaconda install, .
(This occurs both with MaxPooling 1D and AveragePooling 1D).
Everything else runs fine.



`e:\anaconda3\lib\site-packages\theano\gof\cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2311             # difficult to read.
   2312             raise Exception('Compilation failed (return status=%s): %s' %
-> 2313                             (status, compile_stderr.replace('\n', '. ')))
   2314         elif config.cmodule.compilation_warning and compile_stderr:
   2315             # Print errors just below the command line.

Exception: ('The following error happened while compiling the node', Pool{ignore_border=True, mode='average_exc_pad', ndim=2}(Elemwise{Composite{(i0 * ((i1 + i2) + Abs((i1 + i2))))}}[(0, 1)].0, TensorConstant{[2 1]}, TensorConstant{[2 1]}, TensorConstant{(2,) of 0}), '\n', "Compilation failed (return status=1): C:\\Users\\User\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-3.4.5-64\\tmpoqjlgbgr\\mod.cpp: In member function 'int {anonymous}::__struct_compiled_op_m9ff93c4fc5b52f206f634ffe39cbbbe4::run()':\r. C:\\Users\\User\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-3.4.5-64\\tmpoqjlgbgr\\mod.cpp:694:62: error: cannot convert 'long int*' to 'npy_intp* {aka long long int*}' in argument passing\r.                      z = ((dtype_V1*)(PyArray_GetPtr(V1, o_idx)));\r.                                                               ^\r. C:\\Users\\User\\AppData\\Local\\Theano\\compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_42_Stepping_7_GenuineIntel-3.4.5-64\\tmpoqjlgbgr\\mod.cpp:714:63: error: cannot convert 'long int*' to 'npy_intp* {aka long long int*}' in argument passing\r.                        a = ((dtype_V3*)(PyArray_GetPtr(V3,i_idx)))[0];\r.                                                                ^\r. ", "[Pool{ignore_border=True, mode='average_exc_pad', ndim=2}(<TensorType(float32, (False, False, False, True))>, TensorConstant{[2 1]}, TensorConstant{[2 1]}, TensorConstant{(2,) of 0})]")`
