### ISSUE TITLE
Video Preprocessing

### ISSUE THREAD

**Issue by albertomontesg** [fchollet/keras#2205]
Hi everybody,

I am working trying to solve a challenge for the CVPR and the challenge consist on working with a video dataset. Because I would like to focus using convolution 3D and Keras offers these kind of layer in a very easy way I will be working with this framework and I would like to share my contributions for users in the future if they require.

Some of the ideas I have to implement are:
- Change the image transformation functions to be applied to the last two dimensions (height and width) so if you pass them video arrays, the transformations are still correctly applied.
- Write some util transformations for videos.
- Write a video generator. For this generator I would like to write to be done in parallel, so while the training is being done on the GPU for a batch, the generator is loading the videos i memory and then when needed the next batch only need to access.

For videos, because it is very difficult to have a large video dataset loaded in memory, my approach is pass to the generator, a dataset object which have all the information related to the video, as the identifier, the output that generates, the path to the video file, and then the generator load it from this info when it is required.

I'm open to hear improvements and more ideas for contribute related with this topic. Actually I'm starting to write this feature and I would be very glad to have them here, in this project, for everyone.

**Comment by philipperemy** [comment]
Have a look at this repo:

https://github.com/albertomontesg/keras-model-zoo/tree/master/models/C3D-Sports1M
