### ISSUE TITLE
Until now, the sentences of varying length cannot be processed yet with keras?

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#2206]

**Comment by cmyr** [comment]
Yes they can. Set `mask_zero=True` on your Embedding layer, and use 0 as a padding value on your input.

```python
sentence1 = [1, 2, 3, 4, 5]
sentence2 = [9, 27]

padded_input = [
    [1, 2, 3, 4, 5],
    [0, 0, 0, 9, 27]
    ]
```

**Comment by Imorton-zd** [comment]
@cmyr Thanks for your reply! I mean not padding. Because the length of the documents in  my corpus are different a lot. I have tested many parameters, but cannot ensure the `maxlen` to  achieve the expected accuracy (bag of words model can). Therefore, I want to know if there is a way that can still process the sentence not via padding.

**Comment by cmyr** [comment]
Okay, I'm not aware of a non-padding option.

**Comment by Imorton-zd** [comment]
@cmyr Thank you all the same!

**Comment by braingineer** [comment]
You could always use the stateful RNNs.  I've seen some successful non-keras approaches that cache the hidden state of the RNN and pass it as input whenever it is needed to continue (which is precisely what the stateful RNNs do, I believe). 

But in general, why is maxlen not an option?  How long are your sentences?  I'm training a WSJ language model right now on sentences up to 100 words in length (it's a typical subset of the data---<=40 words, <=100 words, full dataset).

**Comment by Imorton-zd** [comment]
@braingineer Thanks for your reply! The maximum length of one sentence (called document exactly) in my corpus is about 4000, but the minimum length is only about 40. I have tested many parameters, but cannot ensure the `maxlen` to achieve the expected accuracy. However, the representations with bag of words model could achieve the expected performance, which doesn't leave any words. Therefore, I think that setting `maxlen` in two long and short length documents is not a good option.
