### ISSUE TITLE
how to set mask_value for multi-feature data

### ISSUE THREAD

**Issue by qzshadow** [fchollet/keras#2208]
Suppose I have a multi-variable(multi-dimensional) time series data for classification, input_shape = (batch_size, time_steps, data_dim). some of the samples have different time steps, so I need to pad 0s to keep the time steps same to feed them into LSTMs.
I would like to mask these padding zeros so I also use a masking Layer, but I do not understand how to set mask_value for these multi-feature data( data_dim > 1), I try to refer to the source code but it seems theanoish... and these is also little explanation in the docs of how mask Layer works. I have no idea.
should I use 
`model.add(Masking(mask_value = np.zeros((1,data_dim)), input_shape=(max_timesteps,data_dim)))`
or
`model.add(Masking(mask_value = 0., input_shape=(max_timesteps,data_dim))`?
if  I misunderstand the meaning of Masking, please point it out.

**Comment by philipperemy** [comment]
Can you post all your code or fake data along with your model?
That will make things easier for people to help you.

**Comment by qzshadow** [comment]
OK, I dived into the code of Masking Layer, then referred to some theano & numpy documents, finding that both of these two usages are right(and it also be confirmed in my experiment, the outputs are the same). The core reason is numpy's **broadcast** mechanism.
