### ISSUE TITLE
Preserving order - Shuffling in flow of ImageDataGenerator

### ISSUE THREAD

**Issue by norman-si** [fchollet/keras#222]
Why do we shuffle X and Y independently of each other? If Y are labels for the dataset, corresponding in row order, we just destroyed the order by using the shuffle. Shouldn't we preserve order by shuffling the indices of the data?

```python
        if shuffle:
            seed = random.randint(1, 10e6)
            np.random.seed(seed)
            np.random.shuffle(X)
            np.random.seed(seed)
            np.random.shuffle(y)
```

Would something like this work?

```python
        if shuffle:
            seed = random.randint(1, 10e6)
            np.random.seed(seed)
            indices = np.arange(X.shape[0])
            np.random.shuffle(indices)
            X = X[indices]
            y = y[indices]
```

**Comment by fchollet** [comment]
Both methods are essentially equivalent, in that both methods do yield the same order. A deterministically-seeded RNG is deterministic.

**Comment by norman-si** [comment]
Awesome thanks!
