### ISSUE TITLE
Plot epoch every x iterations

### ISSUE THREAD

**Issue by philipperemy** [fchollet/keras#2231]
Anyone knows how to verbose only every x iterations? Thanks!
```
Epoch 219/2000
80/80 [==============================] - 0s - loss: 4.4959 - acc: 0.2500 - val_loss: 5.0550 - val_acc: 0.3750
Epoch 220/2000
80/80 [==============================] - 0s - loss: 4.5746 - acc: 0.2375 - val_loss: 5.0429 - val_acc: 0.3750
```

**Comment by philipperemy** [comment]
I mean except for setting nb_epoch=1 in fit() and wrap that in a loop

**Comment by braingineer** [comment]
If I'm not mistaken, you just want a callback, correct?  if 80 batches per epoch, then do "on_batch_begin", have it track the batch_i, and then batch_i % x == 0.

http://keras.io/callbacks/#usage-of-callbacks

**Comment by philipperemy** [comment]
Thanks for the insight. I'll engineer something and I'll post it when I'm done! Might interest other people

**Comment by eduard-netsajev** [comment]
What you actually need is to implement own Callback.

Something like 

`
class PeriodicLogger(Callback):
    def on_train_begin(self, logs={}):
        # Initialization code
        self.epochs = 0

    def on_epoch_end(self, batch, logs={}):
        self.epochs += 1
        if self.epochs % X == 0:
            # Do stuff like printing metrics
`

**Comment by braingineer** [comment]
Sorry if it wasn't clear; that's also what I was recommending.

**Comment by philipperemy** [comment]
No it was all clear! Thanks guys!
