### ISSUE TITLE
How can I get the internal output of left or right model?

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#2232]
```
def train_merge_model(train_q,train_a):

    print('Build model...')
    model0 = Sequential()
    model0.add(LSTM(lstm_output_dims,input_shape=(maxlen,embedding_dims)))
    model0.add(Dropout(0.5))

    model1 = Sequential()
    model1.add(LSTM(lstm_output_dims,input_shape=(maxlen,embedding_dims)))
    model1.add(Dropout(0.5))

    modelmerge = Sequential()
    modelmerge.add(Merge([model0, model1], mode='sum'))
    modelmerge.add(Dropout(0.5))

    modelmerge.add(Dense(1))
    modelmerge.add(Activation('sigmoid')) 
    modelmerge.compile(loss='mse', optimizer='rmsprop')

    hist = modelmerge.fit([train_q,train_a], label, batch_size=batch_size, nb_epoch=10, verbose=1, show_accuracy=True)
    print (hist.history)
```

I want to get the the output of lstm layer in model0. I know how to get the internal output in the simple model without merging, like:

```
get_feature = theano.function([modelmerge.layers[0].input],modelmerge.layers[0].get_output(train=False),
                              allow_input_downcast=False)
feature = get_feature(trains)
```

However, the inputs of my merging model have two styles of input. Please give me some suggestions!

**Comment by mbotumbo** [comment]
I'm not really clear on what you are asking, but is this what you are looking for?
```
model0_lstm_function = theano.function([model0.get_input(train=False)],model0.layers[0].get_output(train=False))
model0_lstm_embedding = model0_lstm_function(np.random.random((128,maxlen, embedding_dims)).astype("float32"))
```

**Comment by Imorton-zd** [comment]
@mbotumbo Thanks for your reply! I am afraid that my description is too vague. In fact, I have trained the merge model via the function `train_merge_model`, which has two branches `model0`, `model1`. And get the best model. then save the best model.
```
def train_merge_model(train_q,train_a):

    print('Build model...')
    model0 = Sequential()
    model0.add(LSTM(lstm_output_dims,input_shape=(maxlen,embedding_dims)))
    model0.add(Dropout(0.5))

    model1 = Sequential()
    model1.add(LSTM(lstm_output_dims,input_shape=(maxlen,embedding_dims)))
    model1.add(Dropout(0.5))

    modelmerge = Sequential()
    modelmerge.add(LambdaMerge([model0, model1], mode='sum'))
    modelmerge.add(Dropout(0.5))

    modelmerge0.add(Dense(1))
    modelmerge0.add(Activation('sigmoid')) 
    modelmerge.compile(loss='mse', optimizer='rmsprop')

    hist = modelmerge.fit([train_q,train_a], label, batch_size=batch_size, nb_epoch=10, verbose=1, show_accuracy=True)
    print (hist.history)
    cPickle.dump(modelmerge0,open("Model\model.pkl","wb")) 

train_merge_model(train_q,train_a)
modelmerge = cPickle.load(open("Model\model.pkl","rb")) 
```
Now, I want to get the output of the left branch in the loaded `modelmerge`. In this merge model, there is not a model0. How can I do?

**Comment by mbotumbo** [comment]
@Imorton-zd ah, ok I see. Well, the short answer, then is that if you have the final modelmerge object, then model0 is:
`modelmerge.layers[0].layers[0]`

That is layers[0] of modelmerge is the Merge([model0, model1]....) layer, which in turn has a .layers of its own, which is the same as the first argument you passed it when creating it. So model0 is at Merge([model0, mode1]...).layers[0]. 

That said, you might want to consider restructuring your code. One thing to consider is to use [model saving](http://keras.io/faq/#how-can-i-save-a-keras-model). Another is to actually return model0, mergemodel from your train_merge_model method. One more is to separate model creation and model training. Keep in mind that a .load_weights() for mergemodel should also populate the weights for model0 without you needing to do anything extra.

**Comment by m274d** [comment]
@mbotumbo Thank you for your kind help! I tried your suggested method to get the intermediate layer output from a merged model and failed.

My model design is almost the same as @Imorton-zd 's, which merges two LSTM together.
the code I use is 
`import theano
get_feature = theano.function([net_comb.get_input(train=False)],net_comb.layers[2].get_output(train=False),
                              allow_input_downcast=False)
feature = get_feature([ input_3D_tra, input_3D_wea])`

and the running result is

`Traceback (most recent call last):
  File "continue_training.py", line 79, in <module>
    allow_input_downcast=False)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 307, in function
    accept_inplace=accept_inplace, name=name)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1759, in orig_function
    inputs = list(map(convert_function_input, inputs))
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1863, in convert_function_input
    (variable, value))
TypeError: The value for input <TensorType(float32, 3D)> should not be a Variable or SymbolicInput instance (got: <TensorType(float32, 3D)>)
`

I do not know why it is illegal to use this kind of input. Could you kindly help me with this problem?

**Comment by mbotumbo** [comment]
@m274d Lucky for you I ran into this one pretty recently. The issue is that .get_input(...) returns a list when there you are using a merge. The theano expect a list as the input when creating a function (which is why you have the [...] as the first argument of theano.function.). However, what it really ends up getting in this case (when you have a merge layer and use [model.get_input(...)] is something like [[input_0, input_1]], which isn't being interpreted correctly by theano.  

The fix is easy. Just remove the brackets from the code you posted. That is what worked for me under similar circumstances with this error.

**Comment by m274d** [comment]
@mbotumbo Thank you for your kind answer! Actually I have tried this method before. However it seems now working for me. Here is my example:

My layer looks like this:
```
--------------------------------------------------------------------------------
Initial input shape: [(None, None, 2), (None, None, 6)]
--------------------------------------------------------------------------------
Layer (name)                  Output Shape                  Param #             
--------------------------------------------------------------------------------
Merge (merge)                 (None, None, 52)              6832                
GRU (gru)                     (None, 32)                    8160                
Dense (dense)                 (None, 20)                    660                 
Dense (dense)                 (None, 8)                     168                 
--------------------------------------------------------------------------------
Total params: 15820
--------------------------------------------------------------------------------
```
first I apply 
```
import theano
get_feature = theano.function(net_comb.get_input(train=False)],net_comb.layers[2].get_output(train=False),allow_input_downcast=False)
feature = get_feature([input_3D_tra, input_3D_wea])
```
input_3D_tra has feature dimension =2, time_stamp = 24 and length = 2
input_3D_wea has feature dimension =6, time_stamp = 24 and length = 2
removing only the brackets at get_feature, the results look like this

```
Traceback (most recent call last):
  File "continue_training.py", line 82, in <module>
    feature = get_feature([input_3D_tra, input_3D_wea])
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 786, in __call__
    allow_downcast=s.allow_downcast)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 150, in filter
    converted_data = theano._asarray(data, self.dtype)
  File "/usr/local/lib/python2.7/dist-packages/theano/misc/safe_asarray.py", line 34, in _asarray
    rval = numpy.asarray(a, dtype=dtype, order=order)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: ('Bad input argument to theano function with name "continue_training.py:81"  at index 0(0-based)', 'could not broadcast input array from shape (2,24,2) into shape (2,24)')
```
I notice that it accepts (2,24), which is not [(None, None, 2), (None, None, 6)].

-----------------------------------------------------------------------------------------------------------------

Then I remove all the brackets

```
import theano
get_feature = theano.function(net_comb.get_input(train=False)],net_comb.layers[2].get_output(train=False),allow_input_downcast=False)
feature = get_feature(input_3D_tra, input_3D_wea)
```

it returns a warning 
```
TypeError: ('Bad input argument to theano function with name "continue_training.py:81"  at index 0(0-based)', 'TensorType(float32, 3D) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function".'
```

But the results is wired. The output from layer[2] should be the first dense layer. If input length =2, it should return (2,20) array. But actually it returns a 3d array (2,24,2)

```
array([[[ 0.80015732,  0.6501751 ],
        [ 0.51629576,  0.52233494],
        [ 0.93145844,  0.64667356],
        [ 0.97819852,  0.52441903],
        [ 0.2520293 ,  0.82481259],
        [ 0.11203669,  0.33217971],
        [ 0.01192562,  0.03782118],
        [ 0.66154183,  0.93990144],
        [ 0.02929218,  0.2568529 ],
        [ 0.76983954,  0.06340482],
        [ 0.79384609,  0.98518246],
        [ 0.79016042,  0.38315709],
        [ 0.88156504,  0.86068901],
        [ 0.38539249,  0.69239963],
        [ 0.80161817,  0.22932781],
        [ 0.46872046,  0.87681631],
        [ 0.5203037 ,  0.99918174],
        [ 0.49846036,  0.03460684],
        [ 0.4608816 ,  0.85825613],
        [ 0.8088823 ,  0.39046288],
        [ 0.79354826,  0.73797197],
        [ 0.17995967,  0.1731891 ],
        [ 0.90153885,  0.08526699],
        [ 0.91843736,  0.81101647]],

       [[ 0.51629576,  0.52233494],
        [ 0.93145844,  0.64667356],
        [ 0.97819852,  0.52441903],
        [ 0.2520293 ,  0.82481259],
        [ 0.11203669,  0.33217971],
        [ 0.01192562,  0.03782118],
        [ 0.66154183,  0.93990144],
        [ 0.02929218,  0.2568529 ],
        [ 0.76983954,  0.06340482],
        [ 0.79384609,  0.98518246],
        [ 0.79016042,  0.38315709],
        [ 0.88156504,  0.86068901],
        [ 0.38539249,  0.69239963],
        [ 0.80161817,  0.22932781],
        [ 0.46872046,  0.87681631],
        [ 0.5203037 ,  0.99918174],
        [ 0.49846036,  0.03460684],
        [ 0.4608816 ,  0.85825613],
        [ 0.8088823 ,  0.39046288],
        [ 0.79354826,  0.73797197],
        [ 0.17995967,  0.1731891 ],
        [ 0.90153885,  0.08526699],
        [ 0.91843736,  0.81101647],
        [ 0.48455888,  0.24200511]]]))
```

I am wondering whether I understand your guidance clearly or I made any mistakes?

**Comment by mbotumbo** [comment]
@m274d I know you used allow_intput_downcast, but that warning is just letting you know that the function is getting a float64 array, but it expects a float32 array. You could avoid that warning by explicitly casting your inputs to float32 with .astype('float32'). 

The only obvious (2,24,2) array I see in what you have described is your input. Are you sure this "output" is actually the output of the function and not part of the error message warning about the array dtype?

**Comment by Imorton-zd** [comment]
@mbotumbo Thanks for your reply! I could get the output of first layer via your method `modelmerge.layers[0].layers[0]`.
```
get_left_first_layer_output = K.function([modelmerge.layers[0].layers[0].input], 
                                  [modelmerge.layers[0].layers[0].get_output(train=False)]) 
```
 but I can't ensure that the output is from `model0` or `model1`. Because I used `modelmerge.layers[1].layers[0]` to expect to get the output of `model1`, it return the error `AttributeError: 'Dropout' object has no attribute 'layers'`. It means that `modelmerge.layers[1].layers[0]` aims to get the output of dropout layer, not `model1`
```
get_right_first_layer_output = K.function([modelmerge.layers[1].layers[0].input], 
                                  [modelmerge.layers[1].layers[0].get_output(train=False)]) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "D:/zhangdong/EMNLP/Denoising_LSTM.py", line 263, in <module>
    get_right_first_layer_output = K.function([modelmerge.layers[1].layers[0].input], 
AttributeError: 'Dropout' object has no attribute 'layers'
```

**Comment by Imorton-zd** [comment]
@m274d How do you show the parameters on console like you posted? Thanks!
```
--------------------------------------------------------------------------------
Initial input shape: [(None, None, 2), (None, None, 6)]
--------------------------------------------------------------------------------
Layer (name)                  Output Shape                  Param #             
--------------------------------------------------------------------------------
Merge (merge)                 (None, None, 52)              6832                
GRU (gru)                     (None, 32)                    8160                
Dense (dense)                 (None, 20)                    660                 
Dense (dense)                 (None, 8)                     168                 
--------------------------------------------------------------------------------
Total params: 15820
--------------------------------------------------------------------------------
```

**Comment by m274d** [comment]
@Imorton-zd You can get the result by doing 
```
pring(model.summary())
```

By the way, could you kindly tell me how do you feed the input data to you layers to get intermediate results? Did you delete the brackets and cast the input? It seems that you did not encounter the problem I and mbotumbo got when feeding in [input1, input2] to the merge layer.

I am sorry for @mbotumbo for I am out so I cannot test your suggestion. I will post my testing results once I get access to my machine.

**Comment by Imorton-zd** [comment]
@m274d Thanks for your reply! In fact, I am not sure for my code.
```
get_left_first_layer_output = K.function([modelmerge.layers[0].layers[0].input], 
                                  [modelmerge.layers[0].layers[0].get_output(train=False)])
layer_output = get_left_first_layer_output([dataq[0]])[0] 
```
I only set the data of left model (`[dataq[0]]`) as input data to get intermediate results.
BTW, do you know how to show the model architecture graph by plot, which always yields errors.

**Comment by mbotumbo** [comment]
@Imorton-zd you've got your list indexes backwards, you want `layers[0].layers[1]`. Please don't be offended by this, but it sounds it might be helpful for you to review some more basic programming guides before you proceed too far with neural network based work.

**Comment by m274d** [comment]
@mbotumbo I really appreciate your help! Now it can generate the correct output as 
```
[[ 0.70639598  0.83154148  1.13575983  1.1247735   1.22542107 -0.16233052
  -2.4022553   1.8384738   1.22195613 -1.25081062 -0.89345479 -2.38926816
  -0.58639354 -0.41196901 -0.00419718  1.15017164 -0.66081542 -1.81838787
   3.28334069  0.82766891]
 [ 0.63114536  0.91458917  1.1166451   1.07084072  1.21291459 -0.04319236
  -2.41196561  1.83151054  1.22122729 -1.2455616  -0.89959782 -2.28953505
  -0.58363152 -0.40064844 -0.01030129  1.26979804 -0.51828861 -1.72511744
   3.35471249  0.82223225]]

```

I think it will help a lot for others who have similar problem. By the way, I agree with you that my problem is mostly caused by my weak basis on python programming. I did not notice that the output was error information but not prediction result. I feel sorry for my carelessness.

-------------------------------------------------
@Imorton-zd Sorry I am not quite clear what you mean by "show the model architecture graph by plot". Could you kindly post your code used to generate what you need?

**Comment by mbotumbo** [comment]
@m274d glad I could help. Yes, having error text and solutions in the same place should help others in the future. 

@Imorton-zd is probably talking about http://keras.io/visualization/ in terms of plotting the graph.

**Comment by walleva** [comment]
@m274d Could you please paste your final correct code? 
Because I also tried to get outputs of the merged two parts. However, when I used the `modelmerge.layers[0].layers[0].get_output(train=False)`, it returned  'AttributeError: 'Sequential' object has no attribute 'get_output''.

I print the type info. and know that `modelmerge.layers[0]` is `Merge `object, `modelmerge.layers[0].layers[0]` is `Sequential` object (i.e. model0).
And my keras version is 1.0.1, is that the reason of the `get_output` error?

**Comment by walleva** [comment]
I modified the `get_output` to `.output` to get the left output, but I don't know whether it's correct or not.
This is the simple code to figure out how to get the left output.
`
from keras.layers.core import Dense
import numpy as np
from construct import euc_dist, euc_dist_shape
from keras.models import Sequential
from keras.engine import Merge
from keras import backend as K

ma = Sequential()
ma.add(Dense(30, input_dim=20))
ma.add(Dense(15))

mb = Sequential()
mb.add(Dense(15,input_dim=50))

modelmerge = Sequential()
modelmerge.add(Merge(layers=[ma,mb], mode=euc_dist, output_shape=euc_dist_shape))

print('Compile')
modelmerge.compile(loss='mae',optimizer='sgd')

nb_train = 20
Xa = np.random.random((nb_train, 20))
Xb = np.random.random((nb_train, 50))
y_train = np.random.uniform(0,0.001, (nb_train, 1))

nb_val = 10
Xa_val = np.random.random((nb_val, 20))
Xb_val = np.random.random((nb_val, 50))
y_val = np.random.uniform(0,0.001, (nb_val, 1))

print('Fit')
his = modelmerge.fit([Xa, Xb], y_train,batch_size=10,nb_epoch=2,
       validation_data=([Xa_val, Xb_val], y_val))
print(his.history)

print('Output...')
get_left = K.function([modelmerge.layers[0].layers[0].input],
                      [modelmerge.layers[0].layers[0].output])
lout = get_left([Xa.astype('float32')])[0]
print lout.shape
print lout`

And here is the output of this test:
`Using Theano backend.
Compile
Fit
Train on 20 samples, validate on 10 samples
Epoch 1/2
20/20 [==============================] - 0s - loss: 7.3952 - val_loss: 3.1794
Epoch 2/2
20/20 [==============================] - 0s - loss: 2.9761 - val_loss: 2.7421
{'loss': [7.395164966583252, 2.9760966300964355], 'val_loss': [3.1794381141662598, 2.7420639991760254]}
Output...
lout.shape: (20, 15)
[[-0.29752189  0.54063684  0.47932231  0.58571303  0.27117354 -0.16635747
   0.03919619  1.17742121 -0.15808856 -0.56467408  0.23523852 -0.04996015
   0.35284364 -0.09786275  0.3975628 ]
 [ 0.11042167  0.20843402 -0.31183773  0.67351294 -0.32845795  0.2223379
  -0.24838641  1.0769012  -0.3211287  -0.31996056 -0.44764751 -0.83010554
  -0.04506258 -0.90259552 -0.74836016]
 [ 0.27247173  0.17563996 -0.05443474  0.57068175  0.03556417  0.10087063
   0.13160269  0.82936627  0.09530564 -0.13461758 -0.2107881  -0.39544177
   0.16184945 -0.67433429 -0.13026895]
 [-0.32218757  0.48334444  0.08250336  0.0357011   0.13456301 -0.18782946
   0.03373951  1.38962734 -0.30731383 -0.59487224  0.06832393 -0.04008519
   0.12443646  0.26369476  0.79869336]
 [-0.25334099  0.13788733 -0.20041949  0.10573965  0.11708385  0.17060541
  -0.23716493  1.10052729 -0.19490673 -0.42897311 -0.00813543  0.21885392
  -0.02576794  0.43328458  0.10510436]
 [ 0.15091003  0.10872449 -0.09467642  0.02185762 -0.42473629  0.29869381
  -0.3736642   0.91815871 -0.46827799 -0.27306017 -0.16498715 -0.41375062
  -0.31937501 -0.24765642  0.09339289]
 [ 0.03709929  0.11616894  0.33721048  0.34559461 -0.21315686 -0.04851351
  -0.50648069  0.89726692 -0.40849242 -0.10610411  0.09356639 -0.78553122
   0.24492511 -0.87928569 -0.60159826]
 [-0.49217701  0.43546161  0.10777767  0.38025489  0.38749775 -0.04911996
   0.30752224  1.40309703 -0.25484943 -0.66342443 -0.07788889 -0.29904953
  -0.07502697 -0.50009125  1.04300618]
 [-0.56780505  0.20509598  0.5991171   0.35829338  0.4908261   0.08374741
  -0.14851446  1.79293871 -0.3142778  -0.67759317  0.63899451 -0.01737495
  -0.11965283  0.10670882  0.78666955]
 [-0.12127011  0.18287171 -0.04841806  0.58530211  0.17800832 -0.14189589
  -0.29665488  0.88892162 -0.20269822 -0.117608   -0.31319582 -0.54862201
  -0.28491315 -0.55421066 -0.59715152]
 [ 0.4322699   0.01429422 -0.3953079   0.17132741 -0.11813643 -0.07074366
  -0.44277447  0.63595659  0.29173085 -0.32130983 -0.38359123 -0.395138
  -0.27407947 -0.41724199  0.0887113 ]
 [-0.03991433  0.224443    0.12940739  0.46133909 -0.02690997  0.0109609
  -0.34815702  0.9559564  -0.08793448 -0.09668098  0.28855959 -0.40301657
  -0.07794558 -0.5062592  -0.14166182]
 [-0.6437161   0.38021091  0.12519673  0.29831496  0.00919813  0.18751262
  -0.20599397  1.01422167 -0.29886875 -0.53375512 -0.13050565 -0.40063182
  -0.05258474 -0.15229879 -0.35667217]
 [ 0.05114115 -0.07481244 -0.14799498  0.35986155  0.39086631 -0.17499039
   0.01655111  0.93136048  0.10974963 -0.59551245 -0.08461879 -0.17574859
  -0.53441381 -0.04518121  0.63598156]
 [-0.17900984  0.00311691  0.08666232  0.10408948 -0.11595063  0.4041948
  -0.10723123  1.25681388 -0.60201609 -0.39172524 -0.30096886 -0.45646989
  -0.40269288 -0.11617351  0.04179386]
 [-0.30496797  0.46950081 -0.33315796  0.48778346  0.0265165  -0.05198411
  -0.61048722  0.88233835  0.19004467 -0.55971795 -0.1686295  -0.21908209
  -0.27611721 -0.14951877  0.18227535]
 [-0.36248177  0.16024785  0.14455163  0.32006842  0.3797324  -0.07864989
   0.38167268  1.3278017  -0.36592484 -0.77254838 -0.01225418 -0.33071771
  -0.0540592   0.01385763  0.69735426]
 [-0.16890599  0.26541033 -0.15517594 -0.0916947  -0.29567039  0.12765598
  -0.88992798  1.35836518  0.04184432 -0.3356151  -0.06074516 -0.5766753
  -0.35017589 -0.6550945   0.02607771]
 [-0.7363888   0.90529042  0.36363772  0.05776925 -0.02633583  0.14764951
   0.22988023  0.90832454 -0.22622816 -0.42634857 -0.06743789  0.19304018
   0.3446869  -0.01430365  0.21656677]
 [-1.00335336  0.31812212 -0.35699698  0.28360671  0.22714682  0.29049462
  -0.06902485  1.43415618 -0.48144135 -0.45620137 -0.6857903  -0.6434229
  -0.41032708 -0.27610201 -0.12651959]]
`

**Comment by Imorton-zd** [comment]
Yeah, it is right. [http://keras.io/getting-started/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer]

**Comment by walleva** [comment]
@Imorton-zd  Thank you for your reply!

**Comment by longma307** [comment]
@walleva Have you checked your lout and rout? I tried your code, something was wired.
The lout[0] is supposed to similar to rout[0], but lout[0] is very same as the lout[1].
Do you have any idea?
