### ISSUE TITLE
Graph Model, add_shared_node() how to deal with various batchsize inputs

### ISSUE THREAD

**Issue by gmyofustc** [fchollet/keras#2233]
I am use Graph Model for my experiment.
Now I have two inputs X1 and X2, they will share the same Convoltion Layer.
X1 has shape(batchsize1, feature_map, row, col)
X2 has shape(batchsize2, feature_map, row, col)
`model.add_shared_node(Convolution2D(feature_map, conv_row, conv_col), name = 'Conv', inputs=[X1, X2], outputs=[Y1, Y2])`
Here, it gives an error,
Expected input with shape**(batchsize1**, feature_map, row, col),
but previous layer has output_shape(**batchsize2**, feature_map, row, col)

How can I deal with various batchsize inputs use add_shared_node()?

**Comment by fchollet** [comment]
The Graph API is getting deprecated. For graphs and shared layers, you should start using the functional API, currently found on branch `keras-1`. It will be released next week.
