### ISSUE TITLE
error when get the layer out of cnn model

### ISSUE THREAD

**Issue by RukinoSaki** [fchollet/keras#2236]
`featuer=K.function([model.layers[0].input],model.layers[21].get_output(train=False))
trainfeature=feature(X_train)`

then, it raised error assert type(inputs) in {list, tuple}  ,AssertionError
My X_train is float32,(380L,1L,160L,160L)

another question:
if i use `featuer=theano.function([model.layers[0].input],model.layers[21].get_output(train=False)),`
it raised error 
`
MemoryError: Error allocating 1189933056 bytes of device memory (out of memory).
Apply node that caused the error: GpuAllocEmpty(Shape_i{0}.0, Shape_i{0}.0, Elemwise{Composite{((i0 + i1) - i2)}}.0, Elemwise{Composite{((i0 + i1) - i2)}}.0)
Toposort index: 55
Inputs types: [TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar)]
Inputs shapes: [(), (), (), ()]
Inputs strides: [(), (), (), ()]
Inputs values: [array(382L, dtype=int64), array(32L, dtype=int64), array(156L, dtype=int64), array(156L, dtype=int64)]
Outputs clients: [[GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})]]`
`Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "C:\Users\Tori\Anaconda2\lib\site-packages\keras\layers\core.py", line 679, in get_output
    X = self.get_input(train)
  File "C:\Users\Tori\Anaconda2\lib\site-packages\keras\layers\core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "C:\Users\Tori\Anaconda2\lib\site-packages\keras\layers\convolutional.py", line 312, in get_output
    X = self.get_input(train)
  File "C:\Users\Tori\Anaconda2\lib\site-packages\keras\layers\core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "C:\Users\Tori\Anaconda2\lib\site-packages\keras\layers\core.py", line 679, in get_output
    X = self.get_input(train)
  File "C:\Users\Tori\Anaconda2\lib\site-packages\keras\layers\core.py", line 175, in get_input
    previous_output = self.previous.get_output(train=train)
  File "C:\Users\Tori\Anaconda2\lib\site-packages\keras\layers\convolutional.py", line 317, in get_output
    filter_shape=self.W_shape)
  File "C:\Users\Tori\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 610, in conv2d
    subsample=strides)`
`HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.`

if you know the problem, plz tell me and thank you very much

**Comment by NasenSpray** [comment]
> `trainfeature=feature(X_train)`
then, it raised error assert type(inputs) in {list, tuple} ,AssertionError
My X_train is float32,(380L,1L,160L,160L)

Input has to wrapped in a list/tuple: `trainfeature=feature([X_train])`

> another question:
if i use `featuer=theano.function([model.layers[0].input],model.layers[21].get_output(train=False)),`
it raised error [...]

You don't have enough memory to process the input. Split it into two or more batches.

**Comment by RukinoSaki** [comment]
That's what I want , thank you very much.
When I saved the model, I used both cPickle and json to save my model.
`cPickle.dump(model,open("model.pkl","wb"))
 model = cPickle.load(open("model.pkl","rb"))`
this showed me high accuracy when predicting, I thought it saved the right model.
But when I used
`json_string = model.to_json()  
 open('my_model_architecture.json','w').write(json_string) 
 origin_model = model_from_json(open('my_model_architecture.json').read()) `
this showed me quite low accuracy when predicting, and I doubted if it saved the model.
I'm not sure if I used if correctly, can you tell me the reason.

**Comment by NasenSpray** [comment]
`model.to_json()` does not store the weights. You can store/load them separately with `model.save_weigths(path)` and `model.load_weigths(path)`

**Comment by RukinoSaki** [comment]
I got it, thanks a lot.
