### ISSUE TITLE
Sequential model compile error

### ISSUE THREAD

**Issue by ghost** [fchollet/keras#2244]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

model.compile(loss='categorical_crossentropy', optimizer='adadelta')

AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?

**Comment by NasenSpray** [comment]
...and? Are you on GPU? If yes, which? Do you have cuDNN? If yes, which version?

**Comment by arieswonder26** [comment]
No I am using personal laptop CPU.

**Comment by kbd2011** [comment]
Same error !!! Pls help !!

**Comment by OuYag** [comment]
Same error!!!Pls help!!! all cnn code arisen this error!!!.....

**Comment by kbd2011** [comment]
I tried using AWS EC2 Spot Instance having GPU , It was working there. I recommend to EC2 instance rather than CPU. It is very faster.
