### ISSUE TITLE
Autoencoder hidden layer dim(input) = dim(output) even if output_reconstruction = False 

### ISSUE THREAD

**Issue by felipemoraes** [fchollet/keras#225]
From documentation:
A customizable autoencoder model. If output_reconstruction = True then dim(input) = dim(output) else dim(output) = dim(hidden).
I did not found how to fix this. Anyone can help?

**Comment by fchollet** [comment]
That's a bug, fixing it now...

**Comment by fchollet** [comment]
You can pull master and reinstall. It is fixed. In test mode (`model.evaluate()`, `model.predict()` / etc), an `AutoEncoder` with `output_reconstruction=False` will return the encoded representation.

**Comment by felipemoraes** [comment]
Thank you! You save my life.

**Comment by fchollet** [comment]
Will close the issue if you confirm everything is working for you (if not, please post details).

**Comment by felipemoraes** [comment]
It's all okay François. You can close now. Again, thank you. I'd like to contribute with keras in the future.

**Comment by fchollet** [comment]
Great, thanks! :)
