### ISSUE TITLE
class_mode deprecated warning from model_from_json

### ISSUE THREAD

**Issue by zhangcx93** [fchollet/keras#2253]
1.dump your model with model.to_json()
2.load your model with model_from_json
3.will show class_mode deprecated warning

problem: when using keras in tornado, any warning will keep the whole process from running, so I have to delete the class_mode from the json to load it properly.

fix:
1.don't dump the class_mode from model.to_json(), i think this is best solution
or 2. don't read class_mode from model_from_json
or 3. don't raise deprecated warning

**Comment by ArdalanM** [comment]
I have similar problem where I try to load a model that was trained on older version of keras (0.3.3).

the error look like this:

Traceback (most recent call last):
  File "/usr/lib/python3.4/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 86, in <module>
  File "<input>", line 40, in load_model
  File "/home/ardalan/env/p3_env/lib/python3.4/site-packages/keras/models.py", line 30, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/home/ardalan/env/p3_env/lib/python3.4/site-packages/keras/utils/layer_utils.py", line 24, in layer_from_config
    class_name = config['class_name']
KeyError: 'class_name'

**Comment by sjhddh** [comment]
same here.
I used my own objective function before, and save the model occasionally.
But when upgrade to keras 1.0.0 , the same problem is aroused.

**Comment by Brabantis** [comment]
@ArdalanM I had the same error, apparently you just have to recompile the models (My issue was #2352) hopefully the weights will stay compatible.

**Comment by sjhddh** [comment]
@Brabantis Yes, maybe you just dont save the model structure into json file, instead, try to build an exact same architecture next time when you want to load the weights. Or, a safer solution is to downgrade your keras into 0.3.3., and then, everything will stay the same as in keras.io.

btw, the newly keras 1.0.1 also have some new changes with save/load functions. Seems like you need to re-compile a model when you load it some time later.

**Comment by Brabantis** [comment]
@sjhddh Yep, I downgraded. I just learned the hard way not to update mid-project the framework everything is based on.
