### ISSUE TITLE
Gradient Noise

### ISSUE THREAD

**Issue by jnphilipp** [fchollet/keras#2255]
Add gradient noise to optimizers based on this paper: http://arxiv.org/abs/1511.06807

**Comment by apacha** [comment]
How about `GaussianNoise`, see https://keras.io/layers/noise/ ? Have you tried that? Seems to me that you have to add a noise-layer instead of changing the optimizer to achieve the effect you desire.

**Comment by cpury** [comment]
@jnphilipp I was also curious to try it out. Here's my implementation. I just tried it and it seems to  improve training as expected:

```python
import keras
from keras import backend as K


class NoisySGD(keras.optimizers.SGD):
    def __init__(self, noise_eta=0.01, noise_gamma=0.55, **kwargs):
        super(NoisySGD, self).__init__(**kwargs)
        with K.name_scope(self.__class__.__name__):
            self.noise_eta = K.variable(noise_eta, name='noise_eta')
            self.noise_gamma = K.variable(noise_gamma, name='noise_gamma')

    def get_gradients(self, loss, params):
        grads = K.gradients(loss, params)

        # Gradient clipping
        if hasattr(self, 'clipnorm') and self.clipnorm > 0:
            norm = K.sqrt(sum([K.sum(K.square(g)) for g in grads]))
            grads = [clip_norm(g, self.clipnorm, norm) for g in grads]
        if hasattr(self, 'clipvalue') and self.clipvalue > 0:
            grads = [K.clip(g, -self.clipvalue, self.clipvalue) for g in grads]

        # Add gradient noise
        t = K.cast(self.iterations, K.dtype(grads[0]))
        variance = self.noise_eta / ((1 + t) ** self.noise_gamma)

        grads = [
            grad + K.random_normal(
                grad.shape,
                mean=0.0,
                stddev=variance,
                dtype=K.dtype(grads[0])
            )
            for grad in grads
        ]

        return grads

    def get_config(self):
        config = {'noise_eta': float(K.get_value(self.noise_eta)),
                  'noise_gamma': float(K.get_value(self.noise_gamma))}
        base_config = super(NoisySGD, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
```

Put this somewhere and use it as your optimizer. If you want to combine it with another optimizer, e.g. Adam, just subclass it and add the gradient noise part to `get_gradients()`

**Comment by edmondja** [comment]
Thanks @cpury but I can't use it, does it work if I do 
    model.compile(loss='mse', optimizer=NoisySGD) ?
And if I want to use Nadam with it I just need to change to 
    class NoisySGD(keras.optimizers.Nadam): ?
To finish, I also wanted to know is there was a way to change the quantity of noise ?

**Comment by cpury** [comment]
@edmondja

> does it work if I do ... ?

I believe you forgot the brackets after `NoisySGD`. Try this:

```python
model.compile(loss='mse', optimizer=NoisySGD())
```

> And if I want to use Nadam with it I just need to change to `class NoisySGD(keras.optimizers.Nadam):` ?

I looked at the Nadam code and it doesn't seem to overwrite the `get_gradients` function, so it would probably work as you proposed. Feel free to try and report back.

> a way to change the quantity of noise

My `NoisySGD` implementation takes two additional keyword args: `noise_eta` and `noise_gamma`. They correspond to η and γ from figure 1 in the paper. By default, they are set to `0.01` and `0.55` respectively. You can experiment with them, e.g. by setting:

```python
model.compile(loss='mse', optimizer=NoisySGD(noise_eta=0.3, noise_gamma=0.8))
```

**Comment by edmondja** [comment]
This works @cpury , thank you, I am testing it while tuning eta.

**Comment by cpury** [comment]
@edmondja I had an error in my code, I just fixed it. Please update your `get_gradients` method accordingly. Sorry for the trouble!

**Comment by cpury** [comment]
I improved and released my code to a separate package: https://github.com/cpury/keras_gradient_noise .
With this you can add Gradient Noise to any Optimizer class.

Install via `pip install keras_gradient_noise`. Usage example:

```python
from keras.optimizers import Adam
from keras_gradient_noise import add_gradient_noise

# ...

NoisyAdam = add_gradient_noise(Adam)

model.compile(optimizer=NoisyAdam(noise_eta=0.1, noise_gamma=0.4))
```

@fchollet if you're interested, I could convert this into a PR.

**Comment by yoquankara** [comment]
@cpury 

I tried your package, but when running Keras with Tensorflow backend, there was error:
```
keras_gradient_noise/gradient_noise.py", line 43, in get_gradients
  for grad in grads
AttributeError: 'IndexedSlices' object has no attribute 'shape'
```

Is this a known issue?

**Comment by cpury** [comment]
@yoquankara I've never seen that before. But let's continue this elsewhere. Could you create an issue on my repository with some more details?

**Comment by yoquankara** [comment]
@cpury Thanks, I will post to your repo.
