### ISSUE TITLE
Merge no longer works on a Graph model

### ISSUE THREAD

**Issue by HyrumAnderson** [fchollet/keras#2263]
In keras 1.0.0, I can no longer use Merge with a Graph model as an input:
```
    from keras.models import Sequential, Graph
    from keras.layers import Dense, Merge

    model1 = Sequential()
    model1.add( Dense( 1, input_dim=1))
    
    model2 = Graph()
    model2.add_input(name='test_input', input_shape=(1,))
    model2.add_node( Dense(1), input='test_input', name='test_layer' )
    model2.add_output(name='test_output', input='test_layer')

    joint = Sequential()
    joint.add( Merge([model1, model2], mode='concat'))```
```

The above code results in 
```
Exception: The layer has never been called and thus has no defined output shape.
```
this worked in earlier versions of keras, e.g., 0.3.3.

This is a useful architecture for many problems, such as learning document similarity.

**Comment by fchollet** [comment]
`Graph` is deprecated. I suggest you rewrite the model using the functional API: http://keras.io/getting-started/functional-api-guide/

If you need to keep using the same model, just stay on Keras 0.3.3 --but keep in mind the future is the functional API.

**Comment by fchollet** [comment]
PS: a quick fix in this case is to build the models before creating the Merge layer:

`model1.build()`
`model2.build()`

**Comment by TomasJiang** [comment]
@fchollet How can I find the previous document about keras 0.3.3?
