### ISSUE TITLE
Error Loading Older Models

### ISSUE THREAD

**Issue by urinieto** [fchollet/keras#2264]
I am trying to load a model with keras 1.0 that I saved using keras 0.3, but I get the following error when I use `model_from_json`:

```
    153     with open(model_file) as f:
    154         json_str = json.load(f)
--> 155     return model_from_json(json_str)
    156 
    157 

/home/onieto/local/anaconda2/lib/python2.7/site-packages/keras/models.pyc in model_from_json(json_string, custom_objects)
     28     from keras.utils.layer_utils import layer_from_config
     29     config = json.loads(json_string)
---> 30     return layer_from_config(config, custom_objects=custom_objects)
     31 
     32 

/home/onieto/local/anaconda2/lib/python2.7/site-packages/keras/utils/layer_utils.pyc in layer_from_config(config, custom_objects)
     22         globals()[cls_key] = custom_objects[cls_key]
     23 
---> 24     class_name = config['class_name']
     25 
     26     if class_name == 'Sequential':

KeyError: 'class_name'
```

Are you planning on adding backwards compatibility with old models? If not, is there any script to update the old json files?

**Comment by fchollet** [comment]
Weights files and code files are (almost entirely) backwards compatible,
but JSON files are not. However, you could write a converter, it should not
be difficult.

What I suggest you do: use your existing code to generate a JSON file using
the new version. Compare the result to the old JSON file. Make changes as
needed.

**Comment by urinieto** [comment]
Thanks for the info, I'll do that then.
