### ISSUE TITLE
Printing epoch multiple times

### ISSUE THREAD

**Issue by civiskdonahue** [fchollet/keras#227]
![screen shot 2015-06-15 at 9 25 50 am](https://cloud.githubusercontent.com/assets/12633648/8162056/99b312f2-1340-11e5-9127-a8d0a4b94203.png)

I'm having an issue where when I rerun lines above (trying to make a new model), when I try to fit, it prints the number of epochs n times, where n is the number of times I have fit the model since last restarting the kernel. Is there any way to stop this from happening? It's annoying when n=2, but gets hard to read outputs when n=10.

**Comment by fchollet** [comment]
This is a known bug that was fixed last week. Just pull master and reinstall, and it will disappear.
