### ISSUE TITLE
Convolutional2D Layers: Filtering Each Channel Separately.

### ISSUE THREAD

**Issue by davisliang** [fchollet/keras#2270]
Hi All,

Hope you're doing well. This is a question about the functionality of Convolutional2D. Thank you for taking your time to look at this! :) 

I'm trying to filter an image with n channels where each channel is filtered separately. However, the Convolution2D layer ends up summing up all my channel activations. For example, a layer of the form

model.add(Convolution2D(32, 3, 3, border_mode='valid', input_shape=(3, 100, 100)))

will produce an output of the following shape:

(None, 64, 224, 224)

I want the output of the layer to be (numFilters, numChannels, rows, cols):

(64, 3, 224, 224)

Is the only way to achieve this with the Convolution3D function? If so, what would that command look like? Thank you for your time!

Best,
Davis

**Comment by mowayao** [comment]
@davisliang You can create a layer  like Convolution2D in keras, it  may requires  only minor modifications.
