### ISSUE TITLE
[Question] Spatial inputs?

### ISSUE THREAD

**Issue by manugarri** [fchollet/keras#228]
Im trying to use some RGB images as an input. Is there any way to use 3dimensional (x,y, rgb)s arrays as the inputs?

**Comment by jonilaserson** [comment]
Yes, just transpose the dimensions to (rgb, x, y).

**Comment by manugarri** [comment]
im not sure i explained myself.

The image read with `scipy.misc.imread` provides a multidimensional array with the shape `(28, 28,3)` . 

That is , 28px width by 28 pixels height by length 3 color RGB array.

I reshaped that into a vector with dimensions (28*28,3), that is (784,3).

Once i put all the images together i get an X_train of dimension (N, 784, 3),  N being the number of sampled images.

How could i convert that np.array into a way that keras would accept?
