### ISSUE TITLE
is there any guide regarding how to transfer 0.3.3 Keras program to 1.0.0 version?

### ISSUE THREAD

**Issue by fluency03** [fchollet/keras#2283]
is there any guide regarding how to transfer 0.3.3 Keras program to 1.0.0 version?

**Comment by fchollet** [comment]
For custom layers, there is this: https://github.com/fchollet/keras/wiki/Porting-your-custom-layers-from-Keras-0.3-to-Keras-1.0

**Comment by fluency03** [comment]
@fchollet so other codes will be automatically compatible?

**Comment by fchollet** [comment]
> @fchollet so other codes will be automatically compatible?

Yes, almost entirely. There will be differences here and there. For instance, the following were removed:
Siamese, Autoencoder, LambdaMerge, add_shared_layer.

Also, accuracy monitoring is now done by passing `metrics=['accuracy']` to `compile`. The argument `show_accuracy` is deprecated.

**Comment by fluency03** [comment]
@fchollet thanks a lot!

**Comment by vivekv80** [comment]
@fchollet is there a way to still implement Autoencoder in 1.0.0 version?

**Comment by fchollet** [comment]
@vivekv80 I recommend you use the functional API to build autoencoders now. You can have three separate models (with all layers shared, of course), one for training (encoding + decoding), one for encoding only and one for encoding only.

**Comment by Imorton-zd** [comment]
Hi, @vivekv80 , have you implemented autoencoders with keras1.01?

**Comment by vivekv80** [comment]
@lmorton-zd: yes, I was able to implement an autoencoder in this way:
    ```
encoder = Sequential([Dense(first_layer, input_dim=num_sens), Dense(hl[1]), Dense(hl[2]),Dense(last_layer[bn])])
    decoder = Sequential([Dense(hl[2], input_dim=last_layer[bn]), Dense(hl[1]), Dense(first_layer), Dense(num_sens)])
    # autoencoder = AutoEncoder(encoder=encoder, decoder=decoder, output_reconstruction=True) # old way in Keras 0.3.3
    autoencoder = Sequential()
    autoencoder.add(encoder)
    autoencoder.add(decoder)
    autoencoder.output_reconstruction=True
    history = History()
    model = models.Sequential()
    model.add(autoencoder)
```
