### ISSUE TITLE
encoder and decoder issue for keras

### ISSUE THREAD

**Issue by shawnkx** [fchollet/keras#2285]
Hi, I have a question about encoder and decoder framework for machine translation. How can I implement this equation: h_t = f(h_{t-1}, y_{t-1}, c) by Keras since I only know how to implement equation: 
h_t = f(h_{t-1}, c). Thanks in advance!

**Comment by nzw0301** [comment]
You could take a look at exsample https://github.com/fchollet/keras/blob/master/examples/addition_rnn.py#L131-L144

**Comment by shawnkx** [comment]
Thanks! so 
for _ in range(LAYERS):
    model.add(RNN(HIDDEN_SIZE, return_sequences=True))
is to use y{t-1} for y{t}? But where is c?

**Comment by nzw0301** [comment]
c is `RepeatVector` in this code

**Comment by shawnkx** [comment]
But to my knowledge, according to the figure I attached, the example only puts the the C(t) instead of h(t) which is y in my question to the next LSTM. 
![1](https://cloud.githubusercontent.com/assets/15963237/14481733/799c14e8-0168-11e6-8d53-ab2a93d72071.png)

**Comment by jllombart** [comment]
I think, in the case of addition_rnn, the thing which is passed to the "decoder" is the ht of the last symbol of the sequence and repeted as many times as long could be the output sequence.
In this example C is not shared with the decoder as it would be in the case of sentence to sentence like http://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf

the lstm layer do not provide the states vector C.

I'm not sure how implement it with keras. Maybe with the new fuctional api would be easier but I think it is neccesary to modify the recurrent layer to support this. I think it would possible if like in tensor flow, the recurrent layer would have an initial_states input and states output but I don't know if it is compatible with functional api.
