### ISSUE TITLE
Add option to change generator queue size in fit_generator

### ISSUE THREAD

**Issue by jbencook** [fchollet/keras#2287]
I'm training a 3D CNN model on video clips and my batch generator is eating up all the memory on my machine. I see that the `generator_queue` function has a `max_q_size` argument, but there's no way to set it in the `fit_generator` call.

Here's [a link](https://gist.github.com/jbencook/15cd39799dbefdccae9c4087647a5f91) to my code, which works until I run out of memory. I'm using the data described [here](https://github.com/gtoderici/sports-1m-dataset).

**Comment by braingineer** [comment]
As a temp fix, you could just modify the training.py, right? 

It'd be nice if you just push the generator kwargs through:

```python
    def fit_generator(self, generator, samples_per_epoch, nb_epoch,
                      verbose=1, callbacks=[],
                      validation_data=None, nb_val_samples=None,
                      class_weight={}, generator_kwargs=None):
        generator_kwargs = generator_kwargs or {} #not sure if this matters; 
```
and
```
generator_queue(generator, **generator_kwargs)
```

**Comment by jbencook** [comment]
Yeah I did modify training.py in my copy of Keras. `**generator_kwargs` is an interesting idea, but it seems a little weird to have to say `model.fit_generator(..., generator_kwargs={"max_q_size": 3})`. It also violates what seems to be a principle of being picky about arguments (e.g. [here](https://github.com/fchollet/keras/blob/0772210dea435e0c8d5cff9ce212b835b40c7a40/keras/models.py#L635)).

Listing out the args in the fit/evaluate/predict generator calls seems like a better approach to me:

```
    def fit_generator(self, generator, samples_per_epoch, nb_epoch,
                      verbose=1, callbacks=[],
                      validation_data=None, nb_val_samples=None,
                      class_weight={}, max_q_size=10, wait_time=0.05, nb_worker=1):
```

But I know that's a little awkward too... I'm happy to implement either approach.

**Comment by braingineer** [comment]
It seems your way fits better with the code base and it definitely makes sense.   There's not really any great option when it comes to having a ton of parameters floating around.  And it's mostly a style choice.  For instance, you can pass property dictionaries for [some matplotlib things](http://stackoverflow.com/questions/7125009/how-to-change-legend-size-with-matplotlib-pyplot). 

In my own implementations, I try to route the massive parameter issue using dummy container classes and `self.__dict__.update(some_dict)`.  Then, you can just pass the dummy and do `dummy.whatever`.   

(and more specifically:
```python

    def __init__(self, config):
        self.__dict__.update(config)

    @classmethod
    def from_file(cls, config_file):
        with open(config_file) as fp:
            config = yaml.load(fp)
        return cls(config)
```
