### ISSUE TITLE
Summary as string

### ISSUE THREAD

**Issue by michiexile** [fchollet/keras#2288]
By the way the HPC center I am using is setup, `stdout` and `stderr` are not visible until the computation finishes. I'm getting around this by creating custom output log-commands that write to files on a shared filesystem.

I want to be able to extract the output from `model.summary` into a string to output through this mechanism, rather than the current printing-only version.

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- N/A: Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by maciejkula** [comment]
This would be great!

**Comment by lauphedo** [comment]
I am looking exactly for this functionality. 
Did you make any progress?
