### ISSUE TITLE
Can i add global pooling layer?

### ISSUE THREAD

**Issue by loyeamen** [fchollet/keras#230]
I have added this layer in my local keras (under convolutional layers):

class GlobalPooling(Layer):
    '''
        Apply a global pooling to an output.
    '''
    def __init__(self, pooling_function = T.mean):
        super(GlobalPooling,self).__init__()
        self.pooling_function = pooling_function
    def get_output(self, train):
        X = self.get_input(train)
        return self.pooling_function(X.flatten(3), axis = 2)

    def get_config(self):
        return {"name":self.__class__.__name__,
               "pooling_function}":self.pooling_function.__name__}

It seems to work fine, can you please add this support?

Thanks!

**Comment by fchollet** [comment]
Sure, you could open up a pull request and we'll look at it.

**Comment by entron** [comment]
Is global pooling added?

**Comment by loyeamen** [comment]
You can use the code i wrote in the first message

**Comment by entron** [comment]
thanks! I am thinking to create a pull request for that; it would make things easier.

**Comment by loyeamen** [comment]
Sure, go for it

**Comment by entron** [comment]
Created a pull request: https://github.com/fchollet/keras/pull/522
