### ISSUE TITLE
validation_split argument in fit() method 

### ISSUE THREAD

**Issue by PhyloStar** [fchollet/keras#2305]
The fit function in training.py does not update ins variable after split. It seems the training is performed on whole of the dataset and testing is performed on the heldout part. The problem shows up when the _fit_generator method prints the size of training and testing data. The training size shows as the same as the full dataset.

**Comment by fchollet** [comment]
Thanks for the report, this is now fixed.

**Comment by PhyloStar** [comment]
Thank you. Working!
