### ISSUE TITLE
identity matrix in Keras 1.0

### ISSUE THREAD

**Issue by keunwoochoi** [fchollet/keras#2309]
For identity connection of Residual networks in Keras, I was using this class.
```
class Identity(Layer):
    def get_output(self, train):
        return self.get_input(train)
```
I checked out [porting guide](https://github.com/fchollet/keras/wiki/Porting-your-custom-layers-from-Keras-0.3-to-Keras-1.0), which says `get_output` should be replaced with `call`. But I'm not sure what would be equivalent to `self.get_input(train)`.

**Comment by fchollet** [comment]
def call(x, mask=None):
   return x

**Comment by keunwoochoi** [comment]
Oh, that simple... thanks!
