### ISSUE TITLE
Activity dependent regularisation?

### ISSUE THREAD

**Issue by phreeza** [fchollet/keras#231]
I thought I had read about this topic here before, but I can't seem to find the issue.

I would like to implement an activity based regularisation, but I don't think this is possible right now. I think it would be possible to include the option to do this without breaking the API but it would include some additional complexity in the code (in particular around [here](https://github.com/fchollet/keras/blob/master/keras/optimizers.py#L30)).

What I want to implement is a sparseness regularisation like [descibed by Andrew Ng here](http://web.stanford.edu/class/cs294a/sparseAutoencoder.pdf).

I realize this might be an obscure use case. Would you be interested in merging such a modification?

**Comment by fchollet** [comment]
>  Would you be interested in merging such a modification?

Sure, I believe it can be useful, if it can be added in a way that fits with the current architecture. What is your proposal for how it would work, architecturally?

**Comment by phreeza** [comment]
OK I am on it then. Essentially what I would do is let a layer have an optional member called cost_update, these can then be stored in Sequential just as the other regularisers and constraints. When the time comes to calculate the cost function, the model adds these to the main cost.

**Comment by phreeza** [comment]
I have updated my PR #241 for this issue.
