### ISSUE TITLE
Merge layer's output_shape attribute doesn't work for tuples

### ISSUE THREAD

**Issue by codekansas** [fchollet/keras#2313]
Hi, while trying to give a tuple as my output_shape for a lambda merge layer

    subt = Merge(name='subt', mode=lambda x: x[0] - x[1], output_shape=(None, n_output_dims))

I get the error

    we cannot infer its output shape because no `output_shape` argument was provided

I'm using Keras 1.0. I'm not sure if this is a known issue / backwards problem, since the help text specifically says you can pass a tuple. I believe it is a pretty easy fix [here](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1259), something like:

    elif isinstance(self._output_shape, tuple):
        return self._output_shape

The error message also seems a bit misleading since it could be given if the wrong argument type is passed.

**Comment by fchollet** [comment]
Thanks for the report, this is now fixed.
