### ISSUE TITLE
When predicting on batch, is it possible to use a worker to load images into disk while running forward pass for last batch?

### ISSUE THREAD

**Issue by sunshineatnoon** [fchollet/keras#2315]
I packed my testing images into batches and use model.predict_on_batch to predict on batch. However, I have 40 images per batch, loading them into disk needs a second, this is a lot of time compared to the forward time, so is there any tool I can use to load next batch into disk while predicting on a batch? Thanks!

**Comment by fchollet** [comment]
Yes, what you want to use is `predict_generator`. See the docs.
