### ISSUE TITLE
Is input_length still needed in Embedding when using the new API? 

### ISSUE THREAD

**Issue by braingineer** [fchollet/keras#2316]
I've run into some cranky issues regarding the re-use of an Embedding layer.  

Specifically, I have two inputs---a word-tree with a parent and many children.  I want to separately embed the parent apart from the children (I'm doing soft attention over the children).   

However, reusing the same Embedding layer makes that difficult because it injects a `None` into the first dimension of `_keras_shape` (to make it `(batch, None, embedding_size)`).

In my local copy, I've dereferenced `input_length` everywhere and use `input_shape[1]` in `get_output_shape_for`. aka:
```python 
    def get_output_shape_for(self, input_shape):
        return (input_shape[0], input_shape[1], self.output_dim)
```

 Is there a better way or should the input_shape be handled by `Input` instead?

**Comment by fchollet** [comment]
Not clear what your issue consist --do you have a script to reproduce it, with details of what behavior you're seeing and what you would have expected instead?

**Comment by braingineer** [comment]
Sure, here is a gist for reproducing the issue:

https://gist.github.com/braingineer/85eaeb8f117ea862f96867e7051106d4

With the Embedding layer having it's original implementation, it should produce:

```
Child shape before embedding:  (64, 20)
Child shape after embeddding & before attending:  (64, None, 50)
Child shape after attending & before repeating:  (64, 50)
Final child shape after repeating:  (64, 30, 50)
Parent shape before embedding:  (64, 1)
Parent shape before embedding:  (64, None, 50)
Traceback (most recent call last):
  File "keras_test.py", line 81, in <module>
    flat_parent = F_flatten(embedded_parent)
  File "/home/cogniton/research/code/keras/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/cogniton/research/code/keras/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/cogniton/research/code/keras/keras/engine/topology.py", line 151, in create_node
    output_shapes = to_list(outbound_layer.get_output_shape_for(input_shapes[0]))
  File "/home/cogniton/research/code/keras/keras/layers/core.py", line 304, in get_output_shape_for
    '(got ' + str(input_shape[1:]) + '. '
Exception: The shape of the input to "Flatten" is not fully defined (got (None, 50). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.
```

by changing it to:
```python
def get_output_shape_for(self, input_shape):
    return input_shape + (self.output_dim,)
```

it becomes

```
Child shape before embedding:  (64, 20)
Child shape after embeddding & before attending:  (64, 20, 50)
Child shape after attending & before repeating:  (64, 50)
Final child shape after repeating:  (64, 30, 50)
Parent shape before embedding:  (64, 1)
Parent shape before embedding:  (64, 1, 50)
Parent shape after flattening before repeating:  (64, 50)
Final parent shape after repeating:  (64, 30, 50)
```

Also, the change above is slightly different than the original post.   At some point I want to embed a 5dim tensor, and changing it to above gives the desired behavior.

**Comment by fchollet** [comment]
I've pushed a fix for this issue. Thanks for the report.
