### ISSUE TITLE
Understanding ImageDataGenerator

### ISSUE THREAD

**Issue by jonilaserson** [fchollet/keras#232]
Some comments after viewing the code in keras/keras/preprocessing/image.py:
1. There is an option to set fit(augment=True), which does not seem to do anything. It works a lot on creating a copy of the whole dataset X where every image is transformed, and then ignores that X.
2. flow() applies all the transformations through random_transform(), on an image with dimensions (Depth, Height, Width). On the other hand, fit(augment=True) applies the same transformations on an image with dimensions (Height, Width, Depth), by applying the helper function array_to_img() first. As a result the transformations in the fit(augment=True) case don't really do what they are supposed to do. 

So it seems that the fit(augment=True) case is no longer working properly, and should probably be removed (or fixed).

**Comment by fchollet** [comment]
> There is an option to set fit(augment=True), which does not seem to do anything

> On the other hand, fit(augment=True) applies the same transformations on an image with dimensions (Height, Width, Depth)

So which one is it, does it do nothing or does it apply the wrong transformations? 

For the record, here's the corresponding bit of code.

```python
if augment:
            aX = np.zeros(tuple([rounds*X.shape[0]]+list(X.shape)[1:]))
            for r in range(rounds):
                for i in range(X.shape[0]):
                    img = array_to_img(X[i])
                    img = self.random_transform(img)
                    aX[i+r*X.shape[0]] = img_to_array(img)
            X = aX
```

How do you suggest to modify this? Where exactly is the issue?

**Comment by jonilaserson** [comment]
It applies the wrong transformations and then throws away the results.
Actually, I think it might still pollute self.mean and self.std which are
calculated based on X.

On Tue, Jun 16, 2015 at 10:28 PM, François Chollet <notifications@github.com

**Comment by fchollet** [comment]
> Actually, I think it might still pollute self.mean and self.std which are
calculated based on X.

The purpose of the `fit` function is to compute `self.mean` and `self.std`. That's it. That's why the results of intermediate computations are discarded after these 2 quantities are computed. 

Can you detail how the transformations are wrong, and what changes are required to correct them?

**Comment by jonilaserson** [comment]
For example, ndimage.interpolation.rotate works in dimensions (1,2) of a 3d
array x. You want these to be the height and width (same rotation is
applied for each rgb frame), and this is indeed the case since your input
is (rgb, h,w).
But when fit() is called, array_to_img cycles the dimensions of x before
calling rotate, so it is now (h,w,rgb), and rotate is working on the wrong
dimensions.

**Comment by jonilaserson** [comment]
To fix you should probably not use array_to_img in fit().
