### ISSUE TITLE
Preprocessing/test_image.py test failing

### ISSUE THREAD

**Issue by dansbecker** [fchollet/keras#2334]
The preprocessing/test_image.py test is failing (both locally and on travis-ci). The error is in the setup_function, and it is:

`>       os.mkdir('test_images')`
`E       FileExistsError: [Errno 17] File exists: 'test_images'`

I've spent some time trying to remedy this, fearing that it resulted from #2291 but I haven't been able to make heads or tails out of the test failure.

**Comment by fchollet** [comment]
The CI build is doing fine, and my tests are also passing locally. Can you point me to the error?

**Comment by dansbecker** [comment]
Here is an example on CI.  

https://travis-ci.org/fchollet/keras/jobs/123038622

It seems that, assuming I am reading the CI logs correctly, this error is happening only some of the time.

**Comment by fchollet** [comment]
Parallelism issue, I fixed it.
