### ISSUE TITLE
How to deal with the dataset for Fully Convolutional Networks

### ISSUE THREAD

**Issue by ycszen** [fchollet/keras#2340]
Recently I am implementing the FCN with the dataset "SiftFlow".Now I have a problem to deal with the labels of SiftFlow. The labels of SiftFlow are semantic labels, not one class per picture. So how can I make labels for training?

**Comment by wongjingping** [comment]
Is your dataset something like the following: http://www.svcl.ucsd.edu/projects/imgnote/eg_annotation.htm? Came across this paper, not sure if it'll help: http://people.csail.mit.edu/torralba/publications/eccv10_ssl.pdf

**Comment by ycszen** [comment]
First, thanks for your reply.The dataset is certainly like this you mentioned. In fact, the dataset provides some image and related mat file in which every pixel is labeled a class.Now I want to know how to deal with this mat file with keras and how to train the model.
