### ISSUE TITLE
Weights from Sequential incompatible with equivalent Model from functional API

### ISSUE THREAD

**Issue by zo7** [fchollet/keras#2341]
It seems that trying to load weights from a Sequential model into an equivalent Model created with the functional API doesn't work, since the input layers are counted as an additional layer that the Sequential model doesn't have.

For example, trying to load a pre-trained VGG-16 model [like the one provided here](https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3) results in the following exception being thrown:

```
Traceback (most recent call last):
  File "ssl_temp.py", line 240, in <module>
    compile(args.model, overwrite=args.overwrite)
  File "ssl_temp.py", line 209, in compile
    model = build_model((3,224,224), (2,200,200), (128,))
  File "ssl_temp.py", line 157, in build_model
    semantic_stream = build_stream()
  File "ssl_temp.py", line 124, in build_stream
    model.load_weights(vgg_path)
  File "/usr/local/lib/python3.5/site-packages/keras/engine/topology.py", line 2273, in load_weights
    str(len(flattened_layers)) + '.')
Exception: You are trying to load a weight file containing 37 layers into a model with 38.
```

[Gist to model used.](https://gist.github.com/zo7/41ce4cccfcfe8f0bff1b4ad82d0ee451)

Would it make sense to disregard input layers when loading weights since they don't have any parameters? (or perhaps have Sequential models start with an implicit InputLayer?)

~~One could just use the original Sequential model instead, but I've been running into trouble mixing the two.~~ Edit: Ignore this comment, it was from my own error.

**Comment by alexendy** [comment]
I had the same problem, here is [a quick patch](https://github.com/fchollet/keras/files/289470/patch-seq.txt) that solves the issue with an optional argument to load_model

**Comment by dk683** [comment]
Hello! Is there any update on this, except the patch with an optional argument to load_model? Thank you!

**Comment by zo7** [comment]
@dk683 I'd suggest to either just define the model the original way or try loading the model from a file that you know works.

Alternatively, you might have some luck trying to load the weights for each layer individually straight from the HDF5 weights file like in [this script](https://gist.github.com/fchollet/7eb39b44eb9e16e59632d25fb3119975#file-classifier_from_little_data_script_3-py-L109).

**Comment by dk683** [comment]
Thank you! I solved the problem by loading the weight individually from the hdf5 weight.
