### ISSUE TITLE
Has LamdaMerge been removed from keras? How to implement a custom-defined merge mode currently?

### ISSUE THREAD

**Issue by walleva** [fchollet/keras#2342]
I found that LamdaMerge was deleted from [core.py](https://github.com/fchollet/keras/blob/master/keras/layers/core.py) and keras.io.
I want to implement a merge mode of the euclidean distance (euclidean is from scipy). 
My left model is a Sequential RNN while the right model is a Sequential CNN.
Here is a snippet of my current code. 

```
def edis(inputs):
    l1 = inputs[0]
    l2 = inputs[1]
    return euclidean(l1,l2)

model =  Sequential()
model.add(LambdaMerge(layers=[left,right], mode=edis))
```

Now I couldn't find the LambdaMerge source code in core.py. Is it removed from keras?
If I want to implement a custom-defined merge code, is the only way  to modify source code of Merge model? It seems that the Merge layer is also moved to another py file. Since I can only find the following [code line ](https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L16)related to Merge in [core.py](https://github.com/fchollet/keras/blob/master/keras/layers/core.py).

`from ..engine import InputSpec, Layer, Merge`

p.s. This is the previous snippet about LamdaMerge in my local downloaded keras package.
`class LambdaMerge(Lambda):
    '''LambdaMerge layer for evaluating an arbitrary Theano / TensorFlow
    function over multiple inputs.

```
# Output shape
    Specified by output_shape argument

# Arguments
    layers - Input layers. Similar to layers argument of Merge
    function - The function to be evaluated. Takes one argument:
        list of outputs from input layers
    output_shape - Expected output shape from function.
        Could be a tuple or a function of list of input shapes
    arguments: optional dictionary of keyword arguments to be passed
        to the function.
'''`
```

**Comment by zo7** [comment]
You can still do that, the functionality is just built into the Merge layer by setting `mode` to a function or lambda. From the [docs](http://keras.io/layers/core/#merge):

> **Arguments**
> * **mode**: string or lambda/function. If string, must be one
>     * **of**: 'sum', 'mul', 'concat', 'ave', 'cos', 'dot'. If lambda/function, it should take as input a list tensors and return a single tensor.

So you can just use: `model.add( Merge(layers=[left, right], mode=edis) )` instead and set the appropriate `output_shape`.

**Comment by walleva** [comment]
@zo7 Thank you! I will have a try.

**Comment by codekansas** [comment]
Make sure to provide the `output_shape` parameter if using a lambda function, since it's not inferred. Here's an example for subtracting two layers:

    merge([a, b], mode=lambda x: x[0] - x[1], output_shape=lambda x: x[0])

**Comment by walleva** [comment]
`def edis(inputs): 
    s = inputs[0] - inputs[1]
    output = K.sqrt(K.batch_dot(s, s, -1))
    return output

def edis_outputshape(input_shape):
    #print 'input_shape', input_shape
    shape = list(input_shape)
    assert len(shape)==2
    outshape = (shape[0][0], 1)
    #print 'output_shape', outshape
    return tuple(outshape)

model.add(Merge(layers=[left, right], 
                    mode=edis, 
                    output_shape=edis_outputshape ))`

**Comment by walleva** [comment]
@codekansas Thank you for reminding the output_shape.
It takes me several hours to figure out how to get the output_shape until finding an example of Lamba layer.

Here is my solution:
![image](https://cloud.githubusercontent.com/assets/6754355/14586037/4d659946-04bd-11e6-937e-74ed5b9826e7.png)

![image](https://cloud.githubusercontent.com/assets/6754355/14586040/5aa32772-04bd-11e6-86bc-ad971d400d16.png)

It could pass the model.compile but failed in model.fit. I am debugging for new errors.

**Comment by walleva** [comment]
My new problem is similar to [https://github.com/fchollet/keras/issues/981](url)
However, my keras version is the newest 1.0.1.

I tried to minimize the euclidean distance between ma's output and mb's output.
Here is my simplified test code.
`
from keras.layers.core import Dense
import numpy as np
from construct import edis, edis_outputshape
from keras.models import Sequential
from keras.engine import Merge

ma = Sequential()
ma.add(Dense(128, input_dim=20))

mb = Sequential()
mb.add(Dense(128,input_dim=50))

mc = Sequential()
mc.add(Merge(layers=[ma,mb], 
            mode=edis, 
            output_shape=edis_outputshape))

# mc.add(Merge([ma,mb], mode='cos'))

print 'ma out', ma.output_shape
print 'mb out', mb.output_shape
print 'mc out', mc.output_shape

print 'compile'
mc.compile(loss='mae',
           optimizer='sgd',
           metrics=['accuracy'])

nb_train = 100
Xa = np.random.random((nb_train, 20))
Xb = np.random.random((nb_train, 50))
y_train = np.random.uniform(0,0.001, (nb_train, 1))

nb_val = 10
Xa_val = np.random.random((nb_val, 20))
Xb_val = np.random.random((nb_val, 50))
y_val = np.random.uniform(0,0.001, (nb_val, 1))

print 'fit'
mc.fit([Xa, Xb], y_train,
       batch_size=10,
       nb_epoch=5,
       validation_data=([Xa_val, Xb_val], y_val))

`

And this is the error information.
`Using Theano backend.
ma out (None, 128)
mb out (None, 128)
mc out (None, 1)
compile
fit
WARNING (theano.gof.compilelock): Overriding existing lock by dead process '1528' (I am process '3305')
Traceback (most recent call last):
  File "/Users/velo/Documents/workspace/APIEmbeddings/embed_api/temp.py", line 44, in <module>
    validation_data=([Xa_val, Xb_val], y_val))
  File "/Users/velo/anaconda/lib/python2.7/site-packages/keras/models.py", line 402, in fit
    sample_weight=sample_weight)
  File "/Users/velo/anaconda/lib/python2.7/site-packages/keras/engine/training.py", line 1015, in fit
    self._make_train_function()
  File "/Users/velo/anaconda/lib/python2.7/site-packages/keras/engine/training.py", line 646, in _make_train_function
    training_updates = self.optimizer.get_updates(trainable_weights, self.constraints, self.total_loss)
  File "/Users/velo/anaconda/lib/python2.7/site-packages/keras/optimizers.py", line 115, in get_updates
    grads = self.get_gradients(loss, params)
  File "/Users/velo/anaconda/lib/python2.7/site-packages/keras/optimizers.py", line 48, in get_gradients
    grads = K.gradients(loss, params)
  File "/Users/velo/anaconda/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 507, in gradients
    return T.grad(loss, variables)
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 561, in grad
    grad_dict, wrt, cost_name)
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 1324, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 973, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 1279, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 1113, in access_term_cache
    input_grads = node.op.grad(inputs, new_output_grads)
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 413, in grad
    return [DimShuffle(gz.type.broadcastable, grad_order)(
  File "/Users/velo/anaconda/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 165, in __init__
    (input_broadcastable, new_order))
ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False, False), (0, 2)))
`

Does this error caused by the Merge part?
It seems that the error appears when the model runs gradient descent on input.
Could anyone help me? :(

**Comment by walleva** [comment]
I  tested the Merge example "[Two merged LSTM encoders for classification over two parallel sequences](http://keras.io/getting-started/sequential-model-guide/#examples)". It's good to run it on my current keras version. 
So did the above error come from the Merge function or the output shape?

**Comment by carlthome** [comment]
Wow, this is fantastic. I too missed that LambdaMerge was still around in the new API. Thanks @zo7!

**Comment by zo7** [comment]
@walleva The error message kinda looks like Theano is having trouble computing your gradient, so it might be a problem with `edis`. Is there a reason you're using `K.batch_dot` instead of `K.dot`? (I'm not sure of the main difference between the two)

**Comment by walleva** [comment]
@zo7 I wrote this function with reference to built-in ['`cos`'](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1219) mode in Merge. 

![image](https://cloud.githubusercontent.com/assets/6754355/14593199/0123ecf2-055a-11e6-8a51-91456de04a70.png)

And `K.batch_dot `comes from [Theano backend batch_dot](https://github.com/fchollet/keras/blob/5dad3786f6a34c15ce11ee862bab7a59ed713d68/keras/backend/theano_backend.py#L114).

![image](https://cloud.githubusercontent.com/assets/6754355/14593217/56fb2618-055a-11e6-9e20-322f511813a0.png)

I also think the problem is caused by the gradient. I wil try to modify my edis function.  Thank you!

**Comment by carlthome** [comment]
Why do you screenshot your code? It makes it hard to read on high DPI
screens, and isn't particularly copy/paste friendly. Could you use Markdown
instead?
Den 18 apr. 2016 05:42 skrev "walleva" <notifications@github.com>:

**Comment by benjaminklein** [comment]
Hey @walleva,

Please try the following definitions instead:

def euc_dist(x):
    s = x[0]  - x[1]
    output = (s ** 2).sum(axis=1)
    output = K.reshape(output, (output.shape[0],1))
    return output

def euc_dist_shape(input_shape):
    shape = list(input_shape)
    outshape = (shape[0][0],1)
    return tuple(outshape)

They worked for me.

**Comment by walleva** [comment]
@carlthome Sorry for pasting the screenshots. Because each time I pastes the code snippets between the code marker, only a few lines of them becomes the code format and others still remain the text format. I will try the markdown you said. Thank you!

**Comment by walleva** [comment]
@benjaminklein They also worked for me!!! Thank you VERY MUCH!!!

**Comment by walleva** [comment]
I pasted the code that worked for me. Hope it would be useful to others.

```
from keras.layers.core import Dense
import numpy as np
from construct import euc_dist, euc_dist_shape
from keras.models import Sequential
from keras.engine import Merge
from keras import backend as K

ma = Sequential()
ma.add(Dense(30, input_dim=20))
ma.add(Dense(15))

mb = Sequential()
mb.add(Dense(15,input_dim=50))

modelmerge = Sequential()
modelmerge.add(Merge(layers=[ma,mb], mode=euc_dist, output_shape=euc_dist_shape))

print('Compile')
modelmerge.compile(loss='mae',optimizer='sgd')

nb_train = 20
Xa = np.random.random((nb_train, 20))
Xb = np.random.random((nb_train, 50))
y_train = np.random.uniform(0,0.001, (nb_train, 1))

nb_val = 10
Xa_val = np.random.random((nb_val, 20))
Xb_val = np.random.random((nb_val, 50))
y_val = np.random.uniform(0,0.001, (nb_val, 1))

print('Fit')
his = modelmerge.fit([Xa, Xb], y_train,batch_size=10,nb_epoch=2,
       validation_data=([Xa_val, Xb_val], y_val))
print(his.history)
```

**Comment by dk683** [comment]
Thank you for sharing your code, @walleva!

**Comment by undertherain** [comment]
but now since Merge layer is being deprecated and the message says it will be removed from 2017.08 - what's the solution for merging with lambda?

**Comment by allenwoods** [comment]
@undertherain Just use Lambda, see answer [keras-merge-layer-warning](https://stackoverflow.com/questions/43160181/keras-merge-layer-warning)

**Comment by abdelwahab** [comment]
I have the same issue, whats the alternative way to do custom merging or lambdaMerge. The previous code doesn't work anymore in keras2
