### ISSUE TITLE
support TensorFlow 0.8 distributed computing

### ISSUE THREAD

**Issue by ybdesire** [fchollet/keras#2346]
The just released [TensorFlow v0.8.0 RC0](https://github.com/tensorflow/tensorflow/releases) has supported [distributed computing](https://www.tensorflow.org/versions/r0.8/how_tos/distributed/index.html) as announced [here](http://googleresearch.blogspot.com/2016/04/announcing-tensorflow-08-now-with.html). Can we support distributed computing by this way of tensorflow? (instead of by Spark)

**Comment by fchollet** [comment]
Yes, you can do that, by setting your own TF session via `K.set_session(sess)`.

**Comment by ybdesire** [comment]
@fchollet   any keras references for this TF distributed computing support? Can we setup keras cluster as TF like this below?
```python
model.ClusterSpec({"local": ["10.0.0.1", "10.0.0.2"]})
model.fit(x, y)
```

**Comment by Froskekongen** [comment]
An example on how to user K.set_session(sess) for this would be awesome. In particular, in the examples folder.
