### ISSUE TITLE
Cannot import Convolution3D and MaxPooling3D

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#2349]
Hi,
I tried to build a 3D CNN, but I already have an issue with the import `from keras.layers import Convolution3D, MaxPooling3D`. I get the following error: 

> ImportError: cannot import name Convolution3D

Everything works fine in 2D, why is that different in 3D?

**Comment by ybdesire** [comment]
I can import `Convolution3D, MaxPooling3D` correctly by keras 0.3.2 and python 3.5.0

**Comment by zo7** [comment]
Which version of Keras do you have?

**Comment by FiReTiTi** [comment]
Thanks for the answers.
I installed Kerasand Theano 5/6 weeks ago, and I didn't think that I needed an upgrade.
Anyway, I've upgraded both, and now it compiles.

Btw: how can I find the Keras version?

**Comment by rpinsler** [comment]
Use `keras.__version__`

**Comment by FiReTiTi** [comment]
Thanks.
