### ISSUE TITLE
Finetuning at Autoencoder Layer

### ISSUE THREAD

**Issue by felipemoraes** [fchollet/keras#235]
Anyone doing a fine tuning in autoencoder layer or anyone knows how to perform this at keras?

**Comment by loyeamen** [comment]
Check this:
https://github.com/fchollet/keras/blob/master/test/test_autoencoder.py

**Comment by felipemoraes** [comment]
I'm looking for something like stacked autoencoder. Like this: http://deeplearning.net/tutorial/SdA.html

**Comment by phreeza** [comment]
I don't have an implementation with the current autoencoder that is in keras, but basically what you would do is:
- build a denoising autoencoder ( see the example @loyeamen posted on how to do that)
- train the autoencoder
- get the *autoencoder.encoder* member and use that as a layer in your full model. 

Hope this helps

**Comment by jramapuram** [comment]
@felipemoraes : stacked autoencoders are currently available as shown in the examples:
```python
def build_deep_classical_autoencoder(autoencoder):
	encoder = containers.Sequential([Dense(input_dim, hidden_dim, activation=activation), Dense(hidden_dim, hidden_dim/2, activation=activation)])
	decoder = containers.Sequential([Dense(hidden_dim/2, hidden_dim, activation=activation), Dense(hidden_dim, input_dim, activation=activation)])
	autoencoder.add(AutoEncoder(encoder=encoder, decoder=decoder, output_reconstruction=False, tie_weights=True))
	return autoencoder
```
 They are not however greedily trained. If you want to do this you will have to train K models and ensure that you set:
```python
output_reconstruction = True 
```
Then it's a simple matter of connecting up the output (i.e. get_output() ) to the input of the next model.

**Comment by felipemoraes** [comment]
Thank you all. 
Maybe later I will fork the repository and implement a StackedAutoencoderLayer.
