### ISSUE TITLE
Optimizer config in a model

### ISSUE THREAD

**Issue by tboquet** [fchollet/keras#2353]
Not an actual issue but a question.

I see that the optimizer configuration is no more included in `get_config` in the new [backend](https://github.com/fchollet/keras/blob/4f5f88b9bab58e363b95ddc1931f2036d13d14e6/keras/models.py#L701-L722) compared to [the old backend](https://github.com/fchollet/keras/blob/master/keras/models.py#L701-L722). This lead to `model_from_json` [not building the model anymore](https://github.com/fchollet/keras/blob/6543b675096725a6ca1d05254d645d636c30d28d/keras/models.py#L404-L425) and it was the case [before](https://github.com/fchollet/keras/blob/6543b675096725a6ca1d05254d645d636c30d28d/keras/models.py#L169-L214).

So now, only the architecture of the model is serialized and not the optimizer. Sometimes different optimization methods could lead to very different results and it could be interesting to warn the users that they should also take care of this step. 
I was surprised when I first reused these funtionnalities, should it be mentionned in the documentation?

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
Sure, it may be better to mention these things in the docs. Do you want to make a PR for it?

In the near future, we will consider adding a Keras savefile format that stores at the same time the weights, the architecture, and the optimizer (alongside with its state). Such a file format would allow to save a model then resume training exactly where you left off.

**Comment by tboquet** [comment]
Yep sure, I will write an example for the doc and submit a PR.

Do you have any direction for the Keras format?
Right now, having the optimizer config and state and the model config at the same place is convenient since I store this information in MongoDB. The hyperparameters could be easilly accessed there. Having the weights in the same file would be convenient for quick experiments but not in the case where you want to quickly interact with the architecture itself? 
It would be nice to start a thread about this by the way :)!
