### ISSUE TITLE
border_mode in convolutional

### ISSUE THREAD

**Issue by xingdi-eric-yuan** [fchollet/keras#2355]
Hey guys,

@fchollet 

Why doesn't Keras support border_mode other than "same" and "valid"? As far as I know for Theano, it supports a bunch of other kind of border modes, especially the "full" mode is super useful. 

Thanks

**Comment by fchollet** [comment]
This is for API compatibility across backends. Also you don't really mean "a bunch of other kinds of border modes", sine "full" is the only additional one as far as I know.

**Comment by xingdi-eric-yuan** [comment]
There are also "half/int/(int1, int2)" mode
