### ISSUE TITLE
Error after final epoch when using fit_generator

### ISSUE THREAD

**Issue by aachkar-miovision** [fchollet/keras#2356]
Using a batch generator and fit_generator raises an error after the final epoch when running with tensorflow backend + gpu on linux and reading images from disk during next(generator) rather than simply taking entries from a pre-populated numpy array. 

Here is a gist of the issue and the log: https://gist.github.com/aachkar-miovision/89daac9ce598dbcb5a698612a3a42684

In my use case, it is not possible to load all the images into a single numpy array as in the cifar10_cnn fit_generator example, so I have to resort to loading images in batches from within my own ImageDataGenerator. I use cv2 because I perform different transforms involving color conversion, etc., so I load the images for a batch using cv2.imread(). 

With small images, I did not see this issue, but my images are on the order of 480x720 pixels and I do see it with images on that size (related to time it takes to read the image?). 

A possible fix would be to also check for AttributeError at https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L399

Is there a reason that this line only checks for ValueError?

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [yes] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [using tf] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [done] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by aachkar-miovision** [comment]
I have updated my prior comment with a gist of the issue and a log of the program's output.

**Comment by ahrnbom** [comment]
I have almost the exact same issue, in a completely different problem, but I'm also using fit_generator and get the same cryptic errors about NoneType. What seems to happen is that the thread which runs the generator starts to unload libraries (cv2 and numpy in your case, only numpy in mine) while the generator still runs. Then you get errors like those, where it tries to run someting on cv2 or np, but those are "None" so it just crashes. Very, very strange error.

**Comment by rmsmith88** [comment]
I am also having this problem, did you fix it?

**Comment by ahendry2688** [comment]
+1

**Comment by caugusta** [comment]
+1
