### ISSUE TITLE
Dropout_W/Dropout_U in LSTM throwing a warning from keras_learning_phase

### ISSUE THREAD

**Issue by Tuyki** [fchollet/keras#2360]
Greetings, 

with the following codes 

```
import numpy as np
import keras
import theano

print keras.__version__
print theano.__version__

from keras.models import Sequential
from keras.layers import LSTM, TimeDistributed, Dense

X = np.random.rand(50, 20, 10)
y = np.random.randn(50, 5)

model = Sequential()
model.add(LSTM(output_dim = 5, input_shape = (20, 10), return_sequences=False, dropout_W=0.1))
model.add(Dense(5))
model.compile('rmsprop', 'mse')
model.fit(X, y, verbose = 2, nb_epoch=1)
```

I get a warning of 

> UserWarning: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 3 is not part of the computational graph needed to compute the outputs: keras_learning_phase.
To make this warning into an error, you can pass the parameter on_unused_input='raise' to theano.function. To disable it completely, use on_unused_input='ignore'.
  **kwargs)

, which disappears without dropout_U/dropout_W or when they are 0. SimpleRNN and GRU do not show any warnings/errors of this kind with dropouts. My keras and theano versions respectively: 
1.0.0
0.8.1.dev-RELEASE

Thanks

**Comment by fchollet** [comment]
Thanks for the report, this is now fixed.
