### ISSUE TITLE
How to have a shared variable between layers?

### ISSUE THREAD

**Issue by benjaminklein** [fchollet/keras#2365]
Hi, 

Let assume that I want to have a matrix W which is learned and is used *differently* in different type of layers. W can be used in layer A in one way, and in layer B in another way. How can I achieve it such that the same W is being updated by all the different layers that are using it?

Thank you.

**Comment by fchollet** [comment]
You create your two custom layers, that use the same shared variable (you could make that variable a layer argument, for instance) and you only add it to the `trainable_weights` argument of one layer. Mind, it may be possible to add it to both (although it would be useless, technically), but it could cause issues with Theano.

**Comment by benjaminklein** [comment]
So one layer will have this as a trainable_weight and will output it so it could be used by the second layer as an input?
