### ISSUE TITLE
ModelCheckpoint saves one extra layer of weights

### ISSUE THREAD

**Issue by penguin2121** [fchollet/keras#2366]
I'm using the ModelCheckpoint as described in keras.io with a sequential model.  When I save the model using the code described in the FAQ and then try to reload it based on the weights saved by ModelCheckpoint, it tells me:

model.load_weights(os.path.join('checkpoints')+'//weights.hdf5')
Traceback (most recent call last):

  File "<ipython-input-15-ca39381e1009>", line 1, in <module>
    model.load_weights(os.path.join('checkpoints')+'//weights.hdf5')

  File "C:\WinPython\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\site-packages\keras\engine\topology.py", line 2286, in load_weights
    str(len(flattened_layers)) + ' layers.')

**Exception: You are trying to load a weight file containing 31 layers into a model with 30 layers.**

Is there an error in the way the ModelCheckpoint saves weights, for instance including input layer weights of 1?

**Comment by penguin2121** [comment]
So, I found a sort of fix.  If I save the model before I start training, it doesn't work, it gives me that error, but if I use the same code to save the model during a callback that runs on_train_begin, the model will have the same number of layers as the saved weights.  Is that intentional?  Is there a way to make it not require that?

**Comment by fchollet** [comment]
Update Keras.

**Comment by jbrownlee** [comment]
Wow, that was fast. Fix works for me. (found this ticket via google search)

**Comment by ylmeng** [comment]
Which version will not have the issue?
I mean, I am using 1.2.2, and updating to 2.0.x will generate tons of import errors...so I hope I can fix it in a lower version.
