### ISSUE TITLE
Doubts in recurrent.py LSTM model

### ISSUE THREAD

**Issue by SourKream** [fchollet/keras#2368]
I was looking through [recurrent.py](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py) as I wanted to implement a custom RNN node.

I don't understand what are [B_U](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L743) and [B_W](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L744) in the step function for LSTM. What are the these variables doing and where are they initialised? 
The new [state](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L763) that we passing out from the step function ([h, c]) contains only 2 elements so technically states[2] and states[3] should not exist.

Also why do we need to multiply the input with B_W [here](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L752)

Any clarification would be immensely helpful.

**Comment by fchollet** [comment]
These are dropout matrices, used when you are using the `dropout` arguments
in recurrent layers.

**Comment by SourKream** [comment]
Saw that. It was stupid of me to miss it.
