### ISSUE TITLE
Download error from the babi_rnn.py and babi_memnn.py

### ISSUE THREAD

**Issue by WI-KIWI** [fchollet/keras#2369]
Hi, thanks for the update to 1.0.1.
i'm trying to run the babi_rnn.py and babi_memnn.py, however, it raises a error like this:

```bash
Downloading data from http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-2.tar.gz
Traceback (most recent call last):
  File "babi_rnn.py", line 149, in <module>
    path = get_file('babi-tasks-v1-2.tar.gz', origin='http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-2.tar.gz')
  File "/home/zzhao/anaconda2/lib/python2.7/site-packages/keras/utils/data_utils.py", line 76, in get_file
    raise e
Exception: URL fetch failure on http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-2.tar.gz: None -- Forbidden
```

by typing the address http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-2.tar.gz 
in Browser i can download the file manually, so i guess the download not on Browser is banned by the website.
Btw, i have the Anaconda python 2.7.
Thanks for replying.

Best wishes

**Comment by dansbecker** [comment]
I can't replicate the error, and babi_rnn.py runs without raising an exception for me.  Tried it with both 2.7 and 3.5.

Wish I had a more helpful suggestion... any chance you are behind a firewall that might treat this traffic differently?

**Comment by fchollet** [comment]
The link works fine. You are almost certainly using a proxy or firewall that doesn't process connections outside of your browser. Not a Keras issue, in any case.

**Comment by gw0** [comment]
I also get the same "Forbidden" error when running the script, but manual downloading with browser or using `wget` works as expected. Tested on 2 machines with completely different ISPs and none of them is behind any proxy or firewall.

**Comment by gw0** [comment]
Maybe a comment with alternative instructions could be sufficient:

```bash
$ wget http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-2.tar.gz
$ mv tasks_1-20_v1-2.tar.gz ~/.keras/datasets/babi-tasks-v1-2.tar.gz
```

**Comment by WI-KIWI** [comment]
Thanks for the update, i also thought maybe it"s because of my ISP, and i tested it somewhere else, the same forbidden error. Anyway, i'll download it manually.

**Comment by 42** [comment]
Just got the same error and I'm definitely not on a network that blocks anything.  Should be a script issue.  Maybe because of python 2

**Comment by akhavr** [comment]
Just got the same error and I'm definitely not on a network that blocks anything. Should be a script issue. Maybe because of python 2

**Comment by gw0** [comment]
I mean, it is obvious that at `http://www.thespermwhale.com/` they are blocking access depending on user agent and they also have some sort of whitelist of IPs (the reason why it works for some). To confirm this I patched `keras/utils/data_utils.py` to fake the user agent in Python 2.7 (not a solution for Python 3.5) and it works.

```diff
--- data_utils.py.orig  2016-08-29 13:13:05.858506106 +0000
+++ data_utils.py       2016-08-29 13:13:34.058506828 +0000
@@ -6,7 +6,7 @@
 import sys
 import shutil
 import hashlib
-from six.moves.urllib.request import urlopen
+from six.moves.urllib.request import urlopen, Request
 from six.moves.urllib.error import URLError, HTTPError
 
 from ..utils.generic_utils import Progbar
@@ -30,7 +30,8 @@
                     reporthook(count, chunk_size, total_size)
                 yield chunk
 
-        response = urlopen(url, data)
+        req = Request(url, data=data, headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36'})
+        response = urlopen(req)
         with open(filename, 'wb') as fd:
             for chunk in chunk_read(response, reporthook=reporthook):
                 fd.write(chunk)
```

This is why I was recommending to add at least a comment to use `wget` or any other browser. Or should we fake the user agent?

**Comment by gw0** [comment]
Ah, actually #3536 was a rejected PR for exactly this.

**Comment by 42** [comment]
Responding from mobile, so I don't have the console, but I believe there
was a suggestion to do `wget`.  Which I did and went with the example
further

**Comment by fchollet** [comment]
Fixed the issue by uploading the dataset on AWS. I guess the original dude could not afford $0.45/month of bandwidth. Thankfully I can.

**Comment by erzaliator** [comment]
Got the same issue, found it was because of the proxy. Running the same script on a different network with no proxy worked for me.
