### ISSUE TITLE
problem of save/load model

### ISSUE THREAD

**Issue by benwu232** [fchollet/keras#2372]
HI, 

Thanks for making such a wonderful tool!

I'm using Keras 1.0. I want to save and load the model both the arch and the parameters. So I use the method in FAQ. Here is the code.

    def save_model(self, model, options):
        json_string = model.to_json()
        open(options['file_arch'], 'w').write(json_string)
        model.save_weights(options['file_weight'])

    def load_model(self, options):
        self.model = model_from_json(open(options['file_arch']).read())
        self.model.load_weights(options['file_weight'])
        return self.model

When I load model and use model.predict(), there is a error:
AttributeError: 'NoneType' object has no attribute 'predict'

Don't know why. If I don't load the model from file, just train a model and use it, everything seems ok.

I checked the issues, most people just need to load the parameters. Is it possible when I load the architecture, I overwrite the old model and loose the model.predict()?

Thanks again for making Keras!

Ben

**Comment by fchollet** [comment]
You need to compile a Keras model before using it.
On Apr 17, 2016 8:31 AM, "Wu, Bin(Ben)" <notifications@github.com> wrote:

HI,

Thanks for making such a wonderful tool!

I'm using Keras 1.0. I want to save and load the model both the arch and
the parameters. So I use the method in FAQ. Here is the code.

def save_model(self, model, options):
    json_string = model.to_json()
    open(options['file_arch'], 'w').write(json_string)
    model.save_weights(options['file_weight'])

def load_model(self, options):
    self.model = model_from_json(open(options['file_arch']).read())
    self.model.load_weights(options['file_weight'])
    return self.model

When I load model and use model.predict(), there is a error:
AttributeError: 'NoneType' object has no attribute 'predict'

Don't know why. If I don't load the model from file, just train a model and
use it, everything seems ok.

I checked the issues, most people just need to load the parameters. Is it
possible when I load the architecture, I overwrite the old model and loose
the model.predict()?

Thanks again for making Keras!

Ben

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/fchollet/keras/issues/2372>

**Comment by benwu232** [comment]
Thanks @fchollet !

I did a quick change of my code as follow. Seems still wrong. I saved model to files and load them into model2. I compared two models, they are not equal.  Then I use the two models to predict, the results are not the same. Any other suggestions?
 
Ben
  
  def save_model(self, model, options):
        json_string = model.to_json()
        open(options['file_arch'], 'w').write(json_string)
        model.save_weights(options['file_weight'])

    def load_model(self, options, pars):
        self.model = model_from_json(open(options['file_arch']).read())

        optimizer = self.def_optimizer(pars)
        self.model.compile(loss=pars['loss_type'], optimizer=optimizer, metrics=['accuracy'])
        self.model.load_weights(options['file_weight'])
        return self.model

**Comment by benwu232** [comment]
Thanks @fchollet !

I changed the code like this and it worked.

    def save_model(self, model, options):
        json_string = model.to_json()
        open(options['file_arch'], 'w').write(json_string)
        model.save_weights(options['file_weight'])

    def load_model(self, options, pars):
        self.model = model_from_json(open(options['file_arch']).read())
        self.model.compile(loss=pars['loss_type'], optimizer='sgd', metrics=['accuracy'])
        self.model.load_weights(options['file_weight'])
        return self.model

**Comment by dupsys** [comment]
@fchollet ,

Please, I need your help. I try to validate my test data using the already training result from the model but I got the following error:

##################
AttributeError Traceback (most recent call last)
in ()
1 # load weights into new model
----> 2 model_info.load_weights(save_best_weights)
3 predictions = model.predict([test_q1, test_q2, test_q1, test_q2,test_q1, test_q2], verbose = True)

AttributeError: 'History' object has no attribute 'load_weights'

In [ ]:
#####################

Below is the snippets of my code:

###Fitting model

save the best weights for predicting the test question pairs

save_best_weights = "weights-pairs1.h5"

checkpoint = ModelCheckpoint(filepath, monitor='loss', verbose=1, save_best_only=True, mode='min')

callbacks = [ModelCheckpoint(save_best_weights, monitor='val_loss', save_best_only=True),
EarlyStopping(monitor='val_loss', patience=5, verbose=1, mode='auto')]
start = time.time()
model_info=merged_model.fit([x1, x2, x1, x2, x1, x2], y=y, batch_size=64, epochs=3, verbose=True,
validation_split=0.33, shuffle=True, callbacks=callbacks)
end = time.time()
print("Minutes elapsed: %f" % ((start - end) / 60.))

#####evaluting

#load weights into a new model

model_info.load_weights(save_best_weights)
predictions = model.predict([test_q1, test_q2, test_q1, test_q2,test_q1, test_q2], verbose = True)

Regards

**Comment by schliffen** [comment]
Im trying to load json model with keras from json, but I got error!!: (this worked previously)

json_file = open( root + "checkpointsmodel_base_201948-154822.json" )
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

Full error log:

    self.do_wait_suspend(thread, frame, event, arg)
  File "/snap/clion/73/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_frame.py", line 125, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "/snap/clion/73/plugins/python/helpers/pydev/pydevd.py", line 889, in do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt

Original exception was:
Traceback (most recent call last):
  File "/snap/clion/73/plugins/python/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/snap/clion/73/plugins/python/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/clion/73/plugins/python/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/clion/73/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)

    loaded_model = model_from_json(loaded_model_json)
  File "/python3.5/site-packages/keras/models.py", line 379, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "python3.5/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "python3.5/site-packages/keras/engine/topology.py", line 2525, in from_config
    process_layer(layer_data)
  File "python3.5/site-packages/keras/engine/topology.py", line 2511, in process_layer
    custom_objects=custom_objects)
  File "python3.5/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "python3.5/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "python3.5/site-packages/keras/layers/core.py", line 730, in from_config
    printable_module_name='function in Lambda layer')
  File "python3.5/site-packages/keras/utils/generic_utils.py", line 161, in deserialize_keras_object
    fn = module_objects.get(function_name)
AttributeError: 'NoneType' object has no attribute 'get'
