### ISSUE TITLE
Is padding necessary for LSTM network?

### ISSUE THREAD

**Issue by gbezerra** [fchollet/keras#2375]
Hi,

I would like to input sequences of different length into an LSTM network without having to pad them (thus reducing the huge waste of memory). Is this possible?

I'm getting the following error when I try to input a list of lists or an array of arrays:

ValueError: ('Bad input argument to theano function with name "/opt/anaconda2/lib/python2.7/site-packages/keras/backend/theano_backend.py:484"  at index 0(0-based)', 'setting an array element with a sequence.')

I have no problems however when I use pad_sequences before I pass the input. Below is my code:

``` python
from keras.layers import Dense, Dropout, Activation
from keras.layers import LSTM
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
import pandas as pd
import config
from numpy import array, random
import pdb

def load_data(test_split = 0.2):
    print 'Loading data...'
    df = pd.read_csv(config.Data.feature_matrix)
    df['encoded_msg'] = df['encoded_msg'].apply(lambda x: \
        [int(e) for e in x.split()])
    df = df.reindex(random.permutation(df.index))

    X_train = df['encoded_msg'].values[:int(len(df) * (1 - test_split))]
    y_train = array(df['was_blocked'].values[:int(len(df) * (1 - test_split))])

    X_test = array(df['encoded_msg'].values[int(len(df) * (1 - test_split))])
    y_test = array(df['was_blocked'].values[int(len(df) * (1 - test_split))])

    #return pad_sequences(X_train) ,y_train, X_test, y_test
    return X_train ,y_train, X_test, y_test


def create_model(input_length):
    print 'Creating model...'
    model = Sequential()
    model.add(Embedding(input_dim = 188, output_dim = 50, input_length = input_length))
    model.add(LSTM(output_dim=256, activation='sigmoid', inner_activation='hard_sigmoid',
        return_sequences = True))
    model.add(Dropout(0.5))
    model.add(LSTM(output_dim=256, activation='sigmoid', inner_activation='hard_sigmoid'))
    model.add(Dropout(0.5))
    model.add(Dense(1, activation = 'sigmoid'))

    print 'Compiling...'
    model.compile(loss='binary_crossentropy',
                  optimizer='rmsprop',
                  metrics=['accuracy'])
    return model


X_train, y_train, X_test, y_test = load_data()
model = create_model(len(X_train[0]))

print 'Fitting model...'
hist = model.fit(X_train, y_train, batch_size=64, nb_epoch=10, validation_split = 0.1,
    verbose = 1)
```

Any help is highly appreciated.

Thanks!

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [ x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [ x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by philipperemy** [comment]
The padding is useful when you batch your sequences. If you don't want to mask, you have several options:

1 -  batch_size=1. You feed the sequences one by one and in this case you don't need to have them of the same length. Something like (from my memory):

```
for seq, label in zip(sequences, y):
   model.train(np.array([seq]), [label])
```

2 - Grouping samples by length (all sequences of length 5 together and all sequences of length 4 together)

I tried both these methods before. Batch of size 1 is indeed too slow (you don't have the batch parallel optimisation), and grouping samples is something I don't find too elegant.

So I would go for the masking.

Seems like you give an array and the function expects a list.

```
keras.preprocessing.sequence.pad_sequences(sequences, maxlen=None, dtype='int32')
```

**Comment by gbezerra** [comment]
Thanks @philipperemy , that's very helpful.

I'm not sure masking will work for me. Currently, my problem is that the GPU runs out of memory for batches larger than 64. I'd like to reduce the memory footprint by not having to pad the sequences so that I could run larger batches.

However, from what I read about masking, I would still have to send the full padded sequence into the network, which wouldn't reduce memory use.

Am I understanding it right?

Also, how did you manage to train the network by grouping sequences of same size? Do you run all epochs for a given size, then you move on to the next size?

Thanks again.

**Comment by philipperemy** [comment]
I'd like to reduce the memory footprint by not having to pad the sequences so that I could run larger batches.
=> **If you use the batch mode, all sequences must be of the same length inside your batch.** You can't help it. Maybe you can truncate your sequences if you have a large number of small sequences and very few big sequences. Because when you pad, you always take into account the largest of your sequences. So your matrix can be very sparse. This approach depends on the length distribution of your sequences (look at if you have a thin or fat tail on the right).

Also, how did you manage to train the network by grouping sequences of same size? Do you run all epochs for a given size, then you move on to the next size?
=> Yes. One epoch means you run through all your training set. Your epoch ends when you processed all the possible lengths (you can begin with the sequences of length=1, then length=2, ...). But I advised you to shuffle this order (by default, the order of the batches is random).

**Comment by braingineer** [comment]
I haven't tried grouping, but I have heard of some approaches that try to group by values when running batches have tried to do it in a stratification of a sorts.   Deep Mind uses this in their improved Experience Replay. They stratify the experiences by TD error so they can sample batches that relatively uniform across all TD errors.

Maybe one thing you could try to do, to find a middle ground, is to arrange the length of your sequences and then group those +- some value.  Then, you find some balance: the groups should be small enough that your stochastic sampling isn't ruined (correlated errors are bad and will result in a bad model).  The groups should also be large enough that you get the parallelization gains. 

@philipperemy  - when you have different sequence lengths, do you have to recompile the model? Or is the model happy not knowing the sequence length ahead of time? I usually have issues with those types of parameters so I over-do it and provide every size ahead of time.

**Comment by codekansas** [comment]
_I'd like to reduce the memory footprint by not having to pad the sequences so that I could run larger batches._

You can try `consume_less='mem'` on the RNN layers, it should help on your GPU and might actually speed up computation. I think most of the memory issues I had come from the RNN's hidden states, since if you're using an embedding, the RNN part is where you get a blowup (masking will help reduce this I believe, although I'm not sure).

To skip over padding for your RNNs, add a masking layer as suggested by @gbezerra although it doesn't work if you want to merge layers later on.

Someone really needs to get masking working for merge layers, at least for certain merge types.

**Comment by voletiv** [comment]
Sorry for the late reply, shouldn't:
```
X_test = array(df['encoded_msg'].values[int(len(df) * (1 - test_split))])
y_test = array(df['was_blocked'].values[int(len(df) * (1 - test_split))])
```
b:
```
X_test = array(df['encoded_msg'].values[int(len(df) * (1 - test_split))**:**])
y_test = array(df['was_blocked'].values[int(len(df) * (1 - test_split))**:**])
```
?

I added a ':' after `... * (1 - test_split))` in each line. So your training data is `data[**:**int(length*0.8)]` and test data is `data[int(length*0.8)**:**]`.

**Comment by xsung** [comment]
@gbezerra 

```python
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)
x_train = sequence.pad_sequences(x_train, maxlen=maxlen, truncating='post')  # zero padding
x_test = sequence.pad_sequences(x_test, maxlen=maxlen, truncating='post')    

model = Sequential()
model.add(Embedding(max_features, 128, mask_zero = True))  #  mask_zero is important
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
```
As the keras doc says:

> If mask_zero is set to True, the input value 0 will be a special "padding" that should be masked out.
Index 0 cannot be used in the vocabulary.

By default, value 0 would be considered as a common word in vocabulary, if **mask_zero=false**.
I guess **mask_zero = True** will work for no padding.
But i am not sure whether it will reduce memory.

**Comment by eromoe** [comment]
Ihave a padding quesion, which looks different : 

For example:

I want to train a model to detect wrong word .

1. I have 1 million sentences with different length. 
2. If a sentence length is  10,  I want LSTM learn 2 words surrounding current word ( so each word become 5 word) . So I need transform the sentence to  [10, 5] .
3. But the first word(doesn't have left words) and  right word (doesn't have right words) . So I need pad them.
4. Then use word2vec transform this sentence to  [10, 5, embedding_size]
5. trainning

Is my steps right ?  Looks like Keras doesn't have this feature built-in .

PS: 
I have some confusing with LSTM input.

1. Some pad all sentence to same length 
2. some split each word block(like I do above).  

I am not sure when to use 1 and 2 . 
Only understand 2 can use for squence tagging.

**Comment by Deltaidiots** [comment]
Hi I have a question regarding variable number of timesteps in a sample and even if i provide None for timesteps in input_shape. it doesn't work 
`from keras.models import Sequential
from keras.layers import LSTM, Dense, Flatten
import numpy as np

# expected input data shape: (batch_size, timesteps, data_dim)
model = Sequential()
model.add(LSTM(1, return_sequences=True,
               batch_input_shape=(2,None, 1)))  

model.add(TimeDistributed(Dense(1, activation='softmax')))

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

# Generate dummy training data
x_train = [[[0.41668948],
        [0.38072783],
        [0.70242528]],

       [[0.65911036],
        [0.01740353],
        [0.03617037],
       [0.04617037]]]
x_train = np.asarray(x_train)
y_train = [[[0.41668948],
        [0.38072783],
        [0.70242528]],

       [[0.65911036],
        [0.01740353],
        [0.03617037],
       [0.04617037]]]
y_train = np.asarray(y_train)


model.fit(x_train, y_train,
          epochs=10)`
ValueError                                Traceback (most recent call last)
<ipython-input-144-d843a8bcd9ad> in <module>
     36 
     37 model.fit(x_train, y_train,
---> 38           epochs=10)

c:\python37\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
    950             sample_weight=sample_weight,
    951             class_weight=class_weight,
--> 952             batch_size=batch_size)
    953         # Prepare validation data.
    954         do_validation = False

c:\python37\lib\site-packages\keras\engine\training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)
    749             feed_input_shapes,
    750             check_batch_axis=False,  # Don't enforce the batch size.
--> 751             exception_prefix='input')
    752 
    753         if y is not None:

c:\python37\lib\site-packages\keras\engine\training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    126                         ': expected ' + names[i] + ' to have ' +
    127                         str(len(shape)) + ' dimensions, but got array '
--> 128                         'with shape ' + str(data_shape))
    129                 if not check_batch_axis:
    130                     data_shape = data_shape[1:]

ValueError: Error when checking input: expected lstm_74_input to have 3 dimensions, but got array with shape (2, 1)
