### ISSUE TITLE
General initialization for layer weight

### ISSUE THREAD

**Issue by joelthchao** [fchollet/keras#2377]
During construction of layers such as Convolution2D and Dense. The argument `init` can only be set by name (e.g. 'normal', 'uniform'). Is there a good way to pass parameter such as 'scale', 'loc' into initialization? Or we should manually initialize weights and pass by argument `weights` for each layer?

**Comment by ArturoDeza** [comment]
Why was this closed? Was this solved; Updates?

**Comment by joelthchao** [comment]
This is solved, now Keras has [Initializer](https://github.com/fchollet/keras/blob/master/keras/initializers.py) class and you can customize your own one.
