### ISSUE TITLE
'Model' object has no attribute 'predict_function' - after loading saved model

### ISSUE THREAD

**Issue by Froskekongen** [fchollet/keras#2379]
There appears to be a minor piece missing in the new functional API.

To reproduce:
```
model=some functional model
modeljson=model.to_json()
model.save_weighths(path)
model2=model_from_json(modeljson)
model2.load_weigths(path)
model2.predict(...)
```

It's possible to fix by calling model.compile(...) after loading. This may be intentional behaviour, but I am not sure.

```
AttributeError                            Traceback (most recent call last)
<ipython-input-2-7f288cbaeaed> in <module>()
----> 1 modelWrap.predict(pList[0])

/home/erlenda/repos/content-classification/model_loader.py in predict(self, inputD)
     41         #maxlen = 168
     42         feed_dict={'input_text':seq,'input_titles':seq_title}
---> 43         predictions=self.model.predict(feed_dict)
     44         predictions['hovedkategori']=predictions['hovedkategori'][0]
     45         predictions['underkategori']=predictions['hovedkategori'][0]

/usr/local/lib/python3.5/dist-packages/keras/engine/training.py in predict(self, x, batch_size, verbose)
   1098         else:
   1099             ins = x
-> 1100         self._make_predict_function()
   1101         f = self.predict_function
   1102         return self._predict_loop(f, ins,

/usr/local/lib/python3.5/dist-packages/keras/engine/training.py in _make_predict_function(self)
    667 
    668     def _make_predict_function(self):
--> 669         if self.predict_function is None:
    670             if self.uses_learning_phase:
    671                 inputs = self.inputs + [K.learning_phase()]

AttributeError: 'Model' object has no attribute 'predict_function'
```

**Comment by trane293** [comment]
This is intended behavior I suppose. I've read a similar issue before here and the mods recommended using model.compile before using predict().

**Comment by Froskekongen** [comment]
Closed, as this seems to be intended behavior.

**Comment by strangeice** [comment]
I am following this tutorial:  https://blog.keras.io/building-autoencoders-in-keras.html
When I reach this step, I got an error message similar to above

    # encode and decode some digits
    # note that we take them from the *test* set
    encoded_imgs = encoder.predict(x_test)

AttributeError: 'Model' object has no attribute 'predict_function'

I am new to this stuff.   I guess it might be trivial for you guys to figure out what's wrong.  Can you give some hint? thx

**Comment by strangeice** [comment]
well, I tried to add 
    encoder.compile(...) and decoder.complile(...)
It will run, but the predicted results are trash.   So this is not the right fix.  I guess the autoencoder.compile(...) should provide the right prediction function, it does not.   Is it an unexpected bug?  I will try to see if it works in previous version.

**Comment by trane293** [comment]
The model must be compiled before predictions can be made, so the error is justified. Regarding the results being trash, that's subjective, can you specify some more detail on the problem you are facing? The encoder.compile() function will compile the encoder model, which will "predict" or rather "encode" the input image to vector of 'd' dimensions. It is not supposed to make much sense visually to you if that's what you are looking at. The statement autoencoder.compile() will compile the whole autoencoder network, and will "predict" or "reconstruct" the input image with a given accuracy. The results of this network is what will make sense to you visually. If they are not, try retraining the model with more examples, or play with hyperparameters.

**Comment by strangeice** [comment]
Thanks trane293 for the reply!
I tried to use 2 approaches to predict over x_test

encoded_imgs = encoder.predict(x_test)
decoded_imgs = decoder.predict(encoded_imgs)

or
decoded_imgs = autoencoder.predict(x_test)

both produce the similar bad results, much worse than the results shown in the tutorial.   Please check out the attached picture.
![figure_1](https://cloud.githubusercontent.com/assets/7541501/18344053/5f2be968-75e8-11e6-9759-9a88a1d8321f.png)

**Comment by tommydino93** [comment]
Hello,
I am facing the same issue with TF 2.4. I am creating a model and loading some weights from a previous training with the [load_weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#load_weights) method. I am NOT compiling the model since I only want to perform inference, but this gives me the error:

`AttributeError: 'Functional' object has no attribute 'predict_function'
`

If I compile the model the same way I did during training, then the problem seems to be solved. However, this does not make sense to me. There shouldn't be the need to compile the model if we only want to perform inference. 

Or am I missing something?

**Comment by kamranabbas20** [comment]
Hi. I am having the same issue with TF 2.4.1. The code runs normally and then stops at random iterations while using Joblib.
`AttributeError: 'Functional' object has no attribute 'predict_function'

Has the solution been found for this?
