### ISSUE TITLE
i use the keras to train my model and save the model to pkl format .My question is to show the detailed information about the model_pkl .I don't know how to do .Can you give me some advice please?

### ISSUE THREAD

**Issue by alyato** [fchollet/keras#2381]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by joelthchao** [comment]
From FAQ: [How can I save a model](http://keras.io/getting-started/faq/#how-can-i-save-a-keras-model)
Load your model and call `model.summary()` to see detail information

**Comment by alyato** [comment]
Thanks. i check the ( how can I save a model) and don't find the SUMMARY function. Then i load my model and call the model.summary(). Like this.
![mo](https://cloud.githubusercontent.com/assets/6815071/15102421/dcaa768a-155c-11e6-8b0f-726b8e913121.png)
But it show me wrong .
![sum](https://cloud.githubusercontent.com/assets/6815071/15102456/459e841a-155d-11e6-954f-39a54868b5d9.png)
