### ISSUE TITLE
AttributeError: 'Sequential' object has no attribute 'predict'

### ISSUE THREAD

**Issue by andyyuan78** [fchollet/keras#240]
ubgpu@ubgpu:~/github/keras/examples$ sudo python lstm_text_generation.py
[sudo] password for ubgpu: 
Using gpu device 0: GeForce GTX 970
Downloading data from https://s3.amazonaws.com/text-datasets/nietzsche.txt
606208/600901 [==============================] - 2s     
corpus length: 600901
total chars: 59
nb sequences: 200294
Vectorization...
Build model...
/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_perform_ext.py:133: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *

--------------------------------------------------
Iteration 1
Epoch 0
200294/200294 [==============================] - 201s - loss: 3.0126     

----- diversity: 0.2
----- Generating with seed: " general,
every huma"
 general,
every humaTraceback (most recent call last):
  File "lstm_text_generation.py", line 95, in <module>
    preds = model.predict(x, verbose=0)[0]
AttributeError: 'Sequential' object has no attribute 'predict'
ubgpu@ubgpu:~/github/keras/examples$ 
ubgpu@ubgpu:~/github/keras/examples$

**Comment by fchollet** [comment]
The API changed a few weeks ago (Keras is still in alpha, changes happen). Just pull master and reinstall.
