### ISSUE TITLE
Issue with evaluate_generator() and datagen_flow()

### ISSUE THREAD

**Issue by EnriqueSMarquez** [fchollet/keras#2400]
Hello all,

I am having a problem when using the evaluate_generator() method or when using datagen.flow().

Example:
`for X_batch, Y_batch in datagen.flow(X_train, Y_train,batch_size=128):
                  model.train_on_batch(X_batch, Y_batch)`

`model(dataAugmentation.flow(X_val,Y_val,batch_size=128),len(X_val))`

The error I am getting is:

UnboundLocalError: local variable 'index_array' referenced before assignment.

Any ideas?

Thank you.

EM

**Comment by joelthchao** [comment]
Do you call `datagen.fit(X_train)` before `datagen.flow`? Could you provide more details on your error message (e.g. file, line number)?

**Comment by EnriqueSMarquez** [comment]
If you add the line `    model.evaluate_generator(datagen.flow(X_test, Y_test,
                        batch_size=batch_size),val_samples=len(X_test))` to the cifar10_cnn.py example, the error is generated.

**Comment by joelthchao** [comment]
@EnriqueSMarquez My Keras is in version '1.0.0' with TensorFlow backend. Adding that line to the `cifar10_cnn.py` doesn't produce any error in my case. Maybe you can check your version and update to the latest one?

**Comment by EnriqueSMarquez** [comment]
I have updated it. I am running with theano as backend. My Keras version is 1.0.1 and my then version is 0.9.0.

Thank you.
