### ISSUE TITLE
LSTM many to many mapping problem

### ISSUE THREAD

**Issue by mininaNik** [fchollet/keras#2403]
I want to implement the forth architecture from the left (first many to many):
![1](https://cloud.githubusercontent.com/assets/17245428/14640043/e4cdf91c-063f-11e6-8844-c89a9e134339.png)

I my case the length of input and outputs aren't equal (I mean that number of blue and red units aren't equal)! I have n samples to train the NN then the shape of input is n\*n_prev\*1 and the out shape is n\*n_nxt\*1. My model is as follows:

    batch_size = 50 
    n_prev = 100
    n_nxt = 5
    print("creating model...")
    unit_number = n_nxt
    model = Sequential()
    model.add(LSTM(unit_number,
               batch_input_shape=(batch_size, n_prev, 1),
               forget_bias_init='one',
               return_sequences=True,
               stateful=True))
    model.add(Dropout(0.2))
    model.add(LSTM(unit_number,
               batch_input_shape=(batch_size, n_prev, 1),
               forget_bias_init='one',
               return_sequences=False,
               stateful=True))
    model.add(Dropout(0.2))
    model.add(Dense(n_nxt))
    model.compile(loss='mse', optimizer='rmsprop')

    print('Training')
    numIteration = len(X_train)/batch_size
    for i in range(epochs):
        print('Epoch', i, '/', epochs)
        for j in range(numIteration):
            print('Batch', j, '/',numIteration,'Epoch', i)
            model.train_on_batch(X_train[j*batch_size:j*batch_size+batch_size,], y_train[j*batch_size:j*batch_size+batch_size,])
         
        model.reset_states()
       

    print('Predicting')
    predicted_output = model.predict(X_test, batch_size=batch_size)

But I think I have implemented the third one (because return_sequences=False in the second LSTM layer, according to this article: https://github.com/Vict0rSch/deep_learning/tree/master/keras/recurrent ). I think I have one output from the second LSTM layer like third architecture (from the left) and then it is extended to five outputs by Dense layer. When I set return_sequences=True in the second LSTM layer I get the following error:

    Traceback (most recent call last):
     File "/home/mina/Documents/research/one cores (LSTM) seq2seq  one core vector2vector  train on batch statefull 15/KerasLSTM.py", line 259, in <module>
    main()
     File "/home/mina/Documents/research/one cores (LSTM) seq2seq  one core vector2vector  train on batch statefull 15/KerasLSTM.py", line 200, in main
       model.add(Dense(n_nxt))
     File "/usr/local/lib/python2.7/dist-packages/keras/layers/containers.py", line 68, in add
    self.layers[-1].set_previous(self.layers[-2])
     File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 85, in set_previous
    str(layer.output_shape))
    AssertionError: Incompatible shapes: layer expected input with ndim=2 but previous layer has output_shape (1, 100, 5)

Can I omit dense layer? As I understood If I don't set return_sequences=True I wil have the third architecture, is it right? Is there any problem that the length of the input is different from the output length?

**Comment by carlthome** [comment]
You're on the right track. Set return_sequences=True then make sure to wrap Dense with a TimeDistributed "wrapper" layer. [See here](https://github.com/fchollet/keras/blob/master/keras/layers/wrappers.py#L42). TimeDistributed() is Keras' way of applying a layer to several time steps.

**Comment by mininaNik** [comment]
@carlthome : Thanks a lotttttt. 
My Keras doesn't have wrappers sub-module to import TimeDistributed! Is it possible?

**Comment by fluency03** [comment]
@mininaNik `TimeDistributedDense` is the old layer class in 0.3.3 version. In Keras>=1.0, you will find the wrapper `TimeDistributed()`, where you can use it by putting `Dense()` into this wrapper.

**Comment by mininaNik** [comment]
@fluency03 Thank you.
The point is that my Keras version is 0.3.1 and It doesn't have wrapper  and can't import this module. I might need to upgrade keras!

**Comment by fluency03** [comment]
@mininaNik I think this will do:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

**Comment by mininaNik** [comment]
Thank you @fluency03. I upgrade it and it works. 

This is my final code. I want to predict "n_nxt" steps ahead by using  "n_prev" previous values. I have n samples to train the NN then the shape of input is n*n_prev*1 and the out shape is n*n_nxt*1 


     n_nxt = 5
     batch_size = 50
     epochs = 12
     n_prev = 100
   
  
      print("creating model...")
      unit_number = 12
      model = Sequential()
      model.add(LSTM(unit_number,
               batch_input_shape=(batch_size, n_prev, 1),
               forget_bias_init='one',
               return_sequences=True,
               stateful=True))
      model.add(Dropout(0.2))
      model.add(LSTM(unit_number,
               batch_input_shape=(batch_size, n_prev, 1),
               forget_bias_init='one',
               return_sequences=True,
               stateful=True))
     model.add(Dropout(0.2))
     model.add(TimeDistributed(Dense(n_nxt)))
     model.compile(loss='mse', optimizer='rmsprop')

    print('Training')
    numIteration = len(X_train)/batch_size
    for i in range(epochs):
        print('Epoch', i, '/', epochs)
        for j in range(numIteration):
         print('Batch', j, '/',numIteration,'Epoch', i)
         model.train_on_batch(X_train[j*batch_size:j*batch_size+batch_size,], y_train[j*batch_size:j*batch_size+batch_size,])

     model.reset_states()

    print('Predicting')
    predicted_output = model.predict(X_test, batch_size=batch_size)

my model is as follows:
![111](https://cloud.githubusercontent.com/assets/17245428/14676125/5a262cbc-070c-11e6-9333-b92832ee8656.png)


Since my batch_size is 50, the input shape for each training step is: (50, 100, 1)
According to the model the output shape is (50, 100,5 ), but I want this shape: (50, 5, 1).
Could you please help me to solve this problem?

**Comment by fluency03** [comment]
I guess what you want is: 

input shape is (50, 100, 12), output shape is (50, 5, 12)

**Comment by mininaNik** [comment]
output shape=(nb_sample, time_dimension, input_dim)

my input matrix is n\*100\*1 and output dim is n\*5\*1  (I want to predict 5 steps ahead by using 100 previous values) and my input_dim and output_dim are 1. When I feed the NN nb_sample is set to batch_size automatically (nb_sample =batch_size). Since I set number of units for middle layers to 12 (I choose it for now reason and it can be changed) the last entry of the output shape has changed to 12.

The shape that I used for training the network is as follows: (batch_size,100,1)=(50,100,1) and I expect to predict five steps ahead and have (50,5,1) as output shape.

**Comment by fluency03** [comment]
Then I think this `model.add(TimeDistributed(Dense(n_nxt)))` should be actually `model.add(TimeDistributed(Dense(1)))` since you single input is with dimension (1, 1, 1) instead of (1, 1, input_length).  If it is (1, 1, input_length), then it should be `model.add(TimeDistributed(Dense(input_length)))`.

**Comment by mininaNik** [comment]
shape=(nb_sample, time_dimension, input_dim)

time_dimension = 100 for input, time_dimension=5 for output,and nb_sample=batch_size=50. Since I have only one time series my input_dim is 1. If I use model.add(TimeDistributed(Dense(1))), then the output shape will be (50,100,1) which should be (50,5,1). For your second suggestion ,model.add(TimeDistributed(Dense(input_length))), the output shape will be (50,100,100). My out put should be (50,5,1). The point here is that I can't change time_dimension form 100 to 5!

**Comment by fluency03** [comment]
No. You did not understand my point. 

I said the parameter of `TimeDistributed(Dense(parameter))` should be the number of classes. It has nothing to do with the timesteps `n_nxt` and  `n_prev` here. 

As to your exactly problem, I said I am not sure whether Keras supports input and output with different timesteps like `(nb_sample, 100, 1)` -> `(nb_sample, 5, 1)`. @fchollet, please confirm this or give some suggestions.  

However, if you train your model well as `(nb_sample, 100, 1)` -> `(nb_sample, 1, 1)`, it will be capable of predicting the next several data. 

Or, if you train your model as `(nb_sample, 100, 1)` -> `(nb_sample, 100, 1)`, but for the data `X` and `y`, instead of letting them have one time difference, what about letting them have the time difference as `n_nxt` you want.

**Comment by mininaNik** [comment]
@fluency03 Thanks a lottt.
Yes I misunderstood you :) I think if @fchollet confirms that keras doesn't support input and output with different timesteps, then the best way for me is testing your last suggestion.

**Comment by fluency03** [comment]
Or, have you considered custom layer [here](http://keras.io/layers/writing-your-own-keras-layers/) for reshaping the data?

**Comment by mininaNik** [comment]
Thank you. No I haven't. I will check it.

**Comment by carlthome** [comment]
So your current model ends with `model.add(TimeDistributed(Dense(n_nxt)))` meaning that you apply a dense operation to your input data and return n_nxt number of outputs **per input timestep**. This is not what your target data is right? Read up on encoder-decoder networks. Here's a basic example stolen from @EderSantana from https://github.com/fchollet/keras/issues/562.

```
model = Sequential()
model.add(LSTM(inp_dim, out_dim, return_sequence=False))  # Encoder
model.add(RepeatVector(sequence_length))
model.add(LSTM(out_dim, inp_dim), return_sequence=True)  # Decoder
```

@fluency03 Cheers! KTH represent! :smile:

**Comment by fluency03** [comment]
@mininaNik  this [addition_rnn](https://github.com/fchollet/keras/blob/master/examples/addition_rnn.py) is indeed a good example and can solve your problem.   

Thanks @carlthome ! Cheers, KTH ! :)

**Comment by mininaNik** [comment]
@fluency03 Thanks a lot :+1: 
Cheers :)

**Comment by mininaNik** [comment]
The output_dim specifies the length of the created vector by encoder. What is your idea about this value? Do you know that having large value is better or it should be small?

**Comment by carlthome** [comment]
That's a question for Google Scholar. Typically smaller, in autoencoder settings (otherwise what would be the point, right?)  but an argument can be made for having a larger hidden layer size as a type of regularization apparently. Search! Also, since this issue has been resolved please close it.

**Comment by mininaNik** [comment]
@carlthome You are right. Thank you.

**Comment by vinayakumarr** [comment]
Any body having character based text classification code in keras like in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/text_classification_character_rnn.py

**Comment by mininaNik** [comment]
@vinayakumarr Sorry I don't have.

**Comment by CuriousCat-7** [comment]
@carlthome Actually I'm not happy to get this result, for actually, the encoder-decoder model just use join two LSTMs to fix this problem. That means you use first LSTM to do a summary and the second LSTM decode the summary. But in practice, we sometimes need to deal with a quite large sequence, and we will lose most of the information if we use a small LSTM doing the summay. And in paper Neural Turing Machine (you can google it), it has been proved that the performance will drop largely if the sequence number up to 20 in some cases.

So we still need a way to implement the first many-to-many case.

**Comment by carlthome** [comment]
Note that the NTM has been superseded by the DNC but I've heard that both are finicky during training and that a two-layer GRU is a better choice for most applications. Regardless, many-to-many is only straightforward if each training example has a constant ratio of input sequence length to output sequence length, otherwise seq2seq (the encoder-decoder variant you describe) were any number of input timesteps can be mapped to any number of output timesteps (like in automatic speech recognition) is required.

To avoid compressing the information in a seq2seq it seems beneficial to add some [attention mechanism](https://arxiv.org/abs/1409.0473) where you design additional inputs to the decoder about what input timesteps were important. For example:

![image](https://user-images.githubusercontent.com/1595907/27697164-c91205f4-5cf3-11e7-88c5-20e6a5d96476.png)
