### ISSUE TITLE
Input dimension issue in seq2seq model for Machine Translation

### ISSUE THREAD

**Issue by shashankg7** [fchollet/keras#2409]
I am using the following model for Machine Translation task :

```
    model = Sequential()
    model.add(Embedding(len(self.proproces.vocab_hind), 128,
                        input_length=self.maxlen))
    model.add(RNN(128))#, input_shape=(100, 128)))
    model.add(RepeatVector(self.maxlen))
    model.add(RNN(128, return_sequences=True))
    model.add(TimeDistributedDense(len(self.proproces.vocab_en)))
    model.add(Activation('softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam')#,
```

maxlen is 128 here. I am training this model on batches (due to memory constraint). 

To perform prediction I am using the following code:

X = (sequence of ints with length maxlen)
model.predict(X)

I am getting following error:

ValueError: GpuReshape: cannot reshape input of shape (32, 128) to shape (0, 128, 128).

I am not sure why is it taking 32 as input size, it should take 128 as input size and produce (128, 128) vector.

Can anyone help me out here?

**Comment by jimi0902** [comment]
Can you show us the values of all your params? such as self.proproces.vocab_en, self.maxlen etc.
