### ISSUE TITLE
Why nb_worker deprecated?

### ISSUE THREAD

**Issue by albertomontesg** [fchollet/keras#2419]
I would like to know why at the model's methods which use a generator, has the argument `nb_worker deprecated.
There is any way to do it now correctly to have multiple threads fetching for your data?
Because in my case I work with a dataset made up by videos, it has an increment of speed fetching the data in multiple threads rather in only one.

**Comment by fchollet** [comment]
What is your speed up with Keras 0.3.3 (with multiple workers) vs. Keras 1.0?

Can you share the code of your generator?

**Comment by carlthome** [comment]
I'd also like to see this return. Duplicate issue (sorry): https://github.com/fchollet/keras/issues/2554

**Comment by fchollet** [comment]
Did you have a setup where you could see significant speedup from using
multiple workers?

The reason it was removed was because it was not clear that a same Python
generator could be run in two threads concurrently.

**Comment by carlthome** [comment]
Yes, absolutely! I'm doing sequence modelling and almost all of the preprocessing could be handled in parallel per sequence. :cake: 

Get your point though, a generator is not thread-safe. You already have the queue though. Couldn't the responsibility be on the user that their data generator must be thread-safe upon ever next() call?

Oh, I don't know... Multi-threading is hard. It would probably make more sense to work parallelization into the preprocessing code, actually. :cactus: 

So uh, nvm.

**Comment by roryhr** [comment]
Here's what I was thinking, you can use `joblib` as a drop-in replacement for list comprehensions and it does the parallelization (threading or multiprocessing) for you.

[Simple parallelization idea](https://github.com/roryhr/keras/commit/376f552cd8a04aca994f3b31ec34a4eefb1cb18f)

**Comment by carlthome** [comment]
@roryhr, thougts? https://github.com/fchollet/keras/pull/3049
