### ISSUE TITLE
Serialization with yaml is broken

### ISSUE THREAD

**Issue by Dapid** [fchollet/keras#2420]
Loading a functional API model from yaml doesn't work, as it is mussing `predict_function`. Example:

```
from keras.layers import Input, Dense
from keras.models import Model
from keras.models import model_from_yaml

import numpy as np

inputs = Input(shape=(784,))

x = Dense(64, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

model = Model(input=inputs, output=predictions)
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
yaml = model.to_yaml()

model = model_from_yaml(yaml)
model.predict(np.random.random((20, 784)))
```
It spits: `'Model' object has no attribute 'predict_function'`

Adding it by hand seems to be enough to make it work:

```
model.predict_function = None
model._function_kwargs = dict()
```

**Comment by Dapid** [comment]
Related: JSON had the same problem, it seems fixed now
https://github.com/fchollet/keras/issues/2197

**Comment by fchollet** [comment]
You need to compile the model after deserializing it.

**Comment by Dapid** [comment]
Oh. That should go in the documentation. I'll make a PR.

**Comment by RaffEdwardBAH** [comment]
@fchollet  I just had this issue. Before 1.0 it would work without having to call compile (at least when loading a graph model), so this is a breaking change that isn't documented. Its also very odd to have to give a optimizer to compile a model when its only going to be used for prediction.
