### ISSUE TITLE
layers_by_depth in  in https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1675

### ISSUE THREAD

**Issue by sordonia** [fchollet/keras#2432]
Given the error:

Traceback (most recent call last):
  File "test.py", line 54, in <module>
    train_model = Model(input=[x, y, a], output=d_i)
  File "/home/alessandro/.local/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/topology.py", line 1681, in **init**
    layers_for_depth = layers_by_depth[depth]
KeyError: 0

in https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1675

should the line be:

depth_keys = list(layers_by_depth.keys())

?

Thanks

**Comment by braingineer** [comment]
This happened to me a minute ago.  I debugged to the point where I noticed it was because I was reusing a dropout for two different inputs.  Are you doing this?  If not, sorry this isn't more helpful.
