### ISSUE TITLE
how to  get the layer output of cnn model in the newest version?

### ISSUE THREAD

**Issue by lji72** [fchollet/keras#2438]
I used to use  
"get_feature = theano.function([model_best.layers[0].input],model_best.layers[17].get_output(train=False),allow_input_downcast=False) "  
to get the output  of a layer  of a cnn model. But in the newest version of keras, it doesn't  have the function  "get_output()".  How can I get the output of  a layer of cnn model in the newest version?
I'm very grateful if you can give some advice.

**Comment by zgmming** [comment]
I met the same issue, 

>>> model.layers[7].get_output()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'Dense' object has no attribute 'get_output'

**Comment by joelthchao** [comment]
Try `model.layers[7].output_shape`?
