### ISSUE TITLE
e...How to get the details of K?

### ISSUE THREAD

**Issue by nightinwhite** [fchollet/keras#2439]
HI , guys
I want to write my own layer recently,but when I read source code of CNN and RNN I can not understand what K is really do,and I can not find the code of K.
could anyone help me ?
any suggestions about how to understand writing custom layers is useful for me

**Comment by kgrm** [comment]
If you look at the import headers, "K" is used an an alias for keras.backend ( `import keras.backend as K` ). The theano backend code is at https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py .
