### ISSUE TITLE
Use Keras/Theano framework to train on large scale image dataset.

### ISSUE THREAD

**Issue by kli-nlpr** [fchollet/keras#2440]
Hi, guys, I am looking for tutorials on using Keras training on large scale dataset.
I noticed that the most difficult part is how to effectively load batches (with augmentation) onto GPU when Keras is training on another batch.

Does anyone successfully did this? Example code is appreciate.

**Comment by mguillau** [comment]
Hi,

Not sure it answers your question exactly but I've found this page to contain interesting information about buffering batch generation: http://jimgoo.com/buffered-gens/

**Comment by kli-nlpr** [comment]
@mguillau Thank you very much. This is super useful.
