### ISSUE TITLE
Shared Embeddings with different input lengths

### ISSUE THREAD

**Issue by tstandley** [fchollet/keras#2442]
I have a situation where I want to split a sentence into three different chunks...

consider the following sentence, where the word 'sat' is called the pivot:
The cat [sat] on the mat 

The words on the left of the pivot and the words on the right of the pivot are fed into GRU units after they get embedded.

However, I want to embed the pivot too, but I can't figure out how to share the embedding layer among the 3 pieces.

Using the functional API I can share the embedding layers for the pre-pivot and post-pivot pieces like so:

`pre_pivot_input = Input(shape=(max_sequence_length,), dtype='int32')`
`post_pivot_input = Input(shape=(max_sequence_length,), dtype='int32')`

`shared_embedding = Embedding(vocab_size, embedding_dimension, weights=embedding_weights, input_length=max_sequence_length, mask_zero=True)`

`pre_pivot_vectors = shared_embedding(pre_pivot_input)`
`post_pivot_vectors = shared_embedding(post_pivot_input)`

`pre_pivot_embedding = getRecurrantFunctional(pre_pivot_vectors)`
`post_pivot_embedding = getRecurrantFunctional(post_pivot_vectors)`

`pivot_input = Input(shape=(1,), dtype='int32', name='pivot_input')`
`second_embedding = Embedding(vocab_size, embedding_dimension, weights=embedding_weights, input_length=1)`
`pivot_embedding = Reshape((embedding_dimension,))(second_embedding(pivot_input))`

`concat = merge([pre_pivot_embedding, pivot_embedding, post_pivot_embedding], mode='concat')`

Is there any way to get these two embeddings to be the same? If not, do you have any suggestions whereby I might achieve something similar?

Thanks!

**Comment by braingineer** [comment]
You have two options:

1.  in the `embeddings` class, do something similar to the following. I did this not only because I had a similar problem, but I also wanted to embed a 5 tensor. 

```python 
    def get_output_shape_for(self, input_shape):
        if len(input_shape) > 2: 
            return input_shape + (self.output_dim,)
        
        if not self.input_length:
            input_length = input_shape[1]
        else:
            input_length = self.input_length
        return (input_shape[0], input_length, self.output_dim)
```

2.  create a shared variable ahead of time with `K.variable(someW)` where `someW` is a numpy matrix of the embedding shape you desire. I recommend `someW` coming from a glorot or similar initialization (find them in keras).  Then, pass your shared variable into two different embeddings layers.  Theano (and I'm presuming Tensorflow) will recognize they are the same weight matrix and update accordingly.

**Comment by tstandley** [comment]
Hey @braingineer,

Thanks for your ideas! I really want to implement the first idea. Can I get a little more detail?

You are proposing that I edit embeddings.py and add the code you wrote to the class? How do I buld the model once that has been accomplished? Will the model still correctly serialize and correctly .to_json()?

**Comment by braingineer** [comment]
It should serialize/etc. It's actually a more accurate/general shape, anyway.  You can embed any sized matrix---all it will do is add a dimension that is the embedding size.   I'm currently saving models and the weights are reloading fine enough; I haven't tried the json config load though.  I don't see why it would affect anything. 

If you peek at the embeddings class, you'll see its config function:

```python
    def get_config(self):
        config = {'input_dim': self.input_dim,
                  'output_dim': self.output_dim,
                  'init': self.init.__name__,
                  'mask_zero': self.mask_zero,
                  'activity_regularizer': self.activity_regularizer.get_config() if self.activity_regularizer else None,
                  'W_regularizer': self.W_regularizer.get_config() if self.W_regularizer else None,
                  'W_constraint': self.W_constraint.get_config() if self.W_constraint else None,
                  'dropout': self.dropout}
        base_config = super(Embedding, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
```

There's no `input_length` being saved.  

If you're worried, try out some smaller models and do some sanity checks.

It should also be noted, though, that when I use mine, I am fully specifying the input batch shape.   I'm not sure if this is vital, but I didn't want an implied `None` floating around in case the model guessed incorrectly what it was supposed to be, or in case I created too ambiguous of a situation.

**Comment by ahmadpgh** [comment]
@tstandley I was wondering if you found a way around your problem? If so, I have a similar scenario to your use-case, and I'll be thankful if you let me know how you dealt with it

**Comment by tstandley** [comment]
Unfortunately, I don't remember. Did @braingineer s solution not work?

**Comment by FremyCompany** [comment]
FWIW, I just created an embedding layer of input size 1, then used timeDistributed and reshape layers to achieve what I wanted.

**Comment by brian36** [comment]
> FWIW, I just created an embedding layer of input size 1, then used timeDistributed and reshape layers to achieve what I wanted.

thank you - this is the solution I needed as well.  For reference, the TimeDistributed layer is here:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/TimeDistributed
