### ISSUE TITLE
unable to load model from json string after upgrading keras to 1.0.1

### ISSUE THREAD

**Issue by suraj-deshmukh** [fchollet/keras#2443]
i have a keras model saved in json format but i am unable to load json model using model_from_json() function after upgrading to 1.0.1

    {"layers": [{"layers": [{"layers": [{"name": "LSTM", "inner_activation": "hard_sigmoid", "go_backwards": false, "output_dim": 512, "input_shape": [30, 300], "stateful": false, "cache_enabled": true, "init": "glorot_uniform", "inner_init": "orthogonal", "input_dim": 300, "return_sequences": true, "activation": "tanh", "forget_bias_init": "one", "input_length": null}, {"name": "LSTM", "inner_activation": "hard_sigmoid", "go_backwards": false, "output_dim": 512, "stateful": false, "cache_enabled": true, "init": "glorot_uniform", "inner_init": "orthogonal", "input_dim": 512, "return_sequences": true, "activation": "tanh", "forget_bias_init": "one", "input_length": null}, {"name": "LSTM", "inner_activation": "hard_sigmoid", "go_backwards": false, "output_dim": 512, "stateful": false, "cache_enabled": true, "init": "glorot_uniform", "inner_init": "orthogonal", "input_dim": 512, "return_sequences": false, "activation": "tanh", "forget_bias_init": "one", "input_length": null}], "name": "Sequential"}, {"layers": [{"cache_enabled": true, "dims": [4096], "name": "Reshape", "input_shape": [4096]}], "name": "Sequential"}], "name": "Merge", "concat_axis": 1, "dot_axes": -1, "cache_enabled": true, "mode": "concat"}, {"b_constraint": null, "name": "Dense", "activity_regularizer": null, "W_constraint": null, "cache_enabled": true, "init": "uniform", "activation": "linear", "input_dim": null, "b_regularizer": null, "W_regularizer": null, "output_dim": 1024}, {"cache_enabled": true, "activation": "tanh", "name": "Activation"}, {"cache_enabled": true, "name": "Dropout", "p": 0.5}, {"b_constraint": null, "name": "Dense", "activity_regularizer": null, "W_constraint": null, "cache_enabled": true, "init": "uniform", "activation": "linear", "input_dim": null, "b_regularizer": null, "W_regularizer": null, "output_dim": 1024}, {"cache_enabled": true, "activation": "tanh", "name": "Activation"}, {"cache_enabled": true, "name": "Dropout", "p": 0.5}, {"b_constraint": null, "name": "Dense", "activity_regularizer": null, "W_constraint": null, "cache_enabled": true, "init": "uniform", "activation": "linear", "input_dim": null, "b_regularizer": null, "W_regularizer": null, "output_dim": 1024}, {"cache_enabled": true, "activation": "tanh", "name": "Activation"}, {"cache_enabled": true, "name": "Dropout", "p": 0.5}, {"b_constraint": null, "name": "Dense", "activity_regularizer": null, "W_constraint": null, "cache_enabled": true, "init": "glorot_uniform", "activation": "linear", "input_dim": null, "b_regularizer": null, "W_regularizer": null, "output_dim": 1000}, {"cache_enabled": true, "activation": "softmax", "name": "Activation"}], "name": "Sequential"}

error:
KeyError: 'class_name'

**Comment by fchollet** [comment]
The Keras JSON format changed. You can still reinstantiate your model from the Python source code.
