### ISSUE TITLE
Encoder Decoder Architecture in Keras?

### ISSUE THREAD

**Issue by suraj-jayakumar** [fchollet/keras#2445]
```
model = Sequential()
model.add(LSTM(100, return_sequences=True, input_shape=(maxlen, len(chars))))
model.add(LSTM(100, return_sequences=False))

````

here, does the above way of stacking represent an "Encoder-Decoder" architecture?

Here by ```return_sequences=True``` are we only passing the O/P of the 1st LSTM to 2nd  or we are passing the context [context vector/hidden activation] also?

**Comment by carlthome** [comment]
That's just a stacked LSTM of depth two.

**Comment by suraj-jayakumar** [comment]
Ok can you suggest me some other architecture using keras that would replicate encoder-decoder architecture please?

Thanks

**Comment by carlthome** [comment]
Try searching. There are multiple issues just like yours already!
