### ISSUE TITLE
Learning multiple embeddings for CNN+LSTM?

### ISSUE THREAD

**Issue by Natanada** [fchollet/keras#245]
hi fchollet,

First thanks for this wonderful code. 

I'm having some difficulty producing a CNN+LSTM model with embedding matrices for both the CNN features and the word encodings (1 of k). 

For the keras example image caption generation model the word encodings were not learned, however my group believes learning the word encodings to be beneficial to the performance of the network. 

We also want to feed the image in for only the initial timestep. Thus for each training instance, the input sequence would be:

t(-1): Wi(CNN)
t(0): We(sent_start_symbol)
t(1): We(word_1)
...
t(x):We(sent_end_symbol)

where Wi and We map the CNN features and the 1 of k word encodings to the same dimensional space.

Does keras have this functionality? I attempted to use the merge layer with separate dense layers for the CNN features and words, but the merge layer cannot produce the 3D tensor the lstm layer needs.

Thanks again!

**Comment by fchollet** [comment]
> I attempted to use the merge layer with separate dense layers for the CNN features and words, but the merge layer cannot produce the 3D tensor the lstm layer needs.

`Merge` is the correct way to do this. What was your issue? You should be able to use `Merge` to concatenate two 3D tensors on their last dimensions (features).

**Comment by Natanada** [comment]
Ah I see, this would be using TimeDistributedDense for each of the modes right?

**Comment by fchollet** [comment]
If you want to apply a dense layer on a sequence of vectors (3D tensor - `(samples, time, features)`), then you should use `TimeDistributedDense`. 

If you want more guidance, you should post your code / network architecture here.
