### ISSUE TITLE
Example of Skipgram or CBOW for training word embeddings?

### ISSUE THREAD

**Issue by joelkuiper** [fchollet/keras#2452]
I'm trying to reproduce some vanilla word2vec examples (e.g. CBOW or Skipgram) in Keras. Unfortunately, I got a bit stuck … and since it's such a common thing to do I was wondering if someone already wrote an example. The goal is to get the dense word vectors from a large corpus of (tokenized) sentences.

**Comment by braingineer** [comment]
this may help: 

https://github.com/cesc-park/CRCN/blob/master/keras/examples/skipgram_word_embeddings.py

just a by the way though, i found this via the search
```
site:github.com keras skipgram
```

you should try there to explore all past discussions & people's forked repos

**Comment by bkj** [comment]
This is using a pretty old version of the package, with different layers and APIs -- plus the example does not run out of the box.  Does anyone know of an implementation that uses a more recent version of Keras?  I know that the advice given elsewhere is to user gensim / word2vec / something else, but I'm interested in implementing some nonstandard word embeddings that use a skipgram model as a component.

**Comment by braingineer** [comment]
If you're writing your own stuff, it should be fairly trivial to port that code.  If you look at it, the model is really just a single layer, found here:
