### ISSUE TITLE
Does the keras with tensorflow backend support windows?

### ISSUE THREAD

**Issue by githubzhanglei** [fchollet/keras#2459]
As I know, the tensorflow does not support windows yet. Does that mean the keras with tensorflow backend can not work on windows?

**Comment by philipperemy** [comment]
Yes as far as I know if you cannot have the backend, Keras won't work

**Comment by fchollet** [comment]
TensorFlow runs on Windows, although it is a CPU-only version. To use the GPU, you should go with Theano, which has better Windows support.
