### ISSUE TITLE
The test method of model will drain memory easily and result in errors

### ISSUE THREAD

**Issue by marearth** [fchollet/keras#246]
When I make some tests on examples,e.g. cifar10_cnn.py,it's very easy to exhaust memory when the size of test example is large enough(size=10000) for a 4G size of memory without GPU. I expect an alternative method can be put forward to smooth the test process.

**Comment by fchollet** [comment]
The `test` method will load all of your samples on the GPU memory. Of course that's terrible for large batches (10000 is massive). You should call it repeatedly on small batches instead. Typical batch size on CIFAR10 should be ~512 at most.
