### ISSUE TITLE
Can some explain the dot_axes ?

### ISSUE THREAD

**Issue by LiuAndYang** [fchollet/keras#2461]
I am sorry to ask such a navie question. But i am really confused with the dot_axes. Can someone explain that, Thank you so much!

**Comment by EderSantana** [comment]
it chooses the dimensions to which operate an inner product. Say you have two tensors of dimensions (4, 2, 3) and (4, 5, 3). So you want to do a matrix inner product between the 4 (2, 3) matrices with the equivalent (5, 3). You just pick dot_axes=(2, 2) to say that the product dimension is the last one. 

Not a super elaborate answer but i hope it helps.
