### ISSUE TITLE
Why Keras remove graph model in 1.0?

### ISSUE THREAD

**Issue by rudaoshi** [fchollet/keras#2462]
How can I update my old code with graph model to keras 1.0?

**Comment by fluency03** [comment]
`Graph` is still can be used. You can still do `from keras.models import Graph` since in `models.py` [here](https://github.com/fchollet/keras/blob/master/keras/models.py), it is done by `from .legacy.models import Graph`.

For new version, you can use this [Model class API](http://keras.io/models/model/) and [Getting started with the Keras functional API](http://keras.io/getting-started/functional-api-guide/).

**Comment by fchollet** [comment]
Old code using the `Graph` model will still work. For new code, use the functional API instead.

**Comment by rudaoshi** [comment]
Thank you for your response.

**Comment by rbharath** [comment]
To resuscitate this old thread, it looks like the `Graph` model support was recently removed. My Travis tests for [deepchem](https://github.com/deepchem/deepchem) started failing with `ImportError: cannot import name Graph`. When I checked models.py history, it looks like this [PR](https://github.com/fchollet/keras/commit/ce814302acee2c474a88b2f4bfcdc92ff866f94f) removed legacy support yesterday.

Would it be possible to put together a roadmap for feature removal moving forward? (My apologies if this expists already). I understand the need to trim dead code from the repo, but there is downstream overhead for users (For example, I'll have to rewrite the [deepchem](https://github.com/deepchem/deepchem) keras models to use the functional API to get Travis functional).

**Comment by fchollet** [comment]
If you depend on a legacy feature which was explicitly deprecated more than 6 months ago, you should not run your code on the latest GitHub version of Keras. You should freeze a version that has the feature you want.

Features from Keras 1 that get deprecated will stay around for longer than 6 months. Graph was a feature from Keras 0, however.

**Comment by karankatiyar92** [comment]
can we use sequential model to design residual nets architecture?
