### ISSUE TITLE
Can I use Input and Embedding layer in keras before stateful LSTM layer? 

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#2465]
1. The input feeding to stateful LSTM layer has to be the pre-trained embedding? 
2. If I do not misunderstand, the Embedding layer is to transform a word frequency index to a vector randomly. (Is it according to random data or some other rules?) 
3. But stateful LSTM wants one batch input every time. Then every time, the same word in different batches will be represented by the different vectors. Therefore, I can't use Input and Embedding layer in keras before stateful LSTM layer? 
4. If possible, what is the input shape in Input layer?
Any suggestions would be appreciated!

```
sequence = Input(shape=(batch_size, maxlen,),dtype='int32')
tweet = Embedding(max_features, embedding_dims, input_length=maxlen)(sequence)
encoder = LSTM(hidden_dims, stateful=True)(tweet)
```

**Comment by fchollet** [comment]
> The input feeding to stateful LSTM layer has to be the pre-trained embedding?

No, it doesn't have to be pre-trained.

> If I do not misunderstand, the Embedding layer is to transform a word frequency index to a vector randomly. (Is it according to random data or some other rules?)

It's a learned embedding, it's not random (except at the very beginning).

> But stateful LSTM wants one batch input every time. Then every time, the same word in different batches will be represented by the different vectors. Therefore, I can't use Input and Embedding layer in keras before stateful LSTM layer?

No, embeddings are not random and you can use them with stateful RNNs.

> If possible, what is the input shape in Input layer?

There are multiple examples in the docs. See http://keras.io/getting-started/functional-api-guide/

**Comment by Imorton-zd** [comment]
@fchollet Thanks for your reply! But I can't ensure the input shape in first layer. It always yields the errors!
```
    sequence = Input(shape=(batch_size,maxlen),dtype='int32')
    tweet = Embedding(max_features, embedding_dims, input_length=maxlen)(sequence)
    stateful_lstm = LSTM(hidden_dims,stateful=True)    
    encoder = stateful_lstm(tweet)
    
    predictions = Dense(nb_classes, activation='softmax')(encoder) 
    model = Model(input=sequence, output=predictions)    
    model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "E:/EMNLP/experiment/test_stateful.py", line 361, in <module>
    StatefulWithLearnedEmbedding('orig')
  File "E:/EMNLP/experiment/test_stateful.py", line 335, in StatefulWithLearnedEmbedding
    encoder = shared_lstm(tweet)
  File "C:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 441, in __call__
    self.assert_input_compatibility(x)
  File "C:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 382, in assert_input_compatibility
    str(K.ndim(x)))
Exception: Input 0 is incompatible with layer lstm_1: expected ndim=3, found ndim=4
```

**Comment by Imorton-zd** [comment]
@fchollet @EderSantana I have an innocent question about shared layers in functional API (e.g. shared LSTM). What is the mathematical theory in shared layers? Which paper can I refer to? Many thanks!

**Comment by willsmithorg** [comment]
See https://arxiv.org/abs/1409.4842 (inception) or https://arxiv.org/abs/1512.03385 (resnet).  Both use shared layers.

**Comment by HimaVarsha94** [comment]
Is it possible to use the above example when the sequence is not padded? I want to use it for encoder-decoder model.
