### ISSUE TITLE
error: Wrong number of dimensions: expected 4, got 3 with shape

### ISSUE THREAD

**Issue by mundher** [fchollet/keras#2466]
I got this error
`(28709L, 48L, 48L)
(3589L, 48L, 48L)
Train on 28709 samples, validate on 3589 samples
Epoch 1/50
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    history = model.fit(trainX, trainY, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1,validation_data=(validX,vali
dY), callbacks=[checkpointer])
  File "c:\keras\keras\models.py", line 402, in fit
    sample_weight=sample_weight)
  File "c:\keras\keras\engine\training.py", line 1036, in fit
    callback_metrics=callback_metrics)
  File "c:\keras\keras\engine\training.py", line 774, in _fit_loop
    outs = f(ins_batch)
  File "c:\keras\keras\backend\theano_backend.py", line 499, in __call__
    return self.function(*inputs)
  File "c:\theano\theano\compile\function_module.py", line 815, in __call__
    allow_downcast=s.allow_downcast)
  File "c:\theano\theano\tensor\type.py", line 178, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "c:\\keras\\keras\\backend\\theano_backend.py:495"  at inde
x 0(0-based)', 'Wrong number of dimensions: expected 4, got 3 with shape (128L, 48L, 48L).')`

here is my code
`img_rows = img_cols = 48
conv_input_shape=(1, img_rows, img_cols)
conv_nb_row = 3
conv_nb_col = 3
conv_nb_pool = 2
dense_out = 7
decay = l2(0.01)

model = Sequential()
model.add(Convolution2D(32,conv_nb_row,conv_nb_col,border_mode='same',input_shape=conv_input_shape,W_regularizer=decay))
model.add(Activation('relu'))
model.add(Convolution2D(32, conv_nb_row, conv_nb_row,W_regularizer=decay))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(conv_nb_pool, conv_nb_pool)))
model.add(Dropout(0.1))

model.add(Convolution2D(64, conv_nb_row, conv_nb_row,W_regularizer=decay))
model.add(Activation('relu'))
model.add(Convolution2D(64, conv_nb_row, conv_nb_row,W_regularizer=decay))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(conv_nb_pool, conv_nb_pool)))
model.add(Dropout(0.2))

model.add(Convolution2D(128, conv_nb_row, conv_nb_row,W_regularizer=decay))
model.add(Activation('relu'))
model.add(Convolution2D(128, conv_nb_row, conv_nb_row,W_regularizer=decay))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(conv_nb_pool, conv_nb_pool)))
model.add(Dropout(0.3))

model.add(Convolution2D(256, conv_nb_row, conv_nb_row,W_regularizer=decay))
model.add(Activation('relu'))
model.add(Convolution2D(256, conv_nb_row, conv_nb_row,W_regularizer=decay))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(conv_nb_pool, conv_nb_pool)))
model.add(Dropout(0.4))

model.add(Flatten())

model.add(Dense(dense_out,W_regularizer=decay))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='Adam',metrics=['accuracy'])

batch_size = 128
nb_epoch = 50

checkpointer = ModelCheckpoint(filepath="best.hdf5",monitor='val_acc')
trainX = np.load('fer2013\\xtrain.npy')
trainY = np.load('fer2013\\ytrain.npy')
trainX, trainY = normaliaze(trainX,trainY)
print trainX.shape
validX = np.load('fer2013\\xvalid.npy')
validY = np.load('fer2013\\yvalid.npy')
validX, validY = normaliaze(validX, validY)
print validX.shape

history = model.fit(trainX, trainY, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1,validation_data=(validX,validY), callbacks=[checkpointer])`

as you can see when I printed trainX shape I got (28709L, 48L, 48L) so my data dim is correct

**Comment by joelthchao** [comment]
You should reshape your data into `(num_data, channel, row, col)`, in your case `(28709, 1, 48, 48)`

**Comment by mundher** [comment]
I got this error after reshape the data

`Using Theano backend.
Using gpu device 0: GeForce GTX 970 (CNMeM is disabled, cuDNN 5004)
(28709L, 1L, 48L, 48L)
(3589L, 1L, 48L, 48L)
Train on 28709 samples, validate on 3589 samples
Epoch 1/50
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    history = model.fit(trainX, trainY, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1,validation_data=(validX,vali
dY), callbacks=[checkpointer])
  File "c:\keras\keras\models.py", line 402, in fit
    sample_weight=sample_weight)
  File "c:\keras\keras\engine\training.py", line 1036, in fit
    callback_metrics=callback_metrics)
  File "c:\keras\keras\engine\training.py", line 774, in _fit_loop
    outs = f(ins_batch)
  File "c:\keras\keras\backend\theano_backend.py", line 499, in __call__
    return self.function(*inputs)
  File "c:\theano\theano\compile\function_module.py", line 902, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "c:\theano\theano\gof\link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "c:\theano\theano\compile\function_module.py", line 889, in __call__
    self.fn() if output_subset is None else\
RuntimeError: Could not set tensorNd descriptor: CUDNN_STATUS_BAD_PARAMdim=4
Apply node that caused the error: GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty
.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Const
ant{0.0})
Toposort index: 277
Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), <theano.gof.typ
e.CDataType object at 0x0000000023F2A3C8>, Scalar(float32), Scalar(float32)]
Inputs shapes: [(128, 128, 2, 2), (256, 128, 3, 3), (128, 256, 0, 0), 'No shapes', (), ()]
Inputs strides: [(512, 4, 2, 1), (1152, 9, 3, 1), (0, 0, 0, 1), 'No strides', (), ()]
Inputs values: ['not shown', 'not shown', CudaNdarray([]), <PyCObject object at 0x0000000026712A08>, 1.0, 0.0]
Inputs name: ('image', 'kernel', 'output', 'descriptor', 'alpha', 'beta')

Outputs clients: [[GpuElemwise{Add}[(0, 0)](GpuDnnConv{algo='small', inplace=True}.0, GpuReshape{4}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This
can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be
 disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.`

**Comment by joelthchao** [comment]
Do you design your model by yourself? You input is too small to use this network. I can run it with 96x96 image without problem. In your case:
48x48 -> 23x23 -> 9x9 -> 2x2 -> boom! 
You should add `border_type='same'` for each your conv layers (VGG style).
