### ISSUE TITLE
Unable two merge two image inputs - error : 'get_output_shape_at'

### ISSUE THREAD

**Issue by shirtzet** [fchollet/keras#2467]
Hi,

the following code does not compile:
`
        part_A_input = Input(shape=(3,self.partSize,self.partSize), name='part_A_input')
        part_B_input = Input(shape=(3,self.partSize,self.partSize), name='part_B_input')
        concat_branch = Merge(layers=[crop_A, crop_B], mode='concat', concat_axis=1)`

the error is :AttributeError: 'TensorVariable' object has no attribute 'get_output_shape_at'

while the old graph model works fine : 
`graph.add_node(Some-Function, name='concatenate', inputs=['part_A_input', 'part_B_input'], concat_axis=-1)`

any idea?

thanks!

**Comment by codekansas** [comment]
Try

    merge([part_A_input, part_B_input], mode='concat', concat_axis=1)

although in the second example you used `concat_axis=-1`

**Comment by fchollet** [comment]
`Merge` is for layers, `merge` is for tensors. This is in the docs...

**Comment by sliedes** [comment]
"This is in the docs" - is it? Looking at https://keras.io/layers/core/#merge , the docs say "A Merge layer can be used to merge a list of tensors into a single tensor" and "layers: Can be a list of Keras tensors or a list of layer instances."

**Comment by reachbp** [comment]
Hi, I have the same question as @sliedes . I dont find a "merge" function in Keras. Can someone point me to the specific import?

**Comment by sliedes** [comment]
It's in keras.layers, both merge and Merge.

**Comment by reachbp** [comment]
Hi. Thank you.
