### ISSUE TITLE
R-CNN ROI pooling layer  

### ISSUE THREAD

**Issue by braingineer** [fchollet/keras#2469]
Someone has a theano port of the layer that was custom implemented for Ross Girschick's [fast/faster RCNN ](https://github.com/rbgirshick/py-faster-rcnn) models:  https://github.com/ddtm/theano-roi-pooling

I thought I'd leave this here in case someone wants to pick that up and run with it to integrate it into Keras.  I can't work on it myself until June at the earliest.

**Comment by Irtza** [comment]
@braingineer I'm new to keras, I am interested in implementing/porting ROI-pooling too, but I'm using Tensorflow Back-end for the rest of the work. 
Do you plan to do it on keras as Tensorflow backend? or in a way that could benefit both backends (if there is a way to hack it)

**Comment by braingineer** [comment]
Hi @Irtza , I wasn't planning on it because I don't really use tensorflow (as least, not in the near future).   But, in general, I wasn't planning on getting to this until at least after the first few weeks in June.   There is way too many other things first. 

If you want to port it, you can always ask the mailing group or slack rooms for advice if you get stuck.

**Comment by Irtza** [comment]
@braingineer I have some time on my hand in June. but the tensorflow layers could be really tricky to implement, I'm not so comfortable with advanced C++ that needs to be written to implement r-cnn through tensorflow. however porting the theano layer to keras sounds like a do-able task, and could be of help to me. I need some guidance.
where is the a mailing group or slack room for keras?

**Comment by AdityaGudimella** [comment]
Hi @Irtza I'm interested in doing ROI pooling too. I'd love to help you out in this.

**Comment by Irtza** [comment]
@AdityaGudimella  lets get intouch on email ? mine is : irtzali@gmail.com

**Comment by braingineer** [comment]
Hi guys, glad you're both touching base on this!  

I won't be able to help out yet, but I'll ping back to see how things are going once research is under control.  

B.

**Comment by AdityaGudimella** [comment]
@Irtza Hey. I just saw your reply. I sent you an email. My id is aditya.gudimella@gmail.com I hope we can start on this soon.

**Comment by Primus-zhao** [comment]
Hi, guys, any progress?

**Comment by wassname** [comment]
FYI: Tensorflow implementation of ROIPooling [here](https://github.com/zplizzi/tensorflow-fast-rcnn)

**Comment by yhenon** [comment]
I am working on implementations [here](https://github.com/yhenon/keras-spp)

**Comment by Irtza** [comment]
@wassname @yhenon Thanks :+1:
