### ISSUE TITLE
How to cite keras in research paper?

### ISSUE THREAD

**Issue by alzhusan** [fchollet/keras#247]

**Comment by fchollet** [comment]
In the future, we may release a paper for the purpose of citations, in the spirit of [this one](http://arxiv.org/pdf/1506.00619.pdf) (which, incidentally, mentions Keras but does not cite it). 

For now, we don't have a paper, so you can simply cite the Github repo. [Here's an example](http://academia.stackexchange.com/a/14015).

**Comment by keunwoochoi** [comment]
For example:

@misc{chollet2015,
  author = {François Chollet },
  title = {keras},
  year = {2015},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/fchollet/keras}},
  commit = {5bcac375530eda2650fff962073a29b07b3b1926}
}
commit will be changed though.

**Comment by bstriner** [comment]
Updating this issue with a link back to the FAQ.
https://keras.io/getting-started/faq/
```
@misc{chollet2015keras,
  title={Keras},
  author={Chollet, Fran\c{c}ois and others},
  year={2015},
  publisher={GitHub},
  howpublished={\url{https://github.com/fchollet/keras}},
}
```
Always throws me how Keras is upper case. Way to break the trend!
Cheers

**Comment by csitaula** [comment]
This BibTex is not working in my LaTex!

**Comment by annanurov** [comment]
The citation on https://keras.io/getting-started/faq/ does not work on Endnote. 

Please advise,

**Comment by csitaula** [comment]
It worked on BibTex after I modified in https!

**Comment by annanurov** [comment]
Could you please post the modified version here?

**Comment by RomainCendre** [comment]
I seen this : https://guides.github.com/activities/citable-code/
It seems to provide a DOI from a github repo
