### ISSUE TITLE
Multiple Inputs to RNN

### ISSUE THREAD

**Issue by karishmamalkan** [fchollet/keras#2474]
Hi,

I am also looking for multiple inputs to an RNN. I dont want to concat them or sum them outside the RNN The reason is that my RNN wants to learn 2 weights. 

my RNN output is:
h(t+1)=g( W0_h(t)  +  W1_ in1[t] +   W2*in2)
where in1 and in2 have different dimensions. 

I cant add W2 to all values of W1 outside my RNN because there is a 4th dimension over a latent variable. Hence, I need to perform this within the RNN. (PS: I am writing a custom RNN class within the recurrent.py file)

**Comment by bhtucker** [comment]
Can you post a gist?
