### ISSUE TITLE
Supporting excluding layer from training

### ISSUE THREAD

**Issue by rudaoshi** [fchollet/keras#2476]
In my task, I need to update some layer in one iteration, and then update other layers in the next iteration. I wish it will be a interface to exclude/include the parameter of the layers in training procedure.

**Comment by rudaoshi** [comment]
In my task, I need to update some layer in one iteration, and then update other layers in the next iteration. I wish it will be a interface to exclude/include the parameter of the layers in training procedure.

**Comment by rpinsler** [comment]
Each layer has a trainable attribute:
> trainable: boolean, whether the layer weights will be updated during training.

**Comment by rudaoshi** [comment]
Thanks. Is that attribute exist in Keras 1.0 ? I cannot find it in the document.
