### ISSUE TITLE
Model compiles fine but gives Value Error during training

### ISSUE THREAD

**Issue by code-ball** [fchollet/keras#2490]
I have following model which merges two similar inputs into one and then embeds it. The embedded input is sent to RNN and the output are two losses. The model compiles fine but once it starts training, it gives following error in first epoch:

>  Traceback (most recent call last):
>   File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform)
> ValueError: Shape mismatch: x has 100 rows but z has 200000 rows

Following is the code snippet:

``` python
a = Input(shape=(1000,), dtype='int32', name = 'a')
b = Input(shape=(1000,), dtype='int32', name = 'b')

merged = merge([a,b], mode='concat', concat_axis=-1, name='merged')
em = Embedding(output_dim=180,input_dim=2000,input_length=1,name='em') (merged)

recur = SimpleRNN(120, activation='relu', name='recur')(em)
loss1 = Dense(1000,name='output1',activation='softmax')(recur)
loss2 = Dense(1000,name='output2',activation='softmax')(recur)

model = Model(input=[a,b], output=[loss1, loss2])
model.summary()

model.compile(optimizer='rmsprop', loss=['categorical_crossentropy',
                'categorical_crossentropy'])
print("\nTraining...")
model.fit([a_train, b_train],
           [a_label,  b_label],
           nb_epoch=50, batch_size = 100) 
```

> Input data shapes:
> ---
> 
> a_train :  (39916, 1000)
> b_train:  (39916, 1000)
> a_label:  (39916, 1000)
> b_label:  (39916, 1000)

The above data shapes mean each file contains 39916 one-hot vectors of dimension 1000.
I am not able to understand the reason for the error. Can someone point me to the cause of error?
Thanks

**Comment by fchollet** [comment]
Don't know what the problem is (you should post the stack trace), but you
could start by not having a `merge` as first layer, I don't think that's
reasonable. Concatenate your inputs as a preprocessing step and have only
one input to your model. That should probably fix your problem in passing.

**Comment by code-ball** [comment]
@fchollet: First, thanks a lot for such great library!

I tried to make changes as suggested by you but it gives me same error. Following is the new code.

```python
xtrain =  Input(shape=(2000,), dtype='int32', name = 'input1')
em = Embedding(output_dim=180,input_dim=2000,input_length=1,name='em') (xtrain)
recur = SimpleRNN(120, activation='relu', name='recur')(em)
    
loss1 = Dense(1000,name='output1',activation='softmax')(recur)
loss2 = Dense(1000,name='output2',activation='softmax')(recur)
    
model = Model(input=xtrain, output=[loss1, loss2])
model.summary()
model.compile(optimizer='rmsprop', loss=['categorical_crossentropy',
                                      'categorical_crossentropy']) 
print("\nTraining...")
relTP_model.fit(Xtrain, [a_label,  b_label], nb_epoch=50, batch_size = 100) 
```
The shape of Xtrain is (39916, 2000).

I have attached model summary and trace here. Please let me know if any other information will help to resolve this.

Thanks

[model_summary.txt](https://github.com/fchollet/keras/files/234746/model_summary.txt)
[trace.txt](https://github.com/fchollet/keras/files/234747/trace.txt)
