### ISSUE TITLE
Visualization not working correctly

### ISSUE THREAD

**Issue by penguin2121** [fchollet/keras#2491]
I am using Python 3.4, Keras 1.0 with the newest pydot2 and graphviz installs.  When I run the recommended code to visualize the network, i get: 
plot(model, to_file='model.png')
Traceback (most recent call last):

  File "<ipython-input-10-8a625a9caab5>", line 1, in <module>
    plot(model, to_file='model.png')

  File "C:\WinPython\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\site-packages\keras\utils\visualize_util.py", line 61, in plot
    dot.write_png(to_file)

  File "C:\WinPython\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\site-packages\pydot.py", line 1809, in <lambda>
    lambda path, f=frmt, prog=self.prog : self.write(path, format=f, prog=prog))

  File "C:\WinPython\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\site-packages\pydot.py", line 1895, in write
    dot_fd = file(path, "w+b")

NameError: name 'file' is not defined

**Comment by fchollet** [comment]
That's an error within Pydot, not within Keras. You should try reinstalling
the still-maintained version of Pydot (pydot_ng) and dependencies.

**Comment by lemuriandezapada** [comment]
I also have pydot issues when trying to run it with python3
works just fine for 2.7

**Comment by penguin2121** [comment]
Hello,

I found out how to get it fixed.  You should follow the instructions found here by LectureMaker: http://stackoverflow.com/questions/18438997/why-is-pydot-unable-to-find-graphvizs-executables-in-windows-8 .  He said:

"I solved this problem on my windows 7 machine by adding the GraphViz bin directory to my computer's PATH. Then restarting my python IDE to use the updated path.

Install GraphViz if you haven't already (I used the MSI download)
Get the path for gvedit.exe (for me it was "C:\Program Files (x86)\Graphviz2.34\bin\")
Add this path to the computer's PATH
One way to get to environment settings to set your path is to click on each of these button/menu options: start->computer->system properties->advanced settings->environment variables
Click Edit User path
Add this string to the end of your Variable value list (including semicolon): ;C:\Program Files (x86)\Graphviz2.34\bin
Click OK
Restart your Python IDE"

Hope that fixes the issue for anyone else!

**Comment by vivekec** [comment]
Final soln.
https://stackoverflow.com/a/50025414/6126603
