### ISSUE TITLE
reuters_mlp.py example raises RuntimeError

### ISSUE THREAD

**Issue by yscacaca** [fchollet/keras#2492]
Hi,

I wrote a simple code with softmax activation and categorical_crossentropy loss, but it raises an error.
So I try the reuters_mlp.py example and it raises the same error.

> Traceback (most recent call last):
>   File "<stdin>", line 3, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 405, in fit
>     sample_weight=sample_weight)
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1025, in fit
>     self._make_train_function()
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 663, in _make_train_function
>     *_self._function_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 509, in function
>     return Function(inputs, outputs, updates=updates, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 495, in __init__
>     **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 322, in function
>     output_keys=output_keys)
>   File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 480, in pfunc
>     output_keys=output_keys)
>   File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1818, in orig_function
>     defaults)
>   File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1682, in create
>     input_storage=input_storage_lists, storage_map=storage_map)
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 690, in make_thunk
>     storage_map=storage_map)[:3]
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/vm.py", line 1021, in make_all
>     no_recycling))
>   File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/**init**.py", line 256, in make_thunk
>     compute_map, no_recycling)
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 978, in make_thunk
>     no_recycling)
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 881, in make_c_thunk
>     output_storage=node_output_storage)
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1200, in make_thunk
>     keep_lock=keep_lock)
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1143, in **compile**
>     keep_lock=keep_lock)
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1595, in cthunk_factory
>     key=key, lnk=self, keep_lock=keep_lock)
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1142, in module_from_key
>     module = lnk.compile_cmodule(location)
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1506, in compile_cmodule
>     preargs=preargs)
>   File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/nvcc_compiler.py", line 415, in compile_str
>     return dlimport(lib_filename)
>   File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 299, in dlimport
>     rval = **import**(module_name, {}, {}, [module_name])
> RuntimeError: ('The following error happened while compiling the node', GpuDnnSoftmaxGrad{tensor_format='bc01', mode='channel', algo='accurate'}(GpuContiguous.0, GpuContiguous.0), '\n', 'could not create cuDNN handle: CUDNN_STATUS_NOT_INITIALIZED', "[GpuDnnSoftmaxGrad{tensor_format='bc01', mode='channel', algo='accurate'}(<CudaNdarrayType(float32, (False, False, True, True))>, <CudaNdarrayType(float32, (False, False, True, True))>)]")

I've updated both Keras and Theano. How can I solve this problem?

Thanks

**Comment by fchollet** [comment]
You should try to reinstall cuDNN. But maybe even just rebooting might fix
this.

**Comment by yscacaca** [comment]
I update cuDNN to latest version and reboot the machine, but unfortunately it doesn't work. So I just replace the softmax layer with own Lambda layer to avoid using nnet.softmax(x), and it helps. Maybe there is something wrong with my CUDA or related things.
