### ISSUE TITLE
how to set  the weight in Convolution2D layer

### ISSUE THREAD

**Issue by alyato** [fchollet/keras#2501]
i'm using the keras to train my model. The follow pic is my convolution2D layer.
![con](https://cloud.githubusercontent.com/assets/6815071/14786061/829d96f6-0aba-11e6-8922-88c828301f19.png)
But i want to set the weight values and read the core.py. It says that
![weights](https://cloud.githubusercontent.com/assets/6815071/14786039/6fa3ba62-0aba-11e6-8dbf-7dcb56c1fdfc.png)
But i don't know how to use. Is there someone meet my question and give me a help?

**Comment by joelthchao** [comment]
You have to prepare weights and pass it as argument.
In your case, weights consists of two numpy ndarray, 
weight: `shape=(32, 1, 5, 5)` and bias: `shape=(32,)`
`Convolution2D(32, 1, 5, 5, border_mode='valid', weights= [weight, bias])`

However, if you want to init weight with a random distribution, you can do:
`Convolution2D(32, 1, 5, 5, border_mode='valid', init='glorot_uniform')`
