### ISSUE TITLE
Combine real-valued feature with embedded feature as input to RNN

### ISSUE THREAD

**Issue by code-ball** [fchollet/keras#2507]
Hi,

I have a case where I want to combine an (integer) embedded feature and real-valued feature or provide them as two separate inputs to a RNN. Following is my example:

``` python
a = Input(shape=(1,), dtype='int32') #Integer classes feature to be embedded
b =  Input(shape=(1,), dtype='float32') #real-valued feature
em = Embedding(output_dim=10,input_dim=20,input_length=1) (a) #20 classes for integer feature
```

I want to pass both features to RNN layer. Is it possible to do so and how? I am aware of the merge layer but it seems directly apply merge to **b** and **em** does not help. I do not want the real valued feature to be embedded. 

Please let me know if there is workaround or if I need to write a new layer for this.

Thanks

**Comment by braingineer** [comment]
Do you want them to be 2 separate inputs with 2 seperate outputs, or do you want them to get pushed through at the same time so they can affect each other?  

You were on the right track with merge.  I'm not sure what went wrong, but if you use the 'concat' flag, then they get added together into one long vector.

**Comment by code-ball** [comment]
Well, I want them to be two separate or concatenated inputs, push together at same time through RNN affecting each other and finally result in single output which is used to calculate two separate outputs (and thereby two losses). Here is the formulation that I want in affect:

> output from RNN (o) = W_1 * **a** + W_2 * **b** + recurrent part

where a is embedded and b is real valued same as before.
Once I get o, I apply some other function over it and get two separate losses.

Merge doesn't work as the shape of embedded tensor em is (num_samples, input_length, output_dim)
while shape of Input layer is (input_dim, num_samples). and just applying reshape on input messes everything.

Thanks

**Comment by braingineer** [comment]
I"m confused on why the shape of your input layer is (input_dim, num_samples) for a couple of reasons. 

1. num_samples should refer to your batch size here.  If you're using it to refer to something else, that's going to be confusing.  If it's the batch size, it should be the first dimension. 
2. input_dim is also used as the name for the embedding layer, so i'm not certain if you're referring to a different number or the same number

Given your code above, here's what I think is happening, what I think you want to happen, and what I think you can do:

```python
### this is size (batch, 1)
a = Input(shape=(1,), dtype='int32') #Integer classes feature to be embedded
### this is size (batch,1)
b =  Input(shape=(1,), dtype='float32') #real-valued feature
### this takes input size (batch, 1), expects all numbers to be 0-19, and outputs (batch, 10)
em = Embedding(output_dim=10,input_dim=20,input_length=1) (a) #20 classes for integer feature

### you now have em = (batch, 1, 10) and b = (batch, 1)
### if you want to concat them, the easiest thing would be to change your input shape 
b = Input(shape=(1,1), dtype='float32') 
# though, you could also reshape to this size, or do a Lambda layer and use K.expand_dims
# now, b's shape is (batch, 1, 1)
# when you concat, you have (batch, 1, 11)
ab = merge([a,b,], mode='concat') 
```

**Comment by code-ball** [comment]
Hmm. Probably, I did it right the first time. It seems your solution is what I wanted and what I did first time. But in between somewhere, I hit some errors which led me to think that merge is not working. Although, a new input from your side is the use of Input layer (or lambda layer) instead of Reshape.
Actually, when I used Reshape layer, it messed up something for me although from your description, it appears that it should have same effect as Input.

This is great feedback and I will try this out in sometime. I will let you know if it doesn't work or close this post.

Thanks again for great help.

**Comment by code-ball** [comment]
@braingineer : It seems there is an issue here. the below text pertains to input **b** in our running example

1.) Input (1,1) : this does not work well. Although the model compiles successfully, it gives an error during training as the input layer itself now expects input in 3 dimensions while it gets it only in 2 dimensions. Do you know of a way of converting input to 3 dimensions?

2.) Using Reshape or Lambda layer (I am not sure if I used lambda correctly) gives error  in compilation as graph becomes disconnected. Actually, it is not allowed to have reshape or lambda layer as input to RNN in keras. 

Do you see where I am going wrong?

Thanks

**Comment by braingineer** [comment]
Hmm. I'm a bit brain fogged since it's the end of a long day, but:

1. The input shape specified earlier was not including the batch shape.  If you have `Input(shape=(1,1))`, then this should be a 3-dimensional input already.  If it is saying it's only getting 2 dimensions, that means you aren't passing a 3-dimensional thing.  What does your input data look like?  Are you formatting your data in 3 dimensions or 2?

2.  Reshape and Lambda usually give me issues too because it's super easy to lose the special properties Keras attaches to the tensors as they get pushed through the graph.  

If the above advice doesn't work, can you post a gist (gist.github.com) tomorrow with the code you use to make the model as well as the code you use to feed the model the data? 

B.

**Comment by code-ball** [comment]
@braingineer: Well, as I mentioned earlier, the model compiles fine when use ` Input(shape = (1,1))`
but the problem is both my inputs are only 2D. 
In my example of **a** and **b**, both are single vectors of 6 samples with shape (6,1). **a** does not create problem as it gets embedded which turns it into 3 dimensions. Hence the Input layer itself does not expect the actual input to be in 3 dimensions.
But in case of **b**, with proposed solution, the Input layer now expects actual input to be in 3 dimension. Can you suggest how can I do that? Probably read data in some way to make it 3 dimensional?

Please let me know if this is not clear and I should post complete code.

Thanks

**Comment by braingineer** [comment]
Right before you feed the data into your code (aka, before the fit function), can't you just reshape b? 

in other words:

```python
In [80]: np.ones((6,1))
Out[80]: 
array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [81]: np.ones((6,1)).reshape((6,1,1))
Out[81]: 
array([[[ 1.]],

       [[ 1.]],

       [[ 1.]],

       [[ 1.]],

       [[ 1.]],

       [[ 1.]]])

In [82]: np.ones((6,1)).reshape((6,1,1)).shape
Out[82]: (6, 1, 1)
```

**Comment by braingineer** [comment]
Though, also, can you show your Reshape code?

```python
In [87]: b = Input((1,))

In [88]: b._keras_shape
Out[88]: (None, 1)

In [90]: Reshape((1,1))(b)._keras_shape
Out[90]: (None, 1, 1)
```

additionally...

```python
In [91]: a = Input((1,), dtype='int16')

In [92]: emb = Embedding(4,20)(a)

In [94]: emb = Embedding(4,20)(a)

In [95]: emb._keras_shape
Out[95]: (None, 1, 20)


In [97]: merge([emb, b], mode='concat')
'''
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-97-120e0ca47319> in <module>()
----> 1 merge([emb, b], mode='concat')

/home/cogniton/research/code/keras/keras/engine/topology.py in merge(inputs, mode, concat_axis, dot_axes, output_shape, output_mask, name)
   1488                             node_indices=node_indices,
   1489                             tensor_indices=tensor_indices,
-> 1490                             name=name)
   1491         return merge_layer.inbound_nodes[0].output_tensors[0]
   1492     else:

/home/cogniton/research/code/keras/keras/engine/topology.py in __init__(self, layers, mode, concat_axis, dot_axes, output_shape, output_mask, node_indices, tensor_indices, name)
   1115                                        concat_axis, dot_axes,
   1116                                        output_shape,
-> 1117                                        node_indices, tensor_indices)
   1118             self.built = True
   1119             self.add_inbound_node(layers, node_indices, tensor_indices)

/home/cogniton/research/code/keras/keras/engine/topology.py in _arguments_validation(self, layers, mode, concat_axis, dot_axes, output_shape, node_indices, tensor_indices)
   1183                 raise Exception('"concat" mode can only merge layers with matching ' +
   1184                                 'output shapes except for the concat axis. ' +
-> 1185                                 'Layer shapes: %s' % (input_shapes))
   1186 
   1187     def call(self, inputs, mask=None):

Exception: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 1, 20), (None, 1)]
'''
In [98]: b2 = Reshape((1,1))(b)

In [99]: merge([emb, b2], mode='concat')
Out[99]: Join.0

In [100]: merge([emb, b2], mode='concat')._keras_shape
Out[100]: (None, 1, 21)

**Comment by code-ball** [comment]
@braingineer : Your initial solution of reshaping the input works well it seems.

If you do use Reshape layer like shown in your last post, it is not helpful as further layers like RNN do not accept Reshape layered input. You can have direct or embedded or merged input. 

You asked to show my Reshape code but it is exactly as you have shown. Is there anything specific you wanted to see?

Thanks

**Comment by braingineer** [comment]
> , it is not helpful as further layers like RNN do not accept Reshape layered input. You can have direct or embedded or merged input.

This isn't true.  I don't know what your code is doing, but it can't be exactly as you have shown.  Also, you haven't shown you input data.  Also, do you have everything updated?

```python
In [285]: a = Input((1,), dtype='int16')

In [286]: b = Input((1,))

In [287]: b2 = Reshape((1,1))(b)

In [288]: emb = Embedding(4,20)(a)

In [289]: merged = merge([emb, b2], mode='concat')

In [290]: from keras.layers import LSTM

In [291]: rnn = LSTM(10)(merged)

In [292]: from keras.engine import Model

In [293]: Model(input=[a,b], output=[rnn])
Out[293]: <keras.engine.training.Model at 0x7f905c73bd90>

In [294]: M = Model(input=[a,b], output=[rnn])

In [295]: rnn = LSTM(1)(merged)

In [296]: M = Model(input=[a,b], output=[rnn])

In [297]: M.compile(loss='MSE', optimizer='SGD')

In [298]: testA = np.random.randint(0,4,(6,1))

In [299]: testB = np.random.random((6,1))

In [300]: testY = np.random.random((6,1))

In [301]: M.evaluate([testA, testB], testY)
6/6 [==============================] - 0s
Out[301]: 0.22876673936843872
```

**Comment by code-ball** [comment]
This is strange. For some reason, I kept getting error when I was trying to do this. I will try out this simple example provided by you when I get back to my machine and see what is the problem. 

Thanks

**Comment by code-ball** [comment]
When I try to run your provided example, I get following error:

Exception: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, None, 20), (None, 1, 1)]

Does thi have something to do with keras version? I have 1.0.0

Thanks

**Comment by braingineer** [comment]
Have you modified Embedding?  It's not passing the correct shape forward.  Everything else is working.  I

Specifically, the `get_output_shape_for` function is not functioning correctly. 

The stock Keras code for that is:
```python
    def get_output_shape_for(self, input_shape):
        if not self.input_length:
            input_length = input_shape[1]
        else:
            input_length = self.input_length
        return (input_shape[0], input_length, self.output_dim)
```




I have a modified one so that I can embed higher dimensional tensors:
```python
    def get_output_shape_for(self, input_shape):
        if len(input_shape) > 2: 
            return input_shape + (self.output_dim,)
        
        if not self.input_length:
            input_length = input_shape[1]
        else:
            input_length = self.input_length
        return (input_shape[0], input_length, self.output_dim)
```

just to check, I checked out the master branch and it worked for the above example.

To sanity check that this is indeed the issue, print the following:
```python
print(emb._keras_shape)
```
 It should be (None, 1, 20)
