### ISSUE TITLE
Symbolical Reshape target_shape

### ISSUE THREAD

**Issue by fvisin** [fchollet/keras#2509]
The problem I am facing is that the input size is variable and I don't know how to get a symbolic shape in the middle of the graph.

Is there a way to:
1. Get the _symbolic_ shape of a layer
2. Specify a _symbolic_ (i.e. variable at run time) `target_shape` in `Reshape(target_shape)`

At the moment I came up with this ugly workaround. Is there something better?

``` python
x_shape = [10, None, None, None, 3]   # batch + 4 axes
model = models.Sequential() 
model.add(Convolution2D(64, 3, 3, border_mode='same', input_shape=x_shape[1:]))
# Will this cause the theano graph to be duplicated??
sh = model.get_output().shape
# Is there an easier way with core.Reshape??
model.add(Lambda(lambda x: x.flatten(ndim=2), output_shape=flattened_shape))
model.add(Activation(K.softmax))
reshape = Lambda(lambda x: x.reshape((sh[0], sh[1], T.prod(sh[2:]))))

# this is what I'd like to do instead
# model.add(Reshape((x.shape[0], x.shape[1], x.shape[2]*x.shape[3])))
```

**Comment by fchollet** [comment]
> Get the symbolic shape of a layer

In Theano:

`layer.output.shape`

In the general case:

`K.shape(layer.output)`

> Specify a symbolic (i.e. variable at run time) target_shape in Reshape(target_shape)

Can you not already do that with `Reshape`?

**Comment by fvisin** [comment]
> In the general case:
K.shape(layer.output)

There doesn't seem to be a `layer.output`
```python
my_conv = Convolution2D(64, 3, 3, border_mode='same', input_shape=[3, None, None])
my_conv.output

*** AttributeError: 'Convolution2D' object has no attribute 'output'
```

Did you mean to use `get_output()`, like this?
```python
my_conv = Convolution2D(64, 3, 3, border_mode='same', input_shape=[3, None, None])
sh = K.shape(my_conv.get_output())
```
What happens if I have a non-deterministic layer in the model and I call `get_output()` to get the shape of a feature map in the middle of the definition of the model? Will this cause the compilation of two separate theano graphs, i.e. the first one when I get the shape tensor and the second when the output of the whole model is used by Keras? Or is Keras smart enough to save the intermediate graph after the first call to `get_output()` and reuse it when `get_output()` is called for the second time?

> Can you not already do that with Reshape?

I think I tried `Reshape(10, 20, -1)` (which is Lasagne's syntax for "whatever else") but I guess I didn't try to use a symbolic variable right away. I will try to combine it with `get_output()`, thanks for the pointer!

**Comment by fchollet** [comment]
You seem to be using an outdated version of Keras.

Also: reshape takes a tuple of integers, e.g. Reshape((10, 20, -1))

**Comment by fvisin** [comment]
>You seem to be using an outdated version of Keras.

You are right, I just updated but it will take me some time to port my code to the new version of Keras.

> Also: reshape takes a tuple of integers, e.g. Reshape((10, 20, -1))

Yes, sorry for the typo. What I am trying to do is to pass a symbolical argument to reshape. Is it possible? Something like:
```python
my_conv = Convolution2D(64, 3, 3, border_mode='same', input_shape=[3, None, None])
sh = K.shape(my_conv.get_output())
Reshape((sh[0], sh[1], -1))
```

Thank you for your help.

**Comment by icemansina** [comment]
@fvisin Have you solve this problem, I face the same problem to reshape with symbolic size?

**Comment by yazfield** [comment]
same here! any solution?

**Comment by fvisin** [comment]
No, as far as I can tell there is no solution unless you want to dig into Keras and modify the Reshape layer. 

The Reshape layer only accepts integers. If you instead try to reshape the tensor directly in Theano (to avoid the Reshape layer completely), Keras fails to get information about the input shape of the next layer and crashes. The fact that Keras maintains a graph of node parallel to that of Theano seems like an unnecessary burden. This is not the case in other frameworks.

**Comment by urinieto** [comment]
Are there any plans to update Reshape to allow for this type of functionality? Thanks.

**Comment by Darthholi** [comment]
Ok i did dig into this:

this function would reshape for conv2d in the best way it could:

```
def ReshapeForConv2D(inp):
  sh_int = K.int_shape(inp)
  
  if (sh_int[1] is not None and sh_int[2] is not None):
    if K.image_dim_ordering() == 'th':
      out = Reshape((1, sh_int[1], sh_int[2]))(inp)  # -1 for batch size....
    else:
      out = Reshape((sh_int[1], sh_int[2],1))(inp)  # -1 for batch size....
  else: #undefined lengths...
    sh = K.shape(inp)
    
    if (sh_int[1] is not None):
      sh[1] = sh_int[1]
    if (sh_int[2] is not None):
      sh[2] = sh_int[2]
      
    # Is there an easier way with core.Reshape??
    if K.image_dim_ordering() == 'th':
      out = Lambda(lambda x: K.reshape(x, (-1, 1, sh[1], sh[2])))(inp) #-1 for batch size....
    else:
      out = Lambda(lambda x: K.reshape(x, (-1, sh[1], sh[2], 1)))(inp)
  return out
```

But if some dimension is not specified, later calling something like Flatten()  orTimeDistributed(Flatten()) would fail not knowing the dimensions...
