### ISSUE TITLE
Sequence Labeling example

### ISSUE THREAD

**Issue by muyinanhai** [fchollet/keras#2510]
Hi all,
Just like the problem here, but things are a little different.
https://github.com/fchollet/keras/issues/848

x_train = [[1,2,3,4,5,6,7,8],[2,4,3,4,5]]
y_train = [[[1],[2],[2],[1],[1],[1],[2],[3]],[[1],[2],[1],[2],[3]]]

What should  I do  to build this network?
What should I do if I want to control the window size of each label?( like https://github.com/fchollet/keras/issues/1029 comment by joetigger)
Thank you

**Comment by kaituoxu** [comment]
Have you solved this problem?
Can you put your solution?
I'm working on the same issue, i.e.sequence labeling.
Thanks a lot.

**Comment by muyinanhai** [comment]
Not yet. Most of suggests goes to  https://github.com/fchollet/keras/issues/40
