### ISSUE TITLE
Why cannot I import Input 

### ISSUE THREAD

**Issue by stevenhanjun** [fchollet/keras#2511]
When I use the sentence 'from keras.layers import Input' in commend line, it returns an error
![p](https://cloud.githubusercontent.com/assets/4454187/14804704/3fee657c-0b98-11e6-8656-060c9c64a15d.png)

**Comment by bhtucker** [comment]
Try the first error first: maybe you have a `dot_parser` problem?
http://stackoverflow.com/questions/15951748/pydot-and-graphviz-error-couldnt-import-dot-parser-loading-of-dot-files-will

Also, it's more helpful to post the text than a screenshot of the text

**Comment by Imorton-zd** [comment]
You should ensure your keras have been updated to newest. You could uninstall keras first, then install.

**Comment by pasky** [comment]
Overally, I think this issue can be closed.

My story: (A) having old keras version systemwide, (B) having new keras version in virtualenv, (C) executing a script as `./script.py` (via #!/usr/bin/python3, bypassing the virtualenv) rather than as `python3 script.py`
