### ISSUE TITLE
Multi GPU in Keras

### ISSUE THREAD

**Issue by ghost** [fchollet/keras#2513]
Hello,

Is it a way to configure multi gpu in Keras ?

Thanks, regards
Kevin

**Comment by henry0312** [comment]
See https://github.com/fchollet/keras/issues/2436

**Comment by arita291** [comment]
Hi,
Thanks, but this is still not clear how to configure Theano...
It seems like an hacking exercice..... ( plug into the source code to see how it works....).

**Comment by fluency03** [comment]
If you are using theano as backend, you have do do this by following [this](http://deeplearning.net/software/theano/tutorial/using_multi_gpu.html).

If you are using tensorflow, you can see [this](http://blog.keras.io/#multi-gpu-and-distributed-training)

**Comment by qbilius** [comment]
Correct link to the TensorFlow examples is [this](http://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html#multi-gpu-and-distributed-training).
