### ISSUE TITLE
Setting callbacks order, including default callbacks

### ISSUE THREAD

**Issue by carlthome** [fchollet/keras#2521]
A minor issue, admittedly, but is there a builtin way to set the call order of a model's callbacks (`on_epoch_end`, `on_batch_begin` and so on)? I assume the callbacks follow the input list's ordering, but what about the defaults. Specifically ProgbarLogger, since it seems to be called last, the output gets wonky in case any other callback also prints to stdout during `on_epoch_end`.

**Comment by braingineer** [comment]
I actually think that this issue could/should trigger a callback rework.  I've been overriding callback instantiations with: 

```python
        self.history = cbks.History()
        callbacks = [cbks.BaseLogger()] + callbacks + [self.history]
        if verbose and all([not isinstance(cbk, cbks.ProgbarLogger) for cbk in callbacks]):
            callbacks += [cbks.ProgbarLogger()]
        callbacks = cbks.CallbackList(callbacks)
```

because I want to input my own progbar.  Maybe the CallbackList could be exposed as an optional input, so you can get more fine-grained control.  then you could do something like 
```python
if callback_list_input is None: 
    ### default behavior
```

**Comment by carlthome** [comment]
A much better way would be to use factories but that doesn't seem common in Python. 

A fast and silly solution would be to allow the `callbacks` parameter to be either a list or a dictionary with optional priority, and maybe just have the defaults accessible through documented keys and letting -1 represent "never call". It would be completely backwards compatible but ugly.

Ultimately maybe just follow the decorator like functional API for the callbacks?

**Comment by braingineer** [comment]
> a much better way
oh ya. my way is totally ugly and hackish. I just needed it work quickly. 

so, idea list:
1. allow `callbacks` to be input into `model.fit(...)` 
2. decorator? not sure I fully understand what you mean.  Do you mean the `__call__` ability of containers?

possible 3, just to elucidate a full range of options:

What if it became fully functional and Callbacks were functional as well? 

```python
some_callbacks = [History(), Whatever()]
callbacks = Callbacks(some_callbacks, option='something')
model = Model(...)
model = callbacks(model) ## callbacks __call__ just modifies model and returns the model
```

on calling `model.fit` or some other method, it would internally check to see if it had any callbacks added, and if not, then put in the defaults.  

for short code, I have a compose function 
```python
def compose(*layers):
    def func(x):
        out = x
        for layer in layers[::-1]:
            out = layer(out)
        return out
    return func
```
and then do things like
```python
        F_alignlex = compose(RepeatVector(repeat_N),
                             Dropout(p_mlp), 
                             Dense(mlp_size, activation='relu'),
                             concat)
```

so then, you could do:

```python
callbacks = Callbacks([some_callback, etc])
optimizer = Adam(...)
compose(callbacks, optimizer)(model)
```

In this way, you could allow for the full range of customization without having to muck with the internals of Model.  It resembles the [visitor design pattern](https://en.wikipedia.org/wiki/Visitor_pattern)

**Comment by carlthome** [comment]
On a different note, that compose function looks neat. I think it should be used to deprecate Sequential() entirely and have everyone use the functional API.

**Comment by braingineer** [comment]
It makes sense to have it, given function composition is a major point of this API.   And the repeatable composed functions are easier to read (fuller example):

```python
        F_multiword = compose(F_attend,
                              F_embedword)
        F_singleword = compose(Fix(),
                               F_embedword)
        F_alignlex = compose(RepeatVector(repeat_N),
                             Dropout(p_mlp), 
                             Dense(mlp_size, activation='relu'),
                             concat)
        children = F_multiword(child_in)
        parent = F_singleword(parent_in)
        grandparent = F_singleword(grandparent_in)

        lexical_context = F_alignlex([children, parent, grandparent])
```

**Comment by dshahrokhian** [comment]
Any news on this regard? Can the order be set in newer versions?
