### ISSUE TITLE
Meet ZeroDivisionError when add_node(Dense) with Graph()

### ISSUE THREAD

**Issue by Shen256** [fchollet/keras#2527]
......
    convs = []
    model = Graph()
    # adding the input as usual
    model.add_input(name='sentence', input_shape=(1,), dtype='int')
    # passing the sentence through the Embedding layer
    model.add_node(Embedding(max_features, embedding_dims, dropout=0.2), name='sentence_embeddings', input='sentence')

    # and now create the convolutions/max_pooling
    for i in filter_length:
        model.add_node(Convolution1D(nb_filter=nb_filter,
                                     filter_length=i,
                                     border_mode="valid",
                                     activation="relu",
                                     subsample_length=1),
                                     name=str(i)+'_convolution',
                                     input='sentence_embeddings',
                                     )

        # that's an approximation of 1-maxpooling that i never really checked.
        model.add_node(MaxPooling1D(pool_length= maxlen - i + 1), name=str(i)+'_maxpooling', input=str(i)+'_convolution')
        model.add_node(Flatten(), name=str(i)+'_sentence_embedding', input=str(i)+'_maxpooling')
        convs.append(str(i)+'_sentence_embedding')

    # We add a vanilla hidden layer:
    model.add_node(Dense(hidden_dims * len(convs)), inputs=convs, name='h1')
    ......

When I ran the code, ZeroDivisionError happened.

    Build model...
    Traceback (most recent call last):
      File "rtp_cnn00.py", line 87, in <module>
        model.add_node(Dense(hidden_dims * len(convs)), inputs=convs, name='h1')
      File "/Library/Python/2.7/site-packages/keras/legacy/models.py", line 184, in add_node
        layer.add_inbound_node(merge)
      File "/Library/Python/2.7/site-packages/keras/engine/topology.py", line 537, in add_inbound_node
        self.build(input_shape=input_shapes[0])
      File "/Library/Python/2.7/site-packages/keras/layers/core.py", line 594, in build
        name='{}_W'.format(self.name))
      File "/Library/Python/2.7/site-packages/keras/initializations.py", line 58, in glorot_uniform
        s = np.sqrt(6. / (fan_in + fan_out))
    ZeroDivisionError: float division by zero

I just copied the code at https://github.com/fchollet/keras/issues/1023, and added a new line:  model.add_node(Dense(hidden_dims * len(convs)), inputs=convs, name='h1')
The ''hidden_dims'' is equal to the number of filters.

When tracing the error, I found that self.build(input_shape=input_shapes[0]) received a negative value whose the absolute value was right.
I don't know how to solve it.

**Comment by rpinsler** [comment]
Graph is deprecated since now, so I'd suggest you use the new functional API instead.

**Comment by Shen256** [comment]
@rpinsler Thanks. I rewrote the code using the functional API. And it worked well.

**Comment by bowlesbe** [comment]
Im still seeing this issue, not using Graph and using the most recent API I tried both the functional API as well as the Sequential model. 

This code is sufficient to replace the error

```

model = Sequential([

    Embedding(2064, 300,
              weights=[emb.embeddings], input_length=91,
              trainable=False),

    Conv1D(128, 5, activation='relu'),
    MaxPooling1D(5),
    Conv1D(128, 5, activation='relu'),
    MaxPooling1D(5),
    Conv1D(128, 5, activation='relu'),
    MaxPooling1D(35),  # global max pooling
    Flatten(),
    Dense(128, activation='relu'),
    Dense(1, activation='softmax'),

])```

**Comment by amorroxic** [comment]
This is the functional API version (taken from the blog post) that triggers the same ZeroDivisionError:

`
embedding_dimension = 300
max_sequence_length = 100
embedding_matrix = np.zeros((len(vocab) + 1, embedding_dimension)) # adding 1 to account for 0th index (for masking)
for word, i in vocab.items():
    embedding_vector = embeddings.vector(word)
    if embedding_vector is not None:
        # words not found in embedding index will be all-zeros.
        embedding_matrix[i,:] = embedding_vector
embedding_layer = Embedding(input_dim=len(vocab) + 1,
                            output_dim=embedding_dimension,
                            weights=[embedding_matrix],
                            input_length=max_sequence_length
                            )
sequence_input = Input(shape=(max_sequence_length,), dtype='int32')
embedded_sequences = embedding_layer(sequence_input)
x = Conv1D(128, 5, activation='relu')(embedded_sequences)
x = MaxPooling1D(5)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(5)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(35)(x)  # global max pooling
x = Flatten()(x)
x = Dense(128, activation='relu')(x)
preds = Dense(.., activation='softmax')(x)
model = Model(sequence_input, preds)
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])

`

**Comment by hits-nlp** [comment]
So, has there been a solution to this? Should I just go back to an older version?
As the previous comment points out, this bug (if it is one) destroys a prominently published tutorial, so I'd have expected that it would be fixed asap.
Is there a way around this, by maybe changing the model structure?

Thanks for any hints!

**Comment by yhenon** [comment]
There is no bug here. The model pools dimensions quite aggressively, so the input shape has to be sufficiently large. The model runs fine for inpute_shape >= 999

Code:
```
embedding_dimension = 3000
max_sequence_length = 999
embedding_layer = Embedding(input_dim=1000 + 1,
                            output_dim=embedding_dimension,
                            input_length=max_sequence_length
                            )

sequence_input = Input(shape=(max_sequence_length,), dtype='int32')
embedded_sequences = embedding_layer(sequence_input)
x = Conv1D(128, 5, activation='relu')(embedded_sequences)
x = MaxPooling1D(5)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(5)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(35)(x)  # global max pooling
x = Flatten()(x)
x = Dense(128, activation='relu')(x)
preds = Dense(1, activation='softmax')(x)
model = Model(sequence_input, preds)
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])
```
Output:

```
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 999)               0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 999, 3000)         3003000   
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 995, 128)          1920128   
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 199, 128)          0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 195, 128)          82048     
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 39, 128)           0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 35, 128)           82048     
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 1, 128)            0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 129       
=================================================================
```

Also, note that `Dense(1,activation='softmax')` will run but makes no sense, since it will always output `1`. 

This issue should be closed.
