### ISSUE TITLE
Missing file docs/sources/layers/writing-your-own-keras-layers.md when building documentation

### ISSUE THREAD

**Issue by ChristianThomae** [fchollet/keras#2529]
When running `mkdocs build` on a up to date Keras repo (c9f7d970e97d5a) following the instructions in `docs/README.md` the following error happens:

`FileNotFoundError: [Errno 2] No such file or directory: '[..]/keras/docs/sources/layers/writing-your-own-keras-layers.md'`

In addition, there could be a small error in the example in `http://keras.io/layers/writing-your-own-keras-layers/`:
`super(Layer, self).__init__(**kwargs)` is supposed to be `super(mylayer, self).__init__(**kwargs)` on line 7 in function `__init__`.

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by asmith26** [comment]
I can confirm I'm missing this file too (i.e. not autogenerated or in templates).

**Comment by asmith26** [comment]
Thanks @fchollet - 36a829c20d5dcd4d8ba120781235c278588b6bb7
