### ISSUE TITLE
GPU memory leaks when training stateful LSTMs

### ISSUE THREAD

**Issue by mirikle** [fchollet/keras#2535]
I'm training a model using stateful LSTM on tensorflow backend, and see some suspicious memory leaks too.

I trained my model using 10,000 batch size at first, after around 20 iterations, OOM exception.

Then I lowered the batch size to 2,000, after around 30 iterations, OOM again.

My GPU memory always shows 95% full when I'm not fitting the model.

Any quick way to work around this?

**Comment by carlthome** [comment]
Theano or TensorFlow?

**Comment by carlthome** [comment]
I can't speak for TensorFlow's custom GPU memory allocator but for Theano it's not weird that GPU memory is constant as it typically relies on pre-allocation with [cnmem](https://github.com/NVIDIA/cnmem) for performance reasons.

I've found that it's good to keep some room in the GPU memory for spikes during training. Maybe 500 MB or so just to be sure. It's not necessarily a memory leak, but rather that GC takes a little time and can't keep up if you're too close to 100% memory.

**Comment by mirikle** [comment]
You are right that the GPU mem allocation seems to be constant. The training still runs into OOM

**Comment by nouiz** [comment]
Can you show the full oom error? It contain much information.
