### ISSUE TITLE
CNN model for sentences' similarity

### ISSUE THREAD

**Issue by dvector89** [fchollet/keras#2543]
Hi, everyone.
I'm building a model for measuring the similarity of two sentences. I want to use a CNN network to encode the sentences pair to vectors pair, then measure the similarity of two vectors. The code i write like this ,but it cannot work.

def build_model():
    sent1 = Input(shape=(word_num, word_embedding_size))
    sent2 = Input(shape=(word_num, word_embedding_size))

```
shared_cnn = Convolution1D(nb_filter=nb_filter,
                                             filter_length= filter_length,
                                             border_mode='valid',
                                             activation='relu',
                                             subsample_length=1,
                                             inpute_shape=(word_num, word_embedding_size))

shared_cnn = MaxPooling1D(pool_length=2)(shared_cnn)
shared_cnn = Flatten()(shared_cnn)
shared_cnn = Dense(hidden_dim, activation='rely')
sent1_cnn = shared_cnn(sent1)
sent2_cnn = shared_cnn(sent2)
merged = merge([sent1_cnn, sent2_cnn], mode='concat', concat_axis=1)
predict = Dense(1,activation='sigmoid')(merged)
model = Model(input=[sent1, sent2], output=predict)
model.compile(loss='mean_squared_error', optimizer='adam')
return model. 
```

**Comment by braingineer** [comment]
> The code i write like this ,but it cannot work.

Can you be more specific?  What error does it give?  

Also, I can see at least 2 typos in the code you've pasted.   Is this the actual code you've run?

--
note the rely
>shared_cnn = Dense(hidden_dim, activation='rely') 

--
note the period
>return model.

**Comment by dvector89** [comment]
@barvinograd Thank you very much. The error information is like this:
File "sentence_similarity_cnn_share.py", line 144, in <module>
    model = construct_model()
  File "sentence_similarity_cnn_share.py", line 23, in construct_model
    shared_cnn = MaxPooling1D(pool_length=2)(shared_cnn)
  File "/home/llshi/anaconda2/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/topology.py", line 441, in __call__
    self.assert_input_compatibility(x)
  File "/home/llshi/anaconda2/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/topology.py", line 377, in assert_input_compatibility
    if K.ndim(x) != spec.ndim:
  File "/home/llshi/anaconda2/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/backend/theano_backend.py", line 57, in ndim
    return x.ndim
AttributeError: 'Convolution1D' object has no attribute 'ndim'

**Comment by braingineer** [comment]
You aren't calling the layer.  instantiating it like you have it just establishes the function.  In other words, `shared_cnn` on line 1 is not a tensor.  

Create an Input layer, then call `shared_cnn` on that.  [details here](http://keras.io/getting-started/functional-api-guide/)

Or, use the Sequential API and follow [one of the examples](https://github.com/fchollet/keras/blob/master/examples/imdb_cnn.py)

**Comment by dvector89** [comment]
@braingineer Thank you.
