### ISSUE TITLE
Sequence to sequence training and predicting (Decoder Encoder)

### ISSUE THREAD

**Issue by mininaNik** [fchollet/keras#2545]
I have 2 questions:
1. I discussed about sequence to sequence learning where the length of input and output are different in problem #2403 and I concluded that I have to use encoder and decoder architecture. I have a fundamental question, what is the reason that keras doesn't support this case and encoder and decoder is needed.  Is it a fundamental problem of recurrent neural networks (if it is, can anyone explain this to me?), or is it the Keras problem that doesn't support this case? 

2.When I have the following model:

```
      model = Sequential()
      hidden_neurons = 50 
      model.add(LSTM(hidden_neurons,
             batch_input_shape=(batch_size, n_prev, 1),
             forget_bias_init='one',
             return_sequences=True,
             stateful=True))
     model.add(LSTM(hidden_neurons,
             batch_input_shape=(batch_size, n_prev, 1),
             forget_bias_init='one',
             return_sequences=False,
             stateful=True))

    model.add(Dense(n_nxt))
    model.compile(loss='mse', optimizer='rmsprop')
```

consider batch_size =1, then which of the following statement is true:
A. All _n_prev_ inputs are fed to all  _hidden_neurons_ in the first LSTM layer?
B. At each time only one of _in_prev_ inputs are fed  to the first LSTM layer and it will propagate to all other _hidden_neurons_ in this layer?

**Comment by kaituoxu** [comment]
batch_input_shape=(batch_size, timesteps, feature_dim)

**Comment by dragonhyq** [comment]
@mininaNik  Question about your code: 

the first LSTM has an output dimension of hidden_neurons, why do you (or why are you allowed to) define the second LSTM input dimension to be 1?

**Comment by dragonhyq** [comment]
@mininaNik I guess batch_input_shape for the second LSTM is ignored, as answered for Q2 in #3038
