### ISSUE TITLE
Graph code breaks updating to 1.0.1 from 0.3.2

### ISSUE THREAD

**Issue by esube** [fchollet/keras#2549]
I had a graph model that has one input, a middle feature extractor sequential model (called 'seq_model') added as a node in the graph right after the input node, and multiple output nodes after the feature extractor sequential model. This code works fine with keras version 0.3.2.

I upgraded keras to version 1.0.1 without any changes to the model as well as any training code that uses the model. 

The first thing it complains were the ThresholdedLinear, ThresholdedReLU and SReLU activation are not definded. Since those were not important in my training, I just commented those out.

Then, it failed with the following exception. 

Exception: Graph disconnected: cannot obtain value for tensor activation_input_1 at layer "seq_model". The following previous layers were accessed without issue: []

Since this same code works even after reverting back to 0.3.2, is graph legacy API broken? Is there any intent in supporting Graph in the future or will it be removed in future releases in favor of the new functional API?

Thanks in advance for any help on this.

**Comment by carlthome** [comment]
Just guessing here but _deprecated_ typically can be interpreted as "you're on your own from here on", and perhaps its just easier to port to the new functional API. It's also way more fun to work with.

**Comment by esube** [comment]
I ported out the graph code to the functional API and it seems easier than I thought. However, the same network structure, data and all, the losses seem a bit different by a factor of two or so. Also, the model compile time is significantly increased and it took a significant amount of delay time to start prediction compared to the graph API. I am not sure what to make of these.

The API looks cleaner and easier to follow, tho, I must admit.
