### ISSUE TITLE
Graph predict returns only one output for one input

### ISSUE THREAD

**Issue by mbz** [fchollet/keras#2551]
In version 1.0.1 it seems that `Graph.predict` function only returns one of the outputs for only one of the inputs, instead of returning all the outputs for all of the inputs.

**Comment by carlthome** [comment]
Graph is deprecated though, so maybe just port to the new [functional API](keras.io/getting-started/functional-api-guide/).

**Comment by pchankh** [comment]
I had the same issue with 1.0.1.  Any tools to convert from graph model and an example for the predict?

**Comment by mbz** [comment]
I ended up reverting Keras back to 0.3.2. That fixes the code.

**Comment by braingineer** [comment]
@mbz 

```python
    def predict(self, data, batch_size=128, verbose=0):
        '''Generates output predictions for the input samples
        batch by batch.

        Arguments: see `fit` method.
        '''
        x = self._get_x(data)
        output_list = super(Graph, self).predict(x, batch_size=batch_size,
                                                 verbose=verbose)
        return dict(zip(self._graph_outputs, output_list))
```

and inside the super method (`keras.engine.training.Model._fit_loop`

```python
        if len(outs) == 1:
            return outs[0]
        return outs
```

Basically, the single length list correction resulted in a bad assumption in the Graph class.

temporary fix 

```python
    def predict(self, data, batch_size=128, verbose=0):
        '''Generates output predictions for the input samples
        batch by batch.

        Arguments: see `fit` method.
        '''
        x = self._get_x(data)
        output_list = super(Graph, self).predict(x, batch_size=batch_size,
                                                 verbose=verbose)
        if not isinstance(output_list, list):
            output_list = list
        return dict(zip(self._graph_outputs, output_list))
```

**Comment by carlthome** [comment]
So issue resolved then. @mbz, don't forget to close it.

By the way, downgrading is never a good solution.

**Comment by pchankh** [comment]
I end up converting graph to functional api. Previous patch suggested did not work.
Dr

**Comment by braingineer** [comment]
@ the functional api bit: awesome.

@ the not working bit: weird.  There must have been another issue. Do you remember? It should  (probably) be fixed for backwards compatibility reasons.
