### ISSUE TITLE
Multiple workers gone from fit_generator

### ISSUE THREAD

**Issue by carlthome** [fchollet/keras#2554]
It was a very useful feature. Why was it removed? Could it be readded?

**Comment by roryhr** [comment]
I'd like to see it back too, and it wouldn't be hard with joblib.

**Comment by carlthome** [comment]
Maybe you could propose a pr? @roryhr  :smile: 

@fchollet, I guess it was removed because the implementation felt messy, rather than the feature not being wanted? I hope.

**Comment by carlthome** [comment]
Duplicate issue
