### ISSUE TITLE
Question about layer_from_config

### ISSUE THREAD

**Issue by dsy412610** [fchollet/keras#2563]
I want to used the model that I have saved with a custom layer, but how to set the parameter custom_objects? Thanks!

**Comment by dsy412610** [comment]
I have solved the problem.

**Comment by htw2012** [comment]
Hello @dsy412610 ,
I also have met the problem like 'AttributeError: 'Sequential' object has no attribute 'from_config''.
How to solve it?

**Comment by joelthchao** [comment]
@htw2012 Do you update Keras to the latest version (1.0.1)?

**Comment by htw2012** [comment]
Not yeah.
Just version0.3.2.You mean that I can solve it by updating keras. @joelthchao

**Comment by joelthchao** [comment]
@htw2012 In 0.3.2, you only have:
```python
# function in model.py, not a static method of class Sequential
def model_from_config(config, custom_objects={}):
```
In 1.0.1, you can use
```python
@classmethod
def from_config(cls, config):
```
Reconmend you to update to the latest version!

**Comment by htw2012** [comment]
Ok, I'll try it,thank you. @joelthchao

**Comment by dsy412610** [comment]
I used the model as following:
`
model = Sequential()
model.add(Convolution2D(96, 11, 11, border_mode = 'valid', input_shape = (3, 227, 227), subsample = (4, 4)))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))
model.add(MaxPooling2D(pool_size = (3, 3), strides = (2, 2), border_mode = 'valid'))

model.add(ZeroPadding2D(padding = (2, 2)))
model.add(Convolution2D(256, 5, 5, border_mode = 'valid'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))
model.add(MaxPooling2D(pool_size = (3, 3), strides = (2, 2), border_mode = 'valid'))

model.add(ZeroPadding2D(padding = (1, 1)))
model.add(Convolution2D(384, 3, 3, border_mode = 'valid'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))

#output_length = 13
model.add(ZeroPadding2D(padding = (1, 1)))
model.add(Convolution2D(384, 3, 3, border_mode = 'valid'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))

model.add(ZeroPadding2D(padding = (1, 1)))
model.add(Convolution2D(256, 3, 3, border_mode = 'valid'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))
model.add(MaxPooling2D(pool_size = (3, 3), strides = (2, 2), border_mode = 'valid'))

model.add(Flatten())
model.add(Dense(512, init = 'normal'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))

model.add(Dense(512, init = 'normal'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))

model.add(Dense(nb_classes, init = 'normal'))
model.add(BatchNormalization(axis=1))
model.add(Activation('softmax'))

sgd = SGD(lr = 0.5, decay = 1e-6, momentum = 0.9, nesterov = True)
model.compile(loss = 'categorical_crossentropy', optimizer = sgd, metrics=['accuracy'])

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=1,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False)  # randomly flip images

datagen.fit(X_train)#, rounds=2, augment=True)

model.fit_generator(datagen.flow(X_train, Y_train, batch_size=batch_size),
                        samples_per_epoch=X_train.shape[0],
                        nb_epoch=nb_epoch, show_accuracy=True,
                        validation_data=(X_test, Y_test),
                        nb_worker=1)
`

**Comment by dsy412610** [comment]
I used the model as following:
`model = Sequential()
model.add(Convolution2D(96, 11, 11, border_mode = 'valid', input_shape = (3, 227, 227), subsample = (4, 4)))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))
model.add(MaxPooling2D(pool_size = (3, 3), strides = (2, 2), border_mode = 'valid'))

model.add(ZeroPadding2D(padding = (2, 2)))
model.add(Convolution2D(256, 5, 5, border_mode = 'valid'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))
model.add(MaxPooling2D(pool_size = (3, 3), strides = (2, 2), border_mode = 'valid'))

model.add(ZeroPadding2D(padding = (1, 1)))
model.add(Convolution2D(384, 3, 3, border_mode = 'valid'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))

#output_length = 13
model.add(ZeroPadding2D(padding = (1, 1)))
model.add(Convolution2D(384, 3, 3, border_mode = 'valid'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))

model.add(ZeroPadding2D(padding = (1, 1)))
model.add(Convolution2D(256, 3, 3, border_mode = 'valid'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))
model.add(MaxPooling2D(pool_size = (3, 3), strides = (2, 2), border_mode = 'valid'))

model.add(Flatten())
model.add(Dense(512, init = 'normal'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))

model.add(Dense(512, init = 'normal'))
model.add(BatchNormalization(axis=1))
model.add(Activation('sigmoid'))

model.add(Dense(nb_classes, init = 'normal'))
model.add(BatchNormalization(axis=1))
model.add(Activation('softmax'))

sgd = SGD(lr = 0.5, decay = 1e-6, momentum = 0.9, nesterov = True)
model.compile(loss = 'categorical_crossentropy', optimizer = sgd, metrics=['accuracy'])

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=1,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False)  # randomly flip images

datagen.fit(X_train)#, rounds=2, augment=True)

model.fit_generator(datagen.flow(X_train, Y_train, batch_size=batch_size),
                        samples_per_epoch=X_train.shape[0],
                        nb_epoch=nb_epoch, show_accuracy=True,
                        validation_data=(X_test, Y_test),
                        nb_worker=1)`
