### ISSUE TITLE
activity regularization with multiple inbound nodes

### ISSUE THREAD

**Issue by chentingpc** [fchollet/keras#2569]
I am using functional API (which is great!), when applying one layer multiple times with different input nodes, the activity regularization would not work. Giving following errors:

Exception: Layer xx has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use `get_output_at(node_index)` instead.

Here's my solution:

instead of using `output = self.layer.output,` we can do 
```
for i in range(len(self.layer.inbound_nodes)):
            output = self.layer.get_output_at(i)
```
and add original regularization according to each of the output. I have tested it on my problem, but if you find anything.

**Comment by fchollet** [comment]
You're right, this is something that was overlooked. You should submit a PR. Thanks!
