### ISSUE TITLE
TensorBoard Callback Deprecated

### ISSUE THREAD

**Issue by discomethod** [fchollet/keras#2570]
Just did fresh upgrades of Keras and TensorFlow today, and there seems to be a change to the TensorBoard API that isn't reflected in the Keras callback implementation. When I train a model with the TensorBoard callback:

```
tb = TensorBoard(log_dir='./logs')
model.fit(X_train, y_train, batch_size=nb_batches, nb_epoch=nb_epochs,
    verbose=1, validation_data=(X_test, y_test), callbacks=[tb])
```

I get a warning:

> WARNING:tensorflow:Passing a `GraphDef` to the SummaryWriter is deprecated. Pass a `Graph` object instead, such as `sess.graph`.

**Comment by fchollet** [comment]
That would be a one line fix, replacing `sess.graph_def` with `sess.graph` in the TensorBoard callback (`callbacks.py`, line 461). Could you try it, check that it works, check that it also works with the previous version of TF, and submit a PR?

**Comment by jingzhehu** [comment]
The warning went away after applying the fix suggested by @fchollet.

**Comment by bnaul** [comment]
I made the same change in my fork but this change does not work with previous versions of Tensorflow. Would a check like this be acceptable?
```
tf_version = tuple(int(i) for i in tf.__version__.split('.'))
if tf_version >= (0, 8, 0):
    ...
else:
    ...
```

**Comment by fchollet** [comment]
There is a PR for the fix, please post there. Yes, I think a conditional
statement would be the right way to handle this.
