### ISSUE TITLE
Keras output shape is different for versions 0.3.2 -> 1.0.1

### ISSUE THREAD

**Issue by prinsherbert** [fchollet/keras#2579]
I found some of my personal tests failing after upgrading from 0.3.2 to 1.0.1 (0.3.3 als didn't work, but I did not investigate that).

The problem is that when I train a model with inputs of shape (100, N0), (100, N1), ... etc I would expect an output of (100, Nout), yet I get an output of shape (Nout). This is illustrated by this minimal working example (using version 1.0.1):

```
import keras
from keras.models import Graph
from keras.layers import Dense
import numpy

N_continuous = 10
N_categorical = 5
N_output = 2

categorical = (numpy.random.randn(100,N_categorical) > 0).astype(numpy.float32)
continuous  = numpy.random.randn(100,N_continuous)
output      = numpy.random.randn(100, N_output)

graph = Graph()

graph.add_input(name='continuous', input_shape=(N_continuous, ))
graph.add_node(Dense(N_output, activation='linear'), name='linear_models', input='continuous')

graph.add_output(name='regression_output', input='linear_models')

graph.compile(optimizer='rmsprop', loss={'regression_output': 'mse'})

graph.fit(data={'continuous': continuous, 'categorical': categorical, 'regression_output': output}, nb_epoch=1)
print( graph.predict({
    'continuous': continuous,
    'categorical': categorical,
    'regression_output': output
})['regression_output'].shape )

print(keras.__version__)
```

The output is `(2, )` for the shape and `1.0.1` for the `__version__`.

In version 0.3.2 the output shape is `(100, 2)`, which I would expect. Why are the shapes different for different versions? Which one is/ones are correct? Is my NN-architecture 'defective'?

Theano has version `0.9.0dev0.dev-5e5e5cc5581a88ab425b9bd73b7719efbd10f6d3`

Thank you in advance!

**Comment by NasenSpray** [comment]
It's a problem with the legacy API and only happens with single output graphs. Temporary fix: remove lines [905-906 in engine/training.py](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L905-L906)

@fchollet: legacy `Graph.predict` expects a list of results, but `Model._predict_loop` returns the bare result when there's only one output...

**Comment by prinsherbert** [comment]
Thank you @NasenSpray. For my comfort: this is a Keras or lower (theano, tensorflow, ...) issue, and not something in my code?

**Comment by NasenSpray** [comment]
> For my comfort: this is a Keras or lower (theano, tensorflow, ...) issue, and not something in my code?

It's a Keras issue. But you shouldn't use the graph API anymore, it was deprecated in favor of the [functional API](http://keras.io/models/model/).

> Moreover, most neural networks will have one output-node with multiple output-values, so wouldn't this affect most users?

idk, maybe? (note: I'm just another user)

**Comment by bayesrule** [comment]
@NasenSpray  any update on Theano/Theano/#4289 , still using your fork to avoid this problem =)

**Comment by prinsherbert** [comment]
> But you shouldn't use the graph API anymore, it was deprecated in favor of the functional API.

Clear! Thanks :)

**Comment by prinsherbert** [comment]
@bayesrule Could state the relevance of your comment to this thread?

**Comment by NasenSpray** [comment]
@prinsherbert: I'm a lazy ass who needs a reminder every once in a while. It's unrelated to this thread.
