### ISSUE TITLE
TypeError: can't pickle function objects, when applying regularizers

### ISSUE THREAD

**Issue by bayesrule** [fchollet/keras#258]
This happened when I added l1/l2 regularizer to a dense layer and intended to save the model with pickle. Many thanks.

**Comment by fchollet** [comment]
Do you have code to repro?

**Comment by bayesrule** [comment]
I think so =)

def create_model():
    model = Sequential()
    model.add(Dense(X_train.shape[1], 1024, init='glorot_uniform'))
    model.add(Activation('relu'))
    # model.add(Dropout(0.5))

    model.add(Dense(1024, 1024, init='glorot_uniform'))
    model.add(Activation('relu'))
    # model.add(Dropout(0.5))

    model.add(Dense(1024, 1024, init='glorot_uniform'))
    model.add(Activation('relu'))
    
    model.add(Dense(1024, Y_train.shape[1], init='glorot_uniform', W_regularizer = l1(0.01)))
    model.add(Activation('linear'))
    return model

model = create_model()
model.compile(loss='mean_squared_error', optimizer='adadelta')

model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch, verbose=1, validation_data=(X_val, Y_val), shuffle=True)

cPickle.dump(model, open("./model.pkl", "wb"))

I'm dealing with regression tasks here, so accuracy=False. But this is not relevant to the issue.

#--------------------------------------

BTW, another flaw is if I add a checkpointer as callback to the model.fit() function, after each epoch the checkpointer will do a validation, if verbose is on, it'll print out the info. However, this info will NOT start a NEWLINE, it'll just append to the tail of the progress bar produced during training epoch.

**Comment by fchollet** [comment]
> However, this info will NOT start a NEWLINE, it'll just append to the tail of the progress bar produced during training epoch.

I fixed that issue some days ago. Make sure your version of Keras is up to date.

I'll look at the pickling issue. It's quite possible that pickling is simply not possible in this case. Any reason why you can't use the efficient hdf5-based weight saving function instead?

**Comment by bayesrule** [comment]
I'm using save_weights() to save as hdf5 now. =) 

The reason why I prefer pickle is when we need to reuse the model for prediction, we don't have to recreate the model and worry whether the recreated model structure is identical to the saved one.

Nevertheless, simply saving weights has another overwhelming advantage (I suppose), which is after loading the weights, we can add more layers to the structure. This can be useful if considering pre-training. Not sure if I'm right, still experimenting...

Many thanks for creating Keras!

**Comment by iskandr** [comment]
I think I'm having the same problem. When pickling this model:

```
>>> print(model.get_config())
[{'output_dim': 64, 'init': 'lecun_uniform', 'name': 'Embedding', 'input_dim': 20}, {'name': 'Flatten'}, {'output_dim': 400, 'init': 'lecun_uniform', 'activation': 'linear', 'name': 'Dense', 'input_dim': 576}, {'beta': 0.1, 'activation': 'relu', 'name': 'Activation', 'target': 0}, {'p': 0.25, 'name': 'Dropout'}, {'output_dim': 1, 'init': 'lecun_uniform', 'activation': 'linear', 'name': 'Dense', 'input_dim': 400}, {'beta': 0.1, 'activation': 'sigmoid', 'name': 'Activation', 'target': 0}]
```

I get this error:

```

Traceback (most recent call last):
  ...line 65, in __init__
    pickle.dumps(self.model)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 663, in _batch_setitems
    save(v)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <function weighted at 0x10a7938c0>: it's not found as keras.models.weighted
```

It would be useful for me to actually pickle model (rather than just load/save weights) since I'd rather load the full network from disk (rather than storing all the hyperparameters in Python code).

**Comment by vzhong** [comment]
what would be a fix for this, given that one needs regularization? Would we need to refactor functions like constraints and regularizers into classes?

**Comment by ClemDoum** [comment]
As a temporary solution I used the tip from [this post](http://stackoverflow.com/a/1816969) in order to be able to pickle the regularizers and constraints.

**Comment by Imorton-zd** [comment]
@bayesrule  @fchollet  @iskandr  I also met  this question. Have you solve this problem? Or, if using  hdf5-based weight saving function, are there some examples about saving weight  and utilizing these weights to construct network. Many thanks.
'''python
cPickle.dump(model,open(r"Model\model_cnn.pkl","wb"))

Traceback (most recent call last):
  File "D:\workspace\search\src\CNN\text_classification_test.py", line 258, in <module>
    cPickle.dump(model,open(r"Model\model_cnn.pkl","wb"))
  File "D:\Python27\lib\copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle function objects
'''

**Comment by fchollet** [comment]
@Imorton-zd you can simply do:

```python
model.save_weights("tmp.h5")
json_data = model.to_json()
# later
from keras.models import model_from_json
model = model_from_json(json_data)
model.load_weights("tmp.h5")
```

**Comment by Imorton-zd** [comment]
@fchollet  I didn't find 'to_json' in models.py, neither 'model_from_json'
Traceback (most recent call last):
  File "D:\workspace\search\src\CNN\lstm_two.py", line 180, in <module>
    json_data = model.to_json()
AttributeError: 'Sequential' object has no attribute 'to_json'

**Comment by Imorton-zd** [comment]
@fchollet  I have updated the keras, and found 'to_json' and 'from_json', but these two segments codes must be in one file. If I only want to save the weights in a file using the first segment code, and in another file, loaded the weights using second segment code, how do I save the 'json_data'? It's just a variable

**Comment by lukedeo** [comment]
Uh, @Imorton-zd it's just a string... save it any way you normally save a string.

**Comment by Codeguyross** [comment]
@fchollet 
`model.save_weights("tmp.h5")
json_data = model.to_json()
# later
from keras.models import model_from_json
model = model_from_json(json_data)
model.load_weights("tmp.h5")`

Doesnt work anymore
