### ISSUE TITLE
Breaking Change from 0.3.x to 1.0.x, predict_on_batch returns single scalar

### ISSUE THREAD

**Issue by RaffEdwardBAH** [fchollet/keras#2580]
The `predict_on_batch` method appers to be broken in 1.0.X (tested with head revision as well). 

If I load a graph defined model (a multi-layered LSTM) and attempt 

`preds_batch =  model.predict_on_batch({'input' : X_batch, 'output': y_batch})`

I get an output like `{u'output': array([ 0.97785485], dtype=float32)}` , even though the batch has 128 items in it. 

The `predict` method appears to have the same issue.

**Comment by braingineer** [comment]
Can you try:
```python
model._make_predict_function()
outputs = model.prediction_function()
```
If outputs is the correct shape/size, then it's this line: https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1220 and somehow the shape is probably (1,N) or something. 

If it's still messed up there, then we've ruled out something at least =D

**Comment by RaffEdwardBAH** [comment]
I'm not sure where you want me to call those. I just copied them after the `predict_on_batch` call exactly as you have them listed, and I get an error on the `outputs` line 

```
'Graph' object has no attribute 'prediction_function'
```

**Comment by braingineer** [comment]
see updated, sorry. typed from memory and I was wrong =(

**Comment by RaffEdwardBAH** [comment]
What are the types of `data`, `model.input_names`, and `model.internal_input_shapes` ? What do they need?

**Comment by RaffEdwardBAH** [comment]
I found the method in keras.engine.training and the `outputs` has the correct shape / looks like it should be the correct output

**Comment by braingineer** [comment]
Found the issue =).

```
    def predict_on_batch(self, data):
        output_list = super(Graph, self).predict_on_batch(data)
        return dict(zip(self._graph_outputs, output_list))
```

Graph is ALSO expecting a 1-length output.. 

You can change it to this for now and it should (hopefully) work:

```python
    def predict_on_batch(self, data):
        output_list = super(Graph, self).predict_on_batch(data)
        if not isinstance(output_list, list):
            output_list = list
        return dict(zip(self._graph_outputs, output_list))
```

I can probably write up a PR later. (unless you want to do it =)).

**Comment by fchollet** [comment]
Cool, please submit a PR when you can.

**Comment by RaffEdwardBAH** [comment]
This is code done at work so I can't do a PR.

**Comment by braingineer** [comment]
I'll write it up quick
