### ISSUE TITLE
Fully Convolutional Network input problem

### ISSUE THREAD

**Issue by MartijnL** [fchollet/keras#2587]
Hi,

I think I have a problem with a simple solution, however I cannot find it.

I have the following fully convolutional network, which worked before I updated to the new Keras*

```
    # A network named 'model' is initialized before calling this network.
    model2 = Sequential()

    model2.add(Convolution2D(64, 3, 3, weights=model.layers[1].get_weights(), 
                             input_shape=(img_channels, None, None))) #img_channels=1
    model2.add(Activation('relu'))
    model2.add(MaxPooling2D((2,2), strides=(2,2)))

    model2.add(Convolution2D(128, 3, 3, weights=model.layers[4].get_weights()))
    model2.add(Activation('relu'))
    model2.add(MaxPooling2D((2,2), strides=(2,2)))

    model2.add(Convolution2D(256, 3, 3, weights=model.layers[7].get_weights()))
    model2.add(Activation('relu'))
    model2.add(MaxPooling2D((2,2), strides=(2,2)))

    model2.add(Convolution2D(4096, 6, 6, activation='relu'))
    model2.add(Dropout(0.5))
    model2.add(Convolution2D(4096, 1, 1, activation='relu'))
    model2.add(Dropout(0.5))
    model2.add(Convolution2D(7, 1, 1))
    model2.add(Flatten())
    model2.add(Activation('sigmoid'))

    sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
    model2.compile(optimizer=sgd, loss='categorical_crossentropy')
```

Because the input shape contains None, None, I could use any size images as input. However, now after the update, I get the following error when trying to train with this network:

`Exception: The shape of the input to "Flatten" is not fully defined (got (7, None, None). Make sure to pass a complete "input_shape" or "batch_input_shape" argument to the first layer in your model.
`

What do I have to change in order to make it work again?

\* EDIT: By reverting back to an older version I found out this is not a problem with Keras 1.x, but rather with upgrading from 0.3.2 tot 0.3.3.

**Comment by joelthchao** [comment]
Once you have a `flatten` layer in your model, you have to specify `input_shape`, not sure why your model is able to run in the old version. Can you describe your task with more details?

**Comment by MartijnL** [comment]
Yes, so I have data on which I want to perform image segmentation. Datafiles are in grayscale, so only have 1 channel. However, the datafiles are really big, I have images of roughly 20.000 by 4000 pixels per image. 
The first thing I did was to create a normal convolutional neural network, shown below:

```
    img_rows, img_cols = 64, 64
    img_channels = 1
    nb_classes = 7

    model = Sequential()
    
    model.add(ZeroPadding2D((1,1),input_shape=(img_channels, img_rows, img_cols)))
    model.add(Convolution2D(64, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))
    
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(128, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))
    
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(256, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))
    
    model.add(Flatten())
    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(4096, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes, activation='softmax'))
    
    sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
    model.compile(optimizer=sgd, loss='categorical_crossentropy', metrics=["accuracy"])
```
I cut my data into pieces of 64 by 64 and trained the CNN on this. Then for testing, I cut one image of 20.000x4000 into pieces of 64x64 and fed them to the CNN so for every piece I got a classification.

After this I tried a fully convolutional network. The network from the first post (model2) is the fully convolutional version of 'model'. I trained 'model2' on pieces of 64x64 again. Then I cut a big image into pieces of 1024x1024 and fed this to the FCN. The good thing from this method was that the image cannot be cut into pieces of 1024x1024 exactly, so the residual parts, which were smaller, could also be used as input without any problems.
I am trying to follow the methods that were used in this [paper](http://arxiv.org/pdf/1412.7062v3.pdf), where there is a classification for every pixel of the image, whereupon a Fully Connected CRF is applied.

I was under the impression that by setting the input layer as None, the network could take any size image as input (because this worked previously).

The results I got were actually really good, so I hope I do not have to rewrite everything.

Thanks in advance for your help!

**Comment by joelthchao** [comment]
Sorry, I don't know how to deal with variant input size. Why not fix your input to `(1, 1024, 1024)` to train the FCN? You can still use the pretrained filters on this network. During testing you can crop input images into pieces and aggregate them to produce the final result.

**Comment by MartijnL** [comment]
The annoying thing is that everything already worked and I actually already got results back, only needed to apply it to some more data. Now I have to rewrite it again.

Obviously not your fault, so thank you for your answer. 
Hopefully someone else reads this and can help me with information on variant input size.

**Comment by jwgu** [comment]
@MartijnL : did you find a solution for this? I have the same question. Thanks.

**Comment by MartijnL** [comment]
No actually. I reverted back to version 0.3.2 and then it works again. I don't know how to fix it for newer versions than that.

**Comment by ChihebTrabelsi** [comment]
I have exactly the same problem using Flatten() as the time steps of the input signal are varying (different instances in the batch have different time steps but the signal length is fixed as it is the same for all the instances. Each instance has a dim = (timesteps, signal_length) where timesteps is None and signal length is fixed). I had to fix the number of time steps by adding sequences of zeros to shorter sequences. This solution seems to be inconvenient as I want to deal with inputs having varying time steps. Is there any way to deal with that?

**Comment by MartinThoma** [comment]
I ran into a similar issue: I want to train a CNN on a classification task and then run it for semantic segmentation. Hence I have a model like

```
def create_model(nb_classes):
    model = Sequential()
    model.add(Convolution2D(32, 3, 3, border_mode='same', activation='relu',
                            input_shape=(None, None, 3)))  # At training time, this is 32x32 images with 3 channels
    model.add(Convolution2D(32, 3, 3, border_mode='same', activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    # model.add(Dropout(0.25))

    model.add(Convolution2D(64, 3, 3, border_mode='same', activation='relu'))
    model.add(Convolution2D(64, 3, 3, border_mode='same', activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    # model.add(Dropout(0.25))

    model.add(Convolution2D(2048, 8, 8,
                            border_mode='valid', activation='relu'))
    model.add(Dropout(0.5))
    model.add(Convolution2D(2048, 1, 1, border_mode='same', activation='relu'))
    model.add(Dropout(0.5))
    model.add(Convolution2D(nb_classes, 1, 1, border_mode='same'))
    model.add(Flatten(input_shape=(None, 1, 1, nb_classes)))  # I know at training time, that this layer will get Batch Size x 1 x 1 x nb_classes
    model.add(Activation('softmax'))
    return model
```

After the training, I want to remove the Flatten / softmax to make this a Fully Convolutional Network (FCN):

```
model = load_model("trained-net.h5")
# Get input
new_input = model.input
new_input.input_shape = (1, None, None, 3)
# Get rid of the flatten
hidden_layer = model.layers[-1].output
# Build a new model
model2 = Model(new_input, hidden_layer)
```

However, this does not work because it seems not to be possible to overwrite the input_shape / shape:

```
ValueError: Error when checking : expected convolution2d_input_1 to have shape (None, 32, 32, 3) but got array with shape (1, 800, 1360, 3)
```

**Comment by MartinThoma** [comment]
By the way, why is softmax not working for Convolutional layers? It seems to me that is a reasonable implementation:

```
def softmax(x):
    ndim = K.ndim(x)
    if ndim == 2:
        return K.softmax(x)
    elif ndim == 3:
        e = K.exp(x - K.max(x, axis=-1, keepdims=True))
        s = K.sum(e, axis=-1, keepdims=True)
        return e / s
    elif ndim == 4:
        channel_dim = -1  # for Tensorflow - for Theano it is 1, I think
        e = K.exp(x - K.max(x, axis=channel_dim, keepdims=True))
        s = K.sum(e, axis=channel_dim, keepdims=True)
        return e / s
    else:
        raise ValueError('Cannot apply softmax to a tensor '
                         'that is not 2D or 3D. '
                         'Here, ndim=' + str(ndim))
```
