### ISSUE TITLE
Accessing the internal states c of LSTM for all the time steps of each input sequence

### ISSUE THREAD

**Issue by yil8** [fchollet/keras#2593]
Hi all,

I'm wondering if there are any easy ways to access the internal states of LSTM, i.e. the c, for all the time steps of each input sequence? I can get the h by setting return_sequences=True, and I know h = o \* self.activation(c). But I can not figure out an easy way to access the c.

Thanks!

**Comment by carlthome** [comment]
You could probably access `self.states` from a LSTM layer to get c:s. Check the source for inspiration: https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py

**Comment by yil8** [comment]
But you have to use stateful=True, which will change the trainng scheme, otherwise the self.states would be None, right?

**Comment by braingineer** [comment]
No.  There is no easy way.  The states are lost after the computation and only the last step is kept. 

I have an implementation which does maintain all steps, but computation is hard and annoying. I won't be releasing it until after I submit it for publication this Sunday, though....
