### ISSUE TITLE
Is statefulness in RNNs doing anything?

### ISSUE THREAD

**Issue by carlthome** [fchollet/keras#2599]
Is `stateful=True` in a RNN layer really doing anything at all?

The initial states upon each call of a RNN layer are set [here](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L215) but `self.states` never seems to be updated to anything meaningful anywhere. States are just appended to [a list] (https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L231) but then never seem to be used again. What am I missing?

**Comment by carlthome** [comment]
Nevermind, it's working. `self.updates` is used by the backend and is not just a list.

**Comment by braingineer** [comment]
Is there documentation for the internal guts of `training.py` and `topology.py`?   I bruted my way through understanding the node stuff, but I still don't completely get it and tracing it can be a bit overwhelming.

**Comment by carlthome** [comment]
This explains a little of it: http://keras.io/layers/writing-your-own-keras-layers/

**Comment by braingineer** [comment]
Lol. I just spent a couple hours crawling both Theano's and Keras's computation graphs.  that's like navigating a rain forest using a globe. 

(i see you've crossed it out, though)

**Comment by carlthome** [comment]
Yup :smile:

**Comment by philipperemy** [comment]
Yes it does : http://philipperemy.github.io/keras-stateful-lstm/
