### ISSUE TITLE
How to save and load model?

### ISSUE THREAD

**Issue by gpernelle** [fchollet/keras#26]
Hello,
Thank you for this module, it looks awesome.
I am using the cifar10_cnn example. Is there any efficient way to save and load the trained network?

I tried to use cPickle on model but I hit the "Maximum recursion depth" error...

**Comment by gpernelle** [comment]
Nevermind, I used  sys.setrecursionlimit(40000) and it works fine now.

**Comment by fchollet** [comment]
So far I've been using cPickle to save/load models, but I'm looking into writing a fast & compact save/load function based on HDF5. Not very high on the priority list though...
