### ISSUE TITLE
Use of travis-ci for continuous integration

### ISSUE THREAD

**Issue by tleeuwenburg** [fchollet/keras#260]
See https://travis-ci.org/tleeuwenburg/keras

Extending on from the work on the test refactor, I have created a configuration file for 'travis ci'. Think of it as free Jenkins for open source projects. It requires adding a .travis.yml file to the repository, then for Francois to go set up the account at travis-ci. I have proven it works by setting Travis up to look at my fork, so I can do a merge request if this is seen as beneficial.

This is useful to the package maintainers as they can see as soon as anyone breaks the build, plus it is also a statement to the public of greater reliability. 

In order to make it really mean something, more work will need to be done on the test coverage, this is just mechanics.

**Comment by phreeza** [comment]
I think this would be a really great addition. Just out of curiosity, does Travis also enable continuous monitoring of performance? Ie to see how changes affect the runtimes of tests?

**Comment by tleeuwenburg** [comment]
Hi Thomas,

Great idea.

Travis doesn't include that by default. I am trying to work out how to get
travis to create test reports, such as coverage information. What you
suggest is definitely a plausible thing, but I am not sure if it's possible
in that environment.

I'll look into it.

Regards,
-Tennessee





On 22 June 2015 at 17:44, Thomas McColgan <notifications@github.com> wrote:

> I think this would be a really great addition. Just out of curiosity, does
> Travis also enable continuous monitoring of performance? Ie to see how
> changes affect the runtimes of tests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/260#issuecomment-114029624>.
>



-- 
--------------------------------------------------
Tennessee Leeuwenburg
http://myownhat.blogspot.com/
"Don't believe everything you think"

**Comment by tleeuwenburg** [comment]
Hi Thomas,

I've spent some time Googling. Short version: I'm happy to help develop
some timing tests, but travis isn't going to help with performance
monitoring. It's entirely possible to use the automated testing tools to
run performance and timing tests.

There are a variety of tools which will integrate with travis to provide
reporting on test compliance and coverage (code climate, coveralls.io,
probably others) but none which offer reporting on performance.

The only project I know of that routinely reports performance stats is
http://speed.pypy.org/. This tracks the performance of pypy, across a
number of performance tests, normalised to the CPython 2.7 performance.
This is a specific web app developed by the pypy team. I've run a copy at
work before for internal use. Setting up a public site for Keras is doable
but the effort involved is probably a lower priority for me at the moment.

It is entirely possible to use the test infrastructure to conduct
performance tests and print out the reported values, or log them to a file.
It's not obvious that travis has a way of displaying or rendering the
performance outputs.

Performance monitoring is also challenging due to the need to hold the
machine specs constant. Travis is hosted in an environment where the
available CPU, memory etc would most likely be varying often. It would be
better to use some kind of VM configuration The pypy folk, last I checked,
have a specific physical machine on which the tests are run, and nothing
else is run on that machine at the time. The results from the speed tests
are then uploaded into a database and presented through the web interface
seen at speed.pypy.org.

For Keras, a huge factor will of course be the choice of CPU and/or GPU
used. It would be useful to have tests run on a variety of hardware.

The simplest thing is probably to develop timing tests which are not run by
default, but which can be easily run using the test framework. It would be
simplest to simply report on those manually, perhaps within the Readme.Md
file. It would be quite reasonable to take some 'classic' examples like
MNIST digit recognition and run timing on it. It would also be possible to
do this compared to other packages to provide some comparisons.

I'm not sure to what extent Keras development concentrates on speed
optimization. To a large degree, I assume that comes from the performance
of Theano, but there will presumably be parts of Keras which could be
faster.

I'd suggest in the first instance setting up the testing from a
coverage/compliance/accuracy perspective is the appropriate first step, but
I'm more than happy to set up some timing tests and report back to the
group. I would actually go about this in a separate repository while
building up the tests. It would be very interesting to do. Let me know if
anyone wants to help with that! :)

Cheers,
-Tennessee




On 22 June 2015 at 17:44, Thomas McColgan <notifications@github.com> wrote:

> I think this would be a really great addition. Just out of curiosity, does
> Travis also enable continuous monitoring of performance? Ie to see how
> changes affect the runtimes of tests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/260#issuecomment-114029624>.
>



-- 
--------------------------------------------------
Tennessee Leeuwenburg
http://myownhat.blogspot.com/
"Don't believe everything you think"

**Comment by phreeza** [comment]
Thanks for your elaborate answer, Tennessee!

What I was thinking about is more of a performance test to make sure one does not accidentally introduce a huge computational overhead in a change to the code, not so much the exact profiling of the runtimes.

Maybe this could be achieved by simply building a couple of tests that measure their own runtime and fail if a certain threshold is exceeded, with the threshold being determined by some kind of 'reasonable' runtime based on the observed times in Travis...

Anyway, I think this can be addressed later, getting unit tests with decent coverage running is much more important.

**Comment by phreeza** [comment]
On a related note, I would suggest adding continuous monitoring of test coverage via [coveralls.io](https://coveralls.io/) while we are at it.

**Comment by fchollet** [comment]
Travis would be a great addition! But our focus for now should be on buffing up our suite of unit tests. The usefulness of continuous integration is limited without much tests to run...
