### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by JinmingZhao** [fchollet/keras#2604]
when I run the imdb_lstm.py, and there is error info:
Using Theano backend.
Loading data...
Traceback (most recent call last):
  File "imdb_lstm.py", line 53, in <module>
    test_split=0.2)
  File "/Library/Python/2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/datasets/imdb.py", line 20, in load_data
    X, labels = cPickle.load(f)
EOFError

Need I add the try expect ?

**Comment by ylqfp** [comment]
I think it's a dataset read error problem, I've not met this before.
I suggest:
1. redownload imdb dataset;
2. You can also download imdb dataset by yourself, and fed to program LOCALLY.

**Comment by JinmingZhao** [comment]
thanks a lot， redownload is ok
