### ISSUE TITLE
A labview GUI application

### ISSUE THREAD

**Issue by justdark** [fchollet/keras#2606]
Hi，I recently found the Tensorflow have a graph visualization called [TensorBoard](https://www.tensorflow.org/tensorboard/index.html#graphs) 
It's really cool and I think the Keras should have some thing like a Labview, 
I mean you can drag and drop a layer into the canvas, connect each other to organise the model Sequence.configure the layer's params in a form.
finally the graph can be export to some python code.

And then what the user need to do is just prepare the data and pass it in the model we just create.
so every user can be a deep learning "expert" :)
Maybe we can gather some people to make it happen.the deep learning will become really really easy for a newbie if he can use this.

**Comment by marcj** [comment]
This model builder for keras is what http://aetros.com/trainer is trying to do. It will probably for free for researcher and individuals, so if you write me your mail (to marc.schmidt@aetros.com) I can add you to the already closed beta registration so you can play with it soon.

**Comment by braingineer** [comment]
Hi @marcj .  How inviting is that invitation? =)

**Comment by marcj** [comment]
@braingineer pretty inviting :P Feel free to mail me also, although we already exceeded our capacity. :) Hopefully not everyone is using the app in day 1, because we have probably not enough GPUs for more people when everyone is trying the free GPU training. Guess I need to buy some extra GPUs 😄

**Comment by marcj** [comment]
Alright guys, since already over a dozen people wrote me via email, we've reopened the registration form as its easier for us to track the invitation (email is not so appropriate to handle such stuff :) ).

We're making sure you get enough resources! Feel free to register http://aetros.com/contact

**Comment by justdark** [comment]
Good job ~~

**Comment by braingineer** [comment]
Awesome!  Thanks, @marcj

**Comment by justdark** [comment]
<img width="351" alt="untitled-1" src="https://cloud.githubusercontent.com/assets/2044835/15017584/af6106d8-1248-11e6-9d15-bec7b2b81dd2.png">
@marcj 's project is really a big one.
I make a simple demo like this,just do the code generator's job.
Drag the layer from left to the middle part, connect each other by draging the small blue rect to red,the params for the layer will placed on the right.
When we have this graph,it's easy to generate the python code when we have all the info.
I'll make it usable if I can make time.

**Comment by marcj** [comment]
@justdark yeah, the current model designer is actually almost like this. See the video:

https://www.youtube.com/watch?v=_oTZVSyPW44
![DNN designer](https://cloud.githubusercontent.com/assets/450980/16876124/05d76dc6-4aa3-11e6-9ddd-6c13358415ba.png)

**Comment by marcj** [comment]
Heads up, http://aetros.com/trainer is now available for everyone for free. Basically the missing GUI for Keras (model designer, monitoring, prediction servers, etc)

**Comment by Wojtas77** [comment]
Great project.
