### ISSUE TITLE
Issue when connecting two models

### ISSUE THREAD

**Issue by jfsantos** [fchollet/keras#2609]
I am working with a GAN-like model where I have a generator and a discriminator. Each of the models is a `Model` (using the new functional API). Both models work individually, but when I try to connect them, I get a `MissingInputError` telling me that an input to the graph is missing. That happens to be the input to the discriminator, which is the second model in the processing chain. I tried connecting the models both by using a `Sequential` object and by creating a new `Model` like this:

```
inputs = Input(shape=generator_input_shape)
generated = generator(input)
output = discriminator(generated)
discriminator_on_generator = Model(input=inputs, output=output)
```

Calling `discriminator_on_generator.predict(batch)` works properly, but `discriminator_on_generator.train_on_batch(batch, targets)` does not.

This was with the Theano backend (I cannot test the Tensorflow backend right now as I'm on a Windows machine).

Any ideas on what could be wrong?

**Comment by jfsantos** [comment]
I found some [code](https://github.com/jacobgil/keras-dcgan) that used to work on Keras 0.3.3 that is similar to what I'm doing and also does not work on Keras >= 1.0. This code uses `Sequential` to wrap and connect the different models.

@fchollet: is this expected? Am I missing something?

**Comment by fchollet** [comment]
Not enough information here... what's your model and what's your error message?

**Comment by jfsantos** [comment]
`generator` is your usual stack of LSTMs (without any dropout between them). `discriminator` is a CNN with batchnorm and leaky ReLUs, like on DCGAN. The code I linked has exactly the same issue on Keras >= 1.0 (but they use CNNs for both the [generator](https://github.com/jacobgil/keras-dcgan/blob/master/dcgan.py#L18) and [discriminator](https://github.com/jacobgil/keras-dcgan/blob/master/dcgan.py#L41)). The error message for the linked code is the following:

```
theano.gof.fg.MissingInputError: ("An input of the graph, used to compute Abstra
ctConv2d{border_mode='half', subsample=(2, 2), filter_flip=True, imshp=(None, No
ne, None, None), kshp=(128, 3, 5, 5)}(convolution2d_input_1, HostFromGpu.0), was
 not provided and not given a value.Use the Theano flag exception_verbosity='hig
h',for more information on this error.", convolution2d_input_1)
```

This is the first convolution from the discriminator, which means that somehow the output of the generator is not interpreted as the input of the discriminator. I had the same error when I converted the model to the functional API (as described above).

**Comment by jfsantos** [comment]
I tried a few more things to see what could be going on and tested having different types of layers in the generator and discriminator. I narrowed the problem down to having a convolutional layer as the first layer of the discriminator, which is the second model in the processing chain. Adding a `Reshape` layer before it does not help and moves the error message to the `Reshape` node.

**Comment by jfsantos** [comment]
I have been working on this for long and wasn't able to find a solution yet. Any clues or directions on what I should investigate, @fchollet? I linked some code above, and the only change you have to make to get it to run (and crash) on Keras 1.0 is to line 23 of dcgan.py (remove `dim=` from the instantiation of the `Reshape` layer). 

Here is the full traceback:

```
Traceback (most recent call last):
  File "dcgan.py", line 154, in <module>
    train(path = args.path, BATCH_SIZE = args.batch_size)
  File "dcgan.py", line 118, in train
    g_loss = discriminator_on_generator.train_on_batch(noise, [1] * BATCH_SIZE)
  File "c:\users\santosj\src\keras\keras\models.py", line 493, in train_on_batch
    class_weight=class_weight)
  File "c:\users\santosj\src\keras\keras\engine\training.py", line 1165, in train_on_batch
    self._make_train_function()
  File "c:\users\santosj\src\keras\keras\engine\training.py", line 670, in _make_train_function
    **self._function_kwargs)
  File "c:\users\santosj\src\keras\keras\backend\theano_backend.py", line 518, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "c:\users\santosj\src\keras\keras\backend\theano_backend.py", line 504, in __init__
    **kwargs)
  File "c:\users\santosj\src\theano\theano\compile\function.py", line 322, in function
    output_keys=output_keys)
  File "c:\users\santosj\src\theano\theano\compile\pfunc.py", line 480, in pfunc
    output_keys=output_keys)
  File "c:\users\santosj\src\theano\theano\compile\function_module.py", line 1823, in orig_function
    output_keys=output_keys).create(
  File "c:\users\santosj\src\theano\theano\compile\function_module.py", line 1475, in __init__
    accept_inplace)
  File "c:\users\santosj\src\theano\theano\compile\function_module.py", line 177, in std_fgraph
    update_mapping=update_mapping)
  File "c:\users\santosj\src\theano\theano\gof\fg.py", line 182, in __init__
    self.__import_r__(output, reason="init")
  File "c:\users\santosj\src\theano\theano\gof\fg.py", line 371, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "c:\users\santosj\src\theano\theano\gof\fg.py", line 413, in __import__
    variable=r)
theano.gof.fg.MissingInputError: An input of the graph, used to compute AbstractConv2d{border_mode='half', subsample=(2, 2), filter_flip=True, imshp=(None, None, None, None), kshp=(128, 3, 5, 5)}(convolution2d_input_1, HostFromGpu.0), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.

Backtrace when the variable is created:
  File "dcgan.py", line 154, in <module>
    train(path = args.path, BATCH_SIZE = args.batch_size)
  File "dcgan.py", line 82, in train
    discriminator = discriminator_model()
  File "dcgan.py", line 43, in discriminator_model
    model.add(Convolution2D(128, 5, 5, subsample=(2, 2), input_shape=(3, 64, 64), border_mode = 'same'))
  File "c:\users\santosj\src\keras\keras\models.py", line 110, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "c:\users\santosj\src\keras\keras\engine\topology.py", line 337, in create_input_layer
    dtype=input_dtype, name=name)
  File "c:\users\santosj\src\keras\keras\engine\topology.py", line 1026, in Input
    name=name, input_dtype=dtype)
  File "c:\users\santosj\src\keras\keras\engine\topology.py", line 952, in __init__
    name=self.name)
  File "c:\users\santosj\src\keras\keras\backend\theano_backend.py", line 42, in placeholder
    x = T.TensorType(dtype, broadcast)(name)
```

**Comment by jfsantos** [comment]
I made a [minimal reproducing example](https://gist.github.com/jfsantos/e1ff730415b9b8b4c6e83cb161046850) and the problem is actually with `BatchNormalization`. If you comment out line 30, taking the `BatchNormalization` layer out of model B, then it works properly.

**Comment by fchollet** [comment]
I understand the bug, although I don't have an immediate fix.

In the `call` method of `BatchNormalization`, we are defining updates based on the input `x`. When you reconnect the model to a different input, the inner updates of the BN layer are still referring to the original input, which is no longer available during training.

Unclear how this could be fixed.

**Comment by fchollet** [comment]
Actually I know how to fix it in your case. Just call `layer.call(prev_layer.output)` after reconnecting the models, where `layer` is the BN layer instance and `prev_layer` is the layer right before BN. This will overwrite the updates of the BN layer.

**Comment by jfsantos** [comment]
Thanks a lot for your suggestion! I will test this tomorrow.

Now I understand what is happening, but can't think on any fix that's not overly complicated (such as having a method to verify and "reconnect" missing inputs based on the current graph structure).

**Comment by jfsantos** [comment]
Apparently `Reshape` has a similar issue, but the proposed workaround does not work. In the [minimal example](https://gist.github.com/jfsantos/e1ff730415b9b8b4c6e83cb161046850), `Reshape` is the first layer of the second model, so I suppose it should be connected to the output of the previous model, but doing modelB.layers[0].call(modelA.layers[-1].output) did not work.

**Comment by jfsantos** [comment]
The proposed fix did not work. Funny thing is that when `BatchNormalization` is added, the error happens at the `Reshape` layer, not the `BatchNormalization` layer. I could not figure out why that is the case.

**Comment by jennsleeman** [comment]
Any further progress on this issue?  I am running into the same problem.

**Comment by jaekyeom** [comment]
Is there any progress on this?
