### ISSUE TITLE
Convolution1D inconsistent with Convolution2D

### ISSUE THREAD

**Issue by ricoj** [fchollet/keras#2610]
Convolution1D behaves differently from Convolution2D, e.g. the output shape are inconsistent. Shouldn't these two layers be equivalent for the following example?

```
from keras.models import Sequential
from keras.layers import Convolution1D, Convolution2D

model = Sequential()
model.add(Convolution2D(32, 1, 3, input_shape=(1, 1, 128)))
print(model.output_shape)  # -> (None, 32, 1, 126)

model = Sequential()
model.add(Convolution1D(32, 3, input_shape=(1, 128)))
print(model.output_shape)  # -> (None, -1, 32) instead of (None, 32, 126), which I would expect
```

Is this a bug or is there a reason for this that I don't understand?

**Comment by NasenSpray** [comment]
Convolution1D(32, 3, input_shape=(128, 1)) # -> (None, 126, 32)

**Comment by ricoj** [comment]
Ah, okay so it is like Convolution2D with the non-default dim_ordering ('tf' instead of 'th'). Maybe it would make sense to also have a dim_ordering argument for Convolution1D and have their default behaviors consistent .. 

Anyways, thank you very much for your quick and helpful response!!!

**Comment by NasenSpray** [comment]
Convolution1D is consistent with the recurrent and time-distributed layers

**Comment by ricoj** [comment]
I see. Thanks again.
