### ISSUE TITLE
Passing incorrect parameter names to RMSprop (and other optimizers) silently does nothing

### ISSUE THREAD

**Issue by iskandr** [fchollet/keras#2616]
I just spent a while trying to hunt down a bug that turned out to be caused by passing `learning_rate` instead of `lr` to `RMSprop`. I'm not familiar enough with the internals of Keras to tell whether there's good reason for allowing any user specified arguments to pass through. It would, however, be nice to get an error message on invalid parameter names.

**Comment by fchollet** [comment]
I fixed this earlier today.
