### ISSUE TITLE
Why nested shared layers as such network doesn't work?

### ISSUE THREAD

**Issue by ylqfp** [fchollet/keras#2619]
Hi,
I design a network which composes of shared layers, I write code using functional API. However, there always be errors.  
I paste my network structure graph , code , and error information below, hope to provide a clue.
Thanks!

Network Structure:

![network structure jpeg](https://raw.githubusercontent.com/ylqfp/attachments/bb396650622b37b2a311d29864795aec67301042/cnn2_2_lstm.jpg)
Share layers:
1. Embedding is shared among 3 input.(blue color). However, input_length is different for input1/input2 and input3. The input_length for input1/input2 is LSTM_MAXLEN, 1000, for input3 is QUERY_MAXLEN, 5, eg. max 5 words for a query.
2. CNN feature learning layer is shared between input1 and input2. (green color)

**Comment by ylqfp** [comment]
`
RNN=recurrent.LSTM
EMBED_HIDDEN_SIZE=50
SENT_HIDDEN_SIZE=100
COMM_HIDDEN_SIZE=100
QUERY_HIDDEN_SIZE=100
BATCH_SIZE=32
EPOCHS=6
QUERY_MAXLEN=5

STEP=6

RUN=1

vocab = 149999

vocab_size=vocab+1

print "build model..."

nb_filter=128
filter_length=3
pool_length=2

def max_1d(X):
	return K.max(X, axis=1)

#embedding_layer = Embedding(vocab_size, EMBED_HIDDEN_SIZE, mask_zero=False)()
sentence_input = Input(shape=(LSTM_maxlen,))
query_input = Input(shape=(QUERY_MAXLEN,))

x = Embedding(vocab_size, EMBED_HIDDEN_SIZE, mask_zero=False)(sentence_input)
x = Dropout(0.2)(x)
x = Convolution1D(nb_filter=nb_filter,
								filter_length = filter_length,
								border_mode='valid',
								activation='relu',
								subsample_length=1)(x)
x = MaxPooling1D(pool_length=pool_length)(x)
x = Convolution1D(nb_filter=nb_filter,
								filter_length = filter_length,
								border_mode='valid',
								activation='relu',
								subsample_length=1)(x)
x = Lambda(max_1d, output_shape=(nb_filter, ))(x)
x = Dense(SENT_HIDDEN_SIZE, activation='relu')(x)
outx = Dropout(0.2)(x)
cnn_share = Model(sentence_input, outx)

a = Input(shape=(LSTM_maxlen, ))
b = Input(shape=(LSTM_maxlen, ))
c = Input(shape=(QUERY_MAXLEN, ))

shared_cnn1 = cnn_share(a)
shared_cnn2 = cnn_share(b)

y = Input(shape=(QUERY_MAXLEN,))
y = Embedding(vocab_size, EMBED_HIDDEN_SIZE, mask_zero=True)(y)
y = RNN(QUERY_HIDDEN_SIZE, return_sequences=False, activation='relu')(y)
y = Dropout(y)

model_query = Model(query_input, y)

qrnn = model_query(c)

merge_vector = Merge([shared_cnn1, shared_cnn2, qrnn], mode='concat', concat_axis=-1)
dense1 = Dense(100, activation='relu')(merge_vector)
dp1 = Dropout(0.2)(dense1)
output1 = Dense(1, activation='sigmoid')(dp1)

model = Model(input=[shared_cnn1, shared_cnn2, qrnn], output=output1)

model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

if RUN:
	model3.fit([X, Xc, Xq],Y, batch_size=BATCH_SIZE, nb_epoch = EPOCHS,validation_split=0.05, show_accuracy=True )
`

**Comment by ylqfp** [comment]
Share layers:
1. Embedding is shared among 3 input.
2. CNN feature learning layer is shared between input1 and input2.

**Comment by ylqfp** [comment]
run ERROR:
Traceback (most recent call last):
  File "shared_cnn_1.py", line 105, in <module>
    x = Embedding(vocab_size, EMBED_HIDDEN_SIZE, mask_zero=False)(sentence_input)
  File "/home/yulei/.local/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/yulei/.local/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/yulei/.local/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/yulei/.local/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/layers/embeddings.py", line 133, in call
    out = K.gather(W, x)
  File "/home/yulei/.local/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/backend/theano_backend.py", line 156, in gather
    return reference[indices]
  File "/home/yulei/.local/lib/python2.7/site-packages/Theano-0.8.1-py2.7.egg/theano/tensor/var.py", line 503, in __getitem__
    return self.take(args[axis], axis)
  File "/home/yulei/.local/lib/python2.7/site-packages/Theano-0.8.1-py2.7.egg/theano/tensor/var.py", line 535, in take
    return theano.tensor.subtensor.take(self, indices, axis, mode)
  File "/home/yulei/.local/lib/python2.7/site-packages/Theano-0.8.1-py2.7.egg/theano/tensor/subtensor.py", line 2387, in take
    return take(a, indices.flatten(), axis, mode).reshape(shape, ndim)
  File "/home/yulei/.local/lib/python2.7/site-packages/Theano-0.8.1-py2.7.egg/theano/tensor/subtensor.py", line 2365, in take
    return advanced_subtensor1(a, indices)
  File "/home/yulei/.local/lib/python2.7/site-packages/Theano-0.8.1-py2.7.egg/theano/gof/op.py", line 611, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/yulei/.local/lib/python2.7/site-packages/Theano-0.8.1-py2.7.egg/theano/tensor/subtensor.py", line 1687, in make_node
    raise TypeError('index must be integers')
TypeError: index must be integers

**Comment by braingineer** [comment]
Input should be an int type.  you can specify in the constructor.  

```python
X = Input(shape=shape, dtype='int32')
```

**Comment by ylqfp** [comment]
It seems that the it's not the type problem.
I'm writing a non-shared version first, hoping to get everything correct.
And then shared version.

**Comment by braingineer** [comment]
Are you getting the same error or a different one? because it looks like the "index must be integers" error that I usually get when I forgot to cast my inputs as ints.

**Comment by ylqfp** [comment]
Same error.
I found some other mistakes in my code, after I modified them, and make sure non-shared version to be OK, and currently the shared version is OK.
However, the model is not completely shared, case the word embedding is not shared between input3 and input1/2.
I'll report after complete share.

**Comment by ylqfp** [comment]
Hi, all,
There comes the error information, I'm wondering if the shared layers can be nested.

Traceback (most recent call last):
  File "shared_cnn_4.py", line 130, in <module>
    model.fit([X, Xc, Xq],Y, batch_size=BATCH_SIZE, nb_epoch = EPOCHS,validation_split=0.05)
  File "/home/yulei/.local/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/training.py", line 1015, in fit
    self._make_train_function()
  File "/home/yulei/.local/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/engine/training.py", line 653, in _make_train_function
    **self._function_kwargs)
  File "/home/yulei/.local/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/backend/theano_backend.py", line 503, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/yulei/.local/lib/python2.7/site-packages/Keras-1.0.1-py2.7.egg/keras/backend/theano_backend.py", line 489, in __init__
    **kwargs)
  File "/home/yulei/.local/lib/python2.7/site-packages/Theano-0.8.1-py2.7.egg/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/yulei/.local/lib/python2.7/site-packages/Theano-0.8.1-py2.7.egg/theano/compile/pfunc.py", line 442, in pfunc
    no_default_updates=no_default_updates)
  File "/home/yulei/.local/lib/python2.7/site-packages/Theano-0.8.1-py2.7.egg/theano/compile/pfunc.py", line 187, in rebuild_collect_shared
    (store_into, update_d[store_into]))
ValueError: ('this shared variable already has an update expression', (embedding_1_W, Elemwise{sub,no_inplace}.0))

**Comment by ylqfp** [comment]
``` python
shared_embed = Embedding(vocab_size, EMBED_HIDDEN_SIZE, mask_zero=False)
x = shared_embed(sentence_input)
x = Dropout(0.2)(x)
x = Convolution1D(nb_filter=nb_filter,
								filter_length = filter_length,
								border_mode='valid',
								activation='relu',
								subsample_length=1)(x)
x = MaxPooling1D(pool_length=pool_length)(x)
x = Convolution1D(nb_filter=nb_filter,
								filter_length = filter_length,
								border_mode='valid',
								activation='relu',
								subsample_length=1)(x)
x = Lambda(max_1d, output_shape=(nb_filter, ))(x)
x = Dense(SENT_HIDDEN_SIZE, activation='relu')(x)
outx = Dropout(0.2)(x)

cnn_share = Model(sentence_input, outx)

shared_cnn1 = cnn_share(a)
shared_cnn2 = cnn_share(b)

#y = Input(shape=(QUERY_MAXLEN,), dtype='int32')
#y = Embedding(vocab_size, EMBED_HIDDEN_SIZE, mask_zero=True)(c)
y = shared_embed(c)
y = RNN(QUERY_HIDDEN_SIZE, return_sequences=False, activation='relu')(y)
y = Dropout(0.2)(y)

#model_query = Model(query_input, y)
#qrnn = model_query(c)

#merge_vector = Merge([shared_cnn1, shared_cnn2, qrnn], mode='concat', concat_axis=-1)
merge_vector = merge([shared_cnn1, shared_cnn2, y], mode='concat', concat_axis=-1)
#merge_vector = merge([outx, outxx, y], mode='concat', concat_axis=-1)
dense1 = Dense(100, activation='relu')(merge_vector)
dp1 = Dropout(0.2)(dense1)
output1 = Dense(1, activation='sigmoid')(dp1)

model = Model(input=[a,b,c], output=output1)

```
ValueError: ('this shared variable already has an update expression', (embedding_1_W, Elemwise{sub,no_inplace}.0))

@braingineer @fchollet

**Comment by dvector89** [comment]
I get a same error as you did. Is there anyone can solve this problem? Thanks a lot.

**Comment by yanshuaicao** [comment]
I get the same error in a similar context, using `TimeDistributed`  layer. After some digging, it looks like that the issue there is `Wrapper` layer class takes `trainable_weights` from the wrapped layer, and somehow that causes `Model.layers` in `engine/training.py` to contain duplicated copies of parameters from wrapped layers, resulting in duplicates `trainable_weights` inside function `_make_train_function` of `Model` class.  After removing the part in `Wrapper` layer class that tries to duplicate, everything works. However, I don't know if that has any un-intended effects in other use cases.

**Comment by dvector89** [comment]
Hi @ylqfp , I tried some other structures without work well. I think maybe Keras doesnot support the nested shared layer right now. For your problem specially, you can pre-train the word embeddings by something like word2vec, then make the embeddings unchangeable during the training.

**Comment by McVilla** [comment]
I also get the same error. Could this error be solved? @fchollet

**Comment by zuoyigehaobing** [comment]
Same issue here. I'm trying to load the Keras model which is trained in Python into MATLAB. However, Matlab complains that weight sharing is not yet supported. Is there other method I can load the model into Matlab? Thanks!

**Comment by SalahAdDin** [comment]
@zuoyigehaobing Same problem here, did you find any solution?
