### ISSUE TITLE
AveragePooling falls back to CPU with Theano backend

### ISSUE THREAD

**Issue by esube** [fchollet/keras#2628]
I have tried to experiment with AveragePooling and it reverts back to CPU and my whole graph training becomes insanely slower.
I searched for similar issues and found this old issue on Theano: https://github.com/Theano/Theano/issues/2792

They seem to suggest that one should use MaxPooling with some weird argument or use the cudnn sandbox from theano. How is the keras averagepooling with Theano backend implemented?

Could somebody confirm that the use of averagepooling reverts back to CPU execution with Theano backend?

**Comment by nouiz** [comment]
Average pool is only available in Theano when cudnn is there. Also, you
must have ignore_border=True

**Comment by nouiz** [comment]
This is fixed for some times already, so closing. We have it in the new gpu back-end.
