### ISSUE TITLE
Any way to save Earlystopping for later use?

### ISSUE THREAD

**Issue by sjhddh** [fchollet/keras#2629]
Hey guys,

I use keras to train a very large piece of data.

Due to my machine's hardware limitation, I have to divide the dataset into N parts, and train them part by part.

So, I save my keras model every-time when I finished one part, and load it when train the next part of data.

I also use Earlystopping to monitor "validation_loss", and avoid overfitting.

However, if I re-load a keras model, the Earlystopping object will be "inited" again. Hence, the power of Earlystopping can only be effective within the same "part" of data.

Is there anyway to make it keep on watching and remember the "val_loss" from previous parts? pickle save it? 

Thx.

**Comment by carlthome** [comment]
Don't. Use [fit_generator()](https://github.com/fchollet/keras/blob/39051ef3ca9a9eedca58c8ea1b80ce5627d44ee5/keras/models.py#L568) and yield samples out-of-memory instead.
