### ISSUE TITLE
Theano warning on model.predict_classes

### ISSUE THREAD

**Issue by cheeyeelim** [fchollet/keras#2630]
I tried to generate model predictions using a trained model as follows.

```
model = model_from_json(open('model_architecture.json').read())
model.compile(loss='binary_crossentropy', optimizer='SGD')
model.load_weights('model_weights.h5')

#load data into test_data.

pred_label = model.predict_classes(test_data)
```

I get a warning from Theano after I run model.predict_classes.

`UserWarning: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 1 is not part of the computational graph needed to compute the outputs: keras_learning_phase.`

Any idea what the warning means and its potential implications?

**Comment by boscotsang** [comment]
I have the same proble as well, could any one solve this problem?

**Comment by cheeyeelim** [comment]
I suspected this is because the model is trained using Keras version prior to 1.0.0, and it is subsequently evaluated using Keras version 1.0.0 or later.

I no longer get the warning with a model trained using Keras 1.0.0 or later.
