### ISSUE TITLE
Implementing Cheng et al.'s LSTMN (Long-Short-Term-Memory-Network)

### ISSUE THREAD

**Issue by anayebi** [fchollet/keras#2631]
Has anyone tried implementing the LSTMN (Long-Short-Term-Memory-Network) described in equations (5)-(10) of [Cheng et al.](http://arxiv.org/pdf/1601.06733v4.pdf)?

I found an implementation of it in Torch/Lua [here](https://github.com/cheng6076/SNLI-attention/), but I think it could more easily be implemented in Keras.

**Comment by tokestermw** [comment]
maybe here? https://github.com/SourKream/NLP-Project/blob/master/Code/LSTMN.py

found the link really useful.
