### ISSUE TITLE
Average non-zero entries

### ISSUE THREAD

**Issue by bkj** [fchollet/keras#2632]
I'm trying to define a lambda function that averages all of the word embeddings from the embedding layer.  This code words, but it includes the word embedding of the `0s` in the input matrix -- those `0`s are just placeholders, so we don't want to include them -- eg 

    model.predict(np.array([[0, 100]]))

should equal

    model.predict(np.array([[100]]))

Does anyone have any ideas how to take the mean but drop the `0`s?  I'm assuming that it can be done with proper use of masking, but I'm not exactly sure how.

Thanks!

```
def s(x):
    return K.mean(x, axis=1)

input = Input(shape=(100,), dtype='int32')

embedding = Embedding(
    input_length = 10,
    input_dim = 100, 
    output_dim = 256,
    mask_zero = True
)(input)

lambda_ = Lambda(s)(embedding)

dense = Dense(1)(lambda_)

model = Model(input=labeled, output=dense)

model.compile(loss='mse', optimizer='rmsprop')
```

**Comment by nouiz** [comment]
Why not make the sum and divide by the number of non zeros? In Theano you
can compute that number as

T.neq(x, 0).sum()

**Comment by xingdi-eric-yuan** [comment]
I agree with @nouiz , masked mean I'm using is basically like that

**Comment by bkj** [comment]
(I think) the issue with that solution is that it backprops into the embedding of the 0s -- so eventually you're adding a nonzero vector for each zero that is supposed to be masked, which is bad.

I solved with:

```
class ZSumLayer(Layer):
    def __init__(self, output_dim, **kwargs):
        self.supports_masking = True
        self.output_dim = output_dim
        super(ZSumLayer, self).__init__(**kwargs)
        
    def call(self, x, mask=None):
        return K.sum(K.switch(mask[:,:,np.newaxis], x, 0), axis=1) # operative line
        
    def get_output_shape_for(self, input_shape):
        return (input_shape[0], self.output_dim)
    
    def compute_mask(self, input, mask):
        return None
```

This satisfies the following:

```
v1 = np.array([[0, 1]])
v2 = np.array([[0, 0, 1]])

assert(model.predict(v1) == model.predict(v2))
model.fit(X, y)
assert(model.predict(v1) == model.predict(v2))
```

regardless of the values in the first row of `model.layers[1].get_weights()[0]`.

(PS, I could additionallty count and divide by the number of non-zeros -- turns out that the zero-masked sum was actually fine for my purposes.)

Thanks everyone!

**Comment by soheilb** [comment]
@bkj Thanks, this is a working solution. I added the count for the sake of completeness:
```python
def call(self, x, mask=None):
        count = K.sum(mask, axis=1)[:, np.newaxis]
        avg = K.sum(K.switch(mask[:, :, np.newaxis], x, 0), axis=1) / count
        return K.cast(avg, x.dtype)```

**Comment by RaffEdwardBAH** [comment]
@bkj @soheilb Have yall tried making a version of this that works under tensorflow as well? It doesn't support that kind of indexing and I'm having trouble getting the switch statement to work.

**Comment by bkj** [comment]
I've only tried for Theano -- not sure how you'd do this in Tensorflow

**Comment by soheilb** [comment]
Check the solution suggested by @mpavankumarreddy in #2728 which should work on TF as well.

**Comment by shwetgarg** [comment]
@soheilb 
Thanks for the code.

With the give code, i am able to train my model.

But when I am loading the saved model as:
    self.model = model_from_json(mj, {'WordAverage':WordAverage})

I am getting following error:
    16   File "/home/shwegarg/anaconda2/lib/python2.7/site-packages/keras/models.py", line 197, in model_from_json
     17     return layer_from_config(config, custom_objects=custom_objects)
     18   File "/home/shwegarg/anaconda2/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 36, in layer_from_config
     19     return layer_class.from_config(config['config'])
     20   File "/home/shwegarg/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2375, in from_config
     21     process_layer(layer_data)
     22   File "/home/shwegarg/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2353, in process_layer
     23     custom_objects=custom_objects)
     24   File "/home/shwegarg/anaconda2/lib/python2.7/site-packages/keras/utils/layer_utils.py", line 36, in layer_from_config
     25     return layer_class.from_config(config['config'])
     26   File "/home/shwegarg/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 929, in from_config
     27     return cls(**config)
     28 TypeError: __init__() takes exactly 2 arguments (1 given)

Please help me in this regard.

**Comment by shwetgarg** [comment]
I have solved the problem my adding following function in the ZSumLayer class:

def get_config(self):
        config = {'output_dim': self.output_dim}
        base_config = super(ZSumLayer, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
