### ISSUE TITLE
Getting internal status from LSTM

### ISSUE THREAD

**Issue by totuta** [fchollet/keras#2634]
Hi all,

I'm trying to monitor the status of LSTM cells(input, forget, output and cell state),
but I can't figure out how to do that.

I found that the method below is related to those states, but can't figure out how to _log_ them to monitor.

Any help would be greatly appreciated.

`

```
def step(self, x, states):
    h_tm1 = states[0]   
    c_tm1 = states[1]   
    B_U = states[2]     
    B_W = states[3]     

    if self.consume_less == 'cpu':
        x_i = x[:, :self.output_dim]
        x_f = x[:, self.output_dim: 2 * self.output_dim]
        x_c = x[:, 2 * self.output_dim: 3 * self.output_dim]
        x_o = x[:, 3 * self.output_dim:]
    else:
        x_i = K.dot(x * B_W[0], self.W_i) + self.b_i
        x_f = K.dot(x * B_W[1], self.W_f) + self.b_f
        x_c = K.dot(x * B_W[2], self.W_c) + self.b_c
        x_o = K.dot(x * B_W[3], self.W_o) + self.b_o

    i = self.inner_activation(x_i + K.dot(h_tm1 * B_U[0], self.U_i))
    f = self.inner_activation(x_f + K.dot(h_tm1 * B_U[1], self.U_f))
    c = f * c_tm1 + i * self.activation(x_c + K.dot(h_tm1 * B_U[2], self.U_c))
    o = self.inner_activation(x_o + K.dot(h_tm1 * B_U[3], self.U_o))

    h = o * self.activation(c)
    return h, [h, c]
```

`

**Comment by braingineer** [comment]
Observing during computation is going to be prohibitively expensive.  Typically, the back end libraries build computation graphs and then push the data through it.  Theano has a page here on printing intermediate values: http://deeplearning.net/software/theano/library/printing.html#module-printing

In general, if you want to spy on your variables, you're going to have to:
1.  interrupt the computation graph so you can call "get_value" or "eval" or "np.asarray" on the variables 
2. keep the intermediate values in an extra datastructure which gets passed into the step state (or resides just outside of it).  Then, you have to do (at least in Theano): `T.inc_subtensor`.  

If you're using theano, you can google around to find tons of people asking about this on stackoverflow and the theano google group.   (I know, I just did it a few days ago).  

In general, however, it's hard because of how GPU calculations work.  

Now.. if you just want the internal states, `h` and `c`.. that's a different question.  And it was asked in the last 2 days and answered (I think).

**Comment by totuta** [comment]
Thank you so much for your quick reply, @braingineer. 

> Now.. if you just want the internal states, h and c.. that's a different question. And it was asked in the last 2 days and answered (I think).

Are you referring to #2593 ? If so, I understood making it stateful won't really change the result as long as we do the overriding thing you've suggested. But how can I get those h,c values? I tried .eval() and .get_value() but both failed. 

Forgive me if this is a very basic question for Theano.

**Comment by braingineer** [comment]
No worries.  Try running thing:

```python
from keras.layers import LSTM, Input
import keras.backend as K
import numpy as np
# all numbers are arbitrarily picked
batch=10
seq=10
feat=10
rhid=10


test_y *= 10.
xin = Input(batch_shape=(batch,seq,feat))
R = LSTM(rhid, return_sequences=True, stateful=True) 
out = R(xin)
M = Model(input=xin, output=out)
M.compile('Adam', 'MSE')

func = lambda r: K.mean(r.states[0]).eval()
print(func(R))
R.reset_states()
print(func(R))
for _ in range(5):
    test_x = np.random.random((batch,seq,feat))
    test_y = np.random.random((batch, seq, rhid)) ## going to be computed against R, so needs to be same size
    M.train_on_batch(test_x, test_y)
    print(func(R))

R.reset_states()
print(func(R))
for _ in range(5):
    test_x = np.random.random((batch,seq,feat))
    test_y = np.random.random((batch, seq, rhid)) ## going to be computed against R, so needs to be same size
    M.train_on_batch(test_x, test_y)
    print(func(R))
```

**Comment by totuta** [comment]
Thanks @braingineer. I modified your code a bit('cause it didn't run as it is) and I got:

	Traceback (most recent call last):
	  File "train.py", line 862, in <module>
	    verbose=False)
	  File "train.py", line 573, in train_nn
	    print(func(R))
	  File "train.py", line 488, in <lambda>
	    func = lambda r: K.mean(r.states[0]).eval()
	  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 184, in mean
	    if 'int' in x.dtype:
	AttributeError: 'NoneType' object has no attribute 'dtype'

What am I missing here?

**Comment by braingineer** [comment]
That error occurs when you haven't set `stateful` to True. 

I ran it from a fresher ipython notebook.  It seems I didn't have the test_x and test_y where they should have been (copy pasting things around can lead to things getting lost).  And I forgot to import Model.  

```python

from keras.layers import LSTM, Input
from keras.engine import Model
import keras.backend as K
import numpy as np
# all numbers are arbitrarily picked
batch=10
seq=10
feat=10
rhid=10
test_x = np.random.random((batch,seq,feat))
test_y = np.random.random((batch, seq, rhid)) ## going to be computed against R, so needs to be same size
test_y *= 10.
xin = Input(batch_shape=(batch,seq,feat))
R = LSTM(rhid, return_sequences=True, stateful=True) 
out = R(xin)
M = Model(input=xin, output=out)
M.compile('Adam', 'MSE')

func = lambda r: K.mean(r.states[0]).eval()
print(func(R))
R.reset_states()
print(func(R))
for _ in range(5):
    test_x = np.random.random((batch,seq,feat))
    test_y = np.random.random((batch, seq, rhid)) ## going to be computed against R, so needs to be same size
    M.train_on_batch(test_x, test_y)
    print(func(R))

R.reset_states()
print(func(R))
for _ in range(5):
    test_x = np.random.random((batch,seq,feat))
    test_y = np.random.random((batch, seq, rhid)) ## going to be computed against R, so needs to be same size
    M.train_on_batch(test_x, test_y)
    print(func(R))
```

**Comment by totuta** [comment]
Thank you @braingineer, your code works. Now I'm in the middle of applying your method to my codes.
Now, I have a number of questions to fully understand what is going on.

1) With stateful=True, we can monitor states values **per batch**?
2) states here mean the **cell-state** values(c) for each recursive neurons in that RNN layer?
3) to monitor input(i), forget(f), output(o), as in the **def step** function in LSTM of Keras, we need to interrupt the computational graph, as you explained above?

Would you please check whether my understanding is all correct?

And one last question.
Suppose that 2) above is correct, how can we monitor hidden state(h) values in LSTM?

Thank you very much in advance, @braingineer.

**Comment by totuta** [comment]
Oh, now I found that states[0] and states[1] are holding values of hidden and cell states. Am I right?
If so, which one is the cell state?

**Comment by braingineer** [comment]
In the LSTM class, the step function is used to iterate over the sequences. In this, the second argument returned is the `states`.  It is returned as `[h,c]` as shown here: https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L824

(also, sorry for not giving a longer response. I'm a bit swamped at the moment)
