### ISSUE TITLE
get sentiment of new text using imdb sentiment model

### ISSUE THREAD

**Issue by mamatopian** [fchollet/keras#2643]
Hi, I'm trying keras for analyzing text sentiment based on examples/imdb_lstm.py . 
1. I trained model and saved in file
   `json_string = model.to_json()
   open('lstm_model.json', 'w').write(json_string)
   model.save_weights('lstm_weights.h5')`
2. Now I want to feed new text to model to get sentiment of text. But how?
- I'm not able to convert string text to word_index.. I tried preprocessing.text.Tokenizer but I need word index dictionary which I don't see to be available for IMDB dataset. Am I missing something? Thank you very much..

**Comment by dandxy89** [comment]
If you take a look at the original dataset that you used to train the model with it does not have a word-index mapping dictionary.

Take a look at [this](https://github.com/dandxy89/DeepLearning_MachineLearning/blob/master/EmbeddingKeras/imdb_embedding_w2v.py) - this script uses word2vec embedding using Gensim. You could easily modify it to learn those during the training on the model - the data is located in the same folder as the script.

**Comment by loretoparisi** [comment]
@dandxy89 as soon the model weights are saved as @amirmamaghani explained, how to feed a new data set / text to get the prediction?

**Comment by dandxy89** [comment]
You should be able to do something like this...

```
def import_model():
    model = model_from_json(open('model_architecture.json').read())
    model.load_weights('model_weights.h5')

    m_input = model.get_input(train=False)
    m_output = model.get_output(train=False)

    f = K.function([m_input], [m_output])

    return f
```

Then 

`model = import_model()`

Finally

`model_output = model([batch_input])`

**Comment by loretoparisi** [comment]
@dandxy89 thank you!
So the core part is the `K.function([m_input], [m_output])`.
At this point I need the word_index to turn my input phrase in the `imdb` dataset format as a `sequence` of word indexes as explained in [datasets](https://keras.io/datasets/)

In the case of the `reuters` dataset this is present and you would do like

```python
word_index = reuters.get_word_index(path="reuters_word_index.pkl")
```

but for the `imdb` it is not.
So I have to follow the Word2Vec example for that with [this](https://github.com/dandxy89/DeepLearning_MachineLearning/blob/master/EmbeddingKeras/imdb_embedding_w2v.py#L164) function

```python
index_dict, word_vectors, train, test = create_dictionaries(train=train,
                                                            test=test,
                                                            model=model)
```

Is that correct?

**Comment by dandxy89** [comment]
That is correct, if you not able to get the work index dictionary from the IMDB dataset I would advise creating your own as shown in the script I created. Please take note that it was written a while ago and the syntax/imports of Keras have a changed slightly since then.

**Comment by loretoparisi** [comment]
@dandxy89 thank you I'm going to follow the Keras embedding example then!
