### ISSUE TITLE
Problem with TimeDistributed Wrapper

### ISSUE THREAD

**Issue by dakshvar22** [fchollet/keras#2649]
I am using the following code to add a TimeDistributed Convolution2D layer to my model -

`
model.add(TimeDistributed(Convolution2D(8, 4, 4, border_mode='valid'), input_shape=(2710,3,32,32)))
`

The full model building code is - 

`
model.add(TimeDistributed(Convolution2D(8, 4, 4, border_mode='valid'), batch_input_shape=(2710,3,32,32)))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2),border_mode='valid')))
    model.add(Activation('relu'))
    model.add(TimeDistributed(Convolution2D(8, 3, 3, border_mode='valid')))
    model.add(Activation('relu'))
    model.add(TimeDistributedFlatten())
    model.add(Activation('relu'))
    model.add(GRU(output_dim=100,return_sequences=True))
    model.add(GRU(output_dim=50,return_sequences=False))
    model.add(Dropout(.2))
    model.add(Dense(1))
`

I get the following error during the model building stage. I have not tried model.fit() yet. - 

> File "/home/toothless/daksh/ml/project/src/model/model2.py", line 133, in buildModel
>     model.add(TimeDistributed(Convolution2D(8, 4, 4, border_mode='valid'), input_shape=(2710,3,32,32)))
>   File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 110, in add
>     layer.create_input_layer(batch_input_shape, input_dtype)
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 337, in create_input_layer
>     dtype=input_dtype, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1026, in Input
>     name=name, input_dtype=dtype)
>   File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 957, in **init**
>     shape = input_tensor._keras_shape
> AttributeError: 'TensorVariable' object has no attribute '_keras_shape'

@fchollet can you help me out with this please?

**Comment by fchollet** [comment]
Can you post more readable code?

**Comment by dakshvar22** [comment]
@fchollet 
I got past the current problem. I think I had messed up my theano_backend file in the installation directory. Doing a clean install, solved it.
Although can you help me out with my specific problem now which involves using these TimeDistributed wrappers.
I have 25 videos in my training data. Each video consists of 2510 frames with frame size of 3 x 32 x 32 (channel size = 3). Now I want to feed in one video(all frames at once) into the CNN layer and this CNN layer will connect to my LSTM layer( right now not bidirectional, but later needed).This is why I needed a TimeDistributed version of Convolution 2D. For my Convolution 2D, I am using 32 filters of size 3 x 3. The sequence length for my LSTM would be 2510 only(the number of frames in video). The output of this whole network should be a vector of length 2510. Basically it is some sort of a regression problem.

Right now I have this architecture set up - 

`
def buildModel():

    model.add(TimeDistributed(Convolution2D(32, 3, 3,
                                        border_mode='valid'),batch_input_shape=(1,2710,img_channels, img_rows, img_cols)))
    model.add(keras.layers.normalization.BatchNormalization())
    model.add(Activation('relu'))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(Dropout(0.25))

    model.add(TimeDistributed(Convolution2D(32, 3, 3, border_mode='valid')))
    model.add(keras.layers.normalization.BatchNormalization())
    model.add(Activation('relu'))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(Dropout(0.25))

    model.add(TimeDistributed(Convolution2D(32, 3, 3, border_mode='valid')))
    model.add(keras.layers.normalization.BatchNormalization())
    model.add(Activation('relu'))
    model.add(TimeDistributed(MaxPooling2D(pool_size=(2, 2))))
    model.add(Dropout(0.25))

    model.add(TimeDistributed(Flatten()))
    model.add(TimeDistributed(Dense(256,activation='relu')))
    model.add(TimeDistributed(Dense(128,activation='relu')))

    model.add(LSTM(output_dim=255,return_sequences=True))

    model.add(TimeDistributed(Dense(2710,activation='sigmoid')))

    sgd = SGD(lr = 0.1, decay = 1e-5, momentum=0.9, nesterov=True)
    model.compile(loss='mean_absolute_error',
              optimizer=sgd,
              metrics=['accuracy'])

`

I am having trouble with preparing the input to the network.
I have successfully compiled the model. Now I have my Input Training Data(X_train) with dimensions - 25x2710x3x32x32 and the Output Training Data(Y_train) as 25x2710.

When I pass this data to the fit function with the call - 

`
model.fit(X_train,Y_train,batch_size=1,nb_epoch=5,shuffle=True,validation_split=0.2)
`

I get this error - 

> TypeError: ('Bad input argument to theano function with name "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py:503"  at index 1(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (1, 2721).')

I hope the problem is clear. Can you help me out with getting the data arranged for the required problem please?

**Comment by kesonyk** [comment]
Hi,@dakshvar22,if the number of frames is not fixed ,can be solved by this method? Thx

**Comment by vvekjoshi** [comment]
convert your Y_train data using   keras.utils.np_utils.to_categorical(Y_train, classes).
for e.g. if classes are 8 then:-
           Y_train = keras.utils.np_utils.to_categorical(Y_train,8)
this will give you 3d output. Which will be 25x2721x8.
