### ISSUE TITLE
BatchNormalization weight serialization issue

### ISSUE THREAD

**Issue by geohot** [fchollet/keras#2652]
Added BatchNormalization to my model and tried to load it with load_weights. It failed with a ValueError. Minimum repro, builds a model and saves and loads the weights. Fails at load_weights, Might have to do with the model being hierarchical. Using the latest keras.

repro: https://gist.github.com/geohot/ce1e9a1c79548f457feddfbdc175fdfa

fails with 

ValueError: ('object of too small depth for desired array', 'Container name "dense_2_W"')

**Comment by fchollet** [comment]
Good catch. I pushed a fix for it, you can just pull master and reinstall.
