### ISSUE TITLE
how can I read labels in words from cifar10 datasets?

### ISSUE THREAD

**Issue by moon5648** [fchollet/keras#2653]
From this page: https://www.cs.toronto.edu/~kriz/cifar.html

It says that I can read labels not as integers, but as meaningful names by reading the batches.meta file in the dataset.

But I just can't seem to find a way to read the file.

I tried by modifying the keras/datasets/cifar10.py at https://github.com/fchollet/keras/blob/master/keras/datasets/cifar10.py, like below:

```
from __future__ import absolute_import
from keras.datasets.cifar import load_batch
from keras.utils.data_utils import get_file
import numpy as np
import os


def load_data():
    dirname = "cifar-10-batches-py"
    origin = "http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz"
    path = get_file(dirname, origin=origin, untar=True)

    nb_train_samples = 50000

    X_train = np.zeros((nb_train_samples, 3, 32, 32), dtype="uint8")
    y_train = np.zeros((nb_train_samples,), dtype="uint8")

    for i in range(1, 6):
        fpath = os.path.join(path, 'data_batch_' + str(i))
        bpath = os.path.join(path, 'batches.meta')
        data, labels = load_batch(fpath)
        label_names = load_batch(bpath)
        
    return data, labels, label_names

data, labels, label_names = load_data()

print(labels[10], label_names[7])
```

But I get an error message like below:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-15-cf7a7f68853d> in <module>()
     24     return data, labels, label_names
     25 
---> 26 data, labels, label_names = load_data()
     27 
     28 print(labels[10], label_names[7])

<ipython-input-15-cf7a7f68853d> in load_data()
     20         bpath = os.path.join(path, 'batches.meta')
     21         data, labels = load_batch(fpath)
---> 22         label_names = load_batch(bpath)
     23 
     24     return data, labels, label_names

/home/robotics/anaconda3/lib/python3.5/site-packages/keras/datasets/cifar.py in load_batch(fpath, label_key)
     17             d[k.decode("utf8")] = v
     18     f.close()
---> 19     data = d["data"]
     20     labels = d[label_key]
     21 

KeyError: 'data'

It doesn't look like I'm on the right track, so could anyone help me with this please??

In addition, I'm trying to display how my model does via displaying the target image and my model prediction with meaningful names.

How can I do those also?? 

Thank you very much in advance.

**Comment by fchollet** [comment]
The indices of each labels can be read on this page:

https://www.cs.toronto.edu/~kriz/cifar.html

0 is airplane, 1 is automobile, etc.

**Comment by sachin1066** [comment]
folowing this code << https://github.com/mila-udem/fuel/blob/master/fuel/converters/cifar10.py >>

using cifar10 for python
![screenshot from 2017-06-19 17 37 21](https://user-images.githubusercontent.com/29143883/27285014-b37a7e8e-5518-11e7-9d79-8dbc283cdd27.png)

**Comment by sachin1066** [comment]
using this code <<   https://github.com/mila-udem/fuel/blob/master/fuel/converters/cifar10.py  >>
for cifar10 for python
![screenshot from 2017-06-19 17 37 21](https://user-images.githubusercontent.com/29143883/27285084-0b698162-5519-11e7-8695-85fbef7b475a.png)

got this error

**Comment by pGit1** [comment]
How about for CIFAR 100? I need the Coarse and Fine labels

**Comment by dqii** [comment]
It would be nice to have the coarse labels easily available as well.

**Comment by itai12312** [comment]
No, it doesn't look that. Here is the list:
coarse_label = [
    'apple', # id 0
    'aquarium_fish',
    'baby',
    'bear',
    'beaver',
    'bed',
    'bee',
    'beetle',
    'bicycle',
    'bottle',
    'bowl',
    'boy',
    'bridge',
    'bus',
    'butterfly',
    'camel',
    'can',
    'castle',
    'caterpillar',
    'cattle',
    'chair',
    'chimpanzee',
    'clock',
    'cloud',
    'cockroach',
    'couch',
    'crab',
    'crocodile',
    'cup',
    'dinosaur',
    'dolphin',
    'elephant',
    'flatfish',
    'forest',
    'fox',
    'girl',
    'hamster',
    'house',
    'kangaroo',
    'computer_keyboard',
    'lamp',
    'lawn_mower',
    'leopard',
    'lion',
    'lizard',
    'lobster',
    'man',
    'maple_tree',
    'motorcycle',
    'mountain',
    'mouse',
    'mushroom',
    'oak_tree',
    'orange',
    'orchid',
    'otter',
    'palm_tree',
    'pear',
    'pickup_truck',
    'pine_tree',
    'plain',
    'plate',
    'poppy',
    'porcupine',
    'possum',
    'rabbit',
    'raccoon',
    'ray',
    'road',
    'rocket',
    'rose',
    'sea',
    'seal',
    'shark',
    'shrew',
    'skunk',
    'skyscraper',
    'snail',
    'snake',
    'spider',
    'squirrel',
    'streetcar',
    'sunflower',
    'sweet_pepper',
    'table',
    'tank',
    'telephone',
    'television',
    'tiger',
    'tractor',
    'train',
    'trout',
    'tulip',
    'turtle',
    'wardrobe',
    'whale',
    'willow_tree',
    'wolf',
    'woman',
    'worm',
]

**Comment by adam-dziedzic** [comment]
I extended the mappings between fine and coarse labels by @itai12312 to other useful mappings between fine (classes) and coarse labels (super classes) for CIFAR100: https://gist.github.com/adam-dziedzic/4322df7fc26a1e75bee3b355b10e30bc

Example mapping from id of a fine label to id of a coarse label:

```
fine_id_coarse_id = 
{0: 4,
 1: 1,
 2: 14,
 3: 8,
 4: 0,
 5: 6,
 6: 7,
 7: 7,
 8: 18,
 9: 3,
 10: 3,
 11: 14,
 12: 9,
 13: 18,
 14: 7,
 15: 11,
 16: 3,
 17: 9,
 18: 7,
 19: 11,
 20: 6,
 21: 11,
 22: 5,
 23: 10,
 24: 7,
 25: 6,
 26: 13,
 27: 15,
 28: 3,
 29: 15,
 30: 0,
 31: 11,
 32: 1,
 33: 10,
 34: 12,
 35: 14,
 36: 16,
 37: 9,
 38: 11,
 39: 5,
 40: 5,
 41: 19,
 42: 8,
 43: 8,
 44: 15,
 45: 13,
 46: 14,
 47: 17,
 48: 18,
 49: 10,
 50: 16,
 51: 4,
 52: 17,
 53: 4,
 54: 2,
 55: 0,
 56: 17,
 57: 4,
 58: 18,
 59: 17,
 60: 10,
 61: 3,
 62: 2,
 63: 12,
 64: 12,
 65: 16,
 66: 12,
 67: 1,
 68: 9,
 69: 19,
 70: 2,
 71: 10,
 72: 0,
 73: 1,
 74: 16,
 75: 12,
 76: 9,
 77: 13,
 78: 15,
 79: 13,
 80: 16,
 81: 19,
 82: 2,
 83: 4,
 84: 6,
 85: 19,
 86: 5,
 87: 5,
 88: 8,
 89: 19,
 90: 18,
 91: 1,
 92: 2,
 93: 15,
 94: 6,
 95: 0,
 96: 17,
 97: 8,
 98: 14,
 99: 13}
```

**Comment by Sehaba95** [comment]
Here is a CIFAR-100 labels, since, I was facing problems to find them, I will share them in here:

`str_labels = ['apple', 'aquarium_fish', 'baby', 'bear', 'beaver', 'bed', 'bee', 'beetle', 'bicycle', 'bottle', 'bowl', 'boy', 'bridge', 'bus', 'butterfly', 'camel', 'can', 'castle', 'caterpillar', 'cattle', 'chair', 'chimpanzee', 'clock', 'cloud', 'cockroach', 'couch', 'crab', 'crocodile', 'cup', 'dinosaur', 'dolphin', 'elephant', 'flatfish', 'forest', 'fox', 'girl', 'hamster', 'house', 'kangaroo', 'keyboard', 'lamp', 'lawn_mower', 'leopard', 'lion', 'lizard', 'lobster', 'man', 'maple_tree', 'motorcycle', 'mountain', 'mouse', 'mushroom', 'oak_tree', 'orange', 'orchid', 'otter', 'palm_tree', 'pear', 'pickup_truck', 'pine_tree', 'plain', 'plate', 'poppy', 'porcupine', 'possum', 'rabbit', 'raccoon', 'ray', 'road', 'rocket', 'rose', 'sea', 'seal', 'shark', 'shrew', 'skunk', 'skyscraper', 'snail', 'snake', 'spider', 'squirrel', 'streetcar', 'sunflower', 'sweet_pepper', 'table', 'tank', 'telephone', 'television', 'tiger', 'tractor', 'train', 'trout', 'tulip', 'turtle', 'wardrobe', 'whale', 'willow_tree', 'wolf', 'woman', 'worm']`

You can get the label of a given class with this line of code:

`print(str_labels[classNumber])`

I wish that will help.
