### ISSUE TITLE
`repeat_elements(x, rep, axis)` incompatibility: in Theano rep="int, scalar or tensor variable", but TF rep must be "int"

### ISSUE THREAD

**Issue by asmith26** [fchollet/keras#2656]
I'm trying to run some [Keras code that implement "Stochastic Depth"](https://github.com/dblN/stochastic_depth_keras/blob/master/train.py) on TensorFlow. The original code runs on Theano, and when switching to TensorFlow I'm getting an error (note I have pulled the latest Keras commits):

```
Traceback (most recent call last):
...
  File "~/git/keras/keras/backend/tensorflow_backend.py", line 525, in repeat_elements
    x_rep = [s for s in splits for i in range(rep)]
TypeError: range() integer end argument expected, got Tensor.
```

The code that is breaking it is (where `x` is a collection of Keras layers built-up using the Functional API):

```
pad_shape = (1,16,80,60)
padding = K.zeros(pad_shape)
# logging.debug(K.shape(x))
# logging.debug(K.shape(x)[0])
padding = K.repeat_elements(padding, rep=K.shape(x)[0], axis=0)
```

Thus is looks like, the [Theano `repeat_elements`](https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L300) (which I believe implements [this function from Theano](https://github.com/Theano/Theano/blob/master/theano/tensor/extra_ops.py#L861)) handles "rep=int, scalar or tensor variable"; however the [TensorFlow `repeat_elements`](https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L515) doesn't.

I'm not particularly familiar with the TensorFlow API so I'm not sure if there already exists a similar `repeat` function to Theano. Otherwise, please can we implement the TensorFlow backend `repeat_elements` function to handle "int, scalar or tensor variable" like Theano? If it helps, when I uncomment my `logging.debug` code above I get Theano:

```
DEBUG:root:Shape.0
DEBUG:root:Subtensor{int64}.0
```

and TensorFlow:

```
DEBUG:root:Tensor("Shape:0", shape=(4,), dtype=int32)
DEBUG:root:Tensor("Squeeze:0", shape=(), dtype=int32)
```

Thanks!

**Comment by allanzelener** [comment]
I also ran into this issue. I think Tensorflow still doesn't have something like repeat_elements yet but I figured out a workaround using other functions. It's relatively messy and I haven't thought about how to generalize it beyond a rank 1 tensor but maybe this will help someone:

```python
    conv_width_index = K.arange(0, stop=conv_dims[1])
    # conv_width_index = K.repeat_elements(conv_width_index, conv_dims[1], axis=0)
    conv_width_index = K.tile(
        K.expand_dims(conv_width_index, 0), [conv_dims[1], 1])
    conv_width_index = K.flatten(K.transpose(conv_width_index))
```

**Comment by myhussien** [comment]
Tensorflow has the tf.tile function with works as follows <output = tf.tile(input, [rep_batch, rep_row, rep_col, rep_ch])>. You can call it from <K.tf.tile> . However, I don't know how to would you deal with None type dimensions as in  <K.repeat_elements(current_output,rep=input.shape[1],axis=1)> if input shape is (None, int, int).

**Comment by myhussien** [comment]
try this:
`padding =K.tf.tile(padding, [K.shape(x)[0],1 , 1, 1])`
