### ISSUE TITLE
on_batch_begin is not called on validation data in fit_generator

### ISSUE THREAD

**Issue by udibr** [fchollet/keras#2661]
I need it to reset RNN before every batch in which validation evaluation are made

**Comment by fchollet** [comment]
Can you give more details?

**Comment by udibr** [comment]
I built a callback sub class which made a print at the beginning of every batch. I gave it to fit_generator with train data generator and validation data generator. I got my prints on every training batch but non for the validation part

**Comment by joelthchao** [comment]
In [`_fit_loop()`](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L789), you can see that `on_batch_begin` won't work for validation.
