### ISSUE TITLE
Output from intermediate layers with functional API

### ISSUE THREAD

**Issue by GelliFrancesco** [fchollet/keras#2664]
In the [FAQ section](http://keras.io/getting-started/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer) there is an example about how to get output from intermediate layers using the Sequential API.

How is it possible to achieve that with the functional API? It is written:
> Another more flexible way of getting output from intermediate layers is to use the functional API.

Could you please give a little bit more details?
Thank you

**Comment by joelthchao** [comment]
Define a new model with intermediates layer as outputs and predict it.
```python
model = Model(input=[your_input], output=[intermediate_layer])
# model.compile(optimizer='sgd', loss='mse') # latest Keras don't need it
results = model.predict([x])
```

**Comment by GelliFrancesco** [comment]
Thank you, I read a similar solution in [another issue ](https://github.com/fchollet/keras/issues/2621), but I fail to understand it. If the pipeline is:

1. Defining a model:  _model_to_train_
2. Training it: _model_to_train_.fit()_
3. defining a second model as you suggested

then how can the second model know to use the same weights of  _model_to_train_, if its definition doesn't contain any reference to it?

What then if I want to define a second model that doesn't share the same weights?

**Comment by joelthchao** [comment]
> how can the second model know to use the same weights of model_to_train, if its definition doesn't contain any reference to it?

Since it's functional API, sharing weight is automatically done. 
> What then if I want to define a second model that doesn't share the same weights?

You have to re-define model layer by layer again to prevent sharing weight. (Write a function to reuse codes!)

**Comment by apinto92** [comment]
@joelthchao Could you give a small example of how to connect two models in the way that @GelliFrancesco  asked?

Imagine that the first model is an autoencoder and the second a CNN. How is the merging of these two models performed so they can share weights an belong to a single optimised model?

**Comment by nnmsIsaac** [comment]
@apinto92 here's a minimal model that gets the point across:
```
import tensorflow
from tensorflow import keras
from keras.layers import Input, Dense
from keras.models import Model
inport numpy as np

inputs = Input(size=(4,))
x = Dense(16, activation="relu")(x)
intermediate = Dense(16, activation="relu")(x)
x = Dense(16, activation="relu")(intermediate)
outputs = Dense(16, activation="relu")(x)

in_to_out = Model(inputs=inputs, outputs=outputs)
# compile and fit the model to your data

in_to_intermediate = Model(inputs=inputs, outputs=intermediate)
# if you do "in_to_intermediate.predict(data)" it will give you the output of the intermediate layer. 
```

**Comment by mjmikulski** [comment]
@nnmsIsaac How can I refactor your model so it is possible to feed sth to intermediate layer:

Obvious solution does not work:
```python
intermediate_to_out = Model(inputs=intermediate, outputs=outputs)
```

```
>>>UserWarning: Model inputs must come from `keras.layers.Input` (thus holding past layer metadata), they cannot be the output of a previous non-Input layer. Here, a tensor specified as input to your model was not an Input tensor, it was generated by layer dense_1.
Note that input tensors are instantiated via `tensor = keras.layers.Input(shape)`.
```
So following this message, I try to use `Input` as intermediate, but then, how to connected both models into `in_to_out`?

**Comment by adthorson** [comment]
I'm by no means an expert; however, felt like tackling this problem.

You need to redefine an Input to this subset of layers model.  First input shape needs to conform to what the intermediate layer expects.

I coded up something, but I haven't verified this code:


def evaluate_from_intermediate_layer_index(model, index, X):
    layers = model.layers
    count_layers = len(layers)
    #
    if (index >= count_layers):
        raise Exception("Index must be < {}".format(count_layers))
    #
    # Create a new input layer using the appropriate shape - shape of requested
    # layer
    input_shape = layers[index].get_input_shape_at(0)
    layer_input = Input(shape=input_shape)
    #
    # Setup new functional model using subset of layers starting at the newly
    # defined input layer
    o = layer_input
    for layer in model.layers[index:]:
        o = layer(o)
    #
    new_model = Model(layer_input, o)
    #
    print(new_model.predict(X))
