### ISSUE TITLE
LSTM as first layer, is the input fully-connected by default?

### ISSUE THREAD

**Issue by carlthome** [fchollet/keras#2673]
Silly question, but when having a RNN as the first layer in a model, are the input dimensions for a time step fully-connected or is a Dense layer explicitly needed?

**Comment by fchollet** [comment]
Sorry, not sure I understand your question. Can you expand?

**Comment by carlthome** [comment]
Does this model result in RNN 1 or RNN 2 (beautifully illustrated below)?

```Python
m = Sequential()
m.add(LSTM(3, input_shape=(None, 3)))
...
```

![image](https://cloud.githubusercontent.com/assets/1595907/15130197/d48f39c8-1646-11e6-9776-1c436d507aac.png)

I'd guess _RNN 1_, and that for _RNN 2_ this is needed:

```Python
m = Sequential()
m.add(TimeDistributedDense(input_shape=(None, 3))
m.add(LSTM(3))
...
```

Correct?

**Comment by fchollet** [comment]
Yes, option 1. But adding a TimeDistributedDense does not result in option
2, either. For option 2 I suppose you'd reshape your sequence (3D) to a 2D
matrix and apply a Dense layer, then reshape back to 3D.

**Comment by carlthome** [comment]
Ok, thanks! Just to be clear though, each neuron (=vertex) and each weight (=edge) is a scalar (i.e. the images represent _a single time step_ for _a single input vector_). Are you sure model 2 wouldn't turn out like RNN 2? Otherwise, I'm very curious what `TimeDistributed(Dense())` is for, as I must be misunderstanding it. "Perform a fully-connected operation at each time step", etc. etc.

**Comment by fchollet** [comment]
TimeDistributedDense is just applying a same affine transformation on every
slice of your sequence.

A sequence is a 3D tensor. A slice of that sequence is a 2D tensor. You
apply a matrix multiplication + bias addition to each of these slices.
Pretty simple, right?

**Comment by carlthome** [comment]
Aaahh, I'm a bonehead... Thanks @fchollet! Way easier to think like that. :yellow_heart:

**Comment by tbenst** [comment]
If I understand correctly, LSTM is fully dense to input features and thus resembless RNN 2?

Let's say my input is of shape `(nexamples, ntimesteps,nfeatures)`. Is it possible to train `nfeatures` LSTM cells such that each cell is independent and exclusively connected to each feature?

Eg equivalent to training `nfeatures` models on data of shape `(nexamples, ntimesteps)` with LSTM (1). I believe this would be drawn as RNN 1.

**Comment by carlthome** [comment]
> LSTM is fully dense to input features and thus resembless RNN 2?
Yes

>Is it possible to train nfeatures LSTM cells such that each cell is independent and exclusively connected to each feature?

If you wish to avoid the input projection you'd need multiple `LSTM()` layers per independent feature AFAIK.

**Comment by bitmanlger** [comment]
@carlthome your last answer contradicts that of @fchollet if I read correctly. i.e. you say the LSTM is fully connected = RNN2 (similar to your answer [here](https://github.com/fchollet/keras/issues/4149#issuecomment-301929500)), while he said it was more like RNN1.

In your first diagram the number of inputs = number of hidden units, but if the number of hidden units were say n+1, then that diagram doesn't work anymore (i.e. there can not be a 1:1 mapping of inputs to units)........

Looking at François' code, I see a dot product over all inputs and the kernel weights, (for GRU it looks like this: `matrix_x = K.dot(inputs * dp_mask[0], self.kernel)` so I conclude you're right. (similar to [your answer](https://github.com/fchollet/keras/issues/4149#issuecomment-258903091) here).

**Comment by asif31iqbal** [comment]
@fchollet a slightly unrelated question about the `input_shape` parameter. I noticed that for `Dense` layers, when the `input_shape` is mentioned as `(10, None)`, it means each input is a 10 element vector and the batch dimension is unspecified. However, for recurrent layers, it seems like the order is reversed, like `(None, 10)` (`None` comes first and 10 goes second). Am I right in thinking that? Is that by design?
