### ISSUE TITLE
GPU not detected anymore

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#2676]
Hi,
I've just upgraded Theano and Keras, and everything was fine.
But suddenly, the GPU is not detected anymore. See the error:

`Using Theano backend.`
`ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device 0 failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1`

`ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device gpu failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1`

`Traceback (most recent call last):`
  `File "ConvolutionalTest.py", line 9, in <module>
    from keras.callbacks import ModelCheckpoint`
 ` File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>`
    `from . import backend
  `File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/__init__.py", line 51, in <module>`
    `from .theano_backend import *`
  `File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1, in <module>`
    `import theano`
  `File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/__init__.py", line 111, in <module>`
    `theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()`
  `File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_driver.py", line 29, in test_nvidia_driver1`
    `A = cuda.shared_constructor(a)`
  `File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/sandbox/cuda/var.py", line 218, in float32_shared_constructor
    enable_cuda=False)`
  `File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py", line 557, in use
    gpu_init(use.device_number, config.lib.cnmem)`
`RuntimeError: ('initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1\n', 'You asked to force this device and it failed. No fallback to the cpu or other gpu device.')`

Any idea why the GPU is not detected anymore?

**Comment by nouiz** [comment]
Try lib.cnmem=0.9 or lower. If you environment changed, this can happen
(for example the other running programme on a GPU that is shared with the
monitor)

**Comment by FiReTiTi** [comment]
It's already the case: cnmem = 0.35

**Comment by nouiz** [comment]
I don't know, maybe a reboot would help. I don't know why, but very
infrequently this help.

**Comment by FiReTiTi** [comment]
Sorry, I should have written that everything worked fine before the upgrade.

**Comment by nouiz** [comment]
Try without cnmem. What nvidia-smi tell you? It seem to be really missing
memory. Could there be a process suspended that still use memory?

**Comment by FiReTiTi** [comment]
I've done a full reinstall of Theano+Keras bleeding edge version and not it works...
