### ISSUE TITLE
eucl_dist_output_shape is wrong in the siamese example?

### ISSUE THREAD

**Issue by benjaminklein** [fchollet/keras#2677]
Below are the definitions from the siamese mnist example (mnist_siamese_graph)
Why eucl_dist_output_shape returns shape1 when the euclidean_distance function is returning a single number (the distance) per pair.

Shouldn't it be:
def eucl_dist_output_shape_fixed(shapes):
    shape1, shape2 = shapes
    return (shape1[0],1)

def euclidean_distance(vects):
    x, y = vects
    return K.sqrt(K.sum(K.square(x - y), axis=1, keepdims=True))

def eucl_dist_output_shape(shapes):
    shape1, shape2 = shapes
    return shape1

**Comment by braingineer** [comment]
correct.  the shape function is incorrect.

well, mostly.  euclidean_distance is returning a vector.  "a single number" would imply a scalar, not a vector.
