### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'name' while loading saved model in Keras 0.3.2, python 2.7

### ISSUE THREAD

**Issue by bienbinod** [fchollet/keras#2687]
While loding pre-trained model, I am getting the following error. Could someone please help me to fix it? For the moment I would like to stick with Keras 0.3.2.
## In [10]: g = model_from_config(json_dict)

TypeError                                 Traceback (most recent call last)
<ipython-input-10-eeec0693ab7e> in <module>()
----> 1 g = model_from_config(json_dict)

 .local/lib/python2.7/site-packages/Keras-0.3.2-py2.7.egg/keras/models.pyc in model_from_config(config, custom_objects)
    175
    176     # Create a container then set class to appropriate model
--> 177     model = container_from_config(config, custom_objects=custom_objects)
    178     if model_name == 'Graph':
    179         model.**class** = Graph

 local/lib/python2.7/site-packages/Keras-0.3.2-py2.7.egg/keras/utils/layer_utils.pyc in container_from_config(original_layer_dict, custom_objects)
     55         nodes = layer_dict.get('node_config')
     56         for node in nodes:
---> 57             layer = container_from_config(layer_dict['nodes'].get(node['name']))
     58             node['layer'] = layer
     59             graph_layer.add_node(**node)

 local/lib/python2.7/site-packages/Keras-0.3.2-py2.7.egg/keras/utils/layer_utils.pyc in container_from_config(original_layer_dict, custom_objects)
     90         if 'custom_name' in layer_dict:
     91             layer_dict['name'] = layer_dict.pop('custom_name')
---> 92         base_layer = get_layer(name, layer_dict)
     93         return base_layer
     94

 .local/lib/python2.7/site-packages/Keras-0.3.2-py2.7.egg/keras/utils/layer_utils.pyc in get_layer(identifier, kwargs)
    156 def get_layer(identifier, kwargs=None):
    157     return get_from_module(identifier, globals(), 'layer',
--> 158                            instantiate=True, kwargs=kwargs)

.local/lib/python2.7/site-packages/Keras-0.3.2-py2.7.egg/keras/utils/generic_utils.pyc in get_from_module(identifier, module_params, module_name, instantiate, kwargs)
     16             return res()
     17         elif instantiate and kwargs:
---> 18             return res(**kwargs)
     19         else:
     20             return res

TypeError: **init**() got an unexpected keyword argument 'name'

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [  ] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by 0x000FF4** [comment]
I also have this problem.

**Comment by sundarcf** [comment]
I ran into similar issue while loading model saved with python 3.4 into python2.7. No issue loading the model with python3.4.
