### ISSUE TITLE
RNN/LSTM with multiple time periods 

### ISSUE THREAD

**Issue by akansal1** [fchollet/keras#2692]
Is it possible to have RNN/LSTM to have multiple periods in same model? I am looking for some like 

![image](https://cloud.githubusercontent.com/assets/8511760/15178605/2df5704c-1794-11e6-94c3-f1a60a1c7ef5.png)

Thnks

**Comment by themummy** [comment]
I think you may be interested in a [Clockwork RNN](https://libraries.io/github/pranv/clockwork_rnn), which combines multiple frequencies in on recurrent network. I'm not sure if it's possible to implement in Keras.

**Comment by theosem** [comment]
> I'm not sure if it's possible to implement in Keras.

I found this one from a keras contributor.. 
https://github.com/braingineer/ikelos/blob/master/ikelos/layers/cwrnn.py
I don't know if and how it works. I haven't tested it. just sharing
