### ISSUE TITLE
Format image dataset for use with Keras?

### ISSUE THREAD

**Issue by oweingrod** [fchollet/keras#2697]
Hello!

New to Keras, looking for information on how to prepare a dataset of images + labels for Keras? Is Pickle the best way? HDF5? Or can they be created using actual directory paths? I'm aware that datasets are just numpy arrays of data and labels, but any information on the creation of a new dataset for Keras would be very helpful.

**Comment by carlthome** [comment]
Go for HDF5. Here's a great example: https://gist.github.com/jfsantos/e2ef822c744357a4ed16ec0c885100a3

If you also need to perform preprocessing of the images, you'll want to look into [model.fit_generator()](https://github.com/fchollet/keras/blob/7b4e157356a60986f2a38d26d00beb19d76dbbd3/keras/models.py#L568).
