### ISSUE TITLE
' Output tensors to a Model must be Keras tensors ' when i use functional api to build QA model

### ISSUE THREAD

**Issue by ssdf93** [fchollet/keras#2704]
![slice 1](https://cloud.githubusercontent.com/assets/5064764/15203485/e111eadc-1836-11e6-9a46-3699796f8237.jpg)

I want to build the network shown in the picture

``` python

    question_input = Input(shape=(maxlen,),dtype='int32')
    answer_input = Input(shape=(maxlen,),dtype='int32')
    good_answer_input = Input(shape=(maxlen,),dtype='int32')
    bad_answer_input = Input(shape=(maxlen,),dtype='int32')

    embedding_layers=Embedding(dicSize,length,input_length=maxlen,weights=[embedding])
    question_embeds=embedding_layers(question_input)
    answer_embeds=embedding_layers(answer_input)


    maxpool = Lambda(lambda x: K.max(x, axis=1), output_shape=lambda x: (x[0], x[2]))
    question_maxpool = maxpool(question_embeds)
    answer_maxpool = maxpool(answer_embeds)

    dot = lambda a, b: K.batch_dot(a, b, axes=1)


    similarity = lambda x: dot(x[0], x[1]) / K.sqrt(dot(x[0], x[0]) * dot(x[1], x[1]))

    similarity_value=merge([question_maxpool, answer_maxpool], mode=similarity,output_shape=lambda x: x[0])


    qa_model=Model(input=[question_input, answer_input], output=similarity_value)

    good_output = qa_model([question_input, good_answers])
    bad_output = qa_model([question_input, bad_answers])

    M=0.03
    max_margin_loss = merge([good_output, bad_output], mode=lambda x:K.maximum(1e-6, M - x[0] + x[1]), output_shape=lambda x: x[0])

    training_model = Model(input=[question_input, good_answer_input, bad_answer_input], output=max_margin_loss)

    training_model.compile(loss=lambda y_true, y_pred: y_pred, optimizer='adam')
    print(training_model.layers)
```

`

  Traceback (most recent call last):
  File "/Users/insuranceQA-master/rnn.py", line 233, in <module>
    build_model(questions,good_answers,bad_answers)
  File "/Users/insuranceQA-master/rnn.py", line 172, in build_model
    training_model = Model(input=[question_input, good_answer_input, bad_answer_input], output=max_margin_loss)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/keras/engine/topology.py", line 1571, in **init**
    'Keras tensors. Found: ' + str(x))
Exception: Output tensors to a Model must be Keras tensors. Found: Elemwise{true_div,no_inplace}.0
`

I think problem may be happened from qa_model to training_model

**Comment by carlthome** [comment]
Just skimming your code a little bit (it's a bit messy and please add [code highlighting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)) the first thing that looks a little weird is how you get the output_shape for your lambda merge.

**Comment by carlthome** [comment]
Also, please consider clarifying the issue title and make it more precise to your problem.

**Comment by CNiallDemensha** [comment]
@ssdf93 Hey! Did you find any solution to your problem?

**Comment by gunashekar** [comment]
@CNiallDemensha  did you find any solution to debug the error?
