### ISSUE TITLE
Sciki-learn wrapper - GridSearchCV not working

### ISSUE THREAD

**Issue by MRLoghmani** [fchollet/keras#2705]
I have a problem with the Scikit-learn wrapper. I have my model ready and I already tested it with some parameter, but I would like to investigate more accurately the hyper-parameter space. I already used scikit-learn's GridSearchCV in the past for some simple classifier, so I'm familiar with its simple syntax. 
Unfortunately when I run GridSearchCV for my keras model I don't get any error message, but the IDLE simply ask me if I want to kill my process. If I push 'cancel' this message appears 4/5 times and at the end it stops asking, but the program never finishes to run and python simply stop to responde. I'm sure that is not because of the running time because I also tried with very limited space to explore and it does not work. I also tried to update Theano, Keras and Scikit-learn, but nothing changed. Do you have any idea of how to solve this problem?

P.S. I'm using OS X El Capitan

**Comment by fbrundu** [comment]
I am having the same issue. Any update on this?

I have `tensorflow==1.0.0` and `Keras==2.0.1`.
Right now I am building the last upstream version of tensorflow and Keras, to see if I can reproduce it.

**Comment by MRLoghmani** [comment]
@fbrundu the project I was doing using Keras is finished. At the end I ended up writing my own ugly GS just for my purpose. So sorry, no updates from me.

**Comment by fbrundu** [comment]
To anyone interested: to debug, set the number of jobs to 1 in the GridSearchCV() call. In this way, the exception which causes the threads to halt can be received by the main thread.
It is most likely that also in @MRLoghmani 's case the problem was hidden by the wrapper.

@fchollet should it be possible to forward the workers' exception to the main thread?
