### ISSUE TITLE
Question about AveragePooling

### ISSUE THREAD

**Issue by dsy412610** [fchollet/keras#2707]
Using AveragePooling may increase computation cost. But after I replaced MaxPooling with AveragePooling, training time became 40 times longer than before. Is there anything wrong? Thanks!

**Comment by joelthchao** [comment]
I do a simple experiment, creating a model with 7 stage of pooling. Two different kind of pooling don't have any computation time difference. Can you provide codes to reproduce this phenomenon?
P.S. I use TensorFlow backend.

**Comment by moothes** [comment]
#2628 maybe this can help you

**Comment by dsy412610** [comment]
@joelthchao @moothes Thank you very much! Average pool is only available in Theano when cudnn is there, but I didn't use cudnn.
