### ISSUE TITLE
is model.fit() accumulative?

### ISSUE THREAD

**Issue by flyingpoops** [fchollet/keras#2712]
Hi, I am new to keras and neural network, and I am wondering if model.fit() is accumulative?

So basically, I accidentally killed the program yesterday, but however I do save weights on every epoch. So I was wondering if I could load the last weight into the model and then call model.fit()?

**Comment by fchollet** [comment]
Yes, you can.

**Comment by flyingpoops** [comment]
OK, thanks. Just to want to validate one other thing. When fit() in keras/models.py is called, it returned with the fit() in keras/engine/training.py. Am I right?

**Comment by flyingpoops** [comment]
@fchollet

**Comment by jfsantos** [comment]
@flyingpoops Yes, the `fit()` implementations in `keras/model.py` do some setting up and then call `fit()` in `keras/engine/training.py`.

**Comment by flyingpoops** [comment]
I think now I have a better understanding of keras, thanks @jfsantos
