### ISSUE TITLE
Working reshape example for CNN running on text data needed

### ISSUE THREAD

**Issue by wailoktam** [fchollet/keras#2713]
Hi, as described in the title. I keep getting:

Wrong number of dimensions: expected 4, got 2 with shape (32, 1) 

where 32 is the batch number

No matter whether I reshape the data (127 sample, 100 tokens, word embedding length = 100) by:

```
testData = numpy.reshape(testData, (127,1,100,100)).astype(theano.config.floatX)
```

or I add a reshape layer before the convolution layer:

```
sequential.add(Reshape((1, 100, 100), input_shape=(100, 100))) 
```

Add or removing the sample number to the shape does not solve the problem either. 

If anyone can provide a working example, I would be extremely grateful. 

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [O] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [O] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [O] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

For reproducing the issue, try the following:

```
sequential = Sequential()
sequential.add(Reshape((1, 100, 100), input_shape=(100, 100)))
sequential.add(Convolution2D(10, 3, 3, border_mode='same'))
sequential.add(Activation("relu"))
test3dArray = numpy.random.random((127, 100,100))
testLabels = numpy.random.randint(2, size=127)
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
sequential.compile(loss='hinge', optimizer=sgd)
sequential.fit(test3dArray, testLabels, nb_epoch=1, batch_size=32)
```

**Comment by geovedi** [comment]
can this example help you?

```
X_train = np.random.random((128, 32, 100, 100))
y_train = np.random.randint(2, size=128)

model = Sequential()
model.add(Convolution2D(10, 3, 3, border_mode='same', input_shape=(32, 100, 100)))
model.add(Flatten())
model.add(Dense(1, activation='relu'))
model.compile(loss='hinge', optimizer='sgd')

model.fit(X_train, y_train, nb_epoch=1, batch_size=32)
```

**Comment by wailoktam** [comment]
Thanks for posting. I am looking for examples including either a reshape layer or a reshape of numpy array before feeding to a CNN. Your sample data can be fed to the CNN without any reshape as it is the 3 dimension image data typically expected. I am working on 2 dimension text data.
