### ISSUE TITLE
Comment mistake in merge function

### ISSUE THREAD

**Issue by hongkunyoo** [fchollet/keras#2714]
It's not a big problem, but some might have problems whether the 'join' merge mode is available or not.

https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1403
In line [1403](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1403), 
If I'm right, you should remove 'join' since it's no longer supported.

**Comment by fchollet** [comment]
I removed it.
