### ISSUE TITLE
Input Convolution1D?

### ISSUE THREAD

**Issue by mikekestemont** [fchollet/keras#272]
Hi all,

I wanted to check out the Convolution1D layer but wasn't sure what its input should look like: my data now has the shape (nb_samples, nb_channels, sequence_length) but Convolution1D seems to be expecting a 4D-tensor. How should I reshape in this case?

Thanks for your input!
Mike

**Comment by fchollet** [comment]
Convolution1D is just a wrapper around conv2d. It calls `T.nnet.conv.conv2d(X, (nb_filter, stack_size, 1, filter_length))`.

**Comment by mikekestemont** [comment]
Oh, OK, I see. That works for me, thx for the quick reply!

**Comment by valexandersaulys** [comment]
I don't quite understand how the wrapper is working. If its wrapping my input already, why do I need to reshape it? Shouldn't the wrapper be taking care of that work for me?
