### ISSUE TITLE
LSTM Text Input Question

### ISSUE THREAD

**Issue by brunoalano** [fchollet/keras#2720]
Hello,

I understand that LSTM layers expect a 3-dimensional input with the following shape: `(batch size, sequence length, features)`.

But for example, I have a sample text: "I love dogs and love cats". Then I can tokenize and transform it into numerical features, for example: `[5, 81, 192, 32, 81, 431]`. The sequence length is 6. But suppose that the biggest sentence length is 20, then I use the `pad_sequences` method to pad with the maximum length, and that become: `[0, 0, ..., 5, 81, 192, ..., 431]`.

So, what I'm doing now is something like that:

``` python
# Generate Sample Dataset (like a text input)
X_train = np.random.randint(55, size=(32, 50)) # (batch size, max sequence length), with `55` words
y_train = np.random.randint(100, size=(32, 70)) # (batch size, max sequence length), with `100` words

# Input Embedding
# ---------------
# Build a Sequential Model
input_embedding_model = Sequential()

# input_dim: maximum index integer on text
# output_dim: dimension of dense output
# input_length: since we are padding the sequence, it's constant
input_embedding_model.add(
    Embedding(input_dim=55, input_length=50, output_dim=128)
)
input_embedding_model.compile('rmsprop', 'mse')

# Output Embedding
# ----------------
# Build a Sequential Model
output_embedding_model = Sequential()

# input_dim: maximum index integer on text
# output_dim: dimension of dense output
# input_length: since we are padding the sequence, it's constant
output_embedding_model.add(
    Embedding(input_dim=100, input_length=70, output_dim=128)
)
output_embedding_model.compile('rmsprop', 'mse')
```

So, after that, I do this to transform into a 3D matrix:

``` python
# Convert X_train and y_train into 3d
X_train_fix = input_embedding_model.predict(X_train)
y_train_fix = output_embedding_model.predict(y_train)
```

Ok, but, how can I transform this into a matrix of shape (sequence length, features)? Should I copy this vector `sequence_length` times? Have some function to do that on numpy or Keras? What I'm doing is right?

**Comment by viksit** [comment]
@brunoalano See the code sample pointed to here: https://github.com/fchollet/keras/issues/2227

Also, read through the discussions at https://github.com/fchollet/keras/issues/853.

**Comment by brunoalano** [comment]
@viksit But what if I don't want to use Word Vectors?

**Comment by robinsloan** [comment]
I'm no Keras expert, but I think you might try this at the outset:

```
X_train = np.random.randint(55, size=(32, 50, 1))
```

As you say, the LSTM expects input of shape `(batch size, sequence length, features)` -- so your initial arrays need that `features` dimension, even though it's just one, and looks a little silly to have `[all] [those] [single] [features] [like] [this]`.

Again, not an expert. Give it a try, though!
