### ISSUE TITLE
I think there's an bug in serialization of advaced activations

### ISSUE THREAD

**Issue by seviyorm** [fchollet/keras#2722]
after training the layers with ELU(advaced activation), I tried to save the model using model.to_json()

but I got an error message containing "AttributeError: 'ELU' object has no attribute '__name__'"

I think model.to_json() method doesn't support for advanced activations

**Comment by joelthchao** [comment]
You probably need to update Keras. It seems to be fixed in this [commit](https://github.com/fchollet/keras/commit/a066cf8680372f107f4da35b1518998a851e02b7#diff-4ea1eab272323ecb1f250db1b8d83443L113).
