### ISSUE TITLE
how many neuron in LSTM hidden layer?

### ISSUE THREAD

**Issue by 450586509** [fchollet/keras#2735]
model = Sequential()
model.add(LSTM(32, input_shape=(10, 64)))

as for this LSTM , i think ,the input layer has 64 neuron,the output layer has 32 neuron. could you please tell me the number neuron of hidden layer.

thank you~

**Comment by carlthome** [comment]
You don't have a hidden layer?

**Comment by 450586509** [comment]
@carlthome thank you so much . I GOT IT. it's a single-layer network. and this 'single-layer' is the hidden layer that i am looking for.
