### ISSUE TITLE
Some issues about image generator

### ISSUE THREAD

**Issue by xuhuaren** [fchollet/keras#2740]
Hi, every one
  Recently, I processed large medical image datasets. Now, there are two issues.
1. I utilized generator because of big data, So how can I address the image preprocess function in Keras?
2. image preprocess may not suitable for 3D images as the error displayed affine registration could't work.
   Thanks!

**Comment by joelthchao** [comment]
1. You can inherit `ImageDataGenerator` to create your own generator. There are some useful util functions in [code](https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py) and you can define your own preprocessing routine.
2. `ImageDataGenerator` is designed to work with 2D images. Maybe you can slice your 3D image into 2D images or write your own generator to deal with it.

**Comment by xuhuaren** [comment]
thanks, I will write my custom generator.

**Comment by srikar2097** [comment]
@xuhuaren was this done? Can you share the code? thanks.

**Comment by yuimo** [comment]
3d image preprocessing is very intresting and essential for some appliacations such as medical images. and i'm wondering if keras provides this function, and it must be a great thing for most people
