### ISSUE TITLE
batch_dot has different behavior in different backend

### ISSUE THREAD

**Issue by joelthchao** [fchollet/keras#2742]
I use `K.batch_dot` to speedup my code, however, encounter different behaviors in different backends. Although the codes claim to perform same. In [theano_backend.py](https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L147):

``` python
if axes is None:
    # behaves like tf.batch_matmul as default
    axes = [x.ndim - 1, y.ndim - 2]
```

This experiment shows the difference.

``` python
# Theano: 0.8.2 / TensorFlow: 0.8.0
# Perform matmul on the last two axis
a = K.variable(np.random.rand(3, 4, 5, 6))
b = K.variable(np.random.rand(3, 4, 6, 7))
result = K.eval(K.batch_dot(a, b))
# Theano: result has shape (3, 4, 5, 4, 7)
# TensorFlow: result has shape(3, 4, 5, 7) (Expected)
```

Anyone can tell me how to do this in Theano?

**Comment by xingdi-eric-yuan** [comment]
looks like theano iterates over ONLY the 0th dimension as batch dimension, so you may need to reshape your a and b to merge the 0th and 1st dim, do T.batched_dot, then reshape the result back to the shape you want.

**Comment by joelthchao** [comment]
Thanks for reply! However, I encounter another [Theano issue](https://github.com/Theano/Theano/issues/4476)  after reshape. Any suggest workaround?
```
ValueError: some matrix has no unit stride
Apply node that caused the error: BatchedDot(Reshape{3}.0, InplaceDimShuffle{0,2,1}.0)
Toposort index: 230
Inputs types: [TensorType(float32, 3D), TensorType(float32, 3D)]
Inputs shapes: [(25, 128, 32), (25, 32, 288)]
Inputs strides: [(4, 3200, 100), (36864, 4, 128)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Reshape{3}(BatchedDot.0, MakeVector{dtype='int64'}.0)]]

... Backtrace ...
input_grads = node.op.grad(inputs, new_output_grads)
```

**Comment by xingdi-eric-yuan** [comment]
could you show me the code which encountered this problem? I suppose it's in [THIS](https://github.com/fchollet/keras/pull/2658)

**Comment by joelthchao** [comment]
The error is from gradient computing in theano and the error should come from the op `K.batch_dot`
```python
# x is 4 dim tensor (e.g. (batch, channel, row, col))
# W is 3 dim tensor (e.g. (nb_output, feature_dim, nb_filter))
xs = []
for i in range(output_row):
    for j in range(output_col):
        slice_row = slice(i * stride_row, i * stride_row + nb_row)
        slice_col = slice(j * stride_col, j * stride_col + nb_col)
        xs.append(K.reshape(x[:, :, slice_row, slice_col], (1, -1, feature_dim))) # this is for TH ordering (broken)
        # xs.append(K.reshape(x[:, slice_row, slice_col, :], (1, -1, feature_dim))) # this is for TF ordering (work well)
x_aggregate = K.concatenate(xs, axis=0)
output = K.batch_dot(x_aggregate, W)
```
I think the slicing operation results in `some matrix has no unit stride`

**Comment by xingdi-eric-yuan** [comment]
I briefly read the code and it seems to be correct, have you tried [THIS](https://github.com/Theano/Theano/pull/2949/files#diff-76b20384b894c01ec416325040ed8411R28) ?

**Comment by joelthchao** [comment]
> I briefly read the code and it seems to be correct, have you tried THIS ?

I haven't tried it. Actually, I am not familiar with theano, is it able to be done in Keras?

> btw, feature_dim = channel * self.nb_row * self.nb_col, right?
and nb_output = output_row * output_col

Exactly, it's for locally-connected layer.

**Comment by fchollet** [comment]
This should be fixed. I am fairly neutral as to whether we should normalize to the Theano behavior or the TensorFlow behavior, as long as both are consistent. Would you like to submit a PR?

**Comment by xingdi-eric-yuan** [comment]
@fchollet maybe we can add one more argument to `K.batch_dot`, like 
`def batch_dot(x, y, axes=None, batch_axes=[0])`?

**Comment by joelthchao** [comment]
@xingdi-eric-yuan Not sure if I do it right. Also it requires theano with version higher than `0.8.2`.
```python
x_aggregate = K.concatenate(xs, axis=0)
if K._backend == 'theano':
    from theano.tensor.extra_ops import cpu_contiguous
    x_aggregate = cpu_contiguous(x_aggregate)
output = K.batch_dot(x_aggregate, W)
```
Same error Q_Q

**Comment by xingdi-eric-yuan** [comment]
Hey @joelthchao , try the following two things:
1. do `cpu_contiguous` before concat, right after `K.reshape()`
2. try something like this to make sure `K.reshape()` works correctly 
```python
tmp = K.reshape(x[:, :, slice_row, slice_col], (-1, feature_dim))
tmp = K.expand_dims(tmp, 0)
xs.append(tmp)
...
```

**Comment by joelthchao** [comment]
@xingdi-eric-yuan Still, same error. Might need to prevent using of `batch_dot` on this case.

**Comment by hantek** [comment]
I think this is only related to Theano. While computing the gradients for T.batched_dot(), the theano code reshapes its input [HERE](https://github.com/Theano/Theano/blob/master/theano/tensor/blas.py#L2329-L2363), which causes the problem. That also explains why it works well in the forward pass.

**Comment by joelthchao** [comment]
@hantek Thanks for the answer, is it fixed in Theano now?

**Comment by hantek** [comment]
Not yet. It seems that it depends on different numpy versions. A quick and dirty way is to add `theano.tensor.cpu_contiguous(gz)` (or other Theano variables that are not CPU-continuous) in the proper if-clause, locally in your installation of theano.

**Comment by nameless-Chatoyant** [comment]
```
import numpy as np
from keras.layers import Input
```    
x = Input(shape=(1,500,))
    M = K.variable(np.ones([1,500,500]))
    res = K.batch_dot(x, M, axes=[1,2])
