### ISSUE TITLE
Implementing the LISTA Network for Sparse Reconstruction

### ISSUE THREAD

**Issue by PkuClosed** [fchollet/keras#2755]
Hi,

I am trying to implement the Learned Iterative Shrinkage and Thresholding Algorithm (LISTA) proposed in Gregor and LeCun 2010, "Learning Fast Approximations of Sparse Coding". LISTA aims to solve a sparse reconstruction problem using the network structure as shown in the figure.
![image](https://cloud.githubusercontent.com/assets/16568763/15381185/e88f08fc-1daf-11e6-8986-d4be0a1cad81.png)
Here W and S are to be learned from training data. Note that the matrix S at different "layers" should have the same parameters. My first thought is to use a Graph model with shared nodes. However, to define the shared node S, its second input (z2) should be defined first. But z2 is not defined until S is defined. Thus, defining S is problematic using this approach.

I am wondering if there is some way to work around the problem and allow the S in the two stages to have the same weights.

Thank you,
Chuyang

**Comment by EderSantana** [comment]
yeah, try the new functional api and just repeat the operations a couple of times
```python
for i in range(3):
    x = dec(x1)  # `e` and `S` operations
    x1 = merged([x, x1], "sum")  # sum
```

btw, doesn't that look a lot like a resnet?

**Comment by PkuClosed** [comment]
Thanks for the reply! Could you please tell me more about the dec() function? Where can I import it? Also, by "merged()", do you mean keras.layers.merge or is there a function named "merged" exactly?

The structure does look similar to a residual network because of the "add" node.

**Comment by PkuClosed** [comment]
Thanks for the reply! 

I believe the difference between LISTA and resnet is that Wx' (x' is the x in the figure) instead of the x1 in your code is added to x (this is the x in your code) at the end of each stage. Therefore, it seems to me that the loop should be
```python
x2 = Wx
x1 = x2
for i in range(3):
    x = dec(x1)  # `e` and `S` operations
    x1 = merged([x, x2], "sum")  # sum
```


By "merged" did you mean keras.layers.merge or is there a function named exactly "merged"? Also, I am curious how this code ensures that the same S is applied (i.e. S is a shared node and it has the same parameters at each layer).

**Comment by EderSantana** [comment]
I mean `keras.layers.merge`, sorry!

**Comment by PkuClosed** [comment]
@EderSantana Could you please tell me more about how S is ensured to have the same weights at different layers here? It seems to me that the loop does not explicitly force it. Thank you!

**Comment by EderSantana** [comment]
you define the `dec` layer before the inner loop, so the weights never change. the layer is just reapplied over and over. you are just reusing a layer which the new functional api allows you to do

**Comment by PkuClosed** [comment]
Thanks! It makes perfect sense!
