### ISSUE TITLE
fit_generator threw an exception.

### ISSUE THREAD

**Issue by dsy412610** [fchollet/keras#2756]
Hi,
    I used fit_generator in my code, but it throw an exception recently as following:
` Traceback (most recent call last):`
`File "model3.py", line 149, in <module>`
`    validation_data=(X_test, Y_test))`
`File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 651, in fit_generator`
`max_q_size=max_q_size)`
`  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1358, in fit_generator`
`    'or (x, y). Found: ' + str(generator_output))`
`Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None`
`Exception in thread Thread-1:`
`Traceback (most recent call last):`
`  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner`
`    self.run()`
`  File "/usr/lib/python2.7/threading.py", line 763, in run`
`    self.__target(*self.__args, **self.__kwargs)`
`  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 404, in`
`data_generator_task`
`    generator_output = next(generator)`
`  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 302, in next`
`    x = self.random_transform(x.astype('float32'))`
`  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 387, in `
`random_transform`
`    fill_mode=self.fill_mode, cval=self.cval)`
`  File "/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.py", line 106, in `
`apply_transform`
`    x = np.stack(channel_images, axis=0)`
`AttributeError: 'module' object has no attribute 'stack'`

    It seems that numpy has no attribute stack.  Is there any change in fit_generator? Why can’t I used that as normal? Thanks!

**Comment by joelthchao** [comment]
What is your numpy version? It should be at least 1.10.0.

**Comment by dsy412610** [comment]
Well, I used numpy version 1.8.2. But I dont't know why fit_generator worked normally before for I didn't update numpy.

**Comment by joelthchao** [comment]
Since the previous version of `ImageDataGenerator` doesn't need `np.stack`.

**Comment by dsy412610** [comment]
Thank you very much!
