### ISSUE TITLE
Any way to share Embedding or LSTM layers if input lengths vary?

### ISSUE THREAD

**Issue by phdowling** [fchollet/keras#2765]
I'm trying to build a character-level model with separate inputs, but I would like to share their Embedding layer and the first LSTM layer. However, my model currently won't compile since my inputs have different lengths (think story vs. question in bAbI).
```python
shared_char_embed = Embedding(
    input_dim=self.num_inputs,
    output_dim=self.char_embedding_size,
    mask_zero=True,
    name="char-embed"
)
shared_word_embed_lstm = LSTM(
    self.input_embed_size,
    return_sequences=False,
    name="shared-lstm"
)
story_embed_input = Input((self.story_maxlen,), dtype='int32', name='story_embed')
story_embed = shared_char_embed(story_embed_input)
story_embed = Dropout(0.3)(story_embed)
story_embed = shared_word_embed_lstm(story_embed)
story_embed = Dropout(0.3)(story_embed)
# LSTM for story encoding
story_embed = LSTM(self.input_embed_size, return_sequences=False, name="story_lstm")(story_embed)
story_embed = Dropout(0.3)(story_embed)
# low-level embed is shared
question_embed_input = Input((self.question_maxlen,), dtype='int32', name='question_embed')
question_embed = shared_char_embed(question_embed_input)
question_embed = Dropout(0.3)(question_embed)
question_embed = shared_word_embed_lstm(question_embed)
question_embed = Dropout(0.3)(question_embed)
# another LSTM for question-specific encoding
question_embed = LSTM(self.input_embed_size, return_sequences=False, name="question_lstm")(question_embed)
question_embed = Dropout(0.3)(question_embed)
``` 
Problem no. 1 is of course that I'm not specifying `input_length` in the embedding layer **EDIT**: nevermind, this part was more likely because of the return_sequences flag
```
Exception: Input 0 is incompatible with layer story_lstm: expected ndim=3, found ndim=2
```
However, I don't see a good way to specify it since my inputs have different lengths.I tried using TimeDistributed, which enables me to share weights for the char embeddings if I use a Dense layer instead, but that doesn't have a mask_zero option. **EDIT**: I got this to work just using a plain embedding layer. The LSTM problem still persists though.

This also does not help with the LSTM varying length problem. Is it somehow be possible to symbolically share the LSTM weights in different nodes but have them have different input_lengths?

I guess a workaround would be to simply force them to the same length, but this is not ideal since my second input tends to be quite a bit shorter than the first input.

Any ideas?

**Comment by phdowling** [comment]
Update: this seems to work with Conv2d Layers: http://keras.io/getting-started/functional-api-guide/#the-concept-of-layer-node

```
a = Input(shape=(3, 32, 32))
b = Input(shape=(3, 64, 64))

conv = Convolution2D(16, 3, 3, border_mode='same')
conved_a = conv(a)

# only one input so far, the following will work:
assert conv.input_shape == (None, 3, 32, 32)

conved_b = conv(b)
# now the `.input_shape` property wouldn't work, but this does:
assert conv.get_input_shape_at(0) == (None, 3, 32, 32)
assert conv.get_input_shape_at(1) == (None, 3, 64, 64)
```
Can this also be implemented with LSTM layers? It would be useful to have them adapt their `input_length` according to the previous input instead of fixing it at first instantiation.

**Comment by xingdi-eric-yuan** [comment]
try set [THIS](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L772) to be None, and the time dimension of your input shape to be None as well

**Comment by phdowling** [comment]
Thanks, but I'm not sure I follow - How would I do this, and wouldn't it break the layer to simply change these after the fact?

**Comment by xingdi-eric-yuan** [comment]
I'm pretty sure it doesn't break things, and actually this is what I'm using right now, similar use case, story sentences and queries share the encoder, and the length of sentences are different in each batch.
Just make a new class which derives from keras LSTM...

**Comment by phdowling** [comment]
I finally implemented it like this, and it seems to work - still too early to say whether the whole thing learns correctly though: 

```
class ShareableGRU(GRU):
    def __init__(self, *args, **kwargs):
        super(ShareableGRU, self).__init__(*args, **kwargs)

    def __call__(self, *args, **kwargs):
        res = super(ShareableGRU, self).__call__(*args, **kwargs)
        self.input_spec = [InputSpec(shape=(self.get_input_shape_at(0)[0], None, self.get_input_shape_at(0)[2]))]
        return res

```

**Comment by xingdi-eric-yuan** [comment]
Seems to be correct, if there's any updates, let me know, thanks!

**Comment by MikulasZelinka** [comment]
Hello, what is the current state of this issue? I'm having trouble figuring out this exact thing (**how to share weights of two Embedding/LSTM layers with different input sizes**).

Could anyone please post a working code example if there is one (ideally using the most recent version of Keras)?

Also, is it possible to get this to work with TensorFlow backend? Sadly, the links inside the posts (one of which said it wasn't possible) seem to lead to different (not relevant) parts of the code.

Any help would be greatly appreciated!
