### ISSUE TITLE
theano.gof.fg.MissingInputError: (......(keras_learning_phase) When i  use the Dropout layer

### ISSUE THREAD

**Issue by alyato** [fchollet/keras#2771]
hi guys. I meet the question when i  load the predict function belongs to the graph
![wrong](https://cloud.githubusercontent.com/assets/6815071/15446368/241adcfc-1edc-11e6-9156-58fde97e7ebe.png)
I know someone has issued this question  But i still don't how to use K.learning_phase()

> https://github.com/fchollet/keras/issues/2417

> https://github.com/fchollet/keras/issues/2430

And if i remove the Dropout layer ,it work well.

thanks

**Comment by bottydim** [comment]
Hi @alyato, how did you fix your problem, I am running into the same issue after a GRU followed by dropout

**Comment by alyato** [comment]
when i call the model.predict ,it show me this error.
>
> SO i load my model and recompile it. Then i call model.predict,it works

If you want to get the output after very layer and use the dropout layer,
you have to set the keras_learning_phase value 0/1.


2016-05-25 4:59 GMT-06:00 Botty Dimanov <notifications@github.com>:

**Comment by franciscovargas** [comment]
how do you recompile it ??? compile with the same arguments ? it does not sabotage the model being trained?

**Comment by alyato** [comment]
@franciscovargas  first,you can save your model to yaml or json  and save the weight to h5 format after calling the fit function.
 then you need  call the function model_from_json or model_from_yaml and load your weight when you want to call the predict function

**Comment by franciscovargas** [comment]
thanks so much !
