### ISSUE TITLE
Join mode is deleted, how can I call lambda on output of two nodes?

### ISSUE THREAD

**Issue by rudaoshi** [fchollet/keras#2773]
I've found that the join mode is deleted in Merge and Lambda. How can I perform a lambda function to the outputs of two nodes, when they cannot be concat?

**Comment by fchollet** [comment]
Just use `Lambda`. There are a couple examples in the docs, in particular in the "functional API guide".

**Comment by rudaoshi** [comment]
No example about Lambda found in API Guide. 

Do you mean that I can just apply the layer with a list of  multiple input ? I tried but got following error: 

Exception: You tried to call layer "lambda_1". This layer has no information about its expected input shape, and thus cannot be built. You can build it manually via: `layer.build(batch_input_shape)`

**Comment by joelthchao** [comment]
> No example about Lambda found in API Guide.

[THIS](http://keras.io/layers/core/#lambda) has example might help you.

> Do you mean that I can just apply the layer with a list of multiple input ? I tried but got following error:

Merge layer is better to apply on a list of input, [Doc](http://keras.io/layers/core/#merge). Also, please don't provide only error message, complete codes are necessary for us to help you.

**Comment by rudaoshi** [comment]
Thank you for your answer. 

I'm reading the document carefully, including two examples you provided. 

However, the example of merge merge two input with concat mode. What if the two input cannot be concat or by any simple operation provided by merge? 

In the previous edition, I can use "join" mode to merge multiple inputs into a dict and apply a complex function in lambda. But since the join mode is deleted, I do not know how to do the same thing with an elegant way.

Now, I use arguments of Lambda to pass multiple inputs. But that is not elegant, since all inputs are not processed in the same manner. I wonder why the join mode is deleted.

Example code:

```
A = ... # output of a sequence 
B = ... # output of a sequence 

def a_complex_function_1(A, B):
      # do some complex things, such as A[B] + B[A]
      pass 

C = Lambda(a_complex_function_1, output_shape=(N,))([A,B])  # failed with previous error 
```
I'm doing this:

```
def a_complex_function_2(A, B = None):
      # do some complex things, such as A[B] + B[A]
      pass 

C = Lambda(a_complex_function_2, arguments={"B":B}, output_shape=(N,))(A) 
```

This seems run smoothly, but I think the trainable parameter chain may be broken for B passing as arguments.

**Comment by rudaoshi** [comment]
OK, I think I miss the option of mode can be a function. I will try this. Thank you.
