### ISSUE TITLE
Adding Inputs to a hidden layer

### ISSUE THREAD

**Issue by lixiao89** [fchollet/keras#2774]
Hi, is there a way to add inputs to a hidden layer and learn the corresponding weights, something like

                  input_1 --> hidden_layer --> output
                                    ^
                                 input_2

Thanks

**Comment by phdowling** [comment]
You basically want to merge two inputs, right? Try something like this:
```python
input_1 = Input(input_shape)
input_2 = Input(input_shape)

merge = merge([input_1, input_2], mode="concat")  # could also to "sum", "dot", etc.
hidden = Dense(hidden_dims, activation="softmax")(merge)
```

**Comment by lixiao89** [comment]
I think that's precisely what I'm looking for. Thanks very much
