### ISSUE TITLE
Scalar Input()

### ISSUE THREAD

**Issue by allentran** [fchollet/keras#2776]
Is it possible to have a scalar Input() instance?

I can use `K.backend.placeholder(ndim=0)` to get output from `theano.function()` correctly but cannot use the input defined by `K.backend.placeholder(ndim=0)` as it is not a Keras Tensor.

Is there a way to generate a scalar Input(), either directly or by converting the backend Tensor object?

**Comment by joelthchao** [comment]
Is this what you want? [Input](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L974)
Docstring below might help you.

**Comment by allentran** [comment]
`Input()` won't work since it automatically makes a tuple, i.e `ndim>0`
See llne 1022, `batch_shape = (None,) + tuple(shape)`

**Comment by altaetran** [comment]
Any updates on this?

**Comment by farizrahman4u** [comment]
```
a = Input(batch_shape=(1,))
```

**Comment by altaetran** [comment]
Thanks!

**Comment by ROZBEH** [comment]
How to you give the input in the training phase then?
Because once you want to train the model based on the scalar value it throws the following error.
`'int' object has no attribute 'shape'`

**Comment by allentran** [comment]
I still had trouble with @farizrahman4u 's solution.

Here's the hacky solution I just came up with (assuming you're going to use the `scalar_input` in some custom or lambda layer.

Just create a vector input and get the scalar via indexing in your custom layer.  Example use case: you want to supply an input with each batch that tells you the max length of the sequence.  This gets around a lot of trickiness with variable length sequences when you reshape a lot.

```
vector_input = Input(shape(1, ))
```
Later on when you need this as a scalar, just access the first position via
```
max_idx = vector_input[0, 0]
relevant_sequence = x[:, :max_idx]
```

**Comment by bionicles** [comment]
this seems insane

**Comment by Hongtao-Niro** [comment]
Any good solution to this? I'm surprised that simple thing like this is not well supported in Keras.
