### ISSUE TITLE
Why convolution 1d filter number become the last dimension of output shape whereas convolution 2d filter number becomes the first dimension of output shape?

### ISSUE THREAD

**Issue by wailoktam** [fchollet/keras#2782]
Hi, in the document　about convolution layers, I find:

```
model.add(Convolution1D(64, 3, border_mode='same', input_shape=(10, 32)))
# now model.output_shape == (None, 10, 64)
```

So the number of filters (64) is the value of the second dimension  of the output, excluding the number of samples (None)

　model.add(Convolution2D(64, 3, 3, border_mode='same', input_shape=(3, 256, 256)))
　# now model.output_shape == (None, 64, 256, 256)

Now the number of filters (64) is the value of the first dimension of the output, excluding the number of samples(None) again. 

Can anyone explain why? Many thanks.

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by joelthchao** [comment]
It's a convention for dimension ordering. You can specify it by argument `dim_ordering='tf' or 'th'`.
If you use TensorFlow (tf), you will see 4D data in `(batch, height, width, channel)` while Theano (th) prefer `(batch, channel, height, width)`.
