### ISSUE TITLE
How can I get the half samples of the output after lstm layer?

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#2783]
![qq 20160523221842](https://cloud.githubusercontent.com/assets/13865086/15473789/5e5278a8-2134-11e6-9459-13841df07000.png)
As above shown, the representations of 4 samples are the output of lstm layer, now I want to get the half samples of the output to merge with the new input (`input2`). I want to implement this in one model, not split to two steps like [visualizing the output of intermediate layer](http://keras.io/getting-started/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer) 
Any opinions would be appreciated!

**Comment by joelthchao** [comment]
Use lambda layer:
```python
input = Input((hidden_dim,))
output = Lambda(lambda x: x[:2, :], output_shape=lambda x: (2, x[1]))(input)
```
