### ISSUE TITLE
verbose=2 in fit_generator

### ISSUE THREAD

**Issue by MartinThoma** [fchollet/keras#2784]
Looking at https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1226 (fit_generator), I wonder what `verbose=2` is good for. Could this probably be explained in the documentation? (I guess it is a real superset for the output of `verbose=1`?)

Also: Why is the verbosity not passed here: https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1418?

(I was trying to figure out why the `ProgbarLogger` is not showing up, although I have `verbose=2`)

**Comment by ruggeri** [comment]
This issue still exists. Looks like `verbose=2` is not really a thing for `fit_generator`? I was confused when I didn't see the progress bar.

If you like I can submit a patch which asserts that verbose is zero or one. Is that desirable?

Thanks!
