### ISSUE TITLE
An error when saving model

### ISSUE THREAD

**Issue by akmahaja** [fchollet/keras#2790]
When I am using the functional API to create the model and try to save it using the following line, It gives me the following error saying:

  File "trainer.py", line 48, in create_training_features
  json_string = model.to_json()
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2368, in to_json
  config = self.get_config()
  File "/usr/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2163, in get_config
  new_node_index = node_conversion_map[node_key]
  KeyError: 'input_1_ib-0'

Here is the gist: https://gist.github.com/akmahaja/ef406b2087b5c50befc1a479989b1921

**Comment by fchollet** [comment]
The error message should be more helpful in that case, but the issue is that your model is not well-formed. You are setting as input `[input1, input2]`, but your input only relies on `input2`. Which is why the model (which is being built top-bottom) is not registering `input1` and complains about it later.

**Comment by akmahaja** [comment]
This works fine, if I do not save/load the model and directly use the trained model to predict. Any suggested workaround for this?

**Comment by fchollet** [comment]
> Any suggested workaround for this?

Properly defining the underlying model. In your case half of your model is simply never called. This doesn't prevent the other half from training, but since the model topology is broken, you will have errors when saving / loading.

**Comment by yHalumi** [comment]
Coming back to this old thread as I came across this in a scenario I am currently working on - 
Say I am adding an input to be used only by the loss function (for allowing weighting the loss pixel-wise, for which as much as I understand the 1-d input weights can't do) - currently this model will break during the save of the model.
Is there a nice way to do this?
Currently I stand one of two 'clean' choices - change the default save_model callback to save only the internal function (not so convenient for continuing training), or add a parallel small network to compute the loss (and then discard it at prediction time).
Either way, unless I miss something about how to work right, it seems lacking a bit from the perspective of saving and then loading 'trainable' model.

**Comment by harikrishnavydana** [comment]
@yHalumi did u find a way to do it i exactly has the same issue passing a variable to loss function and saving the model

**Comment by yHalumi** [comment]
@harikrishnavydana  - well, I didn't find a clean way to do it, but what I eventually did was to encode the information I did to the y_true tensor, and then have the loss function being a special one which know to extract the real labels from the rest of the information, and then perform in the loss function all of the rest of it.
Other than that, it made go native TF (:
