### ISSUE TITLE
weight sharing in keras models

### ISSUE THREAD

**Issue by abayowbo** [fchollet/keras#2794]
Is there a way to share weights between two models in keras 1, where model1 is trained with single gradient update over one batch of samples (train_on_batch) and  model2 is updated with model1 weights. 
In keras 0.3, this is possible by using a single model and setting the trainable attributes of the layers to false for model2 compilation. 

I tried creating identical models and then use model2.set_weights(model1.get_weights()) on each iteration, but this leads to out of memory error after a few iterations with tensorflow.

**Comment by dansbecker** [comment]
Check out the part about shared layers in [the functional API guid](http://keras.io/getting-started/functional-api-guide/) section of the docs.

**Comment by abayowbo** [comment]
With shared layers/models, Is it possible to freeze an instance of a layer? 
e.g layer  is trainable in model1 and not trainable in model2? This will be closer to what I'm looking for. Thanks.

**Comment by geovedi** [comment]
> Is it possible to freeze an instance of a layer?

Something like [this](https://github.com/fchollet/keras/blob/610ccba9f5c030e6106520359c27dc9c226670d7/examples/mnist_transfer_cnn.py#L117)?

**Comment by abayowbo** [comment]
Somewhat similar, but not exactly. The mnist transfer example recompiles the model after freezing layers. Here I want to use train_on_batch and need model1 layers to be trainable and the layers in model2 that corresponds to model1 non-trainable without the need to recompile the model at each iteration.

**Comment by abayowbo** [comment]
I have a working solution by creating two identical models and then updating model2 weights with model1 weights at each train_on_batch iteration. 

The out of memory issue with the set_weights() function is fixed by modifying the tensorflow_backend "batch_set_value" function like so:

```python
def batch_set_value(tuples):
    '''Sets the values of many tensor variables at once.

    # Arguments
        tuples: a list of tuples `(tensor, value)`.
            `value` should be a Numpy array.
    '''
    if not hasattr(K, 'weights_placeholder'):
        K.weights_placeholder = tf.placeholder(tf.float32)
        
    if tuples:
         for x, value in tuples:
             K.get_session().run(x.assign(K.weights_placeholder), feed_dict={K.weights_placeholder: value})
```

**Comment by botcs** [comment]
@abayowbo 
If this is still an issue, I got an alternative probably more efficient solution:

```python
def generator_discriminator(generator, discriminator):
    joined_layers = generator.layers + discriminator.layers
    for layer in joined_layers:
        if layer in discriminator.layers:
            layer.trainable = False
    model = Sequential(layers=joined_layers)
    
    return model
```

Here originally, generator (model1) parameters are trained via the gradients of the discriminator (model2), however I don't want the discriminator layers to be updated in this model. (The discriminator model is trained separately).

**Comment by kirkscheper** [comment]
Hey all, has there been any developments in keras/tensorflow to do this in a more functional way without copying the weights?
