### ISSUE TITLE
Successful Example of Merge by Dot or Cos wanted

### ISSUE THREAD

**Issue by wailoktam** [fchollet/keras#2799]
Hi, 

I get the following warning:

theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 2 is not part of the computational graph needed to compute the outputs: <LAST LAYER>

no matter what I put in the last layer, as long as I do a merge by dot/cos.

It seems to be related to this issue: https://github.com/fchollet/keras/issues/1254

Sample codes as follows:

```
leftKerasModel = Sequential()
leftKerasModel.add(Reshape((1,100,100),  input_shape=(100, 100)))
leftKerasModel.add(Convolution2D(10, 3, 3, border_mode='same'))
leftKerasModel.add(Activation('relu'))
leftKerasModel.add(MaxPooling2D(pool_size=(2, 2)))

rightKerasModel = Sequential()
rightKerasModel.add(Reshape((1,100,100), input_shape=(100,100)))
rightKerasModel.add(Convolution2D(10, 3, 3, border_mode='same'))
rightKerasModel.add(Activation('relu'))
rightKerasModel.add(MaxPooling2D(pool_size=(2, 2)))

mergedKerasModel = Sequential()
merged = Merge([leftKerasModel, rightKerasModel], mode='cos', dot_axis=1)
mergedKerasModel.add(merged)
```

I would be extremely grateful if anyone can give me a successful example or a suggestion of solution/workaround.

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [O] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [O] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [O] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by joelthchao** [comment]
Following code can successfully create a model with latest Keras and theano backend
```python
leftKerasModel = Sequential()
leftKerasModel.add(Reshape((1,100,100),  input_shape=(100, 100)))
leftKerasModel.add(Convolution2D(10, 3, 3, border_mode='same'))
leftKerasModel.add(Activation('relu'))
leftKerasModel.add(MaxPooling2D(pool_size=(2, 2)))

rightKerasModel = Sequential()
rightKerasModel.add(Reshape((1,100,100), input_shape=(100,100)))
rightKerasModel.add(Convolution2D(10, 3, 3, border_mode='same'))
rightKerasModel.add(Activation('relu'))
rightKerasModel.add(MaxPooling2D(pool_size=(2, 2)))

mergedKerasModel = Sequential()
merged = Merge([leftKerasModel, rightKerasModel], mode='cos', dot_axes=1) # dot_axes
mergedKerasModel.add(merged)
mergedKerasModel.add(Activation('relu')) # add this line won't give me any error
```

**Comment by wailoktam** [comment]
Hi, Joel, Thanks a lot for following this closely. I copy and paste your code but still getting the same warning about the last layer:

theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 2 is not part of the computational graph needed to compute the outputs: activation_3_target.

During training and cross-validation, I always get "nan" for loss. 

Epoch 1/10
127/127 [==============================] - 50s - loss: nan     
Epoch 2/10
127/127 [==============================] - 50s - loss: nan

**Comment by joelthchao** [comment]
First, merge with `cos` mode has nan issue and was fixed recently, please make sure your Keras is after PR #2725.
Second, it can also be your data's problem. If it's a classification problem, using `softmax` as activation should be more appropriate.

**Comment by wailoktam** [comment]
Thanks for your reply. I notice that I can do without the nan and the warning about unused input by not using my own custom loss function:

    def custom_objective(y_true, y_pred):
        if (y_true == 1):
           result = theano.tensor.maximum(0.09 - y_pred, 0.)
       else:
          result = theano.tensor.maximum(0.09 + y_pred, 0.)
      return result

which is an implementation of the following:

L = max {0,m − cos(VQ, VA+) + cos(VQ, VA−)}

where m is 0.09,  VQ is the vector representing a question sentence, VA+ is the vector representing a sentence including the correct answer to the question and VA- is the vector representing a sentence not including the correct answer.  

Can anyone tell me what is wrong with my objective function? Many thanks in advance.

**Comment by ChristianThomae** [comment]
The Tensor(-Variable) in the comparison is used in a wrong way `if (y_true == 1)`.
```
>>> import theano.tensor as T
>>> example = T.matrix()
>>> example == 1
False
```
You want to use something like `K.switch(condition, thenValue, elseValue)`.

**Comment by jtaverni** [comment]
First of all great work on the library and documentation. I also find reading through the issues to be quite informative.

Would it be possible to provide a complete working script for Merge "cos"? There are a large number of issues that have been opened related to "cos" Merge and there are no complete examples.

Here's a script I've attempted to get working related to this example:
```python
from keras.layers import Input, Embedding, Merge, Flatten, recurrent, Dropout, RepeatVector, Dense, core, Reshape, Lambda, merge, Convolution2D, MaxPooling2D, Activation
from keras.models import Model
from keras.models import Sequential
import itertools
import numpy as np

a = np.asarray(np.random.randint(2, size=(5, 100, 100)), dtype='int32')
b = np.asarray(np.random.randint(2, size=(5, 100, 100)), dtype='int32')
y = np.asarray(np.random.rand(5))

leftKerasModel = Sequential()
leftKerasModel.add(Reshape((1,100,100),  input_shape=(100, 100)))
leftKerasModel.add(Convolution2D(10, 3, 3, border_mode='same'))
leftKerasModel.add(Activation('relu'))
leftKerasModel.add(MaxPooling2D(pool_size=(2, 2)))

rightKerasModel = Sequential()
rightKerasModel.add(Reshape((1,100,100), input_shape=(100,100)))
rightKerasModel.add(Convolution2D(10, 3, 3, border_mode='same'))
rightKerasModel.add(Activation('relu'))
rightKerasModel.add(MaxPooling2D(pool_size=(2, 2)))

mergedKerasModel = Sequential()
merged = Merge([leftKerasModel, rightKerasModel], mode='cos', dot_axes=1) # dot_axes
mergedKerasModel.add(merged)
mergedKerasModel.add(Activation('relu')) # add this line won't give me any error
mergedKerasModel.compile(optimizer='rmsprop', loss='cosine_proximity', metrics=['accuracy'])
mergedKerasModel.fit([a, b], y, nb_epoch=100, verbose=1)
```
This gives me the following stacktrace:
```
Using Theano backend.
Using gpu device 0: GRID K520 (CNMeM is disabled, CuDNN not available)
Epoch 1/1
Traceback (most recent call last):
  ...
  File "../2799.py", line 36, in <module>
    mergedKerasModel.fit([a, b], y, nb_epoch=1, verbose=1)
  File "keras/models.py", line 413, in fit
    sample_weight=sample_weight)
  File "keras/engine/training.py", line 1082, in fit
    callback_metrics=callback_metrics)
  File "keras/engine/training.py", line 801, in _fit_loop
    outs = f(ins_batch)
  File "keras/backend/theano_backend.py", line 531, in __call__
    return self.function(*inputs)
  File "theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[4] == 50, but the output's size on that axis is 5.
Apply node that caused the error: GpuElemwise{mul,no_inplace}(GpuElemwise{Sqrt}[(0, 0)].0, GpuElemwise{Sqrt}[(0, 0)].0)
Toposort index: 180
Inputs types: [CudaNdarrayType(float32, (True, True, True, True, False, True)), CudaNdarrayType(float32, (False, True, False, False, False, True))]
Inputs shapes: [(1, 1, 1, 1, 5, 1), (5, 1, 50, 50, 50, 1)]
Inputs strides: [(0, 0, 0, 0, 1, 0), (125000, 0, 2500, 50, 1, 0)]
Inputs values: [CudaNdarray([[[[[[ 0.3443177 ]
     [ 0.06990821]
     [ 0.30637595]
     [ 0.11739245]
     [ 0.65022004]]]]]]), 'not shown']
Outputs clients: [[GpuElemwise{Composite{((i0 * i1 * i2) / i3)},no_inplace}(CudaNdarrayConstant{[[[[[[ 0.5]]]]]]}, GpuDimShuffle{x,x,x,x,0,1}.0, GpuElemwise{Composite{(i0 + Abs(i0))},no_inplace}.0, GpuElemwise{mul,no_inplace}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

Any thoughts on what's going wrong and/or a complete script that works?
