### ISSUE TITLE
Visualizing image summaries from intermediate layers using Tensorboard

### ISSUE THREAD

**Issue by hj1210** [fchollet/keras#2805]
Is there a way to use keras to visualize image summaries using tensorboard? The tensorboard callback currently doesn't seem to support them. If there is no existing functionality, can someone give an example of implementing a separate callback for this (or any other suitable way to achieve this)?

**Comment by algoterranean** [comment]
Recently ran across this issue.

The `TensorBoard` callback creates a `self.merged` layer with nodes comprised of the histograms and images, but it only attempts to write this summary info if `model.validation_data` is defined. If you are using `fit_generator` with a generator for the validation data, `validation_data` is set to None, and therefore the images and histograms are never written.

In addition, the code that generates the merged layer looks like it needs to be updated... I'm getting all kinds of invalid size errors related to the image nodes.

At a minimum this should be documented, and certainly the class could use some improvements.
