### ISSUE TITLE
"mem" and "gpu" weights are not transferable

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#2809]
Saving LSTM weights for a model trained in "mem" optimized mode and then trying to load them in a rebuild of the same model but in "gpu" optimized mode yields the following error.

```Layer #6 (named "r1a" in the current model) was found to correspond to layer r1a in the save file. However the new layer r1a expects 3 weights, but the saved weights have 9 elements.```

I can see why it's the case and why patching it would be a bit of a hassle but it's rather inconvenient. 

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
That's by design (or rather, necessity) and there are no plans to fix it. "Fixing" it can only done in a way that would deteriorate runtime performance (weight matrix concatenation).

**Comment by lemuriandezapada** [comment]
Is runtime performance during weight loading/saving a critical aspect?
