### ISSUE TITLE
(Solved)Exception: Input 0 is incompatible with layer dense_2: expected dtype=float32, found dtype=float64

### ISSUE THREAD

**Issue by kevinmartinmauro** [fchollet/keras#2815]
Just want to put this here for others who may be googling

I ran into significant trouble trying to add a Dense layer after an LSTM. Turns out I was selecting my dimensions from a numpy array instead of a list. Once I converted my numNeurons numpy array to a list I was able to add the model correctly.

**Comment by danielhers** [comment]
Hi @kevinmartinmauro,
I got this exception after adding a Dropout layer, but I don't think I'm selecting my dimensions from a numpy array. Could you perhaps share more details about the solution?
Thanks

**Comment by kevinmartinmauro** [comment]
Did you make sure your dropout values are less than one?

Do the dtype values in the issue title (float32, float64) match the ones you're seeing? Otherwise google the exact values + keras + python

**Comment by danielhers** [comment]
My dropout parameters are between zero and one, yes. And I'm getting this
exact message.

**Comment by danielhers** [comment]
So regarding the dropout parameter, I got it from `argparser` and apparently it was casting it to `float64` somehow, but when I tried to cast it to `float32` it didn't help. Now I thought I might as well also tried just converting it to a simple `float`, and this time it seemed to work. Yay!
