### ISSUE TITLE
Neural network illustrations

### ISSUE THREAD

**Issue by pmcao** [fchollet/keras#282]
It'd be nice if we have illustration for each type of network in the documentation (http://keras.io/layers/recurrent/)
I could help with that.

**Comment by vzhong** [comment]
I'm not sure what you mean by illustration. Do you mean like [this](https://github.com/torch/nngraph)?

**Comment by fchollet** [comment]
Might be illustrations like [this one](http://deeplearning.net/tutorial/_images/lstm_memorycell.png).

Could you show us some examples of what you have in mind? Concretely, what files do you want to add to the doc?

**Comment by fchollet** [comment]
Closing for lack of follow-up.
