### ISSUE TITLE
I have trained the weights, how to get the output value of the specific layer.

### ISSUE THREAD

**Issue by chernyaxon** [fchollet/keras#2832]
I have trained the weights, how to get the output value of the specific layer. Keras function with the previous version of the  model.layers.pop()  function can be used, but the latest version of the  model.layers.pop() function is does not work。

**Comment by joelthchao** [comment]
Please reference to [FAQ](http://keras.io/getting-started/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer).
