### ISSUE TITLE
Keras constraints like UnitNorm

### ISSUE THREAD

**Issue by gravity1989** [fchollet/keras#2835]
Hi,

I have a use case where I don't want a constraint like MaxNorm, UnitNorm to be applied at the end of every batch update, but only after an interval of batch updates. Is there some way in which I can use the constraint according to my need?

Thanks,
Rahul.V.

**Comment by sallamander** [comment]
Can you somehow fit from a generator and then just combine the interval of batch updates all into one batch? Do you have some code or a gist to look at?

**Comment by NasenSpray** [comment]
You could use a wrapper that makes constraints togglable, for example (untested):

```
import keras.constraints
import keras.backend as K

class ToggleConstraint(keras.constraints.Constraint):
    def __init__(self, constraint):
        self._active = K.variable(1) # 1 = active, 0 = inactive
        self.constr = keras.constraints.get(constraint)
    
    @property
    def active(self):
        return K.get_value(self._active)
    
    @active.setter
    def active(self, value):
        if value:
            K.set_value(self._active, 1)
        else:
            K.set_value(self._active, 0)
    
    def __call__(self, p):
        # apply constraint when active
        return K.switch(self._active, self.constr(p), p)
```

**Comment by gravity1989** [comment]
Hi @NasenSpray , thanks for the reply.

What is K.switch? What does it do?  Unable to understand how the call method is able to toggle?

Thanks,
Rahul.V.
