### ISSUE TITLE
Bidirectional LSTM

### ISSUE THREAD

**Issue by donkang75** [fchollet/keras#284]
Is there any plan to implement bidirectional LSTM to recurrent.py?

**Comment by fchollet** [comment]
You could take a look at: https://github.com/hycis/bidirectional_RNN

**Comment by makagan** [comment]
I was also able to get BDRNN's without creating a new type of layer by adding the option to return sequences in reverse time order from the recurrent layer.  If the user then reverses the input data, this effectively trains the network in backwards time, but returns the data in the same time-ordering as a forward RNN.  This allows users to easily concatenated with a merge layer.

**Comment by dakshvar22** [comment]
@makagan Can you explain your approach a bit more? Or can you put some code to explain it?

**Comment by miradel51** [comment]
How can I use the bi-LSTM for text classification?

**Comment by vinayakumarr** [comment]
bil-lstm example is not working #3698
