### ISSUE TITLE
 TypeError: 'tuple' object is not callable when using PReLU

### ISSUE THREAD

**Issue by pfrcks** [fchollet/keras#2844]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Upon executing the following piece of code:

`model = Sequential()`

`model.add(Dense(512, input_shape=(43,), init='glorot_uniform'))`

`model.add(PReLU((512,)))`

I get the following error

TypeError: 'tuple' object is not callable

**Comment by joelthchao** [comment]
Don't know why`(512,)` in the arguments, just remove it.
Please make good use of document/code and read the definition first.
`keras.layers.advanced_activations.PReLU(init='zero', weights=None)`
