### ISSUE TITLE
Special Delimiters for zero-padded sequences

### ISSUE THREAD

**Issue by GelliFrancesco** [fchollet/keras#2848]
I read the threads about sequence padding and I still have a doubt. In [#85](https://github.com/fchollet/keras/issues/85), fchollet suggested either to pad with zeros or to feed one sequence per time (batchsize=1). 

There is still a doubt I didn't sort it out yet: in case I choose to pad with zeros, is it necessary to delimit my sequences with special BEGIN and END elements, or can the model automatically understand when to stop considering zeros?

**Comment by jsweg** [comment]
No need for BEGIN and END elements.  However, I typically use a padding value that is not in my data.  For example, if you are using text with characters a-z, I will assign the values 1-26 to a-z and reserve 0 for no data.
