### ISSUE TITLE
Early stop when val_acc has reached a value

### ISSUE THREAD

**Issue by SamChou19815** [fchollet/keras#2866]
Can we stop earlier when keras detects that val_acc has reached a satisfactory value?

**Comment by joelthchao** [comment]
Please browse the document first. [Early stop callback](http://keras.io/callbacks/#earlystopping)

**Comment by SamChou19815** [comment]
@joelthchao Well, I mean: for example, I think 90% is a good val_acc. 
The log may look something like this;
Epoch 12, val_acc = 75%
Epoch 13, val_acc = 70%
Epoch 14, val_acc = 60%
Epoch 15, val_acc = 70%
Epoch 16, val_acc = 90%
Epoch 17, val_acc = 74%
Epoch 18, val_acc = 73%
Epoch 19, val_acc = 73%
Epoch 20, val_acc = 73%
Epoch 21, val_acc = 73%

Now, from the document, I know it is easy to use the patience argument to let it stop when the value is 73%. However, I want to let it stop when it reached 90%. Is it possible for me to implement it without changing the source code of keras package?
