### ISSUE TITLE
why tensorflow backend is 4x slower than theano when i training a word vector level lstm.

### ISSUE THREAD

**Issue by yanyuxiaoxiao** [fchollet/keras#2869]
Same comments say that tensorflow backend is slower than theano when training lstm.I meet the same question. I want to know why this happen? @fchollet

**Comment by talpay** [comment]
Are you using TF 0.8+? The main reason that TF is sometimes slower than theano is that it is newer. It's currently much faster than after release but there's still room for optimization. This takes time, though.

**Comment by yanyuxiaoxiao** [comment]
@talpay Yes, the latest version. Interesting, hope the time will be  short.

**Comment by jonilaserson** [comment]
Also experiencing extreme slowness on TF side.
