### ISSUE TITLE
pad_sequences always truncates the end of the sequence.

### ISSUE THREAD

**Issue by wxs** [fchollet/keras#287]
I believe it makes more sense when padding is set to "pre" that the beginning of the sequence is truncated when it's longer than maxlen. Right now as you reduce maxlen you cut padding characters off the beginning of the sequence until you hit the sequence length and then start cutting characters off the *end* of the sequence. I would think that this should at least be an option in `pad_sequences`. Thoughts?

**Comment by fchollet** [comment]
I see no issue with having this as an option. It's unclear to me why this would be any better than end-truncating, though...

**Comment by wxs** [comment]
I guess it depends on the application. If you think of the label of coming immediately "after" the sequence, which will be true for many sequences types, then you want to truncate the beginning of the sequence, not the end, so that the data that's adjacent to the label in time gets to be used as part of the prediction.

Say I'm trying to do a fin-tech algorithm that looks at a bunch of time-varying financial metrics for a company and tries to predict an acquisition event. If I have a year's worth of data before each acquisition, and then I'm truncating the sequence to 3 weeks, it seems pretty clear that the 3 weeks of data immediately before the acquisition will be a better predictor of the event than the 3 weeks of data from a year earlier.

(I made this example up, but hopefully it gets the intuition across of why I think pre-truncation is better)

I can put up a PR. It's simple.

**Comment by wxs** [comment]
(OK I put up a PR at #297)

**Comment by fchollet** [comment]
Makes sense.

**Comment by wxs** [comment]
Fixed, thanks.
