### ISSUE TITLE
How to stack LSTMs hierarchically?

### ISSUE THREAD

**Issue by siavash9000** [fchollet/keras#2870]
Hello,

I would like to create a sequence of word embeddings on character level by the usage of LSTMs and then feed this embeddings into another LSTM. 

Take the String 'I want to create an embedding' as example. I want first generate a seqeuence of tokens 
['I', 'want', 'to', 'create', 'an', 'embedding'], then a sequence of sequences
[ ['I'], ['w','a','n','t'], ['t','o'], ['c','r','e','a','t','e'], ['a','n'], ['e','m','b','e','d','d','i','n','g']]
Then I want to create with a LSTM a sequence of vectors 
[vector_i, vector_want, vector_to, vector_create, vector_an, vector_embedding]
by feeding each word character for character into a LSTM.
Any ideas how to implement this in keras? My problem is that I dont know how to create a sequence from sequences  of sequences. I thought about using the Reshape Layer, but skipped this since reshaping at batch level is not allowed.

Thanks,
Siavash

**Comment by phdowling** [comment]
I've though about this type of thing before, and I think it should be possible through reshaping your input to the right shape and then using something like this:
```python
word_inputs = Input((max_num_word, max_chars_per_word))
char_embeddings = TimeDistributed(Embedding(..))(word_inputs)  # not sure how to structure the embeddings
char_lstms = TimeDistributed(LSTM(...))(char_embeddings)
word_level_lstm = LSTM(...)(char_lstms)
...
```

I never ended up trying this though, let me know if you're able to make this work!

**Comment by carlthome** [comment]
Looks cool!

**Comment by siavash9000** [comment]
Thanks for the input! I created a model on the reuters data set and published on github:[link](https://github.com/siavash9000/mixed_word_embedding/blob/master/mixed_embeddings_reuters.py)

On CPU: With the (default) `option consume_less='cpu'` a ValueError is thrown at runtime: 
`ValueError: total size of new array must be unchanged` caused by a reshaping in `time_distributed_dense` in `recurrent.py`.

On CPU:  With the `option consume_less='gpu'` training starts, but is extremely slow. One epoch takes 10 minutes on a training set of only 100 samples.

On GPU: With the (default) `option consume_less='cpu'` throws the error:
`ValueError: GpuReshape: cannot reshape input of shape (640, 64) to shape (0, 1000, 64).` 

On GPU: With the `option consume_less='gpu'` throws the error: 
`RuntimeError: c_extract: Some CudaNdarray has dim 21 on broadcastable dimension 0`

Am I missing something or is this bug? The linked script uses only keras and numpy, the errors should therefore be easily reproducible.

**Comment by lngvietthang** [comment]
Hi everyone,

I try to code the hierarchical RNN, following the comment @phdowling. Here is my code:

```python
import numpy as np
from keras.models import Sequential
from keras.layers.wrappers import TimeDistributed
from keras.layers.recurrent import SimpleRNN
from keras import backend as K

def main():
    input = np.random.rand(1, 20, 30, 2).astype('float32')
    tempt = input.reshape((1, 600, 2))
    target = np.sum(tempt, axis=1)
    model = Sequential()
    model.add(TimeDistributed(SimpleRNN(output_dim=2, input_shape=(30, 2), init='identity', inner_init='identity', activation='linear'), input_shape=(20, 30, 2)))
    model.add(SimpleRNN(output_dim=2, init='identity', inner_init='identity', activation='linear'))
    get_model_output = K.function([model.layers[0].input], [model.layers[-1].output])
    model_output = get_model_output([input])[0]
    print target.shape, ':', model_output.shape
    print np.array_equal(target, model_output)
    print 'Target ->', target
    print 'Model ->', model_output
```

And I don't get the problem like @siavash9000 got, maybe my code is too simple.
@siavash9000 Do you fix your problem? If so, could you can share how to fix it?
Thanks!

**Comment by siavash9000** [comment]
@lngvietthang : Thanks for sharing your model. I refactored my script to deliver a more simplified version, where the described behaviour is reproducible [(link):](https://github.com/siavash9000/mixed_word_embedding/blob/master/simplified.py)

```
from keras.models import Model
from keras.utils import np_utils
from keras.layers import Dense, Embedding, Input, TimeDistributed, LSTM,  \
    Activation
import numpy as np


def main():
    DATA_SIZE = 1000
    BATCH_SIZE = 100
    WORD_COUNT = 20
    WORD_LENGTH = 10
    CHAR_VOCAB_SIZE = 50
    NB_CLASSES = 5
    CONSUME_LESS = 'cpu'

    X = np.random.randint(CHAR_VOCAB_SIZE, size=(DATA_SIZE, WORD_COUNT, WORD_LENGTH))
    Y = np.random.randint(NB_CLASSES, size=DATA_SIZE)
    Y = np_utils.to_categorical(Y, NB_CLASSES)

    input = Input(batch_shape=(BATCH_SIZE,WORD_COUNT, WORD_LENGTH, ),
                  dtype='int32')
    embedded = TimeDistributed(Embedding(CHAR_VOCAB_SIZE, 128,
                                         input_length=WORD_COUNT))(input)
    char_lstm = TimeDistributed(LSTM(64, consume_less=CONSUME_LESS))(embedded)
    lstm = LSTM(64,consume_less=CONSUME_LESS)(char_lstm)
    dense = Dense(NB_CLASSES, activation='sigmoid')(lstm)
    output = Activation('softmax')(dense)
    model = Model(input=input, output=output)
    model.compile(loss='categorical_crossentropy', optimizer='adam',
                  metrics=['accuracy'])
    model.fit(X, Y, batch_size=BATCH_SIZE, nb_epoch=5)


if __name__ == "__main__":
    main()
```

There are again errors when using the default option `consume_less='cpu' `for the LSTMs, switching to `consume_less='gpu'` solves the problem.

Are the errors reproducible for you with the script above? I use most current Keras and Theano.

**Comment by bkj** [comment]
@siavash9000 Did you ever resolve this issue?  I get the error

```
   Exception: ('Not a Keras tensor:', <TensorType(float32, 3D)>)
```

when I try to run your code
