### ISSUE TITLE
Is it possible to keep some weights fixed during training

### ISSUE THREAD

**Issue by tuming1990** [fchollet/keras#2880]
I want to keep some weights fixed during training the neural network, which means not updating these weights since they are initialized. 

''Some weights'' means some values in weight matrices, not specific rows or columns or weight matrix of a specific layer. They can be any element in weight matrices.

Is there a way to do this in Keras? I know Caffe can do this by setting a mask to the weight matrix so the masked weight will not affect the output.

**Comment by xingdi-eric-yuan** [comment]
`self.non_trainable_weights` ?

**Comment by tuming1990** [comment]
I think this doesn't work according to https://github.com/fchollet/keras/issues/2395

**Comment by sileod** [comment]
I think that you can use a custom constraint

**Comment by henry0312** [comment]
http://keras.io/getting-started/faq/#how-can-i-freeze-keras-layers may be helpful.

**Comment by tuming1990** [comment]
'''python
# We create an input node, which we will keep updated
            # as we add more layers
            Node(outbound_layer=self,
                 inbound_layers=[],
                 node_indices=[],
                 tensor_indices=[],
                 input_tensors=self.inputs,
                 output_tensors=self.outputs,
                 # no model-level masking for now
                 input_masks=[None for _ in self.inputs],
                 output_masks=[None],
                 input_shapes=[x._keras_shape for x in self.inputs],
                 output_shapes=[self.outputs[0]._keras_shape])
'''python

Seems model-level masking is a future plan, right? @fchollet

**Comment by harchankoj** [comment]
Same issue for a CNN that has three layers in which I want to freeze specific weights (whole kernels) starting in layer 2 which has 32x32 kernels that are 3x3. First trained the model, then saved the model, and then loaded it back in. Here's what I tried

model.layers[2].non_trainable_weights = model.layers[2].W[:, :, 0, 0] #freeze this kernel
model.layers[2].trainable_weights = [model.layers[2].W[:, :, 1:, 1:]] #explicitly keep these kernels trainable

These statements work fine (no errors) but when I do model.summary I get the following:

Layer (type)                     Output Shape          Param #     Connected to                     
================================================================
input_2 (InputLayer)             (None, 32, 32, 1)     0                                            
____________________________________________________________________________________________________
convolution2d_6 (Convolution2D)  (None, 32, 32, 32)    2624        input_2[0][0]                    
____________________________________________________________________________________________________
Traceback (most recent call last):

  File "<ipython-input-31-9a7881f870d4>", line 1, in <module>
    model.summary()

  File "...\keras\engine\topology.py", line 2903, in summary
    positions=positions)

  File "...\keras\utils\layer_utils.py", line 114, in print_summary
    print_layer_summary(layers[i])

  File "...\keras\utils\layer_utils.py", line 106, in print_layer_summary
    fields = [name + ' (' + cls_name + ')', output_shape, layer.count_params(), first_connection]

  File "...\keras\engine\topology.py", line 1039, in count_params
    return sum([K.count_params(p) for p in self.weights])

  File "...\keras\engine\topology.py", line 954, in weights
    return self.trainable_weights + self.non_trainable_weights

  File "...\tensorflow\python\ops\math_ops.py", line 828, in r_binary_op_wrapper
    return func(x, y, name=name)

  File "...\tensorflow\python\ops\gen_math_ops.py", line 73, in add
    result = _op_def_lib.apply_op("Add", x=x, y=y, name=name)

  File "...\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)

  File "...\tensorflow\python\framework\ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)

  File "...\tensorflow\python\framework\ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)

  File "...\tensorflow\python\framework\ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)

  File "...\tensorflow\python\framework\common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)

  File "...\tensorflow\python\framework\common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)

ValueError: Dimensions must be equal, but are 31 and 3 for 'add_86' (op: 'Add') with input shapes: [1,3,3,31,31], [3,3].

**Comment by YuanhaoGong** [comment]
I think this feature is important. Does anyone find out how to do so?

**Comment by caugusta** [comment]
Still having a similar issue. Any ideas?

**Comment by harchankoj** [comment]
This is one reason that implementation of neural networks within hardware or firmware continues to be an issue: network pruning is very limited. It's unfortunate stale bot intervened while the real issue remains open. Or perhaps it's been solved and not shared.

**Comment by maxtomCMU** [comment]
Maybe the tf.bool_mask could do this trick.

**Comment by SunTongtongtong** [comment]
Is it solved? I have the same problem_

**Comment by theforthforgotten** [comment]
how to realize by caffe

**Comment by theforthforgotten** [comment]
@tuming1990

**Comment by otdewiljes** [comment]
> http://keras.io/getting-started/faq/#how-can-i-freeze-keras-layers may be helpful.

This may well be exactly what you need. 

It certainly is exactly what I needed.

**Comment by N0ciple** [comment]
> > http://keras.io/getting-started/faq/#how-can-i-freeze-keras-layers may be helpful.
> 
> This may well be exactly what you need.
> 
> It certainly is exactly what I needed.

Actually @tuming1990 asked for fine grained pruning, the link provided by @henry0312 is about coarse grained pruning. It is only possible to freeze the layers with the `trainable` parameter. However the author clearly asked for a way to freeze any weight in the tensors.

Does anybody have an update about element-wise weight freezing ?

**Comment by fqassemi** [comment]
Is this solved? It is very handy to keep some weights (not necessarily the whole layer) fixed.

**Comment by ryanmaxwell96** [comment]
Any update? I am looking to do this as well.

**Comment by Doekeb** [comment]
If anyone is still watching this, I have two classes (an initializer and a constraint) which may solve this problem. I have only tested them on my use case so take them with a grain of salt. They allow for initializing any slice of a given weight tensor to chosen values (FixSlice) and freezing any slice of a given weight tensor to chosen values (FreezeSlice).
```
from keras.initializers import Initializer

class FixSlice(Initializer):
    """
    Initializer which forces a certain slice to be chosen values

    INPUTS:

    values - An object which can be converted into a numpy ndarray. These are
             the pre-chosen values. When using this initializer, the user should
             ensure that the dtype of values can be converted to the desired
             dtype of the weight tensor.

    slice - A slice or tuple of slices (it is recommended to use numpy.s_ to
            specify this parameter). This specifies which entries should be
            filled with the pre-chosen values. When using this initializer,
            the user should ensure that the slice object "fits inside" the shape
            of the tensor to be initialized, and that the resulting slice of the
            tensor has the same shape as the values ndarray.

    backup - An initializer instance. The remaining values are filled using this
             initializer.
    """
    def __init__(self, values, slice, backup="glorot_uniform"):
        if hasattr(values, "numpy"):
            self.values = values.numpy()
        elif isinstance(values, np.ndarray):
            self.values = values
        else:
            try:
                self.values = values.to_numpy()
            except:
                self.values = np.array(values)

        self.values = values
        self.slice = slice
        self.backup = initializers.get(backup)

    def __call__(self, shape, dtype=None):
        result = self.backup(shape, dtype=dtype).numpy()
        result[self.slice] = self.values
        return tf.Variable(result)
```
```
from keras.constraints import Constraint

class FreezeSlice(Constraint):
    """
    Constraint which keeps a certain slice frozen at chosen values

    INPUTS:

    values - An object which can be converted into a numpy ndarray. These are
             the pre-chosen values. When using this constraint, the user should
             ensure that the dtype of values can be converted to the desired
             dtype of the weight tensor.

    slice - A slice or tuple of slices (it is recommended to use numpy.s_ to
            specify this parameter). This specifies which entries should be
            filled with the pre-chosen values. When using this initializer,
            the user should ensure that the slice object "fits inside" the shape
            of the tensor to be initialized, and that the resulting slice of the
            tensor has the same shape as the values ndarray.
    """
    def __init__(self, values, slice):
        if hasattr(values, "numpy"):
            self.values = values.numpy()
        elif isinstance(values, np.ndarray):
            self.values = values
        else:
            try:
                self.values = values.to_numpy()
            except:
                self.values = np.array(values)

        self.values = values
        self.slice = slice

    def __call__(self, w):
        zs = np.zeros(w.shape)
        zs[self.slice] = self.values
        os = np.ones(w.shape)
        os[self.slice] = 0
        return w * os + zs
```

**Comment by saroj7pathak** [comment]
> If anyone is still watching this, I have two classes (an initializer and a constraint) which may solve this problem. I have only tested them on my use case so take them with a grain of salt. They allow for initializing any slice of a given weight tensor to chosen values (FixSlice) and freezing any slice of a given weight tensor to chosen values (FreezeSlice).
> 
> ```
> from keras.initializers import Initializer
> 
> class FixSlice(Initializer):
>     """
>     Initializer which forces a certain slice to be chosen values
> 
>     INPUTS:
> 
>     values - An object which can be converted into a numpy ndarray. These are
>              the pre-chosen values. When using this initializer, the user should
>              ensure that the dtype of values can be converted to the desired
>              dtype of the weight tensor.
> 
>     slice - A slice or tuple of slices (it is recommended to use numpy.s_ to
>             specify this parameter). This specifies which entries should be
>             filled with the pre-chosen values. When using this initializer,
>             the user should ensure that the slice object "fits inside" the shape
>             of the tensor to be initialized, and that the resulting slice of the
>             tensor has the same shape as the values ndarray.
> 
>     backup - An initializer instance. The remaining values are filled using this
>              initializer.
>     """
>     def __init__(self, values, slice, backup="glorot_uniform"):
>         if hasattr(values, "numpy"):
>             self.values = values.numpy()
>         elif isinstance(values, np.ndarray):
>             self.values = values
>         else:
>             try:
>                 self.values = values.to_numpy()
>             except:
>                 self.values = np.array(values)
> 
>         self.values = values
>         self.slice = slice
>         self.backup = initializers.get(backup)
> 
>     def __call__(self, shape, dtype=None):
>         result = self.backup(shape, dtype=dtype).numpy()
>         result[self.slice] = self.values
>         return tf.Variable(result)
> ```
> 
> ```
> from keras.constraints import Constraint
> 
> class FreezeSlice(Constraint):
>     """
>     Constraint which keeps a certain slice frozen at chosen values
> 
>     INPUTS:
> 
>     values - An object which can be converted into a numpy ndarray. These are
>              the pre-chosen values. When using this constraint, the user should
>              ensure that the dtype of values can be converted to the desired
>              dtype of the weight tensor.
> 
>     slice - A slice or tuple of slices (it is recommended to use numpy.s_ to
>             specify this parameter). This specifies which entries should be
>             filled with the pre-chosen values. When using this initializer,
>             the user should ensure that the slice object "fits inside" the shape
>             of the tensor to be initialized, and that the resulting slice of the
>             tensor has the same shape as the values ndarray.
>     """
>     def __init__(self, values, slice):
>         if hasattr(values, "numpy"):
>             self.values = values.numpy()
>         elif isinstance(values, np.ndarray):
>             self.values = values
>         else:
>             try:
>                 self.values = values.to_numpy()
>             except:
>                 self.values = np.array(values)
> 
>         self.values = values
>         self.slice = slice
> 
>     def __call__(self, w):
>         zs = np.zeros(w.shape)
>         zs[self.slice] = self.values
>         os = np.ones(w.shape)
>         os[self.slice] = 0
>         return w * os + zs
> ```

Can you provide specific example of it's application?

**Comment by NioushaBagheri** [comment]
> Can you provide specific example of it's application?
model.add(Dense(1,input_dim =2,kernel_constraint=FreezeSlice([1],np.s_[0])))
In this example, I set the value of the first weight to 1.

**Comment by NioushaBagheri** [comment]
> > If anyone is still watching this, I have two classes (an initializer and a constraint) which may solve this problem. I have only tested them on my use case so take them with a grain of salt. They allow for initializing any slice of a given weight tensor to chosen values (FixSlice) and freezing any slice of a given weight tensor to chosen values (FreezeSlice).
> > ```
> > from keras.initializers import Initializer
> > 
> > class FixSlice(Initializer):
> >     """
> >     Initializer which forces a certain slice to be chosen values
> > 
> >     INPUTS:
> > 
> >     values - An object which can be converted into a numpy ndarray. These are
> >              the pre-chosen values. When using this initializer, the user should
> >              ensure that the dtype of values can be converted to the desired
> >              dtype of the weight tensor.
> > 
> >     slice - A slice or tuple of slices (it is recommended to use numpy.s_ to
> >             specify this parameter). This specifies which entries should be
> >             filled with the pre-chosen values. When using this initializer,
> >             the user should ensure that the slice object "fits inside" the shape
> >             of the tensor to be initialized, and that the resulting slice of the
> >             tensor has the same shape as the values ndarray.
> > 
> >     backup - An initializer instance. The remaining values are filled using this
> >              initializer.
> >     """
> >     def __init__(self, values, slice, backup="glorot_uniform"):
> >         if hasattr(values, "numpy"):
> >             self.values = values.numpy()
> >         elif isinstance(values, np.ndarray):
> >             self.values = values
> >         else:
> >             try:
> >                 self.values = values.to_numpy()
> >             except:
> >                 self.values = np.array(values)
> > 
> >         self.values = values
> >         self.slice = slice
> >         self.backup = initializers.get(backup)
> > 
> >     def __call__(self, shape, dtype=None):
> >         result = self.backup(shape, dtype=dtype).numpy()
> >         result[self.slice] = self.values
> >         return tf.Variable(result)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > from keras.constraints import Constraint
> > 
> > class FreezeSlice(Constraint):
> >     """
> >     Constraint which keeps a certain slice frozen at chosen values
> > 
> >     INPUTS:
> > 
> >     values - An object which can be converted into a numpy ndarray. These are
> >              the pre-chosen values. When using this constraint, the user should
> >              ensure that the dtype of values can be converted to the desired
> >              dtype of the weight tensor.
> > 
> >     slice - A slice or tuple of slices (it is recommended to use numpy.s_ to
> >             specify this parameter). This specifies which entries should be
> >             filled with the pre-chosen values. When using this initializer,
> >             the user should ensure that the slice object "fits inside" the shape
> >             of the tensor to be initialized, and that the resulting slice of the
> >             tensor has the same shape as the values ndarray.
> >     """
> >     def __init__(self, values, slice):
> >         if hasattr(values, "numpy"):
> >             self.values = values.numpy()
> >         elif isinstance(values, np.ndarray):
> >             self.values = values
> >         else:
> >             try:
> >                 self.values = values.to_numpy()
> >             except:
> >                 self.values = np.array(values)
> > 
> >         self.values = values
> >         self.slice = slice
> > 
> >     def __call__(self, w):
> >         zs = np.zeros(w.shape)
> >         zs[self.slice] = self.values
> >         os = np.ones(w.shape)
> >         os[self.slice] = 0
> >         return w * os + zs
> > ```
> 
> Can you provide specific example of it's application?

model.add(Dense(1,input_dim =2,kernel_constraint=FreezeSlice([1],np.s_[0])))
In this example, I set the value of the first weight to 1.

**Comment by artemglukhov** [comment]
> > > If anyone is still watching this, I have two classes (an initializer and a constraint) which may solve this problem. I have only tested them on my use case so take them with a grain of salt. They allow for initializing any slice of a given weight tensor to chosen values (FixSlice) and freezing any slice of a given weight tensor to chosen values (FreezeSlice).
> > > ```
> > > from keras.initializers import Initializer
> > > 
> > > class FixSlice(Initializer):
> > >     """
> > >     Initializer which forces a certain slice to be chosen values
> > > 
> > >     INPUTS:
> > > 
> > >     values - An object which can be converted into a numpy ndarray. These are
> > >              the pre-chosen values. When using this initializer, the user should
> > >              ensure that the dtype of values can be converted to the desired
> > >              dtype of the weight tensor.
> > > 
> > >     slice - A slice or tuple of slices (it is recommended to use numpy.s_ to
> > >             specify this parameter). This specifies which entries should be
> > >             filled with the pre-chosen values. When using this initializer,
> > >             the user should ensure that the slice object "fits inside" the shape
> > >             of the tensor to be initialized, and that the resulting slice of the
> > >             tensor has the same shape as the values ndarray.
> > > 
> > >     backup - An initializer instance. The remaining values are filled using this
> > >              initializer.
> > >     """
> > >     def __init__(self, values, slice, backup="glorot_uniform"):
> > >         if hasattr(values, "numpy"):
> > >             self.values = values.numpy()
> > >         elif isinstance(values, np.ndarray):
> > >             self.values = values
> > >         else:
> > >             try:
> > >                 self.values = values.to_numpy()
> > >             except:
> > >                 self.values = np.array(values)
> > > 
> > >         self.values = values
> > >         self.slice = slice
> > >         self.backup = initializers.get(backup)
> > > 
> > >     def __call__(self, shape, dtype=None):
> > >         result = self.backup(shape, dtype=dtype).numpy()
> > >         result[self.slice] = self.values
> > >         return tf.Variable(result)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > from keras.constraints import Constraint
> > > 
> > > class FreezeSlice(Constraint):
> > >     """
> > >     Constraint which keeps a certain slice frozen at chosen values
> > > 
> > >     INPUTS:
> > > 
> > >     values - An object which can be converted into a numpy ndarray. These are
> > >              the pre-chosen values. When using this constraint, the user should
> > >              ensure that the dtype of values can be converted to the desired
> > >              dtype of the weight tensor.
> > > 
> > >     slice - A slice or tuple of slices (it is recommended to use numpy.s_ to
> > >             specify this parameter). This specifies which entries should be
> > >             filled with the pre-chosen values. When using this initializer,
> > >             the user should ensure that the slice object "fits inside" the shape
> > >             of the tensor to be initialized, and that the resulting slice of the
> > >             tensor has the same shape as the values ndarray.
> > >     """
> > >     def __init__(self, values, slice):
> > >         if hasattr(values, "numpy"):
> > >             self.values = values.numpy()
> > >         elif isinstance(values, np.ndarray):
> > >             self.values = values
> > >         else:
> > >             try:
> > >                 self.values = values.to_numpy()
> > >             except:
> > >                 self.values = np.array(values)
> > > 
> > >         self.values = values
> > >         self.slice = slice
> > > 
> > >     def __call__(self, w):
> > >         zs = np.zeros(w.shape)
> > >         zs[self.slice] = self.values
> > >         os = np.ones(w.shape)
> > >         os[self.slice] = 0
> > >         return w * os + zs
> > > ```
> > 
> > 
> > Can you provide specific example of it's application?
> 
> model.add(Dense(1,input_dim =2,kernel_constraint=FreezeSlice([1],np.s_[0]))) In this example, I set the value of the first weight to 1.

Thank you, it seems to be working for a single dimension, but I can't get it working on a multidimensional array. The constraint freezes always a full row of weights and I didn't find a way to use it on a single element.
What I would like to obtain is something freely addressable, for example:

```
t1 = tf.constant([[0,0,0],[0,0,0],[0,0,0]])
t2 = tf.tensor_scatter_nd_update(t1, indices=[[0,0],[1,1],[2,2]], updates=[10,10,10])
```
will give as a result 
```
[10 0 0]
[0 10 0]
[0 0 10]
```

Do you think it is possible with something similar to your implementation?

**Comment by MichelHUANGGit** [comment]
Hey, if anyone is still reading this. It seems like **it's impossible to set specific weights inside a layer to untrainable, you either set the whole layer trainable or untrainable**. Instead, I built a custom Constraint and Initializer class to freeze specific weights inside a **2D convolution filter**, inspired by @Doekeb. For example if I'm using a 3x3 filter and I want to freeze all the weights in the corner, i'll create a mask like this : 
[[False, True, False],
 [True,  True,  True],
 [False, True,  False]]
 where True indicates wheter the weight is trainable, and False means frozen.
 

```
class FreezeConv(Constraint):
    '''
    Inherits from keras.constraints.Constraint.
    This class freezes specific kernels weights to 0 after the back propagation according to the mask parameter.
    '''
    def __init__(self, mask, in_channel_axis, out_channel_axis):
        self.mask = mask
        self.in_channel_axis = in_channel_axis
        self.out_channel_axis = out_channel_axis

    def __call__(self, w):
        nb_out_channel = w.shape[self.out_channel_axis]
        nb_in_channel = w.shape[self.in_channel_axis]
        # A (3x3) kernel in reality has weights of shape (3,3,input_channels,output_channels)
        # while the mask has shape (3,3). We do a tf.repeat and reshape to the right size, then multiply it to the weights w.
        try :
          reshaped_mask = tf.reshape(
              tf.repeat(self.mask, nb_in_channel*nb_out_channel),
              shape=w.shape
          )
          return w * tf.cast(reshaped_mask, dtype=w.dtype)
        except :
          print("error")
          print(nb_in_channel, nb_out_channel)
          print(tf.repeat(self.mask, nb_in_channel*nb_out_channel).shape)
          return w
        
class FreezeInit(Initializer):
    '''
    Inherits from keras.initializers.Initializer.
    This class initializes random kernel weights following a gaussian distribution.
    But it sets some specific weights within the kernel to 0 according to the mask parameter.
    '''
    def __init__(self, mask):
        self.mask = mask
        # track the number of frozen weights
        self.frozen_weights = (1-self.mask).sum()

    def __call__(self, shape, dtype=None):
        try :
          kernel_height, kernel_width, in_filters, out_filters = shape
          fan_out = int(kernel_height * kernel_width * out_filters)
          reshaped_mask = tf.reshape(
              tf.repeat(self.mask, in_filters*out_filters),
              shape=shape
          )
          self.frozen_weights *= in_filters*out_filters
          return tf.random.normal(shape, mean=0.0, stddev=np.sqrt(2.0 / fan_out), dtype=dtype) * tf.cast(reshaped_mask, dtype=dtype)
        except :
          print("error")
```

For example : 
```
mask = [
  [False, True, False],
  [True,  True,  True],
  [False, True,  False]
 ]
Freeze_ = FreezeConv(mask)
FreezeInit_ = FreezeInit(mask)
MyConv2D = Conv2D(32, filter_size = (3,3), strides=(1,1), padding='same', kernel_initializer=FreezeInit_, kernel_constraint=Freeze_)
```
should set the corners to 0 at initialization thanks to FreezeInit, and also after every back propagation step thanks to Freeze_.
One cool thing is that it reduces slightly overfitting in specific cases, where you know for certain that the corner weights (or at any other position of the filter) aren't relevant for your model. And you're also technically using less trainable weights that what model.summary() says you are.

Note : I used a very specific code for my own purposes, this might not work everywhere, feel free to adapt the code. I tried this on normal conv2D, DepthwiseConv2D, and grouped convolutions, it worked just fine.
Note 2 : The ideal way would be to freeze certains weights directly when defining the layers, so we don't waste computation time to back propagate gradients then reset to 0 like I did. But it doesn't possible in Keras atm.
