### ISSUE TITLE
Unable to get hidden layer activation of ANN using  .get_output()  function

### ISSUE THREAD

**Issue by rianzaman** [fchollet/keras#2886]
I am using python2 and i'm trying to get the activations of hidden layer. I am using the following code which is giving me an error.My Keras version is 1.0.3. and i have a 1 input 1 hidden and 1 output layer in my model. When I wrote this code I was using python3. Now I have loaded it in pycharm using py2, could this be an issue?
The code I am using is:
`get_activations = theano.function([my_model.layers[0].input], my_model.layers[0].get_output(train=False),
                              allow_input_downcast=True)`

When I run the code it says:
`AttributeError: 'Dense' object has no attribute 'get_output'`
I have tried to use `my_model.layers[0].output()` which also does not work correctly.

What should I do to get the activations?

**Comment by henry0312** [comment]
See http://keras.io/getting-started/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer

**Comment by rianzaman** [comment]
Thank you for your help. Solved it. I had to use `my_model.layers[0].output`  not `my_model.layers[0].output()` .
