### ISSUE TITLE
cross layer constraints

### ISSUE THREAD

**Issue by judyweiying** [fchollet/keras#2888]
Hi all,

Do you know how to implement the following network in keras shown in the picture? The difficulty lies in that I do not know how to constrain W1 = W2. Thank you very much!
![question](https://cloud.githubusercontent.com/assets/5757646/15768259/d956fd58-2981-11e6-8e9f-2bd769011a91.png)

Best Regards,
Ying

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by sileod** [comment]
Wi = Dense(5)

right orange thing = Wi(left orange thing)
right green thing = Wi(left green thing)

**Comment by judyweiying** [comment]
Dear sileod,

Thank you very much! You are right, and this works. But what I really what
to do is to impose such constraints not limited to W1 = W2, for example W1
= 3 * W2 OR W1 * W2 = I. Do you have any idea?

Thank you very much!

Best Regards,
Ying

2016-06-03 15:24 GMT+08:00 sileod <notifications@github.com>:

**Comment by sileod** [comment]
I think you have to be creative to do that because it's not always well defined, and I don't think it's currently possible to do this in a general way in keras (or any DL framework)

W1 = 3 * W2 : define W2 and use a composition of W2 and a Lambda layer that multiplies by 3
The other is harder

You could also manually enforce the constraints after each batch
