### ISSUE TITLE
bug in get_output_shape_for() function of Flatten layer

### ISSUE THREAD

**Issue by ghost** [fchollet/keras#2889]
Currently the get_output_shape_for() funciton of Flatten layer requires all dimensions are explicitly defined, otherwise it will raise an exception. However, when building FCN model with variable-sized input, this will be a problem since not all input dimensions are fixed. I suggest modifying the get_output_shape_for() function from 

```
def get_output_shape_for(self, input_shape):
    if not all(input_shape[1:]):
         raise Exception('The shape of the input to "Flatten" '
                         'is not fully defined '
                         '(got ' + str(input_shape[1:]) + '. '
                         'Make sure to pass a complete "input_shape" '
                         'or "batch_input_shape" argument to the first '
                         'layer in your model.')
    return (input_shape[0], np.prod(input_shape[1:]))
```

to 

```
def get_output_shape_for(self, input_shape):
    if not all(input_shape[1:]):
        return (input_shape[0], None)
    return (input_shape[0], np.prod(input_shape[1:]))
```

This will resolve the problem.

_Index: FCN, fully convolutional network_

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by joelthchao** [comment]
Can you show your code for FCN model? It's necessary for a `Flatten` layer to have determined `input_shape`.
