### ISSUE TITLE
Visualizing the output of an intermediate layer

### ISSUE THREAD

**Issue by dvigneshwer** [fchollet/keras#2890]
**Ref Link** from keras documentation: http://keras.io/getting-started/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer

I referred to the keras documentation to visulaize the intermediate output. PFB my **code snippet** below,

```
get_3_layer_output = K.function([model.layers[0].input, K.learning_phase()],[model.layers[3].output])
print np.shape(get_3_layer_output([X_train, 1])[0])
#Taking 2 Images
for i in xrange(len(get_3_layer_output([X_train, 1])[0])):
    #Saving  32 Activation maps outputs
    for j in xrange(len(get_3_layer_output([X_train, 1])[0][i])):
        cv2.imwrite(location+"layer_3_"+str(j)+".jpg",get_3_layer_output([X_train, 1])[0][i][j])`
```

This is the training phase. I am getting the correct shapes for my layer outputs as expected from my CNN model.

ex: layer output (2, 32, 32, 32) - 2 images 32 activation map of matrix size 32x32.
**Problem:**  When I am writing the intermediate result, all that I am getting is black images for all the activation maps.

**Keras dist:** https://github.com/joelthchao/keras (Supports locally connected layer)
**Theano:**Theano-0.9.0.dev0-py2.7.egg-info (latest)

**Comment by jfsantos** [comment]
Are you using ReLUs as activations for that layer? Getting all zeros could mean your preactivations are all negative so your activations are all zeros. Outputs of ReLU layers tend to be sparse in some models, so maybe you're getting just a few "pixels" that have non-zero values? Check the matrices to see if you have non-zero values instead of plotting to images directly (e.g., with `np.any`). When you plot to JPG, if your activation maps are very sparse, the JPEG encoder might smooth those activations out (because they look like noise). You could also try saving to BMP instead of JPEG so there'll be no encoding.

By the way, you should use `learning_phase=0` if you're trying to see what your model is generating in practice as opposed to during training.

**Comment by dvigneshwer** [comment]
@jfsantos I am using ReLu as my activation function. I printed outputs from the layer and I am getting really low values. 
I now loaded my trained model and made my learning phase 0, also used bmp format for saving, still getting black images only. 

[[ 0.00019351  0.00019351  0.00019351 ...,  0.00019351  0.00019351
   0.00019351]
 [ 0.00019351  0.00019351  0.00019351 ...,  0.00019351  0.00019351
   0.00019351]
 [ 0.00019351  0.00019351  0.00019351 ...,  0.00019351  0.00019351
   0.00019351]
 ..., 
 [ 0.00019351  0.00019351  0.00019351 ...,  0.00019351  0.00019351
   0.00019351]
 [ 0.00019351  0.00019351  0.00019351 ...,  0.00019351  0.00019351
   0.00019351]
 [ 0.00019351  0.00019351  0.00019351 ...,  0.00019351  0.00019351
   0.00019351]]

**Code Snippet** 
```

get_0_layer_output = K.function([model.layers[0].input, K.learning_phase()],[model.layers[0].output])

	print np.shape(get_0_layer_output([X_train, 0])[0])

	for i in xrange(len(get_0_layer_output([X_train, 0])[0])):
		print "The complete matrix : " + str(i) + "\n \n "
		print "Shape is :" + str(np.shape(get_0_layer_output([X_train, 0])[0][i])) + "\n\n"
		print get_0_layer_output([X_train, 0])[0][i]

		for j in xrange(len(get_0_layer_output([X_train, 0])[0][i])):
			print "Individual matrix : " + str(j) + "\n \n "
			print "Shape is :" + str(np.shape(get_0_layer_output([X_train, 0])[0][i][j])) + "\n\n"
			print get_0_layer_output([X_train, 0])[0][i][j]
			cv2.imwrite("./intermediate_result/l0/layer_comv_0_op_"+str(i)+str(j)+".bmp",get_0_layer_output([X_train, 0])[0][i][j])


```

**Comment by jfsantos** [comment]
That's what your model is getting, then, and there's nothing wrong with Keras. Is the model giving you meaningful predictions? Do you get this for the entire training set? If that's the case, I would assume your model is not learning anything meaningful.

**Comment by dvigneshwer** [comment]
I was giving the input in a wrong manner and have changed my weights to the model in which I got best predicitions.
Now I am getting intermediate results but I still finding few activation maps (filter outputs) completely black. 
Do you have any suggestion for me ?
