### ISSUE TITLE
Attention GRU layer implementation issue -- why is complie time so long ?

### ISSUE THREAD

**Issue by stifflerhe** [fchollet/keras#2896]
Hey guys! 
Based on [this paper](http://arxiv.org/abs/1409.0473), I implemented a attention GRU layer, which is based on the current GRU layer, and this is the [gist](https://gist.github.com/stifflerhe/02192afd86fad663f1ffc1d41aa0f95f).  It seems to be able to run in this [example](https://gist.github.com/stifflerhe/567e560bd3ce7a2a63da4c75e61bfb6d),however, the compile time of the test code is extremely long and when I use this layer in a more complex model( say a encoder -decoder model), it seems to take forever to compile. 
Any idea how to solve this ? Am I doing something wrong when I implement this layer ？
@fchollet 
By the way, the arg hidden_input of the init function  is the hidden output of the RNN encoder, because I don't know how to define a multiple input for the GRU layer , I just code like this, could this be the problem?
THANKS !!!!!!!!!!!!

**Comment by stifflerhe** [comment]
I have implemented a custom RNN as you recommended in [2240](https://github.com/fchollet/keras/issues/2240), and the compile time of this layer is to long, could you help me to go through my code, and tell me what is wrong? @matthiasplappert 
Thanks a lot

**Comment by shampool** [comment]
How long does it take?
I trained one multi-dimensional RNN with only two layers, and it takes me almost 900 seconds.  So don't be surprised if it takes you longer with complex RNN model.

**Comment by ymcui** [comment]
have you used the latest version?
it seems in new version of Keras, the compilation speed is far more faster than version 0.x.x
only takes 1~2 minutes to compile a 512 units of bi-GRU for QA task @Tesla K40

**Comment by stifflerhe** [comment]
@shampool  The experiment code I wrote which is more complex than the test took me 4 hours to get to the epoch stage and I ran it on my laptop, however, when I test it in the tesla k20 server, after waiting for 1 hour, I kill the process. I mean 900 seconds is Ok, but 4 hours is too long.

**Comment by stifflerhe** [comment]
@ymcui Yes, I used the latest version of keras to implement my code. I use this layer to build a seq2seq model and it really took me a long time.

**Comment by lemuriandezapada** [comment]
compile times can become insanely huge when your computational graph is complex
I guess it takes quite some time to approximate all those derivatives
Try setting your environment variable mode=FAST_COMPILE and see what that does

**Comment by stifflerhe** [comment]
@lemuriandezapada thanks, I will give it a try
