### ISSUE TITLE
custom a regularizer interfering two layers' weights

### ISSUE THREAD

**Issue by judyweiying** [fchollet/keras#2904]
Dear all,

In current Keras implementation, the regularizer can only regularizes a single layer's parameters. Do you have any idea on how to regularize multiple layers' parameters together, as the following figure shows. Thank you very much!

Best,
Ying
![question](https://cloud.githubusercontent.com/assets/5757646/15810459/600648b2-2bd1-11e6-8fe3-a3b59494beed.png)

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by slychief** [comment]
Hi,

has anybody solved this problem? I'm also trying to figure out how this problem can be realized in keras.
I tried stacking the layers but then I cannot split them again.

Best,
Alex

**Comment by yasserfarouk** [comment]
I also need to apply regularization taking into account multiple layers at the same time.

**Comment by yasserfarouk** [comment]
I could get around it by installing a regularizer at every layer then have one of them do the required change in the objective silencing all others.

**Comment by pvskand** [comment]
@yasserfarouk can you explain your method in a bit more comprehensive manner?
