### ISSUE TITLE
Rerun graph.fit many times

### ISSUE THREAD

**Issue by snownus** [fchollet/keras#2905]
Hi, Guys, 

I have come across a problem that the training dataset is very large so I split it into many subset and then load each subset for training. In each subset, I split it into batches for training. Here, after compiling, can I use the function **graph.fit()** many times to update the weights for different subsets?

**Comment by kgrm** [comment]
Yes. If you've already split your data into minibatches, you may also consider using the `model.train_on_batch()` function.
