### ISSUE TITLE
auto-encoder batch-size value error 

### ISSUE THREAD

**Issue by myouness** [fchollet/keras#2910]
Hello,

I get a value error while playing the code of an auto-encoder https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py.
In order to get it to work I need to choose a batch size that is a divisor of the train size ( train.shape[0] % batch_size == 0)

Is there anyway I can solve this issue ?

Thank you very much.

**Comment by evoclue** [comment]
I think this has to do with the fact that `z = Lambda(sampling, output_shape=(latent_dim,))([z_mean, z_log_std])` has to have a static output shape and that the epsilon tensor needs to have the correct dimensions, which are static, as well.

**Comment by myouness** [comment]
Thank you
