### ISSUE TITLE
keras imdb_lstm.py gives the following error ('The following error happened while compiling the node', GpuJoin(TensorConstant{1}, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0' 

### ISSUE THREAD

**Issue by krishnateja614** [fchollet/keras#2913]
This is full traceback after printing the train and test shapes. Before the below traceback, a 10492 line python code was also printed to the console

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mukris\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "C:\Users\mukris\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/mukris/keras_examples/examples_imdb_lstm.py", line 45, in <module>
    validation_data=(X_test, y_test))
  File "c:\users\mukris\keras\keras\models.py", line 408, in fit
    sample_weight=sample_weight)
  File "c:\users\mukris\keras\keras\engine\training.py", line 1009, in fit
    self._make_test_function()
  File "c:\users\mukris\keras\keras\engine\training.py", line 686, in _make_test_function
    *_self._function_kwargs)
  File "c:\users\mukris\keras\keras\backend\theano_backend.py", line 528, in function
    return Function(inputs, outputs, updates=updates, *_kwargs)
  File "c:\users\mukris\keras\keras\backend\theano_backend.py", line 514, in __init__
    **kwargs)
  File "c:\users\mukris\theano\theano\compile\function.py", line 322, in function
    output_keys=output_keys)
  File "c:\users\mukris\theano\theano\compile\pfunc.py", line 480, in pfunc
    output_keys=output_keys)
  File "c:\users\mukris\theano\theano\compile\function_module.py", line 1828, in orig_function
    defaults)
  File "c:\users\mukris\theano\theano\compile\function_module.py", line 1692, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "c:\users\mukris\theano\theano\gof\link.py", line 693, in make_thunk
    storage_map=storage_map)[:3]
  File "c:\users\mukris\theano\theano\gof\vm.py", line 1021, in make_all
    no_recycling))
  File "c:\users\mukris\theano\theano\sandbox\cuda__init__.py", line 256, in make_thunk
    compute_map, no_recycling)
  File "c:\users\mukris\theano\theano\gof\op.py", line 969, in make_thunk
    no_recycling)
  File "c:\users\mukris\theano\theano\gof\op.py", line 872, in make_c_thunk
    output_storage=node_output_storage)
  File "c:\users\mukris\theano\theano\gof\cc.py", line 1200, in make_thunk
    keep_lock=keep_lock)
  File "c:\users\mukris\theano\theano\gof\cc.py", line 1143, in **compile**
    keep_lock=keep_lock)
  File "c:\users\mukris\theano\theano\gof\cc.py", line 1591, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "c:\users\mukris\theano\theano\gof\cmodule.py", line 1142, in module_from_key
    module = lnk.compile_cmodule(location)
  File "c:\users\mukris\theano\theano\gof\cc.py", line 1502, in compile_cmodule
    preargs=preargs)
  File "c:\users\mukris\theano\theano\sandbox\cuda\nvcc_compiler.py", line 403, in compile_str
    'for cmd', ' '.join(cmd))
Exception: ('The following error happened while compiling the node', GpuJoin(TensorConstant{1}, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0, GpuAlloc.0), '\n', 'nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 -LC:\Users\mukris\AppData\Local\Continuum\Anaconda2\libs -use_fast_math -arch=sm_21 --compiler-bindir C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=18715462c72ed6afcd7ca5d52813ce90,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -IC:\Users\mukris\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.11-64\cuda_ndarray -IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin\include -IC:\Users\mukris\AppData\Local\Continuum\Anaconda2\lib\site-packages\numpy\core\include -IC:\Users\mukris\AppData\Local\Continuum\Anaconda2\include -Ic:\users\mukris\theano\theano\gof -Ic:\users\mukris\theano\theano\sandbox\cuda -o C:\Users\mukris\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.11-64\tmp9z4sxl\e01240057833926033b89ffb155e750b.pyd mod.cu -LC:\Users\mukris\AppData\Local\Theano\compiledir_Windows-8.1-6.3.9600-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-2.7.11-64\cuda_ndarray -LC:\Users\mukris\AppData\Local\Continuum\Anaconda2\libs -LC:\Users\mukris\AppData\Local\Continuum\Anaconda2 -lcudart -lcublas -lcuda_ndarray -lpython27', '[GpuJoin(TensorConstant{1}, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>, <CudaNdarrayType(float32, col)>)]')

Is this something to do with the GPU(NVS 5400M). I'm running the latest theano version (from github) and keras(pip) with VS 2012.

UPDATE: I downgraded to keras 1.0.1 and changed the dimensions of lstm from 128 to 64 which is running fine without any errors?

**Comment by ymcui** [comment]
or you should try lower version of theano (like v0.8.1)?

**Comment by krishnateja614** [comment]
Thanks for the reply, anyway I was just playing around with LSTM, other examples and some of my own experiments seem to run fine. Will try to figure out what exactly is causing this LSTM to fail?
