### ISSUE TITLE
Re-using series of layer specifications, without weight-sharing

### ISSUE THREAD

**Issue by dansbecker** [fchollet/keras#2914]
Is there a way in the functional API to create a group together of layer specifications, so a single command always adds that group of layers *without weight sharing*?

For example, say I create a residual module as 
```
x = Input(shape=(3, 256, 256))
y = Convolution2D(3, 3, 3, border_mode='same')
z = merge([x, y], mode='sum'
```

Now I want to stack these residual modules on top of each other, so the output of one is the input to the next.  I considered putting these three lines into a model with x as an input and z as the output, so I could apply that model repeatedly. But I believe this causes the Convolution to be the same in each stage of my classifier.

Is there a way to bundle together the specification of layers without tying together the weights in each place I apply that bundle?

**Comment by fchollet** [comment]
> Is there a way to bundle together the specification of layers without tying together the weights in each place I apply that bundle?

Yes: the Python language. You can just write a Python function that adds a series of layers on top of an input (or adds them to a Sequential model, etc). This is the approach taken by all scripts that reuse module architecture, e.g. https://github.com/fchollet/keras/blob/master/examples/inception_v3.py#L25
