### ISSUE TITLE
Spearmint and/or Hyperas in Keras

### ISSUE THREAD

**Issue by Riashat** [fchollet/keras#2925]
I want to use Spearmint for Bayesian Optimization in keras.

Keep in mind, I think I am using a fairly older version of keras - last clone around January.

Any ideas how I can integrate Spearmint into keras? Can someone please give me a concrete example of this? 

On a similar thing, instead of using Spearmint, I tried hyperparameter optimization with "hyperas". It did seem to have much easier examples of how to use hyperparas in keras. However, I run into the following error, which I think is because I am using the older keras version?

```
model.add(Dropout({{uniform(0, 1)}}))
```

  File "/Library/Python/2.7/site-packages/hyperopt/pyll_utils.py", line 48, in hp_uniform
    raise TypeError('require string label')
TypeError: require string label

**Comment by EderSantana** [comment]
maybe you want to report that problem in hyperas itself, right?
https://github.com/maxpumperla/hyperas
@maxpumperla do you know what this might be?

**Comment by alyato** [comment]
hi @EderSantana what does the difference between the spearmint and hyperas?  I know the spearmint using the bayes to do it, and do you give one example to using the spearmint. Thanks
