### ISSUE TITLE
implement support for multiple gpus in theano

### ISSUE THREAD

**Issue by cmyr** [fchollet/keras#2926]
Wanted to open an issue because I've started playing around with an implementation of this. Currently working through some issues with theano: https://github.com/Theano/Theano/issues/4597.

My approach is to attempt to mimic the context manager API used in TF, so that we would be able to implement them both transparently and provide a unified interface. This looks like it should work; it's mostly a matter of resolving issues with theano at the moment.

If anyone else has had any success with this let me know?

**Comment by fchollet** [comment]
> My approach is to attempt to mimic the context manager API used in TF, so
that we would be able to implement them both transparently and provide a
unified interface. This looks like it should work; it's mostly a matter of
resolving issues with theano at the moment.


I think this is the right approach and we should definitely go for it.
Technically it seems like it is doable.

Unfortunately I don't have access to multiple GPUs for Keras development,
so it would be difficult for me to develop and test things. But I'm happy
to provide any help I can.

**Comment by cmyr** [comment]
Just for the record:

This is currently on the back-burner; there are some issues in Theano/libgpuarray that are causing regular crashes when trying to implement the unified API, and I'm not able to focus on trying to debug those issues much more. I'll keep checking in as that project moves along, however.
