### ISSUE TITLE
Accuracy issues with CNN model trained using cifar10_cnn.py example

### ISSUE THREAD

**Issue by mpt5** [fchollet/keras#2929]
I successfully trained a model using the [sample code for CIFAR10](https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py). It ran for about 2 hours on a MacPro with a GTX98-Ti GPU, with Theano (latest version) backend. 

All parameters were unchanged (including augmentation on) and model reached ~81% accuracy. At the end of script the weights (weights.h5, 5MB on disk) and architecture (arch.json) were exported.

I then tried to classify single images using [this code](https://gist.github.com/mpt5/f38ec5ea3b4c1b14f43e9c584839b028).

Essentially it restores the model and architecture, then loops through 10 images in a folder, resizing them to 32x32 pixels, reshaping the array, and forwarding the data to `model.predict_classes`. I was surprised to see the below output, in which none of the images was classified correctly. Has anyone done such an experiment and knows if there are issues with the model build or if my procedure is incorrect?

```
Using Theano backend.
Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled, cuDNN 5005)
1/1 [==============================] - 0s
truck predicted \\\ airplane.jpeg truth
1/1 [==============================] - 0s
airplane predicted \\\ bird.jpeg truth
1/1 [==============================] - 0s
airplane predicted \\\ car.jpg truth
1/1 [==============================] - 0s
airplane predicted \\\ cat.jpeg truth
1/1 [==============================] - 0s
frog predicted \\\ deer.jpeg truth
1/1 [==============================] - 0s
ship predicted \\\ frog.jpeg truth
1/1 [==============================] - 0s
automobile predicted \\\| horse.jpeg truth
1/1 [==============================] - 0s
automobile predicted \\\ dog.tif truth
1/1 [==============================] - 0s
frog predicted \\\ ship.jpeg truth
1/1 [==============================] - 0s
airplane predicted \\\ truck.jpeg truth

Process finished with exit code 0
```

**Comment by alyato** [comment]
@mpt5  Do you try to another function calling `model.predict`
