### ISSUE TITLE
Could anybody please tell me how I can put an addition of two input tensor to a network?

### ISSUE THREAD

**Issue by friskit-china** [fchollet/keras#293]
In theano, I can make a layer which declare two tensor variable and just add them up. And then use the result as the input of next layer (hidden layer for example).

Here is an example I wrote by Theano:
```
class PlusNoiseLayer(object):
    def __init__(self, theano_rng, speech_spec, noise_spec, noise_raito_low, noise_ratio_high):
        ratio = theano_rng.uniform(low=noise_raito_low, high=noise_ratio_high)
        mixed = (speech_spec + ratio * noise_spec)
        self.output = mixed
```

Sorry for my poor English expression and please help me. TAT

**Comment by lemuriandezapada** [comment]
I think this can be achieved by just using a merge layer

**Comment by friskit-china** [comment]
@lemuriandezapada Thank you!!!! lol

**Comment by friskit-china** [comment]
@lemuriandezapada

**Comment by friskit-china** [comment]
@lemuriandezapada Thank you! I think I know how to do that!

**Comment by friskit-china** [comment]
@lemuriandezapada Sorry, I still have a question.

I want two of my input tensor add directly. But merge layer will attach additional weight to train.

Does it have impact?

**Comment by friskit-china** [comment]
I think I find a solution to do that. But I don't know will it works.

I can write a class extends Layer, and overwrite its get_output method in order to let it return input directly. So the right and left model to merge no longer have trainable weights.

**Comment by lemuriandezapada** [comment]
keras.layers.core.Merge(models, mode='sum')

Merge the output of a list of models into a single tensor, following one of two modes: sum or concat.

    Arguments:
        models: List of Sequential models.
        mode: String, one of {'sum', 'concat'}. sum will simply sum the outputs of the models (therefore all models should have an output with the same shape). concat will concatenate the outputs along the last dimension (therefore all models should have an output that only differ along the last dimension).


I think you can just say:
left = Sequential()
right = Sequential()
model = Sequential()
model.add(Merge([left, right], mode='sum'))

So you just merge the inputs directly. Merge doesn't have from what I can see the "cannot be used as first layer" restriction. This way your inputs just get summed up and then fed into the network with no actual weights to train.
