### ISSUE TITLE
Scaling the weights and Learn the scale factor

### ISSUE THREAD

**Issue by judyweiying** [fchollet/keras#2930]
Dear all,

Is it possible to scale weights with a factor,  as the following figure states,  and learn the factor dynamically? Thank you for your help very much!
![question](https://cloud.githubusercontent.com/assets/5757646/15882409/d3274c4c-2d70-11e6-856c-6dca7572ed9f.png)

Best Regards,
Ying

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
It would be easy to implement a new layer that does this. Just add the scale factor to the trainable weights of the layer.
