### ISSUE TITLE
very very eager to know how extract input gate,output gate and forget gate from LSTM

### ISSUE THREAD

**Issue by gamehere007** [fchollet/keras#2945]
Hi! Dear All,

I know we can get the weights of LSTM by using "model.get_weights()". And it returns to me a 14-dimnesion list. I understand that the first 12 elements are:
W_i,  U_i,   b_i
W_c, U_c,  b_c,
W_f,  U_f,   b_f,
W_o, U_o,  b_o
But I don't know understand what are the last two elements.

Moreover, my final thought is to extract input gate _i(t)_,output gate _o(t)_ and forget gate _f(t)_ in terms of time. Is there any easy and quick way to extract them. 

I worte a code by myself trying to get  _i(t)_, _o(t)_ and  _f(t)_  but it looks like it does not give me the right matrix. If it is necessary, I can post my code later.

Many thanks! These questions are really bothering me for a long time.

Best,

Oscar

**Comment by ChristianThomae** [comment]
`model.get_weights()` returns all weights of your model, including but not exclusively the weights of the LSTM layer.
Use `model.layers[x].get_weights()`, where x is a number, to get the weights of a specific layer.

**Comment by gamehere007** [comment]
@ChristianThomae 
Hi! Christian! Thanks! I figure out the last two weight matrices are from my dense layer. The things I am more interested in is the input gate, output gate and forget gate. Do you have any good ideas to get them easily and quickly. Many thanks! I look forward to your reply.


Best,

Oscar
