### ISSUE TITLE
Can we add TimeDistributed to an Embeddings layer? 

### ISSUE THREAD

**Issue by dpanshu** [fchollet/keras#2949]
I have a model which contains Paragraphs. Paragraphs in turn contains Sentences. Thus I want to feed in a (Batch_size, nb_para_in_document, nb_sent_in_para) to my embedding layer as input to my Embedding layer and obtain a (Batch_size, nb_para, nb_sent, Word_vector) as ouput. I tried using TimeDistributed(Embedding(10000, 64), input_shape = (20, 10)) but it raises 
''TypeError: index must be integers''

**Comment by braingineer** [comment]
whichever layer before that one needs to be of type 'intX' (int32, etc) for it to be used in an Embedding. 

But more importantly, embedding isn't restricted to 2-dimensional tensors.  Any dimensional object you use to index into a matrix will return the rows as being indexed by the final dimension.

In other words:

```python
X = np.arange(100).reshape(10,2,5)
E = np.arange(1200).reshape(100, 12)
M = E[X]
assert M.shape == (10, 2, 5, 12)
```
