### ISSUE TITLE
How to load images if memory is not enough.

### ISSUE THREAD

**Issue by dsy412610** [fchollet/keras#2953]
Hi,
As I know, all the images are loaded into memory at once before training (using model.fit). But when the image dataset is too large, it's impossible to load all them at once. So how to solve this problem? Thanks!

**Comment by fchollet** [comment]
Use `model.train_on_batch` or `model.fit_generator`. See e.g. http://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html
