### ISSUE TITLE
How to merge two layers which have two different python generators as inputs

### ISSUE THREAD

**Issue by Kevinpsk** [fchollet/keras#2956]
Hi All,

I was wondering if you can merge two layers, each of which has a different python generator as input. 
I have checked the example on Keras documentation, but the inputs two both layers are ready made data. 

If I have two generators, I guess I need to use the fit.generator method to train the model, so shall I use something like the following?

model.fit_generator([generator1, generator2], samples_per_epoch, nb_epoch)

Shall I put two generators as a list or dictionary? 

Thank you very much for your help.

Cheers,
Shuokai

**Comment by ChristianThomae** [comment]
Use one generator, which yields both inputs as a list: `yield [X1, X2], y`

**Comment by Kevinpsk** [comment]
Hi Christian,

Thanks a lot for your help. I have got it working now. It is strange that in the fit.generator section of Keras documentation, it points to generating two inputs as a dictionary. I tried this method, and Keras complained about not able to find the data. I tried your method, it just worked! 

Thanks a lot again. 

Shuokai
