### ISSUE TITLE
When I  visualize the output of an intermediate layer, the layer's number is confusing.

### ISSUE THREAD

**Issue by KevinGUOgit** [fchollet/keras#2958]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
Unclear what the point of this post is.

**Comment by alyato** [comment]
@KevinGUOgit ，when you call `model.add`,it  is represented one layer. The index is from 0. Then you need count the index which layer you  want to visualize
