### ISSUE TITLE
Can't decode the out of bounds IndexError when fitting LSTM

### ISSUE THREAD

**Issue by kotrfa** [fchollet/keras#296]
Hello,

I am trying to use LSTM for predicting vectors of fixed length 12 based on input vectors of the same length 12. Unfortunately I can't get it work. The problem is that I'm not quite sure what input should be pasted into LSTM, since it is unclear in [examples](http://keras.io/examples/) and also in docs. I think I use an embedding layer wrong. 

Here is the minimal example:

```
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM

model = Sequential()
model.add(Embedding(12, 256)) # this might be the cause
model.regularizers = []
model.add(LSTM(256, 128, activation='sigmoid', 
               inner_activation='hard_sigmoid'))
model.add(Dropout(0.5))
model.add(Dense(128, 12))
model.add(Activation('sigmoid'))
model.compile(loss='mean_squared_error', optimizer='rmsprop')

## data preparation
import numpy as np
data = np.random.randint(1,100,(5000,12))

def pred_targ_split(datas):
    X = []
    y = []
    for sample, next_sample in zip(datas, datas[1:]):
        X.append(sample)
        y.append(next_sample)
    return(X,y)

# use 4000 for training, 1000 for testing
sp = 4000
X_train, y_train = pred_targ_split(data[:sp])
X_test, y_test = pred_targ_split(data[sp:sp+200])

model.fit(X_train, y_train, batch_size=16, nb_epoch=10)
```

error:
```
IndexError: index 2615 is out of bounds for axis 1 with size 12
```

What should I use instead? Thank you.

**Comment by wxs** [comment]
@kotrfa your first layer is an Embedding that can only take values in the range `[0-11]`. Your training data is being generated with values between `[0-100]` here: 

    data = np.random.randint(1,100,(5000,12))

You would need to change that to

    data = np.random.randint(1,100,(5000,12))

I also suspect you'll have issues because your y entries are going to be one entry shorter than your X entries. You probably want to do this as well:

    for sample, next_sample in zip(datas[:-1], datas[1:]):

**Comment by kotrfa** [comment]
Thank you very much.
