### ISSUE TITLE
Bug: When loading two sequential models, the second gets the input of the first one. 

### ISSUE THREAD

**Issue by dr-costas** [fchollet/keras#2966]
Hi, following my previous message I can now confirm the bug at loading the models. 

So, a minimum working example is: 

    from keras.models import model_from_json

    with open(model_1_file_name) as f:
        model_1 = model_from_json(f.read())
    with open(model_2_file_name) as f:
        model_2 = model_from_json(f.read())

Now, if someone checks the `model_1.input` and the `model_2.input` he will see that both are the same.

**Comment by dr-costas** [comment]
In case that automatic naming of the layers has been used, one can check the above bug by adding the following lines of code:

    model_1.input.name = 'new_name'
    print(model_2.input.name)

**Comment by dongfangyixi** [comment]
yeah, I have come across the same problem recently, anyone got a solution?

**Comment by fchollet** [comment]
The solution is to update Keras to the master branch.
