### ISSUE TITLE
Why TF-IDF matrix generated by keras.preprocessing.text.Tokenizer() has negative values?

### ISSUE THREAD

**Issue by soloice** [fchollet/keras#2974]
Say, if run the following script:

>>> import keras
>>> tk = keras.preprocessing.text.Tokenizer()
>>> texts = ['I love you.', 'I love you, too.']
>>> tk.fit_on_texts(texts)
>>> tk.texts_to_matrix(texts, mode='tfidf')

The output will be:
array([[ 0.        , -1.09861229, -1.09861229, -1.09861229,  0.        ],
       [ 0.        , -1.38629436, -1.38629436, -1.38629436, -1.38629436]])

But tf-idf values seems should be non-negative?

By the way, is there a neat way to get the word by its index, or the vocabulary (in the order of word indices) of the Tokenizer() class?  Say, sometimes I want to know what's the most frequent word in the documents, then I want to access word with index 1.

I can do it by running:
>>> vocab = tk.word_index.items()
>>> vocab.sort(key=lambda x:x[1])

This gives:
>>> vocab

[('i', 1), ('you', 2), ('love', 3), ('too', 4)]
But is it somehow hacky?

Thank you!

**Comment by soloice** [comment]
Thanks for your quick fixing.
Though, I'm afraid that this bug has **NOT** been fixed.  Because idf is not equivalent to 1/df.

Maybe the following code is more reasonable:
```
idf = np.log(1 +  self.document_count / self.index_docs.get(j, self.document_count))
X[i][j] = tf * idf
```

**Comment by henry0312** [comment]
I'm sorry.
you're right.

**Comment by soloice** [comment]
lol~

**Comment by henry0312** [comment]
@soloice please check whether the latest commit has fixed the issue.

**Comment by henry0312** [comment]
oh my gosh!
I forgot Python 2 completely since I use Python 3 🙄

**Comment by soloice** [comment]
Now it works, I think.
