### ISSUE TITLE
How to use  TimeDistributedDense layer before a RNN layer

### ISSUE THREAD

**Issue by yinruiqing** [fchollet/keras#2977]
@braingineer @fchollet 
I found we always use TimeDistributedDense layer after a RNN layer. If we can use it before  a RNN layer to reduce the dimension of the Input to RNN layer?

**Comment by braingineer** [comment]
If you have a 4-dimensional tensor and want to reduce it to 3-dimensions (or in general, d+1 to d), then you can do something akin to this, yes.  I have a layer called [Summarize](https://github.com/braingineer/ikelos/blob/master/ikelos/layers/distribute.py#L10) which does this.
