### ISSUE TITLE
Race condition during import with multiple processes on shared filesystem

### ISSUE THREAD

**Issue by rmcgibbo** [fchollet/keras#2982]
When multiple processes import keras simultaneously, there is a race condition with reading/writng the `~/.keras/keras.json` file here: https://github.com/fchollet/keras/blob/master/keras/backend/__init__.py#L15-L47. One process can be in the middle of writing the file while the other is trying to read it, leading to a failure when the reading process tries to decode the JSON.

**Comment by ksze** [comment]
#3498 is a duplicate of this, but that issue was marked closed first.
Fixed in https://github.com/fchollet/keras/commit/a4d191d4f97a8100a561b87802fdd6ab5db0ed26
