### ISSUE TITLE
Sparse Input Layer using Tensorflow

### ISSUE THREAD

**Issue by subu-cliqz** [fchollet/keras#2989]
Hi,

I was trying to define a sparse input layer using tensorflow. 
`SparseTensor(indices, values, shape)`
I defined Input layers to accept indices, values and shape. The model seems to compile, but I get issues with input/target size mismatch. 

The input is always the same shape in this case, while the target depends on the batch size. Do you have any tips on handling this situation ?

**Comment by dzhwinter** [comment]
did you find the sparseTensor Layer somewhere else? I'm working on it.

**Comment by subu-cliqz** [comment]
No, but I would be interested in working on it as well. Let me know if I can contribute in any way

**Comment by dzhwinter** [comment]
ok, i wanna to add sparse layer support to keras.  
 It seems need to add some 
1. add backend sparse convolution support in tensorflow and theano
2. write specific convolution layer 
3. convert input into sparse representation format.

In fact, I use text one hot encode method, I find that sparse convolution apply here properly. However, to the best of my knowledge, there is no other place must use sparse layer?

**Comment by kuza55** [comment]
@dzhwinter did you end up getting anywhere with this?
