### ISSUE TITLE
Enhancement Request: Replace dependence on PyDot with a better maintained alternative

### ISSUE THREAD

**Issue by dirkbike** [fchollet/keras#2990]
I think it may be possible to make the Keras visualize_util compatible with Python 3 by using NetworkX instead of PyDot. I do not have much experience with either, but it seems that NetworkX can provide the same GraphViz functionality and more while being better maintained and updated.

**Comment by rilut** [comment]
Agreed. PyDot can't be used on Windows, nor even `import pydot_ng as pydot`

**Comment by lemuriandezapada** [comment]
I failed to get pydot working in python3

**Comment by nouiz** [comment]
pydot_ng worked for me on windows and python 3.

**Comment by dirkbike** [comment]
It looks like NetworkX uses either PyGraphviz or PyDotPlus to interface with GraphViz.  I'm not sure if NetworkX provides a better graphing abstraction than directly using one of it's dependencies.  Also, Keras does try to import pydot-ng before falling back to pydot.  Based on GitHub stats PyGraphviz is the most active project followed by pydot-ng and then PyDotPlus.

**Comment by dirkbike** [comment]
Another thing to note is that the GraphViz website itself is frequently unavailable, and none of these modules will work without GraphViz: http://graphviz.org/

**Comment by cmyr** [comment]
I've had no problem with pydot_ng on python3 in ubuntu or macOS.
