### ISSUE TITLE
can Keras be modified to support SSD or faster-RCNN?

### ISSUE THREAD

**Issue by loveproxy** [fchollet/keras#2993]
I have no idea how to implement it, i like keras, caffe is too complicated!

**Comment by daweileng** [comment]
Hope #1669 can work soon

**Comment by rykov8** [comment]
If it is still interesting, I have ported SSD 300x300 model to Keras, it is supposed to be used with Tensorflow backend. However, I cannot say, that it is tested very well, but luckily it works for several examples.
You can find the port in this [repo](https://github.com/rykov8/ssd_keras), hope it helps.

**Comment by Walid-Ahmed** [comment]
@rykov8 
Thanks I executed your code.
I applied to some images I have and Yolo gave better results, is this expected?

**Comment by planaria158** [comment]
Hi Rykov8,
Thanks very much for the Keras port.  I've verified the inference works on my system.  Now, I am trying to train it from scratch on VOC.  It appears I need additional information on the various input formats for data needed for training?  
Thanks,
Mark

**Comment by planaria158** [comment]
Hi rykov8,

Thanks for porting this to Keras!  I've got it working under Keras 2.0 for inference.
Now, I'd like to try the training code.  Unfortunately, I don't the actual image frames that are referred to in SSD_training notebook.
Do you have these actual frames somewhere on the net?
(I'm assuming the boxes in prior_boxes_ssd300.pkl correspond to this actual training set; correct?)

Cheers,
Mark
