### ISSUE TITLE
Memory inefficient one-hot encoding in LSTM

### ISSUE THREAD

**Issue by prinsherbert** [fchollet/keras#2996]
I've seen some one-hot encoders in Theano and Keras code sniplets, for example in this Char-RNN(/LSTM) snipplet:

https://github.com/fchollet/keras/blob/master/examples/lstm_text_generation.py#L42

Very often one-hot encoded vectors are multiplied with a matrix, which simply extracts one row or column, depending on the order of the operands. This made me wonder why there are no indexing-layers and in particular why `keras.layers.LSTM` expects a one-hot encoded 2D input, instead of a index-encoded 1D input?

As similarly, `sparse_categorical_crossentropy` allows one to use more memory efficient targets w.r.t `categorical_crossentropy`, and 'Embedding`is a more input memory efficient version of`Dense` when applied to one-hot encoded data.

Or am I missing something?

**Comment by prinsherbert** [comment]
As far as I can investigate, forward / backward propagation (RNN-style) only applies x to a dot-product if consume_less == 'mem', so I would expect an `IndexLSTM` layer is plausible?

- https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L791
- https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L809

**Comment by mbollmann** [comment]
But Embedding basically is such an indexing layer, isn't it? You can set the weights manually if you want to, so you can essentially provide a mapping from indices to arbitrary vectors (even simple one-hot vectors if you want), and I believe there's now an option to "freeze" the weights so the layer doesn't get updated during training. Wouldn't this do what you describe?

**Comment by EdwardRaff** [comment]
It's similar but it's not the same as an LSTM model where the input matrix would become a one-hot selection, and the recurrent connections would then be dense. Since this is a model used in some papers, such as the generative text models by Alex Graves, it's a reasonable request IMO.

**Comment by prinsherbert** [comment]
the `Embedding` layer, suggested by @mbollmann, would reduce the dimensionality of the one-hot encoded data in a sensible way, more sensible than just using binary integer encoding. Even if the embedding weights are not trained well, they could be useful for a high enough output dimension. However, it is not equivalent to my suggestion, as @EdwardRaff confirmed.

I often have sequence-like datasets that (just) fit in memory when they are encoded as integers. Encoding them as one-hot integers, however, increases the consumption severely. That's a shame, because them you need al sorts of messy hard-disk caching code.

More importantly, Keras has a great potential for machine learning tasks where the system's design is not overfitted to the problem, but where the system is flexible (towards high-variance and low-bias) and still performs good due to the enormous amounts of data. For example, the Inception V3 network is also a good design for datasets other than ImageNet. Hence simplifying working with large data set is a great win.

**Comment by prinsherbert** [comment]
PS: I guess there are more place where such optimizations are possible, for example convolutional layers where the weight in one dimension is selected by an index can be practical for char-cnn networks where a 2d convolutional layer correlates samples of a (fixed size) discrete-valued sequence in one dimension, and selects the particular discrete symbol on the other.
