### ISSUE TITLE
pooling size > stride

### ISSUE THREAD

**Issue by soumith** [fchollet/keras#3]
Hey,

Last I checked, theano did not support max-pooling op with size > stride. For example:
```
MaxPooling2D(poolsize=(3, 3), poolstride=(2,2))
```

Does keras support it using the cudnn backend?

btw, great work guys!

**Comment by benanne** [comment]
`theano.sandbox.cuda.dnn.dnn_pool` supports it without problems (I've been using it for a couple of months). I think it was recently implemented for Theano's default pooling op as well, but I'm not sure how functional this implementation is at the moment.

**Comment by soumith** [comment]
cool! thanks benanne. Does that mean that there's no such equivalent operation on CPU?

**Comment by benanne** [comment]
No idea about that. I think they were working on that also, but I wouldn't know since I always run my code on the GPU anyway :)
