### ISSUE TITLE
Activity regularizer issues?

### ISSUE THREAD

**Issue by civiskdonahue** [fchollet/keras#300]
Hello,

I'm working with activity regularizers, but I'm having some trouble getting them to work. For example, just running the example code at http://keras.io/regularizers/:

from keras.regularizers import l2, activity_l2
model.add(Dense(64, 64, W_regularizer=l2(0.01), activity_regularizer=activity_l2(0.01)))

produces an error (can't import activity_l2), so later steps don't work. If I skip using activity_l2 and just use l2, I instead get an error saying there was "an unexpected keyword argument 'activity_regularizer'". I see people have been working on this recently (https://github.com/fchollet/keras/pull/241). Is it stable enough for me to just update?

**Comment by fchollet** [comment]
> produces an error (can't import activity_l2)

You are definitely not up to date with master. This change was introduced a couple days ago. Just pull master and reinstall.
