### ISSUE TITLE
TimeDistributed(Merge([t1, t2], mode='concat'))

### ISSUE THREAD

**Issue by pxlong** [fchollet/keras#3005]
I have checked the https://github.com/fchollet/keras/issues/2271, but still can not fix my problems.

If I want to merge two tensors (like codes showed blow) at each timestep, how to write a lambda layer? Since the lambda layer take one argument, how to concatenate two tensors? Is there any other methods to solve this problem?
```
lstm_2 = LSTM(128, return_sequences=True)(dropout_1)
lstm_goal = LSTM(128, return_sequences=True)(masking_goal)
merge_direction = TimeDistributed(Merge([lstm_2, lstm_goal], mode='concat'))
```
If I run the code, will get error "'TensorVariable' object has no attribute 'get_output_shape_at'"

**Comment by phdowling** [comment]
Just use a simple `merge` function, not a `Merge` layer (possibly related: #2788)

**Comment by pxlong** [comment]
@phdowling Thanks for your quick reply.
but when using merge function, it throws the following error: 

```
    merge_direction = TimeDistributed(merge([dropout_2, lstm_goal], mode='concat'))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/wrappers.py", line 84, in __init__
    super(TimeDistributed, self).__init__(layer, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/wrappers.py", line 9, in __init__
    self.uses_learning_phase = layer.uses_learning_phase
AttributeError: 'TensorVariable' object has no attribute 'uses_learning_phase'
```

**Comment by pxlong** [comment]
OK, I found this will work (just remove the TimeDistributed):
merge_direction = merge([dropout_2, lstm_goal], mode='concat')

@phdowling thanks again :)

**Comment by alyato** [comment]
@pxlong where is the function merge? and i just find the Merge layer.

**Comment by pxlong** [comment]
Hi @alyato,
you can find it at https://github.com/fchollet/keras/blob/master/keras/engine/topology.py  Line 1446

**Comment by fhdiaze** [comment]
I can not call a Timedistributed over a list of tensor. I get the next error becuase this wrapper is waiting a 3D tensor not a list:

AssertionError                            Traceback (most recent call last)
<ipython-input-60-4d6550a5ca76> in <module>()
     32 
     33 inputs = [Input(shape=(None, ) + frameDims), Input(shape=(None, 4))]
---> 34 att.model = TimeDistributed(att.model)(inputs)
     35 
     36 

/home/fhdiaze/.local/lib/python2.7/site-packages/keras/engine/topology.pyc in __call__(self, x, mask)
    458                 self.build(input_shapes[0])
    459             else:
--> 460                 self.build(input_shapes)
    461             self.built = True
    462 

/home/fhdiaze/.local/lib/python2.7/site-packages/keras/layers/wrappers.pyc in build(self, input_shape)
     85 
     86     def build(self, input_shape):
---> 87         assert len(input_shape) >= 3
     88         self.input_spec = [InputSpec(shape=input_shape)]
     89         if K._BACKEND == 'tensorflow':

AssertionError:
