### ISSUE TITLE
JSON/YAML loading not working with Lambda merge layers

### ISSUE THREAD

**Issue by carlthome** [fchollet/keras#3008]
It doesn't seem possible to save and load models to/from JSON or YAML if there's a Merge layer with a lambda.

**Comment by carlthome** [comment]
Similar https://github.com/fchollet/keras/issues/3001

**Comment by fchollet** [comment]
Have you updated Keras to master? Have you posted a code snippet to reproduce your issue?

**Comment by EdwardRaff** [comment]
Still an issue in #2582 in head version as well.
