### ISSUE TITLE
How to predict something?

### ISSUE THREAD

**Issue by beeekey** [fchollet/keras#3010]
Sorry, I feel a little bit stupid, but I can't help me other ways.

I'm playing with the reuters-example and it run fine. So I do have now a trained model. Thats where all examples end as far as I can see.

I read about to save the model. So I could load it later to use again.

But, how do I use these models to predict a new text? Do I use models.predict() ?

 Do I have to prepare this text in a special way? I tried it with 

```
import keras.preprocessing.text
text = np.array(['this is just some random, stupid text'])
print(text.shape)
tk = keras.preprocessing.text.Tokenizer(nb_words=2000, filters=keras.preprocessing.text.base_filter(), lower=True, split=" ")
tk.fit_on_texts(text)
pred = tk.texts_to_sequences(text)
print(pred)

model.predict(pred)
```

But I always get
```
(1L,)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-80-dbddb6dc0010> in <module>()
      5 tk.fit_on_texts(text)
      6 pred = tk.texts_to_sequences(text)
----> 7 print(pred.shape)
      8 print(pred)
      9 

AttributeError: 'list' object has no attribute 'shape'
```

Have you any reccomondations, how to start or follow up?

Thank you.

Kind regards
Ben

**Comment by soloice** [comment]
Yes, you should preprocess your training and testing data in the exactly same way.
If your are running the example file reuters_mlp.py, you should look at the line 30 (or line 29), which says:

`X_test = tokenizer.sequences_to_matrix(X_test, mode='binary')`

Then you know what you should do:
```
pred = tokenizer.sequences_to_matrix(text, mode='binary')
model.predict(pred)
```

Warning: I think you should use the same Tokenizer() as it is in the reuters_mlp.py instead of a newly created Tokenizer() object.

**Comment by soloice** [comment]
Well, I recommend you to learn some basic knowledge about Python objects, say: list, dict, etc.  
And some knowledge about useful libraries, say: numpy.

model.predict() accepts a numpy array as its parameter, rather than a list.

**Comment by beeekey** [comment]
Thank you very much for your help!

I'll try to dig deeper into python and kreas.

**Comment by feeeper** [comment]
Hi, @soloice 

> you should preprocess your training and testing data in the exactly same way.

So I have to use the same tokenizer for fitting model and for prediction for new data. So I wonder what the canonical way for saving tokenizer for future usage? Should I use any third-party libs for that (cPicke e.g.)? I didn't find any `save` method in `Tokenizer` class

**Comment by soloice** [comment]
@feeeper I'm afraid that you'll need to pickle it yourself.

**Comment by feeeper** [comment]
Thanks a lot for the answer!

**Comment by michael-erasmus** [comment]
@soloice @fchollet curious if this is still the case? I would love if it was possible to save the Tokenizer along side my model

**Comment by unnir** [comment]
agree with michael-erasmus, this feature is must have
