### ISSUE TITLE
Tensorflow/Theano inconsistency for convolutional2D on CPU (kernel flipping)

### ISSUE THREAD

**Issue by morgangiraud** [fchollet/keras#3015]
Hi everyone,

I was trying to load some model weights lately with both backend i just found that tensorflow backend is not convolving2D the same way as theano does it:

if you look at the theano's doc, it says it **flips** the kernel before convolving, tensorflow is not doing it.
This result into an upside down result between the two implementation:

theano backend result:
```python
[[[[  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  [[318 254 103]
   [364 281 153]
   [153 116 131]]

  [[  0   0   0]
   [  0   0   0]
   [  0   1  52]]]]
```
tensorflow backend result:
```python
[[[[  0   0   0]
   [  0   0   0]
   [  0   0   0]]

  [[131 116 153]
   [153 281 364]
   [103 254 318]]

  [[ 52   1   0]
   [  0   0   0]
   [  0   0   0]]]]
```
This is problematic on my side, there is tow way to fix it:
You can just set the flip flag to false in the Theano backend:
```python
conv_out = T.nnet.conv2d(x, kernel,
                             border_mode=th_border_mode,
                             subsample=strides,
                             input_shape=image_shape,
                             filter_shape=filter_shape,
                             filter_flip=False) <<< for example
```
or flip the kernel in Tensorflow
```python
kernel = tf.reverse(kernel, [False, False, True, True])
x = tf.nn.conv2d(x,kernel, strides, padding=padding)
```

I believe the best way to do it is as a flag you can pass to the convolution since Keras should probably be fully consistent between backend.

What do you think ?

**Comment by fchollet** [comment]
See: https://github.com/fchollet/keras/wiki/Converting-convolution-kernels-from-Theano-to-TensorFlow-and-vice-versa

**Comment by morgangiraud** [comment]
Thanks ! Miss that one.

I wonder, is there any particular reason why you prefer to keep both backend default behaviour instead of harmonizing them for Keras ?
