### ISSUE TITLE
Omit input dimensions (for hidden layers) and auto-calculate if not specified

### ISSUE THREAD

**Issue by simonhughes22** [fchollet/keras#303]
Most of the time when I have a bug it's because I haven't correctly figured out the input dimensionality for some hidden layer that's layered on top of a convolutional or max pooling layer. Can we have the code auto-compute the input dimensionality of non-input layers for ease of use? This would have saved me hours initially, as is how Passage works (you just specify the output dimensionality).

**Comment by fchollet** [comment]
We're thinking about it. It would require significant architecture changes, but it is doable.

**Comment by simonhughes22** [comment]
Awesome. On the flip side, it's forced me to better understand these operations :)

**Comment by fchollet** [comment]
To be honest I like having to specify both dimensions, because it helps you think about what the layer is doing (projections from space A to space B). It's the "functional" way to think about NNs, in terms of inputs and outputs, rather than in terms of hidden units.

However it is true that when it comes to convolutions and max pooling, computing the right values by hand can be a pain.

**Comment by simonhughes22** [comment]
I think it would help newer users. Deep learning is complicated, I frequently recommend keras as it's easy to use yet fully featured (and seems to work well!). I think that would help further in terms of approachability.

**Comment by simonhughes22** [comment]
Getting latest theano fixed the concat issue. Many thanks! I think you should maybe add a comment in the code or docs, as most people will pip install Theano, and who knows when it'll be fixed.

**Comment by ddofer** [comment]
Same - I was about to post an issue asking for help figuring out how to calculate the sizes when stacking convolutional layers. (I'm failing at calcing them)

**Comment by pranv** [comment]
@ddofer Please refer this excellent source: http://cs231n.github.io/convolutional-networks/
