### ISSUE TITLE
Here,how to get tensor value in call function of own layers?

### ISSUE THREAD

**Issue by xyzhang16** [fchollet/keras#3044]
Sorry, I'm a novice. 
I want to define a partial connect layer simalar to convolutional network, but it is non-weight sharing.
I have a problem about getting tensor value in call function.

def call(self, x, mask=None):
1.        output = K.dot(x, self.W)
2.        a=K.eval(output)  #  here
3.        return output
why is step 2 wrong? 
Wrong information:theano.gof.fg.MissingInputError: ("An input of the graph, used to compute dot....

**Comment by ymcui** [comment]
Because they are all "symbolic" representations.
You can just do `return output` without the second step.

**Comment by xyzhang16** [comment]
but if I want to fix something aim at output,  how to do that ?

**Comment by nitish11** [comment]
@xyzhang16  : You can't get the values from the tensor symbolic variable directly. Yo need to write a theano function to extract the value.

Check the notebook link below to get some basic of theano variables and functions : 
http://nbviewer.jupyter.org/github/craffel/theano-tutorial/blob/master/Theano%20Tutorial.ipynb#Functions

**Comment by xyzhang16** [comment]
@nitish11
thank you, I agree with you. But the above that could't be accessed. 
How is the function of extract the value defined?

**Comment by nitish11** [comment]
@xyzhang16 : the link is working. Checkout
http://nbviewer.jupyter.org/github/craffel/theano-tutorial/blob/master/Theano%20Tutorial.ipynb

Checkout the gist with the notebook code.  https://gist.github.com/nitish11/3c352153d8d1e74bdea5929b5f4190bd

**Comment by xyzhang16** [comment]
@nitish11  I get it, but thank you as the same. 
Now I want to define a partial connect layer simarly to convolutional layer in keras, but it is non-weight share. 
code is following:
`#coding=utf-8
'DIY：layer'
import numpy as np
from keras import backend as K
from keras.engine import  Layer

class PartialDense(Layer):

    def __init__(self, input_dim,size=1,  **kwargs):
        self.size=size
        self.output_dim = input_dim-size+1  # fix
        self.input_dim = input_dim
        kwargs['input_shape'] = (self.input_dim,)
        super(PartialDense, self).__init__(**kwargs)

    def build(self, input_shape):
        initial_weight_value=np.random.random((self.size,self.output_dim))
        self.W = K.variable(initial_weight_value)
        self.trainable_weights = [self.W]

    def call(self, x, mask=None):
        list=[]
        for i in range(self.output_dim):
            valve=K.dot(x[i:i+self.size],K.transpose(self.W)[i])
            list.append(valve)
        output=K.concatenate(list)
        return output

    def get_output_shape_for(self, input_shape):
        return (self.input_dim,self.output_dim)
`
why is it wrong? 
Exception: Input 0 is incompatible with layer dense_1: expected ndim=2, found ndim=1

**Comment by nitish11** [comment]
@xyzhang16  : If you want to implement locally connected layer in keras, this [https://github.com/fchollet/keras/pull/2658 PR] might be useful. 

Regarding the error, put input in an empty list, for example : 
`model.predict(test_image[None,:,:,:])`

**Comment by xyzhang16** [comment]
@nitish11  thank you very much.Best wish for you.

**Comment by xyzhang16** [comment]
@nitish11 
I wrote a toy example using locally connected layer in [#2658 PR] 
code:
`
x_test=np.random.random_sample((100,5))
y_test=np.random.randint(2,size=100)
model=Sequential()
model.add(LocallyConnected1D(nb_filter=1,filter_length=2,input_dim=5))
model.add(Flatten())
model.add(Dense(1))
model.compile(optimizer='sgd', loss='mse')
model.fit(x_test,y_test)

`
TypeError: an integer is required
why is it wrong?

**Comment by nitish11** [comment]
@xyzhang16 : I don't know the exact answer but based on my experiments, 
The below code is working. 
```
model=Sequential()
model.add(LocallyConnected1D(nb_filter=1,filter_length=2,input_shape=(5,2)))
model.add(LocallyConnected1D(nb_filter=1,filter_length=2,input_dim=5))
```
Theoretically, it should have worked based on http://keras.io/layers/convolutional/#convolution1d .
