### ISSUE TITLE
lstm for phoneme classification

### ISSUE THREAD

**Issue by Shlomke** [fchollet/keras#3046]
Hi all !
I'm new here, I'm trying to train a RNN using LSTM for phoneme classification. The input to the RNN is the 39 MFCCs coefficients of the current time frame, and the output is one of 39 phoneme classes (one hot).

I understand that  the expected input data shape is in the form: (batch_size, timesteps, data_dim).
I don't understand whatdoes  timesteps stand for?

I used this code:

```
data_dim = 39
nb_classes = 39

model = Sequential()
model.add(LSTM(32, return_sequences=True,
               input_shape=(None, data_dim)))  
model.add(LSTM(32, return_sequences=True))
model.add(LSTM(32)) 
model.add(Dense(39, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop')


model.fit(X_train, Y_train,
          batch_size=64, nb_epoch=5,
          validation_split=0.1)
```

and I keep geting this error:

TypeError: ('Bad input argument to theano function with name "C:\\winpython\\WinPython-64bit-3.4.4.2Qt5\\python-3.4.4.amd64\\lib\\site-packages\\keras\\backend\\theano_backend.py:442"  at index 0(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (64, 39).')

I'l be happy for some help..
Thanks

**Comment by myouness** [comment]
Hello,
I think you need :
 model.add(Dense(1))
model.add(Activation('sigmoid'))
at the end of your network

**Comment by Shlomke** [comment]
But its a multi class problem, I have 39 classes (indexes of the phonemes). Eventually I want to determine which phoneme was active now.

**Comment by myouness** [comment]
Yes, sorry about that.
Lstm expects something like (input_dim=xx, input_length=yy )
Input dim is the dimension of each element of your sequence and input_length is the length of your sequence.
You might need to reshape your input data so that each learning example is two-dimensional ( each row is a element of the sequence)
Hope that helps

**Comment by Shlomke** [comment]
Thanks for the quick answer! 
I just want to be sure - 
My input features are the MFCC vector for each time frame (length of 39), and lets say I have 10000 samples, so my X_train size is [10000,39] . I need to reshape X_train to have time-steps? To do so, i just need to take a window (with length of the time-steps) of my data. For example if i Chose time-steps=3, then X_train will be at size [9998,2,39]?
