### ISSUE TITLE
Test results visualization after each epoch

### ISSUE THREAD

**Issue by SpoorthyBhat** [fchollet/keras#3051]
I am implementing super resolution using Keras.  Is it possible to check the output image after every epoch in keras?

**Comment by nitish11** [comment]
@anna1123  : You can try getting the outputs using Keras callbacks.

Checkout : http://keras.io/callbacks/


Sample code to use callback :
```

from keras.callbacks import ModelCheckpoint, Callback

#saves the model weights after each epoch if the validation loss decreased
#you can write custom theano function here. 
checkpointer = ModelCheckpoint(filepath=save_location+"/model_weights_23.hdf5", verbose=1, save_best_only=True)

odel.fit(X_train, Y_train, batch_size=1,nb_epoch=5, verbose=1,callbacks=[checkpointer])
```
Try it out and let me know if you figured out some better way.

**Comment by AdityaGudimella** [comment]
You could always run it for a single epoch, print the image, run it for another epoch and so on.

```
for _ in range(np_epochs):
    model.fit(X_train, Y_train, batch_size=1,nb_epoch=1, verbose=1)
    print_image()
```
