### ISSUE TITLE
Layer with multiple outputs

### ISSUE THREAD

**Issue by AdityaGudimella** [fchollet/keras#3061]
How do I implement a custom layer which returns multiple outputs instead of a single one?

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by rilut** [comment]
Something like this

```python
.......
main_out = Dense(num_classes, activation='softmax')(the_layer_before)
auxiliary_out = Dense(num_aux_classes, activation='softmax')(the_layer_before)

model = Model(input=layer_in, output=[main_out, auxiliary_out])
model.compile(your_optimizer, 'categorical_crossentropy')
model.fit(X_train, [y_main, y_aux])

yp_main, yp_aux = model.predict(X_test)
```

**Comment by rilut** [comment]
Something like this

```python
.......
main_out = Dense(num_classes, activation='softmax')(the_layer_before)
auxiliary_out = Dense(num_aux_classes, activation='softmax')(the_layer_before)

model = Model(input=layer_in, output=[main_out, auxiliary_out])
model.compile(your_optimizer, 'categorical_crossentropy')
model.fit(X_train, [y_main, y_aux])

yp_main, yp_aux = model.predict(X_test)
```

And please consider closing this issue if this solves your problem.

**Comment by AdityaGudimella** [comment]
@rilut I'm not talking about implementing a model with multiple outputs. I'm talking about implementing a custom layer with multiple outputs. Something along the lines of:

```
class CustomLayer(Layer):
    def __init__(self, *args):
        # do initialization here

    def call(self, inputs):
        # do something with inputs
        return output1, output2, output3

    def build(self, input_shape):
        # initialize weights
```

Unfortunately when I do the above, it gives me an error saying tuple object does not have attribute _keras_shape. What is the correct way to do this?

**Comment by andreatg** [comment]
I am having the same issue. Did you find a solution?

**Comment by eakbas** [comment]
An upvote for this issue!

**Comment by waleedka** [comment]
Another up vote. My guess is that this option is not available. I haven't seen any of the built-in Keras layers return more than one output. 

My hacky work-around is to merge the outputs into one tensor, and then later split it to multiple tensor. It could be more more elegant, though, if Keras supports multiple outputs.

**Comment by rjrowekamp** [comment]
I seem to have a layer with multiple outputs working.

1. I manually set _keras_shape for each tensor the layer returned in call.
2. I wrote compute_mask to return n_output * [None]
3. I wrote compute_output_shape to return the shapes of the outputs.

**Comment by waleedka** [comment]
@rjrowekamp Thanks! I gave it another try and managed to get it working as well, but with slightly different approach. 

1. Let compute_output_shape() return a list of shapes.
2. Let call() return a list of outputs.
3. For easier debugging, set the shapes of returned tensors as such:
```
output_shapes = self.compute_output_shape([K.int_shape(i) for i in inputs])
for o, s in zip(outputs, output_shapes):
    o.set_shape(s)
```

This is mostly working. But it broke the Tensorboard callback (which seems to assume that all layers return one tensor). I disabled the histogram summary in that callback and that allowed me to side-step the bug for now.

**Comment by vqdang** [comment]
@waleedka 
May I ask what errors were thrown by Tensorboard callbacks? I'm wondering if it is the same bug I encountered. This is what I did using a custom layer with hint from @rjrowekamp .

```
class SplitLayer(Layer):

    def __init__(self, n_splits, split_axis = 3, **kwargs):
        self.n_splits = n_splits
        self.split_axis = split_axis
        super(SplitLayer, self).__init__(**kwargs)

    def call(self, x):
        sub_tensors = tf.split(x, self.n_splits, axis = self.split_axis)     
        return sub_tensors

    def compute_output_shape(self, input_shape):
        sub_tensor_shape = list(input_shape)
        num_channels = sub_tensor_shape[-1] 
        sub_tensor_shape[-1] = int(num_channels / self.n_splits)
        sub_tensor_shape = tuple(sub_tensor_shape)
        list_of_output_shape = [sub_tensor_shape] * self.n_splits
        return  list_of_output_shape

    def compute_mask(self, inputs, mask=None):
        return self.n_splits * [None]
```

 My callback still worked but the graph would not display, everything else seemed to be fine though.

**Comment by waleedka** [comment]
@vqdang The TensorBoard callback was trying to create a histogram of the outputs of each layer, and I believe it assumes that all layers generate one output (or similarly shaped outputs). So it was complaining that the shapes and data types of the outputs didn't match. I disabled the histogram feature by setting its frequency to zero as such:

```
keras.callbacks.TensorBoard(log_dir=log_path, histogram_freq=0, 
                            write_graph=False, write_images=False)
```

**Comment by agamemnonc** [comment]
It seems that the plot_model function cannot handle this situation very well, i.e. when a layer returns multiple outputs the visualisation ignores this information and draws a single arrow for the output variables.

**Comment by kureta** [comment]
@agamemnonc at some point `plot_model` used to normally handle this situation as seen on [this web page](http://tiao.io/posts/implementing-variational-autoencoders-in-keras-beyond-the-quickstart-tutorial/), at the output of KLDivergenceLayer. But now it behaves as you've stated.

**Comment by Zhangtd** [comment]
Same problem. Is there any solutions?
