### ISSUE TITLE
Add support for vector in/out for LSTM

### ISSUE THREAD

**Issue by kotrfa** [fchollet/keras#307]
Hello,

it would be great to be able to be able to train LSTM on the 2D vector in -> 2D vector out basis, like is e.g. [OCRopus](https://github.com/tmbdev/ocropy/blob/master/ocrolib/lstm.py) or in [Pybrain](http://pybrain.org/docs/tutorial/netmodcon.html#using-recurrent-networks).

I am not able to easily reproduce this with Keras right now, since LSTM wants 3D array. I couldn't figure out how to simply transfer matrix, where rows are vectors of integers in specific timestep to this 3D format.  

Thank you

**Comment by fchollet** [comment]
You need to use the constructor argument `return_sequences=True`. I believe the documentation covers all of this.
