### ISSUE TITLE
Puzzle about the initialization of the input attribute of first layer

### ISSUE THREAD

**Issue by marearth** [fchollet/keras#308]
Have explored the implementation code for a few days,and had a basic understanding of the implementation architecture.However,some puzzle confused me and kept me from getting ahead. For example, the input attribute of first layer seems not to be initialized by value of input examples(e.g., X_train). Therefore,the y_train of model can not be computed correctly in a recursive way. Surely I have missed out something,but could you give me some indications? PS: I'd like to implement a local response normalization layer.

**Comment by fchollet** [comment]
I recommend you to familiarize yourself with Theano; the deeplearning.net tutorials are a great resource: http://deeplearning.net/software/theano/

LRN layers will come to Keras in the near future.
