### ISSUE TITLE
Error with keras module import

### ISSUE THREAD

**Issue by AliusEquinox** [fchollet/keras#3081]
Hi,
That was my first time with keras and I encountered an error when following the "getting started" sequential guide.

I installed keras by first building my own numpy and then installing keras with pip. Then I tried to import keras module with a simple $python -c "import keras" but gives me that error :

First, it says me that it uses the Theano backend (ok),
Then it writes some python code (see that [pastebin](http://pastebin.com/hEXvQV2k)) (weird)
Finally it recommends me to recompile it with -fPIC gcc flag because it cannot : "relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC." (what's going wrong?)

I would like to know how to add this -fPIC flag to the compilation line, or what's going wrong with my keras.

Thank

**Comment by henry0312** [comment]
Build your python with `--enable-shared`

**Comment by AliusEquinox** [comment]
it works perfectly ! thank you so much

Now I'm wondering how... Did I miss something? Is there a solution that doesn't need python to be built ?

**Comment by henry0312** [comment]
I don't know.
That depends on your system (environment).

**Comment by AliusEquinox** [comment]
I'm working on ubuntu server 14.04, with CUDA
