### ISSUE TITLE
Any interest in having a graphical gallery of examples for Keras?

### ISSUE THREAD

**Issue by emmanuelle** [fchollet/keras#3083]
I would like to know if users and developers of Keras would be interested in having a graphical gallery of examples for Keras, like the ones of matplotlib, scikit-learn or scikit-image (see http://scikit-learn.org/stable/auto_examples/index.html and http://scikit-image.org/docs/dev/auto_examples/). 

Thanks to the new `sphinx-gallery` package, it is now quite easy to build a gallery for a project that already has scripts for examples, as Keras does.

If there is sufficient interest, I could give a hand with the gallery.

**Comment by marcj** [comment]
Yeah, sure!

**Comment by fchollet** [comment]
Yes, I think that would be cool.
