### ISSUE TITLE
How does Masking work?

### ISSUE THREAD

**Issue by poyuwu** [fchollet/keras#3086]
I'm wondering how `Masking` Layer works.
I try to write simple model to test `Masking` on `Activation` Layer

``` python
from keras.models import Model
import numpy as np
from keras.layers import Masking, Activation, Input
a = np.array([[3.,1.,2.,2.,0.,0.]])

inputs = Input(shape=(6,))
mask = Masking(mask_value=0.0)(inputs)
softmax = Activation('softmax')(mask)
model = Model(input=inputs,output=softmax)
model.predict(a)
```

and the result of prediction is 

```
array([[ 0.50744212,  0.06867483,  0.18667753,  0.18667753,  0.02526405,
         0.02526405]])
```

Is this the correct behavior?
My keras version is 1.0.5

**Comment by ipoletaev** [comment]
I'm also interested with this question. It seems to me you expected to get something like the following: [[ 0.53444666  0.07232948  0.19661194  0.19661194]] ?

**Comment by poyuwu** [comment]
@ipoletaev 
yes, sure. However keras can also return `[[ 0.53444666, 0.07232948, 0.19661194, 0.19661194, 0.0, 0.0 ]]` by padding it to keep shape.
Here is another example about `Masknig` on bi-LSTM layer but `sum` two layer
```python
from keras.models import Model
import numpy as np
from keras.layers import Masking, Activation, Input, LSTM, merge
a = np.array([[[.3,.1,.2,.2,.1,.1],[.2,.3,.3,.3,.3,.1],[0,0,0,0,0,0]]])

inputs = Input(shape=(3,6))
mask = Masking(mask_value=0.0)(inputs)
fw = LSTM(1,return_sequences=True)(mask)
bw = LSTM(1,return_sequences=True,go_backwards=True)(mask)
merged = merge([fw,bw],mode='sum')
model = Model(input=inputs,output=fw)
model2 = Model(input=inputs,output=bw)
model3 = Model(input=inputs,output=merged)
```
what `fw`'s output is 
`array([[[-0.07041532],
        [-0.12203699],
        [-0.12203699]]])
`
what `bw`'s output is 
`array([[[ 0.        ],
        [-0.03112165],
        [ 0.02271803]]])
`
what `merge`'s output is
`array([[[-0.07041532],
        [-0.15315863],
        [-0.09931896]]])
`
but I think it should be (Here it also can padding 0 to keep shape.)
`array([[[-0.10153697],
        [-0.09931896]]])
`
which `-0.10153697 = (-0.07041532) + (-0.03112165)` and `-0.09931896 = -0.12203699 + 0.02271803 `
Is is anything wrong on Keras?

**Comment by ipoletaev** [comment]
@poyuwu
> However keras can also return [[ 0.53444666, 0.07232948, 0.19661194, 0.19661194, 0.0, 0.0 ]] by padding it to keep shape.

Hmm... I don't know how to make such out only through the Keras. 

About your example: I think it's similar to the aforementioned example, so you should get `array([[[-0.07041532], [-0.15315863], [0.02271803]]]) `. And it's really strange that `bw` works right but `bw` doesn't, because of its third output is not equal to zero, but it must.

**Comment by lomizandtyd** [comment]
Hi guys, I got this question too.. Especially for LSTM (BRNN).

Masking Layer gives an masked vector, only work for the inputs, not for inner states.
So in @poyuwu 's example, the fw's output still has value in step 3.

This might be correct because inputs are surely masked.
While, I want to find a way to skip the calculation step when coming masked value.

Using Masking layer in bidirectional RNN for sequences with different lengths may be totally wrong.

**Comment by ipoletaev** [comment]
@lomizandtyd
> So in @poyuwu 's example, the fw's output still has value in step 3. 

Yes, it's logically, but in any case we want get zero at the third place, isn't it?

>While, I want to find a way to skip the calculation step when coming masked value.

I think it doesn't matter because of as I understood you should specify output `sample weights` in `fit()` in order to skip necessary timesteps with all zeros in feature vector.

**Comment by lomizandtyd** [comment]
@ipoletaev  Wow, thanks a lot for this!

Yes,  we want to get zero at the masked position.
The problem is we also want to keep the inner states across the masked step.

Maybe we can deliver another `sample_weights` in the `predict()` function?.
If do so, BRNN is still wrong...

**Comment by ipoletaev** [comment]
@lomizandtyd 

>...keep the inner states across the masked step.

I think it's not necessary, because the network shouldn't remember what responses it need to get at empty vectors...

>Maybe we can deliver another sample_weights in the predict() function?.

I don't understand for what task you want to use it? After all you always know in advance what data you process, and you respectively know - which output of the network corresponds to the empty vector, so you can just skip such positions in output, I think.

**Comment by poyuwu** [comment]
> from keras.models import Model
import numpy as np
from keras.layers import Masking,Input,TimeDistributed,Dense
a = np.array([[[3,1,2,2,0,0],[0,0,0,0,0,0],[2,1,1,2,0,0]]])
input = Input(shape=(3,6))
mask = Masking(mask_value=0)(input)
out = TimeDistributed(Dense(1,activation='linear'))(mask)
model = Model(input=input,output=out)
q = model.predict(a)
print (q[0])

@ipoletaev I think it's just `Dense` Layer that have zero inputs, so that its output is 0. If you change activation function to `softmax`, then you will get wrong answer.
Besides, batch_size set `None` on time steps will raise other error in some case (especially on merge layer).

In lasagne, it seems to use Masking matrix to deal with padding. (I do not test its accuracy)

**Comment by ipoletaev** [comment]
@poyuwu : yes, I had checked it - and you are right. It means,as I understood, that and simple `Dense` doesn't keep masked values... 

I write again what does not converge with the expectations:
- Forward RNN doesn't keep mask values, backward does it. It's strange.
- Is this task solving with `batch_size` = 1?
- How to specify correctly what timesteps the network should to skip.

**Comment by poyuwu** [comment]
@ipoletaev I don't think 
> - Forward RNN doesn't keep mask values, backward does it. It's strange.

this statement is true. 
That's because `padding` argument is 'post', not 'pre'. Hence, the reason is the same as Dense layer I said.
> - How to specify correctly what timesteps the network should to skip.

As I said, in lasagne, we provide a mask numpy.array (the same shape as input) to deal with it. Besides, if ```go_backwards=True```, it needs to keep `padding` argument the same.

**Comment by ipoletaev** [comment]
@poyuwu so you want to say that now, there's no way to solve this issue with Keras?

**Comment by xuewei4d** [comment]
Same here. It seems masking mechanism in Keras is not fully supported.

**Comment by CarlosVaquero** [comment]
Does the merge function after masking and pre-padding already work?

**Comment by fferroni** [comment]
I don't think Masking masks input values (neither during forward or back-propagation). It just skips a time-step where all features are equal to the mask value (i.e. when you pad a sequence). You can confirm this by:

```
from keras.models import Model
import numpy as np
from keras.layers import Masking, Activation, Input, TimeDistributed, Dense

if __name__ == "__main__":
	a = np.array([[[3,1,2,2,0.1,0.1],[0,0,0,0,0,0],[2,1,1,2,0.1,0.1]]])
	print 'Input array:'
	print a
	print ''
	input = Input(shape=(3,6))
	mask = Masking(mask_value=0.1)(input)
	out = TimeDistributed(Dense(1, activation='linear'))(mask)
	model = Model(input=input, output=out)

	model.set_weights([np.array([[ 1. ],
							     [ 1. ],
							     [ 1. ],
							     [ 1. ],
							     [ 1. ],
							     [ 1.]], dtype=np.float32), 
	                   np.array([ 0.], dtype=np.float32)])

	print 'Weights'
	print model.get_weights()
	q = model.predict(a)
	print q
```

The answer is:
```
Input array:
[[[ 3.   1.   2.   2.   0.1  0.1]
  [ 0.   0.   0.   0.   0.   0. ]
  [ 2.   1.   1.   2.   0.1  0.1]]]

Weights
[array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]], dtype=float32), array([ 0.], dtype=float32)]
[[[ 8.20000076]
  [ 0.        ]
  [ 6.19999981]]]
```

If it masked the inputs of value 0.1, you would expect result to be 
```
[[[ 8.       ]
  [ 0.        ]
  [ 6.        ]]]
```

**Comment by Fragore** [comment]
Actually Masking works exactly as expected. The problem is that you are working with the wrong dimensions: in input = (3,6) the 3 is the time dimensions, so masking masks only along that dimension.



```
import keras
from keras.utils.visualize_util import plot
from keras.layers import *
from keras.models import Model

net_input = Input(shape = ( 3, 10))
mask = Masking(mask_value = 0.5)(net_input)
conv = TimeDistributed(Dense(1, activation = 'linear', init='one'))(mask)
#perm = Permute((2,1,3,4))(conv)
out = LSTM(1, init='one', inner_init='one',activation='tanh', inner_activation='tanh',)(conv)
model = Model(net_input, out)

print('W: ' + str(model.get_weights()))

in = np.ones((1,3, 10))
val = 0.5
in[0, 2, :] = val
out = model.predict(in)
print('Input: ' + str(in))
print('Output: ' + str(out))
```

In this case the answers are:

```
mask = 0.5 val = 0.0 : 0.73566443
mask = 0.0 val = 0.0 : 0.96402758
mask = 0.0 val = 0.5 : 0.99504161
mask = 0.5 val = 0.5 : 0.96402758
```

so from here you can see that when we mask `val` we get  the same result.

**Comment by Fragore** [comment]
Moreover, I just tested, if you have a Multi-input net (with multiple input branches) and you have a masking layer on each branch, it is enough that just one of the inputs at time step `t` is equal to the masked value that all the time step is skipped.

If you want to skip the time step only when all the inputs are equal to the masked value, you need to have a shared Masking layer.

**Comment by irrationalagent** [comment]
Hi Fragore, I have a similar question to you about masking with multiple inputs. I have two input branches and all I want to do is mask 0 from both. Am I right in thinking that adding a mask to the end of each branch is equivalent to adding a single mask AFTER the inputs are merged? here's my example

`input1 = Sequential()
input1.add(TimeDistributed(Dense(50), input_shape=(MAX_SEQUENCE_LENGTH,48)))
# input1.add(keras.layers.core.Masking(mask_value=0.0)) heres where I would add a pre-merge mask
input2 = Sequential()
input2.add(Embedding(nb_words+2,EMBEDDING_DIM,weights=[embedding_matrix],trainable=False,input_length=MAX_SEQUENCE_LENGTH)) #then I could add mask_zero = True here

model = Sequential()
model.add(keras.engine.topology.Merge([input1,input2],mode='concat',concat_axis=-1))
model.add(keras.layers.core.Masking(mask_value=0.0))
model.add(LSTM(1024,dropout_W=.2,dropout_U=.2,return_sequences=True))
model.add(LSTM(1024,dropout_W=.2,dropout_U=.2,return_sequences=True))
model.add(LSTM(512,dropout_W=.2,dropout_U=.2,return_sequences=True))
model.add(TimeDistributed(Dense(nb_words + 1)))
model.add(Activation('softmax'))
`

**Comment by Fragore** [comment]
Wait, you want to mask the output of the branches that are 0? In that case both of your approaches should give you the same result. But usually you mask inputs, this means to put the mask layer as input of the net. 
Ps it may also be more convenient to use the functional API :)

**Comment by slaterb1** [comment]
I've been experimenting with an without masking for a little bit now and I have finally figured out what the Masking layer actually does. It doesn't actually "skip" the timepoint that has all masked values, it just forces all the values for that timepoint to be equal to 0... So effectively Masking(mask_value=0.) does nothing. That is why in the example provided by @GPaolo  above the results for mask_value=0 and mask_value=0.5 are the same when val matches them.

Here is some easy code to demonstrate what I mean.

Model:

`input1 = Input(batch_shape=(1,1,10)
mask1 = Masking(mask_value=2)(input1)
dense_layer1 = Dense(1, activation='sigmoid')
dense_layer1.__setattr__('supports_masking', True)
output1 = dense_layer1(mask1)

model = Model(input1, output1)
model.compile(optimizer='adam', loss='binary_crossentropy')
`
Data:

`data = np.ones((10, 1, 10), dtype='float32')
#set half of the data equal to mask value
for index in range(5,10): 
	data[index,0,:] = 2

#set first data point equal to mask value to show that this line is uneffected
data[0,0,0] = 2`

print outputs:

`get_mask_output = K.function([model.layers[0].input], [model.layers[1].output])
mask_output = get_mask_output([data])[0]

print(data)
print(mask_output)

[[[ 2.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]]



[[[ 2.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]]`

Predictions:

`test_data = np.ones((5,1,10))
test_data[1,0,:] = 2
test_data[2,0,:] = 0
predictions = model.predict(test_data, batch_size=1)

print(test_data)
print(predictions)
`

Results:

`[[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]]

[[[ 0.09200736]]

 [[ 0.5       ]]

 [[ 0.5       ]]

 [[ 0.09200736]]
 
 [[ 0.09200736]]]`

As you can imagine, "masking" values by setting them to 0 and still calculating the results for those lines in layers causes some mistakes from backpropagation (treating unknown values as a real result) as well as added unneeded computation time. I'm going to try to rework how masking is done in Keras a bit...

**Comment by ragulpr** [comment]
Building on @slaterb1  and @GPaolo 's snippets  I tried digging around to see the benefits of masking but haven't found it yet. It feels like I'm missing something.

- It does not seem to propagate numerically sound values through time
- It propagates np.nan, see [gist](https://gist.github.com/ragulpr/601486471549cfa26fe4af36a1fade21)
- Feels (TODO:test) quite numerically unstable to propagate possibly absurd values down the network?
- It has to test each input
- Quick testing (see [gist](https://gist.github.com/ragulpr/4353ff31a665021ab2d91de84ec20348)) seem to show that there's no immediate performance gains

Does anyone have an idea about if/when it gives performance gains? I didn't have time to run for long and I'm not comfortable about how Python/Keras/Tensorflow/Theano compiles

Have I misunderstood or is mask an intricate way of doing what I think weights would to be doing? I.e multiplying with the loss and dividing by sum of weights in batch? 
It's literally what seems to be done here anyway:
https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L453

Does it actually halt any execution?

**Comment by carlthome** [comment]
@ragulpr, it's my understanding that masking does do more than just scale the loss. If a timestep has been masked, the previous output and state will be reused. See [here](https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L2230) and [here](https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L2237-L2239).

**Comment by slaterb1** [comment]
@ragulpr, I'm not sure about performance gains but Theano is pretty smart about knowing what it needs to hang on to and what it doesn't (based on the API doc: http://deeplearning.net/software/theano/library/scan.html) 

More specifically this line: "Note that there is an optimization, that at compile time will detect that you are using just the last value of the result and ensure that scan does not store all the intermediate values that are used. So do not worry if A and k are large."

So after compiling the model it might pass over the masked values (or at least not hold them in memory as long), but that is pure speculation based on similarities in the underlying code.

@carlthome, I came across the mask snippet in the "theano_backend.py" as well and you are right that the masking  has a direct effect on how the states are evaluated and passed on (T.switch). Maybe this is too general a question but how does this layer accept the mask? Just to give an example, if I have a model with multiple layers, defined as so:

**model = Model(input1, output1)**

I understand that Theano wraps this up as a mathematical equation to calculate:

**output1 = input1 -> [ layers[0] -> layers[1] -> ... layers[N] ]**

but if I have somewhere in the middle: 

 **prev_layer -> Masking_layer -> RNN_layer** 

The output from the Masking_layer gets put into the RNN_layer as input ("x"). Does the "supports_masking" attribute tell the RNN_layer to figure out the mask? I could not find anywhere in the code where the mask is evaluated or interpreted by the RNN_layer, except that I can pass in a "mask" variable via the call() method of the Recurrent(Layer) object. 

I tried calling **RNN_layer(prev_layer, mask=Masking_layer)** but it didn't do anything different. The last comment in the thread, https://github.com/fchollet/keras/issues/176 suggests that it has to be called with a mask but I'm not sure how to do that... Any thoughts?

**Comment by carlthome** [comment]
> I could not find anywhere in the code where the mask is evaluated or interpreted by the RNN_layer

Each Keras layer declares if it supports masking. Each layer is also responsible for using the mask in a sensible way (which I believe is the primary source of confusion: that the masking functionality is implemented across a bunch of different classes). For RNN layers in particular, they rely on the fact that the underlying `K.rnn` operation has mask support so if you're looking for where precisely the logic is, you'll note that [the RNN layers simply pass the mask argument into the backend](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L295), where the magic happens (see [here](https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L2230)).

**Comment by slaterb1** [comment]
@carlthome, I saw that in the code but was not able to get the mask to work in my RNN network. For clarity I was trying to rework stuff in RecurrentShop to setup an encoder decoder network that adjusts the next input based on a prediction made on the previous state from both the encoder and the decoder (a custom RNN that uses a .single_step_rnn() instead of the regular .rnn() ). 

But based on your advice, I tried to just build a basic LSTM network to act as a NOT Gate (pointless but simple) and it does interpret the mask correctly, when the it is passed a mask mid network! I'm including the gist. It shows that masking works for both return_sequences=True and return_sequences=False. It also shows that if you train the network with data that does not have 'masked' input, 'masked' lines in the test data will still get masked appropriately. Hope that helps people understand the masking stuff better!

This is the [gist](https://gist.github.com/slaterb1/aa50bc79d87af2538212e50bc51fb2bb)

**Comment by Seanny123** [comment]
@fferroni apparently, the `TimeDistributed` layer didn't support masking, since this feature has been added in [Pull #6401](https://github.com/fchollet/keras/pull/6401)?

**Comment by mehrdadscomputer** [comment]
Hey Guys, there is a seq2seq example which it's input is a string (sequence) like '5+9' and output is another string '14'.
The author used pre padding to have sequences with same lengths at input but he didn't use masking.
I add a simple line to add masking to his model and there is about 8 percent improvement in accuracy.
Is my case a correct use of masking?

this is main code:
`from random import seed
from random import randint
from numpy import array
from math import ceil
from math import log10
from math import sqrt
from numpy import argmax
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import TimeDistributed
from keras.layers import RepeatVector

# generate lists of random integers and their sum
def random_sum_pairs(n_examples, n_numbers, largest):
	X, y = list(), list()
	for i in range(n_examples):
		in_pattern = [randint(1,largest) for _ in range(n_numbers)]
		out_pattern = sum(in_pattern)
		X.append(in_pattern)
		y.append(out_pattern)
	return X, y

# convert data to strings
def to_string(X, y, n_numbers, largest):
	max_length = n_numbers * ceil(log10(largest+1)) + n_numbers - 1
	Xstr = list()
	for pattern in X:
		strp = '+'.join([str(n) for n in pattern])
		strp = ''.join([' ' for _ in range(max_length-len(strp))]) + strp
		Xstr.append(strp)
	max_length = ceil(log10(n_numbers * (largest+1)))
	ystr = list()
	for pattern in y:
		strp = str(pattern)
		strp = ''.join([' ' for _ in range(max_length-len(strp))]) + strp
		ystr.append(strp)
	return Xstr, ystr

# integer encode strings
def integer_encode(X, y, alphabet):
	char_to_int = dict((c, i) for i, c in enumerate(alphabet))
	Xenc = list()
	for pattern in X:
		integer_encoded = [char_to_int[char] for char in pattern]
		Xenc.append(integer_encoded)
	yenc = list()
	for pattern in y:
		integer_encoded = [char_to_int[char] for char in pattern]
		yenc.append(integer_encoded)
	return Xenc, yenc

# one hot encode
def one_hot_encode(X, y, max_int):
	Xenc = list()
	for seq in X:
		pattern = list()
		for index in seq:
			vector = [0 for _ in range(max_int)]
			vector[index] = 1
			pattern.append(vector)
		Xenc.append(pattern)
	yenc = list()
	for seq in y:
		pattern = list()
		for index in seq:
			vector = [0 for _ in range(max_int)]
			vector[index] = 1
			pattern.append(vector)
		yenc.append(pattern)
	return Xenc, yenc

# generate an encoded dataset
def generate_data(n_samples, n_numbers, largest, alphabet):
	# generate pairs
	X, y = random_sum_pairs(n_samples, n_numbers, largest)
	# convert to strings
	X, y = to_string(X, y, n_numbers, largest)
	# integer encode
	X, y = integer_encode(X, y, alphabet)
	# one hot encode
	X, y = one_hot_encode(X, y, len(alphabet))
	# return as numpy arrays
	X, y = array(X), array(y)
	return X, y

# invert encoding
def invert(seq, alphabet):
	int_to_char = dict((i, c) for i, c in enumerate(alphabet))
	strings = list()
	for pattern in seq:
		string = int_to_char[argmax(pattern)]
		strings.append(string)
	return ''.join(strings)

# define dataset
seed(1)
n_samples = 1000
n_numbers = 2
largest = 10
alphabet = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '+', ' ']
n_chars = len(alphabet)
n_in_seq_length = n_numbers * ceil(log10(largest+1)) + n_numbers - 1
n_out_seq_length = ceil(log10(n_numbers * (largest+1)))
# define LSTM configuration
n_batch = 10
n_epoch = 10
# create LSTM
model = Sequential()
model.add(LSTM(100, input_shape=(n_in_seq_length, n_chars)))
model.add(RepeatVector(n_out_seq_length))
model.add(LSTM(50, return_sequences=True))
model.add(TimeDistributed(Dense(n_chars, activation='softmax')))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
# train LSTM
for i in range(n_epoch):
	X, y = generate_data(n_samples, n_numbers, largest, alphabet)
	print(i)
	model.fit(X, y, epochs=1, batch_size=n_batch)

# evaluate on some new patterns
X, y = generate_data(n_samples, n_numbers, largest, alphabet)
result = model.predict(X, batch_size=n_batch, verbose=0)
# calculate error
expected = [invert(x, alphabet) for x in y]
predicted = [invert(x, alphabet) for x in result]
# show some examples
for i in range(20):
	print('Expected=%s, Predicted=%s' % (expected[i], predicted[i]))`

and I just change this part:
`model = Sequential()
model.add(LSTM(100, input_shape=(n_in_seq_length, n_chars)))`
to this part:
`from keras.layers import Masking
model = Sequential()
model.add(Masking(mask_value = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], input_shape=(n_in_seq_length, n_chars)))
model.add(LSTM(100))`

sources:
http://machinelearningmastery.com/learn-add-numbers-seq2seq-recurrent-neural-networks/#comment-400854

**Comment by MeloMing** [comment]
> I don't think Masking masks input values (neither during forward or back-propagation). It just skips a time-step where all features are equal to the mask value (i.e. when you pad a sequence). You can confirm this by:
> 
> ```
> from keras.models import Model
> import numpy as np
> from keras.layers import Masking, Activation, Input, TimeDistributed, Dense
> 
> if __name__ == "__main__":
> 	a = np.array([[[3,1,2,2,0.1,0.1],[0,0,0,0,0,0],[2,1,1,2,0.1,0.1]]])
> 	print 'Input array:'
> 	print a
> 	print ''
> 	input = Input(shape=(3,6))
> 	mask = Masking(mask_value=0.1)(input)
> 	out = TimeDistributed(Dense(1, activation='linear'))(mask)
> 	model = Model(input=input, output=out)
> 
> 	model.set_weights([np.array([[ 1. ],
> 							     [ 1. ],
> 							     [ 1. ],
> 							     [ 1. ],
> 							     [ 1. ],
> 							     [ 1.]], dtype=np.float32), 
> 	                   np.array([ 0.], dtype=np.float32)])
> 
> 	print 'Weights'
> 	print model.get_weights()
> 	q = model.predict(a)
> 	print q
> ```
> 
> The answer is:
> 
> ```
> Input array:
> [[[ 3.   1.   2.   2.   0.1  0.1]
>   [ 0.   0.   0.   0.   0.   0. ]
>   [ 2.   1.   1.   2.   0.1  0.1]]]
> 
> Weights
> [array([[ 1.],
>        [ 1.],
>        [ 1.],
>        [ 1.],
>        [ 1.],
>        [ 1.]], dtype=float32), array([ 0.], dtype=float32)]
> [[[ 8.20000076]
>   [ 0.        ]
>   [ 6.19999981]]]
> ```
> 
> If it masked the inputs of value 0.1, you would expect result to be
> 
> ```
> [[[ 8.       ]
>   [ 0.        ]
>   [ 6.        ]]]
> ```

Mask layer will work only when all feature of a timestep equals to the mask value.In you case,the input a is a 3d matrix with the shape(1,3,6),1 means batch_size,3 means timesteps,and 10 means the feature of that timestep.Mask will work when the feature of a timestep all equal to 0.1.if you change a to:
`
a = np.array([[[3,1,2,2,0.1,0.1],[0,0,0,0,0,0],[0.1,0.1,0.1,0.1,0.1,0.1]]])
`

you will get the output like:

`
[[[8.200001]
  [0.      ]
  [0.      ]]]
`

**Comment by hoangcuong2011** [comment]
Hi,

I struggled a lot with this recently, and here is some experience I learnt. I hope it would be useful for people.


1. Masking is extremely powerful. I found it perhaps the only way to deal with several "hard" problems that are with sequence of missing inputs, missing outputs as follows.
![image](https://user-images.githubusercontent.com/8759715/69851647-c7940000-12b4-11ea-9586-2a0f718d027d.png)

2. Masking is not that complicated if we understand how the loss is computed with masking. For instance let us assume we have a sequence with length 256. From this sequence we have a masking with only 4 elements that are with masking of 1 (others are with masking 0). I thought the loss is computed as the average between these 4 elements. Guess what - it is not! The average loss will be divided by 256 instead. For this reason sometimes the loss will be extremely small (0.0something) if we have only few 1 elements and long sequence.
Does it matter? I guess not, as what we need is the gradient of loss, rather than the loss itself.

3. When we use softmax as the last layer, the denominator would be the sum of exponential of all elements, regarding whether their masking is 1 or 0.

4. I thought the output of masking inputs is zeros all the time in LSTM. But it is not the case. Let us assume we have a masking:

0 0 0 1 1 0 0 0

With this case, the three first elements with masking zero has output of 0. However, the three last zeros have output that is as the same as the output of the last element with masking 1.

5. Meanwhile, Keras is very convenient in the sense that the loss it computes will be based on only elements with masking of 1. I found this is a big plus of using Keras, something a bit too good too be true as I guess implementing this is not that easy.

6. However, the accuracy in Keras is not computed that way. It is thus not trivial in keras to write a custom metric (for fit). There is something very mysterious to me. I am pretty sure my code for writing custom metric is correct but somehow it does not give me accurate result. Because of this I think it is much much easier if we write such an accuracy function with a custom callback class.

That is it, I hope it is helpful!

**Comment by zhanjiezhu** [comment]
> Hi,
> 
> I struggled a lot with this recently, and here is some experience I learnt. I hope it would be useful for people.
> 
> 1. Masking is extremely powerful. I found it perhaps the only way to deal with several "hard" problems that are with sequence of missing inputs, missing outputs as follows.
>    ![image](https://user-images.githubusercontent.com/8759715/69851647-c7940000-12b4-11ea-9586-2a0f718d027d.png)
> 2. Masking is not that complicated if we understand how the loss is computed with masking. For instance let us assume we have a sequence with length 256. From this sequence we have a masking with only 4 elements that are with masking of 1 (others are with masking 0). I thought the loss is computed as the average between these 4 elements. Guess what - it is not! The average loss will be divided by 256 instead. For this reason sometimes the loss will be extremely small (0.0something) if we have only few 1 elements and long sequence.
>    Does it matter? I guess not, as what we need is the gradient of loss, rather than the loss itself.
> 3. When we use softmax as the last layer, the denominator would be the sum of exponential of all elements, regarding whether their masking is 1 or 0.
> 4. I thought the output of masking inputs is zeros all the time in LSTM. But it is not the case. Let us assume we have a masking:
> 
> 0 0 0 1 1 0 0 0
> 
> With this case, the three first elements with masking zero has output of 0. However, the three last zeros have output that is as the same as the output of the last element with masking 1.
> 
> 1. Meanwhile, Keras is very convenient in the sense that the loss it computes will be based on only elements with masking of 1. I found this is a big plus of using Keras, something a bit too good too be true as I guess implementing this is not that easy.
> 2. However, the accuracy in Keras is not computed that way. It is thus not trivial in keras to write a custom metric (for fit). There is something very mysterious to me. I am pretty sure my code for writing custom metric is correct but somehow it does not give me accurate result. Because of this I think it is much much easier if we write such an accuracy function with a custom callback class.
> 
> That is it, I hope it is helpful!

Hi @hoangcuong2011 , thanks for your explanations. I've validated your second point and indeed it's exactly what you said. I'm currently trying to implement a LSTM-autoencoder model to encode sequence into sequence, in which it involves a LSTM layer with return_sequence = False and then RepeatVector layer to copy that back to the previous timestep dimension. However, the mask get lost right after the LSTM because return_sequence = False (if True it returns the input_mask), then I'm wondering how I can get back the mask so that the loss will also ignore the padded timesteps? Thanks!

**Comment by hoangcuong2011** [comment]
@zhangwj618 I am not really sure what your question is about. I guess you would like to write a custom masking layer. If you explain the question in more detail, I think I can help. Thx!

**Comment by Strateus** [comment]
> 4. I thought the output of masking inputs is zeros all the time in LSTM. But it is not the case. Let us assume we have a masking:
> 
> 0 0 0 1 1 0 0 0
> 
> With this case, the three first elements with masking zero has output of 0. However, the three last zeros have output that is as the same as the output of the last element with masking 1.
> 
> 1. Meanwhile, Keras is very convenient in the sense that the loss it computes will be based on only elements with masking of 1. I found this is a big plus of using Keras, something a bit too good too be true as I guess implementing this is not that easy.

I think it is actually bad if it is implemented that way, because it reveals coupled code. In my case specifically i am still struggling with a right loss implementation right now, and it feels like the only way to go is to split training samples based on their sequence length, and avoid masking, which i would not want to do obviously.

Another approach i am thinking about is pre-pad my sequences, instead of post-pad, have not worked it out yet though. Luckily i have either left or right padding with my problem.

Can anyone please shed some light why keras (and now tensorflow.keras) masking is implemented (and what is more importanlty - kept) that way?
