### ISSUE TITLE
Usage of embedding layer

### ISSUE THREAD

**Issue by ipoletaev** [fchollet/keras#3090]
Hi! I was faced with the following problem. I specify all data types integer, as `Embedding` requires:
`emb_input = Input(shape=(30,),dtype="int32",name="emb_input")`
`add_input = Input(shape=(30,5),dtype="int32",name="add_input")`
`emb_masked_input = Masking(mask_value=0.,input_dtype="int32")(emb_input)`
`add_masked_input = Masking(mask_value=0.,input_dtype="int32")(add_input)`
`emb_model = Embedding(1000,100,input_length=30,input_dtype="int32")(emb_masked_input)`
`model = merge([add_masked_input,emb_model],mode='concat')`
`...`

Code above raise an error,although I specify all data types integer, as `Embedding` requires:
`File ".../theano/tensor/subtensor.py", line 1687, in make_node`
`raise TypeError('index must be integers')`
`TypeError: index must be integers`
Variant with another line:
`emb_model = Embedding(1000,100,input_length=30,input_dtype="int32",mask_zero=True)(emb_masked_input)`
also doesn't work.

Also I have tried another way:
`emb_input = Input(shape=(30,),dtype="int32",name="emb_input")`
`add_input = Input(shape=(30,5),dtype="int32",name="add_input")`
`add_masked_input = Masking(mask_value=0.,input_dtype="int32")(add_input)`
`emb_model = Embedding(8000,100,input_length=30,input_dtype="int32",mask_zero=True)(emb_input)`
`model = merge([add_masked_input,emb_model],mode='concat')`
`...`

And it's working right. I can not understand what's going on. Thanks for help.

**Comment by poyuwu** [comment]
That's because `emb_masked_input` and `add_masked_input` 's .type.dtype is float64.
Just using `mask_zeros` in `Embedding` layer. `Masking` is no need.

**Comment by ipoletaev** [comment]
Ok, thanks a lot! 
And what about `Reshape` layer - will this layer ever to keep the masking??
