### ISSUE TITLE
Error loading a model multiple times

### ISSUE THREAD

**Issue by anMabbe** [fchollet/keras#3091]
I would like to load twice the same model from a yaml string stored in a 'config.txt' file. It is not yet possible, as the loaded models will be initialised the same way and will not have an independent life (the weights are shared). Is this behaviour intended ? I think that this behaviour may not be desirable. Here is a minimal code to reproduce the issue, with the 'config.txt' file attached.

[config.txt](https://github.com/fchollet/keras/files/336542/config.txt)

``` python
from keras.models import model_from_yaml

with open('config.txt', 'r') as f:
    model = model_from_yaml(f)  
model.summary()
model.compile('sgd','mse')

#Make predictions to see that models are all the same
import numpy as np
x = np.random.rand(1,10,2)
model.predict(x)

with open('config.txt', 'r') as f:
    model2 = model_from_yaml(f)  
model2.summary()
model2.predict(x)
#This yields the same prediction as model

model3 = model_from_yaml(model.to_yaml())
model3.summary()
model3.predict(x)
#Same prediction as model and model2
```

Both model2 and model3 make the same predictions as model. I would expect them to be randomly initialized every time and I can't see a quick way of doing it. Any thought on this subject ?

**Comment by anandarupmukherjee** [comment]
Upgrade to latest version:

pip install keras --upgrade 

It should go away.
