### ISSUE TITLE
Maxout over convolutional layer.  

### ISSUE THREAD

**Issue by GodOfProbability** [fchollet/keras#3102]
I am new to keras/theano. I have been trying to implement [maxout](https://arxiv.org/abs/1302.4389) for convolutional layer output. I know that there is MaxoutDense layer present in keras and also Convolution2D layer, but I am unable to merge them for my purpose. It might be because I am not able to understand maxout properly. 
I am trying to replicate the results of [Deep Features for Text Spotting](http://link.springer.com/chapter/10.1007%2F978-3-319-10593-2_34). The maxout network in this paper simply uses max over consecutive filters. 
I would appreciate if someone can share their code for maxout for convolutional layers.
With small understanding that I have, I have written small maxout (lambda layer) of my own but it gives me strange error: 

img_rows = 24
img_cols = 24
def maxout(x):
    out = None
    for i in range(0, 32):
        Max = K.max(x[:, i * 2:(i + 1) * 2, :, :], axis=1, keepdims=True)
        K.expand_dims(Max, dim = 0)
        if out == None:
            out = Max
        else:
            out = K.concatenate([out, Max], axis=1)
    return out

def maxout_output_shape(input_shape):
    shape = list(input_shape)
    shape[1] = 16
    return tuple(shape)

model = Sequential()
model.add(Convolution2D(32, 3, 3, input_shape=(1, img_rows, img_cols)))
model.add(Lambda(function=maxout, output_shape=maxout_output_shape))
model.compile(optimizer='adam', loss="mse")
X = np.ones((1, 1, 24, 24))
layer_output = K.function([model.layers[0].input],
                                  [model.layers[1].output])

layer_output = layer_output([X])

The errors are:
Using Theano backend.
Traceback (most recent call last):
  File "temp.py", line 41, in <module>
    layer_output = layer_output([X])
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.3-py2.7.egg/keras/backend/theano_backend.py", line 518, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Input of CAReduce{maximum} has zero-size on axis 1
Apply node that caused the error: Reduce{maximum}{1}(Subtensor{::, int64:int64:}.0)
Toposort index: 51
Inputs types: [TensorType(float32, 4D)]
Inputs shapes: [(1, 0, 22, 22)]
Inputs strides: [(61952, 1936, 88, 4)]
Inputs values: [array([], shape=(1, 0, 22, 22), dtype=float32)]
Outputs clients: [[InplaceDimShuffle{0,x,1,2}(max)]]

**Comment by ducha-aiki** [comment]
@GodOfProbability I think you can close this issue, sunce #3128 solves it :)
