### ISSUE TITLE
Cifar-10 example error

### ISSUE THREAD

**Issue by Denspa** [fchollet/keras#311]
Hi,

I'm getting the following error when running the cifar-10 example. Any ideas on what could be the issue?

X_train shape: (50000, 3, 32, 32)
50000 train samples
10000 test samples
Using real time data augmentation
----------------------------------------
Epoch 0
----------------------------------------
Training...
50000/50000 [==============================] - 741s - train loss: 1.7240
Testing...
Traceback (most recent call last):
  File "cifar10_cnn.py", line 115, in <module>
    score = model.test(X_batch, Y_batch)
  File ".../egg/keras/models.py", line 159, in test
  File ".../lib/python2.7/site-packages/theano/compile/function_module.py", line 581, in __call__
    self.inv_finder[c]))
TypeError: Missing required input: Elemwise{second,no_inplace}.0

**Comment by fchollet** [comment]
Cannot repro on master. Try updating your version of Keras and Theano maybe?

**Comment by Denspa** [comment]
Theano==0.7.0 is the version installed. For keras did a git pull before installing.

**Comment by fchollet** [comment]
You are right, apparently we forgot to cover the model.test method used by that example. It's a rarely used method otherwise... it's fixed now, you can pull and reinstall.
