### ISSUE TITLE
loss/objective functions involving more then one data-point at a time

### ISSUE THREAD

**Issue by sariel85** [fchollet/keras#3113]
I am using deep nets to learn new features for a data set and then use them for a classification/regression task.

As an objective function for the feature learning stage I want to maximize similarity in the learnt feature space of data points which I know should be similar and distance points which I know should be distant.

So for example if I know that data points x1 and x2 are similar in some sense and the net represents the points as y1, y2 (via the output of some mid layer of the net, before the classifier) I would like to minimize (y1-y2)^2.

Is there a way to do this via Keras?
As far as I can see all objective functions in Keras involve one data point at a time. Can I write a objective function involving the relationship between the net outputs for two different data points?

P.S - I am aware that the division to mini-batches might cause a problem (for example if the two related point do not fall in the same batch the layer outputs might not be both available in the same batch) but I can overcome this issue in other ways or I can even work with non-stochastic/full-batch optimizer if needed

**Comment by AdityaGudimella** [comment]
Why don't you try a siamese architecture?

**Comment by sariel85** [comment]
@AdityaGudimella
That will definitely work and that is what I have have done so far to test my suggested regularization/objective. However I feel that it is highly inefficient in my case.

I have a total of N data point and I have some idea of how close/far each one should be from all of the other N-1 point, so my data doesn't naturally come in pairs of two but rather I "construct" a pair connection for any two data samples.

So if I constructed a Siamese network this effectively turns my N points into N^2 pairs of points without adding any actual information to the system and each point will have to be propagated through the system, back and fourth, N-1 times instead of just once.

I would accept this if it was mathematically/logically unavoidable but my hand-coded implementations of this system in Matlab/theano had no extra overhead when using this type of objective compared to a standard one since the basic math of back-propagation should not have any special problem with this type of cost function.
