### ISSUE TITLE
Stacking Merge layers?

### ISSUE THREAD

**Issue by Natanada** [fchollet/keras#312]
Is it possible to stack Merge layers? The model compiles but the train methods breaks with 
`dimension mismatch in args to gemm`
```
left_left = Sequential()
left_left.add(TimeDistributedDense(10, 20))

left_right = Sequential()
left_right.add(TimeDistributedDense(10, 20))

right_left = Sequential()
right_left.add(TimeDistributedDense(10, 20))

right_right = Sequential()
right_right.add(TimeDistributedDense(10, 20))

left = Sequential()
left.add(Merge([left_left, left_right], mode = 'sum'))

right = Sequential()
right.add(Merge([right_left, right_right], mode = 'sum'))

model = Sequential()
model.add(Merge([left, right], mode='concat'))
model.add(TImeDistributedDense(40, 100))
model.add(Activation('softmax'))
model.compile(loss='categorical_crossentropy', optimizer='sgd')

model.train([left_left_x, left_right_x, right_left_x, right_right_x], y)
```

**Comment by simonhughes22** [comment]
maybe try

`model.train([[left_left_x, left_right_x], [right_left_x, right_right_x]], y)`

**Comment by fchollet** [comment]
Can you post a code snippet to repro this, which includes data (use `np.random.random(shape)` to generate your data)? Your network appears to be correct, but there might be issues with the shape of your inputs / outputs.

**Comment by adamklec** [comment]
Can someone please clarify the correct syntax for passing training data to stacked merge layers? Should I use a nested list as @simonhughes22  suggested?
