### ISSUE TITLE
Is it possible to set CPU / GPU usage without knowing the backend?

### ISSUE THREAD

**Issue by carlthome** [fchollet/keras#3120]
In other words, I don't know if the Keras install will use Theano or TensorFlow, but I'd still like to have control over whether the CPU or GPU is being used. Is this possible? Could we add a flag to `~/.keras/keras.json` for this purpose otherwise?

**Comment by denlecoeuche** [comment]
You could automatically check `~/.keras/keras.json` at the beginning of your script:
- if the backend is Theano then with `os.environ` you can set `THEANO_FLAGS` to `device=gpu` (and/or  `openmp=True` for multi-CPU usage) and then `import theano`.
- if the backend is TensorFlow then it will automatically use the GPU. If needed you could then try to prevent tf to use the GPU with something like [this](https://github.com/tensorflow/tensorflow/issues/754).

**Comment by carlthome** [comment]
Yeah, sure, but it feels like that should be a function provided by Keras, especially as more backends are eventually added. User code should be backend agnostic.

**Comment by Steviey** [comment]
I always get gpu errors like "c:\tf_jenkins\home" etc. and can't simply switch to cpu.
I have NVIDIA GPU Computing installed, but it's not used.
