### ISSUE TITLE
How to add layers to a keras.model Model ?

### ISSUE THREAD

**Issue by cyrilgarcia009** [fchollet/keras#3121]
Hi, 

I would like to ad some layers to a Model type but I can't find how to do so. 

Another solution would be to convert a Mdel to a Sequential(). Does anyone know how to do one of those things please ?

Thanks !!

**Comment by mbollmann** [comment]
I suggest you read the [guide to the functional API](http://keras.io/getting-started/functional-api-guide/) since it's pretty much all explained there.

**Comment by cyrilgarcia009** [comment]
I have already read this guide but there is not any answer to my question

**Comment by fchollet** [comment]
Please refer to the functional API guide as previously mentioned. It explains how to use the `Model` class.
