### ISSUE TITLE
proper deconvolution/conv3d layers

### ISSUE THREAD

**Issue by EderSantana** [fchollet/keras#3122]
for now, keras deconvolutions are implemented as convolutions followed by upsampling with repetition. There are faster and more efficient ways to implement them (plus results seem to look prettier) :

Tensorflow:
https://github.com/carpedm20/DCGAN-tensorflow/blob/master/ops.py#L89-L90

Theano:
https://github.com/Newmu/dcgan_code/blob/master/lib/ops.py#L85-L96

Same thing for conv3d. Now tensorflow supports them:
https://www.tensorflow.org/versions/r0.9/api_docs/python/nn.html#conv3d

Anybody down to wrap them up in a Keras backend op? If not I'll do it later this week/early next one.
Thanks!!!

**Comment by fchollet** [comment]
I think this would be very valuable. Go for it!

I will also look into adding `AtrousConv2D` and `SeparableConv2D` (on the TF side it will be easy, unsure about Theano yet).

**Comment by EderSantana** [comment]
I didn't see `AtrousConv2D` and SeparableConv2D` on Theano either... But they definitively useful for autoencoders/segnet models

**Comment by KlaymenGC** [comment]
I think in Theano ```AtrousConv2D``` can be done by using ```AbstractConv2d_gradWeights```.

**Comment by lukovkin** [comment]
Would you implement deconvolution (convolutional transpose) and dilated convolutions (a trous) for 1D  case specifically or one should just use 2D implementation with rows or cols set to 1?

We've made a 1D convolutional transpose implementation at some point, but with TF backend only - https://github.com/lukovkin/ufcnn-keras/blob/master/models/convolutional_transpose.py#L329.

**Comment by EderSantana** [comment]
@lukovkin I'm working on the PR here #3133
you can submit your 1D adaptation in there if you want and we make it all one PR

**Comment by lukovkin** [comment]
@EderSantana OK, I'll try to catch up ;)

**Comment by SulemanKazi** [comment]
Has anyone started updating `SeparableConv2D`  to work with Theano? Sorry if this should be addressed elsewhere. I wanted to know if anyone has started on an implementation before I try!

**Comment by ahundt** [comment]
looks like this may now be in keras-contrib:
https://github.com/farizrahman4u/keras-contrib/pull/21
https://github.com/farizrahman4u/keras-contrib/blob/master/keras_contrib/layers/convolutional.py#L18
