### ISSUE TITLE
RNN variants: Depth-Gated RNN, ResNet and Gated Feedback RNN

### ISSUE THREAD

**Issue by IbrahimSobh** [fchollet/keras#3124]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [X ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Dear sir, 

I would like to ask if the following is implemented or will be soon: 
    1- Depth-Gated RNN,  http://arxiv.org/pdf/1508.03790v2.pdf 
    2- ResNet, https://arxiv.org/pdf/1512.03385v1.pdf
    3- Gated Feedback RNN, https://arxiv.org/pdf/1502.02367.pdf

Regards

**Comment by fchollet** [comment]
Here is resnet: https://github.com/raghakot/keras-resnet

New architectures come out every week. 95% of them end up never being used after the paper introducing them. Let's see what passes the test of time first (resnet did).
