### ISSUE TITLE
use tensorflow backend and multi-core CPU 

### ISSUE THREAD

**Issue by honglu-intel** [fchollet/keras#3125]
I searched around for quite a while, but still don't understand how to use multi-core with tensor flow backend. I know there are flags that could be set for Theano. How about tensorflow? thanks.

**Comment by dongfangyixi** [comment]
I'm wondering weather keras can specify gpu like gpu0 gpu1 or all gpu when using tensorflow backends. I know that when using tensorflow it's possible to manipulate which gpu to use as in https://www.tensorflow.org/versions/r0.9/how_tos/using_gpu/index.html. So it's possible keras do the same thing?
