### ISSUE TITLE
image_dim_ordering in keras.json will be overwritten as 'th' every time keras is run

### ISSUE THREAD

**Issue by MycChiu** [fchollet/keras#3127]
Which then cause the dim_ordering attribute to always be 'th' for all conv layers, if it's not set locally.
Possible solution
-----
I am not sure if this is intended, but [backend/__init__.py](https://github.com/fchollet/keras/blob/8d3f39852aa6596c41f6a2a901ee76501bc1741e/keras/backend/__init__.py#L37) in current master branch seems to be missing
`set_image_dim_ordering(_image_dim_ordering)`
right below
```python
    set_floatx(_floatx)
    set_epsilon(_epsilon)
```
by adding the missing line, the issue is resolved for me.
Although i am not sure if there will be any unwanted downstream effect.

**Comment by fchollet** [comment]
Thanks, I fixed it.
