### ISSUE TITLE
Training data batch by batch or one by one.

### ISSUE THREAD

**Issue by cdyrhjohn** [fchollet/keras#3135]
How can I train an extremely large dataset? I would like to do something like: read an image or a batch of images from image file --> train --> read another images again --> train--> read --> ...... --> end of epoch. Besides, an alternative method: e.g. I would like to train the network with 100 epochs and I have 10000 images, so I wanna to have the network trained with 100 images(I need to read the images from image files in each epoch) in each epochs. How can I implement the methods I mentioned above in Keras?

**Comment by solomondg** [comment]
You'd use a data generator instead of loading all the data into memory. 
Check out 
http://keras.io/preprocessing/image/
and
https://github.com/fchollet/keras/issues/1627

**Comment by cdyrhjohn** [comment]
@solomondg Thanks a lot
