### ISSUE TITLE
Sequence to Sequence Model Now Fails When Training

### ISSUE THREAD

**Issue by simonhughes22** [fchollet/keras#314]
Over the weekend I wrote this model which was working:

```python
embedding_size = 32
hidden_size = 512

print('Build model...')
model = Sequential()
model.add(Embedding(max_features, embedding_size))
model.add(JZS1(embedding_size, hidden_size)) # try using a GRU instead, for fun
model.add(Dense(hidden_size, hidden_size))
model.add(Activation('relu'))
model.add(RepeatVector(MAX_LEN))
model.add(JZS1(hidden_size, hidden_size, return_sequences=True))
model.add(TimeDistributedDense(hidden_size, max_features, activation="softmax"))

# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy', optimizer='adam', class_mode="binary")
```
This is an attempt at a sequence to sequence model as used in machine translation and in that recent neural conversation model by Quoc Le for google, and originated here (http://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf). At one point the above code was working, but at some point I updated Theano to bleeding edge and keras to the latest and it fails when calling model.train.

```
File "/Users/simon.hughes/GitHub/Theano/theano/compile/function_module.py", line 607, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[0] = 1392, input[1].shape[0] = 952128)
Apply node that caused the error: Elemwise{mul,no_inplace}(Flatten{1}.0, Flatten{1}.0)
Toposort index: 439
Inputs types: [TensorType(float32, vector), TensorType(float32, vector)]
Inputs shapes: [(1392,), (952128,)]
Inputs strides: [(4,), (4,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Sum{acc_dtype=float64}(Elemwise{mul,no_inplace}.0)]]
```
Any ideas? The input is 2D padded (num_samples, max_tokens) which gets converted to 3D by the embedding layer. The output is 3D (num_samples, max_tokens, max_features) which does a softmax over a one hot vector representing the target words. The input and output are padded to the same length, the output being padded with one-hot vectors instead.

**Comment by fchollet** [comment]
Can you share a code snippet to reproduce this?

**Comment by simonhughes22** [comment]
@fchollet  Here's a dummy example predicting random number sequence:

```python
from __future__ import absolute_import
from __future__ import print_function

import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense, Activation, RepeatVector, TimeDistributedDense
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM, GRU

import logging

import datetime
print("Started at: " + str(datetime.datetime.now()))

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
logger = logging.getLogger()

xs = []

maxlen = 100
max_features=maxlen + 1
from numpy.random import shuffle

r = range(1, maxlen + 1, 1)

for i in range(1000):
    shuffle(r)
    new_x = r[::]
    xs.append(new_x)

def to_one_hot(id):
    zeros = [0] * max_features
    zeros[id] = 1
    return zeros

xs = np.asarray(xs)

ys = map(lambda x: map(to_one_hot, x), xs)
ys = np.asarray(ys)

print("XS Shape: ", xs.shape)
print("YS Shape: ", ys.shape)

batch_size = 16
embedding_size = 32
hidden_size = 512

print('Build model...')
model = Sequential()
model.add(Embedding(max_features, embedding_size))
model.add(GRU(embedding_size, hidden_size))
model.add(Dense(hidden_size, hidden_size))
model.add(Activation('relu'))
model.add(RepeatVector(maxlen))
model.add(GRU(hidden_size, hidden_size, return_sequences=True))
model.add(TimeDistributedDense(hidden_size, max_features, activation="softmax"))

model.compile(loss='binary_crossentropy', optimizer='adam', class_mode="binary")

print("Train...")
X_train, y_train = xs, ys

iterations = 0
while True:
    results = model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=1, validation_split=0.0, show_accuracy=True, verbose=1)
    preds = model.predict_proba(X_train, batch_size=batch_size)

    cnt = 0
    for x, y, p in zip(X_train, y_train, preds):
        if p.max() > 0 and cnt < 5:
            print("X   :", " ".join(map(str, x)))
            print("Y   :", " ".join(map(str, map(lambda y: max(y), y))))
            print("Pred:", " ".join(map(str, map(lambda p: np.asarray(p).argmax(), p))))
            cnt += 1

    iterations += 1
    print("Iteration:", iterations)

print("at: " + str(datetime.datetime.now()))
```

**Comment by simonhughes22** [comment]
Output
```
    results = model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=1, validation_split=0.0, show_accuracy=True, verbose=1)
  File "build/bdist.macosx-10.6-x86_64/egg/keras/models.py", line 234, in fit
  File "/Users/simon.hughes/GitHub/Theano/theano/compile/function_module.py", line 618, in __call__
    storage_map=self.fn.storage_map)
  File "/Users/simon.hughes/GitHub/Theano/theano/gof/link.py", line 295, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Users/simon.hughes/GitHub/Theano/theano/compile/function_module.py", line 607, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[0] = 1600, input[1].shape[0] = 161600)
Apply node that caused the error: Elemwise{mul,no_inplace}(Flatten{1}.0, Flatten{1}.0)
Toposort index: 432
Inputs types: [TensorType(float32, vector), TensorType(float32, vector)]
Inputs shapes: [(1600,), (161600,)]
Inputs strides: [(4,), (4,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Sum{acc_dtype=float64}(Elemwise{mul,no_inplace}.0)]]

Debugprint of the apply node: 
Elemwise{mul,no_inplace} [@A] <TensorType(float32, vector)> ''   
 |Flatten{1} [@B] <TensorType(float32, vector)> ''   
 | |AdvancedSubtensor [@C] <TensorType(float32, vector)> ''   
 |   |<TensorType(float32, 3D)> [@D] <TensorType(float32, 3D)>
 |   |Subtensor{int64} [@E] <TensorType(int64, vector)> ''   
 |   | |Nonzero [@F] <TensorType(int64, matrix)> ''   
 |   | | |<TensorType(float32, 3D)> [@D] <TensorType(float32, 3D)>
 |   | |Constant{0} [@G] <int64>
 |   |Subtensor{int64} [@H] <TensorType(int64, vector)> ''   
```

**Comment by fchollet** [comment]
I will look into it. 

Sequence to sequence does in fact work, so the issue is somewhere else (maybe the use of `RepeatVector`). 

> ValueError: Input dimension mis-match. (input[0].shape[0] = 1600, input[1].shape[0] = 161600)

The error might point out to `RepeatVector` as well? But the shape of the output it returns seems correct.

Here's a working snippet of Sequence-to-sequence learning including `TimeDistributedDense`:
```python
from keras.models import Sequential
import numpy as np
from keras.layers.recurrent import SimpleRNN, GRU, LSTM
from keras.layers.core import TimeDistributedDense, Activation

n_in = 10
n_hidden = 20
n_samples = 500
n_timesteps = 5

model = Sequential()
model.add(GRU(n_in, n_hidden, return_sequences=True))
model.add(TimeDistributedDense(n_hidden, n_hidden))
model.compile(loss='mse', optimizer='rmsprop')

X = np.random.random((n_samples, n_timesteps, n_in))

Xp = model._predict(X)
print Xp.shape

model.fit(X, Xp)
```

**Comment by simonhughes22** [comment]
Cool thanks. Simpler models seem to do better. I'll try that out, I didn't think of it that way.
It would be cool to get something like this working in keras:

http://arxiv.org/pdf/1506.06726v1.pdf

Especially ahead of the authors sharing their code, as I'm sure people want to try that out.

**Comment by simonhughes22** [comment]
While the above model works, I suspect as the sequences are of different length, it wouldn't work very well as it's essentially a tagging model, whereas if you are taking in one sequence and predicting another, as in MT or trying to predict the next sentence, I would think it would need to process the entire sentence first before predicting the output, and that doesn't do that if I'm understanding correctly.

**Comment by simonhughes22** [comment]
@fchollet your code sample runs fine but not when I ran it on my data, which is larger. It seems to be to do with the size of the inputs. I switched your example to use a larger set of inputs and got the same error:

```python
from keras.models import Sequential
import numpy as np
from keras.layers.recurrent import SimpleRNN, GRU, LSTM
from keras.layers.core import TimeDistributedDense, Activation

n_in = 684
n_out = 684
n_hidden = 512
n_samples = 2297
n_timesteps = 87

model = Sequential()
model.add(GRU(n_in, n_hidden, return_sequences=True))
model.add(TimeDistributedDense(n_hidden, n_out))
model.compile(loss='mse', optimizer='rmsprop')

X = np.random.random((n_samples, n_timesteps, n_in))
Y = np.random.random((n_samples, n_timesteps, n_out))

Xp = model._predict(X)
print Xp.shape
print Y.shape

model.fit(X, Y, nb_epoch=1)

```

**Comment by transcranial** [comment]
I'm getting the exact same error with a model similar to @simonhughes22 's above.

**Comment by fchollet** [comment]
@simonhughes22 your initial network also works for me when decreasing the quantities involved. So it's definitely a "data size" problem. Which is quite fascinating.

Since the Keras-side logic is the exact same independently of the dimensionality of the data, I suspect a Theano bug. I'll look deeper into what's going on.

**Comment by fchollet** [comment]
Also you second code snippet works for me. This is getting weirder and weirder.

**Comment by fchollet** [comment]
Here's how to get your initial snippet working: replace the compilation line with:
```python
model.compile(loss='mse', optimizer='adam') # or any loss other than binary_crossentropy
```
The concept of "class" does not make sense with sequence to sequence learning, and binary_crossentropy is for scalar outputs.

Still, it should not have triggered this error. But the issue was using a loss meant for scalar outputs.

**Comment by simonhughes22** [comment]
Awesome thanks. Will let you know if any other problems. Given I'm doing a softmax over each predicted output vector (one vector per output word), what would be the best error metric? mse is more for regression, whereas I want basically a probability model. Should I use categorical_crossentropy instead?

**Comment by fchollet** [comment]
> Should I use categorical_crossentropy instead?

Yes, that would work.

**Comment by dribnet** [comment]
informational footnote: @simonhughes22's code snippet worked well for me at size maxlen=100, but failed around maxlen=250 with an error `bracket nesting level exceeded maximum of 256`. My workaround was to edit my ~/.theanorc:
```
[gcc]
cxxflags = -fbracket-depth=1024
```
Decoupling maxlen and max_features hints that this is more likely triggered by the `Embedding` or `RepeatVector` than the `TimeDistributedDense` call.
