### ISSUE TITLE
ImageDataGenerator - feature-request support for 'BGR'

### ISSUE THREAD

**Issue by assaflehr** [fchollet/keras#3140]
ImageDataGenerator - **feature-request** support for 'BGR'
Some (or even a lot of) pre-trained models use BGR and not RGB.
The ImageDataGenerator does not allow using the method flow_from_directory() with that mode.
I think that it can be added as one more color_mode 'bgr', as it's very popular.

Workaround exists, by not using flow_from_directory and loading the data yourself, but this misses the elegance and utilization of the directory generator

**Comment by emsi** [comment]
In the current CSV code one can use preprocessing_function argument to ImageDataGenerator to implement own preprocessing.
According to the documentation:

>       preprocessing_function: function that will be implied on each input.
>             The function will run before any other modification on it.
>             The function should take one argument:
>             one image (Numpy tensor with rank 3),
>             and should output a Numpy tensor with the same shape.
