### ISSUE TITLE
Invalid Arguement Error Training Model in Jupyter Python Notebook

### ISSUE THREAD

**Issue by ViswanathanRajalingam** [fchollet/keras#3152]
"InvalidArgumentError: GraphDef argument to Extend includes node 'MatMul_12', which was created by a previous call to Create or Extend in this session."

When training multiple models in same Ipython notebook (same Kernel), after first model successfully executes and I try to run second model at a new cell, I keep encountering this error. Tried working code from Keras Examples.

The code works fine if I run it at different Ipython notebooks but turns out same error if I run it on same notebook.

Any further information on this would be helpful. Thanks

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [+] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [+] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [+] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by jakubLangr** [comment]
I ran into the same problem! Any updates on this? I basically tried a modified version of [https://github.com/fchollet/keras/blob/master/examples/imdb_cnn_lstm.py](this) but removed the first `embedding` layer and replaced the `X_train` and `X_test` (and the corresponding `y`s) with a custom 24-dimensional matrix.
