### ISSUE TITLE
Insteresting question: Waht is the difference between "100 epoch and 1 epoch iterated for 100 times"

### ISSUE THREAD

**Issue by LinRing** [fchollet/keras#3154]
Hellow!

I made an experiment and found a interesting question that there is a little difference between "optimize a model for 100 epoch" and " optimize a model with 1epoch for 100 times."
# optimize a model for 100 epoch

```
    model.fit(X , Y, nb_epoch=100, batch_size=50)

    outcome_1=model.predict(X, batch_size=50)
```
# optimize a model with 1epoch for 100 times iterations

```
  for i in range(0,100):

       model.fit(X , Y, nb_epoch=1, batch_size=50

       i+=1
  outcome_2=model.predict(X, batch_size=50)
```

I am confused to these two different outcomes (although the difference is small)
Is anybody know the reason why??
Will there be any bias if I choose optimize a model with 1epoch for 100 times iterations rather than optimize a model for 100 epoch?

Thank you for help!

**Comment by grahamannett** [comment]
The difference is probably due to random initializations and other slight variations.  They should be the same thing.

**Comment by LinRing** [comment]
Thank you grahamannett for prompt answer!

Yes, I made an experiment and found you are absolutely right!!!

Really thank you very much !!

Tony L.

**Comment by phdowling** [comment]
I would guess if you're using an adaptive learing-rate method like rmsprop, there might be a bigger difference since the per-weight learning rates are not consistent over epochs in the second case.. Not 100% sure about this though.
