### ISSUE TITLE
how to use mask options  in recurrent layer

### ISSUE THREAD

**Issue by KobeDeShow** [fchollet/keras#3156]
problem description : input data are Variable-length sequences , and  i used pad_sequences for preproccess   then used embedding layer with mask_zero = True ,  when i call the gru layer **call** function, i must set the mask option? 
eg:
input_data = Input(shape=(max_len, ), dtype='int32')
embedding_data = Embedding(vocab_size, embedding_size, input_length=max_len, mask_zero=True)(input_data)

gru_data = GRU(output_dim=gru_size)(embedding_data, mask_tensor)  or gru_data = GRU(output_dim=gru_size)(embedding_data) 

Thank you in advance~~

**Comment by gw0** [comment]
No. Once a mask is introduced in the computation all following layers that support masking will use it (or you get an error if it does not support masking). You should not provide a mask tensor.
