### ISSUE TITLE
Failed to import keras for unknown reason

### ISSUE THREAD

**Issue by zjhzxhz** [fchollet/keras#3165]
I'm using Debian 8.5 with Python 2.7.9.

Firstly, I could import `keras` successfully in Shell.

```
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using Theano backend.
>>> from keras.datasets import mnist
>>> 
```

Then I tried to run this [script](https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py), and I got following error meesage:

```
Traceback (most recent call last):
  File "./keras.py", line 8, in <module>
    from keras.datasets import mnist
  File "/home/hzxie/Development/Python/Experiments/Deep-Learning/keras.py", line 8, in <module>
    from keras.datasets import mnist
ImportError: No module named datasets
```

Then I tried to import `keras` in Shell again, but failed:

```
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras.datasets import mnist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "keras.py", line 8, in <module>
    from keras.datasets import mnist
ImportError: No module named datasets
>>> 
```

So strange isn't it?

**Comment by tboquet** [comment]
Do you have a file named `keras.py` in the same directory?

**Comment by zjhzxhz** [comment]
@tboquet

Yes, I resolved the problem by rename the file. Thanks a lot.

**Comment by Ayesha2788** [comment]
line 4, in <module>
    from keras.datasets import mnist
ModuleNotFoundError: No module named 'keras'

Process finished with exit code 1

can anyone help with this
