### ISSUE TITLE
Training doesn't start when using device=gpu

### ISSUE THREAD

**Issue by sanjeevmk** [fchollet/keras#3168]
My network works properly when I don't use the _device=gpu_ flag. Even with _device=gpu_ , it worked for a couple of times, but then it stopped working. This is how it looks, when it doesn't work:

![gpuproblem](https://cloud.githubusercontent.com/assets/1523786/16659499/f191fe88-4487-11e6-8099-3dcb85fd983b.png)
 As seen above, it just prints Epoch 1/5 and stops. 

Is there any way I can know what's going wrong, debug logs for cuda etc?

I'm using 3D convolutions and I first tried with a small set of examples, and it worked, with gpu. Then I ran a larger set, with _fit_generator_ , and then it gave the above problem. Since then, it has not worked at all, even for the smaller set of examples.

Also, I'm using CUDNN, but Keras prints cuDNN None. What does that mean? Earlier it had printed cuDNN Not availble, and after installing cuDNN it prints "None".

**Comment by Chuck-Aguilar** [comment]
I'm having a similar problem, here is my issue: [9503](https://github.com/keras-team/keras/issues/9503)

how did you resolve your problem?
