### ISSUE TITLE
whether does "fit_generator" accept multi input generator like "fit"?

### ISSUE THREAD

**Issue by dongzhuoyao** [fchollet/keras#3177]
from [http://keras.io/getting-started/functional-api-guide/#multi-input-and-multi-output-models](http://keras.io/getting-started/functional-api-guide/#multi-input-and-multi-output-models),

we can see the we can use multi input and multi output by "fit".

but when the data size is huge,it's not practical to load all data into memory and use "fit" method to start training.

so I think up a idea about "fit_generator",but from keras's document,"fit_generator" seems don't accept the generator that generates multi input(in this case,it may return  a dict).the "fit_generator" only accepts the generator that returns a tuple which can only descibe single one input.

Does there exist any solution to solve the problem,or I have to hack the core to complete  my demand？

**Comment by ChristianThomae** [comment]
You may return a tuple of lists for multi input/output, like:
`yield [X1, X2], [y1, y2]`

**Comment by hassaan90** [comment]
did you able to manege this thing ? I am having similar problem ...
