### ISSUE TITLE
Predictions of trained model are different for same image

### ISSUE THREAD

**Issue by DepthFirstSearch** [fchollet/keras#3188]
Hello,

At the moment, I deal with a strange problem. I've trained a model for several epochs and saved its weights. Now, I want to load/restore this model and make some predictions, i.e. feed the network with some images. But every time I load my model and use its predict() function, the result is different. Here is an example:
`# Load model 1`
`model1 = load_model('/path/to/weights')`
`model1.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])`
`# Load model 2`
`model2 = load_model('/path/to/weights')`
`model2.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])`
`# Note: both models are exactly the same, having the same weights (since they are restored from the same file)`

`img = Image.open('/path/to/image')`
`img = img.convert('RGB')`
`x = np.asarray(img, dtype='float32')`
`x = x.transpose(2, 0, 1)`
`x = np.expand_dims(x, axis=0)`

`out1 = model1.predict(x)`
`print(np.argmax(out1))`
> 0

`out2 = model2.predict(x)`
`print(np.argmax(out2))`
> 9

Where `load_model()` builds the model and loads the weights, [as you can see here](https://gist.github.com/DepthFirstSearch/107529bbf6de05acf19a115d5bfdd1ee).

I have checked that `model1` and `model2` have exactly the same weights. Also, I have run this on GPU but CPU as well (using Theano as backend).

So, how is it possible that the same model generates two different predictions for the same image? By the way, I get the same results if I use the function `evaluate()`.

**Comment by tboquet** [comment]
Try to load the weights after compiling the model. When you recompile a model, you also reinitialize the weights.

**Comment by DepthFirstSearch** [comment]
I just tried what you described, but it didn't solve the problem.

In fact, I took a look at the weights before and after compiling. In both cases they were the same.

**Comment by DepthFirstSearch** [comment]
Actually, I was wrong! 

Now I get the same predictions for two different models restored from the same file.

I was just suspicious because I (I) loaded the weights, (II) printed the weights, (III) compiled the model and (IV) printed the weights again. But there wasn't any difference. So I'm not sure if compiling reinitializes the weights. Can you explain this any further?

But anyhow, I guess it works now, thanks! Later that day I'll do some more tests, and if everything is fine I'll close this issue.

**Comment by tboquet** [comment]
Mmh, you are right you can load the weights before compiling.
I tried to reproduce this behavior with on of the examples:

```python
'''Trains a simple convnet on the MNIST dataset.

Gets to 99.25% test accuracy after 12 epochs
(there is still a lot of margin for parameter tuning).
16 seconds per epoch on a GRID K520 GPU.
'''

from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils

batch_size = 128
nb_classes = 10
nb_epoch = 5

# input image dimensions
img_rows, img_cols = 28, 28
# number of convolutional filters to use
nb_filters = 32
# size of pooling area for max pooling
nb_pool = 2
# convolution kernel size
nb_conv = 3

# the data, shuffled and split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train[:500]
y_train = y_train[:500]
X_test = X_test[:50]
y_test = y_test[:50]
X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

model = Sequential()

model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                        border_mode='valid',
                        input_shape=(1, img_rows, img_cols)))
model.add(Activation('relu'))
model.add(Convolution2D(nb_filters, nb_conv, nb_conv))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(nb_pool, nb_pool)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(128))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(nb_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adadelta',
              metrics=['accuracy'])

model.fit(X_train, Y_train, batch_size=batch_size, nb_epoch=nb_epoch,
          verbose=1, validation_data=(X_test, Y_test))
score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])
```

I run this script to train a simple model and then dump the weights and build 2 other models:

```python
model.save_weights("weights.h5py")

def build_model():
    model = Sequential()

    model.add(Convolution2D(nb_filters, nb_conv, nb_conv,
                            border_mode='valid',
                            input_shape=(1, img_rows, img_cols)))
    model.add(Activation('relu'))
    model.add(Convolution2D(nb_filters, nb_conv, nb_conv))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(nb_pool, nb_pool)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(128))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(nb_classes))
    model.add(Activation('softmax'))
    
    model.load_weights("weights.h5py")
    return model

model_2 = build_model()
model_2.compile(loss='categorical_crossentropy',
              optimizer='adadelta',
              metrics=['accuracy'])
model_3 = build_model()
model_3.compile(loss='categorical_crossentropy',
              optimizer='adadelta',
              metrics=['accuracy'])
```

And when I try to predict and I have exactly the same predictions:

```python
out2 = model_2.predict(X_train[0:100])
print(np.argmax(out2, axis=1))

out3 = model_3.predict(X_train[0:100])
print(np.argmax(out3, axis=1))

assert np.allclose(out2, out3)
```

Could you try this?

**Comment by tboquet** [comment]
I didn't see your last comment. Cool! My bad, the compile method organize the model so it can be trained, especially the loss function (weights on the loss and the observations) and the optimizer. The initialization is made when you instantiate a layer.

**Comment by DepthFirstSearch** [comment]
Thanks for your help and advice so far!

I'm still confused about one thing. How should I handle the following: I want to take a pre-trained VGG16 model and run it on my own data. Because this VGG16 was pre-trained on ImageNet, its output layer contains 1000 neurons/classes. Now, I just want to drop this last layer and replace it with a new output layer, containing say 10 neurons/classes. The workflow would be:
1. Build the pre-trained model with its 1000 classes.
2. Compile this model.
3. Load the pre-trained weights.
4. Drop the last layer and replace it by a smaller one.
5. Necessarily recompile the model.
I'm wondering if this recompiling would do any harm. I don't want to run into similar problems as I had above.

**Comment by alyato** [comment]
@DepthFirstSearch I see  the #2371 can help you.

**Comment by tengerdata** [comment]
I've been trying to use _model.predict_ to predict one single image. But, for some reason, I can't get it right. I get the following error: _"Error when checking : expected convolution2d_input_23 to have 4 dimensions, but got array with shape (1, 28, 28)"_
This is the first time I am experimenting with Keras, so obviously missing something.
Anyone can help me with this?

**Comment by baloodevil** [comment]
@tengerdata The input is expecting array with shape (1,28,28,1) instead of (1,28,28).  Use `myimage = np.expand_dims(myimage, axis=3)`

By the way, this should be posted on [the keras forum](https://groups.google.com/forum/#!forum/keras-users).  Github issues are intended for tracking bugs.

**Comment by agpoyraz** [comment]
when you use your model for prediction after training, dropout layer must ben removed. Otherwise your result can be different in every testing time(generally results are close but different from each other )

**Comment by MichalDulemba** [comment]
@agpoyraz Could you elaborate on this?  I wrote a small function to test on which images my network is failing, and have much worse results than in model.evaluate.

**Comment by anewlearner** [comment]
Any update for this problem?
I saved the model.  In the test process, I removed the dropout layer and load the weight from the saved model. But there remains difference in two test.

**Comment by YaroslavSchubert** [comment]
@agpoyraz No need to remove dropout as it's used only in train phase. Keras use `in_train_phase` under the hood.

**Comment by nageshwaghmare** [comment]
[hkhdkdfkj](xvideos.com)

**Comment by ShahrukhKhan95** [comment]
I want to get the label of 3 classes in food classification using deep learning:

if np.argmax(model_out, axis=1):
        str_label= 'Fries'
    elif np.argmax(model_out, axis=0):
        str_label= 'Pizza'
    else:
        str_label= 'VegBurger'

at the end of code as above, getting the error as:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by mocksu** [comment]
Is there a solution to this problem? I am have the same problem.

**Comment by InChristAlone** [comment]
when I use model.save I also encounter the strange problem--yield random result when predict., so then I save the model architecture to .yaml and weights to .h5. then reload the model, but also face the same problem 

but an exciting thing happen when I change from
model_from_yaml(loaded_model_yaml)
to 
tf.keras.models.model_from_yaml(loaded_model_yaml)

it works, yield the same prediction results!
