### ISSUE TITLE
TimeDistributed layer as output

### ISSUE THREAD

**Issue by joggino** [fchollet/keras#3191]
1) Can I use the time distributed layer as an output?

2) Am I right in thinking if I have a time distributed layer after a LSTM and I give a sequence of targets to learn, it'll transmit the error through every temporal slice, therefore being equivalent to myself splitting the data in every combination going forward;
 i.e. {[t,t+1],[t,t+1,t+2].....[t,...,t+n]}

I'm asking as I could split my data in that way, ensuring it learns all these patterns, but then I'll need it to do a lot more computation for something which should be equivalent if I'm right.

**Comment by fchollet** [comment]
> 1) Can I use the time distributed layer as an output?

Sure, why not? It's just a layer.

2) Yes, TimeDistributed simply repeats the same operation on every temporal
slice of an input, independently.

**Comment by joggino** [comment]
Thanks, Although the description is clear, I think it would be nice to state the output part also, since it only mentions the use as an input.
