### ISSUE TITLE
TypeError: ‘TensorVariable’ object is not callable

### ISSUE THREAD

**Issue by abderhasan** [fchollet/keras#3192]
I'm following [this tutorial](http://blog.christianperone.com/2016/01/convolutional-hypercolumns-in-python/). The code version I currently have can be found [here](https://www.dropbox.com/s/nlg78oyvkrj86v6/hypercolumn.py?dl=1).

When I try to run the code, I get the following:

```
Using Theano backend.
Traceback (most recent call last):
File “hypercolumn.py”, line 85, in
get_feature = theano.function([model.layers[0].input], model.layers[3].output(train=False), allow_input_downcast=False)
TypeError: ‘TensorVariable’ object is not callable
```

How can I solve this issue?

Thanks.

**Comment by ChristianThomae** [comment]
The code seems to be made for a pre-1.0 keras version.
But with a quick modification it should still work.
Have a look at the [FAQ: How can I visualize the output of an intermediate layer](http://keras.io/getting-started/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer).

Something like this should work:
```python
get_feature = K.function([model.layers[0].input, K.learning_phase()], model.layers[15].output)
feat = get_feature([im, 0]) # 0 -> train=false
```

**Comment by jhoffman357** [comment]
Thanks Christian! Was working on the same tutorial as abderhasan. Worked great.

**Comment by abrahamrhoffman** [comment]
Thanks Christian! Worked for me as well.

**Comment by RaceSu** [comment]
I had the same trouble and I solved the problem with the following code.
~~~
from keras import backend as K 
K.function([model.layers[0].input], model.layers[3].output)
~~~
