### ISSUE TITLE
[enhance] SparseTensor support to keras

### ISSUE THREAD

**Issue by dzhwinter** [fchollet/keras#3194]
Recently we encountered a new problem that we need sparse representation and sparse computing. 
In fact,  sparse represent used in many place, even though dense embeding encode is the mainstream method in language model, but one hot encode still worth to explore. And in image processing sparse convolution can apply here properly. We really need sparse computing support in keras.
However, to the best of my knowledge, there is no proper way to meet our needs.

As a result, is there anyone in community wanna to do it with me?

It seems need to do some jobs

```
1. add backend sparse convolution support in tensorflow and theano
2. write specific convolution layer 
3. convert input into sparse representation format.
```

To 1, there is no sparse backend support at this time. 
backend sparse computing support
tensorflow:  https://github.com/tensorflow/tensorflow/issues/1604. 
but there is no highlevel API avaiable at this moment, we need to implement it ourselvs.

theano:  https://groups.google.com/forum/#!searchin/theano-users/sparse/theano-users/K7y3hRc1Qxg/VIAv4TB_8qAJ
theano do have support sparse represent in sandbox, however, there is no example how to use it, and the implement code is a mess, even the sparse layer test code is an fake sparse represent.

cusparse: 
nvidia provide the thrid party support with sparse computing, however, it hard to intergrate cusparse with keras current state.

 sparseConv: https://github.com/btgraham/SparseConvNet/wiki
this is the best implement of sparse convolution so far, and had be proven to use sparse convolution in spatial domain,  besides, he win the CIFAR10 competition in Kaggle, which show the potential in sparse represent.

Im working on support tensorflow sparse represent , Any ideas and any collaborate is welcome!

**Comment by nouiz** [comment]
Just a clarification, Theano on CPU, we support sparse computation. We
don't develop it anymore, but it is working and not in sandbox. On the GPU,
we only have a draft somewhere that I started, it is not in sandbox that
was wrapping cusparse. But some speed tests shown us that we loose a big
part of the GPU speed up with sparse compution. That is why we put it aside.

So for Theano, if you want to quickly start, you probably have all the
operation needed on CPU.

**Comment by tchaton** [comment]
Hello everyone,

https://github.com/openai/blocksparse repo contains highly optimized sparse block.

It won t be too hard to create a Keras wrapper on top of it.

I hope you will have time to look into it.

Best
