### ISSUE TITLE
some doubt about SGD Optimizer Source Code

### ISSUE THREAD

**Issue by dongzhuoyao** [fchollet/keras#3197]
![image](https://cloud.githubusercontent.com/assets/13537104/16737292/4f986a06-47c3-11e6-8717-a95aaee8509b.png)

as above picture described,I have some doubt about:

`
self.weights = [K.variable(np.zeros(K.get_value(p).shape)) for p in params]
`

it seems that every time we call get_update() method,self.weights will be a zero numpy tensorvariable!!!

but according to SGD's definition,it should be the delta value of the last batch,which we call "momemtum"

Did I miss something ? I just cannot figure it out...

**Comment by dongzhuoyao** [comment]
@fchollet could you please give me a hint?

**Comment by maxbry** [comment]
`get_updates` is only called once and symbolic GPU objects are being created. `self.weights` is initialized with zeros, which are then updated later.

**Comment by dongzhuoyao** [comment]
@maxbry  thank you very much!
