### ISSUE TITLE
Missing Documentation Source

### ISSUE THREAD

**Issue by mossaab0** [fchollet/keras#3198]
I can't find the sources folder under [keras/docs](https://github.com/fchollet/keras/tree/master/docs). I wanted to fix the pointers to source code of MaxPooling1D and MaxPooling2D (and maybe others).

**Comment by ddofer** [comment]
I add to this that the documentation and parameters for a number of functions in the  http://keras.io/ documentation is out-of-date or missing parameters found in the source code.

(There are many such examples. e.g. text.tokenizer in the keras.io documentation does not display the "char_level=" option.

https://github.com/fchollet/keras/blob/master/keras/preprocessing/text.py
http://keras.io/preprocessing/text/#tokenizer

Thanks!

**Comment by angelo337** [comment]
this dataset can be found on:
https://research.facebook.com/research/babi/
