### ISSUE TITLE
Non time distributed Embeddings / Lookup tables

### ISSUE THREAD

**Issue by vzhong** [fchollet/keras#320]
Before #244, I could make a lookup table that is not time distributed in the following manner:

```python
net = Sequential()
net.add(Embedding(5, 2))
net.add(Flatten())
net.add(Dense(2, 3))
net.compile(loss='categorical_crossentropy', optimizer='sgd')
```

However, with the changes made to `Embedding` in #244, the above code now raises an Exception:

```text
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-4-3e29ac8f8e5c> in <module>()
      1 net = Sequential()
      2 net.add(Embedding(5, 2))
----> 3 net.add(Flatten())
      4 net.add(Dense(2, 3))
      5 net.compile(loss='categorical_crossentropy', optimizer='sgd')

/Users/victor/Developer/keras/keras/layers/containers.pyc in add(self, layer)
     31         self.layers.append(layer)
     32         if len(self.layers) > 1:
---> 33             self.layers[-1].connect(self.layers[-2])
     34 
     35         params, regularizers, constraints = layer.get_params()

/Users/victor/Developer/keras/keras/layers/core.py in connect(self, layer)
     22     def connect(self, layer):
     23         if not self.supports_masked_input() and layer.get_output_mask() is not None:
---> 24             raise Exception("Attached non-masking layer to layer with masked output")
     25         self.previous = layer
     26 

Exception: Attached non-masking layer to layer with masked output
```

Admittedly, the above code for making a non-time-distributed look up table is somewhat hacky. What's the appropriate way for doing this? From what I understand, #176 was to add masking support for recurrent layers. However this seemed to break functionality for some of the utility layers (eg. `Flatten()`, `Reshape()`) that don't implement the `MaskedLayer` interface.

**Comment by wxs** [comment]
Oh interesting, yeah I think this is a bug with the PR. The issue is that the `Flatten` layer does not support masking, and that the `Embedding` layer is for some layer giving a non-None mask despite not having its mask_zero flag set.

In general every layer should work the same as before, *unless* you explicitly enable masking for a layer, at which point every layer in the stack needs to support masking. 

I'll put up a quick PR that I think should fix this.

**Comment by wxs** [comment]
OK I put up #323, can you give it a try and let me know if it fixes things for you?

**Comment by vzhong** [comment]
Cool! It works on my end. Thanks @wxs !
