### ISSUE TITLE
Keras doesn't work with theano on mac

### ISSUE THREAD

**Issue by sfilatye** [fchollet/keras#3201]
I have OS X 10.11.5 and I just updated keras, theano, and tensorflow. I cannot use Theano anymore - it produces Illegal instruction: 4 error. Tensorflow works but 4x slower than theano used to.

**Comment by dongzhuoyao** [comment]
just paste the 4 error.

**Comment by sfilatye** [comment]
I think I found a way around it. It looks like the c++ compiler clang that mac uses has some issues with theano. I installed gcc 6.1.0 using homebrew and modified .bash_profile to include
export PATH=/usr/local/Cellar/gcc/6.1.0/bin:$PATH
alias gcc='gcc-6'
alias cc='gcc-6'
alias g++='g++-6'
alias c++='c++-6'

Now it seems to be working.

**Comment by kmader** [comment]
Installing Theano freshly from the latest git repository worked for me.

```bash
pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
```

or (for the user directory)

```bash
pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git --user
```
