### ISSUE TITLE
Many to Many sequence with LSTM

### ISSUE THREAD

**Issue by dr-costas** [fchollet/keras#3204]
Hi, 

In the many-to-many sequence paradigm there are two cases as show in the picture:

![diags](https://cloud.githubusercontent.com/assets/7984120/16764437/d590eff2-4836-11e6-9b7a-0b09a5c89725.jpeg)

So, how can one implement in Keras the fourth from left to right?

**Comment by udibr** [comment]
check this code https://github.com/udibr/headlines
