### ISSUE TITLE
Embedding layers and dot product

### ISSUE THREAD

**Issue by code-ball** [fchollet/keras#3207]
Hi,

I have two inputs for which I learn the embeddings and then I want to dot product the embedded vectors to get a scaler value. I tried to use Merge layer with 'dot' mode but it still output a tensor. I am not able to understand how to get the output as I want.

Following is the input and embedding details:

``` python
inp1 = np.random.randint(1000, size=(10000,1))
inp2 = np.random.randint(1000, size=(10000,1))

a = Input(shape=(1,),dtype='int32',name='a')
b = Input(shape=(1,),dtype='int32',name='b')

em_ab = Embedding(output_dim=512,input_dim=1000,input_length=1)
em_a = em_ab(a)
em_b = em_ab(b)
```

As you can see my training input is a pair of integers. Each value range between 1 and 1000, and there are 10000 such pairs.
As each input has only one value, input_lenght=1 for embedding layer. Once the embedding completes,
I want to extract the embedded vectors for each training pair i.e. currently both em_a and em_b will have shape (None, 1, 512). But I want to extract the last dim for both embeddings which will give me a vector of size 512 for each of them.

How to do this? I tried reshape and squeeze options in addition to above but I think I am confused when this should be very simple. Can you help to see where am I going wrong?

Thanks

**Comment by fchollet** [comment]
Surely you want to use the `Flatten()` layer?

**Comment by code-ball** [comment]
Thanks for the response. So the Flatten() will give me the vector itself? If yes, it will still be a tensor variable, correct? How do I access the values of that vector in this scenario?

**Comment by farizrahman4u** [comment]
First of all, you said your inputs are in range [1, 1000]. You might want to map them to range [0, 999].
`Flatten` simply does what you ask for, it reshape your `(None, 1, 512)` tensor to `(None, 512)`.

Can you explain what you mean by "access the values of that vector?"

If you simply want to dot product them:
```python
em_ab = Embedding(output_dim=512,input_dim=1000,input_length=1)
em_a = em_ab(a)
em_a = Flatten()(ema_a)
em_b = em_ab(b)
em_b = Flatten()(ema_b)

match = merge([em_a, em_b], mode='dot', dot_axes=(1, 1))
```

**Comment by aziesmaeili** [comment]
Hi I wanted to apply merge for dot product. But I got this issue [TypeError: 'module' object is not callable].
Do you have any ideas to solve it?

**Comment by anagornaia** [comment]
same issue as @aziesmaeili 
![image](https://user-images.githubusercontent.com/41295312/48342112-857f2880-e677-11e8-8a51-1572c8d967d9.png)

**Comment by anagornaia** [comment]
> Hi I wanted to apply merge for dot product. But I got this issue [TypeError: 'module' object is not callable].
> Do you have any ideas to solve it?

u can use keras.layers.dot instead
