### ISSUE TITLE
Cannot visualise

### ISSUE THREAD

**Issue by willgdjones** [fchollet/keras#3216]
Love the library btw. This seems to be an issue with pydot from what I can tell.

`from keras.utils.visualize_util import plot`

AttributeError                            Traceback (most recent call last)
<ipython-input-47-a56f5e84dcf4> in <module>()
     17 from PIL import Image
     18 import matplotlib.pyplot as plt
---> 19 from keras.utils.visualize_util import plot
     20 get_ipython().magic(u'matplotlib inline')
     21 

/Users/fonz/anaconda/lib/python2.7/site-packages/keras/utils/visualize_util.py in <module>()
      5     # fall back on pydot if necessary
      6     import pydot
----> 7 if not pydot.find_graphviz():
      8     raise RuntimeError('Failed to import pydot. You must install pydot'
      9                        ' and graphviz for `pydotprint` to work.')

AttributeError: 'module' object has no attribute 'find_graphviz'

**Comment by willgdjones** [comment]
Here is my pydot version:

---
Metadata-Version: 2.0
Name: pydot
Version: 1.2.2
Summary: Python interface to Graphviz's Dot
Home-page: https://github.com/erocarrera/pydot
Author: Ioannis Filippidis
Author-email: jfilippidis@gmail.com
Installer: pip
License: MIT
Location: /Users/fonz/anaconda/lib/python2.7/site-packages
Requires: pyparsing
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  Intended Audience :: Science/Research
  License :: OSI Approved :: MIT License
  Natural Language :: English
  Operating System :: OS Independent
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Topic :: Scientific/Engineering :: Visualization
  Topic :: Software Development :: Libraries :: Python Modules

**Comment by nouiz** [comment]
New pydot version break many packages.

Use pydot 1.1.0.

https://github.com/erocarrera/pydot/commit/812e3c40dac1e0225391481073c64da5bafba93e

**Comment by willgdjones** [comment]
Thanks @nouiz

**Comment by johnyf** [comment]
The solution to the issue reported above is to remove the call `pydot.find_graphviz` from here: https://github.com/fchollet/keras/blob/fd3cfb196b2be22c274cc7b7f0abbd1c8e87a2c2/keras/utils/visualize_util.py#L7.

Please let `pydot` itself search for GraphViz executables, and complain if not found in the `$PATH`, which is the user's responsibility to install.

**Comment by nouiz** [comment]
I don't like the idea of postponing the error. WIth the old version, we where able to give an error to the user when it was importing the optional module that use pydot.

Now, the error can happen after hours of computation.

We just need this method to do what pydot currently do when it get called. We don't need the old check, just the current check. This allow much better user error.

**Comment by johnyf** [comment]
Please see this comment: https://github.com/erocarrera/pydot/commit/812e3c40dac1e0225391481073c64da5bafba93e#commitcomment-18236709, where I describe how you can still check early, by calling the method `create` of an empty graph.

**Comment by ogrisel** [comment]
@johnyf the error raised by pydot if graphviz is not installed is the following:

```
Exception: "dot" not found in path.
```

This is error message is not explicit enough for users of third party libraries that use pydot has an internal dependency. The end users do not necessarily know that the `dot` command is provided by graphviz. Furthermore the use of a generic exception type such as `Exception` makes it impossible for the third party library developers to catch the exception and raise a more informative user message such as "graphviz is required to use this visualization. Please install it and ensure that the 'dot' command can be found in the path".

**Comment by 0bserver07** [comment]
This still seems to be an issue, did you folks got it resolved?

I have:
- `keras 1.0.7`
- `Theano-0.8.2` then tried `Theano-0.9.0.dev2`

I tried installing older `pydot` as well, `pydot==1.1.0`, but still this error shows up:

```python
/usr/local/lib/python2.7/site-packages/keras/utils/visualize_util.py in <module>()
      5     # fall back on pydot if necessary
      6     import pydot
----> 7 if not pydot.find_graphviz():
      8     raise RuntimeError('Failed to import pydot. You must install pydot'
      9                        ' and graphviz for `pydotprint` to work.')

AttributeError: 'module' object has no attribute 'find_graphviz'

```

It looks like removing `pydot.find_graphviz()` could resolve this issue, but it's still here [visualize_util.py#L7L-7](https://github.com/fchollet/keras/blob/master/keras/utils/visualize_util.py#L7).

**Comment by varoudis** [comment]
Pydot-ng fixes it
I had the same problem

**Comment by 0bserver07** [comment]
@varoudis 🙌 ! Works like a charm...

**Comment by malaikannan** [comment]
@varoudis did you change visualize_util.py to import pydotng?? I am running into the same issue , installed pydot 1.1.0 still doesn't seem to fix it.

**Comment by johnyf** [comment]
In Theano the problem has been fixed, as reported here: https://github.com/erocarrera/pydot/commit/812e3c40dac1e0225391481073c64da5bafba93e#commitcomment-18266611, and the latest release of `pydot` is 1.2.2.

**Comment by ogrisel** [comment]
> @varoudis did you change visualize_util.py to import pydotng?? I am running into the same issue , installed pydot 1.1.0 still doesn't seem to fix it.

It's already the case. install pydotng instead of pydot.

**Comment by malaikannan** [comment]
Thanks @ogrisel pydot 1.1.0 worked for me and thanks for all the amazing contribution to Scikit-learn.
