### ISSUE TITLE
How does one freeze specific parameters within a layer?

### ISSUE THREAD

**Issue by ago109** [fchollet/keras#3217]
I am using a very recent version of Keras (as of the start of last week).  Very simply put, **how do I freeze a specific weight in a given (recurrent) layer?**  Note that I do NOT want to freeze the entire layer, just a specific parameter (such as the input-to-hidden parameter matrix).

I wrote this manually and it works during training (Note that ellipsis "..." implies "stuff goes here" that is being omitted for clarity):

```
...
model.compile(...)
# move recurrent layer's input-to-hidden parameters to non-trainable
rnn1_W = model.layers[1].W
model.layers[1].trainable_weights = [model.layers[1].U,model.layers[1].b]
model.layers[1].non_trainable_weights = [rnn1_W]
...
```

Saving the model to disk with the usual save_weights(...) also works. _However_, when I load this model with the load_weights(...) routine, I get a Theano error:

```
Traceback (most recent call last):
  .../site-packages/keras/engine/topology.py", line 2402, in load_weights
    K.batch_set_value(weight_value_tuples)
  File ".../site-packages/keras/backend/theano_backend.py", line 515, in batch_set_value
    x.set_value(np.asarray(value, dtype=x.dtype))
  File ".../site-packages/theano/compile/sharedvalue.py", line 127, in set_value
    self.container.value = copy.deepcopy(new_value)
  File ".../site-packages/theano/gof/link.py", line 471, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)
  File ".../site-packages/theano/tensor/type.py", line 178, in filter
    data.shape))
TypeError: ('Wrong number of dimensions: expected 2, got 1 with shape (20,).', 'Container name "simplernn_1_U"')
```

How do I move a specific matrix (such as "W" in the SimpleRNN layer) into non-trainable so that way it isn't updated during training (and any computation normally spent on computing its gradient isn't performed) but the other parameters are?  "W" itself should still be used in the inference process (i.e., to gather statistics normally done in the feedforward operations).

Thank you very much.

**Comment by braingineer** [comment]
The model accumulates its layers inside the [constructor](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1763).  So, in order to get the save/load to work with ad hoc modifying a single layer's, you'd need to redo these steps. 

A better solution would be to subclass the RNN you want, and do:

```python
def build(*args, **kwargs):
    super(CustomRNN, self).build(*args, **kwargs)
    self.trainable_weights = [self.things, self.you, self.want]
    self.non_trainable_weights = [self.things, self.you, self.want]
```

**Comment by RohitKeshari** [comment]
I have also faced a similar problem, wrote on this [page](http://stackoverflow.com/questions/42741402/keras-trainable-weight-issue). While removing W from trainable_weights and learning only bias not possible to freeze W at 0 epoch to 200 epoch

**Comment by br3xk** [comment]
I am facing the same problem. I am trying to build a transfer model using the standard Keras library. I am freezing the weights of the kernel and recurrent_kernel of the first layer of the model by following code...

#freeze weights
for weight in modelTL.layers[0].weights:
    if 'kernel' in weight.name:
        print(weight.name)
        weight._trainable = False
        print(f"weight name: {weight.name}, Trainable: {weight.trainable}") 
    if 'recurrent_kernel' in weight.name:
        print(weight.name)
        weight._trainable = False
        print(f"weight name: {weight.name}, Trainable: {weight.trainable}") 
    elif 'bias' in weight.name:
        print(weight.name)
        weight._trainable = True
        print(f"weight name: {weight.name}, Trainable: {weight.trainable}") 

But when I check the summary of the Transfer Model, I see there are no non-trainable params.

Total params: 1,404
Trainable params: 1,404
Non-trainable params: 0

Can anyone help me how to freeze specific weights with a specific layer of the LSTM model in standard KERAS?
Please note that I don't want to freeze an entire layer. I want to freeze a specific weight type [either kernel (W) or recurrent_kernel (U)] of a layer.

Here is my full code. Please help.....


import random
import numpy as np
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM
from keras.models import load_model

# set random seeds
np.random.seed(1)
tf.random.set_seed(1)
random.seed(1)

'base model'
# Data
train_x = np.random.rand(100, 4, 8)
train_y = np.random.rand(100, 4)
test_x = np.random.rand(30, 4, 8)
test_y = np.random.rand(30, 4)

# LSTM model
model = Sequential()
model.add(LSTM(units=10, activation='relu', input_shape=(train_x.shape[1], train_x.shape[2]), return_sequences=True, use_bias=True))
model.add(LSTM(units=8, activation='relu'))
model.add(Dense(activation='linear', units=4, use_bias=True))
model.compile(loss='mse', optimizer='Nadam', metrics=['mse','mae'] ) 

# fit model
history=model.fit(train_x, train_y, validation_data=(test_x, test_y), epochs=3, verbose=1, batch_size=64)
model.save("source_model.h5")

model.summary()

'check Base model weights'
kernelB, recurrent_kernelB, biasB = model.layers[0].weights
print ('kernelB', kernelB)
print ('recurrent_kernelB', recurrent_kernelB)
print ('biasB', biasB)


'transfer model'
# Data
train_x1 = np.random.rand(200, 4, 8)
train_y1 = np.random.rand(200, 4)
test_x1 = np.random.rand(60, 4, 8)
test_y1 = np.random.rand(60, 4)

# Load the pre-trained model
pretrained_model = load_model('source_model.h5')
pretrained_model.layers

# 'Initialize' new Sequential model
modelTL = Sequential()

# extract all the layers from the pre-trained model with unique names
for layer in pretrained_model.layers:
    new_layer = layer.__class__.from_config(layer.get_config())
    new_layer._name = f'trainable_{layer.name}'
    modelTL.add(new_layer)
    
    
#freeze weights
for weight in modelTL.layers[0].weights:
    if 'kernel' in weight.name:
        print(weight.name)
        weight._trainable = False
        print(f"weight name: {weight.name}, Trainable: {weight.trainable}") 
    if 'recurrent_kernel' in weight.name:
        print(weight.name)
        weight._trainable = False
        print(f"weight name: {weight.name}, Trainable: {weight.trainable}") 
    elif 'bias' in weight.name:
        print(weight.name)
        weight._trainable = True
        print(f"weight name: {weight.name}, Trainable: {weight.trainable}") 


# Compile the model
modelTL.compile(loss='mse', optimizer='Nadam', metrics=['mse', 'mae'])

# Fit the model
historyTL = modelTL.fit(train_x1, train_y1, validation_data=(test_x1, test_y1), epochs=3, verbose=1, batch_size=64)

modelTL.summary()

# Save the transfer model
modelTL.save("TL_model.h5")

'check Transfer model weights'
kernelTL, recurrent_kernelTL, biasTL = modelTL.layers[0].weights
print ('kernelTL', kernelTL)
print ('recurrent_kernelTL', recurrent_kernelTL)
print ('biasTL', biasTL)
