### ISSUE TITLE
Convolution1D Input Error

### ISSUE THREAD

**Issue by valexandersaulys** [fchollet/keras#322]
I saw that Convolution1D layer requires the input to be a 4D tensor and not a 3D tensor of (nb_samples, nb_channels, sequence_length), but some tensor that gets wrapped by T.nnet.conv.conv2d(X, (nb_filter, stack_size, 1, filter_length)). See  <https://github.com/fchollet/keras/issues/272> for more on this post. 

I have the following code that is throwing a weird error for me, after I format the input to be a 4D tensor. I thought that it might be best to leave it as a 2D input of (nb_samples, seq_length), but also throws an error as it expected the input to be 4D. Below is a snippet of my code.

nb_samples = x_train.shape[0]
nb_features = x_train.shape[1]
newshape = (nb_samples, 1, nb_features, 1)
print newshape
x_train = np.reshape(x_train, newshape).astype('float32')
print x_train.shape; print x_train;

model = Sequential()
model.add(Convolution1D(nb_filter=5, 
                        stack_size=1, 
                        filter_length=3, 
                        init='uniform', 
                        activation=activation_function_1))
model.add(MaxPooling1D(pool_length=3))
model.add(Convolution1D(nb_filter=5, 
                        stack_size=1, 
                        filter_length=3, 
                        init='uniform', 
                        activation=activation_function_1))
model.add(MaxPooling1D(pool_length=3))
model.add(Dense(input_dim=100,output_dim=1,init='uniform'))
model.add(Activation('linear'))
print "Now Building Model"
print "Model will run for " + str(num_epochs)
model.compile(loss='mean_squared_error',
              optimizer=RMSprop(lr=LR)
              )

print "Model Compiled! Now fitting ... "

model.fit(x_train,y_train,nb_epoch=num_epochs,batch_size=BATCH_SIZE)

And below is the error I receive. 

Traceback (most recent call last):
  File "keras_conv1d.py", line 103, in <module>
    model.fit(x_train,y_train,nb_epoch=num_epochs,batch_size=BATCH_SIZE)
  File "/home/sensauratech/ml_vincent/keras/keras/models.py", line 241, in fit
    loss = self._train(*ins)
  File "/home/sensauratech/Theano/theano/compile/function_module.py", line 534, in __call__
    allow_downcast=s.allow_downcast)
  File "/home/sensauratech/Theano/theano/tensor/type.py", line 168, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/home/sensauratech/ml_vincent/keras/keras
/models.py:127"  at index 1(0-based)', 'Wrong number of dimensions: expected 4, got 2 with shape (1, 1)
.')       

I am so lost as to what to do here. Not formatting the input to be 4D results in the following error instead.

Traceback (most recent call last):
  File "keras_conv1d.py", line 95, in <module>
    model.fit(x_train,y_train,nb_epoch=num_epochs,batch_size=BATCH_SIZE)
  File "/home/sensauratech/ml_vincent/keras/keras/models.py", line 241, in fit
    loss = self._train(*ins)
  File "/home/sensauratech/Theano/theano/compile/function_module.py", line 534, in __call__
    allow_downcast=s.allow_downcast)
  File "/home/sensauratech/Theano/theano/tensor/type.py", line 168, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/home/sensauratech/ml_vincent/keras/keras
/models.py:127"  at index 0(0-based)', 'Wrong number of dimensions: expected 4, got 2 with shape (1, 73
57).')      

Any help would be much appreciated!  I am at a loss of what to do. :)

**Comment by bcordo** [comment]
I'm having the same problem. Thanks so much for the great library.

**Comment by fchollet** [comment]
Ok, the API for Convolution1D and MaxPooling1D sucks. I agree. It's counter-intuitive and error-prone. That's my daily reminder to be more careful when accepting PRs. 

So let's change it.

**Comment by fchollet** [comment]
I change the API, implementation and documentation of Convolution1D and MaxPooling1D. https://github.com/fchollet/keras/commit/243d4737d1caaf7d586abc69addef16a08276231

The experience should be much better now. Let me know if that solves your problems.

**Comment by bcordo** [comment]
Wow! Thanks for the super fast response. Let me know if you need any help (even if it's boring and repetitive). I feel like I need to give back for Keras saving me so much time. Really appreciate it.

**Comment by mikekestemont** [comment]
Great update, @fchollet! I think it would be insightful to add a working example on conv1d to the examples dir. I could contribute a first attempt using a character-level convolution for a text classification task (with one channel for each char in the alphabet?) in the coming days, if that's useful? The imdb dataset might be good for this, potentially with an LSTM overlaid, to give an example of how the output of 1D convs could be processed?

**Comment by fchollet** [comment]
> The imdb dataset might be good for this, potentially with an LSTM overlaid

Maybe an Embedding + a small stack of Conv1D and MaxPooling1D, for text classification. Would be interesting to see if it outperforms LSTM.

**Comment by valexandersaulys** [comment]
Hello, thanks for the error fixing! I really appreciate the work, this is a fantastic library.

I am still having issues with the conv1d however. Is the y (target) values also to be a 3d tensor? If so, how should they be arranged? 

My input is similar to before, being a 3d-tensor of (sample, time_step, signal). The target values would be just (sample), but I reshaped it to correspond to a 2d-tensor. Doing so causes an error to be thrown as Keras expects a 3d tensor. When I reshape to a 3d-tensor, I get something about the stack size not being uniform.

Error with my earlier approach:
Min Length is 7357
x_input -> (368, 7357, 1) y_input -> (368, 1)
Max Length is 20014
Min Length is 7357
validation_input -> (128, 7357, 1) validation_target -> (128, 1)
Now Building Model
Model will run for 1
Model Compiled! Now fitting ... 
Epoch 0
Traceback (most recent call last):
  File "keras_conv1d.py", line 95, in <module>
    nb_epoch=num_epochs,batch_size=BATCH_SIZE)
  File "/home/sensauratech/ml_vincent/keras/keras/models.py", line 371, in fit
    validation_split=validation_split, val_f=val_f, val_ins=val_ins, shuffle=shuffle, metrics=metrics)
  File "/home/sensauratech/ml_vincent/keras/keras/models.py", line 135, in _fit
    outs = f(*ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 513, in __call
__                                                                                                   
    allow_downcast=s.allow_downcast)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 169, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/home/sensauratech/ml_vincent/keras/kera
s/models.py:286"  at index 1(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (1, 1).')

My error with the reshaping the target values to a 3d tensor is as follows:
Using gpu device 0: GeForce GTX 750 Ti
Max Length is 20014
Min Length is 7357
(368, 7357, 1) (368, 1, 1)
Max Length is 20014
Min Length is 7357
(128, 7357, 1) (128, 1, 1)
Now Building Model
Model will run for 1
Model Compiled! Now fitting ... 
Epoch 0
Traceback (most recent call last):
  File "keras_conv1d.py", line 95, in <module>
    nb_epoch=num_epochs,batch_size=BATCH_SIZE)
  File "/home/sensauratech/ml_vincent/keras/keras/models.py", line 371, in fit
    validation_split=validation_split, val_f=val_f, val_ins=val_ins, shuffle=shuffle, metrics=metrics)
  File "/home/sensauratech/ml_vincent/keras/keras/models.py", line 135, in _fit
    outs = f(*ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 606, in __call
__                                                                                                   
    storage_map=self.fn.storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 595, in __call
__                                                                                                   
    outputs = self.fn()
ValueError: GpuCorrMM images and kernel must have the same stack size
[ Followed by a long stack trace that is likely not that important, but I can post if needed ]


Thanks again for all the help, it is much appreciated!

**Comment by valexandersaulys** [comment]
I also tried not reshaping the target values and just passing them through as is:
(128, 7357, 1) (128,)
Now Building Model
Model will run for 1
Model Compiled! Now fitting ... 
Epoch 0
Traceback (most recent call last):
  File "keras_conv1d.py", line 93, in <module>
    nb_epoch=num_epochs,batch_size=BATCH_SIZE)
  File "/home/sensauratech/ml_vincent/keras/keras/models.py", line 371, in fit
    validation_split=validation_split, val_f=val_f, val_ins=val_ins, shuffle=shuffle, metrics=metrics)
  File "/home/sensauratech/ml_vincent/keras/keras/models.py", line 135, in _fit
    outs = f(*ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 513, in __call
__                                                                                                   
    allow_downcast=s.allow_downcast)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 169, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/home/sensauratech/ml_vincent/keras/kera
s/models.py:286"  at index 1(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (1, 
1).') 

FYI, I also am using this for a regression problem if that means anything.

**Comment by darzok** [comment]
hello, i would like to use conv1D for a regression problem but Conv1D layer soud dosen't work with me ... 

does anybody manage to do a regression with conv1D ?

**Comment by ddofer** [comment]
Currently failing at getting 1D convolutions and pooling working with one-hot encoded characters.
