### ISSUE TITLE
Import Error from fresh install

### ISSUE THREAD

**Issue by willgdjones** [fchollet/keras#3224]
I'm getting an import error when I run the mnist example script [https://github.com/fchollet/keras/blob/master/examples/mnist_mlp.py] with a fresh install on a GPU.

ImportError: ('The following error happened while compiling the node', Dot22(dense_input_1, dense_1_W), '\n', '/nfs/users/nfs_w/wj2/.theano/compiledir_Linux-3.2--generic-x86_64-with-Ubuntu-12.04-precise-x86_64-2.7.3-64/tmpoukhqK/e3c8de9d51e298a853a3dc6d24b85ffd.so: undefined symbol: _gfortran_transfer_integer_write', '[Dot22(dense_input_1, dense_1_W)]')

Any clues as to where to start? I have everything installed from the Theano installation page.

Thans

**Comment by willgdjones** [comment]
Seems like gfortran is not included in the version of Ubuntu I'm using, however this should have been install with gcc.

**Comment by fchollet** [comment]
This is a Theano install error. Better refer to the Theano installation instructions for Ubuntu, and if you're still having problems you should open a ticket with the Theano devs.
