### ISSUE TITLE
Can't use auc_roc_score (or any other metric function based on numpy) as a custom metric?

### ISSUE THREAD

**Issue by keunwoochoi** [fchollet/keras#3230]
#1732 says we can't directly optimise auc as it is not differentiable. Then can't we have it only as a metric? 
I just hoped this might work (without proper understanding...), but have an error message in compilation.
```
from sklearn import metrics
from keras import backend as K

def auc(y_true, y_pred):
	return metrics.roc_auc_score(K.eval(y_true), K.eval(y_pred))

```
and the error is..
```
  File "/Users/gnu/Dropbox/codes/msd_tagging/my_keras_model_essence.py", line 66, in build_convnet_model
    model.compile(loss=loss_function, optimizer=optimiser, metrics=metrics)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/models.py", line 343, in compile
    **kwargs)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/engine/training.py", line 642, in compile
    self.metrics.append(metric_fn(y_true, y_pred))
  File "/Users/gnu/Dropbox/codes/msd_tagging/my_metrics.py", line 9, in auc
    return metrics.roc_auc_score(K.eval(y_true), K.eval(y_pred))
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 71, in eval
    return x.eval()
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/theano/gof/graph.py", line 520, in eval
    self._fn_cache[inputs] = theano.function(inputs, self)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 1428, in __init__
    accept_inplace)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 177, in std_fgraph
    update_mapping=update_mapping)
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/theano/gof/fg.py", line 171, in __init__
    self.__import_r__(output, reason="init")
  File "/Users/gnu/anaconda/lib/python2.7/site-packages/theano/gof/fg.py", line 367, in __import_r__
    raise MissingInputError("Undeclared input", variable)
theano.gof.fg.MissingInputError: ('Undeclared input', dense_1_target)
```
The error is from [this line](https://github.com/fchollet/keras/blob/b32248d615abfd7835886a0f50962856f7d7c986/keras/engine/training.py#L614). 

I would be convenient if numpy-based metric function can be used -- if it is not possible now. I am computing it after each iteration, but then there is redundant predictions and I can't take advantage of callbacks.

**Comment by fchollet** [comment]
Metrics functions must be symbolic functions (built with the Keras backend, or with Theano/TensorFlow).

Also ROC AUC is not a metric that be accumulated in mini-batches, it has to be computed for all the data at once.

The right thing to do is to run predictions on all of your test data at the end of an epoch, then run the sklearn function on your predictions, and display the result. You can do this in a callback.

**Comment by keunwoochoi** [comment]
Oh, I see. Thanks.

**Comment by isaacgerg** [comment]
@fchollet 

> Also ROC AUC is not a metric that be accumulated in mini-batches, it has to be computed for all the data at once.

But its reasonable to have this metric computed on the validation set at the end of each epoch.

> The right thing to do is to run predictions on all of your test data at the end of an epoch, then run the sklearn function on your predictions, and display the result. You can do this in a callback.

Correct, but the problem is that since its not in the keras metrics form, you don't get the output to tensorboard.  Am I correct?

**Comment by fchollet** [comment]
Try to use `tf.contrib.metrics.streaming_auc`. I'd be curious to see how that works out.

**Comment by isaacgerg** [comment]
@fchollet  Already tried it with 2 variations but get an error.  Ideas?
```
def auc(y_true, y_pred):   
    tf.global_variables_initializer()
    #return K.variable(value=tf.contrib.metrics.streaming_auc(y_pred, y_true)[0], dtype='float32')
    return tf.contrib.metrics.streaming_auc(y_pred, y_true)[0]
```
Results in:  FailedPreconditionError: Attempting to use uninitialized value auc/true_positives

**Comment by fchollet** [comment]
Initialize the variables created by the metrics first.

**Comment by isaacgerg** [comment]
@fchollet I don't follow.  y_true and y_pred are already initialized containing values from the keras backend.  Is this not true?

**Comment by fchollet** [comment]
Streaming metrics work by maintaining an internal state. This state exists
as a set of variables. They must be initialized.

A streaming metric is not a pure function, it's closer to a layer.

**Comment by isaacgerg** [comment]
@fchollet I'm not sure I follow.  I don't plan on using the streaming part so wouldnt setting it to None be sufficient?  Can you elaborate with code?

**Comment by isaacgerg** [comment]
@fchollet 

```
def auc(y_true, y_pred):   
    keras.backend.get_session().run(tf.global_variables_initializer())
    #return K.variable(value=tf.contrib.metrics.streaming_auc(y_pred, y_true)[0], dtype='float32')
    return tf.contrib.metrics.streaming_auc(y_pred, y_true)[0]
```

I don't see why this yields, "tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value auc/true_positives..."

**Comment by isaacgerg** [comment]
This works:

```
def auc(y_true, y_pred):   
    ptas = tf.stack([binary_PTA(y_true,y_pred,k) for k in np.linspace(0, 1, 1000)],axis=0)
    pfas = tf.stack([binary_PFA(y_true,y_pred,k) for k in np.linspace(0, 1, 1000)],axis=0)
    pfas = tf.concat([tf.ones((1,)) ,pfas],axis=0)
    binSizes = -(pfas[1:]-pfas[:-1])
    s = ptas*binSizes
    return K.sum(s, axis=0)
```

**Comment by ophiry** [comment]
can you share the full code (binary_PTA & binary_PFA) - or an explanation what they do?

**Comment by isaacgerg** [comment]
```
#-----------------------------------------------------------------------------------------------------------------------------------------------------
# AUC for a binary classifier
def auc(y_true, y_pred):   
    ptas = tf.stack([binary_PTA(y_true,y_pred,k) for k in np.linspace(0, 1, 1000)],axis=0)
    pfas = tf.stack([binary_PFA(y_true,y_pred,k) for k in np.linspace(0, 1, 1000)],axis=0)
    pfas = tf.concat([tf.ones((1,)) ,pfas],axis=0)
    binSizes = -(pfas[1:]-pfas[:-1])
    s = ptas*binSizes
    return K.sum(s, axis=0)

#-----------------------------------------------------------------------------------------------------------------------------------------------------
# PFA, prob false alert for binary classifier
def binary_PFA(y_true, y_pred, threshold=K.variable(value=0.5)):
    y_pred = K.cast(y_pred >= threshold, 'float32')
    # N = total number of negative labels
    N = K.sum(1 - y_true)
    # FP = total number of false alerts, alerts from the negative class labels
    FP = K.sum(y_pred - y_pred * y_true)    
    return FP/N
#-----------------------------------------------------------------------------------------------------------------------------------------------------
# P_TA prob true alerts for binary classifier
def binary_PTA(y_true, y_pred, threshold=K.variable(value=0.5)):
    y_pred = K.cast(y_pred >= threshold, 'float32')
    # P = total number of positive labels
    P = K.sum(y_true)
    # TP = total number of correct alerts, alerts from the positive class labels
    TP = K.sum(y_pred * y_true)    
    return TP/P
```

**Comment by NickYi1990** [comment]
I use code below to test your auc function, but return nan, any suggestion?
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=[auc])
model.optimizer.lr = 1e-4
model.fit(X_train.values, y_train.values, validation_split=0.2, epochs=1, verbose=1)

**Comment by isaacgerg** [comment]
@fchollet I did more research into this issue.  You can't use tf streaming metrics in keras because you don't have access to the tensors y_true and y_pred outside of the metrics framework.  You need to initialize the tf streaming metrics with those 2 tensors and it returns an update_op for you to call each batch

```
value = ...
mean_value, update_op = tf.contrib.metrics.streaming_mean(values)
sess.run(tf.initialize_local_variables())

for i in range(number_of_batches):
  print('Mean after batch %d: %f' % (i, update_op.eval())
print('Final Mean: %f' % mean_value.eval())
```

This paradigm won't fit into keras currently.

**Comment by timpx** [comment]
@NickYi1990 by default the batch size is 32, since the roc auc must use all the validation data to be correct, you need to give a batch size equal to the size of you validation set. In your case:
````python
model.fit(X_train.values, y_train.values, validation_split=0.2, epochs=1, verbose=1, batch_size=X_train.values.shape[0]/5.)
````

**Comment by jamartinh** [comment]
```
class roc_callback(keras.callbacks.Callback):
    def __init__(self,training_data,validation_data):
        
        self.x = training_data[0]
        self.y = training_data[1]
        self.x_val = validation_data[0]
        self.y_val = validation_data[1]
        
    
    def on_train_begin(self, logs={}):
        return
 
    def on_train_end(self, logs={}):
        return
 
    def on_epoch_begin(self, epoch, logs={}):
        return
 
    def on_epoch_end(self, epoch, logs={}):        
        y_pred = self.model.predict(self.x)
        roc = roc_auc_score(self.y, y_pred)      
        
        y_pred_val = self.model.predict(self.x_val)
        roc_val = roc_auc_score(self.y_val, y_pred_val)      
        
        print('\rroc-auc: %s - roc-auc_val: %s' % (str(round(roc,4)),str(round(roc_val,4))),end=100*' '+'\n')
        return
 
    def on_batch_begin(self, batch, logs={}):
        return
 
    def on_batch_end(self, batch, logs={}):
        return   


callbacks=[roc_callback(training_data=training_data,validation_data=validation_data)] 
```

**Comment by rspadim** [comment]
https://www.kaggle.com/rspadim/gini-keras-callback-earlystopping-validation

**Comment by alraisif** [comment]
@isaacgerg NameError: name 'tf' is not defined

**Comment by JoshuaC3** [comment]
@jamartinh - how to get this to work then `validation_data` is a `flow_from_directory` generator?

**Comment by jmrozanec** [comment]
@isaacgerg @fchollet Hi! Thanks for the implementation! 
We use it, though we are not sure which is the purpose of the default value for the threshold:
 `def binary_PFA(y_true, y_pred, threshold=K.variable(value=0.5))`
In the AUC method it invokes this one and binaryPTA with values from 0 to 1 in 0.001 increments as threshold, not using the 0.5 threshold value at all. Is this correct or are we missing something?
Thanks in advance!

**Comment by SwathiPI** [comment]
KeyError                                  Traceback (most recent call last)
<ipython-input-19-90eb47b712ba> in <module>()
      1 ## Get the RMSE on the validation set
      2 perf = prediction_gbm.model_performance(valid)
----> 3 print (perf.auc())

~/anaconda3/lib/python3.6/site-packages/h2o/model/metrics_base.py in auc(self)
    156     def auc(self):
    157         """The AUC for this set of metrics."""
--> 158         return self._metric_json['AUC']
    159 
    160 

KeyError: 'AUC'

**Comment by SwathiPI** [comment]
can anyone help me

**Comment by SwathiPI** [comment]
I'll try it. Thanks a lot for replying

**Comment by SwathiPI** [comment]
H2OTypeError                              Traceback (most recent call
last)<ipython-input-24-47190508f56c> in <module>()      8 for key in
params.keys():      9     if key in dir(prediction_gbm_best) and
getattr(prediction_gbm_best,key) != params[key]['actual']:---> 10
   setattr(prediction_gbm_best,key,params[key]['actual'])
~/anaconda3/lib/python3.6/site-packages/h2o/estimators/gbm.py in
training_frame(self, training_frame)     62     @training_frame.setter
    63     def training_frame(self, training_frame):---> 64
assert_is_type(training_frame, None, H2OFrame)     65
self._parms["training_frame"] = training_frame     66
~/anaconda3/lib/python3.6/site-packages/h2o/utils/typechecks.py in
assert_is_type(var, *types, **kwargs)    455     vtn =
_get_type_name(type(var))    456     raise
H2OTypeError(var_name=vname, var_value=var, var_type_name=vtn,
exp_type_name=etn, message=message,--> 457
skip_frames=skip_frames)    458     459
H2OTypeError: Argument `training_frame` should be an ?H2OFrame, got
H2OResponse {'__meta': {'schema_version': 3, 'schema_name':
'FrameKeyV3', 'schema_type': 'Key<Frame>'}, 'name': 'train.hex',
'type': 'Key<Frame>', 'URL': '/3/Frames/train.hex'}

could you help me

**Comment by SwathiPI** [comment]
prediction_gbm =
h2o.get_model(sorted_grid.sorted_metric_table()['model_ids'][0])
#get the parameters from the Random grid search model and modify them
slightly
params = prediction_gbm.params
new_params = {"nfolds":5, "model_id":None}
for key in new_params.keys():
    params[key]['actual'] = new_params[key]
prediction_gbm_best = H2OGradientBoostingEstimator()
for key in params.keys():
    if key in dir(prediction_gbm_best) and getattr(prediction_gbm_best,key)
!= params[key]['actual']:
        setattr(prediction_gbm_best,key,params[key]['actual'])

## error occured for this code ##

**Comment by nkjsy** [comment]
Technically AUC ROC can be calculated on mini-batch as long as we have the y_true and y_pred. The only concern should be that too small batch size will reduce the accuracy of this metric and make it less meaningful. Am I right? @fchollet

**Comment by isaacgerg** [comment]
I would like to chime in. What you say is correct.  My issue is that the
ROC is often used on imbalanced datasets (think on the order of 100:1) and
batch sizes are generally around 64 items.  So, you may not get an instance
of the object class in your batch and the then the ROC would be invalid.

**Comment by solensolen** [comment]
I have tried to use auc in metrics and callbacks, with a batch_size=2048. Thanks to the code above.
@jamartinh @isaacgerg 
Basically, both ways may work. But use auc in metrics may slow down the cal a lot(it cals every batch), 
and the auc value may change very quickly cause the batch_size is too small for the hole dataset.

So as @fchollet said, use auc in callback every epoch end maybe a batter idea.

**Comment by was84san** [comment]
What about accumulate the y_pred for each batch then concatenate them at the end of one epoch and calculate the AUC for the whole validation dataset ?

**Comment by was84san** [comment]
What about accumulating the y_pred for each batch then concatenate them at the end of one epoch and calculate the AUC for the whole validation dataset ?

**Comment by was84san** [comment]
Can I used tf.metric.auc in custom accuracy metric? what it is the difference between it and tf.contrib.metrics.streaming_auc? I would appreciate if some one can tell me

**Comment by ShiangYong** [comment]
@JoshuaC3 The way to make @jamartinh 's  solution to work with fit_generator by making these changes:

1. In `__init__`, you should pass in the train and val generators instead. Something like this

2. In `on_epoch_end`, replace `model.predict` with `model.predict_generator`.

Here's a sketch where only the AUROC of the val dataset is calculated at the end of every epoch:
`
class roc_callback(keras.callbacks.Callback):
    def __init__(self, val_gen):
        self.val_gen = val_gen
        self.val_reports = []
 
    def on_epoch_end(self, epoch, logs={}):        
        y_pred = self.model.predict_generator(val_gen, .....)
        y_true = self.val_gen.y
        val_roc = roc_auc_score(y_true , y_pred)
        self.val_reports.append(val_roc)
`

**Comment by momih** [comment]
@solensolen are you sure about the metrics method working? I'm using both the methods and the validation AUROC I get from the metrics method increases with each epoch. Towards the end of training, the metrics AUROC is way higher than the callback one (fyi my dataset is pretty imbalanced)

I thought it's like what @isaacgerg said that it is calculated batch-by-batch and averaged which is why it is so high as some batches may not have the underpopulated class. So I decided to make my validation data the same size as my batch size so that it is calculated in one go and I am still experiencing the aforementioned phenomenon. Here is a sample from the output (batch size is 1000).

    def auc_roc(y_true, y_pred):
    	value, update_op = tf.metrics.auc(y_true, y_pred)
    	K.get_session().run(tf.local_variables_initializer())
    	return update_op

    Train on 44088 samples, validate on 1000 samples
    Epoch 1/15
    44088/44088 [==============================] - 3s 78us/step - loss: 0.6872 - acc: 0.5674 - auc_roc: 0.5267 - val_loss: 0.6672 - val_acc: 0.6770 - val_auc_roc: 0.5473

    AUC (from callback) - 0.5823
    .
    .
    .
    .
    
    Epoch 5/15
    44088/44088 [==============================] - 2s 55us/step - loss: 0.3236 - acc: 0.8919 - auc_roc: 0.9386 - val_loss: 0.5749 - val_acc: 0.7430 - val_auc_roc: 0.9279
    
    AUC (from callback) - 0.5860
    
The `val_auc_roc` is calculated by passing the auc_roc function to the `model.compile` method and the `AUC (from callback)` is the same as the `roc_callback` class defined in an above post with only validation data AUC calculated. In epoch 1, the values are similar but by further epochs it's **way** higher. Can anyone explain why is the `val_auc_roc` so different from the `AUC (from callback)`?

**Comment by ldong87** [comment]
I can confirm @momih 's point. 
I use the following function
`
def auc_roc(y_true, y_pred):        
    # any tensorflow metric
    value, update_op = tf.metrics.auc(y_true, y_pred, num_thresholds=200, curve='ROC', summation_method='careful_interpolation' )

    # find all variables created for this metric
    metric_vars = [i for i in tf.local_variables() if 'auc_roc' in i.name.split('/')[1]]

    # Add metric variables to GLOBAL_VARIABLES collection.
    # They will be initialized for new session.
    for v in metric_vars:
        tf.add_to_collection(tf.GraphKeys.GLOBAL_VARIABLES, v)

    # force to update metric values
    with tf.control_dependencies([update_op]):
        value = tf.identity(value)
        return value
`
and call it in model.compile like this
`
model.compile(loss='binary_crossentropy', optimizer=optim, metrics=[auc_pr, auc_roc])
`
I provided the validation set. I found that the val_auc_roc score from the end of epoch is quite different comparing to results from sklearn.

**Comment by danFromTelAviv** [comment]
@NickYi1990 
I had the same issue - I figured out that some of the thresholds had 0 true positives / false negatives. This led to a division by 0 -> return FP / N
A decent solution is: return FP / N -> return FP / (N + 1)
```
import tensorflow as tf
import keras.backend as K
import numpy as np


# -----------------------------------------------------------------------------------------------------------------------------------------------------
# AUC for a binary classifier
def auc(y_true, y_pred):
    ptas = tf.stack([binary_PTA(y_true, y_pred, k) for k in np.linspace(0, 1, 1000)], axis=0)
    pfas = tf.stack([binary_PFA(y_true, y_pred, k) for k in np.linspace(0, 1, 1000)], axis=0)
    pfas = tf.concat([tf.ones((1,)), pfas], axis=0)
    binSizes = -(pfas[1:] - pfas[:-1])
    s = ptas * binSizes
    return K.sum(s, axis=0)


# -----------------------------------------------------------------------------------------------------------------------------------------------------
# PFA, prob false alert for binary classifier
def binary_PFA(y_true, y_pred, threshold=K.variable(value=0.5)):
    y_pred = K.cast(y_pred >= threshold, 'float32')
    # N = total number of negative labels
    N = K.sum(1 - y_true)
    # FP = total number of false alerts, alerts from the negative class labels
    FP = K.sum(y_pred - y_pred * y_true)
    return FP / (N + 1)


# -----------------------------------------------------------------------------------------------------------------------------------------------------
# P_TA prob true alerts for binary classifier
def binary_PTA(y_true, y_pred, threshold=K.variable(value=0.5)):
    y_pred = K.cast(y_pred >= threshold, 'float32')
    # P = total number of positive labels
    P = K.sum(y_true)
    # TP = total number of correct alerts, alerts from the positive class labels
    TP = K.sum(y_pred * y_true)
    return TP / (P + 1)
```

**Comment by ChongWu-Biostat** [comment]
> ```
> class roc_callback(keras.callbacks.Callback):
>     def __init__(self,training_data,validation_data):
>         
>         self.x = training_data[0]
>         self.y = training_data[1]
>         self.x_val = validation_data[0]
>         self.y_val = validation_data[1]
>         
>     
>     def on_train_begin(self, logs={}):
>         return
>  
>     def on_train_end(self, logs={}):
>         return
>  
>     def on_epoch_begin(self, epoch, logs={}):
>         return
>  
>     def on_epoch_end(self, epoch, logs={}):        
>         y_pred = self.model.predict(self.x)
>         roc = roc_auc_score(self.y, y_pred)      
>         
>         y_pred_val = self.model.predict(self.x_val)
>         roc_val = roc_auc_score(self.y_val, y_pred_val)      
>         
>         print('\rroc-auc: %s - roc-auc_val: %s' % (str(round(roc,4)),str(round(roc_val,4))),end=100*' '+'\n')
>         return
>  
>     def on_batch_begin(self, batch, logs={}):
>         return
>  
>     def on_batch_end(self, batch, logs={}):
>         return   
> 
> 
> callbacks=[roc_callback(training_data=training_data,validation_data=validation_data)] 
> ```

Thank you for this elegant and clean solution. It works perfectly for me. Much better than the solutions I found elsewhere.
