### ISSUE TITLE
Reinforcement learning algorithms

### ISSUE THREAD

**Issue by ericvrp** [fchollet/keras#3234]
_This is a feature request._

I would like to experiment with RL. It looks like adding RL algorithms like Q-learning and A3C to Keras seems like a good idea.

**Comment by braingineer** [comment]
There's a side project by @farizrahman4u  for this:

https://github.com/farizrahman4u/qlearning4k

**Comment by ericvrp** [comment]
Oke, I'll better close this issue then. There are plenty of open issues already.
