### ISSUE TITLE
Orthogonal initialization accepts non-square shapes

### ISSUE THREAD

**Issue by phreeza** [fchollet/keras#324]
Ran into this while writing tests. Documentation says input should be square, but code accepts all shapes. One of the two should change, I do not know which.

**Comment by fchollet** [comment]
This is deliberate, we generalize this initialization to any shape because only supporting square shapes would be bad practice. The doc needs to be updated apparently.

**Comment by phreeza** [comment]
Should we make sure that fan in > fan out? I think otherwise it would be a bit pointless, no? since a non-square matrix can only be row- or column-orthogonal, not fully orthogonal.

**Comment by fchollet** [comment]
Sure, let's do that.
