### ISSUE TITLE
Model Summary shape not correct.

### ISSUE THREAD

**Issue by shyamupa** [fchollet/keras#3241]
I have a vector `alpha` of size `(None,20)` and `Y` of size `(None,300,20)`. I can compute the dot product to get a a vector of size `(None,300)`. However, the model summary shape does not agree with the expected shape. Code below should reproduce the error.

``` python
from keras.layers import Input, merge
from keras.models import Model
import numpy as np
import keras.backend as K


def get_R(X):
    Y, alpha = X[0], X[1]
    ans = K.T.batched_dot(Y, alpha)
    return ans


alpha_val = np.arange(200).reshape((10, 20))
Y_val = np.arange(60000).reshape((10, 300, 20))

Y = Input(shape=(300, 20))
alpha = Input(shape=(20,))

r = merge([Y, alpha], output_shape=(300, 1), name="r_", mode=get_R)

model_me = Model(input=[Y, alpha], output=r)

model_me.summary()

print(model_me.predict([Y_val, alpha_val]).shape)

```

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by shyamupa** [comment]
Nevermind, upgrading keras was the issue.

**Comment by alyato** [comment]
@shaunharker I check the Merge source code and don't know how to use it in your way.

> r = merge([Y, alpha], output_shape=(300, 1), name="r_", mode=get_R)
 
Does the `output_shape=(300, 1)` be set randomly?
 [ Y ,alpha]  are passing into the function get_R   
the shape of Y is (none ,300,20), the shape of alpha is (none,20)
> def get_R(X):
    Y, alpha = X[0], X[1]
    ans = K.T.batched_dot(Y, alpha)
    return ans

I don't know the shape of ans. Does the shape of ans be equal to the  `output_shape=(300, 1)`

**Comment by shaunharker** [comment]
@alyato Sorry, but it is unclear to me what relationship your question has to PR #2938.  If you are looking for assistance using Keras the forum is [Keras Google Group](https://groups.google.com/forum/#!forum/keras-users). For instructions on how to submit issues please see <https://github.com/fchollet/keras/blob/master/CONTRIBUTING.md>.

**Comment by alyato** [comment]
@shaunharker I'm so sorry. I should ask shyamupa. Thanks.
