### ISSUE TITLE
How to speed up the test?

### ISSUE THREAD

**Issue by cdj0311** [fchollet/keras#3246]
When I test a classification task, how to speed up inputting result. Currently, the recognition speed is so slowly.

**Comment by MoyanZitto** [comment]
Maybe you should make it more clear. Basiclly the computation speed depends on your computer.

**Comment by marcj** [comment]
If you have a simple python script that loads your model, compiles it, loads its weight and the runs the prediction, most CPU time (if you haven not an incredible big model) is spent in the 3 steps (load model, compile, load weights). To improve that you could build a little application in python, that only does those 3 things in the bootstrap and can accept prediction inputs through an API (maybe http). Of course this blocks constantly your RAM, but it's the easiest way to get very fast response times if you only want to predict some input.
