### ISSUE TITLE
Theano: Force Tensor onto CPU

### ISSUE THREAD

**Issue by subu-cliqz** [fchollet/keras#3250]
Hi,
The theano documentation suggests using theano.tensor._shared() to force a tensor onto CPU. Is there a way to force a keras embedding layer on the CPU using this?

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by nouiz** [comment]
Now in Theano, you can use theano.shared(value, target='cpu').

I forgot if this is in the dev version of Theano 0.8.2.

**Comment by subu-cliqz** [comment]
@nouiz Thanks! I wrote a custom init function for the embeddings as below:

```python
def custom_init(value, name=None, scale=0.05):
    embedding_weights = np.zeros(value, dtype=np.float32)
    return theano.shared(value=embedding_weights, name=name, target='cpu')
```

```python
    model.add(Embedding(vocab_size, embedding_dim, input_length=sequence_length,
                            init=custom_init)
```
Unfortunately, I still get the same error about insufficient memory on gpu.

**Comment by nouiz** [comment]
What is this error? I don't recall such an error in Theano. Can you give
the full error?

**Comment by subu-cliqz** [comment]
Seems more like a keras issue. I also updated https://github.com/fchollet/keras/blob/master/keras/optimizers.py#L327 to mark the embedding updates with target='cpu'. 

I still get the following error: 
```
Error allocating 1600000000 bytes of device memory (out of memory). Driver report 770531328 bytes free and 4294770688 bytes total
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    model.fit_generator(data_helpers.data_generator(vocab=word_dict, num_epochs=5), samples_per_epoch=45609473, nb_epoch = 5, callbacks = [chkpoint], max_q_size=10, verbose=1)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/engine/training.py", line 1445, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/engine/training.py", line 1223, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/backend/theano_backend.py", line 573, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
MemoryError: Error allocating 1600000000 bytes of device memory (out of memory).
Apply node that caused the error: GpuElemwise{mul,no_inplace}(GpuDimShuffle{x,x}.0, GpuFromHost.0)
Toposort index: 116
Inputs types: [CudaNdarrayType(float32, (True, True)), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(1, 1), (4000000, 100)]
Inputs strides: [(0, 0), (100, 1)]
Inputs values: [CudaNdarray([[ 0.89999998]]), 'not shown']
Outputs clients: [[GpuElemwise{add,no_inplace}(GpuElemwise{mul,no_inplace}.0, GpuElemwise{mul,no_inplace}.0)]]

```

**Comment by nouiz** [comment]
This error mean you are still missing memory on the GPU.

The update to the embeded matrix should be done by inc_subtensor or
set_subtensor to have done implace. This save memory. I don't know if keras
does this or not.

I made an issue in Theano to add an optimization that would do that
automatically, but I don't know when we will have time for this:

https://github.com/Theano/Theano/issues/4774
