### ISSUE TITLE
Model build time increasing on every run

### ISSUE THREAD

**Issue by michalgregor** [fchollet/keras#3265]
I am using keras with the tensorflow backend. I am running an interactive shell. What I notice is that when I build a graph using the functional API, the script takes longer to execute on every subsequent run. The following code illustrates the issue:

```
import time
from keras.layers import Dense, Input
from keras.models import Model

start = time.time()

input_data = Input(shape=(100,))
x = Dense(100)(input_data)

for i in range(50):
    x = Dense(100)(x)

end = time.time()
print("{}s".format(end - start))
```

Note that I am not even creating a model or compiling it at any point. The run times increase in the following fashion:
1.6856169700622559s
3.498518943786621s
5.327540397644043s
7.185122013092041s
9.20834469795227s

Any ideas? Is there perhaps some caching going on in the background that could be causing this?
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by codekansas** [comment]
This seems like a memory allocation problem. Even if you don't compile a model, every time you call a layer (e.g. `Dense(100)(x)`) you're allocating memory for the layer's weights by calling the [build](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L587) method.
