### ISSUE TITLE
froze layer, but weights still changed

### ISSUE THREAD

**Issue by benwu232** [fchollet/keras#3268]
I used trainable to freeze some layers of my model, added some layers and continued training. During training, I found the weights still changed. I'm not sure what happened.

Here are some weights in different epochs. I cut them in debug mode.

---

array([[[[ 0.16177908, -0.09839147, -0.0857864 ]],

```
    [[ 0.10176676,  0.16003887, -0.13533698]],

    [[-0.06665382,  0.05389806,  0.01333128]],
```

---

array([[[[ 0.16171053, -0.09800326, -0.08534878]],

```
    [[ 0.10163011,  0.15987687, -0.13544077]],

    [[-0.06666315,  0.05425047,  0.01373971]],
```

---

array([[[[ 0.16169044, -0.09756043, -0.08492716]],

```
    [[ 0.10153792,  0.15963693, -0.13562557]],

    [[-0.06665007,  0.05445961,  0.01388009]],
```

---

array([[[[ 0.16182417, -0.0971467 , -0.08453723]],

```
    [[ 0.10148849,  0.15936331, -0.13582289]],

    [[-0.06648023,  0.05473858,  0.01407069]],
```

**Comment by kgrm** [comment]
>Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by benwu232** [comment]
Hi,

Here is the gist:
https://gist.github.com/benwu232/b844646adb0b077ec2a72a08f808283e

I modified the mnist_cnn in the examples to show this.

I found if I set 'trainable' to false in callback, the layer will not be frozen. That's wield.  What is the difference between inside and outside of callback?

@kgrm

**Comment by tboquet** [comment]
I think you have to recompile the model if you change this parameter because it will affect the theano functions involved in the training (in fact the computation graph). In a callback you can change the value of parameters or hyperparameters by setting the value manually but I'm not sure if you can easily recompile the model. You can still try it, but you will maybe have to restore the state of your optimizer too.

**Comment by benwu232** [comment]
@tboquet 
I just added compilation to on_epoch_end and ran it, got same result.
I'm using tensorflow 0.9 as backend.
What do you mean to restore the state of the optimizer?
Thanks!

**Comment by jfsantos** [comment]
Setting a layer's `trainable` flag has to be done before compiling the model. It is taken into account when generating Theano/Tensorflow functions for that layer. Changing it during runtime (i.e., after compiling the model) has no effect. This is the reason changing it inside a callback does not work.

**Comment by benwu232** [comment]
@jfsantos  Thanks!
Do you mean it can only set once?
I tried to change and recompile it, no effect.
If I want to freeze and unfreeze the parameters from time to time, how to implement it?

**Comment by Aaron-Edwards-93** [comment]
@benwu232 did you come to a solution for this?

**Comment by amessica** [comment]
@benwu232 & @Aaron-Edwards-93  hey guys, any smart solution for modifying  'trainable' on runtime?
