### ISSUE TITLE
Implementing "Deep Structured Semantic models" (DSSM) in Keras

### ISSUE THREAD

**Issue by krishnateja614** [fchollet/keras#3271]
How do we implement a model like DSSM as given in http://emnlp2014.org/material/presentation-EMNLP2014002.pdf in Keras. This model may be helpful for many tasks.
![dssm](https://cloud.githubusercontent.com/assets/7423507/16999679/74a1558c-4e7c-11e6-8b26-997bce6bb972.png)

**Comment by Dref360** [comment]
Hi,
This is basically a siamese network. There is one in the example folder. (change conv2d layer for conv1d or Dense) For questions like this, stackoverflow is better place if you want your question answered.

Thank you

**Comment by krishnateja614** [comment]
Sorry I really didn't know this is called a siamese network. I just found so many mentions of it in keras issues and hopefully I could learn from these. In future, I'll remember to post in SO. Thanks.

**Comment by krishnateja614** [comment]
Hi @Dref360 , I have been reading about the Siamese network but I don't think that's quite the same as the "DSSM" model I have above. Let's assume the problem of "Query-doc" relevancy and in that X can be one query and we can have multiple Ys (each of them representation one doc). We should get vector space representation of both the queries and docs such that relevant query-docs are closer than the non relevant ones. Also, we would have two networks , one for the queries and one for all the docs. The network for docs would be shared by all the docs. So, at each point we will have two networks, while one network learns the query representation, one learns the doc representation. You will have a better idea if you could go through the slides which are very interesting btw.

**Comment by budhiraja** [comment]
Any one who was able to do it?

**Comment by aneesh-joshi** [comment]
A tensorflow implementation can be found [here](http://liaha.github.io/models/2016/06/21/dssm-on-tensorflow.html)

@budhiraja @krishnateja614

**Comment by eggie5** [comment]
DSSM isn't siamese b/c the two towers don't share parameters
