### ISSUE TITLE
attention based sequence to sequence model application with keras?

### ISSUE THREAD

**Issue by ShuoW** [fchollet/keras#3280]
Are there some implementation examples of the attention based sequence to sequence using Keras? The model like that [http://arxiv.org/pdf/1409.0473.pdf](url).
Thanks.

**Comment by ymcui** [comment]
as far as i know, the current version of Keras does not do a good job in seq2seq learning.
maybe you should try: https://github.com/farizrahman4u/seq2seq
which is built on Keras.

**Comment by mynameisvinn** [comment]
agree with @ymcui ....  a good implementation: https://github.com/gelsto/SpeakEasy-AI

it's with tensorflow however.
