### ISSUE TITLE
BLAS error

### ISSUE THREAD

**Issue by samuela** [fchollet/keras#329]
While training a keras model, I'm getting a curious BLAS error:

```
ldb must be >= MAX(K,1): ldb=10 K=250BLAS error: Parameter number 11 passed to cblas_dgemm had an invalid value
```

I wish I could give more information but that's all that is printed and then python quits. The relevant code is just

```python
model = Sequential()
model.add(Dense(input_dim, 500, init='uniform', activation='tanh'))
model.add(Dropout(0.5))
model.add(Dense(500, 500, init='uniform', activation='tanh'))
model.add(Dropout(0.5))
model.add(Dense(500, 2, init='uniform', activation='softmax'))

sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='binary_crossentropy', optimizer=sgd)

fit_history = model.fit(Xtrain, Ytrain, nb_epoch=20, batch_size=256, show_accuracy=True)
```

**Comment by samuela** [comment]
Ah, it only occurs immediately before the final epoch (or after the penultimate epoch)!

**Comment by samuela** [comment]
It could also be due to the fact that my `Xtrain` and `Xtest` matrices have specially constructed strides with `numpy.lib.stride_tricks.as_strided`.

**Comment by fchollet** [comment]
Most likely due to more training data.

**Comment by fchollet** [comment]
Closing as this is not a Keras-related issue.
