### ISSUE TITLE
error: set input and output layer 'train' to False

### ISSUE THREAD

**Issue by varoudis** [fchollet/keras#3297]
Im playing around with this helpful code but Im getting an error at the location below.

Original:
[https://github.com/julienr/ipynb_playground/blob/master/keras/convmnist/keras_conv_autoencoder_mnist.ipynb](https://github.com/julienr/ipynb_playground/blob/master/keras/convmnist/keras_conv_autoencoder_mnist.ipynb)

```
#encode = K.function([encoder.get_input(train=False)], [encoder.get_output(train=False)])
encode = K.function([encoder.layers[0].input], [encoder.layers[-1].output(train=False)])

trained_weights = [l.get_weights() for l in autoencoder.encoding_layers]
for i, l in enumerate(encoding_layers):
    l.set_weights(trained_weights[i])
```

The original line is commanded out, I tried a number of versions but I get an error.
What is nowadays the equivalent in the new API?

Thanks

**Comment by varoudis** [comment]
No easy out from this one?

**Comment by codekansas** [comment]
After you've got your model, you can set the `trainable` attribute on a layer to `False`

**Comment by varoudis** [comment]
Thanks a loT!
