### ISSUE TITLE
output_shape lambda layer

### ISSUE THREAD

**Issue by cdicle** [fchollet/keras#3299]
Hi,

I bet this problem has been addressed in another issue but I couldn't find it, so sorry for replicates.

I am trying to define a lambda layer which takes mean of the the input. I use two versions,

```
dim_data = 105
len_data = 21 
num_data = 7;
num_classes = 12;

X = np.empty((num_data,),dtype=object)

for i in range(0,num_data):
    X[i] = np.random.random((len_data,dim_data))

# version 1
def Kmean(x):
    return K.mean(x,axis=1)
def Kmean_output_shape(input_shape):
    return tuple(input_shape[0],1,input_shape[2])

x = input_data
x = Lambda(Kmean,output_shape=Ksum_output_shape)(x)
x = Dense(num_classes)(x)
x = Activation('softmax')(x)
pred = x

model = Model(input=input_data,output=pred)
model.summary()

# version 2
x = input_data
x = Lambda(lambda x: K.mean(x,axis=1))(x) 
x = Dense(num_classes)(x)
x = Activation('softmax')(x)
pred = x

model = Model(input=input_data,output=pred)
model.summary()
```

Both versions have problem. The first version returns the right output shape but dense layer gives an error. The second layer does not return the right dimensions, the input and the output have the same dimensions, which I believe should not be the case, because I take a mean along second axis.

I would appreciate any help, thanks.

**Comment by farizrahman4u** [comment]
Where is your input_data definition? K.mean reduces a dimension, not add one. If your input_data is 2D, then in version 1:
```python
def Kmean(x):
    return K.expand_dims(K.mean(x, axis=1), 1)
def Kmean_output_shape(input_shape):
    return tuple(input_shape[0],1)
```

**Comment by cdicle** [comment]
Oh sorry 

```
input_data = Input(shape=(len_data,dim_data))
```
I am trying to take mean along `len_data` dimension

Thanks @farizrahman4u

**Comment by cdicle** [comment]
Now the updated code is as follows

```
def Kmean(x):
    return K.expand_dims(K.mean(x, axis=1), 1)
def Kmean_output_shape(input_shape):
    return tuple((input_shape[0],1))   # note double paranthesis. For a reason now tuple gives an error otherwise

input_data = Input(shape=(len_data,dim_data))

x = input_data
x = Lambda(Kmean,output_shape=Kmean_output_shape)(x)
x = Dense(num_classes)(x)
pred = x

```

Now that code gives exception
```
Input 0 is incompatible with layer dense_8: expected ndim=2, found ndim=3
```

Sounds weird to me. Also I believe we should write output_shape function as follows
```
def Kmean_output_shape(input_shape):
    return tuple((input_shape[0],1,input_shape[2])) 
```
Both versions give the same error which is more weird for me.

**Comment by farizrahman4u** [comment]
Ok, so your input is 3D . So it should be:

```python
def Kmean(x):
    return K.mean(x, axis=1)
def Kmean_output_shape(input_shape):
    return i(nput_shape[0], input_hape[2])
```

**Comment by cdicle** [comment]
Oh, thanks @farizrahman4u. That does the job.

Just out of curiosity. Is there a one liner version of this operation as I am attempting in version 2.

**Comment by farizrahman4u** [comment]
```python
x = Lambda(lambda x: K.mean(x, axis=1), output_shape=lambda s: (s[0], s[2]))(x)
```
