### ISSUE TITLE
How to create my own layer?

### ISSUE THREAD

**Issue by by2101** [fchollet/keras#3304]
I would like to test another kind of LSTM using Keras. I add a class named 'FULL_LSTM' to recurrent.py, and then I used it in imdb_lstm.py. But when I use statement 'from keras.layers import FULL_LSTM', the log said "name 'FULL_LSTM' is not defined".

So what's wrong with that?

Thank you!

**Comment by farizrahman4u** [comment]
* Go to `__init__.py` file keras/layers and add your custom layer name there too
* Run `python setup.py install` after all the changes.

**Comment by farizrahman4u** [comment]
Close issue if everythings cool.
