### ISSUE TITLE
Cannot run 3D CNN from #1623

### ISSUE THREAD

**Issue by kglore** [fchollet/keras#3319]
Hi all,

I am trying to run the 3D CNN Example [here](https://github.com/fchollet/keras/pull/1623) with the convolution 3D example in examples/shapes_3d_cnn.py by MinhazPalasara. I've updated Keras already. When I was running it, here's the error that I'm getting:

```
Traceback (most recent call last):
  File "shapes_3d_cnn.py", line 75, in <module>
    model.add(Convolution3D(nb_filters[0], nb_depth=nb_conv[0], nb_row=nb_conv[0], nb_col=nb_conv[0], border_mode='full',input_shape=(1, patch_size, patch_size, patch_size), activation='relu'))
TypeError: __init__() takes at least 5 arguments (4 given)
```

I don't know what is the problem (my machine?) when other people in the thread seem to got it working! Any insights?

Thanks!

**Comment by kglore** [comment]
Hi all, I figured out the issue. There was a keyword argument mismatch between the example code and the internal 3D convolution function.

**Comment by nborkar45** [comment]
What did you do exactly?
I'm having the same issue

**Comment by adityag6994** [comment]
For this particular case, for older version of keras (mine : 2.0.5)
model.add(Convolution3D(input_shape=(1, patch_size, patch_size, patch_size),
				nb_filter = nb_filters[0],
				kernel_dim1=nb_conv[0], 
				kernel_dim2=nb_conv[0],
				kernel_dim3=nb_conv[0], 
				border_mode='valid',
				activation='relu'))
