### ISSUE TITLE
Error when checking model input

### ISSUE THREAD

**Issue by zhaopku** [fchollet/keras#3324]
I'm trying to build an LSTM model to do sentence classfication task. I use pre-trained embeddings to initialize the embedding layer. But when I finished building the model, it says that the model input is wrong. My code is as follows:

```
model = Sequential()
model.add(Embedding(total_words + 1, EMBEDDING_DIM, weights = [embeddings_matrix], input_length = MAX_SEQUENCE_LENGTH,
                            trainable = True, mask_zero = True))
model.add(LSTM(100, return_sequences = False))
model.add(Dense(1))
model.add(Activation('sigmoid'))

sgd = SGD(lr = 0.1, decay = 1e-6, momentum = 0.9, nesterov = True)
model.compile(loss = 'binary_crossentropy', optimizer = sgd, metrics = ['acc'])

model.fit(train_x, train_y, validation_data = (cv_x, cv_y), nb_epoch = 50, batch_size = 50)
score, acc = model.evaluate(test_x, test_y, batch_size = 100)

```

The `EMBEDDING_DIM` is 100, and the shape of `embeddings_matrix` is `(28260, 100)`.

And the error message is as follows:

```
Traceback (most recent call last):
  File "2lstm.py", line 162, in <module>
    model.fit(train_x, train_y, validation_data = (cv_x, cv_y), nb_epoch = 50, batch_size = 50)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 429, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1036, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 963, in _standardize_user_data
    exception_prefix='model input')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 108, in standardize_input_data
    str(array.shape))
Exception: Error when checking model input: expected embedding_input_1 to have shape (None, 100) but got array with shape (0, 1)

```

Thanks!

**Comment by dolaameng** [comment]
For embedding layer, your train_x and cv_x shoud both be of shape (n_seqs, n_words_per_seq), and within each sequence, the hash index should be from 1 to vocab_size, with 0 as paddings. Can you check it?

**Comment by zhaopku** [comment]
@dolaameng Thanks, problem solved! But as I train my model, the train_loss decreased while the val_loss increases. Do you know why?

**Comment by dolaameng** [comment]
Hi @zhaopku, there could be many possibilities, but the first thing you may want to check is whether your model is over fitting.

**Comment by zhaopku** [comment]
Thank you, @dolaameng , but actually, the val_loss increases even if the train_acc is reletively low. See #3328
