### ISSUE TITLE
How to customize LSTM layer?

### ISSUE THREAD

**Issue by zhaopku** [fchollet/keras#3329]
I'm trying to implement this paper: [Semantically Conditioned LSTM-based Natural Language Generation for Spoken Dialogue Systems](http://mi.eng.cam.ac.uk/~thw28/papers/EMNLP15.pdf), in which they add a gate to LSTM and change the way in which cell state is computed. 

So I want to change the internal structure of LSTM layer. Anyone knows how to do that?

**Comment by ymcui** [comment]
modify the `keras/layers/recurrent.py`.
https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L620
the step function is in `def step(self, x, states)`,
https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L784

**Comment by codekansas** [comment]
You can make a subclass of the LSTM layer. I had to do something similar [here](https://github.com/codekansas/keras-language-modeling/blob/master/attention_lstm.py)

**Comment by shaifugpt** [comment]
@zhaopku I am interested in a problem similar to yours. Did you resolve it and manage to change the LSTM cell
