### ISSUE TITLE
Multi-GPU support for Tensorflow Backend

### ISSUE THREAD

**Issue by tetmin** [fchollet/keras#3331]
I'm not quire sure if this is possible or not from reading through prior issues & some examples. Section III of this example: http://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html seems to suggest that multi-GPU support does work with Tensorflow, but in order for that to work do you have to drop into writing custom Tensorflow sess.run() code or can we use Keras model.fit or model.fit_generator in conjunction with this?

If we do drop into the Tensorflow sess.run() is it possible to combine this with Keras ImageDataGenerators for example?

**Comment by fchollet** [comment]
> seems to suggest that multi-GPU support does work with Tensorflow, but in
order for that to work do you have to drop into writing custom Tensorflow
sess.run() code or can we use Keras model.fit or model.fit_generator in
conjunction with this?

Yes, you can use ".fit" with device parallelism in TF.

> If we do drop into the Tensorflow sess.run() is it possible to combine
this with Keras ImageDataGenerators for example?

Yes, you can use ImageDataGenerator when using sess.run() (just use it to
generate batches of data which you can then use in feed_dict).

**Comment by pengpaiSH** [comment]
@fchollet I believe @tetmin intended to know if it is possible to do the data parallelism with multiple GPUs without writing customized TensorFlow codes. And I am also expecting to see we could do such parallelism with Keras perhaps only in one line of code, as as model.fit().

**Comment by pengpaiSH** [comment]
#3258

**Comment by barrykui** [comment]
@pengpaiSH Dear pai, Have you finally solved the data parallelism problem? Now, I have the same problem as you. Maybe, you can help me a lot. Thank you.

**Comment by pengpaiSH** [comment]
@barrykui Not really. I am still waiting the launch of ```fit_distribute``` which should be ongoing by @fchollet.  I have seen you in another related issue #2436 . Does it work?

**Comment by barrykui** [comment]
@pengpaiSH No, the code below can not work, with error "TypeError: DataType float64 for attr 'Index' not in list of allowed values: int32, int64".
'''
L =  sh[0] / n_gpus
'''

**Comment by pengpaiSH** [comment]
@barrykui It works for me with the latest version of TensorFlow and Keras.

**Comment by barrykui** [comment]
@pengpaiSH I tried on TensorFlow 0.11 and Keras 1.1.1, still got the same error

**Comment by pengpaiSH** [comment]
@barrykui That's weird. ```sh[0]``` and ```n_gpus``` should be both ```int``` and ```L```  is expected to be ```int``` as a result. If not, try manually convert these two variables into ```int```? i.e. ```L= int(sh[0]) / int(n_gpus)```

**Comment by gmrhub** [comment]
@barrykui  that would be because of python3, just use integer division as follows
`L = sh[0] // n_gpus`

 @pengpaiSH 
But I am getting different error with u-net.
If I use this
`model = make_parallel(model, 2)`

I cannot load existing weights because it complains as
`Exception: You are trying to load a weight file containing 19 layers into a model with 1 layers.`

If I comment the loading part, I get
`ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, ?)`

So, somehow the model architecture or shapes is not reproduced with that call.
Could you help me out..

**Comment by antonimmo** [comment]
@gmrhub You're right. Python 3 automatically changes to float when performing divisions, unlike Python 2 where dividing two ints results in another int.

I made it work using

`L = tf.div(sh[0], n_gpus)`
