### ISSUE TITLE
Merge over Sequential models

### ISSUE THREAD

**Issue by ishalyminov** [fchollet/keras#3361]
Hi all,

This is kind of an information request issue.
Is the following architecture possible with the Sequential model: LSTM with its output layer connected to several MLPs?

I tried to achieve this as follows:

`Sequential(
    LSTM,
    Merge([Sequential(MLP), ... Sequential(MLP)], mode='concat')
)`

but run into a problem that Merge layer expects Tensors, not Sequential models.

How do I get such architecture to work?

**Comment by Deneb91** [comment]
Shouldn't it be enough to merge the output layers of each Sequential?

**Comment by bernardohenz** [comment]
I strongly suggest you to design the net as a Graph:

```python
input1 = Input(shape=(1, 128, 128))
input2 = Input(shape=(1, 128, 128))

conv1 = Convolution2D(1, 3, 3, border_mode='same')(input1)
conv1 = Convolution2D(1, 3, 3, border_mode='same')(conv1)
conv1 = Convolution2D(1, 3, 3, border_mode='same')(conv1)

conv2 = Convolution2D(1, 3, 3, border_mode='same')(input2)
conv2 = Convolution2D(1, 3, 3, border_mode='same')(conv2)
conv2 = Convolution2D(1, 3, 3, border_mode='same')(conv2)

merged = merge([conv1,conv2],mode='sum') #or 'concat' or 'mul'
lstm_output = LSTM(128, dropout_W=0.2)(merged)

model = Model(input=[input1,input2],output=lstm_output)
```

I am used to work with images, thus I don't know how the LSTM input expects, but I hope you have understood the idea.

**Comment by ishalyminov** [comment]
Thanks all! In the end, I went with Functional API (i.e. defined the model as a graph).
