### ISSUE TITLE
bidirectional

### ISSUE THREAD

**Issue by Kyubyong** [fchollet/keras#3367]
I know there have been quite intensive discussions about applying bidirectional recurrent layer. So, I guess this code is a potential solution to the masking issue.
https://github.com/farizrahman4u/seq2seq/blob/master/seq2seq/layers/bidirectional.py
I tried the following:

model  = Sequential()
model.add(Embedding(30, 10, mask_zero=True, input_length=10))
model.add(Bidirectional(LSTM(10, return_sequences=True)))

But an error occurred. Its message is as follows:
'LSTM' object has no attribute 'batch_input_shape'

Any thoughts?

**Comment by farizrahman4u** [comment]
@meain Can you reproduce this issue? my laptop is broken.

**Comment by Kyubyong** [comment]
I'm also wondering it this line is correct: https://github.com/farizrahman4u/seq2seq/blob/master/seq2seq/layers/bidirectional.py#L88
I guess the reversed result should be 0,0,0,10,9,7,4, not 10,10,10,10,9,7,4.

**Comment by farizrahman4u** [comment]
It will get masked.

**Comment by Kyubyong** [comment]
I don't want to bother you, but can you elaborate on that? I don't see any point where it will get masked. It was already masked in line 87, and the remaining next step is simply concatenating/summing/averaging/multiplying Y and Y_rev. So I guess the final hidden states would be

[[0    0    0 1 3 6 10]
 [10 10 10 10 9 7 4]]

, where the expected result of concatenating is
[[0 0 0 1 3 6 10]
 [0 0 0 10 9 7 4]]

If I miss something, please let me know.

**Comment by farizrahman4u** [comment]
> If I miss something, please let me know.

You are missing ** THE MASK**

**Comment by farizrahman4u** [comment]
> If I miss something, please let me know.

You are missing : 
![4716707-the mask](https://cloud.githubusercontent.com/assets/11006006/17457334/a887ee30-5c12-11e6-9df2-1d58caed9689.jpg)
