### ISSUE TITLE
Exception when serialising model using advanced activations

### ISSUE THREAD

**Issue by NMRobert** [fchollet/keras#3380]
Hi,

if I attempt to serialise a model using the .to_json() call, and this model uses any of the advanced activations (ELU, prelu, etc), this error occurs:
`AttributeError: 'ELU' object has no attribute '__name__'`

I have double checked that I am using the most up-to-date version of Keras off git. Here is a toy example which can be used to reproduce the issue:

```python
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers.core import Dense
import numpy as np

X_train = np.array([1,1,1,1,1]).reshape(1,5)
y_train =  np.array([0,0,0,0,0]).reshape(1,5)

model = Sequential()
model.add(Dense(5, activation=keras.layers.advanced_activations.ELU(alpha=1), input_shape=(5,)))
model.compile(loss='mse', optimizer='SGD')
model.fit(X_train, y_train, batch_size=1, shuffle=False, nb_epoch=10)

json_string = model.to_json()
open('model.json', 'w').write(json_string)
model.save_weights('model.h5', overwrite=True)

**Comment by fchollet** [comment]
Advanced activations are layers, not functions. You use them like regular layers, *not* as the `activation` argument of another layer (which can only take a function).

**Comment by NMRobert** [comment]
Ah, I see now. I should have read the documentation more closely; thank you.
