### ISSUE TITLE
Embedding layer weight is still in model.trainable_weights even if trainable=False

### ISSUE THREAD

**Issue by chentingpc** [fchollet/keras#3387]
Haven't test it with other layers like (Dense), but guess it exists for all layers that have trainable weights.

**Comment by fchollet** [comment]
And that's how it should be. To filter out weights from layers that are set to non-trainable, use:

```
from keras.engine.training import collect_trainable_weights

weights = collect_trainable_weights(layer)   # or (model)
```

**Comment by chentingpc** [comment]
It is a bit confusing to me that with **no trainable weights** in the model (or layer), model.**trainable_weights** is non empty while model.**non_trainable_weights** is empty. Then what's the use of model.non_trainable_weights? Is there any particular reason for that?

**Comment by fchollet** [comment]
The part where you are confused is that these two lists of weights are independent from whether the layer is trainable or not. They're just categories. Like "birds" are "flyings animals", but that doesn't mean they should be flying 100% of the time --just that they can fly.

"trainable_weights" are weights that will be trained, if and only if the layer is trainable. If the layer is non-trainable, that list doesn't go anywhere, it's still the same. It's just a category of weights.

I agree it might be confusing. So I might change it in the near future, if I determine it will not affect anything else and will not induce anti-backwards compatibility effects.

**Comment by chentingpc** [comment]
I see. Thanks for the articulation!
