### ISSUE TITLE
Deconvolution2D Inconsistent Output Shape

### ISSUE THREAD

**Issue by rmkemker** [fchollet/keras#3395]
I am having issues with the Deconvolution2D function.  First of all, I am using the theano backend with the bleeding edge Keras (pulled changes this morning) and Theano.  I am trying to replicate the FCN for Semantic Segmentation code in Keras.  The code below is my model.  There is also a graphical model at the very bottom of this post.  When I build the model, the Deconvolution2D get_output_shape returns (batch_size,21,512,512) even though I explicitly state that the output_shape should be (21,500,500).  My solution was to use a custom crop function (which is working well) to force it to be (21,500,500).  

```
inputData = Input(batch_shape=(batch_size,3,500,500))
pad1_1 = ZeroPadding2D((100,100))(inputData)
conv1_1 = Convolution2D(64,3,3,activation='relu')(pad1_1)
pad1_2 = ZeroPadding2D((1,1))(conv1_1)
conv1_2 = Convolution2D(64,3,3,activation='relu')(pad1_2)
pool1 = MaxPooling2D((2,2), strides=(2,2))(conv1_2)

pad2_1 = ZeroPadding2D((1,1))(pool1)
conv2_1 = Convolution2D(128,3,3,activation='relu')(pad2_1)
pad2_2 = ZeroPadding2D((1,1))(conv2_1)
conv2_2 = Convolution2D(128,3,3,activation='relu')(pad2_2)
pool2 = MaxPooling2D((2,2), strides=(2,2))(conv2_2)

pad3_1 = ZeroPadding2D((1,1))(pool2)
conv3_1 = Convolution2D(256,3,3,activation='relu')(pad3_1)
pad3_2 = ZeroPadding2D((1,1))(conv3_1)
conv3_2 = Convolution2D(256,3,3,activation='relu')(pad3_2)
pad3_3 = ZeroPadding2D((1,1))(conv3_2)
conv3_3 = Convolution2D(256,3,3,activation='relu')(pad3_3)
pool3 = MaxPooling2D((2,2), strides=(2,2))(conv3_3)  

pad4_1 = ZeroPadding2D((1,1))(pool3)
conv4_1 = Convolution2D(512,3,3,activation='relu')(pad4_1)
pad4_2 = ZeroPadding2D((1,1))(conv4_1)
conv4_2 = Convolution2D(512,3,3,activation='relu')(pad4_2)
pad4_3 = ZeroPadding2D((1,1))(conv4_2)
conv4_3 = Convolution2D(512,3,3,activation='relu')(pad4_3)
pool4 = MaxPooling2D((2,2), strides=(2,2))(conv4_3)    

pad5_1 = ZeroPadding2D((1,1))(pool4)
conv5_1 = Convolution2D(512,3,3,activation='relu')(pad5_1)
pad5_2 = ZeroPadding2D((1,1))(conv5_1)
conv5_2 = Convolution2D(512,3,3,activation='relu')(pad5_2)
pad5_3 = ZeroPadding2D((1,1))(conv5_2)
conv5_3 = Convolution2D(512,3,3,activation='relu')(pad5_3)
pool5 = MaxPooling2D((2,2), strides=(2,2))(conv5_3)

fc6 = Convolution2D(4096,7,7,activation='relu')(pool5)
drop6 = Dropout(0.5)(fc6)
fc7 = Convolution2D(4096,1,1,activation='relu')(drop6)
drop7 = Dropout(0.5)(fc7)
score_fr = Convolution2D(21,1,1)(drop7)

deconv  = Deconvolution2D(21,64,64,output_shape=(batch_size,21,500,500),subsample=(32,32),bias=False)(score_fr)
crop = Cropping2D(((6,6),(6,6)))(deconv)

flat = Reshape((21,500*500))(crop)
permute = Permute((2,1))(flat)    
soft = Activation('softmax')(permute)
model = Model(input=inputData, output=soft)    

sgd = SGD(lr=1e-4, decay=5e-4, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)
history = model.fit(trainData, trainGT, batch_size=batch_size, nb_epoch=10, verbose=1)
```

When I run model.fit()  I get an error (below) that says that the output of my crop layer is actually (batch_size,21,488,488) which means that the K.deconv2d is actually outputting the shape that I requested. 

```
File "<ipython-input-5-271f8399bbb6>", line 1, in <module>
runfile('/home/klab/Documents/Python Scripts/VOC2012/net.py', wdir='/home/klab/Documents/Python Scripts/VOC2012')

File "/home/klab/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
execfile(filename, namespace)

File "/home/klab/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 88, in execfile
exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

File "/home/klab/Documents/Python Scripts/VOC2012/net.py", line 193, in <module>
history = model.fit(trainData, trainGT, batch_size=batch_size, nb_epoch=10, verbose=1)

File "/home/klab/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/training.py", line 1107, in fit
callback_metrics=callback_metrics)

File "/home/klab/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/training.py", line 825, in _fit_loop
outs = f(ins_batch)

File "/home/klab/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/backend/theano_backend.py", line 644, in __call__
return self.function(*inputs)

File "/home/klab/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py", line 879, in __call__
storage_map=getattr(self.fn, 'storage_map', None))

File "/home/klab/anaconda3/lib/python3.5/site-packages/theano/gof/link.py", line 325, in raise_with_op
reraise(exc_type, exc_value, exc_trace)

File "/home/klab/anaconda3/lib/python3.5/site-packages/six.py", line 685, in reraise
raise value.with_traceback(tb)

File "/home/klab/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py", line 866, in __call__
self.fn() if output_subset is None else\

ValueError: GpuReshape: cannot reshape input of shape (1, 21, 488, 488) to shape (0, 21, 250000).
Apply node that caused the error: GpuReshape{3}(GpuSubtensor{::, ::, int64:int64:, int64:int64:}.0, TensorConstant{[    -1   ..21 250000]})
Toposort index: 522
Inputs types: [CudaNdarrayType(float32, 4D), TensorType(int64, vector)]
Inputs shapes: [(1, 21, 488, 488), (3,)]
Inputs strides: [(0, 250000, 500, 1), (8,)]
Inputs values: ['not shown', array([    -1,     21, 250000])]
Outputs clients: [[GpuDimShuffle{0,2,1}(GpuReshape{3}.0), GpuElemwise{Composite{Cast{float32}(EQ(i0, i1))},no_inplace}(GpuDimShuffle{0,x,1}.0, GpuReshape{3}.0)]]
```

I am going to checkout the deconv2d function in the theano backend file, but I thought I would bring it up to see if this is a problem for anyone else (or if I am just messing up something simple).  

![current_fcn_model](https://cloud.githubusercontent.com/assets/14336785/17402801/ee11c5da-5a22-11e6-9b76-5a35a815c1a0.png)

**Comment by rmkemker** [comment]
I tried writing my own version of Deconvolution2D to force the declared output shape to be the one that was pre-defined by me.  Everything else is the same.

    def get_output_shape_for(self, input_shape):
        sz = self.output_shape_
        if self.dim_ordering == 'th':
            return sz
        elif self.dim_ordering == 'tf':
            return (sz[0], sz[2], sz[3], sz[1])
        else:
            raise Exception('Invalid dim_ordering: ' + self.dim_ordering)

I am now getting this error:


    File "<ipython-input-1-271f8399bbb6>", line 1, in <module>
    runfile('/home/klab/Documents/Python Scripts/VOC2012/net.py', wdir='/home/klab/Documents/Python Scripts/VOC2012')

    File "/home/klab/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

    File "/home/klab/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

    File "/home/klab/Documents/Python Scripts/VOC2012/net.py", line 193, in <module>
    history = model.fit(trainData, trainGT, batch_size=batch_size, nb_epoch=10, verbose=1)

    File "/home/klab/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/training.py", line 1107, in fit
    callback_metrics=callback_metrics)

    File "/home/klab/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/training.py", line 825, in _fit_loop
    outs = f(ins_batch)

    File "/home/klab/anaconda3/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/backend/theano_backend.py", line 644, in __call__
    return self.function(*inputs)

    File "/home/klab/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py", line 879, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))

    File "/home/klab/anaconda3/lib/python3.5/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)

    File "/home/klab/anaconda3/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)

    File "/home/klab/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py", line 866, in __call__
    self.fn() if output_subset is None else\

    RuntimeError: GpuDnnConvGradI: error getting worksize: CUDNN_STATUS_BAD_PARAM
    Apply node that caused the error: GpuDnnConvGradI{algo='none', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})
    Toposort index: 564
    Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), <theano.gof.type.CDataType object at 0x7f015451e780>, Scalar(float32), Scalar(float32)]
    Inputs shapes: [(21, 4096, 1, 1), (1, 21, 14, 14), (1, 4096, 15, 15), 'No shapes', (), ()]
    Inputs strides: [(4096, 1, 0, 0), (0, 196, 14, 1), (0, 225, 15, 1), 'No strides', (), ()]
    Inputs values: ['not shown', 'not shown', 'not shown', <capsule object NULL at 0x7f014777ad50>, 1.0, 0.0]
    Inputs name: ('kernel', 'grad', 'output', 'descriptor', 'alpha', 'beta')

    Outputs clients: [[GpuElemwise{Composite{((i0 * Composite{Switch(i0, (i1 * i2 * i3), i3)}(i1, i2, i3, i4)) + (i0 * Composite{Switch(i0, (i1 * i2 * i3), i3)}(i1, i2, i3, i4) * sgn(i5)))}}[(0, 3)](CudaNdarrayConstant{[[[[ 0.5]]]]}, GpuFromHost.0, CudaNdarrayConstant{[[[[ 2.]]]]}, GpuElemwise{Composite{Cast{float32}(LT(i0, i1))},no_inplace}.0, GpuDnnConvGradI{algo='none', inplace=True}.0, GpuElemwise{add,no_inplace}.0)]]

**Comment by rmkemker** [comment]
I found a solution that seems to be working (training it right now).  I changed the Deconvolution2D output to be:

    deconv  = Deconvolution2D(21,64,64,output_shape=(batch_size,21,512,512),subsample=(32,32),bias=False)(score_fr)

I just crop the output of the Deconv2D layer, but that doesn't really explain the output mismatch.

**Comment by raghakot** [comment]
+1 I have the same issue.

**Comment by EderSantana** [comment]
@rmkemker I had the same issue with https://github.com/commaai/research/blob/master/models/autoencoder.py when using Theano backend. Tensorflow was ok, though.
I worked hard trying to figure out what was going on but I didn't get it :(

Would you please try your code with tensorflow backend? if it only happens to theano, please change the title to `[theano] Deconvolution2D Inconsistent Output Shape` and maybe a Theano dev will come to help us.

**Comment by rmkemker** [comment]
@EderSantana , I did try using the Tensorflow backend earlier, but I was having some unrelated memory issues with it.  I had to reformat my computer yesterday and have not yet rebuilt Tensorflow.  I will give it a shot once I am back up (hopefully very soon).  If that is the case, I will most definitely change the title name for you.

**Comment by rmkemker** [comment]
@EderSantana, I just rebuilt Tensorflow and my computer rebuild seems to have fixed the (unrelated) memory errors.  The code works just like Theano, but slower.  I still need to crop my data from 512x512 to 500x500 even though I select my output to be 500x500.

**Comment by EderSantana** [comment]
the original sizes don't 512 doesn't work? not even in TF? make your batch size = 1 just to test.

**Comment by chaithu536** [comment]
I faced the same issue with the output shape. I override the method 'get_output_shape_for()' of the class 'Deconvolution2D' to obtain the desired upsampling output shape. It worked.

class Deconv2D_custom(Deconvolution2D):
    
    def get_output_shape_for(self, input_shape):
        
        upsample_rate = self.subsample[0]
        
        if self.dim_ordering == 'th':
            rows = input_shape[2]*upsample_rate
            cols = input_shape[3]*upsample_rate
            
        elif self.dim_ordering == 'tf':
            rows = input_shape[1]*upsample_rate
            cols = input_shape[2]*upsample_rate
        else:
            raise Exception('Invalid dim_ordering: ' + self.dim_ordering)

        if self.dim_ordering == 'th':
            return (input_shape[0], self.nb_filter, rows, cols)
        elif self.dim_ordering == 'tf':
            return (input_shape[0], rows, cols, self.nb_filter)
        else:
            raise Exception('Invalid dim_ordering: ' + self.dim_ordering)

**Comment by EderSantana** [comment]
We recently changed the Deconv2D API after a PR by @tboquet now you have to explicitly pass the output_shape
Are you guys using the latest code now?

**Comment by chaithu536** [comment]
Yes, I am using the latest code and I have passed the desired output shape as an argument. But the resultant output shape is different than the given one.
