### ISSUE TITLE
unstable prediction performance

### ISSUE THREAD

**Issue by sun-peach** [fchollet/keras#3399]
Hi, everyone, I am using keras to build up a regular DNN with dropout and RELU. I find my prediction performance vary among experiments, e.g. with same setting and data, I ran couple of experiments, but the performance from each one is different and the difference sometimes is very large.

I understand this is because random number is used in initialization. I just want to know if there is anyway I can reduce variance in performances of different experiments.

Thank you.

**Comment by dolaameng** [comment]
You can fix the random seed by setting `np.random.seed(1337)` at the beginning of your experiment, if you believe randomness is the reason for the variations.
