### ISSUE TITLE
Reset/Reinitialize model weights/parameters

### ISSUE THREAD

**Issue by felipefariax** [fchollet/keras#341]
It would be great to Reset or Reinitialize a model, in order to reapply the weights initializations of each layers. This would be helpful when we need to run the same model architecture several times to retrieve some metrics like accuracy, precision, recall, etc. If we have to recompile the same model each run, we will lose much time.

In my example, I need to run a gridsearch on some hyperparams and evaluate the model 30 times. Each recompile was taking around 1s.

I came up with a solution like this:

def reset_model(model):
    for layer in model.layers:
        if hasattr(layer, 'init'):
            init = getattr(layer, 'init')
            new_weights = init(layer.get_weights()[0].shape).get_value()
            bias = shared_zeros(layer.get_weights()[1].shape).get_value()
            layer.set_weights([new_weights, bias])

What do you think?

**Comment by wxs** [comment]
That won't work for some models that have extra initializers, like `inner_init` in the recurrent models.

You can reset to *exactly* the same weights (rather than re-initialize randomly) by just doing

    Wsave = model.get_weights()

and then later doing

    model.set_weights(Wsave)

but adding a re-initialize function might be useful.

**Comment by philipperemy** [comment]
```
    W = m.get_weights()

    val_loss_list = []
    np.random.seed(1337)
    for ep in range(1, nb_epoch):
        m.fit(X_train,
              y_train,
              batch_size=batch_size,
              nb_epoch=1, verbose=0,
              validation_data=(X_test, y_test))

        val_loss_list.append(m.evaluate(X_test,
                                        y_test, verbose=0,
                                        batch_size=batch_size))

    best_epoch = np.array(val_loss_list).argmin()

    # reset model
    m.reset_states()
    m.set_weights(W)

    np.random.seed(1337)
    m.fit(X_train,
          y_train,
          batch_size=batch_size,
          nb_epoch=best_epoch+1, verbose=2,
          validation_data=(X_test, y_test))
```

**Comment by jkleint** [comment]
I briefly looked into adding weight reinitialization, and it would be a fairly big refactor; each layer does custom things in different places.

As a workaround, I save the initial weights but then randomly permute them for each fold.  Here's a simple method:

```
def shuffle_weights(model, weights=None):
    """Randomly permute the weights in `model`, or the given `weights`.

    This is a fast approximation of re-initializing the weights of a model.

    Assumes weights are distributed independently of the dimensions of the weight tensors
      (i.e., the weights have the same distribution along each dimension).

    :param Model model: Modify the weights of the given model.
    :param list(ndarray) weights: The model's weights will be replaced by a random permutation of these weights.
      If `None`, permute the model's current weights.
    """
    if weights is None:
        weights = model.get_weights()
    weights = [np.random.permutation(w.flat).reshape(w.shape) for w in weights]
    # Faster, but less random: only permutes along the first dimension
    # weights = [np.random.permutation(w) for w in weights]
    model.set_weights(weights)

```

So save the initial weights after model creation, then pass them to this function before (not after!) each call to `fit()`.  Depending on your model and goals, you could also try permuting the learned weights (i.e., not passing any weights to the method) as a kind of warm restart.

Here is the method and an example in a gist:
https://gist.github.com/jkleint/eb6dc49c861a1c21b612b568dd188668

**Comment by frenzykryger** [comment]
Directly invoking variable initializers seems to work when you're on tensorflow backend:

```
from keras import backend as K


def reset_weights(model):
    session = K.get_session()
    for layer in model.layers:
        if hasattr(layer, 'W') and hasattr(layer, 'b'):
            old = layer.get_weights()
            layer.W.initializer.run(session=session)
            layer.b.initializer.run(session=session)
            print(np.array_equal(old, layer.get_weights())," after initializer run")
        else:
            print(layer, "not reinitialized")
```

**Comment by philipperemy** [comment]
@frenzykryger does this work for all kinds of layers?

**Comment by frenzykryger** [comment]
@philipperemy, this certainly won't work for all kinds of layers. I tested that for usual fully connected layers only.

**Comment by philipperemy** [comment]
@frenzykryger you should probably add a condition if layer.name != 'Dense' raise Exception() 

(I don't remember exactly about the syntax). I'm saying that because people could just copy/paste your snippet.

**Comment by YoelShoshan** [comment]
Is there now a solution for this?

Right now I implemented the following hack:
                                ```
for layer in model.layers:
for v in layer.__dict__:
                                    v_arg = getattr(layer,v)
                                    if hasattr(v_arg,'initializer'):
                                        initializer_method = getattr(v_arg, 'initializer')
                                        initializer_method.run(session=session)
                                        print('reinitializing layer {}.{}'.format(layer.name, v))
```

**Comment by shyamdsundar** [comment]
@YoelShoshan 's solution is quite good. Just that it might miss out if we create a sub-model. I have pasted a recursive solution based on the prev post

def reinitLayers(model):
    session = K.get_session()
    for layer in model.layers: 
        if type(layer) == keras.engine.training.Model:
            reinitLayers(layer)
            continue
        print("LAYER::", layer.name)
        for v in layer.__dict__:
            v_arg = getattr(layer,v)
            if hasattr(v_arg,'initializer'):
                initializer_method = getattr(v_arg, 'initializer')
                initializer_method.run(session=session)
                print('reinitializing layer {}.{}'.format(layer.name, v))

**Comment by maciejgodek** [comment]
@shyamdsundar `isinstance(layer, keras.engine.topology.Container)`, would be a bit more general than `type(layer) == keras.engine.training.Model`.

**Comment by stevenwong** [comment]
I'm guessing there's still no formal solution to this? I was about to just save the initial weights then reload them until I stumbled across this.

**Comment by pjpjean** [comment]
> This function was working, but it is broken in 2.0, does anyone have a fix?

Replace `keras.engine.topology.Container` for `keras.engine.network.Network`.

Updated code:
```
def reinitLayers(model):
    session = K.get_session()
    for layer in model.layers: 
        if isinstance(layer, keras.engine.network.Network):
            reinitLayers(layer)
            continue
        print("LAYER::", layer.name)
        for v in layer.__dict__:
            v_arg = getattr(layer,v)
            if hasattr(v_arg,'initializer'):
                initializer_method = getattr(v_arg, 'initializer')
                initializer_method.run(session=session)
                print('reinitializing layer {}.{}'.format(layer.name, v))
```

**Comment by mxmlnkn** [comment]
The solutions here seem to ignore the seed I specified with:

    tf.keras.initializers.RandomNormal( mean = 0, stddev = 1, seed = 891783 )

When I recreate the model, the weights are determined as wanted but when running:

    myModel.layers[1].kernel.initializer.run( session = tf.keras.backend.get_session() )

I get different results each time.

**Comment by ei-grad** [comment]
@mxmlnkn the specified seed is used by `tf.random.normal` node for its own initialization, so it is natural that it generates different weights. If you need the exact weights, why not to store them after model creation?

```
initial_weights = model.get_weights()
... some work with model ...
model.set_weights(initial_weights)
```

Btw, my version of above snippet:

```python
from keras import backend as K
import keras

def reset_weights(model):
    session = K.get_session()
    for layer in model.layers: 
        if isinstance(layer, keras.engine.network.Network):
            reset_weights(layer)
            continue
        for v in layer.__dict__.values():
            if hasattr(v, 'initializer'):
                v.initializer.run(session=session)
```

**Comment by Kr0n0** [comment]
There is a chance that the reset_weights function can be integrated into the mainline Keras? It will be very useful IMHO.

**Comment by Anurag27031994** [comment]
> 
> 
> @mxmlnkn the specified seed is used by `tf.random.normal` node for its own initialization, so it is natural that it generates different weights. If you need the exact weights, why not to store them after model creation?
> 
> ```
> initial_weights = model.get_weights()
> ... some work with model ...
> model.set_weights(initial_weights)
> ```
> 
> Btw, my version of above snippet:
> 
> ```python
> from keras import backend as K
> import keras
> 
> def reset_weights(model):
>     session = K.get_session()
>     for layer in model.layers: 
>         if isinstance(layer, keras.engine.network.Network):
>             reset_weights(layer)
>             continue
>         for v in layer.__dict__.values():
>             if hasattr(v, 'initializer'):
>                 v.initializer.run(session=session)
> ```

in this user defined function, will you not return anything, at the end of the function?

**Comment by Anurag27031994** [comment]
> 
> 
> @mxmlnkn the specified seed is used by `tf.random.normal` node for its own initialization, so it is natural that it generates different weights. If you need the exact weights, why not to store them after model creation?
> 
> ```
> initial_weights = model.get_weights()
> ... some work with model ...
> model.set_weights(initial_weights)
> ```
> 
> Btw, my version of above snippet:
> 
> ```python
> from keras import backend as K
> import keras
> 
> def reset_weights(model):
>     session = K.get_session()
>     for layer in model.layers: 
>         if isinstance(layer, keras.engine.network.Network):
>             reset_weights(layer)
>             continue
>         for v in layer.__dict__.values():
>             if hasattr(v, 'initializer'):
>                 v.initializer.run(session=session)
> ```

in this user defined function, will you not return anything, at the end of the function?

**Comment by Anurag27031994** [comment]
> 
> 
> @mxmlnkn the specified seed is used by `tf.random.normal` node for its own initialization, so it is natural that it generates different weights. If you need the exact weights, why not to store them after model creation?
> 
> ```
> initial_weights = model.get_weights()
> ... some work with model ...
> model.set_weights(initial_weights)
> ```
> 
> Btw, my version of above snippet:
> 
> ```python
> from keras import backend as K
> import keras
> 
> def reset_weights(model):
>     session = K.get_session()
>     for layer in model.layers: 
>         if isinstance(layer, keras.engine.network.Network):
>             reset_weights(layer)
>             continue
>         for v in layer.__dict__.values():
>             if hasattr(v, 'initializer'):
>                 v.initializer.run(session=session)
> ```

in this user defined function, will you not return anything, at the end of the function?

**Comment by Anurag27031994** [comment]
> 
> 
> > This function was working, but it is broken in 2.0, does anyone have a fix?
> 
> Replace `keras.engine.topology.Container` for `keras.engine.network.Network`.
> 
> Updated code:
> 
> ```
> def reinitLayers(model):
>     session = K.get_session()
>     for layer in model.layers: 
>         if isinstance(layer, keras.engine.network.Network):
>             reinitLayers(layer)
>             continue
>         print("LAYER::", layer.name)
>         for v in layer.__dict__:
>             v_arg = getattr(layer,v)
>             if hasattr(v_arg,'initializer'):
>                 initializer_method = getattr(v_arg, 'initializer')
>                 initializer_method.run(session=session)
>                 print('reinitializing layer {}.{}'.format(layer.name, v))
> ```

in this user defined function, will you not return anything, at the end of the function?

**Comment by Anurag27031994** [comment]
> 
> 
> @mxmlnkn the specified seed is used by `tf.random.normal` node for its own initialization, so it is natural that it generates different weights. If you need the exact weights, why not to store them after model creation?
> 
> ```
> initial_weights = model.get_weights()
> ... some work with model ...
> model.set_weights(initial_weights)
> ```
> 
> Btw, my version of above snippet:
> 
> ```python
> from keras import backend as K
> import keras
> 
> def reset_weights(model):
>     session = K.get_session()
>     for layer in model.layers: 
>         if isinstance(layer, keras.engine.network.Network):
>             reset_weights(layer)
>             continue
>         for v in layer.__dict__.values():
>             if hasattr(v, 'initializer'):
>                 v.initializer.run(session=session)
> ```

in this user defined function, will you not return anything, at the end of the function?

**Comment by Anurag27031994** [comment]
> 
> 
> Is there now a solution for this?
> 
> For now I implemented the following hack, which runs initialization for every member variable on each layer, which has a method "initializer".
> This way I don't need to do any special handling for every type of layer (dense, conv, batchnorm, etc...)
> 
> Is there any need to contribute this into keras? as a model reset function? or is it already implemented ?
> 
> edit:
> would this solve the issues that you mentioned? @wxs
> 
> ```python
> session = K.get_session()
> for layer in model.layers: 
>      for v in layer.__dict__:
>          v_arg = getattr(layer,v)
>          if hasattr(v_arg,'initializer'):
>              initializer_method = getattr(v_arg, 'initializer')
>              initializer_method.run(session=session)
>              print('reinitializing layer {}.{}'.format(layer.name, v))
> ```
> 
> an example (partial) output for this is:
> 
> ```
> reinitializing layer conv2d_28.kernel
> reinitializing layer batch_normalization_28.moving_mean
> reinitializing layer batch_normalization_28.moving_variance
> reinitializing layer batch_normalization_28.beta
> reinitializing layer conv2d_29.kernel
> reinitializing layer batch_normalization_29.moving_mean
> reinitializing layer batch_normalization_29.moving_variance
> reinitializing layer batch_normalization_29.beta
> reinitializing layer conv2d_27.kernel
> reinitializing layer conv2d_30.kernel
> reinitializing layer batch_normalization_27.moving_mean
> reinitializing layer batch_normalization_27.moving_variance
> reinitializing layer batch_normalization_27.beta
> reinitializing layer batch_normalization_30.moving_mean
> reinitializing layer batch_normalization_30.moving_variance
> reinitializing layer batch_normalization_30.beta
> reinitializing layer conv2d_35.kernel
> reinitializing layer batch_normalization_35.moving_mean
> reinitializing layer batch_normalization_35.moving_variance
> reinitializing layer batch_normalization_35.beta
> reinitializing layer conv2d_36.kernel
> reinitializing layer batch_normalization_36.moving_mean
> reinitializing layer batch_normalization_36.moving_variance
> reinitializing layer batch_normalization_36.beta
> reinitializing layer conv2d_32.kernel
> reinitializing layer conv2d_37.kernel
> reinitializing layer batch_normalization_32.moving_mean
> reinitializing layer batch_normalization_32.moving_variance
> reinitializing layer batch_normalization_32.beta
> reinitializing layer batch_normalization_37.moving_mean
> reinitializing layer batch_normalization_37.moving_variance
> reinitializing layer batch_normalization_37.beta
> reinitializing layer conv2d_33.kernel
> reinitializing layer conv2d_38.kernel
> reinitializing layer batch_normalization_33.moving_mean
> reinitializing layer batch_normalization_33.moving_variance
> reinitializing layer batch_normalization_33.beta
> reinitializing layer batch_normalization_38.moving_mean
> reinitializing layer batch_normalization_38.moving_variance
> reinitializing layer batch_normalization_38.beta
> reinitializing layer conv2d_31.kernel
> reinitializing layer conv2d_34.kernel
> reinitializing layer conv2d_39.kernel
> reinitializing layer conv2d_40.kernel
> reinitializing layer batch_normalization_31.moving_mean
> reinitializing layer batch_normalization_31.moving_variance
> reinitializing layer batch_normalization_31.beta
> reinitializing layer batch_normalization_34.moving_mean
> reinitializing layer batch_normalization_34.moving_variance
> reinitializing layer batch_normalization_34.beta
> reinitializing layer batch_normalization_39.moving_mean
> reinitializing layer batch_normalization_39.moving_variance
> reinitializing layer batch_normalization_39.beta
> reinitializing layer batch_normalization_40.moving_mean
> reinitializing layer batch_normalization_40.moving_variance
> reinitializing layer batch_normalization_40.beta
> reinitializing layer conv2d_45.kernel
> reinitializing layer batch_normalization_45.moving_mean
> reinitializing layer batch_normalization_45.moving_variance
> reinitializing layer batch_normalization_45.beta
> reinitializing layer conv2d_46.kernel
> reinitializing layer batch_normalization_46.moving_mean
> reinitializing layer batch_normalization_46.moving_variance
> reinitializing layer batch_normalization_46.beta
> reinitializing layer conv2d_42.kernel
> reinitializing layer conv2d_47.kernel
> reinitializing layer batch_normalization_42.moving_mean
> reinitializing layer batch_normalization_42.moving_variance
> reinitializing layer batch_normalization_42.beta
> reinitializing layer batch_normalization_47.moving_mean
> reinitializing layer batch_normalization_47.moving_variance
> reinitializing layer batch_normalization_47.beta
> reinitializing layer conv2d_43.kernel
> reinitializing layer conv2d_48.kernel
> reinitializing layer batch_normalization_43.moving_mean
> reinitializing layer batch_normalization_43.moving_variance
> reinitializing layer batch_normalization_43.beta
> reinitializing layer batch_normalization_48.moving_mean
> reinitializing layer batch_normalization_48.moving_variance
> reinitializing layer batch_normalization_48.beta
> reinitializing layer conv2d_41.kernel
> reinitializing layer conv2d_44.kernel
> reinitializing layer conv2d_49.kernel
> reinitializing layer conv2d_50.kernel
> reinitializing layer batch_normalization_41.moving_mean
> reinitializing layer batch_normalization_41.moving_variance
> reinitializing layer batch_normalization_41.beta
> reinitializing layer batch_normalization_44.moving_mean
> reinitializing layer batch_normalization_44.moving_variance
> reinitializing layer batch_normalization_44.beta
> reinitializing layer batch_normalization_49.moving_mean
> reinitializing layer batch_normalization_49.moving_variance
> reinitializing layer batch_normalization_49.beta
> reinitializing layer batch_normalization_50.moving_mean
> reinitializing layer batch_normalization_50.moving_variance
> reinitializing layer batch_normalization_50.beta
> reinitializing layer conv2d_55.kernel
> reinitializing layer batch_normalization_55.moving_mean
> reinitializing layer batch_normalization_55.moving_variance
> reinitializing layer batch_normalization_55.beta
> reinitializing layer conv2d_56.kernel
> ```

in this user defined function, will you not return anything, at the end of the function?

**Comment by ei-grad** [comment]
@Anurag27031994 
> in this user defined function, will you not return anything, at the end of the function?

It doesn't return anything because it modify the model weights in-place.

Could you please delete this huge repeated comments and, if your question is still unanswered, explain more clearly if you think if there is something wrong with the functions which doesn't return values? (though the stackoverflow.com is a better place for such questions)

**Comment by daklab** [comment]
This seems to be broken using TF2 as the backend, I get `AttributeError: module 'tensorflow' has no attribute 'get_default_session'`

**Comment by chuong** [comment]
I am surprised that such a commonly needed reset_weights() function is not yet a builtin Keras function. It seems non of the solutions on the internet working at the moment. The only working solution so far is to rebuild the network each time to reset its weights.

**Comment by 183amir** [comment]
If you are using tensorflow 2, you can use this:
```python

def reset_weights(model):
  for layer in model.layers: 
    if isinstance(layer, tf.keras.Model):
      reset_weights(layer)
      continue
    for k, initializer in layer.__dict__.items():
      if "initializer" not in k:
        continue
      # find the corresponding variable
      var = getattr(layer, k.replace("_initializer", ""))
      var.assign(initializer(var.shape, var.dtype))
```
I am not sure if it works in all cases, I have only tested the Dense and Conv2D layers.

**Comment by AZippelius** [comment]
It works for Conv1d as well, but it does not work for the LSTM layer. The initializers are bound to the cell for that layer, which that function doesn't reach.

**Comment by AZippelius** [comment]
An attempt to extend the solution by @183amir in https://github.com/keras-team/keras/issues/341#issuecomment-539198392 to recurrent layers. It works for standard recurrent Keras layers (SimpleRNN, GRU, LSTM, ConvLSTM2D) as well as Dense, Conv1D and Conv2D, but there may be layer types where it doesn't work.


```python
def reset_weights(model):
    for layer in model.layers:
        if isinstance(layer, tf.keras.Model): #if you're using a model as a layer
            reset_weights(layer) #apply function recursively
            continue

        #where are the initializers?
        if hasattr(layer, 'cell'):
            init_container = layer.cell
        else:
            init_container = layer

        for key, initializer in init_container.__dict__.items():
            if "initializer" not in key: #is this item an initializer?
                  continue #if no, skip it

            # find the corresponding variable, like the kernel or the bias
            if key == 'recurrent_initializer': #special case check
                var = getattr(init_container, 'recurrent_kernel')
            else:
                var = getattr(init_container, key.replace("_initializer", ""))

            var.assign(initializer(var.shape, var.dtype))
            #use the initializer
```

**Comment by jneuhauser** [comment]
For me this isn't working... I'm using @AZippelius method that is based on the one from @183amir.

This is my error trace:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-50-b962be4acb5c> in <module>
----> 1 reset_weights(model.netg.decoder)

~tf/models/ganomaly.py in reset_weights(model)
    355     for layer in model.layers:
    356         if isinstance(layer, tf.keras.Model): #if you're using a model as a layer
--> 357             reset_weights(layer) #apply function recursively
    358             continue
    359 

~tf/models/ganomaly.py in reset_weights(model)
    374                 var = getattr(init_container, key.replace("_initializer", ""))
    375 
--> 376             var.assign(initializer(var.shape, var.dtype))
    377 
    378

AttributeError: 'NoneType' object has no attribute 'assign'
```

**model.netg.decoder** is a tf.keras.Sequential() with Conv2d, LeakyReLU and BatchNorm layers.

Any help is appreciated.

**Comment by AZippelius** [comment]
Based on the error, var is None, so I would guess it hasn't been defined yet. Maybe check that in a debugger?

**Comment by jneuhauser** [comment]
Many thanks... 
I thought that this is a generic error, but it turns out that I'm using a `Conv2D(..., use_bias=False)` and the attribute "bias_initializer" is None.

So my solution is a simple check if var is not None:
```
if var is not None:
    var.assign(initializer(var.shape, var.dtype))
```

**Comment by 183amir** [comment]
Could we please have this issue re-opened? I think resetting/reinitializing the weights deserves its own API.

**Comment by jneuhauser** [comment]
I think we have to ping at least one of the keras-team members to get attraction...

Ping @Dref360 @ebursztein @farizrahman4u @gabrieldemarmiesse @haifeng-jin @taehoonlee

**Comment by thongonary** [comment]
@AZippelius I just want to point out that your solution doesn't seem to work for `tf.keras.layers.GRU` in TF 2.3.1. I got the following error:
```
AttributeError: 'GRUCell' object has no attribute 'kernel'
```
When I print out the list of attributes with `print(dir(init_container))`, there is indeed neither `kernel` nor `recurrent_kernel`.

Do you have any suggestion?

**Comment by pfwnicks** [comment]
Is this dead? I am currently looking for this functionality as well, becuase when using time series cross validation I need to iterate and reset the weights many times in order to simulate real-time use. Right now I just repeatedly build and compile my model in order to achieve this...

**Comment by NEGU93** [comment]
Same here. Could this issue be re-opened? I believe we should need an API like `model.reset_weigths()`.

**Comment by vishnuiiit** [comment]
I also think, we could really use a function like model.reset_weights()

**Comment by Janesefor** [comment]
I also think, we could really use a function like model.reset_weights()

**Comment by NEGU93** [comment]
I asked for the feature directly to Tensorflow now to see if any team gets it done. I do understand it is somehow hard to do as every layer inits the weights in a different manner. Here the [link](https://github.com/tensorflow/tensorflow/issues/48230)

**Comment by geajack** [comment]
This seems like such an obvious feature. Why is it not implemented? I don't understand the argument that it's hard to do because "every layer inits the weights in a different manner". After all, when you first build and run the model, it inits the weights somehow, it's just a matter of calling the code that does that a second time.

**Comment by skannan-maf** [comment]
I simply save the weights "before" the first fit..... 
And then before each fit, I set_weights() to the initial untrained weight.....
Thats it!

**Comment by geajack** [comment]
> I simply save the weights "before" the first fit..... And then before each fit, I set_weights() to the initial untrained weight..... Thats it!

That's not the issue - the idea here is to re-*randomize* the weights using the given initialization scheme. For setting the weights back to their (deterministic) initial weights, your method is indeed probably the only viable one, as the user really has to be made to call `get_weights()` explicitly at some point or Keras can't really know what they mean by "initial".

**Comment by skannan-maf** [comment]
The idea of re-randomizing is to ensure that we don't do incremental training. For such cases (that was my requirement), the simply initial-weight saving scheme would do, I guess.

**Comment by zuranski** [comment]
A solution from @AZippelius in their [comment](https://github.com/keras-team/keras/issues/341#issuecomment-547833394) works well, however, when creating an LSTM layer, the bias of the forget cell is set to 1 and other biases are set to 0. This is according to some tribal knowledge that it makes training easier. The bias_initializer of the lstm_cell is Zeros, so running the function zeros all the biases, understandably, but produces a different initial state. 

It looks like there is extra logic for the LSTM cell initialization that cannot be inferred from the initializers.
