### ISSUE TITLE
Partial model saving

### ISSUE THREAD

**Issue by ipoletaev** [fchollet/keras#3418]
Hello! I haven't found the way how to save only the part of weights of the model. Maybe I should to truncate unnecessary layers and save remains? But then it's not clear how to load this part of weights into the another model. 
Thanks for comments.

**Comment by solomondg** [comment]
Honestly as far as I can tell this is a pretty lacking part of Keras, at least at the moment. Caffe-like net surgery functionality would be pretty amazing. What I do is just make another model minus the layers I don't want, then copy the weights over.

**Comment by ipoletaev** [comment]
Ok! I understood that for now I can't do nothing for this. Thank!
