### ISSUE TITLE
Bug in ImageDataGenerator/standartize

### ISSUE THREAD

**Issue by eyaler** [fchollet/keras#3422]
the samplewise operations should be over the spatial axes not over the channel axis. i.e.

x -= np.mean(x, axis=img_channel_index, keepdims=True)

should be:

x -= np.mean(x, axis=(row_channel_index, col_channel_index), keepdims=True)

**Comment by eyaler** [comment]
@fchollet could you please expain if i have misunderstood? Isnt the purpose of samplewise to do global brightness/contrast normalization (per channel)? What is the logic of averaging each pixel over the channels, instead of each channel over all pixels?

**Comment by isaacgerg** [comment]
Why was this closed? It still an issue.

**Comment by isaacgerg** [comment]
@eyaler I just issued a PR to fix this. #4482
