### ISSUE TITLE
Problem with dimensions after recent update

### ISSUE THREAD

**Issue by jfsantos** [fchollet/keras#343]
I cannot pinpoint which release specifically is causing this, but code that was running correctly is now breaking during the validation stage for the first epoch (even though training goes fine). The error is something like this:

```
  File "han2015.py", line 46, in <module>
    model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=nb_epoch, valida
tion_data=[X_valid, y_valid], show_accuracy=False, callbacks=[checkpoint_cb])
  File "/home/jfsantos/src/keras/keras/models.py", line 371, in fit
    validation_split=validation_split, val_f=val_f, val_ins=val_ins, shuffle=sh$
ffle, metrics=metrics)
  File "/home/jfsantos/src/keras/keras/models.py", line 148, in _fit
    val_outs = val_f(*val_ins)
  File "/home/jfsantos/anaconda3/lib/python3.4/site-packages/theano/compile/fun$
tion_module.py", line 531, in __call__
    allow_downcast=s.allow_downcast)
  File "/home/jfsantos/anaconda3/lib/python3.4/site-packages/theano/tensor/type$
py", line 168, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/home/jfsantos/sr$
/keras/keras/models.py:292"  at index 0(0-based)', 'Wrong number of dimensions: 
expected 2, got 3 with shape (154665, 1, 1771).')
```

I don't know why the dimensions of the validation set were changed from `(n_samples, n_features)` to `(n_samples, 1, n_features)`, but that seems to be what's causing this. The code does not do anything fancy reshaping-wise (3 layer MLP with MSE cost).

**Comment by fchollet** [comment]
Do you have code to repro this?

**Comment by simonhughes22** [comment]
Sounds like the issue I was having with the binary_crossentropy. Could be completely different though I guess.

**Comment by jfsantos** [comment]
I will try to make a minimal reproducing example and post it later, as my
current example depends on a lot of code.

--
João Felipe Santos
