### ISSUE TITLE
[Bug?] MemoryError (CNEM_STATUS_OUT_OF_MEMORY) even after going back to a batch size that worked before

### ISSUE THREAD

**Issue by madeofwin** [fchollet/keras#3439]
Let's assume I am in a python shell and I start training a model:

`model.fit(X,Y, batch_size = 8)`

Works like a charm, but now I want to try a larger batch size:

```
model.fit(X,Y, batch_size = 16)
MemoryError: Error allocating 52428800 bytes of device memory (CNMEM_STATUS_OUT_OF_MEMORY).
```

Alright, that was too much, let's go back to the batch size that worked before

```
model.fit(X,Y, batch_size = 8)
MemoryError: Error allocating 26214400 bytes of device memory (CNMEM_STATUS_OUT_OF_MEMORY).
```

woops, suddenly I can't train my model anymore. I've encountered this problem in different keras/theano versions. Running the most recent versions of both now and I can still observe this behaviour.

**Comment by kgrm** [comment]
Are you running anything else on the GPU - eg, your desktop? This might affect the amount of gpu ram available for allocation by cnmem.

**Comment by madeofwin** [comment]
Yes I do, but how does this explain that the process is not reversible, i.e. while batch_size = 8 initially works, increasing to batch_size = 16 and going back to batch_size = 8 does not work?
