### ISSUE TITLE
Can't remove layers

### ISSUE THREAD

**Issue by bernardohenz** [fchollet/keras#3442]
I am loading a pre-trained model and I want to remove the two last layers of it, I think the simple code would suffice:

```python
model.layers.pop()
model.layers.pop()
```

but  when calling ```model.output_shape```, the model continues outputting the same as before. I already tried some answers of other posts  ( #2371), testing also the following code:

```python
model.layers.pop()
model.layers.pop()
model.outputs = [model.layers[-1].output]
model.layers[-1].outbound_nodes = []
```
But it is also not working (at least the ```model.output_shape``` continues the same.

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
Update Keras. What you describe should work.

**Comment by bernardohenz** [comment]
Oh, now that I've runned the ```model.predict```, it is outputting the correct shape

**Comment by keunwoochoi** [comment]
Is it really fixed? I wanna do the same and `.pop()` only affects `model.layers`. Keras 1.10, Theano.

**Comment by bernardohenz** [comment]
You need to do as I've posted:

```python
model.layers.pop()
model.layers.pop()
model.outputs = [model.layers[-1].output]
model.layers[-1].outbound_nodes = []
```

**Comment by keunwoochoi** [comment]
Thanks.

**Comment by zhimingluo** [comment]
`model = ResNet50(False, weights='imagenet', input_shape=[224, 224, 3])

    # remove the last average pooling layer
    model.layers.pop()
    model.outputs = [model.layers[-1].output]
    model.layers[-1].outbound_nodes = []

    print(model.output)
    print(model.outputs)`

The print results: 
```
Tensor("AvgPool_1:0", shape=(?, 1, 1, 2048), dtype=float32)
[<tf.Tensor 'Relu_97:0' shape=(?, 7, 7, 2048) dtype=float32>]
```
also need to change the model.output

**Comment by shahabaslani** [comment]
I want to use 2 Resnet at the same time with two different input. I wrote the code like; (I called the pr-trained Resnets and removed the last layers of both networks)

I1 = Input(shape=(304, 304, 3))
model1 = ResNet50(weights='imagenet', include_top= False, input_tensor= I1, pooling=None)
model1.layers.pop()
model1.outputs = [model1.layers[-1].output]
model1.layers[-1].outbound_nodes = []

I2 = Input(shape=(304, 304, 3))
model2 = ResNet50(weights='imagenet', include_top= False, input_tensor= I2, pooling=None)
for layer in model2.layers:
    layer.name = layer.name + str("_2")
model2.layers.pop()
model2.outputs = [model2.layers[-1].output]
model2.layers[-1].outbound_nodes = []

Then I concatenate the outputs and upsamples them to the same size of input image 304*304;

output1 = model1.get_layer('activation_49').output
output2 = model2.get_layer('activation_98_2').output
Fus1 = Concatenate(axis=-1)([output1, output2])
Up3 =UpSampling2D(size=(30, 30), data_format=None)(Fus1)
Up4 =Conv2DTranspose(64, (5, 5), strides=(1, 1), data_format=None, padding='valid')(Up3)
Up5 = Conv2D(1, (1, 1), activation='sigmoid')(Up4)
model = Model([I1, I2], Up5)

But when I try to train the network like; 

model.compile(optimizer=Adam(lr=1e-5), loss='binary_crossentropy', metrics=[dice])
model_checkpoint = ModelCheckpoint(filepath='/home/shahab/Documents/unet/ms/model/weights.hdf5', monitor='val_loss', save_best_only=False, period=1)
history = model.fit([imgs_train, imgs_validation], [imgs_mask_train, imgs_mask_validation], batch_size=15, epochs=100, verbose=1, shuffle=True, validation_split=0.2, callbacks=[model_checkpoint])

I got the error like this, which seems that during the training again the last layers of both networks are active during the training procedure;

ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[[[ 0.],
         [ 0.],
         [ 0.],
         ..., 
         [ 0.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.],
         ..., 
         [ 0.],

Do you havre any idea how can I fix it?!!1
Thanks.
