### ISSUE TITLE
Is the RNN output with 'go_backwards=True' and 'return_sequence=True' options time synchronized with options 'go_backwards=False' and 'return_sequence=True' ?

### ISSUE THREAD

**Issue by sk210892** [fchollet/keras#3448]
Can someone please confirm this case? Seeing the code and running some dummy experiment, it seems to me that the forward and backward RNN outputs are not time synchronized if 'return_sequence=True'. So when I timestep-wise concatenate the forward and backward outputs to encode something, it does not make any sense.

Thanks :)

**Comment by ymcui** [comment]
if you want to concatenate forward and backward RNN to form a bi-directional RNN,
then you should do a time-reverse operation (using `lambda` layer) on the backward RNN, to keep the same time flows with the forward one.

**Comment by sk210892** [comment]
Is this done on some purpose, i.e., returning the output in a reverse time sequence when 'go_backwards=True' and 'return_sequence=True' ? Or, its just a bug?

**Comment by ymcui** [comment]
i don't think that is a bug.
maybe someone just want the 'reversed' outputs.
so, if you turn on `return_sequence`, both the input and output will be in reversed sequence.
