### ISSUE TITLE
The shape of output in Graph

### ISSUE THREAD

**Issue by floydsoft** [fchollet/keras#345]
Hi,

If the output target is only 1-dimension, i.e., the y_train has the `shape=(n,)`, it will crash unless reshape to `(n, 1)`. Is it meant to be?

**Comment by fchollet** [comment]
I have added output shape standardization to Graph now, so that 1-dimensional arrays will be reshape to 2-dimensional.

**Comment by floydsoft** [comment]
@fchollet :+1:
