### ISSUE TITLE
shape inference issue with tensorflow inputs

### ISSUE THREAD

**Issue by mmmikael** [fchollet/keras#3450]
Since 1.0.7, there is an issue for some networks when using a tensorflow placeholder as input:

``` python
import tensorflow as tf
from keras.layers import Flatten, Convolution2D, Dense

image_shape = (None, 128, 128, 1)
images = tf.placeholder(tf.float32, shape=image_shape)
output = Convolution2D(9, 3, 3)(images)
output = Flatten(trainable=False)(output)
output = Dense(1)(output)
```

This gives the error:

```
  File "...keras/initializations.py", line 58, in glorot_uniform
    s = np.sqrt(6. / (fan_in + fan_out))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

It still works though with an `Input` layer :

``` python
from keras.layers import Flatten, Convolution2D, Dense, Input

image_shape = (None, 128, 128, 1)
images = Input(shape=image_shape[1:])
output = Convolution2D(9, 3, 3)(images)
output = Flatten(trainable=False)(output)
output = Dense(1)(output)
```

The problem seems related to the `Flatten` layer.

**Comment by EderSantana** [comment]
yeah, this is a TF thing. whenever using tensorflow backend, if you have ANY reshape operation in the network, you have to specify all dimensions.

**Comment by mmmikael** [comment]
Interestingly it seems to work with previous versions of Keras (<1.0.7). 

It's not a big issue since we can just define an Input layer instead.

**Comment by ritchieng** [comment]
@mmmikael Hi, may I know what was your solution? I'm struggling with this and I can't find a solution.
