### ISSUE TITLE
A model cannot be restored from configuration

### ISSUE THREAD

**Issue by ruslanagit** [fchollet/keras#3452]
The following code:
```
model = Model(input=a, output=b)
config = model.get_config()
restored_model = model_from_config(config)
```
Fails with an exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2\helpers\pydev\pydevd.py", line 1556, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2\helpers\pydev\pydevd.py", line 940, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/develop/code/ladder/test.py", line 41, in <module>
    model_recovered = model_from_config(config)
  File "C:\Program Files\Dragonfly\Anaconda3\lib\site-packages\keras-1.0.7-py3.5.egg\keras\models.py", line 177, in model_from_config
    return layer_from_config(config, custom_objects=custom_objects)
  File "C:\Program Files\Dragonfly\Anaconda3\lib\site-packages\keras-1.0.7-py3.5.egg\keras\utils\layer_utils.py", line 25, in layer_from_config
    **class_name = config['class_name']
KeyError: 'class_name'**

I have a fix for this, and will submit it as a pull request. 

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [v] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [v] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [v] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
Please share a standalone code snippet to reproduce your issue.

**Comment by ruslanagit** [comment]
This is easily reproachable with **any model**, and the few lines I provided clearly underline the problem. Anyway, here is more complete example (I took it from online keras documentation, and just added a few lines)

```
from keras.layers import Input, Dense
from keras.models import Model
from keras.models import model_from_config

# this returns a tensor
inputs = Input(shape=(784,))

# a layer instance is callable on a tensor, and returns a tensor
x = Dense(64, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

# this creates a model that includes
# the Input layer and three Dense layers
model = Model(input=inputs, output=predictions)

# MY CODE COMES HERE
config = model.get_config()
restored_model = model_from_config(config)
```

**Comment by ruslanagit** [comment]
Well, the main problem is that Model.from_config and model_from_config make different assumptions regarding the configuration parameters:

- **model_from_config** assumes that the configuration is a dictionary of 2 keys: one is 'class_name' (i.e. 'Model'), and the second is 'config' (i.e. the full model configuration).

- **Model.from_config** assumes that the configuration is the full model configuration (i.e. the value of 'config' key from model_from_config method)

Whereas it's completely unexpected to have them both to behave differently, there is code that uses both methods in different situations (i.e. when configuration was saved to file - with additional level of configuration encapsulation, and when the configuration was obtained from Model.get_config method). Obviously, there is a need to redesign the code to get consistent behavior in both scenarios.
Unfortunately, I cannot invest my time in this right now. Somebody will need to fix it one day...

**Comment by fchollet** [comment]
Oh yeah, I see what you meant. It makes perfect sense: `model_from_config` can load any model class, so it requires a `class_name` field. When you call `Model.from_config` it is implied that you are loading a `Model` class, not just any random class.
