### ISSUE TITLE
Issue with the shape in fit() method

### ISSUE THREAD

**Issue by AakashKumarNain** [fchollet/keras#3454]
[myScript.zip](https://github.com/fchollet/keras/files/414006/myScript.zip)

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [* ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [* ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ *] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Please find the attached code file. In that, I have a training set X_train = (1757832, 52) and y_train =(1757832,). Even the same training set worked perfectly fine with sklearn but when I used it with Keras, it throws the following error. Please help!!

`Traceback (most recent call last):
  File "../src/script.py", line 137, in 
    model.fit(X_train, y_train)
  File "/opt/conda/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/wrappers/scikit_learn.py", line 148, in fit
    history = self.model.fit(X, y, **fit_args)
  File "/opt/conda/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/models.py", line 429, in fit
    sample_weight=sample_weight)
  File "/opt/conda/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/training.py", line 1036, in fit
    batch_size=batch_size)
  File "/opt/conda/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/training.py", line 963, in _standardize_user_data
    exception_prefix='model input')
  File "/opt/conda/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/training.py", line 108, in standardize_input_data
    str(array.shape))
Exception: Error when checking model input: expected dense_input_1 to have shape (None, 1757832) but got array with shape (1757832, 52)
`

**Comment by DominicBreuker** [comment]
Two things to fix this as far as I can tell:
- Convert pandas DataFrames to numpy arrays: I'm not sure keras can handle DataFrames, so calling df.to_matrix() yourself is a good idea.
- Change input dimension of first layer to number of features: currently, you pass in the number of data points for the input_dim parameter. Change it to the number of features.

The code below should fix the script:

_Convert to numpy arrays_
```
X_train = X_train.as_matrix()
X_test = X_test.as_matrix()
y_train = y_train.as_matrix()
y_test = y_test.as_matrix()
```

_Use number of features as input dimension_
```
num_features = X_train.shape[1]
...
model.add(Dense(100, input_dim = num_features, activation='relu', init=init))
```

**Comment by AakashKumarNain** [comment]
Thanks a lot. It worked!!
