### ISSUE TITLE
Combining Pretrained model with new layers

### ISSUE THREAD

**Issue by AntreasAntoniou** [fchollet/keras#3465]
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I was wondering how one can load a pretrained model and then add new layers to it. With the pre-functional keras, you could do that by using the model class, building the architecture, loading the weights and then treating the result as another component of the new more complex network.

With the after-functional keras you can no longer do that. 

E.g.

The below script builds and loads the model and pops the last 2 layers:

```
resnet_model = get_resnet50()
weights_file = "th_dim_ordering_resnet50.h5"
resnet_model.load_weights(weights_file)
resnet_model.layers.pop()
resnet_model.layers.pop()
```

The resnet model uses the provided keras example methods, and is of type Model:

```
model = Model(inp, out)
```

Now when I try to use this as just another component with the following code:

```
dense_output = Dense(output_dim=10000, activation='relu')(resnet_model)
model = Model(input=inputs, output=dense_output)
model.compile(optimizer=Adam(lr=1e-5),
 loss='categorical_crossentropy')
```

I get: 

```
Traceback (most recent call last):
File "train.py", line 253, in <module>
train_and_predict()
File "train.py", line 211, in train_and_predict
model = get_unet_multitask()
File "train.py", line 114, in get_unet_multitask
up6 = UpSampling2D(size=(2, 2))(resnet_model)
File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.7-py2.7.egg/keras/engine/topology.py", line    467, in __call__
self.assert_input_compatibility(x)
File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.7-py2.7.egg/keras/engine/topology.py", line  403, in assert_input_compatibility
if K.ndim(x) != spec.ndim:
File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.7-py2.7.egg/keras/backend/theano_backend.py", line 70, in ndim
return x.ndim
AttributeError: 'Model' object has no attribute 'ndim'
```

Any ways to go around this without having to rewrite the architecture building method to using the old keras?

**Comment by Deneb91** [comment]
Did you find any solution for your problem? I have the same problem here.

**Comment by giorgiop** [comment]
Can you try instead:

```
model.layers.pop()
model.layers[-1].outbound_nodes = []
model.outputs = [model.layers[-1].output]
output = model.get_layer('avg_pool').output
output = Flatten()(output)
output = Dense(output_dim=10000, activation='relu')(output) # your newlayer Dense(...)
new_model = Model(model.input, output)
```

**Comment by fera0013** [comment]
I get the same type of error with the following code:

```
 model = VGG16(input_tensor=input_tensor, include_top=False)
        x = model.output
        x = AveragePooling2D((7, 7))(x)
        x = Flatten()(x)
        x = Dropout(0.5)(x)
        x = Dense(1024)(x)
        x = Dropout(0.5)(x)
        x = Dense(256)(x)
        x = Dropout(0.5)(x)
        x = Dense(1)(x)
        model = Model(model.input, x)
```

**Comment by Vijethbv** [comment]
@fera0013 when I try to pop the layers using model.pop() I am getting error like "AttributeError: 'Model' object has no attribute 'pop' " how to aceive this ?

**Comment by kratzert** [comment]
@Vijethbv Don't get confused with the different model types. In the graph models (you can identify them by the function call to `Model(input, output)` there exist no `.pop()` function. This function can only be used in sequential models. 

If you want to use any arbitrary layer of a pretrained network as input to your new model, you can use the `model.get_layer(layername).output` function. Else you will get the 
`AttributeError: 'XXX' object has no attribute 'ndim'`

**Comment by Vijethbv** [comment]
@kratzert I understand what you have mentioned. But, If I want to add few layers on top of VGG16 model, so I wanted to remove the last 3 layers that are fully connected, so how I thought about doing it is :
    model = Sequential()
    model = vgg16_keras.VGG_16()
    
    model.load_weights(weights_path)
    print('Loaded Model from disk')
    
    ##Removing the MLP layer
    for i in xrange(6):
        model.pop()
    print(model.layer[-1])

when I do this I get error saying :  AttributeError: 'Sequential' object has no attribute 'layer'

How to do it ?

**Comment by kratzert** [comment]
Okay, first of all the error that is raised is due to a misspelling. It's `model.layers` with an **s** at the end. But this will not solve your problem. 

If you look carefully at the [documentation](https://keras.io/applications/#vgg16) you can just load the model with `include_top = False`. This will automatically instantiate the vgg16 model without the dense layers at the top. If you want to initialize the rest with the imagenet weights, just add `weights = 'imagenet'` to the function call

E.g.
```
from keras.applications.vgg16 import VGG16
from keras.models import Model
from keras.layers import Flatten, Dense, Dropout
from keras.layers.normalization import BatchNormalization

#load vgg16 without dense layer and with theano dim ordering
base_model = VGG16(weights = 'imagenet', include_top = False, input_shape = (3,224,224))

#number of classes in your dataset e.g. 20
num_classes = 20

x = Flatten()(base_model.output)
x = Dense(4096, activation='relu')(x)
x = Dropout(0.5)(x)
x = BatchNormalization()(x)
predictions = Dense(num_classes, activation = 'softmax')(x)

#create graph of your new model
head_model = Model(input = base_model.input, output = predictions)

#compile the model
head_model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

head_model.summary()
.
.
.
#train your model on data
head_model.fit(x, y, batch_size = batch_size, verbose = 1)
```

There are quite a lot of tutorials out there for fine-tuning vgg16 with keras. Maybe you should check out the deep learning course by Jeremy Howard and Rachel Thomas as they do quite a lot of fine tuning on vgg16 and they have pretty nice jupyter notebooks on everything. Just search for fast.ai

**Comment by valanm** [comment]
@kratzert try with  `model.layers.pop()` should work

**Comment by VamsiKrishna-Penumadu** [comment]
Iam trying to extract features from the fc1 layer using 
extract_fc1_features = Model(input=model.input, output=model.get_layer('fc1').output)
 fc1_features = extract_fc1_features.predict(Image)

But The output vector 4096 values of the image consists of approximately 50% of zeros.

I am assuming this is because of drop out.

Is there any way to get the features without drop out?

Thank you

**Comment by Jie317** [comment]
You may try to get the output in another way according to [keras.io](https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer)
`get_3rd_layer_output = K.function([model.layers[0].input, K.learning_phase()],
                                  [model.layers[3].output])

# output in test mode = 0
layer_output = get_3rd_layer_output([X, 0])[0]

# output in train mode = 1
layer_output = get_3rd_layer_output([X, 1])[0]`

**Comment by lyuzhilinag** [comment]
@kratzert Thank you for your tutorials, I have successfully added the fully connected layers on my pre-trained vgg16 network and it went well. When I loaded the weights in my new network and tried to predict the classes labels for my test data, here I got error ''Model' object has no attribute 'predict_classes', It seems only sequential object has 'predict_classes', the keras 2.0.4 API only provides predict() for functional object, and it gives predict result array like (1,14,14,256), I can't figure out what this array means for the labels prediction, is there any way to use the functional network to predict classes? Appreciate for your reply.

**Comment by shuuchen** [comment]
this works:

model = Model(inputs=base_model.input, outputs=top_model(base_model.output))

**Comment by DawnMe** [comment]
@shuuchen Thanks! I've been looking everywhere for this solution!

**Comment by vladimircape** [comment]
@kratzert  . Thank for that. But you create big mistake, you didn't make VGG16
this part of code is wrong
```

x = Flatten()(base_model.output)
x = Dense(4096, activation='relu')(x)
x = Dropout(0.5)(x)
x = BatchNormalization()(x)
predictions = Dense(num_classes, activation = 'softmax')(x)
```
correct one is 

```
x = Flatten()(base_model.output)
x = Dense(4096, activation='relu')(x)
x = Dropout(0.5)(x)
x = Dense(4096, activation='relu')(x)
x = Dropout(0.5)(x)
x = BatchNormalization()(x)
predictions = Dense(NB_CLASSES, activation = 'softmax')(x)
```

**Comment by kratzert** [comment]
You are right but missed the point of my comment (or I didn't make it so clear). It's not about the correct top of the VGG16 network, but how you are able to use the base as feature extractor and put on top what ever you want. I can be similar in structure to the original VGG16 top, but in principle you can put what ever you want.

**Comment by vladimircape** [comment]
@kratzert. Thank for you solution:). I used your solution, just was surprised why accuracy is soo low, until add these.

**Comment by pkmandke** [comment]
> Okay @Vijethbv, first of all the error that is raised is due to a misspelling. It's `model.layers` with an **s** at the end. But this will not solve your problem.
> 
> If you look carefully at the [documentation](https://keras.io/applications/#vgg16) you can just load the model with `include_top = False`. This will automatically instantiate the vgg16 model without the dense layers at the top. If you want to initialize the rest with the imagenet weights, just add `weights = 'imagenet'` to the function call
> 
> E.g.
> 
> ```
> from keras.applications.vgg16 import VGG16
> from keras.models import Model
> from keras.layers import Flatten, Dense, Dropout
> from keras.layers.normalization import BatchNormalization
> 
> #load vgg16 without dense layer and with theano dim ordering
> base_model = VGG16(weights = 'imagenet', include_top = False, input_shape = (3,224,224))
> 
> #number of classes in your dataset e.g. 20
> num_classes = 20
> 
> x = Flatten()(base_model.output)
> x = Dense(4096, activation='relu')(x)
> x = Dropout(0.5)(x)
> x = BatchNormalization()(x)
> predictions = Dense(num_classes, activation = 'softmax')(x)
> 
> #create graph of your new model
> head_model = Model(input = base_model.input, output = predictions)
> 
> #compile the model
> head_model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
> 
> head_model.summary()
> .
> .
> .
> #train your model on data
> head_model.fit(x, y, batch_size = batch_size, verbose = 1)
> ```
> There are quite a lot of tutorials out there for fine-tuning vgg16 with keras. Maybe you should check out the deep learning course by Jeremy Howard and Rachel Thomas as they do quite a lot of fine tuning on vgg16 and they have pretty nice jupyter notebooks on everything. Just search for fast.ai

@kratzert  I'm trying to add a layer on top of MobileNetV2. After compiling the new model, I'm getting the following error on model.summary()

```
new_model.summary()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/coesip/venv/py3tflow-gpu/lib/python3.6/site-packages/keras/engine/network.py", line 1252, in summary
    'This model has not yet been built. '
ValueError: This model has not yet been built. Build the model first by calling build() or calling fit() with some data. Or specify input_shape or batch_input_shape in the first layer for automatic build.
```

Here is my code:

```

base_model = keras.applications.mobilenet_v2.MobileNetV2(input_shape=(96, 96, 3), alpha=1.0, include_top=False, weights='imagenet', pooling='avg')

base_model.summary() #works

x = Dense(128, activation='linear')(base_model.output)

from keras.models import Model

new_model = Model(base_model.input, x,'my-model')new_model.compile(loss='mean_squared_error', optimizer='sgd')

new_model.summary()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/coesip/venv/py3tflow-gpu/lib/python3.6/site-packages/keras/engine/network.py", line 1252, in summary
    'This model has not yet been built. '
ValueError: This model has not yet been built. Build the model first by calling build() or calling fit() with some data. Or specify input_shape or batch_input_shape in the first layer for automatic build.
```

Anything I'm missing?

**Comment by DSOCT18** [comment]
great you helped me a lot.
But one thing is i am not able to add Dropout layer 
it is giving an error:
AttributeError: 'Node' object has no attribute 'output_masks'

**Comment by copperwire** [comment]
@DSOCT18  I belive you should ask that question over on stack-overflow, but: 
#10907 might have the answer you're looking for.
