### ISSUE TITLE
max mode can not be used in merge function ? Why ?

### ISSUE THREAD

**Issue by bojone** [fchollet/keras#3486]
merge, Not Merge

> > > merge([forwards, backwards], mode='max')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/job/analyse/env/lib/python2.7/site-packages/keras/engine/topology.py", line 1490, in merge
> > >     name=name)
> > >   File "/home/job/analyse/env/lib/python2.7/site-packages/keras/engine/topology.py", line 1148, in **init**
> > >     self.add_inbound_node(layers, node_indices, tensor_indices)
> > >   File "/home/job/analyse/env/lib/python2.7/site-packages/keras/engine/topology.py", line 543, in add_inbound_node
> > >     Node.create_node(self, inbound_layers, node_indices, tensor_indices)
> > >   File "/home/job/analyse/env/lib/python2.7/site-packages/keras/engine/topology.py", line 154, in create_node
> > >     output_masks = to_list(outbound_layer.compute_mask(input_tensors, input_masks))
> > >   File "/home/job/analyse/env/lib/python2.7/site-packages/keras/engine/topology.py", line 1372, in compute_mask
> > >     raise Exception('Invalid merge mode: {}'.format(self.mode))
> > > Exception: Invalid merge mode: max

**Comment by daniilsorokin** [comment]
It seems that the "max" operation for merge is not supported if you mask the inputs. The support for "max" operation in Merge (#3128) was added after the support for masking (#2413) and it was apparently forgotten to add "max" to the "compute_mask" method of Merge.
