### ISSUE TITLE
Fully convolutional autoencoder for variable-sized images

### ISSUE THREAD

**Issue by izikgo** [fchollet/keras#3489]
I want to build a convolutional autoencoder where the size of the input in not constant. I'm doing that by stacking up conv-pool layers until I reach an encoding layer, and then doing the reverse with upsample-conv layers. the problem is that no matter what settings I use, I can't get the exact same size in the output layer as the input layer. The reason for that is that the UpSampling layer (given say (2,2) size), doubles the size of the input, so I can't get odd dimensions for instance. Is there a way to tie the output dimension of a given layer to the input dimension of a previous layer for individual samples (as I said, the input size for the max-pool layer in variable)?

**Comment by jswoodbridge** [comment]
I ran in to the same problem, but I fixed by rescaling the input image.  I'm wondering if rescaling the image so that pooling and up sampling layers will always match in size is the *proper* way to fix this issue, or if there is some other technique?

**Comment by chaltik** [comment]
Just ran into this problem. Curious if either of you found a good solution. Rescaling, if I understand it correctly, could be one, but what gives me pause is that it would have to be dependent on the exact network details (at the minimum, all upsampling layers parameters). What about padding the edges with some constant values?

**Comment by nimpy** [comment]
I have the same problem. Rescaling is not a (great) option for me.    

I am thinking of using an asymmetrical autoencoder (encoder and decoder having different architecture). Has anyone had (good) experience with this?

**Comment by izikgo** [comment]
I think that not using upsample/pooling layers is the best bet here. Strided convolutions and deconvolutions will probably work better and the parameters to corresponding layers can be better aligned
