### ISSUE TITLE
Different mask value than zero in seq2seq model

### ISSUE THREAD

**Issue by shashankg7** [fchollet/keras#3490]
I am trying to implement seq2seq model using keras. Now since the input and output sequence is of variable length I am padding both of them with a special token ("<s"). Now I want to mask these padded values, I am using the following model :

model = Sequential()
model.add(Masking(mask_value=vocab["<s"], input_shape=(inp_len, inp_dim)))
model.add(Embedding(inp_len, inp_dim))
model.add(RNN(hid_dim, return_sequence=True))
model.add(RepeatVector(out_len))
model.add(RNN(hid_dim, return_sequence=True))
model.add(TimeDistributed(Dense(out_size))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', 
                        metrics=['accuracy'])

When I run this model I am getting following error:

TypeError: index must be intergers in the embedding layer

**Comment by farizrahman4u** [comment]
Set your stop symbol as the 0th item in your vocab, get rid of the Masking layer, and set mask_zero arg of Embedding layer to True.
