### ISSUE TITLE
fit_generator is ignoring ValueErrors from generators

### ISSUE THREAD

**Issue by fredtcaroli** [fchollet/keras#3493]
As seen [here](/fchollet/keras/blob/master/keras/engine/training.py#L425), Keras just ignores ValueErrors raised by a generator.
```python
                        try:
                            generator_output = next(generator)
                        except ValueError:
                            continue
```
Is it for thread safety? If it is, then I think a thread safe wrapper would be a better approach (see [this post](http://anandology.com/blog/using-iterators-and-generators/) about the subject). I just spent 1 hour trying to track down a bug because Keras was intercepting my exceptions.

**Comment by fchollet** [comment]
Yes, it is for thread safety. If you'd like to fix it, please open a PR.
