### ISSUE TITLE
Race condition when loading keras config JSON file.

### ISSUE THREAD

**Issue by bryan-lunt** [fchollet/keras#3498]
These lines read the keras JSON config file, if it exists.
Then they unconditionally write back the same keras JSON config file.

https://github.com/fchollet/keras/blob/master/keras/backend/__init__.py#L27-L50

If there are multiple python kernels reading/writing the same config file at once, a race condition is created, and some jobs will throw an exception. This can happen in a cluster environment where the `keras.json` file is shared via NFS, or on shared memory machines starting multiple processes at once.

My suggestion is to make writing the file `keras.json` conditional on that file's non-existence. This will at least mean that the race condition only happens the first time keras is used in an installation. A more complicated idea would write to a temporary file and then use `shutil` to move that temporary file, gaining a certain kind of atomic writing. However, just making the writing code conditional will eliminate most instances of this problem.

>File "/home/my_username/.local/lib/python2.7/site-packages/keras/__init__.py", line 2, in <module>
>    from . import backend
>  File "/home/my_username/.local/lib/python2.7/site-packages/keras/backend/__init__.py", line 26, in <module>
>    _config = json.load(open(_config_path))
>  File "/my/python/installation/python/lib/python2.7/json/__init__.py", line 290, in load
>    **kw)
>  File "/my/python/installation/python/lib/python2.7/json/__init__.py", line 338, in loads
>    return _default_decoder.decode(s)
>  File "/my/python/installation/python/lib/python2.7/json/decoder.py", line 366, in decode
>    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>  File "/my/python/installation/python/lib/python2.7/json/decoder.py", line 384, in raw_decode
>    raise ValueError("No JSON object could be decoded")
>ValueError: No JSON object could be decoded

**Comment by bryan-lunt** [comment]
Additionally... I know that I should have read the backtrace more carefully from the beginning, but it seems like people might confuse this with an error in loading the JSON that defines a model. Perhaps some exception handling in the part that reads the config file could make it clear that that is where the failure lies.

**Comment by fchollet** [comment]
I resolved this.

**Comment by ksze** [comment]
For reference, the fix is this commit https://github.com/fchollet/keras/commit/a4d191d4f97a8100a561b87802fdd6ab5db0ed26
