### ISSUE TITLE
Rename Deconvolution2D to TransposedConvolution2D etc?

### ISSUE THREAD

**Issue by carlthome** [fchollet/keras#3502]
Considering is has nothing to do with deconvolution (see https://en.wikipedia.org/wiki/Deconvolution) and how TensorFlow now is calling "deconvolution" transposed convolution (https://www.tensorflow.org/versions/r0.10/api_docs/python/nn.html#conv2d_transpose) shouldn't the DeconvolutionND layers in Keras be renamed to TransposedConvolutionND or similarly? It's very confusing.

**Comment by sangaline** [comment]
The layers are now named `ConvNDTranspose` so this issue should probably be closed.

**Comment by carlthome** [comment]
Good! Thanks for letting me know.
