### ISSUE TITLE
Make the tensor board logging more obvious in the docs

### ISSUE THREAD

**Issue by camrongodbout** [fchollet/keras#3504]
Just found that Keras supports Tensor Board deep under call backs. I feel that this is an important feature that should be more obvious in the docs.

**Comment by MartinThoma** [comment]
You mean https://keras.io/callbacks/#tensorboard with "deep under call backs", right? How do you think it should be made more obvious?

**Comment by camrongodbout** [comment]
I feel like it is not obvious that keras supports tensorboard out of the box. 

I suggest adding tensorboard as it's own page under keras.io with instructions. 

I understand it is a callback and where it fits into the current site but it is such an important feature that I feel like it should be much more prominent in documentation.
