### ISSUE TITLE
Permuting 3D tensors causes "You cannot drop a non-broadcastable dimension." error

### ISSUE THREAD

**Issue by PiranjaF** [fchollet/keras#3507]
The Keras website has this simple example for using the Permute layer:

```
model = Sequential()
model.add(Permute((2, 1), input_shape=(10, 64)))
# now: model.output_shape == (None, 64, 10)
# note: `None` is the batch dimension
```

The issue is that I want to permute tensors of higher dimensionality (i.e. 3D tensors or 4D tensors). For instance, this is useful when connecting convolutional layers to recurrent layers in a specific type of architecture I'm investigating. However, if I try to permute a 3D tensor I get the following error:

`ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False, False, False), (0, 2, 1)))`

This issue can be reproduced with the following code:

```
model = Sequential()
model.add(Permute((2, 1), input_shape=(10, 64, 20)))
```

Does anyone have an idea how I can fix this issue?

**Comment by farizrahman4u** [comment]
```python
model.add(Permute((2, 1, 3), input_shape=(10, 64, 20)))
```

**Comment by farizrahman4u** [comment]
And if its your first layer, why not do it once on your training data in numpy world instead of doing it for every batch in Keras?

**Comment by PiranjaF** [comment]
This is not my first layer - that was just to keep the example simple. Thanks though! I thought the Permute layer would simply swap those 2 dimensions, but know I understand the way it works.
