### ISSUE TITLE
Question about mnist siamese example

### ISSUE THREAD

**Issue by maxbry** [fchollet/keras#3510]
In the mnist siamese example, two mnist images are mapped onto a vector. The two vectors are merged using euclidian distance. The distance should be low if the images belong to the same number and be high if the two images represent different images.

Questions: In line 59, the labels are set for positive and negative examples. If the euclidian distance for the same numbers should be low, why is the target 1 and why is it 0 for the negative examples? Also, the vectors are created using relu which normally does not have a max_value. How is the euclidian distance kept between 0 and 1?

**Comment by dolaameng** [comment]
There is a `margin` in `contrastive_loss` implementation and `K.maximum(margin - y_pred, 0)` remains positive even when `y_pred` is larger than `margin`.

Intuitively the whole expression `K.mean(y_true * K.square(y_pred) + (1 - y_true) * K.square(K.maximum(margin - y_pred, 0)))` means you want `y_pred` to be close to 0 when `y_true` is 1 (for positive pairs) and `y_pred` close or bigger than 1 when `y_true` is 0 (for negative pairs).
