### ISSUE TITLE
Error while running variational_autoencoder_deconv.py example on TensorFlow

### ISSUE THREAD

**Issue by lukovkin** [fchollet/keras#3513]
Tried to run https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder_deconv.py as is.

Got exception in the generation part (on Keras 1.0.7 and TF 0.10.0rc0):

> InvalidArgumentError: Conv2DSlowBackpropInput: input and out_backprop must have the same batch size
>      [[Node: conv2d_transpose_1 = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](conv2d_transpose_1/output_shape, transpose_9, transpose_7)]]

Full trace - https://gist.github.com/lukovkin/d2619674bb03f7bf3e161d4e1c6dab81.

Works just fine on Theano 8.2.

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by pwaller** [comment]
I have also hit this.

**Comment by kureta** [comment]
Did you resolve this?

**Comment by MicBA** [comment]
anyone? similar  problem here

**Comment by pwaller** [comment]
I can confirm that the example currently works. TF 1.2, keras 2.0.5. I think this issue can be closed.

**Comment by liyunfei1994** [comment]
Did anybody resolve this problem? I met the same problem!
Invalid argument: Conv2DSlowBackpropInput: input and out_backprop must have the same batch size
input batch: 64 outbackprop batch: 56 batch_dim: 0
