### ISSUE TITLE
Using advanced_activations in functional API

### ISSUE THREAD

**Issue by MAGPC** [fchollet/keras#3523]
I have been working using the functional API to design a convolutional neural network which is perfectly working with a normal ReLU activation.

Nevertheless, whenever I define an advanced activation layer it outputs the following error
layer = Act()(layer)
TypeError: __call__() takes at least 2 arguments (1 given)

The layer is defined as:
Act = advanced_activations.PReLU(init='zero', weights=None)

and just added as a layer after each convolution layer which I chose to have such an activation, for example
layer = convolutional.Convolution2D(32,3,3,init='glorot_normal')(layer)
layer = Act()(layer)

Is there some solution I can implement?

**Comment by farizrahman4u** [comment]
layer = Act(layer)

**Comment by MAGPC** [comment]
Thank you very much. It worked.

I was just following Fchollet's reply here
https://www.reddit.com/r/MachineLearning/comments/4lslgw/keras_question_how_do_you_use_the_advanced/
so may be adding this to the documentations or the examples of Keras can be very helpful.

**Comment by farizrahman4u** [comment]
There is nothing to add anything to the documentation here. 
You have already declared Act as:
```python
Act = PReLU()
```
So you replace `layer = PReLU()(layer)` with `layer = Act(layer)`, not `layer = Act()(layer)`.
