### ISSUE TITLE
Error saving model with advanced activation layers

### ISSUE THREAD

**Issue by kl2792** [fchollet/keras#3530]
Hi,

I'm trying to implement an easy method for cloning a model for cross validation; what I've found is that `model_from_json(model.to_json())` is the easiest way. However, this doesn't work with advanced activation layers.

``` python
# ... all required imports, etc.
# I wrote the function build to create and compile a Keras model
net = build(layers=[
     Dense(2500, input_dim = 6380),
     BatchNormalization(),
     PReLU(),
     Dropout(0.2),

     Dense(500),
     BatchNormalization(),
     Activation('sigmoid'),
     Dropout(0.2),

     Dense(100),
     BatchNormalization(),
     Activation(ParametricSoftplus()),
     Dropout(0.2),

     Dense(2),
     Activation('softmax')
], optimizer='nadam', loss='use')


json = model.to_json()
# throws AttributeError: 'ParametricSoftplus' object has no attribute '__name__'
model_from_json(json)
```

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by kemaswill** [comment]
Please provide your original code, this code cannot be ran, since there is some undeclared and unused variables such as ```model``` and ```net```

**Comment by kl2792** [comment]
So sorry about the trouble. I recently realized that the error was when I wrote `Activation(ParametricSoftplus())`; when I changed it to just `ParametricSoftplus()`, I could save the model.

Strangely enough, my neural net was still running just fine with `Activation(ParametricSoftplus())` as a layer.
