### ISSUE TITLE
How to visualize the output of an intermediate layer when the model have multiple input?

### ISSUE THREAD

**Issue by lqj1990** [fchollet/keras#3531]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by abishekk92** [comment]
I am afraid, I don't fully understand what you mean by multiple inputs. If you're simply looking at getting the output of the intermediate layer, you can take a look at this. 
https://keras.io/getting-started/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer

**Comment by stillbreeze** [comment]
@lqj1990 : Did you manage to get your answer? Could you please post it here.

**Comment by lqj1990** [comment]
@stillbreeze If you have multiple input， you can see the order of your input layer when you use model.summary() to print the structure of your network. Then you just need to pick up the order number of the input layer and use them in your code. 

Let's suppose your input layer is the first and third layer, then you can use the code
`get_3rd_layer_output = K.function([model.layers[0].input, model.layers[2].input, K.learning_phase()],
                                  [model.layers[3].output])`
to get the intermediate layers output.

I hope I had make it clear. (●'◡'●)

**Comment by stillbreeze** [comment]
Thanks a lot!
I actually figured out that for my use case, with the new functional API, I could simply write:
`model = Model(input=[input1, input2], output=[intermediate_layer,  intermediate_layer2])`

Thanks for the reply anyway!

**Comment by anewlearner** [comment]
@stillbreeze @lqj1990 
I still have some problems with this question. Could you please help me to figure it out.
 I want to get the output of a merge layer.
The network defined is as follows:
```
#each single_model has it own input
merged = Merge([sigle_model0, sigle_model1, sigle_model2,
                sigle_model3, sigle_model4, sigle_model5,
                sigle_model6, sigle_model7, sigle_model8],
                mode='concat')
model = Sequential()
model.add(merged)
model.add(Dropout(0.5))
model.add(Dense(nb_classes, activation='softmax'))
```
To get the value of the merge layer in the test set
```
from keras import backend as K
get_0rd_layer_output = K.function([[model.input_layers[kk].input for kk in range(9)], K.learning_phase()], [model.layers[0].output])
activations=get_2rd_layer_output([[test0, test1, test2, test3, test4, test5, test6, test7, test8], 0])
```
The error I got is: "TypeError: Invalid input syntax: [convolution2d_input_11, convolution2d_input_12, convolution2d_input_13, convolution2d_input_14, convolution2d_input_15, convolution2d_input_16, convolution2d_input_17, convolution2d_input_18, convolution2d_input_19] (check documentation or use an In instance)".

There was no error in the input data, because I could get the predection by 
`prediction = model.predict([test0, test1, test2, test3, test4, test5, test6, test7, test8])`

Hope someone could help. Thanks.

**Comment by anujshah1003** [comment]
@stillbreeze
where did you made the changes. i have two model which are concatenated in the last layers . how can i get intermediate ourputs

**Comment by philipperemy** [comment]
More generally you can visualise the output/activations of every layer of your model. I wrote an example with MNIST to show how here:

https://github.com/philipperemy/keras-visualize-activations

So far it's the less painful I've seen.
