### ISSUE TITLE
Weights init. without a name ERROR

### ISSUE THREAD

**Issue by shiretzet** [fchollet/keras#3533]
The following error did not occurred before Theano and Keras update (last week) from master.

I've built a costume LSTM layer that worked fine... after the update the following error happened:
1. Weights are initiated like:

``` python
self.W_iof = self.init(self.Shape)
```

 the rest are similar
3. Error happened in the next line (keras/.../training.py, 259) : 

``` python
weights.sort(key=lambda x: x.name)
```

ERROR:

``` python
TypeError: unorderable types: NoneType() < NoneType()
```

After adding names to weights it was fine.

Please change something, like adding default names or remove that sort (why?)

**Comment by kemaswill** [comment]
It would be appreciated that you provide the code you use so that we can help debug quickly.

**Comment by shiretzet** [comment]
As mentioned, if you initiate weight/variable without a name, the following error will occur.
Two solutions:
1) add a default name
2) remove the weights sort in training.py, why do you need that?
