### ISSUE TITLE
Parallel Processing of Graph Architecture

### ISSUE THREAD

**Issue by karanahujax** [fchollet/keras#3537]
Does keras execute the different branches in a graph in parallel? Take for example the Siamese architecture in the example "https://github.com/fchollet/keras/blob/master/examples/mnist_siamese_graph.py". Are the two inputs processed by the model in parallel or sequentially one after the other?

**Comment by shashankg7** [comment]
Each network is processed serially, parallelization is internal to network. As of now keras does not supports this kind of parallelism.
