### ISSUE TITLE
Masking sequences without masked input layer

### ISSUE THREAD

**Issue by beka-evature** [fchollet/keras#355]
I can't figure out how to supply a masked output to an RNN layer, without using the Embeddings layer before it.

Say I have X of shape (1000, len, 500), how to I pad the len dimension correctly, and make SimpleRNN (or LSTM or GRU) understand that this is only padding? If this is the first layer there is no such way... Am i write?

**Comment by simonhughes22** [comment]
You have to right some simple code to pad with a np.zeros(500) vectors or [0] * 500 if you are using a list.

**Comment by melonista** [comment]
But, for example in the code of the LSTM I see:

"(nb_samples, max_sample_length (samples shorter than this are padded with zeros at the end), input_dim)"

Then I see the following line:  "padded_mask = self.get_padded_shuffled_mask(train, X, pad=1)", and then the padded_mask is passed to the step function. 

Therefore, doesn't (at least) the LSTM have automatic masking? However I haven't been able to make it work, whenever I try to input sequences with different lengths I get an error (TypeError: only integer arrays with one element can be converted to an index).

**Comment by beka-evature** [comment]
It didn't worked for me either, although I padded my data from (1000, variable-len, 500) to maxlen (1000, 20, 5000). I think the reason it happens is because inside get_padded_shuffled_mask we have these lines:
```python
mask = self.get_input_mask(train)
if mask is None:
    mask = T.ones_like(X.sum(axis=-1))
```
Because I don't have any layer with output mask before the LSTM, `mask.get_input_mask(train)` returns None, and then I we get to `T.ones_like(X.sum(axis=-1))`:
`X.sum(axis=-1)` returns a matrix of the shape (nb_samples, max_seq_len), where there are non-zeros on all non-padded timesteps, and 0 on padding timesteps, but `T.ones_like` doesn't take this into account, so it's not helping.

So, if I'm getting it right (I'm kind of debugging it with you interactively), all we need to do is create the tensor `T.shared(X.sum(axis=-1) != 0)` instead.

I'm gonna try it and see how it goes

**Comment by amitbeka** [comment]
I'm not totally sure it's working, I get strange results..

**Comment by melonista** [comment]
@beka-evature But, if you pad your data before actually inputing it to the model, then it is impossible for the library to extract the mask, right? I mean, it cannot know which are real zeros in your data and which are zeros introduced in the padding operation. Or I am getting something wrong?

@amitbeka I tried the following snippet with the new version and still fails, I guess I am doing something wrong. I just generate three sequences of different length (type list) and use them as input for the LSTM.

```
ls = [2,5,7]
X_sequences = []
Y_sequences = []
for l in ls:
    xx = []
    yy = []
    for i in range(l):
        xx.append([i])
        yy.append([i+1])
    X_sequences.append(xx)
    Y_sequences.append(yy)
    
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers.recurrent import LSTM

model = Sequential()
model.add(LSTM(1, 5, return_sequences=True))
model.add(Dense(5, 1))

model.compile(loss='mse', optimizer='rmsprop')

model.fit(X_sequences, Y_sequences, batch_size=3, nb_epoch=10)
```

What am I doing wrong?

**Comment by amitbeka** [comment]
I am the same person as @beka-evature :)

What I was thinking about, is that you pad your data before actually providing it to the model, then if a timestep is all-zeores then it is assumed to be padding. I now see that we had different views in mind:

1) I assumed the inputs (X, y) are two matrices, and their timesteps axis (1) should be padded with zeroes (in X) and any value (in y, because we understand it's padding from X). I assumed X and y must be matrices, hence muse be padded before the model

2) You say that the inputs may be list of lists of numpy arrays, so you can supply different length lists, and then the model pads these lists until it gets a matrix.

My patch made the first assumption, and I haven't tried the second. This is what the models currently support?

**Comment by melonista** [comment]
Oh I see.

I thought they were able to do this automatic padding because I read in the LSTM section of the docs that:

```
Eats inputs with shape:
(nb_samples, max_sample_length (samples shorter than this are padded with zeros at the end), input_dim)
```

I will take a look to the code, but I guess I was wrong and the padding has to be made manually before inputing the data to the model.

**Comment by beka-evature** [comment]
I tested your script with the current master, and indeed we must pad the sequences before getting them to `fit`.

This is the script I used (you can't use list of list of list as input):
```python
ls = [2,5,7]
X_sequences = []
Y_sequences = []
for l in ls:
    xx = []
    yy = []
    for i in range(l):
        xx.append([i])
        yy.append([i+1])
    X_sequences.append(xx)
    Y_sequences.append(yy)

from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers.recurrent import LSTM

model = Sequential()
model.add(LSTM(1, 5, return_sequences=True))
model.add(Dense(5, 1))

model.compile(loss='mse', optimizer='rmsprop')

model.fit(X_sequences, Y_sequences, batch_size=3, nb_epoch=10)
```

And the output -- can't use list of 2-d matrices, must use a 3-d matrix, so all lengths must be the same:

```
[array([0, 1]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4, 5, 6])]
[array([1, 2]), array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6, 7])]
/home/beka/.local/lib/python2.7/site-packages/theano/scan_module/scan_perform_ext.py:134: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *
Epoch 0
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model.fit(X_sequences, Y_sequences, batch_size=3, nb_epoch=10)
  File "/home/beka/dev/keras/keras/models.py", line 371, in fit
    validation_split=validation_split, val_f=val_f, val_ins=val_ins, shuffle=shuffle, metrics=metrics)
  File "/home/beka/dev/keras/keras/models.py", line 135, in _fit
    outs = f(*ins_batch)
  File "/home/beka/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 531, in __call__
    allow_downcast=s.allow_downcast)
  File "/home/beka/.local/lib/python2.7/site-packages/theano/tensor/type.py", line 168, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/home/beka/dev/keras/keras/models.py:286"  at index 0(0-based)', 'Wrong number of dimensions: expected 3, got 1 with shape (2,).')
```

One option is to implement an `mask_zero` option which implicitly masks out input samples of all-zeroes, or implement a PaddingLayer which will get as input a list of (n-1)-d matrices (and targets) and outputs a nd-matrix and sets an output mask, which all layers know how to read and handle already.

**Comment by amitbeka** [comment]
I tested your script with the current master, and indeed we must pad the sequences before getting them to `fit`.

This is the script I used (you can't use list of list of list as input):
```python
ls = [2,5,7]
X_sequences = []
Y_sequences = []
for l in ls:
    xx = []
    yy = []
    for i in range(l):
        xx.append([i])
        yy.append([i+1])
    X_sequences.append(xx)
    Y_sequences.append(yy)

from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.layers.recurrent import LSTM

model = Sequential()
model.add(LSTM(1, 5, return_sequences=True))
model.add(Dense(5, 1))

model.compile(loss='mse', optimizer='rmsprop')

model.fit(X_sequences, Y_sequences, batch_size=3, nb_epoch=10)
```

And the output -- can't use list of 2-d matrices, must use a 3-d matrix, so all lengths must be the same:

```
[array([0, 1]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4, 5, 6])]
[array([1, 2]), array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6, 7])]
/home/beka/.local/lib/python2.7/site-packages/theano/scan_module/scan_perform_ext.py:134: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *
Epoch 0
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model.fit(X_sequences, Y_sequences, batch_size=3, nb_epoch=10)
  File "/home/beka/dev/keras/keras/models.py", line 371, in fit
    validation_split=validation_split, val_f=val_f, val_ins=val_ins, shuffle=shuffle, metrics=metrics)
  File "/home/beka/dev/keras/keras/models.py", line 135, in _fit
    outs = f(*ins_batch)
  File "/home/beka/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 531, in __call__
    allow_downcast=s.allow_downcast)
  File "/home/beka/.local/lib/python2.7/site-packages/theano/tensor/type.py", line 168, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/home/beka/dev/keras/keras/models.py:286"  at index 0(0-based)', 'Wrong number of dimensions: expected 3, got 1 with shape (2,).')
```

One option is to implement an `mask_zero` option which implicitly masks out input samples of all-zeroes, or implement a PaddingLayer which will get as input a list of (n-1)-d matrices (and targets) and outputs a nd-matrix and sets an output mask, which all layers know how to read and handle already.

**Comment by makagan** [comment]
Hopefully this is the correct thread, and this is not a dumb question...

I have floats as elements of my sequence which I don't actually want to embed (but I do want to have the masking functionality), so if use the embedding approach in order use to mask_zero (for instance with an identity init matrix), will it cast all of the non-masked floats to int's?

**Comment by amitbeka** [comment]
I'm still not sure what you're trying to do, but the masking doesn't cast floats to ints. What it does, is that for masked timesteps (in your case, single float numbers), it turns the hidden state to zero (=masking it out). I'm still not sure that everything works fine, but you can try it on your own sample data and see if it helps you.
