### ISSUE TITLE
Shared frozen model for joint training

### ISSUE THREAD

**Issue by glouppe** [fchollet/keras#3555]
Hi!

In <=0.3.3, I used to be able to define something like

```
D = Sequential()
D.add(...)
...

G = Sequential()
G.add(...)
...
G.compile(...) # necessary but irrelevant

DG = Sequential()
DG.add(G)  
D.trainable = False
DG.add(D) # layers of D are frozen for GD

D.compile(some_loss)
DG.compile(some_other_loss)
```

And then be able to train jointly `D` and `DG` (writing some small custom loop for alternating updates), such that updates on `DG` only change the weights of the inner model `G`. 

In master, the same code has different behaviour -- namely, `D.trainable = False` seems to no longer be taken into account, resulting in `DG.trainable_weights` to include both `G` and `D` weights. Is this new behaviour expected or this a bug?

**Comment by glouppe** [comment]
Maybe related to #3290

**Comment by fchollet** [comment]
If you set `D.trainable = False` then its weights won't be trained: https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L241-L243

**Comment by glouppe** [comment]
Indeed, but then why is `trainable_weights` including all of them? (this is the bit that is confusing me)

Also, where is `collect_trainable_weights` called? https://github.com/fchollet/keras/search?utf8=%E2%9C%93&q=collect_trainable_weights returns no match except the function definition itself.

**Comment by fchollet** [comment]
You are right that even though the training behavior is correct, the
trainable_weights list should be adjusted. I'll push a fix.

It's called here:
https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L693

**Comment by glouppe** [comment]
Great! Thanks Francois and sorry for the false alarm then. I am closing the issue. 

(and I was confusing by github showing only the top 2 results for the same file, sorry about that ;))
