### ISSUE TITLE
Connect Sequential Model and Functional API Model

### ISSUE THREAD

**Issue by shastakr** [fchollet/keras#3557]
I want to finetune resnet50 model.  But my data's label are just binary, so I have to adapt new full connected layer on top of resnet 50's convolutional layers.

Conceptually, my situation is like below,

```
model = ResNet50(include_top=False, weights='imagenet')  # Functional API 
top_model = TopModel(model.output_shape[1:])
top_model.load_weights("top_model.hdf5")
model.add(top_model)  # => AttributeError: 'Model' object has no attribute 'add'
```

My question is,

Is there **any easy way** to stack **'Sequential based' model** on **'Functional API based' model** ??

I mimic following codes.

- [deep-learning-models](https://github.com/fchollet/deep-learning-models)
- [Fine-tuning a Keras model](https://gist.github.com/fchollet/7eb39b44eb9e16e59632d25fb3119975)

**Comment by farizrahman4u** [comment]
Try replacing last line with:
```python
model = Model(model.input, top_model(model.output))
```

**Comment by farizrahman4u** [comment]
```python
model = ResNet50(include_top=False, weights='imagenet')  # Functional API 
top_model = TopModel(model.output_shape[1:])
top_model.load_weights("top_model.hdf5")
# Stack top_model on top
model = Model(model.input, top_model(model.output))
```

**Comment by shastakr** [comment]
Thanks for the great responses!
