### ISSUE TITLE
mnist_cnn.py: couldn't reach 99.25% test accuracy

### ISSUE THREAD

**Issue by icewater96** [fchollet/keras#3563]
I  copied the code o mnist_cnn.py exactly except that modified the print lines to be compatible with Python 2.7. The np.random.seed(1337) was kept as well for reproducibility. However, I can only get 98.78%. Any clues why I couldn't reach 99.25% test accuracy?

**Comment by shackenberg** [comment]
Same here. Using following versions installed via pip on an AWS P2 instance with ubuntu 16.04:
```keras==1.2.2
tensorflow==1.0.0```

**Comment by shackenberg** [comment]
I just tried with Theano (CPU) and got also ~98,88% again. 
```
keras==1.2.0
theano==0.8.2
```
both runs with CUDA 8 and cudnn 5.1
