### ISSUE TITLE
Modify the L1/L2 weight regularization penalty during the training procedure

### ISSUE THREAD

**Issue by nixingyang** [fchollet/keras#3574]
Hi,
I need to modify the L1/L2 weight regularization penalty during the training procedure. As defined [here](https://github.com/fchollet/keras/blob/08014eea360fd8d66b7baab19cdb9335f52c167b/keras/regularizers.py#L61-L62), it should be useless to modify these values without recompile the model itself. Could I change 
```python
self.l1 = K.cast_to_floatx(l1)
```
to
```python
self.l1 = K.variable(l1)
```
to make it work?
Best Regards.

**Comment by jskDr** [comment]
I think so: not working and no much usefulness at this moment. For my curiosity, why do you want to change it? Once it is changed, it will be not easy to apply for testing data in general? Do you think adaptive for a adaptive system, that is, over-the-air hyper parameter optimization for the given networks? 

--James

**Comment by jskDr** [comment]
Hi, nixingyang

I have a related question. Is regularization working well in your test regardless chasing L1/L2 parameter on the training period? To me, it never works. I get the following warning instead. Could you share some idea on this for me or people who have had the same message? 

/home/jamessungjinkim/anaconda3/lib/python3.5/site-packages/keras/backend/theano_backend.py:558: UserWarning: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 1 is not part of the computational graph needed to compute the outputs: keras_learning_phase.
To make this warning into an error, you can pass the parameter on_unused_input='raise' to theano.function. To disable it completely, use on_unused_input='ignore'.
  **kwargs)

--James

**Comment by nixingyang** [comment]
Hi @jskDr,
I am trying to replicate the work as described [here](http://torch.ch/blog/2015/11/13/gan.html). I need to train two models simultaneously and I want to modify the penalty coefficients throughout the training procedure. In this specific scenario, there is no validation/testing data set. To address this issue, I defined a new class as follows:
```python
class CustomizedWeightRegularizer(WeightRegularizer):
    def __init__(self, l1=0., l2=0.):
        self.l1 = K.variable(l1)
        self.l2 = K.variable(l2)
        self.uses_learning_phase = True
```
Afterwards, I called **get_value** and **set_value** to get and set the penalty coefficients. I have obtained expected results by using the aforementioned trick.
For the warning message you shared, I have not encountered similar problem. IMHO, the model should work just fine even if one modifies the penalty coefficients throughout the training procedure.
Best Regards.

**Comment by jskDr** [comment]
Hi, @nixingyang 
It is a good news to hear that your model is working. For my issue related to regularization of a dense layer, I share my corresponding codes on Gist. So, could you advice me further?
https://gist.github.com/jskDr/f3007817baf54f249e6138fbd384eeea

**Comment by nixingyang** [comment]
Hi @jskDr,
In your code, you are using the default class **l2** provided by Keras. You may try to change it to
```python
model.add(Dense(n_w_l, W_regularizer = CustomizedWeightRegularizer(l2=0.01)))
```
During the training procedure, you may change the value in those regularizers by using 
```python
model.regularizers[0].l2.set_value(0.005)
```
Best Regards.

**Comment by rh314** [comment]
@nixingyang

Worked like a charm, thanks!
PS: In my version of keras I needed to add a blank `p` property to make it work.

```
class CustomizedWeightRegularizer(WeightRegularizer):
    def __init__(self, l1=0., l2=0.):
        self.l1 = K.variable(l1)
        self.l2 = K.variable(l2)
        self.uses_learning_phase = True
        self.p = None
```
