### ISSUE TITLE
How to visualize hidden layers in Keras

### ISSUE THREAD

**Issue by hadim** [fchollet/keras#3583]
I have made a bunch of functions to visualize hidden layer (weights or feature maps) of a Keras model.

You can find the code here : https://gist.github.com/hadim/9fedb72b54eb3bc453362274cd347a6a

Would you be interested to integrate this kind of function in Keras ?

**Comment by hadim** [comment]
A couple of notes : 

- doesnt work with tensorflow backend
- only tested with one model (Conv + MNIST)

**Comment by jskDr** [comment]
Amazing. I have searched these kinds of functions to visualize important static and dynamic patterns in my scientific research for a long time. I will review your codes and try to apply them for my research and then, let you know if I found any points to improve it or share my experience with you during using your visualization tool. Some of them will be posted here with example codes sharing by Gist. 

--James

**Comment by hadim** [comment]
Glad to hear it can be useful.

The ideal thing would be to develop a Tensorboard like server to be able to dynamically explore a Keras model but before we get there such a set of functions are nice to have.

**Comment by jskDr** [comment]
Totally, I agree with your idea and approach. The investigation of weights including the first part in the networks is critical to understand in-depth mechanism of data and processing in many cases. Therefore, any tool whether it is based on Tensorboard or not is significantly beneficial for such purpose. 

--James

**Comment by hadim** [comment]
The functions are available in my keras toolbox : https://github.com/hadim/keras-toolbox

**Comment by varoudis** [comment]
@hadim check the code of aetros-cli you might find it useful to refactor.

great work btw!

**Comment by dandxy89** [comment]
Take a look at this interesting blog, might be slightly off topic though.

http://jacobcv.blogspot.co.uk/2016/08/class-activation-maps-in-keras.html?m=1

**Comment by mauhcs** [comment]
really cool. 

would this work for RNNs also?
