### ISSUE TITLE
Regularization is not working for the Dense layer

### ISSUE THREAD

**Issue by jskDr** [fchollet/keras#3584]
I added a weight regularization parameter in a dense layer. However, I got this warning. I understood that the warning indicates that regularization doesn't work while I add as one of parameters. Please advice me how to fid this issue? 

...anaconda3/lib/python3.5/site-packages/keras/backend/theano_backend.py:558: UserWarning: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 1 is not part of the computational graph needed to compute the outputs: keras_learning_phase.
To make this warning into an error, you can pass the parameter on_unused_input='raise' to theano.function. To disable it completely, use on_unused_input='ignore'.
  **kwargs)

--James

**Comment by fchollet** [comment]
Yes it is, and you can ignore this warning.
