### ISSUE TITLE
Large scale data training in keras, by parallel image preprocessing

### ISSUE THREAD

**Issue by shastakr** [fchollet/keras#3585]
I am already aware of some discussions on how to use Keras for large dataset like Imagenet such as [this](https://github.com/fchollet/keras/issues/1627), [this](https://github.com/fchollet/keras/issues/107) ... but it doesn't help my situation.

By `ImageDataGenerator`, I takes **0.3 sec** for **batch of 32 samples**. But my total training sample size is about **700,000** so one epoch takes almost **2 hours**! OTL.. I think this time is so long, It is impossible for training deep network such as ResNet.

In order to solve this problem, I found `fit_generator` and it has `nb_worker` options. So I understand `nb_worker` option as "I use `nb_worker=23` then 23 process run for preparing batches and other core is training model with GPU". So I use this option but there are no difference time for one epoch with `nb_worker=1` and `nb_worker=23`..

So I have two Questions
1. Why there are no improvement by `nb_worker` option? (by `ps aux | grep 'python run.py'` I checked that there are many process by `nb_worker`....)
2. And are there any tips for large scale Image training by Keras? I heard that in tensorflow, there are `tf.train.batch` methods and it really helps large scale training by parallel data preprocessing(but i do not test it yet.)

**Comment by parag2489** [comment]
Could you tell us the type of network you are using (e.g. AlexNet 8 layers, VGG-16, ResNet-18 etc.). I don't actually remember if I observed any significant improvement when I used `ImageDataGenerator`. However, when I loaded as much data into RAM as possible (I have 128 GB RAM), and trained using `fit`, I saw significant speedup. However, if you are using ImageNet, that won't be possible. However, you can load as much data into RAM as possible, and check the speedup first.

**Comment by KlaymenGC** [comment]
@shastakr I'm having the similar problem, I'm thinking about using the multiprocessing module in python to write a data generator, have you found a solution yet?

**Comment by kwotsin** [comment]
@shastakr Have you seen improvements from this method yet?

**Comment by kashif** [comment]
you also need to pass the `pickle_safe` parameter to `True`, making sure you do not pass non picklable arguments...

**Comment by FrancisYizhang** [comment]
Dear @shastakr 

  Did you solve the problem,  I writed thread safe function packed my data generator, and set workers as 12 and use_multiprocessing as True, but there is a error, Can't pickle local object 'GeneratorEnqueuer.start.<locals>.data_generator_task'.
