### ISSUE TITLE
Why does evaluate_generator does not have verbosity mode?

### ISSUE THREAD

**Issue by khalo-sa** [fchollet/keras#3588]
Hello guys,

while almost all other methods, particularly the fit_generator method, have verbosity mode that allows to monitor the progress of training/evaluation, evaluate_generator method does not. Why is that?

Best, Khalo

**Comment by pengpaiSH** [comment]
+1. I have the same confusion, so that I have to manually split my data into batches and use ```model.predict()``` function.
