### ISSUE TITLE
ask about h5py

### ISSUE THREAD

**Issue by pablozhang** [fchollet/keras#3594]
Hi,

I am not conformable with h5py, and I would like to use vgg16_weights.h5
In my code, I use  **weights_path = 'vgg16_weights.h5'** and **f = h5py.File(weights_path)** in my script using notepad++, but it does not work. 

However, when I use the two code above in my python environment， it can work. So how can I use h5py in my script? 

Thank you

**Comment by carlthome** [comment]
Please close this issue and ask the question here instead: https://groups.google.com/forum/#!forum/keras-users

**Comment by fchollet** [comment]
You need to properly install HDF5 and h5py.
