### ISSUE TITLE
Cannot use TimeDistributed with RNN on TensorFlow but it works on Theano

### ISSUE THREAD

**Issue by carlthome** [fchollet/keras#3596]
Training a model that works in Theano but not TensorFlow.

The exception

``` sh
File ".../tensorflow_backend.py", line 1129, in rnn raise Exception('No initial states provided.')
```

gets raised by the TensorFlow backend (an equivalent exception doesn't seem to exist in the Theano backend) and was caused by TimeDistributed having [this line](https://github.com/fchollet/keras/blob/master/keras/layers/wrappers.py#L121).

**Comment by carlthome** [comment]
For reference my particular model is:
```Python
x0, x1, x2, x3 = map(lambda x: Input(name=x, batch_shape=(sequences, timesteps, features)),
                     ['input0', 'input1', 'input2', 'input3'])
m = Masking(mask_value)(x0)
lstm = functools.partial(
    LSTM,
    output_dim=features,
    stateful=False,
    return_sequences=True,
    consume_less='gpu',
    unroll=False)
lstms = lstm()(lstm()(m))
d = functools.partial(Dense, output_dim=features, activation='sigmoid')
tdd1 = TimeDistributed(d())(lstms)
tdd2 = TimeDistributed(d())(lstms)
tfm = functools.partial(
    merge,
    mode=lambda x: x[0] * x[1] / (x[1] + x[2]) * K.cos(x[3] - x[4]),
    output_shape=lambda x: x[0])
y0 = tfm([x0, tdd1, tdd2, x2, x1])
y1 = tfm([x0, tdd2, tdd1, x3, x1])
model = Model([x0, x1, x2, x3], [y0, y1])
model.compile('rmsprop', 'mse')
```

**Comment by carlthome** [comment]
For reference, the particular model looks like:
```Python
x0, x1, x2, x3 = map(lambda x: Input(name=x, batch_shape=(sequences, timesteps, features)),
                     ['input0', 'input1', 'input2', 'input3'])
m = Masking(mask_value)(x0)
lstm = functools.partial(
    LSTM,
    output_dim=features,
    stateful=False,
    return_sequences=True,
    consume_less='gpu',
    unroll=False)
lstms = lstm()(lstm()(m))
d = functools.partial(Dense, output_dim=features, activation='sigmoid')
tdd1 = TimeDistributed(d())(lstms)
tdd2 = TimeDistributed(d())(lstms)
tfm = functools.partial(
    merge,
    mode=lambda x: x[0] * x[1] / (x[1] + x[2]) * K.cos(x[3] - x[4]),
    output_shape=lambda x: x[0])
y0 = tfm([x0, tdd1, tdd2, x2, x1])
y1 = tfm([x0, tdd2, tdd1, x3, x1])
model = Model([x0, x1, x2, x3], [y0, y1])
model.compile('rmsprop', 'mse')
```

**Comment by carlthome** [comment]
So I guess the problem stems from that initial_states in TimeDistributed for models with a fixed batch_size shouldn't be an empty list but rather an all-zero tensor like how it's done for RNNs?

**Comment by carlthome** [comment]
@fchollet, should this really be an empty list? https://github.com/fchollet/keras/blame/master/keras/layers/wrappers.py#L121

**Comment by carlthome** [comment]
@temporaer and @alex-j-j, are you having a similar issue?

**Comment by temporaer** [comment]
@carlthome yes. As a workaround, I set the batch size (first dimension of input to TimeDistributed) to `None` to fall into the `else` case of https://github.com/fchollet/keras/blame/master/keras/layers/wrappers.py#L124

**Comment by alex-j-j** [comment]
@carlthome yes. @temporaer 's workaround helps, so thank you for that :)

**Comment by Higgcz** [comment]
@temporaer 's workaround works if you're not using the stateful LSTMs, does anyone have an idea how to solve this for them?

My model is little bit more complicated, but it's getting stuck right on the first layer, which is `TimeDistributed(Convolution2D(...))`.

When I set the batch size to `None` the LSTM layer will throw an error because the batch size isn't setted. I've also tried to set `batch_input_shape` parameter for LSTM as well, but it's beeing ignored, because it isn't the first layer in the Sequential model.

**Comment by carlthome** [comment]
Yeah, I'm also using stateful LSTMs... Derp.

**Comment by carlthome** [comment]
Was this resolved by https://github.com/fchollet/keras/pull/3835 ?

**Comment by Higgcz** [comment]
@carlthome Yes, it was resolved, it should work just fine. At least my model is working properly.
