### ISSUE TITLE
How to add a mean pooling layer on the blstm model？

### ISSUE THREAD

**Issue by YFZX** [fchollet/keras#3597]
I want to set a mean pooling layer above the blstm layer,but i don't know, how to make it work
and shoud i add the mean pooling layer ahead of the merge layer or after it?
anyone can help me,please.

**Comment by carlthome** [comment]
Please close this issue and ask the question here instead: https://groups.google.com/forum/#!forum/keras-users

**Comment by YFZX** [comment]
fine,no reseponse.
