### ISSUE TITLE
Documentation is not full

### ISSUE THREAD

**Issue by justanothercoder** [fchollet/keras#3598]
Hello! 

I just wanted to say that [here](https://keras.io/models/sequential/) method `predict_generator` of the `Sequential` model is not listed. However it is available [here](https://github.com/fchollet/keras/blob/master/keras/models.py#L918) in the source code. Please, fix it. 

Thanks!

**Comment by kuza55** [comment]
@justanothercoder Be the change you want to see in the world, submit a pull request and improve open source for everyone!

**Comment by justanothercoder** [comment]
@kuza55, Okay, got it :)

**Comment by fchollet** [comment]
I'm on it, thanks for reporting. No need to PR.

**Comment by kuza55** [comment]
@fchollet I'm not sure what your attitude towards doc incompleteness is in general, but I also noticed the LocallyConnected layers were not in the docs and I ended up finding them while browsing the source.

**Comment by fchollet** [comment]
I've also fixed it in the most recent commit.
