### ISSUE TITLE
How to prevent it printing anything when I import keras

### ISSUE THREAD

**Issue by yuetianluo** [fchollet/keras#3614]
Now when I import keras, it will show
`Using Theano backend.
1 #define _CUDA_NDARRAY_C
2 
3 #include <Python.h>
4 #include <structmember.h>
5 #include "theano_mod_helper.h"
6 
7 #include <numpy/arrayobject.h>
8 #include <iostream>
9 
10 #include "cuda_ndarray.cuh"
11 
12 #ifndef CNMEM_DLLEXPORT
13 #define CNMEM_DLLEXPORT
14 #endif
15 
16 #include "cnmem.h"
17 #include "cnmem.cpp"
18 
19 //If true, when there is a gpu malloc or free error, we print the size of allocated memory on the device.
20 #define COMPUTE_GPU_MEM_USED 0
21 
22 //If true, we fill with NAN allocated device memory.
23 #define ALLOC_MEMSET 0
24 
25 //If true, we print out when we free a device pointer, uninitialize a
26 //CudaNdarray, or allocate a device pointer
27 #define PRINT_FREE_MALLOC 0
28 
29 //If true, we do error checking at the start of functions, to make sure there
30 //is not a pre-existing error when the function is called.
31 //You probably need to set the environment variable
32 //CUDA_LAUNCH_BLOCKING=1, and/or modify the CNDA_THREAD_SYNC
33 //preprocessor macro in cuda_ndarray.cuh
34 //if you want this to work.
35 #define PRECHECK_ERROR 0
...
...
`
I do not want it to be printed, because this log will be regarded as error in another program.
So, how can I do to prevent it from printing, including 'Using Theano backend.' 
Thank you ahead for your help!

**Comment by hadim** [comment]
What is the other program ? How can any output messages be seen as an error... this is so wrong.

Anyway if you are using Linux or OS X you can still use bash redirection : 

```bash
python train.py > /dev/null 2>&1
```

It will redirect both output and error messages to `/dev/null`.

**Comment by yuetianluo** [comment]
@hadim It is a node.js module called python-shell which aims to run python code on the server. I have put issues on https://github.com/extrabacon/python-shell/issues/52 and  https://github.com/extrabacon/python-shell/issues/53. I am not so familiar with the stderr and stdout he mentioned in https://github.com/extrabacon/python-shell/issues/52. Could you have a look at that? I would be really appreciated if you can help me! Thank you so much

**Comment by hadim** [comment]
Well you could use this solution http://stackoverflow.com/questions/11130156/suppress-stdout-stderr-print-from-python-functions

It's an hack but it should work for you.

**Comment by yuetianluo** [comment]
@hadim Thank you! It works now

**Comment by hadim** [comment]
Good.

Please close this issue.

**Comment by kbrose** [comment]
Interpreting a child program writing to `stderr` as an indication that something went wrong is a widely used pattern, and IMO nothing is really gained from doing so.
