### ISSUE TITLE
hierarchical rnn example with imdb data

### ISSUE THREAD

**Issue by ttthhh** [fchollet/keras#3618]
The mnist_hierarchical_rnn.py example mentions that

> HRNNs can learn across multiple levels of temporal hiearchy over a complex sequence.
> Usually, the first recurrent layer of an HRNN encodes a sentence (e.g. of word vectors)
> into a  sentence vector. The second recurrent layer then encodes a sequence of
> such vectors (encoded by the first layer) into a document vector. This
> document vector is considered to preserve both the word-level and
> sentence-level structure of the context.

Is there a code example demonstrating HRNN on text, such as the IMDB data?

**Comment by fchollet** [comment]
You could write one? That sounds pretty easy.

**Comment by ttthhh** [comment]
@fchollet How would you handle variable-length paragraphs? "Pad" the paragraphs with blank sentences to be equal-size [K sentences in each paragraph]? Or can than TimeDistributed wrapper take variable-length sequences [of sentences, that will be padded to equal length]?

**Comment by vinayakumarr** [comment]
I was trying hierarchical rnn but i am getting alsways shape error. Can you please tell how to implement it
