### ISSUE TITLE
Slow TimeDistributed(Dense) or merge

### ISSUE THREAD

**Issue by maxbry** [fchollet/keras#3627]
I have two networks, one with embedding input, one with matrix input:

```
input_emb = Input(shape=(input_len,), dtype='int32', name='input_emb')
input_mat = Input(shape=(input_len, mat), dtype='int32', name='input_mat')

emb = Embedding(input_shape=(max_len,), input_dim=input_dim_emb, output_dim=embedding_size)(input_emb)
mat = TimeDistributed(Dense(embedding_size))(input_mat)

com = merge([emb, mat], mode='sum', output_shape=(max_len, embedding_size))

gru = GRU(gru_dim, ...)(emb) # really fast
gru = GRU(gru_dim, ...)(com) # really slow
```

If I used my combined data, the network is really really slow. If I just remove the merge part, the network is really really fast. Why does using merge make the network so slow?

**Comment by farizrahman4u** [comment]
Its probably the TimeDistributed(Dense()). What is your maxlen and embedding size?

**Comment by maxbry** [comment]
For test reasons, I set `max_len = 1`. My `embedding_size` is `512`.

**Comment by Yevgeniyr1** [comment]
Why was this closed? I have a similar issue when working with 1D convs
