### ISSUE TITLE
Network trained on GPU gives different results in CPU

### ISSUE THREAD

**Issue by aasensio** [fchollet/keras#3633]
I trained a relatively standard convolutional neural network with Keras using Theano with a K40m GPU. The training goes well and I'm happy with the results. I then save the network topology with `model_to_json` and the weights with `save_weights` and read it from another computer without a GPU to do some applications for the network using `model.predict.` The results with the CPU are completely off and different from what I should get. I run the CPU version with the environment variables `device=cpu,floatX=float32` to make sure that the CPU is using 32 bits for the floating point numbers. My version of Keras is 1.0.8. Any indication of how to proceed to solve this issue?

**Comment by tokyoben** [comment]
if you are using cudaNN some of the convolution functions are non-deterministic

**Comment by aasensio** [comment]
I finally realized that the Keras version in the computer with the GPU was 1.0.7, while I was doing the prediction with the CPU in Keras 1.0.8. Apparently, there was a change in the saving/loading weights routines between the two versions, that made it incompatible. Anyway, thanks for pointing out the issue that cudaNN is non-deterministic.

**Comment by hainguyenct** [comment]
HI Aasensio, do you use which command to check version of keras GPU and keras CPU? 
I used "python -c 'import keras; print(keras.__version__)' but I think it only shows the version of keras GPU
