### ISSUE TITLE
RNN seems to be broken on Theano after commit 08014eea360fd8d66b7baab19cdb9335f52c167b

### ISSUE THREAD

**Issue by michael626** [fchollet/keras#3636]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

Please see error trace in the attached log. Ran the following in the examples folder:
python3 mnist_irnn.py

Specs:
3.13.0-32-generic #57-Ubuntu
GeForce GTX 980, Driver version 352.39
Cuda compilation tools, release 7.5, V7.5.17
cuDNN 5004

Started getting this error starting from the above-mentioned commit. The example works fine one commit prior.

[log.txt](https://github.com/fchollet/keras/files/446189/log.txt)

**Comment by fchollet** [comment]
Thanks for the report, I fixed it.
