### ISSUE TITLE
Reduction in accuracy when porting code to Keras

### ISSUE THREAD

**Issue by chrisruk** [fchollet/keras#3654]
I'm just wondering if anyone can see any obvious reason, why, when porting a CNN model from 
TFLearn to Keras, I would get a ~8% reduction in accuracy (I'm assuming I'm making a mistake somewhere in the ported code).   Any help would be much appreciated.

The same dataset is used for both implementations.
# TFLearn code

https://github.com/chrisruk/cnn/blob/master/train_cnn.py#L28

Prints:

```
SNR 18 ACC 0.947874306839
```
# Keras code

https://github.com/chrisruk/models/blob/master/cnn_generate.py#L267

Prints

```
SNR 18 Test accuracy: 0.860998151571
```

Cheers!

**Comment by kuza55** [comment]
Did you run it more than once? Weights are initialized randomly so there's always a chance of a shitty run.

Speaking of which, the weight/bias initialization seems different between TFLearn & Keras. Not sure if that explains this, but it's the only difference that popped out at me.
