### ISSUE TITLE
Not able to import Conv1D from from keras.layers

### ISSUE THREAD

**Issue by anirudhcoder** [fchollet/keras#3655]
I was following the example code from here: https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py

and it says:
from keras.layers import Conv1D
and I get "ImportError: cannot import name Conv1D"
When I went to https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L14
I realized that there wasn't a Conv1D and instead it was Convolution1D, so I am correct in assuming that it should be "from keras.layers import Convolution1D"

**Comment by fchollet** [comment]
Just update Keras.
