### ISSUE TITLE
neural_style_transfer example breaks after update

### ISSUE THREAD

**Issue by dolaameng** [fchollet/keras#3659]
With theano backend, example code breaks in [line 118](https://github.com/fchollet/keras/blob/master/examples/neural_style_transfer.py#L118) when loading VGG16 with an `input_tensor` argument,  after [commit](https://github.com/fchollet/keras/commit/f23f2ff2c96537274beb99aca8417f054f817501).

It traces back to [line 980 in `InputLayer.__init__`](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L980), where auto-infer of shape `K.int_shape` only works for `tf` but not for `th` backend.

However, changing line 980 to `batch_input_shape = K.get_variable_shape(input_tensor)` doesn't work either, because the [`input_tensor`](https://github.com/fchollet/keras/blob/master/examples/neural_style_transfer.py#L112)  in `neural_style_transfer` example is a `K.concatenate` of `K.variable` and `K.placeholder` - so the `th` version of [`get_variable_shape`](https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L648) doesn't work with this compound type either.

Any idea of how to fix this?

**Comment by fchollet** [comment]
Thanks for the report, I just fixed it.

**Comment by dolaameng** [comment]
Great it works! thanks!
