### ISSUE TITLE
Incorrect #params in summary when model embeds some of itself

### ISSUE THREAD

**Issue by yxonic** [fchollet/keras#3661]
Here is an example:

```
x = Input((10,))
layer = Dense(10)
y1 = layer(x)
model1 = Model(input=[x], output=y1)  # this is the model we want to reuse
y2 = model1(y1)  # now model1 is reused, and params should also be shared (right?)
model2 = Model(input=[x], output=y2)
model2.summary()
```

The output should have been 110, but the output here is 220. The summary counted layers inside model1 twice. 

Haven't thought of any bright ideas to solve this problem yet. If something comes up, I would like to code on this issue ;)

**Comment by fchollet** [comment]
You're right, this should be fixed. Please submit a PR. In essence we should check if some underlying layers in a model are models themselves (Model or Sequential), and take the union of the layer sets between the parent and the child.
