### ISSUE TITLE
ValueError caused by the BatchNormalization() layer

### ISSUE THREAD

**Issue by IssamLaradji** [fchollet/keras#3667]
Hi there!
Is there a way I could fix this error? it is caused by the **BatchNormalization()** layer..  

``ValueError: gamma and beta must be of the same dimensionality as inputs; got 1 
and 1 instead of 2``

It happens when I run the following code:

```python
main_model = Sequential()
main_model.add(Convolution2D(16, 10, 10, border_mode='valid', 
               input_shape=(3, img_rows, img_cols)))

main_model.add(Flatten())
main_model.add(Dense(128))
main_model.add(BatchNormalization())       
main_model.add(Activation('relu'))
main_model.add(Dense(2))
main_model.add(Activation('softmax'))

sgd = keras.optimizers.RMSprop()
main_model.compile(loss='categorical_crossentropy', optimizer = sgd)       
```

My machine configuration:
Operating system: openSuse
Theano version: '0.9.0dev2'
Keras version: 1.0.8
cuDNN version: v5.1
CUDA version: 7.5

Thanks!

**Comment by IssamLaradji** [comment]
It worked when I downgraded **Theano** to **0.8.2**.

**Comment by jmhessel** [comment]
I'm also getting this error on the newest theano/keras

**Comment by woozzu** [comment]
I just fixed the issue, see my pull request.
