### ISSUE TITLE
"featurewise_center = True" is not working for ImageDataGenerator::flow_from_directory()

### ISSUE THREAD

**Issue by kevinmtian** [fchollet/keras#3679]
Hello, 

I have been using fit_generator for classifying a large number of images which could not fit into memory. I used the [keras ImageDataGenerator](https://keras.io/preprocessing/image/) and followed [this simple example](https://gist.github.com/fchollet/0830affa1f7f19fd47b06d4cf89ed44d). The **only changes** I made to the [code](https://gist.github.com/fchollet/0830affa1f7f19fd47b06d4cf89ed44d) are:

```
# line 84 changed to
train_datagen = ImageDataGenerator(featurewise_center = True)
# line 92 changed to
test_datagen = ImageDataGenerator(featurewise_center = True)
```

As I just would like to remove from each image the mean pixel values across samples. However, I encountered an error below:

```
File "/home/ubuntu/anaconda/lib/python2.7/site-packages/keras/models.py", line 683, in fit_generator
    pickle_safe=pickle_safe)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/keras/engine/training.py", line 1419, in fit_generator
    'or (x, y). Found: ' + str(generator_output))
Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
```

After checking the [Source code](https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py), I found out that the member variable **self.mean = None** in class **ImageDataGenerator** (line 180) was used before being assigned a value in class **DirectoryIterator** (line 502). 

To be specific, here is the "pathway" in which **self.mean** is used: 
DirectoryIterator -> next() -> line 595:

```
x = self.image_data_generator.standardize(x)
```

and in ImageDataGenerator -> **standardize()** -> line 294:

```
if self.featurewise_center:
    x -= self.mean
```

But **self.mean** was not computed anywhere before being used. So I think the traceback above should be due to subtracting None from x. 

Please let me know if the issue can be fixed or if there are some ideas to get around this issue. 

Thank you !  
     ---

**Comment by slegall56** [comment]
Well, I encountered the same problem. 
So before training, I load my images one by one and I compute the mean. Then I added this mean to the ImageDataGenerator mean. So self.mean won't be None anymore

**Comment by DominicBreuker** [comment]
Check out documentation: https://keras.io/preprocessing/image/

For "featurewise_center" to work, you must call "fit" first to compute the statistics. Unfortunately, it requires a Numpy array as input and does not work with directories. It is meant to be used when you use "flow", not "flow_from_directory".

Imho, the way to go would be to implement a "fit_from_directory" that computes the statistics. WDYT?

**Comment by renzabergos** [comment]
@slegall56 can you please share your code, I want to implement mean subtraction as well but I'm using .flow_from_directory

**Comment by slegall56** [comment]
I add to image.py

 def fit_from_directory(self, mean=None, std=None):
        '''Required for featurewise_center, featurewise_std_normalization 
        when using image from directory.

        # Arguments
            mean: Mean Pixels of training database
            std: Standard deviation of training database
        '''
        if self.featurewise_center:
            self.mean = mean

        if self.featurewise_std_normalization:
            self.std = std

**Comment by slegall56** [comment]
I add to image.py

```
def fit_from_directory(self, mean=None, std=None):
      '''Required for featurewise_center, featurewise_std_normalization 
      when using image from directory.

    # Arguments
        mean: Mean Pixels of training database
        std: Standard deviation of training database
    '''
    if self.featurewise_center:
        self.mean = mean

    if self.featurewise_std_normalization:
        self.std = std
```

**Comment by lunasdejavu** [comment]
@slegall56  I don't get it. How could this code calculate the variation?

**Comment by mariokreutzfeldt** [comment]
Hi, 
I am facing the same problem. How did you guys implement it finally?

Thanks,
Mario

**Comment by chineseqsc** [comment]
I am facing if too...

**Comment by Walid-Ahmed** [comment]
Cmong from 2020 and I cant find an answer to the problem as well
