### ISSUE TITLE
Reg: AttributeError during keras training

### ISSUE THREAD

**Issue by ellurunaresh** [fchollet/keras#3684]
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi,
I was doing batch learning using a batchsize of 256. I found the error at fit model.

 **h = [newm.fit(trainGen.x,trainGen.y,batch_size=256, nb_epoch=10, validation_data=None, class_weight=None, sample_weight=None, verbose=1)]**

Traceback (most recent call last):
  File "keras-adapt/adapt_tmp.py", line 68, in <module>
    h = [newm.fit(trainGen.x,trainGen.y,batch_size=256, nb_epoch=learning['minEpoch'], validation_data=None, class_weight=None, sample_weight=None, verbose=1)]
  File "/usr/local/lib/python3.4/dist-packages/keras/models.py", line 596, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1107, in fit
    callback_metrics=callback_metrics)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 845, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.4/dist-packages/keras/callbacks.py", line 39, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.4/dist-packages/keras/callbacks.py", line 195, in on_epoch_end
    self.progbar.update(self.seen, self.log_values, force=True)
**AttributeError: 'ProgbarLogger' object has no attribute 'log_values'**

I was calling next function in fit command. It combines all the input and output features of all splits.

  def **next** (self):
        while (self.splitDataCounter <= self.numSplit):
            x,y = self.getNextSplitData()
            self.x = numpy.concatenate ((self.x[self.batchPointer:], x))
            self.y = numpy.concatenate ((self.y[self.batchPointer:], y))
            self.splitDataCounter += 1

```
    return (self.x, self.y)
```

I am new to this keras. Could you please help me how to solve this issue.

Thanks
Naresh

**Comment by suku-h** [comment]
did you solve this issue? i am having the same trouble

**Comment by ellurunaresh** [comment]
Yes. I have changed the generator from "fit" to "fit_generator"

**Comment by vladbph** [comment]
Keras should throw an exception when using validation_split and training set is ended up to be 0... Example: your last batch in epoch contains 1 sample and validation_split = 0.3 => training size = 0...
When training set size is 0 you will see this exception...
If you look at callbacks.py in keras, class ProgbarLogger, log_values member is created ONLY when batch starts... So if you don't have data in the batch it gets to on_epoch_end with log_values undefined...
