### ISSUE TITLE
Exposing Cudnn v5 RNN models (in tensorflow) from within keras

### ISSUE THREAD

**Issue by Froskekongen** [fchollet/keras#3692]
Recently an implementation of accelerated RNNs using cudnn v5 was exposed in tensorflow: [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cudnn_rnn](url)

If these implementations are faster and good enough for usage, they should be exposed in keras.

**Comment by carlthome** [comment]
Looking at this now. At a first glance it looks a little tricky because part of the cuDNN optimizations need to know exactly how many LSTM layers there are in the model, and Keras' doesn't (you can append LSTM layers to `Sequential()` as you go).

```Python
tf.contrib.cudnn_rnn.CudnnLSTM(num_layers, num_units, input_size)
```

**Comment by kuza55** [comment]
Does it make any sense to start with an implementation that doesn't use the stacking optimization and just passes num_layers=1 into CudnnLSTM?

**Comment by carlthome** [comment]
No. Stacking at least two RNNs is extremely common and one of the largest performance gains comes from utilizing that. See "Step 3" at https://devblogs.nvidia.com/parallelforall/optimizing-recurrent-neural-networks-cudnn-5/

**Comment by kuza55** [comment]
Right, I saw step 3; but that accounts for a 1.7x improvement, vs the other 6.5x; unless I'm misreading something.

**Comment by carlthome** [comment]
I think you should read the table again. :wink:

**Comment by kuza55** [comment]
So, my understanding of this table:


Optimization | GFLOPS | Speedup
---------------|----------|----------
Baseline | 349 | (1.0x)
Combined GEMMs | 724 | 2.1x
GEMM Streaming | 994 | 2.8x
Fused point-wise operations | 1942 | 5.5x
Matrix pre-transposition | 2199 | 6.3x
Combining Inputs | 2290 | 6.5x
Four layers | 3898 | 11.1x

Is that the speedup column is cummulative, i.e. Doing everything up to "Combining Inputs" gets you a 6.5x speedup compared to baseline. Then doing the 4 layers at a time gets you a 1.7x speedup to an overall 11.1x speedup compared to baseline.

**Comment by carlthome** [comment]
Correct.

**Comment by carlthome** [comment]
It's a 70% increase of the throughput (e.g. 4.6x faster than the baseline with the layer optimizations), no?

**Comment by kuza55** [comment]
Right, combining layers is a 70% increase; I'm not super clear on where you get the 4.6x from though.

I'm just suggesting we might get a good speedup from stacking CudnnLSTMs even if they can't do cross-layer speedups. Maybe it would be best to just benchmark that and see how it goes rather than trying to guess the interactions. Getting it to work on 1 layer is probably step 1 in any progress on the larger goal anyway.

Btw, do you know how representative the baseline is?

**Comment by carlthome** [comment]
I'd prefer to wait on Theano (this week, hopefully) and think a Keras implementation through properly after having seen the mutual aspects of both backends.

How representative? I'd wager NVIDIA's native CUDA baseline is faster than Keras because it doesn't have to go through Python, but who knows?

**Comment by nouiz** [comment]
cudnn speed up isn't related to python or not. Theano and TensorFlow don't
ahve Python code for the execution engine most of the time.

The speed up come from many low level optimization. See the tables. In an
ideal world, Theano/Tensorflow could do all of them automatically, but it
is easier to do them once for a specific/few similar algo. This is what
cudnn RNN did.

**Comment by fchollet** [comment]
It seems impossible to make this 100% compatible with our own LSTM
implementation, so I would suggest adding a new Keras layer instead. In
fact there are several TF ops that I think would benefit from a shallow
Keras wrapping (including these), so we may want to start a
`keras.tensorflow` module.

When Theano has its own version of it we can consider adding a
cross-backend layer in `keras.layer.recurrent`.

**Comment by zpardos** [comment]
Theano has now merged Cudnn v5 bindings
https://github.com/Theano/Theano/pull/4915

**Comment by carlthome** [comment]
@fchollet, I propose adding a `StackedLSTM` layer that takes number of layers as an additional parameter in order to fully utilize the optimizations. Would such a pr be of interest?

**Comment by fchollet** [comment]
First of all it would be necessary to quantify what there is to gain in
terms of performance.

**Comment by nouiz** [comment]
some benchmark on the Theano side with and without cudnn rnn:

https://github.com/MaximumEntropy/cudnn_rnn_theano_
benchmarks/blob/master/README.md

The answer, yes, there is speed up by using it.
