### ISSUE TITLE
Problem in imdb_bidirectional_lstm.py example

### ISSUE THREAD

**Issue by kyrs** [fchollet/keras#3693]
Hi,
I am trying to run the code of imdb_bidirectional_lstm(`https://github.com/fchollet/keras/blob/master/examples/imdb_bidirectional_lstm.py`)  on theano backend. But each time I  try to run it, I got an error of `Floating point exception (core dumped)` after first epoch.  Can you please suggest what am I doing wrong ??

**Comment by kyrs** [comment]
I have tested it with tensorflow backend and it is working perfectly fine..  I guess there is some issue with theano backend.

**Comment by PeterPanUnderhill** [comment]
Same question here.
