### ISSUE TITLE
imdb bidirectional example is not working

### ISSUE THREAD

**Issue by vinayakumarr** [fchollet/keras#3698]
it shows Epoch 1 but after that it directly exits from it. 
![untitled](https://cloud.githubusercontent.com/assets/18217467/18266118/af487a14-7436-11e6-85fb-77d6624d93ef.png)

**Comment by ramananbalakrishnan** [comment]
Unable to reproduce this error.

I just tried running the [example](https://github.com/fchollet/keras/blob/ae7ef37/examples/imdb_bidirectional_lstm.py) with the latest release of keras and it works fine for me.
