### ISSUE TITLE
Has keras interface to load dataset for image classification?

### ISSUE THREAD

**Issue by JulyUp** [fchollet/keras#3702]
For image classification, in the folder 'keras-master/examples', there are just examples for simple mnist and cifar10. And in these two examples, datasets is downloaded from an url and then get x_train and x_test.  So has keras interface to load dataset and get x_train and x_test from anywhere in own local dirs?

**Comment by fchollet** [comment]
Check out https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html
