### ISSUE TITLE
Can I use MeanPooling layer solely to process my data?

### ISSUE THREAD

**Issue by hqsiswiliam** [fchollet/keras#3714]
Hi, I would like to build a model like following to preprocess 2 datasets before feed into my model:
`model = Sequential()`
`model.add(AveragePooling1D(input_shape=(2,2)))`
`model.compile()`

How could do the preprocessing and get the result, should I use `model.train(input_data)` or `model.predict(input_data)`?

**Comment by phdowling** [comment]
If there are no trainable weights in your model, just compile and then use the predict function. Actually, you can pretty much always use the predict function, even if you didn't train your weights (you could use this to try out if your model compiles and if dimensionalities are right.)

**Comment by hqsiswiliam** [comment]
@phdowling ok, thanks.
