### ISSUE TITLE
Bidirectional does not work with stateful RNN

### ISSUE THREAD

**Issue by udibr** [fchollet/keras#3716]
This is because stateful RNN requires batch_input_shape to be defined, however the forward RNN does not know what the batch_input_shape is when creating the Bidirectional object because it did not yet had the chance to connect to the layers below it.

However, the Bidirectional init attempts to create the backward RNN by duplicating the forward RNN and for that it calls the get_config method of the forward RNN.
The get_config of Recurrent places a value of None for batch_input_shape see
https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L233
It has an input_spec but because the forward RNN is not yet connected, its shape is None.

I tried to solve this by manually specifying the batch_input_shape when creating the forward RNN object.
However, even this did not solve the problem because the way get_config is written.
In Recurrent get_config ignores the batch_input_shape parameter and instead re-compute it from input_spec[0].shape and then this recomputed value overwrites the value for batch_input_shape returned from the super get_config

**Comment by alex-j-j** [comment]
I just ran into the same problem, thanks for opening the issue :)

**Comment by udibr** [comment]
As a workaround you can create the RNN object (which is latter passed as a first parameter to Bidirectional) with a `batch_input_shape` parameter set to the correct value.

However another bug in Recurrent.get_config method will overwrite your value with `None`
and to overcome this second problem you need to patch the get_config method. For example, you can change the order of the sum operation in https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L239 to
`
    return dict(list(config.items()) + list(base_config.items()))
`
ensuring that the value set by the parameter (if it exists) has a higher priority than the value automatically computed for `batch_input_shape`
