### ISSUE TITLE
tensorflow and theano backend 

### ISSUE THREAD

**Issue by cdj0311** [fchollet/keras#3717]
hi all, 
  I have trained a model with tensorflow backend, however, when I use it on another machine with theano backend, there have an error. How to solve it?

**Comment by acenewgate** [comment]
The error might be caused because of the "img_dim_ordering" you should reshape your training data

**Comment by cdj0311** [comment]
@acenewgate I just used Convolution1D for text categorization, "img_dim_ordering" can affect it?

**Comment by hqsiswiliam** [comment]
You may check if there is any thing like `import tensorflow as tf` and `tf.func`.

**Comment by cdj0311** [comment]
I have found the answer, load pre-trained weights that include convolutions (layers Convolution2D or Convolution1D),be mindful of this: Theano and TensorFlow implement convolution in different ways (TensorFlow actually implements correlation, much like Caffe),
and thus, convolution kernels trained with Theano (resp. TensorFlow) need to be converted before being with TensorFlow (resp. Theano).
The code as follows:
```
from keras import backend as K
from keras.utils.np_utils import convert_kernel
def tf2th(model):
    for layer in model.layers:
        if layer.__class__.__name__ in ['Convolution1D', 'Convolution2D']:
            original_w = K.get_value(layer.W)
            converted_w = convert_kernel(original_w)
            K.set_value(layer.W, converted_w)
    return model
```
