### ISSUE TITLE
Using theano conv2d for blurring in custom objective function

### ISSUE THREAD

**Issue by fritjofbuettner** [fchollet/keras#3720]
I would like to implement a custom objective function for a convolutional autoencoder network. My objective resembles MSE, but with a Gaussian blurring using [`theano.tensor.signal.conv.conv2d`](http://deeplearning.net/software/theano/library/tensor/signal/conv.html#theano.tensor.signal.conv.conv2d) (since I want to use only one 2D filter):
```python
from theano.tensor.signal.conv import conv2d
from keras import backend as K

def conv_loss(y_true, y_pred):
    input_ = T.fmatrix('image').astype(K.floatx())
    c = conv2d(input=input_, filters=kernel, border_mode='valid')
    blur = theano.function([input_], c)
    image = K.square(y_true - y_pred)
    return K.mean(blur(image), axis=-1)
```
where `kernel` is a predefined 2D `ndarray`. When I  test this objective function on a simple convolutional autoencoder like this:
```python
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, Reshape, Convolution2D, UpSampling2D, ZeroPadding2D

print('X_train shape:', X_train.shape)  # (2000, 1, 32, 32) gray-scale images
model = Sequential()
ae_layers = [
    Convolution2D(8, 3, 3, border_mode='valid', input_shape=(img_channels, img_rows, img_cols), subsample=(2, 2), activation='relu'),
    Flatten(),
    Dense(64),
    Activation('relu'),
    Dense(8 * 15 * 15),
    Reshape(target_shape=(8, 15, 15)),
    UpSampling2D(size=(2, 2)),
    Convolution2D(8, 3, 3, border_mode='same'),
    Activation('relu'),
    ZeroPadding2D(padding=(1, 1))
]
for layer in ae_layers:
    model.add(layer)
model.summary()
print("compile model...")
model.compile(optimizer='adadelta', loss=conv_loss)
print("train model...")
model.fit(X_train, X_train, batch_size=128, nb_epoch=5, shuffle=True)
```
I get the following error:
```
compile model...
Traceback (most recent call last):
  File "test_error.py", line 72, in <module>
    model.compile(optimizer='adadelta', loss=conv_loss)
  File "anaconda/lib/python2.7/site-packages/keras/models.py", line 343, in compile
    **kwargs)
  File "anaconda/lib/python2.7/site-packages/keras/engine/training.py", line 601, in compile
    sample_weight, mask)
  File "anaconda/lib/python2.7/site-packages/keras/engine/training.py", line 323, in weighted
    score_array = fn(y_true, y_pred)
  File "errors.py", line 161, in conv_loss
    return K.mean(blur(image))
  File "anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 788, in __call__
    allow_downcast=s.allow_downcast)
  File "anaconda/lib/python2.7/site-packages/theano/tensor/type.py", line 87, in filter
    'Expected an array-like object, but found a Variable: '
TypeError: ('Bad input argument to theano function with name "errors.py:159" at index 0 (0-based)', 'Expected an array-like object, but found a Variable: maybe you are trying to call a function on a (possibly shared) variable instead of a numeric array?')
```

What exactly does keras expect back from the loss function?
Any help is greatly appreciated.

--
Mac OSX 10.11.6
python 2.7.12 (anaconda)
keras v1.0.5
theano v0.9.0dev2

**Comment by dolaameng** [comment]
When you built `blur` as a `theano.function`, it expects a numpy array rather than a Keras or Theano variable.  That was exactly what the error said: 'Expected an array-like object, but found a Variable: maybe you are trying to call a function on a (possibly shared) variable instead of a numeric array?'

**Comment by fritjofbuettner** [comment]
Thanks for the tip, I ended up with this implementation:
```python
from theano.tensor.signal.conv import conv2d
from keras import backend as K

def conv_loss(y_true, y_pred):
    image = K.square(y_true - y_pred)
    c = conv2d(input=image, filters=kernel, border_mode='full')
    return K.mean(c, axis=-1)
```

**Comment by Neltherion** [comment]
@fritjofbuettner 
Hi! 
I want to write an objective like yours and don't know how to make the kernel.
I wanted to know what kind of 'kernel' filter you used to blur the image? there was no mention of its initialization in your code. If you could write its code, I'd be grateful.

**Comment by fritjofbuettner** [comment]
@Neltherion: I am using a simple Gaussian kernel, which can be computed like this:

```python
import numpy as np
from keras import backend as K


def gaussian(x, mu, sigma):
    return np.exp(-(float(x) - float(mu)) ** 2 / (2 * sigma ** 2))


def make_kernel(sigma):
    # kernel radius = 2*sigma, but minimum 3x3 matrix
    kernel_size = max(3, int(2 * 2 * sigma + 1))
    mean = np.floor(0.5 * kernel_size)
    kernel_1d = np.array([gaussian(x, mean, sigma) for x in range(kernel_size)])
    # make 2D kernel
    np_kernel = np.outer(kernel_1d, kernel_1d).astype(dtype=K.floatx())
    # normalize kernel by sum of elements
    kernel = np_kernel / np.sum(np_kernel)
    return kernel
```
You can of course adapt the kernel radius, the 2σ seems to be default based on what I found.
Calling `make_kernel(sigma=1.0)` will give you the following kernel matrix:
```
[[ 0.00296902  0.01330621  0.02193823  0.01330621  0.00296902]
 [ 0.01330621  0.05963429  0.09832032  0.05963429  0.01330621]
 [ 0.02193823  0.09832032  0.1621028   0.09832032  0.02193823]
 [ 0.01330621  0.05963429  0.09832032  0.05963429  0.01330621]
 [ 0.00296902  0.01330621  0.02193823  0.01330621  0.00296902]]
```

**Comment by Neltherion** [comment]
@fritjofbuettner Thanks for the quick reply...

But this is strange... the output of `image = K.square(y_true - y_pred)` is a 4 dimensional tensor. here's the debugging output:

> T = {TensorVariable} DimShuffle{3,2,1,0}.0
> _is_nonzero = {bool} True
> auto_name = {str} 'auto_11375'
> broadcastable = {tuple} <type 'tuple'>: (False, False, False, False)
> dtype = {str} 'float32'
> imag = {TensorVariable} Elemwise{imag,no_inplace}.0
> index = {int} 0
> name = {NoneType} None
> ndim = {int} 4
> owner = {Apply} Elemwise{sqr,no_inplace}(Elemwise{sub,no_inplace}.0)
> real = {TensorVariable} Elemwise{real,no_inplace}.0
> shape = {TensorVariable} Shape.0
> size = {TensorVariable} Prod{acc_dtype=int64}.0
> type = {TensorType} TensorType(float32, 4D)

but `conv2d(input=image, filters=kernel, border_mode='full')` has an assertion that only allows 2 or 3 dimensional inputs (`assert input.ndim in (2, 3)`) while my input is the 4-Dimensional Tensor, which results in an Assertion Error when using this loss function...

I only want to gaussian blur the images before (or after?) calculating the loss.

Any Ideas?

**Comment by fritjofbuettner** [comment]
I am using grayscale images, so I could just squeeze away the image color channel dimension:
```python
if image.ndim > 3:
    image = K.squeeze(image, axis=1)```

If you have color images, you might have to loop over the batch dimension (0)?

**Comment by Neltherion** [comment]
That's it... I'm going to start working on it...

Thank you so much...
