### ISSUE TITLE
Sequential name not saved

### ISSUE THREAD

**Issue by maxbry** [fchollet/keras#3723]
I have a siamese network with two different sequential models. The networks have the names `L` and `R`. I save the overlaying network using the method `keras.models.save_model`. When loading the network, I'm iteratiing over `model.layers` to extract my sequential models `L` and `R`, but now the models are named `sequential_1` and `sequential_2`. Usually, the layer names are set when loading using the method `get_config`, but at the class `Sequential` this seems to work differently. How do I have to change that method in order to save my sequential layers with their given names?

**Comment by bethard** [comment]
I ran into this issue a while ago, but I just tested with Keras 2.0.6 and the issue is no longer present.
