### ISSUE TITLE
preprocessing modules

### ISSUE THREAD

**Issue by RoyiHD** [fchollet/keras#3726]
Issue with importing modules from preprocessing 

Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras import preprocessing 
Using Theano backend.
>>> dir(preprocessing)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> x = preprocessing.sequence.pad_sequences([1], maxlen=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'keras.preprocessing' has no attribute 'sequence'
>>>

**Comment by AnishShah** [comment]
@RoyiHD 
Correct way of import in Keras would be
`from keras.preprocessing import sequence`

You can see that `dir(preprocessing)` does not have `sequence`

**Comment by RoyiHD** [comment]
Works. thank you
