### ISSUE TITLE
When to use keras.layers.core.Layer?

### ISSUE THREAD

**Issue by kkog** [fchollet/keras#3739]
Hi,

Sorry if this is a simple question as I am new to Keras. I have seen a couple of examples where people were using the function Layer in keras.layers.core. But, I could not find a documentation about it. Can someone explain me what is Layer used for? And is it different from keras.layers.core.Dense?

**Comment by kgrm** [comment]
The [Layer class](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L200) is just an abstract interface used to implement layers. It's not a functional NN layer on its own. You don't need to use it unless you're trying to write your own layers, in which case see https://keras.io/layers/writing-your-own-keras-layers/ .
