### ISSUE TITLE
imdb_bidirectional_lstm

### ISSUE THREAD

**Issue by omarcr** [fchollet/keras#3759]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [ x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Output error:

/usr/bin/python2.7 /home/omar/Pycharm_ubuntu_v2/keras_new_examples/bidirect_lstm.py
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/home/omar/Pycharm_ubuntu_v2/keras_new_examples/bidirect_lstm.py", line 12, in <module>
    from keras.layers import Dense, Dropout, Embedding, LSTM, Input, Bidirectional
ImportError: cannot import name Bidirectional

Process finished with exit code 1

**Comment by gw0** [comment]
Works for me. You do not have the latest version of Keras! Ensure that `pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps` did work and your `/usr/bin/python2.7` is using the latest version.

**Comment by omarcr** [comment]
yes, updating to 1.0.8 fixed the problem. Regards.

**Comment by gw0** [comment]
Close the issue?
