### ISSUE TITLE
Cosine distance

### ISSUE THREAD

**Issue by maxbry** [fchollet/keras#3764]
I have a question about cosine distance:

In the [wikipedia article](https://en.wikipedia.org/wiki/Cosine_similarity), the denominator is defined as `sqrt(sum(a)) * sqrt(sum(b))`, in keras, it is implemented as `sqrt(sum(a) * sum(b))`. Why does the implementation differ?

Also in keras, does the implementation refer to similarity or to distance? And is the range (-1, 1) or (0,1)?

**Comment by rex-yue-wu** [comment]
Not sure where you see the keras version of cosine distance, but I will use the cosine distance objective below

```
def cosine_proximity(y_true, y_pred):
    y_true = K.l2_normalize(y_true, axis=-1)
    y_pred = K.l2_normalize(y_pred, axis=-1)
    return -K.mean(y_true * y_pred, axis=-1)
```

**Comment by maxbry** [comment]
In the [merge layer](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1293).

From my perspective, lines 1296+1297 should look like this:

    denominator = K.sqrt(K.batch_dot(l1, l1, self.dot_axes)) *\
                  K.sqrt(K.batch_dot(l2, l2, self.dot_axes))
