### ISSUE TITLE
TypeError while using ImageDataGenerator

### ISSUE THREAD

**Issue by AnishShah** [fchollet/keras#3765]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I was trying this example from [documentation](https://keras.io/preprocessing/image/) on keras.io and got TypeError. 

```
In [1]: import keras
Using Theano backend.

In [2]: keras.__version__
Out[2]: '1.0.8'

In [3]: import theano

In [4]: theano.__version__
Out[4]: '0.9.0dev2.dev-140d0a064523349b630a284247c7cddd767fc46e'

In [5]: from keras.preprocessing.image import ImageDataGenerator

In [6]: from keras.datasets import cifar10

In [7]: (X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [8]: datagen = ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True)

In [9]: datagen.fit(X_train)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-0dc4891d7ef8> in <module>()
----> 1 datagen.fit(X_train)

/usr/local/lib/python2.7/dist-packages/keras/preprocessing/image.pyc in fit(self, X, augment, rounds, seed)
    401         if self.featurewise_center:
    402             self.mean = np.mean(X, axis=0)
--> 403             X -= self.mean
    404 
    405         if self.featurewise_std_normalization:

TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'



```

**Comment by keskarnitish** [comment]
I guess the problem is happening because you are not converting the input data into a `float` array. 
You can fix the problem by adding a `X_train = X_train.astype('float32')` before you call the `datagen.fit` function.
Notice that this is done in most Keras examples; see e.g. [CIFAR-10; Line 73](https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py#L73).

The reason why this is an issue is that the data is in the `uint8` type. The mean is computed as a float and Python cannot automatically do the casting for you when you try to subtract it off.

**Comment by AnishShah** [comment]
Yep. that works! Should I send a PR to update the documentation? or else this issue can be closed. ;)

**Comment by keskarnitish** [comment]
I'm not sure about the PR, you could try and see what feedback you receive.
