### ISSUE TITLE
error while fitting the model in keras

### ISSUE THREAD

**Issue by saumyaj** [fchollet/keras#3767]
Hi i am new to keras and i am trying to learn from [http://machinelearningmastery.com/tutorial-first-neural-network-python-keras/] by implementing the code available which is as below but i get following error

`Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/lib -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/theano/gof -L/usr/local/lib -L/usr/lib -L/usr/lib -fvisibility=hidden -o /home/saumya/.theano/compiledir_Linux-4.4--generic-x86_64-with-LinuxMint-18-sarah-x86_64-2.7.12-64/tmpX5eWKu/e3c8de9d51e298a853a3dc6d24b85ffd.so /home/saumya/.theano/compiledir_Linux-4.4--generic-x86_64-with-LinuxMint-18-sarah-x86_64-2.7.12-64/tmpX5eWKu/mod.cpp -lopenblas -lpython2.7
/usr/bin/ld: /usr/local/lib/libpython2.7.a(cobject.o): relocation R_X86_64_32 against`PyCObject_Type' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

Traceback (most recent call last):
  File "keras_first_network.py", line 28, in <module>
    model.fit(X, Y, nb_epoch=150, batch_size=10)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 620, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1077, in fit
    self._make_train_function()
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 701, in _make_train_function
    *_self._function_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 727, in function
    return Function(inputs, outputs, updates=updates, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 713, in __init__
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/pfunc.py", line 484, in pfunc
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1789, in orig_function
    defaults)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 1653, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/vm.py", line 1051, in make_all
    no_recycling))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 975, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 875, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1131, in **compile**
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 1145, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cc.py", line 1492, in compile_cmodule
    preargs=preargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py", line 2301, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', Dot22(dense_input_1, dense_1_W), '\n', "Compilation failed (return status=1): /usr/bin/ld: /usr/local/lib/libpython2.7.a(cobject.o): relocation R_X86_64_32 against `PyCObject_Type' can not be used when making a shared object; recompile with -fPIC. /usr/local/lib/libpython2.7.a: error adding symbols: Bad value. collect2: error: ld returned 1 exit status. ", '[Dot22(dense_input_1, dense_1_W)]')
`

`from keras.models import Sequential
from keras.layers import Dense
import numpy
# fix random seed for reproducibility

seed = 7
numpy.random.seed(seed)
# load pima indians dataset

dataset = numpy.loadtxt("pima-indians-diabetes.csv", delimiter=",")
# split into input (X) and output (Y) variables

X = dataset[:,0:8]
Y = dataset[:,8]
# create model

model = Sequential()
model.add(Dense(12, input_dim=8, init='uniform', activation='relu'))
model.add(Dense(8, init='uniform', activation='relu'))
model.add(Dense(1, init='uniform', activation='sigmoid'))
# Compile model

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# Fit the model

model.fit(X, Y, nb_epoch=150, batch_size=10)
# evaluate the model

scores = model.evaluate(X, Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))`

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by nouiz** [comment]
You need the python dynamic library. Try to install python-dev or
python-devel software package from your OS.

http://www.deeplearning.net/software/theano/install.html

**Comment by saumyaj** [comment]
@nouiz Hi, Thanks for the reply but I already have it
I tried it anyway with command : sudo apt-get install python-dev
and i got following output in terminal
I am using linux mint and i am still getting the same error when i run keras code mentioned earlier.


`Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version (2.7.11-1).
The following packages were automatically installed and are no longer required:
  blt tk8.6-blt2.5
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 320 not upgraded.
`

**Comment by chowkamlee81** [comment]
Iam facing the same issue regarding below
 PyCObject_Type' can not be used when making a shared object; recompile with -fPIC. /usr/local/lib/libpython2.7.a: error adding symbols: Bad value. collect2: error: ld returned 1 exit status. ", 

Kindly suggest
