### ISSUE TITLE
weights for resnet have improper shapes

### ISSUE THREAD

**Issue by omarcr** [fchollet/keras#3770]
The weights provided in:
https://github.com/fchollet/keras/blob/master/examples/resnet_50.py

for the resnet50 architecture:
https://drive.google.com/open?id=0B4ChsjFJvew3NVQ2U041Q0xHRHM ('th' dim ordering, for other countries)
https://drive.google.com/open?id=0B4ChsjFJvew3NWN5THdxcTdSWmc ('tf' dim ordering, for other countries)

Have improper bad shapes.

The weights provided in:
 https://github.com/fchollet/deep-learning-models/blob/master/resnet50.py

Which are:
TH_WEIGHTS_PATH = 'https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_th_dim_ordering_th_kernels.h5'
TF_WEIGHTS_PATH = 'https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels.h5'
TH_WEIGHTS_PATH_NO_TOP = 'https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_th_dim_ordering_th_kernels_notop.h5'
TF_WEIGHTS_PATH_NO_TOP = 'https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5'

works for the resnet50 architecture. I recommend changing the URLs in the file.

**Comment by fchollet** [comment]
Fixed by removing the deprecated resnet example script. Use instead `keras/applications/resnet50`.
