### ISSUE TITLE
how to switch tf back to theano?

### ISSUE THREAD

**Issue by JulyUp** [fchollet/keras#3772]
For some needs, I change {"backend": "theano"} to {"backend": "tensorflow"} in file '~/.keras/keras.json'. Now I want to use theano again.So I  change  {"backend": "tensorflow"} back to {"backend": "theano"}.  But when I run my scripts, it shows error:
`I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Couldn't import dot_parser, loading of dot files will not be possible.
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    theano.config.device = 'gpu'
  File "/usr/local/lib/python2.7/dist-packages/theano/configparser.py", line 331, in __set__
    "Can't change the value of this config parameter "
Exception: Can't change the value of this config parameter after initialization!`

What should I do to solve this problems?

**Comment by nouiz** [comment]
The file main.py try to change the Theano flag theano.config.device after
having loaded Theano. You can't do it like that. You can do it by doing

Import Theano.sandbox.cuda as cuda
cuda.usa("gpu")

**Comment by JulyUp** [comment]
@nouiz  Thankyou very much. And it works. Though I do not understand why.
