### ISSUE TITLE
Theano is running very slow on GPU

### ISSUE THREAD

**Issue by ibrahim-amer** [fchollet/keras#3782]
I'm using Theano backend on Keras running on jupyter ipython notebook. Everything was working fine couples of days ago, but today I notice that it is running very very slow !, I think running it on CPU is much faster than that. I'm running [ mnist example](https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py) without making any changes. The batch (128 size) takes too long to process, around 5 minutes or something to finish, the next batch takes the same time almost or longer, it used to run mnist example very very fast (170 seconds for the whole epoch). 

Please help me how could I figure out the problem
Note: I tried it using anaconda then I tried it using winpython and the same problem occur.

I'm using windows 10, 16GB ram, Nvidia GTX 660 2 GB, cuDNN either enabled or disabled the same problem occur

[Theano issues thread](https://github.com/Theano/Theano/issues/4974)

**Comment by ibrahim-amer** [comment]
@fchollet sir could you help me with this please ?

**Comment by keunwoochoi** [comment]
No one knows what happened during the last few days. You should first re-install every drivers and cuda/cudnn.

**Comment by rmkemker** [comment]
@ibrahim-amer I am having the same issue. I am going to reinstall all of the drivers, but let me know if you figure out what was causing it.

**Comment by ibrahim-amer** [comment]
I reinstalled all the drivers (gforce, cuDNN, cuda) but nothing changed, it is still running quite slow. I want first to verify if theano is actually using my GPU or not, when I run this line "import keras" this is the feedback I got: 
Using Theano backend.
Using gpu device 0: GeForce GTX 660 (CNMeM is enabled with initial size: 50.0% of memory, cuDNN 5005)

I think it is using GPU if I get this message. I also tried [this code here ](http://deeplearning.net/software/theano/tutorial/using_gpu.html#returning-a-handle-to-device-allocated-data)
But it prints "Used the cpu" 

This is my THEANO_FLAGS looks like : 
floatX=float32,device=gpu,nvcc.fastmath=True,lib.cnmem=0.5,exception_verbosity=high,optimizer=None

**Comment by rmkemker** [comment]
I know mine is using the GPU since I can use the command nvidia-smi in the terminal to see that the GPU is running.   I have similar theano flags, except I am using 90% of the GPU memory.  Mine runs for a while, and then gets slower as time goes on.

**Comment by ibrahim-amer** [comment]
@rmkemker how much time the epoch take to finish ?

**Comment by rmkemker** [comment]
I am training a different network with a different dataset.  It took about 13 hours to get through 1 epoch (it is a very large dataset) and it took over 2 days to get through the 2nd epoch.  That doesn't make sense to me.

**Comment by ibrahim-amer** [comment]
Damn !!! ... Could you please download GPU-Z and see what is the GPU loading percentage while you train your network ?

**Comment by ibrahim-amer** [comment]
@rmkemker  Damn!! ... Please download GPU-Z and see what is GPU loading percentage while you train your network

**Comment by rmkemker** [comment]
That's a Windows product.  I am using Ubuntu 14.04.  I can still get all of those stats.
![image](https://cloud.githubusercontent.com/assets/14336785/18610363/d8f74be6-7ce8-11e6-89d9-b5bb89fe9766.png)

**Comment by rmkemker** [comment]
I do notice that the load bounces from max to basically zero.  I am pretty sure that is the fit generator in keras loading more data into the GPU.

**Comment by iarroyof** [comment]
This worked for me:

`$ THEANO_FLAGS='mode=FAST_RUN' python myKerasScript.py`

A short explanation [here](http://stackoverflow.com/questions/37768735/why-is-theano-running-so-slow). You can also set this configuration in your `~/theanorc` file.
