### ISSUE TITLE
Multiple GPUs over theano / 3D convolution in Tensorflow

### ISSUE THREAD

**Issue by sanjeevmk** [fchollet/keras#3788]
I'm using Keras with Voxel grids , so I use Convolution 3D and other 3D layers heavily. I'm using Theano as backend.

I want to shift to using Multiple GPUs for my project. I'm planning to buy GPUs conditioned on the fact that I can use it with Keras. Hence I'm asking here before buying the GPUs.

Looking at previous forum questions, these two issues exist, that put me in a deadlock:
1. Multiple GPU support currently is only available with Tensorflow
2. 3D Layer support (like Convolution 3D) are only available with Theano.

Have any of these 2 changed, considering the other posts were over a month old..?
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by kuza55** [comment]
There is a limited implementation of multiple GPU support in this PR: https://github.com/fchollet/keras/pull/3582

So you can probably pull that into your own fork of Keras and try it, though obviously it's not part of mainline Keras, so proceed at your own risk.

Implementing Convolution 3D for TensorFlow before buying extra hardware may be the less risky path for you though.
