### ISSUE TITLE
FCN - None in input shape causes TypeError

### ISSUE THREAD

**Issue by Huxwell** [fchollet/keras#3789]
I need to feed images of different size to FCN learned using keras + tensorflow backend. @
When I specify input
`inputs = Input(shape=(channels,None,None))
`
or
`model_15.add(Convolution2D(32, 3, 3, W_regularizer=l2(l=l2_reg),input_shape=(channels, None, None)))`

during the model compilation i get
`TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'`

while 
`shape=(channels,15,15)` works OK.

Any ideas why does it occur and how to overcome this?
According to @fchollet  ( #1920 ) it should work ok.

**Comment by barrykui** [comment]
Hi, @Huxwell . It seems that the `merge #3429` had solved the bug. But I still have the same problem  as you. Have you solved this problem?

**Comment by cyrilP-qs** [comment]
Hi
I have the same problem.
However, I am reworking on a project I started a few months ago, and back then the same model worked. I thus looked at the history of changes, and the break can be traced back to commit f0bfc24adc41840d937f6f485bb69591532cc538 (integrated in 1.0.4), on keras/initializations.py

So if you really need it, you can revert back to 1.0.3 until someone fixes this.
