### ISSUE TITLE
ImageDataGenerator.flow_from_generator would be nice to decouple image sources from data augmentation

### ISSUE THREAD

**Issue by zacstewart** [fchollet/keras#3798]
I have a big directory of images named like `00001.jpg`. I have an info CSV that maps these filenames to metadata, including their label. I'd like to use `flow`, but there is too much data for me to load into memory. I'd like to use `flow_from_directory`, but it seems like unnecessary work to restructure the directories these images are in just to benefit from class inference.

For the time being, I wrote my own generator that cycles through rows in my info CSV and loads batches of images based on the rows in it. This works well, but I miss out on the benefit of data augmentation unless I want to add a lot more code to my generator.

It would be nice if I could write my own generator that fetches images, whether I need to get them from a directory of images, or pull them out of an hdf5 file, or whatever. How the `(input_batch, label_batch)` gets produced could be no concern of `ImageDataGenerator`. I propose that `ImageDataGenerator` implement a new method, `flow_from_generator`, which takes a generator implementing the same interface as `Model.fit_generator`.

If there's support for this feature, I'd be willing to take a shot at implementing it.

**Comment by mratsim** [comment]
That would be very helpful.

The alternative today to lazily load images from a CSV file is to write a `CSVIterator` similar to `DirectoryIterator`/`NumpyArrayIterator` and create a custom class that inherits from `ImageDataGenerator`.

**Comment by hemagso** [comment]
This would be very helpful. 

I am currently working on a regression problem with a dataset that don't fit in memory, and for obvious reasons the flow_from_directory is not a solution for me, as I can't organize my data in one folder by each label.

I'll probably write some Data Augmentation over in my own generator, but it would be nice to have this functionality included in ImageDataGenerator.
