### ISSUE TITLE
Why do graph outputs have two names?

### ISSUE THREAD

**Issue by iskandr** [fchollet/keras#380]
I love the recently added `Graph` model but it has a bothersome inconvenience. When I added a node to the network I give it a name and then I have to give it a second name via `add_output`. Is there any way to combine these to cut down on the verbosity?

**Comment by fchollet** [comment]
It wouldn't be much of an issue to add an `output=True` flag in `add_node`. But I think the current setup reduces confusion, although it is indeed more verbose.

I'll think about it.

**Comment by fchollet** [comment]
You can now set `create_output=True` in `add_node` to use the current node as an output.
