### ISSUE TITLE
Error when loading saved merged model

### ISSUE THREAD

**Issue by Tharu87** [fchollet/keras#3802]
Hi,

I have a CNN model with two merged branches. The model compiles and trains without error. However when I save the model and load the saved model it gives the following error:

Traceback (most recent call last):
  File "\eclipse\workspace\AKEOS\position_cnn\main_classify.py", line 283, in <module>
    final_model = load_model("causal_model.h5")
  File "\Anaconda2\lib\site-packages\keras\models.py", line 128, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File \Anaconda2\lib\site-packages\keras\models.py", line 177, in model_from_config
    return layer_from_config(config, custom_objects=custom_objects)
  File "\Anaconda2\lib\site-packages\keras\utils\layer_utils.py", line 36, in layer_from_config
    return layer_class.from_config(config['config'])
  File "\Anaconda2\lib\site-packages\keras\models.py", line 1016, in from_config
    merge = Merge.from_config(first_layer_config)
  File "\Anaconda2\lib\site-packages\keras\engine\topology.py", line 1465, in from_config
    return super(Merge, cls).from_config(config)
  File "\Anaconda2\lib\site-packages\keras\engine\topology.py", line 929, in from_config
    return cls(**config)
  File "\Anaconda2\lib\site-packages\keras\engine\topology.py", line 1180, in **init**
    node_indices, tensor_indices)
  File "\Anaconda2\lib\site-packages\keras\engine\topology.py", line 1203, in _arguments_validation
    layer_output_shape = layer.get_output_shape_at(node_indices[i])
  File "\Anaconda2\lib\site-packages\keras\engine\topology.py", line 660, in get_output_shape_at
    'output shape')
  File "\Anaconda2\lib\site-packages\keras\engine\topology.py", line 636, in _get_node_attribute_at_index
    'and thus has no defined ' + attr_name + '.')
Exception: The layer has never been called and thus has no defined output shape.

The code for the CNN model is as below:

```
    text_branch = Sequential()
    text_branch.add(Embedding(vobabsize, embedding_size, input_length=data_len,weights=[U]))

    e1pos_branch = Sequential()
    e1pos_branch.add(Embedding(max_pos+1, dim_pose, input_length=data_len,weights=[U_Pose]))

    e2pos_branch = Sequential()
    e2pos_branch.add(Embedding(max_pos+1, dim_pose, input_length=data_len,weights=[U_Pose]))

    merged_m = Merge([text_branch, e1pos_branch], mode='concat')
    merged = Merge([merged_m, e2pos_branch], mode='concat')       

    final_model = Sequential()
    final_model.add(merged)      
    final_model.add(Convolution1D(nb_filter=num_filters,
                             filter_length=filter_size,
                             border_mode='valid',
                             activation='relu',
                             subsample_length=1))
    final_model.add(MaxPooling1D(pool_length=poolsize, stride=None, border_mode='valid'))
    flatten = Flatten(name="flatten")
    final_model.add(flatten)
    final_model.add(Dense(3))

    final_model.add(Activation('softmax'))
```

what could be the cause of the error?

Thanks in advance!

**Comment by kuza55** [comment]
I'm not sure what is causing your error, but you may want to consider using the Functional API for models like this: https://keras.io/models/model/

**Comment by qixianbiao** [comment]
I try to repeat the error you reported but succussfully run it..

Pls check the following code:


    import numpy as np
    from keras.layers import Dense, Input, Convolution1D, MaxPooling1D, Flatten, Activation
    from keras.layers import Merge, Embedding
    from keras import backend as K
    from keras.models import Model, Sequential
    vobabsize = 1000
    embedding_size = 256
    max_pos = 1000
    data_len = 200
    dim_pose = 100
    num_filters = 16
    filter_size = 5
    poolsize = 2
    
    U = np.random.random((vobabsize, embedding_size))
    U_Pose = np.random.random((max_pos+1, dim_pose))
    
    text_branch = Sequential()
    text_branch.add(Embedding(vobabsize, embedding_size, input_length=data_len,weights=[U]))

    e1pos_branch = Sequential()
    e1pos_branch.add(Embedding(max_pos+1, dim_pose, input_length=data_len,weights=[U_Pose]))

    e2pos_branch = Sequential()
    e2pos_branch.add(Embedding(max_pos+1, dim_pose, input_length=data_len,weights=[U_Pose]))

    merged = Merge([text_branch, e1pos_branch, e2pos_branch], mode='concat')
    #merged = Merge([merged_m, e2pos_branch], mode='concat')       

    final_model = Sequential()
    final_model.add(merged)      
    final_model.add(Convolution1D(nb_filter=num_filters,
                             filter_length=filter_size,
                             border_mode='valid',
                             activation='relu',
                             subsample_length=1))
    final_model.add(MaxPooling1D(pool_length=poolsize, stride=None, border_mode='valid'))
    flatten = Flatten(name="flatten")
    final_model.add(flatten)
    final_model.add(Dense(3))

    final_model.add(Activation('softmax'))
    final_model.summary()
    final_model.save_weights('finalmodel.h5', overwrite=True)
    
    final_model.load_weights('finalmodel.h5')
    print("success")

**Comment by Tharu87** [comment]
Hi,

Thanks for the reply. I actually tried:

final_model.save("finalmodel.h5")
del final_model
final_model = load_model("finalmodel.h5")

which is what gave the error. I shall try save_weights() instead.
