### ISSUE TITLE
About merge(mul) problem

### ISSUE THREAD

**Issue by Biho** [fchollet/keras#3808]
My script is below:

---

```
imodel= {};
for input_index,in_feat_dim in enumerate(v_set.invector_dimension):
    imodel[input_index] = Input(shape=(in_feat_dim,))

modelx = merge([imodel[0], imodel[1],imodel[2]], mode='concat' )
modelx = Dropout(0.2)(modelx)
modelx = Dense(hidden_layer1, activation='relu')(modelx)
modelx = Dropout(0.5)(modelx)
modelx = Dense(hidden_layer2, activation='relu')(modelx)
modelx = Dropout(0.5)(modelx)
modelx = Dense(hidden_layer3, activation='relu')(modelx)
modelx = Dropout(0.5)(modelx)

modelx = Dense(v_set.target_dimension, activation='sigmoid')(modelx)
modelx = merge([modelx,imodel[0]], mode='mul' )


model = Model(input = [imodel[0], imodel[1],imodel[2]],output = [modelx])
```

---

In this script, Output is mul ( imodel[0] and sigmoid(~= 0<x<1 mask)).
So output is smaller than imodel[0]. 

But I checked number, some output is bigger than imodel[0]. why this problem is occurred????
## below is my check script:

output  =  model.predict([input_data[0],input_data[1],input_data[2]])
np.maximum(input_data[0],output) == input_data[0] 
or 
np.maximum((input_data[0] - output) ,0.0)

**Comment by qixianbiao** [comment]
if your input  input_data[0] (you mentioned it also imodel[0]) < 0, then the output is bigger than the imodel[0]....................
