### ISSUE TITLE
Enhancement Suggestion: Name Scopes

### ISSUE THREAD

**Issue by kuza55** [fchollet/keras#3815]
TensorBoard relies on all operators having proper names to group them, and I think any other visualisation tools that seek to examine the graphs would probably want a hierarchical grouping of operators too.

However, it seems like Keras only really names weights and not operators. Naming everything individually is probably a painful process, particularly since extra operations are generated in places which don't necessarily have the context to name things properly.

Rather than trying the herculean task of piping names through everywhere, I would suggest copying the TF idea of name scopes and then adding them to things like layers to start with.
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by kilotaras** [comment]
Here's a comparison between using named with some nodes expanded and default graphs
![named](https://cloud.githubusercontent.com/assets/590292/18681697/dd73a74c-7f71-11e6-9b6b-9015399d7fbe.png)
using tf.named_scope
![simple](https://cloud.githubusercontent.com/assets/590292/18681750/0f4e1a7c-7f72-11e6-91f1-bfa35fb97c97.png)
default Keras graph

The first is both more clean and more expressive, but comes at the cost of a lot of boilerplate code. Moving all that `with named_scope` to Keras would be nice.

The gist to generate https://gist.github.com/kilotaras/7e9f1ea67d93711e3ff422c7123e5d08

**Comment by jakebian** [comment]
Sent a PR for this https://github.com/fchollet/keras/pull/4233.

Example resulting graph (without adding a single line to your examples, this would be the default graph Keras spits out post this PR):

![example](https://cloud.githubusercontent.com/assets/5866348/19848816/2556c7fa-9f0d-11e6-9aa8-3e7a2335e839.png)

**Comment by bshao001** [comment]
Do we have any good approach to add a prefix to all variables/operators in a Keras model?
