### ISSUE TITLE
For 3d convolutions on theano, use GpuCorrMM3d instead of conv3d2d?

### ISSUE THREAD

**Issue by Maltimore** [fchollet/keras#3821]
Hi,

I just modified Keras (with theano backend) to use the GpuCorrMM3d algorithm for 3d convolutional layers (instead of conv3d2d), and the training became about 4x faster. Is there a reason why GpuCorrMM3d isn't being used? If there is interest in this, I'd be happy to make a pull request.

**Comment by fchollet** [comment]
@nouiz would you have any thoughts on GpuCorrMM3d vs conv3d2d?

**Comment by Maltimore** [comment]
See also this issue:
https://github.com/Theano/Theano/issues/3826

**Comment by nouiz** [comment]
We have a pr to add an abstract 3d conv: follow the pr to stay up to date:
https://github.com/Theano/Theano/pull/4862

when done, that would be better thenusing GpuCorrMM3d directly. It will be
like conv2d

**Comment by gvtulder** [comment]
Fixed in #4039, I think.

**Comment by Maltimore** [comment]
Yep I assume that fixes it. Thanks everyone!
