### ISSUE TITLE
No training_data

### ISSUE THREAD

**Issue by luk-f-a** [fchollet/keras#3825]
Hi,

I have recently updated from version 0.3.2 to version 1.1.0. I was using the property training_data of the sequential model for a custom callback which is now missing on version 1.1.0. Is this intentional? This is the sample code:

```
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(output_dim=1, input_dim=1, activation='tanh'))
model.compile(loss='mean_squared_error',optimizer='adadelta')
x_t = np.array([[1]])
y_t = np.array([1])
model.fit(x_t, y_t)
model.training_data
```

The last line returns: 
`
[array([[1]]), array([[1]]), array([ 1.])]
`
on version 0.3.2 but an error on 1.1.0. The former contained, in models.py, function _fit of class Model the following:

```
        self.training_data = ins
        self.validation_data = val_ins
```

while 1.1.0 contains in training.py, in _fit_loop an assignment for self.validation_data but nothing for training_data.
Is this bug or on purpose? How can I access the training_data from a callback?

Thanks,

Luk

**Comment by luk-f-a** [comment]
No answers? Could I just suggest a fix then?

Thanks,

**Comment by vladimir-chernykh** [comment]
I am also interested why validation data is stored as a member of a class and training is not.
Found this thing while trying to change sample_weight inside the Callback. How can I do it then?

Thanks.
