### ISSUE TITLE
keras lstm architecture

### ISSUE THREAD

**Issue by vinayakumarr** [fchollet/keras#3828]
model.add(LSTM(4, input_dim=look_back))  // 4 LSTM blocks

But how many cells it has in keras?

for example i assume 4 memory blocks and 2 cells. Is there any architecture?

In stacked LSTM

model.add(LSTM(4, return_sequences=True))
model.add(LSTM(4, return_sequences=False))

for example i assume 4 memory blocks and 2 cells. How it looks like architecture?

in that case, will have 2 hidden layer, hidden layer i have 4 lstm blocks (layer1) these feedback to another lstm layer which has same 4 lstm blocks. Am i right?

**Comment by ishank26** [comment]
I don't fully understand what you mean by a block here.  
`model.add(LSTM(4, return_sequences=True)` will add a 4 memory units which will unfold over time, see [this](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L667-#L712).

**Comment by carlthome** [comment]
Repost of https://github.com/fchollet/keras/issues/3840 ?

**Comment by vinayakumarr** [comment]
It creates 4 lstm blocks and each block has 4cells
 Is this right. Or it has 4 blocks where each block has a single cell?
