### ISSUE TITLE
Keras can't apply model trained from version 1.0.4

### ISSUE THREAD

**Issue by RaffEdwardBAH** [fchollet/keras#3839]
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

There seems to be an issue applying models trained with version 1.0.4 of keras, that use batch norm, with version 1.0.9+. Depending on the version of theano I get different errors. Not sure what is happening, but interested if other shave observed anything similar. I get the below error when using the head version of Theano, and oddly isn't fixed by taking the max of epsilon and 1e-5. 

``` python
/usr/local/lib/python2.7/dist-packages/keras/layers/normalization.pyc in call(self, x, mask)
    136                 x_normed, mean, std = K.normalize_batch_in_training(
    137                     x, self.gamma, self.beta, reduction_axes,
--> 138                     epsilon=self.epsilon)
    139 
    140                 self.updates = [K.moving_average_update(self.running_mean, mean, self.momentum),

/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.pyc in normalize_batch_in_training(x, gamma, beta, reduction_axes, epsilon)
    413     normed = batch_normalization(x, broadcast_mean, broadcast_var,
    414                                  broadcast_beta, broadcast_gamma,
--> 415                                  epsilon)
    416     return normed, mean, var
    417 

/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.pyc in batch_normalization(x, mean, var, beta, gamma, epsilon)
    426         try:
    427             return theano.sandbox.cuda.dnn.dnn_batch_normalization_test(x, gamma, beta, mean, var,
--> 428                                                                         'spatial', epsilon)
    429         except AttributeError:
    430             pass

/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/dnn.pyc in dnn_batch_normalization_test(inputs, gamma, beta, mean, var, mode, epsilon)
   2783                          (mean.ndim, var.ndim, ndim))
   2784     if epsilon < 1e-5:
-> 2785         raise ValueError("epsilon must be at least 1e-5, got %f" % epsilon)
   2786 
   2787     if ndim < 4:

ValueError: epsilon must be at least 1e-5, got 0.000001
```

**Comment by RaffEdwardBAH** [comment]
There appears to be a new value in keras.json for `"image_dim_ordering"`. Mine had `th` as the orignal value. My old model runs (waiting on output) when switched to `tf`. However, my original model was trained with Theano, and I'm applying it with theano. Why would that make it work? When did this change happen?

**Comment by keunwoochoi** [comment]
Can be about 97d2a73 and 0588393 (source: https://github.com/fchollet/keras/pull/3718#issuecomment-247828201). My weights that is trained in 1.0.6 experienced a similar problem. In my case there was error raised, but the prediction was not correct, only in Theano.

**Comment by atnelson** [comment]
Yes, I'm hitting this same issue when testing a model trained with 1.0.6 on a system running 1.1.0.

**Comment by atnelson** [comment]
Workaround: edit your model's JSON file, and modify the value of epsilon in the batch_normalization layers, setting it to 1e-5. Not sure what effect this will have on the outputs, though.

**Comment by atnelson** [comment]
Never mind: modifying epsilon in the model JSON file does NOT work. Performance is destroyed compared with running the model without modification on Keras 1.0.3

**Comment by a00achild1** [comment]
Have the same issue here.
I forgot what version I used to train my model.
But after I update the Theano and Keras to the new version, I got the similar error.
I'm using Keras 1.2.2, Theano 0.9.0rc1

**Comment by ytsheng** [comment]
Hitting the same error. Did any of you guys solve this?

**Comment by atnelson** [comment]
No, I had to retrain the model with a later version of Keras.
