### ISSUE TITLE
keras lstm cells

### ISSUE THREAD

**Issue by vinayakumarr** [fchollet/keras#3840]
model.add(lstm(4)). This has 4 lstm blocks, but how many cells keras creates it? if I use stacked lstm, then keras lstm contain 2 hidden layer: it will be many to many. Is there any specific architecture keras has for lstm and as well as stacked lstm?

**Comment by carlthome** [comment]
`model.add(LSTM(4))` creates four LSTM cells in a single layer. If you want to stack more layers, call `model.add(LSTM(4))` more times (once per layer).

**Comment by vinayakumarr** [comment]
creates 4 lstm blocks and each block has 4cells
Is this right. Or it has 4 blocks where each block has a single cell?

**Comment by ishank26** [comment]
@vinayakumarr  a "block" is a single cell or memory unit in reference to your query. As mentioned by @carlthome `model.add(LSTM(4))` will create 4 cells or "blocks" in a single layer.  For more info on lstm [1](http://www.felixgers.de/papers/phd.pdf) & [2](https://colah.github.io/posts/2015-08-Understanding-LSTMs/)

**Comment by vinayakumarr** [comment]
according to thesis, first link lstm has blocks, which inturn has cells. But what about in keras? Reference fig 3.3 in thesis

**Comment by vinayakumarr** [comment]
no, FELIX GERS thesis, it is in english [1](http://www.felixgers.de/papers/phd.pdf)

**Comment by carlthome** [comment]
Keras' `LSTM()` assumes you want as many "memory blocks" as cells. If you want to share gates for several cell states you'll need to implement your own custom layer.

**Comment by carlthome** [comment]
So to answer your original question: it has 4 blocks where each block has a single cell.

**Comment by vinayakumarr** [comment]
yes you are right. so keras has 4 blocks where each block has a single cell for lstm(4) . in hidden layer 4 blocks which in turn has 4 cells: this has input gate, output gate, forget gate, error carousel (CEC) and peehole connection, fig 5.1 in thesis. Could you give a basic architecture for these 4 blocks. This helps to understand more clearly


one more question, in staked lstm, i will have two hidden layer am i right?

one hidden layer has 4 blocks , this layer feeds to other hidden layer (contains 4 blocks) for 2 stacked lastm layers am i right?

**Comment by carlthome** [comment]
Honestly, if you're that curious about the particular details of Keras's LSTM, just look at it? [Here it is.](https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L602)

**Comment by ishank26** [comment]
In my opinion, before implementing a model you should take a deeper look into theory of RNNs and its variants. That'll will solve most of the problems. For cell architecture refer [this](https://colah.github.io/posts/2015-08-Understanding-LSTMs/) and for stacked layer representation [this](https://github.com/fchollet/keras/issues/1029#issuecomment-157786333) issue.
