### ISSUE TITLE
border_mode='same' is very slow for Convolution3D

### ISSUE THREAD

**Issue by mdering** [fchollet/keras#3847]
Hi Keras,
Using border_mode = 'same' is causing a substantial slowdown (230s/epoch with same vs 132 with valid, theano backend) in my model using 3D convolutions. I realize this is likely an upstream issue as theano only supports valid border mode in conv3d2d, but I was wondering a few things

1) is that still the fastest way to perform this operation? there is a DNN variant, but I haven't researched it much
2) Is the current method of set_subtensor the fastest? Theano implements a pad_left and pad_right method which could possibly be faster. I haven't done any testing of any of this but thats a pretty substantial slowdown. 

Should I open up a ticket upstream with theano as well?

Thanks

**Comment by nouiz** [comment]
There is a pr in Theano that make conv3d2d support the same parameter. I
forgot if it was merged or not. I'm currently offline. I think using this
will be faster then using set subtensor. Can you look at them PR and try it?

**Comment by mdering** [comment]
Didn't actually seem to speed it up at all. Or hardly at all.

**Comment by nouiz** [comment]
In fact, we wrap cudnn v3 conv. You could call it directly from
theano.sandbox.cuda.dnn.dnn_conv3d(...) (I need to add it in the doc....
until that, you can check in the Theano file directly, it have its
docstring)

I don't remember if it use the same order of dimensions. If you use cudnn
v5, I think it is faster then conv3d2d. But for cudnn v4 conv3d2d was
faster.
