### ISSUE TITLE
A Convolutional Neural Network Model Could not be loaded

### ISSUE THREAD

**Issue by aykutcayir34** [fchollet/keras#3854]
I have saved the model using _model.save('my_model.h5')_ it's working. However, when I try to load the model in a different project I get this error message: ValueError: Tensor("cond/pred_id:0", dtype=bool) must be from the same graph as Tensor("dropout_1/mul_1:0", shape=(?, 1, 256), dtype=float32).
Could this be a bug? Any idea?

**Comment by srviest** [comment]
hi, I happened the same issue, how did you figure this out?
Thanks in advance.

**Comment by towakina** [comment]
Hi , I had experienced the same issue as @aykutcayir34 . My project is a web application which I use flask as framework. Also, model loading request comes from the front end. I recognized it was Flask related issue (I still do not figure out the reason). I solved the problem by loading the model before running the flask application and calling `predict ` function immediately after loading model.
I know this sounds silly but it's the way how I solved the issue.
