### ISSUE TITLE
Possible bug in Autoencoder class

### ISSUE THREAD

**Issue by turambar** [fchollet/keras#386]
Hi Francois, et al., I'm a PhD student in CS/machine learning at USC. We started our DL odyssey using Theano directly and just discovered keras, which has thus far been great, especially for rapidly trying a lot of different models. Thanks for the great work!

I did find what I believe to be a bug in the Autoencoder class, in its handling of tied weights. I noticed after training an autoencoder with tied weights set to true, the actual encoder and decoder weights were NOT identical (which means they WEREN'T actually tied during training). This is because the only place the tie_weights option is used is inside of get_output -- i.e., it just returns the encoder weights as the decoder weights.

Unless I am mistaken, what you want is for the decoder's Theano symbolic variable parameter (e.g., W for a Dense layer) to be the transpose of the encoder's parameter. For example, see the dA class in the Theano tutorial.

I can fix this, but I have two questions:
- Do you have a preferred procedure for accepting fixes? I.e., just fork keras, make the changes, send a pull request?
- I'm torn about the best way to make the actual fix. I created a new Layer called TiedDense that accepts a Dense "layer" in its constructor and does the "right thing" (sets the W parameter to be equal to layer.W.T, makes an untied bias, only includes the bias in the params list, etc.). For now, I've just been sticking that in a Sequential model and eschewing the Autoencoder class altogether.

Another option would be a to make a class method that takes a (generic) layer and creates a decoder version of that layer with tied weights. With that, one could perhaps build the decoder automatically within the Autoencoder constructor.

Thoughts?

P.S. I've also implemented some Noise layers for use with denoising autoencoders, if those are of interest.

**Comment by fchollet** [comment]
> Do you have a preferred procedure for accepting fixes? I.e., just fork keras, make the changes, send a pull request?

Yes. Your PR will be reviewed, you will get feedback, and when everything looks good it will be merged.

> Unless I am mistaken, what you want is for the decoder's Theano symbolic variable parameter (e.g., W for a Dense layer) to be the transpose of the encoder's parameter. For example, see the dA class in the Theano tutorial.

It's not so simple, because encoders/decoders are arbitrary stacks of layers. 

> Another option would be a to make a class method that takes a (generic) layer and creates a decoder version of that layer with tied weights. With that, one could perhaps build the decoder automatically within the Autoencoder constructor.

How would that work?

**Comment by turambar** [comment]
> Yes. Your PR will be reviewed, you will get feedback, and when everything looks good it will be
> merged.

OK, I can do that.

>> Unless I am mistaken, what you want is for the decoder's Theano symbolic variable parameter (e.g.,
>> W for a Dense layer) to be the transpose of the encoder's parameter. For example, see the dA class
>> in the Theano tutorial.

> It's not so simple, because encoders/decoders are arbitrary stacks of layers.

True, but I think the special case of a single layer denoising autoencoder [1] is important enough to warrant a proper implementation in the keras ecosystem (even if it's just an example and not an actual layer). This would permit comparison with the Theano tutorial [2], and it is a common tool for classic unsupervised pretraining [3]. Regarding HOW to do it...

> a class method that takes a (generic) layer and creates a decoder version of that layer with tied
> weights.

> How would that work?

I have some ideas. Let me flesh them out and then re-post them in this thread, for your feedback.

**Comment by fchollet** [comment]
After review, I decided to remove weight tying for now. You can reintroduce it in a cleaner form in a future PR.

**Comment by jramapuram** [comment]
Even if the enc_param is set to the dec_param after the first initial pass everything is in essence the same. But yes, a simple swap of enc_param <--> dec_param in the swapping logic will solve your 1 timestep lag. You do not generally tie biases. The way I implemented weight tying was using:

```python
if len(dec_param.shape) > 1:
```

This is because ```layer.get_weights()``` does not return only the weights.
This is erroneous and needs to be refactored to ```.get_weights()``` & ```.get_bias()```

**Comment by DominikSchniertshauer** [comment]
What's the workaround here? Without tied_weights I get the following error if I try the "unofficial" SAE-example from you: Layer is not connected                and is not an input layer.

**Comment by isaacgerg** [comment]
I see this bug is still open.  I would like to contribute to Keras and feel this would be a good place for me to jump in.  Can someone give me a hand on getting started?

**Comment by niraabe** [comment]
Hi,
what is the current state with the tie_weights parameter ?
Is the bug fix reviewed and released ?

**Comment by isaacgerg** [comment]
It doesnt support the tie_weights parameter.  As far as I have researched,
this is not being implemented.  I believe you don't have to the tie the
weights to get reasonable results.  In fact, I think one of the reasons
tie_weights was removed was because @fchollet didnt want to propagate that
method because he felt it was unnecessary.  @fchollet, can you comment?

**Comment by strangeice** [comment]
I tried this tutorial  https://blog.keras.io/building-autoencoders-in-keras.html  without the tied weights.  But the result is not great (at least given the same effort of training compared with tied weights in theano dA).    This means I have to translate theano dA class into keras convention in order stay within keras?

Here is the results without tied weights
![figure_1](https://cloud.githubusercontent.com/assets/7541501/18496840/0547e0a0-7a5c-11e6-90e9-b14203254e54.png)
