### ISSUE TITLE
Problem with LSTM, GRU with word embeddings

### ISSUE THREAD

**Issue by rajat315315** [fchollet/keras#3861]
I have been trying to make my model work but its been 3 days and I can't get it. I am working on extracting words from a sentence called 'aspect extraction' and The problem is the following: I have (3044, 80, 145) matrix as input where;
3044- number of sentences. 
80- max_number of words in a sentence 
145- dimension of word_embeddings (including POS tags, etc)

and (3044, 80) as output where: 
80- one-hot vector, where 1 occurs at the position of an aspect.

I have tried LSTM and GRU but have the following error(nearly) reported everytime. Please guide.

`TypeError: ('The following error happened while compiling the node', forall_inplace,cpu,scan_fn}(TensorConstant{80}, InplaceDimShuffle{1,0,2}.0, IncSubtensor{InplaceSet;:int64:}.0, TensorConstant{80}, gru_1_U_z, gru_1_U_r, gru_1_U_h), '\n', "Inconsistency in the inner graph of scan 'scan_fn' : an input and an output are associated with the same recurrent state and should have the same type but have type 'TensorType(float32, col)' and 'TensorType(float32, matrix)' respectively.")`
My code is:

```
train_inp = pickle.load(open("train_inp_145.pkl", "rb"))
train_out = pickle.load(open("train_out_145.pkl", "rb"))

train_inp = train_inp.reshape(3044, 80, 145).astype('float32')
train_out = train_out.reshape(3044, 80, 1)

model = Sequential()

model.add(GRU(1, return_sequences=True, input_shape=(80, 145)))
model.add(TimeDistributedDense(1))
model.add(Activation("softmax"))

model.compile(loss='mse',
              optimizer='rmsprop',
              metrics=['accuracy'])

print (model.summary())
model.fit(train_inp, train_out, validation_split=0.2,
          batch_size=100,
          nb_epoch=2
          )
```

Model summary:

```
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
gru_1 (GRU)                      (None, 80, 1)         441         gru_input_1[0][0]                
____________________________________________________________________________________________________
timedistributeddense_1 (TimeDistr(None, 80, 1)         2           gru_1[0][0]                      
____________________________________________________________________________________________________
activation_1 (Activation)        (None, 80, 1)         0           timedistributeddense_1[0][0]     
====================================================================================================
Total params: 443
```

**Comment by billhsia** [comment]
Hello , I faced the same probelm like yours!! Did u solve your problems? Would u share with me?I will appreciate!!

**Comment by jonathanking** [comment]
I also have this problem and would appreciate your assistance. Thank you!
