### ISSUE TITLE
Is it possible to pause the training after each epoch so that python finish its garbage collection before the next epoch starts?

### ISSUE THREAD

**Issue by yxchng** [fchollet/keras#3863]
Currently I am facing memory problems when the training reaches the 2nd epoch. Apparently that means that I have sufficient memory but the training is not waiting for garbage collection to complete before the start of the next iteration. Therefore, I am wondering if it is possible to make the training wait before the start of a new epoch. If so, how can I do it? Thanks

On top of that, should samples_per_epoch affect memory usage? When I lower it, training can last more than 1 epoch. However, I think if garbage collection is done properly, it shouldn't affect memory usage, should it?

**Comment by varoudis** [comment]
Maybe put your fit function in a for loop with epoch = 1?

**Comment by yxchng** [comment]
I tried to put it in a for loop and call gc.collect() at the end of each iteration, but I am still getting memory error. How can I make it wait for full garbage collection before the next iteration starts? 

Does tensorflow consumes more memory than torch, since I am just replicating a model that is built using torch.
