### ISSUE TITLE
1d convolution, with weight sharing across channels?

### ISSUE THREAD

**Issue by larspars** [fchollet/keras#3865]
I have timeseries data, in multiple channels, with `shape=(n_steps, n_channels)`

I want to do a convolution in the time dimension, similar to this:

```
Convolution1D(n_filters, filter_size, input_shape=(n_steps, n_channels))
```

However, this will train a separate filter for each channel - apparently the weights get `shape=(filter_size, 1, n_channels, n_filters)`.

I want to apply the same filter for all channels (weight sharing), so the weights will have `shape=(filter_size, 1, 1, n_filters)`.

Can this be done with Keras?

**Comment by dolaameng** [comment]
How about flattening the input first?

**Comment by larspars** [comment]
I could do that, but there's two problems with it: 

1) It won't be exactly right at the start and end of each segment, at the 'borders'. I'm not sure this would matter too much, so I might be able to live with it.

2) I get a ~10x slowdown when doing this, probably because I lose parallelism over the channels. This is more of a deal breaker to me.

**Comment by dolaameng** [comment]
wow. I didn't expect a 10x slowdown. Do you have any idea why?

Another related idea is to use a `TimeDistributed Conv1D`? So first make the n_channels as the time axis and for each of them apply another Conv1D. The weights across TimeDistributed should be shared to my knowledge. But I haven't tried it myself so not sure about the performance. Glad to know how you explore it.

**Comment by larspars** [comment]
Thanks for the `TimeDistributed` tip, I'll look into that.
