### ISSUE TITLE
Keras on AWS EC2

### ISSUE THREAD

**Issue by roestigraben** [fchollet/keras#3866]
I have developed an ML app on my local machine and now wanted to do the deployment on AWS EC2 (CPU instance only at this time as I talk about a predict flow)

After installation of all packages and specifically Keras and Theano backend, I am able to call under Python (Ubuntu 14:04  - Python version 2.7.6) all packages nicely.

So, as example, when I interactively do call up Python and then import keras, I get the standard print 'Using Theano backend.' as desired and set in the keras.json file

Now, I installed flask server and and apache2 server working with wsgi package.
I test this server out with several types of routes and returns and all is working nicley.

my flask file is looking essentially like

```
from flask import Flask, jsonify, request
import json 
import os
from python import predict 

@app.route("/api/ML/predict", methods=['POST'])
def dicom_tag():

    #print (request.data)

    dataIn = request.get_json()
    data = dataIn[u'id']

    predicted = predict.doPrediction(data)

    return jsonify(predicted)
```

my predict.py file is in the python directory and looks like

```
import os
import cv2
import json
import time
import dicom
import scipy
import keras

# more imports and ...
# and the all my code to do the predict flow

```

so, I start my apache server and look at the logs and the logs tell me 
'Using TensorFlow backend.' which is not what I want.

Can anybody give me a hint why this is happening
many thanks
Peter

**Comment by dolaameng** [comment]
You can check `~/.keras/keras.json` on your EC2 instance for the value of `"backend"`.

**Comment by roestigraben** [comment]
Hey, I have done this but it works only when I am in interactive mode as stated above

**Comment by dolaameng** [comment]
you can print out the "user folder" by `os.path.expanduser('~')` to see where the configuration is located, I guess Apache server is running under a different user than yours?

**Comment by roestigraben** [comment]
Thanks so far but not sure what to do with it. Your hint is interesting to say that the apache server is maybe running under a different user. I am on Amazon Web Services EC2, so going to launch your command, it comes back as /home/ubuntu while apache is installed in the root of the instance, I guess in etc/apache2 (no sure about this).
???

**Comment by dolaameng** [comment]
There are many ways of configuring Keras. I guess a quick fix could be using `os.environ['KERAS_BACKEND']='theano'` before your `import keras` to make it explicit.

**Comment by roestigraben** [comment]
That is an excellent hint.
I will try this
Wish me luck!
Thanks
