### ISSUE TITLE
Why first epoch takes substantially longer than subsequent epoch?

### ISSUE THREAD

**Issue by yxchng** [fchollet/keras#3876]
<img width="960" alt="screen shot 2016-09-27 at 12 04 59 am" src="https://cloud.githubusercontent.com/assets/10518587/18843676/a0b302aa-844c-11e6-8d09-1b90181b960a.png">

This is a screenshot of my training and the first epoch is taking much longer than subsequent epochs? Can I know why?

**Comment by varoudis** [comment]
compile time included?

**Comment by yxchng** [comment]
it is timed after model.compile() and before model.fit(). so it is just timing model.fit(). Is compilation included in the first epoch of model.fit()?

**Comment by varoudis** [comment]
i believe it is
 for example if you use Theano it takes ages to do the first fit. Like minutes..
With tensorflow its way faster but it take some time too.

**Comment by varoudis** [comment]
do a 'top' or 'htop' while running the first fit and you will see the .cu compiled.

**Comment by nouiz** [comment]
If the timing exclude the compilation, if can be explained by some t Theano
flag for cudnn. Some flags tell cudnn to try all the algo and keep the
fastest one after that. It is a good option when the shape don't change any
you run for a long time.

Le 27 sept. 2016 04:02, "Tasos Varoudis" <notifications@github.com> a
écrit :

**Comment by yxchng** [comment]
I am actually using tensorflow

**Comment by nouiz** [comment]
As this is a feature of cudnn, maybe they use it.
