### ISSUE TITLE
TypeError: load_weights() got an unexpected keyword argument 'by_name'

### ISSUE THREAD

**Issue by fish128** [fchollet/keras#3879]
I saved a model's weight in an HDF5 file and I am trying to load it to initialize a different model (with a different output layer) using this command:
model.load_weights('model_weights.h5', by_name=True)

But I got this error:
TypeError: load_weights() got an unexpected keyword argument 'by_name'

Could anyone help?

**Comment by Higgcz** [comment]
Are you sure you have the latest version of keras? This functionality was added 21 days ago in #3488. Try updating keras.

**Comment by fish128** [comment]
Thanks @Higgcz . I just updated Keras and it's working now.

**Comment by Higgcz** [comment]
@fish128 No problem, it happened to me many times. :) I guess the issue can be closed.
