### ISSUE TITLE
decoding reuters?

### ISSUE THREAD

**Issue by mikekestemont** [fchollet/keras#388]
I wanted to add an example for a character-level 1D convolution in the style of "Text Understanding from Scratch" (http://arxiv.org/pdf/1502.01710v3.pdf). For this, I wanted to reconstruct the original text from the Reuters topic classification dataset, which -- unlike the IMDB dataset? -- comes with a vocabulary index in `keras.datasets`. I thought the following would work, but it produces gibberish when I try to decode documents:

```
from keras.datasets import reuters
vocab_dict = reuters.get_word_index(path="reuters_word_index.pkl")
(X_train, y_train), (X_test, y_test) = reuters.load_data(nb_words=max(vocab_dict.values()), test_split=0.2)
print(vocab_dict["million"])
# inverse the dict for lookup via idx:
vocab_dict = dict((v, k) for k, v in vocab_dict.items())
print(vocab_dict[2124])
# reconstruct random document:
txt = [vocab_dict[idx] if idx in vocab_dict else "XXX" for idx in X_train[1000]]
print(txt)
```

Any thoughts? I might be missing something obvious here.

**Comment by fchollet** [comment]
It is quite possible that in your version of the dataset, the word index and the vectorized texts no longer match. You can either regenerate the dataset (`reuters.make_reuters_dataset()` then store the output in your `~/.keras/datasets/`), or clear your `~/.keras/datasets/reuters*` then download the data again.

`reuters.make_reuters_dataset()` now includes a check to verify that texts can be correctly reconstructed using the word index.

**Comment by freakinkatv1** [comment]
Hi fellas. How are we doing today?
