### ISSUE TITLE
set_floatx does not work properly

### ISSUE THREAD

**Issue by danielS91** [fchollet/keras#3891]
Once keras and the backend is imported, it is not possible to change the float type using 'set_floatx()'.

So running the following code snippet:

``` python
import keras
print(keras.backend.floatx())
keras.backend.set_floatx('float16')
print(keras.backend.floatx())

# create dummy variable as internally used for weights etc.
a = keras.backend.variable([10])
print(a.dtype)
```

will result in:

```
float32
float16
float32
```

(only tested with theano backend, but with tensorflow backend it should be the same)

Is this the desired behaviour and 'set_floatx()' only for internal use?
Otherwise the backends should request the current float type by calling 'floatx()' instead of using a default value which is set once.

**Comment by danielS91** [comment]
For example for 'variable()' replacing:
```python
def variable(value, dtype=_FLOATX, name=None):
    '''Instantiate a tensor variable.
    '''

    ...
```
with:
```python 
from .common import floatx

...

def variable(value, dtype=None, name=None):
    '''Instantiate a tensor variable.
    '''
    if dtype is None:
        dtype = floatx()

    ...
```
would fix the problem.
There are a lot of other functions which have to be modified in that way.

**Comment by keunwoochoi** [comment]
> There are a lot of other functions which have to be modified in that way.

More than `variable()` and `placeholder` in each backend?

**Comment by danielS91** [comment]
Yes, for example: `zeros()`, `ones()`, `eye()` and the 5 functions handling randomness `random_*()`.
Before making a PR, it would be nice to know whether this is the desired behaviour @fchollet  (see first post)?

**Comment by jphalip** [comment]
I've just run into the same problem, where the floatx value used by Tensorflow is frozen at module loading time.

I was looking at Keras' code and was about to suggest exactly the same approach as @danielS91's above.

**Comment by jphalip** [comment]
I've submitted a PR for this in #4739. I've also added some tests. Let me know your thoughts.
