### ISSUE TITLE
 merge two layers into a layer, the layer has different numpyarray datetype, one is int32 other is float32, how to merge

### ISSUE THREAD

**Issue by wml1993** [fchollet/keras#3899]
``` python
'''Trains a LSTM on the IMDB sentiment classification task.
The dataset is actually too small for LSTM to be of any advantage
compared to simpler, much faster methods such as TF-IDF + LogReg.
Notes:

- RNNs are tricky. Choice of batch size is important,
choice of loss and optimizer is critical, etc.
Some configurations won't converge.

- LSTM loss decrease patterns during training can be quite different
from what you see with CNNs/MLPs/etc.
'''
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout, Activation, Embedding,Input,merge
from keras.layers import LSTM, SimpleRNN, GRU
from keras.datasets import imdb
from keras.optimizers import SGD, Adadelta, Adagrad, Adam, Adamax
import theano

max_features = 26656
maxlen = 35  # cut texts after this number of words (among top max_features most common words)
batch_size = 32
EmbeddingOutFeature = 100;

print('Loading data...')
# (X_train, y_train), (X_test, y_test) = imdb.load_data(nb_words=max_features)
X_test = np.load("../../document/9_26/new_rnn_int32_test.npy")
X_train = np.load("../../document/9_26/new_rnn_int32_train.npy")
y_train =np.load('../new_9_18/Tag_version2.npy')
y_test = np.load("../new_9_18/Test_Tag_version2.npy")
maskingTrain = np.load('maskingTrain.npy')
maskingTest = np.load("maskingTest.npy")

# print (X_train)
print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')
np.set_printoptions(threshold=np.nan)

print ("handle padding")
print('Pad sequences (samples x time)')
X_train = sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = sequence.pad_sequences(X_test, maxlen=maxlen)

# print (type(X_train))

maskingTrain = sequence.pad_sequences(maskingTrain, maxlen=maxlen)
maskingTest = sequence.pad_sequences(maskingTest, maxlen=maxlen)

# X_train.astype("float32")
# X_test.astype("float32")

X_train = X_train.astype("float32")
X_test = X_test.astype("float32")
maskingTrain  = maskingTrain.astype("float32")

print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)

print('Build model...')
# model = Sequential()
# model.add(Embedding(max_features, 50, dropout=0.2))
# model.add(LSTM(100, dropout_W=0.2, dropout_U=0.2))  # try using a GRU instead, for fun
# model.add(Dense(19,activation="softmax"))
# try using different optimizers and different optimizer configs
mainInput = Input((maxlen,),dtype="int32",name="main_input")
x = Embedding(max_features,EmbeddingOutFeature,dropout=0.3)(mainInput)
# lstm how to work, i do not know so i need to learn more
lstmOut = LSTM(output_dim=100,dropout_U=0.3,dropout_W=0.3,)(x)

# MainLoss = Dense(19,activation="sigmod",name="MainLoss")(lstmOut)

maskInput =Input((maxlen,),dtype="int32",name="mask_input")
print (type(maskInput))
y = merge([lstmOut,maskInput],mode="concat",)
print (type(y))
result = Dense(19,activation="softmax",name="main_loss")(y)

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
# create model
model = Model(input=[mainInput,maskInput],output=result)
model.compile(optimizer=sgd, loss="categorical_crossentropy",
              metrics=['accuracy'])

print('Train...')
model.fit([X_train,maskingTrain],y_train, batch_size=batch_size, nb_epoch=300,
          validation_data=([X_test,maskingTest],y_test))

score, acc = model.evaluate(X_test, y_test,
                            batch_size=batch_size)

print('Test score:', score)
print('Test accuracy:', acc)

```

this is my code, 

the problem is Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/src/document/9_26/TwoInputRNN.py", line 82, in <module>
    result = Dense(19,activation="softmax",name="main_loss")(y)
  File "C:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 465, in **call**
    self.assert_input_compatibility(x)
  File "C:\Anaconda2\lib\site-packages\keras\engine\topology.py", line 389, in assert_input_compatibility
    str(K.dtype(x)))
Exception: Input 0 is incompatible with layer main_loss: expected dtype=float32, found dtype=float64

**Comment by wml1993** [comment]
![lstmout](https://cloud.githubusercontent.com/assets/15571421/18917105/4e199ca6-85c9-11e6-92f7-4f4d82aa184b.jpg)
![maskinput](https://cloud.githubusercontent.com/assets/15571421/18917108/4eda6f12-85c9-11e6-9c81-8cc920962e99.jpg)

**Comment by keunwoochoi** [comment]
How do you *want* to merge? 
And by the way, what is the IDE on the screenshot?

**Comment by wml1993** [comment]
@keunwoochoi i want to merge a layer which "LSTM(output_dim=100,dropout_U=0.3,dropout_W=0.3,)(x)" the output of LSTM 100 dimension with 50 features, and another layer is  "maskInput =Input((maxlen,),dtype="int32",name="mask_input")"  NumpyArray 40*1, how to merge two layer, any kind of merge way i all accept, could you give me some suggestion? 

the IED is named "Pycharm".

**Comment by wml1993** [comment]
@keunwoochoi i want to merge a layer which "LSTM(output_dim=100,dropout_U=0.3,dropout_W=0.3,)(x)" the output of LSTM 100 dimension with 50 features, and another layer is  "maskInput =Input((maxlen,),dtype="int32",name="mask_input")"  NumpyArray 40*1, how to merge two layer, any kind of merge way i all accept, could you give me some suggestion? 

the IED is named "Pycharm"

**Comment by keunwoochoi** [comment]
They have different sizes and different data type. People could help, but probably only after you decide how to merge them - e.g., sum? concatenate? dot product? element-wise multiplication? This is a research question and not an implementation question.

I also recommend you to wrap your code with ``` for better readability.

**Comment by wml1993** [comment]
``
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout, Activation, Embedding,Input,merge
from keras.layers import LSTM, SimpleRNN, GRU
from keras.datasets import imdb
from keras.optimizers import SGD, Adadelta, Adagrad, Adam, Adamax
import theano

max_features = 26656
maxlen = 35  # cut texts after this number of words (among top max_features most common words)
batch_size = 32
EmbeddingOutFeature = 100;

print('Loading data...')
# (X_train, y_train), (X_test, y_test) = imdb.load_data(nb_words=max_features)
X_test = np.load("../../document/9_26/new_rnn_int32_test.npy")
X_train = np.load("../../document/9_26/new_rnn_int32_train.npy")
y_train =np.load('../new_9_18/Tag_version2.npy')
y_test = np.load("../new_9_18/Test_Tag_version2.npy")
maskingTrain = np.load('maskingTrain.npy')
maskingTest = np.load("maskingTest.npy")

# print (X_train)
print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')
np.set_printoptions(threshold=np.nan)

print ("handle padding")
print('Pad sequences (samples x time)')
X_train = sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = sequence.pad_sequences(X_test, maxlen=maxlen)

# print (type(X_train))

maskingTrain = sequence.pad_sequences(maskingTrain, maxlen=maxlen)
maskingTest = sequence.pad_sequences(maskingTest, maxlen=maxlen)

# X_train.astype("float32")
# X_test.astype("float32")

X_train = X_train.astype("float32")
X_test = X_test.astype("float32")
maskingTrain  = maskingTrain.astype("float32")

print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)

print('Build model...')
# model = Sequential()
# model.add(Embedding(max_features, 50, dropout=0.2))
# model.add(LSTM(100, dropout_W=0.2, dropout_U=0.2))  # try using a GRU instead, for fun
# model.add(Dense(19,activation="softmax"))
# try using different optimizers and different optimizer configs
mainInput = Input((maxlen,),dtype="int32",name="main_input")
x = Embedding(max_features,EmbeddingOutFeature,dropout=0.3)(mainInput)
# lstm how to work, i do not know so i need to learn more
lstmOut = LSTM(output_dim=100,dropout_U=0.3,dropout_W=0.3,)(x)

# MainLoss = Dense(19,activation="sigmod",name="MainLoss")(lstmOut)

maskInput =Input((maxlen,),dtype="int32",name="mask_input")
print (type(maskInput))
y = merge([lstmOut,maskInput],mode="concat",)
print (type(y))
result = Dense(19,activation="softmax",name="main_loss")(y)

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
# create model
model = Model(input=[mainInput,maskInput],output=result)
model.compile(optimizer=sgd, loss="categorical_crossentropy",
              metrics=['accuracy'])

print('Train...')
model.fit([X_train,maskingTrain],y_train, batch_size=batch_size, nb_epoch=300,
          validation_data=([X_test,maskingTest],y_test))

score, acc = model.evaluate(X_test, y_test,
                            batch_size=batch_size)

print('Test score:', score)
print('Test accuracy:', acc)
``
this is my code.
And i think in my model mode="concatenate " maybe is the best suggestion . 
But i choose this model and find the dytpe become float64, and the last softmax refuse this data type requiring float32.

**Comment by wml1993** [comment]
`np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout, Activation, Embedding,Input,merge
from keras.layers import LSTM, SimpleRNN, GRU
from keras.datasets import imdb
from keras.optimizers import SGD, Adadelta, Adagrad, Adam, Adamax
import theano

max_features = 26656
maxlen = 35  # cut texts after this number of words (among top max_features most common words)
batch_size = 32
EmbeddingOutFeature = 100;

print('Loading data...')

X_test = np.load("../../document/9_26/new_rnn_int32_test.npy")
X_train = np.load("../../document/9_26/new_rnn_int32_train.npy")
y_train =np.load('../new_9_18/Tag_version2.npy')
y_test = np.load("../new_9_18/Test_Tag_version2.npy")
maskingTrain = np.load('maskingTrain.npy')
maskingTest = np.load("maskingTest.npy")

print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')
np.set_printoptions(threshold=np.nan)

print ("handle padding")
print('Pad sequences (samples x time)')
X_train = sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = sequence.pad_sequences(X_test, maxlen=maxlen)

maskingTrain = sequence.pad_sequences(maskingTrain, maxlen=maxlen)
maskingTest = sequence.pad_sequences(maskingTest, maxlen=maxlen)

X_train = X_train.astype("float32")
X_test = X_test.astype("float32")
maskingTrain  = maskingTrain.astype("float32")

print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)

print('Build model...')
mainInput = Input((maxlen,),dtype="int32",name="main_input")
x = Embedding(max_features,EmbeddingOutFeature,dropout=0.3)(mainInput)
# lstm how to work, i do not know so i need to learn more
lstmOut = LSTM(output_dim=100,dropout_U=0.3,dropout_W=0.3,)(x)
maskInput =Input((maxlen,),dtype="int32",name="mask_input")
print (type(maskInput))
y = merge([lstmOut,maskInput],mode="concat",)
print (type(y))
result = Dense(19,activation="softmax",name="main_loss")(y)

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model = Model(input=[mainInput,maskInput],output=result)
model.compile(optimizer=sgd, loss="categorical_crossentropy",
              metrics=['accuracy'])

print('Train...')
model.fit([X_train,maskingTrain],y_train, batch_size=batch_size, nb_epoch=300,
          validation_data=([X_test,maskingTest],y_test))

score, acc = model.evaluate(X_test, y_test,
                            batch_size=batch_size)

print('Test score:', score)
print('Test accuracy:', acc)`

this is my code , and i think in my model concatenate mode is better, therefore i choose mode ="concat' ,however dtype of output of merge layer is float64, and last layer Dense(softmax) is required 
float32.
how to solve?

**Comment by wml1993** [comment]
``` python

'''Trains a LSTM on the IMDB sentiment classification task.
The dataset is actually too small for LSTM to be of any advantage
compared to simpler, much faster methods such as TF-IDF + LogReg.
Notes:

- RNNs are tricky. Choice of batch size is important,
choice of loss and optimizer is critical, etc.
Some configurations won't converge.

- LSTM loss decrease patterns during training can be quite different
from what you see with CNNs/MLPs/etc.
'''
from __future__ import print_function
import numpy as np
np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.utils import np_utils
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout, Activation, Embedding,Input,merge
from keras.layers import LSTM, SimpleRNN, GRU
from keras.datasets import imdb
from keras.optimizers import SGD, Adadelta, Adagrad, Adam, Adamax
import theano

max_features = 26656
maxlen = 35  # cut texts after this number of words (among top max_features most common words)
batch_size = 32
EmbeddingOutFeature = 100;

print('Loading data...')
# (X_train, y_train), (X_test, y_test) = imdb.load_data(nb_words=max_features)
X_test = np.load("../../document/9_26/new_rnn_int32_test.npy")
X_train = np.load("../../document/9_26/new_rnn_int32_train.npy")
y_train =np.load('../new_9_18/Tag_version2.npy')
y_test = np.load("../new_9_18/Test_Tag_version2.npy")
maskingTrain = np.load('maskingTrain.npy')
maskingTest = np.load("maskingTest.npy")

# print (X_train)
print(len(X_train), 'train sequences')
print(len(X_test), 'test sequences')
np.set_printoptions(threshold=np.nan)

print ("handle padding")
print('Pad sequences (samples x time)')
X_train = sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = sequence.pad_sequences(X_test, maxlen=maxlen)

# print (type(X_train))

maskingTrain = sequence.pad_sequences(maskingTrain, maxlen=maxlen)
maskingTest = sequence.pad_sequences(maskingTest, maxlen=maxlen)

# X_train.astype("float32")
# X_test.astype("float32")

X_train = X_train.astype("float32")
X_test = X_test.astype("float32")
maskingTrain  = maskingTrain.astype("float32")

print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)

print('Build model...')
# model = Sequential()
# model.add(Embedding(max_features, 50, dropout=0.2))
# model.add(LSTM(100, dropout_W=0.2, dropout_U=0.2))  # try using a GRU instead, for fun
# model.add(Dense(19,activation="softmax"))
# try using different optimizers and different optimizer configs
mainInput = Input((maxlen,),dtype="int32",name="main_input")
x = Embedding(max_features,EmbeddingOutFeature,dropout=0.3)(mainInput)
# lstm how to work, i do not know so i need to learn more
lstmOut = LSTM(output_dim=100,dropout_U=0.3,dropout_W=0.3,)(x)

# MainLoss = Dense(19,activation="sigmod",name="MainLoss")(lstmOut)

maskInput =Input((maxlen,),dtype="int32",name="mask_input")
print (type(maskInput))
y = merge([lstmOut,maskInput],mode="concat",)
print (type(y))
result = Dense(19,activation="softmax",name="main_loss")(y)

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
# create model
model = Model(input=[mainInput,maskInput],output=result)
model.compile(optimizer=sgd, loss="categorical_crossentropy",
              metrics=['accuracy'])

print('Train...')
model.fit([X_train,maskingTrain],y_train, batch_size=batch_size, nb_epoch=300,
          validation_data=([X_test,maskingTest],y_test))

score, acc = model.evaluate(X_test, y_test,
                            batch_size=batch_size)

print('Test score:', score)
print('Test accuracy:', acc)

```

this is my code , and i think in my model concatenate mode is better, therefore i choose mode ="concat' ,however dtype of output of merge layer is float64, and last layer Dense(softmax) is required 
float32.
how to solve?

**Comment by keunwoochoi** [comment]
Hm, probably, first `flatten()` mask input, and cast them (int->float) with `cast()` function in [keras backend](https://keras.io/backend/), then concatenate with a proper axis (which would be 1 I guess).

**Comment by wml1993** [comment]
flatten() function is to flatten one layer, what is the purpose
you means concatenating would result become the same  dimensions, the proper axis how to express by code in keras. thx

**Comment by wml1993** [comment]
@ keunwoochoi  it do not work.  the input still float64, do not work. i do not the detail of it.

**Comment by wml1993** [comment]
the K.cast call tf backend but my pc do not use it, rather than theano , i can not install tf on my computer with GPU, have you any suggestion?
