### ISSUE TITLE
load_model causes Python Crashing

### ISSUE THREAD

**Issue by birolkuyumcu** [fchollet/keras#3904]
if i use caffe even only 

> import caffe

causes Python Crashing when

> load_model(...) 

or 

> save_model(...) 

running 
rises eror ; 'Process finished with exit code -1073740940 (0xC0000374)'

load_weights working properly...

my OS = windows 10
python 2.7.x  - Anaconda dist - 64 bit

**Comment by kiritodog** [comment]
I have the same problem, but I solved it now. 
win10, 1080ti, cuda=8.0, cudnn=6.0, keras=2.1.2, tensorflow-gpu=1.3
when I change the version of Python form 3.5.5 to 3.5.2, everything is OK!!!
