### ISSUE TITLE
3 Dimensional weight matrix -> TypeError: Expected int32, got None of type '_Message' instead

### ISSUE THREAD

**Issue by cedias** [fchollet/keras#3909]
Hi,

 i'm trying to replicate the idea from [Generating Text with Recurrent Neural Networks](http://www.cs.utoronto.ca/~ilya/pubs/2011/LANG-RNN.pdf) where the recurrent matrix "change" wrt to the input 1-hot vector.

[Here is the gist of my attempt](https://gist.github.com/cedias/c2b88ad20dfa17378b74f32a5d22caa2)

Which gives two different errors.

In TensorFlow:
`TypeError: Expected int32, got None of type '_Message' instead`

In Theano:
`ValueError: When compiling the inner function of scan (the function called by scan in each of its iterations) the following error has been encountered: The initial state (`outputs_info`in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 1) has 3 dimension(s), while the corresponding variable in the result of the inner function of scan (`fn`) has 3 dimension(s) (it should be one less than the initial state). For example, if the inner function of scan returns a vector of size d and scan uses the values of the previous time-step, then the initial state in scan should be a matrix of shape (1, d). The first dimension of this matrix corresponds to the number of previous time-steps that scan uses in each of its iterations. In order to solve this issue if the two varialbe currently have the same dimensionality, you can increase the dimensionality of the variable in the initial state of scan by using dimshuffle or shape_padleft.` 

I get that in the step function input is processed by batches and that naïvely writing:

```
rec = K.dot(self.REC,i)
 h = K.dot(i,self.INP) + K.dot(hm1, rec )
```

shouldn't work. So i've tried the following: 

```
i = K.expand_dims(i)          #K.reshape(i,(128,10,1))
dot = K.dot(self.REC, i)
dot = K.squeeze(dot,axis=3)
rec = K.transpose(dot)
h = K.dot(i,self.INP) + K.dot(hm1, rec )
```

but I always end up on the same error messages. 
Perhaps there is some framework magic that i'm not grasping ?

**Comment by danielhers** [comment]
I'm getting the same error message with a BatchNormalization layer.
