### ISSUE TITLE
Possible to use Merge layer with Graph API?

### ISSUE THREAD

**Issue by iskandr** [fchollet/keras#391]
Is there any way for a `Merge` layer to work with node names in a `Graph` model? It would be conceptually nice to be able to merge the output of several nodes in a graph without having to associate that merged vector immediately with another node which consumes it.

**Comment by fchollet** [comment]
> It would be conceptually nice to be able to merge the output of several nodes in a graph without having to associate that merged vector immediately with another node which consumes it.

You could achieve the same with a linear Activation layer. It does nothing, it's effectively an empty node.

> Is there any way for a Merge layer to work with node names in a Graph model?

That won't work. The best we could do if here would be to make the layer argument in `add_node` optional.
