### ISSUE TITLE
is there any sliding cnn + LSTM + CTC implement ?

### ISSUE THREAD

**Issue by xylcbd** [fchollet/keras#3910]
the network should like this : 

![cnn-lstm-ctc](https://cloud.githubusercontent.com/assets/3643991/18950322/e26f30e8-8671-11e6-8c7d-215080dcdf1b.png)

thx!

**Comment by carlthome** [comment]
Perhaps you'd be interested in this: https://github.com/fchollet/keras/pull/3906
