### ISSUE TITLE
Unable to save weights and reload them in another model via JSON

### ISSUE THREAD

**Issue by sujitpal** [fchollet/keras#3927]
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by sujitpal** [comment]
Steps to reproduce: add following lines to end of keras/examples/babi_memnn.py to save the JSON and model weights to files. Reason I am using this example is because I have similar network (with Merge layers) and this is self contained (pulls its own data, etc) so its easy to run.

```python
answer.save_weights("/tmp/babi_memnn_copy.h5")
with open("/tmp/babi_memnn_copy.json", "wb") as fjson:
    fjson.write(answer.to_json())
```

Run the code, and once it completes attempt to run the following code to retrieve the model.

```python
from keras.models import model_from_json

with open("/tmp/babi_memnn_copy.json", "r") as fjson:
    model = model_from_json(fjson.read())
model.load_weights("/tmp/babi_memnn_copy.h5")
```

Gives following exception:
```
Using Theano backend.
Traceback (most recent call last):
  File "reload_babi_memnn_copy.py", line 5, in <module>
    model.load_weights("/tmp/babi_memnn_copy.h5")
  File "/Users/palsujit/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 2500, in load_weights
    self.load_weights_from_hdf5_group(f)
  File "/Users/palsujit/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 2552, in load_weights_from_hdf5_group
    str(len(flattened_layers)) + ' layers.')
Exception: You are trying to load a weight file containing 5 layers into a model with 6 layers.
```

Also tried with YAML files, same error message.

Since the reason one would train a model is to be able to use it in another process to do predictions, it seems an important functionality.

Strangely enough, when I try a slightly modified version of the snippet in [Issue 2281](https://github.com/fchollet/keras/issues/2281) as follows:

```python
from keras.models import Sequential, model_from_json
from keras.layers import *

model = Sequential()
model.add(Convolution2D(32, 5, 5,
                        border_mode='valid',
                        input_shape=(3, 216, 384)))
model.add(Activation('relu'))
model.add(Convolution2D(32, 5, 5))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Convolution2D(64, 3, 3, border_mode='valid'))
model.add(Activation('relu'))
model.add(Convolution2D(64, 3, 3))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(8))
model.add(Activation('relu'))
model.add(Dropout(0.))

model.add(Dense(9))
model.add(Activation('linear'))

model.save_weights('test.h5')
config = model.to_json()
open("test.json", "wb").write(config)
```

followed by an attempt to reconstruct it from the h5 and json...

```python
from keras.models import Sequential, model_from_json
from keras.layers import *

config = open("test.json", "rb").read()
model = model_from_json(config)
model.load_weights('test.h5')
```

This succeeds without any exception being thrown.

**Comment by sujitpal** [comment]
Closed by mistake, sorry, reopening.

**Comment by vrodionovpro** [comment]
Man, just try

```python
model.save(file)
m = load_model(file)

```
for save or load model. It save compiled model with weights and you don't need additional working with weights.

**Comment by sujitpal** [comment]
Thanks for the answer @vrodionovpro. Unfortunately it didn't help. I get identical behavior with this as I reported originally.

I replaced the snippet in babi_memnn.py with the following:

```python
answer.save("/tmp/babi_memnn_copy.model")
```

and now my corresponding code to load this back from disk looks like this:

```python
from keras.models import load_model

model = load_model("/tmp/babi_memnn_copy.model")
print(model)
```

Building the model works without complains as before, but when I try to get the model back, I get the same exception.

```
Using Theano backend.
Traceback (most recent call last):
  File "reload_babi_memnn_copy.py", line 16, in <module>
    model = load_model("/tmp/babi_memnn_copy.model")
  File "/Users/palsujit/anaconda/lib/python2.7/site-packages/keras/models.py", line 131, in load_model
    model.load_weights_from_hdf5_group(f['model_weights'])
  File "/Users/palsujit/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 2552, in load_weights_from_hdf5_group
    str(len(flattened_layers)) + ' layers.')
Exception: You are trying to load a weight file containing 5 layers into a model with 6 layers.
```

I did a pip install as required by the issue reporting pre-requisites and my Keras version is 1.1.0 and theano version is 0.9.0dev2.dev-dab0b393a743331c179916680a2fd5ab45759d81.

Thanks.

**Comment by sujitpal** [comment]
I rolled back to the following stable versions according to [this post](https://github.com/philferriere/dlwin): Theano 0.8.5 and Keras 1.0.5 but still no luck. However, I did a little bit of debugging that might be useful, so putting it here:

I tried matching model.flattened_layers and h5py.File.attrs["layer_names"] since that was what the error message was looking at:

```
layer_names      model.flattened_layers                                                      variable in code
------------   --------------------                                                    --------------
'embedding_1'  <keras.layers.embeddings.Embedding at 0x117bea150>  input_encoder_m
'dropout_1'       <keras.layers.core.Dropout at 0x117e3f590>                   input_encoder_m
'embedding_2'  <keras.layers.embeddings.Embedding at 0x117e76050>  question_encoder
'dropout_2'       <keras.layers.core.Dropout at 0x117ef5450>                    question_encoder
'embedding_3'  <keras.layers.embeddings.Embedding at 0x117f1df10>   input_encoder_c
'dropout_3'       <keras.layers.core.Dropout at 0x117f315d0>                   input_encoder_c
'permute_1'      <keras.layers.core.Permute at 0x117fb8090>                   response
                        <keras.layers.embeddings.Embedding at 0x117fb8210>  
                        <keras.layers.core.Dropout at 0x117fc35d0>
'lstm_1'             <keras.layers.recurrent.LSTM at 0x117fc3f90>                 answer
'dropout_4'       <keras.layers.core.Dropout at 0x118250350>                  answer
'dense_1'          <keras.layers.core.Dense at 0x118249890>                      answer
'activation_1'    <keras.layers.core.Activation at 0x118250510>                answer
```

There are 3 merges in this model, match = (input_encoder_m dot question_encoder), response = (match plus input_encoder_c) and answer = (response concat question_encoder), which I am guessing flattened_layers does not list.

However, there is one embedding+dropout layer that are listed in flattened_layers but not in layer_names. The model.summary() output shows that these correspond to repeats of embedding_2 and dropout_2, which is the RHS of the 3rd Merge operation.

So perhaps we need to replace the check with whatever the model.summary() is doing to get these layers?

**Comment by sujitpal** [comment]
I did some more google searches following the above, and came across [Issue 1508](https://github.com/fchollet/keras/issues/1508), where the OP (@ymcui) explains the (similar) problem better, and finally concludes that he can use the Graph model instead. That prompted me to look at the Graph model (which is deprecated and replaced by the functional API). I was able to successfully save and load models using the functional API.

I have put up my [modified code for examples/babi_memnn.py using the functional API](https://gist.github.com/sujitpal/71601f8d672fdb051588add5140880ef) in the gist here in case it is useful to someone.

So I have a workaround, **please advise if I should close the bug** or if you would prefer to fix it in the Sequential model as well. OTOH, if users are supposed to use the Functional API instead of the Sequential API once inputs are reused, then perhaps this should be reflected in the documentation.

**Comment by slychief** [comment]
I have the same problem with an adapted InceptionV3 model based on the application-classes in keras 1.2.0 with up-to-date theano:

```python
from keras.layers import Dense, Input, Flatten, GlobalAveragePooling2D
from keras.models import Model
from keras.applications.inception_v3 import InceptionV3
from keras.layers.core import Dense, Activation, Dropout, Flatten

base_model = InceptionV3(weights='imagenet', include_top=False, input_shape=(3, 256, 200))

top = GlobalAveragePooling2D(name='flatten')(base_model.output)
top = Dense(1024, activation='relu')(top)
top = Dropout(0.2)(top)
top = Dense(1024, activation='relu')(top)
top = Dropout(0.5)(top)
top = Dense(output_units, activation='sigmoid', name='predictions')(top)

model = Model(base_model.input, top, name='vgg16')

for layer in base_model.layers:
	layer.trainable = False
```
I saved the models in both possible ways:
```python
model.save('model.h5')

with open('model.json', "w") as json_file:
	json_file.write(model.to_json())

model.save_weights('model_weights.h5')
```
and loaded them accordingly:
```python
# full model
model = load_model('model.h5')

# partial loading
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

loaded_model.load_weights("model_weights.h5")
```
Either way I get the same error message:

```
ValueError: You are trying to load a weight file containing 191 layers into a model with 3 layers.
```

**Comment by slychief** [comment]
I just tested it with a smaller network consisting of 3 convolutional and one fully connected layer and it worked. The problem seems to be related to the applications module. Maybe it would be better to move this into a new issue.

**Comment by nicholas-tien** [comment]
@slychief I came across the same problem as you.It says You are trying to load a weight file containing 16 layers into a model with 3 layers. Have you found the solution?

**Comment by slychief** [comment]
No, but it seems to be a problem with the applications module. I can store and load my own models, but not those using pre-trained imagenet weights.


Von: Nicholas-tien [mailto:notifications@github.com]
Gesendet: Montag, 6. März 2017 16:58
An: fchollet/keras <keras@noreply.github.com>
Cc: Schindler Alexander <Alexander.Schindler@ait.ac.at>; Mention <mention@noreply.github.com>
Betreff: Re: [fchollet/keras] Unable to save weights and reload them in another model via JSON (#3927)


@slychief<https://github.com/slychief> I came across the same problem as you.It says You are trying to load a weight file containing 16 layers into a model with 3 layers. Have you found the solution?

**Comment by nicholas-tien** [comment]
Hope someone can solve it.
