### ISSUE TITLE
Graph merge issue

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#393]
Hey, so I'm trying to build a graph that has two nodes that eventually merge into one node. All recurrent nodes, of course :P 

```python
graph.add_node(SimpleRNN(input_dim=256, output_dim=128, activation='sigmoid', return_sequences = True), 
			   name='outlayer0', 
               inputs=['inlayer0','inlayer1'],
               merge_mode='concat'
               )
```

Which leads to the inevitable error:

```
Apply node that caused the error: Reshape{2}(InplaceDimShuffle{1,0,2}.0, MakeVector.0)
Inputs types: [TensorType(float32, 3D), TensorType(int64, vector)]
Inputs shapes: [(99, 1, 256), (2,)]
Inputs strides: [(1024, 1024, 4), (8,)]
Inputs values: ['not shown', array([ 99, 128])]
```

Now, it works fine with merge_mode='sum' and the lower input size. But for some reason the merging fails. Both the input sizes are 128 each. Ideas?

**Comment by fchollet** [comment]
Can you share a full code sample to reproduce this?

**Comment by lemuriandezapada** [comment]
Yes, sorry. I keep doing that :)))
Here's a quick cropped up example. Just replace merge_mode with 'sum' (and of course the input size for l3) and it starts training

```python
import keras
import numpy as np
from keras.models import Sequential, Graph
from keras.layers.core import Dense, Activation
from keras.layers.recurrent import SimpleRNN
from keras.optimizers import RMSprop
graph=Graph()

graph.add_input(name='input', ndim=3)
graph.add_node(SimpleRNN(input_dim=10, output_dim = 128,return_sequences = True), name='l1', input = 'input')
graph.add_node(SimpleRNN(input_dim=128, output_dim = 128,return_sequences = True), name='l2', input = 'l1')
graph.add_node(SimpleRNN(input_dim=256, output_dim = 128,return_sequences = True), name='l3', inputs = ['l1','l2'], merge_mode = 'concat')
graph.add_node(Dense(128, 10), name='final', input='l3')
graph.add_output(name='output', input='final')
opt = RMSprop(lr=0.001, rho=0.9, epsilon=1e-6)
graph.compile(loss={'output': 'mse'}, optimizer=opt)
data = np.random.randn(10,10,10)
history = graph.fit({'input':data, 'output':data}, nb_epoch=1)
```

**Comment by fchollet** [comment]
I am able to run your snippet without issue on both CPU and GPU. I believe this would be an instance of a longstanding Theano bug that is known to occur with the Merge layer in concat mode on older Theano versions. 

Make sure you update your version of Theano.

**Comment by lemuriandezapada** [comment]
Indeed, it appears that the pip version of theano isn't up to date and you definitely need to install from source. It's fixed now, thanks.

**Comment by phreeza** [comment]
@fchollet do you know what the minimum version of theano that fixes this is? Maybe I can add a warning to this effect on initial import...
