### ISSUE TITLE
Theano backend will not work on AWS Ubuntu:14.04

### ISSUE THREAD

**Issue by roestigraben** [fchollet/keras#3936]
Hello, 
I am in real troubles here. The reference is AWS EC2 Ubuntu:14.04 instance with all my packages installed including Keras, Theano, Tensorflow and the rest of the more standard imports.

My project should run on Theano backend.
In my files, I preceeded the 

`import keras ...` 

or 

`from keras import ....` 

with the line

`os.environ['KERAS_BACKEND']='theano',`

also, I changed the keras.json in the .keras directory to theano as backend. 

From interactive Python session, I can import both theano or tensorflow without problems depending on the os.environ parameter.
But the I want to run my Python files from a flask app and here Theano does not work while Tensorflow is nicely imported. The app is just waiting (no print of 'using theano backend' shows up.

Can anybody give me a hint please

thanks a lot
Peter

**Comment by nouiz** [comment]
The app probably use a different environment then your default environment.
Print the os env var in it. You probably need to define it elsewhere. I
recall someone else fixing this problem like that. Maybe the flask app
allow to define env var in its configuration.

**Comment by mokhoo** [comment]
I have the same problem, it seems as if it hangs up in the import keras line, though it works in the terminal when I use ssh.

Have you solved this problem?
