### ISSUE TITLE
Unable to Call model.predict_classes()

### ISSUE THREAD

**Issue by ritchieng** [fchollet/keras#3938]
I can do the the following:
`predictions = model.predict(X_test, verbose=1)`

However when I do the following:
`model.predict_classes(predictions, verbose=1)`

I've an error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-260-2cb2ec2aa78f> in <module>()
----> 1 model.predict_classes(predictions, verbose=1)

AttributeError: 'Model' object has no attribute 'predict_classes'

```

I am unable to predict anything with model.predict as it seems to output a np array of very small floating digits. My [notebook (view to the end)](https://github.com/ritchieng/gloqo/blob/master/NumNum/project.ipynb).

**Comment by robertomest** [comment]
From what I've seen the `predict_classes` method is exclusive to the Sequential class. How is your network output? It is usual to have softmax on the end, so your outputs would be normalized.

**Comment by DanlanChen** [comment]
Could you do model.predict_classes(x_test,verbose=1)

**Comment by mongoose54** [comment]
I am getting the same error with a non-sequential network

**Comment by ozabluda** [comment]
Answered in https://github.com/fchollet/keras/issues/2524#issuecomment-218590463

**Comment by amal2121** [comment]
Try this
from sklearn.metrics import accuracy_score
accuracy_score(y_test, np.argmax(NN.predict(X_test), axis=-1))
