### ISSUE TITLE
Input, InputLayer, Embedding, Merge does not import

### ISSUE THREAD

**Issue by oakkas** [fchollet/keras#3951]
Hey all,
I have some import on my code such as from keras.layers.core import Input, Merge, ELU, InputLayer, and these were working just couple days ago. When I wanted to run it again, i saw it does not work anymore. I saw there has been a recent update so where can I find these in the updated version. Especially InputLayer was useful.

Thanks
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [X ] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [ X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by robertomest** [comment]
This seems to work for me: `from keras.layers import Input, Merge, ELU, InputLayer`
