### ISSUE TITLE
Out of memory after 4 epochs

### ISSUE THREAD

**Issue by yxchng** [fchollet/keras#3954]
<img width="1188" alt="screen shot 2016-10-04 at 10 24 46 am" src="https://cloud.githubusercontent.com/assets/10518587/19060696/ea4d877a-8a1c-11e6-9396-2d706e4e2f17.png">

I am using fit_generator for this problem and am wondering why i will face memory problem at the 5th epoch. Even if garbage collection takes time, the memory used for epoch 1 should be released by the time I reach the 5th epoch. Does anyone happen to know why?

**Comment by DanlanChen** [comment]
I do not know why it crashes on the 5th,  but how much memory do you have, how much data do you have

**Comment by yxchng** [comment]
12gb pascal titan x

**Comment by DeanDon** [comment]
I get the same problem,did you solve this problem yet?

**Comment by yxchng** [comment]
nope
