### ISSUE TITLE
Multi outputs

### ISSUE THREAD

**Issue by shaikaz** [fchollet/keras#3969]
Hi,

I trained a model with more then one output, a gave names to all layers including the output layers. I passed the data to the model using dictionary to both input and output by the names I gave. When I use the  model.predict()  (with batch size 1) function the output is an array with length as the size of the number of outputs as desired, but with no names. I wish to see the output as an outputs with the names that I gave. Can someone help me with this issue?

Thanks,
Shai

**Comment by dieuwkehupkes** [comment]
One easy way of doing this is just match it up with the names of the output layers, that you can find with the method output_layers(). 

So for instance, for a model called m and input X do something like this:

```
names = [output.name for output in m.output_layers]
predictions = m.predict(X) 
print '\n'.join(['%s: %s' % (name, prediction) for name, prediction in zip(names, predictions)])
```

Hope that helps

**Comment by shaikaz** [comment]
Thanks @dieuwkehupkes, 
So just to make sure, the order of  'names', as you defined, is in the same order as  'predictions' regard to the model output?

**Comment by dieuwkehupkes** [comment]
yup!

**Comment by shaikaz** [comment]
Thanks again @dieuwkehupkes ! :)
