### ISSUE TITLE
Unpooling using "bed of nails"

### ISSUE THREAD

**Issue by libfun** [fchollet/keras#3973]
Hello, I was wondering if there is a need for implementation of "bed of nails" in UpSampling layers for convolutional autoencoders?

Right now the UpSampling only repeats the value of each element so

```
[[1, 2], 
 [3, 4]] 
```

becomes 

```
[[1, 1, 2, 2], 
 [1, 1, 2, 2],
 [3, 3, 4, 4],
 [3, 3, 4, 4]]
```

while "bed of nails" upsamples it to

```
[[1, 0, 2, 0], 
 [0, 0, 0, 0],
 [3, 0, 4, 0],
 [0, 0, 0, 0]]
```

Examples of usage of "bed of nails" in autoencoders are:
https://arxiv.org/abs/1411.5928
https://arxiv.org/abs/1506.02753
https://arxiv.org/abs/1602.02644

**Comment by clauslang** [comment]
Any news on this one? I vote for it!

**Comment by clauslang** [comment]
On second thought, when used together with a convolution for upsampling, like in https://arxiv.org/abs/1411.5928, isn't 'bed of nails' + convolution equivalent to transpose convolution with stride 2, as explained in https://towardsdatascience.com/types-of-convolutions-in-deep-learning-717013397f4d? I'm fairly new to CNNs, so any hints would be appreciated. @libfun

**Comment by libfun** [comment]
@clauslang, as far as I understood the post, it is explained that they are not numerically the same, but would produce tensors of the same shape. I currently use transposed convolutions for this task.
