### ISSUE TITLE
ValueError: negative dimensions on Linux but not OS X

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#3976]
Hi,

I've installed the last version of Theano and Keras because I want to build CNN that takes color images as input.
On macos X, everything works fine, I can create and train the CNNs.
But on CentOS I have the following error:
    `Traceback (most recent call last):`
    `File "HEsi_main4.py", line 40, in <module>
    model = CNNs.Model31(dataset, labels, nbEpoch, BatchSize)`
    `File "../HEsi_CNNs.py", line 38, in Model31
    model.add(PReLU(init='zero', weights=None))`
    `File "/eppec/storage/sw/conda/envs/tensorflow/lib/python2.7/site-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])`
    `File "/eppec/storage/sw/conda/envs/tensorflow/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])`
    `File "/eppec/storage/sw/conda/envs/tensorflow/lib/python2.7/site-packages/keras/layers/advanced_activations.py", line 67, in build
    name='{}_alphas'.format(self.name))`
    `File "/eppec/storage/sw/conda/envs/tensorflow/lib/python2.7/site-packages/keras/initializations.py", line 97, in zero
    return K.zeros(shape, name=name)`
    `File "/eppec/storage/sw/conda/envs/tensorflow/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 116, in zeros
    return variable(np.zeros(shape), dtype, name)`
    `ValueError: negative dimensions are not allowed`

The error is generated immediately at the beginning of the code/model, by the line containing the Prelu:
    `model = Sequential()`
    `model.add(GaussianNoise((0.004),input_shape=(3, 52, 52)))`
    `model.add(Convolution2D(12, 7, 7, border_mode='valid'))`
    `model.add(PReLU(init='zero', weights=None))`

In order to compile and run on linux, I've to add dim_ordering='th' in all the Convolution Layers, but then the generated network contains three times more weights on Linux than macos X.

Any idea why I have such different behavior on mac and linux?

**Comment by DanielCWard** [comment]
Hi @FiReTiTi
I had the same problem running a network on windows and Linux.
Check your keras config files between your two systems at: ~/.keras/keras.json
Setting dim_ordering='th' is overwriting what is set in the config file so it is likely that on your Linux machine your config file has "image_dim_ordering": "tf" and you will need "image_dim_ordering": "th"

Info about the config file:
https://keras.io/backend/
Info about that flag argument for the 2DConvolutional Layer
https://keras.io/layers/convolutional/

Hope this fixes your problem!

**Comment by FiReTiTi** [comment]
Hi Daniel,
thank you so much for your answer, that was it!!!
TO be extremely exact, nothing was specified into the kerns.json on the linux cluster, so I guess that the parameter "tf" was used by default.
Thanks again!
