### ISSUE TITLE
Bad performance for example/image_ocr.py

### ISSUE THREAD

**Issue by guohengkai** [fchollet/keras#3980]
When with newly keras, Theano and Tensorflow, the Norm. ED of image_ocr is 0.577(TF)/0.622(TH) after 50 epoch. But the performance listed in this file is:

 Norm. ED
## Epoch |   TF   |   TH

```
10   0.072    0.272
20   0.032    0.115
30   0.024    0.098
40   0.023    0.108
```

Is there anything wrong with the codes? Or how to replicate the results? Thanks.

**Comment by mbhenry** [comment]
This example is very sensitive so it wouldn't surprise me if some small change affected convergence.  One of my long term goals is to figure out how to get more consistent results.  

With my slightly out of date forked repo (which is based on Keras 1.0.7)  and v0.9.0-15-gcbfd278 commit of TensorFlow, I get close to the above results. I'll update Keras and Tensorflow and see if I can spot what breaks it.

**Comment by rizkiarm** [comment]
Any update on this?

**Comment by mbhenry** [comment]
see https://github.com/fchollet/keras/pull/4790
