### ISSUE TITLE
Slicing layers from a pre-trained Model

### ISSUE THREAD

**Issue by apapiu** [fchollet/keras#3988]
Say I have a pertained model like the VGG16. If I want to select only the first few convolutional blocks I can so something like:

```
from keras.applications import VGG16
vgg16 = VGG16(include_top=False, input_tensor=input)

conv_output = vgg16.get_layer("block4_pool").output 
feature_extractor = Model(vgg16.input, conv_output)
```

Is there a way to use the same API to slice a middle part of a model (including weights) ? I've tried something like:

```
model_top = Model(input = vgg16.get_layer("block5_conv1").input, 
                  output=vgg16.get_layer("block5_conv3").output)
```

but got an error:

```
Exception: Graph disconnected: cannot obtain value for tensor input_6 at layer "input_6". The      following previous layers were accessed without issue: []
```

**Comment by robertomest** [comment]
I don't think you can do that because it would involve changing the graph which, from what I understand, is not possible (at least in tensorflow). What you could to is, instead of get the tensors, create an input tensor and them apply the layers to it in order. If you use the same layers, the weights will be shared and it should work like you expect it to.

**Comment by apapiu** [comment]
I couldn't find a way either but you're right @robertomest, adding them one layer at a time is going to do it.

Something like this:
```{python}
#adding the last conv block from vgg and one hidden layer on top of that:
input2 = Input(shape=(512, 9, 9))  #pick whatever the output of the previous model is
x = vgg16.get_layer("block5_conv1")(input2)
x = vgg16.get_layer("block5_conv2")(x)
x = vgg16.get_layer("block5_conv3")(x)
x = vgg16.get_layer("block5_pool")(x)
x = Flatten()(x)
x = Dense(512, activation="relu")(x)
x = Dropout(0.5) (x)
preds = Dense(1, activation="sigmoid")(x)

model_top = Model(input2, preds)
```
