### ISSUE TITLE
Bug in 'same' border

### ISSUE THREAD

**Issue by loyeamen** [fchollet/keras#399]
Hi,

+            clip_row = (self.nb_row - 1) // 2
+            clip_col = (self.nb_col - 1) // 2
+            output = output[:, :, clip_row:-clip_row, clip_col:-clip_col]

In case of clip_row or  clip_col are 1 (1D input), there will be a crash.
Can you please fix it?

Thanks

**Comment by fchollet** [comment]
Fixed...
