### ISSUE TITLE
Run one model on cpu, one on gpu?

### ISSUE THREAD

**Issue by ducle90** [fchollet/keras#3992]
For my current training script, I need to use 2 RNN models. One performs both forward and backward passes, and one only performs forward pass. My GPU (4 GB) has enough memory for only one model. I'd like to run the forward-only model in CPU, and the other model in GPU. Is this at all possible?

**Comment by carlthome** [comment]
I guess it should be (soon at least?): https://github.com/fchollet/keras/pull/3582

**Comment by carlthome** [comment]
Also, if the models have absolutely nothing to do with each other aside from reusing the latest weights, obviously you could just start two separate Python processes. Just make sure to dump down the weights to file with model.save and use model.load in the forward-only model before doing predictions.

**Comment by ducle90** [comment]
Great, I'm tracking #3582 now! What you suggested won't work for me because the two models are completely different, and reloading weights repeatedly is too expensive. Thanks though!
