### ISSUE TITLE
How the matrix be merged when mode  is dot?

### ISSUE THREAD

**Issue by wdl000001** [fchollet/keras#4000]
code in Merge layer:

```
        elif self.mode == 'dot':
            l1 = inputs[0]
            l2 = inputs[1]
            output = K.batch_dot(l1, l2, self.dot_axes)
            return output
```

What did it do in "K.batch_dot"?

**Comment by cchhdd** [comment]
could u tell me how u find this code?I searched for a long time in keras/layers/core.py,but found noting```wish your help ,thx

**Comment by wdl000001** [comment]
@cchhdd it's in keras/engine/topology.py

**Comment by crowsonkb** [comment]
It's a batchwise dot product operation. The documentation for it is [here](https://keras.io/backend/#batch_dot).

**Comment by cchhdd** [comment]
@wdl000001 oh...it's embarassed...haha,thank u

**Comment by cchhdd** [comment]
@crowsonkb thanks a lot,it really helps me
