### ISSUE TITLE
input's dimentional error

### ISSUE THREAD

**Issue by Tcorpion** [fchollet/keras#4002]
I am new in Keras. Even my following code is referenced from https://keras.io/ ,  i still do not know how to fix it. Anyone can help me?
```
# this return a tensor
inputs = Input(shape=(784,),dtype='float32')
# a layer instance is callable on a tensor, and returns a tensor
X=Dense(64,activation='relu')(inputs)
X=Dense(64,activation='relu')(X)
predictions=Dense(10,activation='softmax')(X)
model=Model(input=inputs,output=predictions)

print('Compiling')
#sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])             

print('Loading data')
train_X,train_Y=load_minist.load_data_V2('training.pkl')
valid_X,valid_Y=load_minist.load_data_V2('validation.pkl')
early_stop = EarlyStopping(monitor='val_acc', patience=2, verbose=1, mode='max')

print('Begin Training')
model.fit(train_X,train_Y,
          batch_size=32,nb_epoch=20,
          validation_data=(valid_X,valid_Y),
          callbacks=[early_stop])
```

the running error is : 
Exception: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 arrays but instead got the following list of 50000 arrays: [array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.      ...
Process finished with exit code 1

// The shape of data is as following
// print np.shape(train_X)
// (50000, 784)
// print np.shape(train_Y)
// (50000, 10)
// print np.shape(valid_X)
// (10000, 784)
// print np.shape(valid_Y)
// (10000, 10)

**Comment by dieuwkehupkes** [comment]
If you really input the arrays like thas that have the shapes as you are printing I think you shouldn't get an error. I tried it at my system (but with just random errors with the same shape) and then went fine.

Are you sure that train_X and train_Y have that shape? because your error message says that your input is not a numpy array but a list, containing a numpy array. What is this function you use to generate your data? I couldn't find it.

Also are you sure you defined the model exactly as you wanted it, you have a layer that takes itself as input! (and then another layer that takes this layer as input)

**Comment by Tcorpion** [comment]
I fixed  it by adding ''np.array" for train_X , train_Y ,  valid_X  and valid_Y.
```
model.fit(np.array(train_X),np.array(train_Y),
          batch_size=32,nb_epoch=20,
          validation_data=(np.array(valid_X),np.array(valid_Y)),
          callbacks=[early_stop])
```
@dieuwkehupkes ,thanks for you!

**Comment by siddharthkale97** [comment]
> I fixed it by adding ''np.array" for train_X , train_Y , valid_X and valid_Y.
> 
> ```
> model.fit(np.array(train_X),np.array(train_Y),
>           batch_size=32,nb_epoch=20,
>           validation_data=(np.array(valid_X),np.array(valid_Y)),
>           callbacks=[early_stop])
> ```
> 
> @dieuwkehupkes ,thanks for you!

I was getting the same error and was solved by adding numpy.array(train_x) in model.fit()

**Comment by nav9** [comment]
Dear Keras developers. If it's possible to write a few lines of code to automatically convert arrays to numpy arrays instead of throwing this error, please write it.
