### ISSUE TITLE
get mid-model activations is very slow

### ISSUE THREAD

**Issue by IraZarI** [fchollet/keras#4006]
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hey,
i implemented this tool to get the activations of a net for a specific layer like suggested in #41 (and many more)

```
def get_activations1(model, layer, X_batch):
    if layer==-1: #InputLayer returns data itself
        return [X_batch]
    else: #Output of Layer X
        get_activations = K.function([model.layers[0].input, K.learning_phase()], [model.layers[layer].output])
        activations = get_activations([X_batch,0])
        return activations    
```

so everythings works flawless and i love this functionallity, but it has one gamebreaker for me: Speed.
this Calculation for a given model with 3-4 Layers (20 neurons width each, Dense) takes about half of a second.
Since i want to work with the activations and do some (many) calculations (like 240000) this can´t do the trick.

is there a way to speed up things?
thank you

**Comment by robertomest** [comment]
You could maybe try reusing the `get_activations` function. Something like this:
```
def make_get_activations(model, layer):
    get_activations = K.function([model.layers[0].input, K.learning_phase()], [model.layers[layer].output])
    return get_activations

get_activations = make_get_activations(model, layer)
activations = get_activations(X_batch) # Call this many times
```

**Comment by Abhinav-Duggal** [comment]
+1, Speed is also a problem for me. Also is there a way to send batch test data (like multiple images, say 100K) to this function and get activations of a layer for all the 100K images in a list? Will that be faster due to some matrix multiplication perhaps (not sure)? I have seen some answers where u send a batch test data but end up iterating over them when passed as arguments to the K.function which I would think is same as calling get_activations many times with a list of images? Please help..

**Comment by vinayakumarr** [comment]
from keras import backend as K

def get_activations(model, layer, X_batch):
get_activations = K.function([model.layers[0].input, K.learning_phase()], model.layers[layer].output)
activations = get_activations([X_batch,0])
print(activations)
return activations

my_featuremaps = get_activations(cnn, 1, ([X_train[:10], 0])[0])
np.savetxt('featuremap.txt', my_featuremaps)

The above code is generating the below error with TensorFlow as backend

TypeError: outputs of a TensorFlow backend function should be a list or tuple.

Actually, this works fins with theano as backend

**Comment by vinayakumarr** [comment]
from keras import backend as K

def get_activations(model, layer, X_batch):
get_activations = K.function([model.layers[0].input, K.learning_phase()], model.layers[layer].output)
activations = get_activations([X_batch,0])
print(activations)
return activations

my_featuremaps = get_activations(cnn, 1, ([X_train[:10], 0])[0])
np.savetxt('featuremap.txt', my_featuremaps)

The above code is generating the below error with TensorFlow as backend

TypeError: outputs of a TensorFlow backend function should be a list or tuple.

Actually, this works fins with theano as backend

**Comment by jona-sassenhagen** [comment]
I have the same problem - retrieving hidden layer activations takes as long as training the model. It would be very cool if there was an efficient way of retrieving hidden layer activity for multiple layers and multiple inputs.

**Comment by alyato** [comment]
@IraZarI @jona-sassenhagen @robertomest  
thanks.
I have `two input` and  `one output` ,want to extract feature map.
I find the issuse #4600 is well for rnn. Im using the cnn.
If you guys can check #4600, it would be nice.
The following code not works.

> def getFeatureMap(model,layer,X_batch):
featureMap=K.function([model.layers[0].input,model.layers[0].input],[model.layers[layer].output])
gmp = featureMap([X_batch,0])
return gmp

how to rewrite it? thanks.
