### ISSUE TITLE
'shape_invariants ' : error from tensorflow backend

### ISSUE THREAD

**Issue by kivijoshi** [fchollet/keras#4008]
For my model, below is the first layer. The input is of shape (10, 3, 480, 640)

model.add(TimeDistributed(
Convolution2D(16, 8, 8,subsample=(4, 4), border_mode="same", init="he_normal")))
model.add(Activation("relu"))

I getting this error from tensorflow backend
ValueError: The shape for while_3/Merge_2:0 is not an invariant for the loop. It enters the loop with shape (10, 3, 480, 640), but has shape (20, 1, 120, 16) after one iteration. Provide shape invariants using either the `shape_invariants` argument of tf.while_loop or set_shape() on the loop variables.

**Comment by subramanyam86** [comment]
Same issue running https://github.com/jarfo/kchar with tensorflow backend.

**Comment by ParthaEth** [comment]
Update keras to the latest version or atleat to `Keras 1.1.2`, You may use - `sudo pip install git+git://github.com/fchollet/keras.git --upgrade`
