### ISSUE TITLE
Use Keras

### ISSUE THREAD

**Issue by xvk58** [fchollet/keras#4012]
Can you please provide some information about using Keras for speech recognition?
here are my queries:
1. Do I need a GPU to run?
2. If I need, I have a built in 1GB GPU with my core i3 processor. Will it do?
3. Is there ant video tutorials available to learn?

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [/ ] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [/ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [/ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by IraZarI** [comment]
1. No you dont, It just will take longer.
2. Probably not (in the scale you would want to). Bigger Nets needs bigger GPUs.
3. https://www.youtube.com/watch?v=Tp3SaRbql4k
(4). Implement some toy-Nets to get yourself used to it :)

**Comment by xvk58** [comment]
thanks

**Comment by saicoco** [comment]
@xvk58 , maybe you can use [wavenet](https://github.com/usernaamee/keras-wavenet), it is based on raw audio signal, you will learn something helpful from it, change its arch and it can be used to do speech recognition, or add some `LSTM` or `RNN` module upon it, this is a good idea~, you can try it^_^
