### ISSUE TITLE
 keras callbacks does not seem to work by import

### ISSUE THREAD

**Issue by dorbodwolf** [fchollet/keras#4015]
imported by `from keras.callbacks import Plotter`
when I use callbacks in `.fit()`

```
model.fit(data, label, batch_size=32, nb_epoch=100, shuffle=True, validation_split=0.2, callbacks=[Plotter(show_plot_window=False, save_to_filepath="/tmp/last_plot.png")])

```

it's got `ImportError
`who know why is it?
I will be appreciate.

**Comment by saicoco** [comment]
Hi, there is no `Plotter` in `keras`, I don't find it, you can `import Plotter` from you dir, and create   
`plotter = Plotter(show_plot_window=False, save_to_filepath="/tmp/last_plot.png")`, and then 
```
model.fit(data, label, batch_size=32, nb_epoch=100, shuffle=True, validation_split=0.2, callbacks=[plotter])
```.
Try it~~
