### ISSUE TITLE
Upsampling fails with Atrous Convolution

### ISSUE THREAD

**Issue by longlouisly** [fchollet/keras#4018]
It seems Upsampling2D loses track of image size when it comes after a dilated convolution. The only difference between these two models is the atrous_rate. (I'm using tensorflow 0.11, but the error occurs for both dim_orderings={'th','tf'})

```
K.set_image_dim_ordering('th')     

working_model = Sequential()  
working_model.add(ZeroPadding2D((1,1),input_shape=(3,224,224)))  
working_model.add(AtrousConvolution2D(64,3,3, activation='relu',atrous_rate=(1,1)))  
working_model.add(UpSampling2D(size=(2,2)))  
working_model.summary()  

bug_model = Sequential()  
bug_model.add(ZeroPadding2D((1,1),input_shape=(3,224,224)))  
bug_model.add(AtrousConvolution2D(64,3,3, activation='relu',atrous_rate=(2,2)))  
bug_model.summary()  
bug_model.add(UpSampling2D(size=(2,2)))  
```

Error: notice how the summaries output the correct dimensions for the convolution even though tf shape output does not for the 2nd model.

```
[<tf.Tensor 'zeropadding2d_input_1:0' shape=(?, 3, 224, 224) dtype=float32>]
[<tf.Tensor 'Pad:0' shape=(?, 3, 226, 226) dtype=float32>]
[<tf.Tensor 'Relu:0' shape=(?, 64, 224, 224) dtype=float32>]

Layer (type)                     Output Shape          Param #     Connected to
==========================================================================================
zeropadding2d_1 (ZeroPadding2D)  (None, 3, 226, 226)   0           zeropadding2d_input_1[0
__________________________________________________________________________________________
atrousconvolution2d_1 (AtrousConv(None, 64, 224, 224)  1792        zeropadding2d_1[0][0]
__________________________________________________________________________________________
upsampling2d_1 (UpSampling2D)    (None, 64, 448, 448)  0           atrousconvolution2d_1[0
==========================================================================================
Total params: 1792


[<tf.Tensor 'zeropadding2d_input_2:0' shape=(?, 3, 224, 224) dtype=float32>]
[<tf.Tensor 'Pad_1:0' shape=(?, 3, 226, 226) dtype=float32>]
[<tf.Tensor 'Relu_1:0' shape=(?, 64, ?, ?) dtype=float32>]

Layer (type)                     Output Shape          Param #     Connected to
==========================================================================================
zeropadding2d_2 (ZeroPadding2D)  (None, 3, 226, 226)   0           zeropadding2d_input_2[0
__________________________________________________________________________________________
atrousconvolution2d_2 (AtrousConv(None, 64, 222, 222)  1792        zeropadding2d_2[0][0]
==========================================================================================
Total params: 1792


Traceback (most recent call last):
    bug_model.add(UpSampling2D(size=(2,2)))
File "../keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
File "../keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
File "../keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
File "../keras/layers/convolutional.py", line 1336, in call
    self.dim_ordering)
File "../keras/backend/tensorflow_backend.py", line 757, in resize_images
    X.set_shape((None, original_shape[1] * height_factor, original_shape[2] * width_factor, None))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'`
```

where I modified keras.engine.topology.create_node to print out the tensor shapes above:

```
for inbound_layer, node_index, tensor_index in zip(inbound_layers, node_indices, t
            inbound_node = inbound_layer.inbound_nodes[node_index]
            input_tensors.append(inbound_node.output_tensors[tensor_index])
            input_masks.append(inbound_node.output_masks[tensor_index])
            input_shapes.append(inbound_node.output_shapes[tensor_index])

        assert len(input_shapes) == len(input_tensors) == len(input_masks)
+       print (input_tensors)
```

**Comment by ahundt** [comment]
I can confirm this bug. It seems the tests are not catching the issue either. 

conv2d in [tensorflow_backend.py](https://github.com/fchollet/keras/blob/e5529d98fe770019f45b6b5efe7efa88d0dccc4c/keras/backend/tensorflow_backend.py#L2694):


```

    if filter_dilation == (1, 1):
        strides = (1,) + strides + (1,)
        x = tf.nn.conv2d(x, kernel, strides, padding=padding)
    else:
        assert filter_dilation[0] == filter_dilation[1]
        assert strides == (1, 1), 'Invalid strides for dilated convolution'
        x = tf.nn.atrous_conv2d(x, kernel, filter_dilation[0], padding=padding)

```

[test_convolutional.py](https://github.com/fchollet/keras/blob/e5529d98fe770019f45b6b5efe7efa88d0dccc4c/tests/keras/layers/test_convolutional.py#L180):

```
        for subsample in [(1, 1), (2, 2)]:
            for atrous_rate in [(1, 1), (2, 2)]:
                if border_mode == 'same' and subsample != (1, 1):
                    continue
                if subsample != (1, 1) and atrous_rate != (1, 1):
                    continue
```

Dimension test:
```python
# tu pre  shape:  (1, 12, 12, 304) nb_filter:  304
x = AtrousConvolution2D(nb_filters, 3, 3, activation="relu",bias=False, atrous_rate=(2,2))(ip)
# tu post shape:  (1, 8, 8, 304)
```


`± git rev-parse HEAD`
4fa7e5d454dd4f3f33f1d756a2a8659f2e789141

**Comment by ahundt** [comment]
@fchollet @patyork 
it seems the problem in AtrousConvolution2D may be in calculating the output size in [convolutional.py](https://github.com/fchollet/keras/blob/676e227b47865c296d1731270d5f111e1422d1e2/keras/layers/convolutional.py#L801)
```python

    def get_output_shape_for(self, input_shape):
        if self.dim_ordering == 'th':
            rows = input_shape[2]
            cols = input_shape[3]
        elif self.dim_ordering == 'tf':
            rows = input_shape[1]
            cols = input_shape[2]
        else:
            raise ValueError('Invalid dim_ordering:', self.dim_ordering)

        rows = conv_output_length(rows, self.nb_row, self.border_mode,
                                  self.subsample[0],
                                  dilation=self.atrous_rate[0])
        cols = conv_output_length(cols, self.nb_col, self.border_mode,
                                  self.subsample[1],
                                  dilation=self.atrous_rate[1])
```

 which makes a call in [np_utils.py](https://github.com/fchollet/keras/blob/676e227b47865c296d1731270d5f111e1422d1e2/keras/utils/np_utils.py#L99) where the calculation of [output_length](https://github.com/fchollet/keras/blob/676e227b47865c296d1731270d5f111e1422d1e2/keras/utils/np_utils.py#L123) doesn't look right.

```python

def conv_output_length(input_length, filter_size,
                       border_mode, stride, dilation=1):
    """Determines output length of a convolution given input length.
    # Arguments
        input_length: integer.
        filter_size: integer.
        border_mode: one of "same", "valid", "full".
        stride: integer.
        dilation: dilation rate, integer.
    # Returns
        The output length (integer).
    """
    if input_length is None:
        return None
    assert border_mode in {'same', 'valid', 'full'}
    dilated_filter_size = filter_size + (filter_size - 1) * (dilation - 1)
    if border_mode == 'same':
        output_length = input_length
    elif border_mode == 'valid':
        output_length = input_length - dilated_filter_size + 1
    elif border_mode == 'full':
        output_length = input_length + dilated_filter_size - 1
    return (output_length + stride - 1) // stride
```

**Comment by ahundt** [comment]
tf backend also fails to correctly support `border_mode='same'` which the [backend tf atrous convolution call explicitly supports](https://www.tensorflow.org/api_docs/python/tf/nn/atrous_conv2d)

**Comment by ahundt** [comment]
The output dimensions should be calculated as follows from the tf documentation:

- effective height :`filter_height + (filter_height - 1) * (rate - 1)` 
- effective width: `filter_width + (filter_width - 1) * (rate - 1)`

I believe `conv_output_length` should *not* be using `filter_size`, `input_length` and `dilation` in the way it is calculated now, particularly for `same`, and I believe for `valid` as well. I'm not sure about `full`.

**Comment by ahundt** [comment]
hmm... it seems that the atrous convolution only modifies the filter size, to upsample [atrous_conv2d_transpose](https://www.tensorflow.org/api_docs/python/tf/nn/atrous_conv2d_transpose) is required, so I believe @longlouisly you are looking for that? If so I guess that's a new layer that must be added.


Nonetheless, `'same'` for AtrousConvolution2D() remains incorrect because the output tensor width and height dimensions drop by a factor of two when they should remain the same.
[atrous_conv2d_test.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/atrous_conv2d_test.py) is where the TensofFlow unit tests of atrous conv, the transpose versions, and others are located.

**Comment by patyork** [comment]
`same` will not result in the output shape necessarily being equal to the input shape for dilated convolution:

[![image](https://cloud.githubusercontent.com/assets/1304633/23098143/d998235e-f5fb-11e6-9323-bd7ed4d1f7b4.png)](http://deeplearning.net/software/theano_versions/dev/tutorial/conv_arithmetic.html#miscellaneous-convolutions)

**Comment by ahundt** [comment]
In that case this must definitely not be correct:
```
    if border_mode == 'same':
        output_length = input_length
```

**Comment by ahundt** [comment]
@patyork also since your note references theano, the bug I've encountered is with the tf backend, it seems @longlouisly mentions both backends in his first post.

**Comment by patyork** [comment]
Both Theano and TensorFlow handle the change in effective kernel size automatically, such that the border modes are processed correctly.

For example, a dilated conv of kernel shape (3,3) rate 2 is effectively a special convolution of a (5,5) kernel. The effective padding is correctly computed by the backends on the (5,5) sized kernel.

Apologies, the above formula is correct in general, however the backends simply change the calculation to one with a different kernel size and set `d` back to 1. I had never looked at dilated convolutions before.

**Comment by ahundt** [comment]
@longlouisly I believe what you're really looking for is for an atrous transpose convolution, which in tensorflow is [tf.nn.atrous_conv2d_transpose(value, filters, output_shape, rate, padding, name=None)](https://www.tensorflow.org/api_docs/python/tf/nn/atrous_conv2d_transpose). So with Keras what you want is Conv2DTranspose with a dilation rate of (2,2).

https://github.com/tensorflow/tensorflow/issues/4742 contains discussion that clears some things up and may also be the source of the bug mentioned in the original post for this issue #4018.
