### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'layers'

### ISSUE THREAD

**Issue by AnishShah** [fchollet/keras#4020]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

```
In [1]: from keras.models import *
Using TensorFlow backend.

In [2]: model = Sequential()

In [3]: model.summary()
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
Total params: 0
____________________________________________________________________________________________________

In [4]: model = Graph()

In [5]: model.summary()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-9a7881f870d4> in <module>()
----> 1 model.summary()

/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/engine/topology.pyc in summary(self, line_length, positions)
   2687             flattened_layers = self.flattened_layers
   2688         else:
-> 2689             flattened_layers = self.layers
   2690 
   2691         print_summary(flattened_layers, getattr(self, 'container_nodes', None), line_length=line_length, positions=positions)

AttributeError: 'Graph' object has no attribute 'layers'

```
I'm on the latest version of Keras and this happens even if the graph is not empty. If this is a bug and it can be reproduced by others too, then I can try to work on this.

**Comment by crowsonkb** [comment]
`Graph` has been deprecated for a while now. The [functional API](https://keras.io/getting-started/functional-api-guide/) is the current method for constructing arbitrary graphs.
