### ISSUE TITLE
Can't find documentation of keras.layers.Input

### ISSUE THREAD

**Issue by fanyangxyz** [fchollet/keras#4028]
keras.layers.Input is used when constructing keras.models.Model. 
However, I can't find the documentation of keras.layers.Input on the website (https://keras.io/). 
I would like to know the argument of keras.layers.Input, especially the shape argument. 

Thanks!

**Comment by lukovkin** [comment]
You can take look at the docstring in the code - https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1036.
Don't know why it's not on the website documentation.
Spent some time searching for it too.

**Comment by fanyangxyz** [comment]
@lukovkin Thanks a lot for the link!
