### ISSUE TITLE
Accessing Weights Every Iteration

### ISSUE THREAD

**Issue by ritchieng** [fchollet/keras#4054]
Say for MNIST I have 60,000 training points, with a batch size of 100. I would have 600 iterations. I would like to access the weights at every iteration. 

I know I can access the weights with this (for a particular layer). But it is only accessible after it finishes all 600 iterations. 
`model.layers[2].get_weights()[0]` gives a numpy array of the weights.

Any idea?

**Comment by kgrm** [comment]
You could write a custom callback whose `on_batch_end()` method returns the weight tensors, or saves them.

https://keras.io/callbacks/
