### ISSUE TITLE
Convolution2D Dimension Error

### ISSUE THREAD

**Issue by ProgrammerYuan** [fchollet/keras#4056]
Here's my Antoencoder code: 

```
input_img = Input(shape=(1, 2049, 64))
x = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(input_img)
x = MaxPooling2D((2, 2), border_mode='same')(x)
x = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(x)
encoded = MaxPooling2D((2, 2), border_mode='same')(x)

# at this point the representation is (8, 4, 4) i.e. 128-dimensional

x = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(encoded)
x = UpSampling2D((2, 2))(x)
x = Convolution2D(32, 3, 3, activation='relu', border_mode='same')(x)
x = UpSampling2D((2, 2))(x)
decoded = Convolution2D(1, 3, 3, activation='sigmoid', border_mode='same')(x)

autoencoder = Model(input_img, decoded)
autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')

# prepare dataset
train_array = pickle.load(open('train_set2.pkl', 'rb'))
target_array = pickle.load(open('target_set2.pkl', 'rb'))
x_train = np.asarray(train_array, dtype='float32')
x_target = np.asarray(target_array, dtype='float32')
print x_train.shape
print x_target.shape
x_train = np.reshape(x_train, (len(x_train), 1, 2049, 64))
x_target = np.reshape(x_target, (len(x_target), 1, 2049, 64))

x_test = x_train[-438:]
x_train = x_train[:1000]
x_test_target = x_target[-438:]
x_train_target = x_target[:1000]
print x_train.shape
print x_test.shape

# train autoencoder
autoencoder.fit(
    x_train, x_train_target,
    nb_epoch=100,
    batch_size=128,
    shuffle=True,
    validation_data=(x_test, x_test_target),
    callbacks=[TensorBoard(log_dir='/tmp/autoencoder')])`
```

then I got error message below when running fit() function:
`Exception: Error when checking model target: expected convolution2d_5 to have shape (None, 1, 2052, 64) but got array with shape (1000, 1, 2049, 64)`

Please help to indicate what's wrong with my code. from my point of view, my model's structure is symmetrical so there shouldn't be any dimension problem.

Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by keunwoochoi** [comment]
Can you `model.summary()` to check it out exactly in each layer?
