### ISSUE TITLE
Jupyter notebook kernel died (memory shortage)

### ISSUE THREAD

**Issue by csh412** [fchollet/keras#4058]
Hi, 
I have a problem when I use keras model (deep learning library) in jupyter notebook

Before executing code cell, my computer GPU memory is 241 Mib / 8113 MiB
And I executed simple keras model code
![fig2](https://cloud.githubusercontent.com/assets/22813788/19389961/03479dd2-9261-11e6-96cf-06366c280cae.jpg)

After executing above code, GPU memory usage change from 241MB to 7754MB

So, when I run training cell code, jupyter died 
This problem happend again and again... even though I restarted my jupyter notebook..
Strangely, this problem not happend when I run same code in CPU (not using GPU)

Is there any good idea to solve this problem??

**Comment by rohit-patel** [comment]
Has this been resolved? I have similar issues.
