### ISSUE TITLE
performance issues with one of the examples

### ISSUE THREAD

**Issue by Cognitively** [fchollet/keras#406]
I'm running the text-generation LSTM example on an iCore7 machine with 64GB of RAM on Ubuntu, with Python 3.4. No changes to the code except I'm using my own text sample of ~850K characters. One virtual CPU is running the script at 100%, and I have tons of free RAM.

Anyhow, it looks like it'll take ~60K seconds just for Iteration 1 of Epoch 0. Does it sound reasonable or is there a problem on my side?

**Comment by fchollet** [comment]
It is likely that you do not have a BLAS installed. Install OpenBlas, then reinstall Numpy / Theano / Keras. Make sure that all installs can find the path to OpenBlas.
