### ISSUE TITLE
Why my Titan X can't run as fast as I imagine?

### ISSUE THREAD

**Issue by xcmax** [fchollet/keras#4061]
I am using Tian X to train AlexNet. The input is 3*227*227 and when I set the batch_size in fit function, it will break down. As far as I know, Titan X has 12 GB memory. When I use a GPU with 1.5 GB memory, the batch_size can be 64. Why can't I set the batch_size larger than 512?

**Comment by DanlanChen** [comment]
batch size 64 maybe a good choice consider the 64 bit machine .

**Comment by xcmax** [comment]
@DanlanChen Thanks. Actually, my GPU is Tian not Tian X.
