### ISSUE TITLE
MSE question

### ISSUE THREAD

**Issue by HC-2016** [fchollet/keras#4071]
The MSE function defined in objectives.mean_squared_error seems to deal with scalar output. It gets wrong results when output is a tensor with more than one dimension.

**origin**：
def mean_squared_error(y_true, y_pred):
    return K.mean(K.square(y_pred - y_true), axis=-1)

**revision**:
def mean_squared_error(y_true, y_pred):
    if y_true.ndim <= 1:
        return K.mean(K.square(y_pred - y_true), axis=-1)    # for scalar or vector
    else:
        return K.mean(K.sum(K.square(y_pred - y_true), axis=range(1, y_true.ndim)), axis=-1)   # for tensor

**Comment by kgrm** [comment]
No, it produces the correct output when `y_pred` and `y_true` are both 2-dimensional matrices of the same shape - one scalar score per data point.
