### ISSUE TITLE
Container Graph with Sequential as nodes

### ISSUE THREAD

**Issue by PiscesDream** [fchollet/keras#4080]
``` python
  3 import numpy as np
  4 from keras.layers import InputLayer, Dense, Reshape, Merge, Input, Flatten, Permute
  5 from keras.models import Sequential, Model, Graph
  6
  7 if __name__ == '__main__':
  8     m = Sequential([
  9         Dense(10, input_shape=(3,)),
 10         Dense(20),
 11     ])
 12
 13     g = Graph()
 14     g.add_input(name='input', input_shape=(3,))
 15
 16     g.add_node(m, name='seq', input='input')
 17
 18     g.add_output(input='seq', name='o')
 19
 20     g.compile('sgd', {'o':'mse'})
 21
 22     x = np.random.random((10, 3))
 23
 24     g.predict({'input':x})
 25     import ipdb
 26     ipdb.set_trace()
```

I tried to add a Sequence as a node in Graph, and I got `Exception: Layer o has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use`get_output_at(node_index)`instead.` 
Apparently I want to set `get_output_at(1)` as the output of the Graph, does Keras supports that now?

**Comment by EderSantana** [comment]
yeah, keras changed a little bit recently. Graphs are much easier to build with the new functional API. Check it out: https://github.com/fchollet/keras/blob/master/docs/templates/getting-started/functional-api-guide.md
