### ISSUE TITLE
Residual wrapper

### ISSUE THREAD

**Issue by codekansas** [fchollet/keras#4098]
I wrote a relatively simple wrapper that applies the residual function `y = f(x) + x` (by default) or any generic function (using `Merge` layers) that might be useful to other people. I figured I'd create an issue first to see if it was something other people would be interested in including.

Code is [here](https://github.com/codekansas/keras-resnet/blob/master/resnet.py). The repo has some other examples.

**Comment by dbonadiman** [comment]
Hi, can you do a pull request with that? I find it really helpful.
