### ISSUE TITLE
Can't import Graph.

### ISSUE THREAD

**Issue by gbcalsaverini** [fchollet/keras#410]
I installed keras with pip and I'm having an issue trying to create a Graph model:

```python
In [1]: from keras.models import Graph
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-74d2d1fd7bad> in <module>()
----> 1 from keras.models import Graph

ImportError: cannot import name 'Graph'
```
The version I have installed is 0.1.1. Do you guys have any idea what is happening?

**Comment by fchollet** [comment]
Install Keras from the Github source. Pip version is outdated.

**Comment by LopezGG** [comment]
I did an upgrade with the command
 sudo pip install git+git://github.com/fchollet/keras.git --upgrade
I am still having this error :(

**Comment by duonghuuphuc** [comment]
On Keras 1.2.0, I can't import the Graph package, can you use another package to work with this new version of Keras?
