### ISSUE TITLE
plot_loss_callback example doesn't work

### ISSUE THREAD

**Issue by ohadle** [fchollet/keras#4116]
[The `plot_loss_callback` example ](https://keras.io/callbacks/#lambdacallback) doesn't seem to work for me.
When I print the `logs` variable in `on_epoch_end` I get a dict, so previous losses aren't available (and the plot fails due to dimension mismatch).

I'm using `fit_generator` if that's relevant.

**Comment by carlthome** [comment]
Hmm, this one is on me. Sorry. I thought the logs contained the previous epochs too.

Would you care to do a pr and update the documentation so the example works? 

Something like this would do it:
```python
# Plot the loss after every epoch.
import numpy as np
import matplotlib.pyplot as plt

losses = []


def plot_loss(epoch, logs):
    losses.append(logs['loss'])
    plt.plot(np.arange(losses), losses)

plot_loss_callback = LambdaCallback(on_epoch_end=plot_loss)
```
