### ISSUE TITLE
Possible memory issue?

### ISSUE THREAD

**Issue by Ninad998** [fchollet/keras#4129]
I tried to run a model on GTX 950 with Cuda 8 and CuDNN 5.0, not sure if there is a possible memory issue with the different ways to initializing a model.

Original code:
https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py

Edit made:
Changed model into Sequential and added the layer to it rather than create it like the queue mentioned in the original file.

Issue encountered:
- Original code capable to running on the GPU without any issues.
- When model is made into a queue and then compiled it runs out of memory.

Not sure if a sequential model is supposed to occupy more space on GPU or if its a possible memory issue.

**Comment by carlthome** [comment]
Show your changes.

**Comment by Ninad998** [comment]
Original model:
`
embedding_layer = Embedding(nb_words + 1,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                            input_length=MAX_SEQUENCE_LENGTH,
                            trainable=False)
sequence_input = Input(shape=(MAX_SEQUENCE_LENGTH,), dtype='int32')
embedded_sequences = embedding_layer(sequence_input)
x = Conv1D(128, 5, activation='relu')(embedded_sequences)
x = MaxPooling1D(5)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(5)(x)
x = Conv1D(128, 5, activation='relu')(x)
x = MaxPooling1D(35)(x)
x = Flatten()(x)
x = Dense(128, activation='relu')(x)
preds = Dense(len(labels_index), activation='softmax')(x)

model = Model(sequence_input, preds)
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])
`

Edited model:
`
model = Sequential() 
model.add(Embedding(nb_words + 1,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                            input_length=MAX_SEQUENCE_LENGTH,
                            trainable=False))
model.add(Conv1D(128, 5, activation='relu'))
model.add(MaxPooling1D(5))
model.add(Conv1D(128, 5, activation='relu'))
model.add(MaxPooling1D(5))
model.add(Conv1D(128, 5, activation='relu'))
model.add(MaxPooling1D(35))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(len(labels_index), activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['acc'])
`

- Original model runs fine on GTX 950 with 2GB space.
- Edited model runs out of space on the same GPU.

This has led me to believe that maybe a Sequential Model occupies more space than a model made via a queue like structure.

**Comment by carlthome** [comment]
The code you've shared sure looks similar. Please run this after having defined your two respective models and share the two resulting schematics:

```
from keras.utils import visualize_util
visualize_util.plot(model, show_shapes=True, show_layer_names=True)
```

What's floatX in your .theanorc? Are you sure you're not calling the `Sequential()` version with tensors of another dtype than int32?

**Comment by Ninad998** [comment]
@carlthome, after changing the original model to float32 just like the Sequential one, they both manage to run.
Plus the visualization doesn't seem to work because of pydot dependency.

It's sorted I think.
