### ISSUE TITLE
Adapting Yahoo Open_NSFW model to keras 

### ISSUE THREAD

**Issue by ArmenAg** [fchollet/keras#4140]
How would you guys recommend adapting the yahoo opennsfw model (https://github.com/yahoo/open_nsfw) to keras. I tried using MarcBS's code but could not get it to work (https://github.com/MarcBS/keras) 

Any help is appreciated.

**Comment by rohrl** [comment]
+1

**Comment by dribnet** [comment]
note that this port has been done by @kashif though there might be issues with the current implementation: https://github.com/fchollet/deep-learning-models/pull/30

**Comment by kashif** [comment]
I have a new version @dribnet but only with tensorflow weights... I could push that?

**Comment by dribnet** [comment]
sure, I'd appreciate the update (and maybe others would too)!

**Comment by dribnet** [comment]
Hi @kashif - just pinging you again as I'm using your keras open_nsfw for a project currently and would love to get updated tensorflow weights if those are available and work better than [the most current weights path currently found in your open_nsfw branch](https://github.com/kashif/deep-learning-models/commit/0d159a9fde78c93b93038947abc3732657bb3ef1).

**Comment by kashif** [comment]
@dribnet here you go:

https://www.dropbox.com/s/os39us48nfepgll/open_nsfw_keras.zip?dl=0

Its not the cleanest and I got stuck trying to refactor the code... but hopefully it works!

**Comment by dribnet** [comment]
sorry - could you check the link or repost this? I was going to take a stab and refactoring this.

**Comment by kashif** [comment]
@dribnet ok sure... I moment

**Comment by kashif** [comment]
@dribnet  should work again

**Comment by dribnet** [comment]
got it, thanks!

**Comment by jessetrana** [comment]
@dribnet Thanks for the hard work! I was giving this a try and have still been seeing some differences in relative to the caffe version. Can you elaborate on what parts were causing problems during the refactor? I've noticed that mmdnn is giving similar results to your translation, so I'm wondering if there is some fundamental mismatch on caffe vs. keras.
