### ISSUE TITLE
1D Convolution much slower than 2D Convolution

### ISSUE THREAD

**Issue by oliverhiggs** [fchollet/keras#4144]
Hi, I've been playing with the Keras library for a couple of weeks now and I have noticed that on my installation (TensorFlow using CPU) 1D Convolutions are about six times slower than 2D Convolutions with equivalent dimensions. I believe this is caused by the expanding and squeezing of the 1D Convolution output tensor. There is an example on https://github.com/oliverhiggs/keras-examples/blob/master/conv_speed_example.py

Thanks for your time.

**Comment by carlthome** [comment]
"Equivalent dimensions" as in 2D: (x,y) and 1D: (x*y)?

**Comment by oliverhiggs** [comment]
That's correct. Specifically I was looking at 2D: (x, 1) and 1D: (x)

**Comment by fchollet** [comment]
What we should really do is:

- introduce a conv1d backend operation. On the TF side it would wrap the
native tf.conv1d (which didn't exist when we wrote the backend
initially...).
- have the Conv1D layer use that op.
- modify the model loading code to make sure that old saved models are
still compatible with the new implementation.

If you would like, you can start a PR to work on this.

**Comment by oliverhiggs** [comment]
Thanks for your response. I'm happy to work on this; would you like me to keep this issue open until I make the changes?

**Comment by carlthome** [comment]
Sweet! There's really a bunch of cool stuff to be done with Conv1D (learning spectral transforms) so this would be very useful.

**Comment by fchollet** [comment]
>  I'm happy to work on this; would you like me to keep this issue open until I make the changes?

Sure. Thank you!

**Comment by oliverhiggs** [comment]
I've had a look at resolving this issue and this is what I've found. It's a bit of a ride so bear with me:
1) The 1D convolution in the TensorFlow library is simply a wrapper around a 2D convolution operation.
2) The speed difference in my linked example is actually caused by the 1D Pooling layer, not the 1D Convolution layer.
3) The 1D Pooling layer is slow because it hard-codes 'th' dimension ordering and therefore performs two transposition operations on an input tensor. Removing the transpositions improves processing speeds to the point that 2D and 1D layers take the same amount of time.
4) In general, transposition operations are slow for both TensorFlow and Theano backends. Using 'th' dimension ordering on a 2D Convolution layer with TensorFlow backend (and vice versa) reduces performance dramatically. I believe this is because the transposition operation is performed every time the layer is run.

This has lead me on to a new issue that is related to the way by which Keras changes dimension ordering to allow compatibility between the two backends (i.e. allowing a user to utilise the TensorFlow backend with 'th' ordering and vice versa). As far as I can see there are two solutions here. The first is to simply use 'tf' ordering when using TensorFlow and 'th' ordering when using Theano. Obviously this isn't ideal because code must be rewritten to effectively test it on both backends.

The second solution is for Keras to create Tensors according to the backend that is in use rather than the dimension ordering that has been selected. Currently, 'tf' ordering means that tensors are created the way TensorFlow likes them and therefore transpositions are required to use them with the Theano backend. Processing speed would be improved if the layers are created according to the backend, with a one-time conversion between the chosen dimension ordering and the ordering required by the backend. This can be done by adding a check in the Convolution layers' __init__ functions to modify the 'input_shape' variable if the backend ordering and dimension ordering are not the same. 

What are your thoughts on this solution?

Note that this only applies to Convolution layers as I'm not really familiar with that way in which other layers are implemented. Also, I'm a relatively new Keras user so please let me know if I've misunderstood or missed something.

**Comment by fchollet** [comment]
I've improved the performance of 1D pooling layers as you suggested.

> The second solution is for Keras to create Tensors according to the backend that is in use rather than the dimension ordering that has been selected. 

Just set your `image_dim_ordering` properly in `~/.keras/keras.json`.
