### ISSUE TITLE
error occured when set featurewise_center=True in ImageDataGenerator

### ISSUE THREAD

**Issue by EncodeTS** [fchollet/keras#4158]
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
  pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
  pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I have a dir which contains some subdirs,and each subdir has some pics.When I use the following code to train a model,error occured like this.

```
TypeError: ufunc 'subtract' output (typecode 'O') could not be coerced to provided output parameter (typecode 'f') according to the casting rule ''same_kind''
```

Here is the train script.

```
datagen = ImageDataGenerator(featurewise_center=True, rescale=1./255)

train_generator = datagen.flow_from_directory(
    TRAIN_PATH,
    target_size=(64,128),
    color_mode='grayscale',
    batch_size=100)

model.fit_generator(
    train_generator,
    samples_per_epoch = 100,
    nb_epoch = 5
)
```

**Comment by isaacgerg** [comment]
I believe this is the same error as #4047 , its not taking the mean correctly for grayscale data.

**Comment by EncodeTS** [comment]
@isaacgerg Could you please send an PR to fix this problem?

**Comment by isaacgerg** [comment]
I don't have a fix, only a temporary work around which breaks for rgb
imagery.
