### ISSUE TITLE
Get current epoch predictions from inside callback (on_epoch_end) 

### ISSUE THREAD

**Issue by cicobalico** [fchollet/keras#4168]
Is it possible to get the training set predictions of the model at the end of each epoch from inside the function on_epoch_end at the end of a callback without having to call self.model.predict() every time, since the model already computed them?

**Comment by carlthome** [comment]
Similar: https://github.com/fchollet/keras/issues/2859

**Comment by bw4sz** [comment]
this might help. https://stackoverflow.com/questions/47079111/create-keras-callback-to-save-model-predictions-and-targets-for-each-batch-durin
