### ISSUE TITLE
How to train stacked auto-encoder with greedy layer-wise way

### ISSUE THREAD

**Issue by neouyghur** [fchollet/keras#4177]
is there any function available for building stacked auto-encoder in keras library? If no, does some offer some ideas for that. Actually I also have an idea, but I think it is a very naive idea. My idea is that each time train two layer (encode and decode) then freeze them. And add new layers (both decode and encoder) train them. And repeating above processes until reaching the full model.

**Comment by jf003320018** [comment]
You should check the previous issues firstly. This question has been talked. 
Additionally, you can see the bolg from Francois Chollet if you want to build antoencoder with keras. https://blog.keras.io/building-autoencoders-in-keras.html

**Comment by neouyghur** [comment]
@jf003320018  You may misunderstand my meaning. I dont mean stack several lays for auto-encoder. I actually did that. However, the result is not good. Here, I want to train each layer separately, then stack them together.

**Comment by jf003320018** [comment]
I think that this idea is commonly used and you can realize it with keras.

**Comment by darthdeus** [comment]
@jf003320018  I'm confused. The linked blog post doesn't explain how to train the layers separately. I also don't see any other issue addressing this.

**Comment by jgeofil** [comment]
A bit late.. but here's an example where each pair of layers are trained independently from @MadhumitaSushil
[SDAE](https://github.com/MadhumitaSushil/SDAE)
