### ISSUE TITLE
allow variable sequence lengths for stateful rnn

### ISSUE THREAD

**Issue by eyaler** [fchollet/keras#4187]
Stateful rnn requires input_batch_shape = (batch_size, timesteps, nb_features), where batch_size is required for the saving the state. however I am not sure why timesteps is required. it would be beneficial to allow timesteps=None, just as this is possible for stateless rnn having input_shape = (None, nb_features), allowing variable sequence lengths among batches (at least in theano)

usecases:
1. train batches with short seq. length for truncated BPTT vs. validation batches with full seq. length  
2. train and predict with different seq. lengths (in stateful prediction we may want seq len=1 timestep)

**Comment by farizrahman4u** [comment]
```python
batch_input_shape=(100, None, 10)
```

**Comment by eyaler** [comment]
unfortunately this does not work for stateful rnn in theano

**Comment by farizrahman4u** [comment]
Works for me. Do you have a script?

**Comment by farizrahman4u** [comment]
```shell
>>> model=Sequential()
>>> model.add(LSTM(10,batch_input_shape=(100,None,10), stateful=True))
>>> model.compile(loss='mse', optimizer='sgd')
>>> x=np.zeros((100,7,10))
>>> y=np.zeros((100,10))
>>> model.fit(x,y, batch_size=100)
Epoch 1/10
100/100 [==============================] - 0s - loss: 0.0000e+00
Epoch 2/10
100/100 [==============================] - 0s - loss: 0.0000e+00
Epoch 3/10
100/100 [==============================] - 0s - loss: 0.0000e+00
Epoch 4/10
100/100 [==============================] - 0s - loss: 0.0000e+00
Epoch 5/10
100/100 [==============================] - 0s - loss: 0.0000e+00
Epoch 6/10
100/100 [==============================] - 0s - loss: 0.0000e+00
Epoch 7/10
100/100 [==============================] - 0s - loss: 0.0000e+00
Epoch 8/10
100/100 [==============================] - 0s - loss: 0.0000e+00
Epoch 9/10
100/100 [==============================] - 0s - loss: 0.0000e+00
Epoch 10/10
100/100 [==============================] - 0s - loss: 0.0000e+00
<keras.callbacks.History object at 0x000000013FC93940>
>>>
```

**Comment by eyaler** [comment]
You are right. I was probably hitting another issue and blaming the wrong thing. I can no longer recreate the issue. great news. thanks!
