### ISSUE TITLE
VGG19 predict batch error

### ISSUE THREAD

**Issue by dungtn** [fchollet/keras#4189]
Hi,

I have this error while trying to call predict over batch of images:

``` python
model = VGG19(include_top=False, weights='imagenet', input_tensor=None)
...
model.predict(batch, batch_size=20)
```

> Exception: Error when checking : the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 arrays but instead got the following list of 20 arrays:

From Model class API, `predict` should _generate output predictions for the input samples, processing the samples in a batched way._

**Comment by superhans** [comment]
Copy-paste the code below and see if it works or not. 

```
from keras.applications.vgg19 import VGG19
from keras.preprocessing import image
from keras.applications.vgg19 import preprocess_input
import numpy as np

model = VGG19(weights='imagenet', include_top=False, input_tensor=None)
x = np.random.rand(50, 3, 224, 224) * 255
features = model.predict(x, batch_size=20)
print features.shape
```
This code gave me as output 
`(50, 512, 7, 7)`
