### ISSUE TITLE
Lambda output layer

### ISSUE THREAD

**Issue by heshameraqi** [fchollet/keras#4190]
I've a sequential model as follows with a linear activation function (Keras default) for the single output neuron:

```
model = Sequential()
model.add( ...
...
model.add(Dense(100, activation='relu'))
model.add(Dense(1))
```

I need the final number to be bounded by 100, so I modified the last line of code above to be:
`model.add(Lambda(lambda x: x%100, output_shape=(1)))
`
1- Is it correct? Does x here means the net as I expect ?
2- I get an error: "In Lambda, output_shape must be a list, a tuple, or a function".

**Comment by farizrahman4u** [comment]
```python
model.add(Lambda(lambda x: x%100, output_shape=(1,))
```
For bounding by 100, I think you should use K.clip.. Not sure what the gradients would be for % op.

**Comment by heshameraqi** [comment]
@farizrahman4u Thank you so much. But doesn't this mean that I will have 100 output neurons not a single one ?

**Comment by kgrm** [comment]
No. Since your last layer, `Dense(1)` already reduces the dimensionality to 1, and it is conserved through the Lambda layer unless specified otherwise.

**Comment by heshameraqi** [comment]
@kgrm I say "I modified the last line ...", so it's not there any more. So, I think it will produce 100 output neurons, and the workaround is to add a dense(1) layer before.
Can I do it with single layer directly ?

**Comment by kgrm** [comment]
You can, if you use a function that takes 100 inputs and produces a single output.

**Comment by heshameraqi** [comment]
@kgrm can you please refer me to an article or something that tells how to code this please? Thank you.

**Comment by kgrm** [comment]
For an example of a function that takes an arbitrary-shape tensor and outputs a scalar, see `K.sum()`.
