### ISSUE TITLE
can not import to_graph when I'm trying to visualize  a model graph

### ISSUE THREAD

**Issue by adelsalehali1982** [fchollet/keras#4193]
I built a model and tried to visualize it it using :
`
print 'Start Plotting'
from keras.utils.visualize_util import plot
from keras.utils.visualize_util import to_graph
graph = to_graph(model, show_shape=True)
graph.write_png("model.png")
`
but I got 
`
  File "TryBidirectional.py", line 39, in <module>
    from keras.utils.visualize_util import to_graph
`
ImportError: cannot import name to_graph

installing of pydot and graphvis didnot help

**Comment by carlthome** [comment]
There's no such function? [See the module.](https://github.com/fchollet/keras/blob/master/keras/utils/visualize_util.py)

**Comment by adelsalehali1982** [comment]
Thanks @carlthome 
Then How export model to image file and visualize a model?

**Comment by carlthome** [comment]
Please refer to [the documentation](http://keras.io).

**Comment by adelsalehali1982** [comment]
It Says:
ine 8, in <module>
    import pydot
ImportError: No module named pydot

**Comment by carlthome** [comment]
So have you installed pydot? [See this.](https://github.com/fchollet/keras/blob/master/setup.py#L16) and for further help please use the [Google Group](https://groups.google.com/forum/#!forum/keras-users) or the [Gitter](https://gitter.im/Keras-io/Lobby).
