### ISSUE TITLE
Image Transformation on the Fly

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#4204]
Hi,
I have a big dataset to process (millions of small images). Usually I do data augmentation (rotation + flip) before the training, but this time my cluster does not have memory enough to support it.
So I must do it on the fly! So while the NN is training.

How can I automatically modify the images at each epoch?
Ideally, I would like to modify the batch of images N+1 while the NN is still training on the batch N, like that I don't waste any time.

Thank for your help!

**Comment by kgrm** [comment]
Write a python generator to load and pre-process your data and yield input-output minibatches, then use `fit_generator()` to train your model with it.

**Comment by FiReTiTi** [comment]
Thank you for your answer.
It makes sense, but I've never done that before. I guess that the easiest way to do that is to modify the Keras Generator.

Any advise?

**Comment by YoelShoshan** [comment]
@FiReTiTi  see a very simple example I wrote of using keras generator here:
https://gist.github.com/YoelShoshan/3ed8f827685d130cd01fbf787821ee87

(It was created to demonstrate some issue in keras, but you can ignore that)
https://github.com/fchollet/keras/issues/4096

few more tips:
1. I'm using yield in this simple example, which you should probably start with. This is a "python generator". 
2. If you want to improve CPU utilization, and use several workers for your augmentation, use "python iterator", and make sure that your code is thread safe.  And I'm not talking about a single mutex that serializes any access to your generator/iterator. :)

http://anandology.com/python-practice-book/iterators.html

**Comment by FiReTiTi** [comment]
thanks, I am going to look into it!
