### ISSUE TITLE
Convolution layer generate wrong output shape

### ISSUE THREAD

**Issue by abdulqayyum** [fchollet/keras#4210]
Here is the model summary. Please note that output_shape second argument goes negative while I think it is channels I think and should be positive. I was unable to resolve the issue from documentation. 
![model2](https://cloud.githubusercontent.com/assets/6094454/19760705/4a596094-9c4c-11e6-8469-c8e534a2970d.png)

**Comment by lgautier** [comment]
A dimension already becomes 0 (zero) when reaching "convolution2d_5" . This would make a shorter example (and graph) to look at the issue.
