### ISSUE TITLE
Training data as GPU Tensor

### ISSUE THREAD

**Issue by landersson** [fchollet/keras#4216]
How difficult would it be to modify keras to support input training data as GPU tensors, i.e as memory buffers already residing in GPU memory rather than as numpy ndarrays?

Assuming it's not too invasive, would there be any chance of getting such functionality merged into the official repo?

**Comment by carlthome** [comment]
What happens if you just use gnumpy? Does that work?

**Comment by landersson** [comment]
I haven't tried passing in gnumpy tensors, but unless gnumpy is very compatible with standard numpy ndarrays I think it would fail somewhere in keras/engine/training.py.

**Comment by marek-krcal** [comment]
Just hard-wire your data into the model as a non-trainable embedding matrix (Embedding Layer with your custom initializer). Then instead of the training data you pass a bunch of indices to the model.fit method.
