### ISSUE TITLE
How to access variables of layers?

### ISSUE THREAD

**Issue by ritchieng** [fchollet/keras#4220]
If I were to follow the guide and integrate with my TensorFlow workflow (https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html) as with others, you cannot access the weight variable because we **won't be building the model** as shown in the guide. We're merely using the layers. There is no need to compile when we use it as a simplified interface to TensorFlow. **How then do we access the weights (variables)?**

Because if we use with TensorFlow like the guide, we **do not call** `Model` or `Compile` but merely use the layers to build.

**Comment by jf003320018** [comment]
If you just want to get the weights, just use model.get_weights(). Of cousre, each keras layer also can use this function, model.layers[0].get_weights().

**Comment by tomsercu** [comment]
@ritchieng did you find an answer to this question?
I observe that: `[v.name for v in tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)]` includes e.g. `dense_1_W:0` but that the following fails:
```
with tf.variable_scope('', reuse=True):
    W1 = tf.get_variable('dense_1_W')
```
Ugly workaround with inverse lookup works
```
vardic = {v.name: v for v in tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)}
W1 = vardic['dense_1_W:0']
```
But what would be the proper way?

**Comment by ritchieng** [comment]
I did not actually. I ended up using another framework that gave me more flexibility: https://github.com/zsdonghao/tensorlayer
