### ISSUE TITLE
fit_generator with variable number of samples_per_batch

### ISSUE THREAD

**Issue by ganesa90** [fchollet/keras#4223]
I am trying to use fit_generator to train a CNN model on a speech dataset. In speech, training batches are usually defined as the number of speech files per batch. Each speech file can have different number of sample frames. Hence, the number of samples_per_batch will not be the same for every batch. It is inappropriate to have part of a speech file in one batch and the remaining in the next batch. Moreover, if I have to count the number of samples in each audio file to make sure the number of samples_per_batch is met, I will lose all the advantage of batch generator.

Currently, my batch generator reads features and targets from files listed under one batch (pre-decided batch lists) and returns that as numpy arrays. 

Is there some way to accommodate this varying samples_per_batch into the fit_generator code?

**Comment by parag2489** [comment]
If you are not doing on-the-fly data augmentation, try using `model.train_on_batch()`. Then you will have complete control. I have used fit and fit_generator, I did not observe a large speed improvement when using fit_generator (given no augmentation was performed).
