### ISSUE TITLE
LSTM / RNN layer with lateral connections

### ISSUE THREAD

**Issue by JuniorIng** [fchollet/keras#4227]
Hi,

is it possible to create a recurrent layer with lateral connections between each unit of the layer in keras? (picture provided; green box is the layer of interest)
As for now I think the defaul LSTM layer does not provide the lateral connections ???

Thank you very much,
Jan
![rnn_lateralconnections](https://cloud.githubusercontent.com/assets/23149742/19836447/38128652-9ea1-11e6-86fe-fa5153128a81.png)

**Comment by dieuwkehupkes** [comment]
I am not entirely sure what you want to achieve, the state of a unit in the recurrent layer is usually already dependent on the previous state of the entire layer, so what else is it that you want to add?

**Comment by JuniorIng** [comment]
Hi, I want each units output of the LSTM layer to be connected to each neurons input in the LSTM layer.

**Comment by dieuwkehupkes** [comment]
This is still very unclear, the state of the LSTM layer already depends on its previous activation. Could you write down how you want your network to be different from the standard LSTM equations?

**Comment by JuniorIng** [comment]
I have an LSTM layer with 3 LSTM units: 1 to 3. Unit 1 output is connected to unit 1 input. Is unit 1 output also connected to unit 2 input and unit 3 input?

**Comment by JuniorIng** [comment]
May be i misunderstood the functionality of the lstm. As far as i understand the LSTM, it is just a recursive unit, a unit with output connected to its own input. But there are additional gates so that the unit is able to forget ... In keras there is the SimpleRNN layer. This layer has lateral connections between the units as well as self recurrent connections. I need those lateral connections in an LSTM layer ... may be it is clear now?

**Comment by dieuwkehupkes** [comment]
Yeah maybe look up the LSTM formula's first :). I like the explanation in this paper, for instance: https://arxiv.org/pdf/1412.3555.pdf.

**Comment by JuniorIng** [comment]
Thank you very much, I will work this through =)

**Comment by liangbright** [comment]
lateral connection already exist in LSTM.  a LSTM is a layer
In this page, Wf is a matrix, ht is a vector (all the outputs of a LSTM layer), xt is a vector
http://colah.github.io/posts/2015-08-Understanding-LSTMs/
also see https://www.quora.com/What-is-the-meaning-of-%E2%80%9CThe-number-of-units-in-the-LSTM-cell
