### ISSUE TITLE
Custom Layer for element-wise multipilication

### ISSUE THREAD

**Issue by hadikazemi** [fchollet/keras#4230]
I needed a layer to just do element-wise multiplication. I first tried to use locally connected like this:

``` python
model.add(LocallyConnected2D(3, 1, 1, input_shape=(1, 224, 224)))
```

But later I found locally connected is so slow which makes it useless for my problem. Then I started to write a custom layer but it doesn't work and gives me the following error:

>   File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 866, in **call**
>     self.fn() if output_subset is None else\
> ValueError: GpuElemwise. Output dimension mis-match. Output 0 (indices start at 0), working inplace on input 0, has shape[0] == 1, but the output's size on that axis is 3.
> Apply node that caused the error: GpuElemwise{Mul}[(0, 0)](GpuFromHost.0, mylayer_1_W)
> Toposort index: 1
> Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D)]
> Inputs shapes: [(1, 3, 224, 224), (3, 3, 224, 224)]
> Inputs strides: [(0, 50176, 224, 1), (150528, 50176, 224, 1)]
> Inputs values: ['not shown', 'not shown']
> Outputs clients: [[HostFromGpu(GpuElemwise{Mul}[(0, 0)].0)]]

and here is my code (theano backend):

``` python
class MyLayer(Layer):
    def __init__(self, nb_filter, nb_row, nb_col,
                 init='glorot_uniform', activation='linear', weights=None,
                 border_mode='valid', subsample=(1, 1), dim_ordering='default',
                 W_regularizer=None, b_regularizer=None, activity_regularizer=None,
                 W_constraint=None, b_constraint=None,
                 bias=True, **kwargs):
        if dim_ordering == 'default':
            dim_ordering = K.image_dim_ordering()
        self.init = initializations.get(init, dim_ordering=dim_ordering)
        self.activation = activations.get(activation)
        self.nb_filter = nb_filter
        self.nb_row = nb_row
        self.nb_col = nb_col
        self.bias = False
        self.initial_weights = weights
        self.dim_ordering = dim_ordering
        super(MyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        input_dim = input_shape[0]
        if self.dim_ordering == 'th':
            stack_size = input_shape[1]
            self.W_shape = (self.nb_filter, stack_size, self.nb_row, self.nb_col)

        self.W = self.init(self.W_shape, name='{}_W'.format(self.name))

        if self.bias:
            self.b = K.zeros((self.nb_filter,), name='{}_b'.format(self.name))
            self.trainable_weights = [self.W, self.b]
        else:
            self.trainable_weights = [self.W]

        if self.initial_weights is not None:
            self.set_weights(self.initial_weights)
            del self.initial_weights


    def call(self, x, mask=None):
        return x*self.W

    def get_output_shape_for(self, input_shape):
        rows = input_shape[2]
        cols = input_shape[3]
        return (input_shape[0], self.nb_filter, rows, cols)

model = Sequential()
model.add(MyLayer(3,224, 224, input_shape=(3, 224, 224)))

get_2rd_layer_output = K.function([model.layers[0].input],
                                  [model.layers[0].output])
img = np.ones((1,3,224,224))
k = get_2rd_layer_output([img])[0]
```

anybody knows where is the problem?

**Comment by amizan8653** [comment]
what kind of element wise multiplication are you doing? if you have 2 tensors that have the exact same dimensions, where each tensor is the output of a keras layer, then you can do element wise multiplication with the keras merge layer. All you would have to do is pass the string "mul" as the mode:

L1 and L2 are keras layers whose outputs are exactly the same dimensions
product =  merge([L1,L2], mode= "mul")

If you're trying to merge 2 layers that don't have the same shape, you could write a function that takes in the list of 2 layers, and merge them in whatever way you want. There was one time I was trying to multiply a vector by a scalar value, and so I used a merge layer, and passed a function that would do this:

def scalarMult(layersList):
  s = layersList[0]
  h_it = layersList[1]
  return s * h_it

L1 = some layer whose output is a scalar value
L2 = some layer whose output is a 1 X N vector
product = merge([L1,L2], mode= scalarMult, output_shape = (1,N))

Does this help at all? Do you have any more questions?

**Comment by hadikazemi** [comment]
Thabk you for your response. 
However, I am looking for a layer which multiply its input which is a rgb image by the layer's weight tensor element-wise (weight has the same dimension as the input, both 3x224x224 in theano). Then, I want to be able to train this weight. It's different than what merge does. I multiply an input by a trainable weight while merge multiply two inputs.

**Comment by pifelbo** [comment]
Do you want to not combine color channel information? Otherwise, you could just use a convolution layer with a 1x1 kernel to combine information across color channels.

Should each color channel have separate weights? Otherwise, you could just use the TimeDistributed wrapper to make the convolution layer learn the same weights across color channels.

**Comment by hadikazemi** [comment]
I wanted each pixel in each channel to have its own weight. Nothing is shared between channels.
Anyway, I finally fixed my own layer and now it is working (at least no error and weights are getting updated).

```python
class MyLayer(Layer):
    def __init__(self, nb_filter, nb_row, nb_col,
                 init='glorot_uniform', activation='linear', weights=None,
                 border_mode='valid', subsample=(1, 1), dim_ordering='default',
                 W_regularizer=None, b_regularizer=None, activity_regularizer=None,
                 W_constraint=None, b_constraint=None,
                 bias=True, **kwargs):
        if dim_ordering == 'default':
            dim_ordering = K.image_dim_ordering()
        self.init = initializations.get(init, dim_ordering=dim_ordering)
        self.activation = activations.get(activation)
        self.nb_filter = nb_filter
        self.nb_row = nb_row
        self.nb_col = nb_col
        self.bias = False
        self.initial_weights = weights
        self.dim_ordering = dim_ordering
        super(MyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        input_dim = input_shape[0]
        stack_size = input_shape[1]
        self.W_shape = (self.nb_filter, self.nb_row, self.nb_col)

        self.W = self.init(self.W_shape, name='{}_W'.format(self.name))

        self.trainable_weights = [self.W]


    def call(self, x, mask=None):
        return x*self.W

    def get_output_shape_for(self, input_shape):
        rows = input_shape[2]
        cols = input_shape[3]
        return (input_shape[0], self.nb_filter, rows, cols)
```

**Comment by fvarno** [comment]
@hadikazemi here's a more compact version I wrote:
https://github.com/fvarno/keras_utils/blob/master/ScaleAll


```
class MultAll(Layer):
    def __init__(self, **kwargs):
        self.axis = -1
        super(MultAll, self).__init__(**kwargs)

    def build(self, input_shape):
        if input_shape[-1] is None:
            raise ValueError('Axis ' +  + ' of '
                             'input tensor should have a defined dimension '
                             'but the layer received an input with shape ' +
                             str(input_shape) + '.')
        self.input_spec = InputSpec(ndim=len(input_shape),
                                    axes=dict(list(enumerate(input_shape[1:], start=1))))
        
        self.kernel = self.add_weight(name='kernel', 
                                      shape=input_shape[1:],
                                      initializer='uniform',
                                      trainable=True)
        super(MultAll, self).build(input_shape)  # Be sure to call this at the end

    def call(self, x):
        return np.multiply(x,self.kernel)

    def compute_output_shape(self, input_shape):
        return (input_shape)
```
