### ISSUE TITLE
Implementing Rationalization of Neural predictions in Keras

### ISSUE THREAD

**Issue by krishnateja614** [fchollet/keras#4231]
I just stumbledupon this paper https://people.csail.mit.edu/taolei/papers/emnlp16_rationale.pdf and it would cool to have this in keras, the actual code is at https://github.com/taolei87/rcnn/tree/master/code/rationale . This paper shows how to extract the phrase responsible for the sentiment score. This might be very helpful in numerous other application as well like QA etc.

**Comment by JoshuaZe** [comment]
Agree! 
an amazing regularization method for rationale generation, which is really cool and practical idea for any applications that need both insights/understandings and better predictions.

**Comment by RiaanZoetmulder** [comment]
I have an implementation in Tensorflow. It is on my github account. Perhaps that can help you implement it in keras?

here it is: https://github.com/RiaanZoetmulder/Master-Thesis/tree/master/rationale

There are some minor bugs/issues, and they are mentioned in the readme!
