### ISSUE TITLE
Accessing the softmax output of previous RNN state

### ISSUE THREAD

**Issue by monaj07** [fchollet/keras#4232]
The recurrence formula in my RNN is `h(t) = tanh(W.x(t) + U.h(t-1) + V.O(t-1) + b)`, where `O(t-1)` is the classification output (Softmax output) of the RNN at time `t-1`. How can I access this output at the next time step?
I guess I have to write a custom RNN, but I am a bit confused by all the recurrent functions in recurrent.py in Keras and I am not sure which parts should be modified.

**Comment by farizrahman4u** [comment]
Use recurrentshop.

**Comment by monaj07** [comment]
@farizrahman4u Thanks a lot for your response. 
I installed recurrentshop and tried to import it using  `from recurrentshop import *` , but I got the following error:

`Using Theano backend.
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled, cuDNN 5005)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "recurrentshop/__init__.py", line 1, in <module>
    from .engine import RNNCell, RecurrentContainer, weight
  File "recurrentshop/engine.py", line 32, in <module>
    _backend = getattr(K, K.backend() + '_backend')
AttributeError: 'module' object has no attribute 'backend'`

Furthermore, my problem with including the softmax output to the recurrent fiormula is that I don't know where to add the softmax activation, should it be within the `step` function in the custom RNN cell, or it still needs to be applied to the sequential model as a final layer?
I'd really appreciate it if you could add a small sample code to help me understand how to customize it.

**Comment by farizrahman4u** [comment]
Update keras. Just add a softmax activation to the recurrent container, with '`readout=True`. The output from the softmax activation will be added to the input in the next timestep.

**Comment by monaj07** [comment]
@farizrahman4u Thanks for the tips. 
In the step function, in order to extract the output `O` vector from the input vector `x`, I tried to print the shape of `x`, but it is in form of a TensorVariable gave me shape.0. So I am not sure how obtain the recurred output classes. I need to have access to `O` separately because I should apply a non-linear application to it and then use it in the recurrence formula. So in fact what I am after is `h(t) = tanh(W.x + U.h(t-1) + V.f(O(t-1)) + b`
Please bear with me as I am new to Keras.

**Comment by monaj07** [comment]
The problem is that I do not want to directly merge `O(t-1)` with `x(t)`, but I want to have separate access to `O(t-1)` in the `build` function of `SimpleRNN` to process it and then pass it to the recurrence formulation.

**Comment by monaj07** [comment]
@farizrahman4u 
I wrote the following sample code:
	
	dim = 20
	ncls = 4
	ts = 6
	
	rc = RecurrentContainer(readout=True, return_sequences=True)
	rc.add(SimpleRNNCell(10, input_dim=dim))
	rc.add(Dropout(0.5))
	rc.add((Dense(ncls)))
	rc.add(Activation('softmax'))
	
	a = Input((ts, dim))
	b = rc(a)
	model = Model(a, b)
	model.compile(loss='mse', optimizer='sgd')
	
	x = np.random.random((1000, ts, dim))
	y = np.random.random((1000, ts, ncls))
	model.fit(x, y, nb_epoch=5)

that produces this error:


```
File "theano/scan_module/scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform (/home/monaj/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/scan_perform/mod.cpp:4193)
ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[1] == 4, but the output's size on that axis is 20.
Apply node that caused the error: GpuElemwise{add,no_inplace}(<CudaNdarrayType(float32, matrix)>, <CudaNdarrayType(float32, matrix)>)
Toposort index: 4
Inputs types: [CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(32, 20), (32, 4)]
Inputs strides: [(120, 1), (4, 1)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuDot22(GpuElemwise{add,no_inplace}.0, simplernncell_1_W_copy0[cuda])]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Apply node that caused the error: forall_inplace,gpu,scan_fn&scan_fn}(Shape_i{1}.0, GpuSubtensor{int64:int64:int16}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, DeepCopyOp.0, GpuIncSubtensor{InplaceSet;:int64:}.0, Shape_i{1}.0, Shape_i{1}.0, simplernncell_1_W, simplernncell_1_U, dense_1_W, GpuDimShuffle{x,0}.0, GpuDimShuffle{x,0}.0)
Toposort index: 178
Inputs types: [TensorType(int64, scalar), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, matrix), TensorType(int64, scalar), TensorType(int64, scalar), CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, row), CudaNdarrayType(float32, row)]
Inputs shapes: [(), (6, 32, 20), (7, 32, 10), (7, 32, 4), (7, 32, 10), (7, 32, 4), (7, 92160), (), (), (20, 10), (10, 10), (10, 4), (1, 4), (1, 10)]
Inputs strides: [(), (20, 120, 1), (320, 10, 1), (128, 4, 1), (320, 10, 1), (128, 4, 1), (92160, 1), (), (), (10, 1), (10, 1), (4, 1), (0, 1), (0, 1)]
Inputs values: [array(6), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', array(6), array(6), 'not shown', 'not shown', 'not shown', CudaNdarray([[ 0.  0.  0.  0.]]), 'not shown']
Outputs clients: [[GpuSubtensor{int64:int64:int64}(forall_inplace,gpu,scan_fn&scan_fn}.0, ScalarFromTensor.0, ScalarFromTensor.0, Constant{-1}), GpuSubtensor{int64:int64:int64}(forall_inplace,gpu,scan_fn&scan_fn}.0, ScalarFromTensor.0, ScalarFromTensor.0, Constant{-1})], [GpuSubtensor{int64:int64:int64}(forall_inplace,gpu,scan_fn&scan_fn}.1, ScalarFromTensor.0, ScalarFromTensor.0, Constant{-1})], [GpuSubtensor{int64:int64:int64}(forall_inplace,gpu,scan_fn&scan_fn}.2, ScalarFromTensor.0, ScalarFromTensor.0, Constant{-1}), GpuSubtensor{int64:int64:int64}(forall_inplace,gpu,scan_fn&scan_fn}.2, ScalarFromTensor.0, ScalarFromTensor.0, Constant{-1})], [GpuSubtensor{int64:int64:int64}(forall_inplace,gpu,scan_fn&scan_fn}.3, ScalarFromTensor.0, ScalarFromTensor.0, Constant{-1})], [GpuSubtensor{int64:int64:int64}(forall_inplace,gpu,scan_fn&scan_fn}.4, ScalarFromTensor.0, ScalarFromTensor.0, Constant{-1}), GpuSubtensor{int64}(forall_inplace,gpu,scan_fn&scan_fn}.4, ScalarFromTensor.0)], [GpuDimShuffle{1,0,2}(forall_inplace,gpu,scan_fn&scan_fn}.5)], [GpuDimShuffle{1,0,2}(forall_inplace,gpu,scan_fn&scan_fn}.6)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

Can you tell me what the problem could be?
I suppose when I am using recurrentContainers, I don't need to use `TimeDistributed()`. Is that right?

Besides, I still don't know how to extract the readout output from the `step` function in `recurrentshop`. I am really confused right know and I'd appreciate if anyone could give me some clues.

**Comment by monaj07** [comment]
Does it mean that the number of classes of the output and input_dim must be the same when we want to have `readout=True`?

**Comment by farizrahman4u** [comment]
Yes.

```python
model = Sequential()
model.add(TimeDistributed(Dense(nb_classes), input_shape=(nb_timesteps, input_dim))
model.add(rc)
```

**Comment by farizrahman4u** [comment]
Also, if you need separate access to readout, you may write your own recurrent container (simply copy the existing one and change the readout part).

**Comment by monaj07** [comment]
In my case, the number of output classes is different from the input_dim.
So I will try to modify the recurrent container for that purpose. Thanks!

**Comment by farizrahman4u** [comment]
> In my case, the number of output classes is different from the input_dim.

I know.. follow the method I posted above. Use a timedistributed dense layer to change your input dim to ncls.

**Comment by monaj07** [comment]
Thanks. But do I necessarily have to do this dimension reduction (input_dim=4096D --> ncls=18 in my case)? 
I am trying to figure out where in `recurrentContainer`, the softmax on output is computed, so that I could directly pass it to the `step` function. I suppose once `readout` is captured here (line 250 engine.py):
```
if self.readout and i == 0:
	readout = states[-1]
```
I can then skip `x += readout` and return `readout` along with `x, states` to the `step` function in `SimpleRNNCell`. Is that correct.

**Comment by PiranjaF** [comment]
@farizrahman4u
My classification task is binary so by using your example code with TimeDistributed(ncls) I would have to convert the embedding for each of my words down to 2 dimensions before feeding into the RNN, which would make it impossible to learn anything.

Would it be possible to just use recurrentshop for the softmax layer with readout=True? For instance, would something along the lines of this work?

```
rc = RecurrentContainer(readout=True, return_sequences=True)
rc.add((Dense(ncls)))
rc.add(Activation('softmax'))

model = Sequential()
model.add(Embedding(...))
model.add(LSTM(1024, return_sequences=True))
model.add(LSTM(ncls, return_sequences=True))
model.add(rc)
```

**Comment by PiranjaF** [comment]
@monaj07 Did you end up finding a solution?

**Comment by monaj07** [comment]
@PiranjaF Not really, I gave up using recurrentshop. 
I am going to compute the softmax output of the previous time-step out(t-1) in the current time-step, by adding a single line to the step function, as follows:
```
def step(self, x, states):
    prev_output = states[0]
    B_U = states[1]
    B_W = states[2]

    if self.consume_less == 'cpu':
        h = x
    else:
        h = K.dot(x * B_W, self.W) + self.b
    output = self.activation(h + K.dot(prev_output * B_U, self.U))

    prev_softmaxOut = self.activation_dense(K.dot(prev_output, self.W_dense) + self.b_dense)
    return output, [output]
```
I need this output to use it as an extra factor for updating `h(t)`. However, when I introduce the weights `self.W_dense` and `self.b_dense` and add them to the trainable_weights by

`self.trainable_weights += [self.W_dense, self.b_dense]`

I get the following error:
```
theano.gradient.DisconnectedInputError:  
Backtrace when that variable is created:

  File "/home/monaj/Dropbox/codes/RNN/simplifiedReplicateRNN.py", line 87, in <module>
    RNN_out = rnnFunction(RNN_in)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/home/monaj/Dropbox/codes/RNN/ModifiedClasses.py", line 60, in build
    self.W_dense = self.init((self.output_dim, self.num_classes), name='{}_W_dense'.format(self.name))
  File "/usr/local/lib/python2.7/dist-packages/keras/initializations.py", line 59, in glorot_uniform
    return uniform(shape, s, name=name)
  File "/usr/local/lib/python2.7/dist-packages/keras/initializations.py", line 32, in uniform
    return K.random_uniform_variable(shape, -scale, scale, name=name)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 141, in random_uniform_variable
    dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 66, in variable
    return theano.shared(value=value, name=name, strict=False)
```
Do you think it makes sense at all to compute the softmax outputs this way? I could not come up with a straightforward approach to obtain these softmax outputs within the RNN loop.

**Comment by farizrahman4u** [comment]
```python
def step(self, x, states):
    prev_output = states[0]
    B_U = states[1]
    B_W = states[2]

    if self.consume_less == 'cpu':
        h = x
    else:
        h = K.dot(x * B_W, self.W) + self.b
    output = self.activation(h + K.dot(prev_output * B_U, self.U))

    prev_softmaxOut = self.activation_dense(K.dot(prev_output, self.W_dense) + self.b_dense)
    return output, [prev_softmaxOut]
```
Note that this wouldn't work as expected for a stack.

**Comment by farizrahman4u** [comment]
Also note that recurrentshop now supports readout input to arbitrary cells, and you can decide what is done with the readout, not just add/mul.

1. Create your own cell class, inheriting from `RNNCell`. See `SimpleRNNCell` code for example.
2. Define the step function for the cell as follows:

```python
def step(x, states):
    # x is a list; x = [input, readout]
    readout = x[1]
    x = x[0]
    # Rest of your step function.......
    return y, new_states
```
3. Create an object of the cell class. `cell=MyCellClass(output_dim=10)`
4. Set attribute `receive_readout` to True for the object `cell.receive_readout=True`
5. Create `RecurrentContainer` object with `readout=True`;Add your custom cells and other cells.

**Comment by monaj07** [comment]
@farizrahman4u  Thanks for your response. As you said it does not work on a batch and I still get the same error when I add `W_dense` and `b_dense` to the trainable_weights.

**Comment by farizrahman4u** [comment]
Its because you are not using the weights anywhere.

**Comment by monaj07** [comment]
@farizrahman4u Thanks. 
I implemented it using Theano, though it needed more codes.

**Comment by mkusner** [comment]
Hey @monaj07 would you mind posting your solution? I'm also interested in your exact problem!
