### ISSUE TITLE
Trying to train an Autoencoder.  Getting an error with .fit method

### ISSUE THREAD

**Issue by skottapa** [fchollet/keras#4236]
Hi,

I have just started collecting some image data for a project.  Before collecting too much data wanted to run a simple autoencoder to see what features it was learning.  used the following link as a starting point.   https://blog.keras.io/building-autoencoders-in-keras.html

however I am getting the following error.  

C:\Users\satish\Anaconda\Deep Test>python conv_autoencoder.py
Using Theano backend.
Using gpu device 0: GeForce 840M (CNMeM is enabled with initial size: 80.0% of memory, cuDNN 5103)
Found 113 images belonging to 2 classes.
Found 32 images belonging to 2 classes.
Traceback (most recent call last):
  File "conv_autoencoder.py", line 68, in <module>
    validation_data=(valid_generator,valid_generator)
TypeError: fit() takes at least 3 arguments (6 given)

My code is as follows.

from keras.layers import Input, Dense, Convolution2D, MaxPooling2D, UpSampling2D
from keras.models import Model
import numpy as np
import os
import h5py
import numpy as np
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Activation, Dropout, Flatten, Dense

img_width=140 
img_height=140
train_data_dir=r'Photos\train'
valid_data_dir=r'Photos\validation'
input_img = Input(shape=(3, img_width, img_width))

x = Convolution2D(16, 3, 3, activation='relu', border_mode='same')(input_img)
x = MaxPooling2D((2, 2), border_mode='same')(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
x = MaxPooling2D((2, 2), border_mode='same')(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
encoded = MaxPooling2D((2, 2), border_mode='same')(x)

# at this point the representation is (8, 4, 4) i.e. 128-dimensional

x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(encoded)
x = UpSampling2D((2, 2))(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
x = UpSampling2D((2, 2))(x)
x = Convolution2D(16, 3, 3, activation='relu')(x)
x = UpSampling2D((2, 2))(x)
decoded = Convolution2D(1, 3, 3, activation='sigmoid', border_mode='same')(x)

autoencoder = Model(input_img, decoded)
autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')

valid_datagen = ImageDataGenerator(rescale=1./255)
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
		train_data_dir,
		target_size=(img_width, img_height),
		batch_size=32,
		class_mode=None,
		shuffle=False)
valid_generator = valid_datagen.flow_from_directory(
		valid_data_dir,
		target_size=(img_width, img_height),
		batch_size=32,
		class_mode=None,
		shuffle=False)

autoencoder.fit((train_generator,train_generator),
                nb_epoch=50,
                batch_size=32,
                shuffle=True,
                validation_data=(valid_generator,valid_generator)
				)

Appreciate any help as have been stuck at this point for the last day or so.  

Thanks
SK

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [ X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by skottapa** [comment]
Hi,

Forgot to mention, am using Theano backend as I am using a Windows PC for this exercise.

Regards
SK

**Comment by skottapa** [comment]
Apologize for the piecemeal updates.  When I change the fit to

**Comment by skottapa** [comment]
Hi,

When I change the fit to 

autoencoder.fit(train_generator,train_generator,
                nb_epoch=50,
                batch_size=32,
                shuffle=True,
                validation_data=(valid_generator,valid_generator))

get the following error

Traceback (most recent call last):
  File "conv_autoencoder.py", line 64, in <module>
    validation_data=(valid_generator,valid_generator)
  File "C:\Users\satish\Anaconda\lib\site-packages\keras\keras\engine\training.py", line 1032, in fit
    batch_size=batch_size)
  File "C:\Users\satish\Anaconda\lib\site-packages\keras\keras\engine\training.py", line 959, in _standardize_user_data
    exception_prefix='model input')
  File "C:\Users\satish\Anaconda\lib\site-packages\keras\keras\engine\training.py", line 70, in standardize_input_data
    'Found: ' + str(data)[:200] + '...')
Exception: Error when checking model input: data should be a Numpy array, or list/dict of Numpy arrays. Found: <keras.preprocessing.image.DirectoryIterator object at 0x000000001B70AA58>...

PS.  Am using Theano backend as I am using a Windows MAchine

**Comment by tboquet** [comment]
You should use the fit_generator method.

**Comment by skottapa** [comment]
Thanks tboquet.  Made the following change.

autoencoder.fit_generator(train_generator,
                nb_epoch=50,                
                validation_data=valid_generator,
		samples_per_epoch=113,
		nb_val_samples=32)

However am now getting the following error.  

Exception: Error when checking model target: expected convolution2d_7 to have 4 dimensions, but got array with shape (32L, 1L).

Have kept all the layers the same as in the MNIST example.  Only change was rather than use input shape of (1,28,28)of mnist, used (3,140,140) as these are normal jpegs.  

img_width=140
input_img = Input(shape=(3, img_width, img_width))

x = Convolution2D(16, 3, 3, activation='relu', border_mode='same')(input_img)
x = MaxPooling2D((2, 2), border_mode='same')(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
x = MaxPooling2D((2, 2), border_mode='same')(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
encoded = MaxPooling2D((2, 2), border_mode='same')(x)

x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(encoded)
x = UpSampling2D((2, 2))(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
x = UpSampling2D((2, 2))(x)
x = Convolution2D(16, 3, 3, activation='relu')(x)
x = UpSampling2D((2, 2))(x)
decoded = Convolution2D(1, 3, 3, activation='sigmoid', border_mode='same')(x)

autoencoder = Model(input_img, decoded)
autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')

Not sure where I screwed up in the shape/reshape.
Thanks for bearing with a keras newbie.

**Comment by tolgabirdal** [comment]
How about making the output of the last convolution multi-channel? 
decoded = Convolution2D(3, 3, 3, activation='sigmoid', border_mode='same')(x)

**Comment by skottapa** [comment]
Let me try.  Not sure why changing the activation should have any impact.


Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Nov 30, 2016 at 6:47 PM +0530, "Tolga Birdal" <notifications@github.com<mailto:notifications@github.com>> wrote:


How about making the output of the last convolution multi-channel?
decoded = Convolution2D(3, 3, 3, activation='sigmoid', border_mode='same')(x)

-
