### ISSUE TITLE
how to implemente deconv3D

### ISSUE THREAD

**Issue by qinhaifangpku** [fchollet/keras#4238]
hi,all~
i wonder if there any body have ever use decovolution3D,  or unpooling3D ?
the inverse option to convolution3D or maxpooling option.

thank you in advance!

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [1 ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [1 ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ 1] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by prinsherbert** [comment]
Might be usefull: https://gist.github.com/indraforyou/a8964a398474216917459e168e67ab65
