### ISSUE TITLE
Dynamic Network Structures and Topologies

### ISSUE THREAD

**Issue by MannyKayy** [fchollet/keras#4240]
I have been trying to replicate the recent work on networks with dynamic topology. The only available implementations for [Neural Module Networks](https://github.com/jacobandreas/nmn2) have been using Jacob Andreas's [fork](https://github.com/jacobandreas/apollocaffe) of ApolloCaffe and I am wondering if this is possible within Keras.

For example, in a VQA setting, the idea is to have a set of simple primitive "module" networks that are composed at query time to answer a specific question. The manner in which the network is composed and thus it's topology is conditioned on the given query.They use REINFORCE to select the best network architecture from a set of candidate architectures. The [slides](https://people.eecs.berkeley.edu/~jda/slides/ardk_nmn2.pdf)  give some intuition on how it is done and the [paper](https://arxiv.org/abs/1511.02799) details the approach. 

So given a question, the goal is to predict a network architecture (from a set of primitive modules) and use that network to predict an answer. 

Is any of this possible within Keras? 
It would probably require weight-tying across different instantiations of a primitive network module and continuosly [modifying](http://stackoverflow.com/questions/34235225/is-it-possible-to-modify-an-existing-tensorflow-computation-graph) the computation graph.

**Comment by acriptis** [comment]
I have the similar problem. I need a interface to keras neural network model to add/remove specific neurons from network at specific layers. Is there a best practice or recommendations of doing that?
