### ISSUE TITLE
Inputs of arbitrary length for TimeDistributed

### ISSUE THREAD

**Issue by alexander-malafeev** [fchollet/keras#4248]
I am using 
TimeDistributed(Convolution1D(...), input_shape=(None, data_dim, 1)) as a first layer
and get an error. If I use the length of the sequence instead of None everything works, 
but I would like to use this model for prediction of the sequences of arbitrary length afterwards.
Is it possible to not specify the length?

**Comment by dieuwkehupkes** [comment]
I think you always have to specify the length. You can set it to the maximum number and then pad the sequences that are shorter. With a masking layer you can exclude the masked values from the computation.
