### ISSUE TITLE
Reshape for connecting Conv2D and Dense layers

### ISSUE THREAD

**Issue by ikamensh** [fchollet/keras#4257]
I am new to Keras; I was building my first conv net model when I had issue of connecting a Conv2D layer with a Dense layer. I was unable to find much helpful information on google / here, and spent close to 30m tinkering. So to help others with same problem here is the solution I got:

model=Sequential()

model.add(Convolution2D(8, 5, 5, border_mode='same',subsample=(2,2),input_shape=(28, 28, 1)))
#output shape is (nsamples, 14, 14 ,8)
model.add(Convolution2D(8, 5, 5, border_mode='same',subsample=(2,2)))
#output shape is (nsamples, **7, 7 ,8**)
**model.add(Reshape((7 * 7 * 8 , )))**
model.add(Dense(output_dim=256))

There is no problem I need help with now :) thanks for this library enjoying it.

**Comment by skottapa** [comment]
Try model.add(Flatten()) instead of model.add(Reshape((7 * 7 * 8 , )))

**Comment by alyato** [comment]
@ikamensh  Do you understand the difference between `border_mode='same'`and `border_mode='valid'`
the first conv: (none,28,28,8)
the second conv:(none,28,28,8)
