### ISSUE TITLE
fit_generator works with built in deep models but not with Autoencoder

### ISSUE THREAD

**Issue by skottapa** [fchollet/keras#4260]
Hi,

Would like to know what changes need to be made to generators to make them work with Autoencoders.  The generator that worked fine with VGG-19 model fit_generator gives the following error when I tried to fit an Autoencoder

Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: [[[[ 0.86666673  0.86666673  0.86666673 ...,  0.62352943  0.627451
     0.63137257]
   [ 0.86666673  0.86666673  0.86666673 ...,  0.63137257  0.627451
     0.627451  ]
   [ 0.86666673  0.86666673  0.86666673 ...,  0.63137257  0.627451
     0.62352943]
   ...,

The code is as follows

```
img_width=140 
img_height=140
train_data_dir=r'SitePhotos\train'
valid_data_dir=r'SitePhotos\validation'
input_img = Input(batch_shape=(32,3, img_width, img_width))

x = Convolution2D(16, 3, 3, activation='relu', border_mode='same')(input_img)
x = MaxPooling2D((2, 2), border_mode='same')(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
x = MaxPooling2D((2, 2), border_mode='same')(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
encoded = MaxPooling2D((2, 2), border_mode='same')(x)

# at this point the representation is (8, 4, 4) i.e. 128-dimensional

x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(encoded)
x = UpSampling2D((2, 2))(x)
x = Convolution2D(8, 3, 3, activation='relu', border_mode='same')(x)
x = UpSampling2D((2, 2))(x)
x = Convolution2D(16, 3, 3, activation='relu')(x)
x = UpSampling2D((2, 2))(x)
decoded = Convolution2D(1, 3, 3, activation='sigmoid', border_mode='same')(x)

autoencoder = Model(input_img, decoded)
autoencoder.compile(optimizer='adadelta', loss='mse')



valid_datagen = ImageDataGenerator(rescale=1./255)
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        train_data_dir,
        target_size=(img_width, img_height),
        batch_size=32,
        class_mode=None,
        shuffle=True)


valid_generator = valid_datagen.flow_from_directory(
        valid_data_dir,
        target_size=(img_width, img_height),
        batch_size=32,
        class_mode=None,
        shuffle=True)

autoencoder.fit_generator(train_generator,
                nb_epoch=50,                
                validation_data=valid_generator,
                samples_per_epoch=113,
                nb_val_samples=32
                )
```
The only change I made to the generator was to set the class mode to None. 

Keeping the original class mode of 'binary' didn't help either. Since the fit generator expects a tuple, I tried passing (train_generator, train_generator) and (valid_generator,valid_generator) as arguments to fit_generator.

In which case got the following exception

```
Error when checking model input: data should be a Numpy array, or list/dict of Numpy arrays. Found:
 <keras.preprocessing.image.DirectoryIterator object at 0x000000001BA73DD8>...
```

Nothing seems to work. Not sure what I am missing. Being a keras newbie, any help would be greatly appreciated.

Thanks SK

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [X ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by rodgzilla** [comment]
I've had the same issue and I am writing a small patch to solve it.

I'm adding a new class_mode to the flow_from_directory method and DirectoryIterator class which enables to iterate over couple of images (x, x). This would be perfect to train autoencoders.

I have a few questions: 
- Do you think that it is a reasonable way to tackle this problem?
- If you think it is, what should be the name of the new class_mode? I was thinking of class_mode = 'identical'.

Thanks in advance for your answers.
