### ISSUE TITLE
How to merge a part of a layer and other layers

### ISSUE THREAD

**Issue by anewlearner** [fchollet/keras#4261]
Can keras realize the following model?

Thanks!

![aa](https://cloud.githubusercontent.com/assets/10386613/19914285/2f6ba4a8-a0e4-11e6-9d32-6834104bdd6f.png)

**Comment by dieuwkehupkes** [comment]
How about using the merge layer with mode='concat'?

**Comment by anewlearner** [comment]
I tried this before using the following code. But it did not work. There were some errors.

```
model = Sequential()
model.add(Convolution2D(32, 3, 3, border_mode='same',
                        input_shape=X_train.shape[1:]))
model.add(Activation('relu'))
model.add(Convolution2D(32, 3, 3))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.layers[3].output=model.layers[0].input

conv1=model.layers[3].output
pool1=model.layers[5].output
crop_11=conv1[:, :, 15-7:15+8]

merged_vector = merge([crop_11, pool1], mode='concat', concat_axis=1)
```

or 
```
input_img = Input(shape=X_train.shape[1:])
conv_11 = Convolution2D(32, 3, 3, border_mode='same')(input_img)
relu_11 = Activation('relu')(conv_11)
conv_12 = Convolution2D(32, 3, 3)(relu_11)
relu_12 = Activation('relu')(conv_12)
pool_11 = MaxPooling2D(pool_size=(2, 2))(relu_12)

crop_11=relu_12[:, :, 15-7:15+8]
merged_vector = merge([crop_11, pool_11], mode='concat', concat_axis=1)
```

**Comment by dieuwkehupkes** [comment]
Hi @anewlearner,

The first solution doesn't work because the model is not Sequential, you should use the functional API instead. The second one looks fine, only the crop part I am not sure about. What is the error you are getting? Do you still get the same error if you use only the merge and not the crop?

**Comment by anewlearner** [comment]
Hello @dieuwkehupkes ,

```
input_img = Input(shape= (3, 32, 32))
conv_1 = Convolution2D(32, 3, 3, border_mode='same')(input_img) # ouput: batchsize*32*32*32
relu_1 = Activation('relu')(conv_1) # ouput: batchsize*32*32*32
pool_1 = MaxPooling2D(pool_size=(2, 2))(relu_1) # ouput: batchsize*32*16*16
```

I tried 
```
crop_1=relu_1[:, :, 0: 16, 0: 16] # make the output of this layer equal to layer pool_1,  ouput: batchsize*32*16*16
merge1 = merge([crop_1, pool_1], mode='concat', concat_axis=1)
conv_2 = Convolution2D(32, 3, 3, border_mode='same')(merge1)
```
then I got the following error message

> Exception: You tried to call layer "convolution2d_28". This layer has no information about its expected input shape, and thus cannot be built. You can build it manually via: `layer.build(batch_input_shape)`

I don't know how to 

> build it manually via: 'layer.build(batch_input_shape)`

I also tried
```
merge1 = merge([relu_1, pool_1], mode='concat', concat_axis=1)
conv_2 = Convolution2D(32, 3, 3, border_mode='same')(merge1)
```
I got

> Exception: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 32, 32, 32), (None, 32, 16, 16)]

But when I tried
```
crop_2=relu_1[:, :, 0: 5, 0: 5] batchsize*32*5*5
merge2 = merge([crop_2, pool_1], mode='concat', concat_axis=1)
```
There were no error message in the merge layer, but in the conv_2 layer.
I can't merge` relu_1` and `pool_1`, because the shape is different. But I can merge `crop_2` and `pool_1`, the shape is also different.

**Comment by dieuwkehupkes** [comment]
I still suspect the problem is with the cropping. Could you try cropping it not with the indices but with a fixed weight matrix setting some values to 0? I am fairly sure that could work. If you can't figure out how let me know.

Good luck!

**Comment by alyato** [comment]
@anewlearner  Do you solve it ? , you can try the `Reshape`

**Comment by dieuwkehupkes** [comment]
@alyato Can this also be used to reduce the number of values? I thought Reshape was just for changing the shape of a layer (e.g. go from 5*4 to 5*2*2). Otherwise, where do you say which elements of the original layer you want to keep?

**Comment by anewlearner** [comment]
@dieuwkehupkes 
The fixed  weight matrix can be set to 0. But If I do this, the shape of the this crop layer( some weights are set to 0) is different from that of the pool layer, the shape of which is reduced. So merge can not be used.

**Comment by alyato** [comment]
@dieuwkehupkes yeah ,i think so. I see the `Reshape` is used to the Lstm. When i merge two different layer,like this situation. 
c1: (none,100,40,40)
c2:(none,100,20,20)
i change the shape of C1 to `Reshape(none,100*40*40/20*20,20,20)`,then merge them
