### ISSUE TITLE
cannot import backend from keras

### ISSUE THREAD

**Issue by chivalry123** [fchollet/keras#4262]
I am trying to build my custom function in Keras as shown in:

https://github.com/fchollet/keras/blob/master/keras/objectives.py

However, I get this error:

    $ ipython 
    Python 2.7.12 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:43:17) 
    Type "copyright", "credits" or "license" for more information.
    
    IPython 5.1.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    In [1]: import keras
    Using TensorFlow backend.
    im
    In [2]: from . import backend as K
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-2-b7b972de130c> in <module>()
    ----> 1 from . import backend as K
    
    ValueError: Attempted relative import in non-package

Any help? Thank you very much.

**Comment by dieuwkehupkes** [comment]
Relative imports only work for packages. Why are you importing "backend" this way? Where did you define your custom objective?

**Comment by CCXD** [comment]
`from keras import backend as K`

Like your error literally states.

**Comment by chivalry123** [comment]
Thanks. The second issue is that after I save and load the model with custom object, I have this error:

```

    def _save_model(self,net_transfer):
        net_transfer.save(self._load_nn_location)

    def _load_model(self):
        net_transfer = keras.models.load_model(self._load_nn_location)
        return net_transfer

```

```

  File "/Users/a/Desktop/software/WX-site-packages/Quantomic_new/Quantomic_dev_2016_10_05/Quantomic/strategy/QTNNSimplePredictTensorflowDataGen.py", line 346, in build
    self._net = self._load_model()
  File "/Users/a/Desktop/software/WX-site-packages/Quantomic_new/Quantomic_dev_2016_10_05/Quantomic/strategy/QTNNSimplePredictTensorflowDataGen.py", line 657, in _load_model
    net_transfer = keras.models.load_model(self._load_nn_location)
  File "/Users/a/anaconda2/lib/python2.7/site-packages/keras/models.py", line 155, in load_model
    sample_weight_mode=sample_weight_mode)
  File "/Users/a/anaconda2/lib/python2.7/site-packages/keras/models.py", line 547, in compile
    **kwargs)
  File "/Users/a/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 537, in compile
    loss_function = objectives.get(loss)
  File "/Users/a/anaconda2/lib/python2.7/site-packages/keras/objectives.py", line 77, in get
    return get_from_module(identifier, globals(), 'objective')
  File "/Users/a/anaconda2/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 16, in get_from_module
    str(identifier))
Exception: Invalid objective: custom_objective

```

Does i mean that I could not save the custom objective model? (when others load it, I do not want them to build the model first and load the weight.... I just want them to load as is)

**Comment by CCXD** [comment]
Post the code that includes custom_objective please.
Are you skipping the definition of custom_objective when you load the model?

**Comment by chivalry123** [comment]
Here's the part i define my custom_objective:


```

    def _generate_model(self):
        model=keras.models.Sequential()

        for i in range(len(self._hidden_layer_dim)):
            layer_now=self._hidden_layer_dim[i]
            print("i now is ",i)
            if i==0:
                model.add(keras.layers.Dense(layer_now,input_dim=self._input_dimension,
                                             W_regularizer=keras.regularizers.l1(self._weight_decay),
                                             activity_regularizer=keras.regularizers.activity_l1(self._weight_decay)))
            else:
                model.add(keras.layers.Dense(layer_now,W_regularizer=keras.regularizers.l1(self._weight_decay),
                                             activity_regularizer=keras.regularizers.activity_l1(self._weight_decay)))

            print("dropout rate is ", self._dropout_rate)
            if self._activation=="PReLU":
                model.add(keras.layers.advanced_activations.PReLU())
            else:
                model.add(keras.layers.Activation(self._activation))
            model.add(keras.layers.Dropout(self._dropout_rate))

        model.add(keras.layers.Dense(self._output_dimension,W_regularizer=keras.regularizers.l1(self._weight_decay)))
        def custom_objective(y_true, y_pred):
            from keras import backend as K

            '''Just another cross entropy''
            # y_pred_np=np.array(y_pred)
            # y_true_np=np.array(y_true)
            # loss_arr = np.sign(y_pred_np)*(y_pred_np-y_true_np)
            # negative_index = loss_arr < 0
            # loss_arr [negative_index] = 0
            # loss = np.mean(loss_arr)

            loss_arr = K.sign(y_pred)*(y_pred-y_true)
            loss_arr = K.clip(loss_arr,0,np.inf)
            loss = K.mean(loss_arr)

            return loss

        # loss='mean_absolute_error'
        loss=custom_objective

        model.compile(optimizer='Adam',loss=loss,metrics=[loss,'mean_absolute_error','mean_squared_error','mean_squared_logarithmic_error'])
        return model

```'


Do I need to define this more globally?

**Comment by chivalry123** [comment]
i see... when I put the definition in a more global setting (put it on top of  the file), everything works....

**Comment by CCXD** [comment]
Then I guess custom objectives are not saved, and indeed need to be defined before loading the model.

**Comment by drscotthawley** [comment]
> Relative imports only work for packages. Why are you importing "backend" this way? Where did you define your custom objective?


Same error arises in official keras/applications example  [https://github.com/fchollet/keras/blob/master/keras/applications/music_tagger_crnn.py](https://github.com/fchollet/keras/blob/master/keras/applications/music_tagger_crnn.py)

~/keras/keras/applications$ python music_tagger_crnn.py 
Traceback (most recent call last):
  File "music_tagger_crnn.py", line 12, in <module>
    from .. import backend as K
ValueError: Attempted relative import in non-package
~/keras/keras/applications$


...So, is there some kind of "import path" that I need to set?

**Comment by patyork** [comment]
@drscotthawley It's still the same issue: that file you are referencing:
- Is not an example
- Is a part of the Keras package
- includes no runnable code, just a class

**Comment by drscotthawley** [comment]
@patyork Thanks.  I misunderstood the use of the word "applications", thinking it would be executable.  I just now found & ran the usage example in the docs with no problems. :-)
