### ISSUE TITLE
Semantic Meaning of a sentence

### ISSUE THREAD

**Issue by Sanjay-Reddy-S** [fchollet/keras#4271]
Not really an issue, but I haven't found any documentation on how to access the hidden state in LSTM RNN.

**Context:** I want to capture the semantic meaning of a sentence, by feeding in the Glove word embedding vectors ( [https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py](url) ) into the RNN and when the sentence ends, the final hidden state captures the so-called sentence embedding. I want to access this vector obtained from the final hidden state.

**Comment by PPACI** [comment]
You could try to train your model (like a *sentence2vec*) and then get the intermediate result to see the internal embedding. This is described in the [Keras FAQ](https://keras.io/getting-started/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer)
