### ISSUE TITLE
Saving internal states of optimizers for successive calls to model.fit

### ISSUE THREAD

**Issue by the-moliver** [fchollet/keras#428]
I might be wrong, but I think that every call to `model.fit` resets the accumulated states (such as momentum, etc.) in the optimizers. I think it would be great if the optimizers could essentially pick up where they left off training, or at least have the option of doing so. I don't think this would be difficult to do, but I'd like to have some feedback before trying to make this work.

**Comment by kenterao** [comment]
I have an implementation with `get_state` and `set_state` methods on the optimizers.  It's good for continuing the fitting process but it's also needed for parallelized fitting.  When running fitting processes on multiple nodes, both the weights and the optimizers states need to be gathered and broadcast.

**Comment by the-moliver** [comment]
That sounds great, can you make a PR with that feature?

**Comment by kenterao** [comment]
Sure I can make a PR.  I use `OrderedDict` instead of a list of tuples.  I don't know if anyone has a strong opinion.  I've read that Theano actually expects OrderedDict.  https://github.com/Theano/Theano/issues/1306

```python
class Optimizer(object):
    def __init__(self, **kwargs):
        self.updates = OrderedDict({})        
        self.__dict__.update(**kwargs)
    
    def get_states(self):
        return [u.get_value() for u in self.updates]
    
    def set_states(self, value_list):
        assert len(self.updates) == len(value_list)
        for u, v in zip(self.updates, value_list):
            u.set_value(floatX(v))
    
    def get_updates(self, params, constraints, loss):
        raise NotImplementedError

    def get_gradients(self, loss, params):
        grads = T.grad(loss, params)

        if hasattr(self, 'clipnorm') and self.clipnorm > 0:
            norm = T.sqrt(sum([T.sum(g**2) for g in grads]))
            grads = [clip_norm(g, self.clipnorm, norm) for g in grads]

        return grads

    def get_config(self):
        return {"name":self.__class__.__name__}
```

**Comment by TeaPearce** [comment]
> "Successive calls to fit do not reset any of the parameters of the model, including the state of the optimizers. Successive calls to fit with nb_epoch = 1 is effectively the same as a single call to fit."

https://github.com/fchollet/keras/issues/454

**Comment by MunishaTripping** [comment]
how is optimizer state different from weights ? I mean if I could save weights, wouldn't I be able to resume the training from just that.
