### ISSUE TITLE
Convert an activity recognitoin model to keras

### ISSUE THREAD

**Issue by adelsalehali1982** [fchollet/keras#4283]
I'm trying to covert this model :
https://github.com/yjxiong/caffe/tree/action_recog/models/action_recognition
which is in caffe to keras
to do that as small experimen I download  prototxt
https://github.com/yjxiong/caffe/blob/action_recog/models/action_recognition/cuhk_action_spatial_vgg_16_deploy.prototxt
and the model file :
http://mmlab.siat.ac.cn/very_deep_two_stream_model/cuhk_action_spatial_vgg_16_split1.caffemodel
I'm try to convert using @MarcBS 
https://github.com/MarcBS/keras
here is the command line:

python caffe2keras.py -load_path 'TSN/' -prototxt 'cuhk_action_spatial_vgg_16_deploy.prototxt' -caffemodel 'cuhk_action_spatial_vgg_16_split1.caffemodel'

**But I got that IndexError: list index out of range**
____________________
drop7 (Dropout)                  (None, 4096)          0           relu7[0][0]                      
____________________________________________________________________________________________________
fc8-1 (Dense)                    (None, 101)           413797      drop7[0][0]                      
====================================================================================================
Total params: 134637413
____________________________________________________________________________________________________

LOADING WEIGHTS
Traceback (most recent call last):
  File "caffe2keras.py", line 45, in <module>
    main(args)
  File "caffe2keras.py", line 34, in main
    model = convert.caffe_to_keras(args.load_path+'/'+args.prototxt, args.load_path+'/'+args.caffemodel, debug=args.debug)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/caffe/convert.py", line 62, in caffe_to_keras
    weights = convert_weights(param_layers, v, debug)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.0-py2.7.egg/keras/caffe/convert.py", line 395, in convert_weights
    nb_filter = int(blobs[0].shape.dim[0])
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/containers.py", line 204, in __getitem__
    return self._values[key]
IndexError: list index out of range

Please tell me what is the problem

**Comment by hemangjethava** [comment]
Hi @adelsalehali1982 , I am getting same error as yours when i try to convert caffe model to keras! Please let me know if you have found a solution. Thank you!

**Comment by w5688414** [comment]
I also get the same error, 
`eric@eric-ms-7a54:~/Documents/keras/keras/caffe$ python caffe2keras.py -load_path 'models/' -prototxt 'train_val_for_keras.prototxt' \
>                            -caffemodel 'bvlc_googlenet.caffemodel'
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Converting model...
Traceback (most recent call last):
  File "caffe2keras.py", line 49, in <module>
    main(arguments)
  File "caffe2keras.py", line 35, in main
    debug=args.debug)
  File "/home/eric/Documents/keras/keras/caffe/convert.py", line 34, in caffe_to_keras
    input_dim.append(int(layers[0].input_param.shape[0].dim[0]))
IndexError: list index out of range
`
