### ISSUE TITLE
Convolution2D: wrong output shape 

### ISSUE THREAD

**Issue by amarczew** [fchollet/keras#4293]
I wrote an autoencoder based on this [tutorial](https://blog.keras.io/building-autoencoders-in-keras.html), but I got errors related to shapes. I was trying to understand the error and I found out the output on sample is wrong as well. See the sample on GitHub Gist. 

https://gist.github.com/amarczew/418e617c567bd3d248f5c4a585c611a2

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by tboquet** [comment]
You should take a look at your Keras config file and the `image_dim_ordering` value. Try to change it from one to the other (`th` => `tf` or `tf` => `th`).

**Comment by amarczew** [comment]
@tboquet, perfect! I really didn't see that parameter in keras config file. Thank you for your answer.
