### ISSUE TITLE
MissingInputError when trying to eval shape (or other information) of objective function arguments (y_true,y_pred)

### ISSUE THREAD

**Issue by ghost** [fchollet/keras#4307]
I am trying to get the shape information of the arguments passed to the objective functions in Keras, but I always get missing input errors.

For example, the following code:
````
def custom_mse(y_true,y_pred):
    print K.eval(y_true.shape)
    return K.mean(K.square(y_pred - y_true), axis=-1) 
````
returns the following error when executing model.compile:
````
theano.gof.fg.MissingInputError: ("An input of the graph, used to compute Shape(dense_2_target), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", dense_2_target)
````
The same function runs fine without the K.eval line. What is wrong with my code? Is there no way to access information/attributes related to the objective function arguments?

**Comment by crosleythomas** [comment]
@ZetaOri Did you ever figure this out?
