### ISSUE TITLE
[Suggestion for improvement] Snapshot Ensemble

### ISSUE THREAD

**Issue by jaybosamiya** [fchollet/keras#4309]
The paper ["Snapshot Ensembles : Train 1, Get M for Free"](http://openreview.net/pdf?id=BJYwwY9ll) proposes a technique to be able to train an ensemble of neural networks without additional training cost.

One implementation is at https://github.com/gaohuang/SnapshotEnsemble

It would be great to add this into Keras. :)

**Comment by titu1994** [comment]
@jaybosamiya I've implemented the technique in my repository https://github.com/titu1994/Snapshot-Ensembles.

I don't have a large enough GPU to train WRN-34-4 or DenseNet-100, so it currently has the weights for WRN-16-4 instead. It has been trained on CIFAR-10 for now, but I will be training it on CIFAR-100 later as well. Sadly, I can't train the model on the Tiny ImageNet but it's pretty simple for someone to do that.
