### ISSUE TITLE
Does Keras Generator resize the image when the dimensions are the same?

### ISSUE THREAD

**Issue by Neltherion** [fchollet/keras#4310]
I have a huge dataset of images which are fetched by the Keras Generator and it seems the generator uses PIL to read and resize the images.

The generator asks for a `target_size` to be given which has a default value of `[256,256]`.

I'd like to remove the overhead of resizing the images when the generator is fetching them, so I wanted to know if it would help to resize the images once offline and then use the generator to read the files (hopefully without the overhead)?

Would the Generator ignore resizing the images once it checks that the target_size is the same as the image dimensions?

**Comment by ColaColin** [comment]
I've also just run into this, setting save_to_dir effectively rescales the images back to the 0-255 range, causing the rescale option to be without any effect.

Definitely an issue.
