### ISSUE TITLE
Merge time steps

### ISSUE THREAD

**Issue by dr-costas** [fchollet/keras#4311]
Hi, 

How can one merge time steps with LSTMs? 

If we have 3 layers of LSTM (stacked) and h1_t is the output of the 1st layer in timestep t, how can one give as input to the second layer the: h1to2_t = [h1_t; h1_t+1] ?

This means that at the second layer will be half time steps than the first one.

**Comment by kilotaras** [comment]
use LambdaLayer and slicing, the merge

```
i2_1 = Lambda(lambda x: x[:, ::2])(h1)
i2_2 = Lambda(lambda x: x[:, 1::2])(h1)
i2 = merge([i2_1, i2_2], mode='concat')
```
