### ISSUE TITLE
How to make Input data for FCN (Fully Convolutional Net) where input data size varies?

### ISSUE THREAD

**Issue by zxu7** [fchollet/keras#4317]
I am trying to run a FCN for my images of different shapes. I read in another thread to have my input like Input((1, None, None)), meaning that the image has one color channel and of unfixed size. The problem comes as I don't know how to format my input data. I now have them as list of numpy arrays and run the model by generator function, feeding one image at a time of numpy array type. but as I run it, Python gives following error: 

ValueError: all the input array dimensions except for the concatenation axis must match exactly
Apply node that caused the error: Join(TensorConstant{1}, Reshape{4}.0, Elemwise{Composite{(i0 * (Abs(i1) + i2 + i3))}}.0)
Toposort index: 306
Inputs types: [TensorType(int8, scalar), TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(), (1, 512, 8, 16), (1, 256, 9, 16)]
Inputs strides: [(), (262144, 512, 64, 4), (147456, 576, 64, 4)]

My generator function is

def my_generator():

    tot = len(imgs_train) * 2
    print('Total images in data set:', tot)
    Xb = imgs_train * 2
    Yb = imgs_mask_train * 2
    
    for i in range(len(imgs_train)):
        Xb[i], Yb[i] = horz_flip(Xb[i],Yb[i],hor_p)
    arr = np.random.permutation(tot)
    # yield Xb[arr], Yb[arr]
    batch_size = 1
    k = 0
    while k < tot:
        end = k + batch_size
        if end > tot:
            end = tot
        idx = arr[k:end]
        idx = int(idx)
        yield Xb[idx], Yb[idx]
        k += batch_size

Both imgs_train and imgs_mask_train are list of numpy arrays.

How can I fix it?

**Comment by pechersky** [comment]
Your error is somewhere in the architecture of your layers. Could you share it? Also, can you link the thread that suggested passing `(..., None, None)` for the input shapes? What's probably happening is that it cannot infer the variable-shape matching, and is throwing you the error.
