### ISSUE TITLE
Attention model

### ISSUE THREAD

**Issue by adelsalehali1982** [fchollet/keras#4324]
Hi Guys,
I was trying to implement a simple idea related the attention model.
What I'm trying  to do is as follows:
1-given a clip of video which contains 16 frame which can be described by one vector using C3D model as a context.
2- every frame  can be described by VGG model.
my question is: 
how can I do  to calculate the contribution of every frame to to get the context. literally  the value of z in the attached image  [here](https://heuritech.files.wordpress.com/2016/01/detail_attentionmodel1.png?w=768)  using keras?.  The target will be the class of the clip.

here in Image of what I'm trying to implement 

https://heuritech.files.wordpress.com/2016/01/detail_attentionmodel1.png?w=768

Best,
Adel

**Comment by phdowling** [comment]
Perhaps the AttentionSeq2Seq model from [seq2seq](https://github.com/farizrahman4u/seq2seq) can help you. If you need to implement this at a lower level, try [recurrentshop](https://github.com/farizrahman4u/recurrentshop), which is what seq2seq is built on.
