### ISSUE TITLE
Fractional strides in convolution layers

### ISSUE THREAD

**Issue by 23pointsNorth** [fchollet/keras#4331]
Hello,

I am working on re-implementing the [`Generative and Discriminative Voxel Modeling with CNNs`](https://arxiv.org/abs/1608.04236). At the decoder level of the architecture, they are using fractionally strided convolutions - as shown [here](https://github.com/ajbrock/Generative-and-Discriminative-Voxel-Modeling/blob/master/Generative/VAE.py#L151). 

Using TF 0.10rc0 with latest keras, it is not possible to perform e.g. `Convolution3D(32, 3, 3, 3, activation='relu', subsample=(0.5, 0.5, 0.5))(x)`, with a generated error in tf 

>ZeroDivisionError: Intiger division or modulo by zero

Is there a workaround without explicitly performing upsampling in 3D?

-Daniel

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by ajbrock** [comment]
Hi Daniel,

I'm the author of that paper/repo--I think you should note that I wrote that when I was just starting out, and that it's unusual to actually specify a fraction or a float for a stride--usually you'll want something like a "transposedconv" layer that takes the backward pass of a strided convoluton (similar to the [this](https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L496)). You should note that in that version of the code I do exactly this, and have a conditional that notes if the provided stride is fractional and just takes 1/stride to be the stride of the transposed conv. 

I'm a Theano/Lasagne user, but I think that in tensorflow if this doesn't already exist the easiest way to make this happen would be to modify [the nn_op in Tensorflow here](https://github.com/tensorflow/tensorflow/blob/1d76583411038767f673a0c96174c80eaf9ff42f/tensorflow/python/ops/nn_ops.py#L24) to use the backward pass of the 3D conv instead, which is exactly what I did for the voxel-based VAE.

Hope that helps!

**Comment by 23pointsNorth** [comment]
Hi Andy, 

My initial assumption was to use the `transposedconv` or `deconv` layers. However, only recently is it actually going to be available for 3D (#4457)  without having to explicitly code my own operations. 

Thus, from a logical standpoint and the observed code, it made sense as an extension. I assumed my API knowledge was lacking. 

- Daniel
