### ISSUE TITLE
Build our own batch of input data

### ISSUE THREAD

**Issue by amnKhatami** [fchollet/keras#4337]
10000 images are feed to a CNN system as a training set with batches of 128. The question is that we want to create our own batch data, rather than the random one. More specifically, these 128 images setting as one batch are selected specifically. Is there any way in Keras? I appreciate any help.

**Comment by the-moliver** [comment]
Yup! Just use a generator and model.fit_generator.

**Comment by amnKhatami** [comment]
@the-moliver Thanks for the reply. I am new in Keras. Would you please just provide me a link of example of the generator?

**Comment by varun-bankiti** [comment]
@amnKhatami you can find a sample custom generator function [here](https://github.com/fchollet/keras/blob/master/tests/keras/test_multiprocessing.py#L17).
