### ISSUE TITLE
python does not work

### ISSUE THREAD

**Issue by LuM2016** [fchollet/keras#4343]
apply keras to run mnist_cnn.py, when it achieves at model.fit(), the python.exe does not work.why?

**Comment by LuM2016** [comment]
Runing mnist_cnn.py, when it achieves at model.fit(), the python does not work.why?

**Comment by phdowling** [comment]
You're gonna have to be a tiny bit more specific

**Comment by jwarren1984** [comment]
The python has to be fed first for optimal results. I recommend medium sized rodents.

**Comment by farizrahman4u** [comment]
I was having the same issue.. [this](https://www.quora.com/Snakes-How-long-after-feeding-my-python-should-I-wait-before-handling-her-again) helped me.

**Comment by carlthome** [comment]
@farizrahman4u :laughing:

**Comment by LuM2016** [comment]
Could you describe in detail? I am the first time to contact with keras and python. thanks!






At 2016-11-14 01:48:29, "Fariz Rahman" <notifications@github.com> wrote:


I was having the same issue.. this helped me.

**Comment by kgrm** [comment]
@LuM2016 please refer to the following tutorial: https://youtu.be/jCpc72vJ2p8
