### ISSUE TITLE
Custom loss function for sampling loss area

### ISSUE THREAD

**Issue by KlaymenGC** [fchollet/keras#4345]
Hello,

I have an end-to-end network (like FCN), which has the input shape: 
```(batch_size, channel, img_col, img_row)```

and the output shape:
```(batch_size, img_col, img_row, num_class)```

the labels are one-hot-encoded and have the shape:
```(batch_size, img_col, img_row, num_class)```

When computing the loss, I don´t want to compute the loss for the whole output but just compute on the randomly sampling part of the whole region. The custom loss function is like:
```python
def custom_loss_fun(y_true, y_pred)

      from theano.tensor.shared_randomstreams import RandomStreams

      # reshape to (batch_size*img_col*img_row, n_class)
      y_pred = y_pred.dimshuffle(3, 0, 1, 2).flatten(2).dimshuffle(1, 0)
      y_true = y_true.dimshuffle(3, 0, 1, 2).flatten(2).dimshuffle(1, 0)
      
      # sampling
      mask_size = y_true.shape[0]
      rs = RandomStreams(seed=234)
      # make mask for sampling
      mask = rs.binomial(n=1, p=0.8, size=mask_size)
      # get the indices
      label_idx = (mask > 0).nonzero()
     
      y_pred = y_pred[label_idx] # size has changed
      y_true = y_true[label_idx] # size has changed
      
      return keras.objectives.categorical_crossentropy(y_true, y_pred)
```
The error is as follows: 

Note: ```batch_size = 2, batch_size * img_col * img_row = 921600```

```python
Traceback (most recent call last):
  File "C:\lib\site-packages\theano\compile\function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[0] = 921600, input[1].shape[0] = 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
.......
  File "C:\lib\site-packages\theano\compile\function_module.py", line 859, in __call__
    outputs = self.fn()
ValueError: Input dimension mis-match. (input[0].shape[0] = 921600, input[1].shape[0] = 2)
Apply node that caused the error: Elemwise{mul,no_inplace}(mean, reshape_2_sample_weights)
Toposort index: 1709
Inputs types: [TensorType(float32, vector), TensorType(float32, vector)]
Inputs shapes: [(921600,), (2,)]   
Inputs strides: [(4,), (4,)]
Inputs values: ['not shown', array([ 1.,  1.], dtype=float32)]
Outputs clients: [[Elemwise{true_div,no_inplace}(Elemwise{mul,no_inplace}.0, DimShuffle{x}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
 .....
  File "C:/.....py", line 436, in train_model
    model.compile(loss=self.sampled_loss_CE, optimizer='adam', metrics=[keras.metrics.categorical_accuracy])
  File "C:\lib\site-packages\keras\engine\training.py", line 625, in compile
    sample_weight, mask)
  File "C:\lib\site-packages\keras\engine\training.py", line 344, in weighted
    score_array *= weights

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

any ideas?

**Comment by pechersky** [comment]
You probably have to reshape your loss tensor back to the original shape so it can be propagated back. Currently,  your metric is being called on `y_true, y_pred` that are of different shape than what the `model.loss` uses and expects downstream.

**Comment by KlaymenGC** [comment]
@pechersky Thank you for the reply. Sorry I had an error in the comments, the size of ```y_pred, y_true``` in the end has changed. Could you please elaborate?

**Comment by pechersky** [comment]
Since the size of the tensors `y_true, y_pred` you are calculating your objective on has changed, the resulting objective tensor is now that new size. However, the model expects the objective tensor to be of the same shape as the original batch. This comes out in your code when the objective tensor (`score_array`) is being scaled by the `weights` you are using (it seems you are passing in `sample_weight`). 

To fix it, I suggest figuring out how to "undo" the `flatten` and `dimshuffle` operations, so that you get back an objective tensor where the first dimension is your `batch_size`. This will allow your `score_array` to be scaled properly, and then `mean`ed.

**Comment by pechersky** [comment]
Did it work?

**Comment by KlaymenGC** [comment]
@pechersky thank you for your help, it seems to be working now, I'll check the result when the training is done.

**Comment by KlaymenGC** [comment]
@pechersky actually I've got another problem, say the values of the label ```y_true``` are ranging from 0 to N, now I want to ignore all the 0s when calculating the loss. Then for every single image in one batch, the number of pixels will be different, then I guess it wouldn't be possible in Keras? @fchollet

**Comment by pechersky** [comment]
You want to supply a `sample_weight` when you fit, that has 1 where you
want to keep the pixel, and 0 where you don't. Since your inputs seem to be
2D per sample, you'll have to have make sure the weights are the right
dimension. If you want to weigh rows instead, as in have weights be one
dimension smaller, then compile the model with
`sample_weight_mode='temporal'`.

**Comment by KlaymenGC** [comment]
@pechersky I think in this case maybe the ```class_weight``` would make more sense? But I still find it not so easy to do. The thing is, I have N+1 classes in the labels but now I'm only interested in N classes and the model has already been defined to classify N classes, so my intuition to do this is to mask the original labels, delete the undesired class label values and put the rest in loss calculation.
