### ISSUE TITLE
why is keras installing for python 2.7 and not 3.5?

### ISSUE THREAD

**Issue by rshpeley** [fchollet/keras#4349]
I installed tensorflow for python3.5 following the anaconda instructions. Then I installed keras within the tensorflow environment. It installs for python2.7, which is the default python outside of the conda environment on a Ubuntu 14.04 system.

This is my third try and still no luck...

--------------------------

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [ x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ -] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

sudo python setup.py install
running install
running bdist_egg
running egg_info
creating Keras.egg-info
writing requirements to Keras.egg-info/requires.txt
writing Keras.egg-info/PKG-INFO
writing top-level names to Keras.egg-info/top_level.txt
writing dependency_links to Keras.egg-info/dependency_links.txt
writing manifest file 'Keras.egg-info/SOURCES.txt'
reading manifest file 'Keras.egg-info/SOURCES.txt'
writing manifest file 'Keras.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/keras
copying keras/regularizers.py -> build/lib.linux-x86_64-2.7/keras
copying keras/__init__.py -> build/lib.linux-x86_64-2.7/keras
copying keras/metrics.py -> build/lib.linux-x86_64-2.7/keras
copying keras/objectives.py -> build/lib.linux-x86_64-2.7/keras
copying keras/constraints.py -> build/lib.linux-x86_64-2.7/keras
copying keras/initializations.py -> build/lib.linux-x86_64-2.7/keras
copying keras/activations.py -> build/lib.linux-x86_64-2.7/keras
copying keras/optimizers.py -> build/lib.linux-x86_64-2.7/keras
copying keras/callbacks.py -> build/lib.linux-x86_64-2.7/keras
copying keras/models.py -> build/lib.linux-x86_64-2.7/keras
creating build/lib.linux-x86_64-2.7/keras/utils
copying keras/utils/__init__.py -> build/lib.linux-x86_64-2.7/keras/utils
copying keras/utils/data_utils.py -> build/lib.linux-x86_64-2.7/keras/utils
copying keras/utils/test_utils.py -> build/lib.linux-x86_64-2.7/keras/utils
copying keras/utils/layer_utils.py -> build/lib.linux-x86_64-2.7/keras/utils
copying keras/utils/np_utils.py -> build/lib.linux-x86_64-2.7/keras/utils
copying keras/utils/generic_utils.py -> build/lib.linux-x86_64-2.7/keras/utils
copying keras/utils/visualize_util.py -> build/lib.linux-x86_64-2.7/keras/utils
copying keras/utils/io_utils.py -> build/lib.linux-x86_64-2.7/keras/utils
creating build/lib.linux-x86_64-2.7/keras/engine
copying keras/engine/__init__.py -> build/lib.linux-x86_64-2.7/keras/engine
copying keras/engine/topology.py -> build/lib.linux-x86_64-2.7/keras/engine
copying keras/engine/training.py -> build/lib.linux-x86_64-2.7/keras/engine
creating build/lib.linux-x86_64-2.7/keras/legacy
copying keras/legacy/__init__.py -> build/lib.linux-x86_64-2.7/keras/legacy
copying keras/legacy/models.py -> build/lib.linux-x86_64-2.7/keras/legacy
creating build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/__init__.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/advanced_activations.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/recurrent.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/pooling.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/convolutional_recurrent.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/core.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/normalization.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/local.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/noise.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/convolutional.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/embeddings.py -> build/lib.linux-x86_64-2.7/keras/layers
copying keras/layers/wrappers.py -> build/lib.linux-x86_64-2.7/keras/layers
creating build/lib.linux-x86_64-2.7/keras/applications
copying keras/applications/__init__.py -> build/lib.linux-x86_64-2.7/keras/applications
copying keras/applications/vgg16.py -> build/lib.linux-x86_64-2.7/keras/applications
copying keras/applications/audio_conv_utils.py -> build/lib.linux-x86_64-2.7/keras/applications
copying keras/applications/xception.py -> build/lib.linux-x86_64-2.7/keras/applications
copying keras/applications/resnet50.py -> build/lib.linux-x86_64-2.7/keras/applications
copying keras/applications/inception_v3.py -> build/lib.linux-x86_64-2.7/keras/applications
copying keras/applications/music_tagger_crnn.py -> build/lib.linux-x86_64-2.7/keras/applications
copying keras/applications/imagenet_utils.py -> build/lib.linux-x86_64-2.7/keras/applications
copying keras/applications/vgg19.py -> build/lib.linux-x86_64-2.7/keras/applications
creating build/lib.linux-x86_64-2.7/keras/datasets
copying keras/datasets/__init__.py -> build/lib.linux-x86_64-2.7/keras/datasets
copying keras/datasets/cifar10.py -> build/lib.linux-x86_64-2.7/keras/datasets
copying keras/datasets/data_utils.py -> build/lib.linux-x86_64-2.7/keras/datasets
copying keras/datasets/cifar.py -> build/lib.linux-x86_64-2.7/keras/datasets
copying keras/datasets/reuters.py -> build/lib.linux-x86_64-2.7/keras/datasets
copying keras/datasets/imdb.py -> build/lib.linux-x86_64-2.7/keras/datasets
copying keras/datasets/mnist.py -> build/lib.linux-x86_64-2.7/keras/datasets
copying keras/datasets/cifar100.py -> build/lib.linux-x86_64-2.7/keras/datasets
creating build/lib.linux-x86_64-2.7/keras/preprocessing
copying keras/preprocessing/__init__.py -> build/lib.linux-x86_64-2.7/keras/preprocessing
copying keras/preprocessing/image.py -> build/lib.linux-x86_64-2.7/keras/preprocessing
copying keras/preprocessing/sequence.py -> build/lib.linux-x86_64-2.7/keras/preprocessing
copying keras/preprocessing/text.py -> build/lib.linux-x86_64-2.7/keras/preprocessing
creating build/lib.linux-x86_64-2.7/keras/backend
copying keras/backend/__init__.py -> build/lib.linux-x86_64-2.7/keras/backend
copying keras/backend/tensorflow_backend.py -> build/lib.linux-x86_64-2.7/keras/backend
copying keras/backend/common.py -> build/lib.linux-x86_64-2.7/keras/backend
copying keras/backend/theano_backend.py -> build/lib.linux-x86_64-2.7/keras/backend
creating build/lib.linux-x86_64-2.7/keras/wrappers
copying keras/wrappers/__init__.py -> build/lib.linux-x86_64-2.7/keras/wrappers
copying keras/wrappers/scikit_learn.py -> build/lib.linux-x86_64-2.7/keras/wrappers
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/regularizers.py -> build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/__init__.py -> build/bdist.linux-x86_64/egg/keras
creating build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/__init__.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/data_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/test_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/layer_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/np_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/generic_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/visualize_util.py -> build/bdist.linux-x86_64/egg/keras/utils
copying build/lib.linux-x86_64-2.7/keras/utils/io_utils.py -> build/bdist.linux-x86_64/egg/keras/utils
creating build/bdist.linux-x86_64/egg/keras/engine
copying build/lib.linux-x86_64-2.7/keras/engine/__init__.py -> build/bdist.linux-x86_64/egg/keras/engine
copying build/lib.linux-x86_64-2.7/keras/engine/topology.py -> build/bdist.linux-x86_64/egg/keras/engine
copying build/lib.linux-x86_64-2.7/keras/engine/training.py -> build/bdist.linux-x86_64/egg/keras/engine
creating build/bdist.linux-x86_64/egg/keras/legacy
copying build/lib.linux-x86_64-2.7/keras/legacy/__init__.py -> build/bdist.linux-x86_64/egg/keras/legacy
copying build/lib.linux-x86_64-2.7/keras/legacy/models.py -> build/bdist.linux-x86_64/egg/keras/legacy
creating build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/__init__.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/advanced_activations.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/recurrent.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/pooling.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/convolutional_recurrent.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/core.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/normalization.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/local.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/noise.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/convolutional.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/embeddings.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/layers/wrappers.py -> build/bdist.linux-x86_64/egg/keras/layers
copying build/lib.linux-x86_64-2.7/keras/metrics.py -> build/bdist.linux-x86_64/egg/keras
creating build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/__init__.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/vgg16.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/audio_conv_utils.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/xception.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/resnet50.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/inception_v3.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/music_tagger_crnn.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/imagenet_utils.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/applications/vgg19.py -> build/bdist.linux-x86_64/egg/keras/applications
copying build/lib.linux-x86_64-2.7/keras/objectives.py -> build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/constraints.py -> build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/initializations.py -> build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/activations.py -> build/bdist.linux-x86_64/egg/keras
creating build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/__init__.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/cifar10.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/data_utils.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/cifar.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/reuters.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/imdb.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/mnist.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/datasets/cifar100.py -> build/bdist.linux-x86_64/egg/keras/datasets
copying build/lib.linux-x86_64-2.7/keras/optimizers.py -> build/bdist.linux-x86_64/egg/keras
creating build/bdist.linux-x86_64/egg/keras/preprocessing
copying build/lib.linux-x86_64-2.7/keras/preprocessing/__init__.py -> build/bdist.linux-x86_64/egg/keras/preprocessing
copying build/lib.linux-x86_64-2.7/keras/preprocessing/image.py -> build/bdist.linux-x86_64/egg/keras/preprocessing
copying build/lib.linux-x86_64-2.7/keras/preprocessing/sequence.py -> build/bdist.linux-x86_64/egg/keras/preprocessing
copying build/lib.linux-x86_64-2.7/keras/preprocessing/text.py -> build/bdist.linux-x86_64/egg/keras/preprocessing
copying build/lib.linux-x86_64-2.7/keras/callbacks.py -> build/bdist.linux-x86_64/egg/keras
copying build/lib.linux-x86_64-2.7/keras/models.py -> build/bdist.linux-x86_64/egg/keras
creating build/bdist.linux-x86_64/egg/keras/backend
copying build/lib.linux-x86_64-2.7/keras/backend/__init__.py -> build/bdist.linux-x86_64/egg/keras/backend
copying build/lib.linux-x86_64-2.7/keras/backend/tensorflow_backend.py -> build/bdist.linux-x86_64/egg/keras/backend
copying build/lib.linux-x86_64-2.7/keras/backend/common.py -> build/bdist.linux-x86_64/egg/keras/backend
copying build/lib.linux-x86_64-2.7/keras/backend/theano_backend.py -> build/bdist.linux-x86_64/egg/keras/backend
creating build/bdist.linux-x86_64/egg/keras/wrappers
copying build/lib.linux-x86_64-2.7/keras/wrappers/__init__.py -> build/bdist.linux-x86_64/egg/keras/wrappers
copying build/lib.linux-x86_64-2.7/keras/wrappers/scikit_learn.py -> build/bdist.linux-x86_64/egg/keras/wrappers
byte-compiling build/bdist.linux-x86_64/egg/keras/regularizers.py to regularizers.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/data_utils.py to data_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/test_utils.py to test_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/layer_utils.py to layer_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/np_utils.py to np_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/generic_utils.py to generic_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/visualize_util.py to visualize_util.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/utils/io_utils.py to io_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/engine/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/engine/topology.py to topology.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/engine/training.py to training.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/legacy/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/legacy/models.py to models.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/advanced_activations.py to advanced_activations.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/recurrent.py to recurrent.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/pooling.py to pooling.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/convolutional_recurrent.py to convolutional_recurrent.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/core.py to core.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/normalization.py to normalization.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/local.py to local.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/noise.py to noise.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/convolutional.py to convolutional.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/embeddings.py to embeddings.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/layers/wrappers.py to wrappers.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/metrics.py to metrics.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/vgg16.py to vgg16.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/audio_conv_utils.py to audio_conv_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/xception.py to xception.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/resnet50.py to resnet50.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/inception_v3.py to inception_v3.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/music_tagger_crnn.py to music_tagger_crnn.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/imagenet_utils.py to imagenet_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/applications/vgg19.py to vgg19.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/objectives.py to objectives.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/constraints.py to constraints.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/initializations.py to initializations.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/activations.py to activations.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/cifar10.py to cifar10.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/data_utils.py to data_utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/cifar.py to cifar.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/reuters.py to reuters.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/imdb.py to imdb.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/mnist.py to mnist.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/datasets/cifar100.py to cifar100.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/optimizers.py to optimizers.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/preprocessing/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/preprocessing/image.py to image.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/preprocessing/sequence.py to sequence.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/preprocessing/text.py to text.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/callbacks.py to callbacks.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/models.py to models.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/backend/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/backend/tensorflow_backend.py to tensorflow_backend.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/backend/common.py to common.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py to theano_backend.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/wrappers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/keras/wrappers/scikit_learn.py to scikit_learn.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Keras.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Keras.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Keras.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Keras.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Keras.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
keras.backend.theano_backend: module MAY be using inspect.stack
creating dist
creating 'dist/Keras-1.1.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Keras-1.1.1-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg
Extracting Keras-1.1.1-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding Keras 1.1.1 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/Keras-1.1.1-py2.7.egg
Processing dependencies for Keras==1.1.1
Searching for theano
Reading https://pypi.python.org/simple/theano/
Best match: Theano 0.8.2
Downloading https://pypi.python.org/packages/30/3d/2354fac96ca9594b755ec22d91133522a7db0caa0877165a522337d0ed73/Theano-0.8.2.tar.gz#md5=f2d0dfe7df141115201077cd933b2c52
Processing Theano-0.8.2.tar.gz
Writing /tmp/easy_install-gPndjR/Theano-0.8.2/setup.cfg
Running Theano-0.8.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gPndjR/Theano-0.8.2/egg-dist-tmp-GYC8zn
warning: manifest_maker: MANIFEST.in, line 9: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

zip_safe flag not set; analyzing archive contents...
theano.misc.elemwise_openmp_speedup: module references __file__
theano.misc.check_blas: module references __file__
theano.compat.six: module references __path__
theano.gof.op: module MAY be using inspect.trace
theano.gof.cmodule: module references __file__
theano.gof.lazylinker_c: module references __path__
theano.gof.toolbox: module MAY be using inspect.getframeinfo
theano.gof.tests.test_fg: module references __file__
theano.scan_module.scan_perform_ext: module references __path__
theano.scan_module.tests.test_scan: module references __file__
theano.compile.function: module references __file__
theano.sandbox.cuda.blas: module references __file__
theano.sandbox.cuda.nvcc_compiler: module references __file__
theano.sandbox.cuda.dnn: module references __file__
theano.sandbox.cuda.__init__: module references __file__
theano.sandbox.cuda.type: module references __file__
theano.sandbox.cuda.type: module references __path__
theano.sandbox.cuda.tests.test_dnn: module references __file__
theano.sandbox.cuda.tests.test_type: module references __file__
theano.sandbox.gpuarray.blas: module references __file__
theano.sandbox.gpuarray.comp: module references __file__
theano.sandbox.gpuarray.dnn: module references __file__
theano.sandbox.gpuarray.subtensor: module references __file__
theano.sandbox.gpuarray.nerv: module references __file__
theano.sandbox.gpuarray.basic_ops: module references __file__
theano.sandbox.gpuarray.tests.test_type: module references __file__
theano.sandbox.gpuarray.tests.test_pickle: module references __file__
theano.sandbox.tests.test_multinomial: module references __file__
theano.sandbox.tests.test_rng_mrg: module references __file__
theano.d3viz.d3viz: module references __file__
theano.d3viz.d3viz: module references __path__
theano.tests.test_flake8: module references __path__
theano.tests.run_tests_in_batch: module references __path__
theano.tests.main: module references __file__
theano.tensor.nnet.corr: module references __file__
theano.tensor.nnet.sigm: module references __file__
theano.tensor.tests.test_mpi: module references __file__
theano.tensor.tests.test_opt: module references __file__
Adding Theano 0.8.2 to easy-install.pth file
Installing theano-test script to /usr/local/bin
Installing theano-cache script to /usr/local/bin
Installing theano-nose script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/Theano-0.8.2-py2.7.egg
error: Installed distribution six 1.5.2 conflicts with requirement six>=1.9.0
(tensorflow) shpeley@shpeley-gpu:~/keras$ conda list
 packages in environment at /home/shpeley/miniconda3/envs/tensorflow:

h5py                      2.6.0               np111py35_2  
hdf5                      1.8.17                        1  
libgfortran               3.0.0                         1  
mkl                       11.3.3                        0  
numpy                     1.11.2                    <pip>
numpy                     1.11.2                   py35_0  
openssl                   1.0.2j                        0  
pip                       9.0.1                    py35_0  
protobuf                  3.0.0                     <pip>
python                    3.5.2                         0  
pyyaml                    3.12                     py35_0  
readline                  6.2                           2  
scipy                     0.18.1              np111py35_0  
setuptools                27.2.0                   py35_0  
setuptools                28.8.0                    <pip>
six                       1.10.0                    <pip>
six                       1.10.0                   py35_0  
sqlite                    3.13.0                        0  
tensorflow                0.11.0rc2                 <pip>
tk                        8.5.18                        0  
wheel                     0.29.0                    <pip>
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3

**Comment by rshpeley** [comment]
I just tried `pip install keras` and that seemed to work, although `sudo pip install keras` didn't.

**Comment by kilotaras** [comment]
`sudo python/pip` uses system python and installs systemwide libraries. Use python/pip without sudo if you want to work in virtualenvironment

**Comment by lemuriandezapada** [comment]
does ```sudo python3 setup.py install``` not work?
or ```sudo pip3 install keras``` or ```sudo pip-python3 install keras```?
