### ISSUE TITLE
downgrade keras

### ISSUE THREAD

**Issue by Yang507** [fchollet/keras#4364]
I want to install keras and downgrade to 1.0.1, how can i do it

**Comment by sschnug** [comment]
You tried ```pip install keras==1.0.1``` ?

**Comment by carlthome** [comment]
You really shouldn't though. Why do you need to downgrade?

**Comment by BryanBo-Cao** [comment]
@carlthome some reasons for downgrading could be https://github.com/keras-team/keras/issues/9621

**Comment by adibyte95** [comment]
check <a href ='https://github.com/bstriner/keras-adversarial/issues/51'>this</a> link
