### ISSUE TITLE
Is it possible to merge  a input tensor with a layer?

### ISSUE THREAD

**Issue by Wenhao-Jin** [fchollet/keras#4375]
I want to merge a input tensor and a sequential model. Do you have any idea of how to implement it?
Here is my code, but it doesn't work as keras cannot merge a tensor with layer:
model1 = Sequential()
model1.add(Dense(8))
model1.add(Activation('relu'))
input2=Input((3,))

model_merged=Sequential()
model_merged.add(Merge([model1, input2], mode='concat'))
model_merged.add(Dense(8))
model.add(Activation('relu'))
......

The error is : 
AttributeError: 'Tensor' object has no attribute 'get_output_shape_at'.

If there is no way to merge the tensor object with layers, could I make the input tensor as a layer so that it becomes a task of merging two layers? How to do that? 
Great thanks~

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Wenhao-Jin** [comment]
Oh, I figured it out. I can use the Model API to do it. Here is the doc: https://keras.io/getting-started/functional-api-guide/ , the 'Multi-input and multi-output models' section is useful for my question.

**Comment by naisanza** [comment]
@Wenhao-Jin what was your model that you ended up using?

**Comment by Wenhao-Jin** [comment]
@naisanza  What do you mean by model? The deep learning model I'm using? Or the model API?

**Comment by naisanza** [comment]
@Wenhao-Jin the deep learning model that you're using
