### ISSUE TITLE
How to obtain the weights of parts of neural layers?

### ISSUE THREAD

**Issue by Jellyyoung** [fchollet/keras#4378]
&emsp;&emsp;The latest keras has not supported the AutoEncoder，so I write the following code to create the stacked autoencoder:
```python
input_data = Input(shape = (784,)) #输入数据的占位符
encoder_1 = Dense(512,activation = "relu")(input_data)
encoder_2 = Dense(256,activation = "relu")(encoder_1)
encoder_3 = Dense(128,activation = "relu")(encoder_2)

#解码可以理解为对已编码数据根据损失函数进行重建的过程
decoder_1 = Dense(64,activation = "relu")(encoder_3)
decoder_2 = Dense(128,activation = "relu")(decoder_1)
decoder_3 = Dense(784,activation = "relu")(decoder_2)
# autoencoder = Model(input = input_data,output = decoder_3)

autoencoder = Model(input = input_data,output = decoder_3)
autoencoder.compile(optimizer = "adadelta",loss = "binary_crossentropy")
autoencoder.fit(X_pretrain,X_pretrain,batch_size = batch_cnt, nb_epoch = epoch_cnt)
```
&emsp;&emsp;Since the layers of stacked autoencoder is [784  512 256 128 256 512 784], I want to obtain the weights of the first four layers to initialize the weights of neural network whose dimension is [784 584 256 128]. the function `model.save_weights()` saves the weights of all layers. In other words, the `save_weights()` and `load_weights()` doesn't work well.
I ask for help. My Email is yangyd@seu.edu.cn, thank you.

**Comment by jjennings955** [comment]
You probably want model.get_weights() and model.set_weights()
