### ISSUE TITLE
Save LSTM model with its state

### ISSUE THREAD

**Issue by oetcoleman** [fchollet/keras#4379]
Is there a way to save a Keras model containing a stateful LSTM layer with its state information?

I've tried doing `model.save('path/to/file')` but when I load the model back it has lost its state, and I have to call the `predict` method with all of the previous data points to get it back.

**Comment by yukoba** [comment]
I think you have to modify ```save_model()``` and ```load_model()```.
https://github.com/fchollet/keras/blob/master/keras/models.py#L17

**Comment by oetcoleman** [comment]
Thanks - if I understand correctly I need to access the states using
`model.flattened_layers[0].states[0].get_value()`
and then load them back with `set_value()`

**Comment by yukoba** [comment]
When you finished writing, could you send it as a pull request?
I also want to use!
