### ISSUE TITLE
Initiate a ToDo List 

### ISSUE THREAD

**Issue by pranv** [fchollet/keras#44]
Hey,  I'm very interested in contributing to the project.  Can you share a list of things to be done,  probably a roadmap?

**Comment by adammenges** [comment]
Isn't `issues` the todo list?

**Comment by fchollet** [comment]
The short answer as to what the TODO list is, before v1.0:
- more features for convnets. 
- more examples of cool applications.
- a complete test suite.
- Python 2.7-3.4 compatibility (done as of tonight)

Any suggestions as to how/where we should manage a TODO list, milestones, and possibly even feature/issue assignments?

**Comment by adammenges** [comment]
I'd prefer using `issues`. You could tag with milestones, priority, and assign if an item is being worked on by someone.

**Comment by jfsantos** [comment]
+1 to using the issue tracker instead of a text-based list.

**Comment by madisonmay** [comment]
+1 for tagging issues with a few milestones.  Knowing what's mission critical before a v1 / PyPI release will help make sure development effort is focused in the right direction.
