### ISSUE TITLE
How to define Dense layer between Conv layer and LSTM layer?

### ISSUE THREAD

**Issue by hassaku** [fchollet/keras#4403]
I try to implement the following model called LSDNN.

CONVOLUTIONAL, LONG SHORT-TERM MEMORY, FULLY CONNECTED DEEP NEURAL NETWORKS
http://static.googleusercontent.com/media/research.google.com/ja//pubs/archive/43455.pdf

Input -> Conv(+Pool) -> __Dense (to reduce dimension)__ -> LSTM -> Dense -> Output

```
model = Sequential()
model.add(Convolution1D(..., input_shape=(timesteps, data_dim)))
model.add(MaxPooling1D(...))
model.add(Dense(...))  # to reduce dimension
model.add(LSTM(...))
model.add(Dense(...))
model.add(Dense(nb_classes, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

model.fit(...)  # Exception: Input 0 is incompatible with layer dense_1: expected ndim=2, found ndim=3
```

If the first Dense layer is removed, exception not occurs.
But dimension isn't reduced.

How to use Dense layer keeping input shape for LSTM?
Thank you for any help someone can provide.

**Comment by carlthome** [comment]
`LSTM()` expects input of shape `(nb_timesteps, nb_features)` but Dense outputs 1D so use `Reshape()` to add a dummy dimension after the fully-connected layer or use `TimeDistributed(Dense())`.

**Comment by hassaku** [comment]
Thank you for your advice. It's solved by using TimeDistributed now.
