### ISSUE TITLE
Small hack for instantiating a layer from its configuration using layer_from_config.

### ISSUE THREAD

**Issue by duggalrahul** [fchollet/keras#4427]
Hello,

I'm working with Keras 1.1.1 with python 2.7 on ubuntu 14.04.

According to the documentation [here](https://keras.io/layers/about-keras-layers/), the following snippet should instantiate a layer from its configuration.

```python
from keras.models import Sequential
from keras.layers import Dense
from keras.utils.layer_utils import layer_from_config

model = Sequential()
model.add(Dense(output_dim=64, input_dim=100))

config = model.layers[0].get_config()
layer = layer_from_config(config)
```

However, I the following error

```python 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-4a5a56c3cd16> in <module>()
      7 
      8 config = model.layers[0].get_config()
----> 9 layer = layer_from_config(config)
     10 
     11 # config_correct = {}

/home/rahul/anaconda2/lib/python2.7/site-packages/keras/utils/layer_utils.pyc in layer_from_config(config, custom_objects)
     23         globals()[cls_key] = custom_objects[cls_key]
     24 
---> 25     class_name = config['class_name']
     26 
     27     if class_name == 'Sequential':

KeyError: 'class_name'
```

After spending some hours debugging, here is how I got around this issue.

```python
from keras.models import Sequential
from keras.layers import Dense
from keras.utils.layer_utils import layer_from_config

model = Sequential()
model.add(Dense(output_dim=64, input_dim=100))

config = model.layers[0].get_config()
config_correct = {}
config_correct['class_name'] = type(model.layers[0])
config_correct['config'] = config
layer_correct = layer_from_config(config_correct)
```

It would be easier to update this in the documentation meanwhile the get_config method is corrected for every layer type.

Thanks,
Rahul Duggal

**Comment by yukoba** [comment]
According to the documentation of https://github.com/fchollet/keras/blob/master/keras/utils/layer_utils.py#L13
this might be better.

```python
layer = layer_from_config({'class_name': Dense, 'config': config})
```

I wonder why it is not like this.
```python
layer = layer_from_config(class_name=Dense, config=config)
```

**Comment by duggalrahul** [comment]
@yukoba I agree with your points. However wouldn't it be neater to infer the class_name from the layer which is to be reconstructed instead of providing it explicitly?

Like as below 

```python
config = layer.get_config()
reconstructed_layer = layer_from_config({'class_name': type(layer), 'config': config})
```

Also I feel the get_config() method should return a dictionary which contains all the information necessary to reconstruct a layer. So the class_name field should come from the get_config method. I'd like to hear your thought on that.

**Comment by yukoba** [comment]
@fchollet wrote this code in March.
This is the commit https://github.com/fchollet/keras/commit/295bfe4e3ae7e98655b3630a9f83b2df4a82234f

To see this code https://github.com/fchollet/keras/blob/master/keras/legacy/models.py#L735
there was a class name in config.
In Keras 0.3, the class name was ```name``` attribute in config.

Also fchollet wrote this in Layer.get_config().
> The config of a layer does not include connectivity information, nor the layer class name.

I do not know why he decided to remove the class name from config.
