### ISSUE TITLE
fit_generator/flow_from_directory shape bug

### ISSUE THREAD

**Issue by ssieges** [fchollet/keras#4440]
When I run the code in the link at the bottom of this post I get the following error:
Exception: Error when checking model input: expected input_1 to have shape (None, 3, 227, 227) but got array with shape (32, 3, 277, 277)

I specified batch_size=32 in flow_from_directory so fit_generator shouldn't expect 'None' as the batch size. 

I tried changing line 48 from:
inputs = Input(shape=(3,227,227))
to:
inputs = Input(batch_shape=(32,3,227,227))

If I do this I get the following error:
Exception: Error when checking model input: expected input_2 to have shape (32, 3, 227, 227) but got array with shape (32, 3, 277, 277)

This looks like a bug.

Could there be a problem with the way fit_generator reads batch info from the flow_from_directory generator?

I have updated Keras and Theano to the newest releases.

https://gist.github.com/ssieges/61952bf5f0071cc4c8bf23515fc440cc

**Comment by hth013** [comment]
The error is because of different image size, your target size in flow_from_directory should be (227,227), not (277,277).

**Comment by ssieges** [comment]
Thats embarrassing
