### ISSUE TITLE
Load a model and modify intermediate layers

### ISSUE THREAD

**Issue by jsalbert** [fchollet/keras#4450]
Hi, I am loading a VGG-16 CAM model from json (I attach the json [vgg_cam_mod_model.json.zip](https://github.com/fchollet/keras/files/603394/vgg_cam_mod_model.json.zip)) with its corresponding weights and I want to edit intermediate layers of the model in order to deal with different image sizes.

I have seen that there is the .pop() function to remove the last layer, but in my case I want to edit the pool size and strides of the 'CAM_pool' layer which is an AveragePooling2D layer, or if it is also necessary the inputlayer, is it possible to do it?

Case of a fixed image 

`x = np.zeros((1, 3, 720, 1024)) `

` model =
model_from_json(open('models/vgg_cam_mod_model.json').read())`

![screen shot 2016-11-21 at 12 06 59](https://cloud.githubusercontent.com/assets/17982112/20480497/0a1ca798-afe3-11e6-9bc1-5217b4901af7.png)

![screen shot 2016-11-21 at 12 06 20](https://cloud.githubusercontent.com/assets/17982112/20480474/f2be9c28-afe2-11e6-9024-01168ce3f834.png)

Then I have tried:

`pool_layer = model.layers[-5]
pool_layer.pool_size = [45, 64]
pool_layer.strides = [45, 64]`

`model.summary()`
Not doing anything.  

`model.layers[-5] = AveragePooling2D(name="CAM_pool", trainable=True, dim_ordering="th", pool_size=[45, 64], strides=[45, 64], border_mode="valid")(model.layers[-6])`

Error:  `'Activation' object has no attribute 'ndim'`
 
I also tried to define the layer as a GlobalAveragePooling2D in the json: 
`{"class_name": "GlobalAveragePooling2D", "config": {"name": "CAM_pool", "trainable": true, "dim_ordering": "th"}`
Error ` Input 0 is incompatible with layer CAM_fc_flatten: expected ndim >= 3, found ndim=2`

**Do I have to change also the shape of Input Data Layer?** 

`model.layers[0] = Input(shape=(None, 3, 720, 1024))`
Error: `'TensorVariable' object has no attribute 'inbound_nodes'`

Thanks for the help!

**Comment by AJwgnr** [comment]
Hello,
is there any update on this?

**Comment by RamiAwar** [comment]
ping

**Comment by adrcaraf** [comment]
I have done the following for changing Input layer shape. It seems to be working, but I'm not sure if it allows for the alteration of other params of the configuration successfully.

`
json_file = open(rnn_name, 'r')
loaded_json_model = json_file.read()
json_file.close()

# compile model
model = model_from_json(loaded_json_model)

tmp = model.get_config()
tmp['layers'][0]['config']['batch_input_shape'] = (None, depth, height, width, 1)

model = Model.from_config(tmp)
`
