### ISSUE TITLE
PReLU should be channelwise

### ISSUE THREAD

**Issue by singlasahil14** [fchollet/keras#4452]
```

from keras.models import Sequential
from keras.layers.advanced_activations import PReLU
from keras.layers import Convolution2D, MaxPooling2D

model = Sequential()
model.add(Convolution2D(32, 5, 5, input_shape=(28,28,1)))
model.add(PReLU())

model.summary()
```

This script produces the PReLU layer with 18432 parameters. If the PReLU was implemented according to the paper (https://arxiv.org/abs/1502.01852), number of parameters would be 32. Shouldn't this not be implemented that way? It adds an unnecessarily large number of parameters to the model.

**Comment by carlthome** [comment]
What's your `image_dim_ordering`?

**Comment by singlasahil14** [comment]
```
from keras import backend as K
print(K.image_dim_ordering())
```
returns 'tf'

For mnist, image_dim_ordering is '(28, 28, 1)'

**Comment by yukoba** [comment]
The same bug report here. https://github.com/fchollet/keras/issues/3568

https://github.com/fchollet/keras/blob/25dbe8097fba9a6a429e19d0625d78c3b8731527/keras/layers/advanced_activations.py#L66
is `input_shape[1:]` and this should be something like `input_shape[1]` or `input_shape[3]`.

**Comment by the-moliver** [comment]
I submitted a pull request to address this that may work for you in the interim: https://github.com/fchollet/keras/pull/4141

**Comment by yukoba** [comment]
Wow, you have implemented already.
I did the same thing now. https://github.com/yukoba/keras/commit/defaec55d2fce9880e8cae89e36ed49910c2d57a
But I will throw it away.
