### ISSUE TITLE
seems to be a bug when using merge layer

### ISSUE THREAD

**Issue by cbdbdd** [fchollet/keras#4454]
i made a elementwise multiplication merge layer with shape (10,2) as the last layer, where the input layer shape is (10,2), the reshape layer shape is (10,1). following is the code which works fine.
`
import numpy as np

from keras.layers import  Reshape, merge,Input,Flatten,Dense
from keras.models import Model
inputs = Input(shape=(10,2),name='input')
x = Flatten()(inputs)
x = Dense(10*1,activation='sigmoid',name='dense')(x)
x = Reshape((10,1),name='reshape')(x)
y =  merge([ inputs,x],  mode=lambda x: x[0] * x[1],output_shape=lambda x:x[1],name='merge')#, output_shape=lambda x: x[0]
mo=Model(input=inputs,output=y)
mo.summary()
mo.predict(np.random.random((1,10,2)))`

but if i switch the shape of the input and the reshape layer, i.e. change the input layer shape to (10,1), and the reshape layer shape to (10,1),maintaining the elementwise multiplication merge layer with shape (10,2) as the last layer, issues generated as follows:
ValueError: GpuElemwise. Output dimension mis-match. Output 0 (indices start at 0), working inplace on input 0, has shape[2] == 1, but the output's size on that axis is 2.
code is:
`inputs = Input(shape=(10,1),name='input')

x = Flatten()(inputs)
x = Dense(10*2,activation='sigmoid',name='dense')(x)
x = Reshape((10,2),name='reshape')(x)
y =  merge([ inputs,x],  mode=lambda x: x[0] * x[1],output_shape=lambda x:x[1],name='merge')#, output_shape=lambda x: x[0]
mo=Model(input=inputs,output=y)
mo.summary()
mo.predict(np.random.random((1,10,1)))`

anybody knows the problem ? is this a bug since the only change is the switching of shapes of the two layers.@fchollet

**Comment by cbdbdd** [comment]
no answers...

**Comment by farizrahman4u** [comment]
You should not depend on theano's broadcasting while using keras.
