### ISSUE TITLE
Compilation issue with the theano backend

### ISSUE THREAD

**Issue by nixingyang** [fchollet/keras#4456]
Hi,
Assume one have 10 inputs and 10 outputs in one sample and a single prediction model could generate 1 output from 10 inputs at each time. To extend such single prediction model to multiple predictions model, one could shift the latest input sequence by one and concatenate it with the latest single prediction.
For example, the figure illustrates the structure of a multiple predictions model which yields two predictions. Input 1 contains N input ground truth frames represented as GT_1, GT_2, ..., GT_N. After Step 1 and Step 2, the single prediction model generates Output 1 which is the prediction of the next frame P_(N + 1). In Step 3 and Step 4, Input 1 is shifted by one time stamp and concatenated with Output 1. Therefore, Input 2 corresponds to GT_2, ..., GT_N, P_(N + 1). Similarly, Output 2 is the prediction of the next frame P_(N + 2). In Step 7 and Step 8, Final Output P_(N + 1), P_(N + 2) is attained by concatenating Output 1 and Output 2. It is notable that one could repeat this process for arbitrary times to get an output with desired length.
![image](https://cloud.githubusercontent.com/assets/15064790/20484957/42c9d704-b002-11e6-960a-f54996f638c4.png)
By following the aforementioned algorithm, I have tried to train several multiple predictions models. The compilation of the 5 predictions model takes approximately 2 hours and the code works fine afterwards. However, the training process died without any error message for the 10 predictions model after more than 10 hours compilation. Any idea how could I address this compilation issue?
BR.

**Comment by HristoBuyukliev** [comment]
I your figure you have step 3 and step 7 twice. I could not understand what you are trying to do. Can you explain more clearly and add the code?

**Comment by nixingyang** [comment]
@HristoBuyukliev Thanks for your reply. There are two step 3/7 because they happens at the same time. One input for the step 3 is the current input sequence. Another input is the current prediction. And I shift the current input sequence by one and concatenate it with current prediction. It is explained at the second paragraph.
Unfortunately, this issue might be uncommon. I'm wondering whether someone has encountered similar issue.

**Comment by nixingyang** [comment]
I am closing this issue as it should be more related to the theano backend. I addressed this issue by modifying the model structure itself.

**Comment by nouiz** [comment]
Make sure to use a recent Theano dev version. There have been many speed up
in the compilation process recently.

**Comment by nixingyang** [comment]
@nouiz Thanks for the information. I would try your suggestion sometime soon :-)
