### ISSUE TITLE
Usind model inside of threads

### ISSUE THREAD

**Issue by maxbry** [fchollet/keras#4460]
I want to use a trained keras model inside of threads:

    def do_something(params):
        model, input = params
        [...]
        output = model.predict(input)
        [...]

    def __name__ == '__main__:
        [...]
        pool = Pool(12)
        pool.map(do_something, params)

When I use my script like this, CUDA throws an outofmemory exception. Next, I tried to use a global lock:

        [...]
        lock.acquire()
        output = model.predict(input)
        lock.release()
        [...]

Same problem. Next, I set to pool size to 1 to have only one running thread at the same time. But I'm still getting the same error. When I don't use threading and call the model in the main thread, the script runs smoothly.

Has anyone ever used keras inside of threads?

**Comment by varun-bankiti** [comment]
I am thinking it might be because, the memory allocated to thread by the OS is not sufficient enough for your model. Have a look at [this](https://docs.python.org/2/library/threading.html#threading.stack_size)

**Comment by eyesonlyhack** [comment]
Does it work by saving the tensorflow graph first: https://gist.github.com/eyesonlyhack/2f0b20f1e73aaf5e9b83f49415f3601a
or saving the tensorflow graph after compiling the model: https://gist.github.com/eyesonlyhack/35c82d2659c2ad4415cae163153f93f8
