### ISSUE TITLE
System failure runing program implemented with keras 

### ISSUE THREAD

**Issue by TommeyChang** [fchollet/keras#4467]
My os is ubuntu 16.04. The cuda is installed following the instruction in the developer.nvidia.com. The theano and the keras are installed via pip install . And the vesion of theano is 0.8.2. My GPU is GTX970 with 4G memory. All modular are tested and run  properly.
I am training a CNN+LSTM network implemented with keras using theano backend.
If the cuDNN is installed into the cuda, the system will reboot randomly when the program was run.However, If the cuDNN is removed, the program can run properly.

**Comment by nouiz** [comment]
This is an hardware problem. Your PSU isn't powerfull enough. cuDNN is very
well optimized and will trigger more power usage. Replace your PSU. It can
be a PSU not powerfull enough or of low quality. We had this problem
ourself in the past.

Don't use Theano 0.8.2. Update to the dev version.

**Comment by TommeyChang** [comment]
The capacity of my PSU is 650w, and the power rating of the GPU is only 148w.
