### ISSUE TITLE
tensorflow deprecation warning

### ISSUE THREAD

**Issue by isaacgerg** [fchollet/keras#4472]
WARNING:tensorflow:From d:\github\keras\keras\keras\backend\tensorflow_backend.py:195 in _initialize_variables.: initialize_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.variables_initializer` instead.

and 

WARNING:tensorflow:From d:\github\keras\keras\keras\backend\tensorflow_backend.py:187 in _initialize_variables.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2016-03-02.
Instructions for updating:
Please use tf.global_variables instead.

**Comment by fchollet** [comment]
Feel free to open a PR to fix it.

**Comment by isaacgerg** [comment]
I would like to, but none of my models are working after switching to tf.
Have to put out those fires first.

**Comment by isaacgerg** [comment]
@fchollet I looked into this issue a little bit.  I think I can tackle it, but I need a few other issues off my plate first so my research can move forward.   Can you help me solve #4477 first?

**Comment by englaenda** [comment]
Any updates on this?
I tried out setting the tf environmental variable called TF_CPP_MIN_LOG_LEVEL=3. But unfortunately did not work.

**Comment by tomvars** [comment]
Any update on this?

**Comment by isaacgerg** [comment]
Still an issue for me as of a few weeks ago. I gave up and switched to tf.
