### ISSUE TITLE
Mistake in documentation regarding Deconvolution2D?

### ISSUE THREAD

**Issue by mikolchon** [fchollet/keras#4474]
In the first example in https://keras.io/layers/convolutional/#deconvolution2d, the shapes of the predictions are printed. Why is the shape of `GPU Theano (3,13,13)` and `CPU Theano (3,14,14)`? Is this correct?

**Comment by tboquet** [comment]
It was tested in #3838 and at that time I had these results with the latest version of Theano and Tensorflow. It was one of the main reason why it was difficult to have the shape inference working with deconvolution2D.
It's possible that the behavior changed and the shapes are now the same.
Have you tried running the snippets of code provided in the examples?

**Comment by mikolchon** [comment]
Hi. Just tested it and for both CPU and GPU (using Theano) it gave shape `(32, 3, 14, 14)`.
My versions are: 
`theano.__version__` = 0.8.2
`keras.__version__` = 1.1.1
My cuDNN version is 5.1 (higher than officially supported by Theano).
