### ISSUE TITLE
Inception example on https://keras.io/applications/ doesn't work

### ISSUE THREAD

**Issue by isaacgerg** [fchollet/keras#4476]
This example doesn't work in tensorflow and yields and error:

```
    from keras.applications.inception_v3 import InceptionV3
    from keras.layers import Input
    
    # this could also be the output a different Keras model or layer
    input_tensor = Input(shape=(224, 224, 3))  # this assumes K.image_dim_ordering() == 'tf'
    
    model = InceptionV3(input_tensor=input_tensor, weights='imagenet', include_top=True)   
```

yields:

`builtins.ValueError: Negative dimension size caused by subtracting 8 from 5 for 'AvgPool_10' (op: 'AvgPool') with input shapes: [?,5,5,2048].`

**Comment by ozancaglayan** [comment]
Check that your dim_ordering in `~/.keras/keras.json` is `tf` otherwise you need to pass (3, 224, 224) as your tensor's shape.

**Comment by isaacgerg** [comment]
Already checked this.  Still get the error.  Have you verified?
