### ISSUE TITLE
Simple model results in graph disconnected error

### ISSUE THREAD

**Issue by isaacgerg** [fchollet/keras#4477]
```
from keras.applications.resnet50 import ResNet50
import keras.layers

# this could also be the output a different Keras model or layer
input = keras.layers.Input(shape=(400, 400, 1))  # this assumes K.image_dim_ordering() == 'tf'
x1 = keras.layers.AveragePooling2D(pool_size=(2,2))(input)
#x2 = keras.layers.Reshape((40000,))(x1)
x2 = keras.layers.Flatten()(x1)
x3 = keras.layers.RepeatVector(3)(x2)
x4 = keras.layers.Reshape((200, 200, 3))(x3)
x5 = keras.layers.ZeroPadding2D(padding=(12,12))(x4)
m = keras.models.Model(input, x5)  
model = ResNet50(input_tensor=m.output, weights='imagenet', include_top=False)
```

yields:
 
`builtins.Exception: Graph disconnected: cannot obtain value for tensor Output("input_2:0", shape=(?, 400, 400, 1), dtype=float32) at layer "input_2". The following previous layers were accessed without issue: []`

**Comment by fchollet** [comment]
Fixed.

**Comment by jdelange** [comment]
mmm... my input:

```
img_width, img_height = 150, 150

vgg16_model = VGG16(include_top=False, weights='imagenet', input_tensor=None, input_shape=(3, img_width, img_height))
```
Error:

>   File "C:\Program Files\Anaconda2\lib\site-packages\keras\applications\imagene
> _utils.py", line 72, in _obtain_input_shape
>     '`input_shape=' + str(input_shape) + '`')
> ValueError: The input must have 3 channels; got `input_shape=(3, 150, 150)`

Just dowloaded latest Keras 1.1.2 with VGG16 fix. Theano backend.

**Comment by farizrahman4u** [comment]
@jdelange What is your dim ordering?

**Comment by jdelange** [comment]
Hi! Theano default, I never have to set it specifically, it always works.
