### ISSUE TITLE
fit

### ISSUE THREAD

**Issue by sunnyzxf** [fchollet/keras#4485]
Due to the limitation of memory,I want to use some of samples to train the model firstly, and save the model and weights.Then I load the model and weights, and use the rest of samples to train the model again.I set model.trainable = True.I don't know if there is a difference between the above-mentioned way and using all the samples to  train the model

**Comment by carlthome** [comment]
Use `model.fit_generator` instead if you're short on RAM.

**Comment by lautel** [comment]
If you're working with a large dataset I also recommend you to move to model.fit_generator() instead, as carlthome said. In order to use this way of training you'll need to define a generator which provides both the data and target for training the network. Keeping it simple, it should be something as follows:

def my_generator():
	while 1:
	...
	yield (data_train, target_train)


my_generator = my_generator()
model.fit_generator(
        my_generator,
        samples_per_epoch=samples_per_epoch,  # number of examples you expect to see in each epoch
        nb_epoch=nb_epoch,  # number of epochs
        class_weight=None,
        nb_worker=1
    )

**Comment by carlthome** [comment]
Actually, the generator should yield batches, not the entire dataset at once.

```py
def load_data():
    # TODO Fit as much of the data as possible into RAM and yield each part.


def batch_generator():
    while True:
        for X, y in load_data():
            for i in range(0, X.shape[0], nb_samples):
                yield X[i:i + nb_samples], y[i:i + nb_samples]


model.fit_generator(batch_generator(),    
                    samples_per_epoch=nb_samples,
                    nb_epoch=10)
```

I recommend looking into [multiprocessing.Queue](https://docs.python.org/3/library/multiprocessing.html) for performance though in case a `load_data()` call is expected to take a while.
