### ISSUE TITLE
Using Keras trained Model with Tensorflow C++ API

### ISSUE THREAD

**Issue by daniele-sartiano** [fchollet/keras#4491]
How can I use a Keras trained model with Tensorflow C++ API?
I need to integrate the predict function in a C++ project.
I already exported the model using the following code:

`   
    from keras import backend as K
    from tensorflow.contrib.session_bundle import exporter

    K.set_learning_phase(0)  # all new operations will be in test mode from now on

    # serialize the model and get its weights, for quick re-building    
    config = previous_model.get_config()
    weights = previous_model.get_weights()
    model = Sequential.from_config(config)
    model.set_weights(weights)

    export_path = 'export' # where to save the exported graph
    export_version = 1 # version number (integer)
    
    saver = tf.train.Saver(sharded=True)
    model_exporter = exporter.Exporter(saver)

    signature = exporter.classification_signature(input_tensor=model.input,
                                                  scores_tensor=model.output)

    with tf.Session() as sess:
        init = tf.initialize_all_variables()
        sess.run(init)
        model_exporter.init(sess.graph.as_graph_def(),
                            default_graph_signature=signature)
        model_exporter.export(export_path, tf.constant(export_version), sess)
`

and the loading of the model via C++ API si done by the following code:

`#include "tensorflow/core/public/session.h"
#include "tensorflow/core/platform/env.h"

using namespace tensorflow;

int main(int argc, char* argv[]) {
  // Initialize a tensorflow session
  Session* session; 
  Status status = NewSession(SessionOptions(), &session);
  if (!status.ok()) {
    std::cout << "session ko\n" << status.ToString() << "\n";
    return 1;                                                                                                         
  } else {
    std::cout << "session ok\n" << status.ToString() << "\n";
  }
  GraphDef graph_def;
  status = ReadBinaryProto(Env::Default(), "export/00000001/export-00000-of-00001", &graph_def);
  if (!status.ok()) {
    std::cout << "readbinaryproto ko\n" << status.ToString() << "\n";
    return 1;
  } else {
    std::cout << "readbinaryproto ok\n" << status.ToString() << "\n";
  }
  // Add the graph to the session
  status = session->Create(graph_def);
  if (!status.ok()) {
    std::cout << "session->create ko\n" << status.ToString() << "\n";     
    return 1;                                                                                                            
  } else {
    std::cout << "session->create ok\n" << status.ToString() << "\n";
  }
}`

Now I would like to use the model for the prediction step, Is there a way to _translate/convert_ the predicted_class method (Sequential model) with the C++ API of Tensorflow?

**Comment by ahundt** [comment]
I do am interested in exporting a trained model for use with the TensorFlow C++ API.

It looks like some of the utilities from tensorflow, particularly [exporting/importing a metagraph](https://www.tensorflow.org/how_tos/meta_graph/) will be useful as documented in the TensorFlow howtos.

Then I'd like to use something like [TensorFlow serving](https://github.com/tensorflow/serving) to run my model [like in this example for mnist export](https://tensorflow.github.io/serving/serving_basic).

However, to integrate this with Keras will depend on the existence of any gotchas or new ops defined by Keras and how to ensure they are available at import time. Does anyone have information, experience, or suggestions regarding this?

**Comment by fchollet** [comment]
This is partially covered at the end of this tutorial:
https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html

**Comment by ahundt** [comment]
Thanks! 

It looks like #2310 is also about this kind of use case, and I expect to be using tools like TensorBoard for debugging but there may be some naming difficulties as mentioned in #3100 #3357.

**Comment by bitbionic** [comment]
There is a detailed tutorial (video and written) on this topic here: http://www.bitbionic.com/2017/08/18/run-your-keras-models-in-c-tensorflow/
