### ISSUE TITLE
Strange slowdown

### ISSUE THREAD

**Issue by aplavin** [fchollet/keras#4494]
I'm trying out CNNs now, and experience a strange slowdown: epochs start to take significantly longer after some time, see this log for example:

```
Epoch 1/100
10016/10000 [==============================] - 570s - loss: 0.6259 - acc: 0.6696 - val_loss: 0.5100 - val_acc: 0.7690
Epoch 2/100
10016/10000 [==============================] - 572s - loss: 0.5227 - acc: 0.6842 - val_loss: 0.4405 - val_acc: 0.7347
Epoch 3/100
 4288/10000 [===========>..................] - ETA: 1280s - loss: 0.4887 - acc: 0.7297
```

As you see, first two epochs required way less time than the 3rd one. This isn't reproducible for random data, as I understand, so I can't provide a script for everyone to try; but the NN is just a simple CNN for images.

I'm training on CPU, the machine doesn't run any other computations at this time, there is a lot of free RAM, no throttling and so on. Also CPU usage was always high during first two epochs, but then started jumping between high and low at the same time as the process slowed down.

Any ideas how to find the cause of this?

**Comment by nouiz** [comment]
I know that denormal value can cause slow down on the CPU:
https://en.wikipedia.org/wiki/Denormal_number. I saw benchmark that show
10% slow down. I don't know if it can go higher.

I think that with g++ compiler, you can use this Theano flag to remove the
support of denormal value and get some speed up:

gcc.cxxflags=-ffast-math
