### ISSUE TITLE
Test_core.py has an issue/ Add more example in merge/Merge with lambda mode and output_shape

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [fchollet/keras#4496]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

First of all, thanks for your great package.
In the file https://github.com/fchollet/keras/blob/master/tests/keras/layers/test_core.py
you did not utilize merged model in the structure of your new model (after line 56 and 78 of the file). Moreover, I cannot understand how you create lambda and callable function version of merge parameters. (lines 54-56 and lines 76-78)

I think we need more detailed gist of merge as it was very important!
Thanks again.

@codekansas @farizrahman4u @fchollet

**Comment by farizrahman4u** [comment]
Fixed.

**Comment by ErmiaAzarkhalili** [comment]
Could you please provide more example of merge and Merge when they utilize lambda version of mode in their structure?

Moreover, could you please add more example of Lambda and other Core layers?


⁣Best Regard,
Behrooz​

**Comment by farizrahman4u** [comment]
Update Keras (run setup.py after cloning)

**Comment by ErmiaAzarkhalili** [comment]
I am doing it, but why?
We seriously need more elaborate and clear example of how lambda and callable mode can be written and utilized in Merge layer...

**Comment by farizrahman4u** [comment]
> I am doing it, but why?

Since the travis tests are passing, its probably an issue on your side.

**Comment by ErmiaAzarkhalili** [comment]
@farizrahman4u how about tutorials? Should I try myself? :)

**Comment by farizrahman4u** [comment]
> how about tutorials? Should I try myself? :)

Not sure what you are asking exactly. If you are having any specific issues with Keras, post a simplified script which reproduces the issue.

**Comment by ErmiaAzarkhalili** [comment]
I meant that I think it is necessary for users to have more detailed version of Merge specifically when they are defining their own mode...

**Comment by farizrahman4u** [comment]
> does test_core.py file run properly on your system?
Yes; That doesn't really matter since travis build is passing.
If tests fail locally for you, it means you haven't run setup.py after clone/pull.

**Comment by ErmiaAzarkhalili** [comment]
I used pip install git+git://github.com/fchollet/keras.git . Is there any difference?

**Comment by farizrahman4u** [comment]
> Is there any difference as they both clone and then install keras from git?
Nope. 
It might be that you are running the wrong version of test_core.py; From an older installation..
Anyway, all tests are passing, and I checked test_core.py only 2 days ago, so nothing is wrong.

**Comment by ErmiaAzarkhalili** [comment]
Thanks a lot dear Fariz, I will be trying to run more example for Merge and Lambda layer to explain how they works and will send pull request to add them in keras if you are interested in as well.
