### ISSUE TITLE
UnboundLocalError: local variable 'epoch_logs' referenced before assignment

### ISSUE THREAD

**Issue by valexandersaulys** [fchollet/keras#450]
```
Traceback (most recent call last):
  File "pretrained_mlp.py", line 102, in <module>
    batch_size=1);
  File ".../keras/keras/models.py", line 465, in fit
    shuffle=shuffle, metrics=metrics)
  File ".../keras/keras/models.py", line 228, in _fit
    callbacks.on_epoch_end(epoch, epoch_logs)
UnboundLocalError: local variable 'epoch_logs' referenced before assignment
```
Has anybody ever had this issue? It infrequently comes up for me when training with autoencoders. I'm using python 2.7.8 on Ubuntu if that means anything.

**Comment by w0nk0** [comment]
I've actually had the same issue yesterday, when reconstructing a model from a saved yaml. I didn't want to post anything here before I had more of an idea what could have caused it, and in which circumstances it did/didn't appear.

**Comment by fchollet** [comment]
It can happen when the model is trained on empty data (which won't work anyway). I can turn that into a clearer error message.

**Comment by valexandersaulys** [comment]
Ah-hah! That was indeed my error, silly mistake. Thanks for the update!

**Comment by kevinmartinmauro** [comment]
I would say i'm fairly familiar with keras (use a lot of the same scripts in a number of applications). Since the last push, I'm getting this error a lot now... will look into it and report back

**Comment by kevinmartinmauro** [comment]
This can also be due to having a negative batch size.

**Comment by luis-i-reyes-castro** [comment]
Hello! I wanted to report that I got this error too, and I've found that in my case it was (at least partially) caused by having steps_per_epoch = 0.  In this case line 1852 of "training.py" fails to enter the while loop which defines 'epochs_log'. 
![epochs_log_error_cause](https://user-images.githubusercontent.com/28630745/27756393-a470bfaa-5dbc-11e7-9817-7f6012737fba.jpg)

**Comment by jeremykohn** [comment]
Zero steps per epoch caused it for me as well. Specifically:

```
steps_per_epoch=nb_train_samples//batch_size
```

`nb_train_samples//batch_size` was rounded down to 0 because I mistakenly used a batch size larger than the number of training samples.

**Comment by sadihem** [comment]
I have a basic question. My virtual machine is NOT a GPU. Can that cause the data be empty and then the same error be shown in my terminal (which is " local variable 'epoch_logs' referenced before assignment").
