### ISSUE TITLE
 BaseCorrMM: Failed to allocate output 

### ISSUE THREAD

**Issue by vshebunyaev** [fchollet/keras#4500]
I tried( i use CPU and openBLAS) to test sample
> import numpy as np
from scipy.misc import ascent
from theano import tensor as T,function
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers.convolutional import Convolution2D, MaxPooling2D
img = ascent()
I = img.reshape((1,1, img.shape[0], img.shape[1]))
w = np.random.randn(1,1,5,5)
nb_output_chan = 1
nb_rows = 5
nb_cols = 5
pool_row = 3
pool_col = 3
model = Sequential()
model.add(Convolution2D(nb_output_chan,nb_rows,nb_cols,border_mode='valid',input_shape=I.shape[1:]))
model.add(MaxPooling2D(pool_size=(pool_row,pool_col)))
model.compile(loss='mse',optimizer='sgd')
out = model.predict(I)

And get error

> RuntimeError: BaseCorrMM: Failed to allocate output of 1 x 1 x -3 x 508
Apply node that caused the error: CorrMM{valid, (1, 1)}(InplaceDimShuffle{0,3,1,2}.0, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 5
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(1L, 512L, 1L, 512L), (1L, 512L, 5L, 5L)]
Inputs strides: [(2048L, 4L, 1048576L, 2048L), (2048L, 4L, -10240L, -2048L)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Add}[(0, 0)](CorrMM{valid, (1, 1)}.0, InplaceDimShuffle{0,3,1,2}.0)]]

**Comment by nouiz** [comment]
You are missing memory in the computer. Make the model smaller or use
smaller dataset or don't keep the full dataset in ram.

**Comment by vshebunyaev** [comment]
I am nore sure that it's because of memory.
If to check debug

> Debugprint of the apply node: 
CorrMM{valid, (1, 1)} [id A] <TensorType(float32, 4D)> ''   
 |InplaceDimShuffle{0,3,1,2} [id B] <TensorType(float32, 4D)> ''   
 | |convolution2d_input_1 [id C] <TensorType(float32, 4D)>
 |Subtensor{::, ::, ::int64, ::int64} [id D] <TensorType(float32, 4D)> ''   
   |InplaceDimShuffle{3,2,0,1} [id E] <TensorType(float32, 4D)> ''   
   | |convolution2d_1_W [id F] <TensorType(float32, 4D)>
   |Constant{-1} [id G] <int64>
   |Constant{-1} [id G] <int64>

Storage map footprint:
 - InplaceDimShuffle{0,3,1,2}.0, Shape: (1L, 512L, 1L, 512L), ElemSize: 4 Byte(s), TotalSize: 1048576 Byte(s)
 - convolution2d_input_1, Input, Shape: (1L, 1L, 512L, 512L), ElemSize: 4 Byte(s), TotalSize: 1048576 Byte(s)
 - convolution2d_1_W, Shared Input, Shape: (3L, 3L, 512L, 1L), ElemSize: 4 Byte(s), TotalSize: 18432 Byte(s)
 - Subtensor{::, ::, ::int64, ::int64}.0, Shape: (1L, 512L, 3L, 3L), ElemSize: 4 Byte(s), TotalSize: 18432 Byte(s)
 - TensorConstant{(4L,) of 1}, Shape: (4L,), ElemSize: 4 Byte(s), TotalSize: 16 Byte(s)
 - Constant{-1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - convolution2d_1_b, Shared Input, Shape: (1L,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 TotalSize: 1085468.0 Byte(s) 0.001 GB
 TotalSize inputs: 1067036.0 Byte(s) 0.001 GB
Just 0.001GB

**Comment by vshebunyaev** [comment]
I fixed it. Error was not about memory.
I need to set **set_image_dim_ordering**
Why i need to set it in code,when in keras config i set theano as backend?
Please fix it
> from keras import backend as K
K.set_image_dim_ordering('th')

**Comment by stefanofiorentino** [comment]
The problem is sadly still there.

**Comment by nouiz** [comment]
The answer comment is that the fix is in user code. Theano and tensorflow
use different memory layout and not the right one is selected. Check how to
make a keras config file and cherche change the default of the ordering.

**Comment by laplands** [comment]
RuntimeError: BaseCorrMM: Failed to allocate output of 737 x 64 x 147 x 147

**Comment by nouiz** [comment]
You are having a very big output. The output of the convolution take 4G by
itself. Makea smaller model or lower your mini batches size.
