### ISSUE TITLE
merge function with Lambda appears to produce wrong ndim

### ISSUE THREAD

**Issue by phdowling** [fchollet/keras#4504]
I defined the following merge:

```python
def MatchScore(left, right):
    return merge(
        [left, right],
        mode=lambda l_r:
            1. /
            (
                1. +
                K.sqrt(K.dot(l_r[0], l_r[0].T) - 2. * K.dot(l_r[0], l_r[1].T) + K.dot(l_r[1], l_r[1].T))
            ),
        output_shape=(left._keras_shape[1], right._keras_shape[1])
    )

# calling like this:
left_input = Input(shape=(left_seq_len,))
right_input = Input(shape=(right_seq_len,))
left_embed = Embedding(input_dim=vocab_size, output_dim=embed_dimensions, dropout=dropout)(left_input)
right_embed = Embedding(input_dim=vocab_size, output_dim=embed_dimensions, dropout=dropout)(right_input)

match_score = MatchScore(left_embed, right_embed)
```

This should compute a score based on pairwise euclidean distances of the rows of two matrices, thus have output shape (num_samples_left, num_samples_right) as manually specified in the output_shape argument - however, Keras gives the resulting TensorVariable an `ndim` of 4, this it's not compatible with e.g. a TimeDistributed(Dense(...)) as expected.

Is this a possible bug in Keras or am I missing something?

EDIT: Okay, seems that this is Theano doing this, not Keras, and that the output of that lambda really is 4-dimensional (forgot about the num_samples dimension). I guess my question now becomes: how can I use Keras to "broadcast" the above function for each sample in my two inputs?

**Comment by farizrahman4u** [comment]
Can you simplify your problem statement? The function doesnt make sense because lengths of left and right are different and you are doing elem-wise ops on tensors of different shapes. Also what are the expected output shape of each of the dot products?

**Comment by phdowling** [comment]
Solved this finally, here's the code in the unlikely case someone ever has the same issue:

```python
def compute_match_score(l_r):
    return 1. / (
        1. +
        K.sqrt(  # euclidean distance
            -2 * K.batch_dot(l_r[0], l_r[1], [2, 2]) +  
            K.expand_dims(K.sum(K.square(l_r[0]), axis=2), -1) +
            K.expand_dims(K.sum(K.square(l_r[1]), axis=2), 1)
        )
    )


def MatchScore(l, r):
    return merge(
        [l, r],
        mode=compute_match_score,
        output_shape=lambda shapes: (None, shapes[0][1], shapes[1][1])
    )
```
