### ISSUE TITLE
Saving model without Embedding layer

### ISSUE THREAD

**Issue by wwfan91** [fchollet/keras#4511]
My model has Embedding layer with trainable=False and it's initiated with pretrained embeddings. To save space when saving the model, Is there any way to ignore the Embedding layer's weights?

**Comment by ilikedata** [comment]
In some of my models (a number of small models which have the same pre-trained embeddings) a hack I use is to delete the embedding layer after training. As long as you manually create the embedding vectors as input into the final model then all works as expected.

**Comment by farizrahman4u** [comment]
You can just create a model without the embedding layer and save its weights:
```python
model = Sequential()
model.add(....)
model.add(...)

model_with_embedding = Sequential()
model_with_embedding.add(Embedding(...))
model_with_embedding.add(model)
model_with_embedding.compile('sgd', 'mse')
model_with_embedding.fit(x, y)

model.save_weights('weights.dat')

```

**Comment by wwfan91** [comment]
Thanks @ilikedata and @farizrahman4u

**Comment by wwfan91** [comment]
@farizrahman4u , can you show the way to do it using Functional API?

```
emb_layer = Embedding()
in = Input()
emb = emb_layer(in)
hidden = Dense()(emb)
...
out = Dense()(hidden)
model = Model(in, out)
model.fit(X,Y)
model.save_weights('weights.dat')
```

Says I want to save the weights of Dense layers only

Thanks

**Comment by SebiSebi** [comment]
@farizrahman4u +1 for the Functional API

**Comment by carlosg-m** [comment]
@SebiSebi, @farizrahman4u, You have to create three different models, one with only the embedding layer, the other one with the all the layers you want to load the weights, and the third one that joins the two previous models.

```
def embedding_model():
    input = layers.Input(shape=(max_seq_len,))
    embedding = layers.Embedding(input_dim = embedding_matrix.shape[0], 
                                 output_dim = embedding_matrix.shape[1],
                                 input_length = max_seq_len,
                                 weights = [embedding_matrix],
                                 trainable = False,
                                 mask_zero = False)(input)
    return tf.keras.Model(input, embedding)

def rnn_model():
    input_emb = layers.Input(shape=(max_seq_len, embedding_matrix.shape[1]))
    x = layers.GRU(...)(input_emb)
    x = layers.Dense(...)(x)
    return tf.keras.Model(input_emb, x)

embe_nn = embedding_model()
rnn_nn = rnn_model()
full_model = tf.keras.Model(embe_nn.input, rnn_nn(embe_nn.output))
rnn_nn.load_weights('/.../saved_weights.h5')

y_pred = full_model.predict(...)
```
