### ISSUE TITLE
Re-generating a net with to/from_yaml() and save/load_weights() does not preserve training

### ISSUE THREAD

**Issue by w0nk0** [fchollet/keras#452]
I have worked on models for text generation (cough..Karpathy..cough) as my getting-back-into NNs project for a while now. Slowly getting to where they make sense, I would like to preserve the trained network's states. I'm assuming that model.to_yaml() -> model_from_yaml() and model.get_weights() -> model.set_weights() should do that, but either I'm missing something or there's a bug in one of those two functions.

Here's my example code (with a keras version cloned from git yesterday afternoon):

    newmodel = model_from_yaml(model.to_yaml()) 
    # copy the model (model_from_yaml() should compile() according to source code)
    wts=model.get_weights()
    newmodel.set_weights(wts)

This should copy over the weights and thus the trained state
So let's compare the errors of both on a subset of my training data:

    print(model.evaluate(trainX[:1000],trainy[:1000]))
    print(newmodel.evaluate(trainX[:1000],trainy[:1000]))

.. results in this output:

    1000/1000 [==============================] - 2s     
    0.46311536622
    
    1000/1000 [==============================] - 2s     
    4.9628265152

So the errors are clearly not the same. The generated text also coincides with what seems to be an untrained new_network, just like the evaluate error level indicates.

So - am I missing a piece of the puzzle to save/load a trained model or did I find a bug?

**Comment by fchollet** [comment]
It works in our test, though the test did not use a recurrent model. What model are you using?

**Comment by fchollet** [comment]
Also, please try it with `save_weights(fname)` and `load_weights(fname)`, just to check.

**Comment by w0nk0** [comment]
Thank you for the quick response!

I was using a model with 2 JZN1 and 1 Dense layer afaik. I do remember comparing the lists returned from get_weights() and could confirm that they were reconstructed properly. So if there's something missing that destroys the training data, it's probably due to get_weights() not capturing part of the network's state.

I will try it again with a) different models and b) using save_weights() / load_weights() as you indicated and get back to you once I got results!

**Comment by w0nk0** [comment]
I was finally able to produce a clean test notebook, sorry for the delay. 

- LSTM works fine with get_/set_weights()
- JZS1 doesn't
- I couldn'test save_weights() / load_weights() since I can't get h5py to install currently, sorry

This is the ipython notebook of the test. It uses the vectorizer.py module from that same repository (I made it before Keras and got used to it, I realize I reinvented Keras abilities..), but you should be able to plug in any trainX / trainy data obviously.

https://github.com/w0nk0/LSTMtest1/blob/master/keras%20save-load%20tests-cleaned.ipynb

Let me know if I can help with tracking down the bug in other ways as well!

**Comment by ghpu** [comment]
JZS1 does not seem to serialise Pmat in its params.

**Comment by fchollet** [comment]
@ghpu thanks, this is now fixed.
