### ISSUE TITLE
How to change the stride on using the Convolution2D in keras? 

### ISSUE THREAD

**Issue by liuhuixiang** [fchollet/keras#4520]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by liuhuixiang** [comment]
Hello,Sirs,
       I am using the CNNs for picture classification, I doubt that how to change the stride on using the Convolution2D in keras?  
       Thank you so much!

**Comment by MoyanZitto** [comment]
@liuhuixiang 
Personally I recommend users to not open issues before reading the documents. Because there are a lot of issues here, and many of them are actually not good quesions.

You can set the argument `subsample` for modifying the stride.

**Comment by liuhuixiang** [comment]
@MoyanZitto Thank you, Sir!  Get it, I am careless !
