### ISSUE TITLE
LSTM classifier output as a function of time

### ISSUE THREAD

**Issue by crthitmo** [fchollet/keras#4527]
I have built and trained an LSTM classifier which has a single layer of LSTM cells to go from an input of two sequences (time series data) to the classification output.

One feature I would like to implement is to visualize the classification as a function of time, i.e. to get an idea of how many datapoints the classifier needs to be accurate.  Is there a way to return the classifier output as a single sample is fed into the network?

If that works, I would want to take it a step further and visualize the individual cell activations as a function of input, e.g. [as shown in Andrej Karpathy's blog](http://karpathy.github.io/2015/05/21/rnn-effectiveness/#visualizing-the-predictions-and-the-neuron-firings-in-the-rnn).  Is it possible to collect these for a single sequence or a batch?

**Comment by phdowling** [comment]
I have not tried this, but it might work: Assuming your top-level layer is an LSTM that has return_sequences=False, you could train the model, save the weights, and then load them into a model that is identical, but has return_sequences=True in the top level LSTM. If you then feed your data into this model, you get a sequence of outputs representing the top LSTMs intermediate outputs. Is this what you are looking to do?

**Comment by crthitmo** [comment]
Thanks, this worked really well for the second task.  I added in a TimeDistributed Dense layer for the first task.

**Comment by recluze** [comment]
@crthitmo Would you happen to be in a position to share the code for activation visualization? It would be a great tool for a myriad of tasks.

**Comment by crthitmo** [comment]
@recluze Are you asking about the code to generate and collect the feature activations, or the code to visualize them?  If the latter, I didn't do the kind of visualization Karpathy shows in his blog, as our data is not amenable to that.  Currently they are just plotted in a pseudocolor map as a function of time and cell index with plt.imshow().

For the former, it's on my work computer so it would have to be Monday, but if my boss is OK with it I'd be happy to.  It's pretty simple though, I created a new model of the same structure, leaving the LSTM layer as the final layer (i.e. no Dense layer for classification).  I copied over the weights from the original model using get_weights() and set_weights(), then ran Sequential.predict() with my original X_test.  The output of that function is the matrix of feature activations.

**Comment by recluze** [comment]
Ah, alright. I meant the visualization but if it's only direct visualization, it should be straight-forward to do it. In any case, it's the little pieces that cause the headache. 

Also, if you can share the code for the former as well, that would be great as I'm also trying to do something very similar (except I have another space dimension in place of time but it serves the same purpose, kind of).
