### ISSUE TITLE
How can i use model.predict to predict single one result?

### ISSUE THREAD

**Issue by Lone5267** [fchollet/keras#4532]
I wrote LSTM code with keras, the shape of input is (128, 23, 9)
In predicting, i just want one result, so my input shape is  (1, 23, 9)
after that, i got an exception

Exception: Error when checking : expected lstm_input_1 to have shape (128, 23, 9) but got array with shape (1, 23, 9)

may one help me?

sorry for my pool english.

**Comment by MoyanZitto** [comment]
@Lone5267 
Could you explain the meaning of each axis your data?

**Comment by keunwoochoi** [comment]
and probably some codes?

**Comment by phdowling** [comment]
Some code would be useful, but in general it sounds like you may have set your batch_size to 128 in `predict`, try setting it to 1.

**Comment by MoyanZitto** [comment]
@phdowling 
That's why I want him to explain the meaning of data. Normally batch_size is not included in `input_shape` in both `.fit` and `.predict`, pass data with any batch size to `.predict` would be ok.
