### ISSUE TITLE
TensorBoard Callback doesn't close file -  max file descriptors

### ISSUE THREAD

**Issue by unsalted** [fchollet/keras#4533]
The TensorBoard callback never closes the log file.  I've had a 12 hour run interupted by a max file descriptor error.

I suppose this:

        for name, value in logs.items():
            if name in ['batch', 'size']:
                continue
            summary = tf.Summary()
            summary_value = summary.value.add()
            summary_value.simple_value = value.item()
            summary_value.tag = name
            self.writer.add_summary(summary, epoch)
        self.writer.flush()

needs to be followed with:

`self.writer.close()`

based on the [TF docs](https://www.tensorflow.org/versions/r0.12/api_docs/python/train.html#SummaryWriter):

> **tf.train.SummaryWriter.close()**
> 
> Flushes the event file to disk and close the file.
> 
> Call this method when you do not need the summary writer anymore.
> 

@tboquet what do you think - I see it's your callback.

BTW it has been a total blessing to have such a convenient callback available. Thank you!

**Comment by fchollet** [comment]
Fixed.
