### ISSUE TITLE
Reshape Layer gives ValueError  size cannot be unchanged

### ISSUE THREAD

**Issue by Satokaheni** [fchollet/keras#4534]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [check] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [check] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Here is the current code I'm attempting to run for keras:
char = Sequential()
char.add(Embedding(max_features, embedding_size, input_length=maxlen*max_charlen))
char.add(Convolution1D(nb_filter, 3, border_mode='valid', activation='relu'))
char.add(MaxPooling1D(pool_length))
char.add(Reshape((maxlen,embedding_size)))

Everything runs perfectly fine if I remove the Reshape layer but I need the reshape layer so I can concat it with a different input layer. 

Here's a copy of the error given:

Traceback (most recent call last):
  File "sent_nn.py", line 181, in <module>
    char.add(Reshape((maxlen,embedding_size)))
  File "/users/stallbohm/anaconda3/lib/python3.4/site-packages/keras/models.py", line 324, in add
    output_tensor = layer(self.outputs[0])
  File "/users/stallbohm/anaconda3/lib/python3.4/site-packages/keras/engine/topology.py", line 517, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/users/stallbohm/anaconda3/lib/python3.4/site-packages/keras/engine/topology.py", line 571, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/users/stallbohm/anaconda3/lib/python3.4/site-packages/keras/engine/topology.py", line 158, in create_node
    output_shapes = to_list(outbound_layer.get_output_shape_for(input_shapes[0]))
  File "/users/stallbohm/anaconda3/lib/python3.4/site-packages/keras/layers/core.py", line 335, in get_output_shape_for
    return (input_shape[0],) + self._fix_unknown_dimension(input_shape[1:], self.target_shape)
  File "/users/stallbohm/anaconda3/lib/python3.4/site-packages/keras/layers/core.py", line 330, in _fix_unknown_dimension
    raise ValueError(msg)
ValueError: total size of new array must be unchanged

Also on a different note after updating keras to the move recent git version, trying to import the Graph model gives an error.

**Comment by patyork** [comment]
You need to check the output shape of the MaxPooling layer the precedes the Reshape layer; `char.summary()` would be a decent way to do that.

For example: if the output of the MP layer is [None, 10, 10], then the reshape layer must create a shape that is exactly 10*10=100 elements; a valid shape would be (100,) or (25, 4). Reshaping only reshapes the dimensions of the data, it does not add/remove extra data to guarantee the asked for output shape.
