### ISSUE TITLE
how to feed multiple outputs of previous layer to a successive lstm layer

### ISSUE THREAD

**Issue by makai281** [fchollet/keras#4537]
Hello everyone, I am a fresher in Keras . Now I encountered a problem that how to feed multiple outputs of previous layers to a successive lstm layer.My model(part) is just like below:

batch_size = 64
output_1 = Dense(output_dim=(128, ), input_dim=(200, ))
output_2 = Dense(output_dim=(128,), input_dim=(200, ))
output_3 = Dense(output_dim=(128,), input_dim=(200, ))
output_4 = Dense(output_dim=(128,), input_dim=(200, ))

and then how to feed all above outputs to a lstm ? the input_dim should be like (batch_size, number_of_previous_outputs, 128)  

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by 23pointsNorth** [comment]
You can [merge](https://keras.io/getting-started/sequential-model-guide/#the-merge-layer) the outputs into a single layer and feed it into the lstm.
