### ISSUE TITLE
Incorrect input shape of Convolution2D

### ISSUE THREAD

**Issue by binh-vu** [fchollet/keras#4546]
Hi, 

From the documentation at https://keras.io/layers/convolutional/. They suggest that the input for the convolution should follow the order: channels, rows, cols. However, when I run the example codes:

`model = Sequential()`
`model.add(Convolution2D(64, 3, 3, border_mode='valid', input_shape=(3, 256, 256)))`
`print model.output_shape # output (None, 1, 254, 64)`

I get (None, 1, 254, 64) instead of (None, 64, 254, 254). When I switch input shape to: rows, cols, channels, I got the correct result.

`model = Sequential()`
`model.add(Convolution2D(64, 3, 3, border_mode='valid', input_shape=(256, 256, 3)))`
`print model.output_shape # output (None, 254, 254, 64)`

I use Keras version: 1.1.2 (updated from master branch).

**Comment by varun-bankiti** [comment]
input_shape depends on _K.image_dim_ordering()_ that you are using(can be found in ~/.keras/keras.json), you can check [here](https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L355). I think in your case image_dim_ordering is _tf_.

Hope it helps.
