### ISSUE TITLE
Changing Convolution filter number during training.

### ISSUE THREAD

**Issue by mustgoplay** [fchollet/keras#4549]
It looks to me like the number of filters in a net is fixed upon compilation.  If I want to add or remove filters as training progresses, how can you do that after the net is compiled?  Or do you have to get the network outputs, do the calcs, and then recompile for every single input during training?  That would be really slow.  For example, let's say I start with a convlayer of 30 filters and I find that I want to add 5 more during training, how do I do that please?

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
You cannot modify a layer after compilation in any way. If you want to add convolution filters, you must create a new model and partially transfer weights from your old model.
