### ISSUE TITLE
"_predict_loop()" function in "engine/training.py" 

### ISSUE THREAD

**Issue by eaglim** [fchollet/keras#4557]
I'm new to keras!

Just wanted to double check if the [_predict_loop()](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L852) function change the trained model in any ways (e.g. changing the weights of the network) while making predictions?

Thanks before.

**Comment by patyork** [comment]
The _predict_loop() only does predictions and does not apply any updates to the model.

I'm surprised you would ever call that function; I would stick with `predict` for almost everything, or the `predict_generator` if you are trying to get outputs for a large input set that doesn't fit in RAM.

**Comment by eaglim** [comment]
thank you @patyork .. sometimes you need to loop over prediction instances too..

**Comment by lmxhappy** [comment]
is state set to next predict when calling predict()?
