### ISSUE TITLE
Retrieving the output from intermediate layers

### ISSUE THREAD

**Issue by loyeamen** [fchollet/keras#456]
Hi,

In case some of you are interested in retriveing the output from intermediate layers i have changed the compile function and added a 'predict_layer' for predicting the output for a given layer index.
I guess some of you will find this code useful so i post it here (you can also submit PR):
 
    
    def compile(self, optimizer, loss, class_mode="categorical", theano_mode=None, predict_layers = None):
        
        Sequential.compile(self, optimizer, loss, class_mode, theano_mode)
        self._predict_layers = None
        if predict_layers is not None:
            if type(self.X_train) == list:
                predict_ins = self.X_test
            else:
                predict_ins = [self.X_test]
            self._predict_layers = [None] * len(self.layers)
            for layer_index in predict_layers:
                self._predict_layers[layer_index] = theano.function(predict_ins, self.layers[layer_index].get_output(train = False), 
                                                                      allow_input_downcast=True, mode=theano_mode)

def predict_layer(self, X, layer_index, batch_size=128, verbose=1):
        if self._predict_layers is None or self._predict_layers[layer_index] is None:
            raise ValueError("Prediction function for layer {} is not compiled!".format(layer_index))
        X = standardize_X(X)
        batches = make_batches(len(X[0]), batch_size)
        if verbose == 1:
            progbar = Progbar(target=len(X[0]))
        for batch_index, (batch_start, batch_end) in enumerate(batches):
            X_batch = slice_X(X, batch_start, batch_end)
            batch_preds = self._predict_layers[layer_index] (*X_batch
            if batch_index == 0:
                shape = (len(X[0]),) + batch_preds.shape[1:]
                preds = np.zeros(shape)
            preds[batch_start:batch_end] = batch_preds
            if verbose == 1:
                progbar.update(batch_end)
        return preds

**Comment by iskandr** [comment]
This only works for sequential models, right? 

Wouldn't it be more straightforward to attach an output method to each Layer directly (so that it could work with Graph models just as easily)?

**Comment by loyeamen** [comment]
Whatever works for you.
I did not invest much thinking in the implementation and i guess a better design exists. Moreover, i did not try the Graph model yet, so yes, it overrides the compile function of Sequential.

I think it is quite useful though and therefore would be happy if someone could find the time to submit a PR.

**Comment by fchollet** [comment]
> Wouldn't it be more straightforward to attach an output method to each Layer directly (so that it could work with Graph models just as easily)?

Seconded.

**Comment by lemuriandezapada** [comment]
Or implement the training in such a way that only the output layers specified in the .fit method are actually required to compute the gradients. And just leave some outputs just free hanging.

**Comment by pasky** [comment]
This was also asked in #588. To add another recipe, if you want to look at a Graph and don't want to change outputs of your already trained graph, you can use something like this (assuming two inputs):

```python
imd_f = theano.function([model.inputs[name].input for name in model.input_order],
                        model.nodes['your node name here'].get_output(train=False))
imd_f(np.array(inp0, dtype='float32'), np.array(inp1, dtype='float32'))
```

**Comment by alyato** [comment]
hi @pasky ,I use the graph model.
like this,

> model = graph()
  model.add_input(name='input0',input_shape=())
  model.add_node(Convolution2D(),name='c1',input='input0')
.......

And i want to see the output of the `c1`,Then 

> 
getFeatureMap = theano.function(model.inputs['input0'].input,model.nodes['c1'].get_output(train=False),
allow_input_downcast=True)

But it show me that
`TypeError: list indices must be integers, not str`

Do you give me some advices? Thanks.

**Comment by alyato** [comment]
hi @loyeamen ,I use the graph model.
like this,

> model = graph()
  model.add_input(name='input0',input_shape=())
  model.add_node(Convolution2D(),name='c1',input='input0')
.......

And i want to see the output of the `c1`,Then 

> 
getFeatureMap = theano.function(model.inputs['input0'].input,model.nodes['c1'].get_output(train=False),
allow_input_downcast=True)

But it show me that
`TypeError: list indices must be integers, not str`

Do you give me some advices? Thanks.
