### ISSUE TITLE
Trainable parameters in Merge layer

### ISSUE THREAD

**Issue by shashankg7** [fchollet/keras#4568]
Hi,

I want to use a custom merge layers, where the inputs are two 1D vectors (outputs from 2 1D [CONV-POOL] models) and I want to generate a scalar output which computes (X1.T * M * X2.T), where M is the similarity matrix (parameter of dim d*d, X1 and X2 are d dim vectors).

Current merge layers only supports functions and I cannot figure out a way to add parameter to the model.

Thanks,

**Comment by dbonadiman** [comment]
@shashankg7 I don't think there is an easy way to do that, you should implement your own layer.


However, for your specific case there is a simple workaround:

1) X1.T*M is equivalent to a dense layer without bias.
2) once applied that layer, you can simply apply a merge in dot mode.

```python
x1_vec = conv_pool(x1)
x2_vec = conv_pool(x2)

similarity = merge([Dense(x2_vec_size, bias=False)(x1_vec), x2_vec], mode='dot')

```

hope that this "ugly" workaround works for you.

**Comment by shashankg7** [comment]
@dbonadiman Thanks man. This works !!
