### ISSUE TITLE
GPU initialization error with subprocesses depending on location of keras import

### ISSUE THREAD

**Issue by iaroslav-ai** [fchollet/keras#4569]
I get an error

```
Error when trying to find the memory information on the GPU: initialization error
Error allocating 8 bytes of device memory (initialization error). Driver report 0 bytes free and 0 bytes total
```

when I try to execute this python script

```
from keras.layers import Input

def main_theano():
    import theano
    import theano.tensor as T
    import numpy as np

    x = T.matrix()
    f = theano.function(inputs=[x], outputs=T.mean(x))
    print f(np.random.rand(3, 3))

def main_keras():
    #from keras.layers import Input
    ip = Input((32, ))

from multiprocessing import Process

# runs ok
p = Process(target=main_theano)
p.start()
p.join()

# throws exception
p = Process(target=main_keras)
p.start()
p.join()
```

on my Ubuntu 16.04 machine with GeForce GTX TITAN X gpu device using the following command line command:

```
THEANO_FLAGS=device=gpu python script.py
```

Interestingly, if I move import of input layer (`from keras.layers import Input`) inside the 'main_keras' function, gpu initialization error disappears. It seems as if keras or modules it imports acquires some resources in the main script process, which cannot be used then in created subprocesses. 

Could you reproduce the error? If so, is this intended behavior or a bug?

I checked to be up-to-date with keras and theano.

**Comment by nouiz** [comment]
Using multi-process with cuda isn't trivial. This is due to limitation to
the cuda driver, not the frameworks.

Mostly, the parent process should not init the GPU. Only child process. On
the parent after creating all child process.

This page talk about that in more detail, but it is outdated. But could
still be useful:

https://github.com/Theano/Theano/wiki/Using-Multiple-GPUs

**Comment by iaroslav-ai** [comment]
Thank you @nouiz for useful information and pointers! I will keep it in mind. I think this issue can be closed.
