### ISSUE TITLE
Pre-trained nets crash with theano ordering

### ISSUE THREAD

**Issue by mahehu** [fchollet/keras#4574]
Line 70 of `applications/imagenet_utils.py` (function `_obtain_input_shape`) seems to have a minor typo. 

The block tests that the input has three channels. For example, the following model instantiation crashes with using Theano backend:

`base_model = VGG16(include_top = False, weights = 'imagenet', input_shape = (3, 224, 224))`

**Proposed solution:**
Now line 70 of `applications/imagenet_utils.py` reads:

`if input_shape[1] != 3:`

This should be

`if input_shape[0] != 3:`

Thanks, 

Heikki

**Comment by joelthchao** [comment]
Thanks for report, same issue here #4582
