### ISSUE TITLE
Keras Programmer Guide for Dummies - anyone interested in helping write one?

### ISSUE THREAD

**Issue by mustgoplay** [fchollet/keras#4584]
Hi,

The documentation for keras is very good and helps a lot if one is using existing layers and tools.  There are also a lot of examples on how to piece those tools together to reproduce larger nets and different kinds of nets.  I am a dummy however and am having difficulty in finding step by step explanations (not just instructions) of how to write custom classes.  fchollet in the slack group said some of the things I want to do are easy in keras and yet I can't find examples of them, some posts say one of them (change number of filters in a conv net during training) are not possible, and it is not clear where certain changes should be made (thankfully patyork is pointing me to regularizers in another post for changing weights).

It would be nice to have more of a programmers guide and not just a users guide for writing custom objects with explanations of even things like what order the optimizations/regularizations/objectives/callbacks/metrics are calculated, what the limits are of each, and most importantly, how to debug and follow data through them on the fly.

Maybe I've missed some resources but I can't find that level of detail.

Is there such a guide out there and if not is there any interest in developing one?

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by isaacgerg** [comment]
Please close and post in the forum. This is for bug fixes only.

**Comment by mustgoplay** [comment]
Sorry, my bad.
