### ISSUE TITLE
Problem with the sequence input to SimpleRNN

### ISSUE THREAD

**Issue by Krxsy** [fchollet/keras#459]
I have a 2D array consisting of time (nsecs), latitude, longitude and velocity as features which should be the input to simpleRNN. Its shape is (33336,4) as (nb_samples, input_dim). But there's a 3D array (nb_samples, timesteps, input_dim) needed. Of course, I could simply use numpy.expand_dims() but then I would have something like (33336,1,4). But my time features are representing those timesteps. So now I'm confused how to actually create a decent 3D array with latitude, longitude and velocity and the time feature as required timesteps. I tried out different things like first creating a 3D array and then adding the data where its needed. But then I get some memory errors because of its size. Have you guys any ideas how I could create a reasonable input?

**Comment by harpone** [comment]
nb_samples is number of samples/examples, so you should split your training data accordingly. 

If 'data' is your data of shape (33336, 4), X denotes the input data and you use time windows of lenght 25, then X[0] = data[0:25], X[1] = data[1:26] etc.

**Comment by Krxsy** [comment]
#facepalm yes, of course. That makes sense. Thank you!
