### ISSUE TITLE
Using keras in production

### ISSUE THREAD

**Issue by kushia** [fchollet/keras#4607]
Hi everyone,
I was wondering if using keras on a production server was a good idea ?
I want to make request to my server to predict some images.
But I'm not sure how I should do that..
Because, with the GPU, in case of a lot of requests, I'm affraid than CUDA fails while allocating memory for prediction. (And crash the server)
Should I use the CPU for the predictions ? Is it even possible if I trained my model on the GPU ?
But there again, even if it work, use the CPU could take a long time..

How should I do it ?

Thanks to you!

**Comment by kushia** [comment]
Ps : 
I saw this link : https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html#exporting-a-model-with-tensorflow-serving

But in the last pic, I can't figure out how to get the sess variable ?

**Comment by DepthFirstSearch** [comment]
Just look a few lines above ;)
```
server = tf.train.Server.create_local_server()
sess = tf.Session(server.target)
from keras import backend as K
K.set_session(sess)
```
This is not a bug or issue, so maybe it would be better to ask this question in the [Keras forum](https://groups.google.com/forum/#!forum/keras-users).

**Comment by kushia** [comment]
Hi :)
Thanks for your answer!

I saw those lines, but, they corresponds to the initialization of the session, not for retrieve a session from a trained model..

But, I found the answer in reading the manual :)
The solution to retrieve the sess was to use K.get_session()

Thanks to you!
PS : I'll remember for the keras forum
