### ISSUE TITLE
Tensor.eval() doesn't work during compile in layer getting batch size

### ISSUE THREAD

**Issue by mustgoplay** [fchollet/keras#4617]
I have the following in a custom layer:

`    
neibs = images2neibs(x, self.subsample, (1,1), self.border_mode)
`

I need to get the shape of the neibs so that I can get the batch size being fed into the layer for a reshape:

`
batch_shape = K.shape(output_correlations).eval()
`

I can't eval() the shape, it throws an error during compilation:

`
    batch_shape = K.shape(neibs).eval()
  File "C:\Anaconda3\envs\testnet\lib\site-packages\theano\gof\graph.py", line 520, in eval
    self._fn_cache[inputs] = theano.function(inputs, self)
  File "C:\Anaconda3\envs\testnet\lib\site-packages\theano\compile\function.py", line 320, in function
    output_keys=output_keys)
  File "C:\Anaconda3\envs\testnet\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "C:\Anaconda3\envs\testnet\lib\site-packages\theano\compile\function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "C:\Anaconda3\envs\testnet\lib\site-packages\theano\compile\function_module.py", line 1428, in __init__
    accept_inplace)
  File "C:\Anaconda3\envs\testnet\lib\site-packages\theano\compile\function_module.py", line 177, in std_fgraph
    update_mapping=update_mapping)
  File "C:\Anaconda3\envs\testnet\lib\site-packages\theano\gof\fg.py", line 171, in __init__
    self.__import_r__(output, reason="init")
  File "C:\Anaconda3\envs\testnet\lib\site-packages\theano\gof\fg.py", line 360, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "C:\Anaconda3\envs\testnet\lib\site-packages\theano\gof\fg.py", line 465, in __import__
    detailed_err_msg)
theano.gof.fg.MissingInputError: A variable that is an input to the graph was neither provided as an input to the function nor given a value. A chain of variables leading from this input to an output is [imageinputlayer_input_1, AbstractConv2d{border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(32, 1, 3, 3)}.0, Elemwise{clip,no_inplace}.0, Elemwise{mul,no_inplace}.0, Images2Neibs{valid}.0, DimShuffle{1,0}.0, dot.0, Elemwise{sub,no_inplace}.0, Elemwise{true_div,no_inplace}.0, Shape.0]. This chain may not be unique
Backtrace when the variable is created:
  File "C:/Users/Anon/Documents/PycharmProjects/ailearningnetwork/ailearningnetwork/MNISTKeras.py", line 153, in <module>
    input_shape = (1, img_rows, img_cols)))
  File "C:\Anaconda3\envs\testnet\lib\site-packages\keras\models.py", line 275, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "C:\Anaconda3\envs\testnet\lib\site-packages\keras\engine\topology.py", line 363, in create_input_layer
    dtype=input_dtype, name=name)
  File "C:\Anaconda3\envs\testnet\lib\site-packages\keras\engine\topology.py", line 1081, in Input
    input_tensor=tensor)
  File "C:\Anaconda3\envs\testnet\lib\site-packages\keras\engine\topology.py", line 1004, in __init__
    name=self.name)
  File "C:\Anaconda3\envs\testnet\lib\site-packages\keras\backend\theano_backend.py", line 54, in placeholder
    x = T.TensorType(dtype, broadcast)(name)
`

Any ideas please as to how to either make the eval work during the compilation or how to get the batch size during compilation?

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by nouiz** [comment]
the formating of the error message got lost. This make it unreadable. Here
is the most important part of it:

theano.gof.fg.MissingInputError: A variable that is an input to the graph
was neither provided as an input to the function nor given a value.

The shape depend on some input value that aren't provided.

**Comment by mustgoplay** [comment]
Thank you nouiz.

Yes, that seems to be the theme with the compile stage and it's the input variable data that I believe is left as None during compilation and it's not allowing things to calculate.

If I do the exact same commands in a notebook the shape returns just fine because I have an actual input.

But how do I get around this?  How do I get the shape of the input (and therefor the batch size) into a non-tensor variable in such a way that it will compile please?  Just passing a batch_size parameter doesn't work because there can be different batch sizes for testing and for training and plotting and once it compiles with one size it fails with the other.

So is there a way to get K.tensor.eval() to compile despite the fact that the input doesn't exist during compilation?

Thanks.

**Comment by crosleythomas** [comment]
@mustgoplay I'm having a similar issue in a custom loss function.  Being able to use .eval() seems necessary for doing anything dynamic based on the values of your actual data but doesn't work with .compile().

The only thing I can think of is that the compile stage needs everything abstracted into keras backend functions and .eval() doesn't work since it gives you the actual values from a tensor.

I'm trying to do a winner-take-all loss so I need to evaluate the index of the best performing particle but get the same issue when trying to evaluate the index of my best particle.

`# y_true.shape = (batch_size, 1, label_dims)
# y_true.shape = (batch_size, num_particles, label_dims)
def winner_take_all_loss(y_true, y_pred):
	errors = []
	for p in range(0, num_particles):
		errors.append(K.sum(K.abs(y_true - y_pred[:,p,:])))
	min_index = K.argmin(errors).eval()
	if min_index == 0:
		loss = K.abs(y_true - y_pred[:,0,:])
	else:
		loss = K.abs(y_true - y_pred[:,0,:]) - K.abs(y_true - y_pred[:,0,:])
	for p in range(1, num_particles):
		index_compare_tensor = K.variable(value=p)
		if min_index == p: # min_index == p, use true loss
			next_loss = K.abs(y_true - y_pred[:,p,:])
		else:
			# If I just create a K.zeros(...) variable they complain about the 
			# loss variable not being connected to the network, so here's a hacky
			# way of getting zero loss with respect to the actual prediction
			next_loss = K.abs(y_true - y_pred[:,p,:]) - K.abs(y_true - y_pred[:,p,:])
		loss = K.concatenate([loss, next_loss], axis=1)
	return loss
`

**Comment by crosleythomas** [comment]
#4307

**Comment by mustgoplay** [comment]
The only way I could get it to work was to pass the batch size as a parameter.  I think we're stuck :(

**Comment by priyankamandikal** [comment]
@crosleythomas I need to do the exact same thing that you were trying to do. I need to perform some (complex) numpy operations on my output tensor and hence need to run K.eval() on it. Did you get it to work with model.compile()??

**Comment by yashgarg1232** [comment]
Any update on this issue? I am trying to write my own custom merge layer, that seeks to use K.eval(), but during compile time, negative dimension error is thrown.
