### ISSUE TITLE
Images getting grayscale after passing trough ImageGenerator, Is it right?

### ISSUE THREAD

**Issue by mabirck** [fchollet/keras#4619]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

https://gist.github.com/mabirck/7047463f802c0ccf559ae3f18387319a
![screenshot from 2016-12-06 11-56-40](https://cloud.githubusercontent.com/assets/13804708/20928041/219435a2-bbab-11e6-948f-bebff29fd86e.png)

**Comment by DepthFirstSearch** [comment]
That's hardly a question...

Please provide more information.

**Comment by mabirck** [comment]
I have found it out, that was dataype problem, I was passing the images as int and for some reason it was getting the same pixel value to three channels and converting to grayscale after the imageGenerator... Thank you anyway @DepthFirstSearch, it was a very strange behavior probably I was making something wrong
