### ISSUE TITLE
Training multi task networks

### ISSUE THREAD

**Issue by gnuchoi** [fchollet/keras#462]
I'm wondering if I could build a multi-task convolutional network. This concept was introduced in Marc'Aurelio's CVPR 2014 tutorial(https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxsc3ZydHV0b3JpYWxjdnByMTR8Z3g6Njg5MmZkZTM1MDhhZWNmZA), 92page, or as below:
![image]
(http://2.bp.blogspot.com/-tsg6t-cTxW0/Vbn1AlQwnrI/AAAAAAAACTk/HzUHyNbTtxI/s1600/Screen%2BShot%2B2015-07-30%2Bat%2B%25E1%2584%258B%25E1%2585%25A9%25E1%2584%2592%25E1%2585%25AE%2B6.55.01.png)

In my case, even the number of classes would be different for each task, and I still want to minimise theano-level coding for this. 
Any opinion would be appreciated, thanks!

**Comment by pranv** [comment]
Its easy with the `Graph` model. Check out http://keras.io/models/#graph

**Comment by gnuchoi** [comment]
Great, thanks!
