### ISSUE TITLE
How to update parameters for every K batch?

### ISSUE THREAD

**Issue by rex-yue-wu** [fchollet/keras#4622]
Hi all,

As far as I know, the `model.fit( )` updates model parameters for every batch. However, I want my model to update model parameters for every `K` batch, because my model is big and I can only train a model with `batch_size = 1` (otherwise this model cannot be fitted into GPU memory). Of course, my model can still be trained for a single sample batch, but this setting makes my model quickly overfit to training data. Ideally, I want to use `batch_size =16`. Does anyone know how to set `keras` to update model parameters for every `16` batches?

**Comment by jasonTuZq** [comment]
I think the function fit_generator() may help. You can refer to https://keras.io/models/sequential/ for more information.

**Comment by rex-yue-wu** [comment]
Do you mean the `samples_per_epoch` parameter in `fit_generator( )`? Do you mean the `batch_size` in `fit_generator( )` is actually the `minibatch` size in `caffe`?

**Comment by samvaran** [comment]
@rex-yue-wu did you ever find a solution for this?
