### ISSUE TITLE
Regularizer

### ISSUE THREAD

**Issue by gravity1989** [fchollet/keras#4626]
Hi,

I want to implement a custom ActivityRegularizer .

I want to take the output of the network and calculate some additional losses using some Python /Skcit functions.

However, for this I need to use K.eval() on self.layer.output. The code however won't allow me because K.eval() isn't available during compile time. 

How do I get over this problem?

**Comment by fchollet** [comment]
You cannot use pure Python functions inside a Keras layer or regularizer.
You should reimplement the same functionality using the math primitives
from the Keras backend (e.g. K.dot(), etc.)

**Comment by gravity1989** [comment]
I was able to see that one could use pure functions inside a weight regularizer by using K.eval(self.layer.getWeights())

We can see that the EuclidianRegularizer uses the eval() functionality.  Any specific reason why ActivityRegularizer isn't allowed to do this?

**Comment by gravity1989** [comment]
My bad!

There is no K.eval(self.layer.getWeights()) but only a K.eval() on shapes. I wonder however that it is so inconvenient not to be able to add regularization losses for which backpropogation is not important to be specified strictly in Keras.
