### ISSUE TITLE
Theano memory issues. 

### ISSUE THREAD

**Issue by maxaug** [fchollet/keras#4633]
Hello there, 

I don't have an exact message on me now as I am in the middle of training my model under TF but this is an issue i've had on two setups:

Setup 1: 32Gb RAM, no GPU
Setup 2: p2.xlarge instance - 60GB RAM, 1/2 Tesla K80

Model goes like this: LSTM 2, LSTM16, LSTM8, Dense1 ( but this happens on any lstm/gru network) 
Data is 3GB CSV (4*0.75GB)
Memory usage on Theano is like:
![15321436_1588947471135425_2108629537_o png](https://cloud.githubusercontent.com/assets/9210039/20986714/125561f4-bcca-11e6-9c38-47bfb33ad91b.jpeg)

What happens there roughly is theano invokes g++ and each compilation blows up (OOM)
What happens there with TF, it plateaus on 35GB of memory and runs happily, so even though Setup 1 might be out of question (leave optimization), Setup 2 works like a charm.

   
I think it'd be worth to investigating.
Theano==0.9.0.dev3
Keras==1.1.0

**Comment by nouiz** [comment]
So, you tell that g++ is missing memory, not Theano?

Can you use a different g++ version? It seem a bug in g++, not Theano.

**Comment by maxaug** [comment]
I've tried both g++ 5.4.0 and g++ 4.8.4, same thing happens. What I believe is that maybe how theano uses g++ may be a problem. If that intrigues you, @nouiz I can provide more data in a few days.

**Comment by varunagrawal** [comment]
@maxaug did you find out the reason for the memory spike? I am trying to train a VGG network and am facing similar issues during model compilation.

**Comment by maxaug** [comment]
@varunagrawal: didn't have chance to investigate any further: If you can just switch to TF, do it. If that's not an option, I think you can try llvm-based compiler as it seemed faster to me on smaller workloads

**Comment by nouiz** [comment]
IF you use convolution or scan, make sure to update Theano. significant
updates was merged in some of the 0.9rc* version. Make sure to use 0.9rc4
of the current dev version.

If after that you still have the problem, I'll need a way to reproduce
this. Can someone give me a script that when I run it give me this problem?

It would be better to give that script in a Theano issue that reference
this issue. I check them more frequently then keras issue.
