### ISSUE TITLE
Bug in theano_backend for _Pooling1D?

### ISSUE THREAD

**Issue by sunil-at-gh** [fchollet/keras#4640]
From **_Pooling1D** subclasses, **K.pool2d** is called with `pool_size = (pool_length, 1)`.
In **theano_backend.pool2d**, when `border_mode = "same"`, the following line:

`h_pad = pool_size[1] - 2 if pool_size[1] % 2 == 1 else pool_size[1] - 1`

causes h_pad to get the value -1, which results in the following error on my machine:

> WARNING: probably bad CudaNdarray_set_dim arguments: self->ndim=4, idx=3 stride=-1
> Traceback (most recent call last):
>  File "/opt/anaconda3/lib/python3.5/site-packages/theano/compile/function_module.py", line 866, in __call__
>    self.fn() if output_subset is None else\
> AssertionError: Can't store in size_t for the bytes requested 18446744073709551615 * 4

I believe the correct value for `h_pad` in this case is `0`, suggesting the following fix:

`h_pad = pool_size[1] - 2 if pool_size[1] > 2 and pool_size[1] % 2 == 1 else pool_size[1] - 1`

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
Sounds reasonable. Please open a PR to fix it. Also please add a unit test to check this specific case.

Thanks!
