### ISSUE TITLE
Fit_generator not working with batches or with single entries

### ISSUE THREAD

**Issue by premrajnarkhede** [fchollet/keras#4641]
Hi I am consistently getting error "Exception: Error when checking model input: expected dense_input_1 to have shape (None, 3) but got array with shape (3, 1)" with fit_generator while just fit is working fine

`from keras.models import Sequential
from keras.layers import Dense, Activation
import numpy as np
from keras.optimizers import RMSprop,SGD
model = Sequential()
model.add(Dense(3, input_dim=3))
model.add(Activation('sigmoid'))
model.add(Dense(3))
model.add(Activation('sigmoid'))
model.add(Dense(3, activation='softmax'))

model.compile(optimizer=RMSprop(lr=0.01),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

def generator1():
    i=0
    inputData=[]
    outputData=[]
    while i<10:
        inputData.append([False,True,False])
        outputData.append([False,True,False])
        i=i+1
        yield np.array([False,True,False]),np.array([False,True,False])
    #yield np.array(inputData),np.array(outputData)

model.fit_generator(generator1(),samples_per_epoch=10, nb_epoch=10)`

Tried sending batches as well as individual entries.

**Comment by premrajnarkhede** [comment]
IF i send batches instead of individual samples by commented line at end of generator function. I am getting "Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None"

**Comment by premrajnarkhede** [comment]
I am sure there is some trivial mistake that I am doing. It will be great if someone can point it out

**Comment by patyork** [comment]
Alright, a few things:

In your generator, you will yield 10 items and then your generator will quit:
```python
def generator1():
    i=0
    inputData=[]
    outputData=[]
    while i<10: # this guy here
```

but you're wanting to run 10 epochs of 10 items, so you're going to get an exception there. (this is your second exception; your generator is depleted before training is done):
```
Epoch 1/10
 1/10 [==>...........................] - ETA: 0s - loss: 0.0180 - acc: 1.0000
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/engine/training.py", line 404, in data_generator_task
    generator_output = next(generator)
StopIteration

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-27-d134083e467c> in <module>()
----> 1 model.fit_generator(generator1(), samples_per_epoch=10, nb_epoch=10)

/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/models.pyc in fit_generator(self, generator, samples_per_epoch, nb_epoch, verbose, callbacks, validation_data, nb_val_samples, class_weight, max_q_size, nb_worker, pickle_safe, **kwargs)
    923                                         max_q_size=max_q_size,
    924                                         nb_worker=nb_worker,
--> 925                                         pickle_safe=pickle_safe)
    926 
    927     def evaluate_generator(self, generator, val_samples,

/usr/local/lib/python2.7/dist-packages/Keras-1.1.2-py2.7.egg/keras/engine/training.pyc in fit_generator(self, generator, samples_per_epoch, nb_epoch, verbose, callbacks, validation_data, nb_val_samples, class_weight, max_q_size, nb_worker, pickle_safe, initial_epoch)
   1423                     raise Exception('output of generator should be a tuple '
   1424                                     '(x, y, sample_weight) '
-> 1425                                     'or (x, y). Found: ' + str(generator_output))
   1426                 if len(generator_output) == 2:
   1427                     x, y = generator_output

Exception: output of generator should be a tuple (x, y, sample_weight) or (x, y). Found: None
```

Second, check your shapes to resolve your first issue:
```
np.array([False,True,False]).shape, np.array([False,True,False]).shape
```
```
((3,), (3,))
```

It expects `(BATCH_SIZE, 3)` not `(3,)`/`(3, 1)`. Since you appear to just be using a single element for a batch, the below is a valid change:
```
np.array([False,True,False]).reshape((1,3)).shape, np.array([False,True,False]).reshape((1,3)).shape
```
```
((1, 3), (1, 3))
```

**Comment by premrajnarkhede** [comment]
Thank you very much for this help!

**Comment by AdarshMJ** [comment]
I keep getting this error... Im not able to figure out what is the problem exactly... help me out!


![screen shot 2018-01-17 at 8 09 45 pm](https://user-images.githubusercontent.com/24205200/35048219-65ff1272-fbc2-11e7-8d1c-2a4173b5ee5f.png)
