### ISSUE TITLE
Too many indices for array: ImageDataGenerator

### ISSUE THREAD

**Issue by egiralt** [fchollet/keras#4645]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi!
I`m using the example in [https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html](url) to generate more images for each one in my dataset, but I am getting the following error:

> IndexError                                Traceback (most recent call last)
> < ipython-input-14-2d81fc849a89 > in < module >()
>     18 i = 0
>     19 for batch in datagen.flow(x, batch_size=1,
> ---> 20                           save_to_dir='images/train/1', save_prefix='cat', save_format='jpeg'):
>     21     i += 1
>     22     if i > 20:
>
> /usr/lib/python2.7/site-packages/keras/preprocessing/image.pyc in next(self)
>    579         if self.y is None:
>    580             return batch_x
> --> 581         batch_y = self.y[index_array]
>    582         return batch_x, batch_y
>    583 
>
> **IndexError: too many indices for array**
>
The code is the same, with different paths. :(

Gist: My code [https://gist.github.com/egiralt/a64b01fe6a82abd96708aca06c0f6cf6](url)

**Comment by fchollet** [comment]
I don't have access to your code snippet.

**Comment by egiralt** [comment]
Upps!.. My mistake..[here]( https://gist.github.com/egiralt/a64b01fe6a82abd96708aca06c0f6cf6)

**Comment by erilyth** [comment]
@egiralt I am unable to reproduce the issue. I tried using various output directories as well but it seems to work just fine.

**Comment by shirishr** [comment]
I have started getting this error.
See attached code.
Error occurs at line 253

[cd_trial1.zip](https://github.com/fchollet/keras/files/1346941/cd_trial1.zip)
