### ISSUE TITLE
how to use mean vector as default if the input node not in embedding layer

### ISSUE THREAD

**Issue by liuxialong** [fchollet/keras#4648]
If the predict input node not in embedding layer.(for example the input node is out of bound)

I wanna use mean vector of the embedding layer as default.

How should I do?

**Comment by bkj** [comment]
In what scenario would you be feeding an "out of bound node" to the network?  Do you mean a word at test time that was not in the training dataset?

**Comment by liuxialong** [comment]
@bkj 

Yes. Maybe a word that not in the training dataset.

In that case, I may use mean vector as default in embedding layer.
