### ISSUE TITLE
Using Keras model.fit with python Pool on a single GPU

### ISSUE THREAD

**Issue by biomorph** [fchollet/keras#4653]
I am running a 4 fold cross validation using early stopping. I figured I would run the 4 folds in parallel like so.
```
def multiprocess_fit(nn_model, x_train, y_train, early_stopping, x_val, y_val):
    nn_model.fit(x_train, y_train, batch_size=16384, nb_epoch=500, callbacks=[early_stopping],
                 validation_data=(x_val, y_val), verbose=0)
    y_pred = nn_model.predict(x_val)
    comb_score = combined_score(y_val, np.ravel(y_pred))
    return comb_score

def cb_func(result):
    comb_scores.append(result)

comb_scores = []
cv = cross_validation.LabelKFold(groups, 4)

for inner_train, inner_stop in cv:
    result = pool.apply_async(multiprocess_fit, args=(nn_model, x[inner_train], y[inner_train], early_stopping, x[inner_stop], y[inner_stop]), callback=cb_func)
    result.get()

pool.close()
pool.join()
print np.mean(comb_scores)
```

When I try to run this  with theano flags lib.cnmem=0.8,optimizer=fast_run,fast_math=True,device=gpu
I get the following error
```
Process PoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 376, in get
    return recv()
  File "/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/type.py", line 600, in CudaNdarray_unpickler
    return cuda.CudaNdarray(nap)
MemoryError: ('Error allocating 3600 bytes of device memory (CNMEM_STATUS_CUDA_ERROR).', <function CudaNdarray_unpickler at 0x7f42e6a3a9b0>
```
Can someone help me with this? Isn't it logical to use multiprocessing to fit the same model on 4 different training/validation datasets in the cv.
Thanks for any help

**Comment by patyork** [comment]
Theoretical answer, as I haven't ran anything like this, and you didn't provide any code:

Multiprocessing pickles the model, creating 4 separate instances of it. Each of these is sent to the GPU along with 4 sets of data, and are trained separately.

The first issue is that you'd wind up with 4 separate trained models. The second, and main issue that the error relates to, is that 4x the model + data size is too large to fit on your GPU. The only odd part is that 3600 bytes isn't much to be trying to allocate, and it seems pretty coincidental that you've got just barely not enough memory.

**Comment by biomorph** [comment]
Hi Pat,
These are very small models and datasets. The dataset has ~200 training examples with 180 features each. The GPU is not running anything else and has 12GB of memory. I don't necessarily mind that there are 4 separate networks. I only want the scores and the hyper parameters to pass back to hyperopt.
I have a feeling this might be an issue with Keras/theano not allowing multiple processes being run on the GPU from within the same program.
I am able to run multiple separate python scripts that train separate models on the same GPU.

**Comment by sebastian-schlecht** [comment]
@biomorph Did you try decreasing the amount of memory being allocated by cnmem , e.g. lib.cnmem=0.2?

**Comment by biomorph** [comment]
@sebastian-schlecht I tried lib.cnmem=0.2 and lib.cnmem=0.1 with the same issue. Looks like the memory assignment happens when the python script is first invoked. I feel like any additional multiprocessing calls within the python script try to assign an additional memory beyond 20% (lib.cnmem) and fail.

**Comment by sebastian-schlecht** [comment]
I've also noticed that your batch-size is with `batch_size=16384` fairly large. Depending on your data that could flood the memory, too. Another option could be turning off cnmem.

**Comment by biomorph** [comment]
I thought that increasing the batch_size to that large number would put all the training data in memory and speed up computation, considering my training set is small ~200 training rows. I've also tried without setting cnmem and see the same error. In fact I only see ~78MiB of memory being used by the GPU for this 200 row training data. So clearly there is plenty of memory left on the graphics card.

**Comment by Borda** [comment]
Hello, is there an answer to this question for using Tensoflow backend?
I was following discussion #9964 but they are running everything on CPU.
