### ISSUE TITLE
Keras Custom Layer  ValueError: GpuElemwise. Input dimension mis-match. 

### ISSUE THREAD

**Issue by GerardoHH** [fchollet/keras#4654]
Hi,  I'm writing  a custom keras layer, but I can't make it work, my model compiles  but give me a run time error on  model.fit. I hope anyone can help me. And Sory for my English.

### My Custom Layer is ( I know it's not a softmax, I'm starting to code ) 

class CustomSoftmax( Layer ):

    def __init__(self, **kwargs):        
        super(CustomSoftmax, self).__init__(**kwargs)

    def build(self, input_shape):
        self.input_dim = input_shape
        self.output_dim = ( self.input_dim[0],  self.input_dim[ 1 ] , self.input_dim[2] )
        initial_weight_value = np.random.random( ( self.input_dim[2]) ) 
        self.W = K.variable(initial_weight_value)
        self.trainable_weights = [self.W]

    def get_output_shape_for(self, input_shape):
        return (input_shape[0], self.output_dim[1], self.output_dim[2] )  
        
    def call(self, x, mask=None):
        s_x = x.sum( axis = 1 )
        s_x = np.multiply( s_x, self.W )
        return s_x

### The model summary is

convolution3d_1 (Convolution3D)  (None, 7, 15, 54, 34) 1722        convolution3d_input_1[0][0]      
____________________________________________________________________________________________________
maxpooling3d_1 (MaxPooling3D)    (None, 7, 15, 27, 17) 0           convolution3d_1[0][0]            
____________________________________________________________________________________________________
convolution3d_2 (Convolution3D)  (None, 35, 15, 27, 17 18410       maxpooling3d_1[0][0]             
____________________________________________________________________________________________________
maxpooling3d_2 (MaxPooling3D)    (None, 35, 15, 13, 8) 0           convolution3d_2[0][0]            
____________________________________________________________________________________________________
convolution3d_3 (Convolution3D)  (None, 5, 15, 13, 8)  4730        maxpooling3d_2[0][0]             
____________________________________________________________________________________________________
reshape_1 (Reshape)              (None, 5, 15, 104)    0           convolution3d_3[0][0]            
____________________________________________________________________________________________________
permute_1 (Permute)              (None, 5, 104, 15)    0           reshape_1[0][0]                  
____________________________________________________________________________________________________
customsoftmax_1 (CustomSoftmax)  (None, 5, 104)        104         permute_1[0][0]                  
____________________________________________________________________________________________________
flatten_1 (Flatten)              (None, 520)           0           customsoftmax_1[0][0]            
____________________________________________________________________________________________________
dropout_1 (Dropout)              (None, 520)           0           flatten_1[0][0]                  
____________________________________________________________________________________________________
dense_1 (Dense)                  (None, 1000)          521000      dropout_1[0][0]                  
____________________________________________________________________________________________________
dropout_2 (Dropout)              (None, 1000)          0           dense_1[0][0]                    
____________________________________________________________________________________________________
dense_2 (Dense)                  (None, 100)           100100      dropout_2[0][0]                  
____________________________________________________________________________________________________
dropout_3 (Dropout)              (None, 100)           0           dense_2[0][0]                    
____________________________________________________________________________________________________
dense_3 (Dense)                  (None, 6)             606         dropout_3[0][0]                  
____________________________________________________________________________________________________
activation_1 (Activation)        (None, 6)             0           dense_3[0][0]                    

Total params: 646672

### And the error 

ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[2] == 104, but the output's size on that axis is 15.
Apply node that caused the error: GpuElemwise{mul,no_inplace}(GpuReshape{3}.0, GpuDimShuffle{x,x,0}.0)
Toposort index: 110
Inputs types: [CudaNdarrayType(float32, 3D), CudaNdarrayType(float32, (True, True, False))]
Inputs shapes: [(1, 104, 15), (1, 1, 104)]
Inputs strides: [(0, 15, 1), (0, 0, 1)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuReshape{2}(GpuElemwise{mul,no_inplace}.0, MakeVector{dtype='int64'}.0)]]

**Comment by cbdbdd** [comment]
try make shape (1,1,104) as(1,104) to make the broadcast possible

**Comment by cbdbdd** [comment]
or try to make input shape as (1,15,104) and (1,1,104)

**Comment by GerardoHH** [comment]
hi @cbdbdd 

Thank you for your fast reply,  I don't fully understand what I have to do,   let me explain my understanding about custom keras layers

1.-   The input shape of my custom layer is  _( None, 5, 104, 15 )_
- None = batch size 
- 5  Feature Maps  / kernel filters
- 104 , 15   the width and high of  each filter


2. In my "call" method, _**I suppose the shape of X is ( None, 5,105,15) right**_ ?  If true , then, the shape of 
   `s_x = x.sum ( axis =1 )`    

 has to be like  ( None, 5 , 104 )  ( I tested this with theano on a separated function ) 

3.    the element-wise multiplication with _W (of shape 104)_  is  
  ` s_x =  np.multiply( s_x , self.W )`

the element-wise multiplication does not modify the shape, so,  If  I understand correctly, the shape of the ouput tensor  _**s_x  it's  (None, 5, 104 )**_

4. An the return value of the method  get_output_shape_for  it
                         ( None, 5, 104) 

Thank you !

   




-

**Comment by cbdbdd** [comment]
the elememtwise error arises from the mp.multiply operation. also watch my issue #4464  
https://github.com/fchollet/keras/issues/4464

**Comment by cbdbdd** [comment]
maybe (i havn't tested it)the x.sum shape is (1,104,15), you can test it ny quoting the np.multiply line.  try:
1.initialise W with shape (1,104) or (104,1)
if does not work

try
2.switch the input shape dimensions order of your custom layer to(15,104) and w's shape (104)or(1,104)

**Comment by GerardoHH** [comment]
Hi @cbdbdd 

Thank you for your help,  after read your suggestions, I realized that I was missundertanding the x.sum operation,  Thank you  again!!
