### ISSUE TITLE
keras on theano throws error while fitting the data: "this shared variable already has update expression"?

### ISSUE THREAD

**Issue by payman-kh** [fchollet/keras#4656]
I am trying to implement a multilayer CNN in keras running on theano which has 11 inputs. but it throws the error while fitting the data:

`
model.fit([x_train_0,x_train_1,x_train_2,x_train_3,x_train_4,x_train_5,x_train_6,x_train_7,x_train_8,x_train_9,x_train_10], y_train,validation_data([x_test_0,x_test_1,x_test_2,x_test_3,x_test_4,x_test_5,x_test_6,x_test_7,x_test_8,x_test_9,x_test_10], y_test), nb_epoch = 4, batch_size = 16)
`

It seems it happens while it is is validating the result a on the test data. I know this error is related to theano. I can run the code on tensorflow. 
Does anyone know how I can fix this? Do I have to reinstall keras or theano? 
I think I have the latest versions.

thanks,
payman

**Comment by fchollet** [comment]
Provide a minimal code snippet to reproduce the issue.

**Comment by payman-kh** [comment]
I found the problem. My layers were not shared while each convolutional unit was feeding 2 units in the next layer. Now I am using the api to write the same network with shared layers. That should fix the problem. 
btw, thanks for the help
