### ISSUE TITLE
make custom training data for image_ocr.py

### ISSUE THREAD

**Issue by wanghaisheng** [fchollet/keras#4658]
i have successfully build keras environment and run the default training data embedding in image_ocr.py
now  i want  to make some training data for Chinese
simply  put one chinese word in 
wordlist_mono_clean_cn.txt
```
啊
阿
埃
挨
哎
唉
哀
```
and  two same  words in 
wordlist_bi_clean_cn.txt
```
啊 啊
阿 阿
埃 埃
挨 挨
哎 哎
唉 唉
哀 哀
```
it cames into error 
```
string_list  19
num_words  16000

IOError: Could not pull enough words from supplied monogram and bigram files. 
```
@mbhenry

**Comment by jozi** [comment]
@wanghaisheng The number of words for your input data file is too low

**Comment by wanghaisheng** [comment]
@jozi  here is just an example  .what i actually use is 5000 words in wordlist_mono_clean_cn.txt

**Comment by jozi** [comment]
@wanghaisheng  16,000 word you need to have a length of less than 4
in line 
https://github.com/fchollet/keras/blob/master/examples/image_ocr.py#L296
