### ISSUE TITLE
Building docs localy - error

### ISSUE THREAD

**Issue by EdaEhler** [fchollet/keras#4659]
While building the keras documentation locally as described in /docs, I have encountered following error:
'utf-8' codec can't decode byte 0x96 in position 8197: invalid start byte

Turned out that in file ./sources/layers/recurrent.md there is a strange sing "-" on the line 187 (the "Encoder-Decoder" part):
`[On the Properties of Neural Machine Translation: Encoder-Decoder Approaches](http://www.aclweb.org/anthology/W14-4012).`

After changing this "-", the install finished successfully.

My system: Win10, Python 3.5.0 (64 bit)

**Comment by fchollet** [comment]
Fixed.
