### ISSUE TITLE
`Module:clone` from Torch in keras?

### ISSUE THREAD

**Issue by desilinguist** [fchollet/keras#466]
Is there a way to `clone` a layer in keras similar to the way it's [done](https://github.com/torch/nn/blob/master/doc/module.md#clonemlp) in torch? I can use `copy.deepcopy` to get some of the way there but I can't see how to share the parameters between the two copies.

**Comment by andychisholm** [comment]
You might find the discussion in #362 helpful.

**Comment by EderSantana** [comment]
If you use `copy.deepcopy` everything will be shared. In my experience Theano tensors are like global variables though. If you change it in one model, it will change in the others.
