### ISSUE TITLE
Can't import Graph

### ISSUE THREAD

**Issue by byeongcheoljo** [fchollet/keras#4661]
I installed keras with pip and I'm having an issue trying to create a Graph model:

from keras.models import Sequential,Graph

ImportError: cannot import name Graph

pip version 1.5.4
python version 2.7

**Comment by fchollet** [comment]
Graph has been removed. Use the functional API (see docs).

**Comment by rdelassus** [comment]
Would be nice if the doc was updated then.

https://keras.io/layers/containers/ is not true anymore, leading me to search the Graph class with obivously no success. Even the [commit](https://github.com/fchollet/keras/commit/61ade48343bbc9a030f60e4398b1f9007e984517) removing the Graph class doesn't say anything about it.
