### ISSUE TITLE
Howto give constant tensor  as layer input 

### ISSUE THREAD

**Issue by calanchue** [fchollet/keras#4663]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [o ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ o] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [o ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). 
[code gist link](https://gist.github.com/calanchue/28b69cb31e5e440f7b58cc9aa5a71426)

I want to give some constant tensor variable as layer input 

belows is my original implementation. 
(ext_z is tensor variable, decoder_tower is Model)
```python
decoded_list = []
for idx, ext_z in enumerate(ext_z_list) :
 one_hot_label = np.zeros((batch_size, label_dim))
 one_hot_label[:,idx] = 1

 one_decoded_img_set = decoder_tower([ext_z, K.variable(one_hot_label)]) 
 decoded_list.append(one_decoded_img_set)

decoded_set_tn = merge(decoded_list, mode="concat", concat_axis=1)

```

but this give me error at the end of the model creation.

```python
atoz = Model(img_input_tensor, decoded_set_tn)
```
`Exception: Output tensors to a Model must be Keras tensors. Found: Join.0`

If i use 'Input' as input for decoder_tower layer, it works fine

```python
test_label_holder = Input(shape=(label_dim,), name="test_label_layer")
decoded_list = []
for idx, ext_z in enumerate(ext_z_list) :
 one_hot_label = np.zeros((batch_size, label_dim))
 one_hot_label[:,idx] = 1

 #one_decoded_img_set = decoder_tower([ext_z, K.variable(one_hot_label)])
 one_decoded_img_set = decoder_tower([ext_z, test_label_holder])
 decoded_list.append(one_decoded_img_set)

decoded_set_tn = merge(decoded_list, mode="concat", concat_axis=1)

``` 

But, if i use Input implementation, I should make redundant 52 input layer. It also needs big size of redundant batch.

How can i solve these issue? 

my code gist

**Comment by fchollet** [comment]
Use the following in order to convert your tensor to a Keras tensor:

```python
from keras.layers import Input

one_decoded_img_set = Input(tensor= one_decoded_img_set)
```
