### ISSUE TITLE
Tensorboard logs not being written

### ISSUE THREAD

**Issue by bnaul** [fchollet/keras#4667]
Since https://github.com/fchollet/keras/commit/93b7dd99158ddbe99a299606d55f495629556c90,  logs aren't actually being written beyond the initial value; this makes sense since the writer is being closed after the first epoch. Perhaps this change belongs in `on_train_end` instead?

Before  https://github.com/fchollet/keras/commit/93b7dd99158ddbe99a299606d55f495629556c90: ![Before](https://dl.dropboxusercontent.com/u/12771020/Screenshot%202016-12-09%2014.41.23.png)

After: ![After](https://dl.dropboxusercontent.com/u/12771020/Screenshot%202016-12-09%2014.44.53.png)

**Comment by fchollet** [comment]
I fixed it, thanks.
