### ISSUE TITLE
Problem when running the mnist example

### ISSUE THREAD

**Issue by newvic2008** [fchollet/keras#4670]
Hi there

When I ran the mnist_cnn.py, the system told the words below

_Using Theano backend.
Traceback (most recent call last):
  File "mnist_cnn.py", line 33, in <module>
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
ValueError: too many values to unpack_

Anyone encounters the same problem or has any idea to solve it?

Thanks a lot.

**Comment by fchollet** [comment]
It definitely does work. Consider updating Keras.
