### ISSUE TITLE
How to provide output of one model as input to other models?

### ISSUE THREAD

**Issue by atana1** [fchollet/keras#4672]
I have been learning keras. I would like to know how to connects models in the following scenario

    """
                          M1
                        /      \
                     M2     M3
                       \        /
                          M4
    """

M1, M2, and M3 are different models. I want to connect them in such a way that output from M1 is input to both M2 and M3 models and the overall model is trainable. Input is through M1.

**Comment by josepablog** [comment]
M2 -> M4 <- M3 is easy to do using a Merge layer in a ``Sequential`` model.  Unfortunately, you can't do the branching out using the ``Sequential`` model, and you must use the functional API (class: ``Model``).  

Hope that helps!

**Comment by atana1** [comment]
m = Merge([M2, M3], mode="concat")
    out_m1 = M1(input_)
    out_m2 = M2(out_m1)
    out_m3 = M3(out_m1)
    fout = m([out_m2, out_m3])
    finalModel = Model(input="input_", output=fout)

Did you mean something like above?

**Comment by Aziz-repo** [comment]
I'm in the middle of building a project with multiple machine learning models.
The issue is that I'm using multiple libraries (i.e a model built with Keras and another built with Torch). Is there a way to make one of them feed data to the other model?
Thank you
