### ISSUE TITLE
in jupyter notebook any way to set model.fit() output error frequency?

### ISSUE THREAD

**Issue by pswpswpsw** [fchollet/keras#4676]
model.fit() with verbose = 1 can output error status, however, sometimes it is too fast that the webpage is getting slow..remember jupyter notebook is still a webpage..  is there anyway to get around with his?

**Comment by patyork** [comment]
You can set `verbose` to either 0 or 2, use the RemoteMonitor callback (or a variant of it that also posts data on batch_end), and write your own web service to display the data. If you are using TensorFlow, TensorBoard may be an option. But barring those two options, right now, there is no other option other than TensorBoard for TensorFlow, or just logging less data.

Jupyter does not handle the screen clears correctly, and accrues the output, making the notebook larger and larger. If you look at a saved notebook after the `.fit` method, you'll see stuff like this:
```
[=>...................]
[==>..................]
[===>.................]
[====>................]
```
which quickly gets to be a lot of data.

**Comment by pswpswpsw** [comment]
Thanks for the response. Actually I use tensorboard to monitor my work on workstation. The workstation works on a dropbox file folder so I can see what's going on by just tensorboard at this dropbox. 

Another option I just find is that, use command line rather than ipython notebook..which is much faster for output to screen.
