### ISSUE TITLE
difference between ActivityRegularization and activity_regularizer?

### ISSUE THREAD

**Issue by pswpswpsw** [fchollet/keras#4678]
I look some code at the website, it seems to me that they are the same thing. 

But ActivityRegularization is a "layer"

while activity_regularizer is just a argument as a reguarlizer. 

They both contribute to the output of the network that show as a penalty cost function

**Comment by fchollet** [comment]
The ActivityRegularization layer just applies activity regularization on
its input. You can also apply activity regularization on the output of
specific layer by passing them the activity_regularizer argument.
