### ISSUE TITLE
Graph problem with RNN and 2 inputs

### ISSUE THREAD

**Issue by pjadzinsky** [fchollet/keras#468]
Hi,

I have three time serie and I'm trying to predict one from the other two. I want to implement a graph with two inputs and one output and some RNN architecture. Each time series has shape (nb_samples, time_steps, 1). I'd like to concatenate the two inputs into a 3D tensor of shape (nb_samples, time_steps, 2) before calling the SimpleRNN layer. The 1st version of the code below fails. However, the 2nd version (changing merge_mode to 'sum' and adjusting for the expected tensor size in the next recurrent layer) works just fine.

Any idea what the problem might be?

thanks
Pablo

Version 1 (crashes)

        graph = Graph()
        graph.add_input(name='input1', ndim=3)
        graph.add_input(name='input2', ndim=3)

        graph.add_node(Activation(linear), 
                name='concat', inputs=['input1', 'input2'], merge_mode='concat')
        
        graph.add_node(SimpleRNN(2, 1, return_sequences=True),
                name='SimpleRNN', input='concat')

        graph.add_output(name='output', input='SimpleRNN')
        
        graph.compile('rmsprop', {'output':'mse'})

Version 2 (works fine)

        graph = Graph()
        graph.add_input(name='input1', ndim=3)
        graph.add_input(name='input2', ndim=3)

        graph.add_node(Activation(linear), 
                name='concat', inputs=['input1', 'input2'], merge_mode='sum')
        
        graph.add_node(SimpleRNN(1, 1, return_sequences=True),
                name='SimpleRNN', input='concat')

        graph.add_output(name='output', input='SimpleRNN')
        
        graph.compile('rmsprop', {'output':'mse'})

**Comment by fchollet** [comment]
So what error message do you get?

**Comment by pjadzinsky** [comment]
Hey,

This is the error...
Thanks

Epoch 0
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/jadz/miniconda3/lib/python3.4/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    594         try:
--> 595             outputs = self.fn()
    596         except Exception:

ValueError: total size of new array must be unchanged

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-11-19da46d5ab99> in <module>()
----> 1 model.graph.fit(g.get_dict())

/Users/jadz/miniconda3/lib/python3.4/site-packages/Keras-0.1.2-py3.4.egg/keras/models.py in fit(self, data, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle)
    586         metrics = self.output_order + ['val_' + m for m in self.output_order]
    587         history = self._fit(f, ins, out_labels=out_labels, batch_size=batch_size, nb_epoch=nb_epoch, verbose=verbose, callbacks=callbacks, \
--> 588             validation_split=validation_split, val_f=val_f, val_ins=val_ins, shuffle=shuffle, metrics=metrics)
    589         return history
    590 

/Users/jadz/miniconda3/lib/python3.4/site-packages/Keras-0.1.2-py3.4.egg/keras/models.py in _fit(self, f, ins, out_labels, batch_size, nb_epoch, verbose, callbacks, validation_split, val_f, val_ins, shuffle, metrics)
    168                 batch_logs['size'] = len(batch_ids)
    169                 callbacks.on_batch_begin(batch_index, batch_logs)
--> 170                 outs = f(*ins_batch)
    171                 if type(outs) != list:
    172                     outs = [outs]

/Users/jadz/miniconda3/lib/python3.4/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    604                         self.fn.nodes[self.fn.position_of_error],
    605                         self.fn.thunks[self.fn.position_of_error],
--> 606                         storage_map=self.fn.storage_map)
    607                 else:
    608                     # For the c linker We don't have access from

/Users/jadz/miniconda3/lib/python3.4/site-packages/theano/gof/link.py in raise_with_op(node, thunk, exc_info, storage_map)
    204     exc_value = exc_type(str(exc_value) + detailed_err_msg +
    205                          '\n' + '\n'.join(hints))
--> 206     raise exc_type(exc_value).with_traceback(exc_trace)
    207 
    208 

/Users/jadz/miniconda3/lib/python3.4/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    593         t0_fn = time.time()
    594         try:
--> 595             outputs = self.fn()
    596         except Exception:
    597             if hasattr(self.fn, 'position_of_error'):

ValueError: total size of new array must be unchanged
Apply node that caused the error: Reshape{2}(InplaceDimShuffle{1,0,2}.0, MakeVector.0)
Inputs types: [TensorType(float64, 3D), TensorType(int64, vector)]
Inputs shapes: [(10, 128, 2), (2,)]
Inputs strides: [(16, 160, 8), (8,)]
Inputs values: ['not shown', array([1280,    1])]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by fchollet** [comment]
Try upgrading Theano to latest Github version (not pip).

**Comment by pjadzinsky** [comment]
Thanks, that worked.
