### ISSUE TITLE
Using Embedding layer without minibatch

### ISSUE THREAD

**Issue by chithangduong** [fchollet/keras#4686]
Keras gives an excellent example on how to use pre-trained vectors for text classification:
https://blog.keras.io/using-pre-trained-word-embeddings-in-a-keras-model.html

However, the provided example uses minibatches. As my dataset is small, I want to process the training data one sample at a time. From my understanding of the provided code, I can do this easily by removing                             
`input_length=MAX_SEQUENCE_LENGTH` from the [Embedding layer](https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py#L143)
and 
setting 
`batch_size=1` in [model.fit](https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py#L143).
Is it correct? Should I also remove the pad_sequences [part](https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py#L83) ?

**Comment by fchollet** [comment]
> However, the provided example uses minibatches. As my dataset is small, I want to process the training data one sample at a time

Use a `batch_size` of 1.

`input_length` is purely optional, so feel free to remove it if your sequences do not have a fixed length. In that case, padding is no longer necessary, so you can remove the `pad_sequences` call to.

**Comment by chithangduong** [comment]
Without `pad_sequences`, the input array to `model.fit` has mismatching dimensions. This will give an error: `ValueError: setting an array element with a sequence.` Am I missing something here ? 

The error can be reproduced by first replacing [`pad_sequences`](https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py#L83) with `data = np.array(sequences)` or 
```
lse = []
for sequence in sequences:
    lse.append(np.array(sequence))
data = np.array(lse)
```
Both gave the same error.

Second, change the model to the following as the one in the example cannot handle input with varying size:
```
sequence_input = Input(shape=(None,), dtype='int32')
embedded_sequences = embedding_layer(sequence_input)
x = GlobalMaxPooling1D()(embedded_sequences)
preds = Dense(len(labels_index), activation='softmax')(x)
```

Finally, setting the `batch_size` to 1 in model.fit
```
model.fit(x_train, y_train, validation_data=(x_val, y_val),
          nb_epoch=2, batch_size=1)
```

In the example, you said that "although an Embedding layer is capable of processing sequence of heterogenous length, if you don't pass an explicit input_length argument to the layer". Is it the case that the Embedding layer can handle input with heterogeneous length but `model.fit` can't?
