### ISSUE TITLE
full image testing instead of  patch based testing of CNN model

### ISSUE THREAD

**Issue by Mboga** [fchollet/keras#4688]
I am trying to implement a full image test because according to literature eg https://arxiv.org/pdf/1302.1700v1.pdf it is more efficient. Suppose I have two max-pooling layers of stride 2, it means that I have to shift the input in each layer 4 times,. How can one merge the resulting feature maps in each layer before using it as an input to the next convolution layer?
Any advice on how to best approach this?

nic

**Comment by ncullen93** [comment]
You can use the aptly named 'Merge' layer.. 
https://keras.io/layers/core/#merge

Your model might look something like this:
..
...
conv_layer = Convolution2D(...)(previous_layer0
feat_map1 = MaxPooling2D(..)(conv_layer)
model1 = Model(inputs,feat_map1)

feat_map2 = MaxPooling2D(..)(conv_layer)
model2 = Model(inputs,feat_map2)
...
merged_feats = Merge([model1,model2],..)

**Comment by Mboga** [comment]
Thank you for the headstart, I will work on it.
