### ISSUE TITLE
doing attention visualization or class activation map for tex

### ISSUE THREAD

**Issue by wailoktam** [fchollet/keras#4695]
Hi, I find posts like this for image using cnn:

https://github.com/jacobgil/keras-cam
https://blog.keras.io/how-convolutional-neural-networks-see-the-world.html

Any idea on doing this for a LSTM network (a keras implementation of this document classifier(they call it QA but it is not)):

[https://arxiv.org/pdf/1602.03609v1.pdf]

If anyone knows any resources or has any idea, please let me know. I cannot find any open source code from people publishing pictures of highlighted text. 

Currently, the only thing I can think of is either replacing LSTM with CNN or stacking the LSTM with a CNN and adapt the image code. 

Many thanks in advance for any feedback

Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by philipperemy** [comment]
Have a look at this:

https://github.com/philipperemy/keras-simple-attention-mechanism
