### ISSUE TITLE
predict_generator throwing error continuously

### ISSUE THREAD

**Issue by kirk86** [fchollet/keras#4699]
Hi could someone possibly provide some hints on what exactly is going wrong with predict_generator method since fit.generator worked just fine.

Here's the code snippet and the error that I get:

```
> predictions = model.predict_generator(test_generator, nbr_test_samples)
(Pdb) n
Exception: Exceptio...one...',)
predictions = model.predict_generator(test_generator, nbr_test_samples)
(Pdb) Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/user/anaconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user/anaconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 433, in data_generator_task
    generator_output = next(generator)
  File "/home/user/anaconda2/lib/python2.7/site-packages/keras/preprocessing/image.py", line 596, in next
    index_array, current_index, current_batch_size = next(self.index_generator)
  File "/home/user/anaconda2/lib/python2.7/site-packages/keras/preprocessing/image.py", line 444, in _flow_index
    current_index = (self.batch_index * batch_size) % N
ZeroDivisionError: integer division or modulo by zero
```

Furthermore the directory that I'm providing as input to the ImageDataGenrator has 1000 images inside but when I run the code I get a message saying `Found 0 images in 0 classes`. I understand the `0 classes` part since I didn't specify any classes as argument to `ImageDataGenerator` since this is the test dataset. But, I don't understand the `Found 0 images`.

To me the message I would expect to see is`Found 1000 images in 0 classes`. Am I correct? or Am I missing something?

How can I overcome this error?

Thanks!

**Comment by fchollet** [comment]
Where is your reproducible code snippet? (should include some code to create a directory and populate it with fake images, e.g. like we do in the tests for this module).

**Comment by kirk86** [comment]
Apologize for that. Here I'll provide the reproducible code:

```
from keras.models import load_model
import os
from keras.preprocessing.image import ImageDataGenerator
import numpy as np


img_width = 299
img_height = 299
batch_size = 32
nbr_test_samples = 100
root_path = 'path/to/root/directory'
weights_path = os.path.join(root_path, 'weights.h5')
test_data_dir = os.path.join(root_path, 'test_directory')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        test_data_dir,
        target_size=(img_width, img_height),
        batch_size=batch_size,
        shuffle=False,
        classes=None,
        class_mode=None)

test_image_list = test_generator.filenames
model = load_model(weights_path)
predictions = model.predict_generator(test_generator, nbr_test_samples)

np.savetxt(os.path.join(root_path, 'predictions.txt'),  predictions)
```

**Comment by fchollet** [comment]
This is not reproducible since it assumes a specific directory with specific content, as well as a weights file.

**Comment by kirk86** [comment]
ok but that's exactly what I have. I have a pretrained model on which I only train the top layer to obtain the `weights.h5` file. Here I also use augmentation and `model.fit_generator` and it works fine without any problems. After the training finishes I try to do a predict using `model.predict_generator` as in the above text and then I always get errors. I've noticed that if I go until `test_generator = test_datagen.flow_from_directory(....`, then I get the message from `ImageDataGenerator` `Found 0 images with 0 classes`. Since I haven't specified any classes then that's expected but in `test_data_dir` argument given to `ImageDataGenerator` it points to a directory with 100 images but `ImageDataGenerator` still says `Found 0 images`. I don't understand why is that?

**Comment by fchollet** [comment]
I don't know what you issue is and I cannot investigate it unless you provide a reproducible code snippet. Reproducible means I should be able to run it and get the results as you do.

**Comment by kirk86** [comment]
@fchollet thanks for you patience. I just realized that I could use the `.predict` method but I had to create a subfolder inside my original folder of test images. For instance my original folder structure was:

```
test_folder
    |______image_1
    |______image_2
    |______image_3
    |______image_N
```

With the above folder structure whenever I was using the `imageDataGenerator` I was getting the message `Found 0 images in 0 classes`.

With the new folder structure

```
test/test_folder
           |______image_1
           |______image_2
           |_____image_3
           |______image_N
```

Now whenever I use the ImageDataGenerator I'm getting `Found x images in 1 classes`

I believe that's the correct behaviour if I'm not mistaken?

Now I'm testing the `.predict_generator` method for consistency and if I get the same results as with the `.predict` method then I'll close the issue.

**Comment by kirk86** [comment]
I'm closing this issue since both `.predict` and `.predict_generator` require the above folder structure in order to work. Let me know if there is anything wrong in my assumptions above. Thanks.

**Comment by anasb** [comment]
@kirk86 I've run into the same issue. Were you able to confirm that images with no classes (such as for test) need to be in a subfolder? I find it weird that it would say `Found x images in 1 classes`, since the class_mode is None.

**Comment by kirk86** [comment]
@anasb Yes it's true I've run my code that way and it works using a subfolder. I guess this might have to do with the way the `ImageGenerator` was developed. I'm not familiar with the intrinsic representation of it so that's a wild guess.

**Comment by ankitagarwal** [comment]
Isn't is because the generator you are passing to predict_generator is using augmentation ?

**Comment by atejeda** [comment]
[](https://keras.io/preprocessing/image/)
`flow_from_directory(directory)`
> Arguments:
>     directory: path to the target directory. It should contain one subdirectory per class. Any PNG, JPG, BMP or PPM images inside each of the subdirectories directory tree will be included in the generator. See this script for more details.

**Comment by kevinkit** [comment]
I was facing a similiar issue. When checking my dataset I was able to open all files, however in some cases the dpi information was missing in the jpeg-header, so PIL tries to read it from exif.


It then tries to calculate it - this is where the error may rises. 


So one should check if the all data can be read including the dpi information. Another way of finding corrputed files is to change `load_img` function in `keras.preprocessing` to print out the `path` variable. Thus, one can know the file name when the program crashes
