### ISSUE TITLE
What is the best way to implement a projection matrix + max pooling to represent a collection of regions in an image ?

### ISSUE THREAD

**Issue by rohit-gupta** [fchollet/keras#4706]
I am working on implementing **A Hierarchical Approach for Generating Descriptive Image Paragraphs**
by _Jonathan Krause et al_

![Model](http://i.imgur.com/7KQtSgx.png)

I am trying to figure out how to implement the projection and pooling layer to generate the vector which will be used just before the LSTM layers. The equation for the layer is:

![vp = max {i=1 to N} (Wpool . vi+bpool)](http://i.imgur.com/8OyvNge.png)

I was wondering what the ideal way of implementing this would be ?

**Comment by srigithub99** [comment]
Same question ?? still unanswered
