### ISSUE TITLE
Loading weights for initializer

### ISSUE THREAD

**Issue by pallonem** [fchollet/keras#471]
Hello.  I am new to Keras and Theano.  I apologize if this is a very basic question.  I want to load the initial network connection weights from a npy file.  Here are the relevant lines of my code:

```python
import numpy as np
from keras.utils.theano_utils import sharedX
weights = np.loadtxt(my_path).reshape((4,4))
model = Sequential()
model.add(Dense(4, 4, init=sharedX(weights)))
```

The error I get is: TypeError: 'TensorSharedVariable' object is not callable.  I am confused because the initializer functions I saw in the Keras code seemed to return shardX of a numpy array.  Could you please explain why I am getting this error and how to load weights from a file.

Thanks!

**Comment by wxs** [comment]
You need to pass a function that returns weights to the init function, I suppose you could do `init=lambda x: sharedX(weights)`, though you're probably better to just explicitly set the weights afterwards, like

    model.layers[0].W.set_value(sharedX(weights))

**Comment by fchollet** [comment]
The `init` argument expects an initialization function (see the doc: http://keras.io/initializations/)

What you are looking for the is `weights` argument: http://keras.io/layers/core/#dense

**Comment by alyato** [comment]
@wxs ,I also can't understand and read the link [http://keras.io/layers/core/#dense].It tells me the weight format but i also can't how to use. I just want to set the weight in conv layer.
![con](https://cloud.githubusercontent.com/assets/6815071/14785833/c01801c0-0ab9-11e6-8f3a-49d6b743d13d.png)
