### ISSUE TITLE
Euclidean loss / Sum of Squares activation in keras

### ISSUE THREAD

**Issue by idimitriadis** [fchollet/keras#4710]
Hello and congratulations for this active helping community...
I want to add an Euclidean loss layer that computes the sum of squares of differences of its two inputs at the end of my model... in other words i want to use euclideanloss as an activation function for my final Dense layer. Is this implementation for this activation function already available in Keras or do i need to write it by myself? 
I would be grateful if someone could provide me further information on this matter,
Thank you all for your time!

**Comment by kgrm** [comment]
Yes, this is actually very simple to do with the `Lambda` layer. Please refer to the following example.

https://gist.github.com/kgrm/e0741af9fda6ee7b04871d10f6a1d811
