### ISSUE TITLE
Please help me understand K.tile

### ISSUE THREAD

**Issue by aurora1625** [fchollet/keras#4719]
Hi

I am learning Keras, and I know K.tile is the backend of theano.tensor.tile, which can be traced back to numpy.tile. 

But they behave differently, could anyone help me to understand them?

```
import numpy as np
from keras import backend as K
import theano.tensor as T
w = np.array([0.1,0.3,0.5,0.2,0.6])

print np.tile(w,(3,1))
print T.tile(w,(3,1))
print type(K.tile(w,[3,1]))
print type(K.tile(w,[3,1]).eval())
```

The outputs are:

```
[[ 0.1  0.3  0.5  0.2  0.6]
 [ 0.1  0.3  0.5  0.2  0.6]
 [ 0.1  0.3  0.5  0.2  0.6]]
Reshape{2}.0
<class 'theano.tensor.var.TensorVariable'>
<type 'numpy.ndarray'>
```
So how come the `Reshape{2}.0` is a TensorVariable？And why not pass in the actual value like numpy does?

Thanks!

**Comment by EncodeTS** [comment]
You need to understand the **Graph Structures** in theano and tensorflow, before you run tensor.eval(), you can't get the value of it. It behave like this in order to do a lot optimizations.
