### ISSUE TITLE
Keras runs LSTM very slow using theano backends

### ISSUE THREAD

**Issue by Jimmy-jin** [fchollet/keras#4721]
I am running the Keras example code,  imdb_lstm.py. But it is time consuming, nearly 2000 second a epoch, (I saw others only 20second using Titans)I use the TitanX gpu, and set theano_flag=gpu,  but When I run imdb_cnn.py, it's fast ,have anyone known  this problem?

**Comment by ankeshanand** [comment]
Can you try re-running the script with the following theano flags?

`THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python imdb_cnn.py`

**Comment by Jimmy-jin** [comment]
Thank you for the advice , actually I had written `THEANO_FLAGS=mode=FAST_RUN` in the theanorc configuration file. I think the problem is related with *cpu* occupation ratio, because I use the lab common server, when the server is not busy in the night, it needs only 100 second to run a epoch.

**Comment by ankeshanand** [comment]
Cool, you can close the issue if that's the case.
