### ISSUE TITLE
K.switch works with Theano backend but not Tensorflow

### ISSUE THREAD

**Issue by fferroni** [fchollet/keras#4725]
Hello,

I am implementing a layer in Keras. It is working for Theano but when I test it with a Tensorflow backend, it breaks on the following line:

`k = K.switch(is_up, phi/on_mid, K.switch(is_down, (on_end-phi)/on_mid, off_slope*phi))`

The line is part of a` def step() `function of a layer inheriting from the `Recurrent` class.

The error is:
```
/Users/Francesco/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.pyc in _call_cpp_shape_fn_impl(op, input_tensors_needed, input_tensors_as_shapes_needed, debug_python_shape_fn, require_shape_fn)
    673       missing_shape_fn = True
    674     else:
--> 675       raise ValueError(err.message)
    676 
    677   if missing_shape_fn:

ValueError: Shape must be rank 0 but is rank 2 for 'while_2/cond/Switch' (op: 'Switch') with input shapes: [?,10], [?,10].
```

Any ideas? I am not very familiar with Tensorflow.

Best,
Francesco

**Comment by gvtulder** [comment]
Just a guess: what are the shapes of `is_up` and `is_down`? In Theano they can be tensors of the same shape as the other variables, but TensorFlow requires them to be scalar variables. This may be related to #4519.

**Comment by fferroni** [comment]
Hi,

Yes indeed. The `is_up` and `is_down` are tensors of the same shape.

Judging from the related issue you attached, it does seem like K.switch for Tensorflow and Theano are quite different... would be nice to homogenise. The fact that K.switch in Tensorflow can only accept scalars is a bit limiting.

Best,
Francesco
