### ISSUE TITLE
How can i visualize feature map of 1D CNN?

### ISSUE THREAD

**Issue by csh412** [fchollet/keras#4729]
Hi, I'm training 1D data using 1D CNN.

I'd like to visualize feature map

I found visualizing 2D CNN feature map code... but I can't find any code which applied to 1D CNN model

Is there any solution to visualize 1D CNN feature map?

Please help me...

Thanks a lot

**Comment by keunwoochoi** [comment]
What's the problem exactly? If you understand 2d feature map visualisation it's trivial to do it with 1d feature maps.

**Comment by PPACI** [comment]
i **did not** tried it but take a look at [quiver](https://github.com/jakebian/quiver), it should let you do easily what you want.

**Comment by csh412** [comment]
@keunwoochoi Hi, I have implemented the code by referring to the site below.
https://gist.github.com/hadim/9fedb72b54eb3bc453362274cd347a6a
https://blog.keras.io/how-convolutional-neural-networks-see-the-world.html
How do I change the code to look 1d feature map? I'm a beginner of python language... please help me.. Thank you

@PPACI  Hi, thanks a lot. I'll look at quiver
