### ISSUE TITLE
Error when extracting features with VGG16

### ISSUE THREAD

**Issue by zaoyehuo** [fchollet/keras#4730]
Please make sure that the boxes below are checked before you submit your issue. Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Just the example on https://keras.io/applications/
Extract features with VGG16

from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np

model = VGG16(weights='imagenet', include_top=False)

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

features = model.predict(x)

Then I got:
Using gpu device 0: GeForce GTX 1060 3GB (CNMeM is disabled, cuDNN 5005)
ERROR (theano.gof.opt): Optimization failure due to: local_abstractconv_check
ERROR (theano.gof.opt): node: AbstractConv2d{border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(64, 3, 3, 3)}(input_2, block1_conv1_W)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\theano\gof\opt.py", line 1772, in process_node
    replacements = lopt.transform(node)
  File "D:\Anaconda\lib\site-packages\theano\tensor\nnet\opt.py", line 402, in local_abstractconv_check
    node.op.__class__.__name__)
AssertionError: AbstractConv2d Theano optimization failed: there is no implementation available supporting the requested options. Did you exclude both "conv_dnn" and "conv_gemm" from the optimizer? If on GPU, is cuDNN available and does the GPU support it? If on CPU, do you have a BLAS library installed Theano can link against?

It's strange because I can run it without error several days ago.I don't know what happend to my keras.
Thank You.

**Comment by superhans** [comment]
It's a bit hard for me to explain without knowing all details, but this might be a problem of exporting the requisite paths. I strongly believe that while CUDNN paths are correct, BLAS paths are not. Since you said you ran it a few days ago, perhaps you updated scipy or numpy which over-wrote BLAS installations.

My python-script would be wrapped inside a shell script, which would look like this : 

```
#!/bin/bash                                                                                                                              
                                                                                                                              
export PATH=/usr/local/cuda-8.0/bin/:$PATH                                                  
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64/:/homes/superhans/UBUNTU_PANDORA/Softwares/cuda/lib64/:$LD_LIBRARY_PATH                
export LIBRARY_PATH=/homes/superhans/UBUNTU_PANDORA/Softwares/cuda/:/homes/superhans/UBUNTU_PANDORA/Softwares/cuda/lib64/:$LIBRARY_PATH # required for CUDNN
export CPATH=/homes/superhans/UBUNTU_PANDORA/Softwares/cuda/include:$CPATH # required for CUDNN                                                        
export PYTHONPATH=/usr/local/lib/python2.7/dist-packages/:$PYTHONPATH                                                                    
                                                                                                                                         
program=$1                                                                                                                               
gpuid=$2                                  
                                                                                               
export THEANO_FLAGS="device=gpu${gpuid},nvcc.fastmath=True,floatX=float32,optimizer_including=cudnn"                                     
                                                                                                                                         
python $1
```

**Comment by zaoyehuo** [comment]
@superhans 
Thank You!
It's OK now
