### ISSUE TITLE
Vgg16 example: Layer weight shape not compatible with provided weight shape

### ISSUE THREAD

**Issue by jeffreynghm** [fchollet/keras#4738]
This is the error and it seems that the layer shape shown in the example is not the same as the 'vgg16_weights.h5' downloaded. 

**Here is the error message:**
Traceback (most recent call last):
<module>
    model.layers[k].set_weights(weights)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/topology.py", line 889, in set_weights
    'provided weight shape ' + str(w.shape))
Exception: Layer weight shape (3, 3, 128, 64) not compatible with provided weight shape (64, 3, 3, 3)

**System configuration:**
Running vgg16 example on ubuntu 14.04, python 3.4
Using TensorFlow backend

**Comment by fchollet** [comment]
Are you using `keras.applications.VGG16`? That's what you should be using.

**Comment by jeffreynghm** [comment]
thanks, i was following:
https://blog.keras.io/how-convolutional-neural-networks-see-the-world.html
thus using:
https://github.com/fchollet/keras/blob/master/examples/
conv_filter_visualization.py

**Comment by jeffreynghm** [comment]
changed to vgg16 under applications. no problem now.

**Comment by sajjo79** [comment]
@jeffreynghm 
How did u corrected this error? The explanation given here not clear to me.

**Comment by jeffreynghm** [comment]
@sajjo79 , look for file under a different directory. e.g. for my case it is under /usr/local/lib/python 3.5/dist-packages/keras/applications/
