### ISSUE TITLE
Feeding sequence of sequences as a single input

### ISSUE THREAD

**Issue by Nilabhra** [fchollet/keras#4751]
I am trying to implement key-value memory networks in Keras. This requires me to feed in mainly two types of sequences:

1. A question sequence, which is nothing but a sequence of word embedding indices of the shape: (n_batch_samples, max_question_len)

2. The key sequences, each being a sequence of sequences of word embedding indices of shape: (n_batch_samples, max_num_key, max_key_len)

Each question has some associated keys. There are other inputs too, but they will have a dimension similar to that of candidate sequences.

My question is: What is the proper way to feed in the sequences? Also, is there a way to feed in variable number of candidate sequences along with the question sequence?

I have tried this:
```python
question_encoding = Sequential()
question_encoding.add(A)
question_encoding.add(Dropout(0.3))
question_encoding.add(LSTM(output_dim=64))

key_encoding = Sequential()
key_encoding.add(TimeDistributed(A, batch_input_shape=(None, max_num_keys, max_key_len)))
key_encoding.add(TimeDistributed(Dropout(0.3)))
key_encoding.add(TimeDistributed(LSTM(output_dim=64), input_shape=(max_num_keys, max_key_len, A.output_dim)))
```
Here A is an embedding and the number of key sequences per question is fixed and I can't seem to obtain a pairwise dot product among the two layers with Merge().

Would really appreciate any pointers or insights. Thanks!
Please make sure that the boxes below are checked before you submit your issue. Thank you!
- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Nilabhra** [comment]
I was able to perform the dot product by using a couple of Reshape's. Closing the issue since I guess there is no way to define operations on arbitrary length 2D sequences.

**Comment by LukeB42** [comment]
Nilabhra would you mind sharing your model or some tips on how to implement a K/V memory net in Keras?
