### ISSUE TITLE
Vector matrix dot product is inconsistient between backends

### ISSUE THREAD

**Issue by JosephDavidsonKSWH** [fchollet/keras#4758]
Using K.dot(a,b) in the tensorflow backend to compute a vector/matrix dot product crashes because of different dims. The same calculation in the theano backend is correctly computed.

Similarly, matrix/vector and vector/vector products fail

[Gist](https://gist.github.com/JosephDavidsonKSWH/1404e5ea0886a442c2982fae70a4a243)

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

**Comment by Dref360** [comment]
This is because TF backend is using matmul which is only for Tensors of same shape.

tf.mul would do the vector x matrix. 

Maybe just add if a.get_shape() == b.get_shape(): matmul else mul ?

**Comment by JosephDavidsonKSWH** [comment]
Not sure it's as simple as that. tf.mul(a, b) will only work if the final dimensions are the same.
The replacing K.dot(...) in the above gist with a tf.mul still crashes.

I have a fairly inelegant workaround which expands and squeezes tensors in the appropriate dimension if there is a difference of 1 between the dims. It replicates the dot functionality which I am looking for, but probably won't work so well for larger tensors with dims > 2.

```python
def tf_dotproduct(x, y):
        expandx = False
        expandy = False
        dy = K.ndim(y)
        dx = K.ndim(x)
        if dy > 1 or dx > 1:
            if dx == dy - 1:
                # Expand x at dim 0
                xt = K.expand_dims(x, 0)
                expandx = True
            else:
                xt = x
            if dy == dx - 1:
                # expand at dim n
                yt = K.expand_dims(y, dy)
                expandy = True
            else:
                yt = y
            res = K.dot(xt, yt)
            if expandx:
                res = K.squeeze(res, 0)
            if expandy:
                res = K.squeeze(res, dy)
        else:
            res = K.tf.reduce_sum(K.tf.mul(x, y))
        return res
```
