### ISSUE TITLE
Why is nb_worker forced to 1 when pickle_safe == False?

### ISSUE THREAD

**Issue by landersson** [fchollet/keras#4763]
I want to use multiple worker threads (as opposed to worker processes) when training using fit_generator(). I've got a fast GPU, my model is quick to train and I use some fairly expensive data augmentation, so I need 4-6 worker threads in order for them to keep up with the GPU. 

Using processes instead of threads is not a good option because even pickling/unpickling my data batches adds too much CPU overhead. So I set nb_worker=6 and pickle_safe=False, and run into the warning on line 894 in models.py:

https://github.com/fchollet/keras/blob/master/keras/models.py#L893

What is the reason for forcing nb_worker to be 1 when pickle_safe = False? I've tried commenting that whole check out and everything seems to run fine.

**Comment by patyork** [comment]
Threads do not lead to performance improvement for CPU-bound processing due to the python GIL - [here ](http://python-notes.curiousefficiency.org/en/latest/python3/multicore_python.html) is a pretty good explanation. Therefore, using processes is necessary, which generally requires picklable objects (thus the `pickle_safe` flag) allowing each spawned process to pickle/unpickle copies of the data.

**Comment by landersson** [comment]
My understanding is that when you call code in an external C/C++ library (using ctypes, boost-python or similar) the wrapper code will usually release the GIL, and other python threads can make progress. I'm using OpenCV and PIL (Pillow) for much of my data preparation, which is mostly external C/C++ code. 
Also, the GIL should also be released when blocking on IO, which is also a non-negligible part of my data prep delay.

In practice, I certainly see a significant reduction in data preparation delay when increasing the number of worker threads.

**Comment by patyork** [comment]
That may or may not be true, and regardless, Keras makes no assumption that your data generator will be written in such a way as to release the GIL and as a high level library simply balances Threads vs Processes [via the pickle_safe](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L397) flag and makes the safer assumption that the processing will be CPU bound and thus spawn only 1 thread.

If this does not suit your needs, you can go the easy (and dependable) route of spawning a processes using picklable data (such as strings of filepaths/URLs) which in turn spawns N threads that block for IO and continue processing afterwards; or you can modify the Keras code to skip that check (which would work, and spawn `nb_workers` threads, but you couldn't know that for sure without reading through the above source code).

**Comment by landersson** [comment]
For me, just unpickling a batch in the main thread takes nearly as long as actually training it on the GPU, which thus makes the whole training run twice as slow as it could, if the GPU didn't have to wait for the CPU on unpickle the next batch.

My solution so far has been the last option you mentioned, i.e simply commenting out the relevant lines in model.py... I guess what I was hoping for would be some way some way to achieve this without having to modify keras (which makes sharing example code etc with people who just want to use standard keras harder).

One option would be to add another parameter to fit_generator() to explicitly specify what type of workers to use, i.e

worker_type="thread", "process" or "auto",

where "auto" is the default and keeps the current behaviour, and selecting pickle_safe=False and worker_type="process" will cause a runtime error.

**Comment by patyork** [comment]
Just to add a thought from your first sentence: you might try to increase the `max_q_size` setting to be at least 2 * `nb_workers` -- if the unpickling takes less time, even slightly less time, with an available queue and data available to unpickle and feed into the queue, the queue should fill up and stay filled up enough to saturate the GPU. This of course relies on the fact that unpickling takes just a little less time than running on the GPU. Setting the `max_q_size` as I said above should ensure that the Keras backend never "waits" to ask the generator to start processing a new batch because the queue is full, or not empty enough.

You could of course make that change in your Keras fork and submit a PR, referencing this issue, and perhaps get a wider opinion, or some reasons why it was written this particular way.

I'll need to think a bit more - yours seems to be an interesting case of both IO blocking, large CPU usage in preprocessing, and large datasets during (un)pickling. In other words, kind of a worst-case scenario.

**Comment by landersson** [comment]
Not sure I follow your suggestion, but as far as I can tell, unpickling a batch in the main thread is not asynchronous to training the batch on the GPU. The main loop of fit_generator() goes something like this:
```
while (samples_seen < samples_per_epoch):
    1) fetch and unpickle next batch from "data_gen_queue"
    2) launch training on new batch on GPU
    3) sync with GPU, print batch statistics
```

So, in my case, step 1 takes about 0.4 secs (of which unpickling is the main part, assuming the queue is not empty) and step 2 takes about the same. This is why pickling/unpickling is not a good option for me, because unpickling takes about the same amount of time as training, and will thus slow me down by a factor of two. 

I just realised that doing the unpickling of the next batch while the GPU is working on the current batch might be a solution, i.e changing the loop above to something like:
```
current_batch = fetch_and_unpickle_next_batch()
while (samples_seen < samples_per_epoch):
    1) launch GPU training on "current_batch"
    2) next_batch = fetch_and_unpickle_next_batch()  # this will hopefully run async with GPU training
    3) sync with GPU, print batch statistics
    4) current_batch = next_batch
```
Does that make sense?

Btw, IO blocking is not a large factor in my case, I'm fetching data from a fast SSD. The main reason I'm running into these performance issues is that my model is small and unusually fast to train.

**Comment by patyork** [comment]
"unpickling of the next batch while the GPU is working on the current batch" is exactly what i was trying to ensure above. I'm not 100% on the internals, but with nb_workers > 1, the main thread should constantly be unpickling data as the workers send it new batches, until it has `max_q_size` batches unpickled. But, if the max_q_size is too small, the workers will (all?) remain un-queried until a slot in the queue opens up and is available to fill. It was just a thought that setting the queue size to be at least 2x the number of workers may force the main thread to be constantly unpickling, and the worker threads constantly working, to the point that the GPU will remain saturated.

Essentially, if unpickling is at all faster than the GPU training, it should be possible to load the queue to the point that the GPU is always saturated, even if it will take a few iterations to get to that point.

**Comment by landersson** [comment]
Looking at the code for fit_generator() in engine/training.py, what it actually does is more along the lines of my first snippet above, i.e only one batch is unpickled at a time, and it is not done asynchronously to GPU training.

**Comment by patyork** [comment]
I'd disagree. I'd never thought about it before, but the Multiprocessing module looks like it unpickles the data when/before it sends it back to the thread, itself. Meaning the unpickling should be async from the main thread. Keras [does nothing](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1471) in terms of unpickling the data before [using it as a tuple](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1476).

**Comment by landersson** [comment]
Ok, I didn't know multiprocessing.Queue unpickled data automatically in the background without explicitly calling q.get(). Maybe the reason why I still have to wait for data is that all my CPU cores were busy with data augmentation and thus slowed down any automatic background unpickling.

**Comment by patyork** [comment]
I edited my comment. .get() does start the unpickling, unfortunately.

-----Original Message-----

**Comment by landersson** [comment]
I just ran a small standalone test. Calling q.get() to fetch (and I assume, unpickle) a [128,3,224,224] numpy float array (72Mb) takes about 0.25 seconds on an otherwise mostly idle machine. The fact that it takes nearly 0.4 seconds while training is mostly likely because all CPU cores were also busy doing data augmentation.

I guess one solution would be to rewrite the while loop in fit_generator() to work more like my second psudo-code while loop above in order to try and overlap GPU training with CPU unpickling. I could send a PR if there's a general consensus that it would be worthwhile.

Anyway, I guess my situation is a bit of a special case and most people's models don't train that quick (less than 0.4 seconds on a [128,3,224,224] batch on a GTX 1080).
