### ISSUE TITLE
How can I create a variable with shape (None, 1) ?

### ISSUE THREAD

**Issue by dontloo** [fchollet/keras#4767]
My problem is, I'm writing a layer with input shape (None, 10), and I want to append the same value to the end of every row to make it (None, 11). How can I do this? 

Right now I'm thinking of creating another (None, 1), then concatenating them.

Thanks in advance.

**Comment by tiagocalumbi** [comment]
@dontloo try to do this it. I think must solve
 img = img.reshape((1,) + img.shape)

**Comment by fchollet** [comment]
> Right now I'm thinking of creating another (None, 1), then concatenating them.

If you have 2 separate inputs (10-dimensional vectors and single scalars) then the right approach is to create an input of shape (None, 10) and another one of shape (None, 1) and concatenate them.

Then again you could also create an input of shape (None, 11) and feed it the appropriate data.

**Comment by dontloo** [comment]
@fchollet Thanks for the reply. But actually I want to make it as a trainable parameter (instead of an input) and add it to the end of every input vector, I didn't find a simple way to do this.

Say I want to add a value `b` to the end of every row of `x`, right now what I'm doing is like 

```python
self.b = self.init((1,))  # trainable parameter
...
# this is what I did to make b of shape (None, 1)
b_vec = K.expand_dims(0*K.sum(x, axis=1), 1) + self.b
K.concatenate([x, b_vec], axis=-1)
```

so I was wondering if there's a simpler way?

**Comment by fchollet** [comment]
If you need to add trainable weights, you must write a custom layer.

**Comment by dontloo** [comment]
@fchollet yes, my problem is, in the layer I wrote, I'm not able to create a trainable weight of shape (None, 1). The way I worked around this is first squeezing the input into some shape I want, then multiplying them all by zeros and adding my parameter to it like
```python
# this is what I did to make b of shape (None, 1)
b_vec = K.expand_dims(0*K.sum(x, axis=1), 1) + self.b

```
