### ISSUE TITLE
load and save error from different keras version 1.1.2 and 1.2

### ISSUE THREAD

**Issue by lampts** [fchollet/keras#4774]
I have 2 keras instances: GPU keras v1.1.2, CPU keras. v1.2, after training on GPU instance, I serialised models (2 ways: 1 h5 file, or weights and config separately). However I could not load them in CPU instance version 1.2, 1.1 except the same version 1.1.2.

Logs:

CPU instance:

Keras v 1.2

../lib/python2.7/site-packages/keras/engine/topology.pyc in load_weights_from_hdf5_group(self, f)
   2751                                  'containing ' + str(len(layer_names)) +
   2752                                  ' layers into a model with ' +
-> 2753                                  str(len(flattened_layers)) + ' layers.')
   2754 
   2755             # We batch weight value assignments in a single backend call

ValueError: You are trying to load a weight file containing 7 layers into a model with 6 layers.

Keras v 1.1 model

lib/python2.7/site-packages/keras/engine/topology.pyc in from_config(cls, config)
   1465             output_shape = config['output_shape']
   1466 
-> 1467         output_mask_type = config.pop('output_mask_type')
   1468         if output_mask_type == 'function':
   1469             output_mask = globals()[config['output_mask']]

KeyError: 'output_mask_type'

**Comment by lukemurray** [comment]
Also getting this
