### ISSUE TITLE
How could i predict a layer's weights using the output of another network in an end to end way?

### ISSUE THREAD

**Issue by Bassel1** [fchollet/keras#4789]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

i am trying to reproduce the work in this paper https://arxiv.org/pdf/1511.05756v1.pdf
where they predict the weights of 1 layer in a network using a another parameter prediction network.
can anyone tell me how can i do that?

**Comment by bstriner** [comment]
Build your first network that creates a weight matrix and bias vector for each layer for each sample in the batch. Make sure to reshape the weight and bias to the right shape.

Your second network will be a series of merge layers using batch_dot, which will perform a matrix dot for each sample. 

Something like this. Note the output shape of the merge is the same as the shape of the bias layer.

```
x = ...
# networks for W and b
h = Dense(100)(x)
# W = (n, 10, 10)
W = Reshape(10,10)(Dense(100)(h))
# b = (n, 10)
b = Dense(10)(h)
# merge output = (n, 10)
output = merge([x,W,b], mode=lambda z: K.batch_dot(z[0], z[1])+z[2], output_shape=lambda z: z[2])
```

If you're doing convolutional weight prediction, I don't think there is a batched_convolution in the Keras backend. You can build it using scan and T.nnet.conv2d which wouldn't be too hard but would be specific to the backend you're using.

Cheers,
Ben

**Comment by Bassel1** [comment]
thank you really so much for that
