### ISSUE TITLE
IMDB bidirectional lstm example. Is it correct?

### ISSUE THREAD

**Issue by singlasahil14** [fchollet/keras#4791]
https://github.com/fchollet/keras/blob/master/examples/imdb_bidirectional_lstm.py

In this example, the last sequence of the bidirectional LSTM will be used by the next layer right?

The last sequence of the bidirectional LSTM will be just the last sequence of the forward LSTM, concatenated with the first sequence of the backward LSTM, right?
How is it different from a unidirectional LSTM where also only the last layer will be taken?

**Comment by Shuailong** [comment]
It matters when the order of the sequence is important. Sometimes you have more information when you read a sequence backwards. Now you can use the BiLSTM to combine this information. Does this answer your question?

**Comment by singlasahil14** [comment]
If we are taking just the last sequence of a bidirectional LSTM, is it not equivalent to taking the last sequence of a forward LSTM? Because the last sequence of a bidirectional LSTM will just be last sequence of the forward LSTM and the first sequence of the backward LSTM (which hasn't seen any input).

**Comment by patyork** [comment]
They are not equivalent, as at `t0`, the backwards RNN layer will have input `Input[t0]` + `initialization data`. Whether this is useful is another question.

**Comment by singlasahil14** [comment]
Ya exactly. I meant in that sense only. The forward LSTM has seen the last input already right? I wonder whether adding a backward LSTM will make any difference.

**Comment by patyork** [comment]
I doubt it, for this problem as written - as you say, the backward pass will only output one used/usable value in this case; one value that utilizes only one input and the initialization data. The Initialization data, though, may be stateful (if it's a stateful RNN) and provide some useful information from the previous data. This is fairly doubtful though.

Important to note that if there was another RNN layer of any kind after the BRNN, this would not be the case. Or, if this was more than a classification problem and `return_sequences` was set to `True`.
