### ISSUE TITLE
Saving a model with frozen layers?

### ISSUE THREAD

**Issue by hhkarimi** [fchollet/keras#4792]
It appears there is an issue with saving models after freezing layers when fine-tuning.  Following the fine-tuning example of InceptionV3 (https://keras.io/applications/#inceptionv3)  I saved and attempted to load the mode (https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model):

```
from keras.models import load_model
InceptionV3_model.save('inception_model.h5')
model2 = load_model('inception_model.h5')
```

Doing so, however, returns a ValueError:
`ValueError: You are trying to load a weight file containing 191 layers into a model with 39 layers.`

It turns out that when you freeze the layers, they don't get saved.  I tried unfreezing the layers, and saving the model then, but then are incompatibilities with the optimizer weight shape.

**Comment by fchollet** [comment]
This is fixed, thanks for the report.

**Comment by kampta** [comment]
@fchollet @hhkarimi in which version/commit was this bug fixed? Getting same for ```keras 1.2.0 ``` (current github version).
Thanks

**Comment by hhkarimi** [comment]
It was just after 1.2.0, it's not available on pypi yet.  To get the latest version from github:
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`

**Comment by kampta** [comment]
Thanks @hhkarimi
