### ISSUE TITLE
Source-built TF version

### ISSUE THREAD

**Issue by goodyttoor** [fchollet/keras#4794]
When built Tensorflow from source, the version appears as "0.12.head".  This will fail various test conditions:

https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L526
https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L531
https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L541

Can I modified these lines to 
`if parse_version(tf.__version__.rpartition('.')[0]) >= parse_version('0.12.0')` 

or possibly something in the more elegant way? Thank you.

**Comment by joggino** [comment]
Works well for me, you will also need to alter the summaries like so:
`if parse_version(tf.__version__.rpartition('.')[0]) >= parse_version('0.12.0'):
    tf.summary.image(weight.name, w_img)
else:
    tf.image_summary(weight.name, w_img)`
