### ISSUE TITLE
Dense or TimeDistributedDense for lstm_text_generation.py example??

### ISSUE THREAD

**Issue by hugman** [fchollet/keras#480]
Dear all,

I just found good LSTM example (keras)- https://github.com/fchollet/keras/blob/master/examples/lstm_text_generation.py

In the code, author used 'Dense' layer for fully connection LSTM layers.
I wonder why not used 'TimeDistributedDense' instead of 'Dense'?

any idea?

**Comment by fchollet** [comment]
The last LSTM layer does not return a sequence, but a single vector (`return_sequences=False`). Hence `Dense` instead of `TimeDistributedDense`.
