### ISSUE TITLE
Breaking changes with TF version 0.12 that affects Keras

### ISSUE THREAD

**Issue by pifelbo** [fchollet/keras#4805]
The latest version of TF has some breaking changes that affects Keras. See description [here](https://github.com/tensorflow/tensorflow/releases). Below are some issues I've found and quick fixes.

**AttributeError: 'module' object has no attribute 'select'**

> Add the following before importing Keras:
> ```
> import tensorflow as tf
> tf.select = tf.where
> ```
> 

**TypeError: unsupported operand type(s) for : 'IndexedSlices' and 'int'**

> Turn off clipnorm in the optimizer. I'll look into how this can actually be fixed when I have time.

I'll add more as I find them. Of course, these issues have to be fixed in the backend code. These quick fixes are just for anyone needing to get their code running.

**Comment by ahundt** [comment]
@pifelbo close this as per #4815?
