### ISSUE TITLE
SimpleRNN : Hidden and output units of different dimensions

### ISSUE THREAD

**Issue by antoinux** [fchollet/keras#4822]
Hi Keras,

Thank you for this project!

It seems that you can't make the hidden unit and the output units of a SimpleRNN layer have différent values.

The doc says in the argument part :

"output_dim: dimension of the internal projections and final output."

It seems unclear to me what are "internal projections". Anyway there's only one argument of this type so it's clear you can't set the hidden state dimension as you want.

Is it wanted? What if I want a big hidden state yo remember a lot of information but a unidimensionnal output?

Merry Christmas :)

**Comment by patyork** [comment]
A SimpleRNN layer is just plain vanilla RNN, where the layer has `output_dim` neurons. This means that the layer will output `output_dim` values to the next layer, and also to the subsequent step in time. In essence, a SimpleRNN layer will take `input_dim + output_dim` inputs (the input at time `t` and the output from the layer at time `t-1`) and output `output_dim` values.

"Internal Projections" essentially means the number of neurons. The phrasing comes from the fact that, with N neurons in a layer, the data is being "compressed" into N dimensions; compressing something from M dimensions into N is a "projection".

**Comment by antoinux** [comment]
Hi patyork thanks for this answer !

Ok I think I understood what goes on behind the scenes... I was influenced by the litterature I read to think a RNN layer always has two distinct hidden unit and output unit, I think I'll have to add a Dense layer to the network to get what I want.

It may be possible to make this part of the doc more clear with a drawing, since RNNs are not the simplest things to understand for newcomers in my opinion.

Thanks again :)

**Comment by 3dozens** [comment]
Hi, I have a relevant question. 

In the document, not only SimpleRNN but also LSTM or GRU has only the argument `units: Positive integer, dimensionality of the output space.` and there is no argument about hidden state size.

LSTM or GRU also has no hidden unit and its output fed into next time step?
