### ISSUE TITLE
Issue when using TensorFlow backend with GPU.

### ISSUE THREAD

**Issue by sixsamuraisoldier** [fchollet/keras#4830]
Hey there, I am having a problem when using the TensorFlow backend with my GPU.
It starts to train, but my GPU utilization from nvidia-smi shows that there is almost no utilization yet nvcc-version still gives the correct response.
And I've also installed nvidia-modprobe

Output of nvidia-smi:
Sat Dec 24 21:08:00 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.20                 Driver Version: 375.20                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    On   | 0000:03:00.0     Off |                  N/A |
| 23%   33C    P8    10W / 250W |    160MiB / 12221MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    On   | 0000:04:00.0      On |                  N/A |
| 23%   41C    P8    11W / 250W |    968MiB / 12218MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0       991    C   /usr/bin/python                                149MiB |
|    1      1421    G   /usr/bin/X                                     580MiB |
|    1      2336    G   compiz                                         152MiB |
|    1      2746    G   /opt/g                                         189MiB |
|    1     25069    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    34MiB |
+-----------------------------------------------------------------------------

Output of nvcc --version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Wed_May__4_21:01:56_CDT_2016
Cuda compilation tools, release 8.0, V8.0.26

When I run the keras model, I get this as an output:
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Couldn't import dot_parser, loading of dot files will not be possible.
X_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples
Using real-time data augmentation.
Epoch 1/200
E tensorflow/stream_executor/cuda/cuda_driver.cc:509] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: Tesseract
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: Tesseract
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 375.20.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.20  Tue Nov 15 16:49:10 PST 2016
GCC version:  gcc version 4.8.5 (Ubuntu 4.8.5-2ubuntu1~14.04.1) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 375.20.0
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 375.20.0

Thanks in advance, any help would be much appreciated!

**Comment by patyork** [comment]
This is not a Keras issue. But,

Try to run `sudo apt-get install nvidia-modprobe` again. Apparently that fixes your issues, according to [google](https://github.com/tensorflow/tensorflow/issues/394).

**Comment by sixsamuraisoldier** [comment]
Hey pat, thanks for the reply. I didn't mean to annoy anyone by posting it here. Anyways, I did google it before, but it didn't help :(
Any other options?
Thanks for the reply btw :)

**Comment by patyork** [comment]
Running `sudo apt-get install nvidia-modprobe` after the error occurs seems to help a lot of people, did you do that?

**Comment by sixsamuraisoldier** [comment]
Hey pat, yes I did, still no dice :(
Curiously,it ran fine before on the gpu.

**Comment by patyork** [comment]
In the [TensorFlow thread I referenced](https://github.com/tensorflow/tensorflow/issues/394#issuecomment-165034780), someone had the same experience of it running fine, and then suddenly getting this error. I'd recommend starting there and working your way down the thread applying the things they say. It seems to have resolved it for everyone.

**Comment by sixsamuraisoldier** [comment]
@patyork Thanks for the reference. I don't see anything in the thread other than trying sudo apt-get install nvidia-modprobe. Is there something else in the thread I'm missing? The install nvidia-modprobe doesn't fix it for me btw.

**Comment by nitish11** [comment]
I am facing the similar issue. I think GPU is not being used when we use tensorflow as backend. I there any test_code to check this.

**Comment by sixsamuraisoldier** [comment]
Hi okay, so I reinstalled CUDA, TensorFlow and Keras, and now it runs fine, but it straight up ignores the GPU despite using the TensorFlow backend.

**Comment by nitish11** [comment]
@sixsamuraisoldier : How did you install tensorflow??
Follow Installation from [source](https://www.tensorflow.org/get_started/os_setup#installing_from_sources
) . Setup GPU support in this [step](https://www.tensorflow.org/get_started/os_setup#configure_the_installation).

**Comment by sixsamuraisoldier** [comment]
@nitish11 I used "pip install tensorflow"

I can try installing from source, but I doubt that's the problem since it was working fine before by installing through "pip install tensorflow".

**Comment by nicbou** [comment]
Did you ever find a solution, @sixsamuraisoldier ?
