### ISSUE TITLE
RNN/LSTM/GRU input order

### ISSUE THREAD

**Issue by nehz** [fchollet/keras#484]
Sorry couldn't find this in docs anywhere, but just want to double check the order of inputs fed into RNNs:

    x[0] = oldest input
    x[n] = latest input

or:

    x[0] = newest input
    x[n] = oldest input

**Comment by fchollet** [comment]
```
x[0] = oldest input
x[n] = latest input
```

**Comment by nehz** [comment]
Cool thanks !
