### ISSUE TITLE
Example for using Keras backend and optimizers

### ISSUE THREAD

**Issue by bstriner** [fchollet/keras#4843]
Hello everybody,

Everything is easier working within the box, but I sometimes have to use Keras components outside of Keras. There are a lot of questions out there about how to use various components, so I put together this example showing how to use Keras backend, optimizers, etc. in your own code. Should teach you the basics of creating variables and placeholders and creating updates using the optimizer API.

Just putting this out there in case anyone finds it useful. I can add some documentation and submit a PR if this seems helpful.

Cheers,
Ben

https://gist.github.com/bstriner/e1e011652b297d13b3ac3f99fd11b2bc

```
from keras.optimizers import Adam
from keras import backend as K
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical
from keras.metrics import categorical_accuracy
from keras.initializations import glorot_uniform, zero
import numpy as np

# inputs and targets are placeholders
input_dim = 28*28
output_dim = 10
x = K.placeholder(name="x", shape=(None, input_dim))
ytrue = K.placeholder(name="y", shape=(None, output_dim))

# model parameters are variables
hidden_dim = 128
W1 = glorot_uniform((input_dim,hidden_dim))
b1 = zero((hidden_dim,))
W2 = glorot_uniform((hidden_dim,output_dim))
b2 = zero((output_dim,))
params = [W1, b1, W2, b2]

# two-layer model
hidden = K.sigmoid(K.dot(x, W1)+b1)
ypred = K.softmax(K.dot(hidden,W2)+b2)

# categorical cross entropy loss
loss = K.mean(K.categorical_crossentropy(ytrue, ypred),axis=None)

# categorical accuracy
accuracy = categorical_accuracy(ytrue, ypred)

# Train function
opt = Adam()
updates = opt.get_updates(params, [], loss)
train = K.function([x, ytrue],[loss, accuracy],updates=updates)

# Test function
test = K.function([x, ytrue], [loss, accuracy])

# Train the network
((xtrain, ytrain),(xtest, ytest)) = mnist.load_data()
(xtrain, xtest) = [x.reshape((-1, input_dim))/255.0 for x in (xtrain, xtest)]
(ytrain, ytest) = [to_categorical(y, output_dim) for y in (ytrain, ytest)]
for epoch in range(1000):
	loss, accuracy = train([xtrain, ytrain])
	test_loss, test_accuracy = test([xtest, ytest])
	print("Epoch: {}, Train Loss: {}, Train Accuracy: {}, Test Loss: {}, Test Accuracy: {}".format(
		epoch, loss, accuracy, test_loss, test_accuracy))
```

**Comment by keunwoochoi** [comment]
So is it something like using keras as if you're using tensorflow? I think it's good idea. Probably as a one of the examples?
I PR'ed more basic example for almost every functions in backend #4764, your example would server something more complex and complete.

**Comment by bstriner** [comment]
Good way to put it. You can basically directly rewrite most theano or tf programs using Keras backend even if you can't restructure easily to use Keras models, and make them more readable and portable in the process. So, if a friend writes in theano or tf, you can still use Keras optimizers and backend in that program.

This example is basically a skeletonized Keras model, so you can understand what Keras is doing. It also shows how to use Keras optimizers in your own training loops, which was the original intent.

BTW, thanks for the extra documentation. 

Cheers,
Ben

**Comment by BenAsaf** [comment]
Thank you for this @bstriner !

This might be an old issue but still relevant I guess.
This currently works on latest version of Keras:

```
from keras.optimizers import Adam
from keras import backend as K
from keras.datasets import mnist
from keras.utils.np_utils import to_categorical
from keras.metrics import categorical_accuracy
from keras.initializers import glorot_uniform, zero


input_dim = 28*28
output_dim = 10
x = K.placeholder(name="x", shape=(None, input_dim))
ytrue = K.placeholder(name="y", shape=(None, output_dim))

hidden_dim = 128
W1 = K.variable(glorot_uniform()([input_dim, hidden_dim]))
b1 = K.variable(zero()((hidden_dim,)))
W2 = K.variable(glorot_uniform()([hidden_dim, output_dim]))
b2 = K.variable(zero()((output_dim,)))
params = [W1, b1, W2, b2]


hidden = K.sigmoid(K.dot(x, W1)+b1)
ypred = K.softmax(K.dot(hidden, W2)+b2)


loss = K.mean(K.categorical_crossentropy(ytrue, ypred),axis=None)

accuracy = categorical_accuracy(ytrue, ypred)

opt = Adam()
updates = opt.get_updates(params, [], loss, )
train = K.function([x, ytrue],[loss, accuracy],updates=updates)

test = K.function([x, ytrue], [loss, accuracy])

((xtrain, ytrain),(xtest, ytest)) = mnist.load_data()
(xtrain, xtest) = [x.reshape((-1, input_dim))/255.0 for x in (xtrain, xtest)]
(ytrain, ytest) = [to_categorical(y, output_dim) for y in (ytrain, ytest)]
for epoch in range(1000):
	loss, accuracy = train([xtrain, ytrain])
	test_loss, test_accuracy = test([xtest, ytest])
	print("Epoch: {}, Train Loss: {}, Train Accuracy: {}, Test Loss: {}, Test Accuracy: {}".format(
		epoch, loss, accuracy, test_loss, test_accuracy))
```

**Comment by ZeroMaxinumXZ** [comment]
@BenAsaf, how do I make predictions (forwards-propagate) in the keras backend?

**Comment by BenAsaf** [comment]
@ZeroMaxinumXZ 
Well it's been quite a while since then.
We need to create another K.function that it's input is [x] and the output tensor is [ypred].
We obtain: K.function([x], [ypred])   (maybe you could omit the list operator around the arguments)
I can't tell you if it works or not.
