### ISSUE TITLE
A question about ConvLSTM2D in conv_lstm.py

### ISSUE THREAD

**Issue by wdl000001** [fchollet/keras#4847]
Why the input_shape of first ConvLSTM2D layer is (None, 40, 40, 1)？ 
Shouldn't it be  (None, timessteps, 40, 40, 1)?

#We create a layer which take as input movies of shape
#(n_frames, width, height, channels) and returns a movie
#of identical shape.

seq = Sequential()
seq.add(ConvLSTM2D(nb_filter=40, nb_row=3, nb_col=3,
                   input_shape=(None, 40, 40, 1),
                   border_mode='same', return_sequences=True))

**Comment by patyork** [comment]
`n_frames` is used in place of batch size, in this example. That is, a "batch" is a series of frames from the same movie. In other words, the batch size is one, and we feed it `nb_frames`; this shape would be `(1, n_frames, 40, 40, 1)` but we simplify it down to `(n_frames, 40, 40, 1)` and just pass a full movie as a batch.

**Comment by wdl000001** [comment]
thank you!

So, can 'None' be used as timesteps in RNN?

**Comment by manik-50000** [comment]
Yes

**Comment by StevenLOL** [comment]
How to shape the output to a many-to-one  ? eg ( batchsize, 1 )

**Comment by scindew** [comment]
Hi, 
in conv_lstm.py , in line 38, why they used binary_crossentropy as the optimizer? 
They are trying to predict the next frame and for this purpose, shouldn't we use  loss=' mean_squared_error' instead?

Does anyone has the same issue?
