### ISSUE TITLE
Exception: Input arrays should have the same number of samples as target arrays. Found 28019580 input samples and 2142942 target samples

### ISSUE THREAD

**Issue by vinayakumarr** [fchollet/keras#4850]
program snippet given below. I am trying for character based text classification. 

trainlabels = pd.read_csv('labels.csv', header=None)
trainlabel = trainlabels.iloc[:,0:1]

path = "/home/censpark/rancyb/Allinone/other/mydga/lstm/multiclass/dga/New/train.txt"
X = open(path).read()
path = "/home/censpark/rancyb/Allinone/other/mydga/lstm/multiclass/dga/New/test.txt"
T = open(path).read()

# Generate a dictionary of valid characters
valid_chars = {x:idx+1 for idx, x in enumerate(set(''.join(X)))}

max_features = len(valid_chars) + 1
maxlen = np.max([len(x) for x in X])

# Convert characters to int and pad
X = [[valid_chars[y] for y in x] for x in X]

X_train = sequence.pad_sequences(X, maxlen=maxlen)
y_train1 = np.array(trainlabel)
y_train= to_categorical(y_train1)

embedding_vecor_length = 128

model = Sequential()
model.add(Embedding(max_features, embedding_vecor_length, input_length=maxlen))
model.add(LSTM(128))
model.add(Dropout(0.2))
model.add(Dense(18))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

model.fit(X_train, y_train, batch_size=128, nb_epoch=15,validation_data=(X_train,y_train), shuffle=True)
score, acc = model.evaluate(X_train, y_train, batch_size=128)
print('Test score:', score)
print('Test accuracy:', acc)

![untitled](https://cloud.githubusercontent.com/assets/18217467/21497384/83954692-cc4a-11e6-851c-3511c4d6bae0.png)

**Comment by kudkudak** [comment]
I think error says `len(X_train) != len(y_train)`, so you can start debugging by making sure these arrays have the same lengths.

**Comment by abhijitnathwani** [comment]
Hello,
I am facing the same issue. The lengths of the array are same as suggested by @kudkudak . Did anyone solve this?

**Comment by silvanheller** [comment]
@abhijitnathwani I ran into the same Issue - what worked for me is ensuring that train_data.size % batch_size = 0, or in other words the size of your data arrays needs to be a multiple of the batch size.

**Comment by abhijitnathwani** [comment]
Thanks @silvanheller . I did some work around, and concluded the same!

**Comment by rihamriffat** [comment]
i have same propblem i use train data = 1628 and validation =489 wht i should do to solve this

**Comment by russell0** [comment]
Thank you @silvanheller solved my problem.

**Comment by sophchoe** [comment]
When my batch size is 100, I get  ValueError: All input arrays (x) should have the same number of samples. Got array shapes: [(30000, 32, 32, 1), (10000, 10)], where train data%batch size = 0. What do I do?

**Comment by sophchoe** [comment]
Solved by kudkudak

**Comment by brockelmore** [comment]
I had this problem as well - one thing to check is how you are loading in your training data. For me, I versioned my files by adding the number to the end. So, when I was referencing the file name to load it in, I was referencing an older version of the data with a different number of samples thus len(x_train) != len(y_train). Just one more thing to check.

**Comment by shrybht** [comment]
@sophchoe what were the changes you had to do, to get rid of the error?

**Comment by Aveen1** [comment]
ValueError: Input arrays should have the same number of samples as target arrays. Found 4847 input samples and 4846 target samples.

I have this error, can someone solve this?

**Comment by RishikMani** [comment]
If anyone would be able to suggest me a solution here, it would be highly appreciated. I have a model with multiple inputs. One input is fed into a RNN and the other input is fed into a CNN. Basically, I have an image and per image I am generating 10 questions. In my case I have 9800 such images, thus the questions size would become 98000. 
How would someone propose to carry ahead this problem. Initially, I thought of a very dumb approach of copying every image 10 times, but unfortunately that always crashes and leaves the system out of RAM. Is there a way out?

**Comment by cybermi** [comment]
> confirmed!!!!  it was caused by  `len(X_train) != len(y_train)`,

**Comment by cshendye** [comment]
How can this issue be solved??

Somebody reply ASAP please

**Comment by tchaye59** [comment]
I have the same problem and len(X_train) == len(y_train). 
My model is fitted from a generator and I realized that this error happens when the batch size changes.

These are the input and target shapes. When the shape changes from 128 to 4 samples  Bam error.
(128, 900) (128, 11)
(128, 900) (128, 11)
(128, 900) (128, 11)
(128, 900) (128, 11)
(128, 900) (128, 11)
(128, 900) (128, 11)
(128, 900) (128, 11)
(4, 900) (4, 11)

**Comment by tchaye59** [comment]
This works for me :+1: 

```
history = model.fit_generator(train_data, 
                              steps_per_epoch=train_steps,
                              epochs=10, 
                              validation_data=test_data,
                              validation_steps=test_steps,
                              use_multiprocessing=True,
                              callbacks=callbacks_list)

```
I set  use_multiprocessing to True and the error disappeared.
