### ISSUE TITLE
Easy way of adding regularization to intermediate layers of a model

### ISSUE THREAD

**Issue by divamgupta** [fchollet/keras#4852]
I was thinking that we could have a  function that can be used to set regularisation of intermediate layers of a model. 

Eg:
`model.layers[23].set_weight_regularization(l1(0.01))`

The use cases would be 
1) To add regularization in a model loaded from a json file.  
2) Change the regularisation in between training.

**Comment by kudkudak** [comment]
There is layer.add_loss in keras 1.2.0, I think it can serve this purpose
