### ISSUE TITLE
Keras scalar input_shape to LSTM

### ISSUE THREAD

**Issue by Valentin4869** [fchollet/keras#4854]
Is there anyway to add an LSTM layer with scalar input to a Sequential model? I'm trying to build a network that takes in scalar and discrete time input (0,1,2,...), but there doesn't seem to be anyway to make the LSTM layer accept a 1-dimensional `input_shape`:

Here's what I tried with the error listed:
`model2.add(LSTM(1024,input_shape=1));`
Error: `TypeError: 'int' object is not iterable`

`model2.add(LSTM(1024,input_shape=(1,1)));`
`model2.add(LSTM(1024,input_shape=np.asarray(1).reshape((1,1))));`
Both work, but then when I want to train the network, it expects a 3-dimensional input.

Thanks

**Comment by kudkudak** [comment]
You could always have 3 dimensional input with 3rd dimension of size 1 (so batch_size would be (n_batch, n_timesteps, 1)). Alternatively, you can add a Reshape layer before LSTM.

**Comment by Valentin4869** [comment]
Thanks. It seems that's the only way to do it. I don't get any problems with the results so I guess it's not a problem.
