### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by jpriniski** [fchollet/keras#4865]
Hello, 

I am trying to perform a binary classification on vectors of word frequencies, ie. a bag of words.  When I try to run the code  I receive the following error: `ValueError: setting an array element with a sequence.`

My `X_train` and `Y_train` variables are numpy arrays. X_train is a 2D numpy array where each row represents a single document's word frequencies.  And `Y_train` are the classifications (either a 0 or 1) for each document.   `num_features` represents the length of the word frequency vectors, ie the amount of columns in `X_train`. 

My code is outlined below:

`model = Sequential([
	Dense(64, input_dim =num_features),
	Activation('relu'),
	Dense(1),
	Activation('softmax')
	])`

`model.compile(optimizer = 'rmsprop', loss='binary_crossentropy', metrics=['accuracy'])`

`model.fit(X_train, Y_train, nb_epoch=5, batch_size = 32)`

It looks like the error occurs when I compile my model at: `model.fit(X_train, Y_train, nb_epoch=5, batch_size = 32)`

Thanks so much!

=========================================================================

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by bstriner** [comment]
Short answer: use sigmoid activation.

Softmax is only meaningful with >1 output dimension. Softmax is used for multi-class classificiation, where the number of outputs is the number of classes.

Two options:
* Use sigmoid activation with one output. Use binary_crossentropy.
* Use softmax activation of a dense layer with two outputs. Convert your Y_train to one-hot representations using keras.utils.np_utils.to_categorical. Use categorical_crossentropy.

Cheers,
Ben

**Comment by eromoe** [comment]
Using sparse matrix input cause similar error too , https://github.com/fchollet/keras/issues/4984

**Comment by Jayanth07** [comment]
Hello,
@bstriner,   I have a similar problem but cannot figure out what the problem is.
I've tried using the softmax, converted y_train to one-hot and also set it to categorical_crossentropy.
What do u mean by softmax with 2 outputs?

**Comment by kabadbruzzo** [comment]
Hi! I am also having this problem. In my case, my training data is a panda series of arrays of shape (39, 150). I thought some array with a different shape might have slipped during preprocessing, but I checked and double and triple checked and it is not the case. I tried passing the series, the series as a list, the series as an array of shape (len(series), 39, 150) and nothing worked. :(
