### ISSUE TITLE
Add seq2seq model to the Keras models

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [fchollet/keras#4885]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi @farizrahman4u and  @fchollet 
Could you please Fariz's seq2seq package and model to the keras default models as it will be very helpful... As I saw, it needs a few more documentation and modification, but it could be highly helpful for seq2seq modeling in keras...

**Comment by armando-fandango** [comment]
was this added to keras ?
