### ISSUE TITLE
No module named keras

### ISSUE THREAD

**Issue by MrWanter** [fchollet/keras#4889]
I  have installed `Anaconda `package on a server as a user account, then I use `conda install keras` to install `keras `on it, but then when I run `import keras`, it raised `no module named keras`, anyone can help? thanks very much!

**Comment by nzw0301** [comment]
Did your command (: `conda install keras`) succeed?

keras cannot be installed by `conda install keras` because package not found.
(my anaconda is `anaconda3-4.1.1`)

I recommend use `pip install keras` to install keras.

**Comment by raul-jr3** [comment]
I had the same issue when i installed keras using conda

I removed it and then installed using <code>sudo pip3 install keras</code> and it worked.

**Comment by recs84** [comment]
sudo pip3 install keras fixed it, thanks!

**Comment by annanurov** [comment]
I had the a similar problem. Following steps helped

1- Open Anaconda Prompt with admin privileges (in windows: right click -> open as admin, etc)
2- Type the command to install you package, e.g.:
`conda install -c conda-forge keras tensorflow`
If not sure about package name, search web for it.

3- Test if the package was installed correctly. E.g. launch Spider from Anaconda and use command 
`import keras`

4- Restart Rstudio (Session -> Restart R) before trying 
`library(keras)`


PS: now you have to deal with TF's internal errors and warnings like
`Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX`
But, that's a whole different story.

**Comment by Muthuramansivakumar** [comment]
If you are using Anaconda 3.6 version, you can type the below command in Anaconda prompt to install keras

conda install -c conda-forge keras 

Followed by try importing Dense and sequential libraries from the keras package 

from keras.layers import Dense
from keras.models import Sequential


Hope it works

Thanks

**Comment by MayankMurali** [comment]
> 
> 
> I had the a similar problem. Following steps helped
> 
> 1- Open Anaconda Prompt with admin privileges (in windows: right click -> open as admin, etc)
> 2- Type the command to install you package, e.g.:
> `conda install -c conda-forge keras tensorflow`
> If not sure about package name, search web for it.
> 
> 3- Test if the package was installed correctly. E.g. launch Spider from Anaconda and use command
> `import keras`
> 
> 4- Restart Rstudio (Session -> Restart R) before trying
> `library(keras)`
> 
> PS: now you have to deal with TF's internal errors and warnings like
> `Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX`
> But, that's a whole different story.

Thanks a lot mate for the detailed steps :)

**Comment by srikant132** [comment]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-88d96843a926> in <module>()
----> 1 import keras

ModuleNotFoundError: No module named 'keras'
this is the issue after installing through  conda

**Comment by coxymla** [comment]
I had the same problem and it turned out that conda was not adding the environment site-packages onto the python path.

e.g.
`import sys
print (sys.path)`

did not have C:\ProgramData\Anaconda3\envs\foo\Lib\site-packages present.

I set environment variable PYTHONPATH to C:\ProgramData\Anaconda3\envs\foo\Lib\site-packages and now python can find the packages present within virtual environment.

**Comment by pissw2016** [comment]
I restart my conda environment by `conda deactivate` and then `conda activate tf13` and it solved.before this I reinstall my keras by uninstall anything with `keras` in my tf13 environment.

**Comment by VedhaMukund** [comment]
what to do in jupyter , no module not found

**Comment by jimgitonga** [comment]
run this command in anaconda prompt
conda install -c conda-forge keras tensorflow

**Comment by TheUsmanMirza** [comment]
"pip3 install keras"
worked for me

**Comment by master-minszor** [comment]
Thanks all, I realized I was in the wrong environment.

**Comment by kashishmadan** [comment]
pip install keras worked for me!

**Comment by Tjossul** [comment]
Hello,

please know that Keras examples worked for me some weeks ago...

I installed Python 3.7 (with env. path), configured with tensorflow and keras:

`
Name: Keras
Version: 2.4.3
Summary: Deep Learning for humans
Home-page: https://github.com/keras-team/keras
Author: Francois Chollet
Author-email: francois.chollet@gmail.com
License: MIT
Location: c:\users\shopp\appdata\local\programs\python\python37\lib\site-packages
Requires: numpy, scipy, h5py, pyyaml
Required-by:
`

I installed Keras.NET v3.7.4.2 together with its dependencies.

Today running the image example I got this error:

Python.Runtime.PythonException: "ModuleNotFoundError : No module named 'keras'"

Do you have any what the problem could be after (as I said) it worked some weeks ago?

Thanks.

**Comment by MUKESHBADIGINENI** [comment]
I'm able to import the keras after  `conda install -c conda-forge keras tensorflow` but I couldn't import the layers, while importing I'm encountering the following error

`No module named 'keras.layers.img_paths_to_labelsconvolutional'`

**Comment by MennaEwas** [comment]
if `sudo pip3 install kera` doesn't work for you and shows 'sudo' is not recognized as an internal or external command,
operable program or batch file. https://makandracards.com/makandra/1020-sudo-command-for-windows 
try the above link for windows

**Comment by MalikAbdulWahab** [comment]
> I have installed `Anaconda `package on a server as a user account, then I use `conda install keras` to install `keras `on it, but then when I run `import keras`, it raised `no module named keras`, anyone can help? thanks very much!
