### ISSUE TITLE
Wrong weights Initialization in 'tf' mode

### ISSUE THREAD

**Issue by mynameisguy** [fchollet/keras#4895]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

In order to reproduce the error you just need to update the test *test_initializations.py*:
replace:
```
CONV_SHAPE = (25, 25, 2, 2)
```
with:
```
# TH kernel shape: (depth, input_depth, ...)
# TF kernel shape: (..., input_depth, depth)
if (K.image_dim_ordering() == 'tf'):
    CONV_SHAPE = (2, 2, 25, 25)
else:
    CONV_SHAPE = (25, 25, 2, 2)
```
the th conv shape comment was taken from *keras/test_initializations.py* file.

Now if you will try to run the test in tf mode it will fail.

I found out about this issue when a net I created converged only in th mode, when I tried to figure why I found that the initialization was wrong in tf mode.

I also had pull request to fix it which was closed:
https://github.com/fchollet/keras/pull/4842

Any thoughts? Am I looking at this all thing wrong?

**Comment by fchollet** [comment]
Initialization functions have a `dim_ordering` argument. Use it (like all layers do).

**Comment by mynameisguy** [comment]
@fchollet 
At least Convolution2D doesn't.
you can add `print(dim_ordering)` at the start of `glorot_uniform(shape, name=None, dim_ordering='th')` function and run the following code:

```
from keras.layers import Convolution2D
from keras.models import Sequential
import keras.backend as K

K.set_image_dim_ordering('tf')

model = Sequential()
model.add(Convolution2D(10, 3, 3, activation='relu', input_shape=(100,100,3)))
model.compile
```

you will see that 'th' is printed.
The layer pass the dim_ordering only when she get the function (`self.init = initializations.get(init, dim_ordering=dim_ordering)`) but because the function is not *instantiate* in the function `get_from_module` that argument get lost.

we can pass that argument when we actually call the function but then we will have to add this argument to all init function (such as *zeros* for example), so I think the solution I proposed is better.
