### ISSUE TITLE
Run multiple program with multiple GPUs

### ISSUE THREAD

**Issue by MrWanter** [fchollet/keras#4898]
A simple maybe silly question, I want to run different program with different GPUs, ie. run program A with GPU0 and run program B with GPU1 simultaneously, I tried `THEANO_FLAGS='device=gpu1' python myscript.py` ,but it raised `THEANO_FLAGS: Command not found`, can anyone help? thanks very much!

**Comment by kgrm** [comment]
What environment are you running keras from? That syntax is for the bash shell. Instead of setting theano flags when calling the script, you can also do it from within your script, by using

```import os
os.environ["THEANO_FLAGS"] = "device=gpu1"```

before importing Keras or theano.

**Comment by MrWanter** [comment]
Thank you, it turns out that I was using tcsh, adding the lines:
```
import os
os.environ["THEANO_FLAGS"] = "device=gpu1"
```
works for me!
