### ISSUE TITLE
GlobalAveragePooling2D & GlobalAveragePooling3D not working for 'tf' 

### ISSUE THREAD

**Issue by Alireza-Sedghi** [fchollet/keras#4908]
here is a simple example for demonstration of the problem 
https://gist.github.com/Alireza-Sedghi/343705ac76138337068d7df21adb97e4
basically it is a convolution layer (16 filters of 3x3) after the input of 32x32 +global averaging after it 
based on (https://keras.io/layers/pooling/#globalaveragepooling2d) it should generate the output with the (nb_samples, channel) shape but it is not happening in 'tf' 

the first part of the provided smaple code, ('th'),  will generate a tensor with the shape of (None,16) -> correct 
the second part ('tf') will generate a tensor with the shape of (None,30) -> incorrect 

any ideas? this is happening for GlobalAveragePooling3D also !

**Comment by nimishzynga** [comment]
I think dim_ordering should be "th" or "tf" not 1 and 3 in GlobalAveragePooling2D.

**Comment by Alireza-Sedghi** [comment]
Thanks for your answer, i misunderstood the documentation
