### ISSUE TITLE
FAQ "How can I "freeze" Keras layers?" is broken

### ISSUE THREAD

**Issue by joelthchao** [fchollet/keras#4910]
Environment: 
keras version: `1.2.0`, tensorflow version: `0.12.0`

Run script in [FAQ](https://keras.io/getting-started/faq/#how-can-i-freeze-keras-layers), both `frozen_model` and `trainable_model` are unable to train (i.e. weights won't update). Also, `model.summary()` produce wrong params count.

The root cause is that `layer.trainable` is set to `False` before `layer` is called (`y = layer(x)`), 
and results in `layer.weights == []`. Is this behavior expected? Or at least should be documented?

the script should be modified to:
```python
...
x = Input(shape=(32,))
layer = Dense(32)
y = layer(x)
layer.trainable = False

frozen_model = Model(x, y)
...
```

**Comment by bjanssen** [comment]
@joelthchao thanks for mentioning this! This behaviour is also the reason why I could not set the weights of an untrainable layer.

i.e.  this results in an error
```
layer = Convolution2D(1, 3, 3, weights=my_fixed_weights, trainable=False)
```
what does work is
```
layer = Convolution2D(1, 3, 3, weights=my_fixed_weights)
y = layer(x)
layer.trainable = False
```
