### ISSUE TITLE
model.fit() - training data's format

### ISSUE THREAD

**Issue by ZsocaCoder** [fchollet/keras#4931]
Hello everyone!

Would like to ask for your help in connection with the input format of the training data that is given to the model.fit() method (at the moment, I suppose that the problem exists because of the incorrect format). In the case of my task, I would like to build a model based on 120 records that have several hundred attributes.

Initially, I load in the data via pandas from an .xlsx file, and create a pandas.DataFrame from them. Since the .xlsx contains the records in a column-orinted way (so the rows denote the attributes), I transpose the read in dataframe after the load is done.

Now, the data still has the format pandas.DataFrame. My question would be about how to pass this dataframe correctly to model.fit(). The question comes up since the predicted values (talking about a regression task basically) really differ from the expected ones: the target variable is usually between 50 and 60, but the predictions fall into the range [-7, 7], and many times they are constant 0.

Don't understand the reason of this yet, but I hope you can tell me some ideas how to fix this. Let me know, if you would like to know about any further details. :)

(Of course, it's possible that the problem is with the model... And would like to share the code, if anyone asks.)

Thanks in advance for any help! :)

**Comment by Xls1994** [comment]
the function model.fit() need the data format of the python numpy arrary. Maybe you can use the numpy to load your data as the input.  I think pandas may not suit for you.

**Comment by ZsocaCoder** [comment]
Thanks for your reply, Xls1994, but the problem exists somewhere deeper. The code runs without a problem: there aren't any exceptions about incorrect input shape or similar.

The results are my problem: the cross-validation I use is completely deterministic now and I don't understand why, but the model predicts 0.0 many times and it's doing this randomly (when I rerun the code, the prediction is 0.0 in the case of the first record; in the case of another run, the prediction is 0.0 for i.e. the 3rd record).

**Comment by ZsocaCoder** [comment]
Turned out that the problem existed because I didn't manage to create a suitably structured network and this implied the unsufficient regression surface. (I don't think that there were format problems with the input data.)
