### ISSUE TITLE
Please replace callbacks.py for Python 2.7  tf.merge_all_summaries() for tf.summary.merge_all()  

### ISSUE THREAD

**Issue by botasb** [fchollet/keras#4935]
Hi,

Could you please update this line in [https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L529]
` self.merged = tf.merge_all_summaries()`
since tf.merge_all_summaries() is depreciated and should be replace by tf.summary.merge_all()

Thank you

**Comment by Iflier** [comment]
Same here. Some error occurred.
