### ISSUE TITLE
Port inception v4 and inception-resnet-v2 to Keras?

### ISSUE THREAD

**Issue by jrao1** [fchollet/keras#4951]
I noticed TF Slim now has [these two models with pre-trained weights](https://github.com/tensorflow/models/tree/master/slim#Pretrained), I wonder if there're any interests or need to port them to Keras?

Reference: [Inception-v4, Inception-ResNet and the Impact of Residual Connections on Learning](http://arxiv.org/abs/1602.07261)

**Comment by RobSchofield** [comment]
I have also been wondering the same thing!

**Comment by kentsommer** [comment]
@RobSchofield, @jrao1 

I have implemented Inception-V4 and ported the weights. You can find it here: https://github.com/kentsommer/keras-inceptionV4
