### ISSUE TITLE
I can't set "trainable=False" in the keras embedding layer

### ISSUE THREAD

**Issue by jlfu** [fchollet/keras#4952]
I try to add a pre-trained embedding layer, but i can't set "trainable=False". When i move "trainable=False", it can work correctly. How can i fix it?
model11 = Sequential()
model11.add(Embedding(len(vocabulary)+1, word_embedding_size, init='uniform',input_length=word_max_len,
						weights=[embedding_matrix],
						trainable=False))
------------------------------------------------------------------------------
------------------------------------------------------------------------------
ValueError: You called `set_weights(weights)` on layer "embedding_2" with a  weight list of length 22803, but the layer was expecting 1 weights. Provided weights: [[-0.07056077  0.03531956  0.09292351 ..., -0.2440...

**Comment by jlfu** [comment]
and when i move **init='uniform'**, it still cann't work.

**Comment by xiaoleihuang** [comment]
I got the same issue. After removing the trainable=False and setting Theano optimizer=None, it works. I am not sure whether it works in your case. You could tried it....

**Comment by jlfu** [comment]
But I do not want to train the word vector, i want to fix it. I want to use the pre-trained word vectors to be my word representation, so i need to set trainable=False or do something else. Can someone help me?

**Comment by nzw0301** [comment]
see https://github.com/fchollet/keras/issues/4753#issuecomment-268932361
