### ISSUE TITLE
Problem with model saving

### ISSUE THREAD

**Issue by MaratZakirov** [fchollet/keras#4957]
I made a model with one LSTM for query hashing and one for document title hashing. The key thing in my model is that LSTM for document title is shared for 5 examples.
See
`    
    # define title shared lstm
    shared_lstm = LSTM(rnn_size)

    # define positive rnn convolution
    query = Sequential()
    query.add(Masking(mask_value=0.0, input_shape=(q_seq_size, featnum)))
    query.add(LSTM(rnn_size))

    # define positive title
    title_p = Sequential()
    title_p.add(Masking(mask_value=0.0, input_shape=(t_seq_size, featnum)))
    title_p.add(shared_lstm)

    # define first negative title
    title_n_1 = Sequential()
    title_n_1.add(Masking(mask_value=0.0, input_shape=(t_seq_size, featnum)))
    title_n_1.add(shared_lstm)

    # define second negative title
    title_n_2 = Sequential()
    title_n_2.add(Masking(mask_value=0.0, input_shape=(t_seq_size, featnum)))
    title_n_2.add(shared_lstm)

    # define third negative title
    title_n_3 = Sequential()
    title_n_3.add(Masking(mask_value=0.0, input_shape=(t_seq_size, featnum)))
    title_n_3.add(shared_lstm)

    # define fourth negative title
    title_n_4 = Sequential()
    title_n_4.add(Masking(mask_value=0.0, input_shape=(t_seq_size, featnum)))
    title_n_4.add(shared_lstm)

    # define final concatanation
    merge_f = Sequential()
    merge_f.add(Merge([query, title_p, title_n_1, title_n_2, title_n_3, title_n_4], mode='concat'))
`

After training this model was saved. And after that loaded. But then loaded I got the following:

`
ValueError: You are trying to load a weight file containing 2 layers into a model with 6 layers.
`

I do not think that it is a right behavior. I have not check yet whether it works with weights saving but I hope it is or in other way I will need to write bloat-ware peace of soft to save and load.

**Comment by ylmeng** [comment]
I also had similar errors. It seems to me that concatenating input layers (without any other layers before concatenation) causes errors.
