### ISSUE TITLE
class_weight and sample_weight mutually exclusive

### ISSUE THREAD

**Issue by wxs** [fchollet/keras#497]
As far as I can tell, if you pass in both a class_weight and a sample_weight, the class_weight is ignored. Here is the relevant code:

```
def standardize_weights(y, sample_weight=None, class_weight=None):
    if sample_weight is not None:
        return standardize_y(sample_weight)
    elif isinstance(class_weight, dict):
        if len(y.shape) > 2:
```

Is this the desired behaviour? If so we should probably warn when you set both parameters. But I don't see why we couldn't multiply the class_weight with the sample_weight.

**Comment by wxs** [comment]
I put up a PR in #499 with a potential solution.

**Comment by fchollet** [comment]
> Is this the desired behaviour? If so we should probably warn when you set both parameters. But I don't see why we couldn't multiply the class_weight with the sample_weight.

Surely this is desired behavior, since a sample can only have one weight. If you are looking for a specific merge behavior (like multiplication), then you can compute yourself such sample weights. Processing data in a way that is not explicitly desired by the user can be dangerous.

Agreed that a warning might be in order.

**Comment by wxs** [comment]
> Surely this is desired behavior, since a sample can only have one weight

@fchollet I've been looking into the scikit learn architecturea bit, and they *do* allow both a sample_weight and a class_weight,  actually: 

http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html#sklearn.linear_model.SGDClassifier.fit

> Weights applied to individual samples. If not provided, uniform weights are assumed. These weights will be multiplied with class_weight (passed through the contructor) if class_weight is specified
