### ISSUE TITLE
model.build() fails to initiazlize all layer weights

### ISSUE THREAD

**Issue by kirk86** [fchollet/keras#4971]
Hi, thanks for keras. I've been recently trying to play around and I've found that `model.build()` doesn't initialize all layer weights as is indicated in the documentation, instead one has to call `build()` on the individual layer.

Example:

```
from keras.layers import Input, Lambda
from keras.applications import VGG16
from keras.optimizers import Adam
import numpy as np

model = VGG16(include_top=False, weights=None, input_tensor=Input(shape=(224, 224, 3)))
model.summary()

# Now let's say that I want to add the vgg preprocessing after the 'input_1' layer
def vgg_preprocess(x):
    x -= np.array([123.68, 116.779, 103.939])
    return x

model.layers.insert(1, Lambda(vgg_preprocess, input_shape=(224, 224, 3), output_shape=(299,299,3)))

# at this stage I was hopping that `model.compile` would have taken care of everything but that was not true
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# trying to print a summary of the model gives an error
model.summary()

# using model.build((224, 224, 3)) doesn't help either
model.build((224, 224, 3))
model.summary()

# the only solution was to use build on the layer
model.layers[1].build((224, 224, 3))

model.summary()
```

I also have another question, in the printed model summary the layer gets a random name and the output shape says `multiple`.

How can I set my own name plus I don't understand the output shape `multiple` is that good or bad? How can I define that properly?

**Comment by kgrm** [comment]
Lambda layers can only execute differentiable theano/tensorflow functions, not arbitrary python code.

**Comment by kirk86** [comment]
@kgrm got it, so instead I should change `vgg_preprocess` to something like this:

```
x = K.variable(..., ....)
mean = K.variable(...., ....)
def vgg_preprocess(x):
    x -= mean
    return x

symbolic_func = K.function([x, mean], vgg_preprocess)

# so then my Lambda layer should be something like?

Lambda(symbolic_func, input_shape=(224, 224, 3), output_shape=(299,299,3)
```
Assuming that something like the above is correct, which is not but assuming then what is the next step?

```
# Pseudocode
1. model_compile()
2. model.build()
or
3. model.layer_n.build()
```

P.S. Didn't had the time to check this since I'm not in front of the computer

**Comment by kgrm** [comment]
Given a properly specified backend function in the `Lambda` layer, the model can be compiled with `m.compile()`. The layer itself can more easily be specified as

```
mean = K.variable([123.68, 116.779, 103.939])
layer = Lambda(lambda x: x - mean)
```

**Comment by kirk86** [comment]
@kgrm thanks, for the quick reply, closing it. I'll try it once I get in front of my pc.
