### ISSUE TITLE
How to pad for a MLP with embedding layer?

### ISSUE THREAD

**Issue by chenwangliangguo** [fchollet/keras#4974]
Hi, everyone, I am a newer to Keras. I have some issues of padding.

My data is a fixed length of features and a classifier label. For example (1,4,5,6,8,0,10,8,0).  each  feature have different means,  i pad the feature if  some of samples have no such feature with a label of zero. In the model, i want to sent the feature ids  to a embedding layer and then connect the embedding result to MLP for classification. I know the keras Embedding layer have a mask_zero parameter but  i am not sure how to use it. Anyone can give some advice for me? than you.

**Comment by caugusta** [comment]
I have a similar issue. I zero-pad my inputs to ensure they're all the same length, but then I want to mask the zeros for learning later.
