### ISSUE TITLE
Keras Singular value decomposition

### ISSUE THREAD

**Issue by gourab4gd** [fchollet/keras#4975]
Keras has made our life really easy for coding in deep learning. New activation function can be added. But some aspect is not clear. When I try to use Singular value Decomposition(svd) using same way as adding activation function I have failed. While using **theano.tensor.nlinalg.svd(x)** where x is input matrix it is saying expecting matrix. While using **numpy.linalg.svd(x)** it's saying getting 0-dim vector expecting 2-dim matrix. How to solve svd problem in keras

**Comment by bstriner** [comment]
Why are you trying to use SVD as an activation function?

SVD does not return one matrix, it returns a tuple of matrices.

It doesn't make sense to compute SVD across samples.

Hypothetically, lets say you had an output shape of (batch_dim, n, n), you could compute SVD across each nxn matrix in the batch.

To do so, you need something like this. This will run SVD on each matrix in the batch, and create a matrix of the U values (element 0 returned from svd).

```python
Lambda(lambda x: theano.scan(lambda z: svd(z)[0], sequences=x)[0])
```

Cheers,
Ben

**Comment by gourab4gd** [comment]
Thanks a lot Sir for responding.

Actually I would like to reconstruct some images with smaller dimension using svd (PCA). I have utilized autoencoder in keras to reduce the dimension of mnist and it works pretty well. But I would want to do using svd. So like creating custom activation function using Theano, I have tried to  do the same thing with svd using Theano but while parsing matrix dimension is not matching  as theano expects 2 dimension matrix but I am sending 4 dimension mnist train set whose shape is **(60000,1,28,28)**.
So I would like to know will the above code you wrote able to parse svd. 
Example:
**class MyTan(Layer):
    def __init__(self, alpha, **kwargs):
        self.supports_masking = True
        self.alpha = alpha
        super(MyTan, self).__init__(**kwargs)

    def call(self, x, mask=None):
         return theano.tensor.nlinalg.svd(x) 
    def get_config(self):
        config = {'alpha': self.alpha}
        base_config = super(MyTan, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))**

While executing  **return theano.tensor.nlinalg.svd(x)** section dimension mismatch error is giving. How can I execute the section.

Thanks in advance for being so helpful. 

Gourab

**Comment by bstriner** [comment]
Activation functions run on an entire batch, not just one sample. 

Read theano documentation on scan and maybe ask some questions on the theano user groups.

Basically, `scan` can be used to apply an operation over a sequence. so `scan(lambda z: svd(z)[0], sequences=x)` will return svd(z)[0] where z is each row in x.

So if you want to apply matrix decomposition to each image, you need to use scan to apply a function to each image, and write the decomposition you want to do within scan.

If you scan a sequence of shape (x,28,28,1), the lambda within scan will get shape (28,28,1) and be applied x times.

You probably don't need to write an entire layer. You can just use a Lambda layer and make sure to set the output_shape. After you get the Lambda working, you can write a custom class if you want to make a library or something.

**Comment by gourab4gd** [comment]
Thank you so much, I will try your ways to get some solution.
