### ISSUE TITLE
Support for masking in flatten and reshape layers

### ISSUE THREAD

**Issue by shwetgarg** [fchollet/keras#4978]
I have an architecture which is very similar to the one posted [here.](https://groups.google.com/forum/#!topic/keras-users/suKYo6L1bSI) 

It works fine without masking. But it throws following error with masking:
Exception: Layer xyz does not support masking, but was passed an input_mask: All{0}.0

Essentially, I am using Flatten and Reshape layer, which does not support masking, which results in above mentioned error. 

I have been stuck on this issue for quite some time and would appreciate any help on this.

**Comment by jacoxu** [comment]
Maybe you can put an NonMasking layer before using Flatten and Reshape layer as follows, which can successfully compiled. I'm not sure it works as you wish.

<DIV class=dp-highlighter><DIV class=bar></DIV>
<OL class=dp-py>
<LI class=alt><SPAN><SPAN class=keyword>class</SPAN><SPAN>&nbsp;NonMasking(Layer): &nbsp;&nbsp;</SPAN></SPAN></LI>
<LI><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=keyword>def</SPAN><SPAN>&nbsp;</SPAN><SPAN class=magicmethods>__init__</SPAN><SPAN>(</SPAN><SPAN class=builtins>self</SPAN><SPAN>,&nbsp;**kwargs): &nbsp;&nbsp;</SPAN></SPAN></LI>
<LI class=alt><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=builtins>self</SPAN><SPAN>.supports_masking&nbsp;=&nbsp;</SPAN><SPAN class=builtins>True</SPAN><SPAN>&nbsp;&nbsp;</SPAN></SPAN></LI>
<LI><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=builtins>super</SPAN><SPAN>(NonMasking,&nbsp;</SPAN><SPAN class=builtins>self</SPAN><SPAN>).</SPAN><SPAN class=magicmethods>__init__</SPAN><SPAN>(**kwargs) &nbsp;&nbsp;</SPAN></SPAN></LI>
<LI class=alt><SPAN>&nbsp;&nbsp;</SPAN></LI>
<LI><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=keyword>def</SPAN><SPAN>&nbsp;build(</SPAN><SPAN class=builtins>self</SPAN><SPAN>,&nbsp;input_shape): &nbsp;&nbsp;</SPAN></SPAN></LI>
<LI class=alt><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;input_shape&nbsp;=&nbsp;input_shape &nbsp;&nbsp;</SPAN></LI>
<LI><SPAN>&nbsp;&nbsp;</SPAN></LI>
<LI class=alt><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=keyword>def</SPAN><SPAN>&nbsp;compute_mask(</SPAN><SPAN class=builtins>self</SPAN><SPAN>,&nbsp;</SPAN><SPAN class=builtins>input</SPAN><SPAN>,&nbsp;input_mask=None): &nbsp;&nbsp;</SPAN></SPAN></LI>
<LI><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=comment>#&nbsp;do&nbsp;not&nbsp;pass&nbsp;the&nbsp;mask&nbsp;to&nbsp;the&nbsp;next&nbsp;layers </SPAN><SPAN>&nbsp;&nbsp;</SPAN></SPAN></LI>
<LI class=alt><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=keyword>return</SPAN><SPAN>&nbsp;None &nbsp;&nbsp;</SPAN></SPAN></LI>
<LI><SPAN>&nbsp;&nbsp;</SPAN></LI>
<LI class=alt><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=keyword>def</SPAN><SPAN>&nbsp;call(</SPAN><SPAN class=builtins>self</SPAN><SPAN>,&nbsp;x,&nbsp;mask=None): &nbsp;&nbsp;</SPAN></SPAN></LI>
<LI><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=keyword>return</SPAN><SPAN>&nbsp;x &nbsp;&nbsp;</SPAN></SPAN></LI>
<LI class=alt><SPAN>&nbsp;&nbsp;</SPAN></LI>
<LI><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=keyword>def</SPAN><SPAN>&nbsp;get_output_shape_for(</SPAN><SPAN class=builtins>self</SPAN><SPAN>,&nbsp;input_shape): &nbsp;&nbsp;</SPAN></SPAN></LI>
<LI class=alt><SPAN>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</SPAN><SPAN class=keyword>return</SPAN><SPAN>&nbsp;input_shape&nbsp;&nbsp;</SPAN></SPAN></LI></OL></DIV>

**Comment by cTFe** [comment]
@jacoxu Hi jacoxu, I used your code after an Embedding layer with mask_zero=True. However I got this error:
`Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/yan/PycharmProjects/MultiviewRE/LSTM/discover_relation.py", line 207, in <module>
    model.add(NonMasking())
TypeError: 'module' object is not callable`
Any idea how to fix this? Thanks!

**Comment by jacoxu** [comment]
Have you import the self-defined NonMasking layer? My version of keras is also 1.2.2, except that I use Theano backend. I am not sure that TensorFlow backend make the error.

**Comment by xiaomengyc** [comment]
I found it also works if you insert a `Lambda`  layer before `Reshape ` like this:
`x = Lambda(lambda x: x, output_shape=lambda s:s)(x)`

**Comment by baregawi** [comment]
@xiaomengyc you are a god. How did you find that solution?? The errors I had were incredibly difficult to pinpoint the source of. Your solution somehow fixed all of that.

**Comment by Yovoss** [comment]
> I found it also works if you insert a `Lambda` layer before `Reshape ` like this: `x = Lambda(lambda x: x, output_shape=lambda s:s)(x)`.
> 
> But the best thing I guess is to make some operations at this layer. Anyone has a good idea please shows here.

I'm curious about the solution you mentioned, that works indeed!!!! But i'm not sure about the meaning behind the questions, The Lambda layer in fact did nothing, why can it work? I have tried several situations, if there are just one Masking layer, and dowstream Reshape layer will not raise errors, but if there are several masking layers, there will be an error, so why? And i think that the Reshape layer is to process the output of LSTM layer, not the Masking layer, right? why are there still an error about the mask??? Thank you very much.
