### ISSUE TITLE
Multichannel Images

### ISSUE THREAD

**Issue by humzaiqbal** [fchollet/keras#4982]
Would it be possible to support images with more channels than just 3 or 1. I'm currently working on a project where I have images with 8 channels, and currently I have to truncate all but 3 of the channels. Any way around this?

**Comment by the-moliver** [comment]
There shouldn't be an issue. The 2D convolutional layers already support this since a stack of feature maps has identical structure to a multichannel image. Without seeing your code I can't help any more.

**Comment by humzaiqbal** [comment]
Oh sorry I wasn't specific enough, I mean with saving images using the image processing library, 
so for example i have an image c of shape `(64, 64, 8)` and I want to call 
` image.array_to_img(c)` and I get 
`ValueError: ('Unsupported channel number: ', 8)`

**Comment by patyork** [comment]
You can't save an 8 channel image as an RGB image (or really as any image format that I know of). You could save the Numpy arrays yourself (via pickle or h5).

Simply put, standard image formats (JPG, BMP, PNG) generally only support 1, 3, or 4 channel images, where each channel has a specific meaning; 8 channels don't fit as an "image" per say.

**Comment by the-moliver** [comment]
It seems like you want to use the real-time data augmentation and that doesn't support multichannel images. Right? From looking at the code, it should be really easy to modify it to do what you want. I doubt any changes you make will make it into mainline Keras though, since it's a pretty niche issue.

**Comment by GregoryRHart** [comment]
I don't think that it is a niche issue. There are lots of people looking for whys to do data augmentation on 3D images (MRI, CT scans, etc.). That is how I found my way to this discussion. As I have been reading many people just treat the three dimension as just many (10s) of channels. If tools such as ImageDataGenerator could handle more channels it would be used.

**Comment by SimonWalsh1000** [comment]
Definitely agree with this. I'm working with CT data and I've stacking images in the third channel so that I have 512x512x10 inputs into my network.

**Comment by blubbi321** [comment]
Any update on this?

**Comment by katsanz** [comment]
@SimonWalsh1000 Do you mind explaining how you fed the images into keras? Currently I am working with a hyperspectral image of 220 channels. My image is blocked into 5x5x220 blocks. That is 5 pixels by 5 pixels by 220 channels. Can you provide insight into how you formatted your code? Thank you.

**Comment by JamesTownend** [comment]
Also trying to do this for satellite imagery with many bands, plus supporting GIS channels. At the moment I have a terrible hack of creating a new generator for every channel, with a random seed.
