### ISSUE TITLE
custom_objects passed into load_from_json not present in module_params passed into get_from_module

### ISSUE THREAD

**Issue by FeralWhippet** [fchollet/keras#4990]
Thus you can't load models created with custom components, (in this case a custom regularizer)

This happens because custom object entries are copied into the globals dict for keras.utils (in `keras.utils.layer_from_config),` but the globals dict from the top level keras package is passed into `get_from_module` from the `get` function in regularizers.py.

I am sure this pattern is repeated elsewhere (from activation.py, optimizers.py, etc...) but I have not looked in all of them

**Comment by bstriner** [comment]
Do you have a short example that can reproduce your issue? What are you passing in your custom object dictionary?

As a workaround, you can inject your code directly into keras (the beauty of Python). If you have custom class Qwerty, you can just `keras.regularizers.Qwerty=Qwerty` to add your class to keras. Then it should be sure to find it when it runs regularizers.get("Qwery").

**Comment by FeralWhippet** [comment]
yes there are many ways to get around the problem and I am currently doing so. that is not the issue, I am simply reporting a defect in the code. the current implementation does not look like its intended behavior. in regularizers.py the call:

```
def get(identifier, kwargs=None):
    return get_from_module(identifier, globals(), 'regularizer',
                           instantiate=True, kwargs=kwargs)
```

gets the globals dictionary from module `keras `and passes it into `get_from_module`. However in layer_utils.py the call:

```
def layer_from_config(config, custom_objects=None):
    """Instantiate a layer from a config dictionary.
    # Arguments
        config: dict of the form {'class_name': str, 'config': dict}
        custom_objects: dict mapping class names (or function names)
            of custom (non-Keras) objects to class/functions
    # Returns
        Layer instance (may be Model, Sequential, Layer...)
    """
    # Insert custom layers into globals so they can
    # be accessed by `get_from_module`.
    if custom_objects:
        for cls_key in custom_objects:
            globals()[cls_key] = custom_objects[cls_key]
    ...
```

copies values from `custom_objects `into the globals dictionary for `keras.utils` module (this function called from `model_from_json`). so `get_from_module` never sees the additions from `custom_objects`, as it uses the globals from keras module passed in via  the module_params parameter.

as for code that runs into the issue:

```
level_1_dim = 256
level_2_dim = 64
encoding_dim = 16

from keras import regularizers
from keras.layers import Input, Dense
from keras.models import Model, model_from_json

class CustomRegularizer (regularizers.ActivityRegularizer):
  def __call__ (self, x):
    # this is just for purposes of demonstrating a bug
    return super().__call__(x)

input_img = Input(shape=(784,))
encoded = Dense(level_1_dim, activation='relu')(input_img)
encoded = Dense(level_2_dim, activation='relu')(encoded)
encoded = Dense(encoding_dim, activation='relu', activity_regularizer=CustomRegularizer(1e-6))(encoded)
decoded = Dense(level_2_dim, activation='relu')(encoded)
decoded = Dense(level_1_dim, activation='relu')(decoded)
decoded = Dense(784, activation='sigmoid')(decoded)

autoencoder = Model(input=input_img, output=decoded)

encoder = Model(input=input_img, output=encoded)

with open('auto.encoder.model', 'w', encoding='utf-8') as outfile:
  outfile.write(encoder.to_json())

with open('auto.encoder.model', 'r', encoding='utf-8') as infile:
  encoder = model_from_json(infile.read(), custom_objects={'CustomRegularizer': CustomRegularizer})
```

as for what is saved in the json file, the config for the layer in question is below, so as you can see the name matches up:
```
{"class_name": "Dense",
 "config": {
   "activity_regularizer": {"l1": 9.999999974752427e-07, "l2": 0.0, "name": "CustomRegularizer"},
   "activation": "relu",
   "W_regularizer": null,
   "bias": true,
   "output_dim": 16,
   "W_constraint": null,
   "b_regularizer": null,
   "b_constraint": null,
   "trainable": true,
   "input_dim": 64,
   "init": "glorot_uniform",
   "name": "dense_3"},
 "inbound_nodes": [[["dense_2", 0, 0]]],
 "name": "dense_3"}
```

**Comment by bstriner** [comment]
Thanks for the example. Easiest workaround for now is `keras.regularizers.CustomRegularizer=CustomRegularizer` instead of using `custom_objects`.

The whole idea of loading the custom objects into globals seems ugly to me. It also doesn't give a way to override something without overwriting the class in the module.

One fix would be to propagate custom_objects through the code. Would need updates to several functons. Might also get tricky passing custom_objects to the layer constructors for custom layers.

A simpler fix that wouldn't require too many changes would be to save the custom objects globally and have get_from_module first check the global then the requested module. That seems like only a few lines of code that should fix the problem, although I hate globals as a rule.

I might have some free time before classes. Given that there is an easy workaround, not too high a priority.

**Comment by bstriner** [comment]
Please let me know what you think of this:

https://github.com/fchollet/keras/pull/5012

Should fix your issue and also make it a little easier to control the custom objects. Tried to make minimal changes that would fix the issue but there are some other inconsistencies with custom_objects I would want to clean up eventually.

This code works with the PR and breaks without it:

```python
level_1_dim = 256
level_2_dim = 64
encoding_dim = 16

from keras import regularizers
from keras.layers import Input, Dense
from keras.models import Model, model_from_json

class CustomRegularizer (regularizers.ActivityRegularizer):
  def __call__ (self, x):
    # this is just for purposes of demonstrating a bug
    return super(CustomRegularizer, self).__call__(x)

input_img = Input(shape=(784,))
encoded = Dense(level_1_dim, activation='relu')(input_img)
encoded = Dense(level_2_dim, activation='relu')(encoded)
encoded = Dense(encoding_dim, activation='relu', activity_regularizer=CustomRegularizer(1e-6))(encoded)
decoded = Dense(level_2_dim, activation='relu')(encoded)
decoded = Dense(level_1_dim, activation='relu')(decoded)
decoded = Dense(784, activation='sigmoid')(decoded)

autoencoder = Model(input=input_img, output=decoded)

encoder = Model(input=input_img, output=encoded)

with open('auto.encoder.model', 'w') as outfile:
  outfile.write(encoder.to_json())

"""
# This was the workaround, no longer required
import keras.regularizers
keras.regularizers.CustomRegularizer=CustomRegularizer
"""


with open('auto.encoder.model', 'r') as infile:
  encoder = model_from_json(infile.read(), custom_objects={"CustomRegularizer":CustomRegularizer})
  
#this will also work now
d = Dense(encoding_dim, activation='relu', activity_regularizer='CustomRegularizer')
```

Cheers,
Ben

**Comment by bstriner** [comment]
@FeralWhippet this PR just got merged. https://github.com/fchollet/keras/pull/5012

Please try it out, let me know if it fixes your issue, and close the issue if it does.
