### ISSUE TITLE
Tokenizer's nb_words not taking effect when fit_on_texts is run

### ISSUE THREAD

**Issue by bluelight773** [fchollet/keras#4998]
Hello, I can't figure out if I'm doing something wrong, but Tokenizer always seems to ignore the nb_words parameter I provide it and tokenize ALL words rather than just the top nb_words.
I'm running Python 2.7. Note that I ran into this issue while working on a dataset with over 1000 unique words, and any lower value I set for nb_words (e.g. 10, 100, 500..) was ignored.  Below is a simple example to illustrate quickly what I'm getting.   Thank you.

```
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(nb_words=10)
tokenizer.fit_on_texts(['apple book car dog egg fries girl ham inside jam knife leg monkey nod open pear question rough stone tree umbrella voice wax xylophone year zoo'])
print(len(tokenizer.word_index))
# comes out as 26 rather than 10
```

**Comment by ddofer** [comment]
I have the same issue when fitting on char level

**Comment by ivanvladimir** [comment]
I have the same issue

**Comment by Achilles-96** [comment]
Any solution to this?

**Comment by nijianmo** [comment]
Same question here! For word level.

**Comment by ddclone** [comment]
I`m running Python 3.6 and keras with TensorFlow backend, have the same issue.

**Comment by sararob** [comment]
I'm also having this issue with Python 3.6 and TensorFlow. My `Tokenizer` looks like this:

```
tokenize = text.Tokenizer(num_words=5000,
                          lower=True, split=" ", char_level=False,
                          filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n')
```

It works, it just doesn't take into account the `num_words` param.

**Comment by suissemaxx** [comment]
Same problem here. Any news on this issue?

**Comment by suissemaxx** [comment]
I found this thread that explains how Tokenizer apparently correctly interprets `num_words`:

https://github.com/fchollet/keras/issues/7551

**Comment by shafy** [comment]
Is this behavior intended? If yes, it would be very useful to have a parameter to only get the `word_index` for the top `nb_words`

**Comment by caprone** [comment]
same issue...

**Comment by hsiaoyi0504** [comment]
@shafy To get the top nb_words, you can simply use index under nb_words, since the word_index is created by https://github.com/keras-team/keras/blob/018af47bc87b6a48e64c2fc9cfacf595e0f36287/keras/preprocessing/text.py#L191

**Comment by shafy** [comment]
@hsiaoyi0504 what do you mean by "under"?

**Comment by hsiaoyi0504** [comment]
@shafy I mean you can pass the word to word_index and check if the mapping index is under the `nb_words`. It's not a hard task. If the word_index dictionary is large enough, you may want generate a filtered version rather than doing this on the fly.
