### ISSUE TITLE
Fix in cifar example

### ISSUE THREAD

**Issue by aloisg** [fchollet/keras#50]
Hi,

I add an error on the cifar10 example.
Traceback (most recent call last):
  File "cifar10_cnn.py", line 49, in <module>
    model.add(Flatten(64*8*8))
TypeError: __init__() takes exactly 1 argument (2 given)

You should remove the argument for the flatten layer, and it works !

**Comment by fchollet** [comment]
The API for Flatten changed recently. Thanks for pointing this out! It's fixed now.
