### ISSUE TITLE
Error importing modules when loading Keras model

### ISSUE THREAD

**Issue by darkaeon10** [fchollet/keras#5007]
I'm trying to save and load a model, according to https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model

However, when loading the model, this error pops up: **NameError: name 'MaxPooling1D' is not defined**. It seems that loading the model fails to import the necessary modules.

Here's my code snippet:

    model.save("keras_model.h5")
    del model
    model = load_model('keras_model.h5')

The import error points to my custom-pooling function, which finds the element-wise max, min, and avg for all input tensors, then concatenates them.

    def max_min_avg_pooling_context(x):
        max_arr = MaxPooling1D(MAX_SEQUENCE_LENGTH-2)(x)
        min_arr = -K.pool2d(-x, pool_size=(MAX_SEQUENCE_LENGTH-2,1), strides=(MAX_SEQUENCE_LENGTH-2,1), border_mode="valid", dim_ordering="th", pool_mode='max')
        avg_arr = AveragePooling1D(MAX_SEQUENCE_LENGTH-2)(x)

        return K.concatenate([max_arr, min_arr, avg_arr], axis=1)

Notes:
*  I'm using Keras 1.1.1. I don't want to update to the latest version because it might cause problems with Theano, which I really had a hard time installing on Windows.
* I have compiled the model before saving it.
* Also tried saving the model architecture and weights separately (according to this tutorial: http://machinelearningmastery.com/save-load-keras-deep-learning-models/). Same error.

**Comment by bstriner** [comment]
Can't tell if it's your code or keras without a runnable snippet.

Your custom pooling function does seem weird and could be causing the issue. There is nothing wrong with breaking things up into layers. Try something like this. You may have to add the output_shape parameter as well.

```python
max_arr = MaxPooling1D(MAX_SEQUENCE_LENGTH-2)(h)
min_arr = Lambda(lambda x:-K.pool2d(-x, pool_size=(MAX_SEQUENCE_LENGTH-2,1), strides=(MAX_SEQUENCE_LENGTH-2,1), border_mode="valid", dim_ordering="th", pool_mode='max'))(h)
avg_arr = AveragePooling1D(MAX_SEQUENCE_LENGTH-2)(h)
concat = merge([max_arr, min_arr, avg_arr], mode='concat')
```

Cheers

**Comment by darkaeon10** [comment]
My implementation of an elementwise-min is rather strange, because I couldn't find a simple way to do it. Do you have any recommendations to achieve the same in a simpler way (E.g. [1,2,3], [1,1,1], [-1,0,3] results to a minimum vector of [-1, 0, 1]? 

I'm not sure if your suggestion will work in my case, because the custom pooling is defined as a function, and used like this when constructing the architecture:

    context_sequence_input = Input(shape=(MAX_CONTEXTUAL_WORDS,), dtype='int32')
    context_embedding_layer = Embedding(embedding_matrix.shape[0],
                                    embedding_matrix.shape[1],
                                    weights=[embedding_matrix],
                                    input_length=MAX_CONTEXTUAL_WORDS,
                                    trainable=False)
    aux_embedded_sequences = context_embedding_layer(context_sequence_input)
    context_network = Lambda(max_min_avg_pooling_context, output_shape=max_min_avg_output_shape,  name="custom_pooling")(aux_embedded_sequences)
    context_network = Flatten()(context_network)

But I'll try it out. Thanks for the suggestion!

**Comment by bstriner** [comment]
On a side note, can you fix the import error if you put `from keras.... import MaxPooling...` inside your function definition? 

You don't need the entire max pooling to be done in a single lambda. Might work better as separate layers. You could also make max pooling as a Model with several layers, then add that model to another model.

If you just want to calculate a minimum over several tensors, use `merge([...],mode=concat)` to put them into a single tensor then use `Lambda(lambda x: K.min(x, axis=...))`.

Alternatively, you had a good idea with using the negative. Use a merge then a `Lambda(lambda x:-x)` and a `MaxPooling2D`.

Note that min pooling might not work with relus. When relu is 0, it is both the min and has 0 gradient. Might work with other activation functions.

**Comment by darkaeon10** [comment]
Thanks! I tried placing the import statements inside the custom pooling function, and now the original error is gone. But now I'm encountering this one :
`Optimizer` weight shape (3, 1, 200, 200) not compatible with provided weight shape (600, 64)

Seems to be similar to this issue: [https://github.com/fchollet/keras/issues/5014](url)

Regarding splitting the functionality into separate layers, I guess I could try that. Any specific reason as to why it would work better? 

Thanks for the tip regarding min-pooling not working with relus. I'm using tanh, is that alright? I'm not too adept at the theoretical basis for neural nets, so I don't understand why relu won't work with min pooling. I'd appreciate if you could elaborate? Or at least point me to a resource I can read up on?

**Comment by btlk** [comment]
Good afternoon.

I've encountered what seems to be the same issues as OP'd reported.

I have 2 stateless functions
```python
def slice_channel(inputs, channel):
  return Lambda(
    lambda x: tf.expand_dims(x[:, :, :, channel], 3)
  )(inputs)

def fuse_convolutions(inputs):
  return Lambda(
    lambda x: Concatenate(axis = 3)([
      (slice_channel(x, i) + slice_channel(x, j)) / 2.0
      for i in range(4) for j in range(i + 1, 4)
    ])
  )(inputs)
```
First one is known to work perfectly fine in save/load pipeline, but 2nd one outputs 
```python
NameError: name 'Concatenate' is not defined
```
whenever I try to load compiled and saved model. I tried both saving it with Model.save, by separating arch and weights, with ModelCheckpoint - same result. When I tried @bstriner suggestion to import concatenation inside the function, using ModelCheckpoint resulted in this after the first epoch of training:
```python
  File "venv\lib\site-packages\keras\engine\topology.py", line 2434, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "venv\lib\site-packages\keras\models.py", line 103, in save_model
    }, default=get_json_type).encode('utf8')
  File "C:\Program Files\Python35\Lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python35\Lib\json\encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python35\Lib\json\encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "venv\lib\site-packages\keras\models.py", line 73, in get_json_type
    'config': obj.get_config()}
TypeError: get_config() missing 1 required positional argument: 'self'
```
Training without callback and saving arch and weights separately worked, but after I tried to load model, it failed:
```python
  File "src\train.py", line 156, in load_model
    loaded_model = model_from_json(loaded_model_json)
  File "venv\lib\site-packages\keras\models.py", line 333, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "venv\lib\site-packages\keras\layers\__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "venv\lib\site-packages\keras\utils\generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "venv\lib\site-packages\keras\engine\topology.py", line 2378, in from_config
    process_layer(layer_data)
  File "venv\lib\site-packages\keras\engine\topology.py", line 2347, in process_layer
    custom_objects=custom_objects)
  File "venv\lib\site-packages\keras\layers\__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "venv\lib\site-packages\keras\utils\generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "venv\lib\site-packages\keras\layers\core.py", line 706, in from_config
    function = func_load(config['function'], globs=globs)
  File "venv\lib\site-packages\keras\utils\generic_utils.py", line 204, in func_load
    closure=closure)
TypeError: arg 5 (closure) must be None or tuple
```

Is there any workaround to this?

**Comment by bstriner** [comment]
You're nesting functions and lambdas strangely.

`slice_channels` is a function that creates and applies a Lambda. `Concatenate` is a keras layer. You don't need to use keras layers inside Lambda expressions. Inside the Lambda, just manipulate the tensors using keras backend or whatever you want to do.

So one option is to do everything in one layer like you're doing, except use backend functions instead of layers.

```python
def fuse_convolutions(inputs):
  return Lambda(
    lambda x: tf.concatenate([
      (tf.expand_dims(x[:,:,:,i], 3) + tf.expand_dims(x[:,:,:,j],3)) / 2.0
      for i in range(4) for j in range(i + 1, 4)
    ], axis=3)
  )(inputs)
```

Another option, which may be easier to understand, is to break things out into layers. This way `fuse_convolution` isn't making one giant Lambda layer. It is creating a structure of Concatenate, Average and slice_channel layers. (I probably missed a lot of parentheses below but you should be able to get it working.)

```python
def slice_channel(inputs, channel):
  return Lambda(
    lambda x: tf.expand_dims(x[:, :, :, channel], 3)
  )(inputs)

def fuse_convolutions(inputs):
  return Concatenate(axis=3)([
    Average()([slice_channel(x, i), slice_channel(x, j)])
   for i in range(4) for j in range(i + 1, 4)])
```

Cheers
