### ISSUE TITLE
tests fail on cloned repo

### ISSUE THREAD

**Issue by kirk86** [fchollet/keras#5011]
Hi everyone, I just cloned the repo and run the `py.test` and I got the following result.

```
../../../../anaconda2/lib/python2.7/site-packages/theano/gof/op.py:633: ValueError
======================================== 5 failed, 252 passed in 2327.59 seconds =========================================
```
My OS is Ubuntu 16.04 and my python version is 2.7.13 installed via anaconda. Also Theano 0.8.2, tensorflow 0.12.1 and Keras 1.2.0.

The failed tests are the following:
```
gw1] FAILED tests/keras/backend/test_backends.py::TestBackend::test_nn_operations 
[gw0] FAILED tests/keras/backend/test_backends.py::TestBackend::test_function 
[gw1] FAILED tests/keras/backend/test_backends.py::TestBackend::test_random_normal 
[gw1] FAILED tests/keras/backend/test_backends.py::TestBackend::test_random_uniform 
[gw1] FAILED tests/keras/backend/test_backends.py::TestBackend::test_random_binomial 
```
Is that normal? Also I have tensorflow as my main backend.

I'm trying to do a pull request to add another model `u-net` in the `applications` but I can't proceed since I want to also run the tests after the addition of the new model.

**Comment by kirk86** [comment]
Any response from developers?

**Comment by patyork** [comment]
First I'd check that Keras is up to date from github, then I'd ensure that the tests are running on CPU and not the GPU (tests are not setup to allow TF to run on the GPU).

**Comment by kirk86** [comment]
@patyork Keras is up to date 1.2.0. The tests are all run on cpu since I don't have available gpu. TF give the above errors but if I change backend to theano and run again the tests then I get even more errors.

**Comment by patyork** [comment]
The original errors (regarding `backend/test_backends.py`) are independent of your backend (it tests both Theano and TF at the same time).

Without more information (the actual errors) I can't be of much help. All tests pass on the Travis build and on my fork.

**Comment by kirk86** [comment]
ok I'll put the errors, I'm running the test again...

**Comment by fchollet** [comment]
Since tests pass on Travis, any failure on your end is due to having
different library versions from those used on Travis (or possibly a
different environment, although that is less likely). Check your TF and
Theano versions.

**Comment by kirk86** [comment]
Here's a complete log of the tests 
[logs.txt](https://github.com/fchollet/keras/files/705501/logs.txt)

Libraries and their respective versions from anaconda distribution
```
Theano 0.8.2,
tensorflow 0.12.1
Keras 1.2.0.
python 2.7.13
```

**Comment by kirk86** [comment]
For a moment I thought that I might had found the error because by looking at the travis config I saw `coverage=3.7.1` and I had `4.2` installed so I changed the version to depict the one in the travis config re run the tests and but still got errors. Maybe I'm running them in the wrong way?

`py.test tests/ ?`

Someone let me know if that's the correct way to running the tests because in the travis config there are 3 different scenarios...

**Comment by patyork** [comment]
It's looks like, from all of the Theano error messages, that you're running Theano with `compute_test_value=raise`, or your .theano config is corrupted. Check [this issue.](https://github.com/Theano/Theano/issues/1439)

**Comment by kirk86** [comment]
Deleting `.theano` did the trick. Thanks a lot.

**Comment by patyork** [comment]
No worries, and good luck with your new application!
