### ISSUE TITLE
pad_sequences broken for numpy arrays

### ISSUE THREAD

**Issue by bnaul** [fchollet/keras#5019]
As of https://github.com/fchollet/keras/commit/6e03136116c6cfd58a912e575c1980eeb7cd6809:

```
        for s in sequences:
>           if s:
E           ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Tests pass because all the test data is in Python lists. @fchollet was this changed to also handle another case or was it simply for style? If it's the latter I'd say just revert to checking `if len(s) > 0` instead of `if s`.

**Comment by fchollet** [comment]
Fixed, thanks for the report.
