### ISSUE TITLE
How to add FFT (or real FFT) in backends

### ISSUE THREAD

**Issue by keunwoochoi** [fchollet/keras#5020]
TensorFlow doesn't seem to have a rfft but only [fft](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard0/tf.fft.md).

Theano has [rfft](http://deeplearning.net/software/theano_versions/dev/library/tensor/fft.html) but no fft.

I think rfft should be fine for most of the cases. Therefore I'd like to add a backend function under the name of `rfft` which uses theano's `rfft` and tensorflow's `fft` (This should be denoted in docstrings). Would it be okay?

**Comment by keunwoochoi** [comment]
[Note](https://github.com/tensorflow/tensorflow/blob/584d4921014db921a8f4722749adff09737826a8/tensorflow/python/kernel_tests/py_func_test.py#L71) for tf implementation of rfft.
```python
    # a bit excotic function (rfft)
    with self.test_session():
      x = constant_op.constant([1., 2., 3., 4.], dtypes.float32)

      def rfft(x):
        return np.fft.rfft(x).astype(np.complex64)

      y, = script_ops.py_func(rfft, [x], [dtypes.complex64])
      self.assertAllClose(y.eval(), np.fft.rfft([1., 2., 3., 4.]))

```

**Comment by howthebodyworks** [comment]
@keunwoochoi you are my hero. I was just trying to work this out myself for some extensions to [kapre](https://github.com/keunwoochoi/kapre). I would **love** an rfft.

**Comment by keunwoochoi** [comment]
Great :) A theano-only Stft was added and I had no time for tf backend. Please keep me updated!
