### ISSUE TITLE
Dimension not matching in LSTM

### ISSUE THREAD

**Issue by indra215** [fchollet/keras#5030]
Hi,

I want to train a LSTM that learns given a frame of video, predict the next frame of the video. I extracted 20 frames from each video and each frame is passed through a CNN to get a 512 dimensional feature embedding for the frame i.e., each frame is now represented by a 512 dimensional feature vector and I have 20 frames for each video. 

So my input has shape of X_train = (no_videos, 20, 512) and similarly my output has shape of Y_train = (no_videos,20,512) which are the shifted frames.

My model looks like this but I am getting this error,

```
model = Sequential()
model.add(LSTM(128, input_shape=X_train.shape[1:], return_sequences=True))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer='sgd')
print(model.summary())

model.fit(X_train, Y_train, nb_epoch=5, batch_size=batchSize)

```

```
Traceback (most recent call last):
  File "learn_embedding_vids.py", line 37, in <module>
    model.fit(X_train, Y_train, nb_epoch=5, batch_size=batchSize)
  File "/drive2/dhruv/anaconda/anaconda2/lib/python2.7/site-packages/keras/models.py", line 627, in fit
    sample_weight=sample_weight)
  File "/drive2/dhruv/anaconda/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1052, in fit
    batch_size=batch_size)
  File "/drive2/dhruv/anaconda/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 983, in _standardize_user_data
    exception_prefix='model target')
  File "/drive2/dhruv/anaconda/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 111, in standardize_input_data
    str(array.shape))
Exception: Error when checking model target: expected lstm_1 to have shape (None, 20, 128) but got array with shape (500, 20, 512)

```
Can someone please help me how to train this model ?

Thanks in advance.

**Comment by joelthchao** [comment]
Please check shape of `Y_train`, it has shape `(500, 20, 512)` which does not match with `(None, 20, 128)`.

**Comment by indra215** [comment]
Yeah so for that what change should be done in the code or model ? I've changed the number of hidden units in LSTM to 512 and it started training. 

Is this the only solution or is there anything else ?

**Comment by mbollmann** [comment]
`Y_train` has shape `(500, 20, 512)`, that means whatever the model output is has to be the same shape, otherwise you couldn't train it using `Y_train`.

Setting hidden units in your LSTM to 512 is not the only solution: you could also add more layers after the LSTM, as long as the final layer returns output of shape `(500, 20, 512)`.

**Comment by indra215** [comment]
Thanks everyone for the help. 

I have one more doubt in getting the activations of the LSTM layer.

Now I need the activation of the LSTM layer for each video i.e. I pass the training data to the model frame by frame. I give one frame and the model predicts the next frame. I discard this prediction and give the next frame and so on. Now after the 20 frames (no of frames extracted from each video), I want to extract the activations of the LSTM layer after passing all the 20 frames.  I finally want a numpy array of activations with shape activations = (no_videos, 512).

Can anyone please help how to do this ?

Thanks in advance.

**Comment by mbollmann** [comment]
@indra215 It sounds to me like you just want the last timestep's output, but I'm not sure of your exact use case.  If you want to train on "predicting the next frame", but then only extract the LSTM activations for some input data, you could build a function to do this like described in the Keras FAQ here: https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer

You can then simply discard all timesteps of the output except for the last one (`output = output[:, -1, :]`).
