### ISSUE TITLE
run example(mnist.rnn and mnist.mlp) fail, ld: library not found for -lopenblas

### ISSUE THREAD

**Issue by seagullyoyo** [fchollet/keras#5040]
01251	static PyMethodDef MyMethods[] = {
01252		{"instantiate", instantiate, METH_VARARGS, "undocumented"} ,
01253		{NULL, NULL, 0, NULL}
01254	};
01255	PyMODINIT_FUNC init4a2e2b4eb5ab1f2c0542d71bf970840d(void){
01256	   import_array();
01257	   (void) Py_InitModule("4a2e2b4eb5ab1f2c0542d71bf970840d", MyMethods);
01258	}
01259
===============================
Problem occurred during compilation with the command line below:
/usr/bin/clang++ -dynamiclib -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -march=x86-64 -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -undefined dynamic_lookup -I/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/Library/Python/2.7/site-packages/theano/gof -fvisibility=hidden -o /Users/yoyo/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.10-64/tmpWY7nv9/4a2e2b4eb5ab1f2c0542d71bf970840d.so /Users/yoyo/.theano/compiledir_Darwin-14.5.0-x86_64-i386-64bit-i386-2.7.10-64/tmpWY7nv9/mod.cpp -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib -lopenblas
**ld: library not found for -lopenblas
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

Traceback (most recent call last):
  File "mnist_cnn.py", line 79, in <module>
    verbose=1, validation_data=(X_test, Y_test))
  File "/Library/Python/2.7/site-packages/keras/models.py", line 664, in fit
    sample_weight=sample_weight)
  File "/Library/Python/2.7/site-packages/keras/engine/training.py", line 1084, in fit
    self._make_test_function()

**Comment by nouiz** [comment]
What are your theano flag? I think you define blas.ldflags in your
.theanorc or in the env variable THEANO_FLAGS. Remove that.

Make sure to use Theano dev version, not the last release (0.8.2)

**Comment by seagullyoyo** [comment]
it works, thx~
