### ISSUE TITLE
how to write a bilinear interplolation layer?

### ISSUE THREAD

**Issue by hustxujinkang** [fchollet/keras#5043]
I want to implement a bilinear interpolation layer just as in caffe which do filter-wise upsampling. The upsample2d now just do repeat. Here is my code, does anybody know what's wrong:
from theano.tensor.nnet.abstract_conv import bilinear_upsampling
```
`class Deconv2D(Layer):
    def __init__(self, ratio, **kwargs):
        self.ratio = ratio
        super(Deconv2D, self).__init__(**kwargs)
    def build(self, input_shape):
        super(Deconv2D,self).build(input_shape)
    def call(self, x, mask=None):
        return bilinear_upsampling(x, ratio=self.ratio)
    def get_output_shape_for(self, input_shape):
        return (input_shape[0], input_shape[1],
                input_shape[2] * self.ratio, input_shape[3] * self.ratio)`
```

here are my error message:
raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
theano.tensor.var.AsTensorError: ('Cannot convert (None, None, Elemwise{mul,no_inplace}.0, Elemwise{mul,no_inplace}.0) to TensorType', <type 'tuple'>)

**Comment by 9thDimension** [comment]
What happened with this?

I'm also very interested in having this capability in Keras.

**Comment by hustxujinkang** [comment]
@9thDimension Just update to the lasted version of Theano, the above code works!
