### ISSUE TITLE
`ZeroDivisionError` when using `class_mode=None` with `ImageDataGenerator.flow_from_directory()`

### ISSUE THREAD

**Issue by yati-sagade** [fchollet/keras#5044]
[Here's the script][1] to run to see the exception. One can run it like `python imggen_reproduce.py /tmp/somedir_that_you_donot_care_about`. After a quick glance at the source, it seems like `class_mode` is not used in the `DirectoryIterator` constructor to prevent `self.nb_sample` from being set to `0`, which ultimately becomes `self.n` in the base `Iterator`.

Some reporters of a previous bug (#4699) have reported that this "works" when you create an additional directory under the directory passed to `flow_from_directory()`. However, I don't think this is ideal, for semantically, there _is_ no class/label when dealing with test images.

My proposal to fix this is to set self.nb_sample = number of valid image files in the input directory when `self.class_mode is None and not self.classes`, in `DirectoryIterator::__init__`. The second clause in the condition will help prevent breakage of code that has hacked its way around this issue by creating an additional directory (or we don't have to be afraid of breaking, it's up to you). Please let me know if you are okay with this, and if you have any ideas (including calling this issue a non-issue :)), and I can accordingly prepare a quick PR (or not).

[1]: https://gist.github.com/yati-sagade/ff309678a6d6ec849c488b1f9a5fa6b3

**Comment by bloudermilk** [comment]
Just wanted to say that I also found this behavior confusing. I'm attempting to use `DirectoryIterator.flow_from_directory` on a directory containing test images (not labeled) which I want to pass to `predict_generator`. I had to put all my images in an arbitrarily named folder in order to use the function.
