### ISSUE TITLE
Shouldn't we encourage users to use stackoverflow for questions?

### ISSUE THREAD

**Issue by keunwoochoi** [fchollet/keras#5047]
This board is not too bad, but for me it's obvious that stackoverflow is more suitable for question/answers cuz..
 - well, in general, it's the best q&a platform for programmers
 - maybe better search engine optimisation, so no repeating questions
 - answers are editable

Then we could use here for more like really *issues* of Keras.

**Comment by patyork** [comment]
>Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

We already do; unfortunately people tend to not read the guides in the issue box before "Ctrl+A Bkspc" -> "Submit New Issue".

**Comment by jmhessel** [comment]
It is strange -- it seems like the keras issues are disproportionately implementation questions rather than actual bugs when compared to other libraries.

**Comment by keunwoochoi** [comment]
Even I did haha, cuz I thought I know what it says. Hm.. then probably we should discourage people to post answer here?

**Comment by keunwoochoi** [comment]
@jmhessel I agree with it, probably Keras got more beginners -- on GitHub, machine learning. etc.

**Comment by howthebodyworks** [comment]
One issue here is that the [documentation prominently mentions also a slack channel and a google group](https://keras.io/#support) on the front page and omits stackoverflow. Both the slack channel and google gropu which are often frustrating. Perhaps we are getting cross-posts here from users in those forums?
