### ISSUE TITLE
Graph add_node problem (fails on GPU)

### ISSUE THREAD

**Issue by ipod825** [fchollet/keras#505]
#Update: the code fails only on gpu

I am doing an experiment requiring a special topology. So I choose to use Graph.
But I got some problem when adopting add_node function.

A simplified topology of my case is:
X0 -> D0 -> Combo -> SoftMax -> Output
X1 -> D1 -/
where there are two input channel X0, X1.
I need to concatenate D0 and D1 in Combo layer.

If only X0 is used, every thing goes fine. However, if X1 is added, the code fails and I do not know how to fix that with the error message.

Here's my code, changing couldRun to False makes the code fails.

<pre><code>
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from keras.models import Graph
from keras.layers.core import Dense, Activation
from keras.utils import np_utils, generic_utils
import numpy as np

#Changing this to False results in fail of the code
couldRun = True

input_dim=5
nb_sample=256
nb_class = 4

X=np.zeros((2,nb_sample, input_dim)) #Two channel: X0, X1
y=np.zeros((nb_sample,1))

if __name__ == '__main__':

    ##Topology
    #X0 -> D0 -> Combo -> SoftMax -> Output
    #X1 -> D1 -/

    model = Graph()
    model.add_input(name='X0')
    model.add_node(Dense(input_dim, 1), name='D0', input='X0')

    if couldRun:
        model.add_node(Dense(1, nb_class), name='Combo', input='D0', merge_mode='concat')
    else:
        #This does not work
        model.add_input(name='X1')
        model.add_node(Dense(input_dim, 1), name='D1', input='X1')
        model.add_node(Dense(2, nb_class), name='Combo', inputs=['D0', 'D1'], merge_mode='concat')

    model.add_node(Activation('softmax'), name='Softmax', input='Combo')
    model.add_output(name='output', input='Softmax')

    model.compile('sgd', {'output':'categorical_crossentropy'})
    model.fit({
        'X0':X[0,:,:],
        'X1':X[1,:,:],
        'output':np_utils.to_categorical(y, nb_classes=nb_class)
        })

</code></pre>

**Comment by pranv** [comment]
Either change `merge_mode` to `sum` or, change the `Combo` layer to `Dense(2, nb_class)`

**Comment by ipod825** [comment]
I change <code>Combo<code>  to <code>Dense(2, nb_class)<code> but the code still fails.

**Comment by ipod825** [comment]
I found that if I run the code could run on cpu. But it fails on gpu.
The error message is:
<pre><code>
Traceback (most recent call last):
  File "./issue.py", line 44, in <module>
    'output':np_utils.to_categorical(y, nb_classes=nb_class)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 586, in fit
    validation_split=validation_split, val_f=val_f, val_ins=val_ins, shuffle=shuffle, metrics=metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 168, in _fit
    outs = f(*ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
ValueError: dimension mismatch in args to gemm (128,1)x(2,4)->(128,4)
Apply node that caused the error: GpuDot22(GpuJoin.0, Combo_W)
Inputs types: [CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(128, 1), (2, 4)]
Inputs strides: [(1, 0), (4, 1)]
Inputs values: ['not shown', 'not shown']

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

<pre><code>

**Comment by pranv** [comment]
Change the `Combo` layer in the `else:` part. And run it with `couldRun` to `False`

**Comment by ipod825** [comment]
Thank you for your advise. I did change the code, and I just found that it could run on cpu while it still fails on gpu.

**Comment by fchollet** [comment]
Update Theano to the latest version (get it from the git repo, not pip). I believe this is a Theano issue that was fixed a while back.

**Comment by fchollet** [comment]
Assumed solved.

**Comment by ipod825** [comment]
Sorry, I forgot to reply. Problem solved. Thank you for your help.

**Comment by stevenspielberg8** [comment]
Thank you. I had the same issue I got it resolved by installing the latest version of theano from Github (not from pip)
