### ISSUE TITLE
meeting ValueError after adding LSTM layer

### ISSUE THREAD

**Issue by NancyZxll** [fchollet/keras#506]
Hello All,
   I met the same error which is shown "ValueError: new_order[2] is 2, but the input only has 2 axes." when I want to add a LSTM in my model. In addition, I also added "return_sequences=True" in my code, but the error still comes..

   Here is my code:
=========================================================================
model = Sequential()

model.add(Convolution2D(100, 1, 2, 5, border_mode='valid')) 
model.add(Activation('tanh'))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(49600,peptidemaxLen, init='normal')) 
model.add(Activation('softmax'))

model.add(LSTM(peptidemaxLen, peptidemaxLen, return_sequences=True))
model.add(Dropout(0.2))

============================================================================
Before adding LSTM layer, the code can be run successfully. However, the error comes after adding the LSTM layer.

Could any of you can help me solve this problem? I am very appreciated for your great help!

**Comment by fchollet** [comment]
LSTM layers (like all recurrent layers) look at 3D inputs (samples, time, features). Here you're trying to apply one to a 2D input (samples, features).

**Comment by NancyZxll** [comment]
Thank you fchollet. But where I can add the time input? Can't I use convolution2D and Dense before LSTM? But I saw other examples can add LSTM after the convolution2D and Dense.. I am a very beginner of DNN, sorry for my poor understanding..

**Comment by fchollet** [comment]
You can use `TimeDistributedDense` or `Embedding` before a LSTM. In the near future you will be able to use convolutional layers as well.

**Comment by NancyZxll** [comment]
I changed my code to :
choice 1:
==================================================
model.add(TimeDistributedDense(49600,peptidemaxLen, init='normal'))
model.add(Activation('tanh'))

#model.add(Embedding(max_features, 128))
model.add(LSTM(peptidemaxLen, peptidemaxLen, return_sequences=True))
model.add(Dropout(0.2))
==================================================
error is: ValueError: new_order[2] is 2, but the input only has 2 axes.

Choice 2:
==================================================
model.add(Dense(49600,1000, init='normal'))
model.add(Activation('tanh'))

model.add(Embedding(1000, 128))
model.add(LSTM(128, peptidemaxLen, return_sequences=True))
model.add(Dropout(0.2))
==================================================
error is: TypeError: index must be integers

I think all the indexes should be integers...
