### ISSUE TITLE
Keras data streaming reader and training in batch

### ISSUE THREAD

**Issue by sun-peach** [fchollet/keras#5068]
Hi, dear all,

I am using keras to build up a end-to-end ASR system with attention model. Keras has all the functions I need for building the model. However, the problem right now I have is my data is too large to fit the memory. So I have to use data streaming. Is there any way I can stream the data and then send the partition into training as mini-batch?

Thank you very much! I am new to Keras, sorry for the rookie question.

**Comment by patyork** [comment]
Read about the fit_generator functionality.  There is documentation on it, and several examples utilize it.

-----Original Message-----

**Comment by sun-peach** [comment]
@patyork Thank you. I also check find the question in FAQ and a CIFAR10 example.
However, for the CIFAR10 example, I have problem on this piece of code:
model.fit_generator(datagen.flow(X_train, Y_train,
                                     batch_size=batch_size),
                        samples_per_epoch=X_train.shape[0],
                        nb_epoch=nb_epoch,
                        validation_data=(X_test, Y_test))
If I don't mistake, it means for each batch, it will do nb_epoch epochs till the last batch. My personal understanding is that it may be better to do all the batches within 1 epoch and do couple of epochs. If this is right, I should use for loop, right?

Thank you very much!

**Comment by patyork** [comment]
batch_size : minibatch size.
samples_per_epoch : the number of examples/samples that the network will train on per "epoch".
nb_epochs : the number of epochs to run.

The total number of examples the network will see and train on is samples_per_epoch * nb_epochs.

**Comment by sun-peach** [comment]
Thank you. I will close the issue.
