### ISSUE TITLE
keras.backend.tile() not documented

### ISSUE THREAD

**Issue by nelson-liu** [fchollet/keras#5072]
Hi,
It seems like `keras.backend.tile()` ([here in theano backend](https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L685) and [here in TF](https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L1556)) is not documented in the [docs for `keras.backend`](https://keras.io/backend/).

is this intended, or is it a mistake with the docs rendering? Is `keras.backend.tile()` meant to be a publicly useable function?

Thanks!

**Comment by keunwoochoi** [comment]
This is strange. @fchollet Is there any mistake on https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L1562 that blocks it to appear in the document?

**Comment by nelson-liu** [comment]
this is fixed
