### ISSUE TITLE
How dropout_U, dropout_W works in Recurrent Layers

### ISSUE THREAD

**Issue by baziotis** [fchollet/keras#5075]
I have a question regarding `dropout_U` and `dropout_W` in Recurrent Layers. My question is if the same mask is being applied on _all_ the timesteps or a different mask for each timestep.

**Comment by mbollmann** [comment]
https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L21

"same dropout mask for every temporal slice of the input"

**Comment by baziotis** [comment]
Nice, Thanks!
