### ISSUE TITLE
Bug on the save/load mechanism of version 1.2.0

### ISSUE THREAD

**Issue by datumbox** [fchollet/keras#5083]
I believe there is a bug on the save/load mechanism of version 1.2.0. The problem did not exist on version 1.1.2.

To reproduce the bug I'll be using the following code snippet taken from the Keras documentation: [Fine-tune InceptionV3 on a new set of classes](https://keras.io/applications/)

```python
from keras.preprocessing import image
generator = image.ImageDataGenerator().flow_from_directory('./data/cifar2-train', target_size=(224, 224), batch_size=32, class_mode='categorical', shuffle=True)

# ==== Start of Code Snippet from Keras Documentation: https://keras.io/applications/ ====
from keras.applications.inception_v3 import InceptionV3
from keras.preprocessing import image
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D
from keras import backend as K

base_model = InceptionV3(weights='imagenet', include_top=False)

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(1024, activation='relu')(x)
predictions = Dense(2, activation='softmax')(x)

model = Model(input=base_model.input, output=predictions)

for layer in base_model.layers:
    layer.trainable = False

model.compile(optimizer='rmsprop', loss='categorical_crossentropy')

model.fit_generator(generator, samples_per_epoch=1000, nb_epoch=1)

for i, layer in enumerate(base_model.layers):
   print(i, layer.name)

for layer in model.layers[:172]:
   layer.trainable = False
for layer in model.layers[172:]:
   layer.trainable = True

from keras.optimizers import SGD
model.compile(optimizer=SGD(lr=0.0001, momentum=0.9), loss='categorical_crossentropy')

model.fit_generator(generator, samples_per_epoch=1000, nb_epoch=1)
# ==== End of Code Snippet ====

model.save('./data/tempModel')
del model
from keras.models import load_model
model = load_model('./data/tempModel')
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 143, in load_model
    model.load_weights_from_hdf5_group(f['model_weights'])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2753, in load_weights_from_hdf5_group
    str(len(flattened_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 190 layers into a model with 2 layers.

**Comment by joelthchao** [comment]
Can you try setting trainable to True for all layers before saving model in the end? trainable might produce illusion to make model think it only has two layers.

**Comment by datumbox** [comment]
@joelthchao: Thanks for the reply.

If I set all the layers to trainable before the call on the save() I get the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 179, in load_model
    model.optimizer.set_weights(optimizer_weight_values)
  File "/usr/local/lib/python2.7/dist-packages/keras/optimizers.py", line 90, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Optimizer weight shape (96,) not compatible with provided weight shape (320,)

**Comment by bstriner** [comment]
Are you on theano or tensorflow? Can you check what your dim ordering is set to? Do you get the same error if you switch it to whatever the other one is?

Cheers

**Comment by datumbox** [comment]
I am using tensorflow and my dim ordering is set to tf. I'll check this out but can you reproduce the problem on your side?

**Comment by bstriner** [comment]
@datumbox I'm on windows, current git master of keras and theano. I threw some random images into some directories and your code sample runs fine for me. Does it work for you if you switch to th dim ordering?

**Comment by datumbox** [comment]
@bshickel: Thanks a lot for the prompt reply. Interesting, not being able to reproduce it complicates the matters...

I've tested the code on 2 computers (Ubuntu 14 with Tensorflow 0.12.0-rc1 & Ubuntu 16 with Tensorflow 0.12.1) and I get the same error. I am using the latest version of Keras (1.2.0) installed using pip. I also changed the dim ordering as you suggeted from tf to th and I get exactly the same exceptions.

Without setting trainable=true in all the layers:
Traceback (most recent call last):
  File "test.py", line 44, in <module>
    model = load_model('./data/tempModel')
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 143, in load_model
    model.load_weights_from_hdf5_group(f['model_weights'])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2753, in load_weights_from_hdf5_group
    str(len(flattened_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 190 layers into a model with 38 layers.

With trainable=true in all the layers:
Traceback (most recent call last):
  File "test.py", line 47, in <module>
    model = load_model('./data/tempModel')
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 179, in load_model
    model.optimizer.set_weights(optimizer_weight_values)
  File "/usr/local/lib/python2.7/dist-packages/keras/optimizers.py", line 90, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Optimizer weight shape (96,) not compatible with provided weight shape (320,)

**Comment by datumbox** [comment]
I tested again with Keras v1.2.1 and the problem is resolved.

@bstriner As you said earlier, you were testing using the latest snapshot at the time and you could not reproduce it. Possibly it was resolved on the repo immediately after the release of 1.2.0 and you were using a patched version. 

I'm closing the issue. :)
