### ISSUE TITLE
Indentation Problem in the TOC of the Documentation

### ISSUE THREAD

**Issue by MaigoAkisame** [fchollet/keras#5091]
![image](https://cloud.githubusercontent.com/assets/6993299/22125278/1426624a-de61-11e6-9007-aa50c1b0aecb.png)

The current item ("Sequential" and all sub-items in the figure) should be indented by one more tab. The current display is rather confusing.

I played with the CSS for a little bit but couldn't fix it easily.

**How to reproduce:** Open the page https://keras.io/models/sequential/ in Chrome, Firefox, or IE.

**Comment by fchollet** [comment]
Looks fine to me. This is what the theme is supposed to look like.
