### ISSUE TITLE
How to build parallel sub-network in Keras

### ISSUE THREAD

**Issue by sun-peach** [fchollet/keras#5092]
Hi, I am trying to build up a network with two parallel sub-networks in Keras.

Each sub-networks will take its own input, and on top of that the hidden value from the top layers of these two networks will be concatenated.

I plan to use Merge to do the concatenation. However, I am a little bit confused about the input part. How can I do that?

I have already build the model with sequential model object, like E1 = Sequential(); E2 = Sequential(), Can I use Model() to contain them, and use the Input function?

Thank you.

**Comment by patyork** [comment]
You should probably use the [functional API.](https://keras.io/getting-started/functional-api-guide/) You can also use the regular method (as you've started); there is an example of how to do that [here](https://github.com/fchollet/keras/blob/master/examples/babi_rnn.py).

**Comment by shenglin1987** [comment]
https://keras.io/getting-started/sequential-model-guide/
There is a good example to explain your case. See "Two merged LSTM encoders for classification over two parallel sequences".

**Comment by sun-peach** [comment]
Thank you very much!
