### ISSUE TITLE
Popping layer problem when merging it

### ISSUE THREAD

**Issue by kiyoon** [fchollet/keras#5096]
```python
from keras.layers import Merge
from keras.layers import Dense
from keras.models import Sequential

def pop_layer(model):
    if not model.outputs:
        raise Exception('Sequential model cannot be popped: model is empty.')

    model.layers.pop()
    if not model.layers:
        model.outputs = []
        model.inbound_nodes = []
        model.outbound_nodes = []
    else:
        model.layers[-1].outbound_nodes = []
        model.outputs = [model.layers[-1].output]
    model.built = False

if __name__ == "__main__":
    model = Sequential()
    model.add(Dense(32,input_dim=100))
    model.add(Dense(100))
    pop_layer(model)
    print model.layers[-1].output_shape

    model2 = Sequential()
    model2.add(Dense(32,input_dim=100))
    print model2.layers[-1].output_shape

    merged = Merge([model, model2], mode='concat')
    modelp = Sequential()
    modelp.add(merged)
    print modelp.layers[-1].output_shape

    from keras.utils.visualize_util import plot
    plot(modelp, show_shapes=True, to_file='modelp.png')
```

So basically model and model2 should be the same because I popped from model.

However, if you see the output plot (modelp.png), model and model2 has different output and the former seems not has been popped.

And if you check out the printed text to standard output, you'll see model and model2 has 32D output and modelp has 132D output, which doesn't make sense.

I only see this problem when I POP and MERGE the layer.

Thank you.

**Comment by mbollmann** [comment]
Why are you using a custom `pop_layer()` function? If I use `model.pop()` it works as expected.

**Comment by kiyoon** [comment]
Thanks! That was because I first used `model.layers.pop()` and it didn't worked, so I found the custom function at #2371. Now I got to know that `model.pop()` works. I'll close the issue.

**Comment by sakvaua** [comment]
I'm having the same problem with popping layers. They just magically reappear.
 model.pop is not working. It gives AttributeError: 'Model' object has no attribute 'pop'
eg.
```
model = ResNet50(weights='imagenet',include_top=False,input_shape=(3,360,640))
model.summary()
```
Last lines of the model summary are:
```
____________________________________________________________________________________________________
activation_253 (Activation)      (None, 2048, 12, 20)  0           merge_80[0][0]                   
____________________________________________________________________________________________________
avg_pool (AveragePooling2D)      (None, 2048, 1, 2)    0           activation_253[0][0]             
============================================================
Total params: 23,587,712
Trainable params: 23,534,592
Non-trainable params: 53,120
```

I want to remove AveragePooling2D layer.
```
model.layers.pop()
model.summary()
```

The layer is gone from the summary!
```
____________________________________________________________________________________________________
activation_203 (Activation)      (None, 2048, 12, 20)  0           merge_64[0][0]                   
====================================================================
Total params: 23,587,712
Trainable params: 23,534,592
Non-trainable params: 53,120
```
Now I add a bunch of new layers with
```
x = model.output
x=BatchNormalization(axis=1)(x)
x=Convolution2D(nf,3,3, border_mode='same')(x)
x=ELU()(x)
...
full_model = Model(input=model.input, output=predictions)
full_model.summary()
```
And the AveragePooling2D is back!
```
activation_203 (Activation)      (None, 2048, 12, 20)  0           merge_64[0][0]                   
____________________________________________________________________________________________________
**avg_pool (AveragePooling2D)      (None, 2048, 1, 2)    0           activation_203[0][0]**             
____________________________________________________________________________________________________
batchnormalization_10 (BatchNorm (None, 2048, 1, 2)    8192        avg_pool[0][0]                   
```

**Comment by mbollmann** [comment]
> I'm having the same problem with popping layers. They just magically reappear.
model.pop is not working. It gives AttributeError: 'Model' object has no attribute 'pop'

A `Model` object can have layers connected in arbitrary ways, not only sequentially.  It doesn't make sense conceptually to pop a layer from something that doesn't behave like a list.

**Comment by sakvaua** [comment]
Thanks,  that makes sense. So how do i remove the last (average polling) layer from resnet50?
It works fine BTW if i duse pop and don't add layers and use the model to precompute up to the last layer before the average pooling.

**Comment by alyato** [comment]
@kiyoon i use the keras function api and  wanna pop the last layer,adding new layer.
like this ,
> x = Dense(4096, activation='relu', name='fc2')(x)
x = Dense(1000, activation='softmax', name='predictions')(x)
model = Model(img_input, x)
pop_layer(model)
x = Dense(8, activation='softmax', name='predictions')(x)
return model

Is this right ? thanks

**Comment by kiyoon** [comment]
> @kiyoon i use the keras function api and wanna pop the last layer,adding new layer.
> like this ,
> 
> x = Dense(4096, activation='relu', name='fc2')(x)
> x = Dense(1000, activation='softmax', name='predictions')(x)
> model = Model(img_input, x)
> pop_layer(model)
> x = Dense(8, activation='softmax', name='predictions')(x)
> return model
> Is this right ? thanks

No, I recommend you to use `Sequential()` model rather than normal `Model()`, assuming that the model is actually sequential.

It would be something like:

``` python
model = Sequential()
model.add(Dense(4096, activation='relu', name='fc2'))
model.add(Dense(1000, activation='softmax', name='predictions'))
model.pop()
```

**Comment by alyato** [comment]
@kiyoon  That's mean that  there  haven't been  the `model.pop`function in the keras function api. And if  i want to  pop the last layer, i have to use the `Sequential()  model`

**Comment by kiyoon** [comment]
@alyato Yes there's no pop function for `Model`, because `Model` is not necessarily sequential. Popping from non-sequential model doesn't make sense at all. So if you want to pop, use sequential model.
