### ISSUE TITLE
Scikit-learn API bug

### ISSUE THREAD

**Issue by bottydim** [fchollet/keras#5103]
Keras 1.2.1 introduces a small bug in the sckit-learn API on line:
https://github.com/fchollet/keras/blob/master/keras/wrappers/scikit_learn.py#L87
def get_params(self, _):
Since the base.py calls the function with an explicit parameter name
https://github.com/scikit-learn/scikit-learn/blob/0.18.1/sklearn/base.py#L67
 new_object_params = estimator.get_params(deep=False)

TypeError: get_params() got an unexpected keyword argument 'deep' is thrown

**Comment by powerpuffgirl87** [comment]
Im facing the same error too.. Can you fix this asap?

**Comment by bottydim** [comment]
I will make a pull request

Regards,
Botty
