### ISSUE TITLE
Run mkdocs on Travis CI and host artifacts

### ISSUE THREAD

**Issue by bstriner** [fchollet/keras#5112]
I don't think travis currently runs mkdocs but please correct me if I'm wrong. At my old job we used to do something like this to make it easier to review changes to documentation. We were on Jenkins but same idea should apply.

Travis can run mkdocs and host the artifacts for any pending PRs. Would make it easy to see if docs are being generated correctly before merging. Would need to configure a reasonable artifact retention time to not run out of memory.

If this is something that sounds useful, lets start a discussion and see what we can do. Any opinions?

Cheers,
Ben

**Comment by fchollet** [comment]
How do you check that docs are generated correctly? What kind of errors are
you hoping to catch?

**Comment by patyork** [comment]
Do you just mean, so that you can double check when you are modifying the docs, to be able to view the docs as they will appear post-changes? If so, why not just install mkdocd dev server locally?

-----Original Message-----

**Comment by bstriner** [comment]
@fchollet it would make the manual review easier. Every active PR could have a link to the documentation that you could view without having to download or run anything.

In terms of automatic checking:
* Guard against changes that actually break mkdocs build, such as listing the wrong filenames or renaming a function that was explicitly listed, but these issues are hopefully rare.
* Ideally, you enable warnings or errors for functions without documentation, undocumented parameters, etc. You can configure a baseline set of ignores so the current build is green, then any PR that adds an undocumented function or parameter can get a warning or fail.

You don't have to waste time telling people to update documentation, their builds just fail if they don't.

@patyork the main benefit would be for reviewers, not for developers. I felt bad for @fchollet having to review documentation. If there is a link to the docs for every PR, you could check the docs really easily. If you have a lot of PRs to review and comment on, not having to download and build the docs could save a ton of time.

Cheers,
Ben

**Comment by bstriner** [comment]
Ultimately up to you guys but thought it would be worth mentioning as a way I have seen things done. As an example, add a `--validate` argument to `autogen.py` that exits with an error if any functions or parameters are undocumented that are not in a list of exceptions. Add `autogen.py --validate` as a step to travis and fail the build based on the return code. The exception list is also a to-do list and as the code gets fully documented, remove items from the exception list.

**Comment by bstriner** [comment]
@fchollet @patyork I just wrote a simple version to test the idea. This only checks for undocumented functions, not missing parameters or other issues. https://github.com/fchollet/keras/pull/5118 adds a check that there are no new undocumented functions added by a PR. https://github.com/fchollet/keras/pull/5119 adds an undocumented function, so that PR should fail the Travis build. The current list of undocumented functions is in `undocumented_function_exceptions.txt`. Cheers!

**Comment by bstriner** [comment]
@fchollet There are two ways I could envision implementing automatic checking for docstrings, please let me know your opinions:
* Leverage `autogen.py`, since it already goes through the docstrings and just needs some customization. https://github.com/fchollet/keras/pull/5118 is a simple example and gets the job done.
* Run `py.test --pylint -m pylint` to use pylint for more standards-based checking. One available rule is checking for missing documentation.

If we write custom code for checking documentation, we have full control. pylint is not going to be as customizable as customizing autogen, but it would be easier to enable other types of code quality checks in the future and wouldn't involve writing any custom code. If pylint is configurable enough for the kinds of checks you would want, or if you might want to enable other checks in the future, pylint might be the way to go. If it really needs more customization, someone could always write a custom pylint rule.

Static code checking isn't really required, but I find it to save time and eventually make the code better, so hopefully this could be a helpful project. Keras can be the place for all the high-quality code and contrib can be the place where things are still working out the kinks.

Cheers

**Comment by bstriner** [comment]
@fchollet Glad you got something up and running. probot-stale looks like a javascript clone of my python repo but at least I don't have to support anything this way. It looks like they have some nice features. Please let me know any thoughts on how it works out.

Cheers
