### ISSUE TITLE
How to merge two bidirectional layers

### ISSUE THREAD

**Issue by sun-peach** [fchollet/keras#5122]
Hi, dear all,

I am trying to merge two bidirectional layers, however, keras pops up errors from the following codes:

    E1 = Sequential()
    E2 = Sequential()
    E1.add(Bidirectional(LSTM(hidden_dim,unroll=unroll,stateful=stateful,return_sequences=True,batch_input_shape=(shape[0],shape[1],I1_dim)),mode='sum'))
    E2.add(Bidirectional(LSTM(hidden_dim,unroll=unroll,stateful=stateful,return_sequences=True,batch_input_shape=(shape[0],shape[1],shape[2]-I1_dim)),mode='sum'))
    encoder = Merge([E1,E2],mode='concat')

If I remove the bidirectional part, everything is OK, like this:

    E1 = Sequential()
    E2 = Sequential()
    E1.add(LSTM(hidden_dim,unroll=unroll,stateful=stateful,return_sequences=True,batch_input_shape=(shape[0],shape[1],I1_dim)))
    E2.add(LSTM(hidden_dim,unroll=unroll,stateful=stateful,return_sequences=True,batch_input_shape=(shape[0],shape[1],shape[2]-I1_dim)))
    encoder = Merge([E1,E2],mode='concat')

Could anyone tell me how I can merge two bidirectional layers? Thank you.

**Comment by patyork** [comment]
You didn't say, but I'm guessing your error is `ValueError: The first layer in a Sequential model must get an `input_shape` or `batch_input_shape` argument.`

This is as it says. Your first layer is now the `Bidirectional` layer, so the `batch_input_shape` parameter needs to go in that layer. In other words, move `batch_input_shape` to after the `mode=` (which incidentally should be `merge_mode=`).

So:
```python
E1 = Sequential()
E2 = Sequential()
E1.add(Bidirectional(LSTM(hidden_dim, return_sequences=True), merge_mode='sum', batch_input_shape=(shape[0], shape[1], I1_dim)))
E2.add(Bidirectional(LSTM(hidden_dim, return_sequences=True), merge_mode='sum', batch_input_shape=(shape[0], shape[1], shape[2] - I1_dim)))
encoder = Merge([E1, E2], mode='concat')
```

**Comment by sun-peach** [comment]
Thank you. I see.
