### ISSUE TITLE
ValueError or TypeError when using LSTM

### ISSUE THREAD

**Issue by NancyZxll** [fchollet/keras#513]
Hello All,
I used two different models both involving LSTM layer, and got two different errors..
The details are as follows:
model1:
model = Sequential()
model.add(Convolution2D(100, 1, 2, 5, border_mode='valid')) 
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(TimeDistributedDense(49600,max_features, init='normal'))
model.add(Activation('tanh'))
model.add(LSTM(max_features, peptidemaxLen, return_sequences=True))
model.add(Dropout(0.2))
ERROR is: ValueError: new_order[2] is 2, but the input only has 2 axes.

model2:
model = Sequential()
model.add(Convolution2D(100, 1, 2, 5, border_mode='valid')) 
model.add(Activation('tanh'))
model.add(Dropout(0.5))
model.add(TimeDistributedDense(49600,max_features, init='normal'))
model.add(Activation('tanh'))
#model.add(Embedding(max_features, 128))
model.add(LSTM(peptidemaxLen, peptidemaxLen, return_sequences=True))
model.add(Dropout(0.2))
ERROR is: TypeError: index must be integers

Could you tell me how to solve the problem? Many thanks!!

**Comment by jfsantos** [comment]
Without a traceback from the errors, it's hard to guess where it went wrong. Could you post a more complete example and also tell us the shape of your input? The first error at least seems to be related to the input shape, and for the second I suspect (wild guess, though) it could be that max_features is not an integer.

**Comment by amarack** [comment]
I'm running into this as well and I think I can narrow it down a little. It does not happen when an Embedding layer is the first layer of the network, but does happen when a Dense layer is the first layer. The behavior is also shared with SimpleRNN, and I use that in my examples. The error stems from a call to "dimshuffle((1,0,2))" (full stack trace pasted below).

Here's an easy example. First something that works:
<pre><code>
from keras.models import Sequential
from keras.layers.core import Dense
from keras.layers.recurrent import SimpleRNN
from keras.layers.embeddings import Embedding
from keras.optimizers import SGD

# This works
model = Sequential()
model.add(Embedding(10, 64))
model.add(SimpleRNN(64, 10, return_sequences=True))
sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer=sgd)
</code></pre>

Next, something that doesn't work:

<pre><code>
from keras.models import Sequential
from keras.layers.core import Dense
from keras.layers.recurrent import SimpleRNN
from keras.layers.embeddings import Embedding
from keras.optimizers import SGD

# This doesn't work
model = Sequential()
model.add(Dense(10, 64, init='uniform'))
model.add(SimpleRNN(64, 10, return_sequences=True))
sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='mean_squared_error', optimizer=sgd)
</code></pre>


<pre>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-2044ae06821e> in <module>()
     11 model.add(SimpleRNN(64, 10, return_sequences=True))
     12 sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
---> 13 model.compile(loss='mean_squared_error', optimizer=sgd)

/usr/local/lib/python2.7/dist-packages/keras/models.pyc in compile(self, optimizer, loss, class_mode, theano_mode)
    285         self.X_test = self.get_input(train=False)
    286 
--> 287         self.y_train = self.get_output(train=True)
    288         self.y_test = self.get_output(train=False)
    289 

/usr/local/lib/python2.7/dist-packages/keras/layers/containers.pyc in get_output(self, train)
     49 
     50     def get_output(self, train=False):
---> 51         return self.layers[-1].get_output(train)
     52 
     53     def set_input(self):

/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.pyc in get_output(self, train)
     75         X = self.get_input(train) # shape: (nb_samples, time (padded with zeros), input_dim)
     76         # new shape: (time, nb_samples, input_dim) -> because theano.scan iterates over main dimension
---> 77         padded_mask = self.get_padded_shuffled_mask(train, X, pad=1)
     78         X = X.dimshuffle((1, 0, 2))
     79         x = T.dot(X, self.W) + self.b

/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.pyc in get_padded_shuffled_mask(self, train, X, pad)
     25         mask = T.shape_padright(mask) # (nb_samples, time, 1)
     26         mask = T.addbroadcast(mask, -1) # (time, nb_samples, 1) matrix.
---> 27         mask = mask.dimshuffle(1, 0, 2) # (time, nb_samples, 1)
     28 
     29         if pad > 0:

/usr/local/lib/python2.7/dist-packages/theano/tensor/var.pyc in dimshuffle(self, *pattern)
    338             pattern = pattern[0]
    339         op = theano.tensor.basic.DimShuffle(list(self.type.broadcastable),
--> 340                                             pattern)
    341         return op(self)
    342 

/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.pyc in __init__(self, input_broadcastable, new_order, inplace)
    140                     raise ValueError(("new_order[%d] is %d, but the input "
    141                         "only has %d axes.") %
--> 142                         (i, j, len(input_broadcastable)))
    143                 if j in new_order[(i + 1):]:
    144                     raise ValueError((

ValueError: new_order[2] is 2, but the input only has 2 axes.
</pre>

**Comment by fchollet** [comment]
```
model.add(Dense(10, 64, init='uniform'))
model.add(SimpleRNN(64, 10, return_sequences=True))
```

Mixing non-recurrent with recurrent layers will not work (different dimensionality). You should use `TimeDistributedDense` here.

Closing this since the original issue opener did not manifest themselves with actionable information.

**Comment by NancyZxll** [comment]
Thank you all, the problem was solved. I shouldn't use Embedding here.

**Comment by NancyZxll** [comment]
Sorry for my non-action. As I didn't receive any email, so I think no answer in this issue.
Thank you again.
