### ISSUE TITLE
Train a multiclass label model for a video

### ISSUE THREAD

**Issue by indra215** [fchollet/keras#5134]
I've a video and a set of classes attached to it, there are multiple labels for each video. And I want to train a model to predict multiclass labels given a video. 

What would be the way to train a multiclass label model for video using LSTM ?

Could anyone please suggest a method to tackle this problem ?

Thanks in advance.

**Comment by bstriner** [comment]
Simplest method for multiclass predictions is to do each independently (simplest, not best). Just run your video through an LSTM, have sigmoid outputs that are the probability of each class, and use binary_crossentropy to train. If you do some reading on multiclass prediction, independent predictions work sometimes but not others.

Cheers
