### ISSUE TITLE
Documentation: What is/are the default filters used by Keras Convolution2d()?

### ISSUE THREAD

**Issue by chrisfalter** [fchollet/keras#5136]
I am pretty new to neural networks, but I understand linear algebra and the mathematics of convolution pretty decently. 

I am trying to understand the sample code in /blob/master/examples/mnist_cnn.py for training a convolutional NN with MNIST data to recognize digits. My expectation would be that when I create a convolutional layer, I would have to specify a filter or set of filters to apply to the input. But the sample creates a convolutional layer like this:

    model.add(Convolution2D(nb_filter = 32, nb_row = 3, nb_col = 3,
                            border_mode='valid',
                            input_shape=input_shape))

This seems to be applying a total of 32 3x3 filters to the images processed by the CNN. But what are those filters? How would I describe them mathematically? The documentation is no help. 

Thanks in advance,

**Comment by kgrm** [comment]
By default, the convolutional filters are initialised with values drawn from a random distribution that can be specified with the `init` parameter.
