### ISSUE TITLE
How to get the memory cell gate activations in LSTM ?

### ISSUE THREAD

**Issue by indra215** [fchollet/keras#5138]
Hi,

I want to train a LSTM that learns given a frame of video, predict the next frame of the video. I extracted 20 frames from each video and each frame is passed through a CNN to get a 512 dimensional feature embedding for the frame i.e., each frame is now represented by a 512 dimensional feature vector and I have 20 frames for each video.

So my input has shape of X_train = (no_videos, 20, 512) and similarly my output has shape of Y_train = (no_videos,20,512) which are the shifted frames.

After training, I pass each video frame by frame for the network to predict the next frame and I want to extract the memory cell gate activations after the final frame is predicted for that video. This means I want the memory cell gate activations for each video after predicting the final frame (so that the information of the entire video is embedded). 

Could someone please help how to do this ?

Thanks in advance.

**Comment by bstriner** [comment]
If an LSTM is trained to predict the next frame, it is going to forget any information not relevant to that. So your memory cell at the end of the video might not have anything meaningful in it. They way an LSTM is normally used to encode a sequence is to train the LSTM such that its final output can be used to reconstruct the entire sequence. That way you are training the LSTM to actually learn an embedding that reconstructs the sequence.

On the other hand, if you wanted to get all of the memory cells, you are looking at extremely redundant data.

If you really want to get to the states without writing a ton of code, you could modify LSTM.call to store `states` as some attribute and then get it from your code.

If you want to be able to embed an entire video, you might want to try a different approach. Have you found any papers on the topic?

**Comment by indra215** [comment]
I don't want all the memory cells. I just need a single embedding for each video. I thought of getting that by training the LSTM to predict the next frame given the current frame. Then for each video, by passing each frame, the LSTM predicts the next frame and finally I'll take the memory cell activation after predicting the last frame of that video. This way I've the memory cell activation as embedding for that video. I'll repeat the same for each video. This way I have an embedding for each video as the memory cell activation of the last predicted frame of that particular video. 

I don't know how to this in keras. Is it possible to do this in keras ?

**Comment by baziotis** [comment]
From what you are saying, what i understand is that you want the LSTM _outputs_ for each timestep, not the _memory cells_.  Also you are saying that you want the memory cell _activations_. That confuses me even more. I can't imagine what useful information this will give you, as @bstriner said. 

Anyway you can get the LSTM outputs (or hidden states) like this:
Sequential API
```python
...
model.add(LSTM(100, return_sequences=True))
...
```
Functional API
```python
states = LSTM(100, return_sequences=True)(frames)
```

**Comment by indra215** [comment]
I don't want the LSTM outputs for each timestep. **My main aim here is to get a single embedding for each video (which represents the entire information present in the video).** 

I want to extract the memory cell activation after passing the final frame of the video to the LSTM. Like in my example as I said initially, my X_train = (no_videos, 20, 512) and Y_train = (no_videos, 20, 512). Here 20 represents I extract 20 frames from the video and 512 is the CNN feature embedding of each frame. Now I train a LSTM giving it the current frame as input (X_train[:,I,:]) and the next frame as it's target (Y_train[:,i,:]). Once this training is done, I will now pass each video frame by frame and extract the memory cell activation when final frame has been given. 

I apologize if I have confused before. 

Or is there any way of learning a single embedding for a video which captures the entire information in the video ?

**Comment by bstriner** [comment]
Run the LSTM over the entire video and get the final output of the LSTM. Train that final output of the LSTM to recreate the entire video. That is the only way the output of the LSTM will be representative of the entire video.

If the LSTM only tries to recreate the next step, then it isn't going to learn to store information.

If you're trying to predict only the next frame, you could pass in the first frame and hallucinate what might happen next, but your accuracy is going to be terrible.

**Comment by indra215** [comment]
Sorry but can you please elaborate how to do what you are suggesting that is run the LSTM over the entire video. I mean what should be the training data and target data ? And also how to use the final output to recreate the entire video. Sorry if I'm asking a basic question since I'm new to LSTM.

Thank you in advance.

**Comment by bstriner** [comment]
Usage questions should go to stackoverflow, slack or the google group. Github is really for bugs and feature requests. Please close this issue and continue the discussion there if you have further questions.

Basically, you are trying to make an autoencoder. Create 2 LSTMs.
* encoder LSTM: return_sequences = False. This will go through your training data and output a single embedding vector
* decoder LSTM: return_sequences = True, depth=20. This will go through the embedding vector and try to output your original frames.

The input should be your original frames, and the target should be the same set of frames (pass the same array as input and target).
* One popular variation is denoising autoencoders, where you add some noise to the input but not the target
* Another popular model is to reverse the frames in the target. So inputs are frames 1-20, and the target is frames 20-1.

If you want to do something more advanced, use a convolutional autoencoder for the frames. Apply this encoder and decoder using TimeDistributed.
* Input is some frames, lets say (batch_size, 20, 64, 64)
* TimeDistributed frame encoder converts frames, so the output is (batch_size, 20, 256)
* LSTM encoder combines the frames, so the output is (batch_size, 512)
* LSTM decoder decodes the frames back to (batch_size, 20, 256)
* TimeDistributed frame encoder decodes frames back to (batch_size, 20, 64, 64)

After fully training the model, with encoder and decoder, the embedding you want is just the output of the encoder. It is normally easiest to build two models in your code, an encoder and a decoder, then create an autoencoder that uses both models. Run `autoencoder.fit` then use `encoder.predict` to get embeddings.
```python
encoder = Model(...)
decoder = Model(...)
autoencoder = Model(encoder.inputs, decoder(encoder(encoder.inputs)))
```

Cheers

**Comment by dcarr45** [comment]
@bstriner Hey there, I'm getting an odd error trying to implement something like that model you described that I thought I throw in here

```
seq_in = Input(shape=(MAX_WORDS, ), dtype='int32', name='seq_in')
seq_emb = Embedding(input_dim=vocab_size,
                     output_dim=WORD_EMBED_SIZE,
                     weights=[e_weights],
                     mask_zero=True,
                     trainable=False)(seq_in)
seq_emb = Masking(mask_value=0.0)(seq_emb)

sen_enc = LSTM(SENT_EMBED_SIZE, return_sequences=False, name='LSTM_enc')(seq_emb)

dec_in = Input(shape=(None, SENT_EMBED_SIZE), name='dec_in')
sen_dec = LSTM(MAX_WORDS, return_sequences=True, name='LSTM_dec')(dec_in)
onehot_out = Dense(vocab_size, activation='softmax')(sen_dec)

encoder = Model(seq_in, sen_enc)
decoder = Model(dec_in, onehot_out)
encoder.summary()
decoder.summary()
autencoder = Model(encoder.inputs, decoder(encoder(encoder.inputs)))
```

Getting the following error:

```
InvalidArgumentError: Invalid reduction dimension 2 for input with 2 dimensions. for 'model_28/LSTM_dec/Sum' (op: 'Sum') with input shapes: [?,200], [2] and with computed input tensors: input[1] = <1 2>.
```
regardless of the size of my decoder LSTM.

Using a pre-trained word embedding spices up the problem here, but I don't think that's necessarily the issue. Can't quite figure it out, would welcome any suggestions, good chance I'm doing everything wrong

**Comment by dcarr45** [comment]
Hold up, solved the above by adding
`sen_enc = Reshape((1,SENT_EMBED_SIZE))(sen_enc)`
Again, I fear I may be straying from the desired model though

**Comment by dcarr45** [comment]
The above can be solved by adding
`sen_enc = RepeatVector(MAX_WORDS)(sen_enc)
`
But does that have the desired effect?
