### ISSUE TITLE
how to init a layer weights from before layer before model compile

### ISSUE THREAD

**Issue by yanyuxiaoxiao** [fchollet/keras#5146]
I want to implement paper:CNN-RNN: A Unified Framework for Multi-label Image Classification https://arxiv.org/pdf/1604.04573v1.pdf. 
The net work structure can simple understand by below figture
![image](https://cloud.githubusercontent.com/assets/12267543/22232520/d441c1fc-e224-11e6-948b-3ea09e2d318f.png)
My code can be see below
![image](https://cloud.githubusercontent.com/assets/12267543/22232557/0eff999a-e225-11e6-8e64-75ff4913e324.png)
So, the problem coming to me is that how to decoder sequence embed label to label index.
By the way , anyone knows better way to implement the net work.

**Comment by saeed-khorram** [comment]
Hi @yanyuxiaoxiao, 
Did you happen to solve the problem?

**Comment by adymaharana** [comment]
Hi there, did anyone succeed at implementing the mentioned paper? @yanyuxiaoxiao @saeed-khorram
