### ISSUE TITLE
Count number of parameters on each and every layer in hybrid of convolution and lstm

### ISSUE THREAD

**Issue by vinayakumarr** [fchollet/keras#5148]
lstm_output_size = 70

nb_filter = 64

filter_length = 3

pool_length=2

Attachine the image

Could you please tell how to compute the numerically. Is there any formula or method to obtain the number of parameters of each and every layer
![cnnlstm](https://cloud.githubusercontent.com/assets/18217467/22233547/dbfac258-e216-11e6-9c73-23d59d360383.png)

**Comment by Martijnde** [comment]
256 at convolution1d + 37800 at lastm_1 + 355 at dense_1 totals 38.411

So you could see them in the Param # if I am not mistaking

**Comment by vinayakumarr** [comment]
That i also know. My question is how to calculate numerically. Is there any equation for doing parameter calculation at each layer

**Comment by bstriner** [comment]
Not quite sure what you're asking. How can you calculate something not numerically?

* You could iterate over the model trainable_weights, get the shape of each of them and sum them up.
* You could iterate over model layers, get the params for each layer, and get the shape of those

Or are you asking the equation for number of parameters? like `param_count(Dense, input_dim, output_dim) = input_dim*output_dim + output_dim`. This changes depending on the type of layer.

Cheers

**Comment by bstriner** [comment]
The "equation" would depend on the type of layer. If you just need the count, get the params from each layer and check the size.

**Comment by bstriner** [comment]
Also, there is the handy function `layer.count_params()` if you just want the param count for a layer.

**Comment by yoh2292** [comment]
@bstriner You genius. To count the number we should add a count_params function indeed.
