### ISSUE TITLE
count number of parameters in CNN numerically in each and every layer

### ISSUE THREAD

**Issue by vinayakumarr** [fchollet/keras#5149]
nb_filter = 64

filter_length = 3

pool_length=2

dense (128)
dropout(0.5)

Attaching the image

Could you please tell how to compute the numerically. Is there any formula or method to obtain the number of parameters of each and every layer
![cnn](https://cloud.githubusercontent.com/assets/18217467/22233596/582e72de-e217-11e6-920c-9ca524dc8f35.png)

**Comment by ncullen93** [comment]
basically use the model.layers[idx].get_weights() function and multiple the shape values. Something like this structure.. NOTE: probably won't work as is.. you should check out the get_weights() function for a given layer.
```
for layer in model.layers:
     try:
         weights = layer.get_weights()[0]
         biases = layer.get_weights()[1]
         counts = np.prod(weights.shape) + np.prod(biases.shape)
     except:
          print('Layer has no weights')
```

**Comment by bstriner** [comment]
I just noticed the handy function `layer.count_params()` when I was looking through the source code to print the summary. Should be the easiest way if you just want total counts per layer.
