### ISSUE TITLE
ValueError: Error when checking model target: expected convolution1d_16 to have shape (None, 250, 32) but got array with shape (10, 250, 1)

### ISSUE THREAD

**Issue by abhid95** [fchollet/keras#5151]
![screenshot from 2017-01-24 12 38 47](https://cloud.githubusercontent.com/assets/7656411/22237488/1b86e986-e232-11e6-8c57-fd94618e2cf7.png)

**Comment by bstriner** [comment]
Check:
* `model.summary`
* `print(train1d_X.shape)`
* `print(train1d_gt1.shape)`

And you should see what doesn't line up.

Cheers

**Comment by abhid95** [comment]
![whatsapp image 2017-01-26 at 12 19 18 pm](https://cloud.githubusercontent.com/assets/7656411/22323877/9f9a33dc-e3cb-11e6-945b-3687e28ded15.jpeg)

Both of their shapes are same.
Still the above mentioned error is showing up.

**Comment by bstriner** [comment]
Summary is used this way:

```python
model.summary()
```

**Comment by bstriner** [comment]
Should print each layer and the size

**Comment by abhid95** [comment]
![con1d_27_1_2017](https://cloud.githubusercontent.com/assets/7656411/22360536/93144c00-e476-11e6-88c3-e4c2f75289de.png)

This is the example given in Keras documentation with only input given by us. Can you please see through why is this error coming up.
