### ISSUE TITLE
Is there multiple types of TensorVariable in keras?because i see an error in 1 variable

### ISSUE THREAD

**Issue by ghost** [fchollet/keras#5155]
i was trying to do so stuff in the call() function to make a custom layer.
and of course call() function take the input x like `call(self,x):`
i did inside it:
`print type(x) `               
`print x._keras_shape`
`print type(x.shape)`
`print (x.shape)._keras_shape`
 and the first 3 outputs are:
`<class 'theano.tensor.var.TensorVariable'>`   
`(None, 1)`
`<class 'theano.tensor.var.TensorVariable'>`
BUT for the forth output it is an error that says
 "`AttributeError: 'TensorVariable' object has no attribute '_keras_shape'`"

Both of them are Tensor Variables  why it output error only in  `x.shape` ?

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by gvtulder** [comment]
No, there is only one type of `TensorVariable`, but Keras adds additional information to the output of Keras layers.

`TensorVariable` is the type of the underlying Theano variable. These variables do not have a fixed shape, so if you ask for `x.shape` you'll get another `TensorVariable` that, at runtime, will be filled with the current shape of `x`. For variables that are the output of a Keras layer, Keras adds a `_keras_shape` property that contains the shape known at compile time. At runtime, `x._keras_shape` and `x.shape` should be the same (except that the `None` in `x._keras_shape` will have an actual value in `x.shape`).

In your example, `x` is the output of a Keras layer, so it has a `_keras_shape`. `x.shape` is a property of Theano variable `x` and is not an output of a Keras layer, so it doesn't have a `_keras_shape`. It's not hard to derive its shape, though: it is the shape of `x`, so it will be a vector with shape `(x.ndim,)`.

The people on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or on [the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) might be able to help you further.

**Comment by bstriner** [comment]
@gvtulder great explanation!

@Bassel1 remember this is python, so you can add any attribute you want to any object. Objects of the same class can have completely different attributes. Do some reading on "duck typing". What really matters in python isn't the class of an object, but what attributes the object has.

https://en.wikipedia.org/wiki/Duck_typing

If you look at the keras code, it doesn't check if something is a keras tensor by checking the class but by checking if it has the correct attributes `hasattr(tensor, '_keras_shape')`.

Cheers

**Comment by peterwilliams97** [comment]
> If you look at the keras code, it doesn't check if something is a keras tensor by checking the class but by checking if it has the correct attributes hasattr(tensor, '_keras_shape')

I looked at

https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py has 

```
def is_keras_tensor(x):
    ...
    return hasattr(x, '_keras_history')
```
`is_keras_tensor()` gives the wrong answers for the last 2 test cases in its doc string.

When ` hasattr(tensor, '_keras_history')` is replaced with `hasattr(tensor, '_keras_shape')` it gives the answers that match the doc string.

Which behaviour is correct? The current `is_keras_tensor()` implementation or its docstring?
