### ISSUE TITLE
Image Captioning in Keras

### ISSUE THREAD

**Issue by indra215** [fchollet/keras#5158]
As described in image captioning example here [https://keras.io/getting-started/sequential-model-guide/](url), I need to add a image model `(image_model `as in example) and append it to a language model (`language_model` as in example). What if I directly have a CNN feature embedding of the image and don't want to add the `image_model `instead directly use the language model (`language_model`) itself to generate the caption word by word. 

For example, I have a CNN feature embedding of the image as X_train = (no_images, 512) and `partial_captions` and `next_words `as it is described in the example. So how would the model look like and what changes should be done similar to the one described in the example ?

Thanks in advance.

**Comment by ParthaEth** [comment]
@indra215 take a look at [this](https://arxiv.org/pdf/1411.4555v2.pdf). Are you asking a teoritical question of what would happen if you did not have a language model of the type shown in the example or are you asking how to implement a particular model architecture? If it is about a model architecture I can give you a demo code if you post an image

**Comment by indra215** [comment]
Thanks for the paper. I'm asking according to the example here [ https://keras.io/getting-started/sequential-model-guide/](url), instead of writing the image model I want to directly use a custom CNN embedding as `image_model`. I'm saying instead of an image if I have a CNN feature for every image and I want to use them as image features and `partial_captions` and `next_words `as it is described in the example.

Also I'm still skeptical on how to give the `partial_captions` and `next_words` as input. Could you please explain how should we give them as data ? It would be great if you could give me a demo code on image captioning.

Thank you in advance.
