### ISSUE TITLE
keras.backend.squeeze does not return keras tensor

### ISSUE THREAD

**Issue by nelson-liu** [fchollet/keras#5166]
Here's a short snippet to reproduce it, tried on both theano master and latest TF, as well as keras master.:
```python
In [1]: import keras.backend as K
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally

In [2]: import numpy as np

In [3]: keras_tensor = K.variable(np.array([[[1], [2], [3]]]))

In [4]: K.is_keras_tensor(keras_tensor)
Out[4]: True

In [5]: K.int_shape(keras_tensor)
Out[5]: (1, 3, 1)

In [6]: squeezed_keras_tensor = K.squeeze(keras_tensor, axis=2)

In [7]: K.is_keras_tensor(squeezed_keras_tensor)
Out[7]: False

In [8]:
```

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by nelson-liu** [comment]
seems like a similar thing happens for `K.expand_dims`

**Comment by QinDong0102** [comment]
@nelson-liu Hello, I am facing the same problem ,any solution or idea ? Many thanks

**Comment by noahstier** [comment]
@nelson-liu Why did you close this? As far as I can tell it's not fixed. 

I'm getting this error `AttributeError: 'Tensor' object has no attribute '_keras_history'` from the line `model = Model(inputs=inputs, outputs=predictions`, and I believe it's because I have `x = squeeze(x, 3)`, after which `keras.backend.is_keras_tensor(x)` returns `False`.

**Comment by noahstier** [comment]
Using this as a workaround, seems like `keras.backend.squeeze` is not meant to be used directly, and this is what `keras.layers.Lambda` is for:
`x = Lambda(lambda y: squeeze(y, 3))(x)`
