### ISSUE TITLE
How to get the caption for a test image ?

### ISSUE THREAD

**Issue by indra215** [fchollet/keras#5171]
I'm trying to train a image captioning model as described in keras example [https://keras.io/getting-started/sequential-model-guide/](url). How to get the caption for a new test image ? How should I give the test data and get a entire caption for the image ?

As the last layer in the example is "Dense", it would give a single prediction but how do I get the entire caption ?

Could someone please help in solving this. Thanks in advance.

**Comment by ParthaEth** [comment]
You have an RNN at the end so feed back the output of it till it generates a end of sentence token. so you get a character at a time (or a word depending upon your language model).

**Comment by indra215** [comment]
Thank you for the reply. I've understood what you said but I was looking on how to implement it in the code. I'm looking for how to give the test data and extract the output i.e. the whole caption. Could you please provide the code for doing so ? Thank you in advance.
