### ISSUE TITLE
keras.regularizers documentation

### ISSUE THREAD

**Issue by mjs-wpi** [fchollet/keras#5186]
Is there additional documentation available on how "activity regularization" differs from "regularization." I'm having trouble finding information in papers/online and I'm curious how they differ.

example: l2 vs activity_l2

Also, I'm assuming W_regularizer refers to weights and b_regularizer refers to bias?

Thanks

**Comment by bstriner** [comment]
Same idea, just whether you're regularizing the weights or activations. Regularization normally means weight regularization instead of activity regularization but it can mean both.

**Comment by mjs-wpi** [comment]
As in, regularizing the output of the activation functions? Interesting - thank you for clarifying.

**Comment by bstriner** [comment]
Yeah.

Activity regularizer: The model is penalized for having large weights
Weight regularizer: The model is penalized for having large activations

Depending on where you put the activity regularizer, it can regularize the activation before or after the activation function.

**Comment by mjs-wpi** [comment]
Thank you @bstriner
