### ISSUE TITLE
Layer output using its name

### ISSUE THREAD

**Issue by kkarnatak** [fchollet/keras#5187]
Is it possible to get a layer output using the layer name? I know the way mentioned in keras docs using the function and layer number. But, curious to know if its feasible to do so using the layer name.

**Comment by kgrm** [comment]
Yes, you can easily construct a dictionary to look up layers by their name, as in `layer_dict = dict([(layer.name, layer) for layer in model.layers]), which you can then use in the function construction, as in `f = K.function([model.input], layer_dict["a_layer_name"].output)`

**Comment by kkarnatak** [comment]
Thanks alot!
