### ISSUE TITLE
Layer number while building model

### ISSUE THREAD

**Issue by kkarnatak** [fchollet/keras#5189]
Hi,

I am trying to do some computation between the layers while model is being created ( via build graph ). Is it possible that I can know the number of the layer being processed during this time?

For eg. if there are 6 layers

    model = Sequential()
    model.add(ZeroPadding2D((1,1),input_shape=(3,224,224)))
    model.add(Convolution2D(64, 3, 3, activation='relu'))
    model.add(ZeroPadding2D((1,1)))
    model.add(Convolution2D(64, 3, 3, activation='relu'))
    model.add(MaxPooling2D((2,2), strides=(2,2)))

Is is possible to know that Convolution2D is at 3th and 5th place. I can't use the output function( used to get the output using layer list) because this needs to be used during the graph building.

**Comment by bstriner** [comment]
Use `model.layers`. Iterate over the layers, call `type(layer)`, `isinstance(layer, Dense)` or whatever else you need to do.
