### ISSUE TITLE
Error in model.summary() output

### ISSUE THREAD

**Issue by midnitekoder** [fchollet/keras#5195]
I am getting the following output on model.summary().
what is the meaning of convolution2d_1_1[1][0] in the fourth column ?
Note: I have changed layer names by appending '_1' to them based on my work requirements.
![errorsummary](https://cloud.githubusercontent.com/assets/6232762/22351007/0a4cbee6-e43c-11e6-9156-0aaded89f200.png)

**Comment by patyork** [comment]
Per the heading if the table, that is the layer that it is connected to (the layer it follows).

**Comment by midnitekoder** [comment]
My understanding of node_indices and tensor_indices is not very clear which I wanted to clarify. Anyway I figured out by reading layer_utils.py by going through the code of print_summary and definition of Node.
Please read this file if anyone wants to clearly understand model.summary().
So, I am closing it. 
Thank you for quick reply :)
