### ISSUE TITLE
Can TFOptimizer include the scipy optimizer as tensorflow did?

### ISSUE THREAD

**Issue by pswpswpsw** [fchollet/keras#5201]
In tensorflow,
tf.contrib.opt, can call scipy optimizer, like CG... I have used that in my code, and it is converging super super fast than SGD. 

Can anyone add it into keras?

**Comment by janceesvansenden** [comment]
Any tips on doing this? I would like to use a Levenberg-Marquardt optimizer with my Keras project but have not found a good way to do so yet.

**Comment by ayblaq** [comment]
Hi,

Any helpful info about this?, kinda need it for my NN project. Thanks

**Comment by ajebulon** [comment]
I'm also looking for this information. It would be a great help if someone can help. Thanks
