### ISSUE TITLE
Is it possible to obtain current epoch number in layer or cost?

### ISSUE THREAD

**Issue by rudaoshi** [fchollet/keras#5206]
There are some learning method that requires dynamically adjust the behavior of layers when the epoch increasing. 

Is it possible to obtain the current epoch number in the layer's call function?

**Comment by bstriner** [comment]
Relatively straightforward:
* Add a non-trainable weight named iteration to your layer
* Add an update to your layer that increments the iteration.
* Use that variable in call

Most of the optimizers have similar code that you can look at for inspiration.

Cheers
