### ISSUE TITLE
LSTM (return_sequences=True) followed by TimeDistributed(Dense) doesn't work!

### ISSUE THREAD

**Issue by wsstriving** [fchollet/keras#5214]
Hello, everyone,
        Recently I wanted to build a network as following
        Input  -->  sequence padding and masking 0 --> LSTM (return_sequence=True) --> Timedistributed(Dense(outputnumber, softmax)), but an error of mismatched dimension was reported. 
  ```python
    # Model definition
    model = Sequential()
    model.add(Masking(mask_value=0., input_shape=(None,100)))
    model.add(LSTM(args.dimension, dropout_W=0.2, dropout_U=0.2, return_sequences=True)) 
    model.add(TimeDistributed(Dense(97, activation='softmax')))
  ```

The error is as : 
ValueError: Error when checking model target: expected timedistributed_1 to have 3 dimensions, but got array with shape (3000, 97)

The dataset has 3000 sequences as input.

Thanks.

**Comment by wsstriving** [comment]
According to the documentation, the output of LSTM should be a 3D array:

> if return_sequences: 3D tensor with shape  (nb_samples, timesteps, output_dim).
> else, 2D tensor with shape (nb_samples, output_dim).

However, in my case, a 2D array is returned

**Comment by bstriner** [comment]
The input to the LSTM should also be a 3D array. Make sure that is the case.

Your masking input_shape seems weird and should probably have 3 dims.

Make sure to mention **when** the error occurs. When you build the model, when you compile, when you run?

Try running `model.summary()`. If the error happens when you start passing data, check the shape of your data.

**Comment by wsstriving** [comment]
Thanks for reply, and the output of model.summary() (The input feature dimension is now 39):
`
![screenshot from 2017-02-01 10 35 54](https://cloud.githubusercontent.com/assets/9416457/22493293/43f88800-e86a-11e6-893d-e9c5a6532ccd.png)

I tried to change the input shape to (None,None,39) but it will report errors of dimension mismatch.
`

**Comment by wsstriving** [comment]
Thanks again, I have figured out why. Since I thought the softmax layer would automatically deal with the timedistributed stuff, I didn't explicitly  set expand the labels to 3-dimension. Now it works.

**Comment by skeydan** [comment]
Hi,

sorry but could you hlp me? I'm pretty sure I have the same problem and I don't know how to fix it...

Here is my model summary:

Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
lstm_15 (LSTM)                   (95, 5, 4)            96          lstm_input_15[0][0]              
____________________________________________________________________________________________________
timedistributed_14 (TimeDistribut(95, 5, 5)            25          lstm_15[0][0]                    
====================================================================================================
Total params: 121
____________________

**Comment by skeydan** [comment]
Here is the code

<pre>

model.add(LSTM(num_neurons,
                      #  input_dim = lstm_num_features,
                       batch_input_shape=(batch_size, X_train.shape[1], X_train.shape[2]), 
                       return_sequences = True))
            print(model.output_shape) 
            model.add(TimeDistributed(Dense(lstm_num_predictions)))
            print(model.output_shape) 
            model.compile(loss='mean_squared_error', optimizer='adam')

</pre>

And the error happens when I try to fit the model:
<pre>
model.fit(X_train, y_train, nb_epoch = num_epochs, batch_size = batch_size)
</pre>

The error is
<pre>
Exception: Error when checking model target: expected timedistributed_14 to have 3 dimensions, but got array with shape (95, 1)
</pre>

**Comment by skeydan** [comment]
My data shape is

(95, 5, 1)

and variables are set to

<pre>
lstm_num_predictions = 5
batch_size = 1
</pre>

**Comment by skeydan** [comment]
Would be great if somebody could explain! Thank you!

**Comment by bstriner** [comment]
That error might refer to problems with the shape of your data, not problems with your model. Can you confirm that the target you are passing to the model is 3d?

Cheers

**Comment by skeydan** [comment]
Hi, thanks for the quick reply!
The data is just toy data - I'll paste the code below.
It's from a complete "toy notebook"
- https://github.com/skeydan/timeseries_sandbox_python/blob/master/ts_experiment.ipynb - 
 where I've been trying out e.g. stateful vs. stateless, and the other if branches (using LSTM + simple Dense, or stacking LSTMs) all work fine. The only problem is when using TimeDistributed.

Here's the code for this branch:
<pre>
ts_train_lineartrend = np.arange(1,101, dtype='float64').reshape(-1,1) 

def create_dataset(dataset, window_size):
    dataX, dataY = [], []
    for i in range(len(dataset) - window_size):
        a = dataset[i:(i + window_size), 0]
        dataX.append(a)
        dataY.append(dataset[i + window_size, 0])
    return np.array(dataX), np.array(dataY)

X_train, y_train = create_dataset(ts_train, lstm_num_timesteps)

# reshape input to be [samples, time steps, features]
X_train = np.reshape(X_train, (X_train.shape[0], lstm_num_timesteps, lstm_num_features))

X_train.shape # (95, 5, 1)

model.add(LSTM(num_neurons,
                      #  input_dim = lstm_num_features,
                       batch_input_shape=(batch_size, X_train.shape[1], X_train.shape[2]), 
                       return_sequences = True))
model.add(TimeDistributed(Dense(lstm_num_predictions)))
model.compile(loss='mean_squared_error', optimizer='adam')

model.fit(X_train, y_train, nb_epoch = num_epochs, batch_size = batch_size)

</pre>

**Comment by skeydan** [comment]
Hi again,

I think I made several mistakes at once.
The current code works, but it would be great if you could quickly check if this is the correct way to chain LSTM and Time Distributed. Many many thanks!

Here's step-by-step what I'm doing now:

1) create the original timeseries

<pre>
ts_train = np.arange(1,101, dtype='float64').reshape(-1,1)  
ts_test = np.arange(21,41, dtype='float64').reshape(-1,1)
ts_all = np.append(ts_train, ts_test).reshape(-1,1)
</pre>


2) reshape to X_train and y_train matrices with 5 timesteps each

<pre>
def create_dataset2(dataset, window_size):
    dataX, dataY = [], []
    for i in range(len(dataset) - 2 * window_size):
        a = dataset[i:(i + window_size), 0]
        #print(a)
        dataX.append(a)
        b = dataset[(i + window_size):(i + 2* window_size), 0]
        #print(b)
        dataY.append(b)
    return np.array(dataX), np.array(dataY)
    
X_train, y_train = create_dataset2(ts_train, lstm_num_timesteps)
X_test, y_test = create_dataset2(ts_test, lstm_num_timesteps)
</pre>

3) test the shapes

<pre>
X_train.shape, y_train.shape, X_test.shape,  y_test.shape
# ((90, 5), (90, 5), (10, 5), (10, 5))
</pre>


4) reshape again, to match LSTM expected input

Before, I only reshaped X, not y

<pre>
X_train = np.reshape(X_train, (X_train.shape[0], lstm_num_timesteps, lstm_num_features))
X_test = np.reshape(X_test, (X_test.shape[0], lstm_num_timesteps, lstm_num_features))
    
if lstm_predict_sequences:
    y_train = np.reshape(y_train, (y_train.shape[0], lstm_num_predictions, lstm_num_features))
    y_test = np.reshape(y_test, (y_test.shape[0], lstm_num_predictions, lstm_num_features))
        
</pre>        


5) test the shapes again

<pre>
X_train.shape, y_train.shape, X_test.shape,  y_test.shape
# (90, 5, 1), (90, 5, 1), (10, 5, 1), (10, 5, 1))
</pre>


6) create the model

<pre>
model.add(LSTM(num_neurons, batch_input_shape=(batch_size, X_train.shape[1], X_train.shape[2]), 
                       return_sequences = True))

                      
model.add(TimeDistributed(Dense(1)))
model.compile(loss='mean_squared_error', optimizer='adam')

model.fit(X_train, y_train, nb_epoch = num_epochs, batch_size = batch_size)
</pre>

7) model summary

<pre>
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_1 (LSTM)                (1, 5, 4)                 96        
_________________________________________________________________
time_distributed_1 (TimeDist (1, 5, 1)                 5         
=================================================================
Total params: 101.0
Trainable params: 101
Non-trainable params: 0.0
</pre>

**Comment by bstriner** [comment]
Exactly. It is weird to always have that extra 1 dimension in both the input and the target but it makes everything easier internally.

BTW, `np.expand_dims` is a convenience function to just add a 1 dimension to an array. Easier to read than `np.reshape`.

In general, `Error when checking model target` means your numpy target arrays are not the same shapes as the output tensors.

Cheers

**Comment by skeydan** [comment]
>> It is weird to always have that extra 1 dimension in both the input and the target but it makes everything easier internally.

Thanks for explaining!

And thanks for the advice regarding np.expand_dims, I've always found reshape -1 somehow strange ;-)

>> In general, Error when checking model target means your numpy target arrays are not the same shapes as the output tensors.

Yes, my main problem was I somehow never realized the message was talking about the _target_ - after I'd realized that I started to understand ...;-)

Thanks a lot for your help,
Sigrid

**Comment by scollet1** [comment]
Hey guys, I am having an issue with an output dimension mismatch and I'm not sure I follow the solutions provided above.

## Error
```
ValueError: Error when checking target: expected time_distributed_1 to have shape (3, 1) but got array with shape (1, 1)
```

My input dimension is a 3D vector and fits properly with the network, but my Y vector, the one I'm training against only works when it's the same size as my input. 

I am trying to predict 1 value per day, from a (4, N, 1) input 

## Model Summary

```
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_1 (LSTM)                (None, 3, 128)            66560     
_________________________________________________________________
dropout_1 (Dropout)          (None, 3, 128)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 3, 32)             4128      
_________________________________________________________________
dense_2 (Dense)              (None, 3, 32)             1056      
_________________________________________________________________
dense_3 (Dense)              (None, 3, 32)             1056      
_________________________________________________________________
time_distributed_1 (TimeDist (None, 3, 1)              33        
=================================================================
Total params: 72,833
Trainable params: 72,833
Non-trainable params: 0
_________________________________________________________________
```

## Code

```
network = Network({
		'name':'test',
		'inputs':3,
		'outputs':1,
		'layers':3,
		'activation':'relu',
		'loss':'mean_squared_error',
		'optimizer':'RMSprop',
		'metrics':['accuracy']
	})
	network.train({
				'consecutiveDays' : 4,
				'train':{'X':[[
					[1, 1, 1],
					[0, 1, 1],
					[1, 1, 1],
					[0, 1, 1]],
					[[1, 1, 1],
					[0, 1, 1],
					[1, 1, 1],
					[0, 1, 1]]],
				'Y':[[
					[2],
					[0],
					[2],
					[0]],
					[[2],
					[0],
					[2],
					[0]]
				]}})
```

```
def build(self, hP): # HYPER PARAMETERS
		if hP is not None:
			if hP['name'] is not None:
				self.name = hP['name']
			else:
				hP['name'] = 'testNet'
			model = Sequential()
			model.add(LSTM(128,
					return_sequences=True,
					input_shape=(hP['inputs'], 1),
					activation=hP['activation']))
			model.add(Dropout(0.3))
			for i in range(hP['layers']):
				model.add(Dense(32, activation=hP['activation']))
			model.add(TimeDistributed(Dense(output_dim=hP['outputs'], activation=hP['activation'])))
			model.compile(
					loss=hP['loss'],
					optimizer=hP['optimizer'],
					metrics=hP['metrics']
			)
			model.summary()
			return model
		else:
			failed('Network construction')
			return None
```

**Comment by juhatontti** [comment]
At first thanks, for your conversation. I've got some help for the use of TimeDistributed etc.

Now, my LSTM-network doesn't return errors, but when I start training, it seems that no learning occurs. I've tried to change loss-functions and amount of hidden units.
My work is to classify some voice samples. I'm a beginner with real neural network training. So I took at first sounds of two kind and so my target is until this only zeros and ones. I read two music files (one with piano, one with guitar) and split them into  two second samples (with a given code).
How poor ever my model is, I think the weights and loss should change somehow during learning.

I'm grateful, if someone can help me. I should get some result from my network soon.

import numpy as np
import os
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.wrappers import TimeDistributed
from keras.utils import to_categorical

from vggish_input_m import wavfile_to_examples

x_data = []

t1 = np.full((130,64),1)

print(t1)
for i in range(54):
    for j in range(64):        
        t1[i][j] =0
    # I know the amount of samples beforehand. So the 54 first voice files include to the first class (=0).
print(" Check the target after changing zeros ")
print(t1)

targets= t1  # this is in vain, but previously I connected t1 and t2
print('Read voice samples')

path = 'Saint_Agnes'
for filename in os.listdir(path):
    naytteet = wavfile_to_examples(path + "/"+filename)[0]
    #naytteet = naytteet.tolist()
   #lista = np.load(filename)
    x_data.append(naytteet.transpose())
    
path = 'Nocturne_4'
for filename in os.listdir(path):
    naytteet = wavfile_to_examples(path + "/"+filename)[0]    
    x_data.append(naytteet.transpose())
   
x_data = np.array(x_data)
print('Create the model:')


model = Sequential()
model.add(LSTM(32,  input_shape = (64,296), return_sequences = True,  kernel_initializer='random_uniform'))
model.add(TimeDistributed(Dense(1, activation = 'softmax', kernel_initializer='random_uniform')))

print('TaRGETS ')
print(targets)
targets = np.reshape(targets, (targets.shape[0], 64,1))

model.compile(optimizer = 'adam', loss='mean_absolute_error', metrics=['accuracy'])#
model.fit(x_data, targets, epochs = 5000)
model.summary()

**Comment by sariagoudarzvand** [comment]
> Thanks again, I have figured out why. Since I thought the softmax layer would automatically deal with the timedistributed stuff, I didn't explicitly set expand the labels to 3-dimension. Now it works.

Can you please share your workaround solution?
I faced the same problem!
