### ISSUE TITLE
Changelog or Release Note?

### ISSUE THREAD

**Issue by bear0330** [fchollet/keras#5217]
Is there any changelog or releasenote for Keras? 
Some projects claims they requires Keras>1.0.7 some requires >1.1 but if I use 1.2.1, some broken because of API change, e.g. CallbackList._set_model disappeared.

Building a awesome library like Keras might provide a changelog or release note and some backward compatibility docs, then the ecosystem might be integrated better.

Thanks. You guys doing a great job.

**Comment by baziotis** [comment]
Here you go: https://github.com/fchollet/keras/releases

**Comment by bear0330** [comment]
Yes, I know anyone can see commit logs from it, but this wouldn't help if anyone want to migrate Keras from, for example 1.0.1, to latest version. This is very important for library, software authors and odinary users. Even no migration needed, users don't know what's new and he/her need to upgrade or not.

**Comment by chenliu0831** [comment]
It's a little bit odd that there's nothing other than tagging descriptions in the release page...

**Comment by marczellm** [comment]
I think this is a major oversight. How should I know whether it's safe to upgrade my Keras installation, (hoping for bug fixes) or if there is a breaking API change or other known regression. There should definitely be a proper changelog.

**Comment by dmzio** [comment]
in addition to changelog, would ask for versioning of docs (on keras.io): it's very confusing to read docs after breaking changes in some new version and be unable to find how it should work in older one.

**Comment by hillarysanders** [comment]
@dmzio I agree. A hack is to pull down the keras repo with your wanted branch / tag (e.g. keras 2.0.2 vs 1.2.2) and serve the versioned docs locally. e.g.:
https://github.com/fchollet/keras/tree/1.2.2/docs

**Comment by faroit** [comment]
@dmzio @hillarysanders I found this just too annoying and now mirrored them in one place here: https://faroit.github.io/keras-docs/
