### ISSUE TITLE
Adding conv1d after lstm

### ISSUE THREAD

**Issue by Achilles-96** [fchollet/keras#5222]
Hello,

I have sequence input of shape (None, 1000, 100)
I added an LSTM(1000) to get output of shape (None, 1000).
Now, I want to add Conv1D(128, 5) but it throws error 'Exception: Input 0 is incompatible with layer convolution1d_1: expected ndim=3, found ndim=2'

Can someone tell me how to add it.

**Comment by tboquet** [comment]
You can reshape the output of the LSTM to `(None, 1000, 1)` but you maybe want to have an `LSTM(1)` with  `return_sequences=True`?
This way you will have the output of your RNN at each time step and you will be able to apply the 1d convolution. Depending on what you want to achieve, you should be able to have `LSTM(any_size)`; returning the sequences is the important point here.
