### ISSUE TITLE
Show Accuracy Error 

### ISSUE THREAD

**Issue by isrugeek** [fchollet/keras#5230]
UserWarning: The "show_accuracy" argument is deprecated, instead you should pass the "accuracy" metric to the model at compile time:
`model.compile(optimizer, loss, metrics=["accuracy"])`
  warnings.warn('The "show_accuracy" argument is deprecated, '

train_acc=hist.history['accu']

KeyError: 'accu'

**Comment by biprajiman** [comment]
Try 'acc'. If that does not work you should be able to print all the history keys using 
print(history.history.keys())

**Comment by isrugeek** [comment]
@biprajiman Thanks Man, i tried but the Same thing .

**Comment by biprajiman** [comment]
I printed the keys this is what I get:
['acc', 'loss', 'val_acc', 'val_loss']

It should work.

I hope you are assigning the history from the model.fit to your hist variable:

hist=model.fit(....)

**Comment by biprajiman** [comment]
Looks like hist.history is an array object. This worked for me:
hist=hist.history.item() // returns dictionary 
hist['acc'] //will give you access to the data you need

**Comment by joelthchao** [comment]
`all_acc = hist.history['acc']  # list of acc`
(no need for `hist=hist.history.item()`)

**Comment by isrugeek** [comment]
@joelthchao @biprajiman Thank you for your Reply, But the problem is occurred due to Compatibility,

**Comment by codeprb** [comment]
> @joelthchao @biprajiman Thank you for your Reply, But the problem is occurred due to Compatibility,

Hi, Could you please let me know what compatibility issues you had? I am facing a similar problem for the code below
print (history.history.keys())

#plot loss and accuracy
plot_history(model.history.history)

def plot_history(history):
    
    loss = history['loss']
    epochs = len(loss)
    

    plt.figure(figsize=(16,4))
    plt.subplot(121)
    plt.plot(range(1, epochs+1), history['loss'], label='loss')
    plt.plot(range(1, epochs+1), history['val_loss'],'g',label='val_loss')
    min_pos = np.argmin(history['val_loss'])
    min_value = history['val_loss'][min_pos]
    plt.scatter(min_pos+1, min_value, color='green', marker='*', label='min = ({}, {:.4f})'.format(min_pos+1, min_value))
    plt.ylabel('loss'); plt.xlabel('epoch'); plt.legend(); plt.grid()
    plt.subplot(122)
    plt.plot(range(1, epochs+1), history['accuracy'], label='accuracy')
    plt.plot(range(1, epochs+1), history['val_accuracy'],'g',label='val_accuracy')
    max_pos = np.argmax(history['val_acc'])
    max_value = history['val_acc'][max_pos]
    plt.scatter(max_pos+1, max_value, color='green', marker='*', label='max = ({}, {:.4f})'.format(max_pos+1, max_value))
    plt.ylabel('accuracy'); plt.xlabel('epoch'); plt.legend(); plt.grid()
    plt.show()


plot_history(model.history.history)
===============================

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])
result: AttributeError: 'dict' object has no attribute 'history'
