### ISSUE TITLE
Call signature of tf.concat has changed in Tensorflow 1.0.0rc0

### ISSUE THREAD

**Issue by lfloeer** [fchollet/keras#5238]
Because the call signature of `tf.concat` has changed to the one of the deprecated `tf.concat_v2`, the creation of a bidirectional RNN layer fails. This happens in either Version 1.2.1 or the latest master versions.

Example:
```
import keras.layers as kl

test_input = kl.Input(shape=(10, 10), dtype='int32')
test_emb = kl.Embedding(input_dim=100, output_dim=10)(test_input)
test_bgru = kl.Bidirectional(kl.GRU(50, return_sequences=True))(test_emb)
```

This fails with
`TypeError: Expected int32, got <tensorflow.python.ops.variables.Variable object at 0x7f162824e588> of type 'Variable' instead.`
since the arguments of value and axis are switched: https://www.tensorflow.org/versions/r1.0/api_docs/python/array_ops/slicing_and_joining#concat
https://www.tensorflow.org/api_docs/python/array_ops/slicing_and_joining#concat

**Comment by neufang** [comment]
same here.  

tributeError                            Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py in concatenate(tensors, axis)
   1424         try:
-> 1425             return tf.concat_v2([to_dense(x) for x in tensors], axis)
   1426         except AttributeError:

AttributeError: module 'tensorflow' has no attribute 'concat_v2'

**Comment by EinsteinInIct** [comment]
I met the similar problem when writing code like below:

“up6 = merge([UpSampling2D(size=(2, 2))(conv5), conv4], mode='concat', concat_axis=1)”

Seems that there are lots of api changes in new version of tensorflow according to:
https://groups.google.com/a/tensorflow.org/forum/#!msg/discuss/OePXmC9kJ7o/SRErOoYCDQAJ

**Comment by fchollet** [comment]
Keras 2 is coming soon, so you should use that. It's developed for TF 1.0.

**Comment by EinsteinInIct** [comment]
Thanks for reply. I had planed to make a pull request. But I found the fix for my problem is already in the newest code.

Looking forward to embrace Keras 2 :)
