### ISSUE TITLE
Deep transition RNNs - Gradient calculation with K.rnn

### ISSUE THREAD

**Issue by dr-costas** [fchollet/keras#5249]
Hi, 

I'm trying to implement a deep transition RNN with keras (see here: https://arxiv.org/pdf/1312.6026v5.pdf ) and the way that I'm thinking to implement it is to have a loop structure inside the `step` method of the `Recurrent` layer. 

This means that for every iteration of the `theano.scan` (I'm using theano) there are gonna be calculations for inputs and outputs for all the inner layer in the `step` method. 

How is the the gradient at the BPTT process calculated in such a case? I mean, does theano treat every iteration of `theano.scan` as a single time step and a single layer or it can "understand" that in the `step` method are also "inner time steps" and inner layers?

In general, if there are some multi-layered calculations inside `step`, will be treated by theano (in terms of BPTT) as a single layer and/or a single time step or the BPTT will take account all the calculations inside the `step` (and effectively, inside `theano.scan`) method?

**Comment by patyork** [comment]
Theano gradient calculations are purely symbolic, based on the created graph. Modifying the inner step (or even nesting scans) will modify the graph, and the gradient will be calculated based on the input and output/loss, with respect to the trainable parameters. Unless your modification does not affect the output or use (in any way) the trainable parameters, it will affect the gradient calculation. In either case, the gradient will be calculated correctly.

**Comment by GuillermoPuebla** [comment]
Hi dr-costas,

Have you had any luck in implementing this in keras?

**Comment by dr-costas** [comment]
Hi, 

Yes. I had it already implemented but I was not quite sure hot the gradient was calculated.

**Comment by GuillermoPuebla** [comment]
Do you think you could share your code? I just need to implement a DT RNN of depth 1, but it would be very useful to have code to experiment with larger depths.

**Comment by dr-costas** [comment]
Hi GuillermoPuebla, 

Ofc! At some point I will share my code.

**Comment by GuillermoPuebla** [comment]
@dr-costas It seems that Recurrent Shop can solve this problem already https://github.com/datalogai/recurrentshop

**Comment by dr-costas** [comment]
Perfect then!
