### ISSUE TITLE
how to add a new layer with back propagation

### ISSUE THREAD

**Issue by skicy** [fchollet/keras#525]
Hi, I am wondering how to add a new layer with back propagation as I could not find any place to state the code for back propagation the error. Does this process (back propagation) automatically cover by theano? 

Or is there any tutorial on this part?

Thanks a lot.

**Comment by pranv** [comment]
Add a new layer by inheriting the `Layer`  class. Write your own `__init__`  & `get_output ` methods. Back propagation is automatically done with theano's help. So is auto CPU/GPU code conversion.

**Comment by skicy** [comment]
Thanks pranv for your help. It is quite helpful. Could I know what I should do if the new layer is non-differentiable? I am new to Theano/keras. Thanks.

**Comment by pranv** [comment]
Well, I don't have much experience myself in that regard. But, I think keras/theano only supports expressions built using the Symbolic Variables. You would have to dig into theano much more I guess.

**Comment by skicy** [comment]
I see. Thanks.
