### ISSUE TITLE
when i train a model in jupyter notebook i see a lot of check marks. what is the reason? 

### ISSUE THREAD

**Issue by curry111** [fchollet/keras#5254]
![screenshot from 2017-02-02 20 48 03](https://cloud.githubusercontent.com/assets/25343445/22563510/7859db42-e989-11e6-9e9a-b62fa3e782eb.png)

this is the first time to install keras, i did not use anaconda 
i am using Ubuntu 14.04 

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by cccue** [comment]
I had the same problem. Yet you're posting to the wrong place. This seems to be an issue with the ipython notebook package. As a quick fix you can rollback your changes to notebook==4.0.6 for example.
pip uninstall notebook
pip install notebook==4.0.6
That should do it.
my config: Ubuntu 14.04, python 2.7, keras 1.2.1, tensorflow 0.12.1

**Comment by msgfxeg** [comment]
@cccue 
That helped me alot. Thanks
also I have tired and tested notebook==4.2.0 can do the same thing and a bit newer that 4.0.6

**Comment by cccue** [comment]
@msgfxeg 
Glad it helped! At first I thought Nike had finally decided to endorse the notebook devs ;-)
But nahh, same old, same old. Thanks for testing usability of new versions of the notebook package.

**Comment by msgfxeg** [comment]
@cccue Nike LOL :))))))
