### ISSUE TITLE
Missing document--Repeat function in Image captioning

### ISSUE THREAD

**Issue by sq6ra** [fchollet/keras#526]
Hello All

http://keras.io/examples/#image-captioning

In the example of Image Caption, there is a function: Repeat()
```sh
model.add(Repeat(max_caption_len)) 
```
I couldn't find doc of this function in Keras.io

Perhaps it is for using the output y head as input feedbacks when generating sequences ?

Could anyone tell me what's it for, and which module I can find it ? Thank you !

**Comment by lukedeo** [comment]
Check out `RepeatVector`.

**Comment by sq6ra** [comment]
Thank you for reply. 

Personally I don't think Repeat is the RepeatVector

The example is more likely using its previous output Y head , as input..

Are you 100% sure about it ? @lukedeo

**Comment by fchollet** [comment]
Yes, that would be `RepeatVector`. 

About `RepeatVector`:
```
Dimensions of input are assumed to be (nb_samples, dim).
Return tensor of shape (nb_samples, n, dim).
```
Here `RepeatVector` turns a feature vector into of sequence of this same feature vector repeated `max_caption_len` times.
