### ISSUE TITLE
Training an autoencoder without making a second copy of the training set

### ISSUE THREAD

**Issue by Valentin4869** [fchollet/keras#5260]
I'm trying to train a model using a big data set, but since it's an autoencoder, I have to pass the same training set twice, both as "X_train" and "y_train":

`model2.fit(X_train, X_train, nb_epoch=16);`

But this is a huge waste of memory and the machine can't handle it. Is there a way to pass them to the function "as reference"? Or maybe some other workaround?

Thanks

**Comment by kushia** [comment]
You could train it by batch : 
https://keras.io/models/sequential/#train_on_batch
