### ISSUE TITLE
question on LSTM training and clear the memory state

### ISSUE THREAD

**Issue by skicy** [fchollet/keras#527]
Hi,
    My question is as below:
I have an input vector, e.g., 100-d, and I need to feed the same vector into the LSTM multiple times, e.g., 5 times sequentially, and hopefully I can get 5 different outputs based on the input. How could I do this? Based on the input of LSTM layer, the input dimension is fixed, e.g. 100, how should I handle a 100*5 input based on sequential input?

Also, after one input, how should I manually clear the memory state inside the LSTM so that I can feed another (different) input vector to LSTM? 

Many thanks for the help.

**Comment by fchollet** [comment]
Each input is treated independently by the LSTM layer, memory is cleared between ever sample. You don't need to do anything in particular.

**Comment by erfannoury** [comment]
So how can memory reset be prevented?

**Comment by fchollet** [comment]
@erfannoury : see https://github.com/fchollet/keras/issues/98

**Comment by erfannoury** [comment]
@fchollet Thanks. I will take a look.
