### ISSUE TITLE
Using Theano backend. Traceback (most recent call last):   File "C:\Users\liangxin\dive_into_keras\cnn.py", line 37, in <module>     data, label = load_data()   File "C:\Users\liangxin\dive_into_keras\data.py", line 21, in load_data     imgs = os.listdir("./mnist") WindowsError: [Error 3] : './mnist/*.*'

### ISSUE THREAD

**Issue by L-Matthew** [fchollet/keras#5282]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by patyork** [comment]
Even with the terrible formatting:

The answer is that you need to download the dataset, and put it in the correct location.

**Comment by L-Matthew** [comment]
[keras_usage.zip](https://github.com/fchollet/keras/files/753567/keras_usage.zip)
i do it as this,but it still has this  error  @patyork

**Comment by patyork** [comment]
You're 100% sure you extracted it to a folder called `mnist/`?

**Comment by patyork** [comment]
`mnist/mnist/` is not `mnist/`

Extract it correctly and you'll be fine.

**Comment by L-Matthew** [comment]
@patyork  Ok, i will try again. Thank you
