### ISSUE TITLE
How to implement a Cube Activation function

### ISSUE THREAD

**Issue by freesunshine0316** [fchollet/keras#5283]
I'm writing my own activation function (element-wise cubic) with the template from https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L255.
I searched the Keras backend and only found the square() function.
I also see the pow() function, but it needs another tensor with the same shape of the input. Can anyone teach me how to implement that?

**Comment by freesunshine0316** [comment]
I'm writing my own activation function (element-wise cubic) with the template from https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L255.
I searched the Keras backend and only found the square() function.
I also see the pow() function, but it needs another tensor with the same shape of the input. Can anyone teach me how to implement that?

**Comment by joelthchao** [comment]
Is this what you want?
```
Lambda(lambda x: x*x*x)
```

**Comment by freesunshine0316** [comment]
I think so, thank you.
