### ISSUE TITLE
"ValueError: Invalid control character at: line 2 column 35 (char 36)"

### ISSUE THREAD

**Issue by maurus56** [fchollet/keras#5295]
Getting this error when trying to import keras. Appeared after moving to tensorflow, but the keras.json was modified as instructed.

Any help is appreciated.

![screen shot 2017-02-06 at 2 33 54 pm](https://cloud.githubusercontent.com/assets/20258911/22660853/70df50ca-ec79-11e6-8a54-14570c1659fc.png)
![screen shot 2017-02-06 at 2 34 20 pm](https://cloud.githubusercontent.com/assets/20258911/22660854/70e82fb0-ec79-11e6-957d-7780a7279f92.png)

**Comment by patyork** [comment]
Make sure you've saved the keras.json file; the json pictured looks valid.

Also, whenever possible, text is much better than screenshots.

**Comment by patyork** [comment]
As I said, you should paste text.

Your quotation marks after the "tf" is not a quotation mark.

**Comment by maurus56** [comment]
Thaks a lot, I would have never seen that
