### ISSUE TITLE
Accessing internal states

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#53]
Hey guys, cool project. The theano interface itself was really horrific and off-putting. 

Maybe I'm doing it wrong but is there any way to access the activations of different layers? Similar to predict but only computed half way. Would be really useful for analysis and the likes.

**Comment by fchollet** [comment]
Sure, you can. See the answer to this question: https://github.com/fchollet/keras/issues/41

It will probably be made more straightforward in future API upgrades.
