### ISSUE TITLE
Issue with LSTM layer in Keras 1.2.1

### ISSUE THREAD

**Issue by kevinchangwang** [fchollet/keras#5300]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I am running on Theano 0.8.2 in with Keras 1.2.1 (downloaded from PyPI) in the Anaconda scientific package on Ubuntu 16.04 LTS.
I installed the nvidia cuda library using apt-get install nvcc and directed Theano to the library. Testing it with the GPU testing script provided [here](http://deeplearning.net/software/theano/tutorial/using_gpu.html) works just fine. It shows that the GPU is used and raises no errors. 

I am trying to run the imdb_lstm.py example in the examples folder and it gave me the following error. 

[PasteBin](http://pastebin.com/JQDpPyLz)

This didn't happen with version 1.2.0. I tried going back to the previous version but the conda skeleton command would not let me download version 1.2.0 again even after specifying it with the flag --version 1.2.0. Is there a way to 

1. Fix this error
2. Install 1.2.0 in Anaconda
3. Install the master branch of Keras into Anaconda if it is not the same as the one on PyPI

**Comment by jmhessel** [comment]
Update your theano to the dev version and try again

**Comment by kevinchangwang** [comment]
I upgraded to Theano 0.9 dev and the problem persists. It's the exact same error. I managed to find an older version of Keras on the Anaconda Cloud that was 1.2.0 and installed it. The older version works just fine with both Theano 0.8.2 and 0.9 dev.
