### ISSUE TITLE
How to concat two layers?

### ISSUE THREAD

**Issue by qinhaifangpku** [fchollet/keras#5302]
hi~
I am now want to concat two layers output and then use it to convolution and generate next feature maps.
I have tried the Mergr Layer, it just support merge two model.  but not two layers' output.
Anyone here could help me out the problem? thank you very much in advance !

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by jmhessel** [comment]
You might have more success on StackOverflow or the Keras slack channel. However, merge does support merging of two layers' outputs. The example in the documentation shows an example of this.

https://keras.io/layers/core/#merge
