### ISSUE TITLE
theano is going to switch from cuda to gpuarray, are we going to support api changes?

### ISSUE THREAD

**Issue by fayeshine** [fchollet/keras#5303]
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release.  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

theano is going to switch from cuda to gpuarray, the api may have some changes, will we support this change?

**Comment by Dapid** [comment]
I believe it is already compatible. For example, Keras is using [`theano.tensor.nnet.conv2d`](https://github.com/fchollet/keras/blob/master/keras/backend/theano_backend.py#L1516) and the only occurences of `theano.sandbox.cuda.dnn` are in instances of ` _old_batch_normalization` and the like.

I am installing libgpuarray and will do some testing.

**Comment by Dapid** [comment]
I have a simple 3D CNN that works with the new backend. The runtime seems to be slightly longer ( < 10%), but I haven't activated any of the new optimisations.

**Comment by fayeshine** [comment]
@Dapid , How to activate new optimizations in keras?

**Comment by Dapid** [comment]
Through THEANO_FLAGS. The ones I looked at aren't activated by default because they take more memory. http://deeplearning.net/software/theano/library/tensor/nnet/conv.html

For example, `THEANO_FLAGS=optimizer_including=conv3d_fft:convgrad3d_fft:convtransp3d_fft`

You can also activate it per function. In Keras you can pass them as kwargs in `model.compile`.

**Comment by nouiz** [comment]
Those are old flags for the old back-end. They won't affect the speed on
the new back-end.

To compare the speed of both back-end, you should ignore the time in the
first call. Some compilation happen at that moment when we know the strides.

**Comment by nouiz** [comment]
I made an issue to update this doc:
http://deeplearning.net/software/theano_versions/dev/library/tensor/nnet/conv.html

**Comment by HenryJia** [comment]
Hmm, although do you find that you get a discrepancy between the old and the new backends?
I can't seem to get the new backend to work at all
https://github.com/Theano/Theano/issues/5475

**Comment by nouiz** [comment]
Just a follow up, the problem was a bad NVIDIA driver. Now inside
libgpuarray we black list it.

**Comment by alyato** [comment]
hi @Dapid @nouiz I install the latest keras which is `2.0.4,` it show me an error. Then i upgrade the theano to `0.9` `dev` , the new theano show me switch to new gpu backend.

> ValueError: You are tring to use the old GPU back-end. It was removed from Theano

Does i  switch the new gup backend ? or is there good idea? Thanks.
