### ISSUE TITLE
Using CPU instead of GPU with Tensorflow backed

### ISSUE THREAD

**Issue by kushia** [fchollet/keras#5306]
Hi everyone,
I was wondering how to use only the CPU with tensorflow backend ? I know how to do it with Theano, but I can't figure out how to do it with tf...
Thanks!

**Comment by Ori226** [comment]
You can set the environmental variable "CUDA_VISIBLE_DEVICES" to be empty ("" for example) when running your code. This work even if you install the GPU version of tensorflow. Does anyone know of other possibility?
