### ISSUE TITLE
Does it make sense to offset filters in Convolution1D?

### ISSUE THREAD

**Issue by pjadzinsky** [fchollet/keras#531]
Hi,

Implementation of Convolution1D follows closely that of Convolution2D although the problems are quite different since one is most likely meant for time and the other for images. The way I understand it, if we have a time series and convolve with a 1D filter with N points, the output at time t0 corresponds of overlaying N/2 filter points to what happened prior to t0 and N/2 to filter points what happens after t0 (an acausal filter). The fact that the convolution is centered with the filter is fine for images but for time I think we want the possibility of creating an offset. I think in most cases what we want is for all N points in the filter to be in the past such that the convolution output at time t0 corresponds to overlapping all N filter points to what happened just prior to t0 (causal filter).

Another solution would be to constrain half the filter (or whatever number of points we want) to be zero, but I don't think the 'Constraints' can yet handle this.

I can make the necessary changes but before I do that I'd like to know if this sounds like a good idea, whether there are other suggestions and what approach Francois would prefer.

Thanks
Pablo

**Comment by fchollet** [comment]
> The fact that the convolution is centered with the filter is fine for images but for time I think we want the possibility of creating an offset

Isn't this what `border_mode` is about?

What dimensions stand for does not matter. Convolution is still convolution whether your continuous dimension is 2D space, or 1D time, or 3D space. An implementation that would be time-specific would not be desirable, since Convolution1D may well be applied to problems where the continuous dimension is not in fact time.

**Comment by pjadzinsky** [comment]
Hi Francois,

Thanks for the reply. 

I agree with your philosophy and you are correct about `border_mode` but using `border_mode=‘full’` by itself brings another problem. See this simple example:

```javascript
from spicy import convolve
s = range(10)
f = [1,1,1]

c_full = convolve(s, f, ‘full’)
array([ 0,  1,  3,  6,  9, 12, 15, 18, 21, 24, 17,  9])

c_valid = convolve(s, f, ‘valid’)
array([ 3,  6,  9, 12, 15, 18, 21, 24])

c_same = convolve(s, f, ‘same’)
array([ 1,  3,  6,  9, 12, 15, 18, 21, 24, 17])
```

What I would like is a way of outputting 
`c_out = array([ 0,  1,  3,  6,  9, 12, 15, 18, 21, 24])`

c_out is a shorter version of c_full, and allows for example to use straight mse loss between another input (same shape as `s`) and the model output. My models are very deep and I wouldn’t want my representations to have different sizes at each layer. It makes it very difficult to combine layers and even if I didn’t combined them I’ll have to take care of the difference in sizes at the end anyway correct?

Following your suggestions, the new question is: is there a way in keras to split a layer representation? I’m thinking something opposite to what a graph does with `inputs`. Something along the lines of 

`graph.add_node(Split([:-2],[-2:]), outputs=[‘first_part’, ‘tail’], input=‘c_full’)`

BTW, at some point I was working on an image classification problem and I wanted to do something very similar. Split the image in half, process each half with the same architecture and then combine the outputs for each half.

Thanks again

**Comment by fchollet** [comment]
> is there a way in keras to split a layer representation?

You could definitely implement one. The output of such a layer would be a dictionary mapping output names to output tensors. Then you can connect each of these output tensors to downstream containers by manually setting the `input` attribute of the downstream layers.

It's sort of hackish, certainly. Very easy to do, though.

Is there a clear need to add out-of-the-box support of this in Keras? I'm skeptical.

**Comment by pjadzinsky** [comment]
Thanks I'll work on it and will probably send you a PR so that at least you'll have a record of it.

**Comment by pjadzinsky** [comment]
Can you please expand or point me to where to look on how to connect each of these tensors to downstream containers?

Thanks
