### ISSUE TITLE
Merge concat mode fails if only some of the inputs are masked on Tensorflow

### ISSUE THREAD

**Issue by nelson-liu** [fchollet/keras#5311]
Continuation of #3205 , since the issue has not been completely fixed.

**Code to reproduce**:
```
from keras.layers import Input, Embedding, merge

input1 = Input(shape=(2,), dtype='int32')
input2 = Input(shape=(2,), dtype='int32')
embedding = Embedding(input_dim=5, output_dim=10)
masked_embedding = Embedding(input_dim=5, output_dim=10, mask_zero=True)
embedded_input1 = embedding(input1)
embedded_input2 = embedding(input2)
masked_embedded_input1 = masked_embedding(input1)
masked_embedded_input2 = masked_embedding(input2)
both_unmasked_concat = merge([embedded_input1, embedded_input2], mode='concat')
both_masked_concat = merge([masked_embedded_input1, masked_embedded_input2], mode='concat')
one_masked_sum = merge([masked_embedded_input1, embedded_input2], mode='sum')
one_masked_concat = merge([masked_embedded_input1, embedded_input2], mode='concat')
```

I get `TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [bool, uint8] that don't all match.` from this code on the Tensorflow backend. It works properly in the theano backend.

I think the issue lies in [line 1524 of topology.py](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L1524-L1527), where there is an explicit cast to `uint8`. The `Embedding` layer returns a mask of type `bool`, so they are incompatible.

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by vsoto** [comment]
I'm having the same problem. Any fix?

**Comment by vsoto** [comment]
And here is my code:

`    token_layer = Input(shape=(sequence_length,), dtype='int32')
    embedding_layer = Embedding(input_dim=voc_size + 2, input_length=sequence_length, output_dim=embedding_size,
                                mask_zero=True)(token_layer)

    features_layer = Input(shape=(sequence_length, 4))
    dense_layer = Dense(output_dim=4)(features_layer)

    merged = merge([embedding_layer, dense_layer], mode='concat')`
