### ISSUE TITLE
Is there a way to invert a layer (inverse projection) so that it can accept its own output back as input?

### ISSUE THREAD

**Issue by Valentin4869** [fchollet/keras#5323]
I'm trying to implement an autoencoder that will receive an input vector (forward pass), and then feed it back to itself in the reverse direction. I basically want to reproduce the work from this [paper`](http://www.ipab.inf.ed.ac.uk/cgvu/motioncnn.pdf), as explained in the last paragraph of section 5. In the paper, they flip the weights matrix to simulate the backward pass (according to my understanding), so I'm wondering if keras offers a similar functionality?

Thanks

**Comment by unrealwill** [comment]
Hello, I'm not aware of a functionality to invert a layer generically. But you can tie weights (i.e : reuse weights from another layer), and create a custom layer which does the inverse operation but reusing the weights from the original layer.
Something like class DependentDense of https://github.com/nanopony/keras-convautoencoder/blob/master/autoencoder_layers.py should work.

**Comment by tstandley** [comment]
I agree with what @unrealwill said. That's a good solution in the cases where it makes sense, but I would add that many layers aren't invertable by nature, so there could be no good, layer-independent way for Keras to expose such functionality.

**Comment by Valentin4869** [comment]
Thank you for your answers.

**Comment by hamidreza48** [comment]
The reverse of a Conv2D layer is a Conv2DTranspose layer, and the reverse of a MaxPooling2D layer is an UpSampling2D layer.
