### ISSUE TITLE
run imdb_lstm.py   error: 'callkernel_node'  is undefined

### ISSUE THREAD

**Issue by 1064950364** [fchollet/keras#5336]
error info:
mod.cu(299): error: identifier ''callkernel_node_3a084fd032db206a67ca8121a24aa32e_0'' is undefined
1 error detected in the compilation of ''C:Users/aa/AppData/Local/Temp/tmpxft_000041d4_00000000-10_mod.cpp1.ii''

when I run mnist_cnn.py, it worked well. But when I run the imdb_lstm.py, It didn't work.

numpy1.12.0
theano0.8.2
pip8.1.2
Anconda2.7
CUDA7.5
cudnn-7.5-windows7-x64-v5.0-ga
keras1.2.1
GCC4.7.0	

.theanorc.txt:
[global]
openmp=False
device = gpu
optimizer_including=cudnn
floatX = float32
allow_input_downcast=True
[lib]
cnmem = 0.8
[blas]
ldflags=
[gcc]
cxxflags=-ID:\Anaconda2\MinGW
[nvcc]
fastmath = True
flags=-LD:\Anaconda2\libs
compiler_bindir=D:\VS2012\VC\bin

when I run mnist_cnn.py, it worked well. But when I run the imdb_lstm.py, It didn't work.
Please help me!

**Comment by rodrigomfw** [comment]
I am getting the same error

**Comment by rodrigomfw** [comment]
```
    model.add(LSTM(n_hidden[0], input_shape=(seq_length, X.shape[2]),
                           return_sequences=False,W_regularizer=l2(w_reg)))
    model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=nb_epoch,
              class_weight = {0:1, 1:2*n_int/n_ict},validation_data=(X_test,y_test),callbacks=callbacks)``
```

This l

**Comment by iamkkk** [comment]
I run into the same error with theano backend and latest keras1.2.1. But no error if using keras 1.2.0

**Comment by 1064950364** [comment]
when I add 'optimizer=None' to .theanorc.txt, it worked.But it maybe run too slow.
Maybe  it  related to CUDNN?
My OS:win10

**Comment by 1064950364** [comment]
@iamkkk   Thank you,it worked when I used keras 1.2.0

**Comment by rodrigomfw** [comment]
@iamkkk Also worked for me! Thank you so much

**Comment by helloabc99** [comment]
Thank you so much.
