### ISSUE TITLE
out of memory when using model.predict()

### ISSUE THREAD

**Issue by qinhaifangpku** [fchollet/keras#5337]
hi~ I am now using keras to build my network. the training is normal. but when I use the model.predict() to predict the results, it happend to a error : 
out of memory.
It is weired because it can train normally but can not test.
Please help me, thank you very much!

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by unrealwill** [comment]
Hello,
I agree with you that it seems strange, because model usually use less memory to predict than to train. It happened to me once or twice when I was near the max of the memory. Graphs in train phase and in predict phase are usually different, so they can result in a different memory allocation resulting in different memory segmentation and different memory usage. 
If it is indeed an out of memory bug.
You can try to set a small batch_size in predict.
You can try to monitor the memory usage using nvidia-smi.
You can also save the model weights after training. Close python. Relaunch it, Load model weights from disk and try a model.predict from fresh.
You can try to use CNMeM.
If this is not an out of memory bug but something more subtle, You will have to investigate more and provide more info.

**Comment by qinhaifangpku** [comment]
@unrealwill  thank you for your advice, but I  have decrease the batch size. it did not work. and relaunch the python ,it did not work either. 
I use the K.function() can get the middle layer output but when i try to get the last layer to get the predict results. it failed. out of memory....

**Comment by unrealwill** [comment]
https://keras.io/getting-started/faq/
"How can I obtain the output of an intermediate layer?"

Have you tried the first method instead of K.function() (I'm not used to K.function() so can't advice you) 

Try monitoring the memory usage (print summary and nvidia-smi) or try running it in CPU.
If you get it to work with more memory then you are just on the limit and this is not a bug. If you don't get it to work with more memory then you probably have a bug somewhere in your code but you don't provide enough information.

**Comment by qinhaifangpku** [comment]
@unrealwill  hi~ very appreciate for your advice!  I am now can use the model.predict() function to predict results.  it is out of memory because i did not set the batch size to 1 or 2.  So it may convert all the images to the network so it happened to out of memory error.

**Comment by sarath777** [comment]
Resize the image
since its fully connected layer and you are giving large image for prediction it will take whole the memory, so you need to resize the image before prediction

**Comment by f-huang** [comment]
I also ran into this `MemoryError` when trying to predict an array with shape (62000, 190000).
I used [DennyBritz ](https://github.com/dennybritz/cnn-text-classification-tf/blob/master/text_cnn.py)text-cnn-model. Fitting on hundreds of thousands lines works fine. (training's input shape approximately equals (500000, 190000) with batch_size=128)

I tried predicting using `model.predict()` with `batch_size` at `1, 2, 8, 16, 32, etc.` it still doesn't work.
When I predict on less lines (30000), it works though.

I tried looping through the predictions but still got the Error.
How can I solve this ? 

-----------------------------------------------------------------------
Current predict:
`Y_pred = self._trained_model.predict(X, batch_size=32, verbose=1, workers=self.workers, use_multiprocessing=True)`

-----------------------------------------------------------------------
Predictions loop:
```
Y_pred = []
i, chunksize = 0, 10000`
for idx in range(0, len(X), chunksize):
    Y_pred += list(self._trained_model.predict(X[idx:(i+1)*chunksize],
                verbose=1, batch_size=1))
    i += 1
Y_pred = np.array(Y_pred)
```

**Comment by brandonbell11** [comment]
Same issue. I am using model.predict() in a loop and appending that scalar to an array. It appears the results from model.predict() are kept around somewhere and it is ballooning my memory and causing OOM errors after some time.

**Comment by petamind** [comment]
Same issue. I used model.predict() and it blew 35GB TPU

**Comment by marnixkoops** [comment]
Same issue here, calling `model.predict` on a (210944, 4) dimensional array running on a Tesla P100-16GB

**Comment by M00NSH0T** [comment]
if anyone else encounters this, try:

```
from tensorflow.compat.v1.keras.backend import set_session
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True  # dynamically grow the memory used on the GPU
config.log_device_placement = True  # to log device placement (on which device the operation ran)
sess = tf.compat.v1.Session(config=config)
set_session(sess)
```
I found the code in a Medium post, but it fixes a lot of memory related issues I've encountered with tensorflow 2.0+.

Here's the [Medium post](https://kobkrit.com/using-allow-growth-memory-option-in-tensorflow-and-keras-dc8c8081bc96)

**Comment by morrolinux** [comment]
I can confirm that.. How is this issue still closed?

**Comment by kimmo1019** [comment]
> I have the same problem: both my model and one batch takes around 10% of the GPU memory. When I use .predict(...) or run the model in a loop using the call function (model(...)), I run out of memory after a while - no matter the batch size. In your implementation it seems the data is kept on the GPU, even after it is returned to the host device - which is unquestionably a bug, there's no extra computation that one could do with the previous batch remaining in the GPU memory.

any updates? I came across the same problem, model.predict in a loop, it raised OOM error.

**Comment by Tobs40** [comment]
I'm having the same issue, it's been a while, no fix yet?

Seems like it occurs in combination with model.fit(), runs fine with an untrained model.

**Comment by yrogory** [comment]
you can use garbage collection to clean up keras variables. import gc and then call gc.collect() after each call to model.predict()

**Comment by siserte** [comment]
Same problem here. When I use model.evaluate, it works fine.
However, with model.predict it lreads to an OOM.

**Comment by cvarrichio** [comment]
Same problem here.  Even a (1,3000) tensor is causing an OOM on a dedicated V100.  Training had no issues.  I believe the problem may be an inssue in Tensorflow, not Keras.

**Comment by alikaanguven** [comment]
Mine tries to load all the test dataset onto the GPU. Thus, it blows up!
None of the solution suggestions above worked for me either.

**Comment by critopadolf** [comment]
I also face this issue with model(data) and model.predict(data, batch_size=1), I get OOM

**Comment by shanggao11** [comment]
I tried lots of methods online, they did not work, but I finally solve this problem by using tensorflow 1.13 rather than 2.x , old version did help.

**Comment by momei123** [comment]
> Same problem here. When I use model.evaluate, it works fine.
> However, with model.predict it lreads to an OOM.

prediction = model(data) is slow!

**Comment by fight-think** [comment]
> 

I tried this method. It works.

**Comment by fight-think** [comment]
> you can use garbage collection to clean up keras variables. import gc and then call gc.collect() after each call to model.predict()

I tried this method. It works.

**Comment by SharuPaul** [comment]
Is there a solution to this problem?

**Comment by ekurtgl** [comment]
For anyone who faces with this error, there is a high chance that during model.fit() or model.predict(), the model tries to load all the dataset to the GPU memory, even if you specify the batch size. I solved my problem using data loaders. Here is an example:

``` python
def data_generator(data, labels, batch_size=1):              
    """
    Yields the next training batch.
    data is an array  [[[frame1_filename,frame2_filename,…frame16_filename],label1], [[frame1_filename,frame2_filename,…frame16_filename],label2],……….].
    """
    num_samples = data.shape[0]
    
    while True:   
        for offset in range(0, num_samples, batch_size):
    #             print ('starting index: ', offset) 
            # Get the samples you'll use in this batch
            batch_samples = data[offset:offset+batch_size]
            label = labels[offset:offset+batch_size]
            # Initialise X_train and y_train arrays for this batch
            X_train = []
            y_train = []
            # For each example
            for i in range(0,batch_samples.shape[0]):
                X_train.append(batch_samples[i])
                y_train.append(label[i])

            # Make sure they're numpy arrays (as opposed to lists)
            X_train = np.array(X_train)
            #X_train = np.rollaxis(X_train,1,4)
            y_train = np.array(y_train)

            # yield the next training batch            
            yield X_train, y_train
```

Then you create datasets:

``` python
train_dataset = data_generator(x_tr, y_tr, batch_size=batch_size)
test_dataset = data_generator(x_ts, y_ts, batch_size=batch_size)
```

Then fit the model:

``` python
history = model.fit(train_dataset, validation_data = test_dataset,
                        epochs=200, verbose=1, callbacks=[early_stopping, PlotLossesCallback(),
                        LearningRateScheduler(lr_time_based_decay, verbose=0)],
                        steps_per_epoch = math.ceil(len(x_tr) / batch_size),
                        validation_steps = math.ceil(len(x_ts) / batch_size)
                        )
```

For model.predict() you can modify the data loader to:

``` python
def data_generator_pred(data, batch_size=1):              
    """
    Yields the next training batch.
    data is an array  [[[frame1_filename,frame2_filename,…frame16_filename],label1], [[frame1_filename,frame2_filename,…frame16_filename],label2],……….].
    """
    num_samples = data.shape[0]
    
    while True:   
        for offset in range(0, num_samples, batch_size):
    #             print ('starting index: ', offset) 
            # Get the samples you'll use in this batch
            batch_samples = data[offset:offset+batch_size]
            # label = labels[offset:offset+batch_size]
            # Initialise X_train and y_train arrays for this batch
            X_train = []
            # y_train = []
            # For each example
            for i in range(0,batch_samples.shape[0]):
                X_train.append(batch_samples[i])
                # y_train.append(label[i])

            # Make sure they're numpy arrays (as opposed to lists)
            X_train = np.array(X_train)
            #X_train = np.rollaxis(X_train,1,4)
            # y_train = np.array(y_train)

            # yield the next training batch            
            yield X_train#, y_train
``` 
and prediction loader:

``` python

pred_dataset = data_generator_pred(x_ts, batch_size=batch_size)
```
then call prediction function:

``` python
preds = model.predict(pred_dataset, steps=len(x_ts) // batch_size
```

I hope this helps!

Best,
Emre

**Comment by FabianS42** [comment]
Got the same problem for large test dataset. I used a workaround with multiple calls to predict and reshape the data. This way I can still use the speed of the GPU. 


```
steps_per_predict = batch_size * 32  # 32 steps for each predict call

with tf.device("/gpu:0"):
    pred_tmp=[] 
    for i in range(0, len(preprocessed_x_fault_test), steps_per_predict): # Do multiple predicts
        pred_tmp += [model.predict(preprocessed_x_fault_test[i:i+steps_per_predict],batch_size=batch_size, verbose=0)] 
        print("current sample",i)


shape = np.array(pred_tmp[0:-1]).shape
pred = np.reshape(pred_tmp[0:-1], (shape[0]*shape[1],shape[2],shape[3]))
pred = np.append(pred, pred_fault_tmp[-1], axis=0)
```

**Comment by tashrifbillah** [comment]
Same issue on Tensorflow 2.16.1, Redhat 9 Linux, NVIDIA RTX 4080 GPU, Python 3.11.

It is wired that Tensorflow holds GPU memory after `model.fit()` is finished. Again, with `model.predict(batch_size=1)`, I see `Volatile GPU-Util` in `nvidia-smi` output to be only 1% but it still errors out.

Hence, I had to predict on chunks:

```python
results= []
batch= 1000
i=0
while i<25000:
    print(i)
    r= model.evaluate(x_test[i:i+batch], y_test[i:i+batch])
    results.append(r[1])
    i+=batch

average_accuracy= sum(results)/len(results)
```

I credit this idea to https://github.com/keras-team/keras/issues/5337#issuecomment-499472601 .
