### ISSUE TITLE
Allow layer to have multiple inputs

### ISSUE THREAD

**Issue by pcyin** [fchollet/keras#534]
Sometimes it's highly beneficial if a ``Layer`` can have multiple inputs tensors (with different shapes). For example, if we want to compute the weighted sum of ``N`` vectors, which are stored in tensor ``T1`` of shape ``(nb_vectors, dim)`` and the weights are given by another tensor ``T2`` of shape ``(nb_vectors, 1)``. The weighted sum can be computed using a ``Layer`` with two input tensors ``T1`` and ``T2``. But in current implementation of Keras, it seems that we must concatenate ``T1`` and ``T2`` first and feed the concatenated tensor to a Layer and then split them during computation.

**Comment by pjadzinsky** [comment]
Do you want to learn tensor T2?

**Comment by pcyin** [comment]
@pjadzinsky ``T2`` could be derived from a DNN (e.g., as in attention model)

**Comment by fchollet** [comment]
When you are merging layers, you can either concatenate the outputs, or sum the outputs (it's a keyword argument in `Merge` or in the `add_node` method of the `Graph` model). If each of your channels gets through a multiplication (the implementation of a scalar multiplication layer is trivial), and then all channels get merged with the `sum` option, you get your weighted sum. 

Does this solve your problem?

**Comment by pcyin** [comment]
@fchollet Thanks for your reply! Yes:) it's exactly my current implementation. But I was still wondering if there was any plan to natively support multiple input channels.

**Comment by fchollet** [comment]
It's already supported in the general connectivity framework, though no layer implements it at this time (except the Graph container, which can accept multiple inputs from incoming layers). 

See: https://github.com/fchollet/keras/blob/master/keras/layers/containers.py#L129-L136

**Comment by wolterlw** [comment]
I am currently adapting Spacial Transformer Network for Keras
The idea was to isolate `Grid generator` and `Sampler` units to a single Layer with inputs 
**U** (image batch) and **Theta** ( Mat(2x3) generated by Localisation network)
![stl_scheme](https://user-images.githubusercontent.com/11466975/29916501-a7ee9948-8e47-11e7-8bc1-bac1fbda4073.png)
Any suggestions?
