### ISSUE TITLE
Stateful Bidirectional ConvLSTM2D error

### ISSUE THREAD

**Issue by Russ09** [fchollet/keras#5344]
When attempting to build a ConvLSTM2D class, with stateful=True wrapped in a Bidirectional wrapper I get the error

"
Traceback (most recent call last):
  File "/home/rb16/Documents/unet/tests/stateful_test.py", line 6, in <module>
    layer1 = Bidirectional(ConvLSTM2D(10, 3, 3, stateful=True))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/wrappers.py", line 166, in __init__
    self.backward_layer = layer.__class__.from_config(config)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 899, in from_config
    return cls(**config)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional_recurrent.py", line 299, in __init__
    super(ConvLSTM2D, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional_recurrent.py", line 91, in __init__
    super(ConvRecurrent2D, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 326, in __init__
    batch_input_shape = tuple(kwargs['batch_input_shape'])
TypeError: 'NoneType' object is not iterable
"

This issue was addressed in the standard Recurrent class here: 
https://github.com/fchollet/keras/issues/4421

But ConvLSTM2D inherits from ConvRecurrent2D rather than Recurrent, and the implementation of get_config() in ConvRecurrent2D has not had this fix applied to it. 

Minimum reproducing example:

```
from keras.layers import *
from keras.models import *


input = Input(batch_shape=(1, 10, 1, 20, 20))
layer1 = Bidirectional(ConvLSTM2D(10, 3, 3, stateful=True))

model = Model(input=input, output=layer1)
model.compile('adam','mean_squared_error')

```

- [ x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [n/a ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by unrealwill** [comment]
I don't quite know the specific of ConvLSTM2D.

But I find it really strange that we could apply a Bidirectional wrapper to a stateful model.
I mean does it make sense from the mathematical point of view ?
Because in the case of a stateful model we stream the input. So does it make sense to read partial streams in both directions. The backward direction would be doing some kind of smoothing which looks like garbage.

It seems like if when doing text prediction we would ask the model to predict the next(s) sentence(s) in reverse, from the summary of the previous sentence(s) in reverse. There is a huge time jump which is introduced here.

**Comment by Russ09** [comment]
I was also quite confused about this. I mainly submitted because I saw that a similar fix had been merged for the standard Recurrent layer so I presumed that something that I hadnt quite grasped was being done in the stateful model.

**Comment by RajeshThevar** [comment]
Can you please let me know how this issue was overcome ? A bidirectional unit can have stateful to be true ?
