### ISSUE TITLE
the doc of  'constraints 'maybe wrong , need confirmmtion or make clear!

### ISSUE THREAD

**Issue by andyyuan78** [fchollet/keras#535]
Usage of constraints

Functions from the constraints module allow setting constraints (eg. non-negativity) on network parameters during optimization.

The penalties are applied on a per-layer basis. The exact API will depend on the layer, but the layers Dense, TimeDistributedDense, MaxoutDense, Convolution1D and Convolution2D have a unified API.

-----why say 'The penalties are applied on a per-layer basis. '  here?

**Comment by fchollet** [comment]
It means that you configure these constraints independently for each layer. There is a 1:1 relationship between layers weight matrices and constraints.

**Comment by andyyuan78** [comment]
what's the relationship between 'penalties'  and 'constraint'? are they same?
