### ISSUE TITLE
fully convolutional neural network in Keras

### ISSUE THREAD

**Issue by wenouyang** [fchollet/keras#5369]
Dear All,

Just curious, are there any workable fully convolutional network implementation using Keras? One of the essential operation in FCN is deconvolutional operation, which seems to be able to be handled using `tf.nn.conv2d_transpose` in `Tensorflow`. In `Keras`, what is the corresponding layer for this? Thanks a lot.

**Comment by ahundt** [comment]
Specific Keras Classifiers that build FCNs:
- https://github.com/titu1994/Fully-Connected-DenseNets-Semantic-Segmentation
- https://github.com/titu1994/Snapshot-Ensembles
- https://github.com/pradyu1993/segnet 
- https://github.com/heuritech/convnets-keras includes heatmap, useful for semantic
- https://github.com/jocicmarko/ultrasound-nerve-segmentation

**Comment by wenouyang** [comment]
Hi ahundt, thanks for the reply. 

I will temporarily keep this thread open in case some other colleagues may want to add more information. Thanks.

**Comment by mzaradzki** [comment]
Hi,

I wrote this notebook that builds FCN-16s net and transfers the weight file from the MatConvNet site 👍 

https://github.com/mzaradzki/neuralnets/tree/master/vgg_segmentation_keras

A demo segmentation performed at the end of the notebook

**Comment by mzaradzki** [comment]
fyi I also finished the FCN-8s version today : 
https://github.com/mzaradzki/neuralnets/blob/master/vgg_segmentation_keras/fcn8s_tvg_for_rnncrf.ipynb

I adapted the weights trained for the FCN-RNN-CRF model, as you can see at the end of the notebook it gives great result even without the RNN-CRF layers

**Comment by ahundt** [comment]
@mzaradzki looks cool! Would you be interested in adapting that slightly and submitting a pull request to keras-contrib? https://github.com/farizrahman4u/keras-contrib

**Comment by mzaradzki** [comment]
hi @ahundt, I was not familiar with keras-contrib but I can look into it.
What part of the code do you think should be adapted ? I was thinking of maybe giving it an optional dimension instead of the current 512x512.

**Comment by ahundt** [comment]
@mzaradzki it is the new staging area for keras where if they're deemed sufficiently high quality the changes will be merged into keras. By adaptation I mean the code would need to fit the Keras style, example, and unit test rules and file layout.

**Comment by mzaradzki** [comment]
hi all,
for your information I have updated my code and demo to handle flexible image dimensions:
https://github.com/mzaradzki/neuralnets/tree/master/vgg_segmentation_keras

hope it helps
