### ISSUE TITLE
bAbI example broken on GPU?

### ISSUE THREAD

**Issue by ssamot** [fchollet/keras#537]
While the bAbI example works fine when using the CPU, I get the following error when changing to a GPU run 

ValueError: dimension mismatch in args to gemm (32,100)x(200,22)->(32,22)
Apply node that caused the error: GpuDot22(GpuJoin.0, <CudaNdarrayType(float32, matrix)>)
Inputs types: [CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(32, 100), (200, 22)]
Inputs strides: [(100, 1), (22, 1)]
Inputs values: ['not shown', 'not shown']

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

cmd line: THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python babi_rnn.py

**Comment by w0nk0** [comment]
This line

```ValueError: dimension mismatch in args to gemm (32,100)x(200,22)->(32,22)```

says that you're having a part in your net where the output of the first layer is a (32,100) matrix, but the next layer expects a (32,200) to be able to operate. That would be very odd if it would depend on GPU/CPU. Are you 100% sure?

**Comment by ssamot** [comment]
Well - I am not changing anything apart from the CPU vs GPU command line. Are you able to run this using a GPU?

**Comment by fchollet** [comment]
> That would be very odd if it would depend on GPU/CPU. 

I'm pretty sure I know what this is. This is a Theano bug that was fixed a few months ago, if you just update Theano to its latest version (from the Github repo) it will work fine.

**Comment by ssamot** [comment]
Yes - it's a theano bug - if you install from github it works fine
