### ISSUE TITLE
Batch dot on tensorflow gives incorrect shape when output is rank 1

### ISSUE THREAD

**Issue by nelson-liu** [fchollet/keras#5376]
Here's some code to reproduce the issue. If you run it on the tensorflow backend vs the Theano backend, you can see that the tensorflow backend is incorrect and the Theano backend gives the right result

```
import keras.backend as K
K.eval(K.batch_dot(K.ones(shape=(5, 10)), K.ones(shape=(5, 10)), axes=(1,1))).shape
```

### Expected result:
(5,1)

### Actual Result on TF (incorrect):
(5,5)

### Actual Result on Theano (correct):
(5,1)

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by patyork** [comment]
This was updated several weeks ago. Please update Keras.

![image](https://cloud.githubusercontent.com/assets/1304633/22867251/8e1ed470-f139-11e6-897f-d43f999ea5e4.png)
