### ISSUE TITLE
Siamese network with non Sequential model

### ISSUE THREAD

**Issue by slegall56** [fchollet/keras#5387]
Hi, 

I started to implement a siamese network. 

I followed the tuto https://github.com/fchollet/keras/blob/master/examples/mnist_siamese_graph.py which is well written and do pretty much what I want to do. The only difference is that my model is not sequential. 
So in create_base_network(), I wanted to replace Sequential() by Model() but Model() needs a input which I  give as the model need to be shared among inputs. 

Any idea ?

**Comment by unrealwill** [comment]
Hello,

Here is the doc about functional API, which is the more advanced and more powerful way of creating networks.
https://keras.io/getting-started/functional-api-guide/

**Comment by slegall56** [comment]
Ok thanks I found it in the api guide
