### ISSUE TITLE
What's max_feature mean? 

### ISSUE THREAD

**Issue by yangqinj** [fchollet/keras#5394]
I want to ask a really basic problem. In the code `model.add(Embedding(max_features, 128, input_length=maxlen))`,    I know 128 represents the dimension of each word embedding, input_length means each document has maxlen words (or the first layer has maxlen units), but  what's the max_features mean? there are max_features hidden units in LSTM?  Thanks.

**Comment by unrealwill** [comment]
Hello,
This represent the maximum number of words in your vocabulary. (i.e, the number of "word vectors" you use).
That's the number of rows of the embedding matrix.
https://github.com/fchollet/keras/blob/master/keras/layers/embeddings.py#L95

**Comment by yangqinj** [comment]
@unrealwill , Thanks for your reply! I found out the answer in issue #3110 , besides, from your answer, I finally know that the output of Embedding layer is a embedding matrix.  Thanks again!
