### ISSUE TITLE
Graph Model executes ops on CPU when asked to execute on GPU

### ISSUE THREAD

**Issue by kvrd18** [fchollet/keras#5395]
Hi,

I've been following this [Keras tutorial](https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html) for training a model on a Multi-GPU setting. This works fine and the ops are executed on the GPU as long as the models are defined using a **sequential** container. But when I define the same model using **graphical** operations as shown here in this [Gist](https://gist.github.com/kvrd18/d14f9a28c8d73a31300540b1b5d8e8c8), _the ops are being executed on the CPU._

To run the Gist and reproduce the bug, download the script and execute `python kerasSetGPU.py` on the terminal.

When I ran some benchmarks for a fully convolutional network with an input batch size of `4x512x512x1` with around 12 convolutional layers, I found that the sequential model took around **0.7s** per batch on a TITANx card and the graphical model took around **2.2s** per batch.

What's going wrong here? Why are the ops defined by the graphical model being executed on the CPU even if I call it under `with tf.device('/gpu:0'):`?

**Comment by unrealwill** [comment]
I'm don't know tensorflow a lot. It seems that in the sequential model. The sequential model is constructed with the context with tf.device('/gpu:0'):  of line 89 because the x of line 12 is not used (from keras point of view the model is constructed independently of the tensorflow context.

In the graph model function you redefine a local cpu context with tf.device("/cpu:0"), so it's normal that the operation are not executed on GPU.

Be notified that there is probably some subtle issues with tensorflow context https://github.com/fchollet/keras/issues/5352 , but this not what is hitting you now.

**Comment by kvrd18** [comment]
Nope. Doesn't work even if I define `x` within the context of `tf.device('/gpu:0')` and pass it into the graph model as an argument. 

```python
with tf.device('/gpu:0'):
  x = tf.placeholder(tf.float32, shape=[None,512,512,1])
  op = graphModel(x)
```
It still executes the ops on CPU.

**Comment by unrealwill** [comment]
Strange indeed. 
Have you tried to print op.device ?
Maybe you are hitting the https://github.com/fchollet/keras/issues/5352 issue.
I'll let tensorflow experts handle your case.

(Not related but, you are computing one extra layer (last relu activation) in the case of the graph model)

**Comment by nasimrahaman** [comment]
Hi @kvrd18 , 
The bug in your code can be reduced to the following:

```python
import tensorflow as tf

with tf.device('/gpu:0'):
    x = tf.placeholder(tf.float32)
    # The following happens inside the graphModel function
    with tf.device('/cpu:0'):
        y = 2. * x

print(x.device)
print(y.device)
```
which prints:
```
/device:GPU:0
/device:CPU:0
```
This is because of the fact that only the innermost device context manager is respected. To suggest a fix, we'll need to know why you have the `with tf.device('\cpu:0')` statement in there to begin with.

**Comment by kvrd18** [comment]
Multi-GPU training requires your variables to be defined in the CPU. 

```python
with tf.device('/cpu:0'):
    x = tf.placeholder(tf.float32, shape=(None, 784))

    # shared model living on CPU:0
    # it won't actually be run during training; it acts as an op template
    # and as a repository for shared variables
    model = Sequential()
    model.add(Dense(32, activation='relu', input_dim=784))
    model.add(Dense(10, activation='softmax'))

# replica 0
with tf.device('/gpu:0'):
    output_0 = model(x)  # all ops in the replica will live on GPU:0

# replica 1
with tf.device('/gpu:1'):
    output_1 = model(x)  # all ops in the replica will live on GPU:1

# merge outputs on CPU
with tf.device('/cpu:0'):
    preds = 0.5 * (output_0 + output_1)

# we only run the `preds` tensor, so that only the two
# replicas on GPU get run (plus the merge op on CPU)
output_value = sess.run([preds], feed_dict={x: data})
```
This works for sequential model. But doesn't work for graph models.

**Comment by nasimrahaman** [comment]
I see. This should solve your problem:
```python
import tensorflow as tf
from keras.models import Model
from keras.layers import Input, Dense


# Define model
def construct_model():
    with tf.device('/cpu:0'):
        # Input shape is (batch_size, 784)
        a = Input(shape=(784,))
        h = Dense(32)(a)
        b = Dense(10)(h)
        model_ = Model(input=a, output=b)
        return model_

# Make the model
model = construct_model()

# Define input placeholder on the CPU
with tf.device('/cpu:0'):
    x = tf.placeholder(tf.float32, shape=[None, 784])

# Replica 0
with tf.device('/gpu:0'):
    output_0 = model(x)
    # The following is mission critical (see issue #5352):
    model._output_tensor_cache = {}

# Replica 1
with tf.device('/gpu:1'):
    output_1 = model(x)
    model._output_tensor_cache = {}

# Replica 2
# ...
```
