### ISSUE TITLE
Passing variable to Lambda function and loading model JSON

### ISSUE THREAD

**Issue by jessejohns** [fchollet/keras#5396]
I'm not sure if I'm just ignorant of how Lambda functions work, but if I do the following:

`x = Lambda(lambda x: x * 0.1)(x)`

I have no problem saving and loading a model.  However, if I try to pass a variable:

`x = Lambda(lambda x: x * factor)(x)`

I get the following error on the function closure when loading a model:

> TypeError: arg 5 (closure) must be None or tuple.  

When I printed out the closure when the model failed, I get whatever that value passed to the variable was - [0.1], for example.  I can train and run models, no problem, but I just can't load from the JSON.

Relevant JSON of what produces the error - getting a [0.1] where it expects a null:
`{"class_name": "Lambda", "config": {"function": ["c\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0002\u0000\u0000\u0000\u0013\u0000\u0000\u0000s\b\u0000\u0000\u0000|\u0000\u0000\u0088\u0000\u0000\u0014S(\u0001\u0000\u0000\u0000N(\u0000\u0000\u0000\u0000(\u0001\u0000\u0000\u0000t\u0001\u0000\u0000\u0000x(\u0001\u0000\u0000\u0000t\u000e\u0000\u0000\u0000scale_residual(\u0000\u0000\u0000\u0000s-\u0000\u0000\u0000/home/jesse/Source/dl_code/mdl/model_keras.pyt\b\u0000\u0000\u0000<lambda>5\u0004\u0000\u0000s\u0000\u0000\u0000\u0000", null, [0.1]], "name": "lambda_1", "trainable": true, "function_type": "lambda", "arguments": {}, "output_shape": null, "output_shape_type": "raw"}, "inbound_nodes": [[["batchnormalization_18", 0, 0]]], "name": "lambda_1"}`

JSON of working model:
`{"class_name": "Lambda", "config": {"function": ["c\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0002\u0000\u0000\u0000S\u0000\u0000\u0000s\b\u0000\u0000\u0000|\u0000\u0000d\u0001\u0000\u0014S(\u0002\u0000\u0000\u0000Ng\u009a\u0099\u0099\u0099\u0099\u0099\u00b9?(\u0000\u0000\u0000\u0000(\u0001\u0000\u0000\u0000t\u0001\u0000\u0000\u0000x(\u0000\u0000\u0000\u0000(\u0000\u0000\u0000\u0000s-\u0000\u0000\u0000/home/jesse/Source/dl_code/mdl/model_keras.pyt\b\u0000\u0000\u0000<lambda>5\u0004\u0000\u0000s\u0000\u0000\u0000\u0000", null, null], "name": "lambda_1", "trainable": true, "function_type": "lambda", "arguments": {}, "output_shape": null, "output_shape_type": "raw"}, "inbound_nodes": [[["batchnormalization_18", 0, 0]]], "name": "lambda_1"}`

**Comment by allanzelener** [comment]
I address this in PR #5350.

Keras seems to have a freeze on PRs while Keras 2 is being finalized. You can install my branch with `pip install git+https://github.com/allanzelener/keras.git@func_defaults_to_tuple`.

**Comment by jessejohns** [comment]
I had tried your fix, previously, but with no success.  When I converted the closure argument to a list:

`if isinstance(closure,list):
        closure = tuple(closure)
`

it fails with another error where [0.1] is an unrecognized closure argument.  Sadly, I didn't save this output.

**Comment by mobeets** [comment]
I'm getting the same error, ```TypeError: arg 5 (closure) must be None or tuple```. My model also has a merge with a Lambda.

If I try saving the model separately as yaml, this still doesn't work. In this case I get ```TypeError: arg 5 (closure) expected cell, found int```

**Comment by mobeets** [comment]
It's probably worth noting that I get the same exact bug if I try to save the model in the vae example [here](https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py).

This problem definitely has to do with Lambdas, because if you change line 40 to say "z_mean" instead of "z", this problem goes away.

**Comment by allanzelener** [comment]
Yeah, it looks like Keras doesn't properly handle serializing functions with closures. It dumps the contents of the closure but doesn't simulate having a closure when loading the dumped contents. Creating closure cells isn't straightforward but there's a way suggested in [this StackOverflow post](http://stackoverflow.com/questions/37665862/how-to-create-new-closure-cell-objects).

Here's a workaround: Pass in every variable in the closure as an argument. When creating the Lambda layer supply the additional arguments with Lambda(f, arguments=kwargs). 

Another workaround is to never serialize your model, just do `model.save_weights` and whenever you need to instantiate the model run the code used to construct the model and then use `model.load_weights`.

**Comment by bahramlavi** [comment]
Hello all,

Since I added a Lambda layer in my code, I have a problem to load my saved keras model by calling load_model function. Here is the code of the Lambda:

distance = Lambda(cosine_distance,output_shape=cosine_distance_output_shape)([proc_a, proc_b])

Is there any thought to fix?

**Comment by dgorissen** [comment]
Just ran into this, FYI, workaround from @allanzelener (passing in every variable) worked for me

**Comment by Miail** [comment]
I seem to have a similar issue, but aren't quite sure how to implement the suggested workaround. 

```
#
#   Python scritpt -  Keras RCNN model.
#
import keras
from keras.models import Model
from keras.layers import Input, Dense, Dropout, Flatten, Activation
from keras.layers import merge, Conv2D, MaxPooling2D, Input
from keras.layers.normalization import BatchNormalization
from keras.layers.core import Lambda
import numpy as np
from keras.layers import add
from keras import backend as K


#   RCL:
#   BatchNorm(Relu(conv(L-1) + conv(L)))
#

def make_RCNN(input,number_of_rcl,num_of_filter, filtersize,alpha,pool):
    feed_forward = Conv2D(filters=num_of_filter, kernel_size=1, name='init')(input)
    
    for x in xrange(number_of_rcl):
        output = RCL(feed_forward,num_of_filter,filtersize,alpha,pool)
        feed_forward = output
    
    return feed_forward

def RCL(feed_forward_input,num_of_filter, filtersize, alpha,pool):
    conv = Conv2D(filters=num_of_filter, kernel_size=filtersize, padding='same')
    recurrent_input = conv(feed_forward_input)
    merged = add([feed_forward_input,recurrent_input])
    conv_relu = Lambda(lambda x : K.relu(x,alpha=alpha))(merged)
    conv_relu_batchnorm = BatchNormalization()(conv_relu)
    if pool:
        conv_relu_batchnorm_pool = MaxPooling2D()(conv_relu_batchnorm)
        return conv_relu_batchnorm_pool
    else:
        
        return conv_relu_batchnorm

input = Input(shape=(30,30,3))
output = make_RCNN(input,number_of_rcl=3,num_of_filter=3,filtersize=3,alpha=0.2, pool=True)

model = Model(input = input, output = output)
model.compile(optimizer='rmsprop', loss='binary_crossentropy')
model.summary()
```

**Comment by donniek** [comment]
Dear all,
  This issue can fix. The closure in FunctionType need  create a cell.
  Thanks.
