### ISSUE TITLE
How to figure out if Keras is loading the weights "correctly": model.load_weights(filename, by_name=True)

### ISSUE THREAD

**Issue by dc-ai** [fchollet/keras#5397]
I know that if we use the by_name=True option in model.load_weights, it load the weights for the layers with matching name as the saved model. Obviously, my current architecture and saved architecture is not quite the same but share similar layers.

The issue I am running into, is that I can't figure out which layers have their weights reloaded, and I also can't figure out an easy manner to "check" that the loaded weights are correct. This is important because if I accidentally made a typo in my new architecture, an internal check that tells me which layers have reloaded weights, would be a very helpful sanity check.

I know how to print out all of the weights:
```
for layer in model.layers:
    weights = layer.get_weights()

```
But that prints out everything. I also tried summing the entire list of weights, but that doesn't always work (depends on the layer type).

**Comment by cirpue49** [comment]
I have the exact same question here.

**Comment by Chandrak1907** [comment]
Does this issue  pertains only to   by_name=True? 
I found that even for model.load_weights(filename) does not give an error, if new model is different from saved model. gist file of my working is [here.](https://gist.github.com/Chandrak1907/2e1ec3c2c07d734802d28a22f2c16b7a)

**Comment by fchollet** [comment]
In general I would recommend against use `by_name`, it is error prone (same
as TF checkpoints, which are name-based). Load your load model, then
transfer its weights to the new model layer by layer using
`get_weights`/`set_weights`

> I found that even for model.load_weights(filename) does not give an
error, if new model is different from saved model.

Weights loading skips layers that have no weights, so many different models
can be compatible with the same set of weights. If any weight could not be
loaded, or if the target model has weights that no match in the weights
set, an error is always raised.

**Comment by farahanams** [comment]
how to get_weights from previous built model? 
`autoencoder = Model.get_weights('autoencoder_model.h5')`

it gives an error;
`AttributeError: 'str' object has no attribute 'layers'`.

**Comment by dupsys** [comment]
hi, guys,
I need help. I am trying to validate my testing data using the already training result from my model but I got the following error:
Snippets of my code:
###Fitting model
# save the best weights for predicting the test question pairs
save_best_weights = "weights-pairs1.h5"
# checkpoint = ModelCheckpoint(filepath, monitor='loss', verbose=1, save_best_only=True, mode='min')
callbacks = [ModelCheckpoint(save_best_weights, monitor='val_loss', save_best_only=True),
             EarlyStopping(monitor='val_loss', patience=5, verbose=1, mode='auto')]
start = time.time()
model_info=merged_model.fit([x1, x2, x1, x2, x1, x2], y=y, batch_size=64, epochs=3, verbose=True,\
                 validation_split=0.33, shuffle=True, callbacks=callbacks)
end = time.time()
print("Minutes elapsed: %f" % ((start - end) / 60.))

#####evaluting
# load weights into new model
model_info.load_weights(save_best_weights)
predictions =  model.predict([test_q1, test_q2, test_q1, test_q2,test_q1, test_q2], verbose = True)

##################
AttributeError                            Traceback (most recent call last)
<ipython-input-26-718bf6de413f> in <module>()
      1 # load weights into new model
----> 2 model_info.load_weights(save_best_weights)
      3 predictions =  model.predict([test_q1, test_q2, test_q1, test_q2,test_q1, test_q2], verbose = True)

AttributeError: 'History' object has no attribute 'load_weights'

In [ ]:
#####################

**Comment by dupsys** [comment]
Hi Jason,

Please, I need your help. I try to validate my test data using the already training result from the model but I got the following error:

##################
AttributeError Traceback (most recent call last)
in ()
1 # load weights into new model
----> 2 model_info.load_weights(save_best_weights)
3 predictions = model.predict([test_q1, test_q2, test_q1, test_q2,test_q1, test_q2], verbose = True)

AttributeError: 'History' object has no attribute 'load_weights'

In [ ]:
#####################

Below is the snippets of my code:

###Fitting model

save the best weights for predicting the test question pairs

save_best_weights = "weights-pairs1.h5"

checkpoint = ModelCheckpoint(filepath, monitor='loss', verbose=1, save_best_only=True, mode='min')

callbacks = [ModelCheckpoint(save_best_weights, monitor='val_loss', save_best_only=True),
EarlyStopping(monitor='val_loss', patience=5, verbose=1, mode='auto')]
start = time.time()
model_info=merged_model.fit([x1, x2, x1, x2, x1, x2], y=y, batch_size=64, epochs=3, verbose=True,
validation_split=0.33, shuffle=True, callbacks=callbacks)
end = time.time()
print("Minutes elapsed: %f" % ((start - end) / 60.))

#####evaluting

#load weights into a new model

model_info.load_weights(save_best_weights)
predictions = model.predict([test_q1, test_q2, test_q1, test_q2,test_q1, test_q2], verbose = True)

Regards

**Comment by tjdurant** [comment]
can someone give an example of fchollet's answer here? I have same question as OP and I just want to make sure I am understanding the answer correctly.

**Comment by ljames1** [comment]
@tjdurant I believe fchollet is reccomending somthing like this:
```
new_layers = ['flatten_1 ', 'fc6', 'dropout_1', 'fc7', 'dropout_2', 'fc8']
for i in range(len(model.layers)):
  if model.layers[i].name not in new_layers :
  model.layers[i].set_weights(model_pretrained.layers[i].get_weights())
```

The problem that I have with this is that tensorboard show remnants of the original model, in a weird jumbled mess. When displaying the model with `model.summary()`, the model always looks as intended. Unfortunately, this is an ongoing issue #6229 #2371

**Comment by sagnibak** [comment]
@ljames1 @fchollet  If we have a weights file instead of a model file, how can we load the weights layer-by-layer as shown by ljames1 and suggested by fchollet?

**Comment by kangskii** [comment]
Hello,

Is there a formal method to solve the issue from @dc-ai ?

**Comment by askkvn** [comment]
> @tjdurant I believe fchollet is reccomending somthing like this:
> 
> ```
> new_layers = ['flatten_1 ', 'fc6', 'dropout_1', 'fc7', 'dropout_2', 'fc8']
> for i in range(len(model.layers)):
>   if model.layers[i].name not in new_layers:
>   model.layers[i].set_weights(model_pretrained.layers[i].get_weights())
> ```
> 
> The problem that I have with this is that tensorboard shows remnants of the original model in a weird jumbled mess. When displaying the model with `model.summary()`, the model always looks as intended. Unfortunately, this is an ongoing issue #6229 #2371

It worked for me, thanks @fchollet @ljames1

**Comment by cuevas1208** [comment]
another way to do it:

        # store weights before loading pre-trained weights
        preloaded_layers = self.model.layers.copy()
        preloaded_weights = []
        for pre in preloaded_layers:
            preloaded_weights.append(pre.get_weights())

        # load pre-trained weights
        self.model.load_weights(filepath, by_name=True)
        
        # compare previews weights vs loaded weights
        for layer, pre in zip(self.model.layers, preloaded_weights):
            weights = layer.get_weights()

            if weights:
                if np.array_equal(weights, pre):
                    print('not loaded', layer.name)
                else:
                    print('loaded', layer.name)

**Comment by Danmou** [comment]
A correction to @cuevas1208's solution: `Layer.get_weights()` returns a list of weight matrices, but `np.array_equal` only works for individual arrays (on lists of arrays it always returns `False`). This should work in general:
```python
initial_weights = [layer.get_weights() for layer in model.layers]
model.load_weights(checkpoint, by_name=True)
for layer, initial in zip(model.layers, initial_weights):
    weights = layer.get_weights()
    if weights and all(tf.nest.flatten(tf.nest.map_structure(np.array_equal, weights, initial))):
        print(f'Checkpoint contained no weights for layer {layer.name}!')
```

**Comment by Helaly96** [comment]
> A correction to @cuevas1208's solution: `Layer.get_weights()` returns a list of weight matrices, but `np.array_equal` only works for individual arrays (on lists of arrays it always returns `False`). This should work in general:
> 
> ```python
> initial_weights = [layer.get_weights() for layer in model.layers]
> model.load_weights(checkpoint, by_name=True)
> for layer, initial in zip(model.layers, initial_weights):
>     weights = layer.get_weights()
>     if weights and all(tf.nest.map_structure(np.array_equal, weights, initial)):
>         print(f'Checkpoint contained no weights for layer {layer.name}!')
> ```

shouldn't the print say that weights are matched for layer.name?
since the condition is only True if weights exist and weights match?
