### ISSUE TITLE
Set negative bias in Keras?

### ISSUE THREAD

**Issue by duguyue100** [fchollet/keras#5399]
I'm implementing Convolutional Highway Networks in Keras. The paper uses -1 or other negative values to initialise transform gate bias. In Keras's Highway Networks implementation, the transform gate bias is set to 1.

the `add_weights` function calls functions in the `initialization` module and no other ways around it.
Is it possible to initialise bias with customised function?

**Comment by patyork** [comment]
You could initialize the weights, then 
````python
highwayWeights = model.layers[0].get_weights()
highwayWeights[3] *= -1.0
model.layers[0].set_weights(highwayWeights)

model.layers[0].get_weights()[3]
```
to multiply the bias weights by -1 (they will actually be -1).

Or you can generate your own initial weights however you'd like and pass them into the `weights` parameter. As you've said, the carry bias is currently `ones` and bias itself is `zero`.

**Comment by unrealwill** [comment]
Hello, 
Try passing a callable to add_weights : 
https://keras.io/initializations/

**Comment by duguyue100** [comment]
Aha! @unrealwill, this is exactly what I'm looking for, thanks!
