### ISSUE TITLE
cifar10.py -  imports cPickle error

### ISSUE THREAD

**Issue by pranv** [fchollet/keras#54]
Line 6:

```
 import six.moves.cPickle
```

The following code changes fixed the issue for me: 
Code change at Line 6:
```
  from six.moves import cPickle
```
and at Line 20:
```
  d = cPickle.load(f)
```

**Comment by lemuriandezapada** [comment]
import six.moves on line 6 also works

**Comment by fchollet** [comment]
The change you propose do not appear to be changing anything to what the code is actually doing (it's still the same module being imported). I tried it anyway, but the encoding issue still pops up. We'd probably have to re-save the pkl files to fix it, it's a pain...
