### ISSUE TITLE
Can anyone wrap the locally connected layer in pylearn2?

### ISSUE THREAD

**Issue by rex-yue-wu** [fchollet/keras#540]
Hi,

I like keras and want to stay with keras, but keras does not **have locally connected layers**. I've seen pylearn2 has already implemented [locally connected layer](https://github.com/lisa-lab/pylearn2/blob/d43d015d11747bdbd49737ce1163b9af67eac840/pylearn2/packaged_dependencies/theano_linear/unshared_conv/localdot.py), but I am not sure how to correctly wrap it in keras. Conceptually this should not be difficult, but I only started theano for 2 weeks... Can anyone help me?

**Comment by fchollet** [comment]
Does any other library than Pylearn2 have locally connected layers?

If you understand how they work on a mathematical level, implementing them as a series of Theano tensor operations would be quite straightforward.
