### ISSUE TITLE
sequential and general model in keras implementation

### ISSUE THREAD

**Issue by wenouyang** [fchollet/keras#5409]
Hi,

When reading through some blogpost regarding keras implementations, I see some comments about sequential model and general model. For instance, VGG is sequential and Alexnet is not.  I am quite confusing about this comments. And moreover, when should we use sequential, and when should we use general model to implement some deep learning models in Keras?

**Comment by valtron** [comment]
Use sequential when your network is a basic list of layers, where each layer's output only goes to the next layer.

Use the functional API when your network is a [DAG](https://en.wikipedia.org/wiki/Directed_acyclic_graph). E.g. http://rucs.ca/assets/xu-2layer.png, http://i.imgur.com/G3vwhsu.jpg.

BTW, I believe AlexNet is sequential. It only had the "two tower" structure so it could run on 2 GPUs.

**Comment by wenouyang** [comment]
Hi valtron, thanks for the reply. Can I understand this way, the network like FCN, U-Net that includes merge layer, then we have to use functional API. For the network like encoder-decoder, we can use sequential structure.

**Comment by valtron** [comment]
That's right. Also, you can take a look at the [examples](https://github.com/fchollet/keras/tree/master/examples) to get a better sense of the intended usage of each model.

**Comment by wenouyang** [comment]
Many thanks.
