### ISSUE TITLE
How to update project code written with old keras version?

### ISSUE THREAD

**Issue by lex1993** [fchollet/keras#5421]
I want to use the features of the latest version, but the code is written with keras 0.2. How to update the code?
code link:https://github.com/cupslab/neural_network_cracking

**Comment by unrealwill** [comment]
Hello,
That's the multi-billion dollar problem of the software industry.
The generic way is to get all release notes between the two versions, and do the corrections incrementally.
Alternatively you can try to migrate one shot, and correct the bugs that appears.
You probably can file an issue to the relevant project and provide the author incentives to do so.
Alternatively you can have a python venv with the old version and do inter-process communication.
