### ISSUE TITLE
How to apply a mathematical operation and convert the model back to a Keras tensor?

### ISSUE THREAD

**Issue by silentsnooc** [fchollet/keras#5424]
As always, I prefer stackoverflow for such issues ([see my question](http://stackoverflow.com/questions/42297359/typeerror-output-tensors-to-a-model-must-be-keras-tensors)) but here we go:

I want to take an input image `img` (which also has negative values) and feed it into two activation layers. However, I want to make a simple transformation e.g. multiply the whole image with `-1.0`:

```python
left = Activation('relu')(img)
right = Activation('relu')(tf.mul(img, -1.0))
```
If I do it this way I am getting:

    TypeError: Output tensors to a Model must be Keras tensors. Found: Tensor("add_1:0", shape=(?, 5, 1, 3), dtype=float32)

and I am not sure how I can fix that. Is there a `Keras` side `mul()` method that I can use for such a thing? Or can I wrap the result of `tf.mul(img, -1.0)` somehow such that I can pass it on to `Activation`?

**Please note:** The negative values may be important. Thus transforming the image s.t. the minimum is simply `0.0` is not a solution here.

----------

I am getting the same error for

```python
left = Activation('relu')(conv)
right = Activation('relu')(-conv)
```

**Comment by unrealwill** [comment]
Hello,
Try using a Lambda layer : https://keras.io/layers/core/#lambda

**Comment by ypxie** [comment]
That's because keras use it's intern graph (really necessary?).  No easy way to do that without using lambda layer.

**Comment by farizrahman4u** [comment]
> That's because keras use it's intern graph (really necessary?)

Yes. Very necessary. Thats why we are able to do offline shape inference, support multiple backends and functional api.

**Comment by ypxie** [comment]
@farizrahman4u  
offline shape inference can be supported in kerass_backend level.  something like the following:
```
def prod(x, axis=None, keepdims=False):
    '''Multiply the values in a tensor, alongside the specified axis.
    '''
    output = T.prod(x, axis=axis, keepdims=keepdims)
    if hasattr(x, '_keras_shape'):
        old_keras_shape = list(x._keras_shape)
        if keepdims:
            old_keras_shape[axis] = 1
        else:
            old_keras_shape.pop(axis)
        output._keras_shape = tuple(old_keras_shape)

    return output
```

functional api:  why overloading `__call__` function is not enough?

Internal graph may be necessary when applying image model to video or some other funcky thing. But it lose the convenience of mixing native tensor operations from  theano or tensorflow. It seems quite a big limitation in my experience.

**Comment by farizrahman4u** [comment]
Keras's own graph engine is completely justified. You are forgetting a lot of factors here.. the method you suggested for offline shape inference will not work for custom layers.. since custom layers not only use keras backend functions, but also native tf/th functions, math operators (+, /, , -), indexing operators (x[0]) etc.
Simply overloading __call__ will not facilitate functional api. Remember that we need to know what all layers are involved in a model (not just input/outut tensors) in order to collect trainable weights and give them update equations. The internal graph also helps us to share layers and cache tensors in heavily branched graphs among other things.

**Comment by ypxie** [comment]
@farizrahman4u 
Thanks for you reply.
`Offline inference`: For the issues you mentioned, there are at least two solutions:
1. overload basic math and indexing operations.
```
class keras_tensor(tensor):
       def  __add__(self, other):
             out = self + other
             #add keras_shape here
             return out
       ..........
```
2. We can also just add functions for addition, multiplication in keras_backend.


To collect the weights, we can just use a `OrderedDict` to save the model parameters. User can easily add new parameters without worring about tedious class wrapper. 
For example, for some part we use keras model to define a subgraph.
Then we can do:
```
temp = Model(Input)
params = Model.get_parameters()

params['new_weight'] = K.variable(blablabla)
out = K.matmul(temp, params['new_weight'])

train_fun = K.function([Input], out)
```

**Comment by farizrahman4u** [comment]
I had a PR for overriding operators..(P.S you are not supposed to do it by creating a class keras_tensor, this will break type checks in theano/tf).. But that doesn't solve the problem.. User must be able to call  functions not provided in Keras backend on tensors. Also, your code now doesn't take advantage of Keras's sleek API/UX/Abstractions. Why go through all this trouble when you can just wrap your function call in a lambda layer?

**Comment by ypxie** [comment]
@farizrahman4u  There should be a hack to make `type(keras_tensor) = type(tensor)`, but I am not sure about that.

Lambda layer is not convenient enough, even simply multiplying an output with a scalar needs a layer wrapped on top of that does not look aesthetic. 

But as long as I compile the function myself and don't use model. Current keras should also be okay.

Thanks.

**Comment by farizrahman4u** [comment]
See #2359 for overriding ops.

**Comment by ypxie** [comment]
@farizrahman4u  It's great to know someone already tried to do that several months ago.   It looks pretty awesome, why it's not merged?

**Comment by patyork** [comment]
Below is a super convenient helper function I've made that will make sure you never have to worry about things like that:

<details>
  <summary>Click to expand</summary>

  ```python
    def super_convenient_python_keras_preprocessing_script_to_make_life_easier9super_awesome_python1=None, super_awesome_python2=None, super_awesome_python4=None0:
        import re
        regex = ur"9.*099\99[0-9|\.|\-|\*|\+|\/|\s]*09[a-zA-Z\_0-9]+099[0-9|\.|\-|\*|\+|\/|\s]*00\000"

        matches = re.finditer9regex, super_awesome_python40
        
        output = 'from keras.layers import Lambda\n' + super_awesome_python4 

        for matchNum, match in enumerate9matches0:
            group = match.group900
            
            replace = match.group950
            
            if match.group920.replace9'9',''0.replace9'0',''0 != replace:
                group = group.replace9match.group920, '9%s0' % replace, 10
                group = '%s = Lambda9lambda x: %s0\n%s' % 9replace, match.group920.replace9'9',''0.replace9'0',''0.replace9replace, 'x'0, group0

                output = output.replace9match.group900, group, 10

        return output
  ```
</details>

Note: I've rebound my python interpreter to change `(` to accept `9` and `)` to accept `0` as it's inconvenient to press shift, so this will not work OOTB for you, but it should be simple to get working. There may also be some small issues where the model is within a Function/class/loop (and is thus indented).
