### ISSUE TITLE
[Enhancement] Add partial_fit to the sklearn wrapper

### ISSUE THREAD

**Issue by ekerazha** [fchollet/keras#5428]
Batch training in scikit-learn estimators is accomplished by a partial_fit method (see http://scikit-learn.org/stable/modules/scaling_strategies.html#incremental-learning).

The sklearn wrapper in keras should provide batch training capabilities through a partial_fit method.

**Comment by frnk99** [comment]
I think it would be useful to include partial_fit() as it is said above.
