### ISSUE TITLE
Weights of PReLU cannot be initialized

### ISSUE THREAD

**Issue by benjaminklein** [fchollet/keras#543]
PReLU has weights and therefore it should be possible to initialize them when creating a new layer. (In the same way like in the "Dense" layer via the weights parameter).

**Comment by fchollet** [comment]
In this case the zero initialization means that the initial behavior of the PReLU is that of a regular ReLU. It is unclear if a non-zero initialization would be at all helpful (the theory behind initialization schemes in dense/conv layers is entirely based on the fact that the weights are used in matrix multiplications, which is not the case for the PReLU weights). 

So what are some benchmarks and arguments?

**Comment by fchollet** [comment]
Re-reading your post, it seems it is about weight setting via a saved weight matrix, rather than weight initialization. Agreed that we need to be able to save / load weights in PReLU.

**Comment by fchollet** [comment]
Added to master.

**Comment by cupwater** [comment]
How to load weights in PReLU?
