### ISSUE TITLE
failed to switch the backend even after changing keras.json

### ISSUE THREAD

**Issue by wenouyang** [fchollet/keras#5434]
Hi, I changed the` keras.json `to enforce it use `Theano` as backend, shown as following

```
bash-4.1$ cat ~/.keras/keras.json
{"floatx": "float32", "epsilon": 1e-07, "backend": "theano","image_dim_ordering": "th"}
```

However, when running the program, it still show that Tensorflow is backend. How to solve this issue? Thanks.

![capture](https://cloud.githubusercontent.com/assets/5430158/23095546/407f6026-f5d1-11e6-83e9-f567e7d19c57.JPG)

**Comment by JimBiardCics** [comment]
I'm having the same problem.

**Comment by nayriz** [comment]
Same issue. Has this been solved elsewhere?

**Comment by JimBiardCics** [comment]
I installed Keras using conda.

**Comment by JimBiardCics** [comment]
Yes. Thanks!
