### ISSUE TITLE
Different results for same code in two different computers

### ISSUE THREAD

**Issue by enavarrocomes** [fchollet/keras#5435]
Hello,
As title says, I ran exactly the same file in two different computers, both running in the GPU (one over Mac OS X, the other over Ubuntu). 
I have set the same random seed through 'np.random.seed(1234)'.
Both used the same backend (Theano).
Any idea why?

Thank you

**Comment by kirit93** [comment]
In what way are the results different when you run your code on the two machines?

**Comment by patyork** [comment]
Setting the numpy random seed does not guarantee deterministic behavior. It helps, but it is not propagated everywhere, and Theano/TF also have their own random streams independent of numpy.
