### ISSUE TITLE
Can't import sequential

### ISSUE THREAD

**Issue by bangrui** [fchollet/keras#544]
Hi guys,

I just updated my keras package and now I can't import Sequential properly. It will give me the following erros:

  File "/usr/lib/python2.6/site-packages/Keras-0.1.2-py2.6.egg/keras/models.py", line 118
    if model_name not in {'Graph', 'Sequential'}:
                                 ^
SyntaxError: invalid syntax

Could anyone help me?

**Comment by fchollet** [comment]
> py2.6

Keras is supposed to be compatible with Python 2.7-3.4. Compatibility with 2.6 is not checked. You should upgrade your version of Python.

If you cannot do that for some reason, you can fix the syntax incompatibilities for your own use...
