### ISSUE TITLE
Found a tensorflow problem which has a known solution

### ISSUE THREAD

**Issue by AntreasAntoniou** [fchollet/keras#5443]
The concatenate of keras is currently defined as:

```
def concatenate(tensors, axis=-1):
    '''Concantes a list of tensors alongside the specified axis.
    '''
    if axis < 0:
        dims = ndim(tensors[0])
        if dims:
            axis = axis % dims
        else:
            axis = 0

    if py_all([is_sparse(x) for x in tensors]):
        return tf.sparse_concat(axis, tensors)
    else:
        return tf.concat(axis, [to_dense(x) for x in tensors])

```
This will give an error:

`TypeError: Expected int32, got <tensorflow.python.ops.variables.Variable object at 0x7f5e75ef8210> of type 'Variable' instead.
`

The correct concatenate should be:

exchange `return tf.concat(axis, [to_dense(x) for x in tensors])`

with `return tf.concat([to_dense(x) for x in tensors], axis)`

Someone apparently changed the order of the stuff in the API. No idea why. But very dangerous.

**Comment by kentsommer** [comment]
@AntreasAntoniou 

This is not unexpected behavior as Keras-1 targets pre 1.0 TensorFlow which uses: ```tf.concat(axis, [to_dense(x) for x in tensors])```

So, if you want to use Keras with TensorFlow 1 and beyond please use the Keras-2 branch in this repository.
