### ISSUE TITLE
How to write layer to achieve those equations?  Any suggestion or material?

### ISSUE THREAD

**Issue by eustcPL** [fchollet/keras#5449]
h_a = tanh(W_i * v_i + ( W_q* v_q + b_a)) ,   
v_i and v_q are inputs, other parameters need to be trained.

**Comment by kgrm** [comment]
You don't need to, it can be achieved with `Dense`, `merge` and `Activation` layers:

```
v_i = Input(...)
v_q = Input(...)
d_inner = Dense(N, activation="linear")(v_q)
d_outer = Dense(N, activation="linear", bias="false")(v_i)
s = merge([d_inner, d_outer], mode="sum")
h_a = Activation("tanh")(s)
```

**Comment by eustcPL** [comment]
@kgrm  Thank you very much!   
above input v_i is a matrix,  which has a dimension  of  d * m. But v_q is a vector, which has a dimension of d.  I must to rewrite merge to achieve this  '+'. 
In the begining, I want to write a new keras layer to achieve this equation, but I failed. Did you ever write a layer like this, which has two inputs.
