### ISSUE TITLE
Hidden activations retrievable as input tensor, but not as output tensor

### ISSUE THREAD

**Issue by fortuin** [fchollet/keras#5454]
I built a small LSTM model with multiple outputs using the Theano backend and functional API. The dimensions of the inputs are not in the right order for the LSTM, which is why the inputs have to be permuted before being passed on to the LSTM layer. The model construction looks like this:

```python
from keras.models import Model, Sequential
from keras.layers import  Dense, LSTM, Permute, Input
from keras import backend as K

main_input = Input(shape=(3,100))

lstm = Sequential()
lstm.add(Permute(dims=(1,2), input_shape=(3,100)))
lstm.add(LSTM(output_dim=512, consume_less="gpu"))

lstm_out = lstm(main_input)

out1 = Dense(5, activation="softmax")(lstm_out)
out2 = Dense(5, activation="softmax")(lstm_out)

model = Model(input=main_input, output=[out1, out2])

model.compile(loss="categorical_crossentropy", optimizer="sgd")
```

The model compiles without errors and also works in training and prediction. However, when I wanted to assess the hidden activations of the LSTM layer with

```python
get_lstm_activations = K.function([model.input, K.learning_phase()], [model.layers[1].layers[1].output])
```

I get the following error:

```
MissingInputError: ("An input of the graph, used to compute DimShuffle{0,1,2}(permute_input_2), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", permute_input_2)
```

If I try to get the same tensor not as the output of the LSTM layer, but as the input of the next layer, like

```python
get_lstm_activations = K.function([model.input, K.learning_phase()], [model.layers[2].input])
```

I don't get any errors and it indeed seems to work. That seems really counterintuitive to me and I came up with this alternative approach mostly by chance. Can anyone explain why the intermediate output tensor cannot be obtained and whether this is a bug in the functional API or the consequence of an intended behavior?

**Comment by unrealwill** [comment]
Hello, I think the main difference between the two cases is that in the first non working case, you are trying to access a layer from a sub-model which probably break some intended internal model encapsulation. (If you allow an access to an intermediate output then it means that the gradients flowing backward should be able to enter at this intermediate output, which means you can't compose model properly (i.e keeping a sub-model structure), so you must "inline" the whole submodel, but then you lose useful structural information).
