### ISSUE TITLE
Keras-visualizations errors - K.gradients (loss,input_img)[0] gives type error

### ISSUE THREAD

**Issue by raun1** [fchollet/keras#5455]
Hello,

I am following the code here at https://github.com/fchollet/keras/blob/master/examples/conv_filter_visualization.py
for visualizing on my own network and input images. 
However at the step -
I replaced the input_img with my own image instead of the placeholder.
grads = K.gradients(loss, input_img)[0]

I keep getting the error TypeError: Expected Variable, got [[[[ 4.  4.  4. ...,  0.  0.  0.]
   [ 4.  4.  4. ...,  0.  0.  0.]
   [ 4.  4.  4. ...,  0.  0.  0.]
   ...,
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]]] of type <type 'numpy.ndarray'>

Any help is appreciated!

**Comment by kgrm** [comment]
`K.gradients` is a Keras backend function constructor that expects theano/tensorflow tensors as its input, whereas you're calling it with a numpy array. To construct a function callable with numpy arrays from it, you can use something like this:

```
...
from keras.objectives import mse
m = get_your_model()
y_true = K.variable(*your_models_output_shape)
loss = K.mean(mse(y_true, your_model.output))
get_grads = K.function([your_model.input, y_true], K.gradients(loss, your_model.input))

grads = get_grads([np.random.rand(*your_models_input_shape), np.random.rand(*your_models_output_shape)])
```
