### ISSUE TITLE
Location of .keras

### ISSUE THREAD

**Issue by apiszcz** [fchollet/keras#5462]
Can I set the location of .keras to be somewhere other than ~/, say and arbitrary location?
I would like to package my weights in a subfolder of the application not the user directory.
Thank you.

**Comment by kirit93** [comment]
Why do you need to change the location of the .keras folder? If you take a look at the Keras sources (https://github.com/fchollet/keras/blob/25dbe8097fba9a6a429e19d0625d78c3b8731527/keras/backend/__init__.py#L18) you'll see that the base directory is set to your home directory.
I'm not sure if this can be changed.
As for packaging you weights, try doing something like this.
```
filepath="weights.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='loss', verbose=1, save_best_only=True, mode='min')
callbacks_list = [checkpoint]
model.fit(x, y, nb_epoch=10, batch_size=64, callbacks=callbacks_list)
```

**Comment by apiszcz** [comment]
Thanks for checkpoint/model location example.

**Comment by apiszcz** [comment]
this may be another option

_keras_base_dir = os.path.expanduser('~')
if not os.access(_keras_base_dir, os.W_OK):
    _keras_base_dir = '/tmp'

**Comment by tensorfoo** [comment]
Set the environment variable KERAS_HOME.

**Comment by medined** [comment]
> Why do you need to change the location of the .keras folder? 

My /home partition is not large. My /data partition is over 1TB. I try to put everything on the /data partition.
