### ISSUE TITLE
Freezing or Throwing away Filters of a Layer

### ISSUE THREAD

**Issue by KlaymenGC** [fchollet/keras#5470]
Hello,

Is there a way of setting some filters of a layer to zero and freezing them or just throwing away some filters for filter pruning purpose? The most intuitive way of doing it is to build a new model and then load the weights every time the filters are pruned. I was wondering if there is an easier way of doing it in Keras.

**Comment by unrealwill** [comment]
Hello, 
I don't think there is a way to partially set to 0 and freeze a layer. But if you multiply the output of a layer by an appropriate mask, the output will be 0 and the gradients shouldn't propagate hence resulting in frozen partial weights.
So a output=Merge( mode="mul")([output,mask]) should work.

**Comment by KlaymenGC** [comment]
I did it by modifying the model_config dict. Just throwing away the filters.
