### ISSUE TITLE
Splitting the output of a layer over the channels

### ISSUE THREAD

**Issue by atuysuz** [fchollet/keras#5474]
I am trying to implement a single input, multiple-output model using the functional API. I want to split the output of a convolutional layer over the channels and then work these outputs to different loss functions. I tried the following  below; however, it did not work:
```
x = Convolution2D(3, 5, 5, border_mode='same')(x)
x0 = x[:, 0, :, :]  
x1 = x[:, 1, :, :]
x2 = x[:, 2, :, :]
```

 I saw that the possibility of a Split layer has been discussed but I don't think it exists yet. Any suggestions on how I can achieve this splitting?

**Comment by patyork** [comment]
Lambda layer.

**Comment by abhaikollara** [comment]
```
x0 = Lambda(lambda x : x[:,:,:,0])(x)
x1 = Lambda(lambda x : x[:,:,:,1])(x)
x2 = Lambda(lambda x : x[:,:,:,2])(x)
```

**Comment by atuysuz** [comment]
Thank you @patyork  and @abhaikollara for your suggestions.
I tried using the Lambda layer exactly as follows:
```
de_out1 = Lambda(lambda x: x[:, 0, :, :])(de_out) 
```
However ```de_out1``` has the same ```keras_shape``` as ```de_out``` has. Any ideas  why this is not behaving as expected?

**Comment by abhaikollara** [comment]
@atuysuz Could you mention the backend and image dimension ordering ?
I'm using Tensorflow backend and it seems to be working fine
~~~~
x = Input((28,28,1))
x = Convolution2D(3,5,5,border_mode='same')(x)
x0 = Lambda(lambda x : x[:,0,:,:])(x)
x1 = Lambda(lambda x : x[:,1,:,:])(x)
x2 = Lambda(lambda x : x[:,2,:,:])(x)
print x.shape
print x0.shape
~~~~

~~~~
(?, 28, 28, 3)
(?, 28, 3)
~~~~

**Comment by abhaikollara** [comment]
@atuysuz Could you mention the input to the convolutional layer ?

It seems to work fine for me
~~~~
x = Input((1,28,28))
x = Convolution2D(3,5,5,border_mode='same', dim_ordering='th')(x)
x0 = Lambda(lambda x : x[:,0,:,:])(x)
x1 = Lambda(lambda x : x[:,1,:,:])(x)
x2 = Lambda(lambda x : x[:,2,:,:])(x)

print x.shape
print x0.shape
~~~~

~~~~
(?, 3, 28, 28)
(?, 28, 28)
~~~~

**Comment by patyork** [comment]
You should provide the `output_shape` parameter to the Lambda layers when you are changing the shape within the function.

**Comment by abhaikollara** [comment]
Yes,  Theano does not automatically infer shapes of lambda layer outputs. I think updating Keras should produce warnings about this.

**Comment by atuysuz** [comment]
Thank you again folks!
Indeed, this was the issue in using the Lambda layer. I am using Theano backend and once I provided the output shape, all is fine.

**Comment by davidschlegel** [comment]
Is there a way to do this with a layer object?

**Comment by gitmenonsandu** [comment]
If the input shape is ```shape=(?, 64, 64, 64)```
How to split into say 30% and 70% without changing the last three dimension
eg. for(100,64,64,64) to (30,64,64,64) and (70,64,64,64)

**Comment by bairavi26** [comment]
@sandeepnmenon  - Were you able to figure out a solution to your question?

**Comment by sandeepnmenon** [comment]
@bairavi26  Please see the code below

```
def get_gated_connections(gatePercentageFactor,inputLayer):
    fractionG = Lambda(lambda x, factor : factor * x, arguments = {'factor': gatePercentageFactor})(inputLayer)
    complement = Lambda(lambda x: x[0] - x[1])([inputLayer,fractionG])
    
    return fractionG,complement
```
where gatePercentage is the split factor (ex. 0.7) and inputLayer is the layer whose output who you want to split.

Usage
```
 x1 = Conv2D(64, conv_filter, activation='relu', padding='same')(input_img)
 fg1,c1 = get_gated_connections(0.1,x1)
```

Hope it helps

**Comment by vladGriguta** [comment]
Could anyone help me correct this syntax, please?

```python
model = tensorflow.keras.applications.InceptionResNetV2(include_top=False, weights='imagenet', input_tensor=input_tensor, pooling=None)
branch1 = tensorflow.keras.layers.Lambda(lambda x: x[:, :, :, :700])(model)
# same for tensorflow.keras.layers.Lambda(lambda x: x[:, :, :, :700])(model.layers[-1])
```

```
(...)
    return self.function(inputs, **arguments)
  File "<input>", line 1, in <lambda>
TypeError: 'Model' object is not subscriptable
```

**Comment by magnusbarata** [comment]
@vladGriguta Keras Functional API receives a tensor for the function call. So, you must connect with the `model`'s output.
```
branch1 = tensorflow.keras.layers.Lambda(lambda x: x[:, :, :, :700])(model.output)
```

> Could anyone help me correct this syntax, please?
> 
> ```python
> model = tensorflow.keras.applications.InceptionResNetV2(include_top=False, weights='imagenet', input_tensor=input_tensor, pooling=None)
> branch1 = tensorflow.keras.layers.Lambda(lambda x: x[:, :, :, :700])(model)
> # same for tensorflow.keras.layers.Lambda(lambda x: x[:, :, :, :700])(model.layers[-1])
> ```
> 
> ```
> (...)
>     return self.function(inputs, **arguments)
>   File "<input>", line 1, in <lambda>
> TypeError: 'Model' object is not subscriptable
> ```
