### ISSUE TITLE
Save activation output to disk 

### ISSUE THREAD

**Issue by dr-costas** [fchollet/keras#5476]
Hi, 

I want to save the activation output from inside a step function. How can this be done in keras?

**Comment by kgrm** [comment]
Refer to he FAQ for retrieving the activation of an intermediate layer:

https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer

Once you have the activation values (in the form of a numpy array), you can save it, e.g., with `np.save`.
