### ISSUE TITLE
Problems with LocallyConnected1D Layer and Theano

### ISSUE THREAD

**Issue by mwiebusch78** [fchollet/keras#5479]
I am having trouble fitting a network with a locally connected hidden layer using the Theano backend. The code below runs fine for `output_dim = 7*24` but crashes on the call to `model.fit` for `output_dim = 2*7*24`. The error message is quite long and messy but contains this:

```
Compilation failed (return status=1): /Users/martinwiebusch/.theano/compiledir_Darwin-16.4.0-x86_64-i386-64bit-i386-3.5.2-64/tmp_eqbf347/mod.cpp:6135:6: fatal error: bracket nesting level exceeded maximum of 256.
```

Here is the code:
```python
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Reshape, LocallyConnected1D

np.random.seed(1234)

nsamples = 1024
input_dim = 7 + 24 + 3
output_dim = 2*7*24   # change this to 7*24 and it works
stride = 5
nhidden = 5*output_dim

x = np.random.normal(size=(nsamples, input_dim)).astype(np.float32)
y = np.random.normal(size=(nsamples, output_dim)).astype(np.float32)

model = Sequential()
model.add(Dense(nhidden, input_dim=input_dim, activation='tanh'))
model.add(Reshape((nhidden, 1)))
model.add(LocallyConnected1D(1, stride, subsample_length=stride))
model.add(Reshape((output_dim,)))

model.summary()
print('Compiling model.')
model.compile(loss='mean_squared_error', optimizer='adam')

print('Fitting model.')
model.fit(x, y, nb_epoch=10, batch_size=32, verbose=1)
```

My `keras.json` looks like this:
```
{
    "image_dim_ordering": "tf",
    "floatx": "float32",
    "epsilon": 1e-07,
    "backend": "theano"
}
```

**Comment by unrealwill** [comment]
Hello,
Your code sample runs fine with theano for me but I have "image_dim_ordering": "th".

**Comment by mwiebusch78** [comment]
I get the same problem with "image_dim_ordering": "th". I should probably have mentioned that I'm running on a mac. (Mac OS Sierra, 10.12.3)

**Comment by unrealwill** [comment]
A quick search reveals that's its Mac Os related. Some gcc compilation issue.
Some people seemed to have some success ( https://github.com/pymc-devs/pymc3/issues/624 ) by adding the following in ~/.theanorc
```
[gcc]
cxxflags = -fbracket-depth=1024
```

**Comment by mwiebusch78** [comment]
Thanks. I can confirm that it is a mac-specific problem. (Just got the script to run on a linux box.) After adding the `-fbracket-depth=1024` flag to the theano config I now get a *different* error:

```
/Users/martinwiebusch/.theano/compiledir_Darwin-16.4.0-x86_64-i386-64bit-i386-3.5.2-64/tmplsfgc_4d/mod.cpp:37107:54: error: arithmetic on a pointer to void.
```

It seems that gcc accepts this case with a warning but other compilers throw an error.

**Comment by mwiebusch78** [comment]
I finally got it to work! The second compilation error (arithmetic on a pointer to void) seems to be an unrelated mac-specific but in the current *development* version of theano. Using the current PyPI versions of keras and theano (Keras==1.2.2, Theano==0.8.2) and the ~/.theanorc file you suggested the script now runs for `output_dim = 2*7*24`.

**Comment by mwiebusch78** [comment]
Looks like my excitement was premature. If I try `output_dim = 4*7*24` I get a slew of `RecursionError`s. It seems that the graph that theano needs to optimise get increasingly complex as the number of nodes in the output and hidden layer is increased. Is this to be expected? After all we're 'just' talking about a three-layer neural network with 34 input, 3360 hidden and 672 output nodes.

**Comment by unrealwill** [comment]
I'm not sure exactly what you are trying to achieve. But you are probably misusing the layer.
But to increase the number of output, usually we would increase the number of filters 
 `LocallyConnected1D( **nbfilter**, stride, subsample_length=stride))`
I am not familiar with the LocallyConnected1D layer but here you are creating 3360 "timesteps", and for each timestep you do a matrix multiplication. The graph is quite big.

**Comment by mwiebusch78** [comment]
I'm trying to build a network for univariate time series forecasting. The inputs are past values of the time series. I can do predictions at a fixed horizon (predict the signal at exactly n hours in the future) with a dense hidden layer with 5 nodes and an output layer with 1 node. Now I would like to predict the next 3360 values of the time series simultaneously. Rather than training 3360 networks I would like to build a network with 3360 output nodes where each output node is only connected to 5 nodes in the hidden layer. (That is, each output node is connected to a *different* set of nodes in the hidden layer) I'm thinking of a configuration like this:
```
   o
    \
o    o
    /
   o

o

   o
    \
o    o
    /
   o

```
(where the input layer is fully connected to the hidden layer and I've only drawn 2 output nodes connected to 2 nodes in the hidden layer each.) Is `LocallyConnected1D` the right layer for this?

**Comment by mwiebusch78** [comment]
I've now got it to work by implementing my own layer. If there is interest I'd be happy to share the code (and explain what the layer does).

**Comment by unrealwill** [comment]
Cool :)
You should probably put it on your github, or make a blog post about it, it may interest other people who can be interested both in the problem you solved and in the way you use to solved it. I'm not sure it will find its way into Keras, as most layers there have proven themselves useful in some research Papers.
