### ISSUE TITLE
tf.diag support

### ISSUE THREAD

**Issue by Stalence** [fchollet/keras#5482]
It would be useful if we could get a square diagonal matrix from a vector of values similar to the diag command from tensorflow. Currently to do this I utilize broadcasting; I create an identity matrix and multiply(*) with the vector. However that depends on the backend function "eye" which is implemented via numpy and I run into other problems when I do that. The main one is that I can't pass the batch size as an argument to "eye" because it is variable("None").
(Disclaimer: I've only used the Tensorflow backend so I'm not sure how the Theano version would play out)

**Comment by kgrm** [comment]
Theano has the same function, so this could easily be implemented for both backends. `T.diag(K.variable(np.arange(5))).eval()` produces the expected result.

**Comment by shivam05011996** [comment]
How to support for tensorflow backend, because I am getting this error
```
AttributeError: module 'keras.backend' has no attribute 'diag_part'
```

**Comment by eIGato** [comment]
```python
def backendwise_diag(*args, **kwargs):
    backend = keras.backend.backend()
    if backend == 'tensorflow':
        import tensorflow
        return tensorflow.diag_part(*args, **kwargs)
    elif ...
```

**Comment by dgrahn** [comment]
@eIGato I literally just searched for this. Great timing on your result.

This should definitely be included in Keras.
