### ISSUE TITLE
Inconsistency with image preprocessing step for pretrained VGG-16

### ISSUE THREAD

**Issue by florianshkurti** [fchollet/keras#5492]
Hi all,

I'm a bit confused about the image preprocessing that is required in order to use the weights of the pretrained VGG-16 model in Keras. According to https://github.com/fchollet/keras/blob/master/keras/applications/imagenet_utils.py the main image preprocessing operation required is to subtract the mean color, as computed on the training dataset. This is in agreement with the original VGG paper from Simonyan.

But, in the following examples: 
https://gist.github.com/fchollet/7eb39b44eb9e16e59632d25fb3119975  
https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html        
there appears to be some scaling of the image to [0,1] from the original [0,255] range, but no subtraction of the mean color. 

Which one is the correct preprocessing operation for pretrained VGG-16 in Keras?

**Comment by the-moliver** [comment]
I agree it would be helpful to know that appropriate preprocessing for using all of the pre-trained models in the applications. RGB vs BGR, centering and scaling, etc.

**Comment by matteodelv** [comment]
I reopen this issue because there is still confusion about this topic and a bit of clarification would be very helpful. Mostly when using bottleneck feature or when finetuning the pretrained VGG16 net.

**Comment by Osumann** [comment]
Still no answer for  this issue ?? I'm trying to fine tune VGG16 using Keras and I'm curious about the preprocessing part as well.
