### ISSUE TITLE
Predict function running slowly

### ISSUE THREAD

**Issue by dberma15** [fchollet/keras#5500]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I'm also having trouble with a slow model.predict significantly bottle necking my code. I am running Python 3.5 on a Windows 7 laptop, so no GPU and 8GB of RAM, . The model is VGG_16 (https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3) with the last four layers (two dense layers and two drop out layers removed). I am using it as a feature extractor so that I don't have to build a CNN on my own. I resize the images and then use predict on them. 
`features=featureExtractor.predict(X_train)`
I decided to try it on a subset of 3,600 images, a fraction of all of the images I have, and I found that it took just about an hour. That's only 1% of my images. If I use all of them, it'll take four days just to load it all in. Is there anything I can do to speed this up?

I have already tried using
```
get_output = K.function([featureExtractor.layers[0].input],[featureExtractor.layers[32].output])
model_output = get_output([X_test])[0]
```
and that takes even longer. 

I have also tried changing batch_size and that only increases the time as well. 

Does anyone have any suggestions?

**Comment by Dref360** [comment]
Use a smaller network, since you're not using GPU, you cannot efficiently process neural networks.
You could take a look at Tensorflow XLA (https://www.tensorflow.org/versions/master/experimental/) and you could turn a flag to use more cores. (http://blogs.candoerz.com/question/162218/changing-the-number-of-threads-in-tensorflow-on-cifar10.aspx)

Increasing batch_size could also help.
Reducing the input size could also help

**Comment by unrealwill** [comment]
Hello, you can try to extract the VGG features for your training set. Then you save the calculated features, then you can do your training using this precalculated features, and your model will be a lot faster as it won't have to do any convolutions which are really faster on a GPU.

As it is a one-shot pre-calculation you can probably do it quickly in the cloud for a few bucks using GPU.

**Comment by dberma15** [comment]
Hi Dref360, I will look into those sources.

unrealwill, I am currently doing that and that's what's taking so long. Do you have a cloud computing service you recommend? Especially since I have around ~200GB of data?

**Comment by unrealwill** [comment]
@dberma15 It's quite hard to choose without knowing what you are trying to do. The "classic" choice is amazon EC2. They have data transfer fees for data going out but not in. The main problem you will have is going transferring the data-in especially if you don't have a fast upload. They also have storage fees.
Amazon is quite expensive for non-ponctual use, in which case you should probably by your own GPU.
