### ISSUE TITLE
pair distance between two tensors

### ISSUE THREAD

**Issue by pangsaai** [fchollet/keras#5501]
I need to compute the euclidean distance between two data points from two tensors, e.g.
A = [a1, a2]
B= [b1, b2]
the result should be
[[[a1-b1], [a1-b2]]
[[a2-b1], [a2-b2]]
where A and B are with the same dimensionality. Anybody can tell me how to implement it in Keras?

**Comment by unrealwill** [comment]
Hello,

Try doing something like this.

```
rshpA = K.expand_dims( A,dim = 1)
rshpB = K.expand_dims( B,dim = 0)
diff= rshpA-rshpB

```
You may also use K.shape, K.reshape for more complex cases.

**Comment by fabriciorsf** [comment]
```
def euclidean_distance(y_true, y_pred):
    y_true = __l2_normalize__(y_true)
    y_pred = __l2_normalize__(y_pred)
    return K.mean(K.sqrt(2. - (2 * K.sum((y_true * y_pred), axis=-1))))
```
