### ISSUE TITLE
Theano/Tensorflow backend inconsistencies

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#5505]
It appears that some th/tf backend functions are not equivalent.
Particularly the tf implementation of K.switch() through tf.select requires a purely boolean condition, while the th.switch() can also take a tensor. The equivalent of th.switch() is tf.where().

Is that an overlook or is it by design or am I just missing something?

**Comment by abhaikollara** [comment]
The tf implementation of K.switch uses `tf.cond` not `tf.select`

**Comment by lemuriandezapada** [comment]
My bad. tf.cond :)
It still requires a scalar, though. Which is incompatible with the theano implementation. And breaks the whole concept of switch
https://www.tensorflow.org/api_docs/python/tf/cond

**Comment by MaigoAkisame** [comment]
I have the same problem.

It seems that you can build K.switch from tf.where (somehow tf.select isn't available to me...).
It would be good to have a unified K.switch operator.
