### ISSUE TITLE
six.moves

### ISSUE THREAD

**Issue by crazy449** [fchollet/keras#551]
I am using: from keras.models import Sequential
and I get

from six.moves import range
ImportError: cannot import name range?

I have the latest six installed

**Comment by manwinder123** [comment]
I have version 1.8.0 installed and Keras works fine, maybe try reinstalling it (https://pypi.python.org/pypi/six)

**Comment by fchollet** [comment]
You appear to have a version of six that is older than 1.3.0. Just install the latest version.
