### ISSUE TITLE
Calling model.predict inside the generator that feeds model.fit throws ValueError: [...] is not an element of this graph

### ISSUE THREAD

**Issue by lucasdavid** [fchollet/keras#5511]
I found this issue while trying to implement the triplet loss from [FaceNet: A Unified Embedding for Face Recognition and Clustering](https://arxiv.org/abs/1503.03832).

In the paper, input triplets `(a, p, n)` are selected from the batch s.t. they minimize `||f(n)-f(a)||`, where `f(x)` is the network transformation of the sample `x`. Therefore, I need to call `model.predict()` inside the generator that feeds `model.fit()`, which throws the error:
```
ValueError: Tensor Tensor("Relu_1:0", shape=(?, 2048), dtype=float32) is not an element of this graph.
```

Link to gist that reproduces the error (you can also confirm this error goes away when not calling `predict` by commenting lines 59-60 and uncommenting 61-62): [https://gist.github.com/lucasdavid/4cd49f68e5a4002a2611c18c876a1998](https://gist.github.com/lucasdavid/4cd49f68e5a4002a2611c18c876a1998)

**Comment by unrealwill** [comment]
Hello, 
Probably unrelated but I think there is a bug
 line 21 should be :
` K.expand_dims(_x[2]) `

**Comment by lucasdavid** [comment]
That's true, thanks for the catch. Still, the reported problem persists.

**Comment by EderSantana** [comment]
I got that same problem yeah. I just gave up using tensorflow models inside generators :)
also, a solution I'd suggestion for your triplet loss is to create a new cost function and match triplets there using sorting (which I think you can do using [tf.nn.top_k](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard5/tf.nn.top_k.md)). This way you avoid evaluating your model twice.

**Comment by lucasdavid** [comment]
@EderSantana bummer. When I think I had a reasonably pretty solution it turns out it doesn't work. Anyways, I'll try your way out, cheers!

**Comment by perone** [comment]
Also facing this same issue when calling model.predict() inside a generator.

**Comment by manojsukhavasi** [comment]
@lucasdavid I am also facing the same issue. Did you find the fix for this?.

**Comment by collinsimon** [comment]
> use `model.fit_generator(..., workers=0)`

Works here too. CPU used at 50% (instead of 100%) - GPU 50% (like always) - I guess the drop in CPU usage is due to the fact that it feeds slower the model but the bottle neck is most probably the predictions in the generator anyway

**Comment by Barnonewdm** [comment]
@socathie I have tried your skill and successfully get results. Could you explain the reason behind this?

**Comment by dbulhosa** [comment]
@Barnonewdm I believe when one sets `workers=0` both the generator and the model run in the same thread. When we set `workers=1` they run in separate threads, as @manojsukhavasi mentioned. When the model and generator are in the same thread presumably they are also on the same graph by default.
