### ISSUE TITLE
Is there an implement of attention LSTM by keras

### ISSUE THREAD

**Issue by wdl000001** [fchollet/keras#5512]
The paper is here: https://arxiv.org/pdf/1409.0473v7.pdf

**Comment by tboquet** [comment]
https://github.com/farizrahman4u/seq2seq

**Comment by wdl000001** [comment]
This implement is depend on recurrentshop. Is there an implement base on Keras LSTM?

**Comment by tboquet** [comment]
Recurrent shop models and layers are Keras models and layers.

**Comment by abhigarg** [comment]
recurrentshop throwing errors for me when I try to use seq2seq

**Comment by zafarali** [comment]
We recently implemented the Attention Decoder layer from tge paper for a toy translation task here: https://github.com/datalogue/keras-attention 

There is a blog post coming soon!

**Comment by andhus** [comment]
I've laid out a API Design suggestion for supporting recurrent attention in core keras: https://github.com/fchollet/keras/issues/7633
Please give feedback!
