### ISSUE TITLE
GPU not running

### ISSUE THREAD

**Issue by dberma15** [fchollet/keras#5526]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi all, 

I recently acquired a GPU from a friend and want to run my code using the GPU. I installed CUDA and cuDNN, but when I run the code, the GPU is not active at all. I have provided my code to help. 

[eighthCNN_allatonce.txt](https://github.com/fchollet/keras/files/801764/eighthCNN_allatonce.txt)

**Comment by dberma15** [comment]
I installed tensorflow-gpu using pip install tensorflow-gpu

**Comment by israelg99** [comment]
Can you post the output of `nvidia-smi`?

**Comment by dberma15** [comment]
C:\Program Files\NVIDIA Corporation\NVSMI>nvidia-smi
Sun Feb 26 12:37:58 2017
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 378.66                 Driver Version: 378.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 660M   WDDM  | 0000:01:00.0     N/A |                  N/A |
| N/A   55C    P0    N/A /  N/A |     57MiB /  2048MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+

**Comment by israelg99** [comment]
I have no experience with tensorflow and Windows, here's a [guide for tensorflow-gpu on Windows](http://www.heatonresearch.com/2017/01/01/tensorflow-windows-gpu.html), I suggest you make sure you followed it thoroughly.

**Comment by dberma15** [comment]
I now have the GPU working, but it's taking longer than the CPU was.  It originally started out much faster, with the estimated time expected to be 8 hours. However, it's not at 30 hours. This would have taken around 24 hours on the CPU. Did I do something wrong? 
The lines of code it's really dragging on are between 286 and 302 in the file I attached at the top. 


> Using TensorFlow backend.
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:135] successfully opened CUDA library cublas64_80.dll
locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:135] successfully opened CUDA library cudnn64_5.dll lo
cally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:135] successfully opened CUDA library cufft64_80.dll l
ocally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:135] successfully opened CUDA library nvcuda.dll local
ly
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:135] successfully opened CUDA library curand64_80.dll
locally
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') fo
r unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_t
ype: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"')
 for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for
unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_ty
pe: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"')
for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"'
) for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') fo
r unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') fo
r unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"
') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "C
PU"') for unknown op: UpdateFertileSlots
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties:
name: GeForce GTX 660M
major: 3 minor: 0 memoryClockRate (GHz) 0.95
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.93GiB
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\gpu\gpu_device.cc:906] DMA: 0
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\gpu\gpu_device.cc:916] 0:   Y
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (d
evice: 0, name: GeForce GTX 660M, pci bus id: 0000:01:00.0)
N/A% (0 of N/A) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--W
 c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\
common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.05Gi
B. The caller indicates that this is not a failure, but may mean that there coul
d be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 1.02G
iB. The caller indicates that this is not a failure, but may mean that there cou
ld be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.05G
iB. The caller indicates that this is not a failure, but may mean that there cou
ld be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 1.04G
iB. The caller indicates that this is not a failure, but may mean that there cou
ld be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.07G
iB. The caller indicates that this is not a failure, but may mean that there cou
ld be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 1.07G
iB. The caller indicates that this is not a failure, but may mean that there cou
ld be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 551.7
1MiB. The caller indicates that this is not a failure, but may mean that there c
ould be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 2.14G
iB. The caller indicates that this is not a failure, but may mean that there cou
ld be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 1.08G
iB. The caller indicates that this is not a failure, but may mean that there cou
ld be performance gains if more memory is available.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core
\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 586.1
3MiB. The caller indicates that this is not a failure, but may mean that there c
ould be performance gains if more memory is available.
  5% (  0 of 1) |                   | Elapsed Time: 1:13:30 ETA: 1 day, 4:45:03

**Comment by israelg99** [comment]
Your GPU is very low-end so it could be a hint, additionally, it also runs out of memory as you can see in the logs.

**Comment by dberma15** [comment]
It's stuck in a pre-processing step. Would breaking it into smaller chunks improve performance, that way I'm using less memory?
