### ISSUE TITLE
Improve printed messages in fit/evaluate/predict_generator

### ISSUE THREAD

**Issue by datumbox** [fchollet/keras#5531]
This is a proposal for improving the messages printed by fit, evaluate and predict generator methods. If the admins agree it's useful, I'm happy to write it and send a pull-request. Else please feel free to close the issue.

On fit_generator() (training.py, [line 1825](https://github.com/fchollet/keras/blob/keras-2/keras/engine/training.py#L1825)) we sleep if the queue is empty. I propose to periodically inform the user when this happens. I was training a model across different GPUs and the GPU usage was very low. It turned out that the CPUs and the HDDs could not keep up leading to slow training times. The same can be done on evaluate_generator and predict_generator. The question is how often should we inform the user, which verbosity mode should be used etc.

Second, the evaluate_generator and predict_generator methods do not print a progress bar. I think that the progress bar is particularly useful since it allow us to understand how quickly the batches are being processed and whether the speed is decreasing. It would be good to add the ProgbarLogger callback (or something similar) in the two methods. The same can be done in the fit_generator during the validation process at the end of each epoch.

Any thoughts? :)

**Comment by datumbox** [comment]
@fchollet Should I close this?

**Comment by thecheech** [comment]
any log could be useful. would be really nice to send a verbose argument
