### ISSUE TITLE
The 'Classify images' example can't find the 'elephant.jpg' .

### ISSUE THREAD

**Issue by Fansiee** [fchollet/keras#5534]
I run the example code in MacOS and Ubuntu14.04, however, they both go wrong with 
`IOError: [Errno 2] No such file or directory: 'elephant.jpg'`.
I know the reason is there is no such a file, but I don't know why I can't google it in the keras issue.
Only I met the problem?

```
from resnet50 import ResNet50
from keras.preprocessing import image
from imagenet_utils import preprocess_input, decode_predictions

model = ResNet50(weights='imagenet')

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = model.predict(x)
print('Predicted:', decode_predictions(preds))
# print: [[u'n02504458', u'African_elephant']]
```

**Comment by OrenBochman** [comment]
also seeing this when running same keras example from R

**Comment by huwade** [comment]
I meet the same problem too

**Comment by prativadas** [comment]
IOError: [Errno 2] No such file or directory: 'elephant.jpg' 
kindly address this issue how to resolve it

**Comment by GeneralJing** [comment]
IOError: [Errno 2] No such file or directory: 'elephant.jpg'. same question, anyone who knows?

**Comment by huwade** [comment]
Just google a elephant picture and download it, and save the picture name as "elephant.jpg"

**Comment by GeneralJing** [comment]
Is this the correct way of operation?I thought it was the image that comes with keras.

**Comment by mrgransky** [comment]
It seems `elephant.jpg` picture is not included, therefore, you can run the following command to get an image which renames it to `elephant.jpg` used for your algorithm:

`wget https://upload.wikimedia.org/wikipedia/commons/f/f9/Zoorashia_elephant.jpg -O elephant.jpg   `

**Comment by GeneralJing** [comment]
Thank you. Got that image.
