### ISSUE TITLE
class_weights dictionary for one-hot vectors?

### ISSUE THREAD

**Issue by mjs-wpi** [fchollet/keras#5536]
What is the best practice in Keras for class balancing with one-hot vectors? I can't make a dictionary with {vectors:weights} because vectors are not hash-able.

Or is this a non-issue? Does Keras map class labels and weights to the appropriate one-hot vectors in my batches?

**Comment by usuyama** [comment]
Maybe, we can use `sample_weight` parameter?

> sample_weight: optional array of the same length as x, containing
                weights to apply to the model's loss for each sample.
                In the case of temporal data, you can pass a 2D array
                with shape (samples, sequence_length),
                to apply a different weight to every timestep of every sample.
                In this case you should make sure to specify
                sample_weight_mode="temporal" in compile().

https://github.com/fchollet/keras/blob/d89afdfd82e6e27b850d910890f4a4059ddea331/keras/engine/training.py#L1392

**Comment by usuyama** [comment]
There's `sample_weights` for generator, too.

https://github.com/fchollet/keras/blob/73bf06fb023a8b37ddf2e2a168bbf920c7a6c766/keras/models.py#L1030
