### ISSUE TITLE
The output of K.dropout is not as expected!

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#5539]
For example:
```
x = numpy.array[[1,2,3],[4,5,6]]
x = K.variable(value = x, dtype = 'float64')
out = K.dropout(x, 0.4, seed=1334)
K.eval(out)
```

The results:
`array([1.6666666, 3.3333332, 4.9999998], [0. , 8.33333 , 0. ])`

But, in my opinion, the dropout operator only sets entries in `x` to zero at random,  the results should be like: `array([1, 2, 3], [0. , 5 , 0. ])`
why are other elements also modified?
If I want to implement the function like my description,  which method should I use? Any opinions or suggestions would be appreciated!

**Comment by unrealwill** [comment]
Hello,

Because Keras use inverse scaling for dropout.

See https://github.com/fchollet/keras/issues/3305
and https://github.com/fchollet/keras/issues/5357

for more information.

**Comment by Imorton-zd** [comment]
Thanks for your reply.
