### ISSUE TITLE
Cannot Merge (concat) Dense and Embedding Layers

### ISSUE THREAD

**Issue by PilCAki** [fchollet/keras#554]
from keras.models import Sequential
from keras.layers.core import Dense, Merge
from keras.layers.embeddings import Embedding
from keras.optimizers import SGD

DENSE_INPUT_SIZE=9
DENSE_OUTPUT_SIZE = 3

EMBEDDING_INPUT_SIZE = 22
EMBEDDING_OUTPUT_SIZE = 5

TOTAL_HIDDEN_OUTPUT_SIZE = DENSE_OUTPUT_SIZE + EMBEDDING_OUTPUT_SIZE

e = Sequential()
e.add(Embedding(EMBEDDING_INPUT_SIZE, EMBEDDING_OUTPUT_SIZE))

d = Sequential()
d.add(Dense(DENSE_INPUT_SIZE, DENSE_OUTPUT_SIZE))

model = Sequential()
model.add(Merge([e,d], mode='concat'))
model.add(Dense(TOTAL_HIDDEN_OUTPUT_SIZE, 1))

sgd = SGD()
model.compile(loss='mean_squared_error', optimizer=sgd)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-82616a6c4270> in <module>()
     23 
     24 sgd = SGD()
---> 25 model.compile(loss='mean_squared_error', optimizer=sgd)

/home/user/anaconda/lib/python2.7/site-packages/keras/models.pyc in compile(self, optimizer, loss, class_mode, theano_mode)
    285         self.X_test = self.get_input(train=False)
    286 
--> 287         self.y_train = self.get_output(train=True)
    288         self.y_test = self.get_output(train=False)
    289 

/home/user/anaconda/lib/python2.7/site-packages/keras/layers/containers.pyc in get_output(self, train)
     49 
     50     def get_output(self, train=False):
---> 51         return self.layers[-1].get_output(train)
     52 
     53     def set_input(self):

/home/user/anaconda/lib/python2.7/site-packages/keras/layers/core.pyc in get_output(self, train)
    339 
    340     def get_output(self, train=False):
--> 341         X = self.get_input(train)
    342         output = self.activation(T.dot(X, self.W) + self.b)
    343         return output

/home/user/anaconda/lib/python2.7/site-packages/keras/layers/core.pyc in get_input(self, train)
     29     def get_input(self, train=False):
     30         if hasattr(self, 'previous'):
---> 31             return self.previous.get_output(train=train)
     32         else:
     33             return self.input

/home/user/anaconda/lib/python2.7/site-packages/keras/layers/core.pyc in get_output(self, train)
    144         elif self.mode == 'concat':
    145             inputs = [self.layers[i].get_output(train) for i in range(len(self.layers))]
--> 146             return T.concatenate(inputs, axis=-1)
    147         else:
    148             raise Exception('Unknown merge mode')

/home/user/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/basic.pyc in concatenate(tensor_list, axis)
   3860             "or a list, make sure you did not forget () or [] around "
   3861             "arguments of concatenate.", tensor_list)
-> 3862     return join(axis, *tensor_list)
   3863 
   3864 

/home/user/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/gof/op.pyc in __call__(self, *inputs, **kwargs)
    507         """
    508         return_list = kwargs.pop('return_list', False)
--> 509         node = self.make_node(*inputs, **kwargs)
    510 
    511         if config.compute_test_value != 'off':

/home/user/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/basic.pyc in make_node(self, *axis_and_tensors)
   3510 
   3511         return self._make_node_internal(
-> 3512             axis, tensors, as_tensor_variable_args, output_maker)
   3513 
   3514     def _make_node_internal(self, axis, tensors,

/home/user/anaconda/lib/python2.7/site-packages/Theano-0.7.0-py2.7.egg/theano/tensor/basic.pyc in _make_node_internal(self, axis, tensors, as_tensor_variable_args, output_maker)
   3576         if not python_all([x.ndim == len(bcastable)
   3577                            for x in as_tensor_variable_args[1:]]):
-> 3578             raise TypeError("Join() can only join tensors with the same "
   3579                             "number of dimensions.")
   3580 

TypeError: Join() can only join tensors with the same number of dimensions.

**Comment by fchollet** [comment]
Try upgrading Theano to the latest version (get it from the Github repo).

**Comment by PilCAki** [comment]
Just reinstalled via "sudo pip install --upgrade git+git://github.com/Theano/Theano.git"
Same error message

**Comment by PilCAki** [comment]
And just for the record, my Theano was already pretty recent.  I set up Ubuntu from scratch and installed Theano directly from git about 2 weeks ago.

**Comment by fchollet** [comment]
As your probably realize, your post is completely unreadable, which is why the cause of the error was not immediately obvious. Looking at the first lines of your code, it seems you are attempting to merge the output of `Embedding` with the output of `Dense`. According to the documentation, the former is 3D while the latter is 2D, hence it cannot work. 

If you know what you are doing, you can try to use a `Reshape` or a `Flatten` layer.

**Comment by PilCAki** [comment]
Sorry about that - I've never raised an issue on github before.  How can I improve the formatting?

Also, why is the output of the Embedding 3-d?  It's a mapping from sparse inputs to a vector - why isn't it 1-d or 2-d?

**Comment by fchollet** [comment]
It is 3D because it is mapping sequences of integer indices to sequences of dense vectors. Sequences of vectors are 3D tensors. In the indices representation, the last dimension (features) is implicit (the indices!), hence it fits in a 2D tensor.

Here's a guide about Github markdown: https://help.github.com/articles/github-flavored-markdown/
