### ISSUE TITLE
Change the name of pretrained model

### ISSUE THREAD

**Issue by lrg1213** [fchollet/keras#5540]
I am building a two-stream model and use pretrained ResNet-50 twice. But the error came out:

RuntimeError: The name 'resnet50' is used 2 times in the model. All layer names should be unique.

If there is some one knows how can I change the names of my two ResNet50 model?
(My code like this : x=ResNet50(weights='imagenet')(x)
                                y=ResNet50(weights='imagenet')(y)
)

**Comment by Narts** [comment]
Did you figure this out?

**Comment by jonilaserson** [comment]
I think this issue is important enough to reopen.
