### ISSUE TITLE
Different shapes for output of reshape

### ISSUE THREAD

**Issue by abhaikollara** [fchollet/keras#5568]
This is a piece of code from [wrappers.py](https://github.com/fchollet/keras/blob/master/keras/layers/wrappers.py) of keras-2. 

```python
print "Before :", K.int_shape(inputs)
inputs = K.reshape(inputs, (-1,) + input_shape[2:])
print "After :", K.int_shape(inputs)
```
I added the `print` statements to see the change in shape. And apparently, running it with Theano backend gives a different output shape compared to Tensorflow. The print outputs are given below
- Theano
```
Before : (None, 2, 4, 4, 3)
After : (None, 4, 4, 3)
```
- Tensorflow
```
Before : (None, 2, 4, 4, 3)
After : (-1, 4, 4, 3)
```

Could someone tell me what's going on here ?

**Comment by unrealwill** [comment]
Hello,

I don't know the specifics of int_shape, but aren't -1 or None equivalent when we are talking about shapes.
Do you have an example where it causes some issues?

Thank you

**Comment by abhaikollara** [comment]
Thanks. That's what I thought too, but I was just wondering if the above difference was causing this exception being thrown when testing `TimeDistributed` layer with `convolutional.Conv2D` in keras-2.

```python
self = <theano.tensor.opt.ShapeFeature object at 0x7f8f79263050>, s_i = -1

    def unpack(self, s_i):
        """Return a symbolic integer scalar for the shape element s_i.
    
            The s_i argument was produced by the infer_shape() of an Op subclass.
    
            """
        # unpack the s_i that the Op returned
        assert s_i is not None
        if s_i == 1:
            # don't make the optimizer merge a zillion ones together
            # by always returning the same object to represent 1
            return self.lscalar_one
        if type(s_i) is float and int(s_i) == s_i:
            s_i = int(s_i)
        if (type(s_i) in integer_types or
                isinstance(s_i, numpy.integer) or
                (isinstance(s_i, numpy.ndarray) and s_i.ndim == 0)):
            # this shape is a constant
>           assert s_i >= 0
```
```
E           AssertionError
```
