### ISSUE TITLE
what is the initial value for bias term ? what is the range of the random values if we use glorot_uniform? 

### ISSUE THREAD

**Issue by MuOtb** [fchollet/keras#5571]
In the conv layers, what is the initial value for bias terms?  
The initializations  of the weights are clear. but the initialization of the bias terms is not mentioned. How the bias term is  initialized ? and  what is the range of the random value? 
The same question for the glorot_uniform, what is the range of the random values if we use glorot_uniform ( Ex : between 0 - 1 etc) ? 

I am using the TensorFlow. 

Thank you!

**Comment by unrealwill** [comment]
Hello,

About bias of Conc1D : 
https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L140
```

        if self.bias:
            self.b = self.add_weight((self.nb_filter,),
                                     initializer='zero',
                                     name='{}_b'.format(self.name),
                                     regularizer=self.b_regularizer,
constraint=self.b_constraint)
```

About glorot_uniform : 
https://github.com/fchollet/keras/blob/master/keras/initializations.py#L63
https://github.com/fchollet/keras/blob/master/keras/initializations.py#L33

**Comment by MuOtb** [comment]
Thank U.
