### ISSUE TITLE
plot 1d convolution layer weights

### ISSUE THREAD

**Issue by vinayakumarr** [fchollet/keras#5573]
My 1d convolution layer code is given below 

cnn.add(Convolution1D(64, 3, border_mode="same",activation="relu",input_shape=(43, 1)))

code for plot 

cnn.load_weights("checkpoint-766.hdf5")

def plot_filters(layer, x, y):
  filters = layer.W.get_value()
  fig = plt.figure()
  for j in range(len(filters)):
    ax = fig.add_subplot(y,x,j+1)
    ax.matshow(filters[j][0], cmap = matplotlib.cm.binary)
    plt.xticks(np.array([]))
    plt.yticks(np.array([]))
  plt.tight_layout()
  plt.show()
  return plt

plot_filters(cnn.layers[0], 1, 64)

**Comment by Kavchch** [comment]
I have gone through the code for plotting of weights in GitHub.
But when I tried to implement same thing in my code ,I'm not able to plot it. Please help me in this .I want to extract the info from layer1 what filters has learnt and plot it .Thanks in advance.
Below is my code :
 model_cmm.load_weights("results/model1_mfcc_mel_chro_final_cmm.h5")
 model_cmm = Sequential()
 model_cmm. Add(Conv1D(filters=512,kernel_size=5,padding='same',activation='relu',input_shape=(180,1)))

def plot_filters(layer, x, y):
   
    filters = layer.get_weights()
    print(filters)
    fig = plt.figure()
    for j in range(len(filters)):
        ax = fig.add_subplot(y,x,j+1)
        ax.matshow(filters[j][0], cmap = matplotlib.cm.binary)
    plt.xticks(np.array([]))
    plt.yticks(np.array([]))
    plt.tight_layout()
    plt.show()
    return plt

plot_filters(model_cmm.layers[0], 1, 512)

**Comment by hexi03** [comment]
If I understand your purpose correctly, then the only way I know is to take the weights of the desired layer from the first model and transfer them to the layer of another model, consisting of the data preparation layers and the layer you need (similar to your trained model). (using the get_weights () and set_weights () functions of the layers in model.layers) Then you can use predict () to plot
