### ISSUE TITLE
Possible error in formatting for Model Progress Bar

### ISSUE THREAD

**Issue by Ninad998** [fchollet/keras#5578]
While using the `ModelCheckpoint` Callback, there is error in the output formatting.

Console output:
```
...
Epoch 6/30
29320/29320 [==============================] - 2026s - loss: 0.3603 - acc: 0.8564 - val_loss: 0.3464 - val_acc: 0.85270.82933 to 0.85266, saving model to XYZ.hdf5
....
```
Output file:
```
...
Epoch 6/30
...
29310/29320 [============================>.] - ETA: 0s - loss: 0.3604 - acc: 0.8564Epoch 00005: val_acc improved from 0.82933 to 0.85266, saving model to XYZ.hdf5

29320/29320 [==============================] - 2026s - loss: 0.3603 - acc: 0.8564 - val_loss: 0.3464 - val_acc: 0.8527

...
```

I am assuming that this `` is a special formatting character used to reprint on the same line in console and on ipython notebooks. But in the ipython notebook, I receive output similar to the Output file while the console gets rid of certain characters, eg: `... val_acc: 0.85270.82933 ...` should look like `... 0.8564Epoch 00005: val_acc improved from 0.82933 ...` .

Is it possible to make certain changes in the Progress Bar so that by default the `ModelCheckpoint` output goes to the next line?

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by StripedBanana** [comment]
I'm having the same problem with the callback `ModelCheckpoint`. The console output doesn't go to the next line and gets overwritten:
```
Epoch 2/20
798/798 [==============================] - 374s - loss: 0.0592 - val_loss: 0.0567_loss improved from 0.06830 to 0.05668, saving model to ...
```

I think this callback is used fairly often and deserves a clean output
