### ISSUE TITLE
scikit-learn wrapper move params to init()

### ISSUE THREAD

**Issue by JasonTam** [fchollet/keras#558]
I would like to suggest moving the fit and predict params (`batch_size=128, nb_epoch=100 ...` etc) to `__init__()`. Scikit-learn is phasing out any parameters that must be explicitly passed through fit & predict.  This should make the model much easier to incorporate into ensembles and pipelines.

Perhaps we could shove all the params into a dict `self.fit_params = {...}` and load in defaults as necessary.

Thoughts?

**Comment by fchollet** [comment]
Agreed that it would make sense. 

We should also support the methods `set_params` and `get_params`.

**Comment by JasonTam** [comment]
`set_params` and `get_params` were already in there. But I assume @jdwittenauer wrote those as temporary placeholders.

Easiest way to properly incorporate `set_params` and `get_params` is to inherit from `sklearn.base.BaseEstimator` . But it's currently a bit troublesome since `get_params(deep=True)` will call `keras.models.Sequential.get_params` -- which is not sklearn compliant (returns a tuple rather than a dict). I'm not sure if I want to touch that at the moment :)

**Comment by jdwittenauer** [comment]
I'm okay with moving these to init, in hindsight that probably makes more sense.  I didn't use sklearn.base.BaseEstimator because I didn't think it was worth adding a dependency (as long as the API is compatible it shouldn't matter).
