### ISSUE TITLE
Feeding ouput of a layer to 2 layers simultaneously

### ISSUE THREAD

**Issue by KiranBaktha** [fchollet/keras#5584]
Hey guys, hi have a neural network design in mind that needs the output of the embedding layer to be fed to two layers.
model = Sequential()
model.add(Embedding)
Now I want the output of the embedding to be fed to Layer 2 and Layer 3
model.add(Layer2) , model.add(Layer3)
I would also need to add more layers to  these layers (Layers 2 and Layer 3) independently and combine them later on. 
Thanks in advance

![query](https://cloud.githubusercontent.com/assets/9200167/23546805/4531cf40-0027-11e7-9b70-6cdd8aa9119c.jpg)

**Comment by unrealwill** [comment]
Hello,

Use the functional API : 
https://keras.io/getting-started/functional-api-guide/

**Comment by KiranBaktha** [comment]
Thanks a lot :)
