### ISSUE TITLE
Allocating GPU memory before using Convulations causes program to crash

### ISSUE THREAD

**Issue by kush789** [fchollet/keras#5587]
Hi,

I'm using the following function to allocate a percentage of GPU memory

    import os
    import tensorflow as tf
    import keras.backend.tensorflow_backend as KTF

    def get_session(gpu_fraction=0.3):
        '''Assume that you have 6GB of GPU memory and want to allocate ~2GB'''
        num_threads = os.environ.get('OMP_NUM_THREADS')
        gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=gpu_fraction)

        if num_threads:
            return tf.Session(config=tf.ConfigProto(
                gpu_options=gpu_options, intra_op_parallelism_threads=num_threads))
        else:
            return tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
    
    KTF.set_session(get_session(0.5))

This works fine if I try to train a LSTM. However in case I try to train a CNN, the program crashes. I believe this has something to do with the CUDNN. The error I get is 

	I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
	I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
	I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
	I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
	I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
	Using TensorFlow backend.
	W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
	W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
	W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
	W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
	I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
	name: GeForce GTX 980 Ti
	major: 5 minor: 2 memoryClockRate (GHz) 1.291
	pciBusID 0000:01:00.0
	Total memory: 5.94GiB
	Free memory: 3.04GiB
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
	I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0)
	X_train shape: (60000, 28, 28, 1)
	60000 train samples
	10000 test samples
	Train on 60000 samples, validate on 10000 samples
	Epoch 1/12
	E tensorflow/stream_executor/cuda/cuda_dnn.cc:397] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
	E tensorflow/stream_executor/cuda/cuda_dnn.cc:364] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
	F tensorflow/core/kernels/conv_ops.cc:605] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 
	Aborted (core dumped)

To cross check whether it this function is the issue, I tried running the Keras MNIST example [here](https://raw.githubusercontent.com/fchollet/keras/master/examples/mnist_cnn.py).

Running the example as it didn't cause any issue. However after using my function to allocate half the GPU memory before running it, the program crashed.

**Comment by unrealwill** [comment]
Hello, 
Have you tried to write a pure TensorFlow test (i.e. without using Keras at all)?

**Comment by minghao-wu** [comment]
I met the exactly same problem.
@unrealwill  I ran a pure TensorFlow test on my GPU (Titan X Pascal), it worked very well.
Everything is on the latest version.

> Epoch 1/20
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:4b:00.0
Total memory: 11.90GiB
Free memory: 11.34GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:4b:00.0)
Killed
