### ISSUE TITLE
Autoencoder Architechture

### ISSUE THREAD

**Issue by patyork** [fchollet/keras#56]
Given the discussion of weight initializations, any opinions on how an autoencoder architecture should be added?

-Stopping conditions for each in a pre-created set of layers [vs.] manual saving -> layer addition -> compile -> start next level of training?
-Noise addition (perhaps as a layer) over a distribution?
-Used only as a pretraining device [vs.] allow backproagation to create and encoder + decoder?

**Comment by kenterao** [comment]
I have an implementation of Autoencoder with tied weights.  It's basically two-layers-in-one.  After pre-training you can extract the weights and initialize two Dense layers.

```python
def get_output(self, train):
    X = self.get_input(train)
    encode = self.activation1(T.dot(X, self.W) + self.b)
    decode = self.activation2(T.dot(encode, self.W.T) + self.b_p)
    return decode
```
The trick for fitting multi-layer autoencoders is how to not backprop through the previously fit weights.  The method I use is to create a regularizer function
```python
def zero_grad(g, p):
    return 0.
```
Then I pass that into the pre-trained Dense layer to prevent backprop from changing the weights.

**Comment by jramapuram** [comment]
Implemented https://github.com/fchollet/keras/pull/180
