### ISSUE TITLE
improving accuracy 

### ISSUE THREAD

**Issue by vinayakumarr** [fchollet/keras#5604]
I have data as features in probability values. The values are too small. I want to know which normalization i should use and I used convolution1d and dnn, and lstm. But the performance is too les. If i use the same data with DBN tool box in matlab, the accuracy was 70%. Could you please tell how to improve the accuracy. I think i am getting less accuracy because the input data is too small. In DBN matlab tool box they have an option to set input data as binary or probability. This shows train accuracy as 1 in 1 epoch and it remains same till 100 epoch but validation accuracu in epoch was 40% and it decreases till 1000 epoch in lstm, convolution1d and dnn
![untitled](https://cloud.githubusercontent.com/assets/18217467/23586618/a90e0e32-01be-11e7-83f5-0dd85f7db052.png)
ilities values.

**Comment by unrealwill** [comment]
Hello,

You should take the log (do a log transformation) otherwise you are bound to have numerical issues.

**Comment by vinayakumarr** [comment]
How to do? Could you explain

**Comment by vinayakumarr** [comment]
Is there any inbuilt function in scikit or keras

**Comment by unrealwill** [comment]
features = Input( shape="your data shape")
logtransformedFeatures = Lambda(lambda x: K.log(x) )(inp)

**Comment by vinayakumarr** [comment]
NameError: name 'Input' is not defined

**Comment by vinayakumarr** [comment]
my input shape is (5920, 1024) and type is <type 'numpy.ndarray'>

**Comment by unrealwill** [comment]
from keras.layers import Input 
Or you can do the log transformation in numpy before.

**Comment by vinayakumarr** [comment]
i use first option from keras.layers import Input. The code is give for reading a csv file. AFter that waht to do?

traindata = pd.read_csv('data/trainData.csv', header=None)
X = traindata.iloc[:,0:1024]
trainX = np.array(X)

**Comment by unrealwill** [comment]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

**Comment by vinayakumarr** [comment]
no.log10(trainX
After doing this, I have applied convolution1d and lstm, dbn, in most of the cases train accuracy become 1and validation accuracy maximum is 66 and this value fluctuate between epochs

**Comment by vinayakumarr** [comment]
Do you know why it it showing this?
