### ISSUE TITLE
How to use k.function in keras when model have merge layer

### ISSUE THREAD

**Issue by litingsjj** [fchollet/keras#5605]
I use the layer "merge" like this:

model_gray = Sequential()
model_gray.add(Convolution3D(nb_filters[0],kernel_dim1=nb_conv[0], kernel_dim2=nb_conv[0],
                        kernel_dim3=nb_conv[0], input_shape=(1, img_rows, img_cols,patch_size),
                        activation='relu'))
...
model_flow_x = Sequential()
model_flow_x.add(Convolution3D(nb_filters[0],kernel_dim1=nb_conv[0], kernel_dim2=nb_conv[0],
                        kernel_dim3=nb_conv[0], input_shape=(1, img_rows, img_cols,patch_size),
                        activation='relu'))
...
model_flow_y = Sequential()
model_flow_y.add(Convolution3D(nb_filters[0],kernel_dim1=nb_conv[0], kernel_dim2=nb_conv[0],
                        kernel_dim3=nb_conv[0], input_shape=(1, img_rows, img_cols,patch_size),
                        activation='relu'))
...
merged = Merge([model_gray,model_flow_x, model_flow_y], mode='concat')
model = Sequential()
model.add(merged)
model.add(Dense(128, init='normal', activation='relu'))
...
When I define theano.function (or K.function) to get full connect layer, like this:

get_feature = K.function(model_gray.layers[0].input,model_flow_x.layers[0].input,model_flow_y.layers[0].input,
                            K.learning_phase()],model.layers[1].output)  #the function has no error

train_feature = get_feature([X_train_gray,X_train_flow_x,X_train_flow_y]) #have an error: TypeError: ('Bad input argument to theano function with name "<ipython-input-   84-04c3e9b312ad>:3"  at index 0(0-based)', 'Wrong number of dimensions: expected 5, got 6 with shape (3, 3307, 1, 80, 60, 30).')

If I use
train_feature = get_feature(X_train_gray,X_train_flow_x,X_train_flow_y) #the error is :TypeError: Missing required input: keras_learning_phase
I don't have any idea of it! Can you help me? thanks!

**Comment by unrealwill** [comment]
Hello,

You are probably misreading the error.

> at index 0(0-based)', 'Wrong number of dimensions: expected 5, got 6 with shape (3, 3307, 1, 80, 60, 30).')

It means that X_train_gray should be of dimension 5.

**Comment by litingsjj** [comment]
@unrealwill  yes my X_train_gray is (3307, 1, 80, 60, 30) but I don't know why ,I already have train cnn

**Comment by unrealwill** [comment]
call it without []: 
`get_feature(X_train_gray,X_train_flow_x,X_train_flow_y)`

**Comment by unrealwill** [comment]
Edited previous comment.

**Comment by litingsjj** [comment]
@unrealwill  sorry to bother you again, but it doesn't work. I give it a 0 or 1 have a MemoryError:
MemoryError: Error allocating 13045760000 bytes of device memory (CNMEM_STATUS_OUT_OF_MEMORY).
Apply node that caused the error: GpuAllocEmpty(Elemwise{Composite{Switch(EQ(i0, i1), i2, i0)}}.0, Elemwise{Composite{Switch(EQ(i0, i1), i2, i0)}}.0, Elemwise{Composite{((((i0 + i1) - i2) // i3) + i3)}}.0, Elemwise{Composite{((((i0 + i1) - i2) // i3) + i3)}}.0)
Toposort index: 242
Inputs types: [TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar)]
Inputs shapes: [(), (), (), ()]
Inputs strides: [(), (), (), ()]
Inputs values: [array(14000), array(160), array(56), array(26)]
Outputs clients: [[GpuDnnConv{algo='small', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode='valid', subsample=(1, 1), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by unrealwill** [comment]
This is a progress. You are now trying to run the function and consuming too much memory. In fact this is because you are trying to process the whole training set in one go. This is probably not what you want to do.

Do you really want to use K.function?

If so then you have to do the mini batching yourself.

```
out = np.zeros( your output shape )
mbs = 32
for i in range( 0,len(X_train_gray),mbs ):
   out[ i:i+mbs,:] =   get_feature([X_train_gray[ i:i+mbs,:],X_train_flow_x[ i:i+mbs,:],X_train_flow_y[ i:i+mbs,:]]) 
remaining = int( len(X_train_gray)/ mbs) * mbs
out[ remaining:,:] =   get_feature([X_train_gray[ remaining:,:],X_train_flow_x[ remaining:,:],X_train_flow_y[ remaining:,:]]) 
```

If not you can define a Model instead.

You probably want to rewrite using functional API (https://keras.io/getting-started/functional-api-guide/) because it is easier to grab the layers you want.
`getFeatureModel = Model( [model_gray.layers[0],model_gray.layers[0],model_gray.layers[0]] , [model.layers[1] ] )  `

And then use the 
`getFeatureModel.predict( [X_train_gray,X_train_flow_x,X_train_flow_y] )`

which will automatically use a batch_size of 32.

If you still encounter memory error reduce this batch size to 1. If you still encounter a memory error, you can investigat using getFeatureModel.summary(). Or you can use more memory by either buying a bigger GPU or running with CPU.

**Comment by litingsjj** [comment]
@unrealwill  It worked! When I use X_train_gray[ 1:10] , thank you very much! Actually, I wanted to get all features that use SVM to classifing them. But when I use SVM+CNN training minist, the accuracy is not higher than cnn, maybe I should give it up.

**Comment by alyato** [comment]
@unrealwill  @litingsjj 
when i using the following code ,it show me an error

> xy = Model([model.layers[0],model.layers[0]],[model.layers[-2]])
everyFm = xy.predict([li[i],li[i]])

the errror is 

> ValueError: The list of inputs passed to the model is redundant. All inputs should only appear once. Found: [<keras.engine.topology.InputLayer object at 0x7f3ac535f210>, <keras.engine.topology.InputLayer object at 0x7f3ac535f210>]

I load my model using `model_from_json`

The model has two inputs and one outputs.
I think when i use the `Model`,the inputs are should different.
Thanks.
