### ISSUE TITLE
How to get the output of an LSTM layer in a neural network language model

### ISSUE THREAD

**Issue by freesunshine0316** [fchollet/keras#5606]
Hi,

I implemented a neural language model, which has an embedding layer, an LSTM layer and a Dense layer with softmax activation. Basically it looks like this (not the actual code):

model = Sequantial()
model.add(Embedding())
model.add(LSTM(return_sequence=True, stateful=True))
model.add(TimeDistributed(Dense(, activation='softmax')))

Right now, the model has been successfully trained.
During prediction I feed the network one word each time (batch_size=1, and step_size=1), and only want the LSTM layer's output (vector h) as a numpy array object, how can I get this?

======================

I've tried model.get_layer('lstm_1').output, but it is a tensor object.
When I try model.get_layer('lstm_1').output.eval(session=K.get_session(),feed_dict={K.learning_phase():0}), I got the following error:

tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'word' with dtype int32 and shape [1,1]
         [[Node: word = Placeholder[dtype=DT_INT32, shape=[1,1], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by unrealwill** [comment]
Hello,

You should probably define your model using submodels. 
Then you can use a model for training and a model for predicting which will share weights.

```
submodelwithouttop = Sequantial()
submodelwithouttop.add(Embedding())
submodelwithouttop.add(LSTM(return_sequence=True, stateful=True))

inp = Input(...)
trainingOut = TimeDistributed(Dense(, activation='softmax'))( submodelwithouttop(inp) )
modelfortraining = Model(inp,trainingOut)

inp = Input()
predictionOut =submodelwithouttop(inp)
modelForPrediction = Model( inp,predictionOut)
```

**Comment by freesunshine0316** [comment]
The code is written by others that I don't want to change it too much.

**Comment by unrealwill** [comment]
Then you can try :
https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer
