### ISSUE TITLE
Issue when freezing Embedding Layer

### ISSUE THREAD

**Issue by KiranBaktha** [fchollet/keras#5611]
Hi Guys, 
I need to feed custom weights to my embedding layer, so I do it using this line of code:

model.add(Embedding(47747, embedding_vecor_length, input_length=500, weights = [weights],dropout=0.2))

However, I need to prevent the embedding layer from changing these weights, so when I add trainable = False to the code:

Embedding(47747, embedding_vecor_length, input_length=500, weights = [weights],dropout=0.2, trainable = False)

I get the following error:

You called `set_weights(weights)` on layer "embedding_1" with a  weight list of length 1, but the layer was expecting 0 weights. Provided weights: [array([[-2.07139611,  0.38602829, -0.56659412, .....

Kindly help me correct the issue. Thanks in advance.

**Comment by unrealwill** [comment]
Hello, 
Can't reproduce : 

```
import numpy as np
from keras.layers import Input, Dense,Embedding
from keras.models import Model,Sequential

embedding_vecor_length = 100

nbvector = 47747
weights = np.random.randn(nbvector,embedding_vecor_length)

model = Sequential()
model.add(Embedding(nbvector, embedding_vecor_length, input_length=500, weights = [weights],trainable=False))

model.compile( loss="mse",optimizer="adam")

print model.predict(np.random.randint(0,nbvector,(32,500))).shape
model.fit( np.random.randint(0,nbvector,(32,500)),np.random.randn(32,500,100) )
```

**Comment by 1064950364** [comment]
@unrealwill 
I run your code, and I get the same error:
ValueError: You called `set_weights(weights)` on layer "embedding_1" with a  weight list of length 1, but the layer was expecting 0 weights. Provided weights: [array([[-0.34739672, -1.25501704,  0.32280885, .....
I run it at keras1.2.0

**Comment by 1064950364** [comment]
@KiranBaktha 
Did you have fixed this?

**Comment by unrealwill** [comment]
Hello,

I have not upgraded to keras 2 yet.
It worked fine on theano at the time.

But you can try to construct the layer with trainable = True,
and then set the layer to trainable=False on the next line.

```
emb=Embedding(47747, embedding_vecor_length, input_length=500, weights = [weights],dropout=0.2, trainable = True)
emb.trainable = False
```

**Comment by KiranBaktha** [comment]
Upgrade to the latest Keras and proceed this manner....

        inputs = Input(shape = (100,) , dtype = 'int32')
        Embs = Embedding(87510, embedding_vecor_length, input_length=50, weights =   [w1],mask_zero=True,dropout=0.2,trainable=False)
        Embsyo = Embs(inputs)
