### ISSUE TITLE
Obtain output at each timestep

### ISSUE THREAD

**Issue by AahanSingh** [fchollet/keras#5617]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I need the LSTM to generate words at each timestep which is given as input to the next timestep. Can this be done in keras?

**Comment by unrealwill** [comment]
As far as I know, it can not easily be done.

You will have to use either theano or tensorflow "scan" to allow the output to be fed to the input in a recursive fashion.

Alternatively you can have a look at https://github.com/datalogai/recurrentshop with parameter readout=True.
But in its current state, I can not recommend usage of this library.

**Comment by ParthaEth** [comment]
you can make the model stateful and predict one time step at a time. The performance is not very bad. As you only require it in the test time which the performance impact is not that great

**Comment by AahanSingh** [comment]
@unrealwill I didn't quite understand what you meant by 'scan'. 
@ParthaEth How would the training be done in this case? What would be the samples and the targets?

**Comment by unrealwill** [comment]
@AahanSingh By scan I mean http://deeplearning.net/software/theano/library/scan.html
You train your model with stateful = False the usual way (This mean that during training the generated word is not used as input of the next time step) . Then for generation you build a similar model with stateful = True, and you feed it one time step at a time, and it will give an output which you will feedback in.
