### ISSUE TITLE
model.fit_generator() still several times slower than model.fit()

### ISSUE THREAD

**Issue by mikalyoung** [fchollet/keras#5620]
As of Keras 1.2.2, referencing [merge](https://github.com/fchollet/keras/issues/2730), it does have multiprocessing included, but model.fit_generator() is still about 4x slower than model.fit().  How can this be further sped up?

**Comment by tbenst** [comment]
I am also seeing massive slowdowns when training with `fit_generator`. It also appears to get slower over time, i.e. my first epoch took 43 minutes but the 53rd epoch took 2 hours 14 min. Can this be reopened?
