### ISSUE TITLE
image_ocr.py contains incorrect bidirectional GRU code

### ISSUE THREAD

**Issue by pasky** [fchollet/keras#5624]
The image_ocr code contains the typical mistake of trying to construct a bidirectional RNN network manually and failing to notice that the go_backwards sequence output is unfortunately reversed.  Simplifying the model code to

```
    # Two layers of bidirecitonal GRUs
    # GRU seems to work as well, if not better than LSTM:
    gru_1 = Bidirectional(GRU(rnn_size, return_sequences=True, init='he_normal', name='gru1'), merge_mode='sum')(inner)
    gru_2 = Bidirectional(GRU(rnn_size, return_sequences=True, init='he_normal', name='gru2'), merge_mode='concat')(gru_1)

    # transforms RNN output to character activations:
    inner = Dense(img_gen.get_output_size(), init='he_normal', name='dense2')(gru_2)
```

therefore enables the model of actually taking advantage of the backwards GRU. Norm. ED (TF):

Epoch |   old   |   fixed
--------|---------|-------
10  | 0.082 |  0.039
15  | 0.074  | 0.022
20  | 0.039  | 0.021
25  | 0.034  | 0.008

(Not creating a PR myself due to keras-1 PR freeze.)

**Comment by rizkiarm** [comment]
Hi, may I know the detail of your setup (keras version, tensorflow version, etc)?
I am having difficulties in reproducing the listed performance of the original image_ocr.py and the modification that you made (norm. ED stuck at around 0.6 using tensorflow). Thanks.

**Comment by bachhovuong310** [comment]
Can you show me CTC loss in your model ? I modify the model in image_ocr.py  and change the input data. The result is not good :(

**Comment by pasky** [comment]
Muhammad, can you try again with latest keras1 release?  It's possible
the big keras2 changes broke something.

**Comment by rizkiarm** [comment]
I've tried to use Keras 1.2.x using Tensorflow 0.9.0, 0.11.0, and 1.0.x as a backend, and still, couldn't reproduce the listed performance. I used [this version of image_ocr.py](https://github.com/fchollet/keras/blob/c0d95fd6c2cd8ffc0738819825c3065e3c89977c/examples/image_ocr.py), and the following setup (in my latest experiment):
`appdirs==1.4.2
cairocffi==0.8.0
cffi==1.9.1
cycler==0.10.0
dask==0.14.0
decorator==4.0.11
dlib==19.3.1
editdistance==0.3.1
ez-setup==0.9
funcsigs==1.0.2
functools32==3.2.3.post2
h5py==2.6.0
Keras==1.2.0
matplotlib==2.0.0
mock==2.0.0
networkx==1.11
numpy==1.12.0
olefile==0.44
packaging==16.8
pbr==2.0.0
Pillow==4.0.0
protobuf==3.0.0b2
pycparser==2.17
pyparsing==2.1.10
python-dateutil==2.6.0
pytz==2016.10
PyYAML==3.12
recurrentshop==0.0.1
scikit-image==0.12.3
scipy==0.18.1
seq2seq==0.1.0
six==1.10.0
subprocess32==3.2.7
tensorflow==0.9.0
Theano==0.8.2
toolz==0.8.2`

Do you have any ideas on why this could happen?

**Comment by gw0** [comment]
Unfortunately the example does not work anymore, because the `wordlist.tgz` is not available. Probably due to the renaming of the company and setting up of invalid redirects?

```
$ python image_ocr.py
Downloading data from http://www.isosemi.com/datasets/wordlists.tgz
Traceback (most recent call last):
  File "image_ocr.py", line 490, in <module>
    train(run_name, 0, 20, 128)
  File "image_ocr.py", line 419, in train
    origin='http://www.isosemi.com/datasets/wordlists.tgz', untar=True))
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 115, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on http://www.isosemi.com/datasets/wordlists.tgz: None -- [Errno -2] Name or service not known
```

```
$ wget http://www.isosemi.com/datasets/wordlists.tgz
--2017-03-24 16:11:50--  http://www.isosemi.com/datasets/wordlists.tgz
Resolving www.isosemi.com (www.isosemi.com)... 173.236.238.190
Connecting to www.isosemi.com (www.isosemi.com)|173.236.238.190|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.mythic-ai.comdatasets/wordlists.tgz [following]
--2017-03-24 16:11:50--  https://www.mythic-ai.comdatasets/wordlists.tgz
Resolving www.mythic-ai.comdatasets (www.mythic-ai.comdatasets)... failed: Name or service not known.
wget: unable to resolve host address 'www.mythic-ai.comdatasets'

$ wget https://www.mythic-ai.com/datasets/wordlists.tgz
--2017-03-24 16:12:59--  https://www.mythic-ai.com/datasets/wordlists.tgz
Resolving www.mythic-ai.com (www.mythic-ai.com)... 208.113.140.133
Connecting to www.mythic-ai.com (www.mythic-ai.com)|208.113.140.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-24 16:12:59 ERROR 404: Not Found.
```

Anyway, the suggested fix would change the behavior, because currently there are two RNNs with separate weights (for forward and backward), but if I understand correctly with `Bidirectional` layer there is only one set of weights.

**Comment by pasky** [comment]
The wordlist is mirrored at http://pasky.or.cz/datasets/wordlists.tgz
(please do not rely on this URL long term).

With Bidirectional(), the RNN should be instantiated twice so there
would still be two different sets of weights.

**Comment by gw0** [comment]
@pasky Sorry, but the URL does not work (404).

**Comment by pasky** [comment]
Sorry that meant to be http://pasky.or.cz/wordlists.tgz

**Comment by yjchun** [comment]
keras 1.2.2, tf 1.0, python 2.7

| epoch| old|2nd trial | fixed|2nd |
| --- | --- | --- | --- | --- |
| 10 | 0.048|0.125 | 0.054|0.049 |
| 15 | 0.029|0.081 | 0.039|0.034 |
| 20 | 0.023|0.061 | 0.033|0.024 |
| 25 | 0.011|0.032 | 0.018|0.014 |
