### ISSUE TITLE
Report number of floating point operations in model summary

### ISSUE THREAD

**Issue by aizvorski** [fchollet/keras#5625]
This is a feature request.  Could `model.summary()` print the number of floating point operations (FLOPs) as well as the number of parameters?  

From digging a bit through the code, this would require:
- [ ] adding `layer.count_flops()` (what would be the preferred name of this?) as an analog for `layer.count_params()`
- [ ] adding a call to that for each layer in `print_layer_summary(layer)` in layer_utils.py
- [ ] adding one more column to the output (and to positions)

I would be interested in doing a PR for this, but I could use a little bit of help with the first of these.  Could someone more familiar with keras under the hood do `count_flops()` for `Convolution2D`?

**Comment by MartinThoma** [comment]
For tensorflow, this could be helpful: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/tfprof#examine-the-number-of-floating-point-operations

**Comment by lygstate** [comment]
Does this support now?

**Comment by m516** [comment]
> 
> 
> For tensorflow, this could be helpful: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/tfprof#examine-the-number-of-floating-point-operations

I tried clicking the link, but it seems to be down. Is there an alternative link?
