### ISSUE TITLE
SeparableConv3D

### ISSUE THREAD

**Issue by alexvicegrab** [fchollet/keras#5639]
Hi,

This is more of a feature request or question than an issue, is there a straightforward way of implementing SeparableConv in 3D, as I'd like to try port the Xception architecture to medical images in 3D, and it may also be useful to people doing video.

Thank you,
Sasha

**Comment by alexvicegrab** [comment]
Looking deeper it looks like this needs to wait for the TF people to implement a separable_conv3d which requires a native 3D version of depthwise convolution. Difficult to find in the source code where this is implemented in 2D, any pointers would be appreciated!

**Comment by unrealwill** [comment]
Hello, 

Some pointers : 
https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L1036
https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L2777

**Comment by Danielhiversen** [comment]
@alexvicegrab did you found a solution to this?

**Comment by fchollet** [comment]
You can implement a slow version of `SeparableConv3D` using `SeparableConv2D` with constrained kernels. Depthwise convolution is a specific configuration of regular convolution.

Otherwise, you should wait for the available of a 3D sep conv op in TensorFlow.

**Comment by alexvicegrab** [comment]
Hi @unrealwill @fchollet, thanks for the pointers. Ended up leaving project for which this was needed, so won't contribute a solution myself this time.

**Comment by petoor** [comment]
Any idea of when (if?) This is being implemented. This issue is from 2017 and there still is no SeparableConv3D for tensorflow or keras.

**Comment by zx-lhb** [comment]
oh, here i am too is looking for  SeparableConv3D, surprising to find it has not been implemented in tensorflw2.11
