### ISSUE TITLE
How can I bulid an custom acyclic model?

### ISSUE THREAD

**Issue by tiagocalumbi** [fchollet/keras#5653]
I 'm beginning Keras and I'm trying to build a custom acyclic model. I need output returned for hidden layer.  I'm sending illustration image. [link](https://drive.google.com/file/u/1/d/0B0eJkvcHNZP4cDVZZ3M0U1pYaHM/view)
 
The model remember a RNN, but doesn't infinity states,  therefore the build it must be simple model 
Can someone help me? 

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

-

**Comment by unrealwill** [comment]
The image show a cyclic graph.

You can't do that in Keras.

**Comment by tiagocalumbi** [comment]
Thank a lot @unrealwill. Would you talk me what version of keras has support Graphs?

Regarding

**Comment by tiagocalumbi** [comment]
I found. Now I'm trying create model acyclic, but when I added the output layer to forward first dense layer, but throw error  [https://drive.google.com/file/u/1/d/0B0eJkvcHNZP4cDVZZ3M0U1pYaHM/view](link)

Can you help me?
