### ISSUE TITLE
How to change weights ordering of saved keras model

### ISSUE THREAD

**Issue by oak-tree** [fchollet/keras#5659]
Hey
Is it possible to train a model with theano dim ordering, save weights and then run it with tensorflow dim ordering?

Thanks!

**Comment by oak-tree** [comment]
Found [this](https://github.com/fchollet/keras/wiki/Converting-convolution-kernels-from-Theano-to-TensorFlow-and-vice-versa) looks promising I'm going to try it

**Comment by oak-tree** [comment]
OK I tried the method using `convert_kernel` as the link suggested.  I did the following:
1.I ran it when dim was for `theano` i.e `th` 
2. loaded the model from `th` file 
3.I saved it for `tf` convert_kernel(original_w, dim_ordering="tf") 
4.I change `keras` dim to `tf`
5. I tried to load the converted model again and got dim problem 

It seems that it is not enough to change the following layers  `['Convolution1D', 'Convolution2D', 'Convolution3D', 'AtrousConvolution2D']:`

The error I get is:

> ValueError: Cannot feed value of shape (1024, 256, 1, 1) for Tensor u'Placeholder_156:0', which has shape '(1, 1, 256, 1024)'

The is `fully connected` to `fully connected`. What am I missing while converting `th` to `tf` ?

Thanks!

**Comment by titu1994** [comment]
@oak-tree You can use my script `weight_conversion_theano.py` (https://github.com/titu1994/Keras-Classification-Models) to convert your model trained in theano with th dim ordering to : 

- Tensorflow with tf dim ordering (this is what you want)
- Tensorflow with th dim ordering (delete later)
- Theano with tf dim ordering (delete later)

Follow the instructions in the script and edit it wherever it mentions.

**Comment by oak-tree** [comment]
@titu1994 thanks i'll check it out. Can you explain to me why there is a need to shuffle the `fc` layers if there are more than 1 layer?

**Comment by oak-tree** [comment]
I found another issue. I have a complex model. Some kind of graph model. Iterating over model.layers only gets the basic `node` of graph` and does not show all graph layers.

**Comment by titu1994** [comment]
@oak-tree The script works for all types of models, it only needs the model to be built so as to handle tf and th dim ordering. 

Use a script to build the models, once with th dim ordering and another with tf dim ordering. Then just execute the script. It handles graph (functional api) models.

**Comment by hkvision** [comment]
Hi, is there a script or how can I modify the script to convert tf dim_ordering to th dim_ordering, ie in the reverse way as you do in the current script? Many thanks in advance!

**Comment by hkvision** [comment]
Oh, I found it https://github.com/titu1994/Keras-Classification-Models/blob/master/weight_convertion_tensorflow.py thanks!

**Comment by hkvision** [comment]
@titu1994 Hi, want to ask does this weight conversion guarantees the prediction performance? In other words, if I convert pre-trained weights in `tf` dim to `th` dim, is the model still well-trained? Thanks so much!
