### ISSUE TITLE
Setting Sepcific Input for a layer

### ISSUE THREAD

**Issue by NancyZxll** [fchollet/keras#566]
Hello All,
    As we all know that the Keras sequential model receive the input from the output of the previous layer.
   But now I want only some part of the output of the previous layer as the input of the current layer.
   My code is:

===========================================================================
model.add(Convolution2D(filter1Num, 1, filter1Row, filter1Col, border_mode='valid'))   #model layer0
model.add(Activation('tanh'))                                                          #model layer1
model.add(Dropout(0.5))                                                                #model layer2
get_features = model.layers[2].get_output(train=True) 

Layer2Inputs0=get_features[:,:,:,0:70]
model.add(Convolution2D(1,1,1,filter2Col,border_mode='valid'))  # L2Model layer0  3
Layer2Outputs0=model.layers[3].get_output(Layer2Inputs0)       # Define inputs here      

===========================================================================

However, the input of the second Conv layer is still the whole output of the former layer.

Then, I change model.layers[3].output(Layer2Inputs0=True) , an error comes:
TypeError: get_output() got an unexpected keyword argument 'Layer2Inputs0'

Could you tell me how to solve the problem? It is very urgent...:"( 
Thank you all!!

**Comment by NancyZxll** [comment]
I solved this problem by adding a layer in the core layer.
The layer only does the work of getting the revised input as its own output. For clarity, I call it ChangeInput layer here.
But to remember, when use this layer before any layers, you need to use any_layer.set_previous(ChangeInput).
Since I am now not so familiar with keras, I don't know the reason..

The definition of my ChangeInput layer is (I defined it in keras core.py):
class ChangeInput(Layer):
    def __init__(self, train):
        self.params = []
        self.regularizers = []
        self.constraints = []
        self.input = train
        self.output = train


when use it, you can :

==================================================================
model = Sequential()
model.Conv2D()
model.Activation()
model.Dropout()

Getoutput=Dropout().get_output()

Changeoutput = Getoutput[:,:,:,0:60]

model.ChangeInput(Changeoutput)
model.Conv2D()
model.layers[4].set_previous(ChangeInput(Changeoutput))
==================================================================

Please NOTE: you MUST use set_previous function to connect the input of the "Conv2D" to the output of the ChangeInput layer.
This is strange for me... As I think the input of the current layer should be the output of the previous layer. I don't know why the second Conv2D cannot get the output of the ChangeInput layer..

Anyone knows it?

**Comment by severusvinegar** [comment]
hi, I used your ChangeInput class. However,I can't connect the layers. it gives me error about "Exception: Layer is not connected. Did you forget to set "input_shape"?".Have you ever met this problem?Thanks.
