### ISSUE TITLE
Trying to implement model for conversion of 3d input to 2 class output.

### ISSUE THREAD

**Issue by meetkumar** [fchollet/keras#5662]
Hi,
I am trying to implement model which takes input shape (None,1,4) and I want to get just 2 class output. But i am facing an error. The code for the model is below:

model = Sequential()
    layers = [4, 100, 150, 200, 300, 2]
    model.add(Bidirectional(LSTM(output_dim=layers[1], input_dim=layers[0], return_sequences=True), input_shape=(1,4)))
    model.add(Dropout(0.2))
    model.add(Dense(output_dim=layers[2]))
    model.add(Dropout(0.2))
    model.add(Bidirectional(LSTM(layers[3],return_sequences = True, activation='sigmoid', inner_activation='hard_sigmoid')))
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(output_dim=layers[5]))
    model.add(Activation("sigmoid"))
    start = time.time()

### Traceback (most recent call last):
  File "Temp.py", line 424, in <module>
    run_network(model=None, data=None)
  File "Temp.py", line 311, in run_network
    batch_size=255, nb_epoch=epochs, validation_split= 0.2, shuffle=True, verbose=1, callbacks= [earlyStopping])
  File "/home/anaconda3/lib/python3.6/site-packages/keras/models.py", line 672, in fit
    initial_epoch=initial_epoch)
  File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1116, in fit
    batch_size=batch_size)
  File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1033, in _standardize_user_data
    exception_prefix='model target')
  File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 112, in standardize_input_data
    str(array.shape))
ValueError: Error when checking model target: expected activation_1 to have 2 dimensions, but got array with shape (106431, 1, 4)

Any help will be appreciated.. Thanks in advance.

**Comment by lomizandtyd** [comment]
"input_length" in first LSTM layer may be missing. 
It would be better if you use "input_shape" rather than "input_dim" and "input_length".

**Comment by lomizandtyd** [comment]
It would be better, if you use "input_shape" instead of "input_dim".

Maybe you just missed the "input_length" arg in the first layer.

**Comment by meetkumar** [comment]
Its showing me the same error. I changed "input_dim" to "input_length". Is there any specific input_length i should enter?

**Comment by lomizandtyd** [comment]
Aya, sorry, I'm wrong. 
-------
I just run your code in my server. 
Python 3.6 with Keras 1.2.2

```
import numpy as np

data_input = np.random.random((1000, 1, 4)) 
data_output = np.round(np.random.random((1000, 2)))

from keras.models import Sequential
from keras.layers import LSTM, Dense 
from keras.layers import Dropout, Flatten, Activation
from keras.layers import TimeDistributed, Bidirectional

model = Sequential()
layers = [4, 100, 150, 200, 300, 2]
model.add(Bidirectional(LSTM(output_dim=layers[1], input_dim=layers[0], return_sequences=True), input_shape=(1,4)))
model.add(Dropout(0.2))
model.add(Dense(output_dim=layers[2]))
model.add(Dropout(0.2))
model.add(Bidirectional(LSTM(layers[3],return_sequences = True, activation='sigmoid', inner_activation='hard_sigmoid')))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(output_dim=layers[5]))
model.add(Activation("sigmoid"))

model.compile(loss='categorical_crossentropy', optimizer='adam')

model.fit(data_input, data_output, batch_size=100, nb_epoch=10)
```
No bug reported. 

But, the second layer in your model is supposed to be written like this:
```
model.add(TimeDistributed(Dense(output_dim=layers[2])))
```
Make sure, your keras has updated to the latest version.
