### ISSUE TITLE
Problem loading old-trained models

### ISSUE THREAD

**Issue by bernardohenz** [fchollet/keras#5680]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hello,
a time ago I've trained an autoencoder and saved the trained model (by the time I was starting, so I`ve saved the json arch and weights). Now I've updated my keras and can`t load the previously trained model. It pops the error ```ValueError: epsilon must be at least 1e-5, got 9.99999974738e-06 ```, pointing to a batchnorm layer.

If you want to reproduce the issue you can simply execute the following code (with the [saved model](https://drive.google.com/file/d/0B4utINAEi8J8RTJmV25fbHFGTHM) (5.4mb):

```python
from keras.models import Model,Sequential
import numpy as np
from keras.models import model_from_json
import h5py

json_file = open('cnn1.json','r')
loaded_model_json = json_file.read()
json_file.close()
autoencoder = model_from_json(loaded_model_json)
# load weights into new model
autoencoder.load_weights("cnn1.h5")

```

**Comment by FiReTiTi** [comment]
I have exactly the same issue. Have you fixed it?

**Comment by bernardohenz** [comment]
No, I couldn't load old trained models =(

**Comment by FiReTiTi** [comment]
I've just found a solution. This error is generated by Theano, and it comes from twice the same test 
`if epsilon < 1e-5:`
`     raise ValueError("epsilon must be at least 1e-5, got %s" % str(epsilon))`

If you comment the raise line and replace it with `epsilon < 1e-5`, the models will load.
Just don't forget to remove these modifications after you have converted/resaved your models ;-)

**Comment by bernardohenz** [comment]
thank you very much

**Comment by 5ke** [comment]
downgrading theano to version 0.8.0 also works :-)

**Comment by jorgecarleitao** [comment]
What was the conclusion? is this a Theano issue or a Keras issue?

**Comment by FiReTiTi** [comment]
It's a Theano issue!

**Comment by 5ke** [comment]
Or is it? See https://github.com/fchollet/keras/issues/7255 

I get this problem when running Keras 2.0.5 together with Theano 0.9.0, and in that case it can be resolved by downgrading Theano to 0.8.2. This would suggest it's a Theano issue. 

However, when running Keras 1.0.5 together with Theano 0.9.0, the error doesn't occur...

**Comment by FiReTiTi** [comment]
If you take a look to my answer above, you'll see that's a Theano test that generates the error.

**Comment by 5ke** [comment]
Yes, it's theano that produces the error. The code documentation there states that this minimum is actually imposed by cuDNN (and should thefore be unavoidable, independent of which theano or keras one is running). 

However, this all happens in theano's batch_normalization_train in bn.py, and this function,  never gets called when using Keras 1.0.5. Actually, none of the functions in this older Keras' (completely different looking) theano_backend.py seem to have something to do with batch normalization.

So if anyone can shed some light on how batch normalization used to work from Keras, back when smaller epsilons apparently weren't an issue, I'd highly appreciate it. :-)

**Comment by jorgecarleitao** [comment]
Glad you reached an agreement. In that case, I suggest we close this because it is not on our side.
