### ISSUE TITLE
Any idea of adjusting task contributions in multi-task training

### ISSUE THREAD

**Issue by rex-yue-wu** [fchollet/keras#569]
Hi,

I am using **Graph** to train a multi-task CNN. Intutively, it makes sense to force training to focus on a main task, but I did not think this simple feature has already been supported. I guess I can introduce **task_weight** into the current Graph model, but please correct me if I am wrong. 

```python
class Graph(Model, containers.Graph):
    def compile(self, optimizer, loss, theano_mode=None):
        # loss is a dictionary mapping output name to loss functions
        ys = []
        ys_train = []
        ys_test = []
        weights = []
        train_loss = 0.
        test_loss = 0.
        for output_name in self.output_order:
            loss_fn = loss[output_name]
            output = self.outputs[output_name]
            y_train = output.get_output(True)
            y_test = output.get_output(False)
            y = T.zeros_like(y_test)
            ys.append(y)
            ys_train.append(y_train)
            ys_test.append(y_test)

            if hasattr(output, "get_output_mask"):
                mask = output.get_output_mask()
            else:
                mask = None

            weight = T.ones_like(y_test)
            weights.append(weight)
            weighted_loss = weighted_objective(objectives.get(loss_fn))
            # <-- begin of using task weight --> 
            train_loss += weighted_loss(y, y_train, weight, mask) *  task_weight
            test_loss += weighted_loss(y, y_test, weight, mask) * task_weight
            # <-- end of using task weight -->
        train_loss.name = 'train_loss'
        test_loss.name = 'test_loss'
```
I've also seen papers claiming it is important to stop different tasks at different iterations, but not sure how to support this feature in a systematic way ( sure I can manually stop training a model, remove the task I want to stop, and reload weights from previous trained model and lanch training on the rest of tasks again).

**Comment by fchollet** [comment]
Well, that's an easy one: you multiply each loss function by a scalar. Something like:

```python
from keras.objectives import mse
model.compile(optimizer='adam', loss={'output1': 0.2 * mse, 'ouput2':0.8 * mse})
```

**Comment by fchollet** [comment]
> stop different tasks at different iterations

You can write a callback to do this. "Stopping a task" is possible by setting to 0 the weight applied to its loss. You can make the weight re-settable during training simply by using a Theano shared scalar instead of a scalar.

**Comment by rex-yue-wu** [comment]
I followed your suggestions, but I got the following error
```python
  File "<ipython-input-1-1f2f5e768a83>", line 50, in <module>
    model.compile(optimizer='adam', loss={'output1': 0.2 * mse, 'ouput2':0.8 * mse})

TypeError: unsupported operand type(s) for *: 'float' and 'function'
```

**Comment by billzhengC** [comment]
I guess a parameter like "weighted_loss" could be added to graph.compile, which makes it easier to adjust contributions.

**Comment by fchollet** [comment]
@rex-yue-wu then just create a wrapper function f x: 0.2 * mse(x)...
