### ISSUE TITLE
Monte Carlo estimation of KL divergence differs a lot from the analytical result

### ISSUE THREAD

**Issue by sbaurdlp** [fchollet/keras#5691]
Hello everybody, 

I'm currently trying to implement a VAE with several layers of stochastic variables. As the KL divergence is not tractable, I'm trying to approximate it with Monte Carlo method. As it didn't work at all, I tried to compute it with only one layer, and it doesn't work : I can verify it by comparing the Monte Carlo estimation with the analytical value (see for example [Tutorial on VAE](https://arxiv.org/abs/1606.05908))

So i defined two functions, one computing the analytical value and the other one a Monte Carlo estimate.
The base code is the [tutorial from Keras](https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py), the lines 22 to 49 being modified

```
n_sample = 500
# utils
def log_stdnormal(x):
    """log density d'une loi normale centree"""
    c = - 0.5 * math.log(2*math.pi)
    result = c - K.square(x) / 2
    return result


def log_normal2(x, mean, log_var):
    """log density d'une loi normale de moyenne mean et de variance exp(log_var)"""
    c = - 0.5 * math.log(2*math.pi)
    result = c - log_var/2 - K.square(x - mean) / (2 * K.exp(log_var) + 1e-8)
    return result
# input
vae_input = Input(shape=(original_dim,nchar), batch_shape=(batch_size,original_dim,nchar))

z_mean_0, z_log_var_0 = encoder(vae_input)
eps0 = Lambda(sample_eps, name='sample_eps0')([z_mean_0, z_log_var_0])
print(eps0)
z0 = Lambda(sample_z, name='sample_z0')([z_mean_0, z_log_var_0, eps0])

x_decoded_mean = generator(z0)

def kl_cost(args):
    z_mean, z_log_var = args
    return - 0.5 * K.sum(1 + z_log_var - K.square(z_mean) - K.exp(z_log_var))
kl_ = Lambda(kl_cost)([z_mean_0, z_log_var_0])
kl_model = Model(vae_input, kl_)

def monte_carlo_kl_div(args):
    mean, log_var = args
    for k in range(n_sample):
        epsilon = K.random_normal(shape=(batch_size, latent_dim), mean=0.,
                              std=epsilon_std)
        z = mean + K.exp(log_var / 2) * epsilon
        try:
            loss += K.sum(log_normal2(z, mean, log_var) - log_stdnormal(z) , -1)
        except NameError:
            loss = K.sum(log_normal2(z, mean, log_var) - log_stdnormal(z) , -1)
    return loss / n_sample

carlo = Lambda(monte_carlo_kl_div)([z_mean_0, z_log_var_0])
carlo_model = Model(vae_input, carlo)

vae = Model(vae_input, x_decoded_mean)
```

When evaluating `carlo_model` on a test sample, I get negative values. Why ? It should be approximately the same as the output of `kl_model`

**Comment by talpay** [comment]
Have you tried using the KL implementation provided in losses/objectives.py? Some missing details such as clipping might have an impact.

**Comment by around1991** [comment]
How many Monte Carlo samples are you taking? MC estimates of the KL are quite high variance, you might need 100 samples or so to get a reasonable approximation. It's not too difficult though, because once you have a sample you just have the calculate the log-density ratio which is not very computationally taxing.

**Comment by sbaurdlp** [comment]
Hi, thanks for your answers
I finally made it work, and the problem seemed to be purely numerical, as @talpay pointed out

Indeed, I was generating logvar in a very narrow range (about [-1e-3, 1e3]), and when I switched to generating std instead (by using a softplus activation layer), I got values of about log(2), which made it work.

I'm not sure this was the reason but I can't think of anything else
Using MC estimation with 50 samples instead of analytical formula caused the model to have the same train/test performance, with a 28% training speed increase
