### ISSUE TITLE
How can you return # params from a custom layer?

### ISSUE THREAD

**Issue by Lif3line** [fchollet/keras#5697]
I'm writing a custom layer in the standard format:

``` class customLayer(Layer):
    def __init__(self):
        # code
        super(customLayer, self).__init__()

    def build(self, input_shape):
         # code

    def get_output_shape_for(self, input_shape):
         # code
         return tuple(shape)

    def call(self, x, mask=None):
        # code
        return output
```

The layer itself works fine however I was wondering how I might pipe out the number of parameters to model.summary(). I had a look at the source but I'm having trouble seeing how it actually pulls in the parameter numbers from a layer. I can see the flow is something like count_total_params <- count_params <- layer.weights?

Any help would be greatly appreciated.

**Comment by Xls1994** [comment]
In the class Layer, it has a function named count_params, which returns the total number of parameters.
The function like this:
![default](https://cloud.githubusercontent.com/assets/18399421/23888341/75e3e3fa-08c2-11e7-85ce-dea41ad3a3c1.png)


I think you should write the attribute 'trainable_weights' for you layer, then you may pipe out the parameters. 
Gook luck for you!

**Comment by Lif3line** [comment]
Ah don't know how I managed to miss that; thank you very much.

It would appear if using `.add_weight` in a layer this would all work out by itself. In my case I was implementing an abstraction for splitting input to a layer then merging back together. Therefore I found it useful to simply override the `count_params()` function:
``` 
def count_params(self):
    return 4
```

Thanks again!
