### ISSUE TITLE
The problem of GPU for keras using tensorflow backend ?

### ISSUE THREAD

**Issue by litingsjj** [fchollet/keras#5712]
When I using keras by theano,

import keras
Using Theano backend.
Using gpu device 0: GeForce GTX 1080 (CNMeM is enabled with initial size: 10.0% of memory, cuDNN 5105)
/home/lt/anaconda3/lib/python3.5/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)

The GPU can work well!
But now I switch tensorflow, 

import keras
Using TensorFlow backend.(Just it !)

and when I run the demo, GPU doesn't work! Is keras can use GPU automatically when using tensorflow backend?

**Comment by patyork** [comment]
TensorFlow has a CPU version, and a GPU version. From the sounds of it, you've installed the CPU version.

**Comment by nouiz** [comment]
Update Theano to 0.9rc4. it will support that cudnn version and be faster.

**Comment by xiaoleihuang** [comment]
I agree with @patyork 's idea. Because the Theano can find the cuda library. If you installed the tensorflow-gpu version, the terminal should have shown it found local cudnn library successfully.

**Comment by Dahlasam** [comment]
I faced the same issue first. I have a fresh Ubuntu 4.8.0-36-generic #36~16.04.1-Ubuntu SMP x86_64 installation. I setup conda environment with Python3 for Keras + Tensorflow and then first I mistakenly installed 'tensorflow' (CPU version). The python code works using Tensorflow backend, but GPU is not (of course) used. 
Then I installed tensorflow-gpu by copy-pasting "pip3 install --upgrade tensorflow-gpu" from Tensorflow pages. This didn't work and I needed to install tensorflow-gpu with "pip install tendorflow-gpu". Then GPU is activated as expected:
```
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3517] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
```

**Comment by build2create** [comment]
@Dahlasam Just a small typo tensorflow instead of tendorflow right?

**Comment by Dahlasam** [comment]
Sorry about the typo - that should have been **tensorflow** for sure.

**Comment by kartiksubodh** [comment]
@Dahlasam  did you uninstall the cpu version of tensorflow before installing the tensorflow-gpu ?

**Comment by Flock1** [comment]
Hey, 
I don't have tensorflow installed but tf-gpu and keras-gpu through anaconda. Why is keras still using CPU?

**Comment by ZER-0-NE** [comment]
Did you find anything uselful? @Flock1
