### ISSUE TITLE
theano.gradient.DisconnectedInputError when setting a specific input to the Conv layer

### ISSUE THREAD

**Issue by NancyZxll** [fchollet/keras#572]
Hello all, 
     I defined a layer to set a specific input to a certain layer. However, I came across a problem.
    My code is:

========================================================================
Layer2Inputs0=get_features[:,:,:,0:int(layer2Len-filter2Col-aaQuaInt[0])]

model.add(Convolution2D(1,4,1,filter2Col,border_mode='valid')) # model layer3
model.layers[3].set_previous(GetSomeOutput(Layer2Inputs0))
model.add(Activation('tanh'))                                  # model layer4
model.add(Dropout(0.5))                                        # model layer5

Layer2Outputs0=model.layers[5].get_output(Layer2Inputs0)
        

Layer2Inputs1=get_features[:,:,:,int(aaQuaInt[0]+filter2Col):]
        
model.add(GetSomeOutput(Layer2Inputs0))
model.add(Convolution2D(1,1,1,filter2Col,border_mode='valid'))  # model layer6
model.layers[6].set_previous(GetSomeOutput(Layer2Inputs0))
==================================================================

The error is:
****************************************************
raise DisconnectedInputError(message)
theano.gradient.DisconnectedInputError: grad method was asked to compute the gradient with respect to a variable that is not part of the computational graph of the cost, or is used only by a non-differentiable operator: <TensorType(float64, 4D)>
******************************************************************

But the error disapeared when I delete the last line:
model.layers[6].set_previous(GetSomeOutput(Layer2Inputs0))

Anyone has any ideas?

**Comment by fchollet** [comment]
You are definitely not supposed to do that. 

Look into the Graph model instead: http://keras.io/models/#graph
