### ISSUE TITLE
Keras Callback Learning Rate

### ISSUE THREAD

**Issue by KiranBaktha** [fchollet/keras#5724]
Hi guys,
I am trying to change the learning rate at the third epoch in my keras model. I am trying to implement the solution posed by @EderSantana on Issue #888 

     def scheduler(epoch):
        if epoch == 5:
        model.lr.set_value(.02)
    return model.lr.get_value()

     change_lr = LearningRateScheduler(scheduler)

     model.fit(x_embed, y, nb_epoch=1, batch_size = batch_size, show_accuracy=True,
       callbacks=[chage_lr])

However, I get the following error:

           'Variable' object has no attribute 'get_value'
for the last line in scheduler function.  Even " model.optimizer.lr.get_value()"  does not seem to work for me. 

Any help would be appreciated. Thanks in advance.

**Comment by abhaikollara** [comment]
Could you mention Keras version and the backend you're using

**Comment by KiranBaktha** [comment]
Hi, I am using Keras 1.2.2 and TensorFlow backend

**Comment by abhaikollara** [comment]
I don't know if it's a bug, the `Variable` object in TF (`model.optimzer.lr` in your case) does not in fact have a `get_value` or a `set_value` method of their own. The `get_value` seems to be a separate function in keras backend taking a variable object as argument and `set_value` taking  a variable object and the value as argument.

So try this instead

```python
import backend as K
def scheduler(epoch):
    if epoch == 5:
    k.set_value(model.optimizer.lr, .02)
return K.get_value(model.optimizer.lr)
```

The theano version without any glitch because Theano variables have `get_value` and `set_value` methods of their own.

**Comment by ThisRay** [comment]
If it is wrong, you can try: `import keras.backend as K`

**Comment by philipperemy** [comment]
https://keras.io/callbacks/

`ReduceLROnPlateau`

**Comment by hridbiswas** [comment]
hello evryone, I am trying the get the weight matrix, but im getting some error here
autoencoder.layers[3].kernel.get_value()
-----------------
-----------------
AttributeError: 'Variable' object has no attribute 'get_value'

im using keras(backend tensorflow).

Can someone please tell me whets wrong im doing?

**Comment by casperdcl** [comment]
thanks to #8865 this is now much easier:

```python
def lr_sched(epoch, current_lr):
    """linear decay to 0 over 1000 epochs"""
    return current_lr * (1000 - epoch) / 1000

model.fit(..., callbacks=[keras.callbacks.LearningRateScheduler(lr_sched)])
```

to answer the original post:

```python
def lr_sched(epoch, lr):
    """set lr=0.02 at epoch=5 as per original post"""
    return 0.02 if epoch == 5 else lr
```
