### ISSUE TITLE
Lambda layers and merge_mode='list' for Graph

### ISSUE THREAD

**Issue by EderSantana** [fchollet/keras#576]
I've been doing some local experiments and there is no problem to have a layer returning a list at `get_output` as long as the next layer knows how to handle it. Also, I created a Lambda layer that is simply:

```python
class Lambda(MaskedLayer):
    def __init__(self, func, params=None):
        super(Lambda, self).__init__()
        self.func = func
        if params is not None:
             self.params=params
    def get_output(self, train=False):
        X = self.get_input(train)
        return self.func(X)
```
That function can be used to slice the list and communicate with other regular layers that expect `theano.tensors` as input for example. 

I believe that Lambda layers together with a new `Graph` `merge_mode='list'` option would make Keras even more expressive. By `merge_mode='list'` I simply mean creating a list with all the `inputs`, letting the next layer handle its pieces. 

--- Example ---
I'm writing a Spatial Transformer Network using Keras. Right now there is an example at my `edersantana/seya/examples` repo. That layer does the following:
* gets a localization network as parameter
* gets an input
* pass input to localization network and gets its output
* return the input processed with the localization network's output

If that Spatial transformer layer could receive a list as its `merge_mode`, the localization part could be an independent node in the graph and its output could be used somewhere else. It is not always easy to use `merge_mode='concat'` and slice the resulting tensor since the proper shapes would have to be passed to the next layer, cluttering the code.

What do you guys think?

**Comment by fchollet** [comment]
> there is no problem to have a layer returning a list at get_output as long as the next layer knows how to handle it.

We are trying to standardize multi-input / multi-output layers & containers via input dictionaries rather than lists. The explicitness of dictionaries makes it easier to debug, and more flexible (you don't depend on a fixed input order). It also means we will have the same connection API for multi-io layers and for Graphs (as we should).

Take a look at: https://github.com/fchollet/keras/blob/master/keras/layers/containers.py#L129-L136 
which implements multi-io layer support in the Graph container. 

Thoughts?

**Comment by EderSantana** [comment]
I didn't know about that before. I'll check it out and post my thoughts later. Thanks!!!

**Comment by fchollet** [comment]
Also worth noting that Graph layers that have multiple inputs and outputs already work as multi-io layers. This means that for example you can write a graph that maps `n` inputs to `k` outputs, then connect it to a graph that maps `k` inputs to `p` outputs, etc.

It's completely possible to develop a new layer (not graph-based) that does multi-io, it would simply need to respect the conventions set by `Graph` for the methods `layer.get_input`, `layer.get_output`, `layer.set_previous`, and it would need to expose the appropriate values in `layer.nb_input` and `layer.nb_output`.

**Comment by EderSantana** [comment]
I just read the `connection_map` you mentioned. Do you have an example code of how to use them?

**Comment by fchollet** [comment]
Not yet. `connection_map` is simply a dictionary mapping output names from the previous layers to input names to the next layer.

**Comment by EderSantana** [comment]
I got that, but how are we supposed to use it? Is the `model.Graph` passing a `connection_map` to it already?

**Comment by antonmbk** [comment]
Ok, So I have just taken a peak at the Layer class.   I guess my main question is back to what I asked in another thread: why is 'input' defined as a class member for some layers yet is the output of the previous layer for others? Is this a legacy/compatibility thing?? Wouldn't a standard of 'input' being a Layer class member for every layer (no matter what kind of layer it is) be considerably more flexible?  Thoughts??

**Comment by fchollet** [comment]
> why is 'input' defined as a class member for some layers yet is the output of the previous layer for others? Is this a legacy/compatibility thing??

They are two quite different things. Let me explain slowly.

The input to a layer can be either the output of the previous layer, or, if there is no previous layer, a user-provided numpy array. 

The former is accessed via `.get_input(train=False)`. Note that two behaviors are supported, train mode and test mode.

In the latter case, we still need to tell Theano what input type is expected: `matrix`, `imatrix`, `tensor3`, etc. This information is provided by the `input` attribute. This is only done for layers for which such information is relevant; many Keras layers are shape-agnostic and do not have an `input` attribute.

**Comment by fchollet** [comment]
> I got that, but how are we supposed to use it? Is the model.Graph passing a connection_map to it already?

You use `connection_map` when connecting the layer, i.e. in `layer.set_previous`. 

One can imagine that the `add` method of `Sequential` (or `add_node` in Graph) will in the future support an optional `connection_map` argument to use when adding multi-io layers.

**Comment by jfsantos** [comment]
Did anyone decide on how to do the "list merge" @EderSantana was proposing? Currently we have a single `Merge` layer that performs an arbitrary set of operations, so one cannot create other different Merge subclasses for doing fancier stuff (like @EderSantana example here). This is especially limiting since you cannot merge two layer outputs in `Graph` without using the "official" `Merge` layer. Maybe it would be better to support user-provided `Merge` classes instead of expanding `Merge` to have a lot of `Merge` modes, or come up with a way of passing a merging function as a parameter to `Merge`.

**Comment by EderSantana** [comment]
@jfsantos I PRed `merge_mode="join"` check it out https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L236-L243

**Comment by EderSantana** [comment]
I'm closing this issue. @jfsantos, pls open a new one with your idea of custom `Merge` to continue the discussion if you will.
