### ISSUE TITLE
deep-learning-models :  ImportError: cannot import name '_obtain_input_shape'

### ISSUE THREAD

**Issue by apiszcz** [fchollet/keras#5760]
Keras 1.2.2

  File "resnet50.py", line 39, in <module>
    from keras.applications.imagenet_utils import _obtain_input_shape
ImportError: cannot import name '_obtain_input_shape'

**Comment by rola93** [comment]
I'm having same issue, I think thats because I'm running code implemented over an old keras version. How can I fix it? where do I found `_obtain_input_shape`?

Thanks
