### ISSUE TITLE
Proposal: ImageDataGenerator.flow_from_list_of_files

### ISSUE THREAD

**Issue by leereeves** [fchollet/keras#5763]
I'm working with some images which are all contained in a single folder, with classes distinguished by a part of the file name.

Naturally, I could restructure the data to match flow_from_directory (a really convenient function) but I don't control the original source of the data so I'd rather use it in its original form.

And I think this might come up again, so I'm working on a method flow_from_list_of_files that works like flow_from_directory, except that it loads files from a list of `(path, class)` pairs instead of a fixed directory structure.

And I was wondering if this is something that might be welcome as a feature of Keras, and if I should submit a PR when it's finished. 

(And if so, what would be the preferred argument: a list of file paths, a generator, or ... ?)

**Comment by joelthchao** [comment]
I think it's possible to submit a PR, though writing a generator with a customized rule can achieve this purpose easily.

**Comment by leereeves** [comment]
Yep, it's actually really easy as flow_from_directory already builds a list of files. Very little new code is required.

This would just split flow_from_directory into two steps so either type of data structure could be used without understanding the internals of Keras.

**Comment by joelthchao** [comment]
I am not stopping you to give a PR. Anything helps people to use Keras more easily is always welcome.
