### ISSUE TITLE
Kearas 1.2.2 - load_model() is not working corectly

### ISSUE THREAD

**Issue by godenhoden** [fchollet/keras#5764]
- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps
**Keras version 1.2.2**

- [ x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).
**Tensorflow version 1.0.1**

- [x ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps
**i do not use Theano**

- [ x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).
https://gist.github.com/godenhoden/bcca449b4702b46da1feff7e6de8a05d

Problem:
there seems to be an error with either keras model.save methode or load_model() methode. It is only possible to load the latest fitted model. For more details See example script. https://gist.github.com/godenhoden/bcca449b4702b46da1feff7e6de8a05d 

Additional infos:
keras.json ={
    "image_dim_ordering": "tf",
    "backend": "tensorflow",
    "epsilon": 1e-07,
    "floatx": "float32"
}
Os : Windows 10 pro 64 bit
Keras backend: Tensorflow
Running mode : CPU only

**Comment by abhaikollara** [comment]
Get rid of the `optimizer=Adam()` in line 50. Use `optimizer='adam'` as the argument for `model.compile`. I think the problem is that both your models are being saved using the same optimizer object, although it's suited for only the weights of latest fitted model

**Comment by godenhoden** [comment]
@abhaikollara Thx for your fast response. Your suggestion seems to work, but how do i use an non default Adam optimizer for multiplie models? like (lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)

**Comment by abhaikollara** [comment]
@godenhoden Create your optimizer inside the loop, seems to be a much better solution than what I originally mentioned, it should allow you to create optimizers with non-default parameters.
