### ISSUE TITLE
Why explicitly depend on tensorflow on Keras 2.0?

### ISSUE THREAD

**Issue by adamcavendish** [fchollet/keras#5766]
It looks like we have to install tensorflow (CPU) 1.0.1 when upgrading to keras 2.0. However I installed the GPU version, is there any way to fix this?

**Comment by adamcavendish** [comment]
Found one work-around:

`pip install --upgrade --no-deps keras` installs keras without dependencies.

Hope it helps.

**Comment by leriomaggio** [comment]
@adamcavendish What do you mean?
AFAIK, If you have `tensor flow-gpu` installed, the dependency should already be satisfied...

**Comment by adamcavendish** [comment]
The problem is that it was not satisfied, and downloads `tensorflow` (aka. the cpu version) for me.

**Comment by fchollet** [comment]
If you already have TF installed, use the pip flag `--no-deps`.

This seems like more of a TF issue than a Keras issue. On the Keras side,
it is reasonable to list `tensorflow` as a dependency.

**Comment by VaibhavSaini1996** [comment]
Sir, does by installing keras without its dependencies work?
i mean that will it use the conda installed tensorflow(1.2.0) or will it require tensorflow(1.0.1). i am trying to set an environment in anaconda for deep learning.
i  performed following step:
1. installed anaconda
2. installed all nvidia reuirements.
3. installed tensorlow from github repo
4. installed bazel to build tensorflow.
- At this step when i tried to use tensorflow it worked fine without keras.
5. conda install keras with all dependecied( i.e. tensorflow(1.0.1)etc).
- now when i import  keras it just says using tensorflow as backend.
What am i doing wrong? please help

**Comment by Joian12** [comment]
I only want keras but when i try to run keras its always tels me that using tensorflow backend and i didnt even installed tensorflow.
