### ISSUE TITLE
Windows is not stable to run GPU Keras Tensorflow? & Memory Issue

### ISSUE THREAD

**Issue by xiaoleihuang** [fchollet/keras#5769]
I run the Keras with Tensorflow GPU backend. 
I run two programs in two Jupyter notebooks. I tried to run two programs one after another without shutting down any notebooks, the PC stop running, thus I have to restart PC. 
If I shutdown 1st notebook and run the other one, it won't have the same problem.
I tried the following code to release memory, but the problem is still there unless I shutdown the notebook.
`from keras import backend as K
K.clear_session()`

So two questions:

1. Is that due to unstable status of Windows?
2. How to clean the memory of both Keras and Tensorflow? It seems both parameters and models take a lot of memories.

**Comment by yosoufe** [comment]
I am very new, but this is my understandings:
In ubuntu, with the `nvidia-smi`command I can list the processes on GPU and their memory consumption. One instances of Keras (or TF) is getting almost all free memory on GPU. So I guess if you keep it running on jupyter notebook, No memory would left for the second instance.
