### ISSUE TITLE
Docs have not been updated

### ISSUE THREAD

**Issue by abhaikollara** [fchollet/keras#5770]
The documentation pages for [convolutional layers](https://keras.io/layers/convolutional/), [locally connected layers](https://keras.io/layers/local/) are not updated to the new API.

**Comment by maxcan** [comment]
Furthermore, there's no indication in the docs which version they pertain to or an obvious way to get docs for specific versions.

A selector such as on http://www.material-ui.com/#/ would be very very helpful.  
![image](https://cloud.githubusercontent.com/assets/646732/23926434/76257176-08d1-11e7-8be5-2e8cbd68efaa.png)

**Comment by fchollet** [comment]
If someone wants to set up versioned docs, go for it. I have no time for it myself. Maybe Mkdocs already supports it?

**Comment by bstriner** [comment]
Saw this on the forums. Might be worth trying but seems experimental:

https://github.com/mkdocs/mkdocs/issues/193
http://d0ugal.github.io/mkdocs-versioned/

**Comment by abhaikollara** [comment]
@fchollet The original issue I mentioned still exists, though when I build the docs locally I get updated docs.
