### ISSUE TITLE
Return tensor of last states in RNN

### ISSUE THREAD

**Issue by duguyue100** [fchollet/keras#5771]
Hi, all,

Sorry it's not so obvious for the title.

So, there is a special function I need in Recurrent Networks. Typically, if I selected `return_sequences`, then all hidden states will be returned, which is good typically. Or if I set it to `False`, then only the last state will be returned.

However, I need a special format of `return_sequences` where I want all elements in the returned tensor be the last state. More precisely,

Typically, we may have output sequence tensor as:

```
[h_t-2, h_t-1, h_t]
```

Now, I need

```
[h_t, h_t, h_t]
```

Is this even doable? I tried to use `expand_dims` and `repeat_elements` API, but then Keras told me the result is not a Keras tensor. Do anyone have some ideas? Do you think I should write a layer for this purpose? I thought about changing `rnn` API, but it seems too much effort.

**Comment by joelthchao** [comment]
I think [RepeatVector](https://keras.io/layers/core/#repeatvector) can solve your problem, please see the example inside. The only problem is that you will need to know how many time to repeat.

> I tried to use expand_dims and repeat_elements API, but then Keras told me the result is not a Keras tensor.

You need to use `Lambda` layer to wrap these backend function. e.g.:
```python
def repeat(x):
    return K.repeat_elements(x, 3, -1)
x = Lambda(repeat) (x)
```

**Comment by duguyue100** [comment]
Emmmm.... interesting... I will try it out! Thanks!
