### ISSUE TITLE
setting up keras on GPU as instructed causes the error 

### ISSUE THREAD

**Issue by wenouyang** [fchollet/keras#5772]
I have been following the instruction for[ setting up keras on GPU ](https://keras.io/getting-started/faq/#how-can-i-run-keras-on-gpu). This is what I did as suggested by method 3

```
import theano
theano.config.device = 'gpu'
theano.config.floatX = 'float32'
```

However, I get the following error message

> Using Theano backend.
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    theano.config.device = 'gpu'
  File "/devl/geophys/dplearn/tensorflow/tf_0.12/lib/python3.4/site-packages/theano/configparser.py", line 338, in __set__
    "Can't change the value of this config parameter "
Exception: Can't change the value of this config parameter after initialization!

**Comment by kirk86** [comment]
@wenouyang have you tried putting the configuration in .theanorc. I'm not quite sure but should it be `gpu` or `gpu`?

**Comment by wenouyang** [comment]
Hi krik86, I have just created .theanorc under my home directory, looks like it removes the previous error message, and running the program generates the following warning message

> python train.py                                                                        
Using Theano backend.                                                                                                     
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:                                                                          
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29                                                        

ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.

**Comment by kirk86** [comment]
@wenouyang I think you should provide the paths to cuda and nvcc in .theanorc

something like this. Make sure to change paths accordingly

```
[cuda]
root = /usr/local/cuda

[nvcc]
flags = -I/usr/local/cuda/include -L/usr/local/cuda/lib
compiler_bindir = /usr/bin
fastmath = True
```

**Comment by wenouyang** [comment]
Hi kirk86, thanks for your reply. Would you mind to let me know which command to let me identify root for cuda? and where to find compiler_bindir? Thanks.

**Comment by kirk86** [comment]
@wenouyang if you have a gpu on your computer you should have installed cuda. if not then you should if you wanna use your gpu.

Assuming that you have already installed cuda correctly on your pc. Then if you execute
`nvcc --version` you should see some output regarding your gpu and cuda version.

If you don't get any results then it means that you either haven't installed cuda or your installation was faulty. Try to uninstall and reinstall cuda.

If you get results from the above command then you could easily locate cuda if you are on linux or OS X by using one of the below.
 
```
which cuda
locate cuda
```

**Comment by wenouyang** [comment]
Hi kirk86, here is the result of running these command lines. Are there any information can be inferred from these results. It seems to me that `nvcc` and `which cuda` indicate that there is no cuda installed. However, `locate cuda` returns some information instead.

> nvcc --version
-bash: nvcc: command not found

> which cuda
/usr/bin/which: no cuda in (/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/opt/pec:/util/bin:/chap/app-run-shell:/chap/util/prod/sbin)

> ocate cuda
/cm/local/apps/cuda
/cm/local/apps/cuda-driver
/etc/modprobe.d/cuda-driver-blacklist.conf
/etc/rc.d/init.d/cuda-driver
/etc/rc.d/rc0.d/K86cuda-driver
/etc/rc.d/rc1.d/K86cuda-driver
/etc/rc.d/rc2.d/S10cuda-driver
/etc/rc.d/rc3.d/S10cuda-driver
/etc/rc.d/rc4.d/S10cuda-driver
/etc/rc.d/rc5.d/S10cuda-driver
/etc/rc.d/rc6.d/K86cuda-driver
/opt/mellanox/hcoll/include/ocoms/datatype/ocoms_datatype_cuda.h
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/config/m4/acinclude.cuda.m4
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/config/m4/acinclude.cudartwrap.m4
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/vt_cuda_driver_api.h
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/vt_cuda_runtime_api.h
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/vt_cudart.c
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/vt_cudartwrap.c
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/vt_cudartwrap.h
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/.deps/libvt_hyb_la-vt_cudart.Plo
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/.deps/libvt_hyb_la-vt_cudartwrap.Plo
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/.deps/libvt_java_la-vt_cudart.Plo
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/.deps/libvt_java_la-vt_cudartwrap.Plo
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/.deps/libvt_mpi_la-vt_cudart.Plo
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/.deps/libvt_mpi_la-vt_cudartwrap.Plo
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/.deps/libvt_mt_la-vt_cudart.Plo
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/.deps/libvt_mt_la-vt_cudartwrap.Plo
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/.deps/vt_cudart.Plo
/sysadm/openmpi-1.6.4/ompi/contrib/vt/vt/vtlib/.deps/vt_cudartwrap.Plo
/sysadm/openmpi-1.6.4/opal/mca/hwloc/hwloc132/hwloc/include/hwloc/cuda.h
/sysadm/openmpi-1.6.4/opal/mca/hwloc/hwloc132/hwloc/include/hwloc/cudart.h
/usr/include/linux/cuda.h
/usr/lib64/libicudata.so.42
/usr/lib64/libicudata.so.42.1
/usr/share/gtksourceview-2.0/language-specs/cuda.lang
/usr/share/vim/vim72/syntax/cuda.vim
/usr/src/kernels/2.6.32-358.23.2.el6.x86_64/include/linux/cuda.h
/usr/src/kernels/2.6.32-504.16.2.el6.x86_64.debug/include/linux/cuda.h

**Comment by kirk86** [comment]
@wenouyang it seems that you don't have cuda installed. Make sure you have a gpu on your computer preferably an nvidia one. Then install cuda. If you do a google search you'll find millions of records indicating how to install cuda.

**Comment by wenouyang** [comment]
Thanks.
