### ISSUE TITLE
Installing keras makes tensorflow can't find GPU

### ISSUE THREAD

**Issue by ThisRay** [fchollet/keras#5776]
I have used keras + tensorflow-gpu in my old computer, it's very ok. (I forget the tensorflow version) 

I install keras with tensorflow-gpu (version 1.0.1) in my new computer, and before install keras, tensorflow can find my GPU. But after install keras, tensorflow only can find CPU.
(use $ pip3 install keras)

I use these code to check GPU:
```
from tensorflow.python.client import device_lib
device_lib.list_local_devices() 
```
```
$ nvidia-smi
```

And I tried to install keras from source ($ python setup.py install), it would have some error and install fail.

```
...
Installed /home/thisray/keras-test/lib/python3.5/site-packages/Keras-2.0.0-py3.5.egg
Processing dependencies for Keras==2.0.0
Searching for tensorflow
Reading https://pypi.python.org/simple/tensorflow/
No local packages or working download links found for tensorflow
error: Could not find suitable distribution for Requirement.parse('tensorflow')
```

Is this problem about version ?

thanks

**Comment by variac** [comment]
Yeah, currently when you install Keras using pip or pip3 it blows off existing TF and installs the default, non-GPU version. It'd be great if there was a flag to not touch existing TF.

The workaround is to uninstall TF after installing Keras, and then installing the GPU version using pip or pip3 depending on your preferred python version. Not very elegant, but you gotta do what you gotta do.

**Comment by variac** [comment]
Argument in favor of more sophisticated handling: some folks use TF they have compiled themselves for their native machine architecture to speed up things like on-CPU image processing. For them to be reset to default TF when they upgrade is a bit of a nuisance.

**Comment by ThisRay** [comment]
Thanks for your explanation. 
After: install tensorflow -> install keras -> uninstall tensorflow -> install tensorflow
and it works! Thanks a lot!

**Comment by adamcavendish** [comment]
See https://github.com/fchollet/keras/issues/5766 . Use `--no-deps`

**Comment by pierluigiferrari** [comment]
I have the same problem, ever since I updated to Keras 2.0.2 (I'm using the Tensorflow backend) it's no longer using the GPU for training. I followed the workaround suggested by @variac and uninstalled tensorflow entirely, then installed tensorflow-gpu again, but I'm still having the same issue, the CPU is used :/

**Comment by holianh** [comment]
Thank you very much!
It worked for me

`conda create -n ta  anaconda python
source activate ta
pip install tensorflow-gpu
pip install pillow h5py keras
pip uninstall tensorflow
pip install tensorflow-gpu
python
import keras.backend as K;[x.name for x in K.get_session().list_devices()]

git clone https://github.com/fchollet/keras.git
cd keras/examples
python mnist_cnn.py`
