### ISSUE TITLE
how install keras2.0.0 using anacoda

### ISSUE THREAD

**Issue by IvyGongoogle** [fchollet/keras#5778]
hello，I use anaconda2 in `/usr/xxx/local/anaconda2`， How to install the newest keras2.0.0 using anaconda?
thankyou in advance!

**Comment by fchollet** [comment]
You can install Keras via pip, which I believe should be all that anaconda
needs

**Comment by IvyGongoogle** [comment]
@fchollet Thankyou for your reply. Yes, I can install keras-2.0.0 via `pip install keras`. But it will just install `keras: 1.1.1-py27_0` rather than keras-2.0.0 via `pip install keras`.  Why?

**Comment by ptrblck** [comment]
@IvyGongoogle Try `pip install keras --upgrade`.

**Comment by kevinchangwang** [comment]
The other way to install the package is using `conda skeleton pypi`. The full guide to making a conda package is [here](https://conda.io/docs/build_tutorials/pkgs.html).

**Comment by ttungl** [comment]
from @ptrblck comment, adding `--user` if you got any error.
