### ISSUE TITLE
I get AttributeError on tf 1.0.1  running tensorflow  on keras

### ISSUE THREAD

**Issue by ramboforever** [fchollet/keras#5783]
I am running below code:

from keras import backend as K
if K.image_data_format() == 'channels_first':
    input_shape = (3, img_width, img_height)
else:
    input_shape = (img_width, img_height, 3)

Getting this error:
AttributeError: module 'keras.backend' has no attribute 'image_data_format'

How to resolve this?

**Comment by egrinstein** [comment]
"image_dim_ordering" is a [legacy variable](https://keras.io/backend/), so I guess you might be using an old version of Keras. You could change `K.image_data_format() == 'channels_first'` to `K.image_dim_ordering() == 'th'` and it will work fine.

**Comment by alyato** [comment]
hi @egrinstein  thanks .
I meet the same question.
But i have upgrade the keras to 2.1.5 by`pip install keras --upgrade`
You say my keras's version is old ,then cause this question.
It's so wired. 
thanks again.

**Comment by alyato** [comment]
thanks again. I used the old backend. SO i use the new backend and it work.[https://keras.io/backend/](url)
