### ISSUE TITLE
input_dim in Recurrent layer

### ISSUE THREAD

**Issue by Derek-Gong** [fchollet/keras#5786]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

script:
keras.models.load_model(filename)

the model file contained recurrent layer which had argument input_dim.

then I got:
TypeError: ('Keyword argument not understood:', u'input_dim')

I checked keras/layers/recurrent.py in keras2 and keras1, and found a difference that I thought which is not intended:
keras2:

class Recurrent(Layer):
def __init__(self, return_sequences=False,
                 go_backwards=False,
                 stateful=False,
                 unroll=False,
                 implementation=0,
                 **kwargs):
        super(Recurrent, self).__init__(**kwargs)

keras1:
class Recurrent(Layer):
def __init__(self, weights=None,
                 return_sequences=False, go_backwards=False, stateful=False,
                 unroll=False, consume_less='cpu',
                 input_dim=None, input_length=None, **kwargs):
        ......................... some initiating code for other arguments
        if self.input_dim:
            kwargs['input_shape'] = (self.input_length, self.input_dim)
        super(Recurrent, self).__init__(**kwargs)

which means you will not handle input_dim in Recurrent layer in keras2.
however, doc string said in keras2:
input_dim: dimensionality of the input (integer).
            This argument (or alternatively, the keyword argument `input_shape`)
            is required when using this layer as the first layer in a model.

Meanwhile,  this may cause a compatibility problem, which I have encountered.

**Comment by abhaikollara** [comment]
Hmm, strange, you should've got a deprecation warning for `input_dim`. Which recurrent layer are you using `LSTM`, `GRU`, `SimpleRNN` ?

**Comment by Derek-Gong** [comment]
it's LSTM

**Comment by Zach-ER** [comment]
I am having this problem as well, but also for GRU.

**Comment by rilut** [comment]
I think it's fixed in c88a11c378189443cf1f95ed14edd47c9666171a. Please try updating to Keras 2.0.1

**Comment by rilut** [comment]
Nope, sorry

**Comment by Derek-Gong** [comment]
Yeah. that fixed another problem when using load_model with old model.
