### ISSUE TITLE
small bugs in local.py on LocallyConnected2D?

### ISSUE THREAD

**Issue by WeidiXie** [fchollet/keras#5792]
Hello, 

I'm wondering if the line 411-413 is correct ?
https://github.com/fchollet/keras/blob/master/keras/layers/local.py#L412-L413

output = K.reshape(output, (self.output_row, self.output_col, -1, filters))

output is of dimension :  output_row x output_col x batch_size x filters

output = K.permute_dimensions(output, (2, 0, 1, 3))

should this be (1,2,0,3) ?

Thanks !

**Comment by joelthchao** [comment]
`channels_last` output should be in shape `(batch_size, output_row, output_col, filters)`, which is corresponding to `(2, 0, 1, 3)`.
