### ISSUE TITLE
Merging convolutional layer with Merge layer

### ISSUE THREAD

**Issue by hellorp1990** [fchollet/keras#5803]
Hi,
I wanted to merge two sequential models input into one using Merge layer. But it is showing me error. 
I am using image, with size 128x128 (RGB image)  and batch size is 32.

The error coming is : ValueError: The model expects 3 input arrays, but only received one array. Found: array with shape (32, 3, 128, 128)

The model is  ---

model = Sequential()
leftBranch = Sequential()
leftBranch.add(Reshape((3,128,128), input_shape=(3, img_width, img_height)))
leftBranch.add(Convolution2D(14, 3, 1, activation='relu'))
leftBranch.add(ZeroPadding2D((1, 1)))
leftBranch.add(Flatten())

rightBranch = Sequential()
rightBranch.add(Reshape((3,128,128), input_shape=(3, img_width, img_height)))
rightBranch.add(Convolution2D(14, 1, 3, activation='relu'))
rightBranch.add(MaxPooling2D((2, 2), strides=(2, 2)))
rightBranch.add(Flatten())

centralBranch = Sequential()
centralBranch.add(Reshape((3,128,128), input_shape=(3, img_width, img_height)))
centralBranch.add(Convolution2D(14, 5, 5, activation='relu'))
centralBranch.add(MaxPooling2D((2, 2), strides=(2, 2)))
centralBranch.add(Flatten())

merged = Merge([leftBranch, centralBranch, rightBranch], mode='concat')

model = Sequential()
model.add(merged)
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

Error coming is : ValueError: The model expects 3 input arrays, but only received one array. Found: array with shape (32, 3, 128, 128) 

So, whats is the proper way to concatenate two sequential model with convolutional layers. I just want to Merge  convolutional layers output like I did it here.

Any suggestions will be appreciated. Plz help.

**Comment by dasraf9** [comment]
Can you post your `model.fit()` line and everything that have to do with preparing your input? 
It's seems like currently you are only feeding one of the branches with input.

**Comment by hellorp1990** [comment]
model.fit_generator(
        train_generator,
        samples_per_epoch=nb_train_samples,
        nb_epoch=nb_epoch,
        validation_data=validation_generator,
        nb_val_samples=nb_validation_samples,callbacks=callbacks_list)

**Comment by hellorp1990** [comment]
@dasraf9  thanks for replying . I am using imagedatagenerator  for image augmentation. 

Yeah It is saying that it is receiving one array instead of 3. But i am merging three .

**Comment by dasraf9** [comment]
I understand that you wish to have the same input to all 3 branches. 
If so, try this:

`input_layer = Reshape((3,128,128), input_shape=(3, img_width, img_height))
 
leftBranch = Sequential()
leftBranch.add(input_layer)
leftBranch.add(Convolution2D(14, 3, 1, activation='relu'))
leftBranch.add(ZeroPadding2D((1, 1)))
leftBranch.add(Flatten())

rightBranch = Sequential()
rightBranch.add(input_layer)
rightBranch.add(Convolution2D(14, 1, 3, activation='relu'))
rightBranch.add(MaxPooling2D((2, 2), strides=(2, 2)))
rightBranch.add(Flatten())

centralBranch = Sequential()
centralBranch.add(input_layer)
centralBranch.add(Convolution2D(14, 5, 5, activation='relu'))
centralBranch.add(MaxPooling2D((2, 2), strides=(2, 2)))
centralBranch.add(Flatten())`

**Comment by hellorp1990** [comment]
@dasraf9 thanks . its working now
