### ISSUE TITLE
What happened to SReLu?

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#5808]
Hi,

I've just upgraded Keras, and it seems that the SReLu are not available anymore.

> from keras.layers.advanced_activations import PReLU, SReLU, ELU
> ImportError: cannot import name 'SReLU'

And I don't see them anymore in the documentation either: [https://keras.io/layers/advanced-activations/](https://keras.io/layers/advanced-activations/)

What's wrong with the SReLu?

**Comment by thesuperzapper** [comment]
I would like to know as well.

**Comment by fchollet** [comment]
It was removed. If you want to keep using it, you should maintain it as
part of your own codebase.

**Comment by FiReTiTi** [comment]
Thanks for the answer, but I guess that if it was removed it's because there is a compatibility issue (or something else) with the Keras 2.0.
Am I right?

**Comment by the-moliver** [comment]
@FiReTiTi @thesuperzapper SReLU is now in keras-contrib. Please close issue.
