### ISSUE TITLE
How to add different channels into one channel?

### ISSUE THREAD

**Issue by Jason6LIU** [fchollet/keras#5809]
I am writing a FCN model based on Resnet. I want add three previous tensors into one channel tensor. e.g:
add [None, 256, 224,224], [None, 512, 224,224], [None, 1024, 224,224], and [None, 2048, 224,224], into [None,1,224,224]. all channel values are added.
So, how can I do this?
Thanks very much!

**Comment by kgrm** [comment]
One option would be to concatenate the tensors along the channel axis first using a merge layer, then use a lambda layer to sum and reduce the channel axis.
