### ISSUE TITLE
Cannot load pre-trained ImageNet models (VGG16, VGG19, ResNet50, etc.) due to 'convolution' attribute error

### ISSUE THREAD

**Issue by jrosebr1** [fchollet/keras#5813]
Hello, all. I just upgraded to Keras 2.0 and went to load a pre-trained ImageNet network from the `applications` module and received the following error:

<pre>  File "classify_image.py", line 28, in <module>
    model = VGG16(weights="imagenet")
  File "/Users/adrianrosebrock/.virtualenvs/keras2.0/lib/python2.7/site-packages/keras/applications/vgg16.py", line 111, in VGG16
    x = Conv2D(64, (3, 3), activation='relu', padding='same', name='block1_conv1')(img_input)
  File "/Users/adrianrosebrock/.virtualenvs/keras2.0/lib/python2.7/site-packages/keras/engine/topology.py", line 545, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/adrianrosebrock/.virtualenvs/keras2.0/lib/python2.7/site-packages/keras/layers/convolutional.py", line 164, in call
    dilation_rate=self.dilation_rate)
  File "/Users/adrianrosebrock/.virtualenvs/keras2.0/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2858, in conv2d
    x = tf.nn.convolution(
AttributeError: 'module' object has no attribute 'convolution'</pre>

The code to reproduce the error is:

<pre>from keras.applications import VGG16
model = VGG16(weights="imagenet")</pre>

Here are the relevant libraries via `pip freeze`:

<pre>Keras==2.0.0
tensorflow==0.11.0</pre>

I then tried using Keras 1.2.2 and TensorFlow 0.11.0rc2 from a separate virtual environment and the script executed without error.

I have also confirmed that both by image ordering is `channels_last` and my backend is `tensorflow` in the `keras.json` file.

**Comment by jrosebr1** [comment]
UPDATE:

Just tried using a Theano backend by updating my `keras.json` file to switch the backend to `theano` and `image_dim_ordering` to `channels_first`.

I then executed the script and the model was loaded. This seems to be TensorFlow specific.

**Comment by farizrahman4u** [comment]
Update tensorflow to the latest version. (r1.0)

**Comment by jrosebr1** [comment]
@farizrahman4u: Clearly my mistake there. Upgrading to TensorFlow > 1.0 allowed the model to be loaded. I also see that there is now only one set of weights files for Theano and TensorFlow as opposed to explicitly downloading separate weights files for each backend. Thanks for the clarification!
