### ISSUE TITLE
Broken Sequential Examples

### ISSUE THREAD

**Issue by Pavel-Konarik** [fchollet/keras#5821]
Executing both examples from Training section of https://keras.io/getting-started/sequential-model-guide/ will result in error. 

#1 Example ( For a single-input model with 2 classes)
ValueError: Error when checking model input: expected dense_5_input to have shape (None, 100) but got array with shape (1000, 784)

#2 (For a single-input model with 10 classes)
ValueError: Error when checking model input: expected dense_3_input to have shape (None, 100) but got array with shape (1000, 784)

Any ideas how to run them successfully? 

To be sure everything is updated, I created new env with piped tf and keras from git
Tensorflow version - 1.0.0
Keras version - 2.0.0

**Comment by joelthchao** [comment]
It seems like you try to feed model with mnist data, which has shape of `(1000, 784)`. If you following the code snippet, everything works well.
