### ISSUE TITLE
Non centered ZeroPadding2D?

### ISSUE THREAD

**Issue by pjadzinsky** [fchollet/keras#583]
Hi,

I need to zero pad some images but I need to add the zeros only to the bottom and right.

Would you be interested in either:
* changing ZeroPadding2D to include how many to pad in each location
* including either pad_left/right/top/bottom
* a more generic rotation function (something like A[newX0]+A[:newX0])

Thanks

**Comment by fchollet** [comment]
> changing ZeroPadding2D to include how many to pad in each location

Would probably be the best solution. I'll think about it. Meanwhile it would be very easy for you to adapt the current `ZeroPadding2D` layer to your own needs.

**Comment by pjadzinsky** [comment]
I already changed mine to do what I need. But I'm working on a general solution, something like this (that will also take care of the concern I had with the filters)


    def __init__(self, n, dim):
        super(Rotate, self).__init__()
        self.n = n
        self.dim = dim

    def get_output(self, train=False):
        n = self.n
        dim = self.dim

        N = x.shape[dim]
        ndim = x.ndim

        front_slices = (slice(None),)*n
        back_slices = (slice(None),)*(ndim-n-1)

        y = T.zeros_like(x)
        y = T.set_subtensor(
                y[front_slices + (slice(0, n),) + back_slices],
                x[front_slices + (slice(N-n,N),) + back_slices])
        y = T.set_subtensor(
                y[front_slices + (slice(n,N),) + back_slices],
                x[front_slices + (slice(0,N-n),) + back_slices])
        return y

    def get_config(self):
        return {"name": self.__class__.__name__,
                "dims": self.dims}
