### ISSUE TITLE
image_data_ordering and image_data_format

### ISSUE THREAD

**Issue by wenouyang** [fchollet/keras#5830]
In my keras installation, I can see the backend configuration as

> cat $HOME/.keras/keras.json
{"floatx": "float32", "epsilon": 1e-07, "backend": "theano","image_dim_ordering": "th"}

In this [vgg16.py](https://github.com/fchollet/deep-learning-models/blob/master/vgg16.py), author uses 
`data_format=K.image_data_format()`  Are they the same thing? Can I just replace `image_data_format `with `image_data_ordering`?

**Comment by fchollet** [comment]
Yes. Unless you set the image data format manually. Check
what`K.image_data_format()` returns.

**Comment by wenouyang** [comment]
Hi François, thank you for your reply!  What are the best way or (how to check) the return of `K.image_data_format()`? Are there any utility that can enable me to print these information out?

Which keras version is vgg16.py relied on? I am using Keras 1.2.1

Currently, my development environment involves a lot of other dependences, what are the recommend approaches to update keras1.2.1 to the newer version without affecting other installed python packages, such as tensorflow, theano, scipy, ...? THanks.

**Comment by joelthchao** [comment]
@wenouyang Check [this](https://github.com/fchollet/keras/blob/master/keras/backend/common.py#L111) and [this](https://github.com/fchollet/keras/blob/master/keras/backend/common.py#L206). They tell you that you can change it to `K.image_dim_ordering()` for your old keras version.

**Comment by wenouyang** [comment]
Hi joelthchao, thanks.
