### ISSUE TITLE
Broken Model example

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#5831]
Hi,

I tried to the Model example on a Keras version older than 2.0:
	`a = Input(shape=(32,))`
	`b = Dense(32)(a)`
	`model = Model(inputs=a, outputs=b)`

But I get this error.
`model = Model(inputs=a, outputs=b)`
`TypeError: __init__() got an unexpected keyword argument 'outputs'`

How can I run this simple example for a older version than 2.0?

**Comment by fchollet** [comment]
For earlier Keras versions, it's `input` and `output`.

**Comment by FiReTiTi** [comment]
Thanks!

**Comment by FiReTiTi** [comment]
Sorry, last question. What about for multiple inputs?
I have a model like that:
	`dim = 23`
	`input_shape = (1, dim, dim, dim)`

	`input1 = Input(shape=input_shape)`
	`x1 = Convolution3D(8, 5, 5, 5, border_mode='valid', activation='relu')(input1)`
	
	`input2 = Input(shape=input_shape)
	`x2 = Convolution3D(8, 5, 5, 5, border_mode='valid', activation='relu')(input2)`

	`x = merge([x1, x2], mode='concat')`
	`...`
	`x = Dense(1, activation='sigmoid')(x)`

	`model = Model(x, input=[input1, input2])`

But I get the error:
> model = Model(x, input=[input1, input2])
> TypeError: __init__() got multiple values for keyword argument 'input'

**Comment by fchollet** [comment]
The first positional argument is the input. It's just model(x, y)

**Comment by FiReTiTi** [comment]
Thanks a lot!!!
