### ISSUE TITLE
PyPi Install on Windows fails (Python2 Windows 64)

### ISSUE THREAD

**Issue by Ninad998** [fchollet/keras#5833]
Hi all,
I am not sure if more people have tried this but installation of Keras on Windows with Python2 will always fails because of the default back-end. 
Tensorflow does not have a Python2 install for Windows.

**Comment by rilut** [comment]
try adding `--no-deps` in your pip command

**Comment by Ninad998** [comment]
Hi,
Issue seems to be on the Scipy package rather than the Keras package.
--no-deps helps install Keras correctly.
