### ISSUE TITLE
ValueError while trying to fit data to model. (Tensorflow backend)

### ISSUE THREAD

**Issue by ant0nisk** [fchollet/keras#5841]
Hello there,

I am using Keras (version 2.0.1) with the latest Tensorflow (installed from pip) as a backend. This is one of my first attempts to use Keras but I get the following error when I try to fit the training data into my model:
`ValueError: None values not supported.`
which is thrown from within Tensorflow. 
I run MacOS Sierra on a Macbook Pro, but I haven't tried to reproduce the problem on other machines.

Here is an Jupyter notebook with the code which reproduces the problem (_with example preprocessed data_):
https://gist.github.com/ant0nisk/f5ee88af693b37d93d4d6adb572e6f98

I checked my data, and it doesn't have any None values, however I am still new to this, so I am not sure what exactly causes this exception.

Anyone else has this problem?

**Comment by joelthchao** [comment]
Please check the [doc](https://keras.io/layers/embeddings/):
> This layer can only be used as the first layer in a model.

**Comment by ant0nisk** [comment]
Oh, I don't know how I missed this... Thanks
