### ISSUE TITLE
Create customized operation for merge layer

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#5842]
Hi,

I would like to create my own operation to merge networks.
So I've taken a look to the code, keras/layers/Models.py and the code seems easy to modify.
Is that the only class I have to modify?
Don't I have to do something else somewhere else to specify what to do during the backward pass?

**Comment by FiReTiTi** [comment]
I dived into the code and I modified engine/topology.py.
I didn't modified layers/wrappers.py because it's only for RNN and when I modify it I get an error.
Are there other files to modify?

**Comment by FiReTiTi** [comment]
It seems that if I use the backend, then I don't have to modify any other files. But when I take a look to the merging operations into the file topology.py, the operations do not use the backend. How is that possible?

**Comment by farizrahman4u** [comment]
You can use a lambda layer to merge multiple tensors.

**Comment by FiReTiTi** [comment]
Thank you very much, but I don't know how to do that.
