### ISSUE TITLE
issues in help docs of Con2D and Conv1D

### ISSUE THREAD

**Issue by benwu232** [fchollet/keras#5845]
https://keras.io/layers/convolutional/#conv2d

data_format: A string, one of channels_last (default) or channels_first. The ordering of the dimensions in the inputs. channels_last corresponds to inputs with shape  (batch, width, height, channels) while channels_first corresponds to inputs with shape  (batch, channels, width, height)

I think channels_last should be (batch, height, width, channels), which is NHWC. And similar to channels_first. There are many places in the help doc like this.

https://keras.io/layers/convolutional/#conv1d

Input shape

3D tensor with shape: (batch_size, steps, input_dim)

The means of steps and input_dim are not clear. I think steps is the length of the time series, input_dim is features in each time step, similar to the channels in Conv2D. Am I right?

**Comment by abhaikollara** [comment]
The issue has been resolved in #5854

**Comment by benwu232** [comment]
Seems the doc in keras.io is not modified.

BTW, is my understanding of Conv1D right?

Thanks!
