### ISSUE TITLE
How can I install keras with older version? Not 2.0.1 version

### ISSUE THREAD

**Issue by TruongKhang** [fchollet/keras#5852]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by keunwoochoi** [comment]
`$ pip install keras==1.2`

**Comment by joki3** [comment]
how to know Keras is installed or not order is installed so how can we check which version now?

**Comment by JeruLuke** [comment]
@joki3 Enter `python` in the terminal then type the following sequentially:
`>>> import keras`
`>>> keras.__version__`

This will return the keras version. If keras is not installed it would throw an `ImportError`

**Comment by vimalmahi** [comment]
@joki3 If you have pip just type in 
$ pip show {package-name}
For your case
$ pip show keras

**Comment by safciplak** [comment]
> `$ pip install keras==1.2`

But i got it below

    if K.backend() == 'tensorflow' and not K.tensorflow_backend._is_tf_1():
AttributeError: module 'keras.backend.tensorflow_backend' has no attribute '_is_tf_1'
