### ISSUE TITLE
How to access filters(kernels) in CNN?

### ISSUE THREAD

**Issue by YingweiZhou** [fchollet/keras#5856]
Hello, I'm trying to do some customization works with filters of convolution layers. Could someone told me how to get the `input` of filters? Since filters are part of convolutional layers and cannot get their input byu `layer.get_input()`. Besides, I'm wondering how did Keras organise the calculations of CNN?

I checked the codes for some hours but cannot figure out how did Keras calculate feature maps and apply optimization methods on  it? All I found is the backend functions like: `K.get_gradients`, `K.conv_2d` and so on. I understand as a high level library, Keras uses TH or TF as its backend and may not directly support these filter/convolutional calculation, could someone kindly tells me which part in tensorflow defines the calculation of convolution layers?

**Comment by Jiaming-Liu** [comment]
I'm not sure what the question is. Do you mean you want to get the weight (W) of filters in the convolutional layers? Or do you want to find the feature map output (W*X)?
