### ISSUE TITLE
How much does it take to run example/lstm_text_generation.py

### ISSUE THREAD

**Issue by ben46** [fchollet/keras#587]
I am using my macbook pro with Intel GPU(not compatible with CUDA), it's take 40 minutes to run `example/lstm_text_generation.py` every iteration, it's very time consuming and suffers :(. May I ask how much time do you guys take to run on your own GPU. I am considering update my device.

**Comment by EderSantana** [comment]
If there is no CUDA, probably theano isn't using your GPU. It is slow cause its CPU only. I believe that Theano support to non-CUDA GPUs is only in experimental phase still.

**Comment by EderSantana** [comment]
Cuda is definitively the easiest way to do deeplearning nowadays (most libs are based on it). But look for deep learning libraries based on OpenCL to see if you find anyone that you like. I heard that Caffe has a version that uses OpenCL, for example, not sure if it is ready yet, though.

**Comment by ben46** [comment]
Thanks for your answer, it helps a lot.
