### ISSUE TITLE
I update Keras 2. Program run error "sigmoid_cross_entropy_with_logits does not have `labels` . my program run normal before update"

### ISSUE THREAD

**Issue by huynh-phuoc-hai** [fchollet/keras#5871]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by leaprovenzano** [comment]
Ditto this. I'm on tensorflow-1.0.1 backend and keras 2.0.2 (up to date w/ master)
Here's a bottom of traceback:

```
Virtualenvs/tensor_venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in binary_crossentropy(output, target, from_logits)
   2613 
   2614     return tf.nn.sigmoid_cross_entropy_with_logits(labels=target,
-> 2615                                                    logits=output)
   2616 
   2617 

TypeError: sigmoid_cross_entropy_with_logits() got an unexpected keyword argument 'labels'
```

although looking at [ nn_impl in tf repo](https://github.com/tensorflow/tensorflow/python/ops/nn_impl.py) it does actually seem to have a keyword arg for `labels` so I'm not really sure what's going on there...

**Comment by brentcl** [comment]
I am having the same issue with Keras 2.02 and Tensorflow when trying to compile a Convolutional Net.

**Comment by jbn** [comment]
See also: https://github.com/fchollet/keras/issues/6066

(Mine was solved with an update of `tf`. Not sure what's wrong for @leaprovenzano's env though.)
