### ISSUE TITLE
Hello, Can I  ask you how to build a 3D Convolution Autoencoder?

### ISSUE THREAD

**Issue by markofan** [fchollet/keras#5880]

**Comment by valtron** [comment]
Same as a [2D one](https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder_deconv.py), except Keras doesn't have transposed 3D convolution. The following _might_ be equivalent to a transposed 3d conv with 1x1x1 kernel and 0.5 strides:

```
def transposed_conv_3d(chans, input, **kwargs):
    tmp = Upsampling3D()(input)
    tmp = Convolution3D(chans, 1, 1, 1, **kwargs)(tmp)
    return tmp
```

For a complete 3D architecture, take a look at [V-Net: Fully Convolutional Neural Networks for Volumetric Medical Image Segmentation](https://arxiv.org/abs/1606.04797).

**Comment by markofan** [comment]
Thank you so much for your reply, I want to know that if I also use convolution3D while decoding, can this autoencoder works well?

**Comment by valtron** [comment]
You'll have to experiment and see what works best. Another piece of advice though: if you do use a V-Net type architecture, don't use residual (skip) connections, as that will make the autoencoder learn a trivial transform.
