### ISSUE TITLE
preprocess_weights_for_loading [bug]

### ISSUE THREAD

**Issue by kentsommer** [fchollet/keras#5885]
When converting weights (InceptionV3 for instance), if the backend is switched, loading crashes with an error pointing to h5py. It looks like since the conv2d layers are usually included last in any h5 file they are the only ones who have their indexes checked but h5py expects the index to be > 0 as it is not the first layer in the file. 

**How to reproduce**:

1. Change your backend to 'theano' in the keras.json config file
2. Run this script:
```
from keras.applications.inception_v3 import *
from keras.preprocessing import image
from keras.applications.imagenet_utils import decode_predictions
from keras import backend as K
import numpy as np

model = InceptionV3(weights='imagenet')

img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(299, 299))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = model.predict(x)
print('Predicted:', decode_predictions(preds))
```

With the Tensorflow backend this works fine and outputs the following:
```
[[(u'n02504458', u'African_elephant', 0.90738213)]]
````

However, if the backend is switched to Theano you get the following error (full traceback):
```
Using Theano backend.
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    model = InceptionV3(weights='imagenet')
  File "/home/kent/.virtualenvs/keras2/local/lib/python2.7/site-packages/keras/applications/inception_v3.py", line 383, in InceptionV3
    model.load_weights(weights_path)
  File "/home/kent/.virtualenvs/keras2/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2491, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/home/kent/.virtualenvs/keras2/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2893, in load_weights_from_hdf5_group
    original_backend)
  File "/home/kent/.virtualenvs/keras2/local/lib/python2.7/site-packages/keras/engine/topology.py", line 2833, in preprocess_weights_for_loading
    weights[0] = conv_utils.convert_kernel(weights[0])
  File "/home/kent/.virtualenvs/keras2/local/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 86, in convert_kernel
    return np.copy(kernel[slices])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-nCYoKW-build/h5py/_objects.c:2798)
  File "/home/kent/.virtualenvs/keras2/local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 474, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/kent/.virtualenvs/keras2/local/lib/python2.7/site-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/home/kent/.virtualenvs/keras2/local/lib/python2.7/site-packages/h5py/_hl/selections.py", line 363, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
```

This is definitely unexpected behavior, however, I'm unable to see an obvious issue anywhere in the Keras-2 changes which is why I'm posting it here. 

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by kentsommer** [comment]
Looks like the issue is that for whatever reason, the kernel to ```convert_kernel(kernel):``` gets passed as an hd5 dataset and NOT a numpy array as expected. Adding the line ```weights = np.array(weights)``` to the function ```preprocess_weights_for_loading``` in /keras/engine/topology.py fixes this issue, however, it is not very elegant.

**Comment by kentsommer** [comment]
After fixing the issue above, there are still issues with classification. 

Given [this image of an apple](https://static.pexels.com/photos/39803/pexels-photo-39803.jpeg), [the test script here](https://gist.github.com/kentsommer/48e43bf7badd7243849d01ba1e76e3cf) outputs the following:

Tensorflow backend: 
```
('Predicted:', [[(u'n07742313', u'Granny_Smith', 0.83470553), (u'n07753113', u'fig', 0.015361091), (u'n07747607', u'orange', 0.0053814445), (u'n07768694', u'pomegranate', 0.0048999568), (u'n12267677', u'acorn', 0.0044363858)]])
```

Theano backend:
```
('Predicted:', [[(u'n07753113', u'fig', 0.62229174), (u'n12267677', u'acorn', 0.1156325), (u'n07716906', u'spaghetti_squash', 0.048293442), (u'n07716358', u'zucchini', 0.016509119), (u'n07742313', u'Granny_Smith', 0.011241601)]])
```

Setup (separate virtual environment):
Keras 2.0.1
Tensorflow 1.0.1
Theano 0.9.0rc4

**Comment by yellowb0y** [comment]
I'm getting an error in this script:

```
inc_model=InceptionV3(include_top=False,
                      weights='imagenet',
                      input_shape=(3, 150, 150))
```
Updates Keras/Theano did not help.
Edit topology.py сauses a lot of problems in the fit network

**Comment by bis-carbon** [comment]
Am getting the same problem :
base_model = InceptionV3(weights='imagenet', include_top=False, input_shape=(299, 299, 3))

Error:
raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order


Did you get any solution ?

**Comment by jackkwok** [comment]
I am also getting the exact same error with this line of code:

base_model = InceptionV3(weights='imagenet', include_top=False)

I am using theano backend (never installed tensorflow).  I have update to latest master branch code on both keras and theano from github.

Please help.
