### ISSUE TITLE
load_model() doesn't load history callback

### ISSUE THREAD

**Issue by libphy** [fchollet/keras#5890]
I run training with history callback

from keras.callbacks import History
history = History()
model.fit_generator(gen(DATAPATH_TR, BATCH_SIZE),samples_per_epoch=ntr, nb_epoch=10, validation_data =gen(DATAPATH_VAL, BATCH_SIZE), nb_val_samples = nval, verbose=1, callbacks = [history])

This outputs correctly (a dictionary) when I do 
model.history.history 

Then I save the model
model.save('dummy.h5')

Now, in a new python session, I load the model
model = load_model('dummy.h5)
Then when I try to retrieve history callback by typing
model.history.history
It throws an error
AttributeError: 'Model' object has no attribute 'history'

My question is that model.history.history was there before saving the model but why it doesn't exist any more when I load the model? Does it (dropping the model.history.history) happen during model.save() or load_model()?

**Comment by paulshatalov** [comment]
@libphy Hello! I have the similar issue, did you find the solution?

The case is:
- I save the model to hdf5
- Load it using load_model()
- Train loaded model with fit_generator() 
and I get an error "'Sequential' object has no attribute 'history'" in the end of training. It goes from keras lib.

**Comment by unjadded** [comment]
Sane with me

**Comment by paulshatalov** [comment]
> Same with me. Loading a saved VGG19 doesn't return the history callback.
> 
> I tried model.History()

Hi! That was quite long time ago, but as I remember I've found proper History in one of the nested objects. Try: model.model.history or something like that.

**Comment by nguyenvulong** [comment]
> > Same with me. Loading a saved VGG19 doesn't return the history callback.
> > I tried model.History()
> 
> Hi! That was quite long time ago, but as I remember I've found proper History in one of the nested objects. Try: model.model.history or something like that. Or mode;.history.history

I've tried both, it didn't work
Anyone?

**Comment by farznaj** [comment]
I am also dealing with this problem. Did anyone find a workaround?

**Comment by vikasnataraja** [comment]
Currently, it looks like there is no way to recover model history from `load_model`. I've had to resort to using the `CSVLogger` during runtime and then loading that csv file using `pandas` which gives about the same information about the model history. Another way might be pickling but I haven't tried that yet.

**Comment by vibrancy** [comment]
Just to elaborate on @ vikasnataraja  answer: using csv logger as

`from keras.callbacks import CSVLogger

csv_logger = CSVLogger( 'training_history.log', separator=',', append=False )
my_Keras_model.fit(X_train, Y_train, callbacks=[csv_logger])
`

**Comment by vhns** [comment]
Bummer that it doesn't seem like this is properly documented anywhere. Just ran into this issue myself.
