### ISSUE TITLE
Cannot use Keras in threads

### ISSUE THREAD

**Issue by eyesonlyhack** [fchollet/keras#5896]
I'm using Ubuntu 16.04, Python 3.5.2, Keras 2.0.1 and Tensorflow 1.01. 

Keras/tensorflow crash when using threads. The following code is a simplified version of what I am trying to do but recreates the crash.

https://gist.github.com/eyesonlyhack/c43dea734f872a9c45da8587eefec581

I found a way to get around this issue but think this is probably a bug in Keras. My workaround is:
https://gist.github.com/eyesonlyhack/2f0b20f1e73aaf5e9b83f49415f3601a

**Comment by mpariente** [comment]
Calling `K.clear_session()` at the beginning or at the end of the function also works.

**Comment by SeokLeeUS** [comment]
> Calling `K.clear_session()` at the beginning or at the end of the function also works.

can you get me more details? what do you mean the beginning or at the end of the function?
what do you mean by "function"?
