### ISSUE TITLE
Import error " from keras.preprocessing.image import ImageDataGenerator "

### ISSUE THREAD

**Issue by krunalpc** [fchollet/keras#5897]
I am getting an error "  ImportError: cannot import name 'coo_matrix'  " while importing the " from keras.preprocessing.image import ImageDataGenerator ".

**Comment by alexxucui** [comment]
@krunalpc I suggest including your python and Keras version here as they are useful information.

**Comment by krunalpc** [comment]
@alexxucui I am using Keras version 2.0.1.
And Python version 3.5.2.
