### ISSUE TITLE
None is not supported in input_shape [bug]

### ISSUE THREAD

**Issue by rex-yue-wu** [fchollet/keras#5900]
In the new release v2.0.1, `None` is not supported in input_shape, while `None` is must-have for a fully-convolutional network. Below is an example

```
>>> model = Sequential()
model = Sequential()
>>> model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(3, None, None)))
)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/isicvlnas01/share/anaconda/lib/python2.7/site-packages/keras/models.py", line 422, in add
    layer(x)
  File "/nfs/isicvlnas01/share/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 528, in __call__
    self.build(input_shapes[0])
  File "/nfs/isicvlnas01/share/anaconda/lib/python2.7/site-packages/keras/layers/convolutional.py", line 125, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.
>>> print keras.__version__
print keras.__version__
2.0.1
```

**Comment by kivantium** [comment]
Your problem is the order of input_shape. You assume channels come first, but whether channels come first or last depends on the configuration in `$HOME/.keras/keras.json`. See https://keras.io/backend/.

If your `image_data_format` is `channels_last`, your `input_shape` should be `(None, None, 3)`.

**Comment by rex-yue-wu** [comment]
Nope. I use `theano` backend, and the order should be `( 3, None, None )`.

**Comment by bstriner** [comment]
Tried your code and works for me on Theano. Double check the ordering actually loaded in keras.

```python
import keras.backend as K
print(K.image_dim_ordering())
```

> 'th'

Cheers

**Comment by bstriner** [comment]
Just realized I gave you the old API.

```python
import keras.backend as K
print(K.image_dim_ordering())
print(K.image_data_format())
```

> th
> channels_first

**Comment by rex-yue-wu** [comment]
Thank you. As you both said, the `image_data_format` caused my error. The real problem is that I did not notice that my `keras.json` is need to update for the new version, because `image_data_format` is not in a `1.x` version.
