### ISSUE TITLE
Memory leaks when using keras.models.model_from_json 

### ISSUE THREAD

**Issue by ChanYiChih** [fchollet/keras#5909]
Hi, could someone tell me why it would cause memory leaks when using model_from_json several times?

Keras (2.0.0)
Tensorflow (0.12.1)

Thanks a lot.

```
def dumpMemUsage():
    gc.collect()
    process = psutil.Process(os.getpid())
    memory = process.memory_info()
    print('memory: {}'.format(memory))

for i in range(100):
    model = model_from_json(modelJson)
    weights = pickle.loads(weightsPickle)
    model.set_weights(weights)
    del model
    dumpMemUsage()
    objgraph.show_most_common_types()
    time.sleep(3)
```
**first time**
memory: pmem(rss=92004352L, vms=2695143424L, pfaults=30035, pageins=0)
function                   22521
dict                       20037
tuple                      12085
cell                       9692
list                       7717
_Listener                  5572
weakproxy                  5572
weakref                    2925
builtin_function_or_method 2578
wrapper_descriptor         2370

**after several times**
memory: pmem(rss=126005248L, vms=2727243776L, pfaults=45309, pageins=0)
dict                       43644
tuple                      31957
function                   22521
list                       20509
_Listener                  13384
weakproxy                  13384
cell                       9692
AttrValue                  4133
weakref                    2928
builtin_function_or_method 2578

**Comment by ChanYiChih** [comment]
if I comment out following code and related codes in keras.models.add(), the memory seems stable
self.outputs = [layer.inbound_nodes[0].output_tensors[0]]

And I also use memory profiler to see some kind of cyclic references of Tensors, is this a problem?
However, my python could detect cyclic references, and garbage collect them, so I have no idea about how this memory leak could happen?

**Comment by buechel** [comment]
I'm not sure if this is relevant. But I stumbled across  issue  #2102 when I had a similar problem.
