### ISSUE TITLE
New version of imdb dataset is broken (word order?)

### ISSUE THREAD

**Issue by shnayder** [fchollet/keras#5912]
The IMDB dataset in imdb.npz is broken or at least incompatible with the provided word index--converting reviews to a string gives nonsense (either the wrong words or mixed up word order--not sure). Example:

```
import keras
from keras.datasets import imdb
import cPickle as pickle
import os.path

word2index = imdb.get_word_index()
index2word = dict([(i,w) for (w,i) in word2index.items()])

# use new load_data
# (post https://github.com/fchollet/keras/commit/b0500764a8a451882262328c0f1676402fb0a783)
(x_train, y_train), (x_test, y_test) = imdb.load_data()

# Load manually downloaded old pickle file (before above commit)
# from https://s3.amazonaws.com/text-datasets/imdb_full.pkl
path = os.path.expanduser('~/.keras/datasets/imdb_full.pkl')
f = open(path, 'rb')
(x_train2, y_train2), (x_test2, y_test2) = pickle.load(f)

def totext(review):
    return ' '.join(index2word[i] for i in review)

print(keras.__version__)

print("New commit review -- makes no sense:")
print(totext(x_train[0][:20]))

print("\nOld commit review:")
print(totext(x_train2[0][:20]))
```

Output:
```
2.0.1
New commit review -- makes no sense:
the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have

Old commit review:
bromwell high is a cartoon comedy it ran at the same time as some other programs about school life such
```

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by shnayder** [comment]
Vaguely related: https://github.com/fchollet/keras/blob/master/keras/datasets/imdb.py#L103 looks wrong to me. 

It's currently `if w >= num_words or w < skip_top:`, which will only keep overly frequent or overly infrequent words. I think you want the opposite: `if w < num_words and w > skip_top:`. (Looks like a code path that's rarely used since oov_char has a not-None default value).

**Comment by shnayder** [comment]
and related again (how I found the above):
https://github.com/fchollet/keras/blob/master/examples/imdb_lstm.py#L22 says that infrequent words will be dropped, but https://github.com/fchollet/keras/blob/master/examples/imdb_lstm.py#L26 calls `imdb.load_data` without setting `oov_char=None`, so it looks like it'll replace rare words with `oov_char`, not drop them.

If someone can confirm that these are indeed mistakes, I can make a PR to fix...

**Comment by ghego** [comment]
I ran into the same issue today and it seems that the current index is shifted by 3

```python
from keras.datasets import imdb
(X_train, y_train), (X_test, y_test) = imdb.load_data('/tmp/imdb.npz', num_words=None)
idx = imdb.get_word_index()
rev_idx = {v:k for k,v in idx.items()}

# deal with non-existing indices
for i in range(-3, 0):
    rev_idx[i] = '----'

' '.join([rev_idx[word-3] for word in X_train[0]])
```

not sure of the cause of this

**Comment by ghego** [comment]
After comparing the index with the one [here](https://ai.stanford.edu/~amaas/data/sentiment/) they seem to roughly correspond (although the keras index is shorter), so I think it's the numbers in the data that are shifted

**Comment by ghego** [comment]
The shift by 3 is introduced by the `index_from=3` argument in the `load_data` function: https://github.com/fchollet/keras/blob/master/keras/datasets/imdb.py#L94

**Comment by smokh004** [comment]
I got this error while I'm tryig to load the data. 

Traceback (most recent call last):
  File "BiLSTM.py", line 24, in <module>
    (x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)
  File "/usr/local/lib/python3.5/site-packages/keras/datasets/imdb.py", line 53, in load_data
    x_train = f['x_train']
TypeError: tuple indices must be integers or slices, not str
