### ISSUE TITLE
Input dimension mis-match. Pre-trained weights vgg16 Keras 1.2 and 2.0

### ISSUE THREAD

**Issue by bauer1331** [fchollet/keras#5915]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] (url) ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Error:
Every time I run this, in Keras 2.0.1 or Keras 1.2, with VGG16, VGG19, InceptionV3, a custom model, and with pre-resized images to 224. I can debug through other errors and am always left with this one. Same with Theano and Tensorflow.
The code runs without the weights, but with the weights of a pre-trained model I always get this error, [full code in gist](https://gist.github.com/bauer1331/3dab46ace692e42ccd5bad96c6b3e969). Please help.

```python
model_vgg16_conv = VGG16(include_top=False)
input = Input(shape=(3,224,224),name = ‘image_input’)
output_vgg16_conv = model_vgg16_conv(input)
x = Flatten(name='flatten')(output_vgg16_conv)
x = Dense(4096, activation='relu', name='fc1')(x)
x = Dense(4096, activation='relu', name='fc2')(x)
x = Dense(3, activation='softmax', name='predictions')(x)
my_model = Model(input=input, output=x)

my_model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy’])

my_model.fit_generator(
        train_generator,
        samples_per_epoch=32,
        nb_epoch=50,
        validation_data=validation_generator,
        nb_val_samples=32)


ValueError: Input dimension mis-match. (input[0].shape[1] = 3, input[1].shape[1] = 64)
Apply node that caused the error: Elemwise{Add}[(0, 0)](CorrMM{half, (1, 1), (1, 1)}.0, InplaceDimShuffle{x,0,x,x}.0)
Toposort index: 144
Inputs types: [TensorType(float32, 4D), TensorType(float32, (True, False, True, True))]
Inputs shapes: [(17, 3, 224, 225), (1, 64, 1, 1)]
Inputs strides: [(604800, 201600, 900, 4), (256, 4, 4, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{(i0 * (i1 + Abs(i1)))}}(TensorConstant{(1, 1, 1, 1) of 0.5}, Elemwise{Add}[(0, 0)].0), Elemwise{Composite{((i0 * i1) + (i0 * i1 * sgn(i2)))}}[(0, 1)](TensorConstant{(1, 1, 1, 1) of 0.5}, CorrMM_gradInputs{half, (1, 1), (1, 1)}.0, Elemwise{Add}[(0, 0)].0)]]

```

**Comment by Ubikas** [comment]
I receive the same error trying to reuse VGG weights to predict on my images with Keras 2.0.1. 
Theano 0.9.0
Keras 2.0.1 on python 2.7
Ubuntu 16.04
Computations run on GPU GTX 1080, Cuda 8.0, cuDNN 5110

This code used to work on Keras 1.2
`
import keras
from keras.applications import VGG16

vgg640 = VGG16(include_top=False, input_shape=(3,360,640), pooling='max')

#from here I have tried both cases with generator and without, none of it is working
gen=image.ImageDataGenerator()
batches = gen.flow_from_directory(<path>, batch_size=1, target_size=(360,640))
trn_batches = np.concatenate([batches.next() for i in range(batches.samples)])
trn_feat = vgg640.predict(trn_batches)

#with predict_generator
trn_batches = gen.flow_from_directory(<path>, batch_size=32, target_size=(360,640))
trn_feat = vgg640.predict_generator(trn_batches, steps=int(ceil(trn_batches.samples/batch_size)))
`
output:

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in predict(self, x, batch_size, verbose)
   1570         f = self.predict_function
   1571         return self._predict_loop(f, ins,
-> 1572                                   batch_size=batch_size, verbose=verbose)
   1573 
   1574     def train_on_batch(self, x, y,

/usr/local/lib/python2.7/dist-packages/keras/engine/training.pyc in _predict_loop(self, f, ins, batch_size, verbose)
   1200                 ins_batch = _slice_arrays(ins, batch_ids)
   1201 
-> 1202             batch_outs = f(ins_batch)
   1203             if not isinstance(batch_outs, list):
   1204                 batch_outs = [batch_outs]

/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.pyc in __call__(self, inputs)
   1092     def __call__(self, inputs):
   1093         assert isinstance(inputs, (list, tuple))
-> 1094         return self.function(*inputs)
   1095 
   1096 

/usr/local/Theano/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    896                     node=self.fn.nodes[self.fn.position_of_error],
    897                     thunk=thunk,
--> 898                     storage_map=getattr(self.fn, 'storage_map', None))
    899             else:
    900                 # old-style linkers raise their own exceptions

/usr/local/Theano/theano/gof/link.pyc in raise_with_op(node, thunk, exc_info, storage_map)
    323         # extra long error message in that case.
    324         pass
--> 325     reraise(exc_type, exc_value, exc_trace)
    326 
    327 

/usr/local/Theano/theano/compile/function_module.pyc in __call__(self, *args, **kwargs)
    882         try:
    883             outputs =\
--> 884                 self.fn() if output_subset is None else\
    885                 self.fn(output_subset=output_subset)
    886         except Exception:

ValueError: GpuElemwise. Input dimension mis-match. Input 2 (indices start at 0) has shape[1] == 64, but the output's size on that axis is 3.
Apply node that caused the error: GpuElemwise{Composite{(i0 * ((i1 + i2) + Abs((i1 + i2))))}}[(0, 1)](CudaNdarrayConstant{[[[[ 0.5]]]]}, GpuDnnConv{algo='small', inplace=True}.0, GpuDimShuffle{x,0,x,x}.0)
Toposort index: 252
Inputs types: [CudaNdarrayType(float32, (True, True, True, True)), CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, (True, False, True, True))]
Inputs shapes: [(1, 1, 1, 1), (32, 3, 360, 641), (1, 64, 1, 1)]
Inputs strides: [(0, 0, 0, 0), (692280, 230760, 641, 1), (0, 1, 0, 0)]
Inputs values: [CudaNdarray([[[[ 0.5]]]]), 'not shown', 'not shown']
Outputs clients: [[GpuContiguous(GpuElemwise{Composite{(i0 * ((i1 + i2) + Abs((i1 + i2))))}}[(0, 1)].0)]]

**Comment by nikita-astronaut** [comment]
I also got this error. Have you managed to overcome it?

**Comment by sakira** [comment]
Theres a discussion about this one: https://github.com/fchollet/keras/issues/6295
