### ISSUE TITLE
Keep docs for older versions on keras.io

### ISSUE THREAD

**Issue by alex-at-thimble** [fchollet/keras#5918]
The docs on keras.io seem to always refer to the latest released version of keras.  I'm not sure if it says anywhere explicitly which version they refer to. 

Now that we have a new version (2.0) which has a fairly different API, people who are still using the old version may be looking up things online and not realize the rather important version mismatch.  This happened to me, so I'm posting this issue here.

I suggest versioning the docs in the same way as scikit-image does it.  See http://scikit-image.org/docs/stable/  

Concretely, https://keras.io/ would contain the docs for the latest release version, and older versions would be at (for example) https://keras.io/1.2.2/  etc.  The latest github version could be at https://keras.io/dev/ There could be a navigation menu (for example a pulldown) for selecting the version.

**Comment by Givemeyourgits** [comment]
Ran into this same problem just now, totally agree here.

**Comment by faroit** [comment]
I don't think this will ever happen, so I created a repo that hosts old documentations of keras: 

https://faroit.github.io/keras-docs/
