### ISSUE TITLE
K.learning_phase:0 doesnt work after loading from Tensorflow checkpoint

### ISSUE THREAD

**Issue by jihopark** [fchollet/keras#5923]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi, I am using Keras layers for my Tensorflow model following this tutorial (https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html)

I am saving my model into a checkpoint file using `tf.Saver` and loading it back. I have a dropout layer in my model, so I am setting the `K.learning_phase:0` for testing. However, it seems like it is not getting the key-value from the feed_dict.
```
saver = tf.train.import_meta_graph(log_path + file_name + ".meta", clear_devices=True)
graph = tf.get_default_graph()

pred_op = graph.get_operation_by_name("prediction/prediction")
# placerholders
labels = graph.get_tensor_by_name("input/labels:0")
X = graph.get_tensor_by_name("input/X:0")

with tf.Session(config=session_conf) as sess:
    K.set_session(sess)
    saver.restore(sess, log_path + file_name)
    feed_dict = {
        labels: y_test,
        X: x_test,
        K.learning_phase(): 0
    }
    pred = sess.run(pred_op, feed_dict)
```
I am getting the Error:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'nn-layers/fully-connected-layer-0/dropout_1/keras_learning_phase' with dtype bool`

This is quiet strange since setting the learning_phase=0 was working very well when the model was training and evaluating.

+ I tried to save the checkpoint file after setting K.set_learning_phase(0) but still does not work.

**Comment by mqne** [comment]
I am running into what I suppose to be at least a related problem.

I created a tensorflow model making use of the K.learning_phase() flag like this: 

`return tf.cond(K.learning_phase(),
                               true_fn=lambda: 1,
                               false_fn=lambda: -1.)`

When building the model from code, and then running it via `sess.run(..., feed_dict={...,
                                                                                     K.learning_phase(): 1})`, the model behaves as expected. However, when I load the same model from a tensorflow checkpoint created and loaded via a `tf.train.Saver`, `-1` is returned independently of which value is fed to `K.learning_phase()`.
