### ISSUE TITLE
Keras 2 is probably incompatible with some CPU & Out of Memory

### ISSUE THREAD

**Issue by minghao-wu** [fchollet/keras#5924]
Here is the main info of my workstation:
Ubuntu 16.04
i7-6850k
64GB memory
NVIDIA TITAN X PASCAL
tensorflow 1.0.1
keras 2

I tested both tensorflow-cpu and tensorflow-gpu, and they work perfectly well.
However, when I ran keras on top of both tensorflow-cpu and tensorflow-gpu, the memory blows out within a few seconds and the process was killed like following. 

> Epoch 1/20
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:4b:00.0
Total memory: 11.90GiB
Free memory: 11.34GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0: Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:4b:00.0)
Killed

**Comment by Ubikas** [comment]
Hi,

I had the same problem, I guess it could help you:
[](http://stackoverflow.com/questions/41293077/how-to-compile-tensorflow-with-sse4-2-and-avx-instructions)

Probably you should rerun /.configure and on the final steps make a build on instructions provided in the link above.
[](https://www.tensorflow.org/install/install_sources)

**Comment by HareeshBahuleyan** [comment]
I face the same issue of model.fit() running out of memory when using Keras 2.02 with Theano backend.  It was working fine in Keras 1.2.

**Comment by minghao-wu** [comment]
@Ubikas 

thank you for your information, but I installed tensorflow using native pip within anaconda2. When I moved to the tensorflow folder (cd anaconda2/lib/python2.7/site-packages/tensorflow) and tried to run ./configure or ./configure, but an error "No such file or directory" was reported.

Since I cannot run /.configure, I am unable to make a build using bazel (an error: The 'build' command is only supported from within a workspace.). 

So, do you have any suggestion?

Thank you very much.

**Comment by Ubikas** [comment]
@minghao-wu ,

you have to run build in the same dir where it is located, you have to navigate to tensorflow source dir on your pc and run build with all necesary options. Site-packages dir contains already compiled packages. Source dir is where you clone/download tensorflow source. Good luck ;)

**Comment by minghao-wu** [comment]
@Ubikas 
I dont what happened, but today when i tried to reinstall keras using native "pip", the problem was fixed.

just "pip install keras".

Thank you for your luck. ;-)
