### ISSUE TITLE
Network with shared weights and a max function

### ISSUE THREAD

**Issue by superhans** [fchollet/keras#593]
Hi Guys

I'm building this slightly wierd looking neural network with Keras, of course. I was wondering if I could get some help in it's construction. 

The input is of size n_samples x n_channels x dim_1 (for example : 1000 samples of 2 channel audio signals, each channel is of dimension 128).

Now, I'll describe how each sample is processed : I multiply each channel of a sample with a common set of weights (which we need to learn). In our specific case, we get, 2 channels, each of dimension dim_2 (say 256)

Then, I take the max of this 2x256 signal per column (each column has two rows, right, so I pick the max amongst the two), to get a 1x256 vector. I send this through a softmax, which is used to compute the error for backprop.

Can I implement this with Keras ? Does something like the code below do what I want ?

```
model = Sequential()                                                 
model.add(Convolution1D(dim_1,dim_2,1,init='uniform'))           
model.add(Activation('relu'))                                        
model.add(Convolution1D(dim_2,n_classes,1,init='uniform'))     
model.add(MaxPooling2D(poolsize=(n_channels,1),ignore_border=False)) 
model.add(Flatten())                                                 
model.add(Activation('softmax'))                                     
```

**Comment by EderSantana** [comment]
Try this:
```python
model = Sequential()                                                 
model.add(Convolution1D(dim_1,dim_2,1,init='uniform'))           
model.add(Activation('relu'))                                        
model.add(Convolution1D(dim_2,n_classes,1,init='uniform'))     
model.add(MaxPooling2D(poolsize=(n_channels,1),ignore_border=False)) 
model.add(Flatten())                                                 
model.add(Activation('softmax'))    
### Testing helps
X = model.get_input()
Y0 = model.layer[0].get_output()
Y3 = model.layer[3].get_output()
F = theano.function([X], [Y0, Y1], allow_input_downcast=True)

x = np.array( `size a values that I know the output for` )
y0, y3 = F(x)
print y0.shape
print y3.shape
```
So, I believe this net does what you want. But with a code like the one above you will be able answer even more questions ;)

**Comment by superhans** [comment]
Hey, thanks for your reply. The interesting thing is that it works (compiles and runs without errors) on CPU, but on the GPU, it gives the error "ValueError: GpuDownsampleFactorMax: last dimention size of 2001 is bigger then 512. This case is not implemented.". In my case, the output layer is a 2001 size softmax. It looks like the solution is to install cuDNN (I think)

**Comment by YuqiCui** [comment]
Hey, have you solve the dimension problem by cuDNN? I face the same problem with you, and don't know how to do with it

**Comment by stmax82** [comment]
I just ran into the same error ("GpuDownsampleFactorMax: last dimention size of 2001 is bigger then 512.") with a similar piece of code. I think the error comes from theano, not keras. It seems like MaxPooling2D does not like data with a dimension size > 512.

The error only happens when you run it on a GPU **without** cuDNN. It works fine when you run it on a GPU **with** cuDNN or on a CPU.

Also it works when you replace MaxPooling2D with MaxPooling1D.. the 1D function seems to be able to process bigger dimension sizes.

**Comment by nouiz** [comment]
In the new gpu back-end, I think we support it without cudnn.
