### ISSUE TITLE
Embedding and clip_norm with TensorFlow: unsupported operand type(s) for *: 'IndexedSlices' and 'float'

### ISSUE THREAD

**Issue by maremoto** [fchollet/keras#5945]
Hi,

This stems from an old issue #3859, that was fixed by @kracwarlock but has still not being deployed for Keras 2.0 because there is a pending decision from @fchollet:.

- do changes to the backend as was in the initial commits in the former PR
or
- using the backend specific code solution he (@fchollet) suggested later and which he reviewed

THE PROBLEM DESCRIPTION:

Everytime clip_norm feature is used for an Embedding layer in a training with TensorFlow, this error shows up:  **unsupported operand type(s) for : 'IndexedSlices' and 'float'.**

THE ENVIROMENT:

- Keras 2.0
- TensorFlow 1.0.0

Thanks a lot.

**Comment by ViktorM** [comment]
Are there any progress with this bug? It's a very serious error that hasn't been fixed for almost a half of the year, Clipnorm is important for training RNN's models.

**Comment by kracwarlock** [comment]
my previous patch and the above decision is mentioned at  #4915

**Comment by ViktorM** [comment]
Thanks @kracwarlock! Hope it'll be merged soon. It's a bit sad that such a serious and in the same time simple to fix bug neither have been fixed by author nor any fix from contributors was accepted.
