### ISSUE TITLE
'module' object has no attribute '_set_session'

### ISSUE THREAD

**Issue by ktamiola** [fchollet/keras#5947]
Keras 2.0.2
Tensorflow 0.12.1

Trying to address the specific GPU with the following code:
```
import keras.backend.tensorflow_backend as K

with K.tf.device('/gpu:1'):
    K._set_session(K.tf.Session(config=K.tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)))
    model = Sequential()
   # define the rest of your model here...
    model.compile(loss='mse', optimizer='adam')
```
got,
```
      3 with K.tf.device('/gpu:1'):
----> 4     K._set_session(K.tf.Session(config=K.tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)))
      5     model = Sequential()
      6    # define the rest of your model here...

AttributeError: 'module' object has no attribute '_set_session'
```

**Comment by ktamiola** [comment]
Apologies. This is a trivial mistake on my end.

**Comment by wasi069** [comment]
hi Bro, can you please help me how you sort out this issue.

thanks in advance

**Comment by Yaolinwang** [comment]
The problem is the **K._set_session** should be **K.set_session**. After removed _ before set_session, problem solved. @wasi069

**Comment by taposh** [comment]
@ktamiola I am using keras 2.2.2 and getting the same error.

`%watermark -n -v -m -p keras
from keras import backend as K
K.set_session`

Tue Sep 11 2018 

CPython 2.7.13
IPython 5.3.0

keras 2.2.2

compiler   : GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)
system     : Darwin
release    : 15.6.0
machine    : x86_64
processor  : i386
CPU cores  : 8
interpreter: 64bit
`Error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-5903f2fb2668> in <module>()
      1 get_ipython().magic(u'watermark -n -v -m -p keras')
      2 from keras import backend as K
----> 3 K.set_session

AttributeError: 'module' object has no attribute 'set_session'
`
