### ISSUE TITLE
What if the input and output of the layer are the middle computational values of the previous layer?

### ISSUE THREAD

**Issue by NancyZxll** [fchollet/keras#595]
My DNN structure is as follows:
![layerstructre](https://cloud.githubusercontent.com/assets/4602226/9456712/c928877e-4b0d-11e5-85ac-a3eeee3b3630.png)

So the current problem is:
For graph model, I use, for example:
history = graph.fit({'input1':X_train, 'input2':X2_train, 'output':y_train}, nb_epoch=10) (from keras.io)
to define each input and output

In my structure, I should use:
model.fit({'input1':X_train, 'input2':ChangeFormat1(a), 'input3':ChangeFormat2(a),'input4':ChangeFormate3(a),'output1':how to describe?,'output2':y_train}, nb_epoch=10) 

However, for my input2-4 and output1, they are the intermediate computing value of input1, NOT the real output of layer1 (I need re-formate the output of layer1 as the real input of layer2)

How to describe them? I don't know how to illustrate such input and output.

**Comment by rex-yue-wu** [comment]
If it is not an actual output, you should use add_node instead. For example, something like this

```python
model = Graph();
model.add_input( name='input');
model.add_node( Convolution2D( xxxx ), name='ChangeFormat1(a)', input='input' );
model.add_node( Convolution2D( yyyy ), name='ChangeFormat1(b)', input='input' );
model.add_node( Convolution2D( zzzz ), name='ChangeFormat1(c)', input='input' );
model.add_node( Flatten(), name='flatten', inputs=['ChangeFormat1(a)','ChangeFormat1(b)','ChangeFormat1(c)'])
model.add_output(name='output', input='flatten');

model.fit( {'input': X_train, 'output': y_train})
```

**Comment by NancyZxll** [comment]
I see, I should delete the model.add_output between flatten and convolution2D.
Thank you !

So my current model structure is:
![layerstructure1](https://cloud.githubusercontent.com/assets/4602226/9462368/eb9e47f0-4b47-11e5-9c5a-50710b1470bb.png)


Can I write the code like this?
<code>
model = Graph();
model.add_input( name='input');
model.add_node(Convolution2D(Layer1), input='input');
model.add_node( Convolution2D( 1stLayer2 ), name='ChangeFormat(a)', input='input1' );
model.add_node( Convolution2D( 2ndLayer2 ), name='ChangeFormat(b)', input='input2' );
model.add_node( Convolution2D( 3rdLayer2 ), name='ChangeFormat(c)', input='input3' );
model.add_node( Flatten(), name='flatten', inputs=['ChangeFormat(a)','ChangeFormat(b)','ChangeFormat(c)'])

model.add_output(name='output', input='flatten');


a=model.layers[0].get_output()
for i in range(3):
            length1=int(layerLen-nb_col-aaQuaInt[i])
            length2=int(nb_col+aaQuaInt[i])
            X1= a[:,:,:,0:int(length1)]
            X2= a[:,:,:,length2:]
            X3[:,:,0,:]=X1
            X3[:,:,1,:]=X2
            if i==0:
                 I1=X3
            elif i==1:
                 I2 =X3
            else:
                 I3 = X3

model.fit( {'input': X_train, 'input1':I1, 'input2': I2, 'input3': I3, 'output': y_train})
</code>

My concern is the inputs 1-3 are the intermediate values of the output of the first Conv Layer.
I don't know whether I am allowed to do this..
