### ISSUE TITLE
Data preparation takes too much memory -  LSTM 

### ISSUE THREAD

**Issue by HackerzWorkshop** [fchollet/keras#5951]
Hi, 

I have a time series data as 2D array which I want to give as an input to the LSTM and my problem is that LSTM needs a 3D array as input. Suppose my data is a sequence of _n_ rows with _m_ features and I want to train on _k_ timesteps,  is there a way to feed it the data without redundant shifting and copying each row _k_ times?

BR.

**Comment by sallamander** [comment]
@HackerzWorkshop Would [RepeatVector](https://github.com/fchollet/keras/blob/3a666b497db59491d71ce671e3b01af90332e8b9/keras/layers/core.py#L498) work in this scenario?

**Comment by fchollet** [comment]
One way to do this is to write a Python generator that yields batches of data extracted on the fly from your timeseries.

e.g.

```python
def generator(data, targets, lookback, delay, min_index, max_index, shuffle, batch_size, step):
    if max_index is None:
        max_index = len(data) - delay - 1
    i = min_index + lookback
    while 1:
        if shuffle:
            rows = np.random.randint(min_index + lookback, max_index, size=batch_size)
        else:
            if i + batch_size >= max_index:
                i = min_index + lookback
            rows = np.arange(i, min(i + batch_size, max_index))
            i += len(rows)

        samples = np.zeros((len(rows), lookback // step, data.shape[-1]))
        targets = np.zeros((len(rows),))
        for j, row in enumerate(rows):
            indices = range(rows[j] - lookback, rows[j], step)
            samples[j] = data[indices]
            targets[j] = targets[rows[j] + delay]
        yield samples, targets
```

You can then fit with `fit_generator`.
