### ISSUE TITLE
error merge.add tensor with a tf.constant tensor

### ISSUE THREAD

**Issue by Hong-Xiang** [fchollet/keras#5955]
When adding a constant tensor create by `tf.zeros()`
```
a = tf.zeros([batch_size]+list(input_shape))
b = ...(output of some layers)
c = add([a, b])
# a.shape = [batch_size, x, y, c]
# b.shape = [None, x, y, c]
```

raises following error:
```
ValueError: Only tensors of same shape can be merged by layeradd_1 Got input shapes: [(None, 216, 176, 1), (8, 216, 176, 1)]
```
Thus we can not add a constant to a tensor, even given right `batch_size`, since the error is raised during compile time.

**Comment by joelthchao** [comment]
PR #5812 might allow you to broadcast tensor with different shape.
If your constant is a scalar, why not try this:
```python
a = 10
b = ... (output of some layers)
c = Lambda(lambda x: x + a) (b)
```

**Comment by eyaler** [comment]
Lambda layer does not load well on different platforms
