### ISSUE TITLE
AttributeError: 'module' object has no attribute 'concatenate'

### ISSUE THREAD

**Issue by linamede** [fchollet/keras#5964]
I was checking the "Multi-input and multi-output models" in https://keras.io/getting-started/functional-api-guide/

and by executing the line 

x = keras.layers.concatenate([lstm_out, auxiliary_input])
It gives me the error:

AttributeError: 'module' object has no attribute 'concatenate'

I could not find why this does not work in Google.
Any suggestions?

Thank you

**Comment by joelthchao** [comment]
Please update to Keras 2
