### ISSUE TITLE
Variational autoencoder example does not converge with TensorFlow backend

### ISSUE THREAD

**Issue by pnb** [fchollet/keras#5968]
The simple variational autoencoder on MNIST digits example (https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py) does not converge. It converges with Keras 1.2.1.

I am using the CPU TF backend on OSX 10.12.3.

### Steps to reproduce

1. Copy the example code from https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py
2. Revert to old version of Keras (1.2.1)
`pip install keras==1.2.1`
3. Slightly tweak example code to run on Keras 1.2.1, replacing `stddev` with `std` and `epochs` with `nb_epoch`
`cat variational_autoencoder.py | sed 's/stddev=/std=/g' | sed 's/epochs=/nb_epoch=/g' > variational_autoencoder_1.2.1.py`
4. Run example
`python variational_autoencoder_1.2.1.py`
Example training loss monotonically decreases, ending at approximately 150. Validation loss tends to decrease, ending around 153 last time I tried it. Great!
5. Upgrade to newest Keras
`pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps`
6. Run example
`python variational_autoencoder.py`
Training loss decreases for approximately 6 epochs, reaching about 165, then diverges. It ended around 240 a couple times I tried it, and once actually went to infinity. Not great! Validation loss follows suit. The digit visualizations look wrong as well.

### What I've done to investigate
I thought it might have something to do with the `vae_loss()` function, so I looked through the TF backend code history on GitHub to see if `binary_crossentropy()` function might have changed, but it looks functionally the same. It moved from _objectives_ to _losses_, but that's about it.

I looked at `random_normal()` as well since the signature had changed, but didn't see anything suspicious there.

**Update:**
I tried the Theano backend with the latest Keras and it _does_ converge, which suggests it might have something to do with keras/backend/tensorflow_backend.py.

**Update 2:**
I also tried the other VAE example (https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder_deconv.py) and it too does not converge with the TF backend but does with the Theano backend.

### Checklist

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by xkortex** [comment]
I too am running into a lot of issues with my VAEs once I switched to 2.0. It doesn't help that the [deconv vae](https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder_deconv.py) 4aa4162   is also currently not working for me. 

That one works until I run `fit`, then I get

`ValueError: The model expects 0 input arrays, but only received one array. Found: array with shape (10000, 28, 28, 1)`

With my older model, I'm getting divergence in both TF and Theano. A tried-and-true deconvo VAE (can't remember exactly, but I think it was based on 8fab33c245208f9c39f55292af9773574d891a16, on `keras==1.2.0`) which I know converges to a loss of about 160 on MNIST,  now on `2.0.3` blows up to -400000 and the output just gets all goofy.

**Comment by pnb** [comment]
@xkortex I did not manage to figure out what tweaks you made to [this version](https://github.com/fchollet/keras/blob/8fab33c245208f9c39f55292af9773574d891a16/examples/variational_autoencoder_deconv.py) to get it to work. I get:

`InvalidArgumentError (see above for traceback): Incompatible shapes: [72900] vs. [78400]`

This was after converting to eliminate all API warnings. Could you share what you've done to get it to converge?

I re-checked my initial problem with the new Keras (2.0.3) but the result remains the same. Both example VAEs converge using Theano and diverge using TF. Interestingly, I do not see your ValueError problem appear.

**Comment by xkortex** [comment]
@pnb OH! I actually just figured out the incompatible shapes error, on another project I'm working on. It seems to occur in the last convo layer of the autoencoder. There is a difference between padding='valid' vs padding='same' in Keras 1.2 vs 2.0, which results in an output shape of 28x28 in K1.2 but 27x27 in K2.0. Gonna tinker more when I get home, but I think that aspect should be sorted out, and I can test the divergence in 2.0.3.

**Comment by xkortex** [comment]
So...

[DC-VAE from v2.0.2](https://github.com/fchollet/keras/blob/2.0.2/examples/variational_autoencoder_deconv.py) works on K2.0.2 (as expected)
[DC-VAE from v1.2.0 with modifications](https://github.com/xkortex/VAE_Lab/blob/master/vae_v120.ipynb) works on K2.0.2. The trick was to change [decoder_mean_squash](https://github.com/fchollet/keras/blob/1.2.0/examples/variational_autoencoder_deconv.py#L91) from `border_mode='valid'` to `'same'`, and keyword [std](https://github.com/fchollet/keras/blob/1.2.0/examples/variational_autoencoder_deconv.py#L55) to `stddev`. Maybe one other API-related error but it should be pretty obvious.

Now to upgrade Keras to 2.0.3 and see what breaks.

**Comment by xkortex** [comment]
[Here is my branch for testing on K2.0.3](https://github.com/xkortex/VAE_Lab/tree/keras_203). I found I was having issues with the VAE2.0.3, so I re-copied it from github, and now it works fine. 

VAE v120 on K203 - works
VAE v202 on K203 - works. 

VAE v203 on K203 - now it works without error for me. Must've had a typo or something on my last attempt. Ran it for 10 epochs and it converged. 

Late last night I figured out that the exploding negative error seemed to be stemming from forgetting to convert the MNIST numpy array to float32.

**Comment by pnb** [comment]
@xkortex I have also been able to get the deconv VAE to converge with TF now. Apparently there is just a random chance of it not converging. It seems like if the loss is > 200 on the first epoch it will never converge, but otherwise it will.

However, I still have had zero luck getting the simpler VAE example to converge with the TF backend, which has me quite concerned about trusting the TF backend for any of my own VAE tasks. Have you been able to get that one to converge?

**Comment by xkortex** [comment]
@pnb You mean the [vanilla autoencoder](https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py) as opposed to DC-VAE? Yeah I was able to converge that pretty reliably. Final loss ~ 149 after 50 epochs. 

Did you try different seed values? If you can find a seed value that causes it to bork, then I can try that on my system.

**Comment by pnb** [comment]
@xkortex Yes, that's the one. Thanks for trying it! I don't think it is a seed value issue for me, as it diverges in 100% of my tests with the TF backend but converges 100% of the time with the Theano backend. I'm going to try it out on another computer later today if I can.

**Comment by xkortex** [comment]
@pnb What tensorflow are you using? I'm using `tensorflow-gpu==1.0.1`. Haven't tried Theano much because I don't have theano+gpu set up yet.

**Comment by pnb** [comment]
@xkortex I was using tensorflow 1.0.0 CPU-only up until seconds ago when I realized 1.1.0 is out now (I think just today?). I updated and tried again but it still diverged after 13 epochs. Maybe it has to do with GPU vs. CPU? Unfortunately I don't have a compatible GPU to test it on at the moment.
