### ISSUE TITLE
Conv1D and Conv2DTranspose use "channels_last" as default data_format not None.

### ISSUE THREAD

**Issue by JihongJu** [fchollet/keras#5974]
Now the `Conv1D` layer and `Conv2D` layer are using "channels_last" as their default `data_format` instead of `None` as the other layers.
See [Conv1D init](https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L319) and [Conv2DTranspose init](https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L680).

This leads to an issue where these two layers' default data format won't change automatically with respect to the backend `image_data_format()` settings as the other layers.

I wonder is there a specific reason for this. Otherwise, it seems less confusing if these two layers have consistent default `data_format` as the other layers.

**Comment by joelthchao** [comment]
`data_format` in `Conv1D` is not used, so it's fine. But in `Conv2DTranspose`, it should be set to `None`.
