### ISSUE TITLE
How can I install Keras 1.0?

### ISSUE THREAD

**Issue by small-1003** [fchollet/keras#5977]
I use 'pip install keras' to install keras, but I got keras 2.0.2.
I want to use keras 1.0, so I wonder how I can install keras1.0.
Thank you so much!

**Comment by abhaikollara** [comment]
Download the required archive from https://github.com/fchollet/keras/releases and extract it. You can then install by running `pip install .` or `python setup.py install` from the extracted folder.

**Comment by small-1003** [comment]
It worked！ Thank you！
