### ISSUE TITLE
Recurrent layer not accepting multiple inputs list despite source code seemingly handling such case

### ISSUE THREAD

**Issue by fferroni** [fchollet/keras#5986]
Hello,

Reading the source code for Recurrent.py, it would appear that a layer like LSTM would be able to accept multiple input tensors. In call() of Recurrent, I see an option like `ifinstance(inputs, list)` then it will pick the first element of that list to be the input data tensor, and the rest as initial_states presumably.

https://github.com/fchollet/keras/blob/ec9c95fdbd60c2d86288858563c57b0007b24430/keras/layers/recurrent.py#L263
```
 def call(self, inputs, mask=None, initial_state=None, training=None):
        # input shape: `(samples, time (padded with zeros), input_dim)`
        # note that the .build() method of subclasses MUST define
        # self.input_spec and self.state_spec with complete input shapes.
        if initial_state is not None:
            if not isinstance(initial_state, (list, tuple)):
                initial_states = [initial_state]
            else:
                initial_states = list(initial_state)
        if isinstance(inputs, list):
            initial_states = inputs[1:]
            inputs = inputs[0]
```

However, if I run a simple script like such
```
import numpy as np
from keras.models import Model
from keras.layers import LSTM, Input

data_input = Input(shape=(10,5))
time_input = Input(shape=(10,1))

asynchronous = LSTM(15)([data_input, time_input])
model = Model(inputs=[data_input, time_input], outputs=asynchronous)
```

I get the following exception:

```
Traceback (most recent call last):
  File "ras.py", line 24, in <module>
    main()
  File "ras.py", line 16, in main
    asynchronous = LSTM(15)([data_input, time_input])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/recurrent.py", line 252, in __call__
    return super(Recurrent, self).__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 511, in __call__
    self.assert_input_compatibility(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 401, in assert_input_compatibility
    str(input))
ValueError: Layer lstm_1 expects 1 inputs, but it received 2 input tensors. Input received: <built-in function input>
```

I am actually trying to write a custom layer which requires two input tensors than inherits from Recurrent, but I am not sure whether I need to change the Recurrent class as well at this point... from the source code it would appear it can accept a list, and it would just use the first element of that list as the main input tensor. Can someone clarify?

**Comment by Joshua-Chin** [comment]
This will be fixed by #5795. We're currently waiting for someone to review it.

**Comment by jmhessel** [comment]
FYI, for folks reading this -- I was running into some trouble with RNNs not accepting multiple inputs. Turns out the solution was to modify the input_spec, i.e., do: `self.input_spec = [InputSpec(ndim=3), InputSpec(ndim=...)]`

**Comment by aviziskind** [comment]
This still appears to be an issue (I'm using keras 2.0.8). I have implemented my own layer that inherits from recurrent, but get a similar error when I try to pass in multiple inputs as a list.  I did specify the input_spec when I initialize the layer as @jmhessel suggested, but this does not help. The issue first arises in the following lines of code from recurrent.py from __call__:


```
    def call(self, inputs, mask=None, training=None, initial_state=None):
        # input shape: `(samples, time (padded with zeros), input_dim)`
        # note that the .build() method of subclasses MUST define
        # self.input_spec and self.state_spec with complete input shapes.
        if isinstance(inputs, list):
            initial_state = inputs[1:]
            inputs = inputs[0]
        elif initial_state is not None:
            pass
        elif self.stateful:
            initial_state = self.states
        else:
            initial_state = self.get_initial_state(inputs)
```
The assumption in these lines of code is that if the input is a list, then the input is the first element in the list, and the following items are the initial state (even if the initial_state is specified explicitly). I tried modifying this function to remove this assumption (ie. not split up the inputs in this way if the initial_state is specified), but then an error gets raised a few lines later during the call to rnn (tensorflow_backend.py, line 2332, at the beginning of the function:
```
def rnn(step_function, inputs, initial_states,
        go_backwards=False, mask=None, constants=None,
        unroll=False, input_length=None):
    """Iterates over the time dimension of a tensor.
...
# inputs: tensor of temporal data of shape `(samples, time, ...)`  # <-- confirming the assumption that a single tensor is expected.
#            (at least 3D).
...
ndim = len(inputs.get_shape())    # <-- raises the error: "AttributeError: 'list' object has no attribute 'get_shape'"
```
which again assumes that inputs is a single tensor, and not a list of inputs, an assumption that I see is present in the rest of that function as well, including the . Can I conclude that the recurrent layer does not support multiple inputs in the form of a list, or am I missing something?
