### ISSUE TITLE
keras.layers.merge usage unclear in keras2 and "'function' object has no attribute 'concatenate'"

### ISSUE THREAD

**Issue by pasky** [fchollet/keras#5988]
I'm now migrating to keras2 and I find the documentation and hints regarding `keras.layers.merge` unclear:

- The hint says "Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.", however the layers actually have their names capitalized, perhaps the hint is meant to use capitalized initials or say "functions" instead of "layers".

- My naive attempt to use the functional interface was
```
import keras.layers.merge as m  # or even better, "...as merge"
features = m.concatenate(feature_list, name='merged_features', axis=channel_axis)
```
but I get the error `AttributeError: 'function' object has no attribute 'concatenate'`. I think the issue is that this imports the legacy `merge` wrapper. I don't know if this has a good solution but it'd be great to be more verbose about this in the new documentation, and I think many people will not be excited about importing non-namespaced globals like "add", "dot" or "maximum".

**Comment by jjboo** [comment]
The examples in tests/keras/layers/merge_test.py might be of interest.

**Comment by farizrahman4u** [comment]
>  I think many people will not be excited about importing non-namespaced globals like "add", "dot" or "maximum".

You can import `keras.layers` and use `layers.add`, `layers.maximum` etc.

**Comment by pasky** [comment]
That's good to know (though it looks a bit strange in code), thank you!
It'd be great to document this.

**Comment by MarkSeygan** [comment]
For me, even with capitalized layer names -> AttributeError: 'function' object has no attribute 'Add'.
Even though this is not stack QA, for a quick solution: use deprecated merge till 08/2017: 
`residual = keras.layers.merge([conv, input], mode='sum')`

**Comment by Miail** [comment]
I am still a bit confused on what the new API suggest to do, when two tensor has to be merged, as in concatenation or add?  @MarkSeygan  solution works, but if that will be deprecated, what is the solution then?
