### ISSUE TITLE
Should we not be taking the mean in the weighted_objective?

### ISSUE THREAD

**Issue by wxs** [fchollet/keras#600]
I'm getting concerned that we should not be applying a mean to the objective function in a mini-batch, because it means that mini-batches with more labels effectively have their labels downweighted.

Here is the relevant line `weighted_objective`

```
return weighted.sum() / (filtered_mask * filtered_weights).sum()
```

and also:

```
return weighted.sum() / filtered_weights.sum()
```

Originally we always applied a `mean()` to objective functions, so when I created the `weighted_objective` I kept using a mean, just now a weighted mean. However here's why I think this is wrong:

say 99% of my data is labeled A, and 1% is labeled B. I want to train with class-counts renormalized, so I apply a class_weight of 1/99 to class A. However say my mini-batches are of size 10: 90% of these will consist only of class A, so every single loss in the batch will be weighted by 1/99, so when I take the weighted mean (by dividing by the sum) I get the same as if they were all weighted 1. This will obviously not have the desired effect of treating class A and class B as though they had an equal number of training examples.

I think the correct answer is to eschew the normalization completely and replace both of these with:

```
return weighted.sum()
```

I'm a bit nervous about the interaction with masking though, because there was some discussion on another issue (I can't find it at the moment) that was arguing that we _need_ to scale the outputs in the event that there are fewer due to masking.

**Comment by fchollet** [comment]
It does seem like a significant issue when dealing with unbalanced classification problems. 

> `return weighted.sum()`

We should at least divide by the number of samples (instead of dividing by the sum of the weights as we were previously). The number of samples in a batch is actually a variable (the last batch is usually smaller), which is especially true when training batch by batch on heterogenous batches.

> I'm a bit nervous about the interaction with masking though, because there was some discussion on another issue (I can't find it at the moment) that was arguing that we need to scale the outputs in the event that there are fewer due to masking.

Yes, this will definitely need clarification... 

Maybe we need to rewrite the weighting and masking system.

**Comment by wxs** [comment]
> Maybe we need to rewrite the weighting and masking system.

A rewrite is fine but I think it's orthogonal to this issue. The core question here is not software-architectural, it's mathematical: what is the correct behaviour when you have variable numbers of (potentially differently weighted) labels in a batch.

> We should at least divide by the number of samples (instead of dividing by the sum of the weights as we were previously). The number of samples in a batch is actually a variable (the last batch is usually smaller), which is especially true when training batch by batch on heterogenous batches.

I see your point here. What's tricky for me to wrap my head around is in the case of sequence-to-sequence learning how many "samples" to count it as. Do we divide by the length of the first dimension of the y-matrix? (i.e. `nb_samples` as it is often called in the docs) or do we divide by the product of the first two dimensions (`nb_samples*timesteps`). The latter feels a bit more correct to me.

Then: if it's sequence to sequence learning with variable length sequences, you will necessarily mask out some of your `y` matrix. Currently this masking is done via sample_weights. Perhaps the right answer is that we need to have a separate binary output_mask parameter, and when we do the division we divide by the number of ones in the output_mask.

Otherwise we would divide by the number of nonzero entries in sample_weight, but that causes a weird issue where sample_weights of `1e-9` and `0` have very different behaviours, because in both cases the entry's error is near 0, but in one it affects the normalization and in the other it doesn't.

**Comment by wxs** [comment]
To summarize, a bit more concretely: I think for now a correct solution would be:

    return weighted.sum() / (filtered_mask).sum()

in the input masked case, and 

    return weighted.sum() / (weights != 0).sum()

in the other case. But I don't like that this is a special case for weight 0, and so probably would advocate for having an `output_mask` parameter separate from the sample_weight and doing

    return weighted.sum() / output_mask.sum()

and

    return weighted.sum() / (output_mask * input_mask).sum()

when there's input masking.

**Comment by fchollet** [comment]
This sounds reasonable.

> But I don't like that this is a special case for weight 0

I don't think it's a big deal. Zero weight just means we ignore the sample entirely. Introducing `output_mask` seems cumbersome to me.

I think a 0 sample weight will basically never be used by anyone, so this is more a data sanitation issue than a feature.

**Comment by wxs** [comment]
> I think a 0 sample weight will basically never be used by anyone, so this is more a data sanitation issue than a feature.

It'll be used by me! And there have been quite a few people asking about output masking.

Or do I misunderstand and you are saying that 0 sample weight *will* be used, but always as a mask?

**Comment by fchollet** [comment]
The way I see it, if a sample weight is 0, the entire sample is completely ignored during training. So what are some use cases?

I believe output masking is about masking specific features in a sample (missing data), not ignoring entire samples (or what would these samples even be doing here in the first place?).

The way I see it, sample weights be scalars and should have a one to one mapping to samples.

**Comment by wxs** [comment]
> I believe output masking is about masking specific features in a sample (missing data), not ignoring entire samples

Ah I believe this is the source of confusion: currently sample_weight *is* the only way to mask within a sample. So maybe it should be named something different. 

> The way I see it, if a sample weight is 0, the entire sample is completely ignored during training. So what are some use cases?

in the case of an RNN with `return_sequences=True` sample_weight is used to weight *timesteps*, that is there are not `nb_samples` sample_weights, but in fact `nb_samples*timesteps` sample_weights.

In that use-case a sample_weight of 0 corresponds to an output that you want to ignore, so in sequence-to-sequence learning where the outputs are of different length, this is how you tell it which outputs are meaningful.

**Comment by wxs** [comment]
It wouldn't really make sense for a given sample_weight to apply to an entire sample instead of a single timestep, because then how would, for instance, class_weight work when you have a sample with two different classes at two different timesteps.

**Comment by fchollet** [comment]
Do you want to put up a PR with the changes you mentioned yesterday?

**Comment by wxs** [comment]
@fchollet I've been working with @cmyr on this one: we've been setting up a large-scale train. Took a while to work out the kinks, but he'll PR some code next week.
