### ISSUE TITLE
TimeDistributed With Resnet Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float

### ISSUE THREAD

**Issue by albu5** [fchollet/keras#6001]
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         (None, 9, 150528)         0         
_________________________________________________________________
reshape_1 (Reshape)          (None, 9, 224, 224, 3)    0         
_________________________________________________________________
time_distributed_1 (TimeDist (None, 9, 1, 1, 2048)     23587712  
_________________________________________________________________
reshape_2 (Reshape)          (None, 9, 2048)           0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 9, 256)            2360320   
_________________________________________________________________
dense_1 (Dense)              (None, 9, 2)              514       

W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Traceback (most recent call last):
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
    return fn(*args)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
    status, run_metadata)
  File "C:\lib\Anaconda3\envs\keras\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
	 [[Node: mul_1/_1527 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_66_mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/asd/Desktop/Ashish/BMVC/action_lstm_resnet.py", line 53, in <module>
    model.train_on_batch(X, Y)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\engine\training.py", line 1620, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\backend\tensorflow_backend.py", line 2073, in __call__
    feed_dict=feed_dict)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
    run_metadata_ptr)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
	 [[Node: mul_1/_1527 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_66_mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'input_1', defined at:
  File "C:/Users/asd/Desktop/Ashish/BMVC/action_lstm_resnet.py", line 27, in <module>
    resnet = ResNet50(weights='imagenet', include_top=False)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\applications\resnet50.py", line 195, in ResNet50
    img_input = Input(shape=input_shape)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\engine\topology.py", line 1388, in Input
    input_tensor=tensor)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\engine\topology.py", line 1299, in __init__
    name=self.name)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\backend\tensorflow_backend.py", line 349, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1502, in placeholder
    name=name)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 2149, in _placeholder
    name=name)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float
	 [[Node: input_1 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
	 [[Node: mul_1/_1527 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_66_mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_gpu_executor.cc:637] Deallocating stream with pending work

I'm running following code:

resnet = ResNet50(weights='imagenet', include_top=False)
print(resnet.summary())

input_layer = Input(shape=(seq_len, 224*224*3))
curr_layer = Reshape(target_shape=(seq_len, 224, 224, 3))(input_layer)
curr_layer = TimeDistributed(resnet)(curr_layer)
curr_layer = Reshape(target_shape=(seq_len, 2048))(curr_layer)
lstm_out = LSTM(256, return_sequences=True,
                activation='sigmoid', recurrent_activation='tanh',
                use_bias=True, unit_forget_bias=True)(curr_layer)
prediction_layer = Dense(2, activation=kb.softmax)(lstm_out)

model = Model(inputs=input_layer, outputs=prediction_layer)
optimizer = adam(lr=0.00001)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
print(model.summary())
X, Y = get_batch_image(train_dir, batch_size, seq_len)
print(X.shape, Y.shape)
model.train_on_batch(X, Y)

shapes of X,Y = (2, 9, 150528) (2, 9, 2)

**Comment by albu5** [comment]
from keras.models import Model
from keras.layers import Dense, Input, TimeDistributed, Reshape
from keras.layers import LSTM
from keras.layers import SimpleRNN
from keras.layers import Masking
import numpy as np
import matplotlib.pyplot as plt
import random
from keras import backend as kb
from keras.optimizers import adam
from utils import get_batch, get_immediate_subdirectories, get_batch_resnet, get_batch_image
from keras.applications.resnet50 import ResNet50
from keras.layers.core import K


K.set_learning_phase(0)


seq_len = 9
batch_size = 2
num_iter = 10000000
decay_step = 100
disp_step = 1

plt.ion()

resnet = ResNet50(weights='imagenet', include_top=False)
# print(resnet.summary())

input_layer = Input(shape=(seq_len, 224*224*3))
im_layer = Reshape(target_shape=(seq_len, 224, 224, 3))(input_layer)
res_out = TimeDistributed(resnet)(im_layer)
res_squeezed = Reshape(target_shape=(seq_len, 2048))(res_out)
lstm_out = LSTM(256, return_sequences=True,
                activation='sigmoid', recurrent_activation='tanh',
                use_bias=True, unit_forget_bias=True)(res_squeezed)
prediction_layer = Dense(2, activation=kb.softmax)(lstm_out)

model = Model(inputs=input_layer, outputs=prediction_layer)
optimizer = adam(lr=0.00001)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
print(model.summary())
data_dir = './ActivityDataset'
traj_dir = data_dir + '/' + 'TrajectoriesLong'
train_dir = traj_dir + '/' + 'train'

ex_dirs = get_immediate_subdirectories(train_dir)

acc_arr = []
for i in range(num_iter):
    X, Y = get_batch_image(train_dir, batch_size, seq_len)
    print(X.shape, Y.shape)
    model.train_on_batch(X, Y)
    score, acc = model.evaluate(X, Y, batch_size=batch_size, verbose=1)
    acc_arr.append(acc)
    print('Step:', i, 'Score: ', score, 'Accuracy:', acc)
    if (i % decay_step == 0) and i is not 0:
        kb.set_value(optimizer.lr, 0.5 * kb.get_value(optimizer.lr))
    if (i % disp_step == 0) and i is not 0:
        plt.plot(acc_arr)
        plt.pause(0.0005)

**Comment by rgobbel** [comment]
+1, I'm having the same problem. The feed dictionary for the whole sequence looks fine, but it never gets split up by TimeDistributed.

~~~~
def make_cycle_model():
    n_filter = 12
    filter_width = 3
    cycle_input = Input(shape=(SPOT_WIDTH, SPOT_WIDTH, N_CHANNELS))
    bn1 = BatchNormalization(input_shape=(SPOT_WIDTH, SPOT_WIDTH, N_CHANNELS))(cycle_input)
    conv1 = Conv2D(filters=n_filter, kernel_size=(filter_width, filter_width), activation='relu')(bn1)
    bn2 = BatchNormalization()(conv1)
    conv2 = Conv2D(filters=n_filter, kernel_size=(filter_width, filter_width), activation='relu')(bn2)
    bn3 = BatchNormalization()(conv2)
    flat = Flatten()(bn3)
    cycle_output = Dense(4, activation='softmax')(flat)
    return Model(inputs=cycle_input, outputs=cycle_output)

def make_seq_model():
    seq_input = Input(shape=(SEQ_LEN, WIDTH, WIDTH, 2), name='seq_input')
    cycle_model = make_cycle_model()
    td = TimeDistributed(cycle_model)(seq_input)
    lstm = Bidirectional(LSTM(SEQ_LEN*4, name='lstm'))(td)
    seq_out = Reshape((SEQ_LEN, 4), name='seq_out')(lstm)
    seq_model = Model(inputs=seq_input, outputs=seq_out)
    return seq_model

model = make_seq_model()
model.compile(loss={'seq_out': 'categorical_crossentropy'}, optimizer=OPTIMIZER,
      metrics=['accuracy'])
model.fit_generator(train_q.batch_generator(), steps_per_epoch=batches_per_epoch, epochs=FLAGS.max_epochs, verbose=FLAGS.verbose,
    validation_data=valid_q.batch_generator(), validation_steps=1)

~~~~

Output (sorry, not able to post the stack trace):
~~~~
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'batch_normalization_1_input' with dtype float
	 [[Node: batch_normalization_1_input = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
	 [[Node: Mean_3/_69 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1835_Mean_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
~~~~

**Comment by albu5** [comment]
I think time distributed has something wrong in the training phase. It works fine when testing.

**Comment by amn-gti-upm** [comment]
@albu5 I have implemented a similar network where the CNN needs two inputs: images (input1) that are passed to the CNN in the first layer, and 6-dimensional vectors (input2) that are concatenated with one of the last fully-connected layers. I solved this multi-input problem as Keras documentation says here: https://keras.io/getting-started/functional-api-guide/#multi-input-and-multi-output-models. I trained the CNN and it worked. Now I want to merge it with an LSTM, however I don't know how to pass these two inputs to TimeDistributed:

`...
cnn_model = get_cnn(img_height, img_width, img_channels, vec_dim, ...)

input1_layer = Input(shape=(seq_len, img_height, img_width, img_channels))
input2_layer = Input(shape=(seq_len, vec_dim))

cnn_out = TimeDistributed(cnn_model)(??????)
lstm_out = LSTM(256, return_sequences=True)(cnn_out)
...`

It seems it only accepts one input...

**Comment by andiconda** [comment]
> # Layer (type) Output Shape Param #
> input_2 (InputLayer) (None, 9, 150528) 0
> 
> reshape_1 (Reshape) (None, 9, 224, 224, 3) 0
> 
> time_distributed_1 (TimeDist (None, 9, 1, 1, 2048) 23587712
> 
> reshape_2 (Reshape) (None, 9, 2048) 0
> 
> lstm_1 (LSTM) (None, 9, 256) 2360320
> 
> dense_1 (Dense) (None, 9, 2) 514
> 
> W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:993] Invalid argument: You must feed a value for placeholder tensor 'input_1' with dtype float
> [[Node: input_1 = Placeholderdtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]]
> 
> Traceback (most recent call last):
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1022, in _do_call
> return fn(*args)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1004, in _run_fn
> status, run_metadata)
> File "C:\lib\Anaconda3\envs\keras\lib\contextlib.py", line 66, in **exit**
> next(self.gen)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
> pywrap_tensorflow.TF_GetCode(status))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float
> [[Node: input_1 = Placeholderdtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]]
> [[Node: mul_1/_1527 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_66_mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "C:/Users/asd/Desktop/Ashish/BMVC/action_lstm_resnet.py", line 53, in
> model.train_on_batch(X, Y)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\engine\training.py", line 1620, in train_on_batch
> outputs = self.train_function(ins)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\backend\tensorflow_backend.py", line 2073, in **call**
> feed_dict=feed_dict)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 767, in run
> run_metadata_ptr)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 965, in _run
> feed_dict_string, options, run_metadata)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1015, in _do_run
> target_list, options, run_metadata)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\client\session.py", line 1035, in _do_call
> raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'input_1' with dtype float
> [[Node: input_1 = Placeholderdtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]]
> [[Node: mul_1/_1527 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_66_mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]]
> 
> Caused by op 'input_1', defined at:
> File "C:/Users/asd/Desktop/Ashish/BMVC/action_lstm_resnet.py", line 27, in
> resnet = ResNet50(weights='imagenet', include_top=False)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\applications\resnet50.py", line 195, in ResNet50
> img_input = Input(shape=input_shape)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\engine\topology.py", line 1388, in Input
> input_tensor=tensor)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\engine\topology.py", line 1299, in **init**
> name=self.name)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\keras\backend\tensorflow_backend.py", line 349, in placeholder
> x = tf.placeholder(dtype, shape=shape, name=name)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1502, in placeholder
> name=name)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 2149, in _placeholder
> name=name)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
> op_def=op_def)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\ops.py", line 2327, in create_op
> original_op=self._default_original_op, op_def=op_def)
> File "C:\lib\Anaconda3\envs\keras\lib\site-packages\tensorflow\python\framework\ops.py", line 1226, in **init**
> self._traceback = _extract_stack()
> 
> InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1' with dtype float
> [[Node: input_1 = Placeholderdtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]]
> [[Node: mul_1/_1527 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_66_mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]]
> 
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_gpu_executor.cc:637] Deallocating stream with pending work
> 
> I'm running following code:
> 
> resnet = ResNet50(weights='imagenet', include_top=False)
> print(resnet.summary())
> 
> input_layer = Input(shape=(seq_len, 224_224_3))
> curr_layer = Reshape(target_shape=(seq_len, 224, 224, 3))(input_layer)
> curr_layer = TimeDistributed(resnet)(curr_layer)
> curr_layer = Reshape(target_shape=(seq_len, 2048))(curr_layer)
> lstm_out = LSTM(256, return_sequences=True,
> activation='sigmoid', recurrent_activation='tanh',
> use_bias=True, unit_forget_bias=True)(curr_layer)
> prediction_layer = Dense(2, activation=kb.softmax)(lstm_out)
> 
> model = Model(inputs=input_layer, outputs=prediction_layer)
> optimizer = adam(lr=0.00001)
> model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
> print(model.summary())
> X, Y = get_batch_image(train_dir, batch_size, seq_len)
> print(X.shape, Y.shape)
> model.train_on_batch(X, Y)
> 
> shapes of X,Y = (2, 9, 150528) (2, 9, 2)

dear friend, have you come over this issue? i am meeting the same errors
