### ISSUE TITLE
Some metrics have disappeared

### ISSUE THREAD

**Issue by julioasotodv** [fchollet/keras#6002]
Comparing to v 1.2.2, metrics such as `fmeasure`, `precision` and `recall` are not available anymore in Keras 2.

Is there a good reason for this deletion? Perhaps one the backends do not support those metrics anymore?

**Comment by abramhindle** [comment]
Some fields of study use these "legacy" measures and they need them to compare against prior work. This removal is inconvenient and surprising.

**Comment by t-ae** [comment]
They had trouble.
If minibatch contains no positive samples, [precision](https://github.com/fchollet/keras/blob/53e541f7bf55de036f4f5641bd2947b96dd8c4c3/keras/metrics.py#L116) and [recall](https://github.com/fchollet/keras/blob/53e541f7bf55de036f4f5641bd2947b96dd8c4c3/keras/metrics.py#L130) return 0.
And mean of metrics gets lower values.

I don't know they'll be restored or not. Either way I recommend you to calculate them by yourself.

**Comment by julioasotodv** [comment]
Yes that's right. But still: monitoring these metrics while training is crucial to me.

So I guess that I will retriver them from the older version and use them as a separate module.

**Comment by t-ae** [comment]
Found declaration.
https://github.com/fchollet/keras/issues/5794#issuecomment-287641301

**Comment by julioasotodv** [comment]
I see. Thank you so much.
