### ISSUE TITLE
`unboundlocalerror: local variable 'class_name' referenced before assignment`

### ISSUE THREAD

**Issue by Mr8** [fchollet/keras#6007]
BUG report  ^.^

I have re-define the top_k_categorical_accuracy to 
`def top_k_categorical_accuracy(y_true, y_pred):
    return metrics.top_k_categorical_accuracy(y_true, y_pred, 1)`

And as the model training finished, I saved it to my local disk by `mode.save(mypath)`, but I have got this exception while I load model to other process:

`unboundlocalerror: local variable 'class_name' referenced before assignment`

It was from:
`File "<PYTHONPATH>/local/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 157, in deserialize_keras_object`

Absolutely, it a variable which not been assign before using it. In the exception code block, the unit-test may not cover it or the code's static check issue?

Thanks for read

**Comment by KartikSethi** [comment]
Hey @Mr8 I am facing a similar problem. Were you able to find a fix?

**Comment by surfertas** [comment]
@kartiksethi fwiw upgrading to keras-2.1.2 resolved the issue for me.
