### ISSUE TITLE
Regression since Keras 2: Missing SReLU advanced activation function

### ISSUE THREAD

**Issue by gw0** [fchollet/keras#6008]
In Keras 2 some advanced activation functions, like `SReLU`, were removed without any justification in commit <https://github.com/fchollet/keras/commit/b118cef26fae748d5ec23c33b29e9989a7abbe17>. It is true, that `SReLU` has its problems, but in one of my use cases `SReLU` works a little better than anything else.

**Comment by ahundt** [comment]
You could probably re-submit it as a pull request to [keras-contrib](https://github.com/farizrahman4u/keras-contrib) they probably should have simply moved it there in the first place.

**Comment by the-moliver** [comment]
@gw0 SReLU now in keras-contrib. Please close issue.
