### ISSUE TITLE
Consider replacing theano back-end with CGT?

### ISSUE THREAD

**Issue by simonhughes22** [fchollet/keras#602]
This looks promising, especially for RNN's

https://github.com/joschu/cgt

It may be worth replacing theano back-end with this once it's more mature, or have an option to choose either. It looks like they've maintained a similar API to theano.

**Comment by fchollet** [comment]
Definitely looks very promising. We will revisit it in a month or so. I will be specifically looking at the state of GPU / cuDNN support, and at what CGT users are saying about reliability / speed : )

**Comment by EderSantana** [comment]
yeah, I was excited about the possible better support for RNNs too. In the mean time, Theano devs may also just make a better `scan` using the open source technology from CGT itself. 
It's nice that Theano will have some closer competition. A few years ago, Torch7 vs Theano competition pushed both sides forward, for instance.

**Comment by elanmart** [comment]
I've noticed that there is no `scan` in cgt and it doesn't seem like there will be one in the nearest future. This mean all your loops would have to have hard-coded number of steps. Not very convenient IMO.

**Comment by rodrigob** [comment]
Even if CGT is only suitable for a subset of all the Keras features. It would still be quite useful since the compilation speed is quite dramatic. For debugging and fast prototyping at least this would be a game changer.

@pranv had done some initial investigation.
