### ISSUE TITLE
Why can't I write code like "same" mode in convolutional.py?

### ISSUE THREAD

**Issue by NancyZxll** [fchollet/keras#603]
In keras convolutional.py, a piece of code is:
```
     if self.border_mode == 'same':
            shift_x = (self.nb_row - 1) // 2
            shift_y = (self.nb_col - 1) // 2
            conv_out = conv_out[:, :, shift_x:X.shape[2] + shift_x, shift_y:X.shape[3] + shift_y]
```

I created a Changeformat layer in the core.py, which says:
```
        if self.sign ==0:
            X1= X[:,:,:,0:X.shape[3]-shift]
            return X1
```
The error is:
  raise TypeError("Expected an integer")
TypeError: Expected an integer

WHY can't I write the same code? How can I choose some part of the output:"(

**Comment by NancyZxll** [comment]
Then I follow the example of class ZeroPadding2D, and write the code:
```
  shift = self.nb_col + self.index
        in_shape = X.shape
        out_shape = (in_shape[0], in_shape[1], in_shape[2], in_shape[3]-shift)
        out = T.zeros(out_shape)
        if self.sign ==0:
            indices = (slice(None), slice(None), slice(None), slice(0, in_shape[3] - shift))
            return T.set_subtensor(out[indices],X)
```

Again, say it needs integer..
the error is:
TypeError: Shape arguments to Alloc must be integers, but argument 3 is not for apply node: Elemwise{sub,no_inplace}.0

So WIRED!!! How can I solve such a strange problem!!:"(

**Comment by NancyZxll** [comment]
Well, I change:
```
    def __init__(self, sign, index, nb_col):
```
to 
```
    def __init__(self, sign, index=1, nb_col=1):
```

The error dissapeared...

But still strange for me.
Since in the class Convolution2D:
```
        if self.border_mode == 'same':
            shift_x = (self.nb_row - 1) // 2
            shift_y = (self.nb_col - 1) // 2
            conv_out = conv_out[:, :, shift_x:X.shape[2] + shift_x, shift_y:X.shape[3] + shift_y]
```
No initial assignments to self.nb_row and self.nb_col were given. Is this because shift_x already has integer (1 and 2) in it??

**Comment by fchollet** [comment]
The Keras issues section is for Keras issues: bug reports, feature requests and development discussion. Please do not use the Keras issues section as your personal StackOverflow.

Instead, I suggest you post on StackOverflow.

In the span of 2-3 days, you have opened 7 threads that were personal debugging requests, and in almost all cases they were problems that you could have solved yourself in 1 min of googling or simply by re-reading the code you just wrote. Your workflow appears to be:
- encounter minor debugging issue
- ask for help here
- be told what to do
- repeat

You will not learn anything or get anywhere with this mindset. Solve your own minor debugging problems, like everyone else. Or if that's too difficult, you should be in a different field.

Anyway: **please do not post here with debugging questions unrelated to the development of Keras**.
