### ISSUE TITLE
TimeDistribution ignore weights parameter of layer

### ISSUE THREAD

**Issue by udibr** [fchollet/keras#6038]
In Keras 2 the weights parameter are copied inside the __call__ method of a layer. 
However if the layer is wrapped by a TimeDistribution wrapper then the __call__ 
Of the internal layer is never called. 

I'm guessing similar problem in all wrappers

**Comment by patyork** [comment]
All the wrappers do is call the underlying layer's `call` method (in a way that achieves the wrapper's purpose). For TimeDistributed, that is [here ](https://github.com/fchollet/keras/blob/master/keras/layers/wrappers.py#L120)and [here](https://github.com/fchollet/keras/blob/master/keras/layers/wrappers.py#L137).

Do you have any code that shows the weights are not being applied?

**Comment by udibr** [comment]
The call method of a layer does not handle the copying of initial weights if such weights exists. The copying is done in the underscore underscore call underscore underscore method of the Layer class. 

https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L535


When you build a network with TimeDistribution this is called for the TimeDistribution class which then invoke the call of the internal layer however no one is calling the underscore underscore call method of the internal class and therefore the copying of weights is not performed

**Comment by patyork** [comment]
So it is true that `TimeDistributed(Dense(10, weights=default_weights))` will not apply the weights to the Dense layer, as probably expected.

One work around is to move the parameter to the wrapper itself, instead of the layer: `TimeDistributed(Dense(10), weights=default_weights)`

This could probably be considered a bug; the `kwargs` or at least the `weights` argument could/should probably be moved to a different area of the build process.

**Comment by nikparth** [comment]
So for right now is the only way to use predefined weights with a timedistributed layer to put the parameter in the wrapper itself? Is this an issue that plans to get fixed for the layer wrappers?

**Comment by jacskiier** [comment]
Would the fix be as easy as calling `output = self.layer.__call__(x, **kwargs)` before lines 189 and `y = self.layer.call(inputs, **kwargs)` before line 213 of wrappers.py where `TimeDistributed` is defined? Or would that cause more problems for something else?
