### ISSUE TITLE
How can keras unpack a tensor to a list

### ISSUE THREAD

**Issue by wjbianjason** [fchollet/keras#6041]
My idea is as follow
```python
question = Input(shape=(enc_timesteps,), dtype='int32', name='question_base')
answer_good = Input(shape=(dec_timesteps,), dtype='int32', name='answer_good_base')
answer_bad = Input(shape=(random_size,dec_timesteps,), dtype='int32', name='answer_bad_base')
good_sim = basic_model([question,answer_good])
bad_sim_list = [basic_model([question,bad_answer_single]) for bad_answer_single in keras.unpack(bad_answer)] 
# NOTICE!!! I want to know how to realize keras.unpack
assert len(bad_sim_list) == random_size
bad_sim = merge(bad_sim_list,mode="sum")
```
Thanks for everybody's reply.

**Comment by Dref360** [comment]
This question is best suited for StackOverflow.
Unpack is not implemented in Keras, but there is tf.unpack if you use Tensorflow backend.
https://github.com/ahangchen/TensorFlowDoc/blob/master/api_docs/python/functions_and_classes/shard4/tf.unpack.md

**Comment by ruodingt** [comment]
Thanks. But with tensorflow backend, after using tf.unstack, keras seems don't work with tf-tensor


TypeError: Input tensors to a Model must be Keras tensors. Found: Tensor("unstack:0", shape=(?, 2048), dtype=float32) (missing Keras metadata).

**Comment by Dref360** [comment]
Use a Lambda layer

**Comment by emnajaoua** [comment]
@Dref360 can you give an example how please ?
