### ISSUE TITLE
Framework-Design: Why renaming Convolution to Conv in Keras 2?

### ISSUE THREAD

**Issue by apacha** [fchollet/keras#6044]
As mentioned [here](https://github.com/fchollet/keras/wiki/Keras-2.0-release-notes) and seen in the source-code, the new way of creating a convolution layer is by using the `Conv*`-name. Although there exists an alias `Convolution*`, the overall design question is, why would anyone want to swap a perfectly named object with a non-trivial abbreviation in a framework such as Keras? Especially when other abbreviations are being removed at the same time (e.g. `b_regularizer -> bias_regularizer`).

In my experience as a developer, introducing abbreviations is _never_ a good choice, because it makes code harder to read and comprehend ([clarity trumps brevity](http://softwareengineering.stackexchange.com/a/67319)). Especially in core concepts of a framework! I am really interested in the reasons that led to this design decision and would strongly argue that for future releases, the implementation works the other way around again: Having classes called `Convolution*` and aliases `Conv*` for convenience reasons and recommending the use of `Convolution*`.

**Comment by MarxSoul55** [comment]
I agree with you. I was recently looking at the documentation and was surprised to see that `Convolution*` was no longer present, replaced by `Conv*`. Yet in other parts of the code, abbreviations aren't being used and some are even being removed, as you said. I'm not sure what the purpose of all this is?

**Comment by apacha** [comment]
Bump - to avoid this issue from being closed without discussion by the maintainers.

**Comment by apacha** [comment]
Bump - to avoid this issue from being closed without discussion by the maintainers.

**Comment by bozzmob** [comment]
Bump :(

**Comment by fchollet** [comment]
The summary is:
- if you prefer `Convolution*`, you can style use that style. It will be supported indefinitely.
- many people prefer `Conv*`, because it's shorter. 
- we standardized on `Conv*` to unify the Keras API and the `tf.layers` API.
