### ISSUE TITLE
Documentation unclear on how to convert numpy array into tensor

### ISSUE THREAD

**Issue by bixbyr** [fchollet/keras#6045]
I am fairly new to using the Keras backend, and I've been trying to implement AUC via direct tensor arithmetic (I know that tensorflow purports to have such a metric but I've been unable to get it to work, and this is sort of a separate question anyway). 

I can't find anywhere in the documentation a succinct explaination of how to convert a numpy array into a keras tensor via the backend API. This seems like a fairly big oversight since the backend docs only discuss methods (very briefly at that), and there is little explanation given to how the system functions.

Here is an example of what I am trying to do (one input is a list, the other is a numpy array):

def auc_gpu(self, y_true, y_pred):
    points = [(0, 0)]
    with K.get_session() as sess:
        sess.as_default()
        y_pred_cast = K.placeholder(shape=y_pred.shape, dtype='float32')
        y_true_cast = K.placeholder(shape=np.array(y_true).shape, dtype='float32')
        K.set_value(y_pred_cast, y_pred)
        K.set_value(y_true_cast, np.array(y_true))

When I run this segment of code I get the following exception:
  ....
  File "new_combined_qa.py", line 339, in on_epoch_end
    print("\nGPU AUC: {}".format(self.auc_gpu(y, y_pred)))
  File "new_combined_qa.py", line 363, in auc_gpu
    K.set_value(y_pred_cast, y_pred)
  File "C:\Users\Ryan Smith\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 1967, in set_value
    assign_op = x.assign(assign_placeholder)
AttributeError: 'Tensor' object has no attribute 'assign'

I'm using keras 2.0.2 and tensorflow-gpu 1.0.1. Thanks for any help.

**Comment by kgrm** [comment]
You can't assign values to placeholder variables, they're meant to serve as, well, placeholders, for symbolic operations. To create a Keras variable from a numpy array, use `var = K.variable(arr)`.
