### ISSUE TITLE
Error in demo sample image_ocr.py

### ISSUE THREAD

**Issue by vladimircape** [fchollet/keras#6049]
I tried to run 
https://github.com/fchollet/keras/blob/master/examples/image_ocr.py
I used Theano '0.9.0.dev-bd1a12ed706a4ef1a2e1b8f06565737a37eafb99
Python3.5
Ubuntu16
Using gpu device 0: GeForce GTX 1060 6GB (CNMeM is enabled with initial size: 20.0% of memory, cuDNN 5005

I start train(run_name, 0, 20, 128)
and got
`Untaring file...
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
====================================================================================================
the_input (InputLayer)           (None, 128, 64, 1)    0                                            
____________________________________________________________________________________________________
conv1 (Conv2D)                   (None, 128, 64, 16)   160                                          
____________________________________________________________________________________________________
max1 (MaxPooling2D)              (None, 64, 32, 16)    0                                            
____________________________________________________________________________________________________
conv2 (Conv2D)                   (None, 64, 32, 16)    2320                                         
____________________________________________________________________________________________________
max2 (MaxPooling2D)              (None, 32, 16, 16)    0                                            
____________________________________________________________________________________________________
reshape (Reshape)                (None, 32, 256)       0                                            
____________________________________________________________________________________________________
dense1 (Dense)                   (None, 32, 32)        8224                                         
____________________________________________________________________________________________________
gru1 (GRU)                       (None, 32, 512)       837120                                       
____________________________________________________________________________________________________
gru1_b (GRU)                     (None, 32, 512)       837120                                       
____________________________________________________________________________________________________
add_1 (Add)                      (None, 32, 512)       0                                            
____________________________________________________________________________________________________
gru2 (GRU)                       (None, 32, 512)       1574400                                      
____________________________________________________________________________________________________
gru2_b (GRU)                     (None, 32, 512)       1574400                                      
____________________________________________________________________________________________________
concatenate_1 (Concatenate)      (None, 32, 1024)      0                                            
____________________________________________________________________________________________________
dense2 (Dense)                   (None, 32, 28)        28700                                        
____________________________________________________________________________________________________
softmax (Activation)             (None, 32, 28)        0                                            
====================================================================================================
Total params: 4,862,444.0
Trainable params: 4,862,444.0
Non-trainable params: 0.0
____________________________________________________________________________________________________
Epoch 1/20
  389/12800 [..............................] - ETA: 6486s - loss: 8.0250
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/vshebuniayeu/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/vshebuniayeu/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vshebuniayeu/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 606, in data_generator_task
    generator_output = next(self._generator)
  File "<ipython-input-8-4df11d60d660>", line 196, in next_train
    [self.X_text, self.Y_data, self.Y_len], self.val_split)
  File "<ipython-input-8-4df11d60d660>", line 43, in shuffle_mats_or_lists
    np.random.shuffle(a)
  File "mtrand.pyx", line 5027, in mtrand.RandomState.shuffle (numpy/random/mtrand/mtrand.c:37943)
  File "mtrand.pyx", line 5030, in mtrand.RandomState.shuffle (numpy/random/mtrand/mtrand.c:37895)
TypeError: 'range' object does not support item assignment

  390/12800 [..............................] - ETA: 6485s - loss: 8.0160
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-1949a076a282> in <module>()
----> 1 train(run_name, 0, 20, 128)

<ipython-input-5-9df9a651267d> in train(run_name, start_epoch, stop_epoch, img_w)
     84     model.fit_generator(generator=img_gen.next_train(), steps_per_epoch=(words_per_epoch - val_words),
     85                         epochs=stop_epoch, validation_data=img_gen.next_val(), validation_steps=val_words,
---> 86                         callbacks=[viz_cb, img_gen], initial_epoch=start_epoch)

/home/vshebuniayeu/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     86                 warnings.warn('Update your `' + object_name +
     87                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 88             return func(*args, **kwargs)
     89         wrapper._legacy_support_signature = inspect.getargspec(func)
     90         return wrapper

/home/vshebuniayeu/anaconda3/lib/python3.5/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_q_size, workers, pickle_safe, initial_epoch)
   1849                                          'a tuple `(x, y, sample_weight)` '
   1850                                          'or `(x, y)`. Found: ' +
-> 1851                                          str(generator_output))
   1852                     if len(generator_output) == 2:
   1853                         x, y = generator_output

ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None`
How to fix it?

**Comment by abhaikollara** [comment]
Hi, could you make the following change in the `image_ocr.py` file and report back.

Replace line 130  with  `a = [x for x in range(stop_ind)]`
and line 132 with `a += [x for x in range(stop_ind, len_val)]`

**Comment by farizrahman4u** [comment]
#6060

**Comment by vladimircape** [comment]
Working, ticket can be closed.
