### ISSUE TITLE
Data processing for non-sequential data in LSTM

### ISSUE THREAD

**Issue by ikanez** [fchollet/keras#6058]
Hi. Have a question. I was reading an article at http://www.wildml.com/2016/08/rnns-in-tensorflow-a-practical-guide-and-undocumented-features/ and came to know about tf.sequenceexample and how it is able to prepare data for both non-sequential variable and sequential variable. Is there a similar thing in Keras (tensorflow)? How does one normally prepare data for non sequential variable before processing into LSTM? Would appreciate if there's an example as well. Thanks.

**Comment by bstriner** [comment]
Interesting idea. I'm writing custom data pumps all the time. Maybe some way to leverage tf.sequenceexample? You're basically looking for something like the Keras ImageDataGenerator but for things like text?

Cheers

**Comment by ikanez** [comment]
The problem i'm working with right now involves stock prices. Each row of data would contain by the minute data of stock return. Within the same row are the contextual information related to that stock, such as date interval of the data, industry, company, and week id. 

Hope my description above adds more context to my earlier question. Thanks!
