### ISSUE TITLE
Error in InceptionV3 with input_tensor option

### ISSUE THREAD

**Issue by AnnHae** [fchollet/keras#6062]
Hi,

I tried using the InceptionV3 model with a custom input tensor like described in the doc (see also this thread: https://groups.google.com/forum/#!topic/keras-users/G9C55N7e8S4). Here's my code:

```
from keras.applications.inception_v3 import InceptionV3
from keras.layers import Input
import keras.backend as K
import numpy as np

K.set_image_data_format('channels_first')

input_tensor = Input(shape=(3,224, 224))  # this assumes K.image_data_format() == 'channels_first'
model = InceptionV3(input_tensor=input_tensor, weights='imagenet', include_top=True)

def get_dummy_data(batch_size,input_shape,n_classes):   
    imgs = np.zeros((batch_size,input_shape[0],input_shape[1],input_shape[2]))
    labels = np.zeros((batch_size,n_classes))   
    return imgs, labels
   
train_imgs, train_labels = get_dummy_data(10,(3,224,224),1000)


# compile the model (should be done *after* setting layers to non-trainable)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy')

# train the model on the new data for a few epochs
model.fit(x=train_imgs,y=train_labels)
```

but it yields an error:

```
ValueError: The model expects 0 input arrays, but only received one array. Found: array with shape (10, 3, 224, 224)
```

The error vanishes when I give the input tensor a name and provide the training data as a dict, however then I get a MissingInputError in theano.gof.fg.

From the discussion at google/keras-users and my own investigations I think it has to do with the fact, that the provided input_tensor is not a placeholder and doesn't appear in model._feed_input_names, whereas the default input when not using the input_tensor option is a placeholder.

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by AnnHae** [comment]
Update:
I think I got it to work by replacing

```
img_input = Input(tensor=input_tensor, shape=input_shape)
```

by

```
img_input = input_tensor
```

here: https://github.com/fchollet/keras/blob/master/keras/applications/inception_v3.py#L160

I'm not sure though whether this is a bug in the inception code or in the Input layer.

**Comment by Djoulihen** [comment]
Running into the same issue here with VGG19. It seems that you cannot load a model from Keras applications when both specifying an input_tensor and weights="imagenet".

Keras complains about loading the weights because the model returned by the VGG19 function is the full model (input model + VGG model).

@AnnHae Did you manage to solve this problem when you tried to add layers in front of Inception V3 ?

**Comment by Djoulihen** [comment]
Never mind, I got it to work by first loading the VGG model with a dummy input and then recreating an extended model from the VGG one:
```
# Starting from a model with inputs "original_inputs" and output "original_output"
VGG_model = VGG19(input_shape=(3,None,None), weights="imagenet")
VGG_out = VGG_model(original_output)
full_model = Model(original_inputs, VGG_out)
```

**Comment by gautiese** [comment]
> 
> 
> Never mind, I got it to work by first loading the VGG model with a dummy input and then recreating an extended model from the VGG one:
> 
> ```
> # Starting from a model with inputs "original_inputs" and output "original_output"
> VGG_model = VGG19(input_shape=(3,None,None), weights="imagenet")
> VGG_out = VGG_model(original_output)
> full_model = Model(original_inputs, VGG_out)
> ```

Hey I Didnt understand what you did here.
I am stuck with exactly the same problem.
Can you please elaborate?
