### ISSUE TITLE
Calling call method of Layer class in topology.py with wrong parameters

### ISSUE THREAD

**Issue by kumaranvpl** [fchollet/keras#6064]
On [line 556](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L556) of topology.py call method of Layer class is called with `output = self.call(inputs, **kwargs)`.

But [call method](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L470) accepts only one parameter and returns the same without doing anything.
 If I am right this call method is implemented either for future feature implementation or a leftover from past feature.
Also on [line 556](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L556) passing keyword arguments as parameter is implemented by `**kwargs`. It is wrong. It should be passed by `kwargs`.
This bug can be fixed using different ways.

1. Removing `**kwargs` from call method call. 
This way [line 556](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L556) should look like `output = self.call(inputs)`
2. Accepting `kwargs` as keyword arguments in call method and returning inputs only in call method.
This way [line 556](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L556) should look like `output = self.call(inputs, **kwargs)` and [line 470](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L470) should look like `def call(self, inputs, **kwargs):`.
3. Accepting `kwargs` as keyword arguments in call method and returning both inputs and kwargs in call method.
This ways [line 556](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L556) should look like `output, returned_kwargs = self.call(inputs, **kwargs)`, [line 470](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L470) should look like `def call(self, inputs, **kwargs):` and [line 479](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L479) should look like `return inputs, kwargs`.

So, Please let me know which way should be implemented. I like to fix it myself and I want to create a pull request for the fix. This way I can contribute to keras a little.

**Comment by abhaikollara** [comment]
@kumaranvpl `Layer` is an abstract base class, which means there will be no direct instances of the `Layer` class. The layers inherited from the `Layer` class such as Dense, Dropout etc has proper implementations for the `call` method

**Comment by kumaranvpl** [comment]
@abhaikollara I tried running this spacy [example](https://github.com/explosion/spaCy/tree/master/examples/keras_parikh_entailment).
Here GlobalAveragePooling1D has been called at some point which results in an error in line 556

**Comment by abhaikollara** [comment]
Hmm, I haven't read too much of the code yet, so I don't know for sure, but I guess the second option makes sense. Try it out, be sure to run the tests. Good luck !

**Comment by kumaranvpl** [comment]
@abhaikollara The first one also works.. I already fixed this issue by running it locally by applying the first option. But my question is which one should be the proper/corret way?
