### ISSUE TITLE
How to change number of classes in Siamese network example?

### ISSUE THREAD

**Issue by aryopg** [fchollet/keras#6079]
How do i prepare the data if i want to use my own data in siamese net example? Let's say that my data have 4 classes/labels, should i just change all "10" into "4"? Like all of them? Or i only need to change the code in a certain part? I'm currently getting 0.50000 for the accuracy all the time, i assume it might be something to do with the pair/data preparation. Thanks in advance

**Comment by kgrm** [comment]
You only need to change the `create_pairs` function to appropriately generate matching and non-matching pairs from your data.

**Comment by aryopg** [comment]
i think i've done it, is it possible if i use a vgg16-like architecture to train them, it will somehow make the accuracy stagnant?
