### ISSUE TITLE
Keras tensorboard showing nothing but the code runs well

### ISSUE THREAD

**Issue by lk1983823** [fchollet/keras#6099]
I am using tensorflow 1.0.1 keras 2.0 and python 3.4
When I run my code, it shows no error. However tensorboard show that "No graph definition files were found. "

My tensorboard debug is as follows:

INFO:tensorflow:TensorBoard is in debug mode.
INFO:tensorflow:Starting TensorBoard in directory /home/swx/lk
**INFO:tensorflow:TensorBoard path_to_run is: {'/home/swx/lk/=': None}**
INFO:tensorflow:Event Multiplexer initializing.
INFO:tensorflow:Event Multiplexer done initializing
INFO:tensorflow:TensorBoard reload process beginning
INFO:tensorflow:Starting AddRunsFromDirectory: /home/swx/lk/=
INFO:tensorflow:Done with AddRunsFromDirectory: /home/swx/lk/=
INFO:tensorflow:TensorBoard reload process: Reload the whole Multiplexer
**INFO:tensorflow:Beginning EventMultiplexer.Reload()
INFO:tensorflow:Finished with EventMultiplexer.Reload()**
INFO:tensorflow:TensorBoard done reloading. Load took 0.002 secs
INFO:tensorflow:TensorBoard is tag: b'41'

can any one offer some help?

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by gaw89** [comment]
I had a similar issue.  Mine was resolved by directing the tensorboard callback to save the logs on a local drive instead of the network drive I had been using.  Then it worked fine.  For some reason, Tensorboard cannot access a network location (at least in Windows).  Are you using a network location?

**Comment by dickreuter** [comment]
I have the same problem and I'm using a local drive in windows
http://stackoverflow.com/questions/43709728/keras-not-writing-tensorboard-callback
