### ISSUE TITLE
Data augmentation issue

### ISSUE THREAD

**Issue by lan2720** [fchollet/keras#610]
I run the example cifar10_cnn.py and then find something strange.
When I use data_augmentation with "width_shift_range"  and "height_shift_range" = 0.2, time of one epoch is around 290s, but when "width_shift_range" and "height_shift_range" = 0.0, time of one epoch is around 160s.(GPU=NVIDIA GTX 970)
This transformation didn't change the size of input or shape of image, why it slowed down the training process?

**Comment by fchollet** [comment]
> This transformation didn't change the size of input or shape of image, why it slowed down the training process?

It is not slowing down the training process itself, but the image transformations (done in Numpy, on CPU) add quite a bit of time by themselves. If you want to avoid that while still doing data augmentation, I recommend that you pre-generate augmented inputs ahead of time.

You can also look into doing the data augmentation on CPU *while* the current batch in processing on GPU.
