### ISSUE TITLE
image_ocr example performance

### ISSUE THREAD

**Issue by sosoxuc** [fchollet/keras#6108]
image_ocr example on kears was 10 times faster then on keras2
Why that ?
What has changed ?

**Comment by mbhenry** [comment]
Seems the batch size is now 1?  Or am I just imagining that?  I can look into it, but I didn't do any of the Keras2 conversions, so someone may have a quicker answer.

**Comment by sosoxuc** [comment]
declare
```
minibatch_size=32
```
then in fit_generator

```
steps_per_epoch=(words_per_epoch - val_words)/minibatch_size
```
