### ISSUE TITLE
Running Keras model for prediction in multiple threads

### ISSUE THREAD

**Issue by leckie-chn** [fchollet/keras#6109]
I posted my problem on Stackoverflow: [Running Keras model for prediction in multiple threads](https://stackoverflow.com/questions/43136293/running-keras-model-for-prediction-in-multiple-threads) but got no answer. So I come here for help.

I tried copying over the weights, but didn't solve the problem:
```python
        for roundNo in xrange(self.param['max_round']):
            for agent in self.AgentPool:                               # self.AgentPool: type - list of AgentThread
                agent.syncModel(self.getEnv(), self.actor, self.critic, eps)
                agent.start()
            for agent in self.AgentPool:
                agent.join()
```

```python
class AgentThread:
    def syncModel(self, env_, actor_, critic_, eps_):
        """synchronize A-C models before collecting data"""
        # TODO copy env, actor, critic
        self.env = env_     # shallow copy
        self.actor.model.set_weights(actor_.model.get_weights())        # deep copy, by weights
        self.critic.model.set_weights(critic_.model.get_weights())      # deep copy, by weights
        self.eps = eps_     # shallow copy
        self.data = {}
```

I guess there is something wrong about the tensorflow session, but can't figure out a solution.

**Comment by leckie-chn** [comment]
For further information, see [this issue on jaara/AI-blog](https://github.com/jaara/AI-blog/issues/2) and [this issue on Keras](https://github.com/fchollet/keras/issues/6124)

**Comment by fgerard** [comment]
This fixed the problem to me, after loading the model and BEFORE any prediction invoke:
d_model._make_predict_function()
Hope it works for you
