### ISSUE TITLE
Graph model predicting accuracy

### ISSUE THREAD

**Issue by violet-zct** [fchollet/keras#611]
I found that graph model doesn't support the output of test_accuracy or train_accuracy like the sequential model. I was wondering if this feature could be added into the graph model that we can see the predicted accuracy for some specific output given any input.

**Comment by fchollet** [comment]
Accuracy monitoring was added the the Sequential model as a convenience feature (accuracy is not part of the training), but the multi-output nature of the Graph model would make the same feature quite complicated, both technically and in terms of user-facing interface.

So for now, I would recommend you do it by yourself: use the `graph.predict(data)` method to generate predictions after each epoch (train epoch by epoch or batch by batch) then compute accuracy over these predictions.

**Comment by violet-zct** [comment]
Thank you! Yes, I did this by myself. But monitoring accuracy during each epoch is quiet useful when one epoch needs to take a long time.

Thanks for your reply! ;)

**Comment by marcj** [comment]
@violet-zct, do you have some code to share? Guess it would be pretty useful for the world to see code examples :)
