### ISSUE TITLE
How can I add another convolutional layer  and maxpooling layer processing texts in CNN?

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#612]
```python

model = Sequential()

# we start off with an efficient embedding layer which maps
# our vocab indices into embedding_dims dimensions
model.add(Embedding(max_features, embedding_dims))
model.add(Dropout(0.25))

# we add a Convolution1D, which will learn nb_filters
# word group filters of size filter_length:
model.add(Convolution1D(input_dim=embedding_dims,
                        nb_filter=nb_filters,
                        filter_length=filter_length,
                        border_mode="valid",
                        activation="relu",
                        subsample_length=1))

# we use standard max pooling (halving the output of the previous layer):
model.add(MaxPooling1D(pool_length=2))                         
  
# we use standard max pooling (halving the output of the previous layer):
# model.add(MaxPooling1D(pool_length=2))

# We flatten the output of the conv layer, so that we can add a vanilla dense layer:
model.add(Flatten())

# Computing the output shape of a conv layer can be tricky;
# for a good tutorial, see: http://cs231n.github.io/convolutional-networks/
output_size = nb_filters * (((maxlen - filter_length) / 1) + 1) / 2

# We add a vanilla hidden layer:
model.add(Dense(output_size, hidden_dims))
model.add(Dropout(0.25))
model.add(Activation('relu'))

# We project onto a single unit output layer, and squash it with a sigmoid:
model.add(Dense(hidden_dims, nb_classes))
model.add(Activation('softmax'))

```
I have read the keras documentation, in which the input of  convolutional layer has the 'nb_samples', not 'embedding_dims' in example of cnn. Why? And, I want add another convolutional layer using  Convolution1D to do NLP. Will someone tell me how to add the convolutional layer  and maxpooling layer? Also, I don't kown how to calculate the 'output_size' after Flatten(). I'm sorry, so many questions. Thanks!

**Comment by simonhughes22** [comment]
@Imorton-zd read this long post in its entirety - #233. I think that'll answer most if not all of these questions.

**Comment by Imorton-zd** [comment]
In fact, I have read that long post before. You all use convolution2D to do texts processing, which I have tried towards my task that accuracy of texts classification was very low. I don't know if I made a mistake. Now, I use convolution1D that accuracy is good, and I am going to add another convolutional layer after the first convolutional layer and maxpooling layer expecting higher accuracy. Can you teach me how to add another convolutional layer using Convolution1D and explain the difference between Convolution1D and 2D simply. Many thanks.
