### ISSUE TITLE
How to do featurewise_center when using flow_from_dictionary()

### ISSUE THREAD

**Issue by SIAAAAAA** [fchollet/keras#6121]
I want to do some data augment to my dataset, however, when I want to do
`featurewise_center`,` samplewise_center`using
```
train_datagen = ImageDataGenerator(
    rescale=1./255,
    featurewise_center=True,  # set input mean to 0 over the dataset
    samplewise_center=False,  # set each sample mean to 0
    featurewise_std_normalization=False,  # divide inputs by std of the dataset
    samplewise_std_normalization=False,  # divide each input by its std
    zca_whitening=False,  # apply ZCA whitening
    rotation_range=20,  # randomly rotate images in the range (degrees, 0 to 180)
    width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
    height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
    horizontal_flip=True,  # randomly flip images
    vertical_flip=False,
    zoom_range=0.1,
    channel_shift_range=0.,
    fill_mode='nearest',
    cval=0.,

)
```
I find that it need to have the following code to make it works.
`train_datagen.fit(Xtrain)`
the` Xtrain` need to be a array. However, I need to use `flow_from_directory() ` to load my data otherwise I will have a memory problem.
So my question is how can I do  
```
featurewise_center,
    samplewise_center
```
when I use  `flow_from_directory() `

Many thanks!

**Comment by sallamander** [comment]
@SIAAAAAA you can use the `preprocessing_function` argument of the `ImageDataGenerator`... See [here](https://github.com/fchollet/keras/blob/b4f7340cc9be4ce23c768c26a612df287c5bb883/keras/preprocessing/image.py#L367).

**Comment by SIAAAAAA** [comment]
@sallamander  Many thanks! It works.

**Comment by sallamander** [comment]
@SIAAAAAA Great, glad to hear that! If this is all set, would you mind closing this issue, please?

**Comment by sallamander** [comment]
Thanks!

**Comment by chineseqsc** [comment]
@sallamander  can you show me some code? I don't know how to carry it out..

**Comment by chineseqsc** [comment]
@SIAAAAAA can you show me some code? I don't know how to carry it out..
