### ISSUE TITLE
Wrong source links for merge layers

### ISSUE THREAD

**Issue by kemaswill** [fchollet/keras#6144]
The source links for merge layers is not correct: https://keras.io/layers/merge/
Seems that the [inspect](https://github.com/fchollet/keras/blob/master/docs/autogen.py#363) return the wrong starting line number for merge classes:
`
line = inspect.getsourcelines(cls)[-1]
`

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
Please send a PR to fix this.

**Comment by fchollet** [comment]
Fixed as far as I can tell.
