### ISSUE TITLE
large datasets, early stopping

### ISSUE THREAD

**Issue by matudor** [fchollet/keras#616]
Many thanks for Keras, I'm enjoying the package very much.

Following up on a previous question:
https://github.com/fchollet/keras/issues/68
How does one apply early stopping or other epoch-based callbacks to the sub-epoch training approach proposed in the replies?  

Cheers,
Matudor

**Comment by matudor** [comment]
Never mind, I just discovered model.stop_training.
TY

**Comment by auspicious3000** [comment]
How did you use model.stop_training for model.fit(epoch=1) based problem? I would really appreciate if you could give an example. 
Thanks!

**Comment by matudor** [comment]
pseudocde:

for m in minibatchgenerator:
    model.train_on_batch(m[0],m[1])
    if model.stop_training:
        break
