### ISSUE TITLE
Unused function in generic_utils.py

### ISSUE THREAD

**Issue by kumaranvpl** [fchollet/keras#6162]
[make_tuple function](https://github.com/fchollet/keras/blob/master/keras/utils/generic_utils.py#L164) in generic_utils.py is not used in the whole keras repo.
I believe that function was created in order to fix issue [#2814](https://github.com/fchollet/keras/issues/2814) but left unused.
@fchollet Also issue [#2814](https://github.com/fchollet/keras/issues/2814) still exists and the fix specified in this [commit](https://github.com/fchollet/keras/commit/6417d90d5c1f70844d8d346312f1b40f449545a5#diff-56dc3cc42e1732fdb3a3c2c3c8efa32a) was removed in this [commit](https://github.com/fchollet/keras/commit/edae1785327dd7a418ac06c2fe85a8c1f6ea05b7#diff-56dc3cc42e1732fdb3a3c2c3c8efa32a).

**Comment by fchollet** [comment]
I removed it. Thanks for the notice.
