### ISSUE TITLE
K.batch_dot() doc example fails w/ Tensorflow backend

### ISSUE THREAD

**Issue by drscotthawley** [fchollet/keras#6173]
From the batch_dot section of the Backend docs (https://keras.io/backend/):

> Shape inference: Let x's shape be (100, 20) and y's shape be (100, 30, 20). If axes is (1, 2), to find the output shape of resultant tensor, loop through each dimension in x's shape and y's shape:
> 
>     x.shape[0] : 100 : append to output shape
>     x.shape[1] : 20 : do not append to output shape, dimension 1 of x has been summed over. (dot_axes[0] = 1)
>     y.shape[0] : 100 : do not append to output shape, always ignore first dimension of y
>     y.shape[1] : 30 : append to output shape
>     y.shape[2] : 20 : do not append to output shape, dimension 2 of y has been summed over. (dot_axes[1] = 2) output_shape = (100, 30)
> 

Actually running this (see below code) produces errors when using the newest Tensorflow.  Seems to be ok with Theano.

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).
```
from keras import backend as K

x = K.ones(shape=(100,20))
y = K.ones(shape=(100,30,20))
xy = K.batch_dot(x,y,axes=(1,2))
```

Fails with...
Using TensorFlow backend.
Traceback (most recent call last):
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/opt/anaconda/envs/py35/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 2 but is rank 3 for 'MatMul' (op: 'MatMul') with input shapes: [100,20], [100,30,20].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "batch_dot_test.py", line 6, in <module>
    xy = K.batch_dot(x,y,axes=(1,2))
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 917, in batch_dot
    out = tf.matmul(x, y, adjoint_a=adj_x, adjoint_b=adj_y)
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 1801, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1263, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/opt/anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 2 but is rank 3 for 'MatMul' (op: 'MatMul') with input shapes: [100,20], [100,30,20].

When using Theano, no output appears at all, indicating success.

**Comment by sunnysai12345** [comment]
just passing x = K.ones(shape=(100,20,1)) resolves this issue.
From keras.backend.tensorflow_backend.py
>>> x_batch = K.ones(shape=(32, 20, 1))
>>> y_batch = K.ones(shape=(32, 30, 20))
>>> xy_batch_dot = K.batch_dot(x_batch, y_batch, axes=[1, 2])
>>> K.int_shape(xy_batch_dot)
        (32, 1, 30)

**Comment by drscotthawley** [comment]
True, that is a viable workaround, however that is not what the documentation says -- as it stands, there's a contradiction.  And it's not what happens with the Theano backend.  Plus your result produces the wrong number of dimensions; it would need a call to reshape() at the end.

**Comment by fchollet** [comment]
Can someone please investigate what a solution would look like?

**Comment by verashira** [comment]
To me, it is not a bug in code though but somehow inconsistency in the documents. The code example in the official site [https://keras.io/backend/](https://keras.io/backend/), which only appears in the docstring in tensorflow backend, actually implies the fact that x and y should be of the same rank.

Theano backend uses `T.batched_tensordot` to implement `K.batch_dot` which happens to help you expand the missing dim if applicable. While in the tensorflow backend, I don't think this is ever supported, no matter using `tf.batch_matmul` or latest `tf.matmul`. Specifically, see [tf.matmul](https://www.tensorflow.org/api_docs/python/tf/matmul), 
**b: Tensor with same type and rank as a**.

**Solution:**
It is possible to manually fix this, possibly add as below to (https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L911)
```python
        if ndim(x) == 2:
            x = tf.expand_dims(x, axis=ndim(x) if axes[0] == ndim(x) - 1 else ndim(x))
        if ndim(y) == 2:
            y = tf.expand_dims(y, axis=ndim(y) if axes[1] == ndim(y) - 1 else ndim(y))
        
        if axes is not None:
            adj_x = None if axes[0] == ndim(x) - 1 else True
        ....
```

Use ndim(x)-1 not hard code1 or 2 because `tf.matmul` now supports the input to have more than 3 ranks. Or would it be better we raise an error to both backends to notify that the inputs x and y should be of the same rank? Make life easier.

```python
if ndim(x) != ndim(y):
     raise ValueError("Inputs should have same ranks but are " + str(ndim(x)) + " and " + str(ndim(y)) + ".")
```

**Comment by Dref360** [comment]
#6219
