### ISSUE TITLE
model.add(Merge) dimension issue. 

### ISSUE THREAD

**Issue by inctrljinee** [fchollet/keras#618]
I have a problem with "merge" function in model.add

========================================================
        model_f3 = Sequential()

....bla bla .... long story short.

        model_f3.add(Dense(32*img_p2*img_p2, last_node))
        model_f3.add(Activation('relu'))
        model_f3.add(Dropout(0.5))

        model_f5 = Sequential()

....bla bla .... long story short.

        model_f5.add(Dense(32*img_p2*img_p2, last_node))
        model_f5.add(Activation('relu'))
        model_f5.add(Dropout(0.5))

        model = Sequential()
        model.add(Merge([model_f3, model_f5], mode='concat'))
        model.add(Dense(last_node*2, nb_classes)) 
        model.add(Activation('softmax'))

=========================================================
Message (when lastnode*2): 

ValueError: dimension mismatch in args to gemm (32,1024)x(2048,5)->(32,5)
Apply node that caused the error: GpuDot22(GpuJoin.0, <CudaNdarrayType(float32, matrix)>)
Inputs types: [CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(32, 1024), (2048, 5)]
Inputs strides: [(1024, 1), (5, 1)]
Inputs values: ['not shown', 'not shown']

Message  (when lastnode): 
ValueError: The splits sum to 2048, expected 1024
Apply node that caused the error: GpuSplit{2}(GpuDot22.0, TensorConstant{-1}, MakeVector.0)
Inputs types: [CudaNdarrayType(float32, matrix), TensorType(int8, scalar), TensorType(int64, vector)]
Inputs shapes: [(32, 1024), (), (2,)]
Inputs strides: [(1024, 1), (), (8,)]
Inputs values: ['not shown', array(-1, dtype=int8), array([1024, 1024])]

-------------------------------------------------------------------------------------------------------

In the following part of the code, 

     model.add(Merge([model_f3, model_f5], mode='concat'))
     model.add(Dense(last_node*2, nb_classes)) 

when I use [mode='sum'] and change lastnode*2 to lastnode, it works perfectly. 

On the other hand, [mode='concat'] and change it to lastnode, it doesn't work. 

For paramerter in final "Dense" function, 
I've tried lastnode*4, lastnode/2 and whatnots, but none of them has succeeded it. 

Any guys have an idea on this ? 

I believe [mode = concat] needs doubled number of nodes because it concatenates the nodes. (as the term says, literally),

which is different from [mode = sum]. Because [mode=sum] just sums up the weights into a node. 

Am I wrong or is there anything wrong with my code?

Please help me if you have an idea on this thing. 

I always appreciate your support and help. thank you.

**Comment by inctrljinee** [comment]
This issue can be solved by installing brand-new Theano library. 
This was an internal bug of the old Theano library.

**Comment by stevenspielberg8** [comment]
Yeah even I had the same issue and I got it resolved by installing the latest theano from github (not using pip install)
