### ISSUE TITLE
Documentation of Keras v0.3.2 required

### ISSUE THREAD

**Issue by MehulAjax21** [fchollet/keras#6181]
We are still using the old version of Keras (v0.3.2) and want to have the documentation of the same.
It is not available on Keras.io
We are maintaining the codes of other people, which use the old graph APIs. 
Also I wanted to know if there is a script available to port the old models to the latest version of the keras.
Converting these model line to line is a very big effort.
So if we can convert them, we can switch to the new version of Keras for which the documentation is available

**Comment by Danielhiversen** [comment]
You will find here https://github.com/fchollet/keras/tree/0.3.2/docs
Not sure if it is available anywhere else.

**Comment by MehulAjax21** [comment]
Thanks a lot for the reply. I got the docs.
I will close the issue now.
