### ISSUE TITLE
how can I get the gating signals in LSTM with keras 2? please

### ISSUE THREAD

**Issue by jairomon** [fchollet/keras#6185]
from keras import backend as K
K.get_value(layer.W_f)

it is not working

**Comment by jairomon** [comment]
from keras import backend as K
K.get_value(layer.W_f)

it is not working.

**Comment by fchollet** [comment]
If what you are looking for the is the weights of the LSTM layer, they are at `layer.kernel` and `layer.recurrent_kernel`. Each kernel is the concatenation of the weights for the `W_*` gates, and `U_*` gates, respectively.
