### ISSUE TITLE
Question about the TimeDistributed example code in Keras Doc

### ISSUE THREAD

**Issue by JohanWu** [fchollet/keras#6190]
I just read the example code in https://keras.io/layers/wrappers/#timedistributed

![image](https://cloud.githubusercontent.com/assets/14994340/24824931/d6c6c6a0-1bc9-11e7-9988-2f0bf249e691.png)

But I really don't understand why the output shape is (32, 10, 8) instead of (32, 10, 32), especially
the last comment says "# now model.output_shape == (None, 10, 32)"

Could someone explain it?
Thank you very much in advance!

**Comment by sallamander** [comment]
@JohanWu I think that last comment just refers to the shape after the first `TimeDistributed` call. The `model.output_shape` after the `TimeDistributed(Dense(8))` call here will be `(batch_size, 10, 8)`, and after `TimeDistributed(Dense(32))` call will be `(batch_size, 10, 32)`, like the comments say. The comment "The output will then have shape `(32, 10, 8)` refers to the shape after the `TimeDistributed(Dense(8))` call.

**Comment by JohanWu** [comment]
@sallamander Thanks a lot for the precise answer!
