### ISSUE TITLE
GPU value error

### ISSUE THREAD

**Issue by JWarlock** [fchollet/keras#6197]
I am using ResNet50 to extract features from some pictures. I am using Anaconda 2 , Keras 2.0.2 , Theano 0.9.0, CUDA 7.5 on Win10.
However, if I load_weights file (resnet50_weights_th_dim_ordering_th_kernels_notop.h5)from local environment:
    model = ResNet50(include_top=False, weights=None,
                      input_tensor=None, input_shape=None,
                      pooling=None)
   model.load_weights(weight_path+'/resnet50_weights_th_dim_ordering_th_kernels_notop.h5')
   ResNet50_feature=model.predict(train_data)

I get the following error:
    ValueError: GpuCorrMM images and kernel must have the same stack size

   Apply node that caused the error: GpuCorrMM{valid, (1, 1), (1, 1)}(GpuContiguous.0, GpuContiguous.0)
   Toposort index: 2136
   Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D)]
   Inputs shapes: [(32, 128, 28, 28), (512, 256, 1, 1)]
   Inputs strides: [(100352, 784, 28, 1), (256, 1, 0, 0)]
   Inputs values: ['not shown', 'not shown']
   Outputs clients: [[GpuElemwise{add,no_inplace}(GpuCorrMM{valid, (1, 1), (1, 1)}.0, GpuReshape{4}.0)]]

if I just random Initialize the weight,then everything works just fine:
      model = ResNet50(include_top=False, weights=None,
                      input_tensor=None, input_shape=None,
                      pooling=None
   ResNet50_feature=model.predict(train_data)

I know I could set weight='imagenet' and download it automatically, but I always get:
    Exception: URL fetch failure on https://github.com/fchollet/deep-learning-   models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5: None -- [Errno 10060]

So I have to use local weight h5 file. But if I load_weights from resnet50_weights_th_dim_ordering_th_kernels_notop.h5 , I always get GPU error

**Comment by fchollet** [comment]
> resnet50_weights_th_dim_ordering_th_kernels_notop.h5

This file is outdated and not supposed to work anymore. Use the built-in weight loading instead.
