### ISSUE TITLE
Plot from keras.utils.visualize_util crashes in Keras 0.3.2

### ISSUE THREAD

**Issue by MehulAjax21** [fchollet/keras#6204]
Hi Guys,
I want to visualize my graph by plotting it. But I see that the the pydot-ng crashes after running for a long time.
I am using the keras version 0.3.2
pydot-ng version 1.0.0
graphviz version 2.38.0

Please let me know if the versions are to be downgraded for old keras

**Comment by eamag** [comment]
keras has this function in utils/vis_utils.py:
```
def _check_pydot():
    if not (pydot and pydot.find_graphviz()):
        raise ImportError('Failed to import pydot. You must install pydot'
                          ' and graphviz for `pydotprint` to work.')
```
but `pydot.find_graphviz()` was deprecated ([explanation](https://github.com/erocarrera/pydot/issues/126#issuecomment-277791370)), so I suggest PR to fix that
