### ISSUE TITLE
save keras model as .pb tensorflow model

### ISSUE THREAD

**Issue by gauravshelangia** [fchollet/keras#6212]
Please, tell me how can I save Keras model as a tensorflow model ( .pb).
Actually, I want to use the learned model on android that's why I need **.pb** model.
Or is there any other way to run Keras model on android

**Comment by Dref360** [comment]
This question is best suited for StackOverflow,
You can get the current session with K.get_session() then follow any Tensorflow tutorial

**Comment by dhilton** [comment]
This issue is relevant here: https://github.com/fchollet/keras/issues/3223  as @Dref360 said your issue is more suited for StackOverflow.

**Comment by nixingyang** [comment]
I think this scenario is quite interesting. Unfortunately, I haven't found any detailed guide yet.

**Comment by gauravshelangia** [comment]
Okay, No problem, I managed to run the Keras model on android using **deeplearning4j**.

**Comment by saria85** [comment]
@gauravshelangia would yyou please share ur approach, I have the same problem, I mean I wanna to run keras model on android  and I am really stuck in

**Comment by gauravshelangia** [comment]
I build the neural net using **keras** and then import the keras model on android. Look at this issue https://github.com/deeplearning4j/deeplearning4j/issues/3261

**Comment by MoriatyC** [comment]
@gauravshelangia I use dl4j to add keras model ,but it has a unknow exception.**HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:**.Do you know how to solve it?

**Comment by gauravshelangia** [comment]
@MoriatyC sorry, I don't know how to solve this error. 
Can you provide some more information on how you got this error like while loading the keras model in dl4j on android or desktop.

**Comment by jinhshi** [comment]
@MoriatyC 
Hi~
I use dl4j ，have the same problem of you 
May I ask how you solved the problem at that time ？

**Comment by gauravshelangia** [comment]
https://gist.github.com/gauravshelangia/97f5ca0cd8e0f10f6df8581fa5b5209a
this might help you @jinhshi
