### ISSUE TITLE
Loading saved model config + weights

### ISSUE THREAD

**Issue by griff4692** [fchollet/keras#6214]
In my main.py file, I save weights using `model.to_yaml()` and writing a config.yaml file to disk.  I also save teh weights at the end of training as an 'h5' file.

When I want to load the config, I open the yaml file, and call read() on it.  Then I pass this read object into model_from_yaml but get the following error:

`raise ValueError('Missing layer: ' + inbound_layer_name)
ValueError: Missing layer: context_input`

context_input is the name of my input layer.

I am using Keras 2.0.1.  What could be the issue?  I've tried many different things (model.save, json config, etc.)

**Comment by verashira** [comment]
`to_yaml()` only saves the **architecture** of a model, not its weights or its training configuration, you may find this helpful [FAQ](https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model)

It is hard to say the reason without the code, but you may try to examine the generated yaml file directly to see if `context_input` layer is there, as yaml is human-readable.

**Comment by nabihach** [comment]
I have the same issue, and I am using Keras 2.0.3 functional API. I do `model.save()` to save the model and then try to load it using `keras.models.load_model`, but it produces 
`raise ValueError('Missing layer: ' + inbound_layer_name) ValueError: Missing layer: `

**Comment by nabihach** [comment]
Update:
I tried json and yaml tricks, they didn't work. After a lot of search online, the best solution I've found is by AahanSingh here: https://github.com/fchollet/keras/issues/5442

Works like a charm and doesn't require changing the model set up in any way.

**Comment by baregawi** [comment]
Did you model have shared layers? If so that seems to be a known issue: https://github.com/fchollet/keras/issues/6481

With a pending fix: https://github.com/fchollet/keras/pull/7041
