### ISSUE TITLE
Test Generator Filenames: Not shuffled when shuffle=True

### ISSUE THREAD

**Issue by abnera** [fchollet/keras#6234]
Normal Behavior:
```    
test_generator = test_datagen.flow_from_directory(test_data_dir,
                                                      target_size=(img_height, img_width),
                                                      batch_size=batch_size,
                                                      shuffle=False)
y_probabilities = model.predict_generator(test_generator,
                                              val_samples=test_generator.nb_sample)
y_predictions = probas_to_classes(y_probabilities)

```
True: `y_predictions[0] == test_generator.classes[0]`

Because `shuffle=False` I can map `test_generator.filenames` or `test_generator.classes` to the output predictions without any problems. `y_predictions[0] == test_generator.classes[0]`

However, I have an edge case where I need/want to make `shuffle=True`, but I cannot map `test_generator.filenames` and `test_generator.classes` to the out predictions. This is because `test_generator.filenames` returns the list before shuffling and the `y_probabilities` return the list are shuffling. 

Error/Bug:
```
test_generator = test_datagen.flow_from_directory(test_data_dir,
                                                      target_size=(img_height, img_width),
                                                      batch_size=batch_size,
                                                      shuffle=True)
y_probabilities = model.predict_generator(test_generator,
                                              val_samples=test_generator.nb_sample)
y_predictions = probas_to_classes(y_probabilities)
```
False: `y_predictions[0] == test_generator.classes[0]`

Please, someone, help me solve this bug.
Thanks.

**Comment by melissa1601** [comment]
Hi, did you find the solution?

**Comment by abnera** [comment]
@melissa1601 There is no solution. For now, you have to ensure that your test/validation generator is `shuffle=False` in order to map it to the filenames. Since the filenames do not keep track of the shuffling indexes. Not sure why no one has yet to implement or fix this.
