### ISSUE TITLE
[/keras/tensorflow] Writing your own layer

### ISSUE THREAD

**Issue by samik1986** [fchollet/keras#6235]
I am very new to keras.
I'm trying to write (using Functional API) a custom layer in Keras as in Keras.io

```
`class MyLayer(Layer):
    def __init__(self, output_dim, **kwargs):
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # Create a trainable weight variable for this layer.
        self.kernel = self.add_weight(shape=(input_shape[1], self.output_dim),
                                      initializer='uniform',
                                      trainable=True)
        super(MyLayer, self).build(input_shape)  # Be sure to call this somewhere!

    def call(self, x):
        return K.dot(x, self.kernel)

    def compute_output_shape(self, input_shape):
        return (input_shape[0], self.output_dim)'
```

calling as `:`
`'sourcedistribution = Mylayer(dropout2_target)'`

The error traceback is as follows:

File "/root/PycharmProjects/chNET/modelBuild.py", line 77, in <module>
    model = create_network([100, 100, 3])
  File "/root/PycharmProjects/chNET/modelBuild.py", line 53, in create_network
    sourcedistribution = Mylayer(dropout2_source)
NameError: global name 'Mylayer' is not defined

Please help to understand this error.

**Comment by squidszyd** [comment]
You must first initialize that layer and then call it on an input tensor I think.
`from <your implementation python file> import Mylayer`
`...`
`sourcedistribution = Mylayer()(dropout2_target)`

**Comment by deepersystems** [comment]
https://github.com/deepersystems/consolenet

**Comment by Red-Eyed** [comment]
NameError: global name 'Mylayer' is not defined
It's not defined because you have declared "My**L**ayer"
