### ISSUE TITLE
from keras.engine.topology import Merge Failed

### ISSUE THREAD

**Issue by hengqujushi** [fchollet/keras#6240]
Using TensorFlow backend.
Traceback (most recent call last):
  File "deepnet.py", line 10, in <module>
    from keras.engine.topology import Merge
ImportError: cannot import name Merge

**Comment by sallamander** [comment]
@hengqujushi that's the wrong place to import `Merge` from. You can import it from `keras.layers` instead, although if you're using Keras 2 you should check out the [keras.layers.merge](https://github.com/fchollet/keras/blob/7f58b6fbe702c1936e88a878002ee6e9c469bc77/keras/layers/merge.py) module, as the `Merge` layer has been replaced in favor of individual merge layers (`Add`, `Concatenate`, etc.) or individual merge functions (`add`, `concatenate`, etc.).

**Comment by fchollet** [comment]
Correct, import it from `keras.layers`.
