### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_weights'

### ISSUE THREAD

**Issue by Alisaincd** [fchollet/keras#6241]
hi, I just got a problem when I run a sequential model. 
I fit the model firstly, and then I want to get the first FullConnect Layer's parameters ,that is  "dense1 = model.get_layer(index=1).get_weights()".  But I got the wrong "AttributeError: 'NoneType' object has no attribute 'get_weights' "。I have no idea about this. Can anyone help me?

Sincerely

**Comment by sallamander** [comment]
@Alisaincd Do you have a script that could recreate the error? It looks like you're trying to index for a layer that the model doesn't actually have. Using `model.layers`, you can get a list of the layers that the model has, and index from there. From the looks of the above note, you're model doesn't have a layer at index 1.
