### ISSUE TITLE
Problem with conv1D dimension

### ISSUE THREAD

**Issue by protti** [fchollet/keras#6242]
Hi, I have tried to build a CNN with one layer, but I have some problem with it. 
Indeed, the compilator says me that 

`ValueError: Error when checking model input: expected conv1d_1_input to have 3 dimensions, but got array with shape (569, 30)
`

This is the code

```
import numpy
from keras.models import Sequential
from keras.layers.convolutional import Conv1D
numpy.random.seed(7)
datasetTraining = numpy.loadtxt("CancerAdapter.csv",delimiter=",")
X = datasetTraining[:,1:31]
Y = datasetTraining[:,0]
datasetTesting = numpy.loadtxt("CancereEvaluation.csv",delimiter=",")
X_test = datasetTraining[:,1:31]
Y_test = datasetTraining[:,0]
model = Sequential()
model.add(Conv1D(2,2,activation='relu',input_shape=X.shape))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=150, batch_size=5)
scores = model.evaluate(X_test, Y_test)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
```

**Comment by ParseThis** [comment]
see my answer on [stackoverflow](http://stackoverflow.com/questions/43396572/dimension-of-shape-in-conv1d/43399308#43399308)

**Comment by Invince11** [comment]
@ParseThis  Hi I saw your answer on stackoverflow. I usually make model by model.add() and adding layers to it. You didn't specify any activation layer in the conv1D and dense layers. And when I train my dataset using your model accuracy shoots till 99 but when I add 'relu' activation layer to the Conv1D and 'sigmoid' to the Dense layer the accuracy drops to 20.

I didn't understand your network. It would be great if you can help me with this.
Thanks already! :)

**Comment by canibal1** [comment]
` import numpy as np
from sklearn.model_selection import train_test_split
from numpy import zeros, newaxis
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from matplotlib import pyplot
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.utils import to_categorical

seed = 737454
np.random.seed(seed)

X = veriyeni1.values[:]
Y = veriyeni2.values[:]   
#X = np.expand_dims(X, axis=2)
#Y = np.expand_dims(Y, axis=2)

(X_train, X_test, Y_train, Y_test) = train_test_split(X, Y, test_size=0.33, random_state=seed)
print(X_train.shape)



n_timesteps, n_features, n_outputs = X_train.shape[0], X_train.shape[1], Y_train.shape[0]
verbose, epochs, batch_size = 0, 10, 32
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=X_train.shape))
model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(Dropout(0.5))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(n_outputs, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=epochs, batch_size=batch_size, verbose=verbose) `

`Ximport numpy as np
from sklearn.model_selection import train_test_split
from numpy import zeros, newaxis
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from matplotlib import pyplot
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.utils import to_categorical

seed = 737454
np.random.seed(seed)

X = veriyeni1.values[:]
Y = veriyeni2.values[:]   
#X = np.expand_dims(X, axis=2)
#Y = np.expand_dims(Y, axis=2)

(X_train, X_test, Y_train, Y_test) = train_test_split(X, Y, test_size=0.33, random_state=seed)
print(X_train.shape)



n_timesteps, n_features, n_outputs = X_train.shape[0], X_train.shape[1], Y_train.shape[0]
verbose, epochs, batch_size = 0, 10, 32
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=X_train.shape))
model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(Dropout(0.5))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(n_outputs, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=epochs, batch_size=batch_size, verbose=verbose))`

ValueError: Error when checking input: expected conv1d_34_input to have 3 dimensions, but got array with shape (50000, 2)






`X = veriyeni1.values[:]
Y = veriyeni2.values[:]   
X = np.expand_dims(X, axis=2)
Y = np.expand_dims(Y, axis=2)`



ValueError: Input 0 is incompatible with layer conv1d_36: expected ndim=3, found ndim=4

**Comment by canibal1** [comment]
```
`import numpy as np
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from matplotlib import pyplot
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Dropout
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from numpy import zeros, newaxis
seed = 737454
np.random.seed(seed)

X = veriyeni1.values[:]
Y = veriyeni2.values[:]   
#X = np.expand_dims(X, axis=2)
#Y = np.expand_dims(Y, axis=2)

(X_train, X_test, Y_train, Y_test) = train_test_split(X, Y, test_size=0.33, random_state=seed)
print(X_train.shape)`
```

> (33500, 2)

```
n_timesteps, n_features, n_outputs = X_train.shape[0], X_train.shape[1], Y_train.shape[0]
verbose, epochs, batch_size = 0, 10, 32
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=X_train.shape))
model.add(Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(Dropout(0.5))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(100, activation='relu'))
model.add(Dense(n_outputs, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=epochs, batch_size=batch_size, verbose=verbose)

```

 > ValueError: Error when checking input: expected conv1d_37_input to have 3 dimensions, but got array with shape (50000, 2) 







```
X = veriyeni1.values[:]
Y = veriyeni2.values[:]   
X = np.expand_dims(X, axis=2)
Y = np.expand_dims(Y, axis=2)

(X_train, X_test, Y_train, Y_test) = train_test_split(X, Y, test_size=0.33, random_state=seed)
print(X_train.shape)
```

> (33500, 2, 1)

......

> Input 0 is incompatible with layer conv1d_39: expected ndim=3, found ndim=4

**Comment by canibal1** [comment]
> see my answer on [stackoverflow](http://stackoverflow.com/questions/43396572/dimension-of-shape-in-conv1d/43399308#43399308)

I try tsih answer but Its not working
