### ISSUE TITLE
Image dataset representation in Keras

### ISSUE THREAD

**Issue by svjan5** [fchollet/keras#6251]
I want to know that in Keras are we constrained to represent image dataset as `[image_index, channels, rows, cols]` and not `[image_index, rows, cols, channels]`? Based on this [line](https://github.com/fchollet/keras/blob/97174dd298cf4b5be459e79b0181a124650d9148/keras/layers/normalization.py#L83) in `normalization.py` it seems that library makes this assumption.

**Comment by Dref360** [comment]
@pranv Seems you missed to look for image_dim but you pushed this code more than a year ago :P
