### ISSUE TITLE
Adasecant optimizer for Keras?

### ISSUE THREAD

**Issue by kzk2000** [fchollet/keras#6253]
Question

Paper **[A Robust Adaptive Stochastic Gradient Method for Deep Learning](https://arxiv.org/pdf/1703.00788v1.pdf)** proposes the **AdaSecant** optimizer. Its code is available in https://github.com/sotelo/scribe/blob/master/algorithms.py but the code is based on blocks + theano.

Is there an easy way to convert this code into a Keras optimizer?

**Comment by maxleverage** [comment]
This shouldn't be hard to implement. Let me have a read of the paper first.

**Comment by indra-ipd** [comment]
Has anyone tried implementing Adasecant in Keras?
