### ISSUE TITLE
Custom prediction method

### ISSUE THREAD

**Issue by dkarmon** [fchollet/keras#6264]
I would like to use a custom prediction method in a given Kears model.

For example, say I have a binary classifier and my prediction rule says that if the probability that an example belongs to class A is less than 0.8 then it should be labeled as class B (instead of 0.5 currently).

Is there any way to override predict method in Keras and not use `predict_proba` externally method and then applying the custom prediction rule?

**Comment by Dref360** [comment]
Hi!
This question seems best suited for StackOverflow. Could you post your issue there? Also, remember to close your issue if you do so!
Thanks!
