### ISSUE TITLE
How to pass callback to model.predict?

### ISSUE THREAD

**Issue by HackerzWorkshop** [fchollet/keras#6270]
Hi, 
I'm using stateful RNN model with custom callback which resets state between batches on training. I want to use the same callback when predicting with this model. (Each batch in my dataset is a separate sequence.) Can I do this using callbacks, or my only option is to run a loop with predict_batch and reset_state on each iteration?

Thanks :)

**Comment by bstriner** [comment]
If you want a stateful RNN to reset state between batches then it is a stateless RNN (at least during training). Simplest solution might be to just do that, then load those weights into a stateful RNN for whatever stateful stuff you want to do during testing. 

That said, predict loop does not have callback hooks yet (`training.py`) but that should be a PR eventually.

If you just want to get stuff done and don't care how it looks, throw some custom code into `_predict_loop` in `training.py`. 

Cheers
