### ISSUE TITLE
Keras > 1.1.1 breaks convergence on a net

### ISSUE THREAD

**Issue by qichaozhao** [fchollet/keras#6273]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Hi team,

I have been experimenting with this implementation of a convnet:
https://github.com/johnb30/py_crepe

The dataset is available from this link:
https://drive.google.com/drive/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M?usp=sharing (ag_news_csv.tar.gz)

I have found that when using Keras 1.1.1 (or earlier), on both TF and TH backends, this model will start converging and learning (start at 25% and after 9 epochs is >90%). 

Trying on the latest versions of Keras, I will not get any convergence. I iteratively tried different versions of Keras and found that the update from version 1.1.1 to version 1.1.2 is the one that makes the difference. I made no other modifications to the code other than upgrading the Keras package.

Would anyone have any idea what is going on? 

I'd like to be able to experiment with this network on the latest versions of Keras and TF if possible. I would also like to verify if there was a bug that was fixed post 1.1.1 (which then caused the net to break), or if there was a bug that was introduced post 1.1.1 (which then caused the net to break). :)

**Comment by the-moliver** [comment]
One big change I see is a difference in the default Convolution1D weight initializers between 1.1.1 and 1.1.2, from `init='uniform'` to `init='glorot_uniform'`. That could definitely be the source of your issue, especially when using vanilla SGD to train.

**Comment by qichaozhao** [comment]
Ah, that was it indeed, thanks very much for the pointer. I explicitly declared the initialisation and I can see convergence now. Thanks :)
