### ISSUE TITLE
ImportError: cannot import name 'initializations'

### ISSUE THREAD

**Issue by fengjiqiang-git** [fchollet/keras#6278]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Franck-Dernoncourt** [comment]
I have the same issue. My environment: tensorflow==1.1.0; Keras==2.0.3; Python 2.7.12; Ubuntu 16.04 LTS x64.

Running `from keras import initializations`  in the python interpreter triggers the issue:

```
>>> from keras import initializations
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name initializations
```

**Comment by fengjiqiang-git** [comment]
In Keras 2.0, initializations was renamed as initializers. You should therefore instead write

from keras import initializers

At 2017-04-23 11:40:24, "Franck Dernoncourt" <notifications@github.com> wrote:


I have the same issue. My environment: tensorflow==1.1.0; Keras==2.0.3; Python 2.7.12; Ubuntu 16.04 LTS x64.

Running from keras import initializations in the python interpreter triggers the issue:

>>> from keras import initializations
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name initializations

**Comment by AyazSaiyed** [comment]
> In Keras 2.0, `initializations` was [renamed](https://github.com/fchollet/keras/commit/f2fe51a9d2bc9d228e3ac374579e87595f51fef6#diff-4ea1eab272323ecb1f250db1b8d83443) as `initializers`. You should therefore instead write
> 
> ```
> from keras import initializers
> ```

It worked for me !

**Comment by FengZhiheng** [comment]
> > In Keras 2.0, `initializations` was [renamed](https://github.com/fchollet/keras/commit/f2fe51a9d2bc9d228e3ac374579e87595f51fef6#diff-4ea1eab272323ecb1f250db1b8d83443) as `initializers`. You should therefore instead write
> > ```
> > from keras import initializers
> > ```
> 
> It worked for me !

It works for me, too!
