### ISSUE TITLE
the embedding function in the Tensorborad callback seems visualized the weight instead of the output

### ISSUE THREAD

**Issue by ssiaw12345** [fchollet/keras#6287]
in the keras/keras/callbacks.py class TensorBoard

`             embeddings = {layer.name: layer.weights[0]
                          for layer in self.model.layers
                          if layer.name in embeddings_layer_names}

            embeddings_metadata = {}

            if not isinstance(self.embeddings_metadata, str):
                embeddings_metadata = self.embeddings_metadata
            else:
                embeddings_metadata = {layer_name: self.embeddings_metadata
                                       for layer_name in embeddings.keys()}

            config = projector.ProjectorConfig()
            self.embeddings_logs = []

            for layer_name, tensor in embeddings.items():
                embedding = config.embeddings.add()
                embedding.tensor_name = tensor.name

                self.embeddings_logs.append(os.path.join(self.log_dir,
                                                         layer_name + '.ckpt'))

                if layer_name in embeddings_metadata:
                    embedding.metadata_path = embeddings_metadata[layer_name]

            projector.visualize_embeddings(self.writer, config)`

the embedding tensor is the weight of the target layer, but in my understanding, the embedding process should visualization the output of the target layer.  Do I misunderstand the code?

**Comment by ssiaw12345** [comment]
I have modified the Tensorboard class as shown in the following code, but it does not work. There is no error, but the Tensorboard can not recognize embedding [data.](http://wx1.sinaimg.cn/large/47a76ef2ly1feqvgq6av6j210w0l6t9l.jpg)

`class Tensorboard(Callback):
    """Tensorboard basic visualizations.
    This callback writes a log for TensorBoard, which allows
    you to visualize dynamic graphs of your training and test
    metrics, as well as activation histograms for the different
    layers in your model.
    TensorBoard is a visualization tool provided with TensorFlow.
    If you have installed TensorFlow with pip, you should be able
    to launch TensorBoard from the command line:
    ```
    tensorboard --logdir=/full_path_to_your_logs
    ```
    You can find more information about TensorBoard
    [here](https://www.tensorflow.org/versions/master/how_tos/summaries_and_tensorboard/index.html).
    # Arguments
        log_dir: the path of the directory where to save the log
            files to be parsed by Tensorboard.
        histogram_freq: frequency (in epochs) at which to compute activation
            histograms for the layers of the model. If set to 0,
            histograms won't be computed.
        write_graph: whether to visualize the graph in Tensorboard.
            The log file can become quite large when
            write_graph is set to True.
        write_images: whether to write model weights to visualize as
            image in Tensorboard.
        embeddings_freq: frequency (in epochs) at which selected embedding
            layers will be saved.
        embeddings_layer_names: a list of names of layers to keep eye on. If
            None or empty list all the embedding layer will be watched.
        embeddings_metadata: a dictionary which maps layer name to a file name
            in which metadata for this embedding layer is saved. See the
            [details](https://www.tensorflow.org/how_tos/embedding_viz/#metadata_optional)
            about metadata files format. In case if the same metadata file is
            used for all embedding layers, string can be passed.
    """

    def __init__(self, log_dir='./logs',
                 histogram_freq=0,
                 write_graph=True,
                 write_images=False,
                 embeddings_freq=0,
                 embeddings_layer_names=None,
                 embeddings_metadata=None,
                 validation_set_size=None):
        if K.backend() != 'tensorflow':
            raise RuntimeError('TensorBoard callback only works '
                               'with the TensorFlow backend.')
        self.log_dir = log_dir
        self.histogram_freq = histogram_freq
        self.merged = None
        self.write_graph = write_graph
        self.write_images = write_images
        self.embeddings_freq = embeddings_freq
        self.embeddings_layer_names = embeddings_layer_names
        self.embeddings_metadata = embeddings_metadata or {}
        self.validation_set_size=validation_set_size

    def set_model(self, model):
        self.model = model
        self.sess = K.get_session()
        if self.histogram_freq and self.merged is None:
            for layer in self.model.layers:

                for weight in layer.weights:
                    tf.summary.histogram(weight.name, weight)
                    if self.write_images:
                        w_img = tf.squeeze(weight)
                        shape = w_img.get_shape()
                        if len(shape) > 1 and shape[0] > shape[1]:
                            w_img = tf.transpose(w_img)
                        if len(shape) == 1:
                            w_img = tf.expand_dims(w_img, 0)
                        w_img = tf.expand_dims(tf.expand_dims(w_img, 0), -1)
                        tf.summary.image(weight.name, w_img)

                if hasattr(layer, 'output'):
                    tf.summary.histogram('{}_out'.format(layer.name),
                                         layer.output)
        self.merged = tf.summary.merge_all()

        if self.write_graph:
            self.writer = tf.summary.FileWriter(os.path.join(self.log_dir,model.name),
                                                self.sess.graph)
        else:
            self.writer = tf.summary.FileWriter(os.path.join(self.log_dir,model.name))

        if self.embeddings_freq:
            self.saver = tf.train.Saver()

            embeddings_layer_names = self.embeddings_layer_names

            if not embeddings_layer_names:
                embeddings_layer_names = [layer.name for layer in self.model.layers
                                          if type(layer).__name__ == 'Embedding']
            
            from operator import mul
            length_=reduce(mul,layer.output_shape[1:])
            self.embeddings={}
            tensor_dict={}
            for layer in self.model.layers:
                if layer.name in embeddings_layer_names:
                    tensor_dict[layer.name]=tf.Variable(tf.zeros([self.validation_set_size, length_]), name=layer.name+"embedding")
                    tensor_dict[layer.name].assign(K.reshape(layer.output,[self.validation_set_size,length_]))
                    self.embeddings[layer.name] = tensor_dict[layer.name]

            self.sess.run(tf.global_variables_initializer())
            embeddings_metadata = {}

            if not isinstance(self.embeddings_metadata, str):
                embeddings_metadata = self.embeddings_metadata
            else:
                embeddings_metadata = {layer_name: self.embeddings_metadata
                                       for layer_name in self.embeddings.keys()}

            config = projector.ProjectorConfig()
            self.embeddings_logs = {}        
            
            for layer_name, tensor in self.embeddings.items():
                embedding = config.embeddings.add()
                embedding.tensor_name = tensor.name
                
                self.embeddings_logs[layer_name]=os.path.join(self.log_dir,layer_name + '.ckpt')

                if layer_name in embeddings_metadata:
                    embedding.metadata_path = embeddings_metadata[layer_name]

            projector.visualize_embeddings(self.writer, config)

    def on_epoch_end(self, epoch, logs=None):
        logs = logs or {}

        if self.validation_data and self.histogram_freq:
            if epoch % self.histogram_freq == 0:
                # TODO: implement batched calls to sess.run
                # (current call will likely go OOM on GPU)
                if self.model.uses_learning_phase:
                    cut_v_data = len(self.model.inputs)
                    val_data = self.validation_data[:cut_v_data] + [0]
                    tensors = self.model.inputs + [K.learning_phase()]
                else:
                    val_data = self.validation_data
                    tensors = self.model.inputs
                feed_dict = dict(zip(tensors, val_data))
                result = self.sess.run([self.merged], feed_dict=feed_dict)
                summary_str = result[0]
                self.writer.add_summary(summary_str, epoch)

        if self.embeddings_freq and self.embeddings_logs:
            if epoch % self.embeddings_freq == 0:
                for layer_name, tensor in self.embeddings.items():
                    self.sess.run(tensor, feed_dict=feed_dict)
                    self.saver.save(self.sess, self.embeddings_logs[layer_name], epoch)

        for name, value in logs.items():
            if name in ['batch', 'size']:
                continue
            summary = tf.Summary()
            summary_value = summary.value.add()
            summary_value.simple_value = value.item()
            summary_value.tag = name
            self.writer.add_summary(summary, epoch)
        self.writer.flush()

    def on_train_end(self, _):
        self.writer.close()
 `

**Comment by ssiaw12345** [comment]
Now I rewrite the class, and it works.
but something is strange in embedding...


`class embedding_tensorboard(Callback):
    def __init__(self, log_dir='./logs',
                 histogram_freq=0,
                 write_graph=True,
                 write_images=False,
                 embeddings_freq=0,
                 embeddings_layer_names=None,
                 embeddings_metadata=None,
                 validation_set_size=None):
        if K.backend() != 'tensorflow':
            raise RuntimeError('TensorBoard callback only works '
                               'with the TensorFlow backend.')
        self.log_dir = log_dir
        self.histogram_freq = histogram_freq
        self.merged = None
        self.write_graph = write_graph
        self.write_images = write_images
        self.embeddings_freq = embeddings_freq
        self.embeddings_layer_names = embeddings_layer_names
        self.embeddings_metadata = embeddings_metadata or {}
        self.validation_set_size=validation_set_size

    def set_model(self, model):
        self.model=model
        self.sess = tf.Session()
        
        if self.histogram_freq and self.merged is None:
            for layer in self.model.layers:

                for weight in layer.weights:
                    tf.summary.histogram(weight.name, weight)
                    if self.write_images:
                        w_img = tf.squeeze(weight)
                        shape = w_img.get_shape()
                        if len(shape) > 1 and shape[0] > shape[1]:
                            w_img = tf.transpose(w_img)
                        if len(shape) == 1:
                            w_img = tf.expand_dims(w_img, 0)
                        w_img = tf.expand_dims(tf.expand_dims(w_img, 0), -1)
                        tf.summary.image(weight.name, w_img)

                if hasattr(layer, 'output'):
                    tf.summary.histogram('{}_out'.format(layer.name),
                                         layer.output)
                
                #regularization
                from .regularizers import merge_regularizer
                if hasattr(layer,'kernel_regularizer'):
                    if not layer.kernel_regularizer==None:
                        if isinstance(layer.kernel_regularizer,merge_regularizer):
                            k_loss_list=layer.kernel_regularizer.results(layer.weights[0])
                            for i,k_l in enumerate(k_loss_list):
                                tf.summary.scalar('{}_kernel_reg_loss_{}'.format(layer.name,layer.kernel_regularizer.regularizer_name_list[i]),k_l)
                        else:
                            k_loss=layer.kernel_regularizer(layer.weights[0])
                            tf.summary.scalar('{}_kernel_reg_loss'.format(layer.name),k_loss)
                if hasattr(layer,'activity_regularizer'):
                    if not layer.activity_regularizer==None:
                        if isinstance(layer.activity_regularizer,merge_regularizer):
                            k_loss_list=layer.activity_regularizer.results(layer.output)
                            for i,k_l in enumerate(k_loss_list):
                                tf.summary.scalar('{}_activity_reg_loss_{}'.format(layer.name,layer.activity_regularizer.regularizer_name_list[i]),k_l)
                        else:
                            k_loss=layer.activity_regularizer(layer.output)
                            tf.summary.scalar('{}_activity_reg_loss'.format(layer.name),k_loss)
                if hasattr(layer,'bias_regularizer'):
                    if not layer.bias_regularizer==None:
                        if isinstance(layer.bias_regularizer,merge_regularizer):
                            k_loss_list=layer.bias_regularizer.results(layer.weights[1])
                            for i,k_l in enumerate(k_loss_list):
                                tf.summary.scalar('{}_activity_reg_loss_{}'.format(layer.name,layer.bias_regularizer.regularizer_name_list[i]),k_l)
                        else:
                            k_loss=layer.bias_regularizer(layer.weights[1])
                            tf.summary.scalar('{}_bias_reg_loss'.format(layer.name),k_loss)
                            
        self.merged = tf.summary.merge_all()

        if self.write_graph:
            self.writer = tf.summary.FileWriter(os.path.join(self.log_dir,model.name),
                                                self.sess.graph)
        else:
            self.writer = tf.summary.FileWriter(os.path.join(self.log_dir,model.name))
        
        if self.embeddings_freq:
            self.embeddings={}
            embeddings_layer_names = self.embeddings_layer_names
            if not embeddings_layer_names:
                embeddings_layer_names = [layer.name for layer in self.model.layers
                                          if type(layer).__name__ == 'Embedding']
            
            for layer in self.model.layers:
                if layer.name in embeddings_layer_names:
                    from operator import mul
                    length_=reduce(mul,layer.output_shape[1:])
                    self.embeddings[layer.name]=tf.Variable(tf.zeros([self.validation_set_size, length_]), name=layer.name+"_embedding")
                    self.embeddings[layer.name].assign(K.reshape(layer.output,[self.validation_set_size,length_]))
            self.sess.run(tf.global_variables_initializer())
            self.saver = tf.train.Saver(self.embeddings.values())
            config = projector.ProjectorConfig()
            
            if not isinstance(self.embeddings_metadata, str):
                embeddings_metadata = self.embeddings_metadata
            else: 
                embeddings_metadata = {layer_name: self.embeddings_metadata
                                               for layer_name in self.embeddings.keys()}
            self.embeddings_logs={}
            for name,emb in self.embeddings.items():
                    embed= config.embeddings.add()
                    embed.tensor_name = emb.name
                    self.embeddings_logs[name]=os.path.join(self.log_dir,model.name+'_'+name + '.ckpt')
                    if embeddings_metadata != None:
                        if name in embeddings_metadata:
                            embed.metadata_path = embeddings_metadata[name]
            projector.visualize_embeddings(self.writer, config)
    def on_epoch_end(self, epoch, logs=None):
        logs = logs or {}

        if self.validation_data and self.histogram_freq:
            if epoch % self.histogram_freq == 0:
                # TODO: implement batched calls to sess.run
                # (current call will likely go OOM on GPU)
                if self.model.uses_learning_phase:
                    cut_v_data = len(self.model.inputs)
                    val_data = self.validation_data[:cut_v_data] + [0]
                    tensors = self.model.inputs + [K.learning_phase()]
                else:
                    val_data = self.validation_data
                    tensors = self.model.inputs
                feed_dict = dict(zip(tensors, val_data))
                result = self.sess.run([self.merged], feed_dict=feed_dict)
                summary_str = result[0]
                self.writer.add_summary(summary_str, epoch)
        
        if self.validation_data and self.embeddings_freq and self.embeddings_logs:
            if self.model.uses_learning_phase:
                cut_v_data = len(self.model.inputs)
                val_data = self.validation_data[:cut_v_data] + [0]
                tensors = self.model.inputs + [K.learning_phase()]
            else:
                val_data = self.validation_data
                tensors = self.model.inputs
            feed_dict = dict(zip(tensors, val_data))
            if epoch % self.embeddings_freq == 0:
                for layer_name, tensor in self.embeddings.items():
                    self.sess.run(tensor, feed_dict=feed_dict)
                    self.saver.save(self.sess, self.embeddings_logs[layer_name], epoch)
        
        for name, value in logs.items():
            if name in ['batch', 'size']:
                continue
            summary = tf.Summary()
            summary_value = summary.value.add()
            summary_value.simple_value = value.item()
            summary_value.tag = name
            self.writer.add_summary(summary, epoch)
        self.writer.flush()
    def on_train_end(self, _):
        self.writer.close()`

**Comment by gewoonrik** [comment]
I am seeing the same problem indeed. Can you explain a little bit more what you changed?
