### ISSUE TITLE
VGG and ResNet50 model load in weights with wrong dimension ordering

### ISSUE THREAD

**Issue by IvanGoenawan** [fchollet/keras#6295]
This can be easily reproduced with the following short script:

```
from keras.applications.vgg16 import VGG16

model1 = VGG16(include_top=False)
print(model1.layers[1].weights[0].get_value().shape)    #3,64,3,3

model2 = VGG16(include_top=False,weights=None)
print(model2.layers[1].weights[0].get_value().shape)    #3,3,3,64
```

I'm using Keras with Theano. Both channels_first and channels_last format give the same result. The output dimension should come last using both settings. However, after loading in the weights from 'vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5', the weight dimensions are now wrong. This makes the model completely unusable and produces errors such as: 

ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[1] == 64, but the output's size on that axis is 3.
or
ValueError: GpuDnnConv images and kernel must have the same stack size

Using the old theano version weight file 'vgg16_weights_th_dim_ordering_th_kernels_notop.h5' seems to resolve the issue.

**Comment by fchollet** [comment]
This is a known bug: https://github.com/fchollet/keras/projects/1

Feel free to investigate.

**Comment by IvanGoenawan** [comment]
Would it be a good idea for models to always check whether weights that are loaded in have the same dimension as their original weights?

**Comment by brunodoamaral** [comment]
I'm having the same problem too, loading weighs from file 'vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5' and using Theano as backend with `image_data_format` set to "channels_first".
Digging into the issue, I found what it seems to be the culprit inside [preprocess_weights_for_loading](https://github.com/fchollet/keras/blob/master/keras/engine/topology.py#L2803-L2805):
```python
if layer.__class__.__name__ == 'Conv2D':
    if layer.data_format == 'channels_first':
        # old: (filters, stack_size, kernel_rows, kernel_cols)
        # new: (kernel_rows, kernel_cols, stack_size, filters)
        weights[0] = np.transpose(weights[0], (2, 3, 1, 0))
```
The value of `weight[0].shape` before transpose is `(3, 3, 3, 64)`. That is, the filter is the last dim, not the first, as stated in the comment.

@fchollet what should be the correct fix to this issue? Change the weights file or correct the old/new format?

**Comment by brunodoamaral** [comment]
I was able to fix it by forcing all layers in the model to become `'channels_last'` before calling `model.load_weights`. Afterwards, I restored the original `data_format`.

A general fix, IMHO, should be modify the `load_weights[_from_hdf5_group[_by_name]]` functions to not call `preprocess_weights_for_loading` if we are loading a hdf5 file that already has a `channels_last` format.

**Comment by the-moliver** [comment]
Here is a proposed fix: https://github.com/fchollet/keras/pull/6483
