### ISSUE TITLE
What's the difference between "samples_per_epoch" and "steps_per_epoch"???

### ISSUE THREAD

**Issue by HappyStorm** [fchollet/keras#6296]
Hello everyone, I was confused by this problem for several days...

My question is that why the training time has such massive difference between that I set the batch_size to be "1" and "20" for my generator.

If I set the **_batch_size_** to be **1**, the **training time** of _**1 epoch**_ is approximately **180 ~ 200 sec**.
If I set the **_batch_size_** to be **20**, the **training time** of **1 epoch** is approximately **3000 ~ 3200 sec**. 

However, this horrible difference between these training times seems to be abnormal..., since it should be the reversed result:
batch_size = 1, training time -> 3000 ~ 3200 sec.
batch_size = 20, training time -> 180 ~ 200 sec.

The input to my generator is not the file path, but the numpy arrays which are already loaded into the
memory via calling "np.load()".
So I think the I/O trade-off issue doesn't exist.

I'm using Keras-2.0.3 and my backend is tensorflow-gpu 1.0.1

I have seen the update of this merged [PR](https://github.com/fchollet/keras/pull/5879/files),
but it seems that this change won't affect anything at all. (the usage is just the same with original one)

The [link](https://gist.github.com/HappyStorm/cb6c22ffec18a8fbb4912e9c79b6d87c) here is the gist of my self-defined generator and the part of my fit_generator.

Could somebody help me explain this problem...???
Thank you so much...Orz

**Comment by isaacgerg** [comment]
This forum is not for discussion and is for issues.  Please remove and post in the forum.

**Comment by HappyStorm** [comment]
Sorry for that, I will post in the forum.
