### ISSUE TITLE
Feature request: HDF5Matrix support for inferred slice indexing

### ISSUE THREAD

**Issue by siryog90** [fchollet/keras#6297]
@fchollet @jfsantos @mezzode @SnowMasaya @Danielhiversen @lebavarois @nithishdivakar 
Hello,

The implementation of the `HDF5Matrix` class does not support inferred slices (e.g. `data[:10]`) as the code expects both `key.start` and `key.stop` to be integers.
https://github.com/fchollet/keras/blob/master/keras/utils/io_utils.py

Here is tiny modification to the `if` statement to support the said operation. 
https://github.com/siryog90/keras/blob/inferred_HDF5_slices/keras/utils/io_utils.py

This is a small issue, but it can get annoying when inferring the _end_ index (e.g. `data[10:]`), as I have to check the shape of the data set each time.

May I request a pull?

**Comment by fchollet** [comment]
Sure, go ahead and open a PR.

**Comment by kielnino** [comment]
Single item access with
```
idx = 0
X = HDF5Matrix(args.database, 'train_patches', 0, None)
tmp = X[idx]
```
gives now errors like 
```
File "/usr/local/lib/python3.4/dist-packages/keras/utils/io_utils.py", line 65, in __getitem__
    start, stop = key.start, key.stop
AttributeError: 'int' object has no attribute 'start'
```

**Comment by Danielhiversen** [comment]
@kielnino You are not using the newest version of Keras. Try to upgrade and see if that solves your problem.
