### ISSUE TITLE
Performance Using HDF5 File vs In-Memory Dataset

### ISSUE THREAD

**Issue by liujxing** [fchollet/keras#6298]
I am trying out using the HDF5 file as the format of training/testing data, so that I can avoid the problem of big dataset which cannot fit into the memory.

As a test, I used a dataset with about 20 million rows and 10 columns as my input, and my response variable is a real-valued vector. The model is a simple sequential model with 2 hidden layers and 50 neurons per hidden layer, and the training batch size is 10000. I am still using Keras version 1.2.0.

When the dataset is fully loaded into the memory, one epoch of training takes about 30 seconds. However, if I used HDF5 matrix with HDF5Matrix, one epoch of training takes about 360 seconds. Is this huge slow down common due to the I/O bottleneck? Shall I implement some perhaps better data loading process with fit_generator by myself by considering the specifications of my dataset?

**Comment by fchollet** [comment]
`fit_generator` is designed to run in parallel to the graph execution, so
it will not slow you down significantly. `HDF5Matrix` on the other hand
blocks execution while reading data.

You can try implementing a parallel queue system into HDF5Matrix. That
would be a welcome PR.

**Comment by absurdvision** [comment]
@fchollet 

I would like to give a pr for this issue. However since I do not have much knowledge about internals of keras, I would like to put forth a sample implementation and get validation before proceeding further.


My idea is to write a custom generator that takes in Hdf5 data sets.

`
def Hdf5_generator(X, y, batch_size):

    nsamples = len(X)
    
    start_idx = 0
    while True:
        
        if start_idx + batch_size > nsamples:
            start_idx = 0
        x_batch = X[start_idx:start_idx+batch_size, ...]
        y_batch = y[start_idx:start_idx+batch_size, ...]
        
        yield np.asarray(x_batch), np.asarray(y_batch)
`

I have tried with the generator and got a good speedup.

**Comment by gamazeps** [comment]
@fchollet If you ever get bored, having support for parallel reads on HDF5 would be extremely welcome for people with data which don't fit in memory (a few TBs).

Cheers !
