### ISSUE TITLE
Exception: Layer shape (1024, 4) not compatible with weight shape (1024, 5).

### ISSUE THREAD

**Issue by KeironO** [fchollet/keras#630]
Hey there,

I'm having trouble loading in a ```hdf5``` model.

When I load it in as follows:

```
model.load_weights('leafForm.hdf5')
habm_labels = model.predict_classes(habm_data)
```

I get the following stacktrace.

```
Traceback (most recent call last):
  File "/home/osheak/Documents/neural-network-plant-trait-classification/software/neuralNetworkSoftware/allExperiments/cnnTestHab.py", line 73, in <module>
    model.load_weights('leafForm.hdf5')
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 495, in load_weights
    self.layers[k].set_weights(weights)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 60, in set_weights
    raise Exception("Layer shape %s not compatible with weight shape %s." % (p.eval().shape, w.shape))
Exception: Layer shape (1024, 4) not compatible with weight shape (1024, 5).
```

**Comment by lukedeo** [comment]
Did you save the weights with `model.save_weights('fpath.h5')`?

**Comment by KeironO** [comment]
Hey there,

Thanks for replying. It was a problem unrelated to keras.

Thank you,

On 3 September 2015 at 13:00, Luke de Oliveira <notifications@github.com>
wrote:

> Did you save the weights with model.save_weights('fpath.h5')?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/630#issuecomment-137396627>.
>



-- 
Keiron O'Shea 毛毛
King Abdullah University of Science and Technology
Visiting Research Student, Computational Bioscience Research Center
Ymweld â myfyriwr ymchwil, Chyfrifiannol Canolfan Ymchwil Biowyddoniaeth

Aberystwyth University
PhD Student, Department of Computer Science
Israddedig, Adran o Cyfrifiadureg
keo7@aber.ac.uk || KeironTeilo.OShea@Kaust.edu.sa ||
http://users.aber.ac.uk/keo7
