### ISSUE TITLE
Conv2DTranspose does not work with Theano 0.9 (CorrMM shape inconsistency)

### ISSUE THREAD

**Issue by kmader** [fchollet/keras#6302]
The model is very simple
```python
def make_model(out_filters,kernel_size,strides):
    test_input=Input((1,18,18))
    test_conv=Conv2DTranspose(out_filters,
                    kernel_size=kernel_size,
                    strides=strides,
                    padding='same',
                    name='CONV_LAYER',
                    data_format=K.image_data_format())(test_input)
    t_model=Model(inputs=[test_input], outputs=[test_conv])
    return t_model
```
Runs fine with tensorflow but throws an error message for Theano. The message only happens when predicting or training the network (making and compiling work fine)

```python
m=make_model(4,(2,2),(2,2))
m=make_model(4,(4,4),(2,2))
```

Interestingly the code works fine for 
```python
m=make_model(4,(3,3),(2,2))
m=make_model(4,(3,3),(2,2))
```

The output error appears to be related to the padding size 
```
ValueError: CorrMM shape inconsistency:
  bottom shape: 1 4 36 36
  weight shape: 1 4 2 2
  top shape: 1 1 18 18 (expected 1 1 19 19)
```

Version Info
```
Theano-Version 0.9.0.dev-388805f946685e86225cdf602eb8a4f0059f9667
Tensorflow-Version 1.0.1
Keras-Version 2.0.2
```

Self-contained notebook link:
https://gist.github.com/5faf4e0184bb283a89567fb9d023635c

**Comment by mhirimohamed** [comment]
I have exactly the same problem ?

**Comment by goliathl** [comment]
I wasted whole week due to this
Now I found same problem here

**Comment by nouiz** [comment]
I saw somewhere that using keras fix such problems.

**Comment by wentaozhu** [comment]
I am facing the same problem. 

ValueError: impossible convolution output dim: expected 32x1024x4x11 but received gradient with shape 32x1024x3x10 

It happens in the keras Conv2DTranspose.

**Comment by nouiz** [comment]
Update Keras. I saw a fix that could help you.

**Comment by jaiabhayk** [comment]
Please can you let me know work around for this ?

**Comment by jaiabhayk** [comment]
I am also facing the same problem:--

ValueError: impossible convolution output dim: expected 32x512x5x5 but received gradient with shape 32x512x4x4

It happens in the keras (version=2.0.4) Conv2DTranspose.

**Comment by taehoonlee** [comment]
There is still the problem. Main reason is that the padding behavior for `Conv2DTranspose` is different between `TF` and `TH` in case of the `same` padding mode with even kernel sizes. Please see #6613.
