### ISSUE TITLE
Is it possible to add outputs (set existing layers as output) to an existing model without retraining?

### ISSUE THREAD

**Issue by ophiry** [fchollet/keras#6306]
I want to access the activation values of the hidden layers of a model
the method that looks the simplest (other suggestions are welcome) is to define these hidden layers as additional outputs with loss_weight set to 0

this appears to work fine when creating a new model.
Is there a way to change an existing (trained) model to add outputs?

**Comment by joelthchao** [comment]
Two ways:
```python
new_model = Model(inputs=model.input, outputs=model.get_layer(layer_name).output)
new_model = Model(inputs=model.input, outputs=model.layers[k].output)
```
Please check the [doc](https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer) for more details.
