### ISSUE TITLE
Bug in Babi MemNN Example in Attention Mechanism

### ISSUE THREAD

**Issue by EntilZha** [fchollet/keras#6308]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short). (NA)

I was looking at the Keras example for the MemNN model for the babi single supporting task. The paper is here: https://arxiv.org/pdf/1503.08895.pdf (relevant equations/figures are on page 2 in section 2.1)

I believe there is a bug in the implementation here: https://github.com/fchollet/keras/blob/master/examples/babi_memnn.py#L210

`match` is attention over a set of memory vectors represented as `input_encoded_c`. In the paper these are referenced as `p_i` and `c_i` respectively where `p_i` is a scalar and `c_i`is a vector. The formula from the paper broadcasts `p_i` to `c_i` in the sum `o=sum_i p_i*c_i` to produce the final output which in the code is `response`.

The implementation in the models repo uses `response = add([match, input_encoded_c])`. I think this should be something like `response = multiply([match, input_encoded_c])` instead since the current implementation seems to incorrectly correspond to `o=sum_i p_i + c_i`. Perhaps this is also the reason that there is a difference of performance with the paper result of 98.6% vs 100%?

If this does seem like a bug I would be happy to make the change, run the model to make sure it works, and submit a pull request.

**Comment by Iec2009030** [comment]
I also had the same doubt actually. Also the last stage why are we concatenating the result, Instead of simply adding as mentioned in the Paper End-to-End Memory Network. Is that too an error ?

**Comment by theSage21** [comment]
The concatenation I suspect arises from the switch to RNN instead of matrix multiplication in https://github.com/fchollet/keras/blob/master/examples/babi_memnn.py#L218
