### ISSUE TITLE
Incremental PCA using Keras

### ISSUE THREAD

**Issue by ruanxt** [fchollet/keras#6312]
Hi I'm trying to implement PCA using Keras and there are some errors, could anyone help me out? Here is my code: 

```
from keras.models import Model
import numpy as np
from keras.engine.topology import Layer
from keras.layers import Input
from keras.optimizers import RMSprop
import scipy.stats as stats
from sklearn.decomposition import IncrementalPCA
import keras.backend as K

class PCALayer(Layer):

    def __init__(self, pc_dim, input_dim=None, **kwargs):
        self.pc_dim = pc_dim
        self.input_dim = input_dim
        super(PCALayer, self).__init__(**kwargs)

    def build(self, input_shape):
        mean = 0.0
        std = 1.0
        pc_num = self.pc_dim
        p = self.input_dim
        initial_W_values = stats.truncnorm.rvs(-2 * std, 2 * std, loc=mean, scale=std, size=(pc_num, p))
        inital_b_values = np.zeros((1, p))
        self.W = K.variable(initial_W_values)
        self.b=K.zeros((1, p))

        self.ipca = IncrementalPCA(n_components=pc_num)

    def call(self, inputs, mask=None):
        print type(inputs)
        inputs_vals = inputs
        self.ipca.partial_fit(inputs_vals)
        self.W = self.ipca.components_
        self.b = self.ipca.mean_
        result = np.dot((inputs_vals - self.ipca.mean_), self.ipca.components_.T)
        return result

    def get_output_shape_for(self, input_shape):
        return(input_shape[0], self.pc_dim)

inputLayer = Input(shape=(10,))
PCLayer = PCALayer(pc_dim=3, input_dim=10)(inputLayer)

model = Model(input=inputLayer, output=PCLayer)
optimizer=RMSprop(lr=0.001)
model.compile(loss="mse", optimizer=optimizer)

model.fit(np.rand([100, 10]), np.rand([100, 3]), batch_size = 5, nb_epoch = 10)
```

And there are these errors:
```
Using TensorFlow backend.
Traceback (most recent call last):
<class 'tensorflow.python.framework.ops.Tensor'>
  File "/home/ruanxt/projects/DL_shapespace/code/layer_custom_v0.py", line 45, in <module>
    PCLayer = PCALayer(pc_dim=3, input_dim=10)(inputLayer)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 578, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/ruanxt/projects/DL_shapespace/code/layer_custom_v0.py", line 34, in call
    self.ipca.partial_fit(inputs_vals)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/decomposition/incremental_pca.py", line 199, in partial_fit
    X = check_array(X, copy=self.copy, dtype=[np.float64, np.float32])
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 373, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: setting an array element with a sequence.
```

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by Dref360** [comment]
Hi!
This question seems best suited for StackOverflow. Could you post your issue there? Also, remember to close your issue if you do so!
Thanks!

**Comment by bstriner** [comment]
StackOverflow is the place to go. Make sure to read the theano or tensorflow docs as well to understand the way computations work. `call` builds a graph of operations that can be performed on the GPU. It operates on tensors, which are symbolic references to a graph, not actual values. You can't just use any old function within `call`.

Basically, read the documentation on how to make custom layers. Whatever you want to implement needs to be a tensorflow/theano implementation, not any function from any library.

Cheers

**Comment by ruanxt** [comment]
Thanks very much! I will ask in StackOverflow.

**Comment by alyato** [comment]
@bstriner Thanks. It's  hard to understand the source code for keras.  

But you explain that

> `call` builds a graph of operations that can be performed on the GPU

I can know the `call` function do.

Do you give more advice to understand the source code. Thanks.

**Comment by bstriner** [comment]
@alyato not sure what you're asking. Try reading the `call` function for the standard `Dense` layer. It looks like it is doing a dot product and then an addition, as expected (`y=xW+b`). If you put a print statement in that function, it would only print once or twice no matter how many times you trained, because that function is just building up commands to do dot product and additon that are executed layer.

In terms of how that all works, tensorflow and theano override addition, multiplication, etc. for tensor objects, but you should ask about that on theano or TF forums, not here.

https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L839

Is there something you're trying to understand or trying to do?

Cheers

**Comment by spriyatham** [comment]
@ruanxt  were you able to do successfully implement the PCA layer?
