### ISSUE TITLE
Error when checking model target: expected time_distributed_1 to have 3 dimensions, but got array with shape (1822, 1)

### ISSUE THREAD

**Issue by yydxlv** [fchollet/keras#6318]
input = Input(shape=(None, 24), name='input')
x1 = LSTM(50, return_sequences=True, kernel_initializer="orthogonal", dropout=0.2)(input)
x2 = LSTM(50, return_sequences=True, kernel_initializer="orthogonal", dropout=0.2)(x1)
x3 = LSTM(50, return_sequences=True, kernel_initializer="orthogonal", dropout=0.2)(x2)
merge = merge([x3, x1], mode='sum')
output = TimeDistributed(Dense(output_dim=1, activation='linear', init='orthogonal'))(merge)
model = Model(input=input, output=output)
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

When compling the model , It occured ValueError: Error when checking model target: expected time_distributed_1 to have 3 dimensions, but got array with shape (1822, 1) 
can you give me some idea ?

**Comment by clindo** [comment]
Could you post the solution, which you found.
