### ISSUE TITLE
Merging Convolution2D layers: Wrong Dimension?

### ISSUE THREAD

**Issue by Mofef** [fchollet/keras#633]
I'm currently trying to implement the GoogLeNet using a `Graph` model and `Convolution2D`.

`model.fit(...)` results in the following error:
```
ValueError: GpuJoin: Wrong inputs for input 1 related to inputs 0.!
Apply node that caused the error: GpuJoin(...
...
Inputs shapes: [(), (500, 16, 24, 24), (500, 32, 24, 24), (500, 64, 24, 24), (500, 16, 24, 24)]
```
that suggests that the merging of the 4 convolution outputs is not done according to the 2nd dimension.

According to 
https://github.com/fchollet/keras/blob/master/keras/layers/containers.py#L227 
a `Merge` Layer is used for `add_output` and this one concatenates according to axis -1
https://github.com/fchollet/keras/blob/master/keras/layers/core.py#L197
would it be ok to change that to axis=1? or would that cause other problems? Then maybe the axis should be a parameter?

**Comment by Mofef** [comment]
Only now I notice the `()` empty tuple in the list of input shapes... I don't understand where it comes from... Do I use something wrong?

Toy example for mnist data:
```python
from keras.models import Graph
class Convoogle(Graph):
    def __init__(self, c11, r33, c33, r55, c55, pool_features, stack_size, **kwargs):
        super(Convoogle, self).__init__()
        if 'activation' not in kwargs:
            kwargs['activation']='relu'
        if 'init' not in kwargs:
            kwargs['init']='he_normal'
        if 'border_mode' in kwargs:
            assert kwargs['border_mode'] == 'same'
        else:
            kwargs['border_mode'] == 'same'

        self.add_input(name='input', ndim=4)
        self.add_node(Convolution2D(c11, stack_size, 1, 1, **kwargs), name='c11', input='input')

        self.add_node(Convolution2D(r33, stack_size, 1, 1, **kwargs), name='r33', input='input')
        self.add_node(Convolution2D(c33, r33, 3, 3, **kwargs), name='c33', input='r33')

        self.add_node(Convolution2D(r55, stack_size, 1, 1, **kwargs), name='r55', input='input')
        self.add_node(Convolution2D(c55, r55, 5, 5, **kwargs), name='c55', input='r55')
        
        self.add_node(ZeroPadding2D(1), name='pad', input='input',)
        self.add_node(MaxPooling2D((3,3),(1,1), ignore_border=False), name='pool', input='pad',)
        self.add_node(Convolution2D(pool_features, stack_size, 1, 1, **kwargs), name='pooled', input='pool')
        
        self.add_output(name='output1', inputs=['c11', 'c33', 'c55', 'pooled'])

model=Sequential()
model.add(Convolution2D(64,1,5,5))
model.add(Activation('relu'))
model.add(Convoogle(16,8,32,8,64,16, stack_size=64, border_mode='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D((3,3), (2,2), ignore_border=False))
model.add(Convoogle(16,16,32,16,64,16, stack_size=128, border_mode='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D((3,3), (2,2), ignore_border=False))
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(128*7*7,10))
model.add(Activation('softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)
```

**Comment by fchollet** [comment]
> would it be ok to change that to axis=1? or would that cause other problems? Then maybe the axis should be a parameter?

That would cause other problems. But you're right, the concatenation axis should definitely be configurable. This is already the case in the Caffe branch (precisely to support convolution output concatenation). Since we are quite late in merging the Caffe branch, we can incorporate this specific feature into master on its own.

**Comment by Mofef** [comment]
Sorry, I don't understand "we are quite late in merging the Caffe branch" you/we should have done it already? Or you can not do it at the moment? 

Anyway I tried to search for the commit that brought this change in the Caffe branch (btw thanks for pointing this out), hoping that I could just cherry-pick it into master... It turns out that it's a rather huge commit https://github.com/fchollet/keras/commit/bf997c19431ab12a10e60205c9e2b3c4c591e014#diff-05ec8fc63f0e9bb35f99c0ca76a66d0e so i guess it's easier to copy the changes by hand...? (maybe my git-foo is just not good enough?)

If you approve I'd do this and file a pull request.

**Comment by alyato** [comment]
@mofef,i'm using the merge class.But i can't understand the concat_axis = -1 ,1,or 2? Do you give me some advice please. Thanks.

**Comment by Mofef** [comment]
@alyato the concat axis is the axis along which to concatenate the two tensors.
Lets say you have two three-dimensional tensors of shape (2,3,5) and (2,3,10). Then you can only concatenate them along the third (zero based index: 2) axis, because then – figuratively – the two "faces" of the "cuboid" that you "glue together" are each 2-by-3 and only those fit. So you need to set concat_axis = 2 (or -1, since it is the last one) resulting in a new tensor (2,3,15). 
Typically in a NN you would merge along the axis of the features, which depends on the type of layers you use and the implementation in keras. If you are not sure you can try out a few, most likely only one will work for the reason given above. If the figurative "faces don't fit" you will get an error message like the one in my opening post.

I hope I was able to help :) If not feel free to ask.

**Comment by alyato** [comment]
@Mofef and @fchollet , I run the code in the latest keras. But it show me wrong?
![111](https://cloud.githubusercontent.com/assets/6815071/16066682/aa4370e2-3272-11e6-890a-bab4320d0850.png)
