### ISSUE TITLE
TypeError: can't pickle NotImplementedType objects using KerasRegressor

### ISSUE THREAD

**Issue by liyakun** [fchollet/keras#6348]
When I use KerasRegressor for testing by scikit_learn cross-validation method, it gives this error "TypeError: can't pickle NotImplementedType objects". A script which can produce this error is given in "https://github.com/liyakun/time_series/blob/master/lib.py"

**Comment by hamzamerzic** [comment]
Having the same issue with Lambda function as output of a model, when trying to save the model.

```
state_in = ...
h = ...
scale_matrix = K.constant(c) # c is a numpy matrix
out = Lambda(lambda x: K.dot(x, scale_matrix), output_shape=(n_out,))(h)

model = Model(inputs=[state_in], outputs=[out])
model.save(filename)
```

**Comment by damnMeddlingKid** [comment]
trying the same as @hamzamerzic , a previous issue suggested using json to save the model and the save_weights method to save the learned weights. 

this isn't working for me either.

**Comment by G-mel** [comment]
I have the same `TypeError: can't pickle NotImplementedType objects` error that @hamzamerzic and @damnMeddlingKid have when using `Lambda` in my model when attempting to `model.get_config()`
