### ISSUE TITLE
Layer params are nameless

### ISSUE THREAD

**Issue by rodrigob** [fchollet/keras#635]
Current values for `model.param[i].name` is None. When inspecting the created model it is hard to figure out what is what.

For now I am doing

```
self.params = [self.W, self.b]
self.W.name = "Dense W"
self.b.name = "Dense b"
```

but I guess this should be done better.

I saw Layer.set_name but:
a) It does not keep the naming W and b
b) Would break the usual `model.add(Convolution2D(32, 32, 3, 3))`
c) Is not called by default

What about being able to do
`model.add(Convolution2D(32, 32, 3, 3, name="conv5"))`

so that parameters names end up being `conv5.W` and `conv5.b`; and if name is None (default) then have them named (by default) as `Convolution2D.W` and `Convolution2D.b` ?

**Comment by anjishnu** [comment]
+1 for this issue.

**Comment by fchollet** [comment]
This is something we've started doing with Graph models, where parameters do have sensible names. I initially had plans to make parameter naming more widely available but it sort of fell through (it would require modifying every layer to add a `name` constructor parameter, as you point out). 

Is this something for which you want to prepare a PR?

**Comment by rodrigob** [comment]
I do not see what `Graph` related code you are referring to.
I can try to make a PR on this.

**Comment by wuaalb** [comment]
Did you check `keras.layers.containers.Graph` rather than `keras.models.Graph`?

Maybe for `Sequential` it would be nice if the default name could also includes the index of the parameter's `Layer` in the stack..? E.g.
```python
name = 'Layer%d_%s' % (self.layers.index(layer), type(layer).__name__)
```

I guess in that case `name` might be made a property of `Layer` rather than just being assigned to part of the parameter names..

**Comment by rodrigob** [comment]
Created PR #648 to fix this issue.
