### ISSUE TITLE
How to find indices from a tensor for a particular value similar to numpy.where()

### ISSUE THREAD

**Issue by Rithmax** [fchollet/keras#6354]
Hi,

I am searching for a command which is similar to python "numpy.where()" command. Basically my idea is to extract the indices from a tenser. In python I can do simply f_j=(np.where(X==j)) which gives me specific indices(f_j) for the value j.  

ex: X=  [0 1  1 0  0  2 3 ]
f_j=(np.where(X==1))
f_j= [1 2]

Is there is any similar function which I can use for this purpose?

I tried to write array search inside a tensor. However I end up with error when calling "if K.equal():" line as  
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

def loss(y_true, y_pred):
    b=K.equal(y_true,0)
    b=K.cast(b,dtype='float32')
    for i in range(0,5):
        if K.equal(b[i],1):
              ........

y_true = [0 1  1 0  0  2 3 ]

**Comment by Dref360** [comment]
Hi!
This question seems best suited for StackOverflow. Could you post your issue there? Also, remember to close your issue if you do so!
Thanks!

**Comment by Rithmax** [comment]
Hi, thanks for the reply. I am wondering why there is not any inbuilt function for this purpose. In keras backend simply If I know the indices I can use K.gather() to select those values. However, when comes to this problem I couldn't able to think a method to find indices with existing keras backend commands. So the only option is writing a searching algorithm using "for loop" and "if command". Moreover, when writing if command apparently it does not support keras boolean tensors. I think it would be really helpful if there is a command like K.where() in keras backend. 

So I wanted to know am I missing something in here? or does it exist a similar command to numpy.where()? 

According to your reply, I have put this in StackOverflow. Thank you.
