### ISSUE TITLE
Can't use kernel_regularizer in dense layer

### ISSUE THREAD

**Issue by Manipula** [fchollet/keras#6360]
When i use kernel_regularizer in dense layer, it will show me 
  **" TypeError: ('Keyword argument not understood:', 'kernel_regularizer') "**
But when i use activity_regularizer , it's ok.
my code is:
 model.add(Dense(250, kernel_regularizer=activity_l2(0.001), init='he_normal' ))

**Comment by joelthchao** [comment]
It's Keras 2 API, please check your Keras version. (old: `W_regularizer`)
