### ISSUE TITLE
generating and reshaping images

### ISSUE THREAD

**Issue by sachinruk** [fchollet/keras#6372]
The full example is here: https://github.com/sachinruk/keras_simpsons. Basically Im trying to read in a picture of homer simpson, rescale it to size 224, 224 and create rotations, shifts etc. However, when I run the code segment below I get the error: `ZeroDivisionError: integer division or modulo by zero`

```
train_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=5,
        zoom_range=0.2,
        horizontal_flip=True)

img_height = img_width = 224
train_generator = train_datagen.flow_from_directory(
    './train/',
    color_mode = "rgb",
    target_size=(img_height, img_width),
    batch_size=1,
    class_mode=None)

i = 0
img_list = []
for batch in train_generator: #.flow(x, batch_size=1)
    img_list.append(batch)
    i += 1
    if i > 5:
        break
```
The single simpsons image is in the `train` folder.

Any thoughts on what I'm doing wrong here?

**Comment by ghego** [comment]
you just need to move the image into a subfolder named with the label you want

**Comment by sachinruk** [comment]
but suppose its a test set where I do not know the label, how can I reshape it then? I assumed that moving it into the `train` subfolder was enough?

**Comment by kgrm** [comment]
If you use `class_mode=None`, the generator only returns the image without labels anyway, so you can put all your images in a single subfolder.

**Comment by sachinruk** [comment]
@kgrm but I did use `class_mode=None`, see above. And the images are in the single subfolder called `train`.

**Comment by kgrm** [comment]
You don't understand. They need to be in a subdir of the `train` directory, because `ImageDataGenerator.flow_from_directory` expects images from different classes in different subdirectories of the path you initialise it with. If you don't know or don't care about class labels, just make a single subdirectory and put all the images there.

**Comment by sachinruk** [comment]
got it working by adding the subdirectory. Thanks! final ipynb is here: https://github.com/sachinruk/keras_simpsons/blob/master/keras_simpsons.ipynb
[please checkout awesome homer pics!]
