### ISSUE TITLE
Model with for loop can't be saved

### ISSUE THREAD

**Issue by griff4692** [fchollet/keras#6378]
I am running training a dynamic memory network which requires a for loop.  When I train the model architecture that repeats layers, I am unable to save it using model.save.  I am using TF as the backend.  Here is the line that errs out.

>  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 2303, in get_config
>     return copy.deepcopy(config)
 
Any ideas?

Thanks

**Comment by griff4692** [comment]
the specific complaint is 

> TypeError: can't pickle _thread.lock objects

**Comment by superMDguy** [comment]
Are you able to share your code?
