### ISSUE TITLE
Tensor size in custom metric

### ISSUE THREAD

**Issue by hkmztrk** [fchollet/keras#6383]
Hello, I'm trying to define my own metric. It calculates concordance index which is a measure for regression problems.

```
def cindex_score(y_true, y_pred):
    sum = 0
    pair = 0    
    ylen=y_true.get_shape().as_list()[0]
    for i in range(1, ylen):
        for j in range(0, i):
            if i is not j:
                if(y_true[i] > y_true[j]):
                  pair +=1
                  sum +=  1* (y_pred[i] > y_pred[j]) + 0.5 * (y_pred[i] == y_pred[j])
    if pair is not 0:
        return sum/pair
    else:
        return 0
```

I get, "TypeError: 'NoneType' object cannot be interpreted as an integer" error. Because ylen returns as None. I also posted this issue on GoogleGroups and [Stackoverflow](http://stackoverflow.com/questions/43576922/keras-custom-metric-iteration) but so far no solution has came up, so I had to write this here as well.

Could you please help me about how to iterate within a Tensor object?

Best,

**Comment by ilivans** [comment]
I can't see you are actually using `ylen`

**Comment by hkmztrk** [comment]
Sorry, I just updated the code.

**Comment by ilivans** [comment]
Well, I've tried different ways to get Tensor shape inside custom metric and every time I got `None`. 
Probably it's just impossible to retrieve Tensor shape there for some reason. 
You may try to compute your metric using only functions from `keras.backend` like `greater` that don't rely on the shapes, but I believe it's not trivial.

**Comment by ilivans** [comment]
Hi, @hkmztrk !
I've probably found some hack. To get the size of a 1-D tensor `X` you can use the next expression: `K.sum(K.ones_like(X))`. Maybe it will help.
