### ISSUE TITLE
Deconv2D under theano backend not working properly

### ISSUE THREAD

**Issue by izikgo** [fchollet/keras#6384]
The following gist (https://gist.github.com/izikgo/c381812b4eca2f05f0fe18bfecf561f8) contains a very simple code which breaks under Theano and works fine under TF.
The error I get:
```ValueError: impossible convolution output dim: expected 1x1x8x8 but received gradient with shape 1x1x7x7
Apply node that caused the error: GpuDnnConvGradI{algo='none', inplace=True}(GpuContiguous.0, GpuContiguous.0, GpuAllocEmpty.0, GpuDnnConvDesc{border_mode='half', subsample=(2, 2), conv_mode='conv', precision='float32'}.0, Constant{1.0}, Constant{0.0})
Toposort index: 29
Inputs types: [CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), CudaNdarrayType(float32, 4D), <theano.gof.type.CDataType object at 0x7fb349630400>, Scalar(float32), Scalar(float32)]
Inputs shapes: [(1, 256, 4, 4), (1, 1, 7, 7), (1, 256, 14, 14), 'No shapes', (), ()]
Inputs strides: [(0, 16, 4, 1), (0, 0, 7, 1), (0, 196, 14, 1), 'No strides', (), ()]
Inputs values: ['not shown', 'not shown', 'not shown', <capsule object NULL at 0x7fb3495ff720>, 1.0, 0.0]
Inputs name: ('kernel', 'grad', 'output', 'descriptor', 'alpha', 'beta')

Outputs clients: [[GpuSubtensor{int64:int64:int8, int64:int64:int8, int64:int64:int8, :int64:}(GpuDnnConvGradI{algo='none', inplace=True}.0, ScalarFromTensor.0, ScalarFromTensor.0, Constant{1}, ScalarFromTensor.0, ScalarFromTensor.0, Constant{1}, ScalarFromTensor.0, ScalarFromTensor.0, Constant{1}, ScalarFromTensor.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.```

**Comment by kgrm** [comment]
You can't use even kernel sizes with "same" padding. I recommend using "valid" padding and cropping the output later on as appropriate to achieve the same output shape. For example, this works:

https://gist.github.com/kgrm/141da3d672bb4ef01464ddcf070ddbd6

**Comment by izikgo** [comment]
I agree, but then the TF code shouldn't work as well. In general, I don't understand how the deconv layer works at all without supplying the output shape directly, since as stated in the Theano convolution arithmetic docs, there are some cases where the output size needs to be specified

**Comment by kgrm** [comment]
TF and Theano backends aren't fully mutually compatible, there are some implementation details Keras attempts to patch over (eg, image shape format), features that only exist in one or the other (like separable convolution), etc. As for the output shape, if you look at [the code](https://github.com/fchollet/keras/blob/master/keras/layers/convolutional.py#L741), you will notice Keras always tries to infer it automatically from the input shape, kernel size, stride shape and padding setting.

**Comment by izikgo** [comment]
fair enough... closing
