### ISSUE TITLE
Invalid value ("cpu") for configuration variable "gpu". Valid options start with one of "device", "opencl", "cuda"

### ISSUE THREAD

**Issue by ibrahim-amer** [fchollet/keras#6388]
When I try to run this command "import keras" I got this error: 

Invalid value ("cpu") for configuration variable "gpu". Valid options start with one of "device", "opencl", "cuda"

Both Keras and Theano are updated to the latest version.

Here is THEANO_FlAGS env variable: 
"floatX=float32,device=gpu,nvcc.fastmath=True,lib.cnmem=0.6,nvcc.flags=-D_FORCE_INLINES"

I also tried "device=cuda" and "device=cuda0" now I'm getting this error: 

C:\Users\Ibrahim Amer\Anaconda\lib\site-packages\theano\configdefaults.py:1711:
UserWarning: Theano does not recognise this flag: lib.cnmem
  warnings.warn('Theano does not recognise this flag: {0}'.format(key))
C:\Users\Ibrahim Amer\Anaconda\lib\site-packages\theano\configdefaults.py:1711:
UserWarning: Theano does not recognise this flag: nvcc.fastmath
  warnings.warn('Theano does not recognise this flag: {0}'.format(key))
C:\Users\Ibrahim Amer\Anaconda\lib\site-packages\theano\configdefaults.py:1711:
UserWarning: Theano does not recognise this flag: nvcc.flags
  warnings.warn('Theano does not recognise this flag: {0}'.format(key))
ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "C:\Users\Ibrahim Amer\Anaconda\lib\site-packages\theano\gpuarray\__init_
_.py", line 175, in <module>
    use(config.device)
  File "C:\Users\Ibrahim Amer\Anaconda\lib\site-packages\theano\gpuarray\__init_
_.py", line 162, in use
    init_dev(device, preallocate=preallocate)
  File "C:\Users\Ibrahim Amer\Anaconda\lib\site-packages\theano\gpuarray\__init_
_.py", line 65, in init_dev
    sched=config.gpuarray.sched)
  File "pygpu\gpuarray.pyx", line 614, in pygpu.gpuarray.init (pygpu/gpuarray.c:
9415)
  File "pygpu\gpuarray.pyx", line 566, in pygpu.gpuarray.pygpu_init (pygpu/gpuar
ray.c:9106)
  File "pygpu\gpuarray.pyx", line 1021, in pygpu.gpuarray.GpuContext.__cinit__ (
pygpu/gpuarray.c:13468)
GpuArrayException: Error loading library: 0

When I try to run this code I get "used the cpu":

`vlen = 10 * 30 * 768  # 10 x #cores x # threads per core
iters = 1000

rng = numpy.random.RandomState(22)
x = shared(numpy.asarray(rng.rand(vlen), config.floatX))
f = function([], tensor.exp(x))
print(f.maker.fgraph.toposort())
t0 = time.time()
for i in range(iters):
    r = f()
t1 = time.time()
print("Looping %d times took %f seconds" % (iters, t1 - t0))
print("Result is %s" % (r,))
if numpy.any([isinstance(x.op, tensor.Elemwise) and
              ('Gpu' not in type(x.op).__name__)
              for x in f.maker.fgraph.toposort()]):
    print('Used the cpu')
else:
    print('Used the gpu')`

Windows 7, NVIDIA 1060 6GB 
CUDA 7.5
Graphics Driver: 378.92

**Comment by gpp8p** [comment]
I just upgraded both keras and theano to the latest version and I get this error too.

**Comment by nikita-astronaut** [comment]
Yes, started having the very same problem just today! Please fix! Run with flags
THEANO_FLAGS='floatX = float32, device = cuda0'
get 
ValueError: Invalid value ("cpu") for configuration variable "gpu0". Valid options start with one of "device", "opencl", "cuda"

Ubuntu 16.04, NVIDIA GeForce GTX 560 Ti, CUDA 8.0

**Comment by the-moliver** [comment]
Best solution is to install the new backend for Theano: http://deeplearning.net/software/libgpuarray/installation.html#step-by-step-install

and then have `device = cuda0` (or whatever appropriate number) in the .theanorc

**Comment by Andrjusha** [comment]
Same problem

**Comment by Hazarapet** [comment]
I've got the same problem.Could you please suggest any other idea?

**Comment by pplonski** [comment]
Me too! I'll try to dig into it! Any help will be appreciated!

**Comment by Andrjusha** [comment]
I installed the new backend and it worked

**Comment by pplonski** [comment]
You mean you reinstall theano? Can you post the link with instructions?

**Comment by Andrjusha** [comment]
No need to reinstall theano, just install the new backend, see the link above by the-moliver

**Comment by ibrahim-amer** [comment]
I have installed the new backend but it didn't work

**Comment by Hazarapet** [comment]
You should change "gpu0" to "cuda0". It worked for me.

**Comment by deltaz0** [comment]
Same issue. On Windows, issue started after upgrading theano 0.8.2 to 0.9.0. Installing new backend didn't work, changing "gpu0" to "cuda" or "cuda0" didn't work. Removing the .theanorc didn't work. Rolling back to theano 0.8.2 fixes the problem, but how do I get 0.9 to work?

**Comment by Hazarapet** [comment]
You will have a lot of problems with windows.I suggest you to use another OS.The "cuda0" helped for many  people.

**Comment by ibrahim-amer** [comment]
Here is what I did: 
1- Install pygpu library using this command: conda install Theano pygpu
2- Download mingw64 package from [here](conda install Theano pygpu), extract it to C:\ drive then add C:\mingw64\bin to PATH env variable
3- THEANO_FLAGS = "floatX=float32,device=cuda0"

**Comment by jtdowdall** [comment]
I'm running an LSTM but I was having this issue until I pip installed theano-lstm. Using device=gpu0 in my .theanorc. I am not using conda so the above options were just complicating things for me.

Hope this helps at least a few.

**Comment by deltaz0** [comment]
I resolved my issue on Windows. I had THEANO_FLAGS set as a system environment variable with the line device=gpu, which was overriding my .theanorc file settings. I'm guessing the stable 0.9.0 version allowed for either gpu or cuda0, but the latest branch does not. Anyway, deleting the environment variable allowed my theanorc settings to go through and it works fine now.
