### ISSUE TITLE
batch_dot with Theano backend is broken

### ISSUE THREAD

**Issue by the-moliver** [fchollet/keras#6400]
K.batch_dot appears to work fine with Tensorflow backend but gives garbage with Theano; `bd[0]` in the script below isn't even symmetric.

```python
from keras import backend as K
import numpy as np
from numpy.testing import assert_allclose

batch = K.variable(np.random.randn(50, 8, 5))

bd = K.eval(K.batch_dot(batch, K.permute_dimensions(batch, [0, 2, 1])))

d = K.eval(K.dot(batch[0], K.permute_dimensions(batch[0], [1, 0])))

assert_allclose(bd[0], d, atol=1e-05)
```

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by fchollet** [comment]
`batch_dot` is unit-tested to have the same output across the TF and Theano backends for various inputs with various shapes. https://github.com/fchollet/keras/blob/master/tests/keras/backend/backend_test.py#L84-L91

**Comment by the-moliver** [comment]
You're right the unit tests would catch this. This was a GPU specific bug, which resolved when upgrading Theano's new GPU backend libgpuarray from 0.6.2 to 0.6.5 . So the bug may be present with the "Stable Installation" of Theano [which requires libgpuarray 0.6.2](http://deeplearning.net/software/theano/install_ubuntu.html#id1) @nouiz

**Comment by nouiz** [comment]
I'll update the doc, Theano 0.9 also work with more recent libgpuarray that have this libgpuarray bug fixed.

**Comment by the-moliver** [comment]
Great! @nouiz @fchollet
