### ISSUE TITLE
Training takes longer time in Keras 2.0.3 than Keras 1.2.1 using (TensorFlow backend)

### ISSUE THREAD

**Issue by sivagnanamn** [fchollet/keras#6406]
I'm training an 7 class object classification Network-In-Network architecture net. While using Keras 1.2.1 with Tensorflow(v 1.0.1) as backend it takes ~260seconds/epoch. 

```
Epoch 1/10
91234/91234 [==============================] - 245s - loss: 1.0063 - acc: 0.6151 - val_loss: 0.4608 - val_acc: 0.8251
```

But while using the Keras 2.0.3 with TensorFlow(v 1.0.1) backend, the same network (with Keras 2.0.3 API changes) takes ~10000second/epoch.
```
Epoch 1/10
  259/91234 [..............................] - ETA: 10721s - loss: 1.9539 - acc: 0.2284
```
I checked the code and its using GPU only.

**Comment by Dref360** [comment]
Do you have a link to the code?
Have you updated your code to keras 2?
Using fit or fit_generator?

**Comment by fchollet** [comment]
It's likely that you are using fit_generator and you forgot to update your
call to the new API (we use number of steps instead of number of samples
now).

**Comment by sivagnanamn** [comment]
@Dref360 I don't have a link to the code, I've updated my code to Keras 2. I'm not getting any API warnings. And I'm using fit_generator (snippet shown below).
@fchollet  Updated the code to Keras 2, below is my fit_generator snippet. Is there anything wrong in this? Please 

```
model.fit_generator(train_generator, steps_per_epoch= len(train_samples)/batch_size,
            validation_data=validation_generator, validation_steps=len(validation_samples),
           epochs=10)
```

**Comment by dvazquezcvc** [comment]
I also see that keras 2 is much more slow

**Comment by sivagnanamn** [comment]
My bad. Thanks @holli  for pointing it out. But still 2.0.3 takes few minutes longer than 1.2.1. Closing the issue since there was a considerable improvement in training time.
