### ISSUE TITLE
Is there a handy way to get the output feature at a specific layer/node

### ISSUE THREAD

**Issue by rex-yue-wu** [fchollet/keras#641]
Hi,

I am seeking an easy solution to get the output feature at a specific layer/node in a pretrained model. In caffe, this is just one line of code calling ```forward``` with the layer name. I expect keras having something similar, does anyone have a good idea?

**Comment by Imorton-zd** [comment]
just like this:
```python
get_feature = theano.function([model_best.layers[0].input],model_best.layers[0].get_output(train=False),allow_input_downcast=False)
feature = get_feature(X)
```
X is the data of all input samples

**Comment by loyeamen** [comment]
https://github.com/fchollet/keras/issues/456

**Comment by Smerity** [comment]
To build on this, https://github.com/fchollet/keras/issues/621 also discusses extracting embeddings from layers and hidden layer representation of a given input (#41).

We should add this to the docs as it's a very frequent question.

**Comment by rex-yue-wu** [comment]
Many thanks. Problem solved.

**Comment by alyato** [comment]
hi @Imorton-zd ,i use the graph model,refer to #41 
like this,

> model = graph()
  model.add_input(name='input0',input_shape=())
  model.add_node(Convolution2D(),name='c1',input='input0')
.......

And i want to see the output of the `c1`,Then 

> 
getFeatureMap = theano.function(model.inputs['input0'].input,model.nodes['c1'].get_output(train=False),
allow_input_downcast=True)

But it show me that
`TypeError: list indices must be integers, not str`

Do you give me some advices? Thanks.
