### ISSUE TITLE
Skipgram.py typo

### ISSUE THREAD

**Issue by olddaos** [fchollet/keras#643]
Hi fchollet!
Thanks for great software, which was successfully applied by me to train convnets! It really saved me much time and pain, which I definitely had if I had to learn Theano :-)

But when I tried to run keras to learn word embeddings, I had figured out, that you probably mean to say 'model.fit(X, labels)'  instead of 'model.train(X, labels)' ( in skipgram_word_embeddings.py, line 132 ). Because when I run this file as is, I'm getting this output:

Fit tokenizer...
0
Save tokenizer...
Build model...
----------------------------------------
Epoch 0
----------------------------------------
0
Traceback (most recent call last):
  File "./skipgram_word_embeddings.py", line 143, in <module>
    loss = model.train(X, labels)
AttributeError: 'Sequential' object has no attribute 'train'

**Comment by tingtinglu** [comment]
I also come across the same problem. Can anyone know why this will happen?

**Comment by fchollet** [comment]
That example is long outdated and has been removed from Keras a while back.
The method you should be using is "train_on_batch", not "train".

**Comment by tingtinglu** [comment]
Thank you so much! And I have another question, 
I define the model as follows:


def create_model():

	model = Sequential()
	model.add(Convolution2D(4, 1, 5, 5, border_mode='valid'))
	model.add(Activation('relu'))

	model.add(Convolution2D(8,4, 3, 3, border_mode='valid'))
	model.add(Activation('relu'))
	model.add(MaxPooling2D(poolsize=(2, 2)))

	model.add(Convolution2D(16, 8, 3, 3, border_mode='valid')) 
	model.add(Activation('relu'))
	model.add(MaxPooling2D(poolsize=(2, 2)))

	model.add(Flatten())
	model.add(Dense(16*4*4, 128, init='normal'))
	model.add(Activation('relu'))
	model.add(Dropout(0.2))

	model.add(Dense(128, nb_class, init='normal'))
	model.add(Activation('softmax'))
	return model
But I obtain the exception: : Layer is not connected. Did you forget to set "input_shape"?

Could you help me to solve this problem? Thanks so much!
