### ISSUE TITLE
Support for 3D Deconvolution for the new API (2.0)

### ISSUE THREAD

**Issue by meetshah1995** [fchollet/keras#6437]
Is someone working on making 3D Deconv available for the new API? If not I'd like to submit a PR.

Several issues addressed this in the previous API - [4457](https://github.com/fchollet/keras/pull/4457), [3122](https://github.com/fchollet/keras/issues/3122)

Several papers like Volumetric-Nets, 3D-Unet and 3DGAN could use this feature.

**Comment by Danielhiversen** [comment]
You can use this https://github.com/farizrahman4u/keras-contrib/blob/master/keras_contrib/layers/convolutional.py#L19

**Comment by meetshah1995** [comment]
@Danielhiversen - Any specific reason why it isn't included in the main repo?
