### ISSUE TITLE
Layer Reshape along the sample axis

### ISSUE THREAD

**Issue by xn8812** [fchollet/keras#6448]
Hi, I wonder is that possible to reshape a keras tensor along a sample axis? For example, something looks like

```
from keras.layers import Input
from keras.layers.core import Reshape

input_shape = (5,32,32,1) # the batch size is 5
tensor = Input(batch_shape=input_shape)
new_tensor = Reshape((1,)+tensor._keras_shape)(tensor)	# the new tensor should be (1,5,32,32,1)
```

I have a bug when trying the above code: ValueError: total size of new array must be unchanged

It seems that keras does not allow to change the size of sample axis, it this true? Is there any solution to this problem?

Thanks!

**Comment by xn8812** [comment]
I think "TimeDistributed" is the solution.

**Comment by fchollet** [comment]
You can use a `Lambda` layer that wraps `keras.backend.reshape`.
