### ISSUE TITLE
texts classification accuracy between cnn and maxent

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#645]
Taking imdb_cnn as an example, classification accuracy using maxent outperforms that using cnn. Why do we use CNN for texts classification. What the advantages CNN have? In fact, I have used many suitable parameters and add another convolution layer according to my comprehension. I don't know if I didn't  adjust the suitable parameters.
Expect someone who has used two methods to tell me how to handle this problem. After all, deep learning is the tendency in CS.

**Comment by fchollet** [comment]
> Why do we use CNN for texts classification. What the advantages CNN have?

This is not a Keras issue (rather ask it on the mailing list than on Github). But the short answer is that both methods are interesting for different reasons. The conceptual simplicity of CNNs and their ability to form relevant representations from raw features makes them very attractive in text understanding, including word-level and character-level (e.g. [1]), but you will want to use much larger text corpuses to really see it in action.

[1] http://arxiv.org/abs/1502.01710
