### ISSUE TITLE
Could someone please explain to me how momentum works in SGD's code?

### ISSUE THREAD

**Issue by IvanGoenawan** [fchollet/keras#6450]
Here's the code in question:

```
shapes = [K.get_variable_shape(p) for p in params]
moments = [K.zeros(shape) for shape in shapes]
self.weights = [self.iterations] + moments
for p, g, m in zip(params, grads, moments):
    v = self.momentum * m - lr * g  # velocity
    self.updates.append(K.update(m, v))
```

For the life of me I can't understand how that v is not always equal to -lr*g, since m is always just zero. The code for K.update(m,v) also only returns (m,v) without doing anything (in Theano backend). This guy seems to have figured it out https://github.com/fchollet/keras/issues/758 , but I can't. I know that we're dealing with tensors and stuffs, but that m is just zeros and is not a function of anything right? Could someone please enlighten me on this matter?

**Comment by fchollet** [comment]
The answer is that the code you are reading isn't imperative, it's building a symbolic graph which is then executed repeatedly during training. I recommend you look up a tutorial on TensorFlow or Theano.

**Comment by IvanGoenawan** [comment]
For fellow confused amateurs like me, here's what I think is the explanation. It only became clear to me after I looked up the _make_train_function() method in training.py which calls get_update(). The relevant snippet is here:

```
training_updates = self.optimizer.get_updates(
                                self._collected_trainable_weights,
                                self.constraints,
                                self.total_loss)
updates = self.updates + training_updates
# Gets loss and metrics. Updates weights at each call.
self.train_function = K.function(inputs,
                                 [self.total_loss] + self.metrics_tensors,
                                 updates=updates,
                                 **self._function_kwargs)
```

In short (at least in Theano's case), the K.update(m,v) method which got me confused indeed does nothing. But these update pairs are then passed on as the 'update' parameter to Theano's 'function' method. The update is performed each time the resulting function is called after calculating the function's output. This is how the value of m gets updated.
