### ISSUE TITLE
Increasing model compile time and memory usage in successive compile calls

### ISSUE THREAD

**Issue by Sushobhan04** [fchollet/keras#6457]
I have to successively compile a model in loop (making trainable = true and false alternatively as in GAN). This results in increasing compilation time and memory usage as pointed out in issue #2828. I cannot use K.clear_session() as it will reset the weights learned. Please provide a method to get around this memory leak problem. 

I am currently using this implementation to make layers trainable=true or False

def make_trainable(net, val):
    net.trainable = val
    for l in net.layers:
       l.trainable = val

where val = True/False

Any help will be appreciated

**Comment by fchollet** [comment]
> cannot use K.clear_session() as it will reset the weights learned

Save the weight to disk, use `clear_session`, and load the weights back into your model.

The proper way to handle this is either to use `clear_session` in order to start from a blank graph, or to use TensorFlow graph scopes.

**Comment by chrisclarkson** [comment]
@fchollet is there a way to use `clear_session()` without receiving the error: `TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor(....) is not an element of this graph.` in the next iteration of the GAN for loop?

See below my example pipeline:

```
for epoch in range(epochs):
    idx = np.random.randint(0, train_X.shape[0], batch_size)
    imgs = train_X[idx]
    # Sample noise and generate a batch of new images
    noise = np.random.normal(0, 1, (batch_size, int(train_X.shape[1]/4)))
    noise=noise.reshape(noise.shape[0], noise.shape[1],1)
    if epoch!=0:
        generator=load_model('generator')
        discriminator=load_model('discriminator')
    gen_imgs = generator.predict(noise)
    combined=add_layers(generator,discriminator,len(discriminator.layers))
    combined.compile(loss='binary_crossentropy', optimizer=optimizer)
    # Train the discriminator (real classified as ones and generated as zeros)
    d_loss_real = discriminator.train_on_batch(imgs, valid)
    d_loss_fake = discriminator.train_on_batch(gen_imgs, fake)
    d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)
    # Train the generator (wants discriminator to mistake images as real)
    g_loss = combined.train_on_batch(noise, valid)
    generator=add_layers(Sequential(),combined,first_half_length)
    save_model(generator,'generator')
    gen_loss.append(g_loss)
    dis_loss.append(d_loss[0])
    # Plot the progress
    print ("%d [D loss: %f, acc.: %.2f%%] [G loss: %f]" % (epoch, d_loss[0], 100*d_loss[1], g_loss))
    # If at save interval => save generated image samples
    if epoch % save_interval == 0:
        save_imgs(epoch,gen_loss,dis_loss)
    K.clear_session()
```

Thanks in advance
