### ISSUE TITLE
CSVLogger doesn't handle properly a logs' value with str type

### ISSUE THREAD

**Issue by danieljl** [fchollet/keras#6459]
Suppose we have `logs['foo'] = 'bar'`.
`CSVLogger` will output `"[b, a, r]"` instead of `bar` in `foo` column.

I'm currently working with the fix.

**Comment by bstriner** [comment]
Does `logs['foo']=['bar']` work?

**Comment by danieljl** [comment]
No, it will be written to a CSV file as `[bar]` instead of the expected `bar`.
