### ISSUE TITLE
Can't pickle History object

### ISSUE THREAD

**Issue by amitbeka** [fchollet/keras#646]
I've tried to pickle `keras.callbacks.History` object after training, but it failed with infinite recursive loop of objects. A quick look showed that the loop is in the Container object of the Sequential model, references inside the History object.

My question is: do you want the object to be pickle-able? if so, I can reproduce and provide logs. Otherwise this issue can be closed as far as I'm concerned (I just dump History.history dict to JSON which is all I need).

**Comment by tkipf** [comment]
Same problem here. This is a quick workaround:
```python
logs = model.fit(...)

import sys
sys.setrecursionlimit(50000)
pickle.dump(logs, open('logs.pkl', 'wb'))
```

**Comment by fchollet** [comment]
You will pretty much never need to `History` object, what you are most likely looking for is the `History.history` attribute, which is a simple data dictionary.

If you do need the `History` object again, you can simply instantiate a new one then set its `history` attribute.

To pickle the `History` object itself, which should never be needed, you can simply remove its `model` attribute:

```
del hist.model
```
