### ISSUE TITLE
Error in Keras Imdb load_data 

### ISSUE THREAD

**Issue by smokh004** [fchollet/keras#6466]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by smokh004** [comment]
TypeError: load_data() got an unexpected keyword argument 'num_words'

**Comment by smokh004** [comment]
Traceback (most recent call last):
  File "BiLSTM.py", line 24, in <module>
    (x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)
  File "/usr/local/lib/python3.5/site-packages/keras/datasets/imdb.py", line 53, in load_data
    x_train = f['x_train']
TypeError: tuple indices must be integers or slices, not str

**Comment by wandonye** [comment]
Try this:

`pip install keras --upgrade`

**Comment by kimcho30** [comment]
imdb.load_data(num_words=max_features)
Excues me, is there anyone can tell what the "num_words" means in this?

**Comment by stevcabello** [comment]
> imdb.load_data(num_words=max_features)
> Excues me, is there anyone can tell what the "num_words" means in this?

Take a look at this link:
https://keras.io/datasets/

**Comment by BhargavB05** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/40090417/56706057-24cd3f00-6731-11e9-9857-b257002eb293.png)

can anyone help me out with the error.

**Comment by tc-one** [comment]
i have the exactly the same issue

**Comment by rakshithjk** [comment]
Its probably an issue with Google colab's format.py.the parameter 'allow_pickes' needs to set true.
Try using it on a different platform or your local machine, it should work perfectly.

**Comment by rakshithjk** [comment]
> Its probably an issue with Google colab's format.py. The parameter 'allow_pickes' needs to set true.
> Try using it on a different platform or your local machine, it should work perfectly.

**Comment by rakshithjk** [comment]
> ![Screenshot (42)](https://user-images.githubusercontent.com/40090417/56706057-24cd3f00-6731-11e9-9857-b257002eb293.png)
> 
> can anyone help me out with the error.

Its probably an issue with Google colab's format.py. The parameter 'allow_pickes' needs to set true.
Try using it on a different platform or your local machine, it should work perfectly.
