### ISSUE TITLE
tf.split in Lambda layer not working as expected

### ISSUE THREAD

**Issue by pedawia** [fchollet/keras#6468]
Hello,

I'm having some difficulties using `tf.split` in a `Lambda` layer. I'm using Keras v2.0.3 and TensorFlow v1.1.0. Here's a reproducible example that mirrors the error I'm running into:
```
dim = 24
x = Input(shape=(dim,))
x_top, x_mid, x_bot = Lambda(lambda x: tf.split(x, [8, 8, 8], 1))(x)
h_top = Dense(1)(x_top)
h_mid = Dense(1)(x_mid)
h_bot = Dense(1)(x_bot)
```
The last two lines above return a `list index out of range` error, but the line immediately preceding them (`h_top = Dense(1)(x_top)`) does not. I'm curious whether anyone else has run into this particular problem and could offer tips on how I could go about resolving this. Thank you!

---------------------

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by dkorkino** [comment]
Hi all, I've also encountered the same issue. The problem seems to be with the keras Lambda layer with more than one outputs, rather than the split.

**Comment by was84san** [comment]
I have the same issue, any solution yet?
