### ISSUE TITLE
Keras 2.0 is too slow, even with theano 0.9

### ISSUE THREAD

**Issue by Hazarapet** [fchollet/keras#6470]
Guys I've upgraded my keras and theano to keras 2.0 and theano 9.0. I've tested GPU and it works fine, the test script is ok. I've also installed cuDNN 5110 and it works fine too.,but the script runs too slowly. I've even used some configuration in theano to make the performance better:Forced to use dnn, to use float32 (warn if float is 64), made some optimizations, but the learning process goes too long anyway. I had a CNN with about 16 layers (2 FC layers).**With keras 1, the 1 epoch took ~1m, but with keras2.0 it takes ~3.24m**.Is there any idea how I can make the speed better? almost all tests related with theano and gpu run without any problem.

**Comment by the-moliver** [comment]
Check that `image_data_format` is `channels_first`

**Comment by dvazquezcvc** [comment]
I have also noticed that my code with Keras 2 is much more slow

**Comment by Hazarapet** [comment]
everything is ok with "image_data_format", cause I had an issue, the change the channels and it works.If I'm not mistaken image_data_format by default is channel_last

**Comment by the-moliver** [comment]
`channels_last` will work but usually run more slowly under theano.

**Comment by Hazarapet** [comment]
so you suggest to use "channel_first"? I used this to, but it's the same.

**Comment by the-moliver** [comment]
Yes, use `channels_first` with Theano, `channels_last` with Tensorflow for best performance.

**Comment by the-moliver** [comment]
And of course make sure the input dimensions match the `image_data_format`, i.e. (3,32,32) for `channels_first`. Things will often run even if it doesn't, but won't do what you want.

**Comment by Hazarapet** [comment]
ok. Will play a little bit with channels and let you know what happened.

**Comment by Hazarapet** [comment]
thank you @the-moliver .The channel_first solved the problem.now it takes ~1m again.Of course it would be great, if it took ~0.8m for new version, but anyway. this is not bad.

**Comment by meliscicek** [comment]
@Hazarapet Could you please share how you solved this problem?
