### ISSUE TITLE
model.predict taking a long time

### ISSUE THREAD

**Issue by PankajBalani** [fchollet/keras#6474]
I have a very strange issue here:
I have a flask app - where I have the following code in a route
with graph.as_default():
                    prediction = cnn_model.predict(convertInputToVector(input_data, 321))
                    data = prediction[0].tolist()
                    max_index = data.index(max(data))
                    return Response(stream_template('answer_layout.html', data = prediction, max_index = max_index, question = input_data))

this does not seem to work on my AWS instance.
the model is loaded into graph outside of the route in the flask app.
the server gets timed out (set at 100sec) when I attempt this function from web.
however the same code works if I make a separate file and execute it from command line on the same server.
the same code also works if I make an API out of this def
This exact flask app works perfectly fine on my local machine.

The step where I get the issue is **model.predict**

**Comment by khalilia2000** [comment]
I have the exact same issue but with ROS. Did you happen to solve this issue somehow?

**Comment by bact** [comment]
Similar behavior for me as well. Running Keras 2.1.3, tensorflow-1.5.0, and Flask 0.12.2
(Calling it deepcut-0.6 from http://github.com/rkcosmos/deepcut/ )

The same code run fine on command line. But on Flask it just went like too long and timeout.

**Comment by bact** [comment]
May related to this issue of Keras + TensorFlow + Flask
https://github.com/keras-team/keras/issues/2397

**Comment by dyngts** [comment]
hi @bact,

if i have multiple model to load, should i save graph for each model loaded or only once after all models already load?
