### ISSUE TITLE
How do I implement Autoencoder in keras on numerical (CSV) dataset?

### ISSUE THREAD

**Issue by Ahmid** [fchollet/keras#6478]
I am trying to develop an Intrusion Detection System based on deep learning using Keras.

We simulated a NORMAL network traffic and I prepared it in CSV file (numerical dataset of network packets fields (IP source, port,etc..)). But I do not have the ABNORMAL (malicious) packets to train the neural network on.

I searched for problems like that and I found that Autoencoder is a good approach in unsupervised learning, but the thing is that I am new to deep learning, and I only found this example [Image Recognition with Autoencoder](https://blog.keras.io/building-autoencoders-in-keras.html) where they are using Autoencoder on images dataset.

I want to use Autoencoder (or any thing useful in my case) with numerical CSV dataset in order to predict if the incoming packet is normal or malicious.

Any recommendation?

**Comment by gkrisp98** [comment]
Hi @Ahmid did you figure this out ?
