### ISSUE TITLE
Performing tensor flow operations on keras tensors

### ISSUE THREAD

**Issue by Miail** [fchollet/keras#6482]
I am currently working on a lambda layer that takes in data formats it, and pass it through a convolutional layer. 

Problem is the formatting, since keras is more suited for model definition, not much can be done regarding the tensor manipulation... 

Is it possible to somehow convert a keras tensor to a tensor flow tensor,  do the data manipulation, and then convert it back to a keras tensor?

In my case are the operation i would like to perform is tf.unstack and tf.stack. 

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by bstriner** [comment]
Keras tensors are tensorflow tensors with a few extra attributes. Just use a `Lambda` layer with your `tf` calls and make sure to give it an `output_shape`.
