### ISSUE TITLE
Code for training on ImageNet (ILSVRC2012) ? 

### ISSUE THREAD

**Issue by wichtounet** [fchollet/keras#6486]
Hi, 

I'm currently benchmarking several libraries on ImageNet and I was wondering if there was any example on how to train a model (any CNN model) on ImageNet from scratch ? I'm mostly interested in the data loading since the rest of the code should be fairly easy to adapt. 

Thanks

**Comment by Danielhiversen** [comment]
Have you seen this: https://github.com/fchollet/deep-learning-models ?

**Comment by wichtounet** [comment]
Hi, 

Thanks for your answer. 

Yes, I have seen this repository. It contains the code for the model as well as information on how to get the weights, but no information on how to train them from scratch and neither how load data from ImageNet, unless I'm mistaken. I actually need to retrain them myself. 

Thanks

**Comment by wichtounet** [comment]
Finally, I have written my own loader, it's not fast, but it'll be sufficient. 

Thanks

**Comment by thaolmk54** [comment]
Dear Baptiste,
Can you please share your example on training ImageNet on your own network architecture? I am doing the same thing, however, the learning press is not going well as loss is not improved during training. I tried several network model but got no luck. 

Regards,

**Comment by wichtounet** [comment]
@thaolmk54 Sure thing :)

The code is available on Github: https://github.com/wichtounet/frameworks/blob/master/keras/experiment6.py

It's really nothing fancy but it works.

**Comment by thaolmk54** [comment]
@wichtounet Thank you for your reply.
It seems that I have to wait for a few first epochs to see what is going on. In the first epoch, the situation is quite similar to my own scripts as the loss value is not likely to improve during training. 
Do you have any comment? I am wondering if there are some tricks of training ImageNet in particular.

Thank you

**Comment by wichtounet** [comment]
The loss should go down during the first epoch, but slightly indeed. If you don't see it moving at all, there is maybe a problem.

I forgot to mention something important! My code was made for the dataset resized to 256x256.

**Comment by teramototoya** [comment]
Hi @wichtounet I trained VGG16 with reference to your program.  But the learning process is not going well as loss is not improved during training. My code is here:  https://github.com/teramototoya/train_imagent/blob/master/vgg16_imagenet.py
I did not pre-process the images in any other way, except for subtracting the mean activity over the training set from each pixel. Is there any solution? Thank you!

**Comment by wichtounet** [comment]
Hi @teramototoya I looked at your code but didn't find anything wrong. Did you try without the mean subtraction ? Did you try a different learning rate ? Did you resize all the images to 256x256 ?

**Comment by thaolmk54** [comment]
The learning process in the first epochs is very slow. The provided code actually works well.

**Comment by tdt51403100** [comment]
I tried running your code and changed this section to fit the python3 but with this error:
loss = loss // int(nice_n // batch_size)
acc = acc // int(nice_n // batch_size)

Error: ZeroDivisionError: float divmod()
Can you help fix it?

**Comment by wichtounet** [comment]
@tdt51403100 Is that the only thing you changed ? 

I don't really see the point in your change. The first division should not be a floor division, you really don't want to floor the loss and accuracy and I don't really see the point to use floor division for the number of batches either. 

More importantly, are you sure nice_n is greater than 0 ? If the code does not find any image, this will be 0.

**Comment by tdt51403100** [comment]
nice_n = 0 @@~
I don't know how fix it ?

**Comment by wichtounet** [comment]
If nice_n = 0, it means I didn't find any image. Look at [L26](https://github.com/wichtounet/frameworks/blob/3e7fcd1afa67e36731f0fdb302e4fa41796a4025/keras/experiment6.py#L26) and check if the path is correct.

**Comment by tdt51403100** [comment]
Can you show me how to create the file tree?

**Comment by nbansal90** [comment]
Hi @wichtounet, I was exactly looking for something similar. I was actaully getting stuck in more simple thing. I am not sure, how exactly should I download dataset of classification task for Imagenet dataset.
I have my account there at Imagenet. But I am not sure what should I download, as they have provided URLs for different Images. Could you please let me know the download process, so that I could directly leverage your code.

Regards,
Nitin

**Comment by wichtounet** [comment]
@nbansal90 You have to download the original images from image-net.org

On the page Download Original Images, you will have links to either the
full dataset or the subsets used by the ILSRVC competitions.
I personally use the ILSRVC 2012 dataset

From this page for instance, you can download the training, validation
and test images. It's pretty big (>150GB) and the connection to the
website is pretty slow. If you want to use my code as is, you'll also 
need to resize all images to 256x256. Once you have these files, 
it should be easy to use the experiment6.py file.
