### ISSUE TITLE
No test coverage for Keras

### ISSUE THREAD

**Issue by rodrigob** [fchollet/keras#649]
Just noticed that there is no tests for Convolution1D, this is a side effect of not having code coverage metrics.

**Comment by phreeza** [comment]
I just filed a PR with test coverage. I agree we should start tracking coverage! Travis and Coveralls, for example.

**Comment by rodrigob** [comment]
Which PR ?

**Comment by phreeza** [comment]
See edit above, #647

**Comment by rodrigob** [comment]
I see that helps for the Conv1D aspect; but does not fixes the underlying issue: no test coverage metrics.  It is difficult to improve what is not measured.

**Comment by phreeza** [comment]
Indeed. I run coverage locally and use that to select targets for tests I write. we are currently at ca 70% coverage.

You can generate a nice coverage report by running 
> py.test --cov-report html --cov keras tests
in the project root.

But obviously the best thing would be to have automated coverage reporting. Would be nice to hear from @fchollet what his thinking is on this matter.

**Comment by phreeza** [comment]
I have CI and coverage monitoring running on my fork now:

https://travis-ci.org/phreeza/keras
https://coveralls.io/github/phreeza/keras

Will send a PR for this if there is interest.

**Comment by fchollet** [comment]
Thanks @phreeza! So we are now at 70% test coverage (the remainder tends to be rarely used utils, but we'll cover them too in time), and we have coverage monitoring as part of the Travis integration.
