### ISSUE TITLE
data_format enabling for NCHW for conv2D with Tensorflow backend

### ISSUE THREAD

**Issue by rieram** [fchollet/keras#6509]
I noticed that the data_format is still hard coded in the Tensorflow backend to convolution2d (conv2d). I read an issue that stated it was to unstable about a year ago and that is why it wasn't being supported as of that time, but now I think it has been tested enough since then and it may qualify looking into officially supporting it. 

I made the modification to my local version of Keras and notice a good throughput improvement on CPUs.

Can enabling this functionality be revisited?

**Comment by fchollet** [comment]
> I made the modification to my local version of Keras and notice a good throughput improvement on CPUs.

Last time I checked it was only implemented on GPU, not on CPU (in TF). But we can definitely modify the TF backend to support it at least on GPU. Please open a PR.
