### ISSUE TITLE
Can't run eras without gpu

### ISSUE THREAD

**Issue by apcode** [fchollet/keras#651]
I sometimes work on my laptop when developing algorithms and ideas. It doesn't have a gnu however, so I run then on the cpu. 
However, I see that layers/convolutional.py does: from theano.sandbox.cuda import dnn
which fails on my laptop.

Shouldn't we be able to run eras when no gnu is available?

**Comment by fchollet** [comment]
Right. I rolled out a simple fix: https://github.com/fchollet/keras/commit/f3eeb982d0e4858a333246430833b1087d446f5a
