### ISSUE TITLE
loading memory memory leak 

### ISSUE THREAD

**Issue by nes123** [fchollet/keras#6511]
i am using keras 1.2 and running the following simple code on the cpu with tensorflow backend (0.12).
K.clear_session() does not clear the memory completely and there is a serious memory leak.
any ideas how to  solve it ?

import keras.models
import keras.backend as K

for i in range(300):
     try:
      model = keras.models.load_model('my_model.hdf5')
      K.clear_session()
     except Exception as e:
      print(e)
      break

**Comment by Danielhiversen** [comment]
Tried Keras 2?

**Comment by nes123** [comment]
no, since my models were trained on keras 1.2.
If it is a known issue I will upgrade and retrain everything. is it ?

**Comment by Dref360** [comment]
Clearing the session does not clear the graph. you could try tf.reset_default_graph

**Comment by nes123** [comment]
the upgrade to keras 2 fixed this memory leak
