### ISSUE TITLE
LeakyReLU error when using model.save()

### ISSUE THREAD

**Issue by inspiralpatterns** [fchollet/keras#6532]
I have a network built using the `Model` API and I'm using `LeakyReLU` activation functions for my layers. When it comes to the moment of saving the structure, I get this:

`AttributeError: 'LeakyReLU' object has no attribute '__name__'`

Example of a layer of mine:
`x = Conv2D(256, (3, 3), activation=LeakyRelu(alpha=1e-1),  padding='same', activity_regularizer=SparseReg(beta=5e-1,p=1e-2), name='lay3')(x)`

Is creating a custom non-linearity the only way to using the `LeakyReLU` with a `Model` API? I read from #3816 and #2272 that you can't use an activation layer as activation function inside another layer, say a `Conv2d` but those refer to a model built using `Sequential` API.

**Comment by Bisgates** [comment]
LeakyReLU should in a new line, like this
```
from keras.layers.advanced_activations import LeakyReLU
x = LeakyReLU(alpha=1e-1)(x)
```

**Comment by sven-mayer** [comment]
The problem is still present in Keras 2.2.4 using TF 1.12.0

**Comment by linchundan88** [comment]
The problem is still present in Keras 2.2.4 using TF 1.12.0

**Comment by Sum02dean** [comment]
Solved this is by creating an instantiation of LeakyReLU then adding a name attribute to that instance e.g:
`from keras.layers.advanced_activations import LeakyReLU
    LR = LeakyReLU()
    LR.__name__ = 'relu'
#hidden 1
    encoder = Dense(h1, activation =LR, kernel_regularizer=regularizers.l2(l2),
                    kernel_initializer=keras.initializers.glorot_normal(seed=None), use_bias = False)(input_data)`

This worked for me.

**Comment by wangyexiang** [comment]
> 
> 
> Solved this error by creating an instantiation of LeakyReLU then adding a name attribute to that instance e.g:
> 
> from keras.layers.advanced_activations import LeakyReLU
>   LR = LeakyReLU()
>   LR.__name__ = 'relu'
>   encoder = Dense(h1, activation =LR, kernel_regularizer=regularizers.l2(l2),
>                   kernel_initializer=keras.initializers.glorot_normal(seed=None), use_bias = False)(input_data)

> This worked for me, i am now able to save and load my functional API based model.

Does it override the 'relu' function? @Sum02dean

**Comment by Sum02dean** [comment]
@wangyexiang  I assumed it was overwriting. However I have come to br skeptical about this approach. I think that the safest bet is to just call the leaky-relu as a separate layer as recommended in the Keras documentation to be on the safe side. That said, using my approach above I was able to run my model fine and get the a desirable output/reconstruction on my auto-encoder.

**Comment by wangyexiang** [comment]
>  however when loaded the model weights were scrambled and the model produced undesirable outputs.

I agree with you. I find a same issue when  I load the saved model(use save() method to save) just now. If I use `LR.name = 'linear'`, I could get a rather good result with training process, however, when I load the model(use load_model() method to load) and call the predict() method, I get a poor result.

**Comment by sambd86** [comment]
model.add(LeakyReLU(alpha=0.3))
add leaky-relu as seperate layer. do not use as  a parameter in another layer

**Comment by AnasHXH** [comment]
leakyrelu_alpha = 0.2    

gen5 = Conv2D(filters=256, kernel_size=3, strides=1, padding='same')(gen5)
gen5 = LeakyReLU(alpha=leakyrelu_alpha)(gen5)#Activation('relu')'or #LeakyReLU(alpha=0.3)

use this, it will solve your problem

**Comment by leonJCY** [comment]
> Try put LeakyReLU in a new line, like this
> 
> ```
> from keras.layers.advanced_activations import LeakyReLU
> 
> x = Conv2D(256, (3, 3))(x)
> x = LeakyReLU(alpha=1e-1)(x)
> ```


Does this have the same effect as the original activation?
