### ISSUE TITLE
Add support for bayesian neural netwoks with gelato (need symbolic initializer)

### ISSUE THREAD

**Issue by ferrine** [fchollet/keras#6546]
Hi, I'm developing [Gelato](https://github.com/ferrine/gelato) and in [this issue](https://github.com/ferrine/gelato/issues/4) I found that Keras does not support such initialization as Lasagne does. Is it possible to add support for symbolic initialization in keras?

**Comment by tomc4yt** [comment]
I was having the same problem until I downgraded to keras 1.2. It would be nice if this worked in 2.0

**Comment by twiecki** [comment]
@fchollet How difficult do you think it would be to make that change? Which places would need to change?

**Comment by dorian821** [comment]
@fchollet There are several issues/requests for this on github and stackoverflow, but there's been no response from the Keras team. Is support likely to be added for symbolic initialization in coming versions of Keras?
