### ISSUE TITLE
fit_generator steps per epoch

### ISSUE THREAD

**Issue by kiyoon** [fchollet/keras#6549]
Hi, thanks for the nice wrapper.

First of all, why do we have to manually set `steps_per_epoch` and `validation_steps` everytime we call fit_generator?

Once the generator is specified, can't you just use `generator.samples // batch_size` ?
Or you can just make `None` option that specifies it automatically.

Also, what is the correct way to specify it?
```generator.samples // batch_size```
makes it omit the remainings that is less than batch_size

```int(ceil(float(generator.samples) / batch_size))```
Possibly this one is correct?

+ I strongly think the latter with ceiling is the right way to do it, because I could see the remaining batch size (current_batch_size smaller than normal batch size) is shifted every epochs with the former one.

So I guess `legacy/interfaces.py` should be changed to that code.
Thanks in advanced.

**Comment by Dref360** [comment]
* What do you mean by `generator.samples`? If I do a custom generator, I would not have this information since I could take my data from a stream, db, file, etc.

* For your second question, it depends on how you handle the end of your epochs. How does your generator behave when there is less than `batch_size` sample left? Most of the time, shifting your data won't have any effect on your training.

**Comment by ylmeng** [comment]
I have a relevant question here.
When I use a generator to provide validation data in fit_generator(), and set validation_steps=1000, will the generator generate 1000 new data points in each new epoch, or use the same 1000 points again and again?
I think it is the former but want to confirm.

**Comment by Dref360** [comment]
Depend of your generator. If your generator is not doing data augmentation, it will cycle through your dataset and the images will be the same. Otherwise, they will be different.

**Comment by ylmeng** [comment]
OK thanks. My data set is larger than 1000. Just want to make sure the generator will not stop at validation_steps.

**Comment by vianamp** [comment]
Hi guys. I need some help on how to use the data generator. Right now my code look like:

```python
def DataDeliver(Tiles):
	while 1:
		Ids = np.random.choice(np.arange(Tiles.shape[0]), size=8, replace=False)
		Batch = Tiles[Ids,:,:,:]
		Batch = DataAugmentation(Batch)
		yield (Batch, Batch)

Autoencoder.fit_generator(DataDeliver(TilesTrain), steps_per_epoch=np.int(TilesTrain.shape[0]/8), epochs=nepochs, verbose=1, max_q_size=2, callbacks=CallBacks, validation_data=(TilesTest, TilesTest))
```

TilesTrain is of shape (83,128,128,3). Each time DataDeliver is called, it selects 8 samples at random and apply data augmentation, so 8 samples become 512. Next I deliver this batch of 512 samples for training. However, I think my code is not actually doing what I think it does. I have peaks of memory usage that reach 24Gb, which does not make sense given the type amount of data I have. Any idea?
