### ISSUE TITLE
Keras: get weights from  multiple nodes

### ISSUE THREAD

**Issue by LN5user** [fchollet/keras#6550]
Hello,

I create a  model in Functional API in Keras (Using Theano backend) and would like to get weights from intermediate layer. The main problem is, that this Layer is a multiple Embedding Layer. I am looking for something like this: model.layers[4].get_output_at(1).get_weights(). How can I do this?

**Comment by kgrm** [comment]
The Embedding layer has a single embeddings layer no matter its number of inputs.

**Comment by LN5user** [comment]
Thank you so much!

**Comment by Miail** [comment]
I guess something similar to this [link](https://github.com/fchollet/keras/issues/91)

It seems like the version written in there does not support the new keras version, I  guess its just matter of changing the API function calls to the right one.

**Comment by LN5user** [comment]
many thanks! that is what I need
