### ISSUE TITLE
Add support for symbolic weight initialization with Pymc3

### ISSUE THREAD

**Issue by gbengaoti** [fchollet/keras#6551]
Hi, I am trying to combine keras (theano backend) with Pymc3,  I found that Keras does not support such weight initialization as Lasagne does. Is it possible to add support for symbolic initialization in keras?

#6546 - It is the same issue as mine. I also get the missing input error.

Here is a link to a github gist of the code:
https://gist.github.com/gbengaoti/ec88e36d3dd7f66d9bc32fcf8ec93d18

**Comment by tomc4yt** [comment]
+1
