### ISSUE TITLE
Many-to-many LSTM (sequence-to-sequence with a delay) on Keras

### ISSUE THREAD

**Issue by RubenZazo** [fchollet/keras#6555]
![image](https://cloud.githubusercontent.com/assets/19270730/25846669/f28a86e0-34b2-11e7-97d9-9f73b0515391.png)

I have seen different implementations of the fourth architecture. In that topology the first LSTM layer sees the whole sequence, gets an output and using that output (repeated with RepeatVector)  you feed a second LSTM of any size and you get the actual output.

The problem I am trying to tackle is signal cleaning, so I have the following:
X_train = n sequences of the signal + noise, frame by frame.
Y_train = same as X_train but with no noise.

The "easy" solution for this problem is to use the last architecture in the figure, but if we do this we are forcing the LSTM to get the cleaned signal of the first frame seeing only that first frame. The LSTM benefits from the context so what I want is a mix between the fourth and the fifht architecture so:

The LSTM sees n frames (let's say 20), once the LSTM gets the frame 21 it outputs the cleaned version of the frame 1 and the network keeps getting one output for every frame it receives.

This is the architecture I am trying to train:

![image](https://cloud.githubusercontent.com/assets/19270730/25847198/5df0cb5e-34b5-11e7-8961-4936ce2231b8.png)

Is this possible in Keras?

**Comment by RubenZazo** [comment]
Still working on this with no luck, any help?

**Comment by karanvivekbhargava** [comment]
Hey any luck on this? I'm stuck on this problem too. Any help appreciated.

**Comment by voletiv** [comment]
Looking a solution as well.

**Comment by Owenscu** [comment]
Hey! I'm stuck on this problem too.Looking a solution as well.

**Comment by tbrodbeck** [comment]
push

**Comment by tbrodbeck** [comment]
> feel free to re-open a closed issue if needed.
How to reopen the thread?
