### ISSUE TITLE
Problems with convolutional calls inside a for loop..

### ISSUE THREAD

**Issue by Miail** [fchollet/keras#6556]
I seem to have some problem with doing convolutions inside a for loop. Not sure why this is a problem though..

Here is the code: 

```
def slice(x):
    output = []
    for column in xrange(x.shape[2]):
        output.append(x[:,:,column,:])
    return output


def fws():
    #Input shape: (batch_size,40,45,3)
    #output shape: (1,15,50)
    # number of unit in conv_feature_map = splitd
    print "Printing shapes"
 
 
    list_of_input = [Input(shape = (window_height,total_frames_with_deltas,3)) for i in range(33)]
    for inputs in list_of_input:
        s = Lambda(slice)(inputs)
        output = [(Conv1D(filters = J, kernel_size = 8)(s[i])) for i in range(45)]
```

My input is a list of of small images of shape (8,45,3)
and for some reason am I getting an library error when i do the second convolution.. 

This is the error: 
```
Traceback (most recent call last):
  File "keras_cnn_phoneme_original_fit_generator.py", line 211, in <module>
    fws()
  File "keras_cnn_phoneme_original_fit_generator.py", line 164, in fws
    output = Conv1D(filters = J, kernel_size = 8)(index)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2703, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
IndexError: list index out of range
```

The difference there is between the first convolution and the second, is the input type being fed to the convolutional layer. 

First tensor type is: 
`Tensor("lambda_1/strided_slice:0,shape=(?,8,3),dtype=float32)
`
The second type is:
`Tensor("lambda_1/strided_slice_1:0,shape=(?,8,3),dtype=float32)`

They are pretty much the same other than that. 

The error seem to be in library error,  And I am not sure I understand why i even get this error. 
Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by kgrm** [comment]
Hello,

your code doesn't run independently and doesn't reproduce the issue. Please post a self-contained example.
