### ISSUE TITLE
Please add support of Convolution3DTranspose

### ISSUE THREAD

**Issue by jichen3000** [fchollet/keras#6561]
I want to use Keras to implement the 3d UNET, but I found there is no Convolution3DTranspose layer in the eras.layers.

But TensorFlow and Theano both support Convolution3DTranspose, so could you add this layer in the Keras.

**Comment by Danielhiversen** [comment]
https://github.com/farizrahman4u/keras-contrib/blob/master/keras_contrib/layers/convolutional.py#L19

**Comment by jichen3000** [comment]
Thanks Daniel, I'll use Deconvolution3D.

I googled the Keras Convolution 3D Transpose, but got nothing, and forgot to search by the key word "Deconvolution3D".

**Comment by fchollet** [comment]
This is something we can definitely add to core Keras (based on the current `Conv2DTranspose` layer).

**Comment by fchollet** [comment]
(i.e. a PR for this would be welcome)
