### ISSUE TITLE
L1_L2 regularization implemented wrong?

### ISSUE THREAD

**Issue by StefanoD** [fchollet/keras#6585]
Looking at the source code, the L1_L2 (also known as _elastic net_) regularization differs dramatically from description of [this](http://web.stanford.edu/~hastie/Papers/B67.2%20%282005%29%20301-320%20Zou%20&%20Hastie.pdf) paper.
```python
class L1L2(Regularizer):
    """Regularizer for L1 and L2 regularization.

    def __call__(self, x):
        regularization = 0.
        if self.l1:
            regularization += K.sum(self.l1 * K.abs(x))
        if self.l2:
            regularization += K.sum(self.l2 * K.square(x))
        return regularization
```
Is this done on purpose or do you understand something different on the term L1/L2 regularization?

**Comment by kgrm** [comment]
This appears to me to be an accurate implementation of the regularization terms from the equation 3 in the paper.

**Comment by StefanoD** [comment]
You are right!
