### ISSUE TITLE
How to break symmetry in fit_generator() sample generator?

### ISSUE THREAD

**Issue by ophiry** [fchollet/keras#6586]
From what I understand, the same sample generator if run concurrently in multiple thread or processors
Is there a way for the iterator instance to know it's "id" to avoid sending the same samples by all generators?
(besides using a random sample in each)

**Comment by Dref360** [comment]
Just use the GIL?

**Comment by ophiry** [comment]
What do you mean?
Though because of the GIL I believe that multiprocessing will be more relevant than multithreading

**Comment by Dref360** [comment]
Using a [thread_safe iterator](http://anandology.com/blog/using-iterators-and-generators/) You will be sure that there is no concurrent access to your generator

**Comment by ophiry** [comment]
and for multiprocessing?

**Comment by Dref360** [comment]
No real way to do it when using multiprocessing since the generator is copied.

**Comment by parag2489** [comment]
Generate a randomly shuffled vector and use it as a index vector to shuffle your data for the entire epoch. This should be done outside your batch-loop where you yield the samples.

**Comment by joeyearsley** [comment]
This is fixed for multiproc in #7118
