### ISSUE TITLE
Second GridSearch of a KerasClassifier hangs forever

### ISSUE THREAD

**Issue by Flaac** [fchollet/keras#6600]
## Issue

I am currently using a KerasClassifier and I want to make several grid search with it. For the grid search, I use GridSearchCV from scikit-learn. 

The first GridSearch is working perfectly well (using all of my cpu). However, when the second GS is launch, it hangs forever...

This problem does not occur when I am replacing KerasClassifier by XGBClassifier. 

## Version

Ubuntu 16.04 LTS
Keras 2.0.4
tensorflow 1.1.0
sklearn 0.18.1

## Code

```
import numpy as np
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

def create_model():
    model = Sequential()
    model.add(Dense(12, input_dim=8, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return(model)

X = np.random.rand(50,8)
Y = np.random.rand(50,1)

batch_size = [10, 20]
epochs = [10, 100]
param_grid = dict(batch_size=batch_size, epochs=epochs)

model1 = KerasClassifier(build_fn=create_model, verbose=0)
grid1 = GridSearchCV(estimator=model1, param_grid=param_grid, n_jobs=-1, verbose=1)
grid1.fit(X,Y)

model2 = KerasClassifier(build_fn=create_model, verbose=0)
grid2 = GridSearchCV(estimator=model2, param_grid=param_grid, n_jobs=-1, verbose=1)
grid2.fit(X,Y)
```

----------------------------------------------------------------------------------------------------------------------------

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by richford** [comment]
I also get this same exact issue.

**Comment by derek591** [comment]
I am having the exact same issue as well.

**Comment by seralouk** [comment]
+1

**Comment by seralouk** [comment]
The problem seems to be still present. Any solutions when n_jobs > 1 ???

**Comment by jupiters1117** [comment]
Any hope to resolve the issue? Thanks in advanced.

**Comment by jupiters1117** [comment]
@seralouk Here is the [solution](https://stackoverflow.com/questions/42504669/keras-tensorflow-and-multiprocessing-in-python/42506478#42506478) for the hanging issue. In summary, you will need to launch a forked process for Keras/Tensorflow model training.

**Comment by kingzone** [comment]
+1. See [GridSearchCV freezes indefinitely with multithreading enabled (i.e. w/ n_jobs != 1)](https://github.com/scikit-learn/scikit-learn/issues/5115)
