### ISSUE TITLE
Regularizer with cumulative distribution function

### ISSUE THREAD

**Issue by sebastianruder** [fchollet/keras#6608]
I would like to implement a regularizer in keras that uses the [cumulative distribution function](https://en.wikipedia.org/wiki/Cumulative_distribution_function). Is there a way to use this function directly or compose this function out of tensor operations?

**Comment by gokceneraslan** [comment]
You can use https://www.tensorflow.org/api_guides/python/contrib . distributions for TF, instead of implementing from scratch.
