### ISSUE TITLE
Feature Request: FLAGS for setting image_data_format

### ISSUE THREAD

**Issue by capybaralet** [fchollet/keras#6609]
I haven't seen it documented anywhere, except [here](https://www.nodalpoint.com/switch-keras-backend/), but AFAICT:

1. there is no way to set this aspect of the config with COMMAND_LINE_FLAGS (like KERAS_BACKEND)
and 
2. it is not automatically set to be consistent with the backend.

I think there should be a command line flag for it.

**Comment by parag2489** [comment]
There are two ways to set Keras backend: 1. Using the json file `.keras/keras.json` (easier way) 2. change the variable `KERAS_BACKEND` such as `KERAS_BACKEND=tensorflow python -c "from keras import backend"`. Changing the environment variable takes higher priority, Does this answer your question.

All of this is mentioned on the [Keras website](https://keras.io/backend/).

**Comment by capybaralet** [comment]
No.  I understand the features that you've referenced.  I want another feature!

I'm talking about setting the image_data_format.

Since I use both TH and TF, I need to be able to change between them, because the speed difference if very large if you don't use the right image_data_format for the backend that you are using.

**Comment by parag2489** [comment]
Look at `K.set_image_data_format(data_format)`, `K.set_floatx(floatx)` and `K.set_epsilon(e)` [here](https://keras.io/backend/).

**Comment by capybaralet** [comment]
I know it's possible to do it this way.  I am requesting a feature to do it
using a ENVIRONMENT_VARIABLE.
