### ISSUE TITLE
LeakyReLU gives nan loss

### ISSUE THREAD

**Issue by inspiralpatterns** [fchollet/keras#6615]
I have a structure made of several of such convolutional layers:
```
# encoding structure
x = Conv2D(256, (3, 3), padding='same', kernel_regularizer=regularizers.l2(0.01),
activity_regularizer=SparseReg(beta=5e-1,p=1e-2),name='lay1')(input_img)
x = LeakyReLU(alpha=1e-1)(x)
```
and when I inspect the loss values I see all the time
`loss: nan`

When using `activation='relu'` inside the layer, for instance, I get normal values.
Does anyone have any similar experience when using an advanced activation layer?

**Comment by bjtho08** [comment]
Did you ever solve this issue? I'm seeing the same thing with my model.
