### ISSUE TITLE
Out of Memory error at model.compile

### ISSUE THREAD

**Issue by siddharthm28** [fchollet/keras#6647]
I have a relatively large multi-layer regression model that I want to train end-to-end. My training is a two-step procedure in which I first minimize the euclidean loss and then I minimize my loss. Effectively, this means the following pseudo-code:
```
model.compile(optimizer='Adam', loss='mse')
model.fit()
model.compile(optimizer='Adam', loss=my_metric)
model.fit()

```
I am able to run the first two statements without any problems. But I get an out of memory error when my code reaches the second model.compile statement. What should I do differently to avoid this problem ?

**Comment by bfarzin** [comment]
It could be that the compiler runs out of memory on the box.  Watch the memory as the program is running and you will see if it goes up as you compile the second time.

If that is the case, the[ link/comment at the end of this thread](https://github.com/fchollet/keras/issues/929) about increasing the swap space will alleviate the issue.

**Comment by siddharthm28** [comment]
I'll have a look.. thank you !
