### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by entron** [fchollet/keras#665]
When I try to pickle a model. I got this error. I am using python3.

**Comment by madeofwin** [comment]
Not sure about python 3's recursion limit, but the recursion limit of python 2.7 is 1000 and can be increased by

```
import sys
sys.setrecursionlimit(10000)
```

**Comment by entron** [comment]
Indeed this solves the problem! 

I noticed that loading picked model takes only a little bit less time than compiling from scratch. Is there any way that I can load a pre-compiled model very fast?

**Comment by fchollet** [comment]
I would generally recommend not pickling models. The method outlined [here](http://keras.io/faq/#how-can-i-save-a-keras-model) is much safer and should not take much longer in practice.

**Comment by cohimame** [comment]
If you are using ubuntu:

sudo apt-get install libhdf5-dev
sudo pip3 install h5py

**Comment by urbanintell** [comment]
Did you fine a solution? I am having the same problem install PyMEL

**Comment by 9Sarkan** [comment]
did anyone find a solution? I'm having it too.
