### ISSUE TITLE
Keras predict/predict_on_batch says "too many values to unpack"

### ISSUE THREAD

**Issue by Hazarapet** [fchollet/keras#6656]
Why Keras 2.0 predict/predict_on_batch says "too many values to unpack"? The input shape is 
(40, 4, 128, 128) (40 is the batch size), but the evaluate function works fine on the same batch of inputs. Tell me please what the reason is.

**Comment by bfarzin** [comment]
Can you please post some sample code that replicates the problem?

**Comment by Hazarapet** [comment]
`for min_batch in common_util.iterate_minibatches(val, batchsize=BATCH_SIZE):
        v_batch_inputs = []
        v_batch_labels = []

        # load val's images
        for f, tags in min_batch:
            img = getImage(f)
            assert rgbn is not None

            if img is not None:
                targets = 0
                for t in tags.split(' '):
                    if t == 'object':
                        targets = 1

                v_batch_inputs.append([a, b, c, d]) # 4x128x128
                v_batch_labels.append(targets)

        v_batch_inputs = np.array(v_batch_inputs).astype(np.float32)
        v_batch_labels = np.array(v_batch_labels).astype(np.int8)

        [v_loss, v_acc] = model.evaluate(v_batch_inputs, v_batch_labels, batch_size=BATCH_SIZE, verbose=0) # works fine.No any error
        [v_p] = model.predict_on_batch(v_batch_inputs) # gives the error`

The v_batch_inputs's shape is (BATCH_SIZE, 4, 128, 128)

**Comment by bfarzin** [comment]
Can you send more detail about the error message?
Does the value for `v_acc` look reasonable?  
Can you let me know if  `model.predict(v_batch_inputs,batch_size=BATCH_SIZE)` also throws an error?

**Comment by Hazarapet** [comment]
I've given you the details.the batch input shape is (bs, 4, 128, 128).The type of the values is float32. I'm using theano as backend. the predict and predict_on_batch gives the same "too many values to unpack" error, but the evaluate function just one line above it, works fine and never gave that error.

**Comment by bfarzin** [comment]
Understood.  Can you just copy and paste the error here?  The "too many values" can come from many places and since I can't run your code snippet as-is it is hard to determine where the problem is coming from.

**Comment by Hazarapet** [comment]
it just gives that error.nothing else.just that.the error contains only **my** code's location (line number) and nothing else.I don't know what to give you

**Comment by bfarzin** [comment]
Is the output like this (expected 2) or something else?  I realize it is your code but I want to know more detail about the error so I can help you to find the problem.  It could be that you are trying to put the value into a list rather than a variable, but that is not clear unless I see the error message.

```
File "I:\School\Working Glossary.py", line 14, in dictest
(key,value) = line.split(",")
ValueError: too many values to unpack (expected 2)
```
(taken from[ this stackoverflow question/answer](http://stackoverflow.com/questions/28222915/valueerror-too-many-values-to-unpack-expected-2-errors))

**Comment by Hazarapet** [comment]
no my friend.Just that error.I will type here if I will have any other message

**Comment by bfarzin** [comment]
ok.  give this a try, remove the [] from your return variable:
`v_p = model.predict_on_batch(v_batch_inputs) # gives the error`

**Comment by Hazarapet** [comment]
oh~.Maybe you are right.I guess it can't unpack the values.I will close the issue anyway and will open it, if the solution didn't work.
