### ISSUE TITLE
datagen.flow question

### ISSUE THREAD

**Issue by ymcasky** [fchollet/keras#6657]
I using Keras 2.x ‘tf’ seeting.
Why I can’t using
X_batch, y_batch = datagen.flow(train, train, batch_size=32)
For example :

# Code
from keras.datasets import mnist
from keras.preprocessing.image import ImageDataGenerator

(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = X_train.reshape(X_train.shape[0], 28, 28,1)
X_test = X_test.reshape(X_test.shape[0], 28, 28,1)
X_train = X_train.astype(‘float32’)
X_test = X_test.astype(‘float32’)
datagen = ImageDataGenerator(featurewise_center=True, featurewise_std_normalization=True)
datagen.fit(X_train)
X_batch, y_batch = datagen.flow(X_train, y_train, batch_size=9)

#Question 
Can anyone tell me why?
Thanks!

**Comment by sabersword** [comment]
datagen.flow() returns a generator. To obtain the batch, use:
X_batch, y_batch = datagen.flow(X_train, y_train, batch_size=9).next()

**Comment by ymcasky** [comment]
@sabersword 
Thanks a lot!
