### ISSUE TITLE
Weird results from Keras `eval`

### ISSUE THREAD

**Issue by yaringal** [fchollet/keras#6669]
Hi, I came across some weird behaviour today running this simple script:
```
from keras import backend as K
import numpy as np
kvar = K.variable(np.array([[1, 2], [3, 4]]), dtype='float32')
K.eval(kvar)
```
Which gave this output:
```
Using TensorFlow backend.
Out[1]:
array([[  1.00000000e+00,   3.15087917e-29],
       [  8.61639512e-36,   4.50566121e+15]], dtype=float32)
```
My TF version is 1.0.1.

Has anybody else come across this??

**Comment by Ch1nny** [comment]
I have the same issue with my laptop, on public server works fine. Can you share with us about how you managed to solve this problem? Thanks.
