### ISSUE TITLE
how to define the batch size using train_on_batch

### ISSUE THREAD

**Issue by Tangzy7** [fchollet/keras#6673]
How to define the batch size when I use train_on_batch to start training. Or does the model will select the batch size automatically?

I did't find any helpful usage about 'train_on_batch'.

**Comment by Dref360** [comment]
Like the [doc](https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1592) says. `train_on_batch` is used to train a single batch. So it trains what you give. If you give an array of 3000 data, it will feed the network will all 3000 of them at once.

**Comment by StefanoD** [comment]
Please, close this issue again. For questions look for Stackoverflow.
