### ISSUE TITLE
Error in Prediction: ValueError (image_ocr)

### ISSUE THREAD

**Issue by selcouthlyBlue** [fchollet/keras#6686]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I was able to produce a model from training using [image_ocr](https://github.com/fchollet/keras/blob/master/examples/image_ocr.py). I also saved the architecture into a json file which I used with the model in this predict script which passes an image in a numpy array format:

`import keras.backend as K
from keras.models import model_from_json
from skimage.io import imread

K.set_image_dim_ordering('tf')

json_file = open("image_ocr_architecture.json", "r")
loaded_model_json = json_file.read()
json_file.close()
tf_dim_model = model_from_json(loaded_model_json)

weight_fn = "weights03.h5"
tf_dim_model.load_weights(weight_fn)

im = imread("a01-000u-00.png")
tf_dim_model.predict(im)`

However, when I run this script I get this error:
`ValueError: The model expects 4 arrays, but only received one array. Found: array with shape (89, 1661)`

I wonder what I'm doing wrong here :O

**Comment by pigubaoza** [comment]
I'm facing the same problem. can this be re-opened?
