### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'kernel_initializer')

### ISSUE THREAD

**Issue by HsiangHung** [fchollet/keras#6710]
I am using Keras 1.2.0.
I built model as:
`model = Sequential()`
`model.add(Dense(13, input_dim=13, kernel_initializer='normal', activation='relu'))`
`model.add(Dense(1), kernel_initializer='normal')`
`model.compile(loss='mean_squared_error', optimizer='adam')`
When I fit, it shows ton of error messages
`.....`
`.....`
`TypeError: ('Keyword argument not understood:', 'kernel_initializer')`.
I realized Keras 1 and Keras 2 are slightly different. If yes, what are the analogous parameters to initialize kernel, like `kernel_initializer='normal', in Keras 1?

**Comment by kgrm** [comment]
Keras 1.2 doesn't support separate kernel/bias initializers, layers only take a single `init` parameter, eg, `Dense(10, init="normal", activation="relu")`.

**Comment by HsiangHung** [comment]
@kgrm thank you!
