### ISSUE TITLE
Keras Custom Layers: Connections within a Layer

### ISSUE THREAD

**Issue by prabaha007** [fchollet/keras#6717]
I want to make a custom layer through `Keras` such that the neurons with similar feature preference are connected linearly. For example, consider the output of each neuron is,
<a href="http://www.codecogs.com/eqnedit.php?latex=y_k&space;=&space;ReLU\left(\sum_i&space;w_ix_i&space;&plus;&space;\sum_{j&space;\neq&space;k}{\omega_jy_j}\right)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?y_k&space;=&space;ReLU\left(\sum_i&space;w_ix_i&space;&plus;&space;\sum_{j&space;\neq&space;k}{\alpha_jy_j}\right)" title="y_k = ReLU\left(\sum_i w_ix_i + \sum_{j \neq k}{\alpha_jy_j}\right)" /></a><br>
where y<sub>k</sub>-s are neurons with "similar" preferences, i.e. in a layer with shape 224x224x92 each 224x224 neurons are connected by 'alpha' weights but there are no connections between any of the layers corresponding to the 94 filters. How can I implement this? All the weights, 'alpha' and 'w' are going to be trained by back propagation. It is effectively like implementing a Hopfield network in the output of each of the kernels at a particular layer.
I do not want to use 'recurrent' connections, since my data is not time variable. There are 'n' mages of 'm' classes, and I want the network to have connections like the one I mentioned above.

**Comment by Psyf** [comment]
Did you find a solution?
