### ISSUE TITLE
fbeta_score not found in keras 2.0.4

### ISSUE THREAD

**Issue by flamoedo** [fchollet/keras#6719]
The following script
`from keras.metrics import fbeta_score`

Gives me this error:

ImportError: cannot import name 'fbeta_score'

And this script:

```
from keras.metrics import *
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', 'fbeta_score'])
```

Gives me this error:

ValueError: ('Unknown metric function', ':fbeta_score')

So I assume that fbeta_score function is not implemented, as it says in the documentation.

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by StefanoD** [comment]
1. I couldn't find fbeta_score in the documentation
2. It doesn't make any sense to import an instance of fbeta_score and then deliver a string as parameter

**Comment by flamoedo** [comment]
I've found a implementation on git and includ it in my project, thanks.

**Comment by flamoedo** [comment]
callicles commented 19 days ago

> Hi,
> 
> Those metrics have been removed in 2.0. #5794
