### ISSUE TITLE
Can't use sample_weights both for fit or evaluate model

### ISSUE THREAD

**Issue by flamoedo** [fchollet/keras#6720]
If I try to use a list of weights it gives a error:
AttributeError: 'list' object has no attribute 'shape'

If I try to use a 1D array, it gives the error:
ValueError: Found a sample_weight array with shape (17,) for an input with shape (180, 17). sample_weight cannot be broadcast.

`model.evaluate(X, Y, batch_size=50, sample_weight=weights)
`

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by StefanoD** [comment]
The errors are pretty obvious. In the first case you don't deliver a numpy array. In the last case, the shapes don't fit.
This is not a bug. Please ask a question on Stackoverflow or on the Keras Slack channel and close this issue.

**Comment by flamoedo** [comment]
This is a bug indeed, because the document says that a 2D array is for temporal weights, what not is my case, and I've already tried to broadcast the array in 2D and ir gives me another error.

**Comment by flamoedo** [comment]
Would you please, send me a invitation for Keras Slack channel ?
Thank you!

**Comment by flamoedo** [comment]
The correct parameter is class_weight, that accepts a dictionary of weights.
weights = dict({0:1, 1:2, 2:1, 3:5})
`model.evaluate(X, Y, batch_size=50, class_weight=weights)`
