### ISSUE TITLE
Which shape I have to return labels with if I want to use fit_generator

### ISSUE THREAD

**Issue by mrlzla** [fchollet/keras#6728]
So I build neural network with input_shape (255, 255, 3). I want to have my output as (255, 255, 1). In my fit_generator I return inputs and labels with shapes (64, 255, 255, 3) and (64, 255, 255, 1) simultaneously. And when I start to train my neural network, it throws an error: 
```
ValueError: Error when checking model target: expected conv2d_16 to have shape (None, 225, 225, 1) but got array with shape (64, 255, 255, 1)
```
What should I do to resolve this problem?

**Comment by kgrm** [comment]
Looks like your network has an output shape of (batch, 225, 225, 1), whereas you're feeding it output labels shaped (batch, 255, 255, 1). You can verify this with `model.summary()` to help pinpoint the issue.

**Comment by mrlzla** [comment]
Sure. Thank you. Closed.
