### ISSUE TITLE
Docker keras image:  ImportError: No module named 'keras'

### ISSUE THREAD

**Issue by gpp8p** [fchollet/keras#6750]
Hi -

   I recently installed the keras docker image that is served from https://github.com/fchollet/keras/tree/master/docker.

using the makefile, when I invoke it with:
make notebook GPU=0

the notebook comes up fine.  However, when I invoke a cell that has:

import keras

I get this error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c74e2bd4ca71> in <module>()
----> 1 import keras

ImportError: No module named 'keras'

**Comment by DanielMo123** [comment]
I get this too

**Comment by taneta** [comment]
Me too. 
Have you solved the problem?

**Comment by adhaimovich** [comment]
I have the same problem. When I employ the solution below, I get a tensorflow error:

`nvidia-docker` run -it --rm -p 8888:8888 -v $(pwd):/src/workspace --env KERAS_BACKEND=tensorflow keras jupyter notebook --no-browser --port=8888 --ip=0.0.0.0 --allow-root`

"Failed to load the native TensorFlow runtime."

**Comment by marcosfede** [comment]
Same problem here,  using @taneta solution or `make ipython` and importing keras shows 
`ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory`
