### ISSUE TITLE
What will be the input like when you have multi features for LSTM

### ISSUE THREAD

**Issue by 176coding** [fchollet/keras#6762]
I have a time series dataframe like blow, and the number in it is meaning less, and I have some problems when applying LSTM.
I have saw some demos of LSTM, mostly use this pattern: `[y_{t-2},y_{t-1},y_{t}] to predict [y_{t+1}]`, but just as the dataframe blow, I also have` featureA, featureB, featureC`, 

so my quesiton is: how to use multi inputs or multi features to predict target for LSTM
```

time    featureA    featureB    featureC    target
1   2   5   6   1
2   4   1   7   3
3   6   2   1   5
4   2   4   0   7
5   7   6   1   5
6   9   3   2   8
7   1   2   3   5
8   2   9   5   10
9   1   10  7   6
10  3   2   2   11
```

**Comment by fengsam** [comment]
I have a time-series dataset data_x with 3600*50,  its corresponding label is data_y with 3600*1. The following code may help you. 
```
seq_length = 10
x = []
y = []
for i in range(0, len(data_x) - seq_length):
    given = data_x[i:i + seq_length]
    predict = data_y[i + seq_length]
    x.append(given)
    y.append(predict)
```
