### ISSUE TITLE
batch training but online prediction

### ISSUE THREAD

**Issue by Narts** [fchollet/keras#6767]
Hi,

I trained a LSTM models with batch training(stateful=false), but then I want to use it to do online prediction. Is it possible? 

E.g when training the model, the input shape is (32, 5, 2). The batch_size is 32, time_steps is 5, data_dim is 2. But if it is used to do online prediction, the batch_size can not be 32, and the time_steps can not be 5 as well. Actually, both batch_size and time_steps will be 1.(Online prediction)

So how can I implement this with keras?
I would appreciate any ideas!

**Comment by jfelectron** [comment]
You can create a new graph that has a batch size of 1 on the input layer. Use get_weights() to extract the weights from the trained model and set_weights to load the weights into the inference graph.
