### ISSUE TITLE
How to use keras to implement second many-to-many architecture of LSTM

### ISSUE THREAD

**Issue by 176coding** [fchollet/keras#6772]
Just as the image, how to use keras to implement the last many-to-many architecture of LSTM, is there any example, thx.
![nomka](https://cloud.githubusercontent.com/assets/9864284/26516993/683445bc-42c2-11e7-8d33-ac55c5d68ba0.jpg)

**Comment by Miail** [comment]
https://stackoverflow.com/questions/44212259/how-to-use-keras-to-implement-second-many-to-many-architecture-of-lstm

Issues are not for implementation issues... please use other channels for that.
