### ISSUE TITLE
IndexError on predict step

### ISSUE THREAD

**Issue by hwsamuel** [fchollet/keras#6773]
I trained a model on a training dataset, saved the model and weights. In another step, I loaded the saved model and compiled it, and then used it for prediction, but I got the following error. What's the resolution of it? I'm using the latest Keras version.

```
IndexError: Index out of bounds.
Apply node that caused the error: GpuAdvancedSubtensor1(embedding_1/embeddings, GpuContiguous.0)
Toposort index: 76
Inputs types: [GpuArrayType<None>(float32, (False, False)), GpuArrayType<None>(int64, (False,))]
Inputs shapes: [(95604, 300), (800,)]
Inputs strides: [(1200, 4), (8,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[GpuReshape{2}(GpuAdvancedSubtensor1.0, TensorConstant{[ -1 300]})]]

```

**Comment by StefanoD** [comment]
Could you show some code?

**Comment by hwsamuel** [comment]
Sure thing, attached is the code, it's heavily based on [this repo](https://github.com/bradleypallen/keras-quora-question-pairs). 

[script.zip](https://github.com/fchollet/keras/files/1034605/script.zip)

**Comment by StefanoD** [comment]
I'm not gonna look through all the code. Could you show as the part where the error occurs?

**Comment by hwsamuel** [comment]
Sure, here it is (exact line has comment):

```
q1_data = np.load(open(q1_file, 'rb'))
q2_data = np.load(open(q2_file, 'rb'))
json_file = open(model_file, 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights(weights_file)
loaded_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
pred = loaded_model.predict([q1_data, q2_data]) # ERROR
```
In case you're wondering about how the q1_data and q2_data files were stored, here's the code for that:

```
question1 = []
question2 = []
with open(csv_file) as csvfile:
    reader = csv.DictReader(csvfile, delimiter=',')
    for row in reader:
        question1.append(row['question1'])
        question2.append(row['question2'])
questions = question1 + question2
tokenizer = Tokenizer(nb_words=max_nb_words)
tokenizer.fit_on_texts(questions)
question1_word_sequences = tokenizer.texts_to_sequences(question1)
question2_word_sequences = tokenizer.texts_to_sequences(question2)
word_index = tokenizer.word_index
q1_data = pad_sequences(question1_word_sequences, maxlen=MAX_SEQUENCE_LENGTH)
q2_data = pad_sequences(question2_word_sequences, maxlen=MAX_SEQUENCE_LENGTH)

**Comment by ankitmishra262** [comment]
I'm also getting a similar issue. My best guess is during training the tokenizer churns a certain number of tokens, but during prediction, the tokenized value doesn't fit for the embedding layer, as the embedding matrix will use the word index length (if there is a new word encountered, the tokens will increase), if something like this can occur. Any way this error can be debugged?

One way could be doing `tokenizer.fit_on_texts` on the whole data, then `fit` the model. Finally prediction will be done on the test data. But that would mean training every time a new kind of data comes in, not very practical.
