### ISSUE TITLE
AttributeError importing keras:

### ISSUE THREAD

**Issue by stepseazy** [fchollet/keras#6789]
Hi all,

I'm getting this issue importing Keras, not sure what the issue is....

Rik

```
import keras
from keras.models import Sequential, Model
from keras.layers.core import Dense, Dropout, Activation, Flatten, Reshape
from keras.layers import Embedding, Input, merge
from keras.layers.recurrent import SimpleRNN, LSTM
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.optimizers import SGD, Adam, RMSprop
import sklearn.metrics as metrics
```

> Using TensorFlow backend.
> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-9-04a29ddc95d4> in <module>()
> ----> 1 import keras
>       2 from keras.models import Sequential, Model
>       3 from keras.layers.core import Dense, Dropout, Activation, Flatten, Reshape
>       4 from keras.layers import Embedding, Input, merge
>       5 from keras.layers.recurrent import SimpleRNN, LSTM
> 
> /home/rik/anaconda3/lib/python3.5/site-packages/keras/__init__.py in <module>()
>       1 from __future__ import absolute_import
>       2 
> ----> 3 from . import activations
>       4 from . import applications
>       5 from . import backend
> 
> /home/rik/anaconda3/lib/python3.5/site-packages/keras/activations.py in <module>()
>       1 from __future__ import absolute_import
>       2 import six
> ----> 3 from . import backend as K
>       4 from .utils.generic_utils import deserialize_keras_object
>       5 
> 
> /home/rik/anaconda3/lib/python3.5/site-packages/keras/backend/__init__.py in <module>()
>      62 elif _BACKEND == 'tensorflow':
>      63     sys.stderr.write('Using TensorFlow backend.\n')
> ---> 64     from .tensorflow_backend import *
>      65 else:
>      66     raise ValueError('Unknown backend: ' + str(_BACKEND))
> 
> /home/rik/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in <module>()
> ----> 1 import tensorflow as tf
>       2 from tensorflow.python.training import moving_averages
>       3 from tensorflow.python.ops import tensor_array_ops
>       4 from tensorflow.python.ops import control_flow_ops
>       5 from tensorflow.python.ops import functional_ops
> 
> /home/rik/anaconda3/lib/python3.5/site-packages/tensorflow/__init__.py in <module>()
>      22 
>      23 # pylint: disable=wildcard-import
> ---> 24 from tensorflow.python import *
>      25 # pylint: enable=wildcard-import
>      26 
> 
> /home/rik/anaconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py in <module>()
>      75 
>      76 # Bring in subpackages.
> ---> 77 from tensorflow.python.estimator import estimator_lib as estimator
>      78 from tensorflow.python.layers import layers
>      79 from tensorflow.python.ops import image_ops as image
> 
> /home/rik/anaconda3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator_lib.py in <module>()
>      22 from tensorflow.python.estimator.estimator import Estimator
>      23 from tensorflow.python.estimator.export import export_lib as export
> ---> 24 from tensorflow.python.estimator.inputs import inputs
>      25 from tensorflow.python.estimator.model_fn import EstimatorSpec
>      26 from tensorflow.python.estimator.model_fn import ModeKeys
> 
> /home/rik/anaconda3/lib/python3.5/site-packages/tensorflow/python/estimator/inputs/inputs.py in <module>()
>      21 # pylint: disable=unused-import,line-too-long
>      22 from tensorflow.python.estimator.inputs.numpy_io import numpy_input_fn
> ---> 23 from tensorflow.python.estimator.inputs.pandas_io import pandas_input_fn
>      24 
>      25 from tensorflow.python.util.all_util import remove_undocumented
> 
> /home/rik/anaconda3/lib/python3.5/site-packages/tensorflow/python/estimator/inputs/pandas_io.py in <module>()
>      26   # pylint: disable=g-import-not-at-top
>      27   # pylint: disable=unused-import
> ---> 28   import pandas as pd
>      29   HAS_PANDAS = True
>      30 except IOError:
> 
> /home/rik/anaconda3/lib/python3.5/site-packages/pandas/__init__.py in <module>()
>      49 # deprecate tools.plotting, plot_params and scatter_matrix on the top namespace
>      50 import pandas.tools.plotting
> ---> 51 plot_params = pandas.plotting._style._Options(deprecated=True)
>      52 # do not import deprecate to top namespace
>      53 scatter_matrix = pandas.util._decorators.deprecate(
> 
> AttributeError: module 'pandas' has no attribute 'plotting'
> 
>

**Comment by vlasenkov** [comment]
Which versions of `pandas`  and `keras` do you use? Try:
```
