### ISSUE TITLE
Import problem in mnist_mlp.py

### ISSUE THREAD

**Issue by zzhang-cn** [fchollet/keras#679]
Hi there, I run mnist_mlp.py and get the following problem

Traceback (most recent call last):
  File "mnist_mlp.py", line 24, in <module>
    (X_train, y_train), (X_test, y_test) = mnist.load_data()
  File "//anaconda/lib/python3.4/site-packages/keras/datasets/mnist.py", line 19, in load_data
    data = cPickle.load(f, encoding="bytes")
TypeError: must be a unicode character, not bytes

I am on Mac OS X Yosemite, and Python 3.4.1. The file downloaded alright. I saw there was an issue opened before, actually I've tried both versions, the old one:
import six.moves.cPickle

And the new version:
from six.moves import cPickle

Didn't make any differences. Stuck and cannot train. :(

Any idea to get around it will be greatly appreciated!

**Comment by fchollet** [comment]
> data = cPickle.load(f, encoding="bytes")
> TypeError: must be a unicode character, not bytes

What Python version are you using? What platform?

I don't think we've seen this problem before.

**Comment by zzhang-cn** [comment]
![image](https://cloud.githubusercontent.com/assets/8557905/9848271/17ef3d76-5b12-11e5-81cc-121965ee4c82.png)

![image](https://cloud.githubusercontent.com/assets/8557905/9848280/35c26a4e-5b12-11e5-829d-efc75536e0ce.png)

![image](https://cloud.githubusercontent.com/assets/8557905/9848293/68304398-5b12-11e5-8675-d84ba7fd52b3.png)

It's indeed a bit odd.... :( Thank you so much for looking into this,

**Comment by daniel-j-h** [comment]
I can reproduce this when trying to load the `cifar10` dataset:
```
Traceback (most recent call last):
  File "./nn.py", line 31, in <module>
    (data_train, labels_train), (data_test, labels_test) = cifar10.load_data()
  File "/tmp/nn/.env/lib/python3.4/site-packages/keras/datasets/cifar10.py", line 21, in load_data
    data, labels = load_batch(fpath)
  File "/tmp/nn/.env/lib/python3.4/site-packages/keras/datasets/cifar.py", line 12, in load_batch
    d = cPickle.load(f, encoding="bytes")
TypeError: must be a unicode character, not bytes
```

Environment is Ubuntu 15.04, Python 3.4 from within a pyvenv.

**Comment by EderSantana** [comment]
I think `cPickle` is not in python3 or something like that: http://docs.pythonsprints.com/python3_porting/py-porting.html

**Comment by yitang** [comment]
i have the same issue here.

**Comment by wany1601** [comment]
By specifying  `encoding="bytes"`, `cPickle.lod` should be working even for python3.

Actually It can be a numpy version issue, if the numpy version is too old (i.e. 1.8), then you may have this problem, by upgrade it to the latest version(i.e. 1.11), this problem should be fixed. Don't forget, if you reinstall numpy, scipy need to be reinstalled too.
