### ISSUE TITLE
Efficiently get both evaluation metrics and prediction values in a single pass

### ISSUE THREAD

**Issue by Djoulihen** [fchollet/keras#6790]
Hi, I am currently trying to implement a callback that will run every X epochs and do 2 things:

1. Run my image reconstruction model on a specific dataset of images and save the predictions to disk as images.
2. Evaluate the model on the same dataset (i.e. run all the metrics that were compiled with the model, including some custom metrics implemented using the keras backend abstraction) and save this information along with the prediction images.

The Model.predict and Model.evaluate methods fit my needs perfectly. However they require each image to be run twice through the network, which seems really inefficient. So far I haven't found a good way to easily obtain both a prediction on a batch of data and run all the metrics compiled into the model on it. Am I missing something ?

If not, I guess that Model.evaluate could easily return the predictions from the network as an optional output controlled by a an additional parameter such as:
`model.evaluate(x, predictions=True)`

**Comment by ErenBYilmaz** [comment]
I have the same issue, actually quite a large part (about half) of my time goes into evaluation and prediction for my use case so I could speed it up by 2x if it was possible to predict and evaluate at the same time. 

Or maybe only predict and then call the metrics separately with the prediction if that is easier, but I can't get it working.

**Comment by zaccharieramzi** [comment]
I find myself having the same problem. Since I don't see a lot of activity around here I guess there must be a way to do it. I posted also a [question on SO](https://stackoverflow.com/questions/58558761/efficient-way-to-both-predict-and-evaluate-with-a-keras-model) to see if anything comes up.
