### ISSUE TITLE
Need a way to serialize Keras models abstractly -- not only to disk

### ISSUE THREAD

**Issue by vdods** [fchollet/keras#6794]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Currently serialization of a Keras model necessarily involves reading/writing it from/to disk as an HDF5 file.  I wasn't able to find any other Keras method or function that does this to an abstract IO stream (or for a more concrete example, serialize to a memory buffer).  A also looked at the h5py library which is used by Keras, and did not find any way to serialize to anything but a file.

My usecase is that I need to cache many types of data, including Keras models, in different places -- in memory, as well as a piece of data within a larger data structure or file.  Put concisely, I need more control over the serialization of Keras models -- not just "save to file XYZ" or "load from file XYZ".  I would be happy with a means to save/load a Keras model to/from a byte array, even if it was still in hdf5 format.  A reasonable alternative to hdf5 is protobuf.  

Also relevant: An analysis on why hdf5 isn't necessarily a good choice: http://cyrille.rossant.net/moving-away-hdf5/

**Comment by bstriner** [comment]
Nothing built-in but this should get you an array of numpy arrays you can do with as you need. Just pickle them or something should be fine. Use a generator instead of a list if you want to stream everything.

```python
#save
values = [K.get_value(w) for w in model.weights+opt.weights]
#load
for w,v in zip(model.weights+opt.weights, values):
  K.set_value(w, v) 
```

Cheers

**Comment by cockroachzl** [comment]
+1, I would like to cache the model in a distributed cache system and then load the model as a byte stream.

**Comment by enefem** [comment]
+1 as well. I would like to have this as well

**Comment by obi1kenobi** [comment]
Hi all, I opened #9789 to resolve this issue since I had the same problem and wanted to serialize the model to a byte stream without going to disk. Hopefully the maintainers are able to take a look at it soon!

**Comment by obi1kenobi** [comment]
#9789 just got merged, this should be solved now.
