### ISSUE TITLE
Slow convolutions due to not specifying filter and image sizes

### ISSUE THREAD

**Issue by simonzack** [fchollet/keras#680]
`T.nnet.conv.conv2d` supports filter and image shape optimizations, which is missed out on by `Convolution1D` and `Convolution2D`. My batch optimizations went from 1 minute to 3 minutes after using keras, and I think this is the only difference.

**Comment by fchollet** [comment]
I believe we used to have `image_shape` and `filter_shape` keyword args in `Convolution2D`. Not sure why they aren't around anymore. 

Feel free to submit a PR to reintroduce them if you are interested in that. A benchmark of some piece of code with/without setting these parameters would be welcome, to quantify the benefit of the optimizations being run.

**Comment by Smerity** [comment]
Good find @simonzack! I think this will also fix another issue where using stride with certain border modes results in `Exception: ConvOp.grad when dx!=1 or dy!=1 we must have all the optional shape information`.
