### ISSUE TITLE
Time-Series Regression analysis using LSTM in Keras

### ISSUE THREAD

**Issue by ammarsohail** [fchollet/keras#6803]
Hi there,
I am very new to Machine learning and Keras. I have a small task to predict the cost until recovery for each patient. My data contains record of 4000 patients with multiple weeks entries for each patient. for each week for a particular patient, there are 19 different services he can take that contain the number of times a service being taken and in last column we have cost incurred during that week.

So the input vector is of length 19 and output would be single value (cost until recovery). So for the first week, the output would be the sum of cost of all weeks for that patient. and for second week, the output would be cost of all weeks minus first week cost and so on.

Can anyone please help me how can I create LSTM model for this scenario? I mean would would be the layers and their parameters?

Many Thanks

**Comment by the-moliver** [comment]
This is not an issue, please close.
https://github.com/fchollet/keras#support

**Comment by ammarsohail** [comment]
Oh Okay. My mistake.
Many Thanks
