### ISSUE TITLE
how do i get running time of every layers separately

### ISSUE THREAD

**Issue by xzj6795365** [fchollet/keras#6805]
such as my net has one conv and one full-connecter layers, how do i know how much is the time each layer takes?

is there any API can do this?

**Comment by bstriner** [comment]
Not exactly. There is so much optimization and parallel stuff that has no exact meaning. It's like quantum physics. Running a timer at a low-level is going to change the timing.

That said, you can see what the impact of different layers are. Time your code as it exists now, and compare it to replacing layers with linear layers or removing them, and you can see what layers have the most impact.

In terms of actually testing it, try `timeit` to run `train_on_batch` or `predict_on_batch` a bunch of times.

Cheers

**Comment by xzj6795365** [comment]
thanks, bstriner
