### ISSUE TITLE
AttributeError: module 'keras.regularizers' has no attribute 'WeightRegularizer'

### ISSUE THREAD

**Issue by IvyGongoogle** [fchollet/keras#6813]
hello, when I use do `w_reg=keras.regularizers.WeightRegularizer(l1=0.,l2=0.)`, why it shows error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'keras.regularizers' has no attribute 'WeightRegularizer'

```
how to use `keras.regularizers.WeightRegularizer`?
can you give some advises? thank you very much~

**Comment by Flaac** [comment]
Not sure about what you want to do but if you want to add some L1/L2 regularization on your weights, you can use : 
```
keras.regularizers.l1(0.)
keras.regularizers.l2(0.)
keras.regularizers.l1_l2(0.)
```

The doc on the regularizers : https://keras.io/regularizers/

**Comment by IvyGongoogle** [comment]
@Flaac thank you.  I mean how to use `WeightRegularizer` of `keras.regularizers`?
can you give some advises?

**Comment by IvyGongoogle** [comment]
@Flaac  I can use this `WeightRegularizer` when I using keras1.2.2 
thank you very much!

**Comment by Flaac** [comment]
A pleasure ! :)
You might want to close the issue now (not sure about how to do that though)

**Comment by IvyGongoogle** [comment]
@Flaac Ok.
