### ISSUE TITLE
bad prediction with good training result

### ISSUE THREAD

**Issue by awenhu** [fchollet/keras#6836]
I'm using  exaples/imdb_cnn.py to train chinese dataset.
I got a good training result : 99%+, but got bad prediction: 53%+.
Don't understand why, any help?

**Comment by bxwhl** [comment]
can u give more details?

**Comment by awenhu** [comment]
import numpy as np
import re
import itertools
import codecs
from collections import Counter
import jieba
from tflearn.data_utils import to_categorical, pad_sequences, string_to_semi_redundant_sequences



def clean_str(string):
    """
    Tokenization/string cleaning for all datasets except for SST.
    Original taken from https://github.com/yoonkim/CNN_sentence/blob/master/process_data.py
    """
    string = re.sub(r"[^A-Za-z0-9(),!?\'\`]", " ", string)
    string = re.sub(r"\'s", " \'s", string)
    string = re.sub(r"\'ve", " \'ve", string)
    string = re.sub(r"n\'t", " n\'t", string)
    string = re.sub(r"\'re", " \'re", string)
    string = re.sub(r"\'d", " \'d", string)
    string = re.sub(r"\'ll", " \'ll", string)
    string = re.sub(r",", " , ", string)
    string = re.sub(r"!", " ! ", string)
    string = re.sub(r"\(", " \( ", string)
    string = re.sub(r"\)", " \) ", string)
    string = re.sub(r"\?", " \? ", string)
    string = re.sub(r"\s{2,}", " ", string)
    return string.strip().lower()

def isnum(s):
    try:
        float(s)
        return True
    except ValueError:
        return False
    
def passed(word):
    return len(word) >= 2 and not isnum(word)


def load_data_and_labels(posFile, negFile):
    """
    Loads MR polarity data from files, splits the data into words and generates labels.
    Returns split sentences and labels.
    """
    # Load data from files
    positive_examples = list(codecs.open(posFile, "r", "utf-8").readlines())
    positive_examples = [s.strip() for s in positive_examples]
    negative_examples = list(codecs.open(negFile, "r", "utf-8").readlines())
    negative_examples = [s.strip() for s in negative_examples]
    # Split by words
    x_text = positive_examples + negative_examples
    sentences = [list(filter(passed, jieba.cut(line, cut_all=False, HMM=True))) for line in x_text]
#     sentences = [list(s) for s in x_text]

    # x_text = [clean_str(sent) for sent in sentences]

    # Generate labels
    positive_labels = [0 for _ in positive_examples]
    negative_labels = [1 for _ in negative_examples]
    y = np.concatenate([positive_labels, negative_labels], 0)

    return [sentences, y]

def build_vocab(sentences):
    """
    Builds a vocabulary mapping from word to index based on the sentences.
    Returns vocabulary mapping and inverse vocabulary mapping.
    """
    # Build vocabulary
    word_counts = Counter(itertools.chain(*sentences))
    # Mapping from index to word
    vocabulary_inv = [x[0] for x in word_counts.most_common()]
    # Mapping from word to index
    vocabulary = {x: i for i, x in enumerate(vocabulary_inv)}
    return [vocabulary, vocabulary_inv]

def load_data(posFile, negFile):
    sentences, labels = load_data_and_labels(posFile, negFile)
    vocabulary, vocabulary_inv = build_vocab(sentences)
    x = list([[vocabulary[word] for word in sentence] for sentence in sentences])
    y = list(labels)
    return x, y, vocabulary, vocabulary_inv


x, y, vocabulary, vocabulary_inv = load_data(u"./data/chinese/pos.txt", u"./data/chinese/neg.txt")
vocabulary_size = len(vocabulary)

def split_test(x, y, num=1000):
    trainX = np.array(x[num:-num])
    testX = np.array(x[0:num] + x[-num:])
    trainY = np.array(y[num:-num])
    testY = np.array(y[0:num] + y[-num:])

#     print(type(trainX), trainX[:3], type(trainY), trainY[:3], type(testX), type(testY))

    trainX = pad_sequences(trainX, maxlen=400 )
    testX = pad_sequences(testX, maxlen=400)
    ## Converting labels to binary vectors
#     trainY = to_categorical(trainY, nb_classes=2)
#     testY = to_categorical(testY, nb_classes=2)

    return trainX, testX, trainY, testY

trainX, testX, trainY, testY = split_test(x, y)
print(type(trainX), trainX[:3], type(trainY), trainY[:3], type(testX), type(testY))
