### ISSUE TITLE
Error when checking VGG16 input shape with include_top=False

### ISSUE THREAD

**Issue by mptorr** [fchollet/keras#6849]
I'm trying to use Keras' implementation of VGG16 with grayscale images, channels first.
My training data is shaped as follows:

```
x_train shape: (7961, 1, 128, 128)
y_train shape: (7961, 1)
X_test shape: (1991, 1, 128, 128)
y_test shape: (1991, 1)
```

When I build my model:

```
model_vgg16 = VGG16(include_top=False, 
                        weights=None, 
                        input_tensor=None, 
                        input_shape=(1, 128, 128), 
                        pooling=None,
                        classes=CLASSES)
```

it throws this error:

```
File "/Library/.../keras/applications/vgg16.py", line 101, in VGG16
    include_top=include_top)
  File "/Library/.../keras/applications/imagenet_utils.py", line 116, in _obtain_input_shape
    '`input_shape=' + str(input_shape) + '`')
ValueError: The input must have 3 channels; got `input_shape=(1, 128, 128)`
```

This seems odd since I am using `include_top=False` and `weights=None` but it still seems to expect a 3 channel tensor and is passing my shape through `imagenet_utils.py`, which seems inflexible in allowing for anything < 3 channels (see `_obtain_input_shape`).

Is this desirable?

If I keep `input_shape=None` then I get a shape mismatch error at the beginning of training epoch 1.

Keras 2.0.4
Python 3.5

**Comment by emcenrue** [comment]
Although I do think that the flexibility is desirable, I just want to quickly point out for anyone else who reaches this thread what the argument, 'input_shape' specifies for vgg16:

`        input_shape: optional shape tuple, only to be specified
            if `include_top` is False (otherwise the input shape
            has to be `(224, 224, 3)` (with `channels_last` data format)
            or `(3, 224, 224)` (with `channels_first` data format).
            It should have exactly 3 input channels,
            and width and height should be no smaller than 48.
            E.g. `(200, 200, 3)` would be one valid value.`

**Comment by amwfarid** [comment]
I'm having the same problem, but on TF 1.10.0

This is my line of code:
`model = tf.keras.applications.VGG16(weights='imagenet',include_top=False,input_shape=(48,48,3))`

And I get this:

`ValueError: The input must have 3 channels; got `input_shape=(48, 48, 3)`

Maybe I missed something? I admit I kind of new to using TF. I also hope this is the right place to post about the issue (Because I am not using Keras library directly, but rather through TF integration)

**Comment by CosmoDroid** [comment]
@amwfarid As you have set `include_top=False`, you must have `input_shape=(3,48,48)`
