### ISSUE TITLE
model_from_yaml, reshape

### ISSUE THREAD

**Issue by matudor** [fchollet/keras#685]
I'm trying to load a model previously saved to a yaml file.
I'm getting following error.
```
__init__() got an unexpected keyword argument 'dims'
```
The only `dims` in the yaml is:
```
-  dims: !!python/tuple [500, 16]
   name: Reshape
```

This corresponds to a (Sequential) `model.add(Reshape(500,16))` in the original specification.  I notice two potential issues, one is lack of brackets around layer and lack of a comma between the `dims` and `name`, and the other is the *args interface of Reshape.  Not being familiar with yaml, I'm not sure if latter is a problem, but manually editing yaml to: 
```
- {dims: !!python/tuple [500, 16] , name: Reshape}
```
continues to give same error.

Suggestions?
Thanks!
M

**Comment by fchollet** [comment]
During loading the model will call `Reshape((500, 16))`. It should actually be calling `Reshape(500, 16)` or `Reshape(*(500, 16))`. 

You can fix it by modifying `Reshape`'s `__init__` in the following way:

```python
def __init__(self, *dims):
        super(Reshape, self).__init__()
        if type(dims[0]) == tuple:
            dims = dims[0]
        self.dims = dims
```
