### ISSUE TITLE
Reshape output of model as input of another model

### ISSUE THREAD

**Issue by SawyerW** [fchollet/keras#6851]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by SawyerW** [comment]
I am building a hierarchical lstm autoencoder model for documents. The model is trained from word to sentences then to document, finally, the process is reversed back. Now I have got the output of sentences vectors, and the shape is like (None, 8, 300) (every document has 8 sentences.). I want to reshape them as (None, 1,300), removing the timesteps，so the vectors will in words level. 
I am not meaning to set return_sequences, which can only convert 8 sentence vectors into one document vector in this situation. 
After reshaping to (None, 1,300), a repeatvector will be used to get word level vectors.
So my question is how to reshape the vectors from (None, 8, 300) to (None, 1, 300) ?

**Comment by maderafunk** [comment]
I'm pretty sure there must be a much nicer way to solve this, but this should work quick and dirty, inspired by [https://keras.io/layers/core/#lambda]() :


```
def change_td(x):
    index = 0 # index for which timestep should be selected
    x = x[:,index,:]
    return x

def change_output_shape(input_shape):
    shape = list(input_shape)
    del shape[1]
    return tuple(shape)

model_input = Input(shape=(8,300))

td1 = TimeDistributed(Dense(300,activation='relu'))(model_input)
td1 = Lambda(change_td,change_output_shape)(td1)
td2 = Dense(5,activation="softmax")(td1)

model = Model(inputs=[model_input], outputs=[td2])
```
I'm not sure how I could pass that index as an argument to the function. Again, quick and dirty would be to create a separate function for each index :///
