### ISSUE TITLE
How to reshape data for Statefull LSTM?

### ISSUE THREAD

**Issue by danil-z** [fchollet/keras#6855]
Hi folks, I read example https://github.com/fchollet/keras/blob/master/examples/stateful_lstm.py
and still confused how to change(reshape) my input shape so I could feed to stateful LSTM.

```
batch_size = 128
tsteps = 1

# X_train.shape = (107904, 10) 
# Y_train.shape = (107904, 2)
# 107904 % 128 == 0
# X_train and Y_train are both DataFrames

model = Sequential()
model.add(LSTM(50,
               input_shape=(tsteps, Y_train.shape[1]),
               batch_size=batch_size,
               return_sequences=True,
               stateful=True))
model.add(LSTM(50,
               return_sequences=False,
               stateful=True))
model.add(Dense(X_train.shape[1]))
model.compile(loss='mse', optimizer='rmsprop')

```

I'm getting error:

> ValueError: Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (107904, 10)

**Comment by prakritidev** [comment]
It needs 3 dimensions, the third dimension is the batch size I guess

**Comment by danil-z** [comment]
I understand it, but I don't understand how to convert it...Do i need use for loop for this of some chaining some helpers from numpy or something? Could you provide an example please.
