### ISSUE TITLE
Make each layer able to compute norms of their weights (see also #474)

### ISSUE THREAD

**Issue by ndronen** [fchollet/keras#686]
Related to #474.  In addition to changing each layer to know how to correctly constrain its parameters, it would be nice for each layer to know how to report the norms of its parameters as well.  This would make it easy for anyone to monitor norms reliably in custom callbacks.

**Comment by EderSantana** [comment]
You can do that with callbacks already. But I agree that the main repo could use a callback that goes through a list of params and log the norms.

**Comment by ndronen** [comment]
I agree you can do that with callbacks already.  The problem -- as #474 makes clear -- is that naively logging norms of the last dimension of parameter matrices from a callback will give the wrong results for both maxout and convolutional layers.  #474 is about each layer implementing norm constraints in an appropriate way.  This issue requests that each layer also implement a method that reports the norms of its parameters.

**Comment by EderSantana** [comment]
You mean "optionally", right? I don't believe we want to impose logging and go full pylearn2 here.

But yeah, I see what you mean now. A base method `get_norms` or something like that. It would return a dict of parameter names and norms. The Callback collects all the non-empty dicts and logs everything.

**Comment by ndronen** [comment]
Sure, optionally, but to be clear, I'm only asking for the layers to implement a method that returns the norms.  The rest can be handled in a callback.  I'm not even asking for the callback to be implemented.  I just want the library to be such that norms can be gotten reliably by any user, low-information or expert, without having to think about the shape of the parameters.  This would be easy to piggyback on #474, which will change each layer to apply norms constraints in a layer-specific way, once #474 is implemented.

I think my use of "report" instead of "return" might have mislead you.  Sorry.  Red herring.
