### ISSUE TITLE
model_from_json breaks if using custom function

### ISSUE THREAD

**Issue by andreRibeiro1989** [fchollet/keras#6864]
Hi,

Ok so I saved a model in json with a custom activation layer. The model_from_json works fine if the model is loaded on the same machine, yet if I attempt to port the model to a different machine the model_from_json breaks. 

If we look at the json file we see a pointer to the file that contains the custom function. Since we are on a new machine I changed the directory to point to the new file directory. This however does not work. 

For what I understand this is because the custom function is serialised in the json file and I guess something else needs to be changed besides the directory.

Any help to make this work?

**Comment by xinq2016** [comment]
yes, same issue occurs when I use my own active function when I load the model from a json file.
How can I fix it?

Many thanks

**Comment by subhashreeradhakrishnan** [comment]
Same issue here!
