### ISSUE TITLE
Get only green channel weights in a RBG model

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#6868]
Hi,

I have a model that classifies RGB images and it works well.

Now, I would like to use the same model on gray level images without re-training the new model. I could duplicate the gray level image in order to give it three identical channels, but it would use a excessive memory.
So I would like to load the RGB model and get only the weights of a single channel (green for example) that I would affect to my gray level model.

Any idea how I can access the weights of a given channel?

Regards,

**Comment by td2014** [comment]
I believe 
Model.get_weights()
Is the general access method.  From there you can extract the specific bumpy array.  Replace "Model" with whatever you call your model.  Hope that helps.

**Comment by FiReTiTi** [comment]
Hi, thanks for this answer, but I already know this function. What I don't know is using this function, how to target a specific channel.

**Comment by td2014** [comment]
No problem.  If I understand what you are asking, then I think you can target a specific channel (by index) if you select out the weights for a specific layer.  For example, if you want the weights from the input layer (say 2D convolution), you can say:  model.get_weights()[0].   This gives you all the weights.  If you want to select a specific channel, first you can do:  
model.get_weights()[0].shape to verify the arrangement.  
For example, if your 2D convolution filter has shape (5,5), and you are using 3 channels (RGB), and have 16 output filters, you might get shape = (5,5,3,16).  Then you should be able to extract the filter weights for a specific channel (by index), for example input channel 0:
model.get_weights()[0][:,:,0,:]

I hope this helps if you didn't already know this.

**Comment by FiReTiTi** [comment]
Thanks, I am going to test it right away.
