### ISSUE TITLE
predict_generator over a finite set of unknown size

### ISSUE THREAD

**Issue by jonilaserson** [fchollet/keras#6884]
I have a generator that covers a dataset of unkown size (although I can upper-bound it).

I'd like to predict over the entire dataset. `predict_generator` requires declaring the number of steps in advance. If your generator was depleted in the middle the prediction is aborted and you lose all the predictions and also the data the generator already covered.  

On the other hand if you get the batches one by one and just use "predict" your GPU will stand idle while the next batch is being pre-processed.

I guess you have to create your own multi-process queue, or is there a work-around?

**Comment by Dref360** [comment]
Do your own thing, mostly using predict with a try catch for StopIteration. You can dig into the code and start your own queue.

**Comment by jonilaserson** [comment]
Thanks!
