### ISSUE TITLE
How to pass a constant from 'fit' function?

### ISSUE THREAD

**Issue by GauravBh1010tt** [fchollet/keras#6885]
Hi. I am trying to pass a constant from the **fit** function that needs to be accessed by the keras model. 
Specifically, I have the WordNet dataset that has two entities along with a relation - <e1, rel, e2>. I am trying to implement [Neural Tensor Network](https://nlp.stanford.edu/pubs/SocherChenManningNg_NIPS2013.pdf) for knowledge base completion. For each relation, a separate neural tensor model (ntn_layer) needs to be initialized. This can be achieved as follows:
```python
inpx = Input(shape=(dimx,))
inpy = Input(shape=(dimy,))

''' problem in initializing the variable k which is to be passed from fit'''
#k = Input(shape=(1,))
#k = K.constant()

ntn = {}
for i in range(num_relations):
    ntn[i] = ntn_layer(inp_size=dimx,out_size=4)([inpx,inpy])
score = Dense(1,activation='tanh')(ntn[k])
model = Model([inpx,inpy,k],score)
```
Here, ntn[i] is the model's parameters for _ith_ relation. Ntn_layer is the neural tensor layer and is working fine for single relation dataset. In WordNet we have 11 relations, so I have divided the dataset relation-wise, that is I want only the _kth_ ntn parameters to be updated for _kth_ relation data. The fit function looks like this:
```python
for k in range(num_relations):
    for batch_id in range(num_batches[k]):
        e1,e2, labels_train = make_batches(k, batch_id)
        model.fit( [e1,e2,k], labels_train, nb_epoch=1, batch_size=100) 
''' passing only the _kth_ relation data along with the relation number _k_'''
```

**Comment by PiscesDream** [comment]
You should use `K.variable` or `K.placeholder` in the [abstract backend](https://keras.io/backend/#using-the-abstract-keras-backend-to-write-new-code).
