### ISSUE TITLE
Retrain last layers of VGG: CNMEM_STATUS_OUT_OF_MEMORY error

### ISSUE THREAD

**Issue by FiReTiTi** [fchollet/keras#6894]
Hi,

I wanted to retrain the fully connected layers of VGG 16 for big gray level images.
So I've:
 - created a new VGG with a single color channel and loaded the weights from of the original VGG.
 - add trainable=False to all the convolution layers
 - reduced the number of neurons in the dense layers in order to match my problem
 - increase drastically the max pooling dimensions and strides because I work with inputs 1800x1800 (no choice). But the dimensions drop very quickly to match the original VGG dimensions.

But when I start the training, I face a CNMEM_STATUS_OUT_OF_MEMORY error. 
I've tried to delete all the dense layers to keep only the output layers with two neurons, but stil the same problem.

Any idea how to fix it?

**Comment by bzhong2** [comment]
Maybe try smaller batch size? If you are running two programs at the same time, you can use the following to limit the GPU memory use: 
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.33
set_session(tf.Session(config=config))

**Comment by FiReTiTi** [comment]
I already use the minimum batch size. It's 3 in my case.
And unfortunately, I run only the training, nothing else :-(
