### ISSUE TITLE
How can we put Output on 1st convolution layer to input of 4th convolution layer?

### ISSUE THREAD

**Issue by ManishSahu53** [fchollet/keras#6908]
I have a simple deep learning model which has 7 layers. Now in the 4th convolution layer, I need input of 1st convolution layer but not of 3rd conv layer. I dont know how to do this in keras. Can someone tell me how to do this?

**Comment by Dref360** [comment]
Hi!
This question seems best suited for StackOverflow. Could you post your issue there? Also, remember to close your issue if you do so!
Thanks!

**Comment by kgrm** [comment]
Please refer to the functional API documentation and applications/resnet50.
