### ISSUE TITLE
different learning rates to different layers of a CNN.

### ISSUE THREAD

**Issue by sajabdoli** [fchollet/keras#6912]
Hi,
I wonder if there is a way to specify different learning rates to different layers of a CNN.
thanks

**Comment by souryadey** [comment]
I also have this question - can there be different learning rates for different network layers? Also, can weights and biases have different learning rates?

**Comment by sajabdoli** [comment]
hi 
could you please check this:
[https://github.com/nagash91/keras/commit/08d73ef7957fbe5f59099b9e2986d8165ee131e8]
I receive this error when I want to call Convolution1D:

TypeError: __init__() takes at least 3 arguments (1 given)

and here is the code:

inp = Input(shape=(94319,1))
conv1_coch= Convolution1D(filters=129, kernel_size=401)(inp)

**Comment by Dref360** [comment]
You could create your own optimizer where lr is a matrix and not a scalar.
https://github.com/fchollet/keras/blob/master/keras/optimizers.py#L133.

**Comment by souryadey** [comment]
Thanks @Dref360 I'll give it a try.
@sajabdoli Your link is not working for me.
