### ISSUE TITLE
Output masking exception when outputting sequences

### ISSUE THREAD

**Issue by brainwater** [fchollet/keras#693]
I get the error:

```
ERROR: test_graph_seq (test_loss_weighting.TestLossWeighting)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/blake/src/keras/tests/auto/test_loss_weighting.py", line 162, in test_graph_seq
    model.fit(data, nb_epoch=1, batch_size=2, verbose=1, sample_weight=masks)
  File "/home/blake/src/keras/env/lib/python3.4/site-packages/keras/models.py", line 678, in fit
    shuffle=shuffle, metrics=metrics)
  File "/home/blake/src/keras/env/lib/python3.4/site-packages/keras/models.py", line 211, in _fit
    outs = f(*ins_batch)
  File "/home/blake/src/keras/env/lib/python3.4/site-packages/theano/compile/function_module.py", line 513, in __call__
    allow_downcast=s.allow_downcast)
  File "/home/blake/src/keras/env/lib/python3.4/site-packages/theano/tensor/type.py", line 169, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/home/blake/src/keras/env/lib/python3.4/site-packages/keras/models.py:616"  at index 2(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (2, 4).')
```

when attempting to use output masking when outputting sequences. Either I'm doing something wrong, or there's a bug. I have created unit tests that exposes this issue in https://github.com/brainwater/keras/tree/outmasktest 
n.b. This happens in both python 2 and python 3

It can be run with:
`$ python -m unittest test_loss_weighting.TestLossWeighting.test_graph_seq`
or
`$ python -m unittest test_loss_weighting.TestLossWeighting.test_sequential_seq`

**Comment by tttwwy** [comment]
Was it be fixed?

**Comment by brainwater** [comment]
I think this works if one just makes each weight a list of length 1, e.g. for the sample weights for my example tests:
-            'output': [[1.,1.,1.,1.],
-                       [1.,1.,0.,0.]],
+            'output': [[[1.],[1.],[1.],[1.]],
+                        [[1.],[1.],[0.],[0.]]],
Which seems like a bug to me, but this may be the intended behavior.

**Comment by tangjie77wd** [comment]
Hi,guys! @brainwater @tttwwy @bmabey @jfsantos @kashif 
Would you help me to solve this problem when I was getting the feature of Flatten layer.#431 Any help will be much appreciate!
