### ISSUE TITLE
Pack detection 

### ISSUE THREAD

**Issue by MicBA** [fchollet/keras#6943]
Hi everyone.. 
in most of the paper i got cross by, all the problems they try to solve is 
detection of an object and classify it.. 
in my case i have problem that's little bit more complex 
I need to find object and in some cases if there are many from it in some shape it gate different class 

you can think of it as to find a bird in the sky and if there are many it's not bird any more but pack of birds.. 
and depend on the shape they fly we have different classes 
and there can be more then one pack that fly together so there can be overlap 

has someone here got any idea how to approach this ? 
or can point me to some paper.. 

i'm trying now google SSD.. the result are not the best as i hope 
(SSD know to find the same object in several sizes.. but not change the class if there are many is specific shape, so in case of packs the network result is also the birds that combine )

Thanks for the help!
Michael

**Comment by Dref360** [comment]
Hi!
This question seems best suited for StackOverflow. Could you post your issue there? Also, remember to close your issue if you do so!
Thanks!
