### ISSUE TITLE
Two input of one layer?

### ISSUE THREAD

**Issue by Imorton-zd** [fchollet/keras#6944]
I want to add the other input of one layer, as following:
![2](https://user-images.githubusercontent.com/13865086/27011748-383e09f8-4ef5-11e7-8417-2a8e240363bc.png)

Apart from w_t, I also want to add the y of each step in c_t. How can I modify the layer? Any opinions would be appreciated!

**Comment by vrishank97** [comment]
Keras supports multiple inputs for a single layer.
Check this out - https://github.com/bradleypallen/keras-quora-question-pairs

**Comment by Imorton-zd** [comment]
@vrishank97 Thanks for your reply. In fact, the issue you mentioned does't solve my question, that issue only use `merge` method to solve that problem. But my question in this issue can not use `merge` method to process. Although I can use the `attention_lstm` class @codekansas proposed to implement the special `LSTM` layer adding the `y` term via some modification we name that `ConLSTM`, as following:
`lstm = ConLSTM(output_dim, y)(input)`
However, I can not share this type of layer. For example, I have two datasets, which have input and y respectively. I want to share the same layer (called `ConLSTM2` for discrimination) with these two datasets, like following:
```
lstm = ConLSTM2(output)
out1 = lstm([input1, y1])
out2 = lstm([input2, y2])
```
The special `LSTM` layer adding the `y` term via the formulas above on the picture.
