### ISSUE TITLE
Tutorial Install anaconda, theano, keras, CUDA, CUDNN in windows10 64 with NEW GPU

### ISSUE THREAD

**Issue by dycasxe101** [fchollet/keras#6946]
Hiiiiii........

First of all, I want to let you know I have installed anaconda, theano, keras, cuda and it works. so charming.

But after the new gpu appears, I change the configuration according to the tutorial. And it did not work.
I have reinstalled, and no longer work like before. Three days I've been following most of comments on stackoverflow and github, but it still does not work

Is anyone willing to help me just by making a tutorial with NEW GPU?

Please, i need help u

**Comment by Dref360** [comment]
Hi!
This question seems best suited for StackOverflow. Could you post your issue there? Also, remember to close your issue if you do so!
Thanks!

**Comment by dycasxe101** [comment]
i no have permission to post it in there, sorry.

if u know the answer  for my problem, please help me
