### ISSUE TITLE
What is the purpose of "shuffle" in fitting?

### ISSUE THREAD

**Issue by einareinarsson** [fchollet/keras#6955]
I cannot entirely understand the importance of the `shuffle` parameter in case of model fitting, especially when it is set to `False`. Could you kindly enlighten me?

**Comment by Dref360** [comment]
If your datas is highly correlated. (Every class in order for example) Then you need to shuffle or your training will be bad. But if your dataset is already shuffled, then setting it to False is logical.

**Comment by vrishank97** [comment]
You want your model to understand all inputs equally, if classes are in order the model will have a higher accuracy for the last class it trains on than the first.
