### ISSUE TITLE
Keras load_from_json JsonError

### ISSUE THREAD

**Issue by GitLele92** [fchollet/keras#6971]
I'm loading a net architecture from a json, here is the json:
`
{
   "backend":"tensorflow",
   "keras_version":"2.0.3",
   "config":[
      {
         "config":{
            "batch_input_shape":[
               null,
               6,
               6,
               9
            ],
            "kernel_constraint":null,
            "name":"dense_1",
            "dtype":"float32",
            "units":24,
            "bias_constraint":null,
            "kernel_initializer":{
               "config":{
                  "scale":1.0,
                  "distribution":"uniform",
                  "mode":"fan_avg",
                  "seed":null
               },
               "class_name":"VarianceScaling"
            },
            "use_bias":true,
            "kernel_regularizer":null,
            "bias_regularizer":null,
            "activation":"relu",
            "trainable":true,
            "bias_initializer":{
               "config":{

               },
               "class_name":"Zeros"
            },
            "activity_regularizer":null
         },
         "class_name":"Dense"
      },
      {
         "config":{
            "rate":0.25,
            "name":"dropout_1",
            "trainable":true
         },
         "class_name":"Dropout"
      },
      {
         "config":{
            "kernel_constraint":null,
            "name":"dense_2",
            "units":24,
            "bias_constraint":null,
            "kernel_initializer":{
               "config":{
                  "scale":1.0,
                  "distribution":"uniform",
                  "mode":"fan_avg",
                  "seed":null
               },
               "class_name":"VarianceScaling"
            },
            "use_bias":true,
            "kernel_regularizer":null,
            "bias_regularizer":null,
            "activation":"relu",
            "trainable":true,
            "bias_initializer":{
               "config":{

               },
               "class_name":"Zeros"
            },
            "activity_regularizer":null
         },
         "class_name":"Dense"
      },
      {
         "config":{
            "rate":0.5,
            "name":"dropout_2",
            "trainable":true
         },
         "class_name":"Dropout"
      },
      {
         "config":{
            "name":"flatten_1",
            "trainable":true
         },
         "class_name":"Flatten"
      },
      {
         "config":{
            "kernel_constraint":null,
            "name":"dense_3",
            "units":1,
            "bias_constraint":null,
            "kernel_initializer":{
               "config":{
                  "scale":1.0,
                  "distribution":"uniform",
                  "mode":"fan_avg",
                  "seed":null
               },
               "class_name":"VarianceScaling"
            },
            "use_bias":true,
            "kernel_regularizer":null,
            "bias_regularizer":null,
            "activation":"sigmoid",
            "trainable":true,
            "bias_initializer":{
               "config":{

               },
               "class_name":"Zeros"
            },
            "activity_regularizer":null
         },
         "class_name":"Dense"
      }
   ],
   "class_name":"Sequential"
}
`

and this is the error:
Traceback (most recent call last):
  File "D:\workspace2\NN\src\ModelLoader.py", line 19, in <module>
    model2 = model_from_json('ModelNoComp2Dense24Nueuroni.json')
  File "C:\Users\emanuele\python3.5\lib\site-packages\keras-2.0.3-py3.5.egg\keras\models.py", line 332, in model_from_json
    config = json.loads(json_string.encode().decode())
  File "C:\Users\emanuele\python3.5\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\emanuele\python3.5\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\emanuele\python3.5\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

i'm loading the model with:

model2 = model_from_json('ModelNoComp2Dense24Nueuroni.json')

**Comment by vladimircape** [comment]
I think it's not keras issue, check by other python application if structure of you JSON in correct format .
as you see error comes not from keras
"File "C:\Users\emanuele\python3.5\lib\json\decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

**Comment by ricardobarroslourenco** [comment]
I've got this same issue when trying to load the architecture using `model_from_json`. Were you able to solve this issue @GitLele92 ?

**Comment by harpalsahota** [comment]
I had the same issue and came up with the following workaround:

```python
import json

from keras.models import model_from_json

with open(model_architecture, 'r') as json_file:
    architecture = json.load(json_file)
    model = model_from_json(architecture)
```

**Comment by Kizer2** [comment]
@harpalsahota I had to read the file and then do `model = model_from_json(json.dumps(architecture))` to get it to work...

**Comment by WVmf** [comment]
For anyone who ends up here due to the `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` issue (as I did): The `model_from_json()` method expects a JSON string as its first parameter, not the name of a JSON file.
So the following worked for me:
```py
import json
from keras.models import model_from_json

with open('model_architecture.json', 'r') as json_file:
    model = model_from_json(json_file.read())
```
