### ISSUE TITLE
Has an NTM actually been built in keras?

### ISSUE THREAD

**Issue by lahwran** [fchollet/keras#699]
On the home page of the documentation, there is a claim that "...Building ... a Neural Turing Machine ... is just as fast". This doesn't sound implausible, but I didn't think anyone had successfully reproduced the results from the NTM paper; does anyone know if this is referring to a specific NTM implementation, and if so, how well that implementation worked?

from http://keras.io/

**Comment by fchollet** [comment]
Maybe not, but how hard would it be? Just use a `Graph` container.

This specific sentence in the doc is meant to draw attention to the fact that arbitrary directed acyclic graphs are supported (such as NTMs), not just Sequential models.

**Comment by lahwran** [comment]
fair enough. In that case, it seems worth testing.
