### ISSUE TITLE
Large Data ImageDataGenerator MemoryError

### ISSUE THREAD

**Issue by a-ozbek** [fchollet/keras#6994]
I get a memory error while using `ImageDataGenerator.fit(X)` since `X` is large. 

`x = np.copy(x)` is causing the memory error since it is a heavy operation.
https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py#L653

`x = np.copy(x)` seems unnecessary here if `augment` is `False` and 
- self.featurewise_center
- self.featurewise_std_normalization
- self.zca_whitening

are all `False`

**Comment by zkself** [comment]
Hi,if i just want to use zca_whitening,how to handle the memoey error?

**Comment by emoen** [comment]
I also have same error - trying to use zca_whitening
