### ISSUE TITLE
Issues loading sub-modules

### ISSUE THREAD

**Issue by simonhughes22** [fchollet/keras#7]
First of, great work, I've been looking for something like this for a while now, powerful yet simple to use.

I am trying to import the keras from outside the module. I added the parent folder to my PYTHONPATH variable, but when I run the scripts, i'm getting errors loading the modules below the root:

e.g.
/Users/simon.hughes/GitHub/keras/activations.py in <module>()
     24     return x
     25 
---> 26 from utils.generic_utils import get_from_module
     27 def get(identifier):
     28     return get_from_module(identifier, globals(), 'activation function')

ImportError: No module named generic_utils

I've tried adding some of the subfolders to the python path:

sys.path.insert(0, "/Users/simon.hughes/GitHub")
sys.path.insert(0, "/Users/simon.hughes/GitHub/keras")
sys.path.insert(0, "/Users/simon.hughes/GitHub/keras/utils")

But that prevents loading modules like utils.generic_utils. It sees generic_utils as a module, but not utils.generic_utils.

Would it be possible to create a setup.py script to install an egg file? Or is there something simple I can do to make this work? The only way i can run code successfully is from the examples folder.

**Comment by fchollet** [comment]
I have added a setup.py. Hopefully this solves your issue : )

**Comment by simonhughes22** [comment]
Yes thanks!
