### ISSUE TITLE
Batch Embedding

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#70]
Not sure of this is how it's to work or not (seems to be a Theano issue) but Embedding layers do not work in batch mode. They work fine as first layers in recurrent net builds or for batch size =1 in pure feedforward ones but setting the batch size to 16 with an embedding layer included yields the following error:

ValueError: Input dimension mis-match. (input[0].shape[1] = 1, input[2].shape[1] = 16)
Apply node that caused the error: Elemwise{Composite{((i0 + i1) - i2)}}[(0, 0)](Reshape{3}.0, InplaceDimShuffle{x,x,0}.0, InplaceDimShuffle{x,0,1}.0)
Inputs types: [TensorType(float64, 3D), TensorType(float64, (True, True, False)), TensorType(float64, (True, False, False))]
Inputs shapes: [(16, 1, 1), (1, 1, 1), (1, 16, 1)]
Inputs strides: [(8, 8, 8), (8, 8, 8), (128, 8, 8)]
Inputs values: ['not shown', array([[[ 0.]]]), 'not shown']

**Comment by fchollet** [comment]
Embedding layers work fine with batches (see the imdb_lstm.py example, where batch_size=16). Can you post your model and explain what you were trying to do?

**Comment by lemuriandezapada** [comment]
Sorry I'm new to this whole reporting thing, so please bear with me :)
I already changed the code I reported here to something else, but if you go to the imdb_lstm.py example and replace:

model.add(LSTM(256, 128)) 

with 

model.add(Dense(256, 128)) 

you get this error, with batch sizes that are not equal to the second dimension of the dataset. Maybe I'm wrong but removing recurrency shouldn't affect the model's functionality so much.

However, if you also replace:

model.add(Embedding(max_features, 256))

with

model.add(Dense(X_train.shape[1], 256))

then it runs. So I suspect it's something about how this embedding layer indexes the vectors. Ideas?

**Comment by lemuriandezapada** [comment]
Nevermind, I figured it out eventually: moving from embedding/feedforward/recurrent requires a lot of reshape and flatten inbetween.
