### ISSUE TITLE
Biases for LSTM and GRU forget gates

### ISSUE THREAD

**Issue by jpeg729** [fchollet/keras#7028]
The standard implementation of LSTM and GRU initialises the biases to zero.

The referenced literature [Supervised sequence labeling with recurrent neural networks](https://pdfs.semanticscholar.org/1154/0131eae85b2e11d53df7f1360eeb6476e7f4.pdf) states that forget gate biases should be set to something positive and input gate biases should be set to something negative. However Keras doesn't provide an easy way to do it.

The rationale is that the network shouldn't forget past information until it has learnt to forget it, and that it shouldn't bring in new info unless it has learnt that it is good to add new info to its internal state. While that seems sensible I have little idea whether it is useful in practice.

The simplest solution would be to add default bias initializers to LSTM and GRU that set the forget biases to 1, the other gate biases to -1, and any other biases to 0?

If the idea seems good to you, I'll prepare a pull request.

**Comment by tastyminerals** [comment]
[This paper ](http://proceedings.mlr.press/v37/jozefowicz15.pdf)also shows how positive LSTM bias helps to improve the network performance.

**Comment by bzamecnik** [comment]
FYI: It's been already implemented on 20 Apr 2017 in https://github.com/keras-team/keras/commit/47350dc6078053403c59e8da3fd63ac3ae12b5ec.

From LSTM docs:

> `unit_forget_bias: Boolean`. If `True`, add 1 to the bias of the forget gate at initialization. Use in combination with `bias_initializer="zeros"`. This is recommended in [Jozefowicz et al.](http://www.jmlr.org/proceedings/papers/v37/jozefowicz15.pdf)

**Comment by jpeg729** [comment]
Wow. I missed that! It was already implemented when I posted this issue and nobody noticed.
Thanks for pointing it out.
