### ISSUE TITLE
Models zoo

### ISSUE THREAD

**Issue by rodrigob** [fchollet/keras#703]
Mentioned in the "mega-issue" #100, though it would be worth having a separate one.

The simplest model zoo is a github wiki page, another option it to have it as a page in the documentation and receive updates via push requests.

I think model zoo matters most for models that take "more 6 hours to train" (i.e. a large fraction of 24h).

**Comment by fchollet** [comment]
For now we have one VGG net ;-) https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3

In the near future I hope we will be able to load arbitrary Caffe models, which would give us access to the Caffe model zoo.

**Comment by albertomontesg** [comment]
Hello,

Working with Keras what I have missed has been some trained model, so taking the VGG net you previously share and a model that I [manually ported](https://gist.github.com/albertomontesg/d8b21a179c1e6cca0480ebdf292c34d2) from [C3D](https://github.com/facebook/C3D) (Caffe's fork that allow 3D convolution), I created a repository and some contribution guidelines to share between the community trained models for Keras.

I invite you to share your models on the repository:
https://github.com/albertomontesg/keras-model-zoo

Thanks,

**Comment by fchollet** [comment]
Closing this old issue. The Keras model zoo is the applications module: https://keras.io/applications/
