### ISSUE TITLE
Can i Implement a custom pooling function

### ISSUE THREAD

**Issue by beebrain** [fchollet/keras#7045]
I  implement a convolution neural network on Keras with Theano backend. And I want to change pooling function to RMS (Root Mean Square) function.

How to change a pooling function to custom function?

**Comment by td2014** [comment]
Hi.  If this is just for your own use, I can suggest the following:  Make a copy of the "pooling.py" file in your local python directory, and rename it to something like "custom_pooling.py" . It will have all the needed module imports - check in this link: https://github.com/fchollet/keras/tree/master/keras/layers
  Then, select the pooling class that is closest to what you want to implement and rename it to 
"class RMS_Pooling1D(Layer):" etc.  When you are ready, just import this class like any other layer.  I created my own layer in a similar way.  I hope this helps.  Thanks.

**Comment by EliasHasle** [comment]
Maybe I misunderstand, but can't RMS pooling be implemented as square -> avg. pool -> sqrt ?
