### ISSUE TITLE
Sequence classification from vectors

### ISSUE THREAD

**Issue by vicmak** [fchollet/keras#7052]
Hi!

I try to implement a sequence classification.
Each instance is a numpy array of numpy arrays. That is, an array having 60 vectors, each with 50 dimensions. All the instances reside in another numpy array - xx.

I initialize my model as following: 

    model = Sequential()
    model.add(LSTM(50, input_shape=(50,60), return_sequences=False))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.fit(xx, yy, epochs=4, batch_size=5)

but get the following error:

ValueError: Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (44, 1)

44 is the number of instances.

Where am I wrong?

Note that the vectors are not embeddings of any kind :-) but rather measurements I want to use as features.

Thanks ahead!
Victor.

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [X ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [X ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by rravu3** [comment]
A couple of issues:-
1) XX needs to be a 3D tensor of shape [n_training_datapoints, sequence_length, features_per_index/time].
2) Also, each individual sequence has to be of shape (50, 60) based on your model. 50 * 60 matrix per example. If the sequence size is less than 50, either change the input shape or pad the sequence.

Hope this helps.

**Comment by vicmak** [comment]
Thank you for the answer @rravu3 
Sorry for the ignorance, but what is 3D tensor? XX now is a list of lists of lists, 3D-list if i may, having the same dimensions like you specified.  The first list has number of elements like number of instances, the second list is of length sequence_length and stores the features per values, and the third most inner list stores the features per time. 

How do I convert such a 3D list into a 3D tensor with matrix inside?

Thank you so much!

**Comment by rravu3** [comment]
ND Array/Tensor are the same. Just create an ndarray by calling numpy.array(XX) and you should be able to pass that into the fit function.

**Comment by vicmak** [comment]
Actually this was the first thing I tried.
It doesn't work :-(
I am trying now to initialize an empty numpy array and fit the values one-by-one:

numpy.empty((instances_number,sequence_length,features_number))
