### ISSUE TITLE
unexpected initialization of tensorflow variables in `Model.save()`

### ISSUE THREAD

**Issue by cocuh** [fchollet/keras#7081]
Tensorflow variables which is not used in model are initialized when `model.save()` is called.

```python
def unexpected_initialization():
    sess = tf.Session()
    K.set_session(sess)

    var_global_step = tf.Variable(0, trainable=False)

    x = L.Input((8,))
    y = L.Dense(2)(x)
    model = Model(x, y)

    sess.run(tf.global_variables_initializer())

    step_initial = sess.run(var_global_step)
    print(' initial step: {}'.format(step_initial)) # -> outputs 0

    sess.run(var_global_step.assign(16))

    step_assigned = sess.run(var_global_step)
    print('assigned step: {}'.format(step_assigned)) # -> outputs 16 

    model.save('model.h5')

    step_saved = sess.run(var_global_step)
    print('   saved step: {}'.format(step_saved)) # -> outputs 0 !!!!!! expected 16
```

If the model have no layers, this unexpected initialization is not occurred.  (See [my gist](https://gist.github.com/cocuh/148a8b87f9693508d9b9d2a95efe1b61))

I sought cause of this bug, but I didn't find it....

Note: This keras and tensorflow combination technique is introduced in [official keras blog](https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html). So I think this code is not tricky, and keras should fix this bug.

**Comment by partus** [comment]
have the same issue, @cocuh did you find a solution?
