### ISSUE TITLE
Not fully connected CNN

### ISSUE THREAD

**Issue by ElizabethSvit** [fchollet/keras#7082]
Hi everybody!

I am trying to build an architecture of a convolutional network for image denoising as in pic below using keras with tensorflow backend. It's written that "in layers 2, 3, and 4, each feature map is connected to 8 randomly chosen feature maps in the previous layer." 

So I was wondering if there is a way to use only some random number of filters out of all for applying them to feature maps on each convolutional step? I suppose, Conv2D layer in keras by default passes all feature maps from previous layer to all nodes (filters).

Thanks in advance!
![screen shot 2017-06-21 at 20 58 38](https://user-images.githubusercontent.com/9437376/27399207-b26e3712-56c4-11e7-806f-8c86b3c0112e.png)

**Comment by christiantinauer** [comment]
Hi,

> I suppose, Conv2D layer in keras by default passes all feature maps from previous layer to all nodes (filters).

You are right. As a solution I can think of writing your own layer (maybe based on Conv2D), where you overwrite the **call** function and do a loop over output filters length and in the loop call the conv2d of the backend for each "package". After that you combine the packages to the final result.

The drawback is somehow tha you have to split the input image of the layer several times (for each kernel) and join the results back together. I am not sure if this is the best way to go, but maybe a idea you could start from.
