### ISSUE TITLE
Autocancelation

### ISSUE THREAD

**Issue by bstriner** [fchollet/keras#7089]
@fchollet can you enable autocancelation on Travis? Haven't tested it out myself but it should cancel redundant builds (for example, if you push twice to a pr). I don't think it is enabled now but I could be wrong.

https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

Travis seems to be doing a lot of work recently, especially with the new backend. Could help to cut back a little bit.

Cheers

**Comment by fchollet** [comment]
Done, thanks for the heads up.
