### ISSUE TITLE
Can the output of a layer be treated as the index of another layer's output?

### ISSUE THREAD

**Issue by NancyZxll** [fchollet/keras#709]
Dear all,
     I would like to use the output of a layer as the index of another layer's output.
    Such as:
```
inputs = [self.layers[i].get_output(train) for i in range(len(self.layers))] 
aa=inputs[1]
index=T.cast(inputs[0],'int64')
return aa[index]
```
Actually, the inputs[0] is the return value of the layer A, which:
```
return T.nonzero(the inputs of layerA,axis=0)
```

I get the error:
TypeError: AdvancedSubtensor1.grad illegally  returned an integer-valued variable. (Input index 0, dtype int64)

I have upgraded my theano to the developing version.
If I don't cast the inputs[0] to int manually, the error would be: "index must be integers".

How can I solve this problem?

Thanks a LOT!!

**Comment by fchollet** [comment]
I do not believe that is possible with Theano (or any other symbolic computation framework). 

However you can almost certainly find a workaround to achieve what you wanted to do via pure linear algebra. Consider a tensor multiplication-based gating mechanism.

**Comment by NancyZxll** [comment]
Thank you, I will look into the multiplication-based gating mechanism soon.
