### ISSUE TITLE
attribute error when inheriting from Sequential

### ISSUE THREAD

**Issue by simonm3** [fchollet/keras#7096]
Using keras 2 this works fine:
```
from keras.models import Sequential
model = Sequential()
model.add(Dense(4096, activation='relu', input_shape=(3,3,3)))
model.summary()
```
However when I try to inherit from Sequential it fails with "AttributeError: 'Sequential2' object has no attribute 'nodes_by_depth'":
```
class Sequential2(Sequential):
    pass
model2 = Sequential2()
model2.add(Dense(4096, activation='relu', input_shape=(3,3,3)))
model2.summary()
```
I note that Sequential.__init__ does not call the parent __init__. However if that were the problem I am not sure why the first version works. I note also that if I insert a self.build() after the add then it seems to work though not sure if that just causes other problems.

**Comment by AlexanderMath** [comment]
I got the same error with keras 2.2 tf-gpu 1.11 using the code below: 

```
# PRODUCES ERROR
class SequentialChild(Sequential):  
	def new_function(self):	print("test new functionality")
	
model = SequentialChild()
model.add(Dense(10))
model.new_function()
model.predict(np.random.normal(0, 1, size=(1, 10)))
```

I found a rather nasty work-around, If I name the new subclass Sequential I do not get an error (see code below). This is a long way from ideal, but it might give an idea as to what is causing the error. I also tried copying the entire source code for the Sequential class from [1] into a new file. If I change the name to anything else than Sequential (and the subsequent super calls to also include the new name) I get the same error.  

```
# WORKS
class Sequential(Sequential):  
	def new_function(self):	print("test new functionality")
	
model = Sequential()
model.add(Dense(10))
model.new_function()
model.predict(np.random.normal(0, 1, size=(1, 10)))
```

[1] https://github.com/keras-team/keras/blob/master/keras/engine/sequential.py
