### ISSUE TITLE
Updating examples

### ISSUE THREAD

**Issue by nishnik** [fchollet/keras#7097]
We need to update examples, like:
[here](https://github.com/fchollet/keras/blob/master/examples/mnist_mlp.py#L52) `nb_epoch` should be used. 
Similarly at:
https://github.com/fchollet/keras/blob/master/examples/antirectifier.py#L102
https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py#L100
and few other places.

Also [this](https://github.com/fchollet/keras/blob/master/examples/mnist_mlp.py#L34) should be `keras.utils.np_utils.to_categorical`

I can send a PR for this.

**Comment by fchollet** [comment]
The examples are using the Keras 2 API. What you are referring to used to be the Keras 1 API.
