### ISSUE TITLE
Possible bug with tensor outputs

### ISSUE THREAD

**Issue by EderSantana** [fchollet/keras#710]
I wrote the following cost function:

``` python
def cost_function(y_true, y_pred):
    leng = (y_true.shape[1]-1) / 2
    ytrue = y_true[:, -leng:, :]
    ypred = y_pred[:, -leng:, :]
    return binary_crossentropy(ytrue, ypred)
```

But Keras said

```
ValueError: The index list is longer (size 3) than the number of dimensions
of the tensor(namely 2). You are asking for a dimension of the tensor that
does not exist! You might need to use dimshuffle to add extra dimension to your tensor.
```

But I am pretty sure my model outputs a `T.tensor3`. The compiled output does have 3 dimensions. Where did the third dimension go? I tried to read the `compile` method but I had no clue. Have you experienced that before @fchollet ??? Am I missing something here?

**Comment by EderSantana** [comment]
I found this: https://github.com/fchollet/keras/blob/master/keras/models.py#L90
But why? T_T

**Comment by fchollet** [comment]
Yes, basically `y_true` and `y_pred` are reshaped to 2D before loss computation. You can use another reshape inside your custom loss function to recover the original shapes.

Preserving shapes would definitely be more elegant, so if you can figure out how to make the existing loss masking/weighting system work without the reshape, feel free to send a PR : )

**Comment by EderSantana** [comment]
I believe the reshape can go inside the cost functions like `y_true.flatten(ndim=2)` and then you apply the packaged objective. I'll check this out later.

But for now I'm having trouble dealing with inputs with different lengths in theano... That `leng` I mentioned above won't work if the inputs have different time lengths... I'll have to format everything before hand :(
