### ISSUE TITLE
Neural Architecture Search

### ISSUE THREAD

**Issue by edmondja** [fchollet/keras#7103]
Is there any chance to be able to implement a self made Neural Architecture Search (RNN part) one day ?
Because looking at Keras' limitations (https://github.com/fchollet/keras/issues/4112) it seems that it will not be possible for a very long time.

Regards.

**Comment by titu1994** [comment]
I have a more or less working implementation which fuses Keras to build the generator models and Tensorflow directly to train the RNN Controller.

https://github.com/titu1994/neural-architecture-search

I can't guarantee strict adherence to the original papers though.
