### ISSUE TITLE
 probot-stale closing issues without option to reopen them

### ISSUE THREAD

**Issue by eyaler** [fchollet/keras#7104]
probot-stale is closing issues, which took hard work to find and time to report, although these issues are still relevant. there is no possibility to reopen the closed issues. should i create new issues for these cases?

**Comment by eyaler** [comment]
please reopen the following issues:
https://github.com/fchollet/keras/issues/4186#event-1135527675
https://github.com/fchollet/keras/issues/4135#event-1135527132
https://github.com/fchollet/keras/issues/1814#event-1135658082
https://github.com/fchollet/keras/issues/4203#event-1135659745
https://github.com/fchollet/keras/issues/4188#event-1135706167
https://github.com/fchollet/keras/issues/1950#event-1135522721

**Comment by ahundt** [comment]
Yeah create a new one linking the old one for now. I was hoping 30 days notice was enough haha.

On the plus side these will be easier to find because 1k+ other truly stale issues are closed now :-)

**Comment by eyaler** [comment]
i only got notice for 2-3 other bugs. didn't get any notice for the above

**Comment by ahundt** [comment]
Ah that must have been before I added the notice string. Sorry about that! It is already fixed so there should be notice for all future messages.

**Comment by mands** [comment]
still active
