### ISSUE TITLE
ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[1] == 1, but the output's size on that axis is 10.

### ISSUE THREAD

**Issue by lfwin** [fchollet/keras#711]
I just install keras and try an example:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.optimizers import SGD
from keras.datasets import cifar100
#from read_data import get_CIFAR10_data_original

(X_train, y_train), (X_test, y_test) = cifar100.load_data(label_mode='fine')

#datasets = get_CIFAR10_data_original() # 3*32*32

#train_set_x, train_set_y = datasets[0]
#valid_set_x, valid_set_y = datasets[1]
#test_set_x, test_set_y = datasets[2]

model = Sequential()
model.add(Convolution2D(32, 3, 3, 3, border_mode='full')) 
model.add(Activation('relu'))
model.add(Convolution2D(32, 32, 3, 3))
model.add(Activation('relu'))
model.add(MaxPooling2D(poolsize=(2, 2)))
model.add(Dropout(0.25))

model.add(Convolution2D(64, 32, 3, 3, border_mode='full')) 
model.add(Activation('relu'))
model.add(Convolution2D(64, 64, 3, 3)) 
model.add(Activation('relu'))
model.add(MaxPooling2D(poolsize=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(64*8*8, 256))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(256, 10))
model.add(Activation('softmax'))

sgd = SGD(lr=0.1, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd)

model.fit(X_train, y_train, batch_size=64, nb_epoch=5, verbose=2, show_accuracy=True)

I got the error like this:
Epoch 0
Traceback (most recent call last):
  File "/home/mvg/workspace/CIFAR_10/test_keras/test_keras.py", line 43, in <module>
    model.fit(X_train, y_train, batch_size=64, nb_epoch=5, verbose=2, show_accuracy=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 490, in fit
    shuffle=shuffle, metrics=metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 211, in _fit
    outs = f(*ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 618, in __call__
    storage_map=self.fn.storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 297, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 607, in __call__
    outputs = self.fn()
ValueError: GpuElemwise. Input dimension mis-match. Input 1 (indices start at 0) has shape[1] == 1, but the output's size on that axis is 10.
Apply node that caused the error: GpuElemwise{Composite{(i0 * ((i1 / i2) + i3))}}[(0, 0)](GpuElemwise{Composite{Cast{float32}(AND(GE(i0, i1), LE(i0, i2)))},no_inplace}.0, GpuElemwise{Mul}[(0, 1)].0, GpuElemwise{Clip}[(0, 0)].0, GpuElemwise{Composite{((-i0) / i1)}}[(0, 0)].0)
Toposort index: 162
Inputs types: [CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, col)]
Inputs shapes: [(64, 10), (64, 1), (64, 10), (64, 1)]
Inputs strides: [(10, 1), (1, 0), (10, 1), (1, 0)]
Inputs values: ['not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[GpuAdvancedIncSubtensor1_dev20{inplace,inc}(GpuAlloc{memset_0=True}.0, GpuElemwise{Composite{(i0 * ((i1 / i2) + i3))}}[(0, 0)].0, Elemwise{Cast{int64}}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by fchollet** [comment]
If your model output is 10-dimensional, so should be your target. Here your target is 1-dimensional list of labels, it seems...

**Comment by philayres** [comment]
In case anybody else arrives here (it was the top result in Google for me for this error), the issue for me was not the number dimensions not matching. I had a 2D input and output. My issue was that the output of my model did not match the size in one dimension of the expected data y that I was feeding into .fit(), so the loss couldn't be calculated.

Maybe useful to anybody else seeing a similar problem. Check your model output size and the size of the y parameter your are feeding to fit().
