### ISSUE TITLE
Could keras.application.vgg16 and vgg19 support more pretrained weights? 

### ISSUE THREAD

**Issue by DanqingZ** [fchollet/keras#7127]
like these trained models on this webpage: http://www.vlfeat.org/matconvnet/models/beta16/

Thanks! I think this will make life easier for us to use pretrained models.

**Comment by Dref360** [comment]
If you can convert them to hdf5, you can submit a PR with those. Would be a great addition!

**Comment by DanqingZ** [comment]
I found there are h5 files out there in this repo.

https://github.com/fchollet/deep-learning-models/blob/master/vgg16.py

https://github.com/fchollet/deep-learning-models/blob/master/vgg19.py
