### ISSUE TITLE
`Layer.get_config` is not serializable/hashable

### ISSUE THREAD

**Issue by jorgecarleitao** [fchollet/keras#7132]
Consider the following piece of code, with Tensorflow or Theano backend:

```
import json
from keras.layers import Conv2D
from keras.models import Sequential


def define_and_serialize(input_shape):
    model = Sequential()
    model.add(Conv2D(16, (3, 3), activation='relu', input_shape=input_shape))
    model.add(Conv2D(32, (3, 3)))

    return json.dumps(model.get_config(), sort_keys=True) # sort_keys since it is an unsorted dict

assert (define_and_serialize((28, 28, 128)) == define_and_serialize((28, 28, 128))) # RAISES
```

I.e. the models are not serializable (e.g. `hash()`) does not work. This contradicts the documentation of `get_config`

> A layer config is a Python dictionary (serializable) containing the configuration of a layer.

The reason is that we are using a `global` counter to construct the layer's names (through `keras.backend.get_uid(prefix)`) that is added for every layer that is initialized (bad!).

For the user, a solution is to always name all layers (and thus not call `get_uid` to construct names). 

For Keras, IMO this is an issue because it is unexpected, and an anti-pattern. This can be solved by putting the counter on the *model*, instead of a global.

**Comment by Dref360** [comment]
Having the counter on the model is not possible if you want to use multiples models at the same time.
But you're right that we should fix this. I will try to think about a fix.

**Comment by fchollet** [comment]
That is precisely the intended behavior of the name autogeneration system. That's why the counter is global. If you want to give the same names to two layers (in two different models), you should pass a `name` argument to them.

**Comment by jorgecarleitao** [comment]
@Dref360 you mean Tensorflow/Theano would not be able to distinguish them if they run in parallel? Out of curiosity, what happens if two layers are instantiated with the same name on different models, and those models are run at the same time? Is there a naming collision?

@fchollet, why is that the intended behavior? A (very) common Python pattern is that an instance of class `A` initialized with a defined immutable list of arguments `A(1,2,3)` is expected to be equal to an instance initialized with the same arguments. This currently does not happen, e.g. with

```
Sequential(layers=[...])
```

The idiom in Python to solve this common issue (incrementer counter on a class for a uuid) is to have a class member. Specifically, something like

```

class Sequential(...):
    _naming_counter = 1

    def add(self, layer, name=None):

            if name is None:
                   name = '... %s' % _naming_counter
                   _naming_counter += 1
```

but maybe the point you are making is that internally, TensorFlow/Theano forbids two layers with the same name, even if on a different model, because they would collide. Is that the case?

In any case, the point I was making here is that *from the perspective of Python*, the current behavior is anti-idiomatic. We could discuss whether there is a reasonable solution or not, but I do not see why this was outright closed...

**Comment by fchollet** [comment]
The name autogeneration system generates unique names. It's what its for. I don't see why that is so strange to you. Literally everything in computation graphs relies on global states. Nearly every function call and class instantiation in both Theano, TensorFlow, and Keras, alter the global states, in particular generated names for ops, variables, layers and models. *This is the intended behavior*.
