### ISSUE TITLE
Embedding layers in LSTM for modeling IMDB sequence data

### ISSUE THREAD

**Issue by jingweimo** [fchollet/keras#7133]
In a keras example on LSTM for modeling IMDB sequence data (https://github.com/fchollet/keras/blob/master/examples/imdb_lstm.py), there is an embedding layer before input into a LSTM layer:
`model.add(Embedding(max_features,128)) #max_features=20000
`
`model.add(LSTM(128))`

What does the embedding layer really do? In this case, does that means the length of the input sequence into the LSTM layer is 128?  
If so, can I write the LSTM layer as:
`model.add(LSTM(128,input_shape=(128,1))`

But it is also noted the input X_train has subjected to pad_sequences processing:
`print('Pad sequences (samples x time)')`
`X_train = sequence.pad_sequences(X_train, maxlen=maxlen) #maxlen=80`
`X_test = sequence.pad_sequences(X_test, maxlen=maxlen) #maxlen=80`
It seems the input sequence length is 80?

**Comment by sanjuprk** [comment]
Embedding(MAX_NB_WORDS,
                            EMBEDDING_DIM,
                            input_length=MAX_SEQUENCE_LENGTH,
                            trainable=False)

1)     the '128' in the question is the dimension of the Word Embeddings.
2)     the Embedding layer learns the embeddings of each word(in the above case 20,000)
3)     padding sequences mean changing sentences of length 50,100 to 80(maxlen in above case), this makes all the sequences be of length 80(maxlen).

**Comment by jingweimo** [comment]
Does the embedding dimension has something with the length of the input sequence of LSTM layer? In the code:` model.add(LSTM(128)) `, I only define 128 hidden units, no input shape that is related to the input sequence length. How the LSTM decide the sequence length that is I am interested in. 

If I define the argument of input_shape after the embedding layers, does the input_shape override the previous setting of the sequence length if any?
