### ISSUE TITLE
enter input dimension

### ISSUE THREAD

**Issue by farah42** [fchollet/keras#7136]
Hello,

I define this small network but it doesn't work:

    inputs = Input(shape = (input_dim,) )
    dense1 = Dense(output_dim, activation='relu')(inputs)
    conv1 = Conv1D(output_dim, 3, activation='relu')(dense1)
    dense2 = Dense(output_dim, activation='relu')(conv1)
    model = Model(inputs = inputs, outputs = dense2)
    model.compile(optimizer = 'rmsprop', loss = 'msle')
    model.fit(X_train, Y_train)

The error is: ValueError: Input 0 is incompatible with layer conv1d_1: expected ndim=3, found ndim=4

So there anyone who could explain to me how to enter data's dimension?

Thank's :)

**Comment by buaahsh** [comment]
The  shape ndim of Input_0 is len(input_dim) + 1, expected ndim=3. But the ndim of X_train is 4. Please check the shape of X_train.

**Comment by farah42** [comment]
Thank's for your answer! So, the shape of X_train is (1979, 7200), I have 1979 vectors of size 7200 . And my variable Input_dim = 7200 so I don't know why I got this error.
