### ISSUE TITLE
Exceptions thrown in topology.py's get_config

### ISSUE THREAD

**Issue by kesinger** [fchollet/keras#7137]
I'm trying to dump a model to json, and am running into a bit of trouble.

In particular, I can't do this:

    h = H()
    open("h.json","w").write(h.model.to_json())

as I get an exception like:

     Traceback (most recent call last):
       File "./highway.py", line 163, in <module>
         open("hwy.json","w").write(hwy.model.to_json())
       File "/home/jake/tf3/lib/python3.5/site-packages/keras/engine/topology.py", line 2618, in  to_json
         model_config = self._updated_config()
       File "/home/jake/tf3/lib/python3.5/site-packages/keras/engine/topology.py", line 2585, in     _updated_config
         config = self.get_config()
       File "/home/jake/tf3/lib/python3.5/site-packages/keras/engine/topology.py", line 2383, in get_config
         return copy.deepcopy(config)
       File "/home/jake/tf3/lib/python3.5/copy.py", line 155, in deepcopy
         y = copier(x, memo)
       File "/home/jake/tf3/lib/python3.5/copy.py", line 243, in _deepcopy_dict
         y[deepcopy(key, memo)] = deepcopy(value, memo)
       # lots more lines of this snipped, sometimes _deepcopy_dict is _deepcopy_tuple or _list
       File "/home/jake/tf3/lib/python3.5/copy.py", line 306, in _reconstruct
         y.__dict__.update(state)
     AttributeError: 'NoneType' object has no attribute 'update'
     Exception ignored in: <bound method BaseSession.__del__ of   <tensorflow.python.client.session.Session object at 0x7f8fe60509e8>>
     Traceback (most recent call last):
       File "/home/jake/tf3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 595, in __del__
     TypeError: 'NoneType' object is not callable
  
If I use to_yaml, I get a different error at the end:

      File "/home/jake/tf3/lib/python3.5/copy.py", line 174, in deepcopy
        rv = reductor(4)
    TypeError: can't pickle google.protobuf.pyext._message.MessageDescriptor objects

This is how I'm finalizing the model:

        self.model = Model(inputs=self.jointInput, outputs=self.softmaxlayer)
        self.opt = keras.optimizers.Adam()
        self.loss = keras.losses.mean_squared_error
        self.model.compile(loss=self.loss, optimizer=self.opt, metrics=['mae'])
        self.checkpointer = ModelCheckpoint(filepath='weights3.h5',
                                            verbose=1, monitor='mae')
        self.tboard = TensorBoard(log_dir='./highway3.logs', histogram_freq=1,
                                  write_graph=True, write_images=True)
        self.callbacks = [self.tboard, self.checkpointer]

If I don't try to dump to json and just start training:

    h.model.fit(data, output,shuffle="batch", epochs=100, batch_size=1,
              callbacks=h.callbacks)

I get an error at end-of-epoch of the form:

      File "/home/jake/tf3/lib/python3.5/copy.py", line 174, in deepcopy
        rv = reductor(4)
    TypeError: cannot serialize '_io.TextIOWrapper' object

and if I take out the "monitor='mae'" line I get:

      File "/home/jake/tf3/lib/python3.5/copy.py", line 306, in _reconstruct
        y.__dict__.update(state)
    AttributeError: 'NoneType' object has no attribute 'update'

The model has one custom layer, keras_contrib's Deconvolution3D, and a little bit of fancy topology with some ugly Lambda layers and a siamese part, are there special things I need to take into account when trying to save models with that kind of stuff inside?

(p.s.: saving weights only works fine)

**Comment by jorgecarleitao** [comment]
Could you add a minimal and complete code that reproduces the issue? For example, something like [this example](https://github.com/fchollet/keras/issues/7013#issuecomment-311183041), so we can run in our machine and try to narrow the issue?

**Comment by kesinger** [comment]
I got it distilled down to this:

    from keras.layers import Input
    from keras.models import Model
    from keras.layers.merge import Add
    from keras_contrib.layers import Deconvolution3D

    skip = Input(shape=(16,32,8,64,))
    inner = Input(shape=(8,16,4,128,))
    deco = Deconvolution3D(filters=64, output_shape=skip.shape[1:],
	                     padding='same', kernel_size=(3,3,3),
	                     strides=(2,2,2), activation='relu')(inner)
    combo = Add()([deco,skip])

    m = Model(inputs=[skip,inner],outputs=combo)
    print(m.summary()) 
    open("m.json","w").write(m.to_json())

which throws a different error:

    Traceback (most recent call last):
      File "./hx.py", line 21, in <module>
        open("m.json","w").write(m.to_json())
      File "/Users/jake/ten1.2/lib/python3.6/site-packages/keras/engine/topology.py", line 2619, in to_json
        return json.dumps(model_config, default=get_json_type, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
        **kw).encode(obj)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
        return _iterencode(o, 0)
      File "/Users/jake/ten1.2/lib/python3.6/site-packages/keras/engine/topology.py", line 2616, in get_json_type
        raise TypeError('Not JSON Serializable:', obj)
    TypeError: ('Not JSON Serializable:', Dimension(16))

**Comment by jorgecarleitao** [comment]
In the example provided, the issue is not in Keras, but in `keras_contrib`. The error is different in Theano, but it is the same root cause. I suggest closing this issue and adding an issue to `keras_contrib`.

The issue is in the method `Deconvolution3D.get_config`,

```
    def get_config(self):
        config = {'output_shape': self.output_shape_}
        base_config = super(Deconvolution3D, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
```

`self.output_shape_` is not JSON serializable because it is of the form

```
'output_shape': (None, Dimension(16), Dimension(32), Dimension(8), Dimension(64))
```

and `Dimension` is not a serializable object. `output_shape` should be a tuple of integers or something similar.

**Comment by jorgecarleitao** [comment]
Scratch the previous message. The reason for this TypeError is that `output_shape` has a `Dimension` object on it. It has such an object because`skip.shape` passed here,

```
Deconvolution3D(filters=64, output_shape=skip.shape[1:]
```

has a Dimension object (in TensorFlow). Have you considered using something like this:

```
skip_shape = (16,32,8,64,)

skip = Input(shape=skip_shape)
inner = Input(shape=(8,16,4,128,))

deco = Deconvolution3D(filters=64, output_shape=skip_shape,
                     padding='same', kernel_size=(3,3,3),
                     strides=(2,2,2), activation='relu')(inner)
```

**Comment by kesinger** [comment]
Messing with skip.shape did the trick!

    outsh = [s.value for s in skip.shape]
    deco = Deconvolution3D(filters=64, output_shape=outsh[1:],
                                 padding='same', kernel_size=(3,3,3),
                                 strides=(2,2,2), activation='relu')(inner)

Unfortunately in my actual case, this hasn't been enough to fix the problem, I'm now consistently getting this error:

      File "/Users/jake/ten1.2/lib/python3.6/copy.py", line 169, in deepcopy
        rv = reductor(4)
    TypeError: can't pickle _thread.lock objects


I haven't been able to get a reproducible example yet tho, but the offending layer at which it fails looks like:

    input =	Input(shape=(128,256,64,32,))
    outsh = [256, 512, 128, 1]

    deco =	Deconvolution3D(filters=1, output_shape=outsh, padding='same', kernel_size=(3,3,3),
                            strides=(2,2,2), activation='relu')(input)
    slide =	Lambda(lambda x: -x[:,:,:,:,0])(deco)
    nls = numpy.linspace(1,128,128, dtype=numpy.float32)
    nlsx = K.expand_dims(K.constant(nls),1)
    dot = Lambda(lambda x: K.dot(x, nlsx)[:,:,:,0])(slide)
