### ISSUE TITLE
How to write a Bidirectional LSTM in keras?

### ISSUE THREAD

**Issue by daquang** [fchollet/keras#715]
@fchollet I've been reading in the issues you said that building a bidirectional LSTM is keras is possible and straightforward. Can you provide some sample code on how to do this?

**Comment by EderSantana** [comment]
Here is an example https://github.com/EderSantana/seya/blob/master/seya/layers/recurrent.py#L17-L48

**Comment by daquang** [comment]
Thank you. I noticed the Bidirectional class has two arguments in its __init__ method: forward and backward. What would I put there? Just LSTM layers as I would normally write? I also noticed you don't have any examples of using this Bidirectional class. Perhaps you can provide some sample code on how to use it? Thank you.

**Comment by EderSantana** [comment]
this was answered here https://github.com/EderSantana/seya/issues/2

**Comment by anjishnu** [comment]
I think BiDirectional LSTMs are becoming increasingly common in literature, shouldn't keras support them right out of the box?

**Comment by EderSantana** [comment]
@anjishnu there is a PR https://github.com/fchollet/keras/pull/453
maybe you want to help reviewing it.

**Comment by bennythedataguy** [comment]
whatever happened to this?  Looks like the PR was closed without merging.

**Comment by EderSantana** [comment]
keras rnn layers have `go_backwards` parameters that can be used to do bidirectional graphs

**Comment by albertz** [comment]
There is already this example in Keras:
https://github.com/fchollet/keras/blob/master/examples/imdb_bidirectional_lstm.py

Maybe this can be closed?

**Comment by albertz** [comment]
Also see #1629.

**Comment by albertz** [comment]
And #2838.

**Comment by kl2792** [comment]
@albertz this example doesn't work:

```
$ python imdb_bidirectional_lstm.py
Using Theano backend.
Using gpu device 0: Tesla K80 (CNMeM is enabled with initial size: 25.0% of memory, cuDNN 5005)
model.floatX =  float32
Traceback (most recent call last):
  File "imdb_bidirectional_lstm.py", line 13, in <module>
    from keras.layers import Dense, Dropout, Embedding, LSTM, Input, Bidirectional
ImportError: cannot import name 'Bidirectional'
```
