### ISSUE TITLE
selu Activation not found

### ISSUE THREAD

**Issue by BernardOng** [fchollet/keras#7155]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).
------------------------------------------------------------------------
I tried using the Activation('selu') call and it gives me an error message:
ValueError: Unknown activation function:selu

Activation('relu') and Activation('elu') works just fine.
My Keras v2.0.5 running on Tensorflow v1.2.0

What am I doing wrong, or what am I missing?

**Comment by jorgecarleitao** [comment]
The following code runs for me in TensorFlow and Theano and Keras (2.0.5):

```
import keras
from keras.models import Sequential
from keras.layers import InputLayer, Dense, Activation

model = Sequential()
model.add(InputLayer((32,32)))
model.add(Activation('selu'))
model.add(Dense(16))
model.add(Activation('elu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(16))


model.compile(loss='categorical_crossentropy',
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])
```

Can you share a minimal and complete code example?

**Comment by BernardOng** [comment]
This is my code snippet:
`
from keras.models import Sequential
from keras.layers import Input, BatchNormalization, Dense, Reshape, Lambda, Dropout
from keras.layers import Merge, Activation, noise

model = Sequential([
    # input layer
	Dense(200, input_shape=(54,), init='he_uniform'),
    Activation('selu'),
    BatchNormalization(),
    noise.GaussianDropout(0.4),

    # hidden layer #1
	Dense(100, init='he_uniform'),
    Activation('selu'),
	BatchNormalization(),
    noise.GaussianDropout(0.2),

    # hidden layer #2
    Dense(25, init='he_uniform'),
    Activation('selu'),
    BatchNormalization(),
    noise.GaussianDropout(0.2),

    # output layer
    Dense(1, init='he_uniform')
])`

I found what my problem was, but I don't know what caused it.
Somehow, my python setup.py install procedure did not copy over the git sourced activations.py into my envs folder. I compared the two files and sure enough, the selu function was not there (I was sure my envs was activated when I did the install).
Anyway, I just spliced in the selu function into the activations,py and now it's working as expected.

Thanks for your quick reply!

**Comment by jorgecarleitao** [comment]
great! Could you please close this issue then?

**Comment by redsphinx** [comment]
In my case I upgraded keras to 2.0.5 and tensorflow to 1.2.1, but activation `selu` was not found and `AlphaDropout` neither. But then everything just worked after I restarted my computer!
