### ISSUE TITLE
Mean pooling 1D and 2D layer?

### ISSUE THREAD

**Issue by daquang** [fchollet/keras#716]
Would it be possible to include mean pooling layers in addition to the max pooling layers?

**Comment by loyeamen** [comment]
class GlobalPooling(Layer):
    '''
        Apply a global pooling to an output.
    '''
    def __init__(self, pooling_function = T.mean, axis = 2, flatten_dim = 3):
        super(GlobalPooling,self).__init__()
        self.pooling_function = pooling_function
        self.axis = axis
        self.flatten_dim = flatten_dim
    def get_output(self, train):
        X = self.get_input(train)
        return self.pooling_function(X.flatten(self.flatten_dim), axis = self.axis)

    def get_config(self):
        return {"name":self.__class__.__name__,
               "pooling_function}":self.pooling_function.__name__}

**Comment by fchollet** [comment]
@loyeamen reformatted that for you...
