### ISSUE TITLE
FilenamesIterator and flow_from_filenames

### ISSUE THREAD

**Issue by rboyes** [fchollet/keras#7165]
Hello,

Recently I had an issue around multilabel classification, in that DirectoryIterator does not handle it as one can only specify a single label, whilst my dataset is too large to fit into memory when using the NumpyArrayIterator. 

I have a proposed solution that I've committed to my fork 8d087e2c96dc850511202b6598fd5b8ad853a176, namely a new class FilenamesIterator and associated flow_from_filenames method that's part of the ImageDataGenerator class, so it would look something like:

```
trainingDataGenerator = ImageDataGenerator(rescale = 1.0/255.0, rotation_range = 40, zoom_range = 0.15, horizontal_flip = True,                                       
                                           width_shift_range = 0.1, height_shift_range = 0.1, shear_range = 0.1)
trainingGenerator = trainingDataGenerator.flow_from_filenames(trainingFileNames, trainY, batch_size = batchSize, target_size = (nx, ny))
```

I think @tholor came up with a solution whereby he hacked the DirectoryIterator, so this is somewhat tangential to that. 

Is this useful? Happy to do the extra work for tests and the like and make a pull request.

**Comment by abrad1212** [comment]
You really shouldn't make a issue for a fork discussion. omg
