### ISSUE TITLE
MemoryError when calling `to_categorical(y)`

### ISSUE THREAD

**Issue by waissbluth** [fchollet/keras#7167]
I recently hit a MemoryError when using `to_categorical(y)` (with a big dataset, 'y.shape = (10000,256,256,4)', 16 categories). The error was in the line [`np.zeros((n, num_clases))`](https://github.com/fchollet/keras/blob/master/keras/utils/np_utils.py#L24), which, according to [the numpy docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html), defaults to `numpy.float64`.

I fixed the issue by calling `np.zeros((n, num_clases), dtype=numpy.int8)` instead. It could also be `numpy.bool`. Could there be any unforeseen side effects of this? Should I submit a pull request?

**Comment by abrad1212** [comment]
The MemoryError is caused because you are loading the dataset into your RAM and there is no more memory in your RAM.

**Comment by waissbluth** [comment]
I know, my point is that the datatype is much heavier than necessary, and I
should be able to load that dataset into a 48GB RAM.

On Jul 2, 2017 8:28 PM, "abrad1212" <notifications@github.com> wrote:

The MemoryError is caused because you are loading the dataset into your RAM
and there is no more memory in your RAM.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fchollet/keras/issues/7167#issuecomment-312541741>, or mute
the thread
