### ISSUE TITLE
Sequencial.fit_generator() low GPU usage

### ISSUE THREAD

**Issue by brunoklein99** [fchollet/keras#7168]
I'm trying to train with the following code:

```
generator = ImageDataGenerator(
    featurewise_center=True,
    rotation_range=90,
    horizontal_flip=True,
    vertical_flip=True,
    width_shift_range=.5,
    height_shift_range=.5,
    fill_mode='reflect'
)

batch_size = 2560

iterator = generator.flow(x_train, y_train[:, 0], batch_size=batch_size)

steps_per_epoch = math.ceil(len(x_train) / batch_size)

fit = model.fit_generator(iterator, steps_per_epoch, epochs=10000, verbose=True, workers=3, max_q_size=50)
```

But GPU usage is spiking:

![image](https://user-images.githubusercontent.com/11358728/27665597-7394579e-5c44-11e7-8ef0-ef5bf18b9598.png)

This code has proper GPU usage, it only drops when calling `generator.flow`, as expected.

```
for x, y in generator.flow(x_train, y_train, batch_size=30720):
    fit = model.fit(x, y[:, 0],
                    batch_size=3072,
                    epochs=10,
                    verbose=1,
                    validation_split=.3,
                    shuffle=True,
                    callbacks=[checkpoint]
                    )

```
The images are 32x32x3 and `x_train` and `y_train` have 65k rows.

Is this behavior expected?

**Comment by brunoklein99** [comment]
The issue is that I'm training on batches faster than I'm generating them. Please close.

**Comment by Bjoux2** [comment]
I have a similar problem, https://github.com/fchollet/keras/issues/7172

**Comment by brunoklein99** [comment]
These are not the same issues. You probably did not install tensorflow-gpu.

**Comment by lhanbi** [comment]
> The issue is that I'm training on batches faster than I'm generating them. Please close.

Hello i have similar problem. How do you know training on batches is faster than generating them.

**Comment by meidachen** [comment]
@[brunoklein99](/brunoklein99), how did you solve this issue?

**Comment by brunoklein99** [comment]
Get a faster data pipeline.

**Comment by meidachen** [comment]
Could you please discuss more about your new pipeline? I'm working with 3D tensor, and each data is 160*160*160*4. I'm saving them with numpy array and load them with a generator.

**Comment by brunoklein99** [comment]
So, my issue was that the GPU was consuming data faster than I was feeding it. Basically I had to find a way to feed data faster. Meaning multithreading/multiprocessing + fast CPU + fast SSD.
