### ISSUE TITLE
Multi-output layers (no, not a Graph)

### ISSUE THREAD

**Issue by elanmart** [fchollet/keras#717]
I'd like to ask for advice, extending #576 a little bit:

Suppose we have a `Power` layer, which for input `X` computes `X**2` and `X**3`.
`Add` layer computes `a + b + c` for three arbitrary inputs. 

``` python
example = Graph()
example.add_input('X1')
example.add_input('X2')
example.add_node(Power(), input='X1', name='pow')
example.add_node(Add(), connection_map={'a':'X2', 'b':'pow_squared', 'c':'pow_cubed'})
...
```

The problem with this example is that we cannot simply use a `connection_map` to connect 2 layers with matching output/input numbers. We would somehow have to fork the outputs of `Power` into seperate `Layers` (here named `pow_squared` and `pow_cubed`), and then feed those into `Add` alongside `X2`.

The question is: **does it make sense to try implementing something like this**? In this simple scenario we could get away with a simple `Graph`, but I imagine that allowing arbitrary computations inside a `Layer` and then producing several outputs is a more general solution. 
For example the following computation cannot be easily done using `Keras` (unless we go with some concating and slicing):

``` C
X = get_input()
a = f1(X)
b = f2(X)
out_1 = |a-b|
out_2 = a / b
```

If it does make sense, how could I implement this? The only solution I came up is not very elegant:
`Power` outputs a dict `{'squared' : X**2, 'cubed' : X**3}`. 
Then, inside `add_node` method we do the following:

``` python
# of course this would happen inside some kind of a loop
f_square = Filter('squared')
f_square.set_previous(self.nodes['pow'])
f_cube = Filter('cubed')
f_cube.set_previous(self.nodes['pow'])
```

and then only worry about feeding `f_square`, `f_cube` and `X2` to the `Add` layer.
The `Filter` works like this:

``` python
class Filter():
    def __init__(self, key):
        self.key=key
    def get_output(self, train):
        dct = self.get_input(train)
        return dct[key]
```

Again: does it make sense to implement such multi-output support, or I should find a smarter solution? Or simply go for implementing my heavily branching stuff in pure `Theano`?

**Comment by fchollet** [comment]
You should be able to use:

```python
example.add_node(power_layer, input='X1', name='pow')
example.add_node(addition_layer, input='pow', connection_map={'a':'X2', 'b':'pow_squared', 'c':'pow_cubed'})
```

Internally this would call, for instance:
```python
addition_layer.inputs['a'].set_previous(power_layer.outputs['pow_squared'])
```

Assuming that your power layer and addition layer implement the multi-io API (which is the Graph API, basically, because models/containers should have the same topological API as layers, for total compositionality), then the above will work fine. 

Then again, this is largely uncharted territory, so if you encounter any issue let us know and we'll work on it.

> Or simply go for implementing my heavily branching stuff in pure Theano?

There is one non-obvious perk to working in vanilla Keras: when next-gen Keras is here, your old models will still run (with minimal modifications), but they will compile and run faster than any Theano code could. At least that's the goal.

**Comment by elanmart** [comment]
>Internally this would call, for instance:
`addition_layer.inputs['a'].set_previous(power_layer.outputs['pow_squared'])`

OK, that was my initlial thought. It's not clear to me, however, how should this be implemented.
So far I have a solution which uses `Filter` layers to fork (create) the `outputs` dict:

```python
class Filter(LayerMultiIO):
    def __init__(self, key):
        self.key=key
    
    def get_output(self, train):
        dct = self.get_input(train)
        return dct[self.key]

class LayerMultiIO(Layer):
    def __init__(self):
        super(LayerMultiIO, self).__init__()
        self.name = None
        self.fork_outputs()

    def fork_outputs(self):
        self.outputs = {}
        for key in self.outputs_info:
            filt_layer = Filter(key)
            filt_layer.set_previous(self)
            if self.name:
                self.outputs[self.name+'_'+key] = filt_layer
            else:
                self.outputs[key] = filt_layer    

```

So that the `add_node` method can do:
```python
if layer.nb_output > 1:                
     for key in layer.outputs_info:
           self.namespace.add(name+'_'+key)
           self.nodes[name+'_'+key] = layer.outputs[name+'_'+key]
```

When it comes to connecting multiple inputs I could use some help. I do not create an `inputs` dict as @fchollet suggests, instead I do:

```python
def set_previous(self, layers, connection_map={}):               
        if self.inputs_info:
                self.previous = {input_name : layers[connection_map[input_name]] 
                                     for input_name in self.inputs_info} 
        else:
            if not isinstance(layers, Layer):
                raise Exception("This layer accepts a single input, however something different was provided")
            self.previous = layers
                
    def get_input(self, train=False):
        if not hasattr(self, 'previous'):
            return self.input
        else:            
            if self.inputs_info:
                return {input_name : self.previous[input_name].get_output(train) for input_name in self.inputs_info}
            else:
                return self.previous.get_output(train)
```

The complete (working) example looks like this:
```python
class Power(LayerMultiIO):
    def __init__(self):
        super(Power, self).__init__()
        self.input = T.matrix()
    
    @property
    def outputs_info(self):
        return set(('squared', 'cubed'))
        
    def get_output(self, train):
        X = self.get_input(train)
        out_1 = X**2
        out_2 = X**3
        return {'squared': out_1, 'cubed': out_2}
    
    
class Add(LayerMultiIO):
    def __init__(self):
        super(Add, self).__init__()
    
    @property
    def inputs_info(self):
        return set(('a', 'b', 'c'))
        
    def get_output(self, train):
        ins = self.get_input(train)
        X, Y, Z = ins['a'], ins['b'], ins['c']
        return X + Y + Z    


example = NGraph()

example.add_input('X')
example.add_node(Power(), inputs=['X'], name = 'pow')
example.add_node(Add(), mapping={'a':'X', 'b':'pow_squared', 'c':'pow_cubed'}, name='add')              
example.add_output('y', input='add')

example.compile(Adam(), {'y':'mse'})
```
I really need those multi-I/O layers, but I'm a terrible coder, so any advice would be appreciated!

**Comment by elanmart** [comment]
Previous comment was deleted due to its messy structure.

@fchollet would You have a moment to look at this [simplified gist](https://gist.github.com/elanmart/71c6963e4aa3d86f7e7e) and point out what could be improved in multi-io support? I'm using such layers quite extensively lately, but I think my solution is rather not elegant.
