### ISSUE TITLE
Cannot import AlphaDropout, SELU

### ISSUE THREAD

**Issue by SebastianPopescu** [fchollet/keras#7192]
So I have tried to run the code here:

https://github.com/fchollet/keras/blob/master/examples/reuters_mlp_relu_vs_selu.py

and it gives me the following error:

ImportError: cannot import name AlphaDropout

Besides that, it also cannot find 'selu'

I have upgraded Keras to the latest version.

Has anybody experienced this import error before?

**Comment by Danielhiversen** [comment]
It is still not in the latest release. So you should install it from the master branch on github

**Comment by SebastianPopescu** [comment]
Thanks a lot!

**Comment by Fahim7** [comment]
Hi, 
I have the same problem. would you please explain more about that. how can install it from the master branch on github? 
Thanks

**Comment by Danielhiversen** [comment]
`pip install --upgrade git+https://github.com/fchollet/keras.git
`

**Comment by Fahim7** [comment]
Thanks a lot!
