### ISSUE TITLE
Feature Wanted? Recurrent Additive Networks. I'd be happy to implement/PR but...

### ISSUE THREAD

**Issue by jmhessel** [fchollet/keras#7197]
A new paper from [Lee et al.](http://www.kentonl.com/pub/llz.2017.pdf) details a new, simplified recurrent neural network dubbed the "Recurrent Additive Network." It seems to do well on language modeling tasks when compared to the LSTM, despite using simpler computation with less parameters. This model would be easy to implement in Keras as a subclass of Recurrent, and I'd be happy to do it. However, my question is: is this something that would be pulled into the main repo? What is the standard policy for adding new sorts of RNNs?

**Comment by Dref360** [comment]
You can submit your PR to keras-contrib and then if people like it, it will get merged into Keras.

**Comment by jmhessel** [comment]
Cool! Just wanted to see if that was the main path still.

**Comment by edmondja** [comment]
I think its now more interesting to focus on SRU (https://github.com/fchollet/keras/issues/7870#issuecomment-328642850) since it has the same philosophy, its more up to date, and it already takes RAN as a reference.
