### ISSUE TITLE
How can i use the example code without gpu,instead,using the cpu.And when I build my own net,How I config that i can use the cpu

### ISSUE THREAD

**Issue by meanmee** [fchollet/keras#720]

**Comment by elanmart** [comment]
Go to your home directory, find the file `.theanorc` and change `device=cpu`

**Comment by meanmee** [comment]
i was config the device=cpu in my .theanorc file，I think it is the example code config my .theanorc file somewhere

**Comment by dandxy89** [comment]
These were taken from the example scripts:

- Run Commands:
    GPU command:
        ```THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python YOUR_FILE.py```
    CPU command:
        ```THEANO_FLAGS=mode=FAST_RUN,device=cpu,floatX=float32 python YOUR_FILE.py```

**Comment by meanmee** [comment]
I found where is the problem. The example code will test my dnn(if dnn.dnn_available() and theano.config.device[:3] == 'gpu' ),
Although I have installed it ,I may install multi version of it.So it gives me an error:Mixed dnn version. The header is from one version, but we link with a different version (2000, 20)
But I do not know how to fix it,anyone else know it?

**Comment by fchollet** [comment]
> But I do not know how to fix it,anyone else know it?

As indicated in the error message, you should simply uninstall all your cudnn versions and just reinstall the latest one. Then reinstall Theano to make sure it links the proper version. 

Also reinstall Keras, because it seems your version is out of date...
