### ISSUE TITLE
Stacked Autoencoder 

### ISSUE THREAD

**Issue by Bjoux2** [fchollet/keras#7220]
@fchollet 's blog : [Building Autoencoders in Keras](https://blog.keras.io/building-autoencoders-in-keras.html). 
In the  **Let's build the simplest possible autoencoder** section, the author provided a demo: 

```
from keras.layers import Input, Dense
from keras.models import Model

encoding_dim = 32 
input_img = Input(shape=(784,))
encoded = Dense(encoding_dim, activation='relu')(input_img)
decoded = Dense(784, activation='sigmoid')(encoded)
autoencoder = Model(input_img, decoded)
encoder = Model(input_img, encoded)

encoded_input = Input(shape=(encoding_dim,))
decoder_layer = autoencoder.layers[-1]
decoder = Model(encoded_input, decoder_layer(encoded_input))

autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')

from keras.datasets import mnist
import numpy as np
(x_train, _), (x_test, _) = mnist.load_data()

autoencoder.fit(x_train, x_train,
                epochs=50,
                batch_size=256,
                shuffle=True,
                validation_data=(x_test, x_test))

encoded_imgs = encoder.predict(x_test)
decoded_imgs = decoder.predict(encoded_imgs)
```
questions:
1, Why do we not use `decode_imgs = autoencoder.predict(x_test)` to obtain the reconstructed x_test?
2, The encoder and decoder model are not trained, why can we use them to map the data directly?

Thanks!

**Comment by voletiv** [comment]
1. The encoder was built for the purpose of explaining the concept of using an encoding scheme as the first part of an autoencoder. 
The encoder was created with the instruction, "Let's also create a separate encoder model:". This tells you that although it's not required, we are still creating it. 

2. I'm not sure what you mean by "map the data". Which line are you referring to as "mapping the data"?

**Comment by Bjoux2** [comment]
@voletiv thanks for your reply. 
In my opinion, why we can use `decode_imgs = autoencoder.predict(x_test)` is because we fitted it before the prediction. while in this demo, the encoder and decoder are not fitted before prediction.

**Comment by voletiv** [comment]
@Bjoux2 Ok I understand your doubt.
When we defined autoencoder as `autoencoder = Model(input_img, decoded)`, we simply name that sequence of layers that maps `input_img` to `decoded` as a "`autoencoder`". If you are familiar with C/C++,  this is like a pointer. So, when you run `autoencoder.fit(x_train, x_train,...`, you are training the weights corresponding to the layers whom you have named "`autoencoder`".

Similarly, when you run `encoder = Model(input_img, encoded)`, you are only naming the sequence of layers that maps `input_img` to `encoded`. Going by the pointer analogy, the name "`encoder`" simply points to the same set of layers as the first half of the name "`autoencoder`". So when you run `autoencoder.fit(x_train, x_train,...`, the "`encoder`" layers are being trained. Got it?

**Comment by Bjoux2** [comment]
@voletiv Got it, thanks, it is really helpful.
