### ISSUE TITLE
Stateful and Stateless lstm results are different

### ISSUE THREAD

**Issue by vladbph** [fchollet/keras#7224]
Hi,
Please correct me if I am wrong. The fact that the states are reset manually should not change the loss values. Is it true? 
Here is the self contained simple example:
https://gist.github.com/vladbph/5f4e6d64f54653d6a4fa3874ea295bec
, where 
x = (3, 1000, 5), y = (3, 2) processed with stateless lstm give different results from stateful, where I use 100 of x =  (3,10, 5) and then reset lstm states. 

Please use theano for repeatable results:

*** Stateless LSTM
Epoch 1/3
3/3 [==============================] - 0s - loss: 0.9029
Epoch 2/3
3/3 [==============================] - 0s - loss: 0.8094
Epoch 3/3
3/3 [==============================] - 0s - loss: 0.7805

*** Stateful LSTM
_Epoch 1/3 - loss: 0.5947
Epoch 2/3 - loss: 0.497
Epoch 3/3 - loss: 0.4639_

**Comment by taehoonlee** [comment]
The results including loss and prediction should be different between `stateful=False` and `stateful=True`. It may be helpful to look at the `test_statefulness` in `tests/keras/layers/recurrent_test.py`.

**Comment by vladbph** [comment]
@taehoonlee I forgot to mention that the way I get the loss in stateful case is a mean of all losses over the timesteps. Could you please take a look at the code attached to see if I'm doing something fundamentally wrong? I looked at the recurrent_test.py. I don't see the case similar to mine.
https://gist.github.com/vladbph/5f4e6d64f54653d6a4fa3874ea295bec

**Comment by taehoonlee** [comment]
To get the same results between the two, you can put `model.reset_states()` for each timestep, not after all the timesteps.

**Comment by vladbph** [comment]
I'm not sure if I follow... the whole idea of rnn/lstm is to keep the state during the time(t, t+1,t+2,...).  Statefulness gives me the control when to reset the states when the time sequence is finished. Resetting states after each timestep will break the "memory". My time sequence is very long... and I want to create efficient batches of samples on input's axis=0 and batches in "time" on input's axis=1
Example: 2 samples with 9 timesteps of feature vector size = 1
X(2,9,1)
Batch:
sample 0: [0,1,2,3,4,5,6,7,8]
sample 1: [a,b,c,d,e,f,g,h,i]

I want to break timeline by 3. So fit() gets inputs with shape (2,3,1):
1:
[0,1,2]
[a,b,c]

2:
[3,4,5]
[d,e,f]

3:
[6,7,8]
[g,h,i]
After this step I reset the states because all 9 timesteps are finished.

**Comment by taehoonlee** [comment]
Yes, you are right. Resetting states after each timestep will break the "memory". That's why you can not get the same results between the two.

Here is another point: `return_sequences=False`. With your example, stateless RNN tries to learn a mapping from the whole sequence [0,1,2,3,4,5,6,7,8] to a single response y. But stateful RNN does [0,1,2] -> y, [3,4,5] -> y, [6,7,8] -> y with maintaining hidden variables between each timestep.

**Comment by vladbph** [comment]
Thanks! Any suggestions how to make it "closer" to stateless results...?
