### ISSUE TITLE
K.binary_crossentropy is reversed from losses.binary_crossentropy

### ISSUE THREAD

**Issue by bfredl** [fchollet/keras#7228]
`K.binary_crossentropy` has the arguments reversed from `losses.binary_crossentropy` which is very confusing, I can't imagine any rational reason as both are internal to keras, not constrained by any external backend. (I had to switch to the former because I needed sum, not mean). That the respective documentations insist on using different nomenclature (true/pred vs output/target) makes it very easy to overlook even if you read the documentation as I did.

As I guess neither can be changed to backwards-compatibility, maybe a note can be added to both places to reduce the risk of future confusion (and wasted time).

**Comment by myutwo150** [comment]
Guess #7199 is what you want

**Comment by bfredl** [comment]
Indeed, thanks!
