### ISSUE TITLE
Get the type of weights in LSTM model in Keras

### ISSUE THREAD

**Issue by shaifugpt** [fchollet/keras#7242]
I am using Keras with tensorflow for creating LSTM models. The model is a single layer with 16 cells. 

model.trainable_weights
[<tf.Variable 'lstm_1/kernel:0' shape=(6, 64) dtype=float32_ref>, <tf.Variable 'lstm_1/recurrent_kernel:0' shape=(16, 64) dtype=float32_ref>, <tf.Variable 'lstm_1/bias:0' shape=(64,) dtype=float32_ref>, <tf.Variable 'dense_1/kernel:0' shape=(16, 6) dtype=float32_ref>, <tf.Variable 'dense_1/bias:0' shape=(6,) dtype=float32_ref>]

gives this output. From here, I am unable to determine what are the input weights, cell weights, forget and output gate weights. How can we determine that

And

 model.layers[0].states generates ouput:
[<tf.Variable 'lstm_1/Variable:0' shape=(40, 16) dtype=float32_ref>, <tf.Variable 'lstm_1/Variable_1:0' shape=(40, 16) dtype=float32_ref>]

here 40 is the batch size. What are these two states. Is it the cell state? Then how two?

**Comment by hudson-zhao** [comment]
hmm, I actually had the exactly same questions.  

I have looked into #3088, #4209, and https://stackoverflow.com/questions/42861460/how-to-interpret-weights-in-a-lstm-layer-in-keras

But none of these seems working

**Comment by hudson-zhao** [comment]
dig into the current codebase, seems the codes speak for themselves  

https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L1054-L1062

**Comment by elhenceashima** [comment]
@shaifugpt could you please share your findings about the same as well. Especially why is the dimension of bias (64,) and also why the number 64 since I got the exact same number for an entirely different architecture.
looking forward to get a response from you.
Thanks in advance.

**Comment by kevheim** [comment]
The bias is 64 because there are 4 bias vectors of 16 length.
