### ISSUE TITLE
The data type conversion between int32 and float32 in Keras

### ISSUE THREAD

**Issue by yylonly** [fchollet/keras#7246]
I want to build a new layer in Keras, so I defined the layer using Lambda layer. And my self-defined layer requires convert the data type of tensor (dtype=float32) to int32, then I need turn the dtype back (from int32 to float32) after some operations. The code is: 
```
# add my self-defined layer 
y = Lambda(f)(y1)  # y1 is the output of last layer
```
```
def f(x):
    y = tf.to_int32(x)
    # bitwiseXor = tf.bitwise.bitwise_xor(bitwiseXor, kkk)
    z = tf.to_float(y)
    return z
```
But following errors appears, how to solve it? 

> Traceback (most recent call last):
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
> preferred_dtype=default_dtype)
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 675, in internal_convert_to_tensor
> ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
> return constant(v, dtype=dtype, name=name)
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
> tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 364, in make_tensor_proto
> raise ValueError("None values not supported.")
> ValueError: None values not supported.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 504, in apply_op
> values, as_ref=input_arg.is_ref).dtype.name
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 675, in internal_convert_to_tensor
> ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
> return constant(v, dtype=dtype, name=name)
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
> tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 364, in make_tensor_proto
> raise ValueError("None values not supported.")
> ValueError: None values not supported.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/win1/Ubuntu_App/RemotePython/EncNN/My_EncML.py", line 134, in 
> model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_data=(x_test, y_test))
> File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1458, in fit
> self._make_train_function()
> File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1002, in _make_train_function
> self.total_loss)
> File "/usr/local/lib/python3.4/dist-packages/keras/optimizers.py", line 326, in get_updates
> new_a = self.rho * a + (1. - self.rho) * K.square(g)
> File "/usr/local/lib/python3.4/dist-packages/keras/backend/tensorflow_backend.py", line 1225, in square
> return tf.square(x)
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/math_ops.py", line 428, in square
> return gen_math_ops.square(x, name=name)
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 2544, in square
> result = _op_def_lib.apply_op("Square", x=x, name=name)
> File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 508, in apply_op
> (input_name, err))
> ValueError: Tried to convert 'x' to a tensor and failed. Error: None values not supported.
> 
> Process finished with exit code 1

I tried following codes in tensorflow, the result is right.
```
a = tf.constant(3.2, dtype='float32')
b = tf.to_int32(a)
c = tf.bitwise.bitwise_xor(b, b)
z = tf.to_float(c)
sess = tf.Session()
d = sess.run(z)
print(d)
```

**Comment by myutwo150** [comment]
The problem is not casting but gradient computation.
From the error message:
```
File "/usr/local/lib/python3.4/dist-packages/keras/optimizers.py", line 326, in get_updates
new_a = self.rho * a + (1. - self.rho) * K.square(g)

...

ValueError: Tried to convert 'x' to a tensor and failed. Error: None values not supported.
```
The `x` in the `ValueError` refers to `g` in optimizers.py, which is the gradient.
I don't think bitwise XOR is differentiable.
Your TF code works because there's no model fitting in it.

**Comment by yylonly** [comment]
Thank you for your reply. But the error still exist even if I comment the bitwise line.
`# bitwiseXor = tf.bitwise.bitwise_xor(bitwiseXor, kkk)`

For now the code is:
```
def f(x):
    y = tf.to_int32(x)
    z = tf.to_float(y)
    return z
```
And the error is the same:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 490, in apply_op
>     preferred_dtype=default_dtype)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 675, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
>     tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 364, in make_tensor_proto
>     raise ValueError("None values not supported.")
> ValueError: None values not supported.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 504, in apply_op
>     values, as_ref=input_arg.is_ref).dtype.name
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 675, in internal_convert_to_tensor
>     ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 121, in _constant_tensor_conversion_function
>     return constant(v, dtype=dtype, name=name)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
>     tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_util.py", line 364, in make_tensor_proto
>     raise ValueError("None values not supported.")
> ValueError: None values not supported.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/win1/Ubuntu_App/RemotePython/EncNN/My_EncML.py", line 134, in <module>
>     model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_data=(x_test, y_test))
>   File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1458, in fit
>     self._make_train_function()
>   File "/usr/local/lib/python3.4/dist-packages/keras/engine/training.py", line 1002, in _make_train_function
>     self.total_loss)
>   File "/usr/local/lib/python3.4/dist-packages/keras/optimizers.py", line 326, in get_updates
>     new_a = self.rho * a + (1. - self.rho) * K.square(g)
>   File "/usr/local/lib/python3.4/dist-packages/keras/backend/tensorflow_backend.py", line 1225, in square
>     return tf.square(x)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/math_ops.py", line 428, in square
>     return gen_math_ops.square(x, name=name)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 2544, in square
>     result = _op_def_lib.apply_op("Square", x=x, name=name)
>   File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 508, in apply_op
>     (input_name, err))
> ValueError: Tried to convert 'x' to a tensor and failed. Error: None values not supported.
> 
> Process finished with exit code 1

**Comment by Dref360** [comment]
Casting is not differentiable

**Comment by Mrpedi** [comment]
So, is there any solution of casting in the intermediate layer????
