### ISSUE TITLE
Importing Keras without Theano

### ISSUE THREAD

**Issue by wtesler** [fchollet/keras#7250]
Is there any way to import Keras without Theano if using a Tensorflow backend? I ask this because with the new Google Cloud ML, you can train models in the cloud, but the cloud instance needs to download Keras before it can begin training, and I notice that a lot of the time spent downloading Keras is actually downloading Theano. If there was some way to only download the parts of Keras relevant to Tensorflow, that would be ideal.

**Comment by taehoonlee** [comment]
One of the possible workarounds is:
1. Fork `keras`.
2. Remove `theano` of `install_requires` in `setup.py`.
3. Install with `pip install git+https://github.com/wtesler/keras`.
