### ISSUE TITLE
Keras Bidirectional LSTM get_weights()

### ISSUE THREAD

**Issue by LN5user** [fchollet/keras#7257]
Hi,
I have a  question about Bidirectional LSTM implemented in Keras.

I have shared Bidirectional LSTM 

`shared_lstm=Bidirectional(LSTM(50,return_sequences=True),merge_mode='concat')

a=shared_lstm(emb_1)
b=shared_lstm(emb_2)

pool_vec_1=Flatten() (MaxPooling1D(pool_size=max_length)(a))
pool_vec_1 =Flatten() (MaxPooling1D(pool_size=max_length)(b))`

and I would like later to use my pre-trained weights

`lstm = shared_lstm.get_weights()[0]
lstm=Bidirectional(LSTM(50),merge_mode='sum',  weights=[lstm],trainable = False)`

My problem is : shared_lstm has 6 outputs. Which shoul I use?

**Comment by minimaxir** [comment]
A normal LSTM has 3 weight matrices; logically a Bidirectional LSTM should have 6.

**Comment by LN5user** [comment]
Of course, you are right.  My question is: should I use all of them?  
 
```
a = shared_lstm.get_weights()[0]
b = shared_lstm.get_weights()[1]
c = shared_lstm.get_weights()[2]
d = shared_lstm.get_weights()[3]
e = shared_lstm.get_weights()[4]
f = shared_lstm.get_weights()[5]


lstm=Bidirectional(LSTM(50),merge_mode='sum', weights=[a,b,c,d,e,f,g],trainable = False)


```

**Comment by Cerno-b** [comment]
You definitely need all the weights. Three are for the forward pass and three are for the backward pass.

**Comment by LN5user** [comment]
thank you very much!
