### ISSUE TITLE
Shape of output of RNN

### ISSUE THREAD

**Issue by chenzhuo8804** [fchollet/keras#7262]
Hi, I am new to Keras and RNN
I have a dataset that has 1000 videos, each video has 2000 frames and each frame has 5 features. I would like to train a RNN that can classify each video frame to 1 of the 3 categories. 

Example
Video1
  Frame1 [fc11,fc12,fc13,fc14,fc15] -> output1
  Frame2 [fc21,fc22,fc23,fc24,fc25] -> output2
  Frame3 [fc31,fc32,fc33,fc34,fc35] -> output3
  ...
Video2
...

x_shape = [1000, 2000, 5]
y_shape = [1000, 2000, 3] (Since each frame has it's own y value)
I am a little confused how to construct a Model that will fit this shape

**Comment by td2014** [comment]
@chenzhuo8804 .  Are you sure you want an RNN model in the first place?  From your description, it sounds like you want something like logistic regression type/multilayer perceptron if you are classifying individual frames, but in any case the Keras documentation might give you some guidance:  https://keras.io/layers/recurrent/ as a start.  I hope that helps.

**Comment by chenzhuo8804** [comment]
@td2014 Thank you very much, I wanted to use RNN since in videos, current frames's target is somehow related to previous frame's target, that is why I want to try out RNN.
What I am stuck now is that most of the RNN examples included will have only 1 output for a sequence instead per timestep(in my example, the y_shape will be [1000,3] instead of [1000,2000,3])

**Comment by td2014** [comment]
@chenzhuo8804 .  It sounds like what you are asking for is to set "return_sequences=True" in the layer definition, and having 3 output nodes???
