### ISSUE TITLE
Keras Backend K.set_learning_phase(False) not working in TF 1.2 (fine in 1.1)

### ISSUE THREAD

**Issue by dylanrandle** [fchollet/keras#7270]
Hi all,

Works fine in 1.1 but in 1.2:

```
from tensorflow.contrib.keras.python.keras import backend as K
from tensorflow.contrib.keras.python.keras.models import load_model
K.set_learning_phase(False)
model = load_model(MODEL_PATH)
```
`model.uses_learning_phase <-- returns TRUE`

This does not happen in 1.1. What may have changed that cause this in 1.2?

Thank you in advance.
Best regards,
Dylan Randle

**Comment by iamgroot42** [comment]
I'm facing the same issue for v1.2
