### ISSUE TITLE
Accesing the training sample and its index in Keras custom objective function

### ISSUE THREAD

**Issue by mdmustafizurrahman** [fchollet/keras#7275]
Hi,
I am new to Keras and trying to implement a custom objective function as described in this paper https://arxiv.org/abs/1612.04898 (Page 2, Equation 2). For the second part of the equation 2, I need access to the original training sample that is correspondent to y_true and also the index of it. Is it possible to access it in Keras. 

Thanks

**Comment by thefiddler** [comment]
The most straightforward way is to concatenate this into the output of your model as a separate channel. For example (assuming tensorflow backend with BHWC tensor layout):

```python
def loss(y_true, y_pred):
    x_training = y_true[..., 1:]
    y_true = y_true[..., :1]
    # implement equation 2 here
    error = ...
    return error

# build your model as you already do
x = input = Input(shape=[1, None, None])
x = ... 
# concatenate the input with the output
x = concatenate([x, input], axis=3)
model = Model(input, x)
model.compile(loss=loss, optimizer=SGD())
```

**Comment by mdmustafizurrahman** [comment]
Thanks a lot. That is really a hacky way. But it should work. 👍

**Comment by mdmustafizurrahman** [comment]
@thefiddler hope you are fine. I need some little more help.

Hi,
I am trying to implement a custom loss function in keras where I need to compute the equation:
If you can remember the second part of the equation 2, page 2 of https://arxiv.org/abs/1612.04898 which is: 
$$ \sum_{i=1}^n \sum_{j=1^n} \omega_{i,j} * KLD( (y_pred_i) || (y_pred_j) ) $$ 

so in Keras I am getting y_pred which have shape (n_data_points, n_dim)
According to the above equation, I first need compute the KLD = KL Divergence between all pairs of (i,j) in y_pred. That means if y_pred is of size 3, then I have to compute KL divergence between 
(1,1), (1,2), (1,3), 
(2,1),(2,2,), (2,3),
(3,1), (3,2), (3,3)

Which is basically a nested for loop:

for i in range (1,3):
  for j in range(1,3):
     compute KLD between (i,j)
Note KL Divergence return a scalar value
And I need to store all these scaler value in a tensor so that I can later make element wise product between these scalar tensor and the omega 
Since I am new to Keras, I am trying to use the following nested theano scan

`initial_result = theano.tensor.alloc(np.array(0), num_classes)

        def second_step(y_pred, prev_result, y_pred1): # y_pred vector and y_pred1 is matrix
            result2, updates2 = theano.scan(
                lambda y_pred1, y_pred: (y_pred + eps) * (K.log(y_pred + eps) - K.log(y_pred1 + eps)),
                sequences=[y_pred1], non_sequences=y_pred)
            prev_result = result2

        # y_pred and y_pred1 both matrix, first scan take one instance of y_pred and pass the whole y_pred1 as non seqenece to the secodn scan
        result1, updates1 = theano.scan(
            second_step,
            sequences=[y_pred],
            outputs_info= [initial_result],
            non_sequences=[y_pred1]
        )
`

But I am always reciving the message:
 'The return value of your scan lambda expression may only be '
ValueError: The return value of your scan lambda expression may only be made of lists, tuples, or dictionaries containing Theano variables (or `theano.scan_module.until` objects for conditions). In particular if you need to use constant values, you can use `tensor.constant` to turn them into Theano variables.

Can you help me to correctly implement the function under custom loss?
