### ISSUE TITLE
NARX in Keras, Tensorflow

### ISSUE THREAD

**Issue by Denis-Evseev** [fchollet/keras#7277]
I am writing a thesis where the main task it to rewrite a MatLab script using NARX into a Python script. 
I would like to use Keras and Tensorflow to implement it but wasn't able to find anything about NARX in the documentation and even google doesn't cope with it. 

Is here anybody who is very familiar with Keras and Tensorflow and can say whether I can use the library to implement a script using NARX.

Here is a link how NARX works in MatLab(https://uk.mathworks.com/help/nnet/ug/design-time-series-narx-feedback-neural-networks.html)

Here is a link to a python library which works with NARX
(http://pyneurgen.sourceforge.net/recurrent.html)

**Comment by rajil** [comment]
I think RNN LSTM within keras is similar to NARX. It is possible to put a time delay on both X and Y variables (https://www.mathworks.com/help/nnet/gs/neural-network-time-series-prediction-and-modeling.html). 

However, I did not get a good result using LSTM for Non-linear Input-Output method in Matlab wherein the time delay is only on X variable.

**Comment by Denis-Evseev** [comment]
Thank you rajil for the response. I tried to better get acquainted with LSTM and time delay.
Have I got it properly that time delays mean time series in Keras?

**Comment by joshim27** [comment]
I also implemented NARX using MATLAB. However, I would like to ask if anyone now knows about how to implement NARX model using Keras and Tensorflow ?

**Comment by rola93** [comment]
Hi David, could you finish your work? Did you find a solution for this? Did you implement it on python/keras? I'm having same problem, and would like to hear from your work

Thanks

**Comment by okarchafik** [comment]
Hi everyone 
I am facing the same problem. I want to run NARX in python, but pyneurgen does not have a good documentation. I would like to run NARX in Keras.
Did you apply NARX in python?

**Comment by S2Mostafa** [comment]
Hi you can check https://pypi.org/project/fireTS/
