### ISSUE TITLE
errer appeared when include "from keras.engine.training import collect_trainable_weights"

### ISSUE THREAD

**Issue by TommySun1994** [fchollet/keras#7293]
When I execute the command 
from keras.engine.training import collect_trainable_weights

error appeared:
ImportError: cannot import name 'collect_trainable_weights'

I cannot sovle this problem. And I want to konw that which part should I modify if I want to run it correctly and why?

Thank you very much!!!

**Comment by td2014** [comment]
@TommySun1994 .  What are you trying to do?  You can check the source code to see if the function/class you are trying to import exists with that name.  Perhaps you want a class instead.  https://github.com/fchollet/keras/blob/master/keras/engine/training.py .  Hope this helps.
