### ISSUE TITLE
sparse_categorical_crossentropy loss function output shape didn't match

### ISSUE THREAD

**Issue by BrambleXu** [fchollet/keras#7303]
I have a dataset which has 3570 labels. When I use the `sparse_categorical_crossentropy` as the loss function, the output shape didn't match.
```
model = Sequential()
model.add(Dense(1024, input_dim=79, activation='relu'))
model.add(Dense(2048, activation='relu'))
model.add(Dense(3570, activation='sigmoid'))

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model.fit(x_train, y_train,
          epochs=10,
          batch_size=1,
          validation_data=(x_valid, y_valid))
```
and the output is 
`ValueError: Error when checking model target: expected dense_42 to have shape (None, 1) but got array with shape (1055, 3570)` 

Then I fount this [issue#2444](https://github.com/fchollet/keras/issues/2444) and used `np.expand_dims(y, -1)` to change the code. But there was still have error. How should I change the code?

```
model = Sequential()
model.add(Dense(1024, input_dim=79, activation='relu'))
model.add(Dense(2048, activation='relu'))
model.add(Dense(3570, activation='sigmoid'))

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])
model.fit(x_train, np.expand_dims(y_train, -1),
          epochs=10,
          batch_size=1,
          validation_data=(x_valid, np.expand_dims(y_valid, -1)))
```
the error
`ValueError: Error when checking model target: expected dense_45 to have 2 dimensions, but got array with shape (1055, 3570, 1)`

**Comment by EvenOldridge** [comment]
I've run into the same issue.  categorical_crossentropy works just fine, but sparse_categorical_crossentropy gives a similar "ValueError: Error when checking model target:" error.

**Comment by StevenLOL** [comment]
Same here any updates ?

**Comment by bgshin** [comment]
Same here any updates ? (2)

**Comment by bgshin** [comment]
The following link worked for me.

[https://github.com/farizrahman4u/seq2seq/issues/164](https://github.com/farizrahman4u/seq2seq/issues/164)
