### ISSUE TITLE
[Question] Transposed Conv equivalent to Upsampling + Conv?

### ISSUE THREAD

**Issue by pietz** [fchollet/keras#7307]
Is

    m = Conv2DTranspose(16, 3, strides=2, padding='same')(m)

equivalent to

    m = Upsampling2D(2)(m)
    m = Conv2D(16, 3, padding='same')(m)

?

If not, how are they different a) in Keras b) in practical terms?

**Comment by sorenchiron** [comment]
they are different
strides=2  implies such an operation:  
> f( pix1,pix2,...,pixN*N) = newpix1, ... , newpixM*M

while upsampling then strides=1 implies:

> g(pix1,pix2,...,pixN*N) = pix1,pix1,pix1,pix1,pix2,pix2, ... , pixN*N, pixN*N, pixN*N
> f(pix1,pix1,pix1,pix1,pix2,pix2, ... , pixN*N, pixN*N) = 
> newpix1,newpix1,newpix1,newpix1,newpix2,newpix2, ... , newpixN*N, newpixN*N, newpixN*N

**Comment by ubersexualShupeng** [comment]
Are there any 'more detailed' interpretations of the differences between these two operations (Conv2DTranspose vs Upsampling2D + Conv2D)? In terms of images features re-presentation?

**Comment by davidtellez** [comment]
They are not equivalent. You can have a look at https://distill.pub/2016/deconv-checkerboard/
