### ISSUE TITLE
ImageDataGenerator ValueError

### ISSUE THREAD

**Issue by dp225** [fchollet/keras#7318]
I'm trying to run the following simple bit of code to generate augmented data, but I come across the following error:

> X_batch, y_batch = datagen.flow(x_train, y_train, batch_size=16)
> Traceback (most recent call last):
> 
>   File "<ipython-input-7-e7d6dbcf5ed1>", line 1, in <module>
>     X_batch, y_batch = datagen.flow(x_train, y_train, batch_size=16)
> 
> ValueError: too many values to unpack

I'm running tensorflow-GPU backend 
I've searched for the issue, but cannot find a solution. Any ideas?!
Thanks

```
from keras.datasets import mnist
from keras.preprocessing.image import ImageDataGenerator

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(x_train.shape[0], 28, 28,1)
x_test = x_test.reshape(x_test.shape[0], 28, 28,1)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
datagen = ImageDataGenerator(width_shift_range=0.1,  height_shift_range=0.1)
X_batch, y_batch = datagen.flow(x_train, y_train, batch_size=16)
```

**Comment by Dref360** [comment]
Just like explained in the doc : https://keras.io/preprocessing/image/

flow returns a generator, you cannot unpack a generator.
More info on generators here : https://wiki.python.org/moin/Generators

**Comment by dp225** [comment]
I'd just worked this out
many thanks
