### ISSUE TITLE
get the output of convolutional layers

### ISSUE THREAD

**Issue by amaltarghi** [fchollet/keras#7324]
@fchollet  My question is:

i need to use just the output of the output of the covolutional layers and use them for and other network with other data there is any way to do it ?

**Comment by nzw0301** [comment]
Maybe, https://keras.io/getting-started/faq/#how-can-i-obtain-the-output-of-an-intermediate-layer

**Comment by amaltarghi** [comment]
@nzw0301  Thank you but me i need only the output of flatten i don't know if it can be done or not ?

**Comment by nzw0301** [comment]
Like this?

```python
from keras.models import Model

model = ...  # create the original model

layer_name = 'conv_layer_name'
intermediate_layer_model = Model(inputs=model.input,
                                 outputs=model.get_layer(layer_name).output)
x = flatten()(intermediate_layer_model)
```

**Comment by amaltarghi** [comment]
@nzw0301  thank you but i have 2 datasets the first data set i want to apply a convolution and keep the result of flatten and concatenate with an other data set and a do a simple feed forward it is possible with keras ?

**Comment by nzw0301** [comment]
Yes, you can do that by using [`merge or Merge`](https://keras.io/layers/merge/) layer to concatenate 2 datasets in functional API.
