### ISSUE TITLE
Dataset link broken

### ISSUE THREAD

**Issue by farizrahman4u** [fchollet/keras#733]
The link to the training data :https://mega.co.nz/#F!YohlwD7R!wec0yNO86SeaNGIYQBOR0A is broken.

**Comment by fchollet** [comment]
Really? It works for me.

Agreed that hosting stuff there is not a good idea, though. If you have a better suggestion...

**Comment by farizrahman4u** [comment]
@fchollet Can we move it to a more standard hosting service? I am still getting a "DNS_PROBE_FINISHED_NXDOMAIN"

**Comment by fchollet** [comment]
That's either a DNS lookup failure at the level of your ISP, or a DNS caching issue (which could be either your browser or your OS). You can try flushing the DNS cache of your browser to start with...

I assure you the link itself does work.

**Comment by farizrahman4u** [comment]
Hi, I googled it and it seems mega.co.nz is blocked in India, it could still be accessed using VPNs and stuff.. but i still recommend switching the hosting service.

**Comment by fchollet** [comment]
> mega.co.nz is blocked in India

Why would it be?

> i still recommend switching the hosting service

Then again, do you have any realistic suggestion? I don't feel like paying for terabytes of S3 bandwidth.

**Comment by farizrahman4u** [comment]
Well, its simple, the court bans a website, ISPs block the website, court lifts the ban, ISPs don't care, they continue blocking. Why the court bans mega you might ask. For distributing pirated movies.
For example, mega was blocked in Itally in july 2014 (https://torrentfreak.com/dotcoms-mega-blocked-italy-piracy-concerns-140719/). I am curious about the actual size of the file. I would like to set up a mirror for those in countries like India.
