### ISSUE TITLE
what is the "states" in LSTM layers

### ISSUE THREAD

**Issue by sun-peach** [fchollet/keras#7331]
Hi, dear all,

I am implementing a custom LSTM layer based on the original version. I don't use stateful LSTM. I see in the "step" function, there is the variable "states" which seems to store some internal information, like the previous c and h. Is this the one for every step or only for the stateful LSTM use(e.g. memorize the last step in previous sequence)?

Also, there is a self.states variable in the class. Could anyone tell me if this is for state of every step or only for stateful LSTM?

Thank you very much!

**Comment by td2014** [comment]
@sun-peach . I don't have a complete answer for your question, but it is interesting.  I did a quick check running a single LSTM layer with arguments: return_sequences=True, return_state=True
and looked at the output I get.  A least, what appears to be returned is the outputs for each time step (I guess this is the "h"), and then the final timestep h and _I think_ the internal state c for the final timestep (or at least I should say only one value is returned, not a series).  In other words, whatever is passed back through that function call to the outputs seems to only keep track of the LSTM output, but not state for each time step.  This might help your diagnostics of the code logic.  I hope this helps.

**Comment by sun-peach** [comment]
Thank you. I agree that h is for every step whatever it is stateful "True" or "False". However, I think c is also for every step. But I am not quite sure. That's why I asked. How do you think?@td2014

**Comment by td2014** [comment]
@sun-peach .  I think that c is defined for each time step, as well.  From the code for the LSTM step function:
https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L1156

i = self.recurrent_activation(x_i + K.dot(h_tm1 * rec_dp_mask[0],
--
  | self.recurrent_kernel_i))
  | f = self.recurrent_activation(x_f + K.dot(h_tm1 * rec_dp_mask[1],
  | self.recurrent_kernel_f))
  | c = f * c_tm1 + i * self.activation(x_c + K.dot(h_tm1 * rec_dp_mask[2],
  | self.recurrent_kernel_c))
  | o = self.recurrent_activation(x_o + K.dot(h_tm1 * rec_dp_mask[3],
  | self.recurrent_kernel_o))
  | h = o * self.activation(c)
  | if 0 < self.dropout + self.recurrent_dropout:
  | h._uses_learning_phase = True
  | return h, [h, c]

Thanks.

**Comment by samre12** [comment]
Please refer to Colah's Blog on [Understanding LSTMs](http://colah.github.io/posts/2015-08-Understanding-LSTMs/) for a more detailed explanation of internal states of LSTMs and as to how c and h change with each timestep.
