### ISSUE TITLE
Modelcheckpoint issue while loading model

### ISSUE THREAD

**Issue by achalshah20** [fchollet/keras#7335]
Hi All, 

I am running following code for model checkpoint.

```
filepath="weights-improvement-{epoch:02d}-{val_SNR:.2f}.hdf5"
        modelCheck = ModelCheckpoint(self.args.logname +"/"+filepath, monitor='val_SNR', verbose=1,save_best_only=True, mode='max',save_weights_only=True)

    
        print("Starting training... It will take a while")
        model.fit(X_train,
                  Y_train,
                  epochs=self.args.epochs,
                  callbacks=[tensorboardCallback,modelCheck],
                  validation_data=(X_val,Y_val),
                  batch_size=self.args.batch_size)
```

And below code for loading weights
```
        model = self.create_model() # This will build my dnn model
        model.load_weights("One of the weight improvement files")
```

I am getting this error:
`ValueError: You are trying to load a weight file containing 1 layers into a model with 19 layers.
`

So, modelcheckpoint only stores weight improvement? It doesn't save the actual weights of all the layers after each epoch?

**Comment by YaronBlinder** [comment]
Were you able to solve this?

**Comment by intohole** [comment]
u get solution? same error in my code,this bug fixed?

**Comment by achalshah20** [comment]
This is very old issue so I don't remember the exact problem. But you can post you code and I can help you! 

Did you use model API to build model?
model = Model(inputs=a, outputs=b)
