### ISSUE TITLE
Unclear error message with model.fit/fit_generator

### ISSUE THREAD

**Issue by gowtham1997** [fchollet/keras#7354]
Hello,
I was trying to make a model with multi-inputs and outputs:

`model = Model(inputs=[input_a, input_b], outputs= [output_a, output_b]) 
model.fit_generator(data_generator(True, batch_size=batch_size),
                    steps_per_epoch=train_steps,
                    epochs=20)
`
^ data_generator returns two inputs and a target ( [X1, X2], y)
and I got this error:
ValueError: The model expects 2 input arrays, but only received one array. Found: array with shape (32, 1).

It was confusing as I was passing two input_arrays. It turned out that I had to pass two targets for two outputs, which was not clear from the error. Is this the intended behavior or should it be addressed?

Thanks

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [X] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by PavlosMelissinos** [comment]
That's a peculiar bug...

If the generator returns values like this: ([input_a, input_b], output), then a model that accepts two inputs and two outputs shouldn't complain about receiving one input.
