### ISSUE TITLE
a question about the training with low memory

### ISSUE THREAD

**Issue by Fahim7** [fchollet/keras#7361]
Hello,

I have a question about the training procedures. 
I have GPU with low memory so I can't increase my batch sizes(up to 4 images), therefore I want to train a model in a way that the networks update the weights after some batch iterations not in every batch iteration.  Is there a way in keras to do this? 
Or, Does anyone know a solution to increase batch size with low memory?

Thanks

**Comment by td2014** [comment]
@Fahim7 .  This might be helpful reading:  https://keras.io/getting-started/faq/#how-can-i-use-keras-with-datasets-that-dont-fit-in-memory
Thanks.

**Comment by Fahim7** [comment]
Thanks, I use this for loading and training. 
With this issue I can use only batch size= 4. I want a method to update the weights after for example 10 batches and don't update after each batch. 
fit_generator and train_on_batch also update the weights after each batches....

**Comment by AyanKumarBhunia** [comment]
Hi, 
Say, for example, I am using l2_regularization 
Tensorflow has - tf.nn.l2_loss
Can I use this?
1. K.sum(K.square(K.abs(Weights)))
2. tf.nn.l2_loss(Weights)

Can I use this interchangeably while using Keras(tensorflow backend)?
