### ISSUE TITLE
Bidirectional wrapper does not allow specifying initial state for RNN layer

### ISSUE THREAD

**Issue by marcoleewow** [fchollet/keras#7365]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

rnn_size = 10
init = K.variable(value=np.zeros(rnn_size), dtype='float64', name='init_state')
gru_1 = GRU(rnn_size)(x, initial_state=init)

runs without error but running

rnn_size = 10
init = K.variable(value=np.zeros([rnn_size, 2]), dtype='float64', name='init_state')
gru_2 = Bidirectional(GRU(rnn_size))(x, initial_state=init)

gives
TypeError: call() got an unexpected keyword argument 'initial_state'

**Comment by bchu** [comment]
Still running into this issue.
