### ISSUE TITLE
How to apply gaussian blur using my own keras layer

### ISSUE THREAD

**Issue by Kay1794** [fchollet/keras#7372]
Hi all, I was struggling with creating a new layer to add gaussian blur to the INPUT layer. 

The shape of gaussian kernel size is (1,1,5,5) which is precalculated(referring to 'g_filter' in the code belew)and the input shape should be (none,3,32,32) since the input shape of my INPUT layer is (3,32,32)

Below is the main code if my def call(self, x, mask = None) function. What I want to do is to create a gaussian blured input which just like the cv2 function `cv2.GaussianBlur(img,(5,5),1.0)` does to the img.
`    def call(self, x, mask = None):
        
        input_shape = K.shape(x)
        if self.dim_ordering == 'th':
            num_rows = input_shape[2]
            num_cols = input_shape[3]

        elif self.dim_ordering == 'tf':
            num_rows = input_shape[1]
            num_cols = input_shape[2]

        outputs = []
        g_filter = make_kernel(1.0)
        if self.dim_ordering =='th':
            for i in range(3):
                blur =  x[input_shape[0], i,:,:]
                blur = K.reshape(blur,(1,1,num_rows,num_cols))
                blur = K.conv2d(blur,kernel=g_filter, padding='same',data_format='channels_first')
                outputs.append(blur)

        outputs = K.reshape(outputs,(input_shape[0],self.num_channels,num_rows,num_cols))`

While I got the error:
Traceback (most recent call last):
  File "~/gbl_test.py", line 225, in <module>
    model.fit(X_train, y_train, epochs=1, batch_size=256, callbacks=[csv_logger, LearningRateScheduler(step_decay)])
  File "/Library/Python/2.7/site-packages/keras/engine/training.py", line 1507, in fit
    initial_epoch=initial_epoch)
  File "/Library/Python/2.7/site-packages/keras/engine/training.py", line 1156, in _fit_loop
    outs = f(ins_batch)
  File "/Library/Python/2.7/site-packages/keras/backend/theano_backend.py", line 1196, in __call__
    return self.function(*inputs)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/Library/Python/2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
IndexError: index out of bounds
Apply node that caused the error: Subtensor{int64, int64}(/main_input, ScalarFromTensor.0, Constant{0})
Toposort index: 133
Inputs types: [TensorType(float32, 4D), Scalar(int64), Scalar(int64)]
Inputs shapes: [(10, 3, 32, 32), (), ()]
Inputs strides: [(12288, 4096, 128, 4), (), ()]
Inputs values: ['not shown', 10, 0]
Outputs clients: [[InplaceDimShuffle{x,x,0,1}(Subtensor{int64, int64}.0)]]

I am new to keras and theano. I'll be so grateful if anyone can help.

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by zwh42** [comment]
same problem here. Did anyone have a solution here?
