### ISSUE TITLE
Feature matching in GAN

### ISSUE THREAD

**Issue by xcszbdnl** [fchollet/keras#7376]
Hi, I want to implement feature matching techniques in GAN. See this paper [https://arxiv.org/pdf/1606.03498.pdf](https://arxiv.org/pdf/1606.03498.pdf)
How can I do it in keras?

**Comment by zhongsheng-chen** [comment]
> Hi, I want to implement feature matching techniques in GAN. See this paper https://arxiv.org/pdf/1606.03498.pdf
> How can I do it in keras?

Hi there, I suffered from the same issue. Did u get solved. if so, would u mind sharing the code?
