### ISSUE TITLE
Cost function that isn't just y_pred, y_true?

### ISSUE THREAD

**Issue by stulacy** [fchollet/keras#7379]
I have a cost function that in addition to using the overall network output, needs to multiply it by another function of the network weights (it's actually the partial derivative of the output with respect to one of the inputs). Custom cost functions are parameterised as `f(y_true, y_pred)`, and so cannot be used to provide this second function of the weights that I want.

I've seen a [similar issue before](https://github.com/fchollet/keras/issues/369) where @shamidreza states that they had to use Theano for this functionality.

Is it still the case that this is the best option? I've only used Keras in R before so have no experience with either TensorFlow or Theano, would either be suitable in R?

**Comment by td2014** [comment]
@stulacy .  This might be something you can implement in a custom loss function using the following approach (not sure, but offering as a suggestion).  (1) The current weights of the model are available to your custom cost function via model.get_weights,  (2) consider using the tensorflow call: to symbolically compute the partial derivative in question (using "zero" for the predicted output so that the gradient is the model output wrt to node weights.)  https://www.tensorflow.org/api_docs/python/tf/gradients

3) Write the final cost expression in terms of these derived parameters.

Experimental idea that may or may not work, but wanted to give a suggestion.  Hope this helps.  Thanks.

**Comment by hgaiser** [comment]
It sounds like this [example implements](https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py) what you need. It's not ideal in my opinion, feels a bit like a workaround, but it appears to work.

**Comment by stulacy** [comment]
I think I've understood how to structure my network to use this cost function by using the approach shown by @hgaiser where the model is fitted using a large network with a custom layer calculating loss, but the model used in practice takes its output from an intermediary layer of interest. However, I'm currently having problems determining the output of one layer as the derivative of a previous one with respect to an input.


[prevsim_short.csv.zip](https://github.com/fchollet/keras/files/1170624/prevsim_short.csv.zip)

I'm trying to use the parametric likelihood function for survival analysis, [see the equation on the last page here](http://data.princeton.edu/pop509/ParametricSurvival.pdf). To do so, I need the intermediary function S(t) and lambda(t), where lambda(t) = -S'(t) / S(t). S(t) is the output of the sigmoid layer. I thought I could use `tf.gradients` to calculate S'(t) as @td2014 suggested but I get an error message:

Traceback (most recent call last):
  File "/home/stu/repos/ANNsurv/Python/continuous_nn.py", line 177, in <module>
    main()
  File "/home/stu/repos/ANNsurv/Python/continuous_nn.py", line 173, in main
    build_manual(data)
  File "/home/stu/repos/ANNsurv/Python/continuous_nn.py", line 152, in build_manual
    verbose=0)
  File "/home/stu/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/engine/training.py", line 1430, in fit
    initial_epoch=initial_epoch)
  File "/home/stu/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/engine/training.py", line 1085, in _fit_loop
    callbacks.on_batch_end(batch_index, batch_logs)
  File "/home/stu/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/callbacks.py", line 113, in on_batch_end
    callback.on_batch_end(batch, logs)
  File "/home/stu/.virtualenvs/keras/local/lib/python2.7/site-packages/keras/callbacks.py", line 218, in on_batch_end
    self.totals[k] += v * batch_size
ValueError: operands could not be broadcast together with shapes (32,1) (8,1) (32,1) 

32 is the batch size but I have no idea where 8 is from. I could directly calculate S'(t) but this would require capturing previous network weights and the pre-activation levels of hidden neurons. My code is below, and I've attached the CSV file that `data` comes from.

    X_train = data[:, (0, 2, 3)]
    Y_train = data[:, 1]
    covar_ip = X_train[:, (1, 2)]
    time_ip = X_train[:, 0]
    status_ip = Y_train

    # Input layers
    covars = keras.layers.Input(shape=(2, ), name="covariates")
    time = keras.layers.Input(shape=(1, ), name="time")
    status = keras.layers.Input(shape=(1, ), name="status")
    input_layer = keras.layers.concatenate([covars, time], name="all_covars")

    # Computational layers
    hidden = keras.layers.Dense(2, activation='relu', name="hidden")(input_layer)
    survival = keras.layers.Dense(1, activation='sigmoid', name="survival")(hidden)

    # Intermediary layers to calculate log LH
    survival_deriv = keras.layers.Lambda(lambda inputs: keras.backend.gradients(inputs[0], [inputs[1]]),
                                         output_shape=(1, ),
                                         name="survival_deriv")([survival, time])
    hazard = keras.layers.Lambda(lambda inputs: -inputs[1] / inputs[0],
                                 output_shape=(1, ),
                                 name="hazard")([survival, survival_deriv])

    # Class that calculates logLH
    class LogLHLayer(keras.layers.Layer):
        def __init__(self, **kwargs):
            self.is_placeholder = True
            super(LogLHLayer, self).__init__(**kwargs)

        def loglh_loss(self, st, ht, status):
            loss = keras.backend.log(keras.backend.pow(ht, status) * st)
            return loss

        def call(self, inputs):
            st, ht, status = inputs
            print inputs
            print ht
            loss = self.loglh_loss(st, ht, status)
            self.add_loss(loss, inputs=inputs)
            return st # Doesn't actually use layer output

    # Inputs are S(t), h(t), delta(t)
    logLH = LogLHLayer(name='logLikelihood')([survival, hazard, status])

    loss_model = keras.models.Model(inputs=[covars, time, status],
                                    outputs=logLH)

    # Just test it for now
    loss_model.compile(optimizer='rmsprop',
                       loss=None)

    #keras.utils.vis_utils.plot_model(loss_model, to_file="loss_model.png")
    loss_model.fit([covar_ip, time_ip, status_ip],
                   batch_size=32, epochs=20,
                   shuffle=True,
                   verbose=0)

**Comment by stulacy** [comment]
I'm going to close this issue as the [custom Layer method](https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py) method suggested by @hgaiser works for my use case. Essentially rather than adding a loss function explicitly, you create a custom layer that calculates the loss. When using the network for prediction you create a new model that uses an earlier layer as the output of interest.

**Comment by cam333** [comment]
Any chance you could show an example of how you implemented this in keras for R? 
If you in fact did add the custom layer in R. Thanks.

**Comment by tomwesolowski** [comment]
`Model.compile(...)` function takes `target_tensors` as argument. You can use it with extended output of your model.
