### ISSUE TITLE
Possible duplication (bug) in ImageDataGenerator outputs?

### ISSUE THREAD

**Issue by yliu7366** [fchollet/keras#7396]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short)

Below is my simple code to use ImageDataGenerator to do some data augmentation. Let's say I have 1000 input cat images, I want to use ImageDataGenerator to augment each image 20 times, so totally I should get 1000*20 = 20,000 augmented images. However, the following code only produces < 10,000 files. The output files have a 'cat_0_xxxx.jpeg' pattern in filenames where xxxx goes from  0 to 9999, does that mean ImageDataGenerator won't go beyond 10,000 files? I would expect it will save 'cat_1_xxxx.jpeg" after saving cat_0_9999.jpeg but that did not happen. Is this a bug?

BTW, I installed Keras using pip: pip install keras, the installed version is keras-2.0.6.tar.gz.

from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import glob
import os, sys

datagen = ImageDataGenerator(
            rotation_range=40,
            width_shift_range=0.2,
            height_shift_range=0.2,
            shear_range=0.2,
            zoom_range=0.2,
            horizontal_flip=True,
            fill_mode='nearest')
            
path = 'test20170721/train/cats'
outPath = 'test20170721/augmentation/cats'
files = glob.glob(path + '/*.jpg')

for file in files:
  print file
  img = load_img(file)
  x = img_to_array(img)
  x = x.reshape((1,) + x.shape)
  
  i = 0
  for batch in datagen.flow(x, save_to_dir=outPath, save_prefix='cat', save_format='jpeg'):
    i += 1
    if i > 20:
      break

**Comment by yliu7366** [comment]
Update:

I have modified my code to group augmented image files into folders. For example, for input image 'cat.0.jpeg', I will create a 'cat.0' folder and save the 20 augmented images under the 'cat.0' folder. I repeated this for all 1000 input images, and still there are file name duplication problems in ImageDataGenerator: for example, the cat.83 folder has only 18 files, a few other folders contains 19 instead of 20 files. This seems to be a bug on  how ImageDataGenerator create output file names.

Code:

from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import glob
import os, sys
from os.path import basename

datagen = ImageDataGenerator(
            rotation_range=40,
            width_shift_range=0.2,
            height_shift_range=0.2,
            shear_range=0.2,
            zoom_range=0.2,
            horizontal_flip=True,
            fill_mode='nearest')
            
path = 'test20170721/train/cats'
outPath = 'test20170721/augmentation/cats'
files = glob.glob(path + '/*.jpg')

for file in files:
  img = load_img(file)
  x = img_to_array(img)
  x = x.reshape((1,) + x.shape)
  
  outPathX = outPath + '/' + os.path.splitext(os.path.basename(file))[0]
  os.mkdir(outPathX)
    
  i = 0
  for batch in datagen.flow(x, batch_size=1, save_to_dir=outPathX, save_prefix='cat', save_format='jpeg'):
    i += 1
    if i >= 20:
      break

**Comment by Dref360** [comment]
Yeah, Keras uses a hash between 0 and 9999. This should get updated maybe?

Code
https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py#L820

**Comment by yliu7366** [comment]
Hi Dref360,

There is an 'index' variable in the code so it should offset the limitation of the 0~9999 hashing. But in my test, the index is fixed to be '0', not sure why, seems that it is tied to batch_size and a 'current_index' variable but I tried batch_size=32 and index is still fixed to be '0'.

fname = '{prefix}_{index}_{hash}.{format}'.format(prefix=self.save_prefix,
                                                                  index=current_index + i,
                                                                  hash=np.random.randint(1e4),
format=self.save_format)

**Comment by Dref360** [comment]
I will be able to look at it somewhere around Thursday or Friday.

**Comment by Dref360** [comment]
Oh I see!!
You try to save the same image all the time. So you have a batch of 1 with a dataset of 1.

**Comment by yliu7366** [comment]
Thank you, but I have 1000 different images to flow through the data generator and the data generator will generate 20 different augmentation so totally I should get 1,000 x 20 = 20,000 augmented images. I am following this particular tutorial: https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html

However, in my test, Keras data generator only saved out ~8,774 augmented images. I have tried a batch of 1 with the dataset of 1000 and a batch of 32 with the dataset of 1000, the results are the same: only ~8,000 images saved out to disk.  I will do one more test to use larger batch size to see if the 'index' part in the prefix_index_hash file name pattern actually goes beyond '0'.

**Comment by skumarlabs** [comment]
I ran into same issue. were you able to fix this? @yliu7366 I am not able to generate more than 10k images per class.

**Comment by yliu7366** [comment]
Nope, I ended up not using the ImageDataGenerator.

**Comment by Jen-Bati** [comment]
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
datagen = ImageDataGenerator(shear_range=0.2, zoom_range=0.2) 

path=Path("test20170721/train/cats")
print(path)

j = 1

for f in path.glob("*.png"):
    img = load_img(f)  
    x = img_to_array(img) 
    # Reshape the input image 
    x = x.reshape((1, ) + x.shape)  
    i = 1

    # generate 5 new augmented images 
    for batch in datagen.flow(x, batch_size = 1, save_to_dir ='test20170721/augmentation/cats', save_prefix = str(j), save_format ='jpeg'):
        i += 1
        if i > 10: 
            break
    j += 1
