### ISSUE TITLE
TensorBoard Callback write_grads fails when using LSTM and embedding layer

### ISSUE THREAD

**Issue by Eadword** [fchollet/keras#7397]
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

The following error occurs when the TensorBoard callback is used and has `write_grads=True` with an embedding layer.

```
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [<tensorflow.python.framework.ops.IndexedSlices object at 0x7ff93c4a00f0>]. Consider casting elements to a supported type.
```

Code which can reproduce this:
```python
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense
from keras.callbacks import TensorBoard
import numpy as np


SEQUENCES = 5
TIME_STEPS = 10

model = Sequential()
model.add(Embedding(100, 4))
model.add(LSTM(32))
model.add(Dense(1))
model.compile(optimizer='rmsprop', loss='mse')

tensor_board = TensorBoard(log_dir='log', batch_size=2, write_graph=False,
                           write_grads=True, histogram_freq=4)

x_train = np.random.randint(100, size=(SEQUENCES, TIME_STEPS), dtype='int8')

y_train = np.random.rand(SEQUENCES)

model.fit(x_train, y_train, batch_size=2, epochs=4, shuffle=True, callbacks=[tensor_board])
```
Note, by simply setting `write_grads=False`, no errors occur.

I am running this with a GPU (GTX 1070) on Manjaro Linux. cuda 8.0.61-2, cudnn 6.0.21-2. Tensorflow back-end.

Hope this helps.

**Comment by ijustloveses** [comment]
same situation, please help
