### ISSUE TITLE
`trainable` flag not used in `Embedding` layer

### ISSUE THREAD

**Issue by matt-peters** [fchollet/keras#7399]
The master branch of keras does not pass the `trainable` flag when creating `Embedding` weights:

https://github.com/fchollet/keras/blob/master/keras/layers/embeddings.py#L95

This makes all `Embedding` layers trainable (silently, without notifying the user) regardless of the parameters passed to the constructor.

**Comment by fchollet** [comment]
See answer to: https://github.com/fchollet/keras/pull/7400
