### ISSUE TITLE
Feature request - datagen.flow_from_files

### ISSUE THREAD

**Issue by sachinruk** [fchollet/keras#7405]
So as you know there is already `datagen.flow_from_directory` which takes the images from whatever order that is in the directory. The function in itself is extremely useful in that we can rotate, zoom, resize the image.

However, it will be extremely useful if:
1. We have a `datagen.flow_from_files` function where we specify the files as say an array. This will help us resample images that have a under-represented class. It will also help with randomising the images so that we aren't limited to how they are ordered within the 'positive'/ 'negative' class folders (eg. in the cats vs dogs example in the blog)
2. (optional) A second function that lets us control the amount of zoom, rotation etc. Right now I do not know how much it zooms in, or rotates at each epoch when I specify the values as (0.1, 10). This would be useful if I could create my own generator function so that I can control the levels of zoom, rotations etc. with a for loop in my generator function.

I am happy to contribute if someone could point me to the code where I can create such a function.

**Comment by gewoonrik** [comment]
you can find the flow_from_files function here 
https://github.com/fchollet/keras/blob/ec39c35975906801d49ceab931f6b35deab8f438/keras/preprocessing/image.py#L463

it used the DirectoryIterator, which you can find here https://github.com/fchollet/keras/blob/ec39c35975906801d49ceab931f6b35deab8f438/keras/preprocessing/image.py#L898

**Comment by ahundt** [comment]
I made a proposal that would support this at https://github.com/fchollet/keras/issues/6538#issuecomment-302835861, let me know what you think over on #6538.
