### ISSUE TITLE
train_on_batch for multiple predictions

### ISSUE THREAD

**Issue by ftiguidou** [fchollet/keras#7424]
Hi,

I'm not pointing a problem, I'm just wondering how I can manage to do what I want. I explain myself : 
For an image X, the Y that I want to predict is a couple of numpy array [Y1, Y2]. Y1 is (38, 60, 18) shaped and Y2 is (38, 60, 72) shaped. As I am working with a big dataset, I would like to use the train_on_batch function. However, this function should take a numpy array of X  values (which is not a problem) and a numpy array of Y values. Because Y1 and Y2 are not of the same shape, I can't stack them into a single array, and using a list raise an exception because train_on_batch calls the Y shape. Does anyone has an idea about how I can trick that ?

Thanks for reading

**Comment by samre12** [comment]
If by "I want to predict is a couple of numpy array [Y1, Y2]", you mean that that you want to predict multiple outputs from the same model, you could opt for using functional api to build a model which allows a model to have multiple outputs and thus while using `train_on_batch`, you could supply the different outputs as a list and won't have to pass them in a single concatenated array.
