### ISSUE TITLE
VAE + Classification

### ISSUE THREAD

**Issue by mongoose54** [fchollet/keras#7427]
Hi all,

I am trying to modify the [VAE example ](https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder_deconv.py) for classification purposes. I want to use the latent variables of the VAE as input to the MLP classifier. Are the `z_mean` and `z_log_var` be concatenated and fed as an input to the MLP classifier? Or should it just be `z`? 

Thanks!

**Comment by ThitherShore** [comment]
It should just be `z`. Actually `z` is calculated by `z =  z_mean + K.exp(z_log_var) * epsilon`, see the sampling function defined in the code:
```
def sampling(args):
    z_mean, z_log_var = args
    epsilon = K.random_normal(shape=(batch_size, latent_dim),
                              mean=0., stddev=epsilon_std)
    return z_mean + K.exp(z_log_var) * epsilon
```

Then `z` is what we mean by "latent variables". You will want to put `z` as the input of your MLP.
