### ISSUE TITLE
Reshaping image data in Keras to match CNN requirements

### ISSUE THREAD

**Issue by malamo** [fchollet/keras#7438]
0down votefavorite | My input data's dimension is equal to `(500000,3253)`, 
When I try to execute this line in my code:
`model.fit(x_train, y_train, batch_size=100, epochs=100,verbose=0)`
 It gives me this error:

`ValueError: Error when checking input: expected conv1d_1_input to have 3 dimensions, but got array with shape (500000, 3253) `

So please how to reshape my data in order to have 3 dimensions ?

**Comment by thefiddler** [comment]
You can do this:
```python
# for theano backend
x_train = np.expand_dims(x_train, 1)
```
or
```python
# for tensorflow backend:
x_train = np.expand_dims(x_train, -1)
```
