### ISSUE TITLE
Calculating the output size in convolutional layers

### ISSUE THREAD

**Issue by vinayakumarr** [fchollet/keras#7452]
I am using the following layer like fully connected, convolutional 

Type, Input dimension, Kernel, Stride ,      Outputs
FC ,        32 ,                                            32
conv,     32x1,          4 ,        1 ,                  32x2
conv,     32x2,          2,         2 ,                 16x4
conv ,    16x4,          1,         1  ,                16x4
conv ,    16x4 ,         1,         1     ,             16x1

Could you please tell any formulae exist for calculating the outputs size in each and every layer.

**Comment by alexklibisz** [comment]
You can use the `model.summary()` function and it will print the output shape at each layer.

**Comment by vinayakumarr** [comment]
I have already have output shape here. Do you know how did we get this. Any mathematical equation or procedure to do this?

**Comment by vinayakumarr** [comment]
Type, Input dimension, Kernel,   Stride ,    Outputs
 FC ,                32 ,                                   32
conv,       32x1,                4 ,        1 ,         32x2

Do you know how did we get the 32*2 here

**Comment by alexklibisz** [comment]
@vinayakumarr Ah, I see. This blog post explains it very nicely: https://adeshpande3.github.io/adeshpande3.github.io/A-Beginner's-Guide-To-Understanding-Convolutional-Neural-Networks-Part-2/

**Comment by vinayakumarr** [comment]
This I had seen already. Could you please tell how I am getting 32*2 output in the above case.

**Comment by alexklibisz** [comment]
I'm not sure from your descriptions. Could you copy/paste the model.summary() output on here?

**Comment by vinayakumarr** [comment]
http://www.liangjy.com/pdf/NeuralCryptography.pdf

Paper link

**Comment by vinayakumarr** [comment]
In the above paper table 1

**Comment by alexklibisz** [comment]
Hmm, I'm not sure at first glance.. It's likely they're using a notation different from that of keras. You can probably still implement it with keras based on the layers they describe and then deduce what they meant with that notation.
