### ISSUE TITLE
Constraint on subset of weight matrix

### ISSUE THREAD

**Issue by stulacy** [fchollet/keras#7456]
I've got an MLP with an input layer connecting into a `Dense` layer. I currently have 3 inputs, the last of which must only have non-negative weightts, but for the other 2 covariates I don't want any restrictions.

Currently, my `Dense` layer is defined as:

    Dense(2, activation='relu',
          kernel_constraint=non_neg(), 
          kernel_initializer=RandomUniform(minval=0, maxval=2))

However, I'd ideally only apply this initialiser and constraint to the last input, i.e. the last row of the weight matrix. Is this possible?

**Comment by raghakot** [comment]
Implement custom constraint.

```
class NonNegLast(Constraint):
    def __call__(self, w):
        w[:, -1] *= K.cast(K.greater_equal(w[:, -1], 0.), K.floatx())
        return w
```

**Comment by stulacy** [comment]
It doesn't seem to like the slicing of the Tensor `w`, as it gives this error:

    w[:, -1] *= keras.backend.cast(keras.backend.greater_equal(w[:, -1], 0.), keras.backend.floatx())
    TypeError: 'Tensor' object does not support item assignment

Whereas if I remove the `[:, -1]` (actually shouldn't it be `[-1, :]` for the last row?) it runs fine.

**Comment by stulacy** [comment]
I had to separate the row of weights that I'm interested in and concatenate it with the rest of the weight matrix, rather than modify it in place.

    class NonNegLast(Constraint):
        def __call__(self, w):
            last_row = w[-1, : ] * keras.backend.cast(keras.backend.greater_equal(w[-1, :], 0.), keras.backend.floatx())
            last_row = keras.backend.expand_dims(last_row, axis=0)
            full_w = keras.backend.concatenate([w[:-1, :], last_row], axis=0)
            return full_w

**Comment by raghakot** [comment]
Ah yes. Glad you figured it out from there.

**Comment by shaifugpt** [comment]
@raghakot  How can we define such a custom constraint in a bidirectional wrapper, need two separate custom kernel constraints: one for the forward layer and other for backward layer?
