### ISSUE TITLE
LSTM layer sandwiched between two dense layers

### ISSUE THREAD

**Issue by julie-jiang-bose** [fchollet/keras#7457]
Bit new to RNNs so bear with me...

I want to create an RNN layer (LSTM maybe?) in between two dense layers, but I'm having issues with the correct ndims. 

    ValueError: Input 0 is incompatible with layer lstm_1: expected ndim=3, found ndim=2

This issue https://github.com/fchollet/keras/issues/915 suggested to use embedding or TimeDistributedDense layers, but embedding layers can only be used as the first layer (https://keras.io/layers/embeddings/) and I cannot find any documentation on TimeDistributed Dense. So I'm not sure how this would work...Suggestions?

**Comment by td2014** [comment]
@julie-jiang-bose .  A few thoughts that might help point in the right direction.  Does your input have shape (None, num_timesteps, num_features).  When I say "input", I mean the input to the first layer (which I guess is a dense layer).  The output from that dense layer, I think, should be something like (None, num_timesteps, num_output_elements) where num_output_elements is the number of output units of your Dense Layer.  The batch dimension is anything you want it to be (depending on the number of examples in your training set) but you don't specify it in Keras.  You should only be specifying (num_timesteps,num_features) in your input layer.  I hope this helps.  Thanks.
