### ISSUE TITLE
model.fit_generator(Sequence) incorrectly goes through data

### ISSUE THREAD

**Issue by alxndrkalinin** [fchollet/keras#7458]
- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

Keras 2.0.6, TF 1.2.1, Ubuntu 16.04.2 LTS, CUDA 8.0, cuDNN 6.0

Snippet: https://gist.github.com/alxndrkalinin/6cc4228e9178ec4af7b2696a0d1ad5a1

Seems like `model.fit_generator` incorrectly calls data generator based on `keras.utils.data_utils.Sequence`.
In [snippet example](https://gist.github.com/alxndrkalinin/6cc4228e9178ec4af7b2696a0d1ad5a1) with [custom generator as described in docs](https://keras.io/utils/), 20 training samples and batch size 4, `model.fit_generator` is called with `steps_per_epoch=5`, `epochs=3` without multiprocessing. Generator correctly returns 4 samples per batch.

But during training generator is called 25 times instead of `steps_per_epoch` x `epochs` = 15. Each unique batch requested 5 times instead of 3. In generator `on_epoch_end` is called 5 times.

Trying different parameters showed that `model.fit_generator` always does 2 more epochs compared to it's `epochs` parameter.

**Comment by myutwo150** [comment]
The default value for `max_queue_size` is 10, which is twice the number of your `steps_per_epoch `. The generator is called 10 times before the training begins to fill up the queue.

**Comment by alxndrkalinin** [comment]
@myutwo150 thanks, I didn't realize that it keeps queue full
