### ISSUE TITLE
Keras breaks with newest Theano - no such file or directory ... theano/tensor/c_code/dimshuffle.c

### ISSUE THREAD

**Issue by peschn** [fchollet/keras#7463]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

I have installed Theano with: pip install --no-deps git+https://github.com/Theano/Theano.git#egg=Theano

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

```python

model = Sequential()
model.add(Masking(...))
model.add(LSTM(....))
model.add(Dense(....))
model.compile()

model.fit_generator(...)
```

This snippet will fail, with whatever you put, in the `Masking` layer. I get:

```
Traceback (most recent call last):
  File "simply/models/recurrent/run.py", line 71, in <module>
    model.run(**params)
  File "/home/ubuntu/janus/simply/models/recurrent/model.py", line 57, in run
    dropout=dropout)
  File "/home/ubuntu/janus/simply/models/recurrent/helpers.py", line 19, in compile_model
    lstm = Masking(mask_value=0.)(inp)
  File "/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/keras/layers/core.py", line 62, in call
    boolean_mask = K.any(K.not_equal(inputs, self.mask_value),
  File "/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 620, in not_equal
    return T.neq(x, y)
  File "/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 492, in make_node
    DimShuffle, *inputs)
  File "/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 448, in get_output_info
    ['x'] * difference + list(range(length)))(input))
  File "/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/theano/tensor/elemwise.py", line 157, in __init__
    COp.__init__(self, [self.c_func_file], self.c_func_name)
  File "/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/theano/gof/op.py", line 1308, in __init__
    self.load_c_code(func_files)
  File "/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/theano/gof/op.py", line 1331, in load_c_code
    with _open_u(func_file) as f:
  File "/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/theano/gof/op.py", line 46, in _open_u
    return open(file, 'U')
IOError: [Errno 2] No such file or directory: '/home/ubuntu/miniconda2/envs/janus/lib/python2.7/site-packages/theano/tensor/c_code/dimshuffle.c'
```

Downgrading theano to a much earlier commit solves the issue.

**Comment by rdauria** [comment]
Same problem here: the entire c_code/ directory is missing:

```
ls /PATH/TO/lib/python2.7/site-packages/theano/tensor/
alt_gemm_common.c         blas_scipy.pyc            inc_code.py               opt.py                    slinalg.py                utils.py
alt_gemm_template.c       elemwise_cgen.py          inc_code.pyc              opt.pyc                   slinalg.pyc               utils.pyc
basic.py                  elemwise_cgen.pyc         __init__.py               opt_uncanonicalize.py     sort.py                   var.py
basic.pyc                 elemwise.py               __init__.pyc              opt_uncanonicalize.pyc    sort.pyc                  var.pyc
blas_c.py                 elemwise.pyc              inplace.py                raw_random.py             subtensor.py              xlogx.py
blas_c.pyc                extra_ops.py              inplace.pyc               raw_random.pyc            subtensor.pyc             xlogx.pyc
blas_headers.py           extra_ops.pyc             io.py                     shared_randomstreams.py   tests/                    
blas_headers.pyc          fft.py                    io.pyc                    shared_randomstreams.pyc  type_other.py             
blas.py                   fft.pyc                   nlinalg.py                sharedvar.py              type_other.pyc            
blas.pyc                  fourier.py                nlinalg.pyc               sharedvar.pyc             type.py                   
blas_scipy.py             fourier.pyc               nnet/                     signal/                   type.pyc                  

```

**Comment by harryxu-yscz** [comment]
exact same problem here ```IOError: [Errno 2] No such file or directory: '/Users/user/anaconda/envs/p2-kdxf/lib/python2.7/site-packages/theano/tensor/c_code/dimshuffle.c'```

@peschn Could you post the theano commit you installed on?

**Comment by peschn** [comment]
@harryxu-yscz I've used this commit: pip install --no-deps --no-cache-dir git+https://github.com/Theano/Theano.git@0282eac71106baa0c99af8ec98afe042b4e8d4d5

**Comment by ck37** [comment]
Also ran into this; reverting to the normal pip version of Theano works for me (Python 2.7, Ubuntu 16.10): `pip install theano`

**Comment by peschn** [comment]
The problem with reverting back to the pip version is, that it won't work
with cuDNN 6 (you'll get a warning message and it may fail).

  Peter Schneider
Co-Founder
<http://www.soma-analytics.com/> (GER) +49 173 6348 741
peter.schneider@soma-analytics.com <johann.huber@soma-analytics.com>
Website <http://www.soma-analytics.com/> LinkedIn
<https://www.linkedin.com/company/soma-analytics> Twitter
<https://www.twitter.com/SomaAnalytics> Facebook
<https://www.facebook.com/SomaAnalytics>
The Smart Way
to Beat Stress at Work
SOMA Analytics awarded €1.8M EU funding... Read more
<http://soma-analytics.com/soma-awarded-eu-funding.html>


SOMA Analytics UG (haftungsbeschränkt) Sitz: München Amtsgericht München
HRB 202498 Geschäftsführung: Johann Huber
SOMA Analytics UK Registered office: London Company No. FCO31359 Director:
Johann Huber

**Comment by HenryJia** [comment]
Manually copying the files across seems to fix it, however I'm still running into this issue with the mnist_cnn.py example https://github.com/Theano/Theano/issues/6224

**Comment by rdauria** [comment]
@HenryJia thanks

**Comment by tengyuma** [comment]
@HenryJia  somehow after manually downloading it, I got the error No valid section marker was found in file /home/tengyu/miniconda2/lib/python2.7/site-packages/theano/tensor/c_code/dimshuffle.c

**Comment by nouiz** [comment]
The problem was fixed in Theano. Update again to the dev version.
