### ISSUE TITLE
applications.resnet50 has superflous averagepooling layer

### ISSUE THREAD

**Issue by simonm3** [fchollet/keras#7471]
In applications.resnet50 there is an averagepooling layer at the end of the convolution layers. However in the "include_top" layers there is the option of adding globalaveragepooling or globalmaxpooling. 

It makes no sense to do averagepooling then globalaveragepooling. Therefore the averagepooling is superfluous.

**Comment by hgaiser** [comment]
Addresed in PR https://github.com/fchollet/keras/pull/7434 , but denied.

**Comment by fchollet** [comment]
We may revisit it at a time of major version change (since this "allows" us to introduce small breaking changes).
