### ISSUE TITLE
Output of K.mean() not a Keras tensor

### ISSUE THREAD

**Issue by berrendorf** [fchollet/keras#7479]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

The result of K.mean applied onto a Keras tensor is not a Keras tensor anymore.

```python
import keras

a = keras.Input(shape=(20, 20))
b = keras.backend.mean(a)

print(keras.backend.is_keras_tensor(a))  # Is true
print(keras.backend.is_keras_tensor(b))  # Is false
```

**Comment by fchollet** [comment]
A "Keras tensor" is a tensor that came from a layer. Backend functions are not layer, thus their output is not kosher. You can wrap them in a `Lambda` layer to get what you want though.

In the future we will consider automatic the wrapping process.
