### ISSUE TITLE
model.add(...) silently crashes when using cuDNN

### ISSUE THREAD

**Issue by benjaminalt** [fchollet/keras#7498]
When I run the example script provided [here](https://github.com/fchollet/keras/blob/master/examples/conv_lstm.py), the program just terminates after the first call to add() (line 17 in the script). I observe the same behavior with my own scripts: The first call of add() kills the program. No exception is thrown, no error message is shown, the program just terminates with exit code 0xC0000005. Everything worked fine before I installed cuDNN (and still works if I disable cuDNN), just very slowly.

Here is my setup:
OS: 64-bit Windows 10
Graphics card: Nvidia GeForce GT 730
Python: Python 2.7.13 (Anaconda 4.4.0 64-bit)
Keras: 2.0.6
Theano: 0.9.0
CUDA: 8.0.60
cuDNN: 5.1
Graphics driver: NVIDIA Graphics Driver 376.51

My .theanorc:

    [global]
    floatX = float32
    device = cuda0

    [lib]
    cnmem = 0.2

    [cuda]
    root = C:/Users/alt/Tools/cuda

    [dnn]
    library_path = C:/Users/alt/Tools/cuda/lib/x64
    include_path = C:/Users/alt/Tools/cuda/include

Script output:
   
    Using Theano backend.
    Using cuDNN version 5110 on context None
    Mapped name None to device cuda0: GeForce GT 730 (0000:01:00.0)

and then the process dies. Is this a known issue? Could it be a problem with my setup?

**Comment by mahnerak** [comment]
Definitely not a Keras issue. 
Most likely cuda/cuDNN are not installed correctly. I suggest you to reinstall both cuda and cuDNN, then open issue in theano repo or nvidia forums if problem is not solved.
