### ISSUE TITLE
no pip yet?

### ISSUE THREAD

**Issue by speedcell4** [fchollet/keras#75]
tried to install keras with `pip install keras`, but what I got looks like this:

    Collecting keras
      Could not find a version that satisfies the requirement keras (from versions: )
      No matching distribution found for keras`

**Comment by jfsantos** [comment]
You can install it with pip using the following command:

`pip install git+git://github.com/fchollet/keras.git`

The library is not available at PyPI yet as it is still alpha. We should probably think about releasing it on PyPI after we reach a stable version.

**Comment by pikeas** [comment]
+1! Tag with a version number < 1.0 and release on PyPi.

**Comment by speedcell4** [comment]
thx~
