### ISSUE TITLE
Difference between steps_per_epoch and epochs in model.fit_generator

### ISSUE THREAD

**Issue by NeilRon** [fchollet/keras#7506]
I have doubt about the parameter steps_per_epoch and epochs in model.fit_generator.

I found that below two functions work the same way.
`model.fit_generator(generate_arrays_from_file, steps_per_epoch=10, epochs=1)`
`model.fit_generator(generate_arrays_from_file, steps_per_epoch=1, epochs=10)`

Am I right? Or I can do something between epochs?

**Comment by ISosnovik** [comment]
You can use callbacks. In this case, some operations would be performed when the epoch is started/ended.

**Comment by NeilRon** [comment]
@ISosnovik Thank you for your answer!

**Comment by samre12** [comment]
`model.fit_generator` requires the input dataset generator to run infinitely. `steps_per_epoch` is used to generate the *entire dataset* once by calling the generator `steps_per_epoch` times where as `epochs` gives the number of times the model is trained over the *entire dataset*. 
As @ISosnovik pointed out, callbacks can be used to perform certain operations such as Tensorboard Logging (specific to Tensorflow backend), model checkpointing etc. at the end of each epoch.

**Comment by kartikeyaGUPTA45** [comment]
I have a doubt in what is the difference between steps_per_epochs and batch size
