### ISSUE TITLE
Error during installation: Setup script exited with error:

### ISSUE THREAD

**Issue by cosmos2006** [fchollet/keras#751]
Dear Fchollet,
The installation exited with the following error:

Command "/usr/bin/gfortran -Wall -g -L/usr/local/lib -L/sw/lib build/temp.linux-x86_64-2.7/scipy/cluster/_vq.o -L/usr/lib64/atlas -L/usr/lib64 -Lbuild/temp.linux-x86_64-2.7 -llapack -lptf77blas -lptcblas -latlas -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/scipy/cluster/_vq.so" failed with exit status 1

Please suggest the solution.
-------------------------------
The tail of error message is pasted below:
scipy/special/specfun/specfun.f: In function ‘fcoef’:
scipy/special/specfun/specfun.f:8757:0: warning: ‘jm’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cik01’:
scipy/special/specfun/specfun.f:12799:0: warning: ‘IMAGPART_EXPR <cw>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:12799:0: warning: ‘REALPART_EXPR <cw>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘airyb’:
scipy/special/specfun/specfun.f:7466:0: warning: ‘km2’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘ciknb’:
scipy/special/specfun/specfun.f:12449:0: warning: ‘IMAGPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:12449:0: warning: ‘REALPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cjynb’:
scipy/special/specfun/specfun.f:6844:0: warning: ‘IMAGPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:6844:0: warning: ‘REALPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘csphjy’:
scipy/special/specfun/specfun.f:1181:0: warning: ‘IMAGPART_EXPR <cs>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:1181:0: warning: ‘REALPART_EXPR <cs>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cjylv’:
scipy/special/specfun/specfun.f:1471:0: warning: ‘IMAGPART_EXPR <cfy>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:1471:0: warning: ‘REALPART_EXPR <cfy>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cisia’:
scipy/special/specfun/specfun.f:2093:0: warning: ‘bj[0]’ may be used uninitialized in this function [-Wuninitialized]
scipy/special/specfun/specfun.f: In function ‘clqn’:
scipy/special/specfun/specfun.f:2230:0: warning: ‘IMAGPART_EXPR <cqf0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:2230:0: warning: ‘REALPART_EXPR <cqf0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘airyzo’:
scipy/special/specfun/specfun.f:2383:0: warning: ‘u1’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:2366:0: warning: ‘u’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cjyva’:
scipy/special/specfun/specfun.f:3532:0: warning: ‘IMAGPART_EXPR <cs>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3532:0: warning: ‘REALPART_EXPR <cs>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3354:0: warning: ‘IMAGPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3354:0: warning: ‘REALPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3468:0: warning: ‘IMAGPART_EXPR <cju0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3468:0: warning: ‘REALPART_EXPR <cju0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3354:0: warning: ‘IMAGPART_EXPR <cyv1>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3354:0: warning: ‘REALPART_EXPR <cyv1>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3354:0: warning: ‘IMAGPART_EXPR <cyv0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3354:0: warning: ‘REALPART_EXPR <cyv0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3547:0: warning: ‘cg0’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3539:0: warning: ‘cyv0’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3499:0: warning: ‘IMAGPART_EXPR <cjv0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3499:0: warning: ‘REALPART_EXPR <cjv0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3529:0: warning: ‘cjv0’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cjyvb’:
scipy/special/specfun/specfun.f:3734:0: warning: ‘IMAGPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3734:0: warning: ‘REALPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3610:0: warning: ‘IMAGPART_EXPR <cyv0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:3610:0: warning: ‘REALPART_EXPR <cyv0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘ciklv’:
scipy/special/specfun/specfun.f:5460:0: warning: ‘IMAGPART_EXPR <cfk>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:5460:0: warning: ‘REALPART_EXPR <cfk>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘hygfx’:
scipy/special/specfun/specfun.f:5827:0: warning: ‘nm’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cchg’:
scipy/special/specfun/specfun.f:6133:0: warning: ‘IMAGPART_EXPR <cy1>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:6133:0: warning: ‘REALPART_EXPR <cy1>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:6088:0: warning: ‘IMAGPART_EXPR <chw>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:6088:0: warning: ‘REALPART_EXPR <chw>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘hygfz’:
scipy/special/specfun/specfun.f:6431:0: warning: ‘k’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:6365:0: warning: ‘IMAGPART_EXPR <zw>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:6365:0: warning: ‘REALPART_EXPR <zw>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cjyna’:
scipy/special/specfun/specfun.f:6741:0: warning: ‘IMAGPART_EXPR <ch0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:6741:0: warning: ‘REALPART_EXPR <ch0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:6629:0: warning: ‘IMAGPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:6629:0: warning: ‘REALPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘csphik’:
scipy/special/specfun/specfun.f:10294:0: warning: ‘IMAGPART_EXPR <cs>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:10294:0: warning: ‘REALPART_EXPR <cs>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:10237:0: warning: ‘IMAGPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:10237:0: warning: ‘REALPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cikvb’:
scipy/special/specfun/specfun.f:11331:0: warning: ‘IMAGPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:11331:0: warning: ‘REALPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cikva’:
scipy/special/specfun/specfun.f:11492:0: warning: ‘IMAGPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:11492:0: warning: ‘REALPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘clqmn’:
scipy/special/specfun/specfun.f:12194:0: warning: ‘IMAGPART_EXPR <cqf0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:12194:0: warning: ‘REALPART_EXPR <cqf0>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘cikna’:
scipy/special/specfun/specfun.f:12557:0: warning: ‘IMAGPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f:12557:0: warning: ‘REALPART_EXPR <cf>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/special/specfun/specfun.f: In function ‘stvhv’:
scipy/special/specfun/specfun.f:13117:0: warning: ‘bjv’ may be used uninitialized in this function [-Wmaybe-uninitialized]
scipy/stats/statlib/spearman.f:12.49:

      double precision zero, one, two, b, x, y, z, u, six,              
                                                 1
Warning: Unused variable 'z' declared at (1)
resetting extension 'scipy.odr.__odrpack' language from 'c' to 'f77'.
In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from scipy/cluster/_vq.c:257:
/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
scipy/cluster/_vq.c: In function ‘__pyx_fuse_0__pyx_f_5scipy_7cluster_3_vq_cal_M’:
scipy/cluster/_vq.c:1533:3: warning: implicit declaration of function ‘sgemm_’ [-Wimplicit-function-declaration]
scipy/cluster/_vq.c: In function ‘__pyx_fuse_1__pyx_f_5scipy_7cluster_3_vq_cal_M’:
scipy/cluster/_vq.c:1570:3: warning: implicit declaration of function ‘dgemm_’ [-Wimplicit-function-declaration]
In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h:317:0,
                 from scipy/cluster/_vq.c:258:
scipy/cluster/_vq.c: At top level:
/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/__ufunc_api.h:241:1: warning: ‘_import_umath’ defined but not used [-Wunused-function]
/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
/usr/lib/gcc/x86_64-redhat-linux/4.7.2/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
error: Setup script exited with error: Command "/usr/bin/gfortran -Wall -g -L/usr/local/lib -L/sw/lib build/temp.linux-x86_64-2.7/scipy/cluster/_vq.o -L/usr/lib64/atlas -L/usr/lib64 -Lbuild/temp.linux-x86_64-2.7 -llapack -lptf77blas -lptcblas -latlas -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/scipy/cluster/_vq.so" failed with exit status 1

**Comment by lukedeo** [comment]
This is a Scipy installation issue -- try installing Scipy separately, then installing Keras.

**Comment by cosmos2006** [comment]
Thanks for the prompt reply.
It was indeed a Scipy problem, which got resolved by unsetting all the LDFLAGS before installing scipy,  i.e.
> unset LDFLAGS
> python setup.py install

Keras is running on my machine now.
