### ISSUE TITLE
conda install -c conda-forge keras

### ISSUE THREAD

**Issue by Code4SAFrankie** [fchollet/keras#7518]
conda install -c conda-forge keras gives me

PackageNotFoundError: Packages missing in current channels:

  - keras

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

Even though it is listed under the search

**Comment by theseatoms** [comment]
FYI, this command just worked for me on macOS 10.12.4, so it's likely windows specific.

Though I wasn't able to locate keras at https://repo.continuum.io/pkgs/free/osx-64/. Maybe I looked in the wrong place.

**Comment by theseatoms** [comment]
Strike that. I'm encountering that same error message as OP when I run "conda create --name env python=3 keras" on my macOS 10.12.4 machine.

This is despite the fact that "conda install -c conda-forge keras" exited successfully.

**Comment by theseatoms** [comment]
In the end, I got keras installed within a conda environment by running the following three commands in order:

conda create --name env python=3
source activate env
conda install -c conda-forge keras

That may or may not be helpful for you.

**Comment by Code4SAFrankie** [comment]
Seems the server was just temporarily down
