### ISSUE TITLE
Support CNTK backend via Docker

### ISSUE THREAD

**Issue by nzw0301** [fchollet/keras#7525]
[Keras via Docker](https://github.com/fchollet/keras/tree/master/docker) does not support CNTK 　backend. Unfortunately, I don't know how to fix `Dockerfile` for CNTK support.

Could anyone fix it?  (cc @souptc )

**Comment by souptc** [comment]
Sure, I will take a look.

**Comment by nzw0301** [comment]
@souptc thank you so much!
