### ISSUE TITLE
How does repetition of layer name get treated in Keras?

### ISSUE THREAD

**Issue by vedhas** [fchollet/keras#7531]
This is a little basic question, but I couldn't find anything under the documentation, nor in the examples.
My question is how does following statement get interpreted in Keras?
`for numnodes in [10,20,30]:`
`    MyLayer1=Dense(numnodes)(MyLayer1)`

Is there a way I can freeze this layer from the Model level? I notice that I can run `model.get_layer('freezeThis').trainable=False` if I have 
`MyLayer1=Dense(10,name="freezeThis")(prev_layers)`
`for numnodes in [10,20,30]:`
`   MyLayer1=Dense(numnodes)(MyLayer1)`

I get error `keras all layer names should be unique` if I do 
`MyLayer1=Dense(10)(prev_layers)`
`for numnodes in [10,20,30]:`
`   MyLayer1=Dense(numnodes,name="freezeThis")(MyLayer1)`

Reason why I wondered about this question. Kindly reply! 

(Note: This is a reduced/simplified query. In the actual script, I have GRU, autoencoder, CNN and what not! Possible that I might have misunderstood something else. Is this a safe way to freeze the layers?)

UPDATE: Currently failing for the other alternative too. It cannot find the layer, debugging it, kindly ignore question for now..

**Comment by mahnerak** [comment]
I want to suggest you a very elegant way to do that.
First, encapsulate your multiple layers into one:
```python
part = Sequential(name='freezing_layer')
part.add(InputLayer(input_shape=(100,)))
for numnodes in [10, 20, 30]:
    part.add(Dense(numnodes))
```
Then use the `'freezing_layer'` to define the model.
```python
input_layer = Input(shape=(50,))
prev_layers = Dense(100) (input_layer)
my_layer = part(prev_layers) # here you apply encapsulated layers

model = Model(input_layer, my_layer)
model.summary()
```
This will print
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         (None, 50)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 100)               5100      
_________________________________________________________________
freezing_layer (Sequential)  (None, 30)                1860      
=================================================================
Total params: 6,960
Trainable params: 6,960
Non-trainable params: 0
_________________________________________________________________
```

In order to freeze layers, you can simply get the `'freezing_layer'` and make `trainable = False`:
```python
model.get_layer('freezing_layer').trainable = False
model.summary()
```
This time it will print 
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_2 (InputLayer)         (None, 50)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 100)               5100      
_________________________________________________________________
freezing_layer (Sequential)  (None, 30)                1860      
=================================================================
Total params: 6,960
Trainable params: 5,100
Non-trainable params: 1,860
_________________________________________________________________
```
