### ISSUE TITLE
epoch value in ModelCheckpoint is inconsistent

### ISSUE THREAD

**Issue by pisnxw** [fchollet/keras#7541]
Hi:
Keras offer a easy way to add epoch to the model name when saving 
https://github.com/fchollet/keras/blob/master/keras/callbacks.py#L400
`filepath = self.filepath.format(epoch=epoch, **logs)`

But with the code like below one, which is suppose to save model every 20 eopch:
```
checkpointer = ModelCheckpoint(filepath="{epoch:03d}"+".hdf5", period=20)
```
It save the model every 20 epochs like:
019.hdf5
039.hdf5

The model saving operation does happen after 20, 40 epoch were finished.
Is there a bug, or I missed something(?

thanks for your review

**Comment by rravu3** [comment]
Don't think it's a bug. The epoch value coming into the callback is zero indexed.

**Comment by ozabluda** [comment]
fixed in https://github.com/fchollet/keras/pull/8137
