### ISSUE TITLE
utils.to_categorical doesn't work for classes with negative numbers

### ISSUE THREAD

**Issue by ygorcanalli** [fchollet/keras#7549]
I'm using a dataset for binary classification that classes are -1 (negative) or 1 (positive), and the function `utils.to_categorical` understand all values as positive. I've solved the problem using a handmade encoding function:

```
def encode_target(y):
    y_encoded = np.zeros( (y.shape[0], 2) )
    
    y_neg_index = y == -1
    y_pos_index = y == 1
    
    y_encoded[y_neg_index,0] = 1
    y_encoded[y_pos_index,1] = 1

    return y_encoded
```

I'ts also possible reescale the target to [0, 1], but is intresting for usability that the native keras function can deal with it.

**Comment by mahnerak** [comment]
It's not bug, nor an issue.

Look at Keras utils documentation page: https://keras.io/utils/
The part referring to function `to_categorical` states:

> y: class vector to be converted into a matrix (integers from 0 to num_classes).

It clearly prohibits using any value except `0 ... num_classes-1`.
