### ISSUE TITLE
How to serialize model weights?

### ISSUE THREAD

**Issue by anjishnu** [fchollet/keras#755]
I tried using the model.to_json() function but it only outlines the overall structure of the model, doesn't serialize the weights. 

I want to serialize entire networks as snapshots as I train so I don't need to start from scratch if something kills my process.

**Comment by lukedeo** [comment]
Check out callbacks and `model.save_weights(...)` -- I think they're what you need.

**Comment by fchollet** [comment]
Right. It's the in keras.io FAQ.

**Comment by MartinThoma** [comment]
For people coming here from Google looking for a way to serialize a Keras model: [How can I save a Keras model?](http://keras.io/getting-started/faq/#how-can-i-save-a-keras-model)
