### ISSUE TITLE
model.predict function for Functional API

### ISSUE THREAD

**Issue by khizeramin** [fchollet/keras#7577]
===========================================================================
I have created a model using Keras functional api...

i'm passing 2 inputs as you can see in the code below...
but during prediction im getting the following error:
"InvalidArgumentError (see above for traceback): Incompatible shapes: [100,4] vs. [100,32]"
the size for both inputs are:
(100, 4)
please have a look at code... i'm not even sure if we can use predict function with functional api's

model_output = Model(inputs=[input1, input2], outputs=output_update)
targets_out = model_output.predict([inputdata1, inputdata2])

Thanks in advance

**Comment by mahnerak** [comment]
I'm pretty sure you are feeding tensors with wrong size numpy arrays.

Please add this code before those two lines.
```python
from keras import backend as K
print('keras tensor shapes:', K.int_shape(input1), K.int_shape(input2))
print('numpy array shapes:', inputdata1.shape, inputdata2.shape)
```
Run this and write here the ouput so we can investigate the shapes.
