### ISSUE TITLE
Examples to convert tensorflow trained model to Keras model

### ISSUE THREAD

**Issue by jerrypaytm** [fchollet/keras#7581]
It would be nice to include an example showing how to programmatically convert a tensorflow model to keras model such that model learns from Tensorflow can be imported into Keras for further development/experiment.

**Comment by Dref360** [comment]
TF is much more flexible than Keras. Making a parser from TF to Keras would be a humongous task.
Has anyone started a project like that?

TF at its core has no concept of `layers` it's just a big graph.

**Comment by dextroza** [comment]
How can I convert a. pb file to .h5.file? I have frozen_inference_graph.pb from tensorflow, and I need to have h5 format for loading weights in Keras

**Comment by bottydim** [comment]
@dextroza @GustavZ I think you might benefit from this issue: 
https://github.com/keras-team/keras/issues/8026

> If you want to convert only weights (suppose you have code for the same model), you have to create model with random weights (you can find InceptionV3 in keras.applications) then read the TensorFlow .ckpt file with tf.train.NewCheckpointReader then call set_weights() method for each corresponding layer.

**Comment by dextroza** [comment]
@bottydim thank you for the suggestion!

**Comment by nyck33** [comment]
This repo has a .ipynb notebook for this.
https://github.com/nyoki-mtl/keras-facenet/blob/master/notebook/tf_to_keras.ipynb
