### ISSUE TITLE
I'm passing a correct shaped list of arrays but I get this error ValueError: Error when checking target: expected dense_1 to have shape (None, 10) but got array with shape (19 541, 1)

### ISSUE THREAD

**Issue by Abner77** [fchollet/keras#7587]
Hi. I'm stuck with what I think it's very strange issue.... 

Heres is my model, it's a recurrent LSTM network....

def create_model():
    model = Sequential() 
    
    #primera capa, esta retorna secuencias.....
    model.add(keras.layers.LSTM(input_dim=lengthvector, output_dim=20, return_sequences=True))  
    model.add(Dropout(0.2))  
    model.add(keras.layers.LSTM(20, return_sequences=False))
    model.add(Dropout(0.2))
    model.add(Dense(output_dim=lengthvector, activation='sigmoid'))   
    
    model.compile(loss='mse', optimizer='rmsprop', metrics=['accuracy'])
 
    return model

In my entry point i have this.
#this gets lists of shape 
    x_train, y_train = load_data('d:\\datosdax\\VectoresVelas2017.txt')    
    print (str(len(x_train)) +  " - " + str(len(x_train[0])) + " - " + str(len(x_train[0][0])))
    print (str(len(y_train)) +  " - " + str(len(y_train[0])))   
   **#the two above lines of code return 
   #19541 - 30 - 10
   #19541 - 10 as intended**
    model = create_model()    
    #this is for tensorboard
    tbCallBack = keras.callbacks.TensorBoard(log_dir='C:\\Users\\David\\Tensorboardlogs\\',        histogram_freq=0, write_graph=True, write_images=True) 

   #the issue
    model.fit(x_train, y_train, epochs=epochs, validation_split=0.0, callbacks=[tbCallBack], shuffle=False, batch_size=500)       
**#here, at the above line i get this error.**

> Traceback (most recent call last):
>   File "C:\Users\EXCC0176\Documents\Visual Studio 2015\Projects\LSTMDAXv1\LSTMDAXv1\LSTMVelas2.py", line 125,
> in <module>
>     model.fit(x_train, y_train, epochs=epochs, validation_split=0.0, callbacks=[tbCallBack], shuffle=False, ba
> tch_size=500)
>   File "C:\Users\EXCC0176\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\models.py", line 863,
>  in fit
>     initial_epoch=initial_epoch)
>   File "C:\Users\EXCC0176\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py",
> line 1358, in fit
>     batch_size=batch_size)
>   File "C:\Users\EXCC0176\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py",
> line 1238, in _standardize_user_data
>     exception_prefix='target')
>   File "C:\Users\EXCC0176\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py",
> line 140, in _standardize_input_data
>     str(array.shape))
> ValueError: Error when checking target: expected dense_1 to have shape (None, 10) but got array with shape (19
> 541, 1)

I don't understand, I have a previous example from which this is derived, which works nice (the vectors representes characters instead of vectors that represents candlesticks), same dimensions in both lists x_train, y_train, but this, keras insists I'm passing a 19541, 1 vector when as you can see in the lines above when I print the dimensions of the data it's a 19541, 30, 10 for x_train, and 19541, 10 as it's intended. 

What am I missing? 

Thanks in advance....

**Comment by Abner77** [comment]
At the end, the problem seem to be the length of the sequence, not the dimensions..... 
Sorry.

**Comment by shivargha98** [comment]
What do you mean by length of the sequences?
