### ISSUE TITLE
Wrong result when passing K.cumsum() a sub-tensor

### ISSUE THREAD

**Issue by Niwis** [fchollet/keras#7592]
Hi,

I'm using the current version of Keras with Theano as backend. When passing `K.cumsum()` a hyperplane of a tensor, it returns a wrong result. See following example:
```
from keras import backend as K
>>> a = K.variable([[1, 2], [3, 4]])
>>> b = K.variable([2, 4])
>>> c = a[..., 1]
>>> K.eval(c)
array([ 2.,  4.], dtype=float32)
```
so that `b` and `c` should be the same. But
```
>>> K.eval(k.cumsum(b))
array([ 2.,  6.], dtype=float32)
>>> K.eval(k.cumsum(c))
array([ 1.,  4.], dtype=float32)
```

**Comment by mahnerak** [comment]
Please check both your Theano version.
With the latest Keras and Theano, it runs correctly and outputs `array([ 2.,  6.], dtype=float32)` for both.
Most probably it's Theano bug.

**Comment by Niwis** [comment]
That's strange. Theano is also up-to-date (even reinstalling didn't help), so it's probably some system bug. I will consider switching the backend, and in the meanwhile, `K.cumsum(a)[..., 1]` does the job.
Thanks for the help!
