### ISSUE TITLE
AttributeError: 'Model' object has no attribute 'predict_classes'

### ISSUE THREAD

**Issue by MuOtb** [fchollet/keras#7594]
predicts = KerasClassifier.predict(x_test)
print (accuracy_score(Y_test , predicts) * 100 )

I am using keras wrappers for scikit_learn (KerasClassifier) . I am also using Keras functional API style to write my code.  

When I try to predict the result i get the following error: 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-108-9bef79717a93> in <module>()
      1 print('Test accuracy')
----> 2 predicts = KerasClassifier.predict(x_test)
      3 print (accuracy_score(Y_test , predicts) * 100 )

C:\Users\***\Anaconda3\lib\site-packages\keras\wrappers\scikit_learn.py in predict(self, x, **kwargs)
    219         """
    220         kwargs = self.filter_sk_params(Sequential.predict_classes, kwargs)
--> 221         classes = self.model.predict_classes(x, **kwargs)
    222         return self.classes_[classes]
    223 

AttributeError: 'Model' object has no attribute 'predict_classes'

Any help?

Thanks .

**Comment by mahnerak** [comment]
May you provide more code of your network definition?
Also, please, check your Keras version.

**Comment by raofengyun** [comment]
The problem is that `predict_classes` method is only available for the `Sequential` class  but not for the `Model` class
