### ISSUE TITLE
Imbalanced Data with return_sequences and multi-labeling

### ISSUE THREAD

**Issue by SamantaGreen** [fchollet/keras#7595]
Hi,

I am trying to use keras for imbalance datasets (0.05 vs. 0.95).
I implemented it with return_sequences=true (output for each input) in RNN.
The output is 1 hot vector (for example with 7 outputs).

How should I do it? Should I use class_weight? how?
And how should I do it when I am using masking (I have 1 output neuron for all masked/padded input).

Thanks

**Comment by mahnerak** [comment]
I don't understand how you show the imbalance in your dataset with numbers 0.05 vs 0.95 if your prediction vector size is 7.

**Comment by SamantaGreen** [comment]
right I was wrong. The output vector contains 3 outputs (1 for masking, and 2 classes).
I am attaching the architecture to make it more clear:
![image](https://user-images.githubusercontent.com/30914133/29205291-9a3c5060-7e84-11e7-8a09-53cc7eb674aa.png)

**Comment by mahnerak** [comment]
So what shape does your data labels have?

**Comment by SamantaGreen** [comment]
I will wrote it like nlp problem).
input: (number of sentences, max size of sentences)
output:  (number of sentences, max size of sentences, number of labeling).
