### ISSUE TITLE
Tests don't run if Theano isn't installed

### ISSUE THREAD

**Issue by tleeuwenburg** [fchollet/keras#7601]
- [ yes ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ yes ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ no ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ yes ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

If you run "py.test" and don't have Theano installed, there is an immediate issue. I think better behaviour would be to run the tests on whatever backend(s) you have available, but I don't know if that's the right approach. I installed Theano but then ran into the same issue with cntk.

I was able to modify the relevant test so that it imported all available back-ends without failing. Please let me know if you would like a pull request for this change.

`(/Users/tjl/dev/envs/me) CSSVIC015225L:keras tjl$ py.test
Test session starts (platform: darwin, Python 3.6.1, pytest 3.1.3, pytest-sugar 0.8.0)
cachedir: .cache
rootdir: /Users/tjl/dev/source/keras, inifile: pytest.ini
plugins: sugar-0.8.0

――――――――――――――――――――――――――――――――――――――――――――――――― ERROR collecting tests/keras/backend/backend_test.py ―――――――――――――――――――――――――――――――――――――――――――――――――
ImportError while importing test module '/Users/tjl/dev/source/keras/tests/keras/backend/backend_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/keras/backend/backend_test.py:7: in <module>
    from keras.backend import theano_backend as KTH, floatx, set_floatx, variable
keras/backend/theano_backend.py:3: in <module>
    import theano
E   ModuleNotFoundError: No module named 'theano'

=================================================================== warnings summary ===================================================================
tests/keras/utils/data_utils_test.py::TestSequence
  cannot collect test class 'TestSequence' because it has a __init__ constructor

-- Docs: http://doc.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Results (2.85s):
`

**Comment by nicolewhite** [comment]
@tleeuwenburg I believe this is fixed in https://github.com/fchollet/keras/pull/7620. Should this be closed?

**Comment by tleeuwenburg** [comment]
Yes, thanks Nicole. I'll close it off now.
