### ISSUE TITLE
Shapes don't match

### ISSUE THREAD

**Issue by zsong** [fchollet/keras#7604]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [X] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [X] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

from keras import backend as K
tensor = K.one_hot(indices=3, num_classes=5)

The shape of this tensor is (1, 5). However Keras requires the shape to be (None, 1, 5) during the LSTM training process and throws this error

ValueError: Error when checking input: expected lstm_1_input to have 3 dimensions, but got array with shape (1, 5)
I traced down to the training.py, and I found the expected shape is (None, 1, 5).

I tried to use K.zeros(shape=(None, 1, 5)) to define the tensor, but I can't update the value at a specific index from 0 to 1.

Is there any way to make the one-hot array the correct shape? Thanks!

**Comment by mahnerak** [comment]
K.one_hot is intended to get indices array and return the same but encoded in one-hot format.
According to documentation:
```
Computes the one-hot representation of an integer tensor.
    # Arguments
        indices: nD integer tensor of shape
            `(batch_size, dim1, dim2, ... dim(n-1))`
        num_classes: Integer, number of classes to consider.
    # Returns
        (n + 1)D one hot representation of the input
        with shape `(batch_size, dim1, dim2, ... dim(n-1), num_classes)`
```
So, I guess you're doing something wrong by `K.one_hot(indices=3, num_classes=5)`.
What exactly you want to convert to one_hot? Maybe you missed a tensor write somewhere here.
