### ISSUE TITLE
Hi, I have two exactly similar architectures and inputs. But one of them throws ValueError. I have attached the screenshots in the comments. Am new to keras. What have I done wrong here ?

### ISSUE THREAD

**Issue by bhowmiks** [fchollet/keras#7605]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by bhowmiks** [comment]
Hi,
I have two exactly similar architectures and inputs. But one of them throws ValueError. Am new to keras, What could have gone wrong out here ?

the onbe that fails:-
![image](https://user-images.githubusercontent.com/12883340/29226397-8ef0432c-7eef-11e7-8e9c-983349aff3a5.png)

The one that works:-
![image](https://user-images.githubusercontent.com/12883340/29226543-0fb71670-7ef0-11e7-9336-80129da7f201.png)

**Comment by Dref360** [comment]
Hi!
This question seems best suited for StackOverflow. Could you post your issue there? Also, remember to close your issue if you do so!
Thanks!

PS: Seems like train_y has the shape [None,300] but your model is defined to receive [None,1] The error message is clear.

**Comment by bhowmiks** [comment]
Thanks Dref360 :)
