### ISSUE TITLE
KerasRegressor: cannot get model attributes

### ISSUE THREAD

**Issue by tawe141** [fchollet/keras#7608]
I don't see any way of getting any of the model's attributes, such as seeing a layer's weights and bias, in KerasRegressor. This is unfortunate, as Pipeline is quite convenient, and I'm reluctant to give it up. The closest I can get is getting `build_fn`. Is there some other way of getting a layer's weights in KerasRegressor that I'm missing?

**Comment by tawe141** [comment]
Never mind, found it. For those wondering, `KerasRegressor.model` returns the model used.

**Comment by smile-on** [comment]
> KerasRegressor.model returns the model used.
@tawe141 
I don't see how to get it too. Using keras 2.0.4 in python 3.6:

    kr = grid_result.estimator # keras.wrappers.scikit_learn.KerasRegressor
    kr.model

AttributeError: 'KerasRegressor' object has no attribute 'model'
