### ISSUE TITLE
Having multiple copies of a model trained on different data sets

### ISSUE THREAD

**Issue by meghmehta** [fchollet/keras#7610]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by meghmehta** [comment]
Hi,

I am not sure where the problem is coming from but when I save a model which is trained on a data set, and then when I create another model (same architecture) on another dataset....then if I load the previously trained model, the weights become random...it's as good as an untrained model so I am not sure why this is happening.

Best,

Megh

**Comment by meghmehta** [comment]
I get this error if I just create different instances of the model:
Cannot interpret feed_dict key as Tensor: Tensor Tensor("embedding_2_input:0", shape=(?, 43), dtype=int32) is not an element of this graph.

**Comment by mahnerak** [comment]
Please provide code for your model. I assume your model is not build right.
Also, you are saying the weights became random only since it performs equally good as random-initialized model?
