### ISSUE TITLE
Negative dimension size caused by subtracting 3 from 1 for 'conv2d_2/convolution'

### ISSUE THREAD

**Issue by datomnurdin** [fchollet/keras#7611]
I got this error message when declaring the input layer in Keras.

```
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv2d_2/convolution' (op: 'Conv2D') with input shapes: [?,1,28,28], [3,3,28,32].
```

My code is like this

```
model.add(Convolution2D(32, 3, 3, activation='relu', input_shape=(1,28,28)))
```

Sample application: https://github.com/IntellijSys/tensorflow/blob/master/Keras.ipynb

Please advice. Thank you.

**Comment by mahnerak** [comment]
Please use Keras 2 API. The way you define Convolution layers is outdated. 
Look Keras documentation to see how it have to be done.
Then report here whether problem still exists or not.

**Comment by datomnurdin** [comment]
I already fixed the problem, https://stackoverflow.com/questions/45645276/negative-dimension-size-caused-by-subtracting-3-from-1-for-conv2d-2-convolution/45647715#45647715.

**Comment by warpdriv** [comment]
@datomnurdin , that link fixed the same error I have. My line of code is (note the data_format:

`model.add(Convolution2D(32, (3, 3), activation='relu', input_shape=(1,28,28), data_format='channels_first'))
`

**Comment by VijetaTulsiyan** [comment]
@warpdriv 
Your code worked for me :)

model.add(Convolution2D(32, (3, 3), activation='relu', input_shape=(1,28,28), data_format='channels_first'))

**Comment by narmin-23** [comment]
> @datomnurdin , that link fixed the same error I have. My line of code is (note the data_format arg):
> 
> `model.add(Convolution2D(32, (3, 3), activation='relu', input_shape=(1,28,28), data_format='channels_first')) `

it solved my problem, thank you :)

**Comment by vamsitharun** [comment]
I am getting this error

> train.py:227: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), strides=(1, 1), padding="valid", kernel_initializer="orthogonal")`
>   x = Convolution2D(n_filters, kH, kW, subsample=(sH, sW),border_mode=border_mode, init=init_conv)(x)

Anyone Help me please

**Comment by pranjalsharma26** [comment]
ValueError: Negative dimension size caused by subtracting 4 from 1 for 'conv2d_7/convolution' (op: 'Conv2D') with input shapes: [?,6,1,1], [4,4,1,32].
I didn't get the solution to this error by applying the method that are suggested.
Please suggest some way to get rid of this issue.

**Comment by pranjalsharma26** [comment]
Sir @vamsitharun, you can solve this isse by providing paddind parameter as suggested below -
model.add(Conv2D(32, (3,3), activation='relu', padding='same',input_shape=(1,1,6), data_format='channels_first'))

**Comment by hyderit** [comment]
You can fix this problem throughout the entire CNN network by setting the `data_format=NHWC`

**Comment by Al-Badri179** [comment]
Despite the changing data format to be "data_format='channels_first'"  but I still have this issue:

"InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
	 [[{{node max_pooling2d_2/MaxPool}}]]"
any other solution?
