### ISSUE TITLE
Stateful GRU example

### ISSUE THREAD

**Issue by EderSantana** [fchollet/keras#763]
Guys, 

Check this example of a stateful GRU (hidden stated is not wiped out after everybatch) on the text generation example. It makes the initial state a shared variable and updated after each batch:

https://github.com/EderSantana/seya/blob/master/seya/layers/recurrent.py#L94-L96

It is also included a callback to reset it:
https://github.com/EderSantana/seya/blob/master/seya/callbacks.py#L22-L40

The full example is here:
https://github.com/EderSantana/seya/blob/master/examples/stateful_text_generation.py

Let me know what you guys think. Specially if worked on your computer or not :D 
I'd also appreciate some feedback on the logic and how to improve it.
Note one thing for instance, a `batch_size` is required when initializing the network. This forces a maximum value on the input batch length.

**Comment by erfannoury** [comment]
The callback only works on the `epochs` variable, wouldn't it be useful if it could work on the data in the mini-batch? In that case state could be cleared when EOF character is detected in the mini-batch.

**Comment by EderSantana** [comment]
Yeah, but Keras callbacks do not have access to the current batch though. This would have to change the way callbacks work. I've thought about callbacks with access to the batch before. 

But right now, using the knowledge of which batch you are and having the dataset, you will have to figure the EOF inside your `ResetRNNstate` function.

**Comment by erfannoury** [comment]
Also having the ability to access mini-batch content in the callbacks can somehow overcome the issue of variable-length input to RNNs.

> But right now, using the knowledge of which batch you are and having the dataset, you will have to figure the EOF inside your `ResetRNNstate` function.

But it won't produce the correct behavior, since the EOF might be placed anywhere in the mini-batch.

Only way to fix this, apparently, is to come up with _extended callbacks_ which have access to the mini-batch content, among other things that might be useful.

**Comment by EderSantana** [comment]
I believe we should open an issue and ask the opinion of others about that specifically. If we callbacks should or should not be able to see the current batch.

**Comment by erfannoury** [comment]
Yeah, I agree. I'm specifically concerned about how optimization is performed for mini-batches if an state reset happens half-way through the mini-batch. 
It may also be a good opportunity to see what other data is preferred to be available in a callback.

**Comment by EderSantana** [comment]
I don't think you will be able to do the reset in the middle of the batch. Unless you use Theano if statements inside your `_step` function. That would be more of an extension to your layer than to a callback.

**Comment by elanmart** [comment]
Why the model does not return a sequence?

**Comment by EderSantana** [comment]
@elanmart it does https://github.com/EderSantana/seya/blob/master/seya/layers/recurrent.py#L97-L99

**Comment by elanmart** [comment]
@EderSantana Lately I did not have much time to look at the code in detail, but the core model does not return a sequence of characters. Is this how karpathy's char-rnn worked as well? I thought the whole point of statefull RNNs was to allow learning from all the outputs in the sequence.

I'm talking about the line https://github.com/EderSantana/seya/blob/master/examples/stateful_text_generation.py#L58

**Comment by EderSantana** [comment]
This is how to original code was intended. See Keras' original example: https://github.com/fchollet/keras/blob/master/examples/lstm_text_generation.py#L56

**Comment by elanmart** [comment]
I know, but wasn't this only due to stateless nature of Keras' RNNs? The network had to re-discover the hidden state for each batch, which should be avoidable using statefull nets.

**Comment by LeavesBreathe** [comment]
@EderSantana , off topic, but just really want to say that I appreciate you creating this.

**Comment by EderSantana** [comment]
tkx @LeavesBreathe, I appreciate your feedback. Maybe you would also want to check out this new DRAW  example http://agnez.herokuapp.com . The code uses an adaptive hidden state, which is an alternative to stateful https://github.com/EderSantana/seya/blob/master/seya/layers/draw.py#L166-L172

**Comment by LeavesBreathe** [comment]
Thanks, I have much to learn so these are good resources for me to get a better understanding. I'm more focused on NLP right now. But I've read in a few places that stateful LSTM's and GRU's can be very useful. Anyways thanks!!!

**Comment by raingo** [comment]
@EderSantana could you please answer @elanmart 's question:

> I know, but wasn't this only due to stateless nature of Keras' RNNs? The network had to re-discover the hidden state for each batch, which should be avoidable using statefull nets.

I am also interested in. Thanks for creating the stateful example.

**Comment by EderSantana** [comment]
@raingo you are right... We had several discussions about this in Seya you can look for SGRU in the issues if you are interested. There is no need to "rediscover" the states indeed. And the good news is there is a PR to support steafulness natively over here as well :D https://github.com/fchollet/keras/pull/964

**Comment by LeavesBreathe** [comment]
>And the good news is there is a PR to support steafulness natively over here as well :D #964

Keras just gets better and better everyday.
