### ISSUE TITLE
Retrieve hidden states in LSTMs while training

### ISSUE THREAD

**Issue by v1nc3nt27** [fchollet/keras#7632]
I want to use an implementation of an attention mechanism by [Yang et al.][1]. I found a working implementation of a custom layer that uses this attention machanism [here][2]. Instead of using the output values of my LSTM:

    my_lstm = LSTM(128, input_shape=(a, b), return_sequences=True)
    my_lstm = AttentionWithContext()(my_lstm)
    out = Dense(2, activation='softmax')(my_lstm)

I would like to use the hidden states of the LSTM:

    my_lstm = LSTM(128, input_shape=(a, b), return_state=True)
    my_lstm = AttentionWithContext()(my_lstm)
    out = Dense(2, activation='softmax')(my_lstm)

But I get the error:

> TypeError: can only concatenate tuple (not "int") to tuple

I think I interprete the returning value of return_state incorrectly but I can't find any examples on how to do this. Is this working? Do I have to use it in combination with return_sequences? I also don't understand whether it returns all of the hidden states or only the last hidden state. 

Thanks!

  [1]: http://www.aclweb.org/anthology/N16-1174
  [2]: https://gist.github.com/cbaziotis/7ef97ccf71cbc14366835198c09809d2

**Comment by samre12** [comment]
`LSTM` with `return_sequences=True` returns the hidden state of the LSTM for every timestep in the input to the LSTM. For example, if the input batch is `(samples, timesteps, dims)`, then the call `LSTM(units, return_sequences=True)` will generate output of dimensions `(samples, timesteps, units)`.
However, if you also want the final internal cell state of LSTM, use `LSTM(units, return_sequence=True, return_state=True)` as in [Recurrent Layers](https://keras.io/layers/recurrent/)

**Comment by v1nc3nt27** [comment]
@samre12 Thanks for your answer. `return_sequences=True` returns the output states for each time step, but not the hidden (cell) states as far as I know. 
I want to have the hidden states of each time step, not only the internal one. As far as I understand it, in the paper they use the hidden states and these should refer to the internal states, not the output states.

**Comment by samre12** [comment]
@v1nc3nt27 , in the case of LSTM, there are two internal states, the hidden state, usually denoted by *h*, and the cell state usually denoted by *c*. There is as such no concept of *output state* for a LSTM. The hidden state *h* is output for every timestep the LSTM is unrolled.
`return_sequences=True` gives you the hidden state of the LSTM for every timestep.

**Comment by v1nc3nt27** [comment]
@samre12 That is quite confusing now. In the [wiki article for LSTMs](https://en.wikipedia.org/wiki/Long_short-term_memory) they talk of `h: output vector` and `c: cell state vector`. 
That would mean there is no unique terminology and I'd have to guess whether they use the cell or `"output" vector` whenever they talk about a `hidden vector`.
Also, did you see that [here](https://keras.io/layers/recurrent/) they write:

> return_sequences: Boolean. Whether to return the last output in the **output** sequence, or the full sequence.

> return_state: Boolean. Whether to return the last state in addition to the **output**.

**Comment by samre12** [comment]
@v1nc3nt27 , I agree with you that there is no unique terminology that is followed in the literature. However, in my opinion, it is the *hidden vector* that they consider whenever they mention *output vector*.

**Comment by v1nc3nt27** [comment]
@samre12 It might be, since I actually don't see a reason (doesn't have to mean anything, though) why you would skip using one of the trained matrices and take the cell state instead. I was just confused by the terminology. Thanks for your help.

**Comment by samre12** [comment]
@v1nc3nt27 Please close the issue if you think it is resolved. :)

**Comment by sharod** [comment]
Hi, using return_states=True and return_sequences=False I am able to get the value of the c and h. But after that I am doing model.fit() and then I want to print the values of c and h. But I am not being able to do that. I am only seeing tf.Tensor objects. I need to store these c and h values. Please help.

**Comment by samre12** [comment]
@sharod please elaborate your use case for storing the values of `c` and `h` and please provide some code that you are using.

**Comment by sharod** [comment]
@samre12 I need to store the value of c and h after training and store the model. So when I again load the model I need to initialize the states with the stored c and h. I need to do this during prediction as well. I need to predict on some test data and then store the resulting c and h. Again when i get more test data I need to load the model initialize the c and h with the stored values and continue with the prediction. My model is as follows:

inputs = Input(shape=(None,124))
lstm=LSTM(150, W_regularizer=l2(0.001), return_state=True)(inputs)
dense1=Dense(2)(lstm[0])
predictions=Activation("softmax")(dense1)
model= Model(inputs=inputs, outputs=predictions)

After that I am compiling the model and fitting it. The fitting line is as follows:

model.fit(X_train,Y_train,nb_epoch=100,batch_size=10,callbacks=callbacks_list,validation_data=(X_val, Y_val), verbose=1)

After this I need to store the values of c and h.

**Comment by vianamp** [comment]
Hi. I have the same question. I think using a custom loss function is the way to go, but I couldn't get this working yet. Here is my example code:

```python
def mymse(Yv, Yp):
    return K.mean(K.square(Yv-Yp), axis=-1) 

def get_model(seqlg,depth):
	x = Input(shape=(seqlg,))
	y = Embedding(input_length=seqlg, input_dim=depth, output_dim=2)(x)	
	z, sh, sc = LSTM(units=128, return_state=True)(y)
	z = Dense(1, activation='relu')(z)

	model = Model([x],[z,sh,sc])
	model.compile(loss=mymse, optimizer='rmsprop')
	return model
```
Basically you specify a model that returns the states (sh and sc), but this variables are not used for calculating the loss. As I said, not working yet.

**Comment by vianamp** [comment]
I think I found a solution. We can simply define two models that share variables. The 1st model only returns the target variable. The 2nd model returns the states in addition to target. See:

```python
def get_model(seqlg,depth):
	x = Input(shape=(seqlg,))
	y = Embedding(input_length=seqlg, input_dim=depth, output_dim=2)(x)	
	z, sh, sc = LSTM(units=128, return_state=True)(y)
	z = Dense(1, activation='relu')(z)

	model1 = Model(input=[x],output=[z])
	model2 = Model(input=[x],output=[z,sh,sc])
	model1.compile(loss='mse', optimizer='rmsprop')
	return model1, model2
```

So you can do: `model.fit(X,Y)` for training and `Y, Sh, Sc = model.predict(X)` to retrieve the states related to a particular input X. Not sure there is a best way to do that though.

**Comment by streamride** [comment]
@vianamp Can you please explain what model for predict and what for train ?

**Comment by vianamp** [comment]
Hi @streamride. I'm not sure what is your question.

**Comment by streamride** [comment]
@vianamp I mean, if I use your method get_model(), I get 2 models ( model1 and model2) , then how can I train model2 to use it for retrieve hidden states?

**Comment by vianamp** [comment]
@streamride , the beauty of it is that the models have shared variables by construction, which means you don't have to train model2. You only train model1 with `model1.fit(...)`. Then you do `model2.predict(...)` to retrieve the hidden states. Is that clear?

**Comment by streamride** [comment]
@vianamp yeah, now I get it, thank you!

**Comment by mohammadrezaebrahimi** [comment]
@streamride, thanks for the smart solution! Do you think this approach can give all the 'hidden states' for each time step during the training? I need to store all hidden states in an hdf5 file for investigating the dynamics of state changes and was wondering if I can use this approach or any other alternative. Thanks in advance!
