### ISSUE TITLE
who can point out how to implement like this

### ISSUE THREAD

**Issue by WangCharlie** [fchollet/keras#7662]
who can point out how to implement like this:
data/
train/
dogs1/
dog001.jpg
dog002.jpg
...
dogs2/
dog001.jpg
dog002.jpg
...
validation/
dogs/
dog001.jpg
dog002.jpg
...
dogs2/
dog001.jpg
dog002.jpg
...
and set the name of dog1 is dd,set the name of dog2 ff
then when i put an image it will show the result like this > this is a dog named dd&ff

**Comment by DEKHTIARJonathan** [comment]
Clearly not the correct place for this, please close the issue and go over StackOverflow

**Comment by GH1995** [comment]
closed #1077
