### ISSUE TITLE
Papers references in examples

### ISSUE THREAD

**Issue by omarcr** [fchollet/keras#767]
Some of the examples provided in https://github.com/fchollet/keras/tree/master/examples do not have the corresponding source/paper. Including would be very helpful to further understand the models.

**Comment by fchollet** [comment]
Not all of them are based on a paper. Which ones specifically?

**Comment by omarcr** [comment]
I am looking for the paper for mnist_cnn.py 
I don't think it is lenet ([LeCun et al., 1998]: Gradient-Based Learning Applied to Document Recognition) right?

**Comment by fchollet** [comment]
It's sort of a miniaturized version of a VGGNet. http://www.robots.ox.ac.uk/~vgg/research/very_deep/

**Comment by omarcr** [comment]
what about this one https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py
which model/paper did you use for that one?

**Comment by fchollet** [comment]
Same story. It's VGGNet-inspired.

**Comment by omarcr** [comment]
but where are the details of your "inspiration"?

**Comment by lukedeo** [comment]
Try reading the paper. It's quite clear.
