### ISSUE TITLE
CNN - Other pooling functions

### ISSUE THREAD

**Issue by tjurczyk** [fchollet/keras#768]
Hi,

I started using Keras recently and it is really great!
I needed to use an Average Pooling in my project, so I had to write my own custom class, because apparently Keras supports only Max function. I started actually wondering whether this option could be built in Keras? 
In MaXPooling2D class the following method is being called:

```
output = downsample.max_pool_2d(X, ds=self.poolsize, st=self.stride, ignore_border=self.ignore_border)
```

and max_pool_2d [actually supports different modes](http://deeplearning.net/software/theano/library/tensor/signal/downsample.html)

>- mode ({‘max’, ‘sum’, ‘average_inc_pad’, ‘average_exc_pad’}) – Operation executed on each window. max and sum always exclude the padding in the computation. average gives you the choice to include or exclude it.

**Comment by transcranial** [comment]
There's an active pull request: https://github.com/fchollet/keras/pull/522

@entron @fchollet What's the status? I agree it would indeed be useful, also including k-max pooling.
