### ISSUE TITLE
Cannot add new layers to pre-trained models for re-training. 'Model' object has no attribute 'add'

### ISSUE THREAD

**Issue by abhijitnathwani** [fchollet/keras#7680]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [Done ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [Done ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I have a saved a model using ```model.save()```. I'm trying to reload the model and add a few layers and tune some hyper-parameters, however, it throws the AttributeError.

Model is loaded using ```load_model()```.

I guess I'm missing understanding how to add layers to saved layers. If someone can guide me here, it will be great. I'm a novice to deep learning and using keras, so probably my request would be silly.

Snippet:
```
prev_model = load_model('final_model.h5') # loading the previously saved model.

prev_model.add(Dense(256,activation='relu'))
prev_model.add(Dropout(0.5))
prev_model.add(Dense(1,activation='sigmoid'))

model = Model(inputs=prev_model.input, outputs=prev_model(prev_model.output))
```
And the error it throws:

```
Traceback (most recent call last):
  File "image_classifier_3.py", line 39, in <module>
    prev_model.add(Dense(256,activation='relu'))
AttributeError: 'Model' object has no attribute 'add'

```

I know adding layers works on new Sequential() model, but how do we add to existing saved models?

Can you help @joelthchao @fchollet ?

**Comment by MatinHz** [comment]
I suppose you should probably write your code like this:

```
prev_model = load_model('final_model.h5') # loading the previously saved model.

top_model = Sequential()
top_model.add(Dense(256,activation='relu'))
top_model.add(Dropout(0.5))
top_model.add(Dense(1,activation='sigmoid'))

model = Model(inputs=prev_model.input, outputs=top_model(prev_model.output))

```

**Comment by joelthchao** [comment]
I think the model you load is not a `Sequential` model but `Model` for functional-API (`'Model' object has no attribute 'add'`). You should try @MatinHz 's approach.

`Sequential` model works well after `load_model`.
```python
from keras.models import load_model, Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(5, input_shape=(10,)))
model.save('test_model')

model = load_model('test_model')
model.add(Dense(1))
model.summary()
```

**Comment by abhijitnathwani** [comment]
Alright, thanks for the advice @MatinHz and @joelthchao . @MatinHz 's approach works just fine.I'll close this issue for now.
