### ISSUE TITLE
choose the specified GPU with tensorflow backend

### ISSUE THREAD

**Issue by WenmuZhou** [fchollet/keras#7737]
there are four graphics cards in my machine, I would like to use the specified graphics card, in the previous version of  keras and tensorflow, the following code is normal operation, but after updating to the latest version of keras and tensorflow, the following code does not work.

```python
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
from keras.backend.tensorflow_backend import set_session
config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.5
set_session(tf.Session(config=config))
```

**Comment by kkalavantavanich** [comment]
Hi, did you actually find a solution? I am facing the same problem.
