### ISSUE TITLE
Understanding input dimensions for LSTM

### ISSUE THREAD

**Issue by smolendawid** [fchollet/keras#7746]
For a long time I cannot figure out how to set input dimensions for RNN. 

My data is 5000 examples of 60 time series. For example 5000 records of 60 successive times. If they are regular it is ok, if not, we classify it as error. Shape=(5000, 60)

I would like to use a simple model

```
    model = Sequential()
    model.add(LSTM(256, activation='relu', input_shape=(60,1), return_sequences=True))
    model.add(Dense(num_classes, activation='softmax'))
```

It does not work.

How should I reshape features and change the input_shape?
Is it possible to classify data with not equal number of recodred  successive times (some records have 60, but other 20?)

**Comment by td2014** [comment]
@smolendawid .  I'm not sure I understand your question, but the input array should be 3d -> (5000,60,1) and your target array should be 2d  -> (5000,1), if I understand your basic configuration.  I hope that helps.  Thanks.
