### ISSUE TITLE
How to encode non-indexable data 

### ISSUE THREAD

**Issue by mhjang** [fchollet/keras#776]
I am trying to train a MLP model using keras. They take a sequence of integer vector as input data, which is an index of a present word if the target data are text documents.

In addition to these features, I have a word embedding vector for each document, which is a 200 dimension of real number that I also want to include in the input data. Since these weights cannot be indexed, how should I encode this as input data?

**Comment by fchollet** [comment]
Check out the `mnist_mlp` example, and the other examples as well. This is basic stuff, and all the information you need is in the examples and documentation.
