### ISSUE TITLE
documentation unclarity for model.fit / model.fit_generator

### ISSUE THREAD

**Issue by flomlo** [fchollet/keras#7804]
Hello!

Just a little issue with the documentation, which can be misleading: The documentation about the model.fit function (and analogously the model.generator_fit function) tells us:

*  epochs: integer, the number of epochs to train the model.
*  initial_epoch: epoch at which to start training (useful for resuming a previous training run)

I understood that this code starts at epoch 15 and goes on to epoch 25:

    model.fit(x, epochs=10, initial_epoch=15)

What happens instead is that the model isnt fitted at all, the as the parameter epochs is understood is "final_epochs" or "total_epochs". As the initial_epoch is bigger that the "final_epoch", it simply never starts.

The same happens if I write

    model.fit(x, epochs=100, initial_epoch=15)

In that case the model is trained *until* epoch 100, not *for* 100 epochs.

I think the documentation is slightly misleading and see two solution to fix this:
* Convince me that I'm the only person who misunderstood this
* Make the documentation more verbose. 

If the consensus goes for the latter, I can try to fix it myself.

-------------------------------------

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [ x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

**Comment by samre12** [comment]
In the Keras source code, [training.py](https://github.com/fchollet/keras/blob/5ce69728aa821677fb5b2f9bc052790b0f283b3e/keras/engine/training.py#L1130),
the training in the ```_fit_loop``` function runs in the ```range(initial_epochs, epochs)```. So it must be the case that the training loops starts from ```initial_epochs``` and runs until ```epochs```.

**Comment by flomlo** [comment]
I have no problems with the behaviour (in hindsight, I think its reasonable). I just think its not clear from the documentation alone.

**Comment by samre12** [comment]
Yes, I agree to that.

**Comment by flomlo** [comment]
Ok, if I'm not alone with that assesment I'll quickly make a patch for the docstring.

I think the best place for that would an additional line in the description of initial_epoch.
