### ISSUE TITLE
The default argument of LSTM activation is tanh. But the document says 'linear'.

### ISSUE THREAD

**Issue by tykimos** [fchollet/keras#7805]
The document of LSTM said as the following

"keras.layers.recurrent.LSTM(units, activation='tanh', "

activation: Activation function to use (see activations). If you pass None, no activation is applied (ie. "linear" activation:  a(x) = x).

**Comment by td2014** [comment]
@tykimos .  If you check this codebase, you'll see the behavior is as described if you set the flag activation=None.  If you don't set it explicitly, then the default is tanh, as you correctly point out.
From:  https://github.com/fchollet/keras/blob/master/keras/activations.py
def get(identifier):
    if identifier is None:
        return linear

I hope this helps.  Thanks.
