### ISSUE TITLE
set_of_lengths() fails to handle TensorShape

### ISSUE THREAD

**Issue by InonS** [fchollet/keras#7810]
training.py line 224:
```python
return set([0 if y is None else y.shape[0] for y in x])
```
raises `TypeError: unhashable type: 'Dimension'`
for x of type `<class 'list'>: [<class 'tensorflow.python.framework.ops.Tensor'>]`.

See https://github.com/fchollet/keras/issues/7756
The solution @facaiy offered me there was to use the equivalent of `y.shape.as_list()[0]` here, but this time it's the Keras code, not mine.

Example:
https://github.com/InonS/Open-GPGPU-ANN/blob/sub-packages/testkeras/testKerasFunctionalMinimal.py#L81

**Comment by fchollet** [comment]
This function is meant to handle Numpy array, not symbolic tensors.

**Comment by InonS** [comment]
@fchollet I never called it. If you look at my example, all I did in that line was call fit():

```
Traceback (most recent call last):
...
  File ".../Open-GPGPU-ANN/testkeras/testKerasFunctionalMinimal.py", line 92, in <module>
    main()
  File ".../Open-GPGPU-ANN/testkeras/testKerasFunctionalMinimal.py", line 88, in main
    run()
  File ".../Open-GPGPU-ANN/testkeras/testKerasFunctionalMinimal.py", line 82, in run
    model.fit(x=x_train, y=y_train, batch_size=None, epochs=1, validation_split=0.3)
  File "...\keras\engine\training.py", line 1522, in fit
    batch_size=batch_size)
  File "...\keras\engine\training.py", line 1390, in _standardize_user_data
    _check_array_lengths(x, y, sample_weights)
  File "...\keras\engine\training.py", line 226, in _check_array_lengths
    set_x = set_of_lengths(inputs)
  File "...\keras\engine\training.py", line 224, in set_of_lengths
    return set([0 if y is None else y.shape[0] for y in x])
TypeError: unhashable type: 'Dimension'```

**Comment by fchollet** [comment]
You called  `fit` on symbolic tensors, which isn't possible at this time. It can only handle Numpy arrays.

**Comment by InonS** [comment]
@fchollet , could you please direct me to the definition of "symbolic tensors"? 

All I'm trying to do is use the Functional API with a TensorFlow backend. 
Is it because I'm using 
```python
from keras.backend import expand_dims, one_hot
```
instead of
```python
from numpy import expand_dims
from keras.utils import to_categorical
```
 Would it only work with the Sequential API?
Do I have to convert my datasets from `tf,Tensor` to `np.ndarray`?

**Comment by fchollet** [comment]
> Do I have to convert my datasets from tf,Tensor to np.ndarray?

Yes, you could, which would be efficient if their are small datasets.

You can also use Keras models with symbolic tensors as follow: https://github.com/fchollet/keras/blob/master/examples/mnist_tfrecord.py

**Comment by InonS** [comment]
@fchollet , so basically I can only use generic Keras with NumPy arrays? I thought that's why you have Keras tensors.

Implementing option 2 of [my previous comment](https://github.com/fchollet/keras/issues/7810#issuecomment-326830980), which worked.
