### ISSUE TITLE
different inputs cannot go through the same embedding layers in a graph.

### ISSUE THREAD

**Issue by jeffzhengye** [fchollet/keras#783]
Hi. all. 
I have a problem to make different inputs go through the same/shared embedding layer. Is there any good workaround? 

'''
shared_embedding_layer = Embedding(max_features, embedding_size, weights=[W2V], W_regularizer=l2(50.), mask_zero=False)
graph = Graph()
graph.add_input(name='input1_story', ndim=3, dtype='int64')  # story_input: nb_story * nb_sentence * nb_words
graph.add_input(name='input2_question', ndim=2, dtype='int64')  # question_input:  nb_story*4 * nb_words
graph.add_node(shared_embedding_layer, name='story_word_embedding',
               input='input1_story')  # nb_batch * nb_sentence * nb_words * embedding_size

graph.add_node(shared_embedding_layer, name='question_word_embedding', input='input2_question')

'''

The problem is if you use a shared_embedding_layer, shared_embedding_layer.previous will change. 
But I also don't want to multiple embedding with the same weights. 

Thanks

**Comment by jeffzhengye** [comment]
@fchollet Can you give some suggestion to the above problem?

**Comment by fchollet** [comment]
Sure. Instantiate your two Embeddings, then on the second one, set `embed2.params = embed1.params`. Then add them to your network. 

You're creating two embeddings with shared weights.

(Untested, let me know if it worked).

**Comment by lemuriandezapada** [comment]
This is interesting. If you set x1.params = x2.params you're forcing them to share the weights?
Because they will point to the same memory space? The params won't just get copied over and things trained separately?

**Comment by fchollet** [comment]
Thinking about it, the real solution would be a tad more involved. You would also have to set the weights pointer of the new Embedding to be the same as that of the old Embedding (otherwise your new Embedding would have different weights, and they would never be trained).

```
embed2.W = embed1.W
embed2.params = embed1.params
```

Basically, you only want one Theano tensor underlying the operations of both layers.

**Comment by sergeyf** [comment]
In case someone searches for this (like I did), here's a worked-through example that seems to work:

```
dense_dim_1 = 10
dense_dim_2 = 1

model = Graph()
model.add_input(name='x1',input_shape=(d,))
model.add_input(name='x2',input_shape=(d,))
model.add_input(name='x3',input_shape=(d,))

D11 = Dense(dense_dim_1, activation='relu')
D12 = copy.deepcopy(D11)
D12.params = []
D13 = copy.deepcopy(D11)
D13.params = []

model.add_node(D11,name='D11', input='x1')
model.add_node(D12,name='D12', input='x2')
model.add_node(D13,name='D13', input='x3')

model.add_node(Dense(dense_dim_2, activation='relu'),
               name='dense_merge', merge_mode="concat", 
               inputs=['D11','D12','D13'])

model.add_output(name='output', input="dense_merge")

rmsprop = RMSprop(lr=0.001)
model.compile(optimizer=rmsprop, loss={"output": 'mse'})

data = {'x1':X1, 'x2':X2, 'x3':X3, 'output':y}
model.fit(data)
```

**Comment by jeffzhengye** [comment]
Hi Sergey.
   I don't think this is going to work. Since you are using deep copy, D12
will have its own parameters, which will be constant.
But the parameters in D11 can update.
   BTW, you don't have to set D12.params = [], you can set .trainable =
False.


On Thu, Oct 29, 2015 at 6:56 PM, Sergey Feldman <notifications@github.com>
wrote:

> In case someone searches for this (like I did), here's a worked-through
> example that seems to work:
>
> dense_dim_1 = 10
> dense_dim_2 = 1
>
> model = Graph()
> model.add_input(name='x1',input_shape=(d,))
> model.add_input(name='x2',input_shape=(d,))
> model.add_input(name='x3',input_shape=(d,))
>
> D11 = Dense(dense_dim_1, activation='relu')
> D12 = copy.deepcopy(D11)
> D12.params = []
> D13 = copy.deepcopy(D11)
> D13.params = []
>
> model.add_node(D11,name='D11', input='x1')
> model.add_node(D12,name='D12', input='x2')
> model.add_node(D13,name='D13', input='x3')
>
> model.add_node(Dense(dense_dim_2, activation='relu'),
>                name='dense_merge', merge_mode="concat",
>                inputs=['D11','D12','D13'])
>
> model.add_output(name='output', input="dense_merge")
>
> rmsprop = RMSprop(lr=0.001)
> model.compile(optimizer=rmsprop, loss={"output": 'mse'})
>
> data = {'x1':X1, 'x2':X2, 'x3':X3, 'output':y}
> model.fit(data)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/783#issuecomment-152350985>.
>



-- 
Jeff Ye.

**Comment by jeffzhengye** [comment]
Hi. Francois.
    For layers that only very few parameters, we can just do embed2.W =
embed1.W, but what if I want to share parameters for gru or lstm for
different inputs?


On Thu, Oct 8, 2015 at 1:14 PM, François Chollet <notifications@github.com>
wrote:

> Thinking about it, the real solution would be a tad more involved. You
> would also have to set the weights pointer of the new Embedding to be the
> same as that of the old Embedding (otherwise your new Embedding would have
> different weights, and they would never be trained).
>
> embed2.W = embed1.W
> embed2.params = embed1.params
>
> Basically, you only want one Theano tensor underlying the operations of
> both layers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/783#issuecomment-146627655>.
>



-- 
Jeff Ye.

**Comment by sergeyf** [comment]
Ah, interesting. How would you recommend I do it then?

**Comment by jeffzhengye** [comment]
I would do a copy.copy(a_layer), but still ugly. But I don't want to change
the core of keras.

On Tue, Nov 10, 2015 at 8:08 PM, Sergey Feldman <notifications@github.com>
wrote:

> Ah, interesting. How would you recommend I do it then?
>
> On Tue, Nov 10, 2015 at 3:05 PM, Jeffery Ye <notifications@github.com>
> wrote:
>
> > Hi. Francois.
> > For layers that only very few parameters, we can just do embed2.W =
> > embed1.W, but what if I want to share parameters for gru or lstm for
> > different inputs?
> >
> >
> > On Thu, Oct 8, 2015 at 1:14 PM, François Chollet <
> notifications@github.com
> > >
> > wrote:
> >
> > > Thinking about it, the real solution would be a tad more involved. You
> > > would also have to set the weights pointer of the new Embedding to be
> the
> > > same as that of the old Embedding (otherwise your new Embedding would
> > have
> > > different weights, and they would never be trained).
> > >
> > > embed2.W = embed1.W
> > > embed2.params = embed1.params
> > >
> > > Basically, you only want one Theano tensor underlying the operations of
> > > both layers.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/fchollet/keras/issues/783#issuecomment-146627655>.
> >
> > >
> >
> >
> >
> > --
> > Jeff Ye.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/fchollet/keras/issues/783#issuecomment-155596209>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/783#issuecomment-155621213>.
>



-- 
Jeff Ye.

**Comment by around1991** [comment]
Hi @jeffzhengye 

That doesn't seem to work if a_layer is the first layer of your network. The issue seems to be the input variable: if `a` is an Embedding layer (for example), and `b = copy.copy(a)`, then `b.input` is the same as `a.input` and this messes up the data input. 

I think the right thing to do is to set `b.input = K.placeholder(a.input_shape)` after calling copy.

Kris

**Comment by tstandley** [comment]
@fchollet Regarding your solution: What happens if you write out the weights of this hacked model then read them back in to continue training? Are all copies of the weights stored? Does the model architecture serialize correctly with model_to_json if you do this trick?

I tried to implement this idea, but got:
AttributeError: 'Embedding' object has no attribute 'W'

**Comment by nijianmo** [comment]
Hi, is there any update on this post?
I failed to run this command embed2.params = embed1.params, which showed embedding layer do not have "params". Does anyone know what is the corresponding field in the embedding layer class for current version?

**Comment by scorpionsky** [comment]
Is this what you are looking for? https://stackoverflow.com/questions/42122168/keras-how-to-construct-a-shared-embedding-layer-for-each-input-neuron?rq=1
