### ISSUE TITLE
Question about h_t formula in GRU 

### ISSUE THREAD

**Issue by hugman** [fchollet/keras#785]
I've checked Keras GRU implementation line by line to extend it.
In Keras GRU code, the update function is looks like 
> h_t        = z * h_mask_tm1 + (1 - z) * hh_t
( from https://github.com/fchollet/keras/blob/master/keras/layers/recurrent.py#L272 )

But, from the referenced paper, the h_t formula is slightly different. 
![image](https://cloud.githubusercontent.com/assets/2958929/10277437/d5c4fc94-6b90-11e5-8295-796f7846b09b.png)

( from http://arxiv.org/pdf/1412.3555v1.pdf)

The difference is (1-z)*h~   or (1-z)*h .
Am I missing something? 
I'm very sure Keras implementation is alright. (It works all the time)

**Comment by transcranial** [comment]
Both formulations should work - it's just that the learned weights are different. Incidentally, if you check the implementations of JZS1-3, they do reflect how they're expressed in the reference paper (similar to your GRU reference paper equation): `h_t = hh_t * z + h_mask_tm1 * (1 - z)`

**Comment by EderSantana** [comment]
z is fixed between 0 and 1. So is (1-z). Thats why it works.

**Comment by hugman** [comment]
Thank you for answer. z (update gate) is just a kind of weighted switch, so it doesn't matter in both cases.
