### ISSUE TITLE
How to change RNN sequence size after training

### ISSUE THREAD

**Issue by sileod** [fchollet/keras#7852]
Hi,
Is there an easy way to cast the RNN cell of a RNN model of sequence_length=10 into a RNN model with higher sequence length ?
It would be useful since we often restrict sequence_length to make training more efficient, but for inference, execution time might not be critical and it could be better to use different lengths of RNN. (It could even shorten time if we use smaller RNN on smaller sequences)
I know it sounds like dynamic RNN but I think it's less demanding.
We could transfer weights from old one to new one but it sounds a bit messy to me. Is there a better wya ?
Thanks

**Comment by fchollet** [comment]
Use `None` for the sequence length, which allows for any sequence size to be processed by the model.

E.g.

```python
model = Sequential()
model.add(LSTM(32, input_shape=(None, input_dim))
```
