### ISSUE TITLE
why val_loss and val_acc increase together?

### ISSUE THREAD

**Issue by micklexqg** [fchollet/keras#7866]
why val_loss and val_acc increase together?  I tried to finetune inception v3 on my own dataset.
Is there anything wrong?
![image](https://user-images.githubusercontent.com/13776012/30245783-4ee20560-9617-11e7-9b6e-0a3e630a294e.png)

**Comment by bdwyer2** [comment]
Checkout this gist:
https://gist.github.com/dusenberrymw/89bc12a8f9a9afaacdb91668abe4065d

**Comment by micklexqg** [comment]
@bdwyer2 ， thank you, it is helpful!
