### ISSUE TITLE
customized output instead of just Merge

### ISSUE THREAD

**Issue by jeffzhengye** [fchollet/keras#787]
Hi. All
It seems that when there are multiple inputs for a node (graph.add_node), the output can only be something from Merge. Is there any nice workaround if I want to have a customized output? Thanks.

**Comment by fchollet** [comment]
> Is there any nice workaround if I want to have a customized output?

Not clear what you mean by "customized output", but maybe you can simply write your own layer?

**Comment by jeffzhengye** [comment]
@fchollet first, thanks for your reply. 
See the code here https://github.com/fchollet/keras/blob/master/keras/layers/containers.py#L209
The inputs have to be merged (can only use Merge). What if I want to merge/operate the inputs in a customized way?
Writing my own layer cannot change 'the Merge' at line L209.

**Comment by fchollet** [comment]
Technically, you could concatenate your inputs (Merge -> concat), then in your own custom layer you could retrieve the original inputs from the concatenated ones.

In the near future, we have plans to support custom multi-input layers (see https://github.com/fchollet/keras/issues/620#issuecomment-144483091). But it's not supported for now.

**Comment by jeffzhengye** [comment]
@fchollet The problem is Merge is not applicable due to the dimension of the inputs. 
My current walk-around is to extend Graph to have a customized add_node method, in which we don't use a fixed Merge.  But it's kinda ugly to me.

**Comment by fchollet** [comment]
Glad you have a workaround. In the future it will be possible as part of the standard Graph API.
