### ISSUE TITLE
Eliminate Edges in Dense Layer

### ISSUE THREAD

**Issue by Paxanator** [fchollet/keras#788]
Is there any support for eliminating edges in a Sequential Model with fully connected nodes, so when backprop occurs during training the edges are not updated? 
If not, what's the best way of implementing it (was thinking of having adding a constraint, but unsure and seems hacky)?

**Comment by fchollet** [comment]
What do you mean by "eliminating edges"?

**Comment by Paxanator** [comment]
Whoops, sorry wasn't totally clear. 

Suppose I have a fully connected layer and want pare it down, or initialize it such that it isn't fully connected, but partially connected. This would be equivalent, in my mind to the weight from a Neuron in Layer 1 to a Neuron in Layer 2 being statically 0 or NaN during updates. Is there anyway to impose this constraint (I know there's regularization and nonzero, but nothing that imposes zero-only constraints for some weights)? The purpose would be to impose sparsity in a layer.

Hope that makes sense, thanks!

**Comment by fchollet** [comment]
You can either use an `ActivityRegularizer`, or write a custom weight initialization function that will set certain coefficients to zero.

**Comment by Paxanator** [comment]
Thank you!

**Comment by Paxanator** [comment]
Thanks for the input! I want to just re-clarify the question, because I don't think activity-regularizing is what I'm looking for. 

The purpose is to impose a user-defined graph structure on a layer, such that some pre-defined edges are not existant. ie)  see the simplified picture below

The Fully Connected Layer: 
![image](https://cloud.githubusercontent.com/assets/10686914/10321095/e759bb8e-6c44-11e5-90ef-0288e9d37f09.png)

Becomes the User Defined Sparsely Connected:
![image](https://cloud.githubusercontent.com/assets/10686914/10321153/28605cfa-6c45-11e5-8efc-1ab2f1f0fcd1.png)

Which can then be trained, with only those edges persisting, and new edges not coming back to the fully connected paridigm. As I understand it, activity_regularizer does this in an automatic way with either an L1 or L2 penalty for activations, but there is no way to set the connections in a user-defined fashion.
