### ISSUE TITLE
Getting NotImplementedError for "on_epoch_end" while training using fit_generator on a Sequence object

### ISSUE THREAD

**Issue by rohit-gupta** [fchollet/keras#7890]
> Exception in thread Thread-8:
> Traceback (most recent call last):
>   File "/users/gpu/rohitg1/miniconda2/envs/tensorflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/users/gpu/rohitg1/miniconda2/envs/tensorflow/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/users/gpu/rohitg1/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 492, in _run
>     self.sequence.on_epoch_end()
>   File "/users/gpu/rohitg1/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 358, in on_epoch_end
>     raise NotImplementedError
> NotImplementedError

I am trying to train a Video classification model. Gist for portion of code is available here:

https://gist.github.com/rohit-gupta/7668b79389e29598ace41813fc1a50d2

Do I need to implement a "on_epoch_end" function in my Sequence object to get this o work ?

**Comment by Dref360** [comment]
yes you need to, 
You can do it as simple as : 
```def on_epoch_end(self):
        pass
```
@joeyearsley Should we make it optional or clarify the doc instead to avoid issues for newcomers?

**Comment by joeyearsley** [comment]
I'ld say optional as it isn't always needed

**Comment by rohit-gupta** [comment]
@Dref360 Thanks for your reply, Its solved my issue ! Though I am curious as to what the purpose of this is ? What do people usually implement in this function ?

**Comment by Dref360** [comment]
If you want to shuffle your data between epoch, on_epoch_end is called at this time.

**Comment by fredtcaroli** [comment]
Had to read keras' code to figure out why my code was raising this `NotImplementedError`. This should be definitely be documented or made optional asap

**Comment by jlherren** [comment]
Seems fixed with PR #8007

**Comment by fchollet** [comment]
Yes, it is fixed at `master`.
