### ISSUE TITLE
Training not starting with fit_generator and use_multiprocessing=True

### ISSUE THREAD

**Issue by MarcoForte** [fchollet/keras#7902]
After upgrading to latest keras version 2.0.8 my previous keras code written for 2.0 no longer works.
I use multiple `ImageDataGenerator`'s since my code takes in multiple images and outputs one. I needed to write my own custom generator that took as input all the images coming from each `ImageDataGenerator.flow_from_directory` and preforms some preprocessing.
The custom generator looks like,   

```
def train_generator():
    while True:
        img1 = next(img1_generator)
        img2 = next(img2_generator)
        img_res = next(res_generator)
        # Do some processing
        yield [img1, img4], img_res
```

The training works if I set `use_multiprocessing=False`, but gets stuck displaying 
> epoch 1/10  

if I set `use_multiprocessing=True`.  

My batch_size is set to 6 and I've tried different settings for num_workers and max_queue_size, but none worked.
I saw that there were some changes in version 2.0.6 so maybe it broke something.

**Comment by Dref360** [comment]
Hey, I tried to recreate the issue, but I'm unable to... Could you tell me the difference between my snippet and yours?
```python
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.layers import Input, Lambda
import numpy as np


img1 = ImageDataGenerator().flow(np.zeros([30,20,20,3]),None,10)
img2 = ImageDataGenerator().flow(np.zeros([30,20,20,3]),None,10)
out = ImageDataGenerator().flow(np.zeros([30,20,20,3]),None,10)


def create_gen():
    for x1,x2,o in zip(img1,img2,out):
        yield [x1,x2],o

inp = Input([20,20,3])
inp2 = Input([20,20,3])
o = Lambda(lambda i: i[0] + i[1])([inp,inp2])
mod = Model([inp,inp2],o)
mod.compile('adam','mse')
mod.fit_generator(create_gen(),3,use_multiprocessing=True)
```

**Comment by MarcoForte** [comment]
Hi thanks for that code snippet, helped me realize where the bug/(error?) is. It's something to do with the `cv2.resize` function from OpenCV. I was using it to preprocess my images but it doesn't seem to work with `use_multiprocessing=True`. It's likely a OpenCV bug so I will just show an example snippet that doesn't work and close the issue. 

```
image_dim = 320
IMG_DIR  = 'imgs'

image_datagen  = ImageDataGenerator()

img_generator = image_datagen.flow_from_directory(
    IMG_DIR, class_mode=None, batch_size=BATCH_SIZE, target_size=(320, 320))

def train_generator():
    while True:
        img = next(img_generator)
        y = np.zeros_like(img)
        img0 = img[0]
        # the opencv resize does not work with multiprocessing
        img0 = cv2.resize(img0, (640, 640))
        img0 = cv2.resize(img0, (320, 320))
        # The scipy resize does
#         img0= scipy.misc.imresize(img0, (640,640)).astype(np.float32)/255
#         img0 = scipy.misc.imresize(img0, (320,320)).astype(np.float32)/255
        img[0] = img[0]
        
        yield img, y

train_gen = train_generator()

def n_layer(input_img_dim, num_output_channels=1):
        
    img = Input(shape=input_img_dim)

    x = img
    x = Conv2D(num_output_channels, (1, 1), activation='tanh', padding='same')(x)
    
    model = Model(inputs=img, outputs=x)
    return model

model = n_layer((image_dim, image_dim,3 ),3)

model.compile(Adam(lr=1e-5), loss='mse')

hist = model.fit_generator(train_gen, steps_per_epoch=int(50000/BATCH_SIZE),  epochs=30,  workers=4, use_multiprocessing=True)

```

**Comment by AutumnZ-94** [comment]
I have the same problem, which is stuck after the `model.compile` and not start iteration. Have you figured it out?
