### ISSUE TITLE
Get intermediate weights of a CNN in graph model

### ISSUE THREAD

**Issue by hemanth2090** [fchollet/keras#794]
Hi,

  I am using graph model with one input and two outputs. I have several convolution and pooling layers. I want to obtain the weights after the first convolution layer (named as 'conv1'). I implemented  the code given in the <a href="http://keras.io/faq/#how-can-i-visualize-the-output-of-an-intermediate-layer" >documentation</a>. Here is the pertinent code for obtaining the weights.

```
model.fit({'input':X_train, 'output1':y1_train, 'output2':y2_train}, batch_size=128, nb_epoch=250)

# Save the model weights
model.save_weights('model_weights.h5', overwrite=True)

# Convolution Layer weights
get_conv_layer_output = theano.function([model.inputs[i].input for i in model.input_order], model.outputs['conv1'].get_output(train=False), on_unused_input='ignore')
    conv_output = get_conv_layer_output({'input':X_train})
    print("Printing conv1 layer weights: ",conv_output)
```

I got the following error.

```
File "train.py", line 269, in <module>
get_conv_layer_output = theano.function([model.inputs[i].input for i in model.input_order], model.outputs['conv1'].get_output(train=False), on_unused_input='ignore')
KeyError: 'conv1'
```

Can someone please tell me how I can save the weights after the convolution layer in a graph model?

**Comment by julienr** [comment]
```
convout1_f = theano.function([model.get_input(train=False)],
                              convout1.get_output(train=False))
```
Where convout1 is your convolution layer.
You can have a look at [this notebook](https://github.com/julienr/ipynb_playground/blob/master/keras/convmnist/keras_cnn_mnist.ipynb) where I think I do what you want.
