### ISSUE TITLE
keras imports only from super user

### ISSUE THREAD

**Issue by cosmos2006** [fchollet/keras#7940]
keras 2.0.8 gets installed (> python setup.py install) but while importing it in python for a local user, keras does not get imported.
>>> import keras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named keras

But when I import keras from superuser, it works fine. With every in installation, .keras directory is generated in root only. Please suggest the solution?

**Comment by bdwyer2** [comment]
Does `sudo which python` and `which python` return the same thing?

**Comment by cosmos2006** [comment]
>Does sudo which python and which python return the same thing?

No.
 root python version is Python 2.7.13 :: Anaconda 4.4.0 (64-bit)
user python version     Python 2.7.12

**Comment by cosmos2006** [comment]
problem got solved when I compiled the keras with same version pf python in
root and user.

Thanks for the hint.

Regards
Mradul

**Comment by bdwyer2** [comment]
Excellent. If everything is working would you mind closing this issue?
