### ISSUE TITLE
Input layer's dtype default parameter improperly calls K.floatx()

### ISSUE THREAD

**Issue by bchu** [fchollet/keras#7951]
model.layers.Input's constructor has a default parameter `dtype=K.floatx()`. This just calls `K.floatx()` when Keras is first imported, instead of calling `K.floatx()` at construction time. This is problematic because the user might call `K.set_floatx(...)` after importing Keras.

Happy to submit a PR fixing this.

**Comment by facaiy** [comment]
Sounds reasonable, at least for me.
