### ISSUE TITLE
LSTM return_sequences: why output dimension with none instead of timesteps?

### ISSUE THREAD

**Issue by wddddds** [fchollet/keras#7961]
Hi, I am using lstm layer with return sequences = True, say:

`x = LSTM(32, return_sequences=True, input_shape=(timesteps, data_dim))(inp)`
And I would expect the output shape to be : (None(batch size), timesteps, 32(units)),
In my case it is (?, 8, 32)
but what I got is :Tensor("lstm_1/transpose_1:0", shape=(?, ?, 32), dtype=float32)

I wonder why it returns another None dimension? It dose not influence the model compiling but when trying to implement some more complicated models it cause troubles.

Or is there anything I misunderstood?

Thanks very much for your help!

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [* ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [* ] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [ ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by td2014** [comment]
@wddddds .  Is the LSTM layer the first layer (input layer) in your model?  If not, then you don't (or probably shouldn't) need to specify input_shape.  Keras will infer this from the input layer.  Just a thought.  I hope this helps.  Thanks.

**Comment by wddddds** [comment]
Hi td,  Thanks very much for your reply, Sorry I am not clear enough in my question. I modified the code based on your suggestion:

```
inp = Input(shape=(timesteps, data_dim,))
x = LSTM(32, return_sequences=True)(inp)
x = LSTM(32, return_sequences=True)(x)  # returns a sequence of vectors of dimension 32
x = LSTM(32)(x)  # return a single vector of dimension 32
pred = Dense(10, activation='softmax')(x)
```
And here's the shape of tensors and model summary: I am wondering why the tensor shape is of  shape=(?, ?, 32) instead of  (None, 8, 32) in the model summary.

```
Tensor("input_1:0", shape=(?, 8, 16), dtype=float32)      #input shape
Tensor("lstm_1/transpose_1:0", shape=(?, ?, 32), dtype=float32)     #1 lstm layer
Tensor("lstm_2/transpose_1:0", shape=(?, ?, 32), dtype=float32)     
Tensor("lstm_3/TensorArrayReadV3:0", shape=(?, 32), dtype=float32)
Tensor("dense_1/Softmax:0", shape=(?, 10), dtype=float32)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 8, 16)             0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 8, 32)             6272      
_________________________________________________________________
lstm_2 (LSTM)                (None, 8, 32)             8320      
_________________________________________________________________
lstm_3 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dense_1 (Dense)              (None, 10)                330       
=================================================================
```

**Comment by wddddds** [comment]
Hi, Thanks for help, I managed to solve this problem by using tensorflow's set_shape method.

**Comment by Zaabit** [comment]
Hi wddddds, 
                   Can you plz specify it, how you used set_shape here?

**Comment by Zaabit** [comment]
I am using the following approach but could not succeed:
 lstm = lstm.set_shape([None,embedding_dim, 32]) #None = batch size, embedding = embedding dimension, and 32 means lstm output

**Comment by Puruaero** [comment]
set_shape is a setter method which will assign the given value as the shape attribute (assuming other requirements of set_shape method  satisfied) without returning. "lstm = lstm.set_shape([None,embedding_dim, 32])" would make lstm a NoneType object

**Comment by Shitiz1708** [comment]
> Hi, Thanks for help, I managed to solve this problem by using tensorflow's set_shape method.

@wddddds cam you explain how you solved the problem with set_shape.
Because using set_shape i got the same error as mentioned by @Puruaero 
Please Help..
