### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by dineshbvadhia** [fchollet/keras#8]
Not an Issue per se but it is good to see a Theano-based deep learning library as Theano can be pretty difficult to understand when all is needed is plug-and-play functionality. Are there plans to support word2vec and sentence2vec? Anything else planned?

**Comment by fchollet** [comment]
I am very interested in word/sentence/text embedding, so there will definitely be more to come in that area. In the mean time, I suggest you check out Gensim. 

Anything else planned: yes, I'm also interested in memory networks and their application to text understanding and question answering. I will most likely add Keras support for memory networks in the near future.
