### ISSUE TITLE
Error while predicting in image_ocr example? 

### ISSUE THREAD

**Issue by codeheadshopon** [fchollet/keras#8008]
I was trying to use my own image to predict for OCR. I havent modified the image_ocr.py code. I just added these lines in the end of train functions. 

`model.load_weights('weights11.h5')

    img = cv2.imread('Test_Img.png')
    img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    img = np.array(img)
    img = np.reshape(img, (1, 256, 64, 1))
    print(img.shape)

    labels = np.ones([1, 30])
    input_length = np.ones([1, 1])
    label_length = np.ones([1, 1])

    print("Input Length",input_length[0])

    outputs_1 = {'ctc': np.zeros([1])}
    source="abc"

    model.predict([img,labels,input_length,label_length])`

I am getting these errors. 

`
    2017-09-28 20:30:18.226142: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.

    2017-09-28 20:30:18.226316: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.

         [[Node: ctc/scan/TensorArrayUnstack/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/gpu:0"](ctc/scan/TensorArrayUnstack/Shape/_95, ctc/scan/TensorArrayUnstack/strided_slice/stack, ctc/scan/TensorArrayUnstack/strided_slice/stack_1, ctc/scan/TensorArrayUnstack/strided_slice/stack_2)]]

    2017-09-28 20:30:18.226444: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.

         [[Node: ctc/scan/TensorArrayUnstack/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/gpu:0"](ctc/scan/TensorArrayUnstack/Shape/_95, ctc/scan/TensorArrayUnstack/strided_slice/stack, ctc/scan/TensorArrayUnstack/strided_slice/stack_1, ctc/scan/TensorArrayUnstack/strided_slice/stack_2)]]

    2017-09-28 20:30:18.226463: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.

         [[Node: ctc/scan/TensorArrayUnstack/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/gpu:0"](ctc/scan/TensorArrayUnstack/Shape/_95, ctc/scan/TensorArrayUnstack/strided_slice/stack, ctc/scan/TensorArrayUnstack/strided_slice/stack_1, ctc/scan/TensorArrayUnstack/strided_slice/stack_2)]]

    2017-09-28 20:30:18.645834: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: slice index 0 of dimension 0 out of bounds.

         [[Node: ctc/scan/TensorArrayUnstack/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/gpu:0"](ctc/scan/TensorArrayUnstack/Shape/_95, ctc/scan/TensorArrayUnstack/strided_slice/stack, ctc/scan/TensorArrayUnstack/strided_slice/stack_1, ctc/scan/TensorArrayUnstack/strided_slice/stack_2)]]

    Traceback (most recent call last):
      File "/home/codehead/PycharmProjects/BanglaOCR/BanglaOCR/BanglaOCR_FullCombined.py", line 694, in <module>
        train(run_name, 0, 150, 256, type, lang)
      File "/home/codehead/PycharmProjects/BanglaOCR/BanglaOCR/BanglaOCR_FullCombined.py", line 667, in train
        model.predict([img,labels,input_length,label_length])
      File "/home/codehead/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1517, in predict
        batch_size=batch_size, verbose=verbose)
      File "/home/codehead/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1141, in _predict_loop
        batch_outs = f(ins_batch)
      File "/home/codehead/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2268, in __call__
        **self.session_kwargs)
      File "/home/codehead/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
        run_metadata_ptr)
      File "/home/codehead/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
        feed_dict_tensor, options, run_metadata)
      File "/home/codehead/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
        options, run_metadata)
      File "/home/codehead/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
        raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 0 out of bounds.
         [[Node: ctc/scan/TensorArrayUnstack/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/gpu:0"](ctc/scan/TensorArrayUnstack/Shape/_95, ctc/scan/TensorArrayUnstack/strided_slice/stack, ctc/scan/TensorArrayUnstack/strided_slice/stack_1, ctc/scan/TensorArrayUnstack/strided_slice/stack_2)]]
         [[Node: ctc/scan/while/Fill/_139 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_144_ctc/scan/while/Fill", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](^_cloopctc/scan/while/TensorArrayReadV3/_81)]]`

**Comment by ivyteng** [comment]
Have you solved the problem? How to fix it? Thanks

**Comment by codeheadshopon** [comment]
Yeah, I solved it. Actually thing was you cant predict an image using the "MODEL" as the model in the end outputs a LOSS VALUE. So what you need to do is. take an image. Let me write the desired code 

`
image=cv2.imread('img.png')
#Reshape the image or what ever modification you need to do 
image=image.astype(np.float32) / 255
result=test_func(image) [ test_func is declared previously before training the model] 
`
Now the rsulatnt probablities are in the **result** variable. Just use np.argmax to extract the result from it

**Comment by puyangsky** [comment]
thks buddy! You solved my problem and I use the decode_batch() function which is more convenient.

**Comment by doktopaibolit** [comment]
@puyangsky Can you publish your code? Tnx

**Comment by puyangsky** [comment]
@doktopaibolit  use the line below:
pred_result = decode_batch(test_func, test_X)[0]

"decode_batch" and "test_func" were defined in the code, the test_X is the test data, its type is numpy.ndarray with the same format with the training data.

**Comment by doktopaibolit** [comment]
@puyangsky I get this error:
ValueError: Cannot feed value of shape (1, 128, 64, 3) for Tensor u'the_input:0', which has shape '(?, 128, 64, 1)'

**Comment by puyangsky** [comment]
@doktopaibolit this example requires single channel picture, so you need to transfer (1, 128, 64, 3) to (1, 128, 64, 1) by  using tmp_X = tmp_X[:, :, 0]. You can refer my repo:  [https://github.com/puyangsky/KerasCaptcha](https://github.com/puyangsky/KerasCaptcha)
