### ISSUE TITLE
TypeError: fit_generator() got an unexpected keyword argument 'shuffle'

### ISSUE THREAD

**Issue by colllin** [fchollet/keras#8016]
New to keras so 🤞 this isn't user error.

Keras `v2.0.8` (installed from master just now)
Theano `v0.9.0` (couldn't install from master just yet, due to needing to upgrade to libgpuarray)

I'm following the docs here: https://keras.io/models/model/#fit_generator, which show that `fit_generator()` supports a `shuffle` keyword argument.

... but when I pass in `shuffle=True`:

```
history = model.fit_generator(
    TrainSequence(images=train_images, targets=train_targets, batch_size=batch_size),
    steps_per_epoch=len(train_images) // batch_size,
    epochs=epochs,
    shuffle=True,
    validation_data=ValidationSequence(images=validation_images, targets=validation_targets),
    validation_steps=len(validation_images) // batch_size
)
```

... I get this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-4b4e4616b417> in <module>()
     27         train_targets=y_train,
     28         validation_images=images_val,
---> 29         validation_targets=y_val
     30     )
     31 

<ipython-input-8-8b418f8cf20f> in train(train_images, train_targets, validation_images, validation_targets)
     19         shuffle=True,
     20         validation_data=ValidationSequence(images=validation_images, targets=validation_targets),
---> 21         validation_steps=len(validation_images) // batch_size
     22     )
     23 

/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     85                 warnings.warn('Update your `' + object_name +
     86                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 87             return func(*args, **kwargs)
     88         wrapper._original_function = func
     89         return wrapper

TypeError: fit_generator() got an unexpected keyword argument 'shuffle'
```

**Comment by whistler** [comment]
I can verify that this is an issue on Keras v2.0.8. This looks like a documentation error to me. I don't see shuffle as an argument in the [source](https://github.com/fchollet/keras/blob/master/keras/models.py). This does not seem too surprising to me as shuffling using a generator is much more complicated than shuffling data in-memory as in the case of `fit()`

**Comment by colllin** [comment]
Thanks, @whistler.

I found two different implementations of `fit_generator` in the keras source.  One [`fit_generator` implementation](https://github.com/fchollet/keras/blob/8ac788a5614570d222c484ab49cf9e878eeab9ff/keras/engine/training.py#L2001) supports the use of a `shuffle` option when using a [`Sequence`](https://keras.io/utils/#sequence).  The other [`fit_generator` implementation](https://github.com/fchollet/keras/blob/48b8676e64dfe4ca4b81cc4286300ae60f140dca/keras/models.py#L1029) doesn't support using a `Sequence` or the accompanying `shuffle` option. 

I'm not sure why keras chooses one implementation over another.  I'm looking into it now.  I do see the word "legacy" in the source next to `fit_generator`, but I actually see it next to both of these implementations, so I'm not sure if that gets me anywhere.

**Comment by sbakana** [comment]
TypeError: fit_generator() got an unexpected keyword argument 'samples_per_epoch'

How to solve this error...?

**Comment by vidhi-adp** [comment]
Even I have the same error. I need help too

**Comment by u19900101** [comment]
> Even I have the same error. I need help too

solved?

**Comment by KiLJ4EdeN** [comment]
Use 'steps_per_epoch' instead. some of the kwargs has been changed in newer versions.
