### ISSUE TITLE
cifar10_cnn.py example throws error

### ISSUE THREAD

**Issue by yueranyuan** [fchollet/keras#803]
I'm not sure if I have non-standard numpy configurations but the github version of examples/cifar10_cnn.py throws:

TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
on line 239 of keras/preprocessing/image.py which is "X -= self.mean"

This is presumably due to the fact that np.mean(X) returns a float and X is type 'uint8'. I notice that a cast to float occurs in examples/cifar10_cnn.py under data_augmentation == False but not if it's True.

Does this error occur for anyone else?

**Comment by fchollet** [comment]
I've never seen this error, the casting should be automatic (you could always cast manually but that shouldn't be necessary). Most likely you have an outdated version of Numpy.

**Comment by outlace** [comment]
I get this same error, running python 3.5

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-2976d70ea0f1> in <module>()
    109     # compute quantities required for featurewise normalization
    110     # (std, mean, and principal components if ZCA whitening is applied)
--> 111     datagen.fit(X_train)
    112 
    113     for e in range(nb_epoch):

/Users/brandonbrown/anaconda/lib/python3.5/site-packages/keras/preprocessing/image.py in fit(self, X, augment, rounds, seed)
    237         if self.featurewise_center:
    238             self.mean = np.mean(X, axis=0)
--> 239             X -= self.mean
    240         if self.featurewise_std_normalization:
    241             self.std = np.std(X, axis=0)

TypeError: Cannot cast ufunc subtract output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'
