### ISSUE TITLE
commit 19e1b breaks fit_generator & flow_from_dictionary

### ISSUE THREAD

**Issue by alicanb** [fchollet/keras#8058]
Here's the [gist](https://gist.github.com/alicanb/1d22a97f01ce1aa6a47c391dc1aeaf02) for a MWE. Runs correctly with Keras built from [ab57009](https://github.com/fchollet/keras/commit/ab5700962a74500aef0c6838580d285dbbb359c5) but gives ```StopIteration: Asked to retrieve element 486, but the Sequence has length 86``` on start of second epoch with Keras built from [19e1b](https://github.com/fchollet/keras/commit/19e1be2cf2592dcdb1650afc00bad9e08fa07954) (using TF 1.3.0 backend)

**Comment by bdwyer2** [comment]
Thanks for pointing this out. This issue should be resolved by #8060 403d5778756efd12c1cf8a0904ffa910809df66

**Comment by alicanb** [comment]
Yep, closing.
