### ISSUE TITLE
Why is a input which be already flattened incompatible with keras.layers.Flatten ?

### ISSUE THREAD

**Issue by kzm4269** [fchollet/keras#8067]
Why is a input which be already flattened incompatible with keras.layers.Flatten?
Just replacing `self.input_spec = InputSpec(min_ndim=3)` in `keras.layers.Flatten.__init__` with `self.input_spec = InputSpec(min_ndim=2)`, the input will be compatible with the layer.

**Comment by unrealwill** [comment]
Hello,
We all know the earth is flat, why would you want to flatten it again ? 
You can already use the Reshape((-1,)) layer (but in all case if it is the first layer then you must specify input_shape).

**Comment by sixtrees** [comment]
HaHa, you just need to comment on your `Flatten()........` code block.
