### ISSUE TITLE
Why don't layers' build() methods set weights to _initial_weights if available?

### ISSUE THREAD

**Issue by nathanmori** [fchollet/keras#8095]
Layer's `_initial_weights` are only used if the layer is built by [Layer.\_\_call__()](https://github.com/fchollet/keras/blob/771be1a587780ddeea9ad90ca435a11ff297830e/keras/engine/topology.py#L581). Why not do the following in the `build()` methods, so the weights passed to the constructor are actually used regardless of when it is built?
```
if self._initial_weights is not None:
    self.set_weights(self._initial_weights)
```

This arises, because for example if I use a TimeDistributed Embedding with pretrained weights, the weights aren't actually used:
```
time_distributed = TimeDistributed(
    Embedding(
        VOCAB_SIZE,
        EMBEDDING_DIM,
        weights=[WEIGHTS]),
    input_shape=SHAPE))
```
It only works if the weights are passed to TimeDistributed instead of Embedding, which doesn't seem ideal:
```
time_distributed = TimeDistributed(
    Embedding(
        VOCAB_SIZE,
        EMBEDDING_DIM),
    input_shape=SHAPE,,
    weights=[WEIGHTS]))
```

**Comment by fchollet** [comment]
The reason is simply that we expect the `weights` argument to always work, even if support for it isn't implemented by the authors of the layer considered (authors of custom layers will be implementing their own `build` methods, and they don't need to know about `_initial_weights`).

Passing the `weights` argument to top-level layers when using a wrapper is the proper thing to do, as you point out.

**Comment by nathanmori** [comment]
What I'm proposing is using `weights` if given. How does that impede the `weights` argument from working?

Passing to the wrapper's `weights` is the way to get the job done right now, but is it really more intuitive than passing the weights to the layer that's actually using them?

**Comment by fchollet** [comment]
If this has to be implemented in `build`, then it wouldn't work for custom layers (unless custom layers also take care of implementing it). As it stand currently, it will work all the time without requiring extra work for custom layers.

**Comment by nathanmori** [comment]
Ok, so maybe it doesn't happen in the `build` method, but how about setting the initial weights (if given) in the other places where the layer gets built, instead of only if that happens in `\_\_call__`?

Currently, if someone means to use pretrained weights in the example above, but - unaware of this issue - passes them to Embedding instead of to TimeDistributed, those weights are silently ignored.
