### ISSUE TITLE
Custom merge operations?

### ISSUE THREAD

**Issue by psmaragdis** [fchollet/keras#811]
I'm working on a `Graph` network which at various points has to multiply or divide the outputs of two preceding nodes. It looks like I can sum or concatenate the outputs of  two such nodes using the `merge_mode` and `inputs` options, but there is no clear way to perform any other binary functions. Am I missing an alternative or is this a limitation in the current syntax of Keras?

Thanks!

ps. oh, and using `log` and `exp` activations to perform multiplications using the `merge_mode=sum` also seems to run into trouble (no complex number support?). Not that this is an elegant solution in any way ...

**Comment by elanmart** [comment]
It's not a perfect solution, but it'll work for now.
In the [attached gist](https://gist.github.com/698813a8a8aa60d32040.git) you can find code that implements layers with multi-input support and a `NGraph` model which can handle connecting them. Note that this worked for me on the old version of keras (without shape inference). I'll update it soon and put on my fork, but I think Keras' devs will soon have their own support for such things.

[gist](https://gist.github.com/698813a8a8aa60d32040.git)

**Comment by elanmart** [comment]
Well, alternatively you could just add few lines to the Graph model to support dividing as an additional merge_mode.
