### ISSUE TITLE
Sudden Stopping Issue(?)

### ISSUE THREAD

**Issue by valexandersaulys** [fchollet/keras#812]
Does anyone know why my convolutional neural network would just suddenly stop? Like it displays epoch 0 with no training information and just quits on me. I put print statements after the data to see if it progresses beyond it, but it literally breaks before even beginning training and drops out to the terminal line. My code is very long so I don't think it would necesarily help to post all of it, but the array dimensions are very large with a particularly large stack size. 

Help is appreciated :)

**Comment by Chasego** [comment]
Can you use a simple and existing example to test it? Otherwise, we can't know it's the problems of your computer setting or bugs within your code.

**Comment by fchollet** [comment]
Most likely that is a segfault in the C part of Theano. And most likely, you are on Windows. 

Windows support is pretty poor for Theano. In general, if you are serious about doing scientific computing on your machine, you should be using Unix. Keras is never tested on Windows, and if it works, then you're just lucky.

**Comment by valexandersaulys** [comment]
huh weird no I'm on linux, Kubuntu 15.04 specifically. Let me see if I can
simplify it and still get the same error.

**Comment by fchollet** [comment]
A quick test you could try would be to run your code on a different machine and OS (e.g. on EC2), see if it behaves any differently.

**Comment by valexandersaulys** [comment]
Hey I'm not running into the issue anymore, so I'm going to close this.
Thanks for all the help!

For the sake of posterity, I don't know what I changed that caused it to
stop. I think it might have to do with trying to build far too large of a
convolutional neural network, I was trying stack sizes of 1010 or so.
