### ISSUE TITLE
Creating a model with a new Input creates a model-in-model.

### ISSUE THREAD

**Issue by TimZaman** [fchollet/keras#8131]
Creating an existing `Model` with a new `Input` (by using `Model`'s `call` method) created a new model stacked on top of that new input. Example:

```python
model =  ..

new_input = keras.layers.Input(shape=(784,))
new_model = keras.models.Model(inputs=[new_input], outputs=[model(new_input)])
```

Although functional, the summary however, now shows this:
```
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 784)               0         
_________________________________________________________________
orig_model (Model)           (None, 10)                669706    
=================================================================
```
How do I flatten this?

**Comment by fchollet** [comment]
This is nominal behavior: if you use a model as a layer, we treat it as a layer.

If you need to print the original summary, you still get access to it via `model.layers[1].summary()`.

Otherwise, you can also do `outputs = model.call(inputs)` then `new_model = Model(inputs, outputs)`.

**Comment by vijaychav** [comment]
@fchollet, thanks for your tip. But I am encountering this error on using model.call(inputs)
`TypeError: Output tensors to a Model must be Keras tensors. Found: Tensor...`

Any suggestion on how to convert the tensor to a Keras tensor? Thanks!

**Comment by TimZaman** [comment]
He might refer to the `model.__call__` which I am using in the snippet (`model(new_input)`), which gives the problem above. I can recall that I once made a function to flatten nested models but I seem to have forgotten how..

**Comment by TimZaman** [comment]
Any idea how to get around this nominal behavior?

**Comment by vijaychav** [comment]
Looks like `keras.models.clone_model()` can be used here.
==> `keras.models.clone_model(old_model, new_input_layer)`

**Comment by CA4GitHub** [comment]
@viirya the `keras.models.clone_model(old_model, new_input_layer` results in new_input_layer connected to the old_model's input_layer followed by the rest of the old_model.  Is there a way to just get the new_input_layer connected to the rest of the old_model w/o the old_model's input_layer?

**Comment by devanshkv** [comment]
@CA4GitHub I am also facing the same issue. Any luck getting a fix?

**Comment by pewalh** [comment]
just add the "call" method. It will drop the old input and connect the new one without stacking the models


```
model =  ..

new_input = keras.layers.Input(shape=(784,))
new_model = keras.models.Model(inputs=[new_input], outputs=[model.call(new_input)])

````

note: outputs=[model.**_call_**(new_input)]

**Comment by devanshkv** [comment]
@pewalh Thanks a lot! this works perfectly!

**Comment by THalfar** [comment]
@pewalh Big thanks for this information! Helped me a lot.
