### ISSUE TITLE
How can i load a model into a new model with the same structure but different layer names?

### ISSUE THREAD

**Issue by IstrateRoxana** [fchollet/keras#8134]
I checked a model h5 file and i saw that the weights of the layers are kept in a dictionary having as key the layer name. If i want to load the weights of another network with the exact same structure from another model file where the only thing that differs is the layer names, how can i do it?

Since the layers are kept in a dictionary which is sorted alphabetically i see no way of initialising a second model without first creating and compiling the old one. 

Is this right or I am missing something?

**Comment by fchollet** [comment]
By default, `model.load_weights(fname)` only looks at the model structure, not at layer names. You don't need to do anything special, it will just work.

**Comment by IstrateRoxana** [comment]
I see. But when I inspect the hd5 myself I get a dictionary of length the
size of the number of weights. If the dictionary keys are not order based
on the layer order but based on the alphabetical order, and considering
that more than 2 weights can have the same shape, how do you know how to
correctly initialize the weights?
