### ISSUE TITLE
In Keras with TF backend, how to load weights to a model which has different input shape as the pre-trained model?

### ISSUE THREAD

**Issue by toseattle** [fchollet/keras#8142]
Say, I trained a model M1 with input_shape as (a, a, 1), and saved the weights in a hdf5 file for future use. Now I build another model M2 which is the same as M1 except the input_shape. It is (c, d, 1) in M2 model, and 'a' is not equal to 'c' or 'd'. How can I load the M1 trained weights to M2?

**Comment by hutauf** [comment]
This depends on what your features stand for. Usually something like this doesn't make any sense. Say a=2 and c=4, then a very simple network would use your old data (0,1) and multiply it with your weights (1,1). The result would be 1.
Now your new input is (0,1,2,3), and it has the weights (1,1). What should it do now?

I guess what you really need to do is to map the new features onto your old using some preprocess, then just feed it into M1.

**Comment by toseattle** [comment]
'a', 'c' and 'd' are the width and height of images. Not a classification task, the input and the final output of the model would have exactly the same dimension.

**Comment by toseattle** [comment]
Remove 'BN' would solve this issue.

**Comment by DanielBonanno** [comment]
@toseattle what do you mean remove 'BN'? Thanks
