### ISSUE TITLE
no dilation_rate in SeparableConv2D and Conv2DTranspose

### ISSUE THREAD

**Issue by Dobiasd** [fchollet/keras#8146]
The [documentation of `Conv2DTranspose` describes](https://github.com/fchollet/keras/blob/7af02c324004e6a743120c244101f44ce661dcdf/keras/layers/convolutional.py#L632) the parameter `dilation_rate`. However the class [actually does not take such a parameter](https://github.com/fchollet/keras/blob/7af02c324004e6a743120c244101f44ce661dcdf/keras/layers/convolutional.py#L679).

Additionally the [documentation of SeparableConv2D](https://github.com/fchollet/keras/blob/7af02c324004e6a743120c244101f44ce661dcdf/keras/layers/convolutional.py#L1066) also talks about `dilation_rate`, but this class also does not support dilation.

**Comment by Dobiasd** [comment]
Additionally I just noticed the [documentation of SeparableConv2D](https://github.com/fchollet/keras/blob/7af02c324004e6a743120c244101f44ce661dcdf/keras/layers/convolutional.py#L1066) talks about `dilation_rate`, however the class does not support dilation at all.

(Since I don't want to spam the repo with these small issues, I report it here.)

**Comment by Dref360** [comment]
dilation_rate is a parameter to the parent class `Conv2D`. The dilation_rate will be inside the `kwargs`.
https://github.com/fchollet/keras/blob/7af02c324004e6a743120c244101f44ce661dcdf/keras/layers/convolutional.py#L430

Please close.

**Comment by Dobiasd** [comment]
You are absolutely right of course. I totally missed `kwargs`. Sorry, and thanks for the explanation.

**Comment by Dobiasd** [comment]
Sorry again, but I have to re-open this issue.

The `SeparableConv2D` layer does not support `dilation_rate` despite forwarding `kwargs` as far as I can tell.

The [actual call to the backend function `separable_conv2d`](https://github.com/fchollet/keras/blob/7af02c324004e6a743120c244101f44ce661dcdf/keras/layers/convolutional.py#L1214) does not use the possibly provided `dilation_rate`.

One can verify this with the following code snippet:

```python
from keras.models import Model
from keras.layers import Input, SeparableConv2D
from keras import backend as K

assert K.backend() == "tensorflow"
assert K.floatx() == "float32"
assert K.image_data_format() == 'channels_last'

kernel_size = (2, 1)
strides = (1, 1)
padding = 'valid'
input_shape = (6, 1, 1)
inp = Input(shape=input_shape)
sep_1_1 = SeparableConv2D(1, kernel_size, strides=strides,
                          padding=padding, dilation_rate=(1, 1))
sep_2_1 = SeparableConv2D(1, kernel_size, strides=strides,
                          padding=padding, dilation_rate=(2, 1))
print('layer input shape     ', input_shape)
print('layer sep_1_1 shape', sep_1_1(inp).shape)
print('layer sep_2_1 shape', sep_2_1(inp).shape)

k_inp = K.constant([[[[0]],[[1]],[[2]],[[3]],[[4]],[[5]]]])
k_sep_1_1_res = K.separable_conv2d(k_inp,
                                   sep_1_1.depthwise_kernel,
                                   sep_1_1.pointwise_kernel,
                                   strides=strides,
                                   padding=padding, dilation_rate=(1, 1))
k_sep_2_1_res = K.separable_conv2d(k_inp,
                                   sep_2_1.depthwise_kernel,
                                   sep_2_1.pointwise_kernel,
                                   strides=strides,
                                   padding=padding, dilation_rate=(2, 1))
print('k_inp.shape        ', k_inp.shape)
print('k_sep_1_1_res shape', k_sep_1_1_res.shape)
print('k_sep_2_1_res shape', k_sep_2_1_res.shape)
```

which outputs the following:
```
layer input shape      (6, 1, 1)
layer sep_1_1 shape (?, 5, 1, 1)
layer sep_2_1 shape (?, 5, 1, 1)
k_inp.shape         (1, 6, 1, 1)
k_sep_1_1_res shape (1, 5, 1, 1)
k_sep_2_1_res shape (1, 4, 1, 1)
```

The output shapes of the two `SeparableConv2D` layers (`layer sep_1_1 shape` and `layer sep_2_1 shape`) are the same, but they should not be. The output shapes of the backend function (`k_sep_1_1_res shape` and `k_sep_2_1_res shape`) shows this.

If `SeparableConv2D` would support `dilation_rate`, `layer sep_2_1 shape` would be `(?, 4, 1, 1)`.

**Comment by Dref360** [comment]
Will take a look, thanks for reporting this issue.

**Comment by Dobiasd** [comment]
Wow, that fix was quick. Thanks a lot.

With [`Conv2DTranspose`](https://github.com/fchollet/keras/blob/7af02c324004e6a743120c244101f44ce661dcdf/keras/layers/convolutional.py#L632) I am not sure. The [call to the backend](https://github.com/fchollet/keras/blob/7af02c324004e6a743120c244101f44ce661dcdf/keras/layers/convolutional.py#L768) also does not include `dilation_rate`, but I can not compare its behaviour to the pure [backend function `conv2d_transpose`](https://github.com/fchollet/keras/blob/c2268794ab638dd1c4f85b67b582ceb08acfe3c1/keras/backend/tensorflow_backend.py#L3280) since it does not even support dilation. Is there something else going on that dilates the kernels?

In the following test at least the output of a `Conv2DTranspose` layer with `dilation_rate == (2, 1)` has the same shape as with `dilation_rate == (1, 1)`.

```python
from keras.models import Model
from keras.layers import Input, Conv2DTranspose
from keras import backend as K
import numpy as np

assert K.backend() == "tensorflow"
assert K.floatx() == "float32"
assert K.image_data_format() == 'channels_last'

kernel_size = (2, 1)
strides = (1, 1)
padding = 'valid'
input_shape = (6, 1, 1)
inp = Input(shape=input_shape)
ct_1_1 = Conv2DTranspose(1, kernel_size, strides=strides,
                         padding=padding, dilation_rate=(1, 1))(inp)
ct_2_1 = Conv2DTranspose(1, kernel_size, strides=strides,
                         padding=padding, dilation_rate=(2, 1))(inp)
model = Model(inputs=inp, outputs=[ct_1_1, ct_2_1])
model.compile(optimizer='rmsprop', loss='mse')

data_in = np.random.random((1, *input_shape))

result = model.predict(data_in)
print('data_in.shape  ', data_in.shape)
print('result[0].shape', result[0].shape)
print('result[1].shape', result[1].shape)
```
output:
```
data_in.shape   (1, 6, 1, 1)
result[0].shape (1, 7, 1, 1)
result[1].shape (1, 7, 1, 1)
```
So perhaps by accident this layer type also currently does not support dilation?

**Comment by Dref360** [comment]
https://www.tensorflow.org/api_docs/python/tf/nn/conv2d_transpose

The dilation is not supported and I don't think it would make much sense? Conv2D is already *dilating* the image to make it bigger.

**Comment by Dobiasd** [comment]
OK, TensorFlow uses a separate function ([atrous_conv2d_transpose](https://www.tensorflow.org/api_docs/python/tf/nn/atrous_conv2d_transpose)) for this.

So in Keras `Conv2DTranspose` lets its base class (i.e. `Conv2D`) apply the dilation? It it normal that this is not visible in the output sizes in my Conv2DTranspose example above?

**Comment by Dobiasd** [comment]
Since this issue is closed now by the merge of the PR and I can not re-open is, I moves the `Conv2DTranspose` problem to a [separate issue](https://github.com/fchollet/keras/issues/8159).
