### ISSUE TITLE
How is keras calculating the accuracy in CNN?

### ISSUE THREAD

**Issue by dhariyalbhaskar** [fchollet/keras#8163]
I want to calculate the accuracy of my customized model. I have the loss value and last layer weights. Is there any way to calculate using keras functions?

**Comment by bdwyer2** [comment]
StackOverflow is the best place to ask this kind of question. Issues are for bug in Keras.

To answer your question look at [examples/cifar10_cnn.py](https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py#L67), specifically line 67

**Comment by dhariyalbhaskar** [comment]
Ok, I will post it in SO.
