### ISSUE TITLE
RuntimeError: Graph disconnected

### ISSUE THREAD

**Issue by gitmenonsandu** [fchollet/keras#8166]
I am running tensorflow 1.3.0 backend for keras 2.0.8.
While running the following code 
```
    import keras.backend as K

    input_img = Input(shape=(64,64,3))

    x1 = Conv2D(64, (3, 3), activation='relu', padding='same')(input_img)

    gateFactor = Input(tensor = K.variable([0.3]))

    fractionG = Multiply()([x1,gateFactor])

    complement = Lambda(lambda x: x[0] - x[1])([x1,fractionG])

    x = MaxPooling2D((2, 2), padding='same')(fractionG)
```

PS: All functions are properly imported. Complete code can be found [here](https://gist.github.com/gitmenonsandu/eb4badfa70dd0d18cc5dc2683e071353)

The following RunTimeError occurs while creating the model
RuntimeError: Graph disconnected: cannot obtain value for tensor <tf.Variable 'Variable_2:0' shape=(1,) dtype=float32_ref> at layer "input_6". The following previous layers were accessed without issue: ['input_5', 'conv2d_11']

**Comment by abhaikollara** [comment]
You have to include `gateFactor` as an input to your model, so your `Model` instantiation would look like
`model = Model([input_img, gateFactor], layers)`

**Comment by gitmenonsandu** [comment]
Thank you very much
That solved it

**Comment by StudentRepresentative** [comment]
I run the program in Google colab.....If i run the this line                                                               
model = Model(inputs = vgg.input,outputs=preds)
model = Model(inputs = base_model.input,outputs=preds) 
then it will show the below error. Why?
-----------------------------------------------------------------------------------------
ValueError Traceback (most recent call last)
in ()
----> 1 model = Model(inputs = vgg.input,outputs=preds)
2 model = Model(inputs = base_model.input,outputs=preds)

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in _map_graph_network(inputs, outputs)
1819 'The following previous layers '
1820 'were accessed without issue: ' +
-> 1821 str(layers_with_complete_input))
1822 for x in nest.flatten(node.output_tensors):
1823 computable_tensors.add(x)

ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_6:0", shape=(?, 224, 224, 3), dtype=float32) at layer "input_6". The following previous layers were accessed without issue: []

**Comment by StudentRepresentative** [comment]
I run the program in google colab....If i want to run this line 
model = Model(inputs = vgg.input,outputs=preds)
model = Model(inputs = base_model.input,outputs=preds)
then it will show the below error.Why?
---------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-54-280f8a2e9913> in <module>()
----> 1 model = Model(inputs = vgg.input,outputs=preds)
      2 model = Model(inputs = base_model.input,outputs=preds)

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in _map_graph_network(inputs, outputs)
   1819                              'The following previous layers '
   1820                              'were accessed without issue: ' +
-> 1821                              str(layers_with_complete_input))
   1822         for x in nest.flatten(node.output_tensors):
   1823           computable_tensors.add(x)

ValueError: Graph disconnected: cannot obtain value for tensor Tensor("input_12:0", shape=(?, 224, 224, 3), dtype=float32) at layer "input_12". The following previous layers were accessed without issue: []
