### ISSUE TITLE
LSTM layer cannot connect to Dense layer after Flatten

### ISSUE THREAD

**Issue by trungnt13** [fchollet/keras#818]
The following code given error when compile, input = (nb_samples,20,390):
```python
m = keras.models.Sequential()
# ====== LSTM ====== #
m.add(keras.layers.recurrent.LSTM(250, input_dim=390, return_sequences=True))
m.add(keras.layers.recurrent.LSTM(250, input_dim=390, return_sequences=True, input_length=20))
m.add(keras.layers.core.Flatten())
m.add(keras.layers.core.Dense(1024))
```
This is the stack trace:
> Traceback (most recent call last):
>   File "test.py", line 60, in <module>
>     m.add(keras.layers.core.Dense(1024))
>   File "keras/keras/layers/containers.py", line 37, in add
>     self.layers[-1].set_previous(self.layers[-2])
>   File "keras/keras/layers/core.py", line 32, in set_previous
>     assert self.input_ndim == len(layer.output_shape), "Incompatible shapes: layer expected input with ndim=" +\
>   File "keras/keras/layers/core.py", line 487, in output_shape
>     return (input_shape[0], np.prod(input_shape[1:]))
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2481, in prod
>     out=out, keepdims=keepdims)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/_methods.py", line 35, in _prod
>     return umr_prod(a, axis, dtype, out, keepdims)
> TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

However, this code work well:
```python
m = keras.models.Sequential()
# ====== LSTM ====== #
m.add(keras.layers.recurrent.LSTM(250, input_dim=390, return_sequences=True, input_length_20))
m.add(keras.layers.core.Flatten())
m.add(keras.layers.core.Dense(1024))
```
I think there is problem of keep track **input_dim** to second layer of LSTM

**Comment by fchollet** [comment]
There is no issue. Well, actually, there is one: the error message should be more helpful. 

Think about what you are asking your network to do. You are asking it to flatten a 3D tensor where one of the dimension (the length of the sequence) is unknown. Obviously not possible.

Easy to fix, though: simply tell the network what sequence length you are expecting using the `input_length` in the first layer. All of this is in the documentation, by the way. 

Also: do not provide shape information (`input_dim` or `input_length`) in other layers than the first one. That's useless and it will be ignored.

**Comment by LeavesBreathe** [comment]
> Also: do not provide shape information (input_dim or input_length) in other layers than the first one. That's useless and it will be ignored. These arguments are for the network input only, everything else will be automatically inferred.

If you're applying an embedding layer first, should you not provide any shape information the layer that follows? I would assume that this is automatically inferred?

**Comment by fchollet** [comment]
Yes, it's automatically inferred. Shape information should be provided to the fist layer only.

**Comment by LeavesBreathe** [comment]
Great thanks! That's what I figured

**Comment by anguyen8** [comment]
I've come across another use case that breaks the code similarly. i.e. even if I put input_dim/input_length properly in the first layer, but somewhere in the middle of the network I call e.g. K.spatial_2d_padding on a layer (which calls tf.pad on it) then the output layer of this spatial_2d_padding doesn't have _keras_shape anymore, and so breaks the **flatten**.

@fchollet Do you have any ideas how to solve this? Thanks!
