### ISSUE TITLE
Loading model from json/yaml

### ISSUE THREAD

**Issue by jeanpijon** [fchollet/keras#820]
Hi, 
I recently encountered an issue with serialization/deserialization of models. 
When someone create new type of model (e.g. we have GenSequential for loading data on the fly from generator) problem occurs when one tries to load it from file. 
In models.model_from_config there is a list of possible models, which doesn't count on newly created model types. Even if one modify this one, problem persist in keras.models.container_from_config where the same list comes to play again. 

I have a feeling, that initialization of model should be part of Model itself - only thing to do from outside is to choose right model and pass json to it. Model itself should be able to initialize itself from it. 

flow:
# load json
# pass it to the load_from_config()
# check if such a name exists in a namespace
# call class method of such model class and let that object initialize itself
# thats it

I can write such mod, but I would like to hear a bit from community. 
What do you think? Did I miss something? Does it make sense?

Regards
Jan

**Comment by joshburkart** [comment]
I think in general whether a layer/model/etc. can be accessed should be independent of which namespace it exists in. This is probably best achieved with "registration", which might look like
``` python
@models.register("new_model_etc")
class NewModelEtc(models.Model):
  pass
```
(Could also do it by changing `Model`'s metaclass. Probably other ways too.) The class decorator updates some global `dict` within `models`, and from then on any reference to the string "new_model_etc" in a JSON file or whatever can be mapped to the defined model. Similar deal for regularizers, optimizers, and such.

**Comment by jeanpijon** [comment]
Yes, it seems reasonable to me - if no one will look into it, I would start to. But before I would like to hear from the community. Also a quick look into utils/layer_utils.py reveals lots of the new ad hoc code in container_from_config(...)
