### ISSUE TITLE
'float' object has no attribute 'get_value' problem.

### ISSUE THREAD

**Issue by MoyanZitto** [fchollet/keras#821]
When I was trying to print the configuration of a model by "model.get_config()" or trying to save my model as a 'json' file:

json_str = autoEncoder.to_json()
open('temp_model.json','w').write(json_str)
autoEncoder.save_weights('temp_model_weights.h5')

It raise the exception "float object has no attribute 'get_value' " in file 'optimizer.py', in class SGD(because I was using SGD as the optimizer), the definition of get_config() is:

 def get_config(self):
        return {"name": self.__class__.__name__,
                "lr": float(self.lr.get_value()),
                "momentum": float(self.momentum.get_value()),
                "decay": float(self.decay.get_value()),
                "nesterov": self.nesterov}

while the __init__ of class SGD does not contain decay and nesterov

    def __init__(self, lr=0.01, momentum=0., decay=0., nesterov=False, *args, **kwargs):
        super(SGD, self).__init__(**kwargs)
        self.__dict__.update(locals())
        self.iterations = shared_scalar(0)
        self.lr = shared_scalar(lr)
        self.momentum = shared_scalar(momentum)

Is it a bug? Can I fix the problem by adding 'self.decay = shared_scalar(decay)' or something like this?

Thank you very much!

**Comment by MoyanZitto** [comment]
well, it seems I can't fix it by myself....sad ￣﹏￣

**Comment by jfsantos** [comment]
`self.__dict__.update(locals())` sets up all the named parameters from `__init__` to the created object, so a correctly initialized object of class `SGD` should have both `decay` and `nesterov`. The problem here is that `decay` is a float and not a shared Theano variable. I'll fix this in a bit.
