### ISSUE TITLE
How to set LSTM parameters

### ISSUE THREAD

**Issue by sdustwdd** [fchollet/keras#822]
Hi,
Now, I use LSTM to process EEG data,but you know that in LSTM may be have many parameters ,but I don't know how to choose,
such as I have a matrix (10,796,1035),the the number of LSTM layer and the number of units ....

**Comment by LeavesBreathe** [comment]
I'd read the docs section on lstm -- very informative http://keras.io/layers/recurrent/#lstm

However, they haven't updated it to reflect the new api yet.
