### ISSUE TITLE
test function not working 'module' object has no attribute 'relu'

### ISSUE THREAD

**Issue by seven808** [fchollet/keras#825]
I just installed theano and all its dependencies as well as keras and all its dependencies...

when I want to run the test functions (e.g. test_graph_model.py) I get an error as follow

```
Traceback (most recent call last):
File "test_graph_model.py", line 58, in test_1o_1i_2
    graph.compile('rmsprop', {'output1': 'mse'})
File "build/bdist.linux-x86_64/egg/keras/models.py", line 581, in compile
    y_train = output.get_output(True)
File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 305, in get_output
    s = self.layers[0].get_output(train)
File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 411, in get_output
    return self.activation(X)
File "build/bdist.linux-x86_64/egg/keras/activations.py", line 20, in relu
    return T.nnet.relu(x)

AttributeError: 'module' object has no attribute 'relu'

```  

I have the newest version of theano and keras... what could cause the error?
By the way the very same error appears in all test functions except *test_datasets.py* and *test_embeddings.py*

Thanks for your help!!

**Comment by jfsantos** [comment]
How did you install Theano and Keras? `T.nnet.relu` should be found in a correctly-installed Theano.

**Comment by fchollet** [comment]
For the record, you need bleeding-edge Theano (get it from the Theano
repo). It's necessary for more than the relus, since Keras relies on bug
fixes not found on the PyPI version of Theano.

**Comment by seven808** [comment]
thanks! I somehow installed theano via pip... 
I cloned the repo and installed via the setup.py :) now it's working

**Comment by daleloogn** [comment]
how to resolve this problem :+1: 
AttributeError: 'module' object has no attribute 'relu'

**Comment by xuxy09** [comment]
Thanks, I re-installed the Theano via setup.py from git, and it works!

**Comment by anirban93** [comment]
I have reinstalled but the error remains. What possibly can go wrong ?

**Comment by manasRK** [comment]
relu is only in the dev version of Theano. Update Theano to it: 

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

Download the zip from Github, and run ``` python setup.py develop ```
