### ISSUE TITLE
How to get difference or square between two tensor？

### ISSUE THREAD

**Issue by shichengcn** [fchollet/keras#8292]
I define two subnets that output the tensor of the same dimension use functional model. I want get  difference between them. for example：tensor1 [1,2,3,4,5], tensor2 [1,1,1,1,1], output=tensor1 -tensor2 =[0,1,2,3,4]
I don't know how to coding it in keras，I found  “keras.layers.merge.Add()”，but i want difference，so i try “Add([tensor1 ,-tensor2])”, it is  wrong
Can you tell me how to get difference between two tensor，or square of one  tensor？
Thank you very much.

**Comment by srv902** [comment]
There is subtract function in keras.layers under merge section of the Keras doc. Also, you can use Lambda layer with lambda functions to do the same.

**Comment by shichengcn** [comment]
I refer to the Chinese document at the beginning, Part of the content is omitted. when I read the English document, I also found a solution.Thank you, buddy@srv902
