### ISSUE TITLE
Creating AUC/ROC after run.

### ISSUE THREAD

**Issue by KeironO** [fchollet/keras#832]
Could somebody point me in the right direction of how to do this? 

Thank you,

Keiron.

**Comment by elanmart** [comment]
`preds = my_model.predict_proba(X_val)`

then just use `sklearn`:
 [sklearn.metrics.roc_auc_score](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html#sklearn.metrics.roc_auc_score)
[sklearn.examples.plot_roc](http://scikit-learn.org/stable/auto_examples/plot_roc.html)

**Comment by KeironO** [comment]
Thank you :)

On 14 October 2015 at 12:07, Marcin Elantkowski <notifications@github.com>
wrote:

> preds = my_model.predict_proba(X_val)
>
> then just use sklearn:
> sklearn.metrics.roc_auc_score
> <http://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_auc_score.html#sklearn.metrics.roc_auc_score>
> sklearn.examples.plot_roc
> <http://scikit-learn.org/stable/auto_examples/plot_roc.html>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fchollet/keras/issues/832#issuecomment-148019073>.
>



-- 
Keiron O'Shea 毛毛
King Abdullah University of Science and Technology
Visiting Research Student, Computational Bioscience Research Center
Ymweld â myfyriwr ymchwil, Chyfrifiannol Canolfan Ymchwil Biowyddoniaeth

Aberystwyth University
PhD Student, Department of Computer Science
Israddedig, Adran o Cyfrifiadureg
keo7@aber.ac.uk || KeironTeilo.OShea@Kaust.edu.sa ||
http://users.aber.ac.uk/keo7

**Comment by kimardenmiller** [comment]
When I call fit first I get an error:
``` 
for (train, test), color in zip(cv.split(X, y), colors):
    probass = model.fit(X[train], y[train]).predict_proba(X[test])

==> probass = model.fit(X[train], y[train]).predict_proba(X[test])
AttributeError: 'History' object has no attribute 'predict_proba'
```

If I don't call fit first I get curves, but that seems wrong somehow?
![image](https://cloud.githubusercontent.com/assets/2165336/21509290/59a9c6b8-cc3c-11e6-83bf-c87326496f2d.png)

**Comment by yelongclass** [comment]
I am using Keras 2.0.6. When I used model.fit(X[train], y[train]).predict_proba(X[test]) or model.predict_proba(X[test]), it always say `AttributeError: 'Model' object has no attribute 'predict_classes'`.
I do not know why. Could you help resolve this problem?

**Comment by FernanOrtega** [comment]
@yelongclass Are you using Functional API? In that case, the method 'predict_proba' doesn't exist.

**Comment by fabricecarles** [comment]
@kimardenmiller I have exactly the same code and the same issue. As you said without calling model.fit  the model is wrong (ie not trained).
