### ISSUE TITLE
fit_generator    TypeError: function object is not an iterator

### ISSUE THREAD

**Issue by jt827859032** [fchollet/keras#8321]
When I'm using fit_generator function with my own generator, I got the error code here.
`
Exception in thread Thread-1:
    Traceback (most recent call last):
    File "/opt/software/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_innerself.run()
    File "/opt/software/anaconda2/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs)
    File "/opt/software/anaconda2/lib/python2.7/site-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
TypeError: function object is not an iterator
Epoch 1/100
Traceback (most recent call last):
    File "xception.py", line 85, in <module>
    model.fit_generator(train_gen, steps_per_epoch=5380, epochs=100, callbacks=[checkpoint], verbose=1)
    File "/opt/software/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
    File "/opt/software/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
StopIteration
`

while my generator is coded like this:

`

def data_generator():
    datapath = '../images/crop_train_images/'
    csvpath = '../images/crop_train_images.csv'
    csvfile = pd.read_csv(csvpath)

    train_images = []
    train_labels = []
    
    while True:
        for index, (image_id,label_id) in csvfile.iterrows():
            index = int(index)
            image_id = str(image_id)
            label_id = int(label_id)
            print(index)
            furl = datapath + image_id.replace('.jpg', '.npy')
            images = np.load(furl)
            for idx in range(len(images)):
                train_images.append(images[idx])
                train_labels.append(np.squeeze(to_categorical(label_id, 80)))
            if index !=0 and index % 10 == 0 or index == len(csvfile)-1:
                train_images = np.array(train_images)
                train_labels = np.array(train_labels)
                N = train_images.shape[0]
                choice = random.sample(range(N), N)
                train_images = train_images[choice] 
                train_labels = train_labels[choice]
                yield (train_images, train_labels)
                train_images = []
                train_labels = []
`
I've tried to use the data_generator function to load data and it goes well. But when using the fit_generator function , there threw an exception and i don't know where goes wrong . can someone help me figure out what had happened?

**Comment by monktastic** [comment]
The formatting is messed up in your question, so we can't see the full generator. Also, I don't see where you are using the generator.

Nonetheless, a common cause for this is passing the generator function itself, rather than calling it. That is, you should be doing:

```
m2.fit_generator(my_generator(), ...)
```

Not
```
m2.fit_generator(my_generator, ...)
```

**Comment by jt827859032** [comment]
@monktastic thank you for your reply!!!! It's my mistake, I correct this part you mentioned and my code goes well !!!
