### ISSUE TITLE
nb_samples, timesteps, input_dim Explanation

### ISSUE THREAD

**Issue by KOHMA** [fchollet/keras#834]
Hey, I am currently working on a LSTM Music Composer.
Looking at the required Input Shape of LSTM the Documentation states as follows: Input shape: 3D tensor with shape: (nb_samples, timesteps, input_dim).
I was wondering what nb_samples, timesteps, and input_dim actually mean exactly. I know it must be obvious, but I couldn't figure out what nb_samples is exactly referring to.

So I am going to feed my LSTM RNN with a piano roll like representation of a Midi File. So it's a matrix with ones and zeros, 1 meaning note_on, 0 meaning note_off. So what I have as piano roll is a matrix with each row representing one note (= input_dim?) and the columns representing one Midi tick (timing in midi files) (= timesteps?). This tells the Net which Note is on at what point in time. But I can't figure what the third dimension should be in my case.

Thanks for your help!

**Comment by fchollet** [comment]
Assumedly you have more than a single MIDI file (otherwise you won't be learning much). So each MIDI file you have is a "sample", and the 0th dimension of your input tensor is your different files.

**Comment by KOHMA** [comment]
Thanks for giving proof to my assumption :)

**Comment by mphielipp** [comment]
So this a correct (simplify) example , isn't it? 
X = [  [ [1, 4, 2, 0] , [2, 3, 1, 0],  [3,7,8,0] ] , [1,1,1,0],4].

X = self.get_input(train)  # shape: (nb_samples, time (padded with zeros), input_dim)
        # new shape: (time, nb_samples, input_dim) -> because theano.scan iterates over main dimension
        padded_mask = self.get_padded_shuffled_mask(train, X, pad=1)
        X = X.dimshuffle((1, 0, 2))
        x = T.dot(X, self.W) + self.b
