### ISSUE TITLE
TFOptimizer does not apply constraints

### ISSUE THREAD

**Issue by staticfloat** [fchollet/keras#8360]
Hello there, I recently started using the [YellowFin](https://arxiv.org/abs/1706.03471) optimizer in my models ([keras implementation here](https://github.com/nnormandin/yellowfin_keras)), which is implemented through the `TFOptimizer` class.  This kind of an optimizer has a few downsides, but one I was not expecting was the fact that it does not apply constraints!

Looking through `optimizers.py`, it becomes clear that every other optimizer has an explicit section in which constraints are applied (Example: [`SGD`](https://github.com/fchollet/keras/blob/e5f2fb7852b505893e863a0c0fc0598a73e52372/keras/optimizers.py#L176-L178)), however [`TFOptimizer` does not](https://github.com/fchollet/keras/blob/e5f2fb7852b505893e863a0c0fc0598a73e52372/keras/optimizers.py#L626-L632).

Is this intentional?  Is there some fundamental reason behind why a `TFOptimizer` cannot have the constraints applied to it in the same way as other optimizers?  It seems to me we can still iterate over the parameters, check for the `constraint` attribute, and if it exists, apply it.

**Comment by fchollet** [comment]
There is a reason, which is that the underlying TF optimizer applies the constraints itself. So, no need to do it on the Keras side.
