### ISSUE TITLE
Extend fit_generator to with fit_sequence to handle parallelization

### ISSUE THREAD

**Issue by josepablog** [fchollet/keras#8362]
Hello,

Never contributed to Keras before, but I am interested in creating a PR with a new feature, but before I do so, I want to get feedback and check if it would be accepted :P 

The function ``fit_generator'' is extremely useful, but it is difficult to use parallelized.  It expects a generator, which are not thread-safe in Python.  Alternatively,  it can run each generator on a different process, but then it is likely that you would end with duplicated observations across processes since generators can't talk to each other.

The class [`keras.utils.Sequence`](https://keras.io/utils/) is a very useful work-around, but it's not very well documented and not easy to use (it requires an undocumented `OrderedEnqueuer` wrapper, etc.)  I am interested in creating a `fit_sequence` method that takes care of this. 

Thoughts?

Thanks,
Jose

**Comment by josepablog** [comment]
PS: I think the name `Sequence` is unfortunate, as it may get confused with sequential models

**Comment by josepablog** [comment]
it looks like fit_generator already supports sequences, it's just not documented!

**Comment by rawmean** [comment]
lack of documentation for `feral.utils.Sequence` makes it unusable.
