### ISSUE TITLE
Does keras support distributed computing?

### ISSUE THREAD

**Issue by komal436** [fchollet/keras#8392]
Hi,

I have huge amount of training data (around 52Gb). I can't load it onto memory as numpy array to pass it to keras models.
So, I used spark to create an rdd. I am not sure how to pass the rdd's to keras? 
What is the best approach to send that huge amount of data to keras models on local machine of 32Gb RAM?

**Comment by fchollet** [comment]
There are various things you could do. Maybe the simplest would be to use third-party implementations of support for Keras on Spark.
E.g. [dist-keras](https://github.com/cerndb/dist-keras) or [elephas](https://github.com/maxpumperla/elephas).

In general, if you want to feed a Keras model with a large amount of data you should be using `fit_generator` with a Python generator (or Keras `Sequence` instance). In your case, you'd need to figure out how to get your generator or sequence to pull data from remote sources.

**Comment by komal436** [comment]
@fchollet Thanks. 
I don't find any good example that helps in creating a keras sequence instance and passing to keras models.
If the participants knows, please share it.
Thanks.

**Comment by komal436** [comment]
Thanks, I figured out it. 
class KSequence(Sequence):
     def __init__(self, **args):
         <implement>
     def __len__(self, **args):
         <implement>
     def __getItem__(self, **args):
        <implement>
     def on_epoch_end(self, **args):
       <implement>
