### ISSUE TITLE
Can I set the session on a per model basis?

### ISSUE THREAD

**Issue by baluyotraf** [fchollet/keras#8405]
I'm trying to build a model which can be cleared afterwards. However it seems that set_session and clear_session does it globally. It is possible to do it per model?

**Comment by datumbox** [comment]
Unfortunately, as far as I know, there is no way to clear a specific model from memory. It's either all or nothing. 

What I typically do is wrap my models in pipelines; at the end of each stage the model is stored on disk and the session is cleared. It's not great but it has the nice side-effect of keeping your pipelines modular.

**Comment by baluyotraf** [comment]
I see. If that's the case, I'm thinking if I can have different sessions. Then each time I do an operation on a model, I switch the global session to its corresponding model session. I'll try and go back to see if that works. However, I'm not sure it is a good way around it.

That being said, thanks for your suggestion. I'll also give it a try.

**Comment by fchollet** [comment]
You can wrap all code related to model A into a session scope for session A, and likewise with another model B / session B.

i.e.

```python
with sess_A.as_default():
    ...

with sess_B.as_default():
   ...
```
