### ISSUE TITLE
Does keras have any plans to support multi-dimensional LSTM？

### ISSUE THREAD

**Issue by shampool** [fchollet/keras#842]

**Comment by jmhessel** [comment]
You mean stacked LSTMs? Yes, it currently does. Also, you might want to ask this type of question on the keras-users google group.

**Comment by shampool** [comment]
@jmhessel  No, I meant the LSTM described in this paper: http://arxiv.org/pdf/0705.2011.pdf

**Comment by jmhessel** [comment]
Oh, I see. I can't think of how that could be implemented at the moment, no.

**Comment by fchollet** [comment]
No, if you are doing funky things like you are almost certainly better off working directly in Theano. There are assumptions in Keras that make it unsuitable for *certain* types of research, and multi-dimensional RNNs in one of these cases.

**Comment by davidbuniat** [comment]
What do you think about modifying DeepRNN such that? 
1) Hidden layer matrix vector instead will be +1 dimension with matrix with shape ((shape_hidden_layer_units), N - number of dimensions in the sequence)
2) Instead of accessing up to -depth steps, there will be only access the -size per each dimension on each step and taking only [(n_hidden_layer_units), nth dimension]

Does that sound feasible?

Sorry if it is not that clear and not well formulated, I can explain in depth if there is a need, I hope you can get the idea.

**Comment by shampool** [comment]
＠davidbuniat  that sounds very interesting! Could you elaborate it a little more? 
Thanks!

**Comment by shampool** [comment]
@davidbuniat

**Comment by davidbuniat** [comment]
@shampool Suppose you have an image (2D, with 300x400px). Reshape it into 1D vector (with 120,000px) on each rnn scan step access h-1 element and (h-400) element. Number 400 is based on how the reshape is done on your image. And you can expand this into multidimensional case. 

I might be wrong, but seems scan supports multiple access to previous ones. I need MDRNN as well and I think to implement Grid LSTM which seems more powerful. In case of success in implementation let me know, I will as well.

**Comment by shampool** [comment]
＠davidbuniat  That sounds doable. If we make the taps fixed, things might be easier. But in certain types of traversal of the 2D grid. We may need taps to be able to chang over time. I am not sure if scan supports that. 

Will let you know, if I finally make it work.

Thanks!

**Comment by shampool** [comment]
@davidbuniat

**Comment by arita297** [comment]
@davidbuniat 
Wondering if you had positive results  on this : 
(2D, with 300x400px). Reshape it into 1D vector (with 120,000px)

**Comment by davidbuniat** [comment]
No ,@arita297 as I said before I moved to Torch and I got positive results on MNIST dataset with 28x28 reshaping to 784px which I will agree is very far from 120,000px. Reshaping into 1D is just an idea how you could overcome Theano limitations. Furthermore, you might also consider to split the 120,000px into chunks and feed iteratively (should be very careful).

**Comment by BenjaminAbdi** [comment]
"No, if you are doing funky things like you are almost certainly better off working directly in Theano. There are assumptions in Keras that make it unsuitable for certain types of research, and multi-dimensional RNNs in one of these cases."

@fchollet : Is it thus pointless that I try to make my own layer of MD-LSTM, from existing implementation, fit the "build-your-own-layer" canvas ?

**Comment by xylcbd** [comment]
so , does keras support multi-dimensional LSTM now ?

**Comment by egottschalk** [comment]
+1

**Comment by 123mitnik** [comment]
+1

**Comment by ypxie** [comment]
I have a 2D implementation of several RNN, but they are pretty old and for pre-functional keras api. Will put it somewhere when I got time.

**Comment by Jeronymous** [comment]
+1

**Comment by grodinh** [comment]
:+1:

**Comment by wellescastro** [comment]
+1

**Comment by omrivm** [comment]
+1

**Comment by zibayii** [comment]
I really need to 2_dimentional LSTM in kers for my project and i have a little time,
Please give me this code
Thanks alot
