### ISSUE TITLE
Deconvolution 3D

### ISSUE THREAD

**Issue by tsharmamba2014** [fchollet/keras#8427]
Hi - We have been using deconvolution 3D for our algo but it seems that this has been removed from contrib.layers.convolutional Is there any other alternative to using deconvolution 3d ?

**Comment by Dref360** [comment]
You can use the tf function and wrap it with a Lambda layer
https://www.tensorflow.org/api_docs/python/tf/nn/conv3d_transpose

**Comment by fchollet** [comment]
We currently have a `Conv3DTranspose` layer in `keras.layers`, that's probably what you want to use.

**Comment by petrare** [comment]
I would also need 3d deconvolution but I don't seem to have it in keras.layers? Do you know what may be the issue?

**Comment by Nassimcfc23** [comment]
3d deconvolution is conv3dtranspose ..

**Comment by Meiyd** [comment]
But there is problem with conv3dtranspose, which is that if we give a dynamic shape as input to conv3dtranspose, it returns us an error. This problem has not been fixed since years.
