### ISSUE TITLE
Post processing with ImageDataGenerator 

### ISSUE THREAD

**Issue by abhinav-iiit** [fchollet/keras#8441]
ImageDataGenerator offers argument of 'preprocessing_function' which is run BEFORE any modification  is made to input. I want to perform CLAHE on image input AFTER modifications like random shifts, rotations etc have been made to it. Please suggest a suitable way out.

**Comment by maderafunk** [comment]
I think this in a mistake in the documentation, I also stumbled upon this.
When you look at the code, the preprocess_function is executed at first in the "standardize" function. However, in the Generator, the "standardize" function is executed after the "random_transform" function, which is responsible for the shifts, rotations etc.

So actually, it behaves exactly as you want now, the documentation is just wrong,
