### ISSUE TITLE
Unable to create custom merge operation

### ISSUE THREAD

**Issue by shaifugpt** [fchollet/keras#8445]
I want to create a custom merge operation similar to Average().

class Average1(Merge):
    """Layer that averages a list of inputs.
    It takes as input a list of tensors,
    all of the same shape, and returns
    a single tensor (also of the same shape).
    """

    def _merge_function(self, inputs):
        print("here")
        output = inputs[0]
        for i in range(1, len(inputs)):
            output += inputs[i]
        return output / len(inputs)

Does not execute merge function as print("here") does not get printed

**Comment by roya0045** [comment]
Print statements are not executed in the model, this doesn't mean that the merge function is not properly executed. Just check the output tensor to see if everything is ok.

And use class Average1(_Merge): for proper inheritance, just to be safe.
