### ISSUE TITLE
engine.training.evaluate_generator failing when input is sparse

### ISSUE THREAD

**Issue by asos-saul** [fchollet/keras#8454]
When the input is a scipy sparse vector, evaluate_generator fails:
`TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]`

The fix looks simple, just replace the failing line:
https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L2220
with its correct counterpart in fit_generator:
https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L2069

Cheers,
Saúl

**Comment by fchollet** [comment]
Feel free to open a PR.

**Comment by asos-saul** [comment]
Will do.

**Comment by asos-saul** [comment]
Fixed!
