### ISSUE TITLE
Change lr without recompiling the model

### ISSUE THREAD

**Issue by RaduStoicescu** [fchollet/keras#8457]
Can I change the lr without model.compile(), if I compile the model several times I run out of memory. If I use clear_session() I lose the weights.

Is there a way to change the lr without recompiling?

**Comment by roya0045** [comment]
https://keras.io/callbacks/
This should contain what you want.

**Comment by fchollet** [comment]
> If I use clear_session() I lose the weights.

You could use `get_weights` / `set_weights`...

Note that you can change the learning rate at any time via `K.set_value(model.optimizer.lr, value)` (see code in the learning rate scheduler callback).
