### ISSUE TITLE
Drive layer weights to zero

### ISSUE THREAD

**Issue by SyedAhsanAnsar** [fchollet/keras#847]
Is there a way to drive layer weights to 0 using regularization? I have lots of irrelevant inputs and I want to generate sparse weight matrices.

**Comment by fchollet** [comment]
Sure, you can simply use a [weight regularizer](http://keras.io/regularizers/).

**Comment by pipiyang** [comment]
Hi, I noticed the weight regularizer has been removed from keras. What's the new option to set sparsity weight matrix?

Thanks

**Comment by the-moliver** [comment]
Not removed, just renamed to kernel_regularizer.
