### ISSUE TITLE
LSTM multiclass prediction

### ISSUE THREAD

**Issue by ngopee** [fchollet/keras#848]
I am currently trying to run an LSTM on multi classes. The input is in the form:

```
x_train = [[1,2,3,4,5],[1,2,3,4,5]]
y_train = [[[1],[2],[3],[4],[5]],[[3],[4],[5],[6],[4]]] #keras require a 3d matrix
```
However, I am getting prediction of all 0s

When I'm compiling, I'm using:

```
model.compile(loss='categorical_crossentropy', optimizer='adam', class_mode="categorical")
```
Can anybody point out how I should train such LSTM?

PS. The idea is to train an LSTM to do POS Tagging on Penn Tree bank where each array in x_train is a sentence and each integer represent a word and each integer in y_train is a tag.

**Comment by fchollet** [comment]
Something like:

```python
model = Sequential()
model.add(Embedding(nb_words, 256))
model.add(LSTM(128, return_sequences=True))
model.add(TimeDistributedDense(nb_classes))
model.add(Activation('softmax'))
```
