### ISSUE TITLE
How to read 16 bit COLOR image with flow_from_directory?

### ISSUE THREAD

**Issue by FrostedPenguin** [fchollet/keras#8497]
Currently I have bunch of 16bit color image as training set. (So each RGB channel is 16 bit not 8 bit)
I know `flow_from_directory` use PIL as its backend and PIL possibly can read 16bit grey image. But I'm not sure it can read 16bit color image.
Currently flow_from_directory read image as 8 bit. So it shrink 16bit to 8bit and give it to me.
I've searched quite a lot of examples but couldn't find right answer.
Is there any idea?

**Comment by shaantamchawla** [comment]
@lazysquid were you able to find a solution to this? I am having the exact same issue right now.

**Comment by lazysquid** [comment]
@shaantamchawla No I couldn't find any good solution for this problem. I made my 16bit images into 8bit PNG images and then read those PNG images.
