### ISSUE TITLE
Image caption generation in the style of Vinyals et al. 

### ISSUE THREAD

**Issue by avisingh599** [fchollet/keras#851]
Hello,

I am interested in implementing a system that is similar to the current image caption generation example of Keras, but with one difference: Instead of feeding the image feature vector at every time step of the RNN, I only want to feed it once (i.e. the first time step), and the rest of input vectors to the RNN will be word vectors. This was done in Vinyals at al<sup>1</sup>, and gives better results than feeding identical image features at every time step. Note that the dimension of the word vectors and the image vector will have to be the same in this case. 

Is there an elegant way to do this in Keras such that the system is still end-to-end trainable? Could it be done via changing the concatenation axis in Merge?

Thank you.

[1]Show and Tell: A Neural Image Caption Generator
http://arxiv.org/abs/1411.4555
http://arxiv.org/pdf/1411.4555v2.pdf

**Comment by fchollet** [comment]
A trivial way to do it is by precomputing image vectors and word vectors, then feeding sequences of [image, word, word,... word] into a recurrent setup (such a stacked LSTM).

If you want to be learning the image/word vectors at the same time... You'd use a multi-branch setup, where one branch learns a vector sequences representing a caption (Embedding + LSTM), one branch learns the image representation (VGG net), and the two branches are concatenated at axis=1. 

It would be a quasi-identical setup as the captioning example in the README, except you don't repeat the image vector and you concatenate the two branches at axis=1 instead of axis=2 (or -1).

**Comment by avisingh599** [comment]
Thank you for the response. Related:[#95](https://github.com/fchollet/keras/issues/95)

The problem that I am trying to tackle is not exactly image caption generation, but visual question answering. What I plan to do is along these lines:
Pre-compute image features from VGG net (4096 dimensions), and take some pre-computed word vectors (300 dimensions). I then only have to learn a (linear) mapping from 4096 dimensions to 300 dimensions, and feed the image and word vectors in a sequential manner to an LSTM, which then has a softmax layer on top (I am assuming a fixed set of possible answers, so it becomes a multi-class classification problem from vision and text data).

Some code that I've written from reading the examples and the documentation:

```python
#4096-dimensional input features (pre-computed from VGG Net), linearly mapped to 300 dimensions.
image_model = Sequential()
image_model.add(Dense(300, input_dim=4096, init='uniform', activation='linear'))

#512 hidden units in LSTM layer. 300-dimensional word vectors.
language_model = Sequential()
language_model.add(LSTM(512, return_sequences=True, input_shape=(maxlen, 300))

model = Merge([image_model, language_model], mode='concat', concat_axis=1)
model.add(Dense(NumClasses))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

model.fit(X_train, Y_train, batch_size=16, nb_epoch=10)
```
Does this make sense? Currently it gives me the error:
```
Traceback (most recent call last):
  File "lstm_exp1.py", line 16, in <module>
    model.add(Dense(NumClasses))
AttributeError: 'Merge' object has no attribute 'add'
```
I am using the latest versions of both Theano and Keras. I tried the Merge example in the documentation, and did not receive any error. Please let me know if there are is any obvious mistake in the code.

Thank you.

**Comment by fchollet** [comment]
`Merge` is a layer, not a model. What you want to do is:

```python
model = Sequential()
model.add(Merge([image_model, language_model], mode='concat', concat_axis=1))
```

**Comment by avisingh599** [comment]
Oh, I copied that from the README. After add that line, the error is:
```
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.7.0-py2.7.egg/theano/tensor/basic.py", line 3768, in _make_node_internal
    raise TypeError("Join() can only join tensors with the same "
TypeError: Join() can only join tensors with the same number of dimensions.
```
This probably points to a deeper problem in what I'm doing, I'm trying to find out what it is. Do let me know what you think. On trying concat_axis=2, I get:
```
  File "lstm_exp1.py", line 17, in <module>
    model.add(Dense(NumClasses))
  File "build/bdist.linux-x86_64/egg/keras/layers/containers.py", line 37, in add
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 32, in set_previous
  File "build/bdist.linux-x86_64/egg/keras/layers/core.py", line 297, in output_shape
IndexError: list index out of range
```
P.S. Should I fix that model = Merge() line in the README ?

**Comment by fchollet** [comment]
> P.S. Should I fix that model = Merge() line in the README ?

I fixed it, thanks for catching this.

> On trying concat_axis=2, I get:

Apparently you are trying to concatenate tensors where at least one has less than 3 dims.

> After I add that line, the error is:

Now you just have to make sure the shape of the tensors you are trying to merge matches. You can try outputting (via `predict`) the shape of the output of the different branches, for starters...

**Comment by avisingh599** [comment]
I managed to get running by changing a line in the LSTM model: return_sequences=False

**Comment by bityangke** [comment]
Are the two Sequential model fine-tuned before the Merge layer？ @fchollet @avisingh599
