### ISSUE TITLE
utils.to_categorical should output a matrix even if input is single element

### ISSUE THREAD

**Issue by ceefour** [fchollet/keras#8519]
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [ ] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/fchollet/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] just copy the script here if it is short

```python
print(np_utils.to_categorical([3]))

[ 0.  0.  0.  1.]

print(np_utils.to_categorical([3, 3]))

[[ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]]
```

to_categorical documentation says "Converts a class vector (integers) to binary class **matrix**."

When a single element is provided, it outputs a vector, why this anomaly? It should still output a matrix just as the documentation specified (and it is the intuitive behavior).

**Comment by jbrownlee** [comment]
I believe this is a bug.

Given:

`from keras.utils import to_categorical
print(to_categorical([3]))`

In Keras 2.0.8 the result is a matrix: 

`[[ 0.  0.  0.  1.]]`

In Keras 2.1.1 (and perhaps others), the result is an array:

`[ 0.  0.  0.  1.]`

This undocumented change in behavior breaks a ton of my code.

**Comment by fchollet** [comment]
Yes, it seems that we don't handle the scalar case consistently. It should return a matrix.

@jbrownlee can you provide some examples of code that would break? Why would you call `to_categorical` with a scalar?

**Comment by jbrownlee** [comment]
@fchollet thanks for the confirmation, much appreciated.

I have data prep loops that build up the framing of a text sequence prediction problem (e.g. image captioning, translation, text summarization). The loop crawls across the output sequence taking a portion of input for a given sample and the next word as output, a single output integer. This output is then encoded with a call to to_categorical and added to a list as we build up the whole training dataset.

I can pull the encoding out to the end of the loop, it's all just code, nevertheless, the API behavior change broke "finished" code.

**Comment by ozabluda** [comment]
I think this fixes it:
https://github.com/fchollet/keras/commit/d956d19fccf6de6344c282218f1b027453785fa9

**Comment by fchollet** [comment]
Right, it's fixed.
