### ISSUE TITLE
Support NNVM/TVM

### ISSUE THREAD

**Issue by Nuka-A** [fchollet/keras#8563]
Hi,

I'm using this framework recently, and I'm very happy to be done DL works easily with it.
Thanks for your great work!

I heard that there is a future work to support NNVM/TVM.
And its status is in "work in progress".

http://www.tvmlang.org/2017/10/06/nnvm-compiler-announcement.html

is there any progress about this work now?
there is no source code and no issues about it, so i'm wondering about the current status.

Thanks

**Comment by fchollet** [comment]
On their side, I suppose, there is work in that direction. I don't know about it.

For the time being, it seems that you can use Apple's CoreML as a bridge to export Keras models to NNVM.

**Comment by Nuka-A** [comment]
thanks for your fast reply. i got it.
I will check the progress to the developer of NNVM.

Thanks again and closes this issue now.
