### ISSUE TITLE
LSTM return_sequences = false . Expected output??

### ISSUE THREAD

**Issue by alejandrok** [fchollet/keras#858]
Hi, I understand that when using LSTM layers if I set the return_sequences = false , that layer will output the last vector in the input sequence, being the input sequence a matrix of the form [timestep x input_dim] and if I set it to true, it will output the whole sequence (timestep x input_dim matrix). I've been doing some tests and it seems that when return_sequences = false, the layer actually outputs the whole sequence but as a vector, meaning it outputs a flattened version of the sequence instead of the last vector in the sequence.

Can someone point out if this is ok? Based on the documentation this should not be the output right?

Thanks

**Comment by fchollet** [comment]
Recurrent layers do what the documentation says they do, i.e. when `return_sequences` is `False`, they return the last predicted timestep. 

Why don't you read the source code, if you want to check?

**Comment by LeavesBreathe** [comment]
Thank you I was wondering the same thing, but @fchollet  was right, I should have just read the code.
