### ISSUE TITLE
Connecting one layer with two other layers

### ISSUE THREAD

**Issue by benjaminklein** [fchollet/keras#86]
Hi,

Can one create a layer with this library that is connected to two other layers and not only to one? 

For example - one can apply a conv and then max pooling on an image and call this layer 1 and then apply only a conv on the original image and call this layer 2. Now we can create a fully connected layer that will be connected to layer1 and layer2. Therefore the network is not linear and can be any kind of a directed acyclic graph.

Thank you!

**Comment by fchollet** [comment]
This is something I've been thinking of adding: a way to merge two models (or more) into a single input layer. This is not supported yet, but chances are it will be in the near future.

**Comment by benjaminklein** [comment]
That will be a great feature. Thank you!

**Comment by fchollet** [comment]
Now possible through the use of the Merge layer: http://keras.io/layers/core/#merge
