### ISSUE TITLE
model zoo

### ISSUE THREAD

**Issue by wolet** [fchollet/keras#861]
Hello,

similar to caffe, keras should have model zoo so that people can replicate results of others. does anyone agree on that?

**Comment by alvations** [comment]
There's an example folder, so replicating is quiet easy to follow: https://github.com/fchollet/keras/tree/master/examples

Similar to [lasagna](https://github.com/Lasagne/Lasagne)'s recipe: https://github.com/Lasagne/Recipes

**Comment by EderSantana** [comment]
There is also work in progress to load caffe models into keras.

**Comment by wolet** [comment]
@alvations : model zoo is for trained models not for the recipes/scripts. not everyone has powerful GPUs and it would be good to have model files (like VGGs in caffe).

@EderSantana : it would be nice to have such thing. but what I meant is a platform to share trained models (h5 file and architecture jsons).

**Comment by EderSantana** [comment]
@wolet have your head about https://github.com/sklearn-theano/sklearn-theano they have some good models pre-trained and you don't need GPU to test them. Since they also use theano for backend, all that we need is a Keras wrapper so we can fine tune and test them (Volunteers Needed!!!).

**Comment by willard-yuan** [comment]
There is a [VGG16 model for Keras](https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3).

**Comment by wolet** [comment]
@willard-yuan great! we should have more!

**Comment by zormit** [comment]
This is a duplicate of #703.

**Comment by MartinThoma** [comment]
> There is also work in progress to load caffe models into keras.

@EderSantana Is there an update?
