### ISSUE TITLE
Combining identical inputs of multiple models into one

### ISSUE THREAD

**Issue by vadimstot** [fchollet/keras#8613]
I have large number of models (of different structure) that were built using the same input shape (but not the same InputLayer object).
Is it possible to merge their input into one of the same dimension?
I know I can do 
m = Model(inputs=[m.input for m in models], output=....
But this approach requires duplication the x variable in fit method. I would like to avoid this as the number of models is very large.

Thanks

**Comment by mpariente** [comment]
Are the inputs the same or do they only have the same shape?

**Comment by mpariente** [comment]
So just define one input layer. And this input layer can be the input to any other layer.
Here is an example  :
```
# Common input
input_common = Input((None,10))

# First "branch"
y1 = Dense(10, activation='sigmoid')(input_common)

# Second "branch"
y2 = Dense(10, activation='relu')(input_common) 

# Define and compile model
model = Model(inputs=input_common, outputs=[y1,y2])
model.compile(loss='mse', optimizer='adam')

```



```

**Comment by vadimstot** [comment]
Yes this is probably what I would do. The models are pre trained and I didn't want to change their creation, but it seems there is no other way around it.

**Comment by vadimstot** [comment]
My models were already pre trained and saved to the disk, so I ended up doing the following hack:
Defined a singleton input like that
`class SingletonInputLayer(InputLayer):
     instance = None
    @classmethod
     def from_config(cls, config):
        if SingletonInputLayer.instance:
              return SingletonInputLayer.instance
        else
              SingletonInputLayer.instance = InputLayer.from_config(config)
              return SingletonInputLayer.instance
`
Then I passed it to model_from_json as substitute for InputLayer.

**Comment by abhi4singhal** [comment]
I know this is very late, but anyone looking to do the same thing can do this via:

`
def fuseInputModel(_model,_input):
    _layers = _model.layers
    _m = _input
    for layer in _layers:
        layer.trainable = False
        _m = layer(_m)
    return Model(inputs=_input,outputs=_m)

def averageAllModels(_model_list,_input):
    _outputs = [fuseInputModel(_m,_input).output for _m in _model_list]
    return Model(inputs=_input,outputs=Average()(_outputs),name="ensemble")

ensemble_model = averageAllModels(all_models,common_input)
`

**Comment by TruscaPetre** [comment]
Thank you really much @cyphx !
