### ISSUE TITLE
Cifar10 ResNet error

### ISSUE THREAD

**Issue by mister11** [fchollet/keras#8617]
Keras version 2.1.1
Tensorflow version 1.4.0
Python version 3.6

If I try to run `cifar10_resnet.py` example, I get this error: `TypeError: fit_generator() missing 1 required positional argument: 'steps_per_epoch'`.

If I add this parameter and set it to what it was before it was removed as a part of #8574 , everything works fine.

What is causing this issue?

**Comment by ozabluda** [comment]
See https://github.com/fchollet/keras/pull/8574#issuecomment-347931912
