### ISSUE TITLE
error in cifar10_cnn example

### ISSUE THREAD

**Issue by wolet** [fchollet/keras#862]
Hello,

cifar10_cnn example gets argument error. Convolutional2D constructor does not have input_shape argument.

     $ python cifar10_cnn.py
     X_train shape: (50000, 3, 32, 32) 
     50000 train samples
     10000 test samples
     Traceback (most recent call last):
      File "cifar10_cnn.py", line 49, in <module>
        input_shape=(img_channels, img_rows, img_cols)))
     TypeError: __init__() got an unexpected keyword argument 'input_shape'

**Comment by yueranyuan** [comment]
Your Keras looks old. Input_shape was added to all layers in an earlier commit to master. Try git cloning and 'python setup.py install' the latest

(P.S. Shoutout to LTI)

**Comment by wolet** [comment]
cloning and reinstalling fixed that error. now I get 

     File "build/bdist.linux-x86_64/egg/keras/activations.py", line 20, in relu
     AttributeError: 'module' object has no attribute 'relu'

any ideas?

**Comment by yueranyuan** [comment]
Pip install the latest Theano in the Theano git repo. This instruction was added to the readme but not the setup.py (I'm assuming in hope that this fix will not be necessary when Theano is updated)

**Comment by wolet** [comment]
thanks updating theano has solved my problem!
