### ISSUE TITLE
Masking is not supported for CuDNN RNNs error

### ISSUE THREAD

**Issue by carmelrabinov** [fchollet/keras#8620]
I'm using keras 2.1.1 with python 3.5 and tensorflow-gpu 1.3.0.
I'm training sequential data with this model:

        net_input = Input(shape=(None,features_num), dtype='float32', name='input')
        mask_value = 0.
        mask = Masking(mask_value=mask_value)(net_input)
        BiLstm1 = Bidirectional(CuDNNLSTM(30, return_sequences=True)) (mask) 
        BiLstm2 = Bidirectional(CuDNNLSTM(20, return_sequences=True)) (BiLstm1)
        output = TimeDistributed(Dense(10, activation=None))(BiLstm3)
        model = Model(inputs=net_input, outputs=output)

but getting this error:
     ValueError: Masking is not supported for CuDNN RNNs.

is there a work around?

full error:
  File "/u/train.py", line 209, in <module>
    BiLstm1 = Bidirectional(CuDNNLSTM(30, return_sequences=True)) (mask) 
  File "/u/anaconda3/envs/tf_gpu/lib/python3.5/site-packages/keras/engine/topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "/u/anaconda3/envs/tf_gpu/lib/python3.5/site-packages/keras/layers/wrappers.py", line 290, in call
    y = self.forward_layer.call(inputs, **kwargs)
  File "/u/anaconda3/envs/tf_gpu/lib/python3.5/site-packages/keras/layers/cudnn_recurrent.py", line 60, in call
    raise ValueError('Masking is not supported for CuDNN RNNs.')
ValueError: Masking is not supported for CuDNN RNNs.

Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

**Comment by fchollet** [comment]
> is there a work around?

No, you will have to remove your masking layer. CuDNN RNNs cannot be used with masking for the time being, and likely never will be. It would need to be implemented at the CuDNN level.

Any workaround we could implement on the TF side would be very inefficient (doing per-sample stripping of masked entries and per-sample calls to the CuDNN API).
