### ISSUE TITLE
Capability to parse in json a model with custom activation functions

### ISSUE THREAD

**Issue by mmolero** [fchollet/keras#8636]
First of all, **Awesome project**, 

Does anyone know how we can save a model using a custom activation function.

For example, I'm doing the next:

```
def swish(x):
    return (K.sigmoid(x) * x)

get_custom_objects().update({'swish': Activation(swish )})
```
then we are able to use a custom activation function but when I'm trying to parse a model using this custom function in json (*model.to_json()*) 
I got the following:

```
AttributeError: 'Activation' object has no attribute '__name__'`
```

Any idea to proceed?

Thanks!!

**Comment by fchollet** [comment]
`get_custom_objects().update({'swish': swish})` is the way to go. Activations used as the `activation` argument of a layer should be plain functions, not layers.
