### ISSUE TITLE
MiniBatchProvider between epochs

### ISSUE THREAD

**Issue by felipefariax** [fchollet/keras#864]
Hello!

I didn't find anything in keras that I could choose how the batches are taken.

My problem is: I have some sequences so classify, and I would like to pick a window of X time steps to classify the next point. Today I had to manipulate a database creating another one with my needs, but it happens that I ran out of memory and I had to try hdf5.
Is there another way to do it in keras already implemented?

If there isn't, I think that we could have some kind of MiniBatchProvider object that could be passed into the model.fit and at each epoch_begin we could do something like this:

    try:
        if mini_batch_provider is None:
    	    ins_batch = slice_X(ins, batch_ids)
        else:
    	     ins_batch = mini_batch_provider.get_mini_batch(ins, batch_index)
        except TypeError as err:
            raise Exception('TypeError while preparing batch. \
            If using HDF5 input data, pass shuffle="batch".\n')

Or even put the main loop of the model.fit inside a ```while mini_batch_provider.has_more_mini_batches() ```

What do you think?

**Comment by felipefariax** [comment]
The BatchIterator from nolearn maybe a good idea to have...

https://github.com/dnouri/nolearn/blob/master/nolearn/lasagne/base.py


We could have the BatchIterator not only on model.fit, but also on model.predict as in nolearn has different BatchIterators if the network is training or testing.

**Comment by fchollet** [comment]
You can train your model on custom minibatches by using the methods `model.train_on_batch` and `model.test_on_batch`. You can refer to the documentation for more details.

You can also check out the CIFAR10 Keras example, which using this method to do real time data augmentation.
