### ISSUE TITLE
Multi_gpu in keras not working with callbacks, but works fine if callback is removed

### ISSUE THREAD

**Issue by nbansal90** [fchollet/keras#8649]
_Code:

_with tf.device("/cpu:0"):
        model = resnet_model.Resnet_model.build_model_v1(input_shape, num_class,depth)

model = multi_gpu_model(model, gpus=2)
model.compile(loss='categorical_crossentropy',optimizer=Adam(lr=lr_schedule(0)),metrics=['accuracy'])

#Viewing Model Confuguration
model.summary()
checkpoint = ModelCheckpoint(filepath=filepath, monitor='val_acc',verbose=1,
                                save_best_only=True)

lr_scheduler = LearningRateScheduler(lr_schedule)

lr_reducer = ReduceLROnPlateau(factor=np.sqrt(0.1), cooldown=0,
                                patience=5, min_lr=0.5e-6)

callbacks = [csv_log, checkpoint, lr_scheduler, lr_reducer]

#Adding Data Augmentation Provided by Keras Module
datagen = ImageDataGenerator(featurewise_center=False,samplewise_center=False,featurewise_std_normalization=False,
                                samplewise_std_normalization=False,zca_whitening=False,rotation_range=0,
                                width_shift_range=0.1,height_shift_range=0.1,horizontal_flip=True,vertical_flip=False)

datagen.fit(x_train)
steps_per_epoch = int(np.ceil(x_train.shape[0] / float(batch_size)))
model_info = model.fit_generator(datagen.flow(x_train, y_train, batch_size=batch_size),
                        steps_per_epoch=steps_per_epoch,
                        validation_data=(x_test, y_test),
                        epochs=epochs, verbose=1, workers=4,
                        callbacks=callbacks)__

Error:
Learning rate: 0.001
Epoch 1/100
1562/1563 [============================>.] - ETA: 0s - loss: 2.3464 - acc: 0.4998Epoch 00001: val_acc improved from -inf to 0.56260, saving model to /home/bansa01/resnet_final/saved_models/cifar10_v1_model.001.h5
Traceback (most recent call last):
  File "resnet_cifar_gpu.py", line 184, in <module>
    callbacks=callbacks)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/engine/training.py", line 2154, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/callbacks.py", line 73, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/callbacks.py", line 414, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/engine/topology.py", line 2556, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/models.py", line 108, in save_model
    'config': model.get_config()
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/engine/topology.py", line 2397, in get_config
    return copy.deepcopy(config)
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 223, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 223, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/keras-python3/lib/python3.5/copy.py", line 306, in _reconstruct
    y.__dict__.update(state)
AttributeError: 'NoneType' object has no attribute 'update'

Not Sure how to deal with this.

**Comment by fchollet** [comment]
For the time being, we recommend doing saving through *the original model* and not the multi-gpu model. So you could pass the multi-gpu model a callback that regularly saves *the original model*.

**Comment by nbansal90** [comment]
Thanks @fchollet  for your comment. So what exactly should I change in my code,because fitting the model has to be using multi-gpu model, So where exactly should I call the callbacks?

**Comment by fchollet** [comment]
Basically I am describing a system like this:

```python
original_model = ...
parallel_model = multi_gpu_model(original_model, gpus=n)

class MyCbk(keras.callbacks.Callback):

    def __init__(self, model):
         self.model_to_save = model

    def on_epoch_end(self, epoch, logs=None):
        self.model_to_save.save('model_at_epoch_%d.h5' % epoch)

cbk = MyCbk(original_model)
parallel_model.fit(..., callbacks=[cbk])
```

We will try to make it easier in the future.

**Comment by nbansal90** [comment]
@fchollet Thank You! For the detailed Explanation!
Would be of Great Help!

**Comment by nbansal90** [comment]
@fchollet I Think I understood what you meant to say, But Some how I am receiving similar error, even after making following changes. Error occurs at the start of 2nd Epoch.


model = resnet_model.Resnet_model.build_model_v2(input_shape, num_class,depth)

parallel_model = multi_gpu_model(model, gpus=2)
parallel_model.compile(loss='categorical_crossentropy',optimizer=Adam(lr=lr_schedule(0)),metrics=['accuracy'])

"""Callbacks Used"""

csv_log=CSVLogger(filename, separator=',', append=False)
checkpoint = ModelCheckpoint(filepath=filepath, monitor='val_acc',verbose=1,
                                save_best_only=True)
lr_scheduler = LearningRateScheduler(lr_schedule)
lr_reducer = ReduceLROnPlateau(factor=np.sqrt(0.1), cooldown=0,
                                patience=5, min_lr=0.5e-6)

"""New Callback called used the original model"""
callbacks_l = [csv_log, checkpoint, lr_scheduler, lr_reducer]
cbk = MyCallBack(callbacks_l,model)



"""New Class Defined"""

class MyCallBack(keras.callbacks.Callback):

        def __init__(self, callbacks,model):
                super().__init__()
                callbacks = callbacks
                self.callbacks = [c for c in callbacks]
                self.model = model

        def on_epoch_begin(self,epoch,logs=None):
                for callback in self.callbacks:
                        callback.on_epoch_begin(epoch, logs=logs)

        def on_epoch_end(self,epoch,logs=None):
                for callback in self.callbacks:
                        callback.on_epoch_end(epoch, logs=logs)

        def on_batch_end(self, batch, logs=None):
                for callback in self.callbacks:
                        callback.on_batch_end(batch, logs=logs)

        def on_batch_begin(self, batch, logs=None):
                for callback in self.callbacks:
                        callback.on_batch_begin(batch, logs=logs)

        def on_train_begin(self, logs=None):
                for callback in self.callbacks:
                        callback.set_model(self.model)
                        callback.on_train_begin(logs=logs)

        def on_train_end(self, logs=None):
                for callback in self.callbacks:
                        callback.on_train_end(logs=logs)



"""Getting similar Error"""
Epoch 1/100
1562/1563 [============================>.] - ETA: 0s - loss: 2.3793 - acc: 0.4827Epoch 00001: val_acc improved from -inf to 0.55510, saving model to /home/bansa01/resnet_final/gpu_dir/saved_models/cifar10_v1_model.001.h5
Traceback (most recent call last):
  File "resnet_cifar10.py", line 187, in <module>
    callbacks=[cbk])
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/engine/training.py", line 2187, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/keras-python3/lib/python3.5/site-packages/keras/callbacks.py", line 73, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/bansa01/resnet_final/gpu_dir/resnet_model.py", line 182, in on_epoch_end
    callback.on_epoch_end(epoch, logs=logs)

**Comment by corneel** [comment]
@fchollet That code you provided does not work in 2.0.6 of the product. It does not have a multi_gpu_model function. I decided to implement the callback anyway and just created a second model for the parallel work, and it seems to be working. I would also like to ask if you would update you great [tutorial](https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html) to work with 2.0.6? 

As you might know Apple announced that they will only support Keras up to 2.0.6 and Tensorflow up to 1.2.1 for now. That means there are a lot of people trying to build neural networks with Keras 2.0.6.

**Comment by corneel** [comment]
I have now proven that the CPU version of 2.0.6 also does not save the model as expected. I assume there is suppose to be an implicit save after training?

**Comment by nbansal90** [comment]
@corneel I tried the way Francois had mentioned, but there is a problem while using multiple callbacks; Have you tried with one callback or multiple ? With the code mentioned at this issue [https://github.com/keras-team/keras/issues/8764](url), I am getting the same error. Wondering if you face the same issue.

**Comment by corneel** [comment]
Oh yes, it is just amazing to me that people will let software out that doesn't check whether it actually writes out a file. There are no regression tests in these open source projects. Almost like it is one never-ending hackathon.

This is the message  I sent to my investors that cannot understand why it takes that long to get a neural network working. They don't get that apple only supports Caffe V1 and Keras 2.0.6. I have basically spent two weeks chasing bugs because nobody cares to update their code that used to work with sone ancient piece of code. Anyway - this was my message to them. 

So this morning 4am when the network finally builds (thanks to my laptop’s GPU), I discover that Keras had a bug in their parallel code that would not save the model after it was built. Funny, that would be one thing I would test if I write code but anyway. Here is the confession by Mr. Keras himself François Chollet:
 
fchollet commented 16 days ago
Basically I am describing a system like this:
 
original_model = ...
parallel_model = multi_gpu_model(original_model, gpus=n)
 
class MyCbk(keras.callbacks.Callback):
 
    def __init__(self, model):
         self.model_to_save = model
 
    def on_epoch_end(self, epoch, logs=None):
        self.model_to_save.save('model_at_epoch_%d.h5' % epoch)
 
cbk = MyCbk(original_model)
parallel_model.fit(..., callbacks=[cbk])
We will try to make it easier in the future.
 
So I had to hack that code and as backup decided to start building it on my CPU on my Mac. That was four hours ago and it is only halfway. Then I decide to take one of the checkpoint datasets from the GPU build and convert it so long with coremltools... you know just to see if Apple have their shit together.
 
Wouldn’t you know it, I cannot make this up. This is the bug I get:
 
File "/Users/corneel/tensorflow/lib/python2.7/site-packages/coremltools-0.7-py2.7.egg/coremltools/converters/keras/_topology2.py", line 174, in make_output_layers
    self.model.output_layers]
IndexError: list index out of range
 
Index out of range? That is the things we used to slap the junior programmers about if they did not test for. Oh but it gets better – someone else got the bug  and decided to go read the Apple code. This is what he saw in the module at the place the bug occurred.
 
davidbenari commented 4 days ago
 
so it seems there is an unfinished TODO in the part of code the raises the exception
 
def make_output_layers(self):
"""
Extract the ordering of output layers.
"""
# TODO - finish this
 
Yes Apple, perhaps you should finish your code before you tell the world about it... Anyway, I will get past this like the million other bug I had to fix, we are in the final stretch.

**Comment by ikvision** [comment]
To save the original_model, can I use the predefined ModelCheckpoint and overwrite its model?
`
from keras.callbacks import ModelCheckpoint

original_model = ...
parallel_model = multi_gpu_model(original_model, gpus=n)

cbk      = ModelCheckpoint(output_model_file)
cbk.set_model(original_model) 

parallel_model.fit(..., callbacks=[cbk])
`

**Comment by DNXie** [comment]
@fchollet With all your code, how can I set up the parameters in callback functions.  
`checkpoint = ModelCheckpoint(path, monitor='val_acc', save_best_only=True,  save_weights_only=False, mode='auto', period=1)`

**Comment by ranjeetthakur** [comment]
And how to use  ReduceLROnPlateau since this also doesn't work with multi GPU setup?

**Comment by guiyuliu** [comment]
how to name the model with accuracy and loss ?
not just epoch ?

**Comment by jashshah** [comment]
It's 2019 and TF 2.0 is just around the corner. Are there any significant developments around this?

**Comment by apoorva-slingshot** [comment]
Still having this issue with TF 1.15 and Keras 2.3.1

**Comment by abafna** [comment]
@DNXie , working from what @fchollet proposed, we can extend the ModelCheckpoint class itself. You can then use the other parameters. This is what I use :

```python
from keras.callbacks import ModelCheckpoint

class OrgModelCheckpoint(ModelCheckpoint):

    def __init__(self, model, *args, **kwargs):
        super(OrgModelCheckpoint, self).__init__(*args, **kwargs)
        self.model = model

    def set_model(self, model):
        """Set the model at instantiation."""
        pass

cbk = OrgModelCheckpoint(original_model, path, monitor='val_acc', save_best_only=True, save_weights_only=False, mode='auto', period=1)
parallel_model.fit(..., callbacks=[cbk])
```
