### ISSUE TITLE
Running on keras models on GPU (TF backend)

### ISSUE THREAD

**Issue by JoaoLages** [fchollet/keras#8658]
Hi there!

What is the difference of using keras' `multi_gpu_model` or just changing the visible CUDA_VISIBLE_DEVICES? Don't they accomplish the same?

**Comment by szymko1995** [comment]
You specify CUDA_VISIBLE_DEVICES just to let TF see which gpus it should use (for example 2 gpus of 4 avaliable). multi_gpu_model is used to replicate and divide model and input batches into many gpus.

**Comment by JoaoLages** [comment]
So, what is the difference in here? By specifying the GPUs to use, won't tensorflow automatically divide computation between them?

**Comment by tRosenflanz** [comment]
No it won't

**Comment by JoaoLages** [comment]
What do you mean with that? I see my specified GPUs being used and training is way faster

**Comment by tRosenflanz** [comment]
By default TF only uses the GPU with the lowest id number. [You have to manually splice your batches across several GPUs if you want to use multiple GPUs](https://www.tensorflow.org/tutorials/using_gpu)

**Comment by JoaoLages** [comment]
Ok then, understood :).
