### ISSUE TITLE
with latest Theano updates, LSTM faster but GRU much slower

### ISSUE THREAD

**Issue by transcranial** [fchollet/keras#866]
With the latest updates to scan in Theano, anybody else experiencing dramatically different training times? In particular, LSTM is faster, but GRU/JZS1-3 is much, much slower:

A relative comparison on a test network, exchanging the recurrent layer:

```
LSTM: 15s
GRU: 94s
JZS1: 63s
JZS2: 83s
JZS3: 91s
```

For this same network, LSTM pre Theano scan changes was ~24s.

Anybody have some insight into this?

**Comment by nouiz** [comment]
If you can tell me which commit of Theano was faster on GRU and the current
commit that is slower and the way to reproduce it, we can investigate
relatively fast.

**Comment by transcranial** [comment]
@nouiz  Theano commit https://github.com/Theano/Theano/commit/f0bd940e85e42a9844a0e91e24b30badb5f9902a

GRU before ~14s / epoch on my test network vs ~90s / epoch after. Again, LSTM speed is improved, though. This is on GPU, but it seems on CPU GRU is also now also slower than LSTM, but not to the same degree.

**Comment by transcranial** [comment]
After tinkering around a bit, it appears the source of the slowdown with the new theano changes is the `r * h_mask_tm1` part of `hh_t = self.activation(xh_t + T.dot(r * h_mask_tm1, u_h))` where `r = self.inner_activation(xr_t + T.dot(h_mask_tm1, u_r))`. LSTM doesn't have a similar expression so it is unaffected.

**Comment by nouiz** [comment]
How can I recreate it? I never used keras, so maybe just point me to there
the example/code is.


Also, which version of Theano was faster? Do you have a commit number? An
proximate date of the checkout?

When was your last update of Theano that caused this slow down? We got one
such case in Theano master for ~2 days, but it was fixed around 2 weeks ago.

**Comment by brainwater** [comment]
The first bad commit was 5dcd39997736cdb04fb55de35f6917977791e8e6 in theano, though a couple commits before that were taking about 50%-100% longer for GRU than it had been.

**Comment by transcranial** [comment]
https://github.com/Theano/Theano/commit/f0bd940e85e42a9844a0e91e24b30badb5f9902a:
my test GRU, 85 s / epoch

https://github.com/Theano/Theano/commit/6d21a3f84e7a2826d32ef2d649e0eeabf2e8384d:
same GRU, 14 s / epoch

**Comment by nouiz** [comment]
I need to be able to run this code. I'm currently looking how to do this. If you know how, tell me.

**Comment by nouiz** [comment]
I changed examples/imdb_lstm.py to use Keras GRU layers instead of LSTM and I'm able to reproduce the problem.

**Comment by brainwater** [comment]
I've verified that https://github.com/Theano/Theano/commit/6d21a3f84e7a2826d32ef2d649e0eeabf2e8384d is also good. I suspect the performance issue was fixed but then re-introduced, or perhaps this commit was not a descendant of the commit that introduced the performance regression.

**Comment by nouiz** [comment]
I have a PR that fix this:
https://github.com/Theano/Theano/pull/3548

thanks for the report and the help!

**Comment by fchollet** [comment]
Great work on Theano @nouiz !

**Comment by transcranial** [comment]
@nouiz wow awesome, thanks!

**Comment by nouiz** [comment]
We merged the PR yesterday. So update Theano if you see this issue.
