### ISSUE TITLE
fit_generator has thread leak?

### ISSUE THREAD

**Issue by BrashEndeavours** [fchollet/keras#8665]
**Issue:**
I am experiencing an issue with becoming overrun with threads produced when I run the below code using fit_generator functionality. 

Attached is a screenshot displaying the # of threads over time at 0.5s intervals.
![screenshot from 2017-12-02 16-36-27](https://user-images.githubusercontent.com/8198523/33519940-fd31751c-d77e-11e7-8be4-8dfad1b442c7.png)

I know my code invokes the `OrderedEnqueuer` functionality, using threads and not processes. 
Placing a debug print in the `__init__()` fucntion shows that it is created every epoch.

**Questions:**
1. Can anyone else confirm this issue? 
To watch the threads I used: `watch -n 0.5 ps -elfT | grep scriptname` 
2. Is the creation of the OrderedEnqueuer on every epoch normal behaviour?

**Versions:**
Keras (2.1.2, installed from fchollet/keras, 2 Dec 2017)
Tensorflow (1.4.0)

**Code:**
```from keras.layers import Dense
from keras.layers import Activation
from keras.layers import Flatten
from keras.layers import LocallyConnected1D
from keras.layers import Dropout
from keras.models import Sequential
import time
from keras.utils import Sequence
import numpy as np

class SequenceGen(Sequence):
    def __init__(self, batch_size):
        self.batch_size = batch_size

    def __len__(self):
        return 10

    def __getitem__(self, idx):
        batch_x = np.zeros((self.batch_size, 100, 2))
        batch_y = np.zeros((self.batch_size, 1))
        time.sleep(0.1)
        return batch_x, batch_y

    def next(self):
        while True:
            for idx in range(len(self)):
                return self.__getitem__(idx)

data_generator = SequenceGen(batch_size=20000)
val_generator = SequenceGen(batch_size=20000)

model = Sequential()

model.add(LocallyConnected1D(
                filters=100,
                kernel_size=1,
                input_shape=(100, 2)))
model.add(Activation('linear'))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(units=25))
model.add(Dense(units=1))
model.add(Activation('linear'))

model.compile(optimizer='rmsprop',loss='mae')
model.fit_generator(
                generator=data_generator, 
                steps_per_epoch=None, # Gets figured out from len(generator)
                epochs=6000, 
                verbose=1, 
                callbacks=[],
                validation_data=val_generator, 
                validation_steps=None, # Gets figured out from len(generator) 
                class_weight=None, 
                max_queue_size=10, 
                workers=10,
                use_multiprocessing=False, 
                shuffle=False, 
                initial_epoch=0)
```

**Comment by fchollet** [comment]
@Dref360 what do you think -- should be solved by using a context scope?

**Comment by Dref360** [comment]
Yeah, probably the same issue as https://github.com/fchollet/keras/issues/8622#issuecomment-348710044

I proposed a change, I will try to see if it works for threads as well.

Indeed an Enqueuer is created at each epoch.

**Comment by Dref360** [comment]
Which version of Python are you using @BrashEndeavours ? Not able to reproduce on my end.  (Python 3.5, Ubuntu 16.04)

**Comment by BrashEndeavours** [comment]
Python 2.7.14
Ubuntu 17.10

Will keep you posted on testing

**Comment by BrashEndeavours** [comment]
Solid work, @Dref360 !
Works with my setup, recommend merge if no conflicts.

![screenshot from 2017-12-02 18-55-33](https://user-images.githubusercontent.com/8198523/33520938-69dca98a-d792-11e7-9260-01d31af38046.png)

Specifically, my use case that discovered this issue was exploring hyperparams with [hyperas](https://github.com/maxpumperla/hyperas). Having my system lockup after 2-3 hours of exploring different scenarios was a non-starter. Thanks again, great work!
