### ISSUE TITLE
__init__() got an unexpected keyword argument 'node'

### ISSUE THREAD

**Issue by Ham72** [fchollet/keras#8670]
I wanted to save the best weights using checkpoint method of Keras, and use those best wights for model evaluation.

`filepath="weights.best.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
callbacks_checkpt = [checkpoint]`

Receiving following error
TypeError                                 Traceback (most recent call last)
<ipython-input-15-fe9aba75971b> in <module>()
     75 
     76 filepath="weights.best.hdf5"
---> 77 checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=0, save_best_only=True,node='max')
     78 callbacks_checkpt = [checkpoint]
     79 

TypeError: __init__() got an unexpected keyword argument 'node'

IS there another way of storing and loading "Best weights"

**Comment by tRosenflanz** [comment]
This is just a typo in your code it seems. You have node='max' instead of mode='max' in line 77

**Comment by fchollet** [comment]
Correct, this class accepts a `mode` argument but no `node` argument, as the error message describes.

**Comment by Ham72** [comment]
Copy that!
