### ISSUE TITLE
Feature Suggestion: Shared memory for Sequence generator sub-processes

### ISSUE THREAD

**Issue by tRosenflanz** [fchollet/keras#8674]
Hello,

This feature might be too niche but I thought it could be useful for developers like myself who are less accustomed with multiprocessing:
When working with large objects that can not be saved to disk efficiently (in my case pandas dataframe with lists of lists inside the columns) memory usage of multiple workers that operate on this object can become prohibiting and bottleneck the training. [There are ways to enable memory sharing between sub processes ](https://stackoverflow.com/a/14135569), however, since Sequence generator hides away multiprocessing functionality, user will have to write their own multiprocessing logic to enable shared memory. 
I imagine Sequence utility could have an optional method that would accept a list of objects and will enable them as shared before initializing the pool of processes that will cut down on the RAM requirements of workers
Please let me know your thoughts and thank you for continuous support to an awesome library!

**Comment by Dref360** [comment]
I've never tried it, but couldn't you just initialize your Sequence with some shared values?

like : 
```python
class MySequence(Sequence):
      def __init__(self,my_shared_array):
            self.my_shared_array = my_shared_array

     def __getitem__(self,idx):
           return self.my_shared_array[idx]
```

Where `my_shared_array` is a `mutliprocessing.Array` ?
https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Array

**Comment by tRosenflanz** [comment]
I will test, will be good if it actually works. For some reason I just assumed that you need to call multiprocessing.Array within the same method as defining the pool. In retrospect that makes 0 sense

**Comment by Dref360** [comment]
I already used a Manager inside a Sequence to share a list, I guess you can do the same? Of course, a Manager is not using shared memory, but it would cut the amount of memory.

**Comment by tRosenflanz** [comment]
This is quickly turning into an implementation question than actual feature suggestion so I will close the issue down. 

multiprocessing.Array only support simple structures - that's not fit for any kind of useful generator. I will investigate custom ctypes and the Manager work around

**Comment by Dref360** [comment]
You can hit me up on Slack if you got any question, same username
