### ISSUE TITLE
Using custom loss function with model_from_json

### ISSUE THREAD

**Issue by jpeg729** [fchollet/keras#868]
It doesn't work.
```
Traceback (most recent call last):
  File "myFile.py", line 100, in <module>
    model = model_from_json(open('savefile.json').read())
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 116, in model_from_json
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 142, in model_from_config
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 346, in compile
  File "build/bdist.linux-x86_64/egg/keras/objectives.py", line 64, in get
  File "build/bdist.linux-x86_64/egg/keras/utils/generic_utils.py", line 12, in get_from_module
Exception: Invalid objective: custom_loss_function
```

It is obviously trying to load the loss function from the relevant keras module, and not finding it.

How about adding some parameters to model.model_from_json? Something like `model.model_from_json("savefile.json", loss=my_custom_loss_function)` would be great.

More generally though, maybe we should add the possibility of giving a dictionary of named functions for all the custom functions the model might use: activation, loss, optimizer, ...

**Comment by fchollet** [comment]
> More generally though, maybe we should add the possibility of giving a dictionary of named functions for all the custom functions the model might use: activation, loss, optimizer, ...

Yes, that's a pertinent idea. We already have such support for custom layers. Let's see if we can extend it the custom loss functions and optimizers in the simplest possible way. Is this something you would like to take on?

**Comment by jpeg729** [comment]
Looking at the code that manages the custom layers...
https://github.com/fchollet/keras/blob/master/keras/utils/layer_utils.py#L130
```python
def get_layer(identifier, kwargs=None, custom_layers={}):
    # Insert custom layers into globals so they can be accessed by `get_from_module`.
    for cls_key in custom_layers:
        globals()[cls_key] = custom_layers[cls_key]
    return get_from_module(identifier, globals(), 'layer', instantiate=True, kwargs=kwargs)
```

It just adds the whole dictionary into the global scope.
That's kind of cheating, if you don't mind me saying so, but it is neat and easy.

I *think* that adding whatever I want to `custom_layers` when I call `model_from_json` would cover most cases, exceptions being custom containers and custom functions given to containers.

My suggestion would be to rename `custom_layers` to `custom_elements`, and move the code that adds stuff to the global scope to the beginning of [`container_from_config`](https://github.com/fchollet/keras/blob/master/keras/utils/layer_utils.py#L20)

How does that sound?

**Comment by fchollet** [comment]
> How does that sound?

Sounds great, it's the simplest thing we can do. Not a big fan of "custom_elements" as an API, maybe "custom_objects" would be better?

**Comment by tzachar** [comment]
I second that request. Having support for custom loss functions would be gr8.

**Comment by jpeg729** [comment]
It is a pleasure when contributing is so easy.
