### ISSUE TITLE
mnist_irnn.py example doesn't work

### ISSUE THREAD

**Issue by kjancsi** [fchollet/keras#874]
Hello,
when trying to run the mnist_irnn.py example, I get an error about 'relu' like this: 
File "/Users/vetek/Projects/KerasProjects/keras/keras/activations.py", line 20, in relu
    return T.nnet.relu(x)
AttributeError: 'module' object has no attribute 'relu'
Cheers, kj

**Comment by EderSantana** [comment]
you have to update your Theano to the latest version

**Comment by kjancsi** [comment]
Thanks.
