### ISSUE TITLE
Questions about Graph Parallelization in Theano

### ISSUE THREAD

**Issue by felipefariax** [fchollet/keras#875]
Hello!

I am really liking keras!
I am using it to do my masters on EEG classification.

I don't know exactly how Theano does the parallelizations under the hood.

I am starting with the Graph model and I would like to know if I am understanding it right.

In this code:

```
# Graph to run 2 independent models in parallel
graph = Graph()
graph.add_input(name='input', input_shape=(32,))

# Model 1
graph.add_node(Dense(16), name='dense1_1', input='input')
graph.add_node(Dense(4), name='dense1_2', input='dense1_1')
graph.add_output(name='output1', input='dense1_2')

# Model 2
graph.add_node(Dense(16), name='dense2_1', input='input')
graph.add_node(Dense(4), name='dense2_2', input='dense2_1')
graph.add_output(name='output2', input='dense2_2')

graph.compile('rmsprop', {'output1':'mse', 'output2':'mse'})

history = graph.fit({'input':X_train, 'output1':y_train, 'output2':y_train}, nb_epoch=10) #history (dict with keys for 'output1' and 'output2')

predictions = graph.predict({'input':X_test, 'input2':X2_test}) #predictions (dict with keys for 'output1' and 'output2')
```

I have some questions:
1 - Is it equivalent to train 2 Sequential() models with Dense(16) -> Dense(4) with different init weights, sharing the same batches_ids?

2 - How this graph will run in parallel? Each 'branch' is calculated in parallel, for example, the 'dense1_1' and 'dense1_2' will be calculated at the same time? And if I change the 'dense2_1' from 16 to 30, will change something on the parallelization?

3 - Either this Graph running in CPU or GPU, it will be faster than run 2 Sequential() models separately? 

And if I add a 3rd model like

```
# Model 3
graph.add_node(Dense(16), name='dense3_1', input='input')
graph.add_node(Dense(20), name='dense3_2', input='dense3_1')
graph.add_node(Dense(4), name='dense3_3', input='dense3_2')
graph.add_output(name='output3', input='dense3_3')
```

4 - How the parallelization would occur? Models 1 and 2 will reach the output layer before the Model 3, will Models 1 and 2 wait for Model 3 reach the output layer, backpropagate layer 'dense3_3' and finally Models 1, 2 and 3 starts to backpropagate in parallel?

OT:
5 - Is the issues the right place to do this kind of questions?

Thank you!

**Comment by felipefariax** [comment]
I've just figured out the keras user group, sorry for the wrong place!

**Comment by EderSantana** [comment]
Think that using a single Graph will be a little bit faster since you are moving the batches to the GPU only once. With two separate compiled Sequential models you have to move that data to the GPU twice. But the only way to have a final word is running experiments :/ 

Could you change your question to something like `Questions about Graph Parallelization in Theano`? Maybe a Theano dev finds it interesting and comes over to give a more accurate answer.

**Comment by felipefariax** [comment]
Thank you, Eder!

Changed the title as you suggested.

**Comment by nouiz** [comment]
1) I think one model will be faster. This could remove copy (depending how handle dataset, I'm a Theano dev) and it will also remove some overhead. For small model size as given in the example, this could make a difference
2) On the CPU, we won't run in parallel each branch. Theano won't run in parallel multiple node, but do some parallelism inside each computation node. Be sure to link to a parallel blas. On the GPU, this is in the pipeline after multi-gpu.
3) I think in all case, a single model will be faster. They current size are so small the I'm pretty sure the CPU will be faster then the GPU.

4) I described the parallelism above. For the grad, it depend how keras implement the multiple output. But I think it will be equivalent as training each model separatly.
