### ISSUE TITLE
Difference between Conv2DTranspose and Deconvolution2D ?

### ISSUE THREAD

**Issue by ybdesire** [fchollet/keras#8765]
The info of Deconvolution2D still cannot be found at keras doc.
Is there any example for `Conv2DTranspose` and `Deconvolution2D`?
And what is the difference between `Conv2DTranspose` and `Deconvolution2D`?

**Comment by fchollet** [comment]
They are the same layer. "deconvolution" is a (somewhat misleading) name sometimes used in deep learning to refer to transposed convolution. It does not, in fact, refer to what is called "deconvolution" in signal processing.

**Comment by ybdesire** [comment]
Thanks @fchollet for the help. BTW. Yny example for keras de-convolution network?
