### ISSUE TITLE
can not use rule/lrelu/prelu; raise a error like : 'module' object has no attribute 'relu'

### ISSUE THREAD

**Issue by meanmee** [fchollet/keras#879]

**Comment by meanmee** [comment]
also i want to know if CNN in keras can haddle a 4-ways image(RGB NIR)

**Comment by dbonadiman** [comment]
You need to update theano to their github version not the pip one for the relu problem.

**Comment by meanmee** [comment]
My theano's version is 0.7。the latest version。

**Comment by EderSantana** [comment]
you gotta use the bleeding edge from their repo. Try this for example:

`pip install git+https://github.com/Theano/Theano.git@15c90dd3#egg=Theano==0.8.git`
