### ISSUE TITLE
Error reading hdf5 dataset

### ISSUE THREAD

**Issue by trungnt13** [fchollet/keras#887]
When ever I used **hdf5** dataset for method **fit** this error will come up:
> Traceback (most recent call last):
>  File "tmp/tmp1.py", line 37, in <module> m.fit(f['X'], f['y1'], shuffle=False, nb_epoch=1)
>  File "/Users/trungnt13/libs/keras/keras/models.py", line 490, in fit shuffle=shuffle, metrics=metrics)
>  File "/Users/trungnt13/libs/keras/keras/models.py", line 205, in _fit If using HDF5 input data, pass shuffle="batch".\n')
> Exception: TypeError while preparing batch.                         If using HDF5 input data, pass shuffle="batch".

It is because of this code:
```python
def slice_X(X, start=None, stop=None):
    if type(X) == list:
        if hasattr(start, '__len__'):
            return [x[start] for x in X]
        else:
            return [x[start:stop] for x in X]
    else:
        if hasattr(start, '__len__'):
            return X[start]
        else:
            return X[start:stop]
```
The **start** value as indices is a numpy array, and hdf5 dataset (from h5py) does not support indices as numpy array, hence, the indices should be converted to list.

**Comment by fchollet** [comment]
Would you like to submit a pull request?

**Comment by EderSantana** [comment]
Fixed here https://github.com/fchollet/keras/pull/889
