### ISSUE TITLE
How to get the output of Conv layer and FC layer?

### ISSUE THREAD

**Issue by wepe** [fchollet/keras#89]
Hi, fchollet

I just spend several hours reading the documentation,  looking  through the example **cifar10_cnn.py**, and I find it really easy to use keras.   But as shown in the title, I am confused by these two question:

- how to get the output of the convolution layer? I want to visualize the feature map after each convolution layer. Although it is not so important, I need this when writing  paper.  Any other methods of this framework?

-   I want to use CNN  as feature extractor, so the output of the fully connected layer should be saved. It seems that keras do not support?

Thanks!

**Comment by pranv** [comment]
Hey,  I think I can answer your questions. 

1. In order to visualize the feature maps,  just use the get_weights method of each layer and plot it using matplotlib. I have a working implementation of the same, and hope I'll be able to generalize it soon and create a PR. 

2. For this, the best method that works for me is to create 2 models.  Train the 1st model with your labels.  The 2nd model is identical to the 1st except,  it does not contain the last (or all fully connected) layer (don't forget to flatten). Using get_weights method above, get the weights of the 1st model and using set_weights assign it to the 2nd model. Then use predict_proba to get the feature vectors. 

Hope it helps.

**Comment by fchollet** [comment]
As pointed out by pranv, all this is possible : ) 
To retrieve the output of any layer, you can also check out the answers here: https://github.com/fchollet/keras/issues/41

**Comment by lemuriandezapada** [comment]
Less headache for me was to just "deepcopy" the model and then just .pop() the last few layers

**Comment by wepe** [comment]
Thanks! 
I try the method ｀save_weights｀after training the model:
```
model.save_weights("./model.hdf5")
```
And then create a  new model of same architecture, init with  the saved weights,  and use it to predict the test_data:

```
model_load = create_model()
model_load.load_weights('./model.hdf5')
test_label = model_load.predict_classes(test_data)
```
But it shows error:
```
test_label = model_load.predict_classes(test_data)
 File "build/bdist.linux-x86_64/egg/keras/models.py", line 174, in predict_classes
 File "build/bdist.linux-x86_64/egg/keras/models.py", line 160, in predict_proba
AttributeError: 'Sequential' object has no attribute '_predict'
```

**Comment by lemuriandezapada** [comment]
did you also recompile the model?

**Comment by loyeamen** [comment]
a

**Comment by lemuriandezapada** [comment]
I would be interested I've been fucking around with it for 5 hours with no luck

**Comment by loyeamen** [comment]
Check the code i posted here. It works well but I would change the design if i had time ...

**Comment by alyato** [comment]
hi @wepe ,I use the graph model.
like this,

> model = graph()
  model.add_input(name='input0',input_shape=())
  model.add_node(Convolution2D(),name='c1',input='input0')
.......

And i want to see the output of the `c1`,Then 

> 
getFeatureMap = theano.function(model.inputs['input0'].input,model.nodes['c1'].get_output(train=False),
allow_input_downcast=True)

But it show me that
`TypeError: list indices must be integers, not str`

Do you give me some advices? Thanks.

**Comment by alyato** [comment]
hi @pranv  ,I use the graph model.
like this,

> model = graph()
  model.add_input(name='input0',input_shape=())
  model.add_node(Convolution2D(),name='c1',input='input0')
.......

And i want to see the output of the `c1`,Then 

> 
getFeatureMap = theano.function(model.inputs['input0'].input,model.nodes['c1'].get_output(train=False),
allow_input_downcast=True)

But it show me that
`TypeError: list indices must be integers, not str`

Do you give me some advices? Thanks.

**Comment by philipperemy** [comment]
More generally you can visualise the output/activations of every layer of your model. I wrote an example with MNIST to show how here:

https://github.com/philipperemy/keras-visualize-activations

So far it's the less painful I've seen.
