### ISSUE TITLE
Is there a way to split an output according to the number of samples?

### ISSUE THREAD

**Issue by benjaminklein** [fchollet/keras#894]
Let say that we have an output of a specific layer of shape (2n x c x h x w) where 2n is the number of samples. Is there a way to split it into two outputs: (n x c x h x w) and (n x c x h x w)?

**Comment by EderSantana** [comment]
You can probably try something like that with the incoming `Lambda` layer. But I'd rather suggest you to use `Graph` and have two different inputs and make sure that shared layers have shared weights. The desired will have that 2n batch size and you will have to stack everything again in the end but that is too hacky to be good.

**Comment by benjaminklein** [comment]
I think that there was a discussion here regarding sharing weights. Using a callback in order to achieve share weights was reported as time consuming (with a large factor)... I hoped to solve this using the proposed solution...

**Comment by EderSantana** [comment]
I think you can do that without callbacks. Example
```python
layer1 = Dense(4, input_dim=5)
layer1_copy = copy(layer) # not sure if copy or deepcopy
layer1_copy.params = []  # avoid Theano complaining "we already got these guys grad"

graph = Graph()
graph.add_input('inp1')
graph.add_input('inp2')
graph.add_node(layer1_copy, input='inp1', name='layer1_1') # These two have shared
graph.add_node(layer1_copy, input='inp1', name='layer1_2') # parameters and diff. inputs
...
```

**Comment by sergeyf** [comment]
Francois also addressed this in #783, but his solution was a bit different, and does not use copy. Are they identical @EderSantana ?

**Comment by EderSantana** [comment]
@sergeyf oh yeah, if you have control over the parameters you can just share them the way François did.
```python
layer1.W = layer2.W
layer1.b = layer2.b
```

but I believe you will have to 
```python
layer1.params = []
```

instead.

**Comment by sergeyf** [comment]
OK, let me mess around a bit and post what I discover. Thanks!

**Comment by sergeyf** [comment]
@EderSantana The following compiled with no issues, but after training for a while, the actual weights in the 3 dense layers had diverged. Did I misunderstand what the sharing means? The goal would be to ensure they are the same throughout the training.

```
dense_dim_1 = 10
dense_dim_2 = 1

model = Graph()
model.add_input(name='x1',input_shape=(d,))
model.add_input(name='x2',input_shape=(d,))
model.add_input(name='x3',input_shape=(d,))

D11 = Dense(dense_dim_1, activation='relu')
D12 = copy.deepcopy(D11)
D12.params = []
D13 = copy.deepcopy(D11)
D13.params = []

model.add_node(D11,name='D11', input='x1')
model.add_node(D12,name='D12', input='x2')
model.add_node(D13,name='D13', input='x3')

model.add_node(Dense(dense_dim_2, activation='relu'),
               name='dense_merge', merge_mode="concat", 
               inputs=['D11','D12','D13'])

model.add_output(name='output', input="dense_merge")

rmsprop = RMSprop(lr=0.001)
model.compile(optimizer=rmsprop, loss={"output": 'mse'})

data = {'x1':X1, 'x2':X2, 'x3':X3, 'output':y}
model.fit(data)
```

**Comment by EderSantana** [comment]
nice @sergeyf!!! I believe that is it.
I also think that `model.nodes['D12'].W = model.nodes['D11'].W` is not necessary because the deepcopy makes sure they are already equal right? Deepcopy is a pure python thing. So they just link to the same theano shared variable, which on its hand, points to a position on the GPU.

But let me know if I'm wrong

**Comment by sergeyf** [comment]
I tried to do just deepcopy, but it didn't do what you're suggesting. There were separate weights for each dense layer, and they had diverged after training. Not sure why... I also tried using copy.copy as well as copy.deepcopy, and neither worked.

**Comment by EderSantana** [comment]
@sergeyf good to know. Tkx!!!

**Comment by sergeyf** [comment]
Happy to help.

**Comment by schnpwr** [comment]
I tried on similar lines, but I am getting an error saying that Graph model has no attribute 'nodes'. Could please clarify on this?
