### ISSUE TITLE
Best practices question: decreasing learning rates between epochs

### ISSUE THREAD

**Issue by sergeyf** [fchollet/keras#898]
Howdy,

In published papers I often see that the learning rates are decreased after some hundreds of epochs when learning stalls. What is the best way to do this in Keras? Thus far, I have been recompiling, but (not knowing if there is a better way), that seems foolish.

An example:

First, I build some model and train it.

```
model = Sequential()
# insert model here
optimizer = adagrad(lr=0.01)
model.compile(optimizer=optimizer)
model.fit(X,y,nb_epoch=50)
```

UPDATE -- the following works without having to recompile

```
model.optimizer.lr.assign(0.01)
model(X,y,nb_epoch=50)
```

Thank you to @EderSantana for the quick reply.

**Comment by EderSantana** [comment]
@sergeyf check the solution in this https://github.com/fchollet/keras/issues/888
Please leave this issue open, even if it solves the problem for you. This is the second time we get this question, which means we need a better documentation. Since I'm already working on something else, would anybody else volunteer to write the documentation? We should close this after somebody writes the docs.

**Comment by sergeyf** [comment]
Thank you very much! I will leave this open.

**Comment by jiumem** [comment]
This code may be worked.
```python
class LrReducer(Callback):
    def __init__(self, patience=0, reduce_rate=0.5, reduce_nb=10, verbose=1):
        super(Callback, self).__init__()
        self.patience = patience
        self.wait = 0
        self.best_score = -1.
        self.reduce_rate = reduce_rate
        self.current_reduce_nb = 0
        self.reduce_nb = reduce_nb
        self.verbose = verbose

    def on_epoch_end(self, epoch, logs={}):
        current_score = logs.get('val_acc')
        if current_score > self.best_score:
            self.best_score = current_score
            self.wait = 0
            if self.verbose > 0:
                print('---current best val accuracy: %.3f' % current_score)
        else:
            if self.wait >= self.patience:
                self.current_reduce_nb += 1
                if self.current_reduce_nb <= 10:
                    lr = self.model.optimizer.lr.get_value()
                    self.model.optimizer.lr.set_value(lr*self.reduce_rate)
                else:
                    if self.verbose > 0:
                        print("Epoch %d: early stopping" % (epoch))
                    self.model.stop_training = True
            self.wait += 1
```

**Comment by sergeyf** [comment]
Thanks @jiumem! This might be a good pull request to Keras?

**Comment by LeavesBreathe** [comment]
@sergeyf I just saw this thread, and I'd thought I'd throw in my own function I made to address this. I always use nb_epoch =1 because I'm interested in generating text:

	def set_learning_rate(hist, learning_rate = 0, activate_halving_learning_rate = False, new_loss =0, past_loss = 0, counter = 0, save_model_dir=''):
		if activate_halving_learning_rate and (learning_rate>=0.0001):
		    if counter == 0:
		        new_loss = hist.history['loss'][0]
		        if new_loss>=(past_loss): #you want at least a 0.5% loss decrease compared to the previous iteration
		            learning_rate = float(learning_rate)/float(2)
		            print 'you readjusted the learning rate to', learning_rate
		            with open('models/'+save_model_dir+'/'+'history_report.txt', 'a+') as history_file:
		                history_file.write('For next Iteration, Learning Rate has been reduced to '+str(learning_rate)+'\n\n')
	    	            with open('history_reports/'+save_model_dir+'_'+'history_report.txt', 'a+') as history_file:
		                history_file.write('For next Iteration, Learning Rate has been reduced to '+str(learning_rate)+'\n\n')
		        	
		        past_loss = new_loss
	        return (learning_rate, new_loss, past_loss)

**Comment by sergeyf** [comment]
Awesome, thanks!

**Comment by Rusianka** [comment]
I have a problem using the solution like
```
model.optimizer.lr.set_value(0.01)
model(X,y,nb_epoch=50)

```
with tensorflow backend.
Can't do set_value and get_value as it was discussed here and in another thread.

```
return model_systole.optimizer.lr.get_value()
AttributeError: 'Tensor' object has no attribute 'get_value'
```

Any suggestions please?

**Comment by entron** [comment]
@Rusianka  I just found that one can do this got get and set value:

```
import keras.backend as K
sgd = SGD(lr=0.1, decay=0, momentum=0.9, nesterov=True)
K.set_value(sgd.lr, 0.5* K.get_value(sgd.lr))
```

**Comment by ShuaiW** [comment]
@entron when does the .set_value() happen? after every epoch?

**Comment by entron** [comment]
@ShuaiW you can put the line `K.set_value(sgd.lr, 0.5 * K.get_value(sgd.lr))` inside the epoch loop to set lr at each epoch.

**Comment by ShuaiW** [comment]
@entron thanks for your response. 

my model doesn't have a epoch; instead it's like this:

`model.fit(imgs_train, imgs_mask_train, batch_size=64, nb_epoch=N_EPOCH, verbose=1, shuffle=True,
              callbacks=[model_checkpoint])`

Anyway to fit in?

**Comment by entron** [comment]
Maybe you can set N_EPOCH=1 and loop outside.

**Comment by mewanthoneycomb** [comment]
So I had problems with the `model.fit_generator` function, so I decided to use `model.fit` instead and put it inside a for loop like so:

`for x, y in generate_arrays_from_file():
    x = model.fit(x, y, batch_size=16, nb_epoch=1, verbose=1)`

Here are my questions:

1) I am using Adam for my optimizer, and I saw on another thread that it is impossible to directly get the **current** learning rate. You have to calculate it yourself indirectly. 
[http://stackoverflow.com/questions/37091751/keras-learning-rate-not-changing-despite-decay-in-sgd](url)
Since `nb_epoch` is only 1 in the above function, and `model.fit` is inside a loop, is the learning rate guaranteed to decrease (that's my understanding of how Adam works) or do I have to write a separate function to manually decrease the learning rate myself?

2) My loss initially decreases quite rapidly, but then appears to fluctuate and stop decreasing even after several days of training. This is true both when I train on single images and multi-channel images. Since the loss is fluctuating after every call of `model.fit`, will that screw up Adam's calculations since it relies on the number of iterations and previous losses, or is all of this taken care of by Theano?

I am unfamiliar with Theano, and I do not have time at this point to learn about it so any information you can provide on both these questions is much appreciated.

Thanks.

**Comment by ishank26** [comment]
@sergeyf @ShuaiW  A more simpler solution for decay after specified epochs.
``` python
class decay_lr(Callback):
    ''' 
        n_epochs = no. of epochs after decay should happen.
        decay = decay value
    '''  
    def __init__(self, n_epoch, decay):
        super(decay_lr, self).__init__()
        self.n_epoch=n_epoch
        self.decay=decay

    def on_epoch_begin(self, epoch, logs={}):
        old_lr = self.model.optimizer.lr.get_value()
        if epoch%self.n_epoch == 0 :
            new_lr= self.decay*old_lr
            k.set_value(self.model.optimizer.lr, new_lr)
        else:
            k.set_value(self.model.optimizer.lr, old_lr)

decaySchedule=decay_lr(10, 0.95)
```


You can use this directly without the epoch loop.

**Comment by anewlearner** [comment]
In my case, the learning rate was supposed to be decayed by specific iterations. In a theano backend keras, I can do using the following code:
```
class SGDLearningRateTracker(Callback):
    def on_batch_begin(self, epoch, logs={}):
        optimizer = self.model.optimizer
        rate= 0.95
        iteration=5000
        lr = optimizer.lr.get_value()
        iterations=optimizer.iterations.get_value()
        if iterations % iteration == 1:
            lr_now = np.array(lr * rate, dtype= 'float32')
            optimizer.lr.set_value(lr_now) 
            print('Ir reduced from %f to %f' % (lr, lr_now))
```
But when I changed to a tensorflow backend keras, I can not use above code, beacause  `optimizer.lr` is a tensorflow variable, and there is no `get_value()`. So I changed the code as follows:
```
class SGDLearningRateTracker(Callback):
    def on_batch_begin(self, epoch, logs={}):
        optimizer = self.model.optimizer
        rate= 0.95
        iteration=5
        lr = optimizer.lr 
        
        init_op = tf.initialize_all_variables()
        sess = tf.Session()
        sess.run(init_op)
        iterations=optimizer.iterations 
        lr_ori=sess.run(lr)
#        print('iter:', sess.run(iterations))  # this always prints 0 here
        if iterations % iteration == 0:
            a= np.array(lr*rate, dtype='float32')
            optimizer.lr.set_value(a) 
            lr_now=sess.run(optimizer.lr)             
            print('Ir reduced from %f to %f' % (lr_ori, lr_now))
```
But it did not work. I found that the `optimizer.iterations` was always 0. So the learning rate will not chagne. Could someone help me to figure this? 
Thanks!

Carol

**Comment by alalbiol** [comment]
Another option could be to use the LearningRateScheduler that
I found in the Keras documentation:
https://keras.io/callbacks/

You can use the schedule function that best fits your needs

**Comment by mohamed-ezz** [comment]
`model.optimizer.lr.set_value(0.01)` is Theano-specific, so won't work with tensorflow.

Use Keras backend instead : `K.set_value(model.optimizer.lr, 0.01)`

**Comment by FedericoMuciaccia** [comment]
@sergeyf please update the answer inside your initial question, because model.optimizer.lr.set_value() is no longer valid.
the actual method should be model.optimizer.lr.assign(your_learning_rate).
this also solves the problem of @Rusianka

**Comment by sergeyf** [comment]
@FedericoMuciaccia Thanks, I did as you suggested.

**Comment by marc-moreaux** [comment]
With TF backend, I did this (for inception-V3)
```
from keras.callbacks import LearningRateScheduler
def scheduler(epoch):
    if epoch%2==0 and epoch!=0:
        lr = K.get_value(model.optimizer.lr)
        K.set_value(model.optimizer.lr, lr*.9)
        print("lr changed to {}".format(lr*.9))
    return K.get_value(model.optimizer.lr)

lr_decay = LearningRateScheduler(scheduler)

model.fit_generator(train_gen, (nb_train_samples//batch_size)*batch_size,
                  nb_epoch=100, verbose=1,
                  validation_data=valid_gen,    nb_val_samples=val_size,
                  callbacks=[lr_decay]

```

**Comment by ViaFerrata** [comment]
@FedericoMuciaccia @sergeyf 
I think the syntax has changed again (using TF backend).
```
    adam = ks.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
    model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
    model.optimizer.lr.assign(100)
    # -> still trains perfectly, lr is not changed 
```
Keras doesn't throw an exception, but the lr doesn't change anyways.

Fortunately, the backend method still works:
```
K.set_value(model.optimizer.lr, 10)
```

**Comment by ghShu** [comment]
The "decay" option in the optimizer meant seems to be designed for learning rate decay. I did not see any suggestion on using this in the discussion. Could someone please comment on the use (or not use) the "decay"?
adam = ks.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)

**Comment by eram1205** [comment]
It does learning rate decay:
https://github.com/fchollet/keras/blob/master/keras/optimizers.py#L420

**Comment by Issam28** [comment]
when using rate decay in SGD do the optimizer.iterations reset at each epoch?

**Comment by Ostnie** [comment]
@ViaFerrata 
Why you change your code ?Does the code before you edit can be used rightly ? I don't understand the late one clearly

**Comment by casperdcl** [comment]
FYI updated issue and much simpler solution at #5724

**Comment by AndreyStille** [comment]
would never write my project on tf, despite job. Common things take hours to solve, miserable wooden api

keras 2.1.5
class CustomLearningRateScheduler(keras.callbacks.Callback):
            def __init__(self):
                super(CustomLearningRateScheduler, self).__init__()
                self.global_train_steps = 0
                self.lr = 0
            def on_batch_end(self, batch, logs=None):
                self.global_train_steps += 1
                if not hasattr(self.model.optimizer, "lr"):
                    raise ValueError('Optimizer must have a "lr" attribute.')
                if self.global_train_steps <= 66:
                    self.lr += 0.00001
                elif self.global_train_steps > 66 and self.global_train_steps <= 2000:
                    self.lr = 0.00066
                elif self.global_train_steps > 2000 and self.global_train_steps <= 4000:
                    self.lr = 0.00055
                elif self.global_train_steps > 4000 and self.global_train_steps <= 8000:
                    self.lr = 0.00044
                elif self.global_train_steps > 8000 and self.global_train_steps <= 12000:
                    self.lr = 0.00033
                else:
                    self.lr = 0.00033
                print(self.lr, self.global_train_steps, self.model.optimizer.lr)
                tf.keras.backend.set_value(self.model.optimizer.lr, self.lr)
                self.model.optimizer.lr.assign(self.lr)

No method changes the lr:
0.00066 66 <tf.Variable 'Adam/lr:0' shape=() dtype=float32_ref>
