### ISSUE TITLE
Problem with return_sequences=True

### ISSUE THREAD

**Issue by lemuriandezapada** [fchollet/keras#90]
Hey guys so I'm trying to feed a bunch of 2d (batches,seq_len) indices of text sequences into the model in an attempt to try to predict the next word. This leads to a 3d output of (batches,seq_len,vocab_size) time distributed softmax. 

```python
model = Sequential()
model.add(Embedding(vocabsize,128)) 
model.add(GRU(128, 128, return_sequences=True))
model.add(Reshape(seqlen,128))
model.add(Dense(128,vocabsize))
model.add(Reshape(seqlen,vocabsize))
model.add(Activation('time_distributed_softmax'))
```

So far so good. Running the model.predict_probas(sequences) yields a (batches,seq_len,vocab_size) output matrix. Problem is that doing the model.fit(sequences, bin_sequences, batch_size= 4) gives me the theano error of:

('Bad input argument to theano function with name "build/bdist.linux-x86_64/egg/keras/models.py:66"  at index 1(0-based)', 'Wrong number of dimensions: expected 2, got 3 with shape (4, 16, 15423).')

Even though the model does output a 3d array, theano still expects a 2d array. Or am I overlooking something?
Is there any way to deal with multiple multi-dimensional time sequences then?

**Comment by patyork** [comment]
You should be able to use TimeDistributedDense layers in place of Dense layers for this to work.

This layer was meant for use after a recurrent layer (when `return_sequences=True`, but it should work as a first layer.

https://github.com/fchollet/keras/blob/master/docs/sources/layers/core.md#timedistributeddense

**Comment by lemuriandezapada** [comment]
First of all, oh god thank you I feel so "dense" I completely overlooked the TimeDistributedDense. :)))

However even with that one replacing my mess:

```python
model = Sequential()
model.add(Embedding(vocabsize,128))
model.add(GRU(128, 128, return_sequences=True))
model.add(TimeDistributedDense(128,vocabsize))
model.add(Activation('time_distributed_softmax'))
```
I get the same error when running fit

```
('Bad input argument to theano function with name "build/bdist.linux-x86_64/egg/keras/models.py:66"  at index 1(0-based)', 'Wrong number of dimensions: expected 2, got 3 with shape (4, 16, 15423).')
```
It works running the predict function, though.
And the model.train() function works for one datapoint if I restrict the target dimensions to 2.

**Comment by patyork** [comment]
I'm not sure, but it looks like the `Embedding` layer is constrained to 2D inputs. @fchollet can probably answer more thoroughly.

**Comment by fchollet** [comment]
> So far so good. Running the model.predict_probas(sequences) yields a (batches,seq_len,vocab_size) output matrix. Problem is that doing the model.fit(sequences, bin_sequences, batch_size= 4) gives me the theano error of: ('Bad input argument to theano function with name "build/bdist.linux-x86_64/egg/keras/models.py:66" at index 1(0-based)', 'Wrong number of dimensions: expected 2, got 3 with shape (4, 16, 15423).')

It seems you are doing batches of batches (4x16). Why not just .fit(X, y, batch_size=16) where X would be an array of your sequences? The embedding inputs would then be (16, 15423).

**Comment by lemuriandezapada** [comment]
As I said, the embedding layer works fine. I can "predict_proba(sequences)" just fine all the way to the end of the network.

The embedding inputs  are already 2D or size (batches,seq_len). The targets, however, are 3D of size (batches,seq_len,vocab_size) . "batches" should be split during training, that's what "batch_size" does, seq_len is the same and vocab_size merely expands the target space. At the end of the embedding layer we're already at a (batches,seq_len,128) projection so that gets computed from 2d just fin. The model.fit() function is where I have problems. 

16 is my sequence length and 4 is my "batch size". From what I understand it should be able to compute the sequences, and then get the average gradient for those 4 batches, right? 

But for some reason, it won't compute and/or pass the gradient from the final layers backwards through the network because... theano. Computing it with the predict functions works just fine.

**Comment by lemuriandezapada** [comment]
I mean, for this particular case, the inputs to the embedding layer is of size (160,16) and the output at the end of the softmax is (160,16,15423), where 16 is the sequence length and 160 is the number of sequences.

I find it weird that I don't get this error during .predict(), but only during .fit() and .train(). Although running the .train() function with an X(1,16) and an y(16,15423) does me one iteration for one data point. Not with X(1,16) and  y(1,16,15423) as you'd imagine is normal.

But still, maybe I'm doing something wrong?

**Comment by lemuriandezapada** [comment]
simple model actually:

```python
model = Sequential()
model.add(GRU(256, 256, return_sequences=True))
model.compile(loss='mean_squared_error', optimizer='sgd')

inz = np.random.randn(100,100,256)
rez = model.predict_proba(inz) # 3d array
model.fit(inz,rez)
```
yields the same wrong number of dimensions error.

```python
model = Sequential()
model.add(GRU(256, 256, return_sequences=False))
model.compile(loss='mean_squared_error', optimizer='sgd')

inz = np.random.randn(100,100,256)
rez = model.predict_proba(inz) # 2d array
model.fit(inz,rez)
```

Works just fine. Quite convinced it's a keras/theano issue.

**Comment by mthrok** [comment]
In the simple case, it feels to me that in case you put 2D array, the dimension is (#Samples, #Dim-of-input-signal) since you set the input dimension to 256. 
Input dimension may be (100, 256) for 3D?

**Comment by fchollet** [comment]
Regarding your simple example above: you're attempting to train a model using targets that are 3D tensors. That's not currently possible, targets have to be 2D. Hence the dimension error. 

Here's why:
```python
models.py line 45:
self.y = T.matrix() # TODO: support for custom output shapes
```
If you change T.matrix() to T.tensor3() it will work (but then it will stop working for every other case...).

**Comment by lemuriandezapada** [comment]
mthork, the problem is that with time series you have (#samples, #length-of-signal, #dim-of-signal) as the errors need to backpropagate through time across the length-of-signal. So in this case you'd have 100 time series that are each 256 dimensional and 100 timesteps long.

fchollet, oh, ok, that's cool, thanks! I can definitely hack it in there myself. Maybe set a check for dimensionality and if it's 3d make it a tensor3. I'll give it a try on monday.

**Comment by lemuriandezapada** [comment]
fchollet, you're right. I had to change the models file but works like that. 
Would be nice to have it as a feature though

Thanks

**Comment by fchollet** [comment]
This is now a feature, you can pass an argument `y_dim_components` to the `compile` method of a model. Default is 1. In your example you'd have to use `y_dim_components=2`.

**Comment by lemuriandezapada** [comment]
Oh great! Even better! Thanks!

**Comment by andreas12345** [comment]
So, while this now works in the current version (at least it runs, I haven't checked the results):
```
model = Sequential()
model.add(GRU(256, 256, return_sequences=True))
model.compile(loss='mean_squared_error', optimizer='sgd')

inz = np.random.randn(100,100,256)
rez = model.predict_proba(inz) # 3d array
model.fit(inz,rez)
```
as soon as the number of samples and number of time steps are different, it does not work any more:
```
model = Sequential()
model.add(GRU(256, 256, return_sequences=True))
model.compile(loss='mean_squared_error', optimizer='sgd')

inz = np.random.randn(100,68,256)
rez = model.predict_proba(inz) # 3d array
model.fit(inz,rez)
```
```
AssertionError                            Traceback (most recent call last)
<ipython-input-89-5c6ce0d8a880> in <module>()
----> 1 model.fit(inz,rez)

/usr/local/lib/python2.7/site-packages/Keras-0.1.1-py2.7.egg/keras/models.pyc in fit(self, X, y, batch_size, nb_epoch, verbose, callbacks, validation_split, validation_data, shuffle, show_accuracy, class_weight)
    205                     batch_logs['accuracy'] = acc
    206                 else:
--> 207                     loss = self._train(*ins)
    208                 batch_logs['loss'] = loss
    209 
...
AssertionError: Theano Assert failed!
Apply node that caused the error: Assert(InplaceDimShuffle{1,0,2}.0, Elemwise{Composite{EQ(i0, ((i1 + i2) - Switch(LT(i3, (i1 + i2)), i4, (i1 + i2))))}}.0)
Inputs types: [TensorType(float64, 3D), TensorType(int8, scalar)]
Inputs shapes: [(68, 100, 256), ()]
Inputs strides: [(2048, 139264, 8), ()]
Inputs values: ['not shown', array(0, dtype=int8)]
```
Is this a bug, or am I missing something?
