### ISSUE TITLE
TypeError: __init__() got multiple values for keyword argument 'input_dim'

### ISSUE THREAD

**Issue by slmjlf** [fchollet/keras#909]
I installed Keras yesterday. I think the version is the newest. I just uninstalled Theano and reinstalled the Theano from Theano-master. Now I still get the following TypeErrors: 

model.add(Dense(10, init='uniform', input_dim=2))
TypeError: __init__() got multiple values for keyword argument 'input_dim'

model.add(Dense(128, input_shape=(784,)))
TypeError: __init__() got an unexpected keyword argument 'input_shape'

Could anyone tell what I can do? Thank you!

**Comment by slmjlf** [comment]
I solved the problem by download the new keras and copy the folder keras to Lib\keras to renew the libraries. Only uninstall the keras and reinstall it does not solve the problem. I manually deleted the keras lib and copy new libs into it.

**Comment by EvanVanNess** [comment]
@slmjlf can you provide more details on what you did to solve this problem?

**Comment by micklexqg** [comment]
@slmjlf   I come across the same problem, what is your version of keras?
