### ISSUE TITLE
Seemingly a small error in documentation

### ISSUE THREAD

**Issue by chunyangx** [fchollet/keras#912]
In the documentation for TimeDistributedDense, for initializing weights, it is written:

weights: list of numpy arrays to set as initial weights. The list should have 1 element, of shape (input_dim, output_dim).

I didn't look into the source code. But from my use, it seems to me that in fact the list should have 2 elements of shape (input_dim, output_dim) and output_dim initializing W (weight matrix) and b (bias).

**Comment by fchollet** [comment]
You're right. The `TimeDistributedDense` layers has two parameters, the weight matrix and the bias.
