### ISSUE TITLE
Dot merge mode between a sequential and a dense

### ISSUE THREAD

**Issue by chunyangx** [fchollet/keras#918]
Hello, 

I would like to know if it is possible to do this and how. 

I tried the following code getting an "Exception:  Dot incompatible layers can not be merged using dot mode"

```
input_model = Sequential()
input_model.add(TimeDistributedDense(dim, input_shape=(max_length1, dict_input_len1)))
input_model2 = Sequential()
input_model2.add(TimeDistributedDense(dim, input_shape=(max_length2, dict_intput_len2)))
input_model2.add(LSTM(dim, return_sequences=False))
attention = Sequential()
attention.add(Merge([input_model, input_model2], mode='dot'))
```

The idea is to do a dot product between the output of input model 2 (a dim dimension vector) and the output of input model (a max_length1, dim dimension vector). The wished output is (self.uttr_max_length, 1). Is it possible to do so using merge dot mode ?

**Comment by farizrahman4u** [comment]
Hi @chunyangx , The `dot` merge uses `theano.tensor.batched_tensordot(X,Y,axes)` to evaluate the dot product. Checkout the documentation of this function to understand the conditions to be satisfied by the output shapes of your input model.: http://deeplearning.net/software/theano/library/tensor/basic.html

**Comment by farizrahman4u** [comment]
@chunyangx 

Here is any easy fix:
* `attention.add(Merge([input_model, input_model2], mode='dot', dot_axes=1))`
Or a more explicit approach:
* `attention.add(Merge([input_model, input_model2], mode='dot', dot_axes=([2],[1])))`

Output shapes (ignoring `nb_samples`):

* Output shape of input_model: (max_length1,dim)
* Output shape of input_model2: (dim)
* Output shape of attention:  (max_length1)

> The wished output is (self.uttr_max_length, 1). Is it possible to do so using merge dot mode ?

The role of `dot` merge is over at this point. Now you can reshape your output using the `Reshape` layer. I am dumping the whole thing here:

```
import keras
from keras.models import Sequential
from keras.layers.core import TimeDistributedDense, Merge, Reshape
from keras.layers.recurrent import LSTM


dim = 10
max_length1 = 25
max_length2 = 30
dict_input_len1 = 15
dict_intput_len2 = 20

input_model = Sequential()
input_model.add(TimeDistributedDense(dim, input_shape=(max_length1, dict_input_len1)))
input_model2 = Sequential()
input_model2.add(TimeDistributedDense(dim, input_shape=(max_length2, dict_intput_len2)))
input_model2.add(LSTM(dim, return_sequences=False))
attention = Sequential()
attention.add(Merge([input_model, input_model2], mode='dot', dot_axes=([2],[1])))
attention.add(Reshape([max_length1,1]))
print attention.output_shape

```
* Again, the output shape is (max_length1,1). You can do padding to convert it to (uttr_max_length, 1). Hope this helps! And good luck with the attention model, contribute back to the community when done!

**Comment by chunyangx** [comment]
@farizrahman4u .

I should have thanked you earlier. Thanks to your previous comment, I figured out how to do it (exactly as your easy fix). But Thanks again for the even clearer explanation above.

**Comment by farizrahman4u** [comment]
Glad to help!

**Comment by farizrahman4u** [comment]
@chunyangx  #920 is merged. Now you don't need this fix!

**Comment by vyraun** [comment]
@farizrahman4u Hi, could you take a look at https://github.com/fchollet/keras/issues/4702 . I am getting a dimension incompatibility error. I am missing something trivial I guess. Thanks.

**Comment by longzaitianguo** [comment]
@farizrahman4u 
When I run your codes, the program reports the following bug:
1. with attention.add(Merge([input_model, input_model2], mode='dot', dot_axes=([2],[1]))):
        ValueError: Invalid format for dot_axes - list elements should be "int".
2. with attention.add(Merge([input_model, input_model2], mode='dot', dot_axes=1)):
        ValueError: Dimension incompatibility using dot mode: 25 != 10. Layer shapes: (None, 25, 10), (None, 10)

Looking forward to your reply. Thanks!
