### ISSUE TITLE
Limited Weight Sharing (LWS) for convolution layer

### ISSUE THREAD

**Issue by trungnt13** [fchollet/keras#925]
LImited weight sharing is used in speech recognition, you can found brief description of it in this link: http://recognize-speech.com/acoustic-model/knn/comparing-different-architectures/convolutional-neural-networks-cnns

Is it possible in keras ? 

I think the idea is similar to using many convolution layer for each subregion of spectra image, the issue is how to make a clean implementation of this operator, especially when each subregion will need different pooling layer. 
![Math](http://recognize-speech.com/images/MichaelT/CNN/4_CNN_weights_matrix_limited_sharing.png)
![Illus](http://recognize-speech.com/images/MichaelT/CNN/5_CNN_weights_sharing_matrixx.png)

**Comment by Miail** [comment]
Hmm... is it necessary to do a specific implementation for that? 
I mean limited weight sharing suggest that certain filter bank area are allowed to share their weight. 

What if you made the network to take in multiple input, each being a section you've defined , and each section has its own convolutional and pooling layer... 

Wouldn't you thereby have established some thing similar to limited weight sharing..  The weight is only sharing for each section.

**Comment by moses1994** [comment]
Will this suggestion be added to keras?
