### ISSUE TITLE
Dot Merge do not return the correct output shape

### ISSUE THREAD

**Issue by dbonadiman** [fchollet/keras#936]
This is not a bug but only a consideration. The dot merge mode as first intended was thinked to do a dot product between 1d tensors.
For that it works perfectly, however if we give the possibility to use 2D tensors in input and a dot-asxes we need to make some adjustment.
Giving the following tensors as input (None, 50, 100) and (None, 50, 2) and ([1], [1]) as dot-asxes the computed output shape is (None, 100) if we invert the order of the input is (None, 2) But the correct output shape are (None, 100, 2) and (None, 2, 100).

From that the function dimshuffle(0, 'x') will fail.

I'm here to reason about a possible solution (that can be a simple check that the two shape are equal) and directly limit the api potential. 

The first Naive solution is to correctly compute the output_shape by concatenating all the dimension excluding the "dotted_ones" and using the reshape function instead of the dim shuffle 'don't know about the last change so i ask for suggestion'.

**Comment by fchollet** [comment]
@farizrahman4u thoughts on this?

I also don't understand why `dimshuffle(0, 'x')` was ever necessary in the first place. Removing it does not make the tests fail. If removing a line of core logic does not make the tests fail, either the line is superfluous either the tests need to be rewritten.

**Comment by dbonadiman** [comment]
@fchollet In my first implementation that was then integrated in the @farizrahman4u code the `dimshuffle(0, 'x')` was added to deal with the very simple case of doing the dot product between two vectors.

As you can se in https://github.com/fchollet/keras/issues/878 i justified this addition in that way:
> By the way you can use the batched dot to do the trick and remember to dimshuffle the output since the output shape of the function is always a vector in the form (Batch_size,) but you need (Batch_size, 1).

And we do not have a layer to fix this problem. So a simple solution is an if to deal with that simple case (like doing the dim shuffle when: no axis are presented or all the axis are presented as dot_axes)

**Comment by fchollet** [comment]
> So a simple solution is an if to deal with that simple case (like doing the dim shuffle when: no axis are presented or all the axis are presented as dot_axes)

Agreed. We should do that.
