### ISSUE TITLE
Dataset inside GPU, is it possible?

### ISSUE THREAD

**Issue by felipefariax** [fchollet/keras#940]
Hello!

I have a small dataset (less than 20% of my GPU memory). I would like to know if I could load all the dataset inside the GPU in order to decrease memory transfers and manipulate each batch to train the model with train_on_batch().

**Comment by fchollet** [comment]
Basically, no. But it would be fairly easy to add support for it (modify `models.Sequential.fit()`), if you feel like it.

**Comment by felipefariax** [comment]
Ok, @fchollt.

in this code:

    ins = X + [y, sample_weight]

if X and y are shared variables, everything will work fine, isn't it? All I have to do is deal with some len(y) among other things that don't work with CudaNdarray?

If so, I'll try it at night!

**Comment by felipefariax** [comment]
@fchollet 
I would like to use it at train_on_batch, because I need to create a special minibatch at each iteration (as I'm using a timeseries, each example for a CNN should be some past inputs and I don't want to repeat all the examples because of the memory usage, I rather create like X[n_past_inputs:current, :]. If the data was already on GPU, I think that it shoud be faster.

Do you have any clues on how I could do it?

**Comment by JohannesAck** [comment]
Has anything changed on this matter, in the last four years?
