### ISSUE TITLE
Loading dataset error

### ISSUE THREAD

**Issue by dnth** [fchollet/keras#943]
Hi, I am facing this error when I run the reuters_mlp.py
This error happens after I interrupted the training process halfway. 

The next time I run the same script this error pops up. 
Loading data...
Traceback (most recent call last):
  File "reuters.py", line 26, in <module>
    (X_train, y_train), (X_test, y_test) = reuters.load_data(nb_words=max_words, test_split=0.2)
  File "/home/camaro-workstation/anaconda/lib/python2.7/site-packages/keras/datasets/reuters.py", line 92, in load_data
    X, labels = six.moves.cPickle.load(f)
ValueError: could not convert string to int

**Comment by mmmikael** [comment]
Did you interrupt it while it was downloading the dataset?
You can delete the dataset file ```reuters.pkl``` (in ```~/.keras/datasets```) and try running it again.

**Comment by dnth** [comment]
Thanks, that did the job! I interrupted the training loop to be precise. But somehow it causes the dataset to corrupt?
