### ISSUE TITLE
version change too much，some of my personal idea can not merge keras.

### ISSUE THREAD

**Issue by meanmee** [fchollet/keras#945]

**Comment by meanmee** [comment]
for example,I can use SPP in version 1,but not in version 2 now

**Comment by meanmee** [comment]
for example,I can use SPP in version 1,but not in version 2 now

**Comment by meanmee** [comment]
for example,I can use SPP in version 1,but not in version 2 now

**Comment by fchollet** [comment]
Time to upgrade your personal ideas then.
