### ISSUE TITLE
T.nnet.relu missing implementation

### ISSUE THREAD

**Issue by rfeinman** [fchollet/keras#948]
I have noticed that Theano's tensor.nnet will not support the relu() function until the next version, 0.7.1, however, Keras source code makes calls to this function currently. Is there a mistake?

**Comment by Chasego** [comment]
You probably installed the stable release of Theano (0.7.0). You should follow the instructions of https://github.com/fchollet/keras/blob/master/README.md to install the latest development version of theano where relu() is implemented.
