### ISSUE TITLE
Layer is not connected. Did you forget to set "input_shape" (older keras versions don't have the issue)

### ISSUE THREAD

**Issue by elligottmc** [fchollet/keras#952]
I saw a similar issue posted but it has been closed and I didn't see a resolution.  So opening fresh.

The above error occurs when adding a Dense layer to any of the recurrent layers.

For example very simple things that used to work fine in the older version like...

model = Sequential()
model.add(GRU(128))
model.add(Dense(1))

..now produce this error

Is there a workaround besides downgrading?

**Comment by mmmikael** [comment]
With the new API, I think you need to specify '''input_dim''' for the first layer '''GRU'''. That will initialize '''input_shape'''.

**Comment by elligottmc** [comment]
That did it.  Thanks!
