### ISSUE TITLE
model.save_weights/model.load_weights incompatible with layer.trainable = False

### ISSUE THREAD

**Issue by stephenroller** [fchollet/keras#953]
Writing this down so I don't forget, but I haven't got a patch or test yet (ICLR deadline approaching fast...)

The new .trainable parameter is very nice; I've found it particularly useful for settings where I want to keep my word embeddings fixed and learn a task-specific _transformation_ of them, rather than backprop into them.

Currently, save_weights and load_weights are broken by these: one uses get_weights(), which returns weights for the frozen layers (desirable); however, load_weights fails, since it uses .params, which only returns trainable parameters.

**Comment by mmmikael** [comment]
If I understand correctly, the problem happens at [this line](https://github.com/fchollet/keras/blob/master/keras/layers/containers.py#L104) when you have an "inner-container", i.e. ```self.layers[i]``` is a ```Sequential``` or ```Graph```. One way to go around it is by adding a property ```nb_params``` that does not check the ```trainable``` flag. 

What do you think?

**Comment by stephenroller** [comment]
You're correctly identifying the bug. One issue then is that serializing and reloading would cause frozen layers to have random initialization values, rather than the correct frozen ones.

**Comment by mmmikael** [comment]
@stephenroller do you have a "minimal" sample network to test that?

**Comment by kg07** [comment]
I was wondering if this issue is fixed? I am having a problem in load_weights/save_weights as well. 

I have two models that I merge (one is an embedding layer, the other is a Conv Layer). I can load the weights fine if I do NOT include the "trainable" parameter as I add layers to my model, that is:
model.add(Dense(16, activation="tanh"))

The issue arises when I add the "trainable" parameter (to either True or False).
model.add(Dense(lstm_cells, activation="tanh", trainable = True))

Thanks.

**Comment by kg07** [comment]
I have a temporary workaround for this if anyone is interested. It only works if any of the layers in the model is a one-deep "Merge". My problem was as @mmmikael described, that the model has an "inner-container". That is, my model had a "merge" container in it that concatenated two models.

I modified the load_weights() in /keras/models.py as follows
```
 777     def load_weights(self, filepath): 
 778         '''Load all layer weights from a HDF5 save file. 
 779         ''' 
 780         import h5py 
 781         f = h5py.File(filepath) 
 782         for k in range(f.attrs['nb_layers']): 
 783             # This method does not make use of Sequential.set_weights() 
 784             # for backwards compatibility. 
 785             from keras.layers.core import Merge 
 786             g = f['layer_{}'.format(k)] 
 787             
 788             weights = [g['param_{}'.format(p)] for p in range(g.attrs['nb_params'])] 
 789             #Check if this is a Merge layer. If so, set the parameters accordingly 
 790             if(isinstance(self.layers[k],Merge)): 
 791                 no_subcontainers = len(self.layers[k].layers) 
 792                 for idx in range(no_subcontainers): 
 793                     #Get the number of parameters in this sequential model 
 794                     no_weights  = len(self.layers[k].layers[idx].get_weights()) 
 795                     #Set the weights 
 796                     self.layers[k].layers[idx].set_weights(weights[:no_weights]) 
 797                     weights = weights[no_weights:]  
 798             else: 
 799                 self.layers[k].set_weights(weights) 
 800         f.close() 
```

**Comment by lxmeng** [comment]
@kg07 i found that using 'merge', the 'trainable' flag for previous layer setting is not-work any more, how u solve that problem?

**Comment by divamgupta** [comment]
Any updates on this issue?
I am still facing this problem.

**Comment by timpx** [comment]
I am experimenting the same issue with keras 1.2.0
