### ISSUE TITLE
Unroll option in recurrent layers

### ISSUE THREAD

**Issue by stephenroller** [fchollet/keras#954]
Forgive me if this has come up before.

It's common in other NN libraries to unroll recurrent layers whenever possible, replacing a theano.scan with bunch of non-scan computations. This can significantly speed up the network, though often at the cost of memory. In general, Theano [advises against using scans](http://deeplearning.net/software/theano/library/scan.html#minimizing-scan-usage) whenever possible, as performance is greatly hindered on the GPU.

Should we unroll scans in the recurrent layers when we can? One option would to borrow Lasagne's [unroll_scan](https://github.com/Lasagne/Lasagne/blob/80b61cb1bda4d2a3eca1a8b97f0ccfc4ed8205b4/lasagne/utils.py#L340) utility function, which conveniently has the same options as the theano.scan option.

Pros:
- Potentially much faster recurrent computations (my preliminary experiment saw the training time of one epoch go from ~1300s to ~1050s, which adds up quickly)

Cons
- No more truncate_gradient option (does anyone use this?)
- Only possible when input_length is provided
- More confusing code base

**Comment by EderSantana** [comment]
This seems super cool!!! Does it compile faster too? Let me try it.

**Comment by fchollet** [comment]
Pretty cool stuff, I wasn't aware of this. 

> truncate_gradient (does anyone use this?)

I've used it before. It can be useful in some specific setup. Removing it wouldn't be a huge loss though.

> Only possible when input_length is provided

That's a reasonable restriction.

> More confusing code base

I find it surprisingly clean!

**Comment by nouiz** [comment]
This unroll scan could be moved to Theano. It was on our todo list, but we
didn't got the time for this. If someone want to help, it would be great.

**Comment by stephenroller** [comment]
I'm going to copy it into Keras and integrated into the RNNs for now, but it would be great to see it moved upstream.

It's worth noting that it has a *slightly* different call structure than theano.scan (namely, outputs_info *must* be a list, and it returns a list, even if it's a singleton). This could be easily amended though.

**Comment by elanmart** [comment]
@stephenroller how much longer does "unrolled" version compile?

**Comment by stephenroller** [comment]
My current NN has an input_length of 10, which is super small. So far it hasn't been noticeable for me. Maybe an extra 5-10s of compile time, on top of what's already ~50s? It should grow substantially with input_length. Right now the ~20% time saved in training time seems well worth it to me though (one takes a minute or so, the other takes hours), but the trade-off is definitely there.

**Comment by elanmart** [comment]
I was just curious, for long runs it won't matter and for prototyping you can use normal scan.

**Comment by gokceneraslan** [comment]
`truncate_gradient` gone for good here? https://github.com/fchollet/keras/commit/47ed18a3af8be20dce91286a331d4671074ee0ca

**Comment by Pranav-Goel** [comment]
Can anyone please clarify the conclusion of this? And how to use truncate_gradient option (to perform Truncated BPTT) in keras? truncate_gradient in theano should have something equivalent for keras, right? I would really appreciate some help here.
