### ISSUE TITLE
Trainable Scalar weight

### ISSUE THREAD

**Issue by tasmalinakis** [fchollet/keras#955]
Hello,

Is there a way to add a trainable scalar weight in order to multiply a dense matrix, preferably in a Graph? I am trying to build morphologically aware word embeddings and I need to be able to weigh differently the embeddings of the whole word and its morphemes. I am trying to build a variation of this model: http://research.microsoft.com/pubs/226628/[COLING2014]%20Morphological%20Word%20Embedding.pdf 

Thanks for your help!

**Comment by EderSantana** [comment]
Try defining your scalar using "shared_scalar": https://github.com/fchollet/keras/blob/master/keras/utils/theano_utils.py#L19-L20

If you find problems with the gradient in that case, define your variable with a regular `sharedX` (or with the layers `init` method) and use Theano `T.repeat` to make it have the proper size.

**Comment by tasmalinakis** [comment]
Thanks for your fast response. I had seen the theano utils module and thought about shared_scalar, but it is not obvious to me how I can mix Theano variables with Keras layers. Can you give me a dummy example of a keras layer output being multiplied with a Theano scalar?

Thanks for your support!

**Comment by EderSantana** [comment]
You have to define your own class. Or use the Lambda layer... but I think both solutions has the same amount of work.
```python
class Scalar(Layer):
    def __init__(**kwargs):
        super(Scalar, self).__init__(**kwargs)
    def build(self):
        self.scalar = shared_scalar(.001) # initial value
        self.input = T.matrix()
        self.params = [self.scalar]
     def get_output(self, train=False):
        X = self.get_input()
        return X*self.scalar
    @property
    def output_shape(self):
 

model = Sequential()
model.add(Dense(100, input_dim=30))
model.add(Scalar())
