### ISSUE TITLE
Coordinate Keras user meeting at NIPS

### ISSUE THREAD

**Issue by wxs** [fchollet/keras#962]
OK a Github issue is an… unorthodox way to coordinate this. But I think it'll do the trick. @fchollet apologies if you'd rather we do this another way.

Over in the discussion at #395 it turned out that a bunch of Keras users and contributors will be at NIPS in Montreal this year. We should organize some sort of face-to-face meeting, maybe a dinner? I'll set up an availability poll and we'll try to pick a time and location that works for everybody. Watch this issue for updates.

Paging: @gautamb85 @sergeyf @mphielipp @lukedeo @cmyr

**Comment by lukedeo** [comment]
Awesome, keep us posted @wxs!

**Comment by sergeyf** [comment]
I am 100% in.

**Comment by EderSantana** [comment]
we could setup a Slack or Gitter here on Keras. The chat data could also be publicly used for building RNN based chat bots. Wouldn't that be cool? It seems that keras.slack.com already exists so I created kerasio.slack.com
Anybody down for that idea? I can send chat invitations already

**Comment by wxs** [comment]
A Keras Slack sounds fun. I'd defer to @fchollet to anoint his preferred community hub...

**Comment by EderSantana** [comment]
@wxs agreed. Let us wait for @fchollet.

**Comment by fchollet** [comment]
I'm pretty old-school, I like email and Github issues. I wouldn't have much time to check a Slack or Gitter channel (I already can't keep up with a lot of what's happening on Github). But if you guys think it would be valuable to you, then go ahead!

**Comment by iskandr** [comment]
@fchollet Will you be at NIPS this year?

**Comment by EderSantana** [comment]
@fchollet if you don't mind us eventually using issues in such off topic cases, that is cool too!!!

**Comment by LeavesBreathe** [comment]
> if you don't mind us eventually using issues in such off topic cases, that is cool too!!!

That would be great -- I feel that the github issues forum is so clean and very easy to follow. The Google Users group just has alot of unnecessary text within the thread (not your fault, Google's).

**Comment by cinjon** [comment]
Pretty new to the Keras scene, but I'm game for meeting up too!

**Comment by jimfleming** [comment]
As a Keras user who will be at NIPS this year a meetup sounds great.

**Comment by kenterao** [comment]
I will be at NIPS as well.

**Comment by wxs** [comment]
Great! Sounds like we've got lots of interest. I've set up a Doodle with three different evenings to choose from (I left out the Monday because of the opening reception, and the Thursday since the symposia supposedly go late).

http://doodle.com/poll/smm9tmkphneixkyi

Fill it out and we'll figure out a time that works for everyone!

**Comment by the-moliver** [comment]
Sounds fun, filled it out!

**Comment by wxs** [comment]
OK next week I'm going to pick the date, so if you haven't filled out the Doodle yet please fill it out by Sunday night!

**Comment by wxs** [comment]
Alright, it's official, we're going to do 8PM on Wednesday the 9th at Kanbai, a good Szechuan place right near the convention centre. Looks like there'll be about 10 of us.

Link here: https://www.google.com/maps/place/Kanbai/@45.507861,-73.5620021,17z/data=!4m2!3m1!1s0x4cc91a51c34cac65:0xa49e3523966e1b82

Looking forward to meeting you all!

**Comment by ogrisel** [comment]
I'd like to join and probably @charlesollion, @eickenberg as well.

**Comment by wxs** [comment]
OK reminder everyone this is tonight! I'll get a big table and hopefully there's room for everyone.

**Comment by mynameisfiber** [comment]
Great night!  As per our parting remarks, I've created a slack server to be used for keras users to talk about cool stuff they're working on and to coordinate possible collaboration!

Just fill out this survery and I'll send you an invite as soon as the NIPS wifi gives me a good enough signal -- http://goo.gl/forms/23sPWIRG0s
