### ISSUE TITLE
[Keras + (VIM + YouCompleteMe)] - PYTHONPATH keras problem

### ISSUE THREAD

**Issue by felipefariax** [fchollet/keras#968]
Hello!

Someone uses this combination?

YouCompleteMe looks for the source code based on the PYTHONPATH environment variable.

When I've installed Theano, automatically the path to Theano was added to sys.path, but when I've installed Keras, it didn't happen. So YouCompleteMe can't find it's sources, unless I type

```
export PYTHONPATH=/path/to/keras
vim test.py
```

then it works...

Is there a way to permanently put keras on sys.path, without being through ~/.bashrc?
I think that it can be done on setup.py, is it possible?

**Comment by EderSantana** [comment]
I actually thought about this xD I wanted a snippet to quickly setup models :+1:

**Comment by phreeza** [comment]
Did you run ```python setup.py install``` in the keras directory?

**Comment by felipefariax** [comment]
Yes @phreeza, I did.
