### ISSUE TITLE
How to modify source code and add new function?

### ISSUE THREAD

**Issue by jerryli1981** [fchollet/keras#973]
Hi All,
I try to add a new merge mode. Therefore, I modified Merge class.
At the beginning, I installed keras with "sudo python setup.py install" command.

So after I modified the source code. I run "sudo python setup.py install" again. However, I seems it doesn't work. And throw below exception. 

  File "build/bdist.macosx-10.11-intel/egg/keras/layers/containers.py", line 33, in add
  File "build/bdist.macosx-10.11-intel/egg/keras/layers/core.py", line 34, in set_previous
TypeError: object of type 'NoneType' has no len()

I am not sure it is a installation problem or modify Merge class problem. 
Thanks

**Comment by jerryli1981** [comment]
Is there any easy way to update keras module?

**Comment by FiReTiTi** [comment]
Have you succeeded in adding a new merge mode?
I have to do exactly the same thing.
