### ISSUE TITLE
[UX issue] Graph model currently limited.

### ISSUE THREAD

**Issue by dbonadiman** [fchollet/keras#974]
From my opinion there is an issue in the current implementation of graph model.
Actually if you want to add a layer with multiple input you need to merge and use the standard sequential layers. But graph model are much more powerful from my point of view. Moreover having two kinds of input arguments makes all very clutter.
At the moment we are making the Merge function really messy only to avoid this problem.
Here is an example that worth more then a 1000 words.

Let's assume that we want to create a model accepting two sentence or two images, creates a representation of the two and computes a similarity function between the two representation

``` python

model = Graph()
model.add_input(... , name='input1')
model.add_input(... , name='input2')

#i will skip some of the nodes to create the representation
model.add_node(some hidden nodes, name='inp1repr', input='input1')
model.add_node(some hidden nodes, name='inp2repr', input='input2')

#then it is possible to build a similarity function between the two representation in this way. 
#Assume x = inp1repr and z= inp2repr so the similarity function can be computed as follows y =  xWz where W is similarity matrix and y is the similarity score.

model.add_node(Dense(inp1repr_size), name='intermediate_node', input='inp2repr')
model.add_node(Activation('linear'), name='similarity', inputs=['inp1repr', 'intermediate_node'], merge_mode='dot')

```

This implementation is confusing and redundant. 
What i'm proposing is to make the Graph model more transparent giving the possibility to add Layers that accepts multiple inputs.

So it is possible to implement a `Similarity` layer computing `y = xWz` with a trainable matrix `W`. By doing so the implementation of the previous code would be.

``` python

model = Graph()
model.add_input(... , name='input1')
model.add_input(... , name='input2')

#i will skip some of the nodes to create the representation
model.add_node(some hidden nodes, name='inp1repr', input='input1')
model.add_node(some hidden nodes, name='inp2repr', input='input2')

model.add_node(Similarity(), name='similarity',  input=['inp1repr', 'inp2repr'])
```

That will remove most of the problems in the Merge Layer by simply implementing all the layers accepting multiple inputs as autonomous layers.

This change can break previous models but it can be implemented in a way that if we have a standard layer with multiple inputs and a merge mode, we can simply add two layers: a merge layer, and the chosen layer on top; in this way it should work exactly as before. 

What do you think?
Since it is a big change i ask for the @fchollet opinion in particular before starting on anything.

Thanks to all of you.

**Comment by EderSantana** [comment]
But that already works... just use 
```python
model.add_node(Similarity(), name='similarity',  input=['inp1repr', 'inp2repr'], merge_mode='join')
```

and inside your Similarity
```python
def get_output(self, train)
    X = self.get_input() # returns OrderedDict {'inp1repr': tensor1, 'inp2repr': tensor2}
    X = list(X.items())
    return T.dot(T.dot(X[0], self.W), X[1])
```

Also, you may not even need to write a whole new class. Just use a LambaLayer.

**Comment by farizrahman4u** [comment]
@EderSantana  I dont think you can have a trainable matrix inside a lambda function. Lambda functions are stateless functions.. just an F(x).

**Comment by EderSantana** [comment]
@farizrahman4u oh, my bad! So yeah, I think he just needs to write his new class then.

**Comment by dbonadiman** [comment]
Thanks you guys i just not got how the join mode worked, but now i have another question. In order to build the layer (for the Weight matrix) i need the inputs shapes. the merge mode join do not provide any output shape, so my layer should get the two input_shapes directly, like that?

```python
model.add_node(Similarity(1, activation='sigmoid', input_shapes=[model.nodes['input1'].output_shape, model.nodes['input2'].output_shape]), name='sim', inputs=['input1','input2'], merge_mode='join')
```

**Comment by dbonadiman** [comment]
There is even this error that the join mode does't find the name of the inputs https://github.com/fchollet/keras/issues/975#issuecomment-156851799

**Comment by farizrahman4u** [comment]
Lot of people have been having trouble with join mode recently.We really need @fchollet to look into it.
