### ISSUE TITLE
How to use the join mode?

### ISSUE THREAD

**Issue by jerryli1981** [fchollet/keras#975]
I am struggle with the join mode, still can not figure out how to use it correctly, here is my code

```
mul_layer = Sequential()
mul_layer.add(Merge([first_rep_layer, second_rep_layer], mode='mul'))

sum_layer = Sequential()
sum_layer.add(Merge([first_rep_layer, second_rep_layer], mode='sum'))

model = Sequential()
model.add(Merge([mul_layer, sub_layer], mode='join'))
model.add(Dense(args.hiddenDim, input_shape=(2*args.wvecDim,)))
model.add(Activation('sigmoid'))
```

Always get 

Traceback (most recent call last):
  File "rnn_mlp_keras.py", line 117, in <module>
    model.add(Dense(args.hiddenDim, input_shape=(2*args.wvecDim,)))
  File "build/bdist.macosx-10.11-intel/egg/keras/layers/containers.py", line 33, in add
  File "build/bdist.macosx-10.11-intel/egg/keras/layers/core.py", line 34, in set_previous
TypeError: object of type 'NoneType' has no len()

**Comment by jerryli1981** [comment]
It seems the reason is in core.py, line 359

```
 def output_shape(self):
        input_shapes = [layer.output_shape for layer in self.layers]
        if self.mode in ['sum', 'mul', 'ave', 'abs_sub']:
            return input_shapes[0]
        elif self.mode == 'concat':
            output_shape = list(input_shapes[0])
            for shape in input_shapes[1:]:
                output_shape[self.concat_axis] += shape[self.concat_axis]
            return tuple(output_shape)
        elif self.mode == 'join':
            return None
````
The output_shape method of Merge class return None if the mode is join. This will cause the base class can not verify the assert
```
def set_previous(self, layer, connection_map={}):
        assert self.nb_input == layer.nb_output == 1, "Cannot connect layers: input count and output count should be 1."
        if hasattr(self, 'input_ndim'):
            assert self.input_ndim == len(layer.output_shape), "Incompatible shapes: layer expected input with ndim=" +\
                str(self.input_ndim) + " but previous layer has output_shape " + str(layer.output_shape)
        if layer.get_output_mask() is not None:
            assert self.supports_masked_input(), "Cannot connect non-masking layer to layer with masked output"
        self.previous = layer
        self.build()
````

So this means current version keras don't support merge mode is join ?

**Comment by fchollet** [comment]
Are you looking to use `concat` instead? Your code doesn't make sense to me.

**Comment by jerryli1981** [comment]
It seems I can not use concat. Because My hidden layer have two input. For example
Hidden_layer_output = activation(W1.dot(X1) + W2.dot(X2) + B)

**Comment by gw0** [comment]
@jerryli1981 `W dot (X1 concat X2)` is a more general formula, also capable of expressing what you want, and `concat` should be make it work.

Anyway, I am also wondering what is the use case for `merge_mode='join'`? To me it seems like it is part of a refactoring process that will standardize handling of inputs and outputs in `Graph`-like style?

**Comment by gw0** [comment]
I was trying to unsuccessfully use it to pass two inputs through the same `Embedding` layer (to get same mappings) and then separate them again:

```
    model.add_input(name='aaa', input_shape=(None,), dtype='int')
    model.add_input(name='bbb', input_shape=(None,), dtype='int')
    model.add_node(Embedding(vocab_size, embedding_dim), name='layer_1', inputs=['aaa', 'bbb'], merge_mode='join')
```

**Comment by farizrahman4u** [comment]
@jerryli1981 `join` merge mode is exclusively for `Graph` models.(except when you have a `Lambda` layer on top of `join` merge)

@gw0 Your inputs will be merged before going to the embedding layer. You  have to use the incoming Siamese layer(#928) to avoid it.

**Comment by dbonadiman** [comment]
Guys are we sure that the `join` mode is working properly anyone tested it recently.
Cause when i'm using it in `Graph` models i'm getting some wired exception like (it is working only on named inputs when my input should have a name ) in particular the layers in input are time distributed merge layers (i've tested even with Dense Layers but it does't work).

**Comment by gw0** [comment]
@farizrahman4u Thank you very much.

**Comment by jerryli1981** [comment]
@gw0 , Thanks for your suggestion, Currently, I am using what you said 
```
 W dot (X1 concat X2)
```
to simulate join. That works

**Comment by dbonadiman** [comment]
@jerryli1981 That implementation works but it doesn't work in the way you wanted a simple way to do your implementation is to do something like.

```
(W1 dot X1 + b1) +  (W2 dot X2 + b2)
```
You can do it with two simple Dense layers plus a Merge Sum. 

```python
mul_layer = Sequential()
mul_layer.add(Merge([first_rep_layer, second_rep_layer], mode='mul'))
mul_layer.add(Dense(dim))

sum_layer = Sequential()
sum_layer.add(Merge([first_rep_layer, second_rep_layer], mode='sum'))
sum_layer.add(Dense(dim))

model = Sequential()
model.add(Merge([mul_layer, sum_layer], mode='sum'))
model.add(Activation('sigmoid'))
```

Probably you have to add some shapes around but that's the idea.
For my code i implemented a layer that implements your formulae but it works only in graph modes and with the modification to the join layer you can see in the pull request.

**Comment by dbonadiman** [comment]
@jerryli1981 In my pull request https://github.com/fchollet/keras/pull/1018 i implemented the bilinear layer you wanted, if the pull request passes you can easily implement your model as.

```python
mul_layer = Sequential(name='mul_layer')
mul_layer.add(Merge([first_rep_layer, second_rep_layer], mode='mul'))

sum_layer = Sequential(name='sum_layer')
sum_layer.add(Merge([first_rep_layer, second_rep_layer], mode='sum'))

model = Sequential()
model.add(Merge([mul_layer, sub_layer], mode='join'))
model.add(BiLinearLayer(args.hiddenDim, input_dim=[2*args.wvecDim, 2*args.wvecDim]))
model.add(Activation('sigmoid'))
```
join wasn't working in Sequential models because:
  - layer wasn't named 
  - There was no Layer with weights that was actually taking two inputs (I have others layer in my personal repository other then the BiLinearLayer) such as the Similarity that takes two vectors and computes the follows (xWz) and the NeuralTensor Layer used by the Stanford  group, but i'm waiting for the join mode to be added to implement them in Keras.

**Comment by charlesollion** [comment]
I'm also having having trouble using the join mode, in order to be able to pass two inputs to a specific RNN (one input to iterate on, the other to condition the generation, fixed). Any other idea on how to do that without join? 
Also UX question: shouldn't join be the default merge mode?

**Comment by dbonadiman** [comment]
Your RNN is a custom RNN i assume?
In that sense you could concat the two and then split it is horrible but it should work in some way :D The join has problem i started to solve them but for now i don't have much time to finish it

**Comment by jerryli1981** [comment]
@farizrahman4u, When you implement graph, did you face this issue 
```
ValueError: ('this shared variable already has an update expression', (mul_merge_p0, Elemwise{sub,no_inplace}.0))
```
Below is my code on graph, it seems so weird.
```
mul = Merge([lstm_1, lstm_2], mode='mul')
model.add_node(mul, inputs=['lstm1', 'lstm2'], name='mul_merge', merge_mode="mul")
```
I try to merge to two lstm output, however, there are two merge mode I need to set. ''join" can't put into Merge layer, it can be set like merge_mode="join", However, it seems doesn't affect anything. So the question is how to use merge in graph?

```
model.compile(optimizer=optimizer, loss={'softmax_out':'categorical_crossentropy'})
  File "/Users/peng/Develops/keras/keras/models.py", line 620, in compile
    allow_input_downcast=True, mode=theano_mode)
  File "/Library/Python/2.7/site-packages/theano/compile/function.py", line 308, in function
    output_keys=output_keys)
  File "/Library/Python/2.7/site-packages/theano/compile/pfunc.py", line 489, in pfunc
    no_default_updates=no_default_updates)
  File "/Library/Python/2.7/site-packages/theano/compile/pfunc.py", line 184, in rebuild_collect_shared
    (store_into, update_d[store_into]))
ValueError: ('this shared variable already has an update expression', (mul_merge_p0, Elemwise{sub,no_inplace}.0))
````
