### ISSUE TITLE
Better keras checks and exceptions.

### ISSUE THREAD

**Issue by dbonadiman** [fchollet/keras#977]
Hello everybody,
At the moment we execute all the variable checks inside the init function of every layer.
Shouldn't we build a more consistent type check?

Here is an example from convolution 1d:

``` python
        if border_mode not in {'valid', 'full', 'same'}:
            raise Exception('Invalid border mode for Convolution1D:', border_mode)

```

I think that this check shouldn't be inside the init directly but we should have something like:

``` python

self.border_mode =  border_mode

```

inside the init function and 

``` python
@property
def border_mode(self):
        return self._border_mode

@border_mode.setter
def border_mode(self, value):
        if value not in {'valid', 'full', 'same'}:
            raise Exception('Invalid border mode for Convolution1D:', value)
        self._border_mode = value       

```

In this way properties are checked even if we change a variable in a second stance.

``` python
layer.border_mode  =  'full'
```

and  we can build a more solid types check for every keras layer and property.

another interesting things is to make some private types. That rise exception if you try to change them.
What we need at the moment is a more solid environment to experiment on.

This is in line with https://github.com/fchollet/keras/issues/754 and in particular this point:

> Thorough checking of assumptions made about user-provided constructor arguments throughout the codebase, and raising helpful and clear error messages when some assumptions aren't respected. Ideally no error will ever be raised by Theano, because we will be catching everything on the Keras side. This will make debugging of Keras models much faster and easier.

Moreover this will help when we want to build much more "complex class" such as the Merge.
We can make the merge mode variable immutable (we block the setter function with an exception).
by doing so we can move all the type checks for the layers away from the init leaving it as clean as possible.

EDIT:
An example can be found in this branch for the merge mode:
https://github.com/dbonadiman/keras/commit/14c2fc66b6620cc8496b272c4472ae643ad1192c

**Comment by phreeza** [comment]
:+1: This is a great idea. A nice way to get started would be to ammend a couple of tests that implement this assignment after instantiation, and make them fail when no error is raised.
