### ISSUE TITLE
error happed in example code mnist_mlp.py

### ISSUE THREAD

**Issue by danieljf24** [fchollet/keras#980]
I runned example code mnist_mlp.py, getting following warning and error. I wondering what leads to these error. Thanks in advance.

UserWarning: MRG_RandomStreams Can't determine #streams from size (Shape.0), guessing 60*256
  nstreams = self.n_streams(size)

ValueError: size must remain unchanged, changed from 1280 to -10
Apply node that caused the error: GpuReshape{2}(GpuElemwise{Add{output_types_preference=transfer_type{0}}}[(0, 0)].0, MakeVector.0)
Inputs shapes: [(128, 10), (2,)]
Inputs strides: [(10, 1), (8,)]
Inputs types: [CudaNdarrayType(float32, matrix), TensorType(int64, vector)]
Use the Theano flag 'exception_verbosity=high' for a debugprint of this apply node.

**Comment by fchollet** [comment]
Do you have the latest Keras and Theano (from the Github repos)?

**Comment by danieljf24** [comment]
No, I installed the Keras 1.2 and the Theano 0.7.  I can running successfully with these two on other computer, but failed on my computer.

**Comment by danieljf24** [comment]
I made a mistake, I install both Theano 0.6 and 0.7, and actually run on Theano 0.6, which leads to these error.
