### ISSUE TITLE
ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False), (0, 'x'))) in a first attemp implementing attention model

### ISSUE THREAD

**Issue by chunyangx** [fchollet/keras#981]
Hello, 

The attention model that I tried to implement is as http://arxiv.org/abs/1412.7449

The code for the model was the following:

    self.model = Graph()
    self.model.add_input(name='utterance', input_shape=(uttr1_max_length, uttr1_dict_length)))
    self.model.add_input(name='utterance2', input_shape=(uttr2_max_length, uttr2_dict_length)))
    self.model.add_node(TimeDistributedDense(dim), name='Embed_uttr', input='utterance')
    self.model.add_node(TimeDistributedDense(dim), name='Embed_uttr2', input='utterance2')
    self.model.add_node(LSTM(dim), name='Hidden_uttr', input='Embed_uttr')
    self.model.add_node(LSTM(dim), name='Hidden_uttr2', input='Embed_uttr2')
    # Build attention vector
    self.model.add_node(TimeDistributedDense(dim), name='Above_embedding', input='Embed_uttr')
    self.model.add_node(Dense(dim), name='Above_hidden', input='Hidden_uttr2')
    self.model.add_node(RepeatVector(self.preprocessor.uttr_max_length), name='repeat_above_hidden', input='Above_hidden')
    self.model.add_node(Activation('tanh'), name='intermediate',inputs=['Above_embedding', 'repeat_above_hidden'], merge_mode='sum')
    self.model.add_node(TimeDistributedDense(1), name='inter_att', input='intermediate')
    self.model.add_node(Flatten(), name='flatten_att', input='inter_att')
    self.model.add_node(Activation('softmax'), name='att_vector', input='flatten_att')
    self.model.add_node(Activation('linear'), name='attention', inputs=['Embed_uttr','att_vector'], merge_mode='dot', dot_axes=[[1],[1]])
    # Final prediction
    self.model.add_node(Dense(uttr2_dict_length)), name='merged', inputs=['Hidden_uttr','Hidden_uttr2', 'attention'], merge_mode='concat')
    self.model.add_node(Activation('softmax'), name='activation', input='merged')
    self.model.add_output(name='output', input='activation')
    self.model.compile('rmsprop', {'output':'categorical_crossentropy'})

And I receive the error message: ValueError: ('You cannot drop a non-broadcastable dimension.', ((False, False), (0, 'x'))). Could somebody tell me where is the problem please ?

**Comment by dbonadiman** [comment]
You are a step away from the solution, just update to the latest keras i assume the problem is in the old dot implementation, i fixed it yesterday. You are doing exactly the same as i did. (and i mean EXACTLY ^_^)

Just having fun compiling the model :)

**Comment by chunyangx** [comment]
Yes. That is the issue.
 
Thanks a lot. 

PS: From the few experiences I have with models like LSTM, having some representation near the actual word level in plus de LSTM hidden layer seems to be helpful in general.

**Comment by kaya27** [comment]
hello @chunyangx  @dbonadiman 
I have a question please, can this implementation be adapted to sequence labelling problem?

**Comment by chunyangx** [comment]
Hello, 
This implementation has apparently two issues (i) It doesn't deal with masks (and I just hear from others that this may have some implications) (ii) This implementation is based on Keras 0.3 and this is really an outdated version for now. 
Personally, I haven't looked very closely on Keras for a while. But I don't see a standard attention layer implementation inside Keras. Does anyone have some ideas of the reasons for this choice, please ?
