### ISSUE TITLE
TensowFlow Backend

### ISSUE THREAD

**Issue by felipefariax** [fchollet/keras#985]
Hello!

As some of you may know, the TensorFlow library (http://tensorflow.org) has been released opensource. It's "like" Theano, developed by Google.

I was wondering if it's worth to port Keras backend to use it.

What do you think?

**Comment by EderSantana** [comment]
yes https://twitter.com/fchollet/status/663735623119949824

**Comment by felipefariax** [comment]
Nice to hear that! =]

**Comment by farizrahman4u** [comment]
@EderSantana Does this mean that keras models can run on android in the future? TensorFlow has an android example.
@felipefariax Please reopen the issue
