### ISSUE TITLE
CNMeM is disabled

### ISSUE THREAD

**Issue by danieljf24** [fchollet/keras#987]
I have already installed Keras 2.0 successfully. But, it print "CNMeM is disabled", who can tell me what's meaning of this note.

**Comment by jacobzweig** [comment]
See here: http://deeplearning.net/software/theano/library/config.html

You can change this in the environment variables. I added the following to my .theanorc file and saw significant speed increases during training of a cnn:

[lib]
cnmem=.75 

Beyond .75 I got out of memory errors, but I'd imagine this varies based on your setup.

**Comment by danieljf24** [comment]
Thanks very much, jacobzweig.

**Comment by carlthome** [comment]
@jacobzweig, @danieljf24 so how much faster is the model training with cnmem? Is it worth using?

**Comment by nouiz** [comment]
It is worth using. The speed up depend of many factor, like the shapes and
the model itself. The speed up go from 0 to 2x faster.
