### ISSUE TITLE
io_utils.HDF5Matrix seems broken for three dimensional inputs.

### ISSUE THREAD

**Issue by c0nn3r** [fchollet/keras#991]
Hello, I was just trying to use HDF5Matrix class to load a three dimensional dataset, when I noticed that the shape method wasn't returning the real shape of the dataset. Is the class only intended for 2 dimensional data?

**Comment by EderSantana** [comment]
You may want to write your own "HDF5Tesnor" or use this one from Seya https://github.com/EderSantana/seya/blob/master/seya/data_utils.py#L94-L143
