### ISSUE TITLE
Lambda layer - Documentation inconsistent with code

### ISSUE THREAD

**Issue by farizrahman4u** [fchollet/keras#994]
For both `Lambda` and `LambdaMerge` layer, output_shape should be a function of input shape(s), **without including** samples dim. (or tuple(s), excluding samples dim). The docs says otherwise. So either I have to PR to correct the doc, or change the code. Which one?

**Comment by fchollet** [comment]
Change the code. The *tuple value argument* should excluding the dimension,
the *shape function* should include it.

**Comment by farizrahman4u** [comment]
@fchollet #995
